### ISSUE TITLE
Attribute's Row on the fly modification and after saving giving 404 error [ScreenRecord Added]

### ISSUE THREAD

**Issue by shakib04** [bagisto/bagisto#10002]
**Describe the bug**
I have created a row in existing attribute and modified the row before save. After saving giving 404 error. 

**To Reproduce**
1. Go to Catelogs
2. Click on 'Attributes'
3. Scroll down to 'Add Row'
4. After adding, edit the row
5. Save

**Expected behavior**
It should save properly.

**Screenshots**
Screen-Record Added
[Screencast from 12-7-24 12:37:58 পূর্বাহ্ণ +06.webm](https://github.com/bagisto/bagisto/assets/51458806/525a4414-c640-4f72-9cdb-1a07300f2959)

**Desktop (please complete the following information):**
 - OS: [ubuntu 22.04]
 - Browser Tested [chrome]
 - Bagisto Version [2.1.2]

**Comment by ashishkumar-webkul** [comment]
@shakib04 

Thank You So Much for bringing this issue in light, as per checking the video we were able to find it and hence we are working on it for quickiest fixing. I would really appreciate your patience. 
Thank You,

**Issue Video**


https://github.com/user-attachments/assets/9139b815-1ca6-4957-bd69-8e9942db898a

**Comment by ashishkumar-webkul** [comment]
@shakib04 

Thank you so much for your patience. We really appreciate it.

We are pleased to inform you that the issue has been fixed and a pull request has been created. Everything is now working fine.

PR Link: https://github.com/bagisto/bagisto/pull/10054

For reference, you can check the video.

**Video**

https://github.com/user-attachments/assets/515db9ae-38c5-48ba-a489-78289e109f74
