### ISSUE TITLE
We need to add a note indicating the required image resolution dimensions for uploading the image.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10013]
**Describe the bug**
We need to add a note indicating the required image resolution dimensions for uploading the image.
When I uploaded a random image for the PDF invoice print, it overlapped the address section. This should not happen.

**Steps to Reproduce**

1. Go to Admin -> Configure -> Sales -> Invoice Settings -> Upload Image
2. Add any random image and save.
3. Now Create and order and complete invoice generation step.
4. Go to Admin -> Sales -> Invoice -> view -> Print Invoice -> Check the PDF.
5. We can see that the image is overlapping with Shipping Address.

**Expected behavior**
It should not happen and also there should be a proper note added for the same.

Sample Screenshot -> https://jam.dev/c/4d3e43c3-485c-44d1-ac13-a83a46c535ed
 
**Issue Screenshots**

Currently we can see that there is no note added and hence we can add any random image, which leads to inappropriate display of PDF.

Screenshot [here](https://jam.dev/c/89d7b3e8-af95-4fed-8c9a-1ca658c35dde)

**Sample PDF**

[invoice-16-07-2024.pdf](https://github.com/user-attachments/files/16245307/invoice-16-07-2024.pdf)

**Comment by vinaybadola** [comment]
Hello @ashishkumar-webkul 

I want to do this task and I have a question regarding the image size validation for the logo in the invoice settings. Should the image dimensions be hardcoded to a maximum of 55px height and 45px width, or should the admin have the ability to set these dimensions?

Thank you!
