### ISSUE TITLE
The collapse and expand animation of the side menu in the admin end is appearing with a slight delay.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10019]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The collapse and expand animation of the side menu in the admin end is appearing with a slight delay.

### Preconditions

1. Admin must be logged in.

### Steps to reproduce

1. Go to Admin -> Check the Side Menu.
2. now Collape it and then expend it.
3. You may be able to see that the context is appearing before expending the side menu.

### Expected Result

Colapse and Expend Animation must be smooth.

### Actual Result

Check the video for the issue.

https://github.com/user-attachments/assets/20443928-d216-4b72-9056-cd2c0828a5e9

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, 

I have checked and found that the slidebar is working fine with animation.
