### ISSUE TITLE
Eloquent Repository findOneByField() $columns parameter issue

### ISSUE THREAD

**Issue by eness** [bagisto/bagisto#10027]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.2

### Issue Description

\Webkul\Core\Eloquent\Repository::findOneByField method has an option parameter named $columns which let you to specify the columns that will be included in the query. But the method body has overrided $columns parameter instead of directly passing it down.

```
    public function findOneByField($field, $value = null, $columns = ['*'])
    {
        $model = $this->findByField($field, $value, $columns = ['*']); // <-- issue here

        return $model->first();
    }
```

### Preconditions

master branch of latest Bagisto version.

### Steps to reproduce

1. Create new project with bagisto/master
2. Use findOneByField() method over any repository by specifying $columns to fetch.
3. $columns variable is not handled in method body

### Expected Result

Only specified columns should be queried.

### Actual Result

Provided $columns is not used

**Comment by devansh-webkul** [comment]
@eness,

Thank you for the contribution.
