### ISSUE TITLE
[CMS MODULE] Admin Not Working on Clean Install

### ISSUE THREAD

**Issue by dev-b-l** [bagisto/bagisto#10022]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.2

### Issue Description

Error trying to open the CMS Admin module, datagrid doesn't populate.

### Preconditions

Clean Install:

Platform: Apple M3 Sonoma 14.5 / PHP 8.3.8 / Curl v8.6

### Steps to reproduce

- Download a copy of bagisto v2.2.2
- uncompress go to folder
- [terminal] composer create-project
- [terminal] php artisan bagisto:install
- [terminal] php artisan serve
- [browser] admin login
- [browser] go to /admin/cms

Error: Query #4 cms?pagination[page]=1&...

Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'channels.code' in 'field list' (Connection: mysql, SQL: select count(*) as aggregate from (select `bb_cms_pages`.`id`, `bb_cms_page_translations`.`page_title`, `bb_cms_page_translations`.`url_key`, `bb_cms_page_translations`.`locale`, GROUP_CONCAT(DISTINCT channels.code) as channel from `bb_cms_pages` inner join `bb_cms_page_translations` on `bb_cms_pages`.`id` = `bb_cms_page_translations`.`cms_page_id` and `bb_cms_page_translations`.`locale` = en left join `bb_cms_page_channels` on `bb_cms_pages`.`id` = `bb_cms_page_channels`.`cms_page_id` left join `bb_channels` on `bb_cms_page_channels`.`channel_id` = `bb_channels`.`id` group by `bb_cms_pages`.`id`, `bb_cms_page_translations`.`locale`) as `aggregate_table`)

Message:

LOG.error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'channels.code' in 'field list' (Connection: mysql, SQL: select count(*) as aggregate from (select `bb_cms_pages`.`id`, `bb_cms_page_translations`.`page_title`, `bb_cms_page_translations`.`url_key`, `bb_cms_page_translations`.`locale`, GROUP_CONCAT(DISTINCT channels.code) as channel from `bb_cms_pages` inner join `bb_cms_page_translations` on `bb_cms_pages`.`id` = `bb_cms_page_translations`.`cms_page_id` and `bb_cms_page_translations`.`locale` = en left join `bb_cms_page_channels` on `bb_cms_pages`.`id` = `bb_cms_page_channels`.`cms_page_id` left join `bb_channels` on `bb_cms_page_channels`.`channel_id` = `bb_channels`.`id` group by `bb_cms_pages`.`id`, `bb_cms_page_translations`.`locale`) as `aggregate_table`) {
    "exception": {
        "errorInfo": [
            "42S22",
            1054,
            "Unknown column 'channels.code' in 'field list'"
        ],
        "connectionName": "mysql"
    }
}

### Expected Result

<img width="800" alt="Screenshot 2024-07-17 at 09 53 30" src="https://github.com/user-attachments/assets/46a23b97-4c2b-4e19-a323-5629567868b5">

### Actual Result

<img width="937" alt="Screenshot 2024-07-17 at 10 05 07" src="https://github.com/user-attachments/assets/e787af41-e89a-4aec-b22c-7d41403bca05">

**Comment by ashishkumar-webkul** [comment]
@dev-b-l 

Hello there,

Thank you so much for your query, and we really appreciate your contribution to Bagisto. Upon checking the issue you raised, I found that it is not appearing. Could you please provide a more detailed description of the issue, or share a video for reference? This will help us understand your issue better. For now you can check the video for reference.

**Video**

https://github.com/user-attachments/assets/4f729700-871f-425f-9859-b4d59e2b0022


Thank you.

**Comment by dev-b-l** [comment]
https://github.com/user-attachments/assets/611cdafa-5669-4fa0-8f95-919717058654

**Comment by ashishkumar-webkul** [comment]
@dev-b-l

Upon checking the video, it was found that you have entered the **composer install** command. As a result, your vendor folder is created, but the .env file is not generated.

For a proper installation, you need to run **composer create-project**. Once you run this command, the .env file will be generated.

You can also follow the documentation for the installation.

[Documentation Link](https://devdocs.bagisto.com/2.2/introduction/installation.html#install-using-gui-installer)

Please let us know, if this helps you in your proper installation of Bagisto.

**Comment by dev-b-l** [comment]
using composer create-project is indifferent regarding the issue:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'channels.code' in 'field list' (Connection: mysql, SQL: select count(*) as aggregate from (select `bagistotest_cms_pages`.`id`, `bagistotest_cms_page_translations`.`page_title`, `bagistotest_cms_page_translations`.`url_key`, `bagistotest_cms_page_translations`.`locale`, GROUP_CONCAT(DISTINCT channels.code) as channel from `bagistotest_cms_pages` inner join `bagistotest_cms_page_translations` on `bagistotest_cms_pages`.`id` = `bagistotest_cms_page_translations`.`cms_page_id` and `bagistotest_cms_page_translations`.`locale` = en left join `bagistotest_cms_page_channels` on `bagistotest_cms_pages`.`id` = `bagistotest_cms_page_channels`.`cms_page_id` left join `bagistotest_channels` on `bagistotest_cms_page_channels`.`channel_id` = `bagistotest_channels`.`id` group by `bagistotest_cms_pages`.`id`, `bagistotest_cms_page_translations`.`locale`) as `aggregate_table`)

I installed all previous versions up to 2.1.2 without this issue and is ONLY in the CMS module.

**Comment by ashishkumar-webkul** [comment]
@dev-b-l 

Please allow us some time so that I can discuss the concern with team, so that we can try to help you out in this concern ASAP.
Your Patience really be appreciated.

Thank You.

**Comment by dev-b-l** [comment]
I think i found the issue:

File: packages/Webkul/Admin/src/Datagrids/CMS/CMSPageDataGrid.php

I added to

  $queryBuilder = DB::table('cms_pages')
            ->select(
               ...                
           **'cms_page_channels.channel_id'**
            )
            
 and change
 
             ->addSelect(DB::raw('GROUP_CONCAT(DISTINCT **channel_id**) as channel'))

**Comment by dev-b-l** [comment]
<?php

namespace Webkul\Admin\DataGrids\CMS;

use Illuminate\Support\Facades\DB;
use Webkul\DataGrid\DataGrid;

class CMSPageDataGrid extends DataGrid
{
    /**
     * Prepare query builder.
     *
     * @return \Illuminate\Database\Query\Builder
     */
    public function prepareQueryBuilder()
    {
        $currentLocale = app()->getLocale();

        $queryBuilder = DB::table('cms_pages')
            ->select(
                'cms_pages.id',
                'cms_page_translations.page_title',
                'cms_page_translations.url_key',
                'cms_page_translations.locale',
                'cms_page_channels.channel_id'
            )
            ->addSelect(DB::raw('GROUP_CONCAT(DISTINCT channel_id) as channel'))
            ->join('cms_page_translations', function ($join) use ($currentLocale) {
                $join->on('cms_pages.id', '=', 'cms_page_translations.cms_page_id')
                    ->where('cms_page_translations.locale', '=', $currentLocale);
            })
            ->leftJoin('cms_page_channels', 'cms_pages.id', '=', 'cms_page_channels.cms_page_id')
            ->leftJoin('channels', 'cms_page_channels.channel_id', '=', 'channels.id')
            ->groupBy('cms_pages.id', 'cms_page_translations.locale');

        $this->addFilter('id', 'cms_pages.id');
        $this->addFilter('channel', 'cms_page_channels.channel_id');
        $this->addFilter('locale', 'cms_page_translations.locale');

        return $queryBuilder;
    }

    /**
     * Add columns.
     *
     * @return void
     */
    public function prepareColumns()
    {
        $this->addColumn([
            'index'      => 'id',
            'label'      => trans('admin::app.cms.index.datagrid.id'),
            'type'       => 'integer',
            'filterable' => true,
            'sortable'   => true,
        ]);

        $this->addColumn([
            'index'              => 'channel',
            'label'              => trans('admin::app.cms.index.datagrid.channel'),
            'type'               => 'string',
            'filterable'         => true,
            'filterable_type'    => 'dropdown',
            'filterable_options' => collect(core()->getAllChannels())
                ->map(fn ($channel) => ['label' => $channel->name, 'value' => $channel->id])
                ->values()
                ->toArray(),
            'sortable'   => true,
            'visibility' => false,
        ]);

        $this->addColumn([
            'index'      => 'page_title',
            'label'      => trans('admin::app.cms.index.datagrid.page-title'),
            'type'       => 'string',
            'searchable' => true,
            'filterable' => true,
            'sortable'   => true,
        ]);

        $this->addColumn([
            'index'      => 'url_key',
            'label'      => trans('admin::app.cms.index.datagrid.url-key'),
            'type'       => 'string',
            'searchable' => true,
            'filterable' => true,
            'sortable'   => true,
        ]);
    }

    /**
     * Prepare actions.
     *
     * @return void
     */
    public function prepareActions()
    {
        $this->addAction([
            'icon'   => 'icon-view',
            'title'  => trans('admin::app.cms.index.datagrid.view'),
            'method' => 'GET',
            'index'  => 'url_key',
            'target' => '_blank',
            'url'    => function ($row) {
                return route('shop.cms.page', $row->url_key);
            },
        ]);

        if (bouncer()->hasPermission('cms.edit')) {
            $this->addAction([
                'icon'   => 'icon-edit',
                'title'  => trans('admin::app.cms.index.datagrid.edit'),
                'method' => 'GET',
                'url'    => function ($row) {
                    return route('admin.cms.edit', $row->id);
                },
            ]);
        }

        if (bouncer()->hasPermission('cms.delete')) {
            $this->addAction([
                'icon'   => 'icon-delete',
                'title'  => trans('admin::app.cms.index.datagrid.delete'),
                'method' => 'DELETE',
                'url'    => function ($row) {
                    return route('admin.cms.delete', $row->id);
                },
            ]);
        }
    }

    /**
     * Prepare mass actions.
     *
     * @return void
     */
    public function prepareMassActions()
    {
        if (bouncer()->hasPermission('cms.delete')) {
            $this->addMassAction([
                'title'  => trans('admin::app.cms.index.datagrid.delete'),
                'method' => 'POST',
                'url'    => route('admin.cms.mass_delete'),
            ]);
        }
    }
}

**Comment by CanhHoangN** [comment]
@ashishkumar-webkul @dev-b-l 
I've found the cause. If you set the 'DB_PREFIX' value when installing Bagisto, you'll encounter the above error. The code doesn't automatically add the PREFIX_channels.code.

**Comment by devansh-webkul** [comment]
If there are any raw queries, the raw method will not apply a prefix automatically; developers need to add it manually. If this issue is present in the master branch, we will definitely address it.

**Comment by devansh-webkul** [comment]
@ashishkumar-webkul,

Verify with db prefix installation.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and I have checked the same with DB-Prefix, Now it is working fine. check the video for reference.

**Video**

https://github.com/user-attachments/assets/cec2edb2-b09e-48f3-945c-47743eaf2e7f
