### ISSUE TITLE
Apply coupon button is not responsive if we enter any random data in coupon code field, it should throw an error message "Invalid coupon code".

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1004]
- Framework version: 0.1.6

------------------------------------------

![Screenshot from 2019-06-11 10-45-02](https://user-images.githubusercontent.com/45203177/59245730-8d1ba580-8c37-11e9-8cbe-694d29239e9f.png)

**Comment by stefano73it** [comment]
The boolean false returned by applyCouponAbleRule($code) is not a valid return value.

**Comment by prashant-webkul** [comment]
@stefano73it The Discount module is not yet released and we are in mid of the process to comply features that need to be deployed in next release.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

----------------------------------------
Fixed, now showing "Cannot apply coupon"
