### ISSUE TITLE
404 page resonsiveness issue

### ISSUE THREAD

**Issue by ajeetkesherwani** [bagisto/bagisto#10041]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.2.1

### Issue Description

Bagisto Demo Link-https://demo.bagisto.com/bagisto-common/arctic-frost-winter-accessories-bundle-j
There are some padding issue between 404 and Page not found senetence. ( Responsivess issue ) 

### Preconditions

No any condition , check your 404 error page.

### Steps to reproduce

One any error page (404 error page).

### Expected Result

Make this fully responsive.

### Actual Result

404 page responsive

### Screenshots

![Screenshot 2024-07-24 224101](https://github.com/user-attachments/assets/0c13bf67-73c0-46df-a40b-03395c0fafd7)
![Screenshot 2024-07-24 224118](https://github.com/user-attachments/assets/51f5d25b-8d7b-4b52-a3a8-46722efefa82)

**Comment by ashishkumar-webkul** [comment]
@ajeetkesherwani

Hello there,

Thank you so much for your contribution towards Bagisto.

Upon checking the issue, it was found that the URL attached from your end is incorrect, which is causing the issue.

Issue URL: https://demo.bagisto.com/bagisto-common/arctic-frost-winter-accessories-bundle-j
Correct URL: https://demo.bagisto.com/bagisto-115-113-191-18/arctic-frost-winter-accessories-bundle

I have checked and found it working. I am attaching a video for your reference. Please have a look at it. If you are still facing this issue, I would really appreciate it if you could share the steps to reproduce the issue.

Thank you.

**Video**

https://github.com/user-attachments/assets/9949d999-b55d-404d-8ebe-2f6c695b8dab

**Comment by ajeetkesherwani** [comment]
You once again check the issue title on Geet. I raised an issue for
the responsiveness of the 404 error page. Your error page is not
responsive.
