### ISSUE TITLE
session lose when checkout success

### ISSUE THREAD

**Issue by chakson** [bagisto/bagisto#10047]
**Describe the bug**
Session lose when checkout success.
When I place an order and pay successfully, the page jumps to /checkout/cart .
I have located the file at: packages\Webkul\Shop\src\Http\Controllers\OnepageController.php on line 77.
Printing session('order_id') shows null.

**version: 2.2.2**

**To Reproduce**
1. Go to 'checkout page'
2. Click on 'submit'
3. Redirect to 'payment page'
4. Pay successful

**Comment by devansh-webkul** [comment]
We are not able to reproduce this on 2.2.2 as well as master version. Checkout seems to be working fine.

**Comment by devansh-webkul** [comment]
The `order_id` session is designed as a one-time flash session to support the success callback. Once the session ID is retrieved, the session is intentionally destroyed. This means that the `order_id` cannot be retrieved again after the order has been placed.

**Comment by chakson** [comment]
> The `order_id` session is designed as a one-time flash session to support the success callback. Once the session ID is retrieved, the session is intentionally destroyed. This means that the `order_id` cannot be retrieved again after the order has been placed.

What could be the cause of this problem? Or what configuration file do I need to provide to solve this problem?

**Comment by devansh-webkul** [comment]
Have you done any customization or have you able to reproduce it in our demo? Let us know.

**Comment by chakson** [comment]
It is difficult to reproduce. Can session('order_id') be changed to another acquisition method?

**Comment by chakson** [comment]
> Have you done any customization or have you able to reproduce it in our demo? Let us know.

It is difficult to reproduce. Can session('order_id') be changed to another acquisition method?

**Comment by devansh-webkul** [comment]
You can customize or override as per your need because i guess you are directly calling the success method endpoint from somewhere.
