### ISSUE TITLE
Category Tree in Admin - show inactive categories

### ISSUE THREAD

**Issue by giazach** [bagisto/bagisto#10074]
**Describe the bug**
In Admin Product (edit) there is the Category tree. The tree shows only the active/visible in menu categories.  

**To Reproduce**
1. Go to Admin->Catalog->Products->Create/Edit a Product

**Expected behavior**
Also showing the inactive categories in tree was expected

**Additional context**
I managed to reveal the inactive categories in tree by changing in packages/Webkul/Admin/src/Http/Controllers/Catalog/CategoryController.php the "getVisibleCategoryTree" to "getCategoryTree" method.

```
public function tree(): JsonResource
    {
        $categories = $this->categoryRepository->getVisibleCategoryTree(core()->getRequestedChannel()->root_category_id);

        return CategoryTreeResource::collection($categories);
    }
```
   to

```
   public function tree(): JsonResource
    {
        $categories = $this->categoryRepository->getCategoryTree(core()->getRequestedChannel()->root_category_id);

        return CategoryTreeResource::collection($categories);
    }

**Comment by amit-webkul** [comment]
Hello @giazach  ,

Thank you for your contributions to Bagisto. I appreciate your efforts.

Regarding your concern, I have reviewed the issue and found that we are only listing active categories using the tree method. Inactive categories are not included in the tree for any section.
