### ISSUE TITLE
i install bagisto from softaculous and it working fine  but admin panel does not working  why ?

### ISSUE THREAD

**Issue by nadeemabualarayes** [bagisto/bagisto#10079]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.2

### Issue Description

i install bagisto from softaculous
and it working fine 
but admin panel does not working 
why ?

### Preconditions

i install bagisto from softaculous
and it working fine 
but admin panel does not working 
why ?

### Steps to reproduce

i install bagisto from softaculous
and it working fine 
but admin panel does not working 
why ?

### Expected Result

i install bagisto from softaculous
and it working fine 
but admin panel does not working 
why ?

### Actual Result

i install bagisto from softaculous
and it working fine 
but admin panel does not working 
why ?

### Screenshots

![image](https://github.com/user-attachments/assets/b9972d02-8491-443b-9ca2-187747dc53ca)
![image](https://github.com/user-attachments/assets/22dda278-9470-414d-94c5-20f230d313fb)

**Comment by amit-webkul** [comment]
Hello @nadeemabualarayes ,

This issue needs to be handled at the softaculous end. From here, everything seems to be fine.
