### ISSUE TITLE
Linux - Apache2 - Class "Webkul\Product\DataTypes\CartItemValidationResult" not found

### ISSUE THREAD

**Issue by Diverti** [bagisto/bagisto#10075]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.2

### Issue Description

When i try to add an item into the cart, i got this exception:
Class "Webkul\Product\DataTypes\CartItemValidationResult" not found

### Preconditions

Clean install, with product.

### Steps to reproduce

1. Clean install
2. Create a product
3. Go to the frontend page of the product and click 'Add to Cart'

### Expected Result

No exception

### Actual Result

I got exception with a notification: Class "Webkul\Product\DataTypes\CartItemValidationResult" not found

### Screenshots

![image](https://github.com/user-attachments/assets/5e647547-9586-4864-ac65-1abcd29e4d49)

### Additional context

I found out the problem source is that the Webkul/Product/src/Datatypes folder should spelled DataTypes with capital T. 
The linux system doesn't like that

**Comment by devansh-webkul** [comment]
Spelling is correct on yur mentioned version,
https://github.com/bagisto/bagisto/tree/v2.2.2/packages/Webkul/Product/src/DataTypes
