### ISSUE TITLE
Missing generic event in product view for new product types in default shop theme

### ISSUE THREAD

**Issue by Pizdiec** [bagisto/bagisto#10086]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.2

### Issue Description

I was trying to create new product type and add custom field for customer to fill when ordering product. However, I couldn't trigger view insertion event because code on "Webkul\Shop\src\Resources\views\products\view.blade.php" is written in a static way.
code: 
`                                {!! view_render_event('bagisto.shop.products.short_description.after', ['product' => $product]) !!}

                                @include('shop::products.view.types.configurable')

                                @include('shop::products.view.types.grouped')

                                @include('shop::products.view.types.bundle')

                                @include('shop::products.view.types.downloadable')`
I noticed that on "Webkul\Admin\src\Resources\views\catalog\products\edit.blade.php" it is written in dynamic way.
code:
`                        
                        @includeIf('admin::catalog.products.edit.types.' . $product->type)`.
Shop view should be written in the same way as admin view. If I were to develop general package for users to use I would need to override their theme view for custom view event to appear, which isn't really practical. People developing themes and using default theme as a base for theirs wouldn't be able to use my package out of the box.

### Preconditions

Installed bagisto 2.2.2 version and created my own product type package and tried adding event listener into service provider boot method:`        Event::listen('shop::products.view.types.my-custom-type', function ($viewRenderEventManager) {...`

### Steps to reproduce

1. Set up bagisto 2.2.2 version
2. Create product type package using package manager
3. In service provider boot method add event listener for customer product view with dynamic product type
4. Notice that event is not triggered and html is not inserted.

### Expected Result

My custom product type view should be inserted when ordering product.

### Actual Result

Nothing changes, there isn't a provided way to insert dynamic content to product view.

**Comment by amit-webkul** [comment]
Hello @Pizdiec ,
As per your concern regarding the product events, 

If you would like to add custom elements to the product, you can utilize the `view_render_events`. This approach allows you to append additional features to the product display.

**Comment by Pizdiec** [comment]
Yes, there is an event. **Thanks** for pointing it out I overlooked it **mb. It solves my concern.** 

Single @includeIf statement with dynamic typing would solve it too and would match admin panel code. Just pointing it out for more cleaner/consistent solution.
