### ISSUE TITLE
Getting  ? Symbol rather than ₹ (Indian ruppee currency in invoice)

### ISSUE THREAD

**Issue by Abhijittribhuvan** [bagisto/bagisto#10082]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2

### Issue Description

I am using latest bagisto version, i use indian currency for my ecommerce site, when i tried to print invoice or download invoice then rather than ₹ (Indian currency) i am getting ? (Question mark symbol)

### Preconditions

Bagisto - version 2.2

### Steps to reproduce

 Go to invoice, download or print in a admin panel

### Expected Result

Should visible ₹ INR symbol

### Actual Result

Visibling ? (Question mark) symbol rather than ₹ (INR) symbol

### Screenshots

[invoice-16-08-2024-2.pdf](https://github.com/user-attachments/files/16636253/invoice-16-08-2024-2.pdf)

**Comment by amit-webkul** [comment]
Hello @Abhijittribhuvan ,

Thanks for your contribution; we will fix this issue ASAP. and will update you accordingly.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and working fine.

![Screenshot from 2024-09-16 16-35-36](https://github.com/user-attachments/assets/580b0ba3-0611-4640-b15f-b9378fa963e2)
