### ISSUE TITLE
not work after installation if password contains character  `#`

### ISSUE THREAD

**Issue by micross** [bagisto/bagisto#10080]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

When installing with `php artisan bagisto:install`, if database password contains `#` and is not escaped when written to the `.env` file.  it dosn't work after installation.

### Preconditions

The database password contains special character `#`

### Steps to reproduce

install with `php artisan bagisto:install`, on database password step,  input like `my#password`

### Expected Result

on `.env` file, `DB_PASSWORD="my#password"`

### Actual Result

on `.env` file, `DB_PASSWORD=my#password`

**Comment by tusharnain4578** [comment]
Please assign this to me.

**Comment by tusharnain4578** [comment]
@devansh-webkul Please review the PR.
