### ISSUE TITLE
Add the possibility to register directly when checking out

### ISSUE THREAD

**Issue by ag84ark** [bagisto/bagisto#10083]
### Is your feature request related to a problem? Please describe.

Now when someone new order on your site, most of the time they won't create a user prior to ordering, they just go to checkout which makes them checkout as guest.
I don't think that everybody just doesn't want to register, they just don't want to go throw the extra hurdle

### Describe the solution you'd like

I think that by just adding a password field ( 2 in case of confirm ) that it's not required with some text like "create your account by adding a password" or something like this that they understand the intent could increase the registered users on a website.

Thank you for your product once again.

**Comment by devansh-webkul** [comment]
This is not in our roadmap. You can customize this in your own project.
