### ISSUE TITLE
In the condition of the cart rule and catalog rule section, float value is not accepted for weight, height, etc.

### ISSUE THREAD

**Issue by harshit-webkul** [bagisto/bagisto#10096]
**Bagisto version: v2.2.2:**

**Describe the bug:**

   In the condition of the cart rule and catalog rule section, float value is not accepted for weight, height, etc.

**To Reproduce**

1. Go to the admin dashboard
2. Click on the Marketing section ->> Catalog and Cart rule section.
3. apply the condition for weight, height, etc.
4. See error.

**Expected Result:**

Float value should be accepted for these conditions.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

![core issue](https://github.com/user-attachments/assets/7788719f-3191-4004-9c2d-da7e35a71d80)

**Comment by ashishkumar-webkul** [comment]
Checked and found that the float values are being accepted now. 

Screenshot -> https://prnt.sc/P4dRwXHvEhNm
