### ISSUE TITLE
SVG file is not saved

### ISSUE THREAD

**Issue by helgvor-stoll** [bagisto/bagisto#10095]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.2

### Issue Description

When uploading a SVG file/image, we can see it in the field (example: product description as below) but when trying to save, it doesn't work (the file is not save on the disk)
![image](https://github.com/user-attachments/assets/6a7250d4-d61a-4131-ade6-319750388fd5)

### Preconditions

Version tested: 2.2.2

### Steps to reproduce

1. Upload a svg picture in the product description for example
2. Click on '.Save product'
3. See error: the file is not saved

### Expected Result

When uploading a svg image, we should be able to save it and recover it in the product description (for example). It works fine on the Unopim application (the same framework as Bagisto)

### Actual Result

The file is not saved actually

### Screenshots

![image](https://github.com/user-attachments/assets/dc650e3e-9527-41bf-849b-646887b5e42f)

**Comment by amit-webkul** [comment]
@helgvor-stoll 

Thanks for your contribution in bagisto I appreaciate your efforts.

As per your concern, I have checked to reproduce the issue, and it does not appear in the stable branch version 2.2. I have recorded a video for your reference.

Please take a look at the [recorded video](https://webkul.chatwhizz.com/share/view-recording/66d844a38e63b50c7259e0d9)

**Comment by helgvor-stoll** [comment]
@amit-webkul Hi Amit, thank you for your feedback. I uploaded the last source code via git and it works fine. I think I used a bad version but now I work on the good one
Thank you a lot for your video.
