### ISSUE TITLE
If shipping method is selected in cart attribute conditions then it should show all shipping methods.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1009]
- Framework Version: 0.1.6

-------------------------------------

![Screenshot from 2019-06-11 13-07-19](https://user-images.githubusercontent.com/45203177/59252925-c0b3fb00-8c4a-11e9-9f52-b64cac8fc489.png)

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
