### ISSUE TITLE
If payment method is selected in cart attribute conditions then it should show all payment methods.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1010]
- Framework Version: 0.1.6

-------------------------------------------

![Screenshot from 2019-06-11 13-19-42](https://user-images.githubusercontent.com/45203177/59253764-89464e00-8c4c-11e9-99b2-eea60f26b11b.png)

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
