### ISSUE TITLE
Categories not showing

### ISSUE THREAD

**Issue by Maaz0313** [bagisto/bagisto#10119]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.2

### Issue Description

As you can see in the image below, the Categories section is empty. Although I have created a category.

![image](https://github.com/user-attachments/assets/1799e44f-86e9-46be-8e09-1eab7593ff00)

### Preconditions

    Apache/2.4.59 (Win64) OpenSSL/3.0.13 PHP/8.3.8
    Database client version: libmysql - mysqlnd 8.3.8
    PHP extension: mysqli Documentation curl Documentation mbstring Documentation
    PHP version: 8.3.8

### Steps to reproduce

1. After running php artisan bagisto:install, add a category.
2. Then go to products page and click Add a Product.
3. You will see that the category you added is not listed in the Categories section.

### Expected Result

It should show all added categories.

### Actual Result

Not showing any category.

**Comment by amit-webkul** [comment]
Hello @Maaz0313 ,

As per your query, I have checked in our system, and there are no issues in the category section. You need to check once inside the created category to enable the feature visible in the menu. After that, your menu will be visible inside the product section.

Kindly use bagisto forum for queries
https://forums.bagisto.com/

**Comment by Maaz0313** [comment]
I also do that but still categories not displaying

**Comment by deadrohan** [comment]
I am facing same issue 😥

**Comment by zalito12** [comment]
If you are using the seed categories  and creating new ones it will  have a strange behaviour because of missing  translations, I guess.
Delete all the seed categories but root  and create yours
