### ISSUE TITLE
Admin Credentials Prompts Missing During Bagisto Installation via Artisan Command

### ISSUE THREAD

**Issue by Pizdiec** [bagisto/bagisto#10147]
During the installation process of Bagisto via the php artisan bagisto:install command, the prompts for entering admin credentials (admin name, email, and password) are missing. The labels and text fields that should appear for these inputs are not shown after the optimize:clear step is executed. The installation seems to be stuck, as no input is visibly requested. However, if the expected inputs are entered manually (without visible prompts), the installation continues successfully.

**To Reproduce**
1. Run the command php artisan bagisto:install in the terminal.
2. Progress through the initial steps until the optimize:clear step.
3. After the optimize:clear command runs, the terminal no longer displays prompts for admin credentials (name, email, password).
4. The installation appears to hang, but manually entering the expected inputs (e.g., admin name, email, and password) allows it to proceed.

**Expected behavior**
The installation process should display prompts for admin credentials (name, email, password) after the optimize:clear step, allowing the user to input them visibly and without guessing.

**Screenshots**
![image](https://github.com/user-attachments/assets/a798c96b-5ab2-4d89-a265-03715c787aea)
![image](https://github.com/user-attachments/assets/b2ac0cb1-6c1f-40ba-a20c-5449899317ce)

**Desktop:**
 - OS: Windows 10 Pro N
 - Bagisto version 2.2.3
 - Composer version 2.7.9

**Additional context**
The issue seems to stem from the php artisan optimize:clear command, which might be clearing cached data and affecting the prompt display. Despite no visible prompts, the installation does not actually freeze; manually entering the expected admin credentials allows the installation to continue. However, this behavior is confusing and appears to halt progress.

**Suggested Solution**
To avoid this issue, consider moving the php artisan optimize:clear command to the last step of the installation process. This way, all prompts, including those for admin credentials, can be displayed correctly before any cache clearing occurs. By running the optimize:clear at the very end, it would prevent any unintended clearing of cached views or data that might interfere with prompt visibility during the installation process.

**Comment by devansh-webkul** [comment]
I am not able to reproduce this,

![image](https://github.com/user-attachments/assets/4040a485-208c-4e89-b853-cfbe8d9e1000)

**Comment by Pizdiec** [comment]
I tested this on both PowerShell and CMD, so it could be related to the environment. Another key observation is that the issue seems to occur when using:
```
use function Laravel\Prompts\select;
use function Laravel\Prompts\text;
```
For example, this code causes the issue:
```
        $adminName = text(
            label: 'Enter the name of the admin user',
            default: 'Example',
            required: true
        );
```
However, traditional prompting like this works perfectly:
```
$adminName = $this->ask('Enter the name of the admin user', 'Example');
```
Additionally, if I move this block of code:
```
        $this->warn('Step: Clearing cached bootstrap files...');
        $this->call('optimize:clear');
```
to before the database prompts, it also hides the prompts in the final results.

**Comment by devansh-webkul** [comment]
Got it, you are using windows this might be creating issues in window. We will fix this, thanks for reporting this.

**Comment by Minhazul-Islam18** [comment]
![image](https://github.com/user-attachments/assets/bb56baed-f47c-4e20-a4a5-4ce99bde574a)

I'm facing same issue in Laragon+Windows machine.
@devansh-webkul  Any Suggestion??
