### ISSUE TITLE
New,Featured,All Product not show

### ISSUE THREAD

**Issue by KharisG1234T** [bagisto/bagisto#10157]
when I want to see new, featured, and all products the page doesn't display the results. It just refreshes the page and returns to the front page.

how to solve it?

**Comment by devansh-webkul** [comment]
Thank you for reaching out. It looks like your request is not an issue report. For discussions, questions, or general support, we encourage you to use the [Bagisto Forum](https://forums.bagisto.com/). The forum is the best place for such queries, and you'll be able to connect with other community members and get the help you need.

Please reserve the GitHub issue tracker for reporting bugs and issues with the codebase. This helps us keep the issue tracker focused and ensures that problems are addressed promptly.

Thank you for your understanding!
