### ISSUE TITLE
Adjust Paginator Number of Elements.

### ISSUE THREAD

**Issue by CarlJKashnier** [bagisto/bagisto#1015]
![image](https://user-images.githubusercontent.com/13282866/59282945-b9372680-8c37-11e9-9171-9db150baba00.png)

It over flows on mobile causing page side scrolling and a hidden page 2. Can this be set lower?

**Comment by rahulshukla-webkul** [comment]
Hi @CarlJKashnier 

Thanks for notifying us. We will check & update it.

**Comment by rahulshukla-webkul** [comment]
Hi @CarlJKashnier 

We have fixed it. Thanks.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

---------------------------------------------
Fixed
![Uploading Screenshot from 2019-07-30 16-18-03.png…]()
