### ISSUE TITLE
In Home Page Product Crousal, View All Button is redirect to Home Page.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10161]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

In Home Page Product Crousal, View All Button is redirect to Home Page.

### Preconditions

1. Admin must be logged in.
2. There must be some products added on shop.

### Steps to reproduce

1. Go to Shop Front -> Click On product Crousal View All Button.
2. It will redirect to home page.

### Expected Result

It should show all new products, Featured Product or all product according to Crousal Working.

### Actual Result

Please check the video for the same.

**Video**

https://github.com/user-attachments/assets/1ec8ebf4-872d-4ab1-9d6e-39816ac5adac

**Comment by ashishkumar-webkul** [comment]
Checked and found that the view all button issue has been fixed and working fine, please check  the  video for reference.

**Video**

https://github.com/user-attachments/assets/eda28ee4-c822-4054-9180-b341cc73c00c

**Comment by aneeshideaux** [comment]
In after upgrade from v2.2.2  to v2.2.3 i also getting same issue
