### ISSUE TITLE
Censoring product reviewer name

### ISSUE THREAD

**Issue by aghaeian** [bagisto/bagisto#10168]
In product page when a user write his review his name is showing fully and for privacy most censor name characters like A**** G**** or user can select name view type.

**Comment by ashishkumar-webkul** [comment]
@aghaeian 

I have checked and confirmed that the setting has been added to the configurations, and it is now working fine. Please refer to the attached screenshot for reference. You can also review the PR for further details.

I hope this helps with your concern. We truly appreciate your efforts and attention towards Bagisto.

**Screenshot**

https://prnt.sc/U39pb04P2g99
https://prnt.sc/yoyfCa9cTJdJ
https://prnt.sc/ClaFdiG7CW2F

**Comment by ashishkumar-webkul** [comment]
I have reviewed the PR again and in Network Review -> There also we are able to see the issue has been fixed.

**Video**

https://github.com/user-attachments/assets/56dcf9bf-9071-480f-a4d8-6d7887a10b2f
