### ISSUE TITLE
Getting 400 Bad Request error on console in checkout page when added with Bundle Product.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10167]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

Getting 400 Bad Request error on console in checkout page when added with Bundle Product.

### Preconditions

1. Atleast 1 Bundle Product must be created.

### Steps to reproduce

1. Go to Shop -> Add Bundle Product to Cart -> Continue to checkout.
2. Check Console -> We can see 400 Bad Request Error in checkout.

### Expected Result

There should be no error in  the checkout page.

### Actual Result

Please check th e video for reference.

*Video**

https://github.com/user-attachments/assets/24d79bf0-dbc2-4f0e-8a0f-7d0c81ea4ff0

**Comment by suraj-webkul** [comment]
Hello, @ashishkumar-webkul sir

Checked with fresh installation this issue is not appearing , may be this is appearing due to to PayPal SDK account, please re-install and check or provide proper steps in detail so that we can replicate the issue.
