### ISSUE TITLE
 Meta Title is Being Used as URL Instead of Slug

### ISSUE THREAD

**Issue by sudeep2003** [bagisto/bagisto#10171]
In my Bagisto setup, the meta title is being used to generate URLs, but it should be the slug generating the URLs for SEO-friendly links. The meta title should only be used for SEO purposes in the page's `<title>` tag, not for URL generation.

Please provide assistance on how to resolve this issue or confirm if this is a bug.

Look at the provided [screenshot](https://github.com/sudeep2003/screenshot/blob/main/abcd/Screenshot%20(542).png).
![Screenshot (542)](https://github.com/user-attachments/assets/3dbe4cc2-0ad7-4fae-b9c3-c054e5fae2ec)

**Comment by ashishkumar-webkul** [comment]
@sudeep2003 

Thank you so much for your query. Can you please help us where exactly you are facing this, Can you please elaborate in which section you are getting this.
This will help us to understand the concern more. 

Thanks.

**Comment by sudeep2003** [comment]
https://github.com/user-attachments/assets/76abce94-b33a-4b5b-b818-a58d71a3162d

In this video, we can see that both the slug and meta title are working correctly in terms of functionality. However, in the admin panel's **`SEO details section`**, when attempting to preview, the preview URL shows as `baseUrl/meta-title`. It should actually display `baseUrl/slug`. This issue occurs when creating both products and categories.

**Comment by suraj-webkul** [comment]
Hello, @sudeep2003,

This is a preview of how the SEO metadata will appear in search engine results. Please note, however, that it does not represent the actual SEO functionality. The SEO features are working correctly in the actual workflow. Additionally, some issues have been identified and resolved with this [pr](https://github.com/bagisto/bagisto/pull/10186).
