### ISSUE TITLE
while installing admin password validation issue.

### ISSUE THREAD

**Issue by abusalameh** [bagisto/bagisto#10179]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.2

### Issue Description

When I installed the Bagisto on my machine, I set a password of 3 characters as an admin password.
and when I tried to login to admin panel, I got validation for the password which requests the password to be minimum of 6 characters.

I think it's better to remove the validation on login, because it doesn't make sense to validate an entered password for login, on creating a user it makes sense to have such validation rule.

### Preconditions

--

### Steps to reproduce

1. Install new App
2. Set a password of 3 characters length.
3. Navigate to admin login
4. Validation for password input requires 6 characters length.

### Expected Result

Password validation shouldn't be required at login.

### Actual Result

validation is set on password input field.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the CLI installation issue has been fixed, now validation is appearing on the CLI Installation for minimum 6 words for password.
Please check the screenshot for reference.

**Screenshot**

![Screenshot from 2024-10-21 13-17-06](https://github.com/user-attachments/assets/be8b7b59-a5ca-44b0-a740-5b5b4ccca036)
