### ISSUE TITLE
Catalog Rule -> Add Conditons -> One of the details is having translation missing.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10191]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

Catalog Rule -> Add Conditons -> One of the details is having translation missing.

### Preconditions

Admin must be logged in.

### Steps to reproduce

1. Go to Admin -> Promotions -> Catalog Rule -> Create
2. Add Condition -> check the dropdown.

### Expected Result

Translation must be clear and proper.

### Actual Result

Please check the screenshot below.

![Screenshot from 2024-10-17 15-12-36](https://github.com/user-attachments/assets/6ab01e21-570a-4267-9e13-a2a4265601d0)

**Comment by suraj-webkul** [comment]
Hello, @ashishkumar-webkul Sir

Checked, this issue is not appearing, please re-install and check or provide proper steps in detail so that we can replicate the issue

**Comment by ashishkumar-webkul** [comment]
Checked after the fresh installation and found that the issue is not appearing.

![Screenshot from 2024-10-22 08-55-12](https://github.com/user-attachments/assets/55fe83cf-abc4-4906-a722-5a065bc54ade)
![Screenshot from 2024-10-22 08-55-14](https://github.com/user-attachments/assets/fa781010-1c37-4578-92ae-2206b30c4380)
