### ISSUE TITLE
Unassigned Attributes and Right Side Column Not Displaying After Moving Groups to Main Column in Attribute Families

### ISSUE THREAD

**Issue by rohitpal-webkul** [bagisto/bagisto#10193]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.2.3

### Issue Description

After moving all groups from the Right Side Column to the Main Column and saving, the Right Side Column and Unassigned Attributes do not display when reopened.

### Preconditions

v2.2.3 

### Steps to reproduce

1. Open the interface.
2. Move all groups from the Right Side Column to the Main Column.
3. Save the changes.
4. Close and reopen the interface.

### Expected Result

The Right Side Column should display as blank, including Unassigned Attributes.

### Actual Result

The Right Side Column not visible, and Unassigned Attributes are empty.

### Screenshots

![Screenshot from 2024-10-18 10-06-27](https://github.com/user-attachments/assets/83ec5cd7-2e21-44d1-9fa2-ba78ee0917ae)

### Additional context

https://webkul.chatwhizz.com/share/view-recording/6711e63e67225a69d1a7e248

**Comment by ashishkumar-webkul** [comment]
Checked and found that the issue has been fixed and now working fine. Please check the video for reference.

**Video**


https://github.com/user-attachments/assets/1fe1e6a7-f631-46bc-985e-fc738a0f6b05
