### ISSUE TITLE
Getting Console Error when we add symbols On Search Bar on Shop Front.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10217]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

Getting Console Error when we add symbols On Search Bar on Shop Front.

### Preconditions

1. Bagisto must be installed.

### Steps to reproduce

1. Go to Shop -> Search Bar.
2. Search Product with Symbols

### Expected Result

There should be no error.

### Actual Result

Please check the video.

**Video**

https://github.com/user-attachments/assets/cf263212-1811-4caf-9557-73e2d28941fe

**Comment by Asyassin10** [comment]
To fix this, I implemented the following solution in the Blade template to escape the title using the addslashes function. This ensures that special characters are handled correctly in the search query: 
`<h1 class="text-2xl font-medium max-sm:text-base" v-text="`{{ addslashes($title) }}`" ></h1> `
This change can be made in the file located at `packages/Webkul/Shop/src/Resources/views/search/index.blade.php.`

After making this adjustment, the page now correctly handles search queries with special characters without throwing errors, and products are displayed as expected.

**Comment by suraj-webkul** [comment]
Thank you for your attention.

Using `addslashes` will work with Vue string interpolation. Additionally, the purpose of using `v-text` is indeed to prevent XSS (Cross-Site Scripting) vulnerabilities by safely rendering text.

The remaining issues are being addressed by this [PR](https://github.com/suraj-webkul/bagisto/commit/bd78711538a155f35debda5e05fedcc8e4608a72).

Thanks again!

**Comment by ashishkumar-webkul** [comment]
Checked and found that the issue has been fixed. Please check the video for reference.

**Video**


https://github.com/user-attachments/assets/6cef1871-bdba-46a8-ac27-eeea20a48798

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and working fine. Please check the video for reference.

**Video**


https://github.com/user-attachments/assets/801c907a-da61-4a4f-b7e6-1f49355bc7e6

**Comment by ashishkumar-webkul** [comment]
Checked and Found after the minor changed the issue has been fixed and working fine, Please check the video for reference.

**Video**

https://github.com/user-attachments/assets/b7a0a9ee-7f1e-4c05-8dfa-2055bcbf0c5b

**Comment by ashishkumar-webkul** [comment]
Checked and Found it working fine now. Please check the  video for the same.

**Video**

https://github.com/user-attachments/assets/bdf400c4-1628-4ac5-b869-ec268e12d376
