### ISSUE TITLE
Add support for Multiselect field type in system configuration

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#10248]
### Is your feature request related to a problem? Please describe.

The current system configuration options in Bagisto are limited to basic field types such as text, textarea, number, select and boolean. This restriction makes it challenging to provide users with the flexibility they need to select multiple options for various settings. For instance, when configuring payment methods, user roles, or feature toggles, there is often a requirement to allow for multiple selections, which is not possible currently.

### Describe the solution you'd like

I would like to propose the addition of a `multiselect` field type for configuration settings in Bagisto. This new field type should allow administrators to select multiple options from a dynamically generated list. The `multiselect` field should have a user-friendly interface and function similarly to the existing select field but support multiple selections.

### Additional context

![image](https://github.com/user-attachments/assets/76171353-0f74-4d01-b28b-6892f1af292c)

**Comment by devansh-webkul** [comment]
Use CTRL + click.

**Comment by ghermans** [comment]
> Use CTRL + click.

Did you test it before answering?
In my case it only accepts one value not 2
Check video for reference
https://github.com/user-attachments/assets/e16db42a-bd53-4d02-9e69-ba94793f1529

**Comment by devansh-webkul** [comment]
Hello @ghermans,

Here are the steps, i tested on the dashboard page,

```blade
<x-admin::form.control-group.control
        type="multiselect"
        name="swatch_type"
>
        @foreach (['dropdown', 'color', 'image', 'text'] as $type)
            <option value="{{ $type }}">
                @lang('admin::app.catalog.attributes.create.option.' . $type)
            </option>
        @endforeach
</x-admin::form.control-group.control>
```
Then you can check on the page,

https://github.com/user-attachments/assets/78e43691-6e1c-41b1-9386-e32f92392d49

If you need any more information, feel free to ask me. I will help you :innocent: 

Thanks!

**Comment by ghermans** [comment]
@devansh-webkul please try the following 

**config/system.php**
```php
<?php

return [
    [
        'key'    => 'sales.carriers.myparcel',
        'name'   => 'myparcel::app.myparcel',
        'info'   => 'myparcel::app.admin.system.info',
        'sort'   => 3,
        'fields' => [
            [
                'name'          => 'apiKey',
                'title'         => 'myparcel::app.admin.system.api_key',
                'info'          => 'myparcel::app.admin.system.api_key_info',
                'type'          => 'password',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'active',
                'title'         => 'myparcel::app.admin.system.status',
                'type'          => 'boolean',
                'channel_based' => true,
                'locale_based'  => false,
            ], [
                'name'          => 'something',
                'title'         => 'Testing',
                'type'          => 'multiselect',
                'options' => [
                    [
                        'title' => 'option_1',
                        'value' => 'value_1',
                    ], [
                        'title' => 'option_2',
                        'value' => 'vallue_2',
                    ],[
                        'title' => 'option_3',
                        'value' => 'vallue_3',
                    ],
                    
                ],
                'depends'       => 'active:1',
                'channel_based' => true,
                'locale_based'  => false,
            ]
        ],
    ],
];
```

i'm unable to select more then one option

https://github.com/user-attachments/assets/3dc40bd6-f32f-480e-a719-cb8cbf54a946

**Comment by devansh-webkul** [comment]
As from the video its look like there may be a bug.

**Comment by devansh-webkul** [comment]
@amit-webkul,

Please look into this.

**Comment by ashishkumar-webkul** [comment]
@ghermans 

We have checked and verified the details and now the multiselect issue has been fixed.

**Video**

https://github.com/user-attachments/assets/96d8cf38-5473-4e74-bdee-b2ed764e6e2e
