### ISSUE TITLE
ACL: A custom role assigned without dashboard access still logs in with the dashboard by default.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10240]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

ACL: A custom role assigned without dashboard access still logs in with the dashboard by default.

### Preconditions

1. Admin must be logged in.

### Steps to reproduce

1. Go to Admin -> Settings -> Roles -> Create custom role without  Dashboard.
2. Go to Admin -> Settings -> Users -> Create a User and assign custom roie.
4. Open a new window in incognito -> Login with custom user and check Not Found Page appears.
5. See error in URL it is still showing Dashboard.

### Expected Result

When a custom role is assigned to a user, logging in with the same user should redirect to the assigned path.

### Actual Result

Please check the video for reference. 

**Video**

https://github.com/user-attachments/assets/8f6ed7de-742a-4915-baf0-951c4ec21fda

**Comment by amit-webkul** [comment]
@ashishkumar-webkul ,

It shows 404 because it does not have appropriate permission for that page. And in Genearl we are redirected to Dashborad after admin user login.

**Comment by ashishkumar-webkul** [comment]
Checked and found that the issue has been fixed and working fine now, Please check the video for reference.

**Video**


https://github.com/user-attachments/assets/d3d0e988-cad6-4c87-96a2-2459e8538679
