### ISSUE TITLE
Custom Application Logo Not Displayed on Error Page

### ISSUE THREAD

**Issue by Pizdiec** [bagisto/bagisto#10249]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master and other 2.x.x versions

### Issue Description

When setting the .env variable APP_DEBUG to false in a Bagisto application, any thrown exceptions generate an error page that displays the default Bagisto logo instead of the custom application logo. This behavior occurs even though a custom logo has been set elsewhere in the application.

### Preconditions

A custom application logo has been set in the Bagisto configuration, overriding the default Bagisto logo.

### Steps to reproduce

1. Set APP_DEBUG=false in the .env file.
2. Cause an exception or navigate to a route that triggers an error.
3. Observe the generated error page.

### Expected Result

The error page should display the custom application logo that has been set for the application, rather than the default Bagisto logo.

### Actual Result

The default Bagisto logo appears on the error page instead of the custom logo.

### Screenshots

Error page:
![image](https://github.com/user-attachments/assets/5fb5d435-fdc4-4a5c-b874-f43b49155c63)
code in "rootProject/packages/Webkul/Admin/src/Resources/views/errors/index.blade.php":
![image](https://github.com/user-attachments/assets/740ed855-5c1f-4d45-913d-4c9fde043d23)
suggested fix:
![image](https://github.com/user-attachments/assets/7739c47e-7c36-4276-ac1c-bb11dc50bd4b)

**Comment by ashishkumar-webkul** [comment]
Checked and Found the issue and we will discuss the same in team and will be working on the same.

**Screenshot**

![Screenshot from 2024-11-04 09-27-42](https://github.com/user-attachments/assets/e653f7d4-c9b5-437e-ad60-43c335180e3a)

**Comment by ashishkumar-webkul** [comment]
@Pizdiec 

We have checked and fixed the issue and now you check the images are appearing as per logo.

https://prnt.sc/xc960UFY9gXP
