### ISSUE TITLE
Site Maintenance Mode is not working properly with IP.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10251]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

When I am adding the Public URL and then checking the Site it is showing the 503 Service Unavailable Message but when we are proceeding with Site IP then we are able to check the site.

### Preconditions

1. Admin must be logged in.

### Steps to reproduce

1. Go to Admin -> Settings -> Channels -> Edit Channel -> Maintenance Mode
2. Add Warning Message 
3. Add IP address

### Expected Result

1. For IP's also this must  work.
2. Warning message must appear when Maintenance Mode is activated.

### Actual Result

Currently having 2 issues.

1. Maintainance Mode is not working properly with IP Address.
2. Message is not appearing in the Service page which we have added.

### Screenshots

Please check the video and Screenshot for the same.

**Video**

https://github.com/user-attachments/assets/24b7d4b3-29cc-4bcf-bce0-ed097cc02e98

**Screenshot**

https://prnt.sc/aoECMd6hMX2O
https://prnt.sc/1T5Z_Es4xbpc

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir,

In this video, we can see the IP-based maintenance mode is working fine, as I have checked on my IP. Please check the reference video and let me know if any criteria we have missed.

[Reference Video](https://webkul.chatwhizz.com/share/view-recording/6728918567225a69d1aa3ac1)
