### ISSUE TITLE
Add to cart and Buy now button

### ISSUE THREAD

**Issue by suraj-webkul** [bagisto/bagisto#10283]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2

### Issue Description

When we enable the "Buy Now" feature in the configuration, go to any product view page, click the "Buy Now" button, then go back and click the "Add to Cart" button, it behaves as if the "Buy Now" button was clicked.

### Preconditions

Admin must be logged in.  
The customer can either be logged in or can browse as a guest.

### Steps to reproduce

1. Go to the admin configuration and enable the "Buy Now" feature.
2. Go to the product view page and click on the "Buy Now" button. Then, go back to the previous product view page.
3. Click on the "Add to Cart" button.

### Expected Result

It should only add product to the cart.

### Actual Result

It behaves as if the "Buy Now" button was clicked.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and found working now. Please check the video for reference.

**Video**


https://github.com/user-attachments/assets/039e71f0-6a49-400e-aac2-64ce15a0d1cb


https://github.com/user-attachments/assets/dd28c855-7130-45c9-9a9a-4cf73e29ea33
