### ISSUE TITLE
Other categories are not appearing after 3 level categories assigned.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10300]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

Other categories are not appearing after 3 level categories assigned.

### Preconditions

1. Atleast 3 categories must be created.

### Steps to reproduce

1. Go to Catalig -> Categories -> Add 3 Level Categories.
2. Now Again create a new Category -> Check the catgory assign list.

### Expected Result

All the categories must appear clearly.

### Actual Result

Please check the video for reference.

**Video**

https://github.com/user-attachments/assets/c1ceb342-7110-4fb9-bf32-efba6e695b2a

**Comment by amit-webkul** [comment]
@ashishkumar-webkul ,

I checked the reported issue in the master branch and found that there is no issue as described. I also recorded a short reference video for this, which you can review.


https://webkul.chatwhizz.com/share/view-recording/6734b10a67225a69d1abe0f7
