### ISSUE TITLE
Configurable Product with Over 100 Variants Fails to Save, Reloads Page Without Changes

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10311]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

When creating a configurable product in Bagisto with over 100 variants, attempting to save the product results in a page reload without any changes being saved. Initially, warnings about max_input_vars and max_multipart_body_parts exceeding limits appeared. After increasing these limits in php.ini (to 5000 for max_input_vars and 6500 for max_multipart_body_parts), the warnings stopped. However, the product still does not save, and the page simply reloads without providing any error message or indication of failure

### Preconditions

Bagisto Version: [2.2]
PHP Version: [8.2]
Database: MySQL

Admin must be logged in.

### Steps to reproduce

1] Create a configurable product in Bagisto.
2] Add more than 100 variants to the product.
3] Attempt to save the product.

**Observed Behaviour**

The page reloads after hitting save, and none of the entered data is saved. No error message appears, and the issue persists even after adjusting PHP settings (input variables, multipart body parts, memory limit, execution time).

### Expected Result

The product should save successfully with all variants intact.

### Actual Result

The page reloads after hitting save, and none of the entered data is saved. No error message appears, and the issue persists even after adjusting PHP settings (input variables, multipart body parts, memory limit, execution time).

### Additional context

PHP limits adjusted: max_input_vars = 5000, max_multipart_body_parts = 6500, memory_limit = 512M, max_execution_time = 300.
No errors found in PHP or Laravel logs.
Browser console shows no AJAX or JavaScript errors.

Increased PHP limits (max_input_vars, max_multipart_body_parts, memory_limit, max_execution_time).

Tried saving variants in smaller batches

**Comment by jeevatrippy** [comment]
I'm also facing the same issue in the same version, I have upgraded the server to VPS, Still having this issue. This is the error in the error log

[19-Dec-2024 03:08:16 America/New_York] PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in /home/corte/public_html/vendor/barryvdh/laravel-debugbar/src/DataCollector/QueryCollector.php on line 275

Please help us to fix this.
