### ISSUE TITLE
The Header and Footer should Enabled on Checkout Success page. 

### ISSUE THREAD

**Issue by amit-webkul** [bagisto/bagisto#10315]
**Describe the bug**
After checking multiple sites, I have come to know that the header and footer should be enabled on the check success page.

**To Reproduce:**
1. Go to the application
2. place the successful order
3. On the checkout success page, the header and footer are missing.

**Expected behavior**
The header and footer should be enabled on the checkout success page.

**Screenshots**

Current checkout success page:

![image](https://github.com/user-attachments/assets/cb4328c4-c264-40ac-b386-2eac6be46b7f)

Expected checkout success page:

![image](https://github.com/user-attachments/assets/9cc86080-6c7f-4c71-b7e7-a2a3a520ea42)

**Comment by ashishkumar-webkul** [comment]
I have checked the PR in multiple locale and found it working fine. hence I am approving the PR. Please check the video for reference.

**Video**


https://github.com/user-attachments/assets/f8b93ccc-632c-4e46-85a3-5f419e40e0ce


https://github.com/user-attachments/assets/4cdb7458-f9d9-4202-a246-0bead23ff4d3

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the Feature has been added and now we are able to see the footer and header in checkout page.

**Screenshot**

![Screenshot from 2024-12-18 09-29-29](https://github.com/user-attachments/assets/c6111ca1-fa00-40b0-9421-9ad32ecdc7ce)
![Screenshot from 2024-12-18 09-30-04](https://github.com/user-attachments/assets/4efebf40-ede7-4ac8-84ef-585bb852d7c6)
