### ISSUE TITLE
On the bundle product page, if any options contain a special price, then it should show.

### ISSUE THREAD

**Issue by amit-webkul** [bagisto/bagisto#10325]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2

### Issue Description

On the bundle product view page, if any bundle options contain a special price, then it should show. with the discounted price.

### Preconditions

Should have at least one bundle product with bundle options. and the added product in bundle as an option should have a special price as well.

### Steps to reproduce

1. Go to 'Admin -> Catalog -> Products'
2. Edit the product and add the bundle options.
3. Now open a preview of the page.
5. See error

### Expected Result

It should show the original price also.

### Actual Result

For now, it is showing only a discounted price.

### Screenshots

Expected result 

![image](https://github.com/user-attachments/assets/8bf419f9-4948-4c93-9dba-1f8adf65849e)

### Additional context

Thanks !

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the special price related information which was not appearing on Bundle Product has been fixed. Please check the video for reference.

**Video**

https://github.com/user-attachments/assets/3d9570dc-c6e7-481a-ae6e-970024db2969
