### ISSUE TITLE
The product page and admin datagrid should handle long product names effectively.

### ISSUE THREAD

**Issue by amit-webkul** [bagisto/bagisto#10323]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2

### Issue Description

If I add a longer length of product name, then it should manage responsiveness on the product page and admin datagrid product name section. 

### Preconditions

We have at least one product in the admin panel, or we need to create one product.

### Steps to reproduce

1. Go to 'Admin -> Catalog -> Products'
2. Click on 'create product / Edit Product'
3. Add longer length of product mame.
4. Go to product page or Admin -> Product datagrid 
5. See the error

### Expected Result

It should handle the responsiveness.

### Actual Result

For now, it is looking like this 

https://webkul.chatwhizz.com/share/view-recording/6735fe0da487c1594210dd81

### Screenshots

The expected response should look like this.

![Screenshot from 2024-11-14 19-20-42](https://github.com/user-attachments/assets/53a8d834-fe39-4ae8-8c80-fe364123eb47)
![Screenshot from 2024-11-14 19-20-31](https://github.com/user-attachments/assets/a309a7c2-f883-431f-bd1f-ca24dadfc9ca)

### Additional context

Thanks !

**Comment by ashishkumar-webkul** [comment]
Checked and found that the issue has been fixed and working fine. Please check the video for reference.

**Video**

https://github.com/user-attachments/assets/a893580c-88f0-4772-83be-057b3aef4d64
