### ISSUE TITLE
Position field in add and edit category pages should only take integer values.

### ISSUE THREAD

**Issue by kartikeywebkul9260** [bagisto/bagisto#10331]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.2

### Issue Description

Open Admin->catalog->categories->create fill all data enter any word in Position field and save category. It should not save.
Open Admin->catalog->categories->edit enter any word in Position field and save category. It should not save.

### Preconditions

Open Admin->catalog->categories->create fill all data enter any word in Position field and save category. It should not save.
Open Admin->catalog->categories->edit enter any word in Position field and save category. It should not save.

### Steps to reproduce

1. Go to 'Admin'
2. Click on 'Catalog'
3. Click on 'Category'
4. Click on 'Create Category'
5. Fill any word in Position field
6. See error

### Expected Result

Only integer value should accepted

### Actual Result

Alphabets can enter and save.

### Screenshots

![Screenshot from 2024-11-18 16-38-49](https://github.com/user-attachments/assets/b58179f6-1983-4f9f-9277-c9d5b2a9973a)

**Comment by ashishkumar-webkul** [comment]
Checked and found that the category position issue has been fixed and working fine. Please check the video for reference.

**Video**

https://github.com/user-attachments/assets/518b29da-6182-4a28-b218-2cfe61bc6155
