### ISSUE TITLE
Getting SQLSTATE[23000] in error msg while mass deletion of few attributes like size, color, weight. 

### ISSUE THREAD

**Issue by kartikeywebkul9260** [bagisto/bagisto#10341]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.2.2

### Issue Description

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`test_bagisto`.`product_super_attributes`, CONSTRAINT `product_super_attributes_attribute_id_foreign` FOREIGN KEY (`attribute_id`) REFERENCES `attributes` (`id`) ON DELETE RESTRICT) (Connection: mysql, SQL: delete from `attributes` where `id` = 24)

msg showing in error msg while mass deletion of few attributes like size. 

### Preconditions

Use mass delete in attributes page

### Steps to reproduce

1. Go to 'Admin'
2. Click on 'Catalog'
3. Click on 'Attributes'
4. Select CheckBox In front of 'size' Attribute
5. Select Action as Delete
6. Click on Agree button
7. See error

### Expected Result

A proper message should show

### Actual Result

Attribute Deletion Failed

### Screenshots

https://webkul.chatwhizz.com/share/view-recording/673c396d16db6f070f0ef9ca

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and working fine now. Please check the video for reference.

**Video**


https://github.com/user-attachments/assets/d6d97da7-6fdb-471a-84b6-6e889560dddb
