### ISSUE TITLE
Local issue in category edit section at Description.

### ISSUE THREAD

**Issue by kartikeywebkul9260** [bagisto/bagisto#10345]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0

### Issue Description

When we try to edit category and change the local after that changes in Description field saved into english local always.__

### Preconditions

Create a new category in english local.

### Steps to reproduce

1. Go to 'Admin->Catalog->Categories'
2. Click on 'edit button(pen symbol) for new created category'
3. Change Local to 'Arabic'
4. Scroll down to 'Description'
5. Edit Description
6. Save Category
7. Again Click on 'edit button(pen symbol) of same category'
8. Change Local to 'English'
9. Scroll down to 'Description'
10. See Description
11. See error
12. Change Local to 'Arabic'
13. Scroll down to 'Description'
14. See Description
15. See error

### Expected Result

The Description should save for different local not for english only.

### Actual Result

The Description save for for english only.

### Screenshots

![trans-issue](https://github.com/user-attachments/assets/54873413-fedc-4d08-9013-e247ed9b7fa6)
![transsssssss](https://github.com/user-attachments/assets/0092b54f-9122-4e9d-b0a1-5195b66a10cc)

**Comment by amit-webkul** [comment]
@kartikeywebkul9260

As per the reported issue, we could not replicate the problem in our stable branch version 2.2.

Please refer to the video for more details: [Reference Video](https://webkul.chatwhizz.com/share/view-recording/673d8f6f16fa4b0580b5951a).
