### ISSUE TITLE
Update Exchange Rate button is not working

### ISSUE THREAD

**Issue by kartikeywebkul9260** [bagisto/bagisto#10352]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.2.3, v2.2.2

### Issue Description

Update Exchange Rate button is not working at admin/settings/exchange-rates showing unexpected error message

### Preconditions

Login to admin

### Steps to reproduce

1. Go to 'admin/settings/exchange-rates'
2. Click on 'Update Exchange Rate' button

### Expected Result

It should be work properly or show proper message

### Actual Result

showing unexpected error message

### Screenshots

![Screenshot from 2024-11-21 14-13-53](https://github.com/user-attachments/assets/57962abd-7a19-4808-b69f-eeb3981f88fe)

**Comment by amit-webkul** [comment]
@kartikeywebkul9260 

This is not an issue If you are trying to check the `updated exchange rate`, you need to add the Fixer or exchange rate API in your application under  .env file.

**Add the Keys to Your Bagisto Environment**:
-- Open the `.env` file in the root of your Bagisto project and input the details:

FIXER_API_KEY=your_fixer_api_key
EXCHANGE_RATES_API_KEY=your_exchange_rates_api_key
EXCHANGE_RATES_API_ENDPOINT=https://api.exchangeratesapi.io/latest
