### ISSUE TITLE
Creating new variant , the new product doesnt show the correct attributes

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#10357]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.3

### Issue Description

Creating new variant , the new product doesn't show the correct attributes

### Preconditions

No pre conditions

### Steps to reproduce

please see video

https://github.com/user-attachments/assets/47b0d905-4d7c-4ec9-9444-7ec1c5dfd823

### Expected Result

the new product contain the correct attributes

### Actual Result

the new product not has the correct attributes

**Comment by amit-webkul** [comment]
Thank you so much for bringing this issue to our attention and for your valuable contribution. We truly appreciate your efforts in helping us improve the platform.

We’d like to inform you that this issue has already been identified and reported earlier. You can view the details here: [Link](https://github.com/bagisto/bagisto/issues/10262).

Additionally, a Pull Request (PR) has already been created to address it: [Link](https://github.com/bagisto/bagisto/pull/10284).

Please feel free to share any further insights or suggestions. Your feedback is always valuable to us.
