### ISSUE TITLE
Undefined array key "info" when generate custom shipping method

### ISSUE THREAD

**Issue by zeffrypfs** [bagisto/bagisto#10363]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.3

### Issue Description

I want create custom shipping method and bagisto provide generator to do it. in [docs](https://devdocs.bagisto.com/2.2/advanced/create-shipping-method.html) we can using package generator. After running the command then i run : 
- composer dump-autoload
- php artisan optimize:clear

But the problem is when navigate into admin -> configuration i got error : 
```
Undefined array key "info" (View: C:\Project Prima Food Solutions\php\pfs-ecommerce-bagisto\packages\Webkul\Admin\src\Resources\views\configuration\index.blade.php)
```

### Preconditions

Php Version
8.2.9

Laravel Version
10.48.24

Laravel Locale
en

Laravel Config Cached
true
App Debug
true
App Env
local

OS : 
OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631

### Steps to reproduce

1. Follow [this](https://devdocs.bagisto.com/2.2/advanced/create-shipping-method.html#introduction) instruction for create custom shipping method
2. Navigate into : http://127.0.0.1:8000/admin/configuration

### Expected Result

Web running smoothly

### Actual Result

Got error : 
```
Undefined array key "info" (View: C:\Project Prima Food Solutions\php\pfs-ecommerce-bagisto\packages\Webkul\Admin\src\Resources\views\configuration\index.blade.php)
```

### Screenshots

![image](https://github.com/user-attachments/assets/b4fba7a9-bb1d-4e54-b8ca-35ce70c2050a)

**Comment by amit-webkul** [comment]
Thank you for reaching out. It looks like your request is not an issue report. For discussions, questions, or general support, we encourage you to use the [Bagisto Forum](https://forums.bagisto.com/). The forum is the best place for such queries, and you'll be able to connect with other community members and get the help you need.

Please reserve the GitHub issue tracker for reporting bugs and issues with the codebase. This helps us keep the issue tracker focused and ensures that problems are addressed promptly.

Thank you for your understanding!
