### ISSUE TITLE
language file mess up

### ISSUE THREAD

**Issue by 10twenty** [bagisto/bagisto#10375]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2.2

### Issue Description

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php

The above should be the language file for Chinese. 
However, line 3744 to 4136 are all entered as Japanese.

### Preconditions

none.

### Steps to reproduce

none.

### Expected Result

correct the language.

### Actual Result

messed up with some Japanese.

**Comment by amit-webkul** [comment]
Hello @10twenty ,

Thank you for your valuable contribution to Bagisto.

We are actively working on resolving this issue and will provide an update here shortly. We sincerely appreciate your time, effort, and support in helping us improve.
