### ISSUE TITLE
Empty Home Page

### ISSUE THREAD

**Issue by shaizy1234** [bagisto/bagisto#10381]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.2.3

### Issue Description

Hello,
I have just installed your app and updated the home page slider and other options exactly your demo but home page is empty
I have even cleared the cache but same.
Its just showing header and footer and nothing between them.
can you please look into this?

### Preconditions

new installation

### Steps to reproduce

check attached pics of home page and also admin panel theme edit.

### Expected Result

home page with header and footer only

### Actual Result

empty home pge

### Screenshots

<img width="1435" alt="Screenshot 2024-12-02 at 19 12 16" src="https://github.com/user-attachments/assets/cf5619c4-f26e-43c6-80b9-b34f7660107a">
<img width="1226" alt="Screenshot 2024-12-02 at 19 12 07" src="https://github.com/user-attachments/assets/e3daf92a-7239-43d8-8264-080af284af9c">
<img width="1202" alt="Screenshot 2024-12-02 at 19 12 00" src="https://github.com/user-attachments/assets/16a4e5b8-72e6-4607-b34c-72a20a598e68">

**Comment by ashishkumar-webkul** [comment]
@shaizy1234 

Could you please let us know if, after the installation, you were able to see the default banner images and other respective images?

**Comment by ashishkumar-webkul** [comment]
**@shaizy1234**  

I have freshly installed Bagisto with the V2.2.3 branch and did not encounter any issues related to the details mentioned above. Please refer to the video for reference.  

If you are still facing this issue, kindly share detailed steps to reproduce it. We would be happy to assist you further. For now, I am closing the issue.  

**Video:**

https://github.com/user-attachments/assets/05245b17-34c0-4a35-9fce-06729d48d392

**Comment by shaizy1234** [comment]
Hello, I don't have new installation, I did upgrade from my old website and I follow 
https://devdocs.bagisto.com/1.x/introduction/upgrade-to-latest-bagisto.html#bagisto-changes

Thanks

**Comment by shaizy1234** [comment]
any update please?
