### ISSUE TITLE
 Add "Cost Price" field for products

### ISSUE THREAD

**Issue by KarimQaderi** [bagisto/bagisto#10383]
### Is your feature request related to a problem? Please describe.

Yes, currently Bagisto only has a field for the selling price of products, but there is no way to define a "Cost Price" for products. This limitation makes it difficult to accurately manage product costs and calculate profits.

Comment This feature would help store owners better track their profit margins and make financial management more efficient within the platform.

### Describe the solution you'd like

I would like a new field called "Cost Price" to be added to the product details. The field should be numeric (Decimal) and optional for the store owner to fill in. Additionally, it should be accessible in the admin panel for viewing and editing.

### Describe alternatives you've considered

 Currently, there is no alternative within the platform for tracking cost price directly. Some store owners may manage this manually outside of the system, but an integrated solution would be much more efficient.

### Additional context

Adding a "Cost Price" field would provide more accurate financial reporting, allowing store owners to calculate their profits more easily and improving the overall management of product pricing. The API should also be updated to allow access to this field for integration with external systems if needed.

**Comment by ghermans** [comment]
The cost field is already available 

![image](https://github.com/user-attachments/assets/c3a2c56a-1a5b-4709-99c5-894f55d690f5)

**Comment by KarimQaderi** [comment]
Thank you for the update! I have a follow-up question:

Is the cost price recorded within the order items when an order is placed?
Is it included in reports for calculating profit or cost-related metrics?

**Comment by ashishkumar-webkul** [comment]
@KarimQaderi

You can navigate to Admin -> Catalog -> Products -> Edit Product Page and check the Price section on the right.

The Cost Price field is already available there.

Thank you.

**Comment by ashishkumar-webkul** [comment]
**@KarimQaderi**  

When a product is created, if you add a **Selling Price**, **Cost Price**, and **Special Price**, only the **Special Price** and **Selling Price** will be visible on the Shop Front.  

- **Admin Screenshot:** [[View here](https://img001.prntscr.com/file/img001/Jc_RL2CNRJG019ELCU2LJw.png)]
- **Shop Front Screenshot:** [[View here](https://img001.prntscr.com/file/img001/rYjWOX-JQ5iA4xUvyHqREQ.png)]

### Cost Price Handling After Placing an Order:  

- **Is the Cost Price recorded within the order items?**  
  - No. Only the **Product Selling Price**, **Subtotal**, **Discount**, and **Tax** details are recorded.  

- **Is the Cost Price included in reports for profit or cost-related metrics?**  
  - No. You can refer to this screenshot for details: [[View here](https://img001.prntscr.com/file/img001/DVT9chqzS9i1vrzIGZ3Gew.png)] 

Thank you.

In case you have any doubt feel free to reach out to us.

**Comment by KarimQaderi** [comment]
Thank you.
