### ISSUE TITLE
Change channel_id problem

### ISSUE THREAD

**Issue by jimmY276** [bagisto/bagisto#1048]
ErrorException (E_ERROR)
file_put_contents(D:\xampp\htdocs\bagisto\storage\app/db-blade-compiler/views/3ad3cf66a3856b81120bd1be29475b50): failed to open stream: No such file or directory (View: D:\xampp\htdocs\bagisto\packages\Webkul\Shop\src\Resources\views\home\index.blade.php)

**Comment by rahulshukla-webkul** [comment]
Hi,

Please run following  commands- 

1. composer dump-autoload
2. php artisan vendor:publish

at root of your project directory.


Thanks
Rahul Shukla

**Comment by ashikdnd** [comment]
Why did you close this issue? This is not the solution! Running the vendor:publish command lists a number of packages asking to choose one.

**Comment by vaishaliwebkul** [comment]
@ashikdnd 
you can press 0 to continue, it will publish all packages then check the error again.
