### ISSUE TITLE
If cart rule get expired the on using that coupon it should throw an error message that coupon code is expired.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1062]
- Framework Version: 0.1.6

**Comment by prashant-webkul** [comment]
@jyoti-webkul A generic message is displayed "Coupon cannot be applied" is displayed when the coupon is not applicable due to any kind of reason.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6
-------------------------------------------
Fixed, showing message "Cannot apply coupon"
