### ISSUE TITLE
Provide a button to change the "am" and "pm" of time

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1063]
- Framework Version: 0.1.6

--------------------------------------------------

![Screenshot from 2019-06-18 13-58-21](https://user-images.githubusercontent.com/45203177/59665952-83fb7d00-91d1-11e9-85b0-787e4c83afbc.png)

**Comment by rahulshukla-webkul** [comment]
you can click on 'AM' or 'PM' to change it.
