### ISSUE TITLE
Validation error message is not showing for Customer Group.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1075]
- Framework Version: 0.1.6

-----------------------------------------

![Screenshot (18)](https://user-images.githubusercontent.com/45203177/59765782-6fe07a00-92bc-11e9-8c41-b9b72cde78e2.png)

**Comment by prashant-webkul** [comment]
@jyoti-webkul Check this issue.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------
Fixed

![Screenshot from 2019-06-27 15-00-57](https://user-images.githubusercontent.com/45203177/60255062-a5085000-98ec-11e9-801e-0b131a8322ba.png)
