### ISSUE TITLE
I have an configration error

### ISSUE THREAD

**Issue by MichleLI** [bagisto/bagisto#1077]
![image](https://user-images.githubusercontent.com/45660446/59792098-05ecc280-9306-11e9-8818-5648a6534cf9.png)

**Comment by prashant-webkul** [comment]
Hey you just need to turn off your strict mode of php from php settings file called php.ini

**Comment by MichleLI** [comment]
Thanks, Prashant!
when i install using ui method, it installed perfectly. only console mode have this kind of error.
And I have another issue
![image](https://user-images.githubusercontent.com/45660446/59816488-e75ee980-934e-11e9-8171-e71843474355.png)
please help me!

**Comment by rahulshukla-webkul** [comment]
Hi @MichleLI ,

In foreach loop change 'product_types' to 'product-types' in the given place or you can download our latest version - https://github.com/bagisto/bagisto.

Thanks
Rahul Shukla

**Comment by MichleLI** [comment]
Thanks for your quickly response, Rahul Shukla.
