### ISSUE TITLE
Success message should display in green color after editing the cart and approving the customer.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1086]
- Framework Version: 0.1.6

------------------------------------------

![Screenshot from 2019-06-21 11-45-39](https://user-images.githubusercontent.com/45203177/59902062-c9f75180-941a-11e9-8b2a-950e7174fa36.png)
![Screenshot from 2019-06-21 11-51-53](https://user-images.githubusercontent.com/45203177/59902127-fca14a00-941a-11e9-8c0d-c3bd8931274f.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-------------------------------------------

Updated only for cart.Change this for customer update status also.

![Screenshot(1)](https://user-images.githubusercontent.com/45203177/60173304-0caa9680-982c-11e9-9d7c-645955f1dfd2.png)
![Screenshot from 2019-06-26 16-04-48](https://user-images.githubusercontent.com/45203177/60173399-4085bc00-982c-11e9-8ac5-d24a6d1b7b79.png)

**Comment by prashant-webkul** [comment]
Issue is fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6
-----------------------------------------

Fixed
![Screenshot from 2019-06-27 15-00-57](https://user-images.githubusercontent.com/45203177/60254933-78543880-98ec-11e9-8001-2ef1c8b7494b.png)
