### ISSUE TITLE
Remove "For Guest" column from cart rule. Add customer group column instead of this.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1091]
- Framework Version: 0.1.6

-------------------------------------------------

![Screenshot(10)](https://user-images.githubusercontent.com/45203177/59905755-a76a3600-9424-11e9-8f70-b900c3c8da16.png)

**Comment by prashant-webkul** [comment]
@jyoti-webkul This issue is fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.2

-------------------------------------------

For Guest is removed but Customer Group column is not added.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------------
Fixed
