### ISSUE TITLE
If maximum quantity allowed to discount is selected as 2 then on both product discount should be applied.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1095]
- Framework Version: 0.1.6

------------------------------------------
![Screenshot(14)](https://user-images.githubusercontent.com/45203177/59920736-18bbe000-9449-11e9-872b-4bf8d570aaf3.png)

![Screenshot(16)](https://user-images.githubusercontent.com/45203177/59920900-adbed900-9449-11e9-863f-f13f4c62e2ab.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------
Not fixed

**Comment by prashant-webkul** [comment]
@jyoti-webkul This issue is fixed as per the current situation the cart rules only work for least worth item.

**Comment by jyoti-webkul** [comment]
ok
