### ISSUE TITLE
Coupon get applied if only one product is added in cart and from action it is saved as buy atleast 2.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1097]
- Framework Version: 0.1.6

**Comment by prashant-webkul** [comment]
![buyatleast](https://user-images.githubusercontent.com/41140572/60178688-be03f900-9839-11e9-8ed3-c4c6a4866eb8.png)

Took only one item in cart the rule doesn't work as it required atleast two quantiy of the item:
![not being applied](https://user-images.githubusercontent.com/41140572/60178834-f4da0f00-9839-11e9-900f-c6f279a1a965.png)

Updated quantity:
![updated qty](https://user-images.githubusercontent.com/41140572/60179219-d9233880-983a-11e9-9646-ec023b9b704b.png)


Rule now works:
![applied after quantity applied](https://user-images.githubusercontent.com/41140572/60179242-e4766400-983a-11e9-8a5b-66f6df7fd3f7.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Fixed
