### ISSUE TITLE
Avoid undefined variables in compact()

### ISSUE THREAD

**Issue by stefano73it** [bagisto/bagisto#1101]
From PHP 7.3.0 compact() issues an E_NOTICE level error if a given string refers to an unset variable. Formerly, such strings have been silently skipped.

**Comment by prashant-webkul** [comment]
@stefano73it Please configure your php.ini file with the setting using strict mode and turn your strict mode off.
Strict mode on will give the soft warnings and will hindering in tasting the smoothness of Laravel framwork.
