### ISSUE TITLE
After exporting the customer status of customer is showing as "0" and "1" in csv and xls file

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1120]
- Framework Version: 0.1.6

-----------------------------------------------
![Screenshot from 2019-06-27 14-26-58](https://user-images.githubusercontent.com/45203177/60252669-44771400-98e8-11e9-950b-af2f760d1bee.png)

**Comment by prashant-webkul** [comment]
Cannot be done database values that are actually stored are exported as it is.
