### ISSUE TITLE
If "does not contain" is used in case of Shipping method, then discount amount get implemented before selecting any shipping method.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1130]
- Framework Version: 0.1.6

---------------------------------------------

![Screenshot (40)](https://user-images.githubusercontent.com/45203177/60265487-7e094880-9903-11e9-990d-1a5dd5cd33ce.png)
![Screenshot (41)](https://user-images.githubusercontent.com/45203177/60265533-95483600-9903-11e9-8bc6-3851421f1697.png)

**Comment by prashant-webkul** [comment]
This issue is fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------

Fixed
