### ISSUE TITLE
Invoice Print

### ISSUE THREAD

**Issue by webkul** [bagisto/bagisto#114]
Great project how can an admin create an invoice?

**Comment by jitendra-webkul** [comment]
![download](https://user-images.githubusercontent.com/39991107/47784139-bc297a80-dd2a-11e8-9867-3c8a7181d6ac.png)

By clicking on invoice button in order view page.

**Comment by webkul** [comment]
How we can download it in PDF?

**Comment by jitendra-webkul** [comment]
In next release, we will add this feature

**Comment by jitendra-webkul** [comment]
![download](https://user-images.githubusercontent.com/39991107/47899997-5f040500-dea1-11e8-9903-86e3b58f3b8f.png)

Download PDF feature added
