### ISSUE TITLE
Use the translated strings in cart remove action

### ISSUE THREAD

**Issue by stefano73it** [bagisto/bagisto#1147]
The confirmation message for cart remove action must use the translated string:

onclick="removeLink('Do you really want to do this?')">

**Comment by rahulshukla-webkul** [comment]
Hi @stefano73it 

We have changed it to translated strings. Thanks for notifying.

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.6

------------------------------------------
Fixed
