### ISSUE TITLE
Zip code is mandatory on tax rate

### ISSUE THREAD

**Issue by rabol** [bagisto/bagisto#1149]
the zip code is a mandatory field when one create a new Tax Rate.

In many European countries the zip code is not used, e.g the tax rate in Denmark is 25%, in Spain it is 21%

The zip code requirements should only apply if 'Enable zip range' is selected

**Comment by rahulshukla-webkul** [comment]
Hi @rabol,

You can enter *(star) in zip code field so it will be beyond zip code & will work accordingly.
