### ISSUE TITLE
in total item condition value for products should start from 1 insted of 0.1

### ISSUE THREAD

**Issue by simantverma** [bagisto/bagisto#1154]
![item-condition](https://user-images.githubusercontent.com/49390338/60752437-437a6c80-9fe3-11e9-8972-65dfb36a6544.png)

**Comment by prashant-webkul** [comment]
@simantverma  Its correct way to take input as there are cases where fractions of whole units also get involved.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

------------------------------------------
Not fixed

![Screenshot (66)](https://user-images.githubusercontent.com/45203177/64610732-8692fa80-d3ed-11e9-9227-6e4524b89fa5.png)
