### ISSUE TITLE
Front-end Filterable Attributes shoud be more intelligent

### ISSUE THREAD

**Issue by prowseed** [bagisto/bagisto#1160]
Front-end Filterable attributes (those in side panel) should not be visible unless there is a specific product that could be filtered. In big shops with lots of different attributes (sometimes with same names but different values, like Manufacturer) it gets really messy. Perhaps they should be bound to and displayed only on specific categories? Or just taken from all the products that are attached to given category? This should be addressed somehow.

**Comment by rahulshukla-webkul** [comment]
Hi @prowseed thanks for your suggestion. We will change it.

**Comment by selvarajblr93** [comment]
> Front-end Filterable attributes (those in side panel) should not be visible unless there is a specific product that could be filtered. In big shops with lots of different attributes (sometimes with same names but different values, like Manufacturer) it gets really messy. Perhaps they should be bound to and displayed only on specific categories? Or just taken from all the products that are attached to given category? This should be addressed somehow.

This is really a very important feature that required to be added.

**Comment by rahulshukla-webkul** [comment]
Hi @prowseed 

We have solved this one. Now Filterable attributes is visible only if products belong to that filterable attribute. 
You can clone from master branch of our repository.

Thanks
