### ISSUE TITLE
Table too big

### ISSUE THREAD

**Issue by prowseed** [bagisto/bagisto#1162]
Hello, I am creating pretty big store (more than 2000 products) and now I'm stuck in situation, where I have lots of attributes bound to product and need to add 180 more, but only when I want to add another attribute, i get the error:

```
Illuminate \ Database \ QueryException (42000)
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs (SQL: alter table `product_flat` add `lb_266c7766c0` text null)
```

Is there any way to overcome this?

**Comment by rahulshukla-webkul** [comment]
Hi @prowseed ,

We have resolved this issue, kindly pull from master branch & 
do one thing, remove all 'Visible on Product View Page on Front-end'(https://prnt.sc/oc1kjv) from 'product_flat' table.

Thanks for notifying us.

**Comment by stoney024** [comment]
I don't think it will fix the problem. If you have to create many attribute filter, like my shop now has 4K products, with 2300 attributes. You can easily get over the mysql column limit with the product_flat table.

**Comment by rahulshukla-webkul** [comment]
Hi @stoney024 

In next release, we will give option for attribute to decide whether it will column in product_flat table or not.
