### ISSUE TITLE
Currency Format

### ISSUE THREAD

**Issue by prowseed** [bagisto/bagisto#1166]
Each currency should expose a formatting function with fixed parameters:
- `Position: Left, Left with space, Right, Right with space`
- `Thousand separator: Space, dot, comma, none`
- `Decimal separator: dot, comma`
returned string should have currency sign wrapped in some html element to allow further styling customizations, like `1 299,00 <span>PLN</span>`

Now, for PLN currency I get PLN1299.00 which doesn't looks good.

**Comment by VoidCupboard** [comment]
Is this still still up for Hacktoberfest 2022? If so I would love to work on it

**Comment by sunarcrajneesh** [comment]
Is this still up ?  If yes I would love to work on it. I will need more explanation. Because I saw in latest version of bagisto currency symbol and readable number format is available.

**Comment by sunarcrajneesh** [comment]
Position: Left, Left with space, Right, Right with space
// If this position is related to the currency symbol, we can provide a dropdown for custom spacing like left, right etc.

Thousand separator: Space, dot, comma, none
Decimal separator: dot, comma

// Thousand separators and decimal separators are available in Bagisto's new version. However, we can add more options by customization , such as using a different symbol like ^ or &, we can provide that option as well.

The returned string should have the currency sign wrapped in an HTML element to allow for additional styling customizations, like 1 299,00 <span>PLN</span>.
// For this purpose, we can provide the symbol with <span> tag, enabling further styling.

**Comment by saurav-webkul** [comment]
This is fine @sunarcrajneesh , please proceed

**Comment by saurav-webkul** [comment]
When are we looking to have PR for this issue @sunarcrajneesh , any approx idea so we can see for the launch schedule

**Comment by sunarcrajneesh** [comment]
We are aiming for October 3rd to submit the PR. 
Along with this, In the Bagisto 2.0 beta version, we have come across two issues for which we can provide solutions. These issues are as follows: 

The first issue is that both the currency add and edit forms have the same title for editing.
![Screenshot from 2023-09-29 11-55-42](https://github.com/bagisto/bagisto/assets/45708520/18c577a9-f46b-4683-ab0f-2aff7bf84f3e)

The second issue is in the currency datagrid on the admin side, where the column with the title "code" displays the names of currencies, and the column with the title "name" displays the codes of currencies.
![Screenshot from 2023-09-29 11-52-50](https://github.com/bagisto/bagisto/assets/45708520/8fff5b48-95f7-420f-a64b-25f753a405c4)

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh Thank you for your interest. Point 1 is not an [issue](https://prnt.sc/aMcik02FfOrN). for that please take a pull from master. and the second point for the data grid issue will be fixed internally.

**Comment by sunarcrajneesh** [comment]
This enhancement is done by our team on our local setup. We are testing it. 

I saw that you marked it completed here. Let me know what it means. Shall we continue our work on this or it's done by someone else?

Waiting for your reply.

**Comment by amit-webkul** [comment]
Hi @sunarcrajneesh ,

Point 1 as mentioned is not an issue. The second one will be done internally by the core team.

Kindly don't work as of now on this issue. Thanks for the follow-up.

**Comment by devansh-webkul** [comment]
Hi @sunarcrajneesh,

You can feel free to raise the PR which we already discussed in the thread.
