### ISSUE TITLE
Toggle instead of selects in boolean values

### ISSUE THREAD

**Issue by prowseed** [bagisto/bagisto#1167]
In admin panel for any given Yes/No attribute there should be Yes/No Toggle (Radio) Buttons instead of select with two values (perhaps yes/no/off for no mandatory fields- to decide). Also I would suggest to transform selects into toggle buttons with less or equal 5 fields to choose from. It would be more user friendly.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

------------------------------------

Toogle implemented
