### ISSUE TITLE
Admin Area UI Enhancements

### ISSUE THREAD

**Issue by prowseed** [bagisto/bagisto#1168]
Title and Save button should be sticky (fixed) on top, with huge forms there is lots of scroll down/scroll up unnecessary events.

Also, when there is some error with form (like save product) there should be red toast warning, it is unclear now if there are some warnings, because they are usually not visible on screen.

SKU field should allow to use Big Letters and dots, like: `LB-001.02` should be legal SKU

During the creation of iterating fields (like fields for select attribute) Order is mandatory, so it should be autopopulated with 0, 1 or autoincrementing value

**Comment by prashant-webkul** [comment]
Hello @prowseed we have added the functionality in our latest master builds that keeps the submit buttons fixed regard less of the page scrolls.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

---------------------------------------

Fixed
![Screenshot (67)](https://user-images.githubusercontent.com/45203177/64610838-c22dc480-d3ed-11e9-8757-666149535a03.png)
