### ISSUE TITLE
Same item, different price

### ISSUE THREAD

**Issue by prowseed** [bagisto/bagisto#1171]
Is there any possibility to have different prices in different shops? Let's say I have two channels connected to same warehouse, but I'd like to display different prices in each channel. Is there any sensible option for that?

**Comment by rahulshukla-webkul** [comment]
Hi @prowseed 

Yes you can do it. You need price (attribute) per channel so while creating product, price will be save according to channel.

Thanks

**Comment by rahulshukla-webkul** [comment]
Hi @prowseed 

By default price (attribute) did not depends on channel  (Value Per Channel) & you can't edit it through UI so you need to set '1' in price attribute's 'value_per_channel' column in database directly.

**Comment by AliRazaLilani** [comment]
but when you manually update 'value_per_channel' to '1' . It removes variant's prices
