### ISSUE TITLE
Admin logo is visible only at login page.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1173]
- Framework Version: 0.1.6

--------------------------------------------------
It should display here also

![Screenshot (83)](https://user-images.githubusercontent.com/45203177/60972842-ad2caa80-a344-11e9-812e-462c0afcfd37.png)

**Comment by prashant-webkul** [comment]
Fixed in PR #1175

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Fixed

![Screenshot (71)](https://user-images.githubusercontent.com/45203177/62274028-aa613900-b45c-11e9-8053-78b8d4e2fd88.png)
