### ISSUE TITLE
Admin - price with channel's base currency

### ISSUE THREAD

**Issue by prowseed** [bagisto/bagisto#1174]
While creating a product, the price field is always in USD even though default currency is any other there is no USD in this channel at all, because of that it is harder to maintain the products portfolio. Please consider price field to be in base currency of the channel.

**Comment by rahulshukla-webkul** [comment]
Hi @prowseed 

Base currency is a currency, which will show on channel's front end. Systems base currency is used while product creation (config->app.php).
