### ISSUE TITLE
api

### ISSUE THREAD

**Issue by parimahziyi** [bagisto/bagisto#1176]
Hi
great bagisto 
how can I send my token in URL to access special route in API?
for example, I enter: "http://127.0.0.1:8000/api/addresses/create"
and responded is:   "error": "Unauthenticated"
I try to send toke like?token=1734fe9bb3f5f21abe6697e162825671
or in the authorization tab and put the token in the bearer token field in postman 
i know that your project uses $customer = auth($this->guard)->user(); for authentication but how can i access this? 
but the answer is the same
also when I add auth:api for urls the same thing happened

**Comment by rahulshukla-webkul** [comment]
Hi @parimahziyi 

You can see the following - https://forums.bagisto.com/topic/149/i-need-to-deliver-the-api-token-from-the-json-response-not-the-header/4

**Comment by parimahziyi** [comment]
thanks for your response. but what I need is how to carry token in API URL.
i used:
     Route::group(['middleware' => 'auth.jwt'], function() {

            // your routes
            Route::get('/pari', 'ProductController@pari');
        });
and send api like: http://127.0.0.1:8000/api/pari?token=1734fe9bb3f5f21abe6697e162825671 or http://127.0.0.1:8000/api/pari but in both i get  "error": "Unauthenticated" as response. either i use my adminmiddleware or auth:api for limitinng access to function like:
       Route::middleware('auth:api')->group(function() {
            Route::get('/user' , 'ProductController@index');
        });
    Route::group(['middleware' => ['auth', 'admin']], function() {
            Route::get('products/{id}', 'ProductController@get');
    }); 
but again same error. what should i do? how to authorize bagisto?with jwt?

**Comment by parimahziyi** [comment]
and I should say also when I add token in authorized tap bearer token ..it returns for me the same error unauthorized.
how should I sent token to access in protected API URL?

**Comment by prashant-webkul** [comment]
@parimahziyi Have you attached XSRF token?

**Comment by parimahziyi** [comment]
no actually. I change anything. I just want to know how could I access to auth:api route in api within your project. or it means in which way I should send the token to access in  auth:api route

**Comment by prashant-webkul** [comment]
@parimahziyi We haven't used scaffold routes of Laravel, you can try using them directly in routes/api.php file.

**Comment by parimahziyi** [comment]
yes. you said right. thanks for your perfect guides
I will do it right now

**Comment by nintellectaugmentation** [comment]
the bagisto documentation on authentication for api is very unreliable, everyone is facing issues with auth, should be addressed
