### ISSUE TITLE
Getting exception when trying to recover password.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1177]
- Framework Version: 0.1.6

![Screenshot from 2019-07-11 16-44-58](https://user-images.githubusercontent.com/45203177/61046747-7fef0380-a3fb-11e9-81b3-7d163651e16a.png)

**Comment by prashant-webkul** [comment]
You mail settings are not configured correctly.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6
--------------------------------------------
Fixed
