### ISSUE TITLE
Configure menu is not visible properly.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1179]
- Framework Version: 0.1.6

--------------------------------------------

![Screenshot (18)](https://user-images.githubusercontent.com/45203177/61121686-7201b700-a4bd-11e9-8b26-e8d5d7582ae2.png)

**Comment by prashant-webkul** [comment]
The release that you are testing is not production ready. Do compilation of assets in Admin panel my npm install and npm run dev yourself.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

----------------------------------------------
Fixed
![Screenshot (59)](https://user-images.githubusercontent.com/45203177/64606406-cfde4c80-d3e3-11e9-8944-17f4baa7e04d.png)
