### ISSUE TITLE
Missing ProductGrid class in Product/ModuleServiceProvider

### ISSUE THREAD

**Issue by laurenwilliams92** [bagisto/bagisto#1185]
Illuminate\Contracts\Container\BindingResolutionException  : Target [Webkul\Product\Contracts\ProductGrid] is not instantiable while building...

This is being thrown due to the ProductGrid class being missed from the ModuleService provider,  all other models are included except this one.

**Comment by rahulshukla-webkul** [comment]
Hi @laurenwilliams92 

We have removed ProductGrid model & its table, Kindly install new version.
Follow this repository for new instillation or for pull -  https://github.com/bagisto/bagisto

Thanks
