### ISSUE TITLE
After printing invoice at customer end, price is not getting change according to currency in invoice.  . 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1190]
Framework Version: 0.1.6

![Screenshot (73)](https://user-images.githubusercontent.com/52821836/61457228-775f7580-a985-11e9-9e1a-45ba40c5c6c8.png)

![Screenshot from 2019-07-18 17-54-27](https://user-images.githubusercontent.com/52821836/61457117-40895f80-a985-11e9-947a-4c4c1b8211fe.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------------
Fixed
