### ISSUE TITLE
filter is checking all the product in a category

### ISSUE THREAD

**Issue by selvarajblr93** [bagisto/bagisto#1192]
This is checking all the product in a category, if in a case category has more products. 

Example :- if a category has 1000 product, filter will check all 1000 products in a for loop

_Originally posted by @selvarajblr93 in https://github.com/bagisto/bagisto/issues/1160#issuecomment-513213240_

**Comment by rahulshukla-webkul** [comment]
Hi @selvarajblr93 

We will reduce its query. Thanks for your concern.

**Comment by rahulshukla-webkul** [comment]
Hi @selvarajblr93 

We have removed for loop of products. Right Now, no matters how many number of products is in a category.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------------

Fixed
