### ISSUE TITLE
Most development packages are being used

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#1194]
The fact that the composer flag **"prefer-stable": true"** is not being used most if not all the packages being installed are development packages. For a stable solution stable packages should be used and development packages used when there are no alternatives.

Can you give a reason why the stable flag is not being used?

**Comment by prashant-webkul** [comment]
Thanks @emperorjm we will look into this matter deeply. And will shortly update the dependencies versions to minimum stable.
