### ISSUE TITLE
After signup on the frontend, the customer is still not the signup page.

### ISSUE THREAD

**Issue by webkul-shruti** [bagisto/bagisto#120]
After signup on the frontend, the customer is still on the signup page. Does not allow them to signup just shows a message success message.

![1](https://user-images.githubusercontent.com/39335353/48752948-cbf50880-ecb1-11e8-9b3d-7fd9b2dfa0d9.png)

**Comment by prashant-webkul** [comment]
The flow is changed by @rahulshukla-webkul and it will be there soon.

**Comment by Jyoti-Singh1** [comment]
Fixed
Framework Version: 0.1.2
