### ISSUE TITLE
no catergory as menu is showing

### ISSUE THREAD

**Issue by binoysarker** [bagisto/bagisto#1200]
I have installed bagisto according to this github instruction. But in the front end the menues are not showing up. Why?
![image](https://user-images.githubusercontent.com/26120595/61721010-9eed7e00-ad89-11e9-841a-add99b0a1e3b.png)

![image](https://user-images.githubusercontent.com/26120595/61721120-c8a6a500-ad89-11e9-81e2-b913d6900de5.png)

**Comment by rahulshukla-webkul** [comment]
Hi @binoysarker 

Kindly take pull from git & make sure that you were assign your category to channel's root category.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------------

Fixed
