### ISSUE TITLE
There is an  image issue while ordering any variant of configurable product.  

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1209]
Framework Version: 0.1.6

![Screenshot (91)](https://user-images.githubusercontent.com/52821836/61795730-b2f4b680-ae41-11e9-9cc9-cbe2f10346bd.png)

**Comment by bhanu-362** [comment]
![Screenshot (92)](https://user-images.githubusercontent.com/52821836/61795854-f2230780-ae41-11e9-926c-47135c45070f.png)

in cart it is showing exact image of variant but after proceeding further on final page it is showing image of main product

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6
-----------------------------------------
Fixed
![Screenshot from 2019-07-30 12-27-46](https://user-images.githubusercontent.com/45203177/62107575-84edf700-b2c5-11e9-90ce-d90023f0434f.png)
