### ISSUE TITLE
not retriving product name 047

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#1211]
on dashboard when clicking on out of stock products it redirects to edit product which does not retrieve some items of product like product name image and description and they should be entered  again to finish edit .

**Comment by rahulshukla-webkul** [comment]
Hi @farshadff 

When you create configurable product then its created with its variant with some of its field like name, price etc. Now this variant is showing on dashboard, so after clicking edit form is open & you need provide images & description for this variant because you do not provided yet.
