### ISSUE TITLE
Product Flat will not scale

### ISSUE THREAD

**Issue by caesarcxiv** [bagisto/bagisto#1212]
When using multiple channels product flat duplicates the product data for each channel regardless if the product is displayed on the channel or not.

1 channel could have 3 products and 1 with 100,000. Both channels will have 100,000 flat lines.

Solution:
Create solution to assign products to channels. Reference table when updating product flat.

**Comment by rahulshukla-webkul** [comment]
Hi @caesarcxiv 

Thanks for your precious suggestion. We will change it.

**Comment by rahulshukla-webkul** [comment]
Hi @caesarcxiv 

We have fixed it, Now product will create according to selected channels. Thank you.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6
-----------------------------------
Fixed

![Screenshot (75)](https://user-images.githubusercontent.com/45203177/62293021-49019000-b485-11e9-8457-4b3aa82f94b5.png)

**Comment by caesarcxiv** [comment]
Thanks for the quick turn-around. However a table needs added to keep track of what products are in which channels. Currently you have to re-select on every save and there is no way to easily hook into the database to validate products in channels.

**Comment by rahulshukla-webkul** [comment]
Hi @caesarcxiv 

'product_flat' table already consist channel column, so i think, we don't need any new table.
