### ISSUE TITLE
Getting exception on creating category.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1214]
- Framework Version: 0.1.6

------------------------------------------

![Screenshot from 2019-07-25 13-27-25](https://user-images.githubusercontent.com/45203177/61856751-64e2c000-aee0-11e9-8782-bb9d8e810ffc.png)

**Comment by rahulshukla-webkul** [comment]
run 'php artisan migrate' then check.

**Comment by jyoti-webkul** [comment]
Working fine
