### ISSUE TITLE
Seller information is not displayed in product detailed page

### ISSUE THREAD

**Issue by selvarajblr93** [bagisto/bagisto#1222]
Show seller information in product details page

![Capture23](https://user-images.githubusercontent.com/6057470/61993402-11f83c80-b089-11e9-885f-120c432ace2e.JPG)

**Comment by rahulshukla-webkul** [comment]
Hi @selvarajblr93 

Kindly create ticket for it at https://bagisto.uvdesk.com/en/customer/create-ticket/

Thanks
