### ISSUE TITLE
Integrate the system in existing project

### ISSUE THREAD

**Issue by microdesign** [bagisto/bagisto#1230]
I really enjoy your project but I just read all the docs and cant find a way to add it to existing project where i need e-commerce functionality.

Is there a way for this?

**Comment by rahulshukla-webkul** [comment]
Hi @microdesign 

Its a open source project & created in such a way that any one can easily customise it and can add their own functionality.

AS you see, we have created different package according to functionality. Same trick you can also use - https://bagisto.com/en/step-by-step-guide-for-bagisto-module-development/

If you need to override any of our model, then you can do it easily - https://devdocs.bagisto.com/override-core-model.html

You can create custom theme for front-end and can override view of both front end & back end to make it more attaractive - https://bagisto.com/en/create-custom-theme-in-bagisto/
https://forums.bagisto.com/topic/221/how-to-override-view-file-in-bagisto


Thanks

**Comment by microdesign** [comment]
I`m not sure how this answers my question. Other libraries have both create project with their lib and composer require only.

**Comment by prashant-webkul** [comment]
Hello @microdesign currently we do not support this type of architecture. As we do not support use Bagisto as composer dependency. But it would be better if you could integrate your existing system with Bagisto using its API resources for storefront. Or add some modules and make your own resources for your another system with which you wanna use.
