### ISSUE TITLE
Layered Navigation Filters

### ISSUE THREAD

**Issue by CarlJKashnier** [bagisto/bagisto#1231]
My company sells shoes and t-shirts. The problem is that the filter in navigation shows all sizes for example when I'm in shoes it will show XXL which is not a valid shoe size but is a size for t-shirts. We would really like to get this fixed so we can turn on additional filters and allow bagisto user's customers a better much improved shopping experience.

Simplely - Only show filterable options relevant for the results (including size and brand)

Thanks!

**Comment by ghermans** [comment]
You could create 2 attributes & attribute families
https://bagisto.com/en/bagisto-product-attribute-families/

**Comment by rahulshukla-webkul** [comment]
Hi @CarlJKashnier 

We have already fixed it. You can see -https://github.com/bagisto/bagisto/issues/1160

I think, your category consist both of this product that why filterable attribute of both products are showing & recommend you to take pull from master branch, may be you are using old one.

Thanks

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-------------------------------------------

Fixed
