### ISSUE TITLE
Give configuration for converting textarea to wysiwyg editor or not for browser compatibility

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1238]
- Framework Version: 0.1.6

**Comment by prashant-webkul** [comment]
Legit issue as it will speed down page load, when someone don't want wysiwyg editors.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Thanks**, now this enhancement **is done.** so I am **closing** this enhancement.
And I have attached a screenshot [Here](https://prnt.sc/v3OXNJ4NYuCI) for future reference.
