### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by enesk** [bagisto/bagisto#1241]
`Call to undefined method Illuminate\Events\Dispatcher::fire() (View: /Users/enes/Desktop/Sites/dorfsneaks/packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php) (View: /Users/enes/Desktop/Sites/dorfsneaks/packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php)`

I did "composer dump-autoload" and " php artisan vendor:publish"
Version 0.1.6

Edit:
Event::fire is deprecated since Laravel 5.4.
I changed all Event::fire methods to Event::dispatch but its not a good way i think, it should be fixed.

**Comment by rahulshukla-webkul** [comment]
Hi @enesk 

In versions prior to Laravel 5.7, this method classname was fire but with Laravel 5.8, it is now dispatch and I think you are using 5.8 that's why this error is showing.

Thanks
