### ISSUE TITLE
Currency symbol other than INR and USD are not displaying on print invoice.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1242]
- Framework Version: 0.1.6

---------------------------------------
![Screenshot from 2019-08-01 13-17-39](https://user-images.githubusercontent.com/45203177/62302061-5162c680-b497-11e9-9723-541736c8f15f.png)

**Comment by ghermans** [comment]
Why is this tagged as a low priority?

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6
-----------------------------------------
Fixed
![Screenshot from 2019-09-13 13-31-14](https://user-images.githubusercontent.com/45203177/64846657-cabf0e80-d62a-11e9-9219-9fe328c32eaa.png)
