### ISSUE TITLE
/categories and /products is horrible for SEO

### ISSUE THREAD

**Issue by elfeffe** [bagisto/bagisto#1244]
My personal opinion is that in the year 2019 is very bad to use that instead of some middleware that redirects to proper controller using /electronics or /iphone-6
Instead of /categories and /products.
I think none of the popular stores (Magento, WooCommerce, Prestashop, etc) uses that url structure.
Do you plan to change it?

**Comment by prashant-webkul** [comment]
We can surely make a provision for customization and u too can change that by creating new package that loads your own routes and suppress the exisiting routes in Bagisto. By creating new packages you can create new routes, new views and obviously your own controllers and other things.

**Comment by elfeffe** [comment]
I know we can customize it, but to have those urls is proper from an online shop of 2003.

**Comment by elfeffe** [comment]
I don't want to be rude, I just think if you plan to do a new e-commerce system, when we already have some leaders in the market, and you promote SEO features in your homepage, you should not commit those mistakes.
It is impossible to rank when your products have /products/ before

**Comment by prashant-webkul** [comment]
> I don't want to be rude, I just think if you plan to do a new e-commerce system, when we already have some leaders in the market, and you promote SEO features in your homepage, you should not commit those mistakes.
> It is impossible to rank when your products have /products/ before

Quite right as i told we will move this issue to *help wanted* and let some search engine optimisation view to flow in.

**Comment by jitendra-webkul** [comment]
Fixed in #1785
