### ISSUE TITLE
Admin should get notification when an order gets placed.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1245]
- Framework Version: 0.1.6

-------------------------------------------------------

**Comment by nguyen123** [comment]
error can not load list notifications in admin/notifications
1/ in image Capture1111.JPG : ajax get have data but not show on page.
2/ i tested in image Capture2.JPG, "await this.$http.get(this_this.url " : this code get list notifications but when load page completed then it process this function. this function need process before load page.

please check help me. thanks
![Capture1111](https://user-images.githubusercontent.com/11591574/188534194-091713cb-de39-45fd-b2e7-e7c8e29e9038.JPG)
![Capture2](https://user-images.githubusercontent.com/11591574/188534204-e1a9ec81-d9e2-4f81-adf2-451f3148ca22.JPG)
