### ISSUE TITLE
Implement a feature to import product through csv file.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1246]
- Framework Version: 0.1.6

**Comment by andrew-za** [comment]
Would definitely need this!

**Comment by prashant-webkul** [comment]
@andrew-za Currently this feature might get implemented soon after implementation of generating demo products randomly for demonstration purposes. Which is also under development right now as a command.

Thanks.

**Comment by andrew-za** [comment]
@prashant-webkul I would recommend making this a paid for extension. Bagisto can generate some money for their hard work.

**Comment by prashant-webkul** [comment]
@andrew-za We already have a store buddy: https://store.webkul.com/Bagisto.html or https://bagisto.com/en/extensions/

Still thanks though.

Have a nice day.

**Cheers!!!**
Webkul Team.

**Comment by IvalinV** [comment]
Hi, will it be implemented soon by any chances ?

**Comment by vaishaliwebkul** [comment]
Hi @IvalinV 
It's implemented now, you can download this package from here https://store.webkul.com/laravel-ecommerce-bulk-upload.html#

Thanks

**Comment by IvalinV** [comment]
Just what i need right now, thanks

**Comment by IvalinV** [comment]
Hi @vaishaliwebkul  the extension is great, but the "Live Demo" & "User Guide" links does not work.

**Comment by vaishaliwebkul** [comment]
HI @IvalinV 
currently, Live Demo & UserGuide links are not added yet, we will add these soon.
Till then you can download the extension and review.

**Comment by piersky** [comment]
A feature like this must be free if you want people migrate to bagisto. I'll pay for an importer plugin when this one give some extra interesting functions. Magento and prestashop has this feature for free.

**Comment by ghermans** [comment]
@piersky the extension is already available for free..
![bulk](https://user-images.githubusercontent.com/1594411/108599512-dc652380-7391-11eb-903f-1f79ccbd077b.PNG)
