### ISSUE TITLE
Delete button is not available for mass delete of Products in Product Grid.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#125]
Framework version- 0.1.1

Test Steps:
1.Click on Checkbox to select all available products.
![mass delete](https://user-images.githubusercontent.com/45203177/48823806-2fea0080-ed88-11e8-82ea-560f247945a4.png)

**Comment by prashant-webkul** [comment]
same as [https://github.com/bagisto/bagisto/issues/132](url)

**Comment by Jyoti-Singh1** [comment]
For now mass delete functionality is removed from Product Grid.Closing this issue but raising a separate issue(enhancement) to implement this functionality. Because mass delete functionality is an important feature of any e-commerce platform.
