### ISSUE TITLE
If payment is done through paypal then invoice should generate automatically and status of Order should be processing.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1258]
- Framework Version: 0.1.6

---------------------------------------------------

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------
Not fixed,still getting Pending invoice.
![Screenshot (55)](https://user-images.githubusercontent.com/45203177/64538074-9cdf7e80-d339-11e9-8419-0d57ddf147d4.png)
![Screenshot (56)](https://user-images.githubusercontent.com/45203177/64538089-a2d55f80-d339-11e9-9560-0d3e9cca6129.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Fixed

**Comment by vaishaliwebkul** [comment]
In master, the same issue exists

Framework - master

Invoice is not generated when payment is done using PayPal method

![Screenshot (30)](https://user-images.githubusercontent.com/43210406/77223226-846ddd80-6b80-11ea-9e3e-7d2709b751fb.png)

![Screenshot (31)](https://user-images.githubusercontent.com/43210406/77223218-76b85800-6b80-11ea-9170-68e1def6027a.png)

![Screenshot (29)](https://user-images.githubusercontent.com/43210406/77223341-a7e55800-6b81-11ea-9ab0-53c6927716f3.png)

**Comment by jyoti-webkul** [comment]
Hi@ vaishali
It works fine on live, please check on that.

**Comment by vaishaliwebkul** [comment]
fixed
