### ISSUE TITLE
Not getting the email from the account that has been setup in env.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1261]
- Framework Version: 0.1.6

----------------------------------------------

![Screenshot(9)](https://user-images.githubusercontent.com/45203177/62546184-aa0fd600-b880-11e9-97a8-57428a33e0a3.png)
![Screenshot(8)](https://user-images.githubusercontent.com/45203177/62546214-b3993e00-b880-11e9-8bd1-fb0c7da8dbea.png)

**Comment by prashant-webkul** [comment]
Fixed it in my commit https://github.com/prashant-webkul/bagisto/commit/fbedc8a161547aa01ddff0680429dd29bc3984be wait till my merge in master.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

---------------------------------------------

Fixed
