### ISSUE TITLE
If multiple locale is created and only one locale is selected at a time from back-end then on frontend shop is not getting translated according to locale.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1262]
- Framework Version: 0.1.6

------------------------------------------------
![Screenshot (85)](https://user-images.githubusercontent.com/45203177/62546733-aa5ca100-b881-11e9-94b1-87ae2dfdf709.png)
![Screenshot (84)](https://user-images.githubusercontent.com/45203177/62546746-b0528200-b881-11e9-8c3d-b71d788d5485.png)

**Comment by rahulshukla-webkul** [comment]
Hi @jyoti-webkul 

Locales is basically a field which holds the supportive locales for channel and Default locale is kind of locale which will be show when user firm time open that. They are two different things.

**Comment by jyoti-webkul** [comment]
Ok
