### ISSUE TITLE
All strings are not translated in arabic language.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1265]
- Framework Version: 0.1.6

--------------------------------------------
![Screenshot (87)](https://user-images.githubusercontent.com/45203177/62599551-239fd680-b90a-11e9-94e3-8ae1bbed516a.png)
![Screenshot (88)](https://user-images.githubusercontent.com/45203177/62599558-2ac6e480-b90a-11e9-932f-011133f553af.png)
![Screenshot (89)](https://user-images.githubusercontent.com/45203177/62599562-30242f00-b90a-11e9-87cd-29f62d0d8492.png)
![Screenshot (90)](https://user-images.githubusercontent.com/45203177/62599578-374b3d00-b90a-11e9-9d8a-b120dd2c47bf.png)
![Screenshot (91)](https://user-images.githubusercontent.com/45203177/62599586-3e724b00-b90a-11e9-82e0-86882b00efb8.png)
![Screenshot (92)](https://user-images.githubusercontent.com/45203177/62599595-4500c280-b90a-11e9-989b-6bbdaa4a63f5.png)
![Screenshot (93)](https://user-images.githubusercontent.com/45203177/62599612-4e8a2a80-b90a-11e9-864b-2eaae3eccc64.png)
![Screenshot (94)](https://user-images.githubusercontent.com/45203177/62599624-58139280-b90a-11e9-9f64-1f6fc5711e70.png)
![Screenshot (95)](https://user-images.githubusercontent.com/45203177/62599635-619cfa80-b90a-11e9-965c-c83a4d7ed230.png)
![Screenshot (96)](https://user-images.githubusercontent.com/45203177/62599643-695c9f00-b90a-11e9-81f8-bbb08ee09742.png)
![Screenshot (97)](https://user-images.githubusercontent.com/45203177/62599654-6feb1680-b90a-11e9-913d-f80d63b04b9f.png)
![Screenshot (98)](https://user-images.githubusercontent.com/45203177/62599666-78435180-b90a-11e9-9dcf-46245b921195.png)
![Screenshot (99)](https://user-images.githubusercontent.com/45203177/62599682-809b8c80-b90a-11e9-978b-978d6821b98d.png)
![Screenshot(10)](https://user-images.githubusercontent.com/45203177/62600478-99a53d00-b90c-11e9-9286-efa58bf10275.png)
![Screenshot(11)](https://user-images.githubusercontent.com/45203177/62600487-a0cc4b00-b90c-11e9-8849-8db90293028c.png)
![Screenshot(12)](https://user-images.githubusercontent.com/45203177/62600527-c2c5cd80-b90c-11e9-93bf-1c6ec658e589.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
closing this as the reported translated are already done.
