### ISSUE TITLE
Extending shop view resulting into broken CSS path

### ISSUE THREAD

**Issue by tushargugnani** [bagisto/bagisto#1266]
I created a new package inside packages folder and trying to extend the shop layout for it's view file. (@extends('shop::layouts.master') )
View file works fine but the assets are not getting loaded because of the path issue. This is what I am getting in the console

```
GET http://localhost:8008/css/shop.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost:8008/images/logo.svg 404 (Not Found)
GET http://localhost:8008/js/shop.js net::ERR_ABORTED 404 (Not Found)
ui.js:1 Uncaught ReferenceError: Vue is not defined
```

**Comment by rahulshukla-webkul** [comment]
Hi @tushargugnani 

Kindly Make sure that your view's route file are passing through theme middleware.

**Comment by tushargugnani** [comment]
@rahulshukla-webkul Thanks for the prompt reply. This is how my route definition looks like.

```
Route::get('addresses/create', 'MyPackage\Customer\Http\Controllers\AddressController@create')->defaults('_config', [
     'view' => 'customer::customer.account.address.create'
])->name('customer.address.create');
```

Where can I exactly have my middleware defined?

**Comment by rahulshukla-webkul** [comment]
Hi @tushargugnani 

`Route::group(['middleware' => ['web', 'theme', 'locale', 'currency']], function () {
    Route::get('addresses/create', 'MyPackage\Customer\Http\Controllers\AddressController@create')->defaults('_config', [
	 'view' => 'customer::customer.account.address.create'
    ])->name('customer.address.create');
});`

Thanks

**Comment by tushargugnani** [comment]
@rahulshukla-webkul Thanks, It works now. It was an overlook on my part. Thanks again.
