### ISSUE TITLE
Update the heading "Title" to "Sliders".

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1268]
- Framework Version: 0.1.6

-------------------------------------------
![Screenshot(13)](https://user-images.githubusercontent.com/45203177/62686507-819fed00-b9e2-11e9-8627-a93c8dd9aa39.png)

**Comment by prashant-webkul** [comment]
Fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-------------------------------------------
Fixed
![Screenshot (70)](https://user-images.githubusercontent.com/45203177/63432291-8df26400-c43e-11e9-8dec-44e4ecb29d5e.png)
