### ISSUE TITLE
Add asterisk symbol for image field of slider.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1269]
- Framework Version: 0.1.6

-------------------------------------------
![Screenshot(14)](https://user-images.githubusercontent.com/45203177/62690734-de9fa100-b9ea-11e9-8e44-18367e123580.png)

**Comment by prashant-webkul** [comment]
Fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------------
Fixed

![Screenshot (69)](https://user-images.githubusercontent.com/45203177/63432200-571c4e00-c43e-11e9-9648-9dd620f7476f.png)
