### ISSUE TITLE
Unable to filter product if first product is filtered according to status then according to product id.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1270]
- Framework Version: 0.1.6

----------------------------------------------------
![Screenshot(15)](https://user-images.githubusercontent.com/45203177/62697653-c9317380-b9f8-11e9-9479-d4c6f3112d8e.png)
![Screenshot(16)](https://user-images.githubusercontent.com/45203177/62697660-d0588180-b9f8-11e9-8cce-2246a729db13.png)
![Screenshot(20)](https://user-images.githubusercontent.com/45203177/62697684-dea69d80-b9f8-11e9-8034-72f09de11037.png)

**Comment by bhanu-webkul** [comment]
Framework version: 0.1.8
issue fixed
