### ISSUE TITLE
Filter conditions need to be according to numeric for Rate column in Tax Rates

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1275]
![Screenshot from 2019-08-12 11-05-59](https://user-images.githubusercontent.com/52821836/62847550-828f9200-bcf4-11e9-8450-d2e351c43610.png)

**Comment by prashant-webkul** [comment]
Fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------
Fixed
![Screenshot from 2019-09-07 12-58-24](https://user-images.githubusercontent.com/45203177/64471424-3ad31d80-d16f-11e9-9538-b597dfeca2da.png)
