### ISSUE TITLE
Not able to select category in promotion.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1276]
- Framework Version: 0.1.6

------------------------------------------------

![Screenshot](https://user-images.githubusercontent.com/45203177/62861338-c5675f00-bd20-11e9-9602-4840e5f5b852.png)

**Comment by prashant-webkul** [comment]
Fixed.
Since branch was in development mode. In that case assets needed to be compiled manually.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------------

Fixed
