### ISSUE TITLE
Getting exception on creating cart rules.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1277]
- Framework Version: 0.1.6

----------------------------------------

![Screenshot from 2019-08-12 17-10-33](https://user-images.githubusercontent.com/45203177/62862787-876c3a00-bd24-11e9-8714-9055521bcdb7.png)

**Comment by prashant-webkul** [comment]
Fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Fixed
