### ISSUE TITLE
Translation issue in promotion.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1278]
- Framework Version: 0.1.6

---------------------------------------------------
![Screenshot(1)](https://user-images.githubusercontent.com/45203177/62863729-4e819480-bd27-11e9-895c-4501dce68071.png)
![Screenshot(4)](https://user-images.githubusercontent.com/45203177/62863802-82f55080-bd27-11e9-8800-a82e71b8c9d4.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

-----------------------------------------

Fixed

![Screenshot from 2019-10-14 13-04-47](https://user-images.githubusercontent.com/45203177/66735176-465ae800-ee83-11e9-9c98-8c94d4c717c5.png)

**Comment by bhanu-webkul** [comment]
Framework version v 0.1.8

getting same issue  while selecting condition for those columns where we need to enter value when trying to edit cart rule 

![Screenshot from 2019-11-13 11-55-35](https://user-images.githubusercontent.com/52821836/68738664-e899f700-060c-11ea-9a64-f9ab2e7b173b.png)

**Comment by bhanu-webkul** [comment]
fixed in new cart rule
