### ISSUE TITLE
Calender icon should also be clickable,and on click calender should display.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#128]
Framework Version:0.1.1

![calender](https://user-images.githubusercontent.com/45203177/48825017-18147b80-ed8c-11e8-9840-36eb95630dd3.png)

**Comment by rahulshukla-webkul** [comment]
Turned calendar icon to clickable & after click calendar will display.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
