### ISSUE TITLE
UI issue on cart-rule page and product page.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1285]
- Framework Version: 0.1.6

----------------------------------------

![Screenshot (13)](https://user-images.githubusercontent.com/45203177/62923244-f7cd9680-bdca-11e9-80ea-e009cbd25164.png)
![Screenshot (14)](https://user-images.githubusercontent.com/45203177/62923251-fd2ae100-bdca-11e9-8577-648885cf8160.png)

**Comment by prashant-webkul** [comment]
Fixed this issue system wide.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6
---------------------------------------------

Fixed the complete header ,header should not scroll on scrolling the page.
![Screenshot (68)](https://user-images.githubusercontent.com/45203177/63430595-95177300-c43a-11e9-8d68-2353f2861c30.png)
