### ISSUE TITLE
Incorrect discount is showing in cart.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1286]
Framework Version: 0.1.6

---------------------------------------
- Do not add any condition.
- Apply action as fixed amount of 10.
- Add 2 products in cart, it will show discount of rs 10
- Remove any one product from cart, now it will show discount amount as 5.

![Screenshot from 2019-08-13 15-15-09](https://user-images.githubusercontent.com/45203177/62932129-32402f00-bddd-11e9-9ccb-6d9311e5bfe4.png)
![Screenshot from 2019-08-13 15-15-18](https://user-images.githubusercontent.com/45203177/62932143-38cea680-bddd-11e9-818d-62f47ed0ad52.png)

**Comment by prashant-webkul** [comment]
ACK, will apply recalculation provision for these kind of situations.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------------

Fixed
