### ISSUE TITLE
Those attributes are not displaying in select option while creating cart rule whose attribute name are not written for en locale.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1287]
- Framework Version: 0.1.6

--------------------------------------

![Screenshot from 2019-08-13 15-51-56](https://user-images.githubusercontent.com/45203177/62940309-e7c8ad80-bdf0-11e9-8910-90102e2d92d4.png)

**Comment by prashant-webkul** [comment]
Fixed, wait till next merge.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

----------------------------------------------
Fixed

![Screenshot from 2019-08-21 11-56-55](https://user-images.githubusercontent.com/45203177/63407731-e4de4600-c40a-11e9-8b86-9e0feb200fd2.png)
