### ISSUE TITLE
Getting issue when deleting orders.Mass action is not working in any grid(Getting Internal server error) while updating status.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#129]
Framework Version: 0.1.1

Test Condition: No order should be available in Order Grid.
Test Steps:
1.Click on checkbox that is available for mass selection and click on delete.
![select](https://user-images.githubusercontent.com/45203177/48825683-295e8780-ed8e-11e8-9ea9-1c0003fa51af.png)
![delete1](https://user-images.githubusercontent.com/45203177/48825689-2d8aa500-ed8e-11e8-929e-f30534c04fbe.png)

**Comment by prashant-webkul** [comment]
For now the deletion of order is disabled but this might get changed in near future. As we get more response and feedback from our users who will be using this framework whether to delete orders or not.

**Comment by Jyoti-Singh1** [comment]
Fixed. Mass deletion is removed from Order Grid because it is not required in Order Grid.
Framework Version: 0.1.2
