### ISSUE TITLE
After opening a cms page if clicking again on cms link then getting 404 and redirect to admin cms page.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1291]
- Framework Version: 0.1.6

-------------------------------------------------

![Screenshot from 2019-08-14 12-58-41](https://user-images.githubusercontent.com/45203177/63002489-a1785a80-be93-11e9-8e61-232a6f8f6dae.png)

**Comment by prashant-webkul** [comment]
use code @php echo route('shop.cms.page', 'about-us') @endphp as the redirect value.

*For example:*
```
<a href="@php echo route('shop.cms.page', 'about-us') @endphp">About Us</a>
```

**Comment by rockgold22** [comment]
<a href="@php echo route('shop.cms.page', 'about-us') @endphp">About Us</a> This is not working
![image1](https://user-images.githubusercontent.com/16397436/93016819-8e2d4680-f5e1-11ea-84e3-0ac49cebbded.png)
![image2](https://user-images.githubusercontent.com/16397436/93016825-92f1fa80-f5e1-11ea-8d97-b5cbca389b89.png)
I can't find a solution and you have mentioned it as a bug fixed.

**Comment by bhanu-webkul** [comment]
@rockgold22 
Could you please confirm Bagisto version

**Comment by rockgold22** [comment]
> @rockgold22
> Could you please confirm the Bagisto version

@bhanu-webkul : version 1.2.0

**Comment by rockgold22** [comment]
I have installed bagisto using composer, can you please provide me the guidelines to upgrade the latest bagisto, so that i can have bug fixes in my new version.

**Comment by rockgold22** [comment]
Hi @bhanu-webkul  Any update on this ? Let me know this if this already has been resolved how can i find the fix, i am stuck.

**Comment by vaishaliwebkul** [comment]
@rockgold22 
You may easily upgrade your Bagisto version. check this doc https://devdocs.bagisto.com/upgrade_to_latest_bagisto.html

In the new version, we have done some update in cms page for velocity theme https://github.com/bagisto/bagisto/issues/3811
so kindly upgrade your version then add your cms page URL key inside velocity-> meta data -> footer middle content( by clicking on source code icon) .

**Comment by rockgold22** [comment]
I have tried to follow the link provided above [https://prnt.sc/ui69u3]((https://prnt.sc/ui69u3)) but in vain, for your reference kindly, check the screenshot provided here.
it is showing a 404 error. See my second image.
How is this working and how is this marked as a fix, I am not understanding it?
![issue2](https://user-images.githubusercontent.com/16397436/93665490-81eb3280-fa94-11ea-8447-23cb0b0b1834.png)

![issue](https://user-images.githubusercontent.com/16397436/93665408-de018700-fa93-11ea-9171-7fd2910b7e74.png)

**Comment by vaishaliwebkul** [comment]
@rockgold22 
either install the fresh latest bagisto to see the changes or you could run the below commands to set the default cms-page URL key into your existing project( make sure it should be bagisto 1.2.0)
**php artisan db:seed**

**Comment by rahulanand77** [comment]
Hi @vaishaliwebkul ,

are you really sure about this command? I executed this command and guess what, I lost my admin users and it dumped my DB with "admin@example.com" and wiped out my admin. All my categories are gone. I can see default category only. I have no idea what other details are gone after running this command. 

Why don't you guys test it before publically speaking?

is there anyone really experienced in Webkul to sort out public issues instead of such short way solutions, which are not even tested internally in Webkul? Is there any composer command to upgrade bagisto without losing our data? On the live websites, we can't afford such mistake.

**Comment by rockgold22** [comment]
> either install the fresh latest bagisto to see the changes or you could run the below commands to set the default cms-page URL key into your existing project( make sure it should be bagisto 1.2.0)

I already have 1.2.0 what else do i need to install, if any new update was there it must have been there any update. Still waiting @prashant-webkul @vaishaliwebkul @jyoti-webkul
