### ISSUE TITLE
Getting exception on changing the locale from cms page.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1295]
- Framework Version: 0.1.6

----------------------------------------------

![Screenshot from 2019-08-14 13-32-53](https://user-images.githubusercontent.com/45203177/63004508-2c5b5400-be98-11e9-9e9d-5cdc5e70184f.png)

**Comment by bhanu-webkul** [comment]
issue fixed

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-------------------------------------
Fixed
