### ISSUE TITLE
Before saving the page user should be able to preview.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1299]
- Framework Version: 0.1.6

----------------------------------------

**Comment by prashant-webkul** [comment]
No, this is not a right flow to preview the page as it will force creating an entry in database.

**Comment by prashant-webkul** [comment]
@jyoti-webkul  Please close the issue, as the preview functionality is already implemented for that you need to edit a page.
At the time of creation multiple pages are created according to locales and channels selected.
