### ISSUE TITLE
Getting exception on checkout.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1301]
- Framework Version: 0.1.6

-----------------------------------------------

![Screenshot from 2019-08-14 17-47-09](https://user-images.githubusercontent.com/45203177/63020408-ad781280-bebb-11e9-9647-5a5d7c9b21f1.png)

**Comment by prashant-webkul** [comment]
Fixed wait till next merge.

**Comment by bhanu-webkul** [comment]
issue fixed
