### ISSUE TITLE
Show Price Filter from min to max

### ISSUE THREAD

**Issue by selvarajblr93** [bagisto/bagisto#1302]
Suggestion

![price](https://user-images.githubusercontent.com/6057470/63022453-9851b280-bec0-11e9-8810-43e92abf1ed6.png)

**Comment by rahulshukla-webkul** [comment]
Hi @selvarajblr93 

We have changed it. Now you can select filterable attribute for category.If you don't have any filterable attribute in category then according to category product filter attribute will be appear.
Try to take pull from master branch.

Thanks

**Comment by selvarajblr93** [comment]
> Hi @selvarajblr93
> 
> We have changed it. Now you can select filterable attribute for category.If you don't have any filterable attribute in category then according to category product filter attribute will be appear.
> Try to take pull from master branch.
> 
> Thanks

Actually i am not saying about functional category pricing. I am talking about UI by default the dragging start and end point is showing 0 -0, please show the pointer from min to max value like the 2nd one in the above picture.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

------------------------------------------

Fixed

![Screenshot (60)](https://user-images.githubusercontent.com/45203177/64606571-28ade500-d3e4-11e9-8d1e-5f22309720dd.png)
