### ISSUE TITLE
Error pages views redirected to Admin error pages

### ISSUE THREAD

**Issue by yxuko** [bagisto/bagisto#1303]
Hey,

I noticed that in
> packages/Webkul/Admin/src/Exceptions/Handler.php

        $path = $this->isAdminUri() ? 'admin' : 'shop';
was changed to
>
        $path = 'admin';

This caused error pages in Shop part to show error pages of Admin and possible source for issue #1300 

![Opera Instantané_2019-08-15_184949_bagisto](https://user-images.githubusercontent.com/1786317/63114860-38c5d680-bf96-11e9-95d9-f5b9aff34979.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

-------------------------------------------

Fixed
