### ISSUE TITLE
Show min and max value in price filter according to selected category.  

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1304]
As of now,  min and max value is visible according to whole products, due to that in case in any category max price of item is $50 and max price of item from whole product is $1000, then if customer is looking products in that specific category then also 0-$1000 is visible in price filter. 
hence 

![Screenshot - 2019-08-16T170229 636](https://user-images.githubusercontent.com/52821836/63165193-53588800-c048-11e9-864b-acf747bbd187.png)

**Comment by rahulshukla-webkul** [comment]
Hi @bhanu-webkul 

This is not an issue.
