### ISSUE TITLE
Unable to create exchange rates in latest master

### ISSUE THREAD

**Issue by prashant-webkul** [bagisto/bagisto#1305]
![exchangerateerror](https://user-images.githubusercontent.com/41140572/63167067-d203f400-c04d-11e9-988c-026a0eab1e3b.png)

**Comment by prashant-webkul** [comment]
Fixed this issue in PR #1307

**Comment by bhanu-webkul** [comment]
Issue fixed 

![Screenshot - 2019-08-16T180615 783](https://user-images.githubusercontent.com/52821836/63168014-93bc0400-c050-11e9-8af4-f745f127480f.png)
