### ISSUE TITLE
Wrong column name is coming in CMS page 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1308]
![Screenshot - 2019-08-16T183507 883](https://user-images.githubusercontent.com/52821836/63169503-9882b700-c054-11e9-9127-29d1d2b622ee.png)

**Comment by prashant-webkul** [comment]
Fixed this issue in PR #1310

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

------------------------------------------

Fixed

![Screenshot (22)](https://user-images.githubusercontent.com/45203177/63244341-be89a080-c27a-11e9-85e6-cdcd7fbc8ac6.png)
