### ISSUE TITLE
Change the filter conditions for locale and channel column in cms page 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1311]
![Screenshot from 2019-08-16 18-55-05](https://user-images.githubusercontent.com/52821836/63170688-763e6880-c057-11e9-817a-4fd636572fa6.png)

![Screenshot from 2019-08-16 18-54-59](https://user-images.githubusercontent.com/52821836/63170693-7b031c80-c057-11e9-822d-c8ba49ddbca8.png)

**Comment by prashant-webkul** [comment]
Invalid issue.

**Comment by bhanu-webkul** [comment]
Every where for locale and channel we have used string conditions. 

![Screenshot from 2019-08-16 19-05-04](https://user-images.githubusercontent.com/52821836/63171307-f0bbb800-c058-11e9-98bf-062c949bb671.png)
![Screenshot from 2019-08-16 19-04-48](https://user-images.githubusercontent.com/52821836/63171328-fdd8a700-c058-11e9-80cc-6fbed01df248.png)

For any one it would be easy to remember locale or channel by their names than their id.
