### ISSUE TITLE
Getting exception when creating cms page by selecting multiple channels or multiple locale

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1312]
- Framework Version: 0.1.6

-----------------------------------------

![Screenshot from 2019-08-19 11-18-25](https://user-images.githubusercontent.com/45203177/63242000-5d120380-c273-11e9-879b-a03153f51b07.png)

**Comment by prashant-webkul** [comment]
Ok, this will get fixed in my next PR. It is the last edge case which needs manual validation for URL keys.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------
Fixed

![Screenshot (59)](https://user-images.githubusercontent.com/45203177/63413092-a3ec2e80-c416-11e9-8c16-aa03875f5eb4.png)
