### ISSUE TITLE
Getting exception when click on Apply Rules.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1317]
- Framework Version: 0.1.6

-----------------------------------------

![Screenshot (34)](https://user-images.githubusercontent.com/45203177/63321461-72079900-c33e-11e9-9418-92571d0dcd5f.png)
![Screenshot from 2019-08-20 11-32-51](https://user-images.githubusercontent.com/45203177/63321468-78961080-c33e-11e9-94b1-37af3f9dda67.png)

**Comment by prashant-webkul** [comment]
Resolved in PR #1318

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Fixed
