### ISSUE TITLE
Catalog rule is not working according to selected attributes, if category is not selected.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1320]
- Framework Version: 0.1.6

----------------------------------------------

**Comment by lYesterdaYl** [comment]
Hi, has this bug been fixed in version 0.1.7? I am still have this issue. The discount does not work select or not select the category. Try using attribute SKU = 'product id' or SKU = 'product name'. Not working for me.

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
