### ISSUE TITLE
No further dropdown fields appear after selecting Starts From and Ends Till .

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1321]
- Framework Version: 0.1.6

-----------------------------------------

![Screenshot (36)](https://user-images.githubusercontent.com/45203177/63338948-72fdf200-c361-11e9-945e-dde2a0584b0e.png)

**Comment by prashant-webkul** [comment]
Fixed

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------

Fixed

![Screenshot from 2019-08-21 12-05-34](https://user-images.githubusercontent.com/45203177/63411470-3c80af80-c413-11e9-8333-fece504d2652.png)
