### ISSUE TITLE
Update the button title "Edit" to "Save".

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1323]
- Framework Version: 0.1.6

--------------------------------------------
![Screenshot (39)](https://user-images.githubusercontent.com/45203177/63339876-78f4d280-c363-11e9-9080-3b9f29120479.png)

**Comment by prashant-webkul** [comment]
Done.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

------------------------------------------
Fixed

![Screenshot (48)](https://user-images.githubusercontent.com/45203177/63408727-515a4480-c40d-11e9-9629-a3766fe417e3.png)
