### ISSUE TITLE
Not able to edit the catalog rule if Categories is not selected in Conditions.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1324]
- Framework Version: 0.1.6

-------------------------------------------------

![Screenshot (41)](https://user-images.githubusercontent.com/45203177/63340213-20720500-c364-11e9-9d08-6c7358effc09.png)
![Screenshot from 2019-08-20 16-02-17](https://user-images.githubusercontent.com/45203177/63340225-2667e600-c364-11e9-95b4-21fcc9cdb446.png)

**Comment by prashant-webkul** [comment]
Fixed

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

------------------------------------------
Fixed
