### ISSUE TITLE
Remove asterisk symbol from Start and End.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1325]
- Framework Version: 0.1.6

--------------------------------------------

![Screenshot (40)](https://user-images.githubusercontent.com/45203177/63340296-51ead080-c364-11e9-9ab6-66dc77c2f589.png)

**Comment by prashant-webkul** [comment]
Fixed

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

---------------------------------------
Fixed

![Screenshot (57)](https://user-images.githubusercontent.com/45203177/63411853-10196300-c414-11e9-942e-99974cfccf41.png)
