### ISSUE TITLE
Search for Catalog rule is not working.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1326]
- Framework Version: 0.1.6

-------------------------------------------

![Screenshot (42)](https://user-images.githubusercontent.com/45203177/63340627-29170b00-c365-11e9-94f3-f15d04a74a68.png)

**Comment by prashant-webkul** [comment]
Fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------
Fixed

![Screenshot (58)](https://user-images.githubusercontent.com/45203177/63412471-7357c500-c415-11e9-96b1-bf4dae5c73ad.png)
