### ISSUE TITLE
Getting exception on creating customer from admin end if smtp is not configured in env.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1327]
- Framework Version: 0.1.6

------------------------------------------
![Screenshot from 2019-08-20 16-23-24](https://user-images.githubusercontent.com/45203177/63342650-a6dd1580-c369-11e9-8042-6bd1f4bdba1a.png)

**Comment by prashant-webkul** [comment]
Silly issue though, it is advised to configure mail settings prior to using the instance as multiple flows depends on communicating through receiving emails.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------------

Fixed
