### ISSUE TITLE
Description field of catalog field should not be required.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1328]
- Framework Version: 0.1.6

-----------------------------------------------
![Screenshot (43)](https://user-images.githubusercontent.com/45203177/63345053-7a2bfc80-c36f-11e9-88fe-300611ddda09.png)

**Comment by prashant-webkul** [comment]
Provision done in PR #1322

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Asterisk symbol has been added

![Screenshot (44)](https://user-images.githubusercontent.com/45203177/64472790-39125580-d181-11e9-93ef-ef01e951f247.png)
