### ISSUE TITLE
Layout issue on Edit Category page.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1331]
- Framework Version: 0.1.6

------------------------------------

![Screenshot (60)](https://user-images.githubusercontent.com/45203177/63413365-34c30a00-c417-11e9-91c9-3d47a8fd83c2.png)

**Comment by prashant-webkul** [comment]
Fixed issue in PR #1332

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

------------------------------------------
Fixed

![Screenshot (65)](https://user-images.githubusercontent.com/45203177/63426470-87f58680-c430-11e9-995b-a3a86ad6875a.png)
