### ISSUE TITLE
Unable to login with the user account that is created in user grid with custom access.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#134]
Framework Version: 0.1.1
 Test Steps:
1. Create a user role with permission of Dashboard and Catalog.
2. Now create a user and assign this role to the user.
3. Now try to login with the created user.

**Comment by prashant-webkul** [comment]
Wait till next release to see the result.

**Comment by Jyoti-Singh1** [comment]
Fixed
Framework Version: 0.1.2
