### ISSUE TITLE
Target [Webkul\CMS\Contracts\CMS] is not instantiable 

### ISSUE THREAD

**Issue by laravelian** [bagisto/bagisto#1344]
Fresh install. In admin panel, when clicking 'CMS', getting: 
Target [Webkul\CMS\Contracts\CMS] is not instantiable while building [Webkul\CMS\Http\Controllers\Admin\PageController].

Illuminate\Contracts\Container\BindingResolutionException thrown with message "Target [Webkul\CMS\Contracts\CMS] is not instantiable while building [Webkul\CMS\Http\Controllers\Admin\PageController]."

Stacktrace:
#44 Illuminate\Contracts\Container\BindingResolutionException in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:933
#43 Illuminate\Container\Container:notInstantiable in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
#42 Illuminate\Container\Container:build in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:646
#41 Illuminate\Container\Container:resolve in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:601
#40 Illuminate\Container\Container:make in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:734
#39 Illuminate\Foundation\Application:make in /home/vagrant/Dev/ledgrowlights/vendor/prettus/l5-repository/src/Prettus/Repository/Eloquent/BaseRepository.php:177
#38 Prettus\Repository\Eloquent\BaseRepository:makeModel in /home/vagrant/Dev/ledgrowlights/vendor/prettus/l5-repository/src/Prettus/Repository/Eloquent/BaseRepository.php:93
#37 Prettus\Repository\Eloquent\BaseRepository:__construct in /home/vagrant/Dev/ledgrowlights/packages/Webkul/CMS/src/Repositories/CMSRepository.php:35
#36 Webkul\CMS\Repositories\CMSRepository:__construct in [internal]:0
#35 ReflectionClass:newInstanceArgs in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:800
#34 Illuminate\Container\Container:build in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:646
#33 Illuminate\Container\Container:resolve in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:601
#32 Illuminate\Container\Container:make in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:734
#31 Illuminate\Foundation\Application:make in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:900
#30 Illuminate\Container\Container:resolveClass in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:828
#29 Illuminate\Container\Container:resolveDependencies in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:795
#28 Illuminate\Container\Container:build in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:646
#27 Illuminate\Container\Container:resolve in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Container/Container.php:601
#26 Illuminate\Container\Container:make in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:734
#25 Illuminate\Foundation\Application:make in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Route.php:226
#24 Illuminate\Routing\Route:getController in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Route.php:796
#23 Illuminate\Routing\Route:controllerMiddleware in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Route.php:757
#22 Illuminate\Routing\Route:gatherMiddleware in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Router.php:678
#21 Illuminate\Routing\Router:gatherRouteMiddleware in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
#20 Illuminate\Routing\Router:runRouteWithinStack in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Router.php:642
#19 Illuminate\Routing\Router:runRoute in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Router.php:608
#18 Illuminate\Routing\Router:dispatchToRoute in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Router.php:597
#17 Illuminate\Routing\Router:dispatch in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#16 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#14 Illuminate\Session\Middleware\StartSession:handle in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#11 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#8 Illuminate\Cookie\Middleware\EncryptCookies:handle in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#2 Illuminate\Pipeline\Pipeline:then in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /home/vagrant/Dev/ledgrowlights/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /home/vagrant/Dev/ledgrowlights/public/index.php:74

**Comment by prashant-webkul** [comment]
@laravelian Kindle check if this line is added in your config/concord.php file:
*\Webkul\CMS\Providers\ModuleServiceProvider::class*

**Comment by prashant-webkul** [comment]
@laravelian Please download the latest master there had been some issue with Github while downloading latest master.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------------

Fixed
