### ISSUE TITLE
Updating a product price sets product price in cart to $0

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#1347]
Updating a product price sets the price to $0 if it was already added to a customer's cart.

**Comment by rahulshukla-webkul** [comment]
Hi @emperorjm 

Can you tell me which version of bagisto you are using.

**Comment by prashant-webkul** [comment]
@emperorjm The possible chances of getting this bug is that you are using v0.1.3 or v0.1.2. Please upgrade to higher version by downloading the master branch, its stable.

**Comment by emperorjm** [comment]
I am using version 0.1.6. I had installed 0.1.5 initially and upgraded to 0.1.6. I am still having this issue. A customer just made an order and some of the products have $0 prices and when checked those products do have their correct prices.

**Comment by bhanu-webkul** [comment]
Framework version 0.1.8

issue fixed
