### ISSUE TITLE
Showing incorrect grandtotal in invoice section of admin, if order is placed in currency other than base currency.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1348]
- Framework Version: 0.1.6

------------------------------------------------

![Screenshot (78)](https://user-images.githubusercontent.com/45203177/63576642-3d981500-c5aa-11e9-82b4-7280c3c2c87f.png)
![Screenshot (81)](https://user-images.githubusercontent.com/45203177/63576704-615b5b00-c5aa-11e9-93bb-6bf4113256ff.png)

**Comment by prashant-webkul** [comment]
Fixed this issue in PR #1345 wait till merge.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------

Fixed
