### ISSUE TITLE
symfony component console exception commandnotfoundexception command "artisan" is not defined

### ISSUE THREAD

**Issue by gydachandra** [bagisto/bagisto#1353]
When i installed bagisto on android localhost, when i installed the bagisto and run 'php artisan migrate'. there's an error "symfony component console exception commandnotfoundexception command "artisan" is not defined".

How to fix it?

Thank you

**Comment by prashant-webkul** [comment]
@gydachandra Most command answer would be that you haven't performed the command *composer install* or *composer create-project* from your project's root.

**Comment by gydachandra** [comment]
> @gydachandra Most command answer would be that you haven't performed the command _composer install_ or _composer create-project_ from your project's root.

I've been installed 'composer install' and the result was package manifest generated successfully but when i try 'php composer.phar artisan migrate', there's still notification "artisan" is not defined.

**Comment by prashant-webkul** [comment]
*php composer.phar artisan migrate* -> use this -> *php artisan migrate*

**Comment by gydachandra** [comment]
there's an error when using _php artisan migrate_ "Illuminate/Database/QueryException:SQLSTATE[HY000] .....

**Comment by prashant-webkul** [comment]
> there's an error when using _php artisan migrate_ "Illuminate/Database/QueryException:SQLSTATE[HY000] .....

Please attach a screenshot so we can see the whole error.

**Comment by gydachandra** [comment]
Here's the screenshot 
[http://ge.tt/68mQlix2](url)

**Comment by gydachandra** [comment]
Here's the screenshot http://ge.tt/68mQlix2

**Comment by prashant-webkul** [comment]
> Here's the screenshot
> [http://ge.tt/68mQlix2](url)

This issue seems with your stack installed locally on your system. Your Bagisto instance cannot connect to your database might be your credentials are wrong.

**Comment by gydachandra** [comment]
I've already checked my credentials, dbname, pass, host, servername are already the same with database and in file '. env'. Am I missing the step?

**Comment by prashant-webkul** [comment]
> I've already checked my credentials, dbname, pass, host, servername are already the same with database and in file '. env'. Am I missing the step?

No, if MySQL had any problem with its authentication then it would have returned authentication error.

Did you created the database before running the migrations?
