### ISSUE TITLE
Cannot do a Free Shipping promotion without giving an actual discount

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#1355]
I want to do a Free Shipping promotion but a **"Discount Amount"** must be set but in this case I only want to offer Free Shipping as the discount. Even when I select apply discount to Shipping it still shows a discount amount and even the discount amount was off.

**Comment by prashant-webkul** [comment]
@emperorjm 
By adding your own action you can do that you need to put your own action class by merging the configuration with **discount-rules** configuration file.
