### ISSUE TITLE
public/vendor + public/themes

### ISSUE THREAD

**Issue by iSparkyZA** [bagisto/bagisto#1360]
Hello :)

Wondering if there a reason the folders above are not on Github but with composer install they are?

Thank You

**Comment by prashant-webkul** [comment]
@iSparkyZA Yes they are not on github as we they are created when you run vendor publish.
As it will create duplicate copies of assets and thus increase the download size of the repo.

**Comment by iSparkyZA** [comment]
Thank You for taking the time to answer - have a super day.
