### ISSUE TITLE
Site logo and Category Image are broken

### ISSUE THREAD

**Issue by haggag** [bagisto/bagisto#1362]
I have configured the default channel with the correct hostname. Which is showing in the browser. Also I have set the APP_URL in .env. Then I have also defined the public site logo by uploading it in the Channel settings.

Expected Behaviour: I expected that my custom logo will appear on the site
Actual Behaviour: However I found that the logo is broken because the URL used to display it is http://localhost/storage/channel/1/y5h0EWrBHRAbOqekvhjnhrsaezwnrg2xBcVd6yvJ.png. 

As you can see the hostname is localhost, not the custom domain that I have defined in the Channel settings! And I replace localhost with my domain and open that URL in a new tab the image is displayed correctly, meaning that uploading worked successfully and storage linking is correct.

The same issue is happening for category images.

What could be the issue?

**Comment by rahulshukla-webkul** [comment]
Hi @haggag 

When you are providing hostname to channel, use the same hostname in APP_URL also.
IF your image URL is using localhost to display it then we need to set APP_URL to your hostname instead of localhost.

**Comment by rahulshukla-webkul** [comment]
Hi @andrew-za 

Make sure that your domain is pointing to public (index.php) directory of Application & you have run 'php artisan storage:link' command at root of your project.

Thanks

**Comment by SIMONNABUKO** [comment]
This issue still persists. Product images are showing but the logo and banner images arent showing. Now I Deleted storage directory in the public folder then ran `PHP artisan storage: link` and it worked on the localhost. However, when I uploaded the project to the shared hosting, the images are broken again. Kindly help. This is the project URL showing broken banner images and logos: https://sirerics.co.ke/

**Comment by SIMONNABUKO** [comment]
https://sirerics.co.ke/storage/velocity/images/KiOFLUaooSdle9tHWavyOcMc0QkswGzjsxeuD2ph.jpeg
It is storing images in the storage directory yet that directory directory doesn't exist

**Comment by poppabear8883** [comment]
Same issues here: 

I have configured the `default channel` AND the `APP_URL` value with my `custom hostname` but yet the UI is still rendering `localhost` as the domain in the image src attribute. Can we get this re-opened ?

**Comment by ghermans** [comment]
Hi @poppabear8883 can you please try to run `php artisan optimize` once that is done see if the page is still trying to render as localhost

**Comment by poppabear8883** [comment]
@ghermans Thanks! That fixed it ...

**Comment by prabin-1990** [comment]
Hi, @ghermans I followed all the instructions but still, I am not able to fix the issue for my site.
I installed the fresh Bagisto 1.3.3, My product image is visible but the categories images, icons, and logo are not appearing in both frontend and backend.

My logo img src is https://www.nihantstores.com/public/storage/channel/1/tmRshWm7M8sXaZ7b0jATOO8PueiWQfn5hRhBTF2Q.png and images are uploaded as per the path specified.

My category icon path is https://www.nihantstores.com/public/storage/velocity/category_icon_path/2/kfTVsfZVFjJfBULoZftRCn79bGXPpEaYOOrFssWo.png and images are uploaded as per the path specified.

I have my default channel and APP_URL correct which is pointed up to /public folder
https://www.nihantstores.com/public/

Can you please assist me and open this thread.

Thanks
