### ISSUE TITLE
The "Discount Amount" field must be 0.0001 or more, but getting warning for this amount

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1366]
Framework Version: 0.1.6

![Screenshot - 2019-08-30T124726 130](https://user-images.githubusercontent.com/52821836/64000933-5bbec180-cb24-11e9-8b24-edbf76bef2b4.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-------------------------------------------
Fixed
![Screenshot (41)](https://user-images.githubusercontent.com/45203177/64472647-6a8a2180-d17f-11e9-9dcc-1c56c35a2f7b.png)
