### ISSUE TITLE
Carbon 1 is deprecated

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#1369]
After running **composer install** i noticed this error
```
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run ".\vendor\bin\upgrade-carbon" to get help in updating carbon and other frameworks and libraries that depend on it.
```

**Comment by theimerj** [comment]
Hello, I already submitted a pull request that includes updating Carbon to version 2. See #1364 If you want, you could help me check wether I did not omit anything. Thanky you.

**Comment by ghermans** [comment]
I noticed the pull request, nice job btw 👍 it also seems that the people from Webkul are already reviewing the pr.
i will also test the pr when i'm back from lunch :)

**Comment by andrew-za** [comment]
Trying to install the POS extension but getting the `Carbon 1 is deprecated` after running `composer.phar dump-autoload`

**Comment by prashant-webkul** [comment]
@andrew-za If you have purchased the module then please file a support ticket by writing mailto:support@bagisto.com
