### ISSUE TITLE
Wrong discount applied on cart in case of fixed discount.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1375]
- Framework Version: 0.1.6

------------------------------------------

![Screenshot from 2019-08-31 18-01-13](https://user-images.githubusercontent.com/45203177/64063982-8e96b180-cc19-11e9-90a4-136686df3120.png)
![Screenshot from 2019-08-31 18-01-03](https://user-images.githubusercontent.com/45203177/64063983-935b6580-cc19-11e9-95be-9d29364d7bd1.png)

**Comment by prashant-webkul** [comment]
Already fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

--------------------------------------------
Fixed
![Screenshot from 2019-09-07 13-51-09](https://user-images.githubusercontent.com/45203177/64472083-9359e900-d176-11e9-85de-b621ae6c7cfe.png)
![Screenshot from 2019-09-07 13-50-54](https://user-images.githubusercontent.com/45203177/64472088-99e86080-d176-11e9-9cb2-662af44d36b1.png)
