### ISSUE TITLE
In case of discount as percentage showing incorrect discount amount but grand total is correct.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1376]
- Framework Version: 0.1.6

-----------------------------------------

Created a rule having discount as percentage 10, added a product having price 240 and its showing discount amount as 23.04 .

![Screenshot from 2019-08-31 18-08-24](https://user-images.githubusercontent.com/45203177/64064071-d36f1800-cc1a-11e9-8f1e-bc83a582daa5.png)

![Screenshot from 2019-08-31 18-07-46](https://user-images.githubusercontent.com/45203177/64064073-d833cc00-cc1a-11e9-9b39-639d47ac853c.png)

**Comment by prashant-webkul** [comment]
@jyoti-webkul Not an issue as exchange rates were applied.
