### ISSUE TITLE
Filter is not working properly for action type column in cart rule 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1381]
Issue Description:-  filter is not working properly for action type column.
Preconditions:-
framework Version:-0.1.6, 0.1.7,0.1.8
Commit id:-0463622

steps to reproduce:
1- create any cart rule
2- use filter for action type column
2- select condition equals  to and enter action name 

Expected result:-should work according to conditions applied 
Actual result: not working properly.

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
