### ISSUE TITLE
In case of "Adjust whole cart to percent" discount amount is getting calculated according to price of one product 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1382]
Issue Description:- In case admin has selected Adjust whole cart to percent in action type. then at shop if customer has added 1 quantity or more than 1 quantity of same product. after applying coupon discount amount is same in both conditions.   

Preconditions:-
framework Version:-0.1.6
Commit id:-0463622
Expected result:-discount amount should be calculated according to sub total 
Actual result: discount amount is getting calculated according to price of product. 

![Screenshot - 2019-09-02T134510 067](https://user-images.githubusercontent.com/52821836/64099862-f0752980-cd87-11e9-949d-a0c484b68c48.png)

![Screenshot - 2019-09-02T134523 367](https://user-images.githubusercontent.com/52821836/64099876-f8cd6480-cd87-11e9-9c2c-fbbce41f599a.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-------------------------------------------

Fixed

![Screenshot (49)](https://user-images.githubusercontent.com/45203177/64475710-d5e5ea80-d1a3-11e9-8e66-e28af3f5fbce.png)
![Screenshot (50)](https://user-images.githubusercontent.com/45203177/64475714-ded6bc00-d1a3-11e9-8d3d-bb7054200f66.png)
