### ISSUE TITLE
Correct the spelling of "default" in theme.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#142]
Framework Version: 0.1.1

![grammar](https://user-images.githubusercontent.com/45203177/48843316-b7516700-edbc-11e8-851d-892dbe8b0df3.png)

**Comment by Jyoti-Singh1** [comment]
Fixed
Framework Version:0.1.2
![screenshot 1](https://user-images.githubusercontent.com/45203177/49428875-25d6f180-f7cd-11e8-967b-cb9acb51aea0.png)

**Comment by bl4ckz0ul** [comment]
how can i change the color of buttons, i modified the css but nothing happens.
