### ISSUE TITLE
Slider repository error

### ISSUE THREAD

**Issue by matatashadrack** [bagisto/bagisto#1421]
# Bug report

### Title
    **Title is a vital part of bug report for developer and triager to quickly identify a unique issue.**

    A well written title should contain a clear, brief explanation of the issue, making emphasis on the most important points.

### Issue Description
    **Bug description helps the developer to understand the bug.It describes the problem encountered.**

### Preconditions
    **Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
    **It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
    **Tell us what should happen.**
*    [Screenshots, logs or description]

### Actual result
    **Tell us what happens instead.**
    * [Tell us what happens instead]

**Comment by matatashadrack** [comment]
![image](https://user-images.githubusercontent.com/42380854/64475896-50f1d580-d191-11e9-8eb2-3162f8cd775a.png)

**Comment by prashant-webkul** [comment]
@matatashadrack Please take the latest build of Bagisto from its master branch. Its stable and try installing it again.

**Comment by blackyzero** [comment]
well, it works for master branch, but some feature is not available such as "Attribute Family, ...."

**Comment by prashant-webkul** [comment]
@blackyzero Really!!!
Care to upload a screenshot, we would love to help?

**Comment by KarimQaderi** [comment]
run

`composer dump-autoload`
