### ISSUE TITLE
Installation error with Webkul related class not found

### ISSUE THREAD

**Issue by wilbyang** [bagisto/bagisto#1423]
Steps to reproduce:
1. git clone https://github.com/bagisto/bagisto.git
2. go to bagisto  dir 
3. composer install
4. php artisan migrate 
5. php artisan db:seed
6. php artisan vendor:publish
7. php artisan storage:link 
8. composer dump-autoload
9. php artisan serve
10. go to http://localhost:8000 

Class Webkul\Core\Repositories\SliderRepository does not exist

**Comment by blackyzero** [comment]
same here, i also got this error, don't know how to fix it.

**Comment by accountmine** [comment]
same error

**Comment by prashant-webkul** [comment]
@blackyzero @accountmine Can you try again and download the latest build of Bagisto by downloading it from its master branch.

**Comment by wilbyang** [comment]
@prateek-webkul what do you mean by latest build specifically? git clone from master branch will get the latest build, right?

**Comment by prashant-webkul** [comment]
@wilbyang Yeah exactly.

**Comment by wilbyang** [comment]
@prashant-webkul 
When I clone from the master Branch, I get a warning as follows:


warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'packages/Webkul/Shop/publishable/assets/images/Arrow-Down.svg'
  'packages/Webkul/Shop/publishable/assets/images/arrow-down.svg'
  'packages/Webkul/Shop/publishable/assets/images/Logo.svg'
  'packages/Webkul/Shop/publishable/assets/images/logo.svg'
  'packages/Webkul/Shop/src/Resources/assets/images/Arrow-Down.svg'
  'packages/Webkul/Shop/src/Resources/assets/images/arrow-down.svg'
  'packages/Webkul/Shop/src/Resources/assets/images/Logo.svg'
  'packages/Webkul/Shop/src/Resources/assets/images/logo.svg'


Do you think is it a potential reason explain Class Webkul\Core\Repositories\SliderRepository does not exist?

**Comment by prashant-webkul** [comment]
@wilbyang No, those warnings are none of this concern and will not impact application in any way.

**Comment by wilbyang** [comment]
> @blackyzero @accountmine Can you try again and download the latest build of Bagisto by downloading it from its master branch.

It works now.

**Comment by prashant-webkul** [comment]
@wilbyang You haven't installed the project, please install it using the command **composer create-project** or **composer install**.
If already done then run the command: **composer dump-autoload**

**Comment by wilbyang** [comment]
@prashant-webkul 
It works now.

**Comment by flakerimi** [comment]
I just took it from master and composer install:

`Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

   ReflectionException  : Class Webkul\Product\Repositories\ProductRepository does not exist

  at /Users/flakerimismani/Sites/homeface/bagisto/vendor/laravel/framework/src/Illuminate/Container/Container.php:826
    822| 
    823|             // If the class is null, it means the dependency is a string or some other
    824|             // primitive type which we can not resolve since it is not a class and
    825|             // we will just bomb out with an error since we have no-where to go.
  > 826|             $results[] = is_null($dependency->getClass())
    827|                             ? $this->resolvePrimitive($dependency)
    828|                             : $this->resolveClass($dependency);
    829|         }
    830|

  Exception trace:

  1   ErrorException::("Declaration of Webkul\Core\Eloquent\Repository::count() should be compatible with Prettus\Repository\Eloquent\BaseRepository::count(array $where = Array, $columns = '*')")
      /Users/flakerimismani/Sites/homeface/bagisto/packages/Webkul/Core/src/Eloquent/Repository.php:15

  2   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Declaration of Webkul\Core\Eloquent\Repository::count() should be compatible with Prettus\Repository\Eloquent\BaseRepository::count(array $where = Array, $columns = '*')", "/Users/flakerimismani/Sites/homeface/bagisto/packages/Webkul/Core/src/Eloquent/Repository.php", ["/Users/flakerimismani/Sites/homeface/bagisto/vendor/composer/../../packages/Webkul/Core/src/Eloquent/Repository.php"])
      /Users/flakerimismani/Sites/homeface/bagisto/packages/Webkul/Core/src/Eloquent/Repository.php:15

  Please use the argument -v to see more details.
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
`

**Comment by flakerimi** [comment]
Same now
```Class Webkul\Core\Repositories\ChannelRepository does not exist (View: bagisto/bagisto/packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php) (View: bagisto/bagisto/packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php)```

**Comment by yaser-alazem** [comment]
Same here:
`ReflectionException
Class Webkul\Core\Repositories\SliderRepository does not exist`

I installed bagisto with `composer require ` then did the normal process steps then run the server and got this class missing error!

**Comment by yaser-alazem** [comment]
Problem solved after cloning the latest repository 
inside your server folder run `clone https://github.com/bagisto/bagisto.git`
after setting up the DB info inside `.env` file do the `migrate` artisan command followed with `db:seed` then `vendor:publish` and `storage:link` then `composer dump-autoload` and everything should be fine after running the server.
The problem seems to be with the old version of `SliderRepository` while installing with `composer require bagisto/bagisto` .

**Comment by bhanu-webkul** [comment]
Framework version: v 0.1.8

issue fixed
