### ISSUE TITLE
Error on running migrate:refresh

### ISSUE THREAD

**Issue by tushargugnani** [bagisto/bagisto#1426]
I get this error when I run php artisan migrate:refresh on fresh bagisto installation

` Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails (SQL: drop table if exists `catalog_rules`)`

**Comment by prashant-webkul** [comment]
@tushargugnani Please follow manual steps:
1. Drop all tables manually.
2. Run migrations.
3. Then run seeders.

**Comment by prashant-webkul** [comment]
Reopened as #1543
