### ISSUE TITLE
when navigated to some page and filtering causing issue

### ISSUE THREAD

**Issue by selvarajblr93** [bagisto/bagisto#1433]
### Issue Description
    When you navigated to last page in the pagination and filter shows "No products available in this category" even though product is available. 

### Steps to reproduce
    1. When on last page
    2. Then Filter the product

### Expected result
    shows the product based on the filter

### Actual result
    No products available in this category

### Solution 
     Rewrite the page number based on the result

**Comment by Sopizhenko** [comment]
In template **layered-navigation.blade.php**  make changes in method applyFilter
Change
>                     for(key in this.appliedFilters) {
>                             params.push(key + '=' + this.appliedFilters[key].join(','))
>                     }

To

>                     for(key in this.appliedFilters) {
>                         if (key != 'page') {
>                             params.push(key + '=' + this.appliedFilters[key].join(','))
>                         }
>                     }
It will solve the problem.
