### ISSUE TITLE
Checkout - payment methods are not visible when using Google Chrome

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#1436]
# Bug report

As the title explains on the checkout page payment methods are not available when using [Google Chrome](https://www.google.com/intl/en/chrome/).
I verified this with a clean install from the master branch.

### Steps to reproduce
    1. Add a product to your cart.
    2. Click on Checkout.
    3. Select delivery address.
    4. Select a shipping method.
    5. Click on continue and notice that nothing happens.

![imgKnipsel](https://user-images.githubusercontent.com/1594411/64618254-319cb780-d3e0-11e9-9c42-65d8b6cbdce6.PNG)

I do receive a error in the browser console
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```
### Expected result
- The wizard should  continue and show the payment methods.

**Comment by prashant-webkul** [comment]
@ghermans 
Very unfortunate.
Please open the network tab and take screenshot of the response of the failed request.

**Comment by ghermans** [comment]
@prashant-webkul i can't verify this right now as i had this issue on my machine at work and i am currently at home but i will verify it in a couple minutes with a new homestead instance

**Comment by ghermans** [comment]
I'm going to close this issue since i verified this on a new homestead instance, and couldn't replicate the issue,
