### ISSUE TITLE
Upgrading to Laravel 6.x LTS

### ISSUE THREAD

**Issue by haggag** [bagisto/bagisto#1438]
Bagisto is using Laravel 5.6, and security updates for that version stopped on February 7th, 2019. Laravel 6 is already released now, and it's an LTS version meaning bug fixes are provided for 2 years and security fixes are provided for 3 years. 

So I think it's good to upgrade ASAP because security is very critical when it comes to e-commerce systems.

Thanks.

**Comment by haggag** [comment]
Note that Laravel started using Semantic Versioning. This means Bagisto should depend on Laravel via "^6.0" as recommended in Laravel's Docs https://laravel.com/docs/6.x/releases. Minor and patch releases should never contain breaking changes.

**Comment by prashant-webkul** [comment]
@haggag Yeah obviously thanks though.
