### ISSUE TITLE
Order ID is not matching after printing invoice 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1447]
Issue after printing invoice at admin and customer both end

Preconditions
    1. framework Version: 0.1.6
    2. Commit id: e604037adfed4fad81710c50b193162923cc3d7b

 Steps to reproduce:
    1. step1- complete Invoice Number Settings
    2. step2- place an order 
    3. step3-check invoice and shipment  option under sales 

![Screenshot - 2019-09-12T135436 655](https://user-images.githubusercontent.com/52821836/64767185-e19b2d80-d564-11e9-94ee-d0a556a7f126.png)

![Screenshot from 2019-09-12 13-34-27](https://user-images.githubusercontent.com/52821836/64767418-4eaec300-d565-11e9-829e-afe4d6306208.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Fixed this issue for customer end also

![Screenshot from 2019-09-13 16-03-53](https://user-images.githubusercontent.com/45203177/64856653-1af49b80-d640-11e9-8c05-4608e9027ab7.png)

![Screenshot from 2019-09-13 16-03-47](https://user-images.githubusercontent.com/45203177/64856663-21831300-d640-11e9-95f4-420f2528e1f4.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Fixed
![image](https://user-images.githubusercontent.com/45203177/65020489-e851e800-d94a-11e9-9467-01e908fa00b8.png)
