### ISSUE TITLE
Apply as fixed amount and Percentage of Product not working according to products chosen in rule instead rule is getting applied to whole cart.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1453]
# Bug report

### Title
    Apply as fixed amount and Percentage of product is working same as "Adjust Whole cart to fixed amount" and "Adjust whole cart to percent".

### Issue Description
    If Apply as fixed amount or Percentage of product is selected from Action and in categories only one categories is select and during checkout product from other category is added in cart then discount is applied on that product also.

### Preconditions
   
    1. framework Version: 0.1.6
   

### Steps to reproduce
    
    1. step1- Create a cart rule by selecting fixed discount or percent of product, in category select only one category.
    2. step2- During checkout also add a product in cart that is not selected in cart rule.

### Expected result
   Discount should get applied on only product that lies in selected category of cart rule

### Actual result
     Discount gets applied on both categories product

![Screenshot from 2019-09-13 12-11-38](https://user-images.githubusercontent.com/45203177/64842371-aad61d80-d61f-11e9-8d25-406e7ed00aa0.png)
![Screenshot from 2019-09-13 12-11-32](https://user-images.githubusercontent.com/45203177/64842378-b1649500-d61f-11e9-881d-03dd0318e973.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

-----------------------------------

Not Fixed

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
