### ISSUE TITLE
filter is not working properly in equals to and not equals to condition for those column where value consists special characters

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1459]
# Bug report

### Title
    **filter is not working properly in equals to and not equals to condition for those column where value consists special characters **

### Issue Description:     
for ex. if any column consists value invoice#01 then while applying filter for that column if equals to condition has been selected and same value given then it is searching  only invoice.  

### Preconditions
   
    1. framework Version: 0.1.6

### Steps to reproduce
   
    1. step1- complete invoice setting 
    2. step2- place an order 
    3. step3- use filter for id column in order section of sales 

### Expected result
    should check condition  according to complete given value  

### Actual result-
    its not working according to complete given value

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
