### ISSUE TITLE
Attributes are not visible in layered navigation.

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#1466]
# Bug report

### Preconditions
    1. framework Version: v0.1.6 (using the master branch from Github)

### Steps to reproduce
1. Create a new attribute and set **Use in layered Navigation** to yes.
2. assign the attribute to a product or attribute family.
3. go to the frontend and check the navigation (the attribute isn't visible).
4. Check the attribute in the backend and you will see that the **Use in layered Navigation** is set to **No**.

![AttributesKnipsel](https://user-images.githubusercontent.com/1594411/64969022-6fe41c00-d8a3-11e9-9357-aa5ee420004e.PNG)

**Comment by rahulshukla-webkul** [comment]
Hi @ghermans 

Only 'Select' and 'Multiselect' type of attribute can be used in layered Navigation, Rest type of attribute can not be used in layered Navigation.

**Comment by ghermans** [comment]
@rahulshukla-webkul 

thanks for your answer, is there a reason why only these 2 types work?

**Comment by rahulshukla-webkul** [comment]
Hi @ghermans 

Only these type of Attribute have multiple values rest contains single one.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this enhancement **is done**. so I am **closing** this enhancement.
And I have attached a screenshot [Here](https://prnt.sc/o9n5rsS0uZyU). for **future reference.**
