### ISSUE TITLE
Tax rate application is dependent on STATE

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#1467]
### Title
Addresses using the right Zip/Post Code from a country but having a STATE value which is different from the value for the saved tax rate does not apply the tax rate to the order.

### Issue Description
So say for example the STATE is saved as "FL" for the tax rate in the backend but the customer used "FLORIDA" in their Address, the tax rate would not be applied to that address. 

Seeing that two states should not have the same zip/postal code in the same country it would be better to use just the Country and Zip/Postal Code range to find the right tax rate for a customer's address.

**Comment by jitendra-webkul** [comment]
Fixed in master
