### ISSUE TITLE
Discount not applied if attribute condition is selected while creating cart rule.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1469]
# Bug report

### Title
    Discount not applied if attribute condition is selected while creating cart rule.

### Issue Description
   While creating rule if attribute condition is selected then during checkout if cart contains that attribute then also discount not getting applied.
### Preconditions
   
    1. framework Version: 0.1.6
   
## Steps to reproduce
    
    1. step1- Create a cart rule with condition and select sku, size or color from attribute selection.
    2. step2- Checkout with cart following all condition and attribute choice.

### Expected result
    Discount should get applied.
### Actual result
    Discount not applied.

![Screenshot (81)](https://user-images.githubusercontent.com/45203177/65028148-34a42480-d959-11e9-9539-7c9a8237615f.png)
![Screenshot (82)](https://user-images.githubusercontent.com/45203177/65028163-3bcb3280-d959-11e9-96c8-310bfcc39807.png)

**Comment by prashant-webkul** [comment]
@jyoti-webkul Which action was used with this test?

**Comment by jyoti-webkul** [comment]
@prashant-webkul 
You can select any action to replicate the issue, if any attribute condition is selected discount will not work.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

---------------------------------------

Not Fixed

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
