### ISSUE TITLE
Add a functionality so that not logged-in user can also check his order from home page.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#147]
Framework Version :0.1.1

If a Guest User place an order for any product that he will not able to check his order status.Add a feature on home page so that guest user can also check his order status and return by using his order id and email.

**Comment by prashant-webkul** [comment]
Although the guest customer will be communicated by store keepers themselves using email or phone provided by the customer at the time of order.

But we will look into the possibility of adding it in near future.

**Comment by prashant-webkul** [comment]
This issue is for the guest users who ordered and wants to see their order details using their browser.
We have integrated email communications and any sort of information that is needed to be passed to the guest customer who ordered will be sent through emails.
