### ISSUE TITLE
Undefined index: whole_cart_to_percent

### ISSUE THREAD

**Issue by laurenwilliams92** [bagisto/bagisto#1479]
# Bug report

### Title
    Created a whole cart to percent discount but throws undefined index error

### Issue Description
    Undefined index error when getting to checkout page

### Steps to reproduce
    Created a new cart rule for a specific customer group, use coupon = 0, with no conditions and actions are adjust whole cart to percent with discount amount 25, max quantity 100, no to the rest. No products selected.

Go to checkout page and get undefined index error on NonCouponAbleRule helper.

### Expected result
    25% discount applied to whole cart

### Actual result
    Undefined index error.

![image](https://user-images.githubusercontent.com/32837730/65155350-0be96100-da25-11e9-9cb9-75fdf2d427de.png)

![screencapture-lauren-jtc-dev-helastel-net-admin-promotion-cart-rules-edit-1-2019-09-18-15_02_29](https://user-images.githubusercontent.com/32837730/65155571-6c789e00-da25-11e9-83d3-79cad06b8d55.png)

**Comment by prashant-webkul** [comment]
@laurenwilliams92 Which version were you using, while you encountered this situation?

**Comment by laurenwilliams92** [comment]
@prashant-webkul it is the latest version 0.1.7

**Comment by prashant-webkul** [comment]
Not getting this issue.

**Comment by bhanu-webkul** [comment]
@laurenwilliams92 

we have tested multiple times this thing but did not get any exception, its working fine. 

![Screenshot (48)](https://user-images.githubusercontent.com/52821836/67261972-a45d8000-f4c0-11e9-969f-20365a797db7.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

-----------------------------------------

Unable to replicate this issue
