### ISSUE TITLE
Quantity of Product doesn't get updated after creating a refund.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1489]
# Bug report

### Title
   Quantity of Product doesn't get updated after creating a refund.
### Issue Description
    Product Quantity not updated after refund is placed.
### Preconditions
    
1. framework Version-0.1.7

### Steps to reproduce

    1. step1-    Place and order and generate invoice and shipment for that order

    2. step2 - Create refund for that order and check the inventory.

### Expected result
    Product Quantity should get updated

### Actual result
      Product Quantity doesn't updated

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.7

--------------------------------------

Fixed

**Comment by bhanu-webkul** [comment]
Framework Version v0.1.8

still same issue for bundle product.

**Comment by bhanu-webkul** [comment]
Framework Version v0.1.8


issue fixed
