### ISSUE TITLE
Getting exception in creating configurable product.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#149]
Framework Version : 0.1.1
Test Steps:
1.Create product with type configurable
2. Add name to variants and delete some of the variants.
Exception occur when any of variant is deleted and then saving the product.
![screenshot from 2018-11-22 15-04-07](https://user-images.githubusercontent.com/45203177/48895549-5896f680-ee6b-11e8-83cc-04f48191746d.png)

**Comment by prashant-webkul** [comment]
The issue is fixed by @prashant-webkul in the commit bf6354589519fecc21eea388ccbb64d4ee18cd13.
Wait till next release to see the changes.

**Comment by Jyoti-Singh1** [comment]
Fixed
Framework Version: 0.1.2
