### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by OmarWael1** [bagisto/bagisto#1502]
# Bug report

### Title
       **Your requirements could not be resolved to an installable set of packages.**
### Issue Description
       Hello everyone , i have installed bagisto , after that i am trying to use command "composer install or composer update " but a problem occurs , ** Problem 1
    - The requested PHP extension ext-intl * is missing from your system. Install or enable PHP's intl extension.** 

I use laragon as a server , and this is a 3 lines  in php.in  in php folder  
;extension=php_gmp.dll
extension=php_intl.dll
;extension=php_imap.dll

### Preconditions
    **Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
    **It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
    **Tell us what should happen.**
*    [Screenshots, logs or description]

### Actual result
    **Tell us what happens instead.**
    * [Tell us what happens instead]

**Comment by prashant-webkul** [comment]
@OmarWael1 Can you please try again and reverify it using php_info() function and put screenshots.

**Comment by OmarWael1** [comment]
![screen1](https://user-images.githubusercontent.com/42839527/65400667-cbdb0300-ddc3-11e9-9b7d-876a1751a922.jpeg)

**Comment by OmarWael1** [comment]
![image](https://user-images.githubusercontent.com/42839527/65400858-efeb1400-ddc4-11e9-91d9-cfbcec7a4e3d.png)

here is php.ini file

**Comment by OmarWael1** [comment]
how to re verify it using php_info() ? ,, i have tried many times @prashant-webkul

**Comment by prashant-webkul** [comment]
@OmarWael1 
Please check php version using command line: ***php -v*** and verify that its v7.1.7?

**Comment by OmarWael1** [comment]
![image](https://user-images.githubusercontent.com/42839527/65484261-239a6c80-de9f-11e9-9513-08aa806d406f.png)

@prashant-webkul

**Comment by prashant-webkul** [comment]
@OmarWael1 Your extension is not working then, because sometime there are chances of different version working on command line and different on server but that is not the case.

I recommend you to see guide on how to install php extensions on your environment.

**Comment by OmarWael1** [comment]
thanks i have solved the problem , it was with php path in environment variables , it looked at another server (xammp) , and i tried to enable intel extension in laragon server   @prashant-webkul

**Comment by naqibullahmalikzada** [comment]
@prashant-webkul  i have the same issue with xampp i am not able to install it ,
same error happens 
![1111](https://user-images.githubusercontent.com/33382700/77244096-ef73ee80-6c2a-11ea-9183-e2d9c227ba1a.PNG)
![22222](https://user-images.githubusercontent.com/33382700/77244097-f0a51b80-6c2a-11ea-94c9-5885879b191c.PNG)
