### ISSUE TITLE
Getting incorrect refund amount.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1509]
# Bug report
Getting incorrect refund amount.

### Issue Description
    If order placed for more than one quantity for same amount and discount get applied on only one product, and at time of refund if refund is created for 2 product once and then for last product then at information page its showing incorrect refund amount.

### Preconditions
    
    1. framework Version.-0.1.7
    
### Steps to reproduce
   
    1. step1- Place an order for 3 quantity of same product.
    2. step2- Discount should get applied on only one Product
    3.step3-Create invoice and create refund of any 2 quantity.
    4step3-Create invoice and refund for 3rd quantity

### Expected result
  It should show correct refund amount
### Actual result
  While creating refund for 3rd product again discount get applied on that product.

![Screenshot from 2019-09-23 16-34-26](https://user-images.githubusercontent.com/45203177/65421915-9fa29f00-de22-11e9-920a-78e93e2e8718.png)
![Screenshot from 2019-09-23 16-34-35](https://user-images.githubusercontent.com/45203177/65421919-a5988000-de22-11e9-81ca-b9ee585c7536.png)

**Comment by bhanu-webkul** [comment]
framework Version: 0.1.7

 Commit id :  35acdc5e0a6134433e8699bf7c54b0586c1dfd63

fixed
