### ISSUE TITLE
Whole cart fixed amount applying to all items not whole cart

### ISSUE THREAD

**Issue by laurenwilliams92** [bagisto/bagisto#1511]
# Bug report

### Title
    **Applying a 'whole_cart_fixed_amount' is applying to individual items instead of cart**

### Issue Description
    Have applied a 'whole_cart_fixed_amount' to my cart which has two items, discount is applied to both instead of a whole

### Preconditions
    1. 0.1.7

### Steps to reproduce
    1. Create 'whole_cart_to_fixed_amount' discount with coupon, no conditions for £10 off
    2. Add two items to cart
    3. Apply coupon code

### Expected result
    On applying the coupon code it should apply the discount off the whole amount not each item.

![image](https://user-images.githubusercontent.com/32837730/65437572-f789d780-de1b-11e9-9cf0-008b955bed1c.png)

![image](https://user-images.githubusercontent.com/32837730/65435899-281c4200-de19-11e9-9bd2-94911cd094ab.png)

![image](https://user-images.githubusercontent.com/32837730/65435999-513cd280-de19-11e9-854b-4d837ae82cd6.png)

### Actual result
    Discount amount is incorrect and total is wrong, i.e being added multiple times. 
    Discount should be £10 not £19.99

**Comment by prashant-webkul** [comment]
Thanks for raising, will fix it real soon.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

--------------------------------------

Not Fixed

**Comment by prashant-webkul** [comment]
Fixed in PR #1766

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
