### ISSUE TITLE
Getting exception while creating cart rule in case admin did not fill selected attribute's value in attribute condition. 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1518]
# Bug report

### Title
    while creating cart rule, getting exception in case admin did not fill selected attribute's value.   
### Issue Description: 
if admin left blank text field after selecting sku attribute in attribute condition ,then getting exception.  

### Preconditions
  
    1. framework Version.v0.1.7
    2. Commit id. 819b397b679cf3c30c119a047d0f547f79ed0d55

### Steps to reproduce

    1. step1: click on add to cart. 
    2. stpe2: fill the required fields properly except add attribute condition  
    2. step2: click on add attribute condition  and select option SKU and select and any condition and do not provide any value. 

### Expected result:
 instead of exception it should give validation message.  
### Actual result
    getting exception. 
![Screenshot from 2019-09-25 18-58-16](https://user-images.githubusercontent.com/52821836/65606457-95220a00-dfc8-11e9-86ff-c37b12244b81.png)

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
