### ISSUE TITLE
API: user login doesn't support cart merge doesn't work

### ISSUE THREAD

**Issue by accountmine** [bagisto/bagisto#1519]
# Bug report

### Title
Cart not being merged after register if using API

### Issue Description
Cart being merged if I use laravel portal but not as API call

```
Event::fire('customer.after.login', $request->input('email'));
```

### Steps to reproduce
I used postman and tried local server to call using React + axios

1) http://127.0.0.1:8000/api/checkout/cart/add - returned items in my cart
2) http://127.0.0.1:8000/api/customer/register - successfully sign up
3) http://127.0.0.1:8000/api/customer/login  - successfully sign in
4) http://127.0.0.1:8000/api/checkout/cart - returned empty cart

**Comment by prashant-webkul** [comment]
@accountmine Please use the given format. And provide necessary proofs.

**Comment by accountmine** [comment]
@prashant-webkul updated

**Comment by jitendra-webkul** [comment]
Hi @accountmine 

Issue has been fixed, you pull from master or wait for release.

**Comment by bhanu-webkul** [comment]
Framework version v 0.1.8

issue fixed
