### ISSUE TITLE
Able to redirect to admin panel through newly created Channels.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1520]
# Bug report

Able to redirect to admin panel through newly created Channels.
### Issue Description
    User is able to redirect to admin panel by manually editing the url
### Preconditions
  
    1. framework Version-0.1.7
    

### Steps to reproduce
    
    1. step1- Create a new channel and open it
    2. step2- Manually enter admin/login

### Expected result
  User should not redirect to admin panel
### Actual result
   User redirected to admin panel
![Screenshot from 2019-09-26 13-27-18](https://user-images.githubusercontent.com/45203177/65670292-b20b1b80-e062-11e9-86dd-02db7b7ec5c3.png)

**Comment by ghermans** [comment]
Closing this issue as no feedback has been provided
