### ISSUE TITLE
Quick Links broken

### ISSUE THREAD

**Issue by flakerimi** [bagisto/bagisto#1522]
# Bug report
 
![Screen Shot 2019-09-26 at 11 20 46](https://user-images.githubusercontent.com/871482/65676181-baa62680-e04f-11e9-9396-97a70e05a227.png)

### Quick Links broken
    **On latest release footer quick links cannot parse route url.**

    Please be calm, short and emaphasize on points.

### Issue Description
    **Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
    **Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
    **It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
    **Tell us what should happen.**
*    [Screenshots, logs or description]

### Actual result
    **Tell us what happens instead.**
    * [Tell us what happens instead]

**Comment by flakerimi** [comment]
On database are as 

> <li><a href="@php echo route(" shop="" cms="" page="" refund-policy="" endphp="">Refund Policy</a></li>

**Comment by flakerimi** [comment]
This is bug from Channel Seeder, because tinymce replace code

**Comment by ridasaidd** [comment]
use single quotes on the route parameters.
<li><a href="@php echo route('shop.cms.page', 'refund-policy') @endphp">Refund Policy</a></li>

**Comment by flakerimi** [comment]
@ridasaidd, here is PR: https://github.com/flakerimi/bagisto/commit/5ed486dfb0cd6666e301101f2543e0c1c31e8bfa

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

-------------------------------------------

Fixed

**Comment by venkat402** [comment]
This issue till not at all fixed.

**Comment by venkat402** [comment]
Here is the links 
<ul class="list-group">
<li><a href="@php echo route(" shop="" cms="" page="" about-us="" endphp="">About Us</a></li>
<li><a href="@php echo route(" shop="" cms="" page="" return-policy="" endphp="">Return Policy</a></li>
<li><a href="@php echo route(" shop="" cms="" page="" refund-policy="" endphp="">Refund Policy</a></li>
<li><a href="@php echo route(" shop="" cms="" page="" terms-conditions="" endphp="">Terms and conditions</a></li>
<li><a href="@php echo route(" shop="" cms="" page="" terms-of-use="" endphp="">Terms of Use</a></li>
<li><a href="@php echo route(" shop="" cms="" page="" contact-us="" endphp="">Contact Us</a></li>

**Comment by N-Kumbhare** [comment]
Hello,

In velocity theme,

footer link not working it shows the @php route(code) @endphp in anchor tag

please help me with this

**Comment by vaishaliwebkul** [comment]
Hello @N-Kumbhare 
Please mention the bagisto version along with some error screenshots.

Thanks

**Comment by N-Kumbhare** [comment]
Hello,

this is a admin side screenshot where i have put the php code with route 
![image](https://user-images.githubusercontent.com/32652992/82862348-07befd00-9f3d-11ea-95ef-14743f597c22.png)

also please check frontend side screenshot
![send](https://user-images.githubusercontent.com/32652992/82862399-29b87f80-9f3d-11ea-89f1-e29580be9810.png)


Please help me with that ...

**Comment by N-Kumbhare** [comment]
Sorry,

forgot to tell you bagisto version 

It is 1.1.0

Thanks

**Comment by vaishaliwebkul** [comment]
Hi @N-Kumbhare 

you are adding the default theme custom code which will not work for velocity, instead of it you could  add this as shown below:-

![Screenshot (13)](https://user-images.githubusercontent.com/43210406/82864961-57082c00-9f43-11ea-918c-a2aa04fd4614.png)

![Screenshot (12)](https://user-images.githubusercontent.com/43210406/82864977-5f606700-9f43-11ea-8805-43467ba39a27.png)

**Comment by N-Kumbhare** [comment]
hi,

thanks for your kind reply..

but it will not work when you are on the cms pages..

Please see the screenshot
![test](https://user-images.githubusercontent.com/32652992/82871070-9720dc00-9f4e-11ea-8e4f-5ba582a9b063.png)

Where page appended twice... 

So please help me with that

**Comment by N-Kumbhare** [comment]
Hello hope you checked this ...

**Comment by vaishaliwebkul** [comment]
Hi @N-Kumbhare 
Now please add this code inside anchor tag "@php echo route('shop.cms.page', 'about-us') @endphp"

Thanks

**Comment by vaishaliwebkul** [comment]
@N-Kumbhare 
Before it update the code with master branch or also change the code of line as mention in this commit https://github.com/bagisto/bagisto/commit/b254736bd5c7c4ed56e51935035cf6470aaa072f

**Comment by N-Kumbhare** [comment]
Hello,

I didn't get you

Update master branch means ???

Can you give me directions how to do that ???

**Comment by vaishaliwebkul** [comment]
@N-Kumbhare 
open this file 
packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-middle.blade.php

then do the following changes as mentioned here https://github.com/bagisto/bagisto/commit/b254736bd5c7c4ed56e51935035cf6470aaa072f

after this run php artisan config:cache

**Comment by N-Kumbhare** [comment]
Thank you so much for your kind reply
