### ISSUE TITLE
Customer registered at one channel is able to login at all channel.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1524]
# Bug report

Customer registered at one channel is able to login at all channel.
### Issue Description
  If customer creates his/her account on any channel then he/she will be able to login at any channel.
### Preconditions
 
    1. framework Version- 0.1.7

### Steps to reproduce
  
    1. step1- Create a customer at one website
    2. step2- Try to login at other channel with same credential.

### Expected result
   Customer should not be logged in.
### Actual result
   Customer gets logged in.

**Comment by prashant-webkul** [comment]
Channels removed from customers.
