### ISSUE TITLE
All registered customer is saved in default channel at admin customer section.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1525]
# Bug report
All registered customer is saved in default channel at admin customer section.

### Issue Description
   Create a customer at any website and at admin customer grid it will be saved in default channel only.

### Preconditions
 
    1. framework Version-0.1.7

### Steps to reproduce
    
    1. step1- Create a customer on any website
    2. step2- Edit the customer from admin end.

### Expected result
   It should display in the channel on which the customer is created.

### Actual result
 Displaying in default channel.

![Screenshot from 2019-09-26 16-33-26](https://user-images.githubusercontent.com/45203177/65683665-74ff5300-e07b-11e9-860b-4c549ac483cf.png)
![Screenshot from 2019-09-26 16-33-52](https://user-images.githubusercontent.com/45203177/65683678-7df02480-e07b-11e9-9332-a9cadbe4719e.png)

**Comment by prashant-webkul** [comment]
Channels removed.
