### ISSUE TITLE
Product created at default channel is visible in all channels.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1526]
# Bug report
Product created at default channel is visible in all channels.

### Issue Description
   Product created at default channel is visible in all channels.
### Preconditions
   
    1. framework Version-0.1.7
  
### Steps to reproduce
  
    1. step1- Create a product at default channel
    2. step2- Check the same product in all channel

### Expected result
 Product should display only in selected channel
### Actual result
  Product displays in all channels.

**Comment by jitendra-webkul** [comment]
Can not reproduce this issue
