### ISSUE TITLE
Channel not Working according to Selected Locale.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1528]
# Bug report
Channel not working according to Selected Locale.

### Issue Description
  If default locale and locale is selected different from default channel then also default locale is working for that channel also.

### Preconditions

    1. framework Version.-0.1.7

### Steps to reproduce
    
    1. step1- Create a locale
    2. step2- Select that locale as a default locale and in locale field also.

### Expected result
 Locale for new channel should be according to the selected locales in that particular channel.
### Actual result
  Channel not working according to selected Locale.

![Screenshot from 2019-09-26 17-10-20](https://user-images.githubusercontent.com/45203177/65685825-89921a00-e080-11e9-8e22-3b4b5e5a1d34.png)
![Screenshot from 2019-09-26 17-09-25](https://user-images.githubusercontent.com/45203177/65685835-90b92800-e080-11e9-9470-f9d284f57767.png)

**Comment by jitendra-webkul** [comment]
Can not reproduce this issue
