### ISSUE TITLE
Digital Product like file?

### ISSUE THREAD

**Issue by AGhasemzadeh** [bagisto/bagisto#153]
Can we sell file wit bagisto?

**Comment by prashant-webkul** [comment]
No, currently you can only sell products that are simply categorised as Simple and Configurable products.
Yet you can list digital products on your store and take orders from customers and communicate using their email and phone details for providing them download for e-file products.

But we will soon have the **Electronic File** type products soon in our framework.

**Comment by alighasemzadeh** [comment]
@prashant-webkul 
Hello,
Did you implement Electronic File?

**Comment by prashant-webkul** [comment]
@alighasemzadeh No dear currently we are bumping up the core. May be in release 0.2 or greater we will have new type of products.
But you can now surely make new type of products on your own. As in product package we have a configuration file their you can define your own product type. And then you have to change in the core for that product type.

**Comment by mailnike** [comment]
Hi there,

Is there any update regarding this?

**Comment by rahulshukla-webkul** [comment]
Hi @mailnike 

We have added four new type of product.
1. Virtual
2. Downloadable
3. Grouped
4. Bundle
 
You can clone or download from master branch & it is on testing phase.
