### ISSUE TITLE
Customer model still has `channel_id` as fillable

### ISSUE THREAD

**Issue by accountmine** [bagisto/bagisto#1532]
# Bug report

### Title
Customer model still has `channel_id` as fillable

https://github.com/bagisto/bagisto/blob/15d935e68b2dda9dbf47bb370d9bd3d29ad6901c/packages/Webkul/Customer/src/Models/Customer.php#L20

But actual column were removed. As a result API register is broken

https://github.com/bagisto/bagisto/blob/04c93e233906d9b2f271ab7c873f0d78ab9781a0/packages/Webkul/Customer/src/Database/Migrations/2019_09_26_163950_remove_channel_id_from_customers_table.php

Don't you guys run any tests when you pushing changes like this?

**Comment by prashant-webkul** [comment]
@accountmine We heavily rely on manual testing. And it gets done on a periodical basis.

**Comment by accountmine** [comment]
@prashant-webkul Are you considering implementing unit tests? Also, I wish you code would be more consistent. 

### Some notes on API
- In `checkout/cart/add/:id` you are accepting `quantity` but in `checkout/cart/update` you are taking `qty` as a object with {"product_key": quantity (number)}. (Complete missing in documentation had to go through you code to make it work)
. Also, you are missing that `checkout/cart/add/:id` requires `quantity` and `product` in body payload. Without `product` it would give silence error. Not sure why you need `product` twice in URL and body payloads (Complete missing in documentation had to go through you code to make it work)

**Comment by accountmine** [comment]
@prashant-webkul Would you mind helping me with those? https://forums.bagisto.com/topic/425/promotion-free-shipping-over-100 and https://forums.bagisto.com/topic/423/api-how-to-get-parent-url_key?

**Comment by prashant-webkul** [comment]
@accountmine We are in transition phase for implementing some unit tests and then automating them also. 
We are targeting releases around this year's end will come with unit & functional test assertions performed with the help of  automation testing and with CI too.

Currently team is too over occupied with other deliverable(s) that unit and functional tests have taken a road block.

But it will be done be assure of that.

**Comment by prashant-webkul** [comment]
@accountmine On this: https://forums.bagisto.com/topic/425/promotion-free-shipping-over-100

You can make your own action class and push it into **discount-rules** config file with its fully qualified path and then you need to push that same thing in **pricerules.cart.actions** after successfully merging your configuration you would be able to see your action class in cart rule forms.

**Comment by accountmine** [comment]
@prashant-webkul Thank you.

Free shipping after some amount in cart everywhere in e-commerce nowadays why not to add some native support?
