### ISSUE TITLE
Cart Rule not updating when cart changes

### ISSUE THREAD

**Issue by laurenwilliams92** [bagisto/bagisto#1534]
# Bug report

### Title
    **Cart Rule and total amount not updating when cart changes**

### Issue Description
    **When a discount is applied and a product is added/removed from the cart the totals/discount amounts are not updated**

### Preconditions
    1. v0.1.7

### Steps to reproduce
    1. Add product to cart
    2. Apply discount (coupon code - whole_cart_to_percent)
    3. Add another product / Remove a product
 
### Expected result
    **On adding a another product or removing a product, the cart rule and impacts should be recalculated. Resulting in the totals updating**
![image](https://user-images.githubusercontent.com/32837730/65890599-0b44b900-e39b-11e9-9a96-19a10b501288.png)

![image](https://user-images.githubusercontent.com/32837730/65890659-2283a680-e39b-11e9-91c8-b7c590f60f77.png)

### Actual result
    **On adding or removing a product from the cart, the totals are not updated.**

**Comment by prashant-webkul** [comment]
@laurenwilliams92 Thanks for notifying this.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

-------------------------------------------

Fixed
