### ISSUE TITLE
Change rate should change

### ISSUE THREAD

**Issue by alighasemzadeh** [bagisto/bagisto#1539]
Hello,
1 USD = 125000 IRR
While we can't save this value into database with decimal(10,5).
125000 return 9999.9999

**Comment by prashant-webkul** [comment]
Hello @alighasemzadeh,
you are probably right as we have used Decimal (12, 4) for storing decimal values such as price, weight dimensions, etc.
And there are some places which even have higher precision for calculation than Decimal (12, 4).

Decimal (12, 4) is enough to save the values large enought for every one's need.

And coming on to your problem that when you are storing 125000 it returns as 9999.9999 can you please point out in which table you are facing this issue. As we haven't used decimal 10, 5 columns other than inventories table which have lat, long fields.

And also please specify version of your **database**, **bagisto**, **php** also.

**Comment by prashant-webkul** [comment]
@alighasemzadeh We will provide a necessary fix for this by changing this column to **decimal 24, 12**
Thanks for pointing this out.
