### ISSUE TITLE
While creating channel Description field,Home Page Content and footer _content is required, but it doesn't throw any validation error if we leave that field blank.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#154]
Framework Version: 0.1.1

Test Steps:
1. Add a new Channel.
2. Leave description field, Home Page Content field and footer_content field blank
3. Now save the channel.

**Comment by prashant-webkul** [comment]
All the tinyMCE editor fields are not getting validated on the client side properly.

**Comment by Jyoti-Singh1** [comment]
Fixed. Now these fields are not required
Framework Version :0.1.2
