### ISSUE TITLE
API: /addresses giving other customer addresses

### ISSUE THREAD

**Issue by accountmine** [bagisto/bagisto#1540]
# Bug report

### Title
/addresses giving other customer addresses. Per you documentation (To get the address of a customer, that customer must be logged in to the Bagisto Store. You can achieve this job by using addresses API call resource.)

### Proof
1) Database of `customer_addresses` table. Address ID = 1 and Customer ID = 3
![image](https://user-images.githubusercontent.com/53593159/66101061-39282a00-e562-11e9-901d-e09309651129.png)
2) My current user ID = 6
![image](https://user-images.githubusercontent.com/53593159/66101077-4f35ea80-e562-11e9-95cd-910a08845005.png)
3) Being returned Address ID  = 1
![image](https://user-images.githubusercontent.com/53593159/66101091-59f07f80-e562-11e9-9943-e2d5c88a1dea.png)

**Comment by accountmine** [comment]
@prashant-webkul I made a PR. Can you please help me with implementing free shipping over $150?

**Comment by prashant-webkul** [comment]
> @prashant-webkul I made a PR. Can you please help me with implementing free shipping over $150?

Current version have issues with rules working with shipments. I suggest you to wait a little longer for exact implementation of this.

**Comment by accountmine** [comment]
@prashant-webkul Do you have any estimates? I am launching my shop next week

**Comment by prashant-webkul** [comment]
> @prashant-webkul Do you have any estimates? I am launching my shop next week

Real soon.

**Comment by accountmine** [comment]
@prashant-webkul Thank you. Ill be waiting
