### ISSUE TITLE
Laravel's migrate down and refresh does not work properly, improper implementation of migrations.

### ISSUE THREAD

**Issue by prashant-webkul** [bagisto/bagisto#1543]
# Bug report

### Title
    **php artisan migrate:refresh, php artisan migrate:reset does not work.**

### Issue Description
    **Hassle free migration provisions provided by Laravel are not properly implemented and had left migrations only on single way.**

### Preconditions
    **Please provide as detailed information about your environment as possible.**

    1. v0.1.4, v0.1.5, v0.1.6, v0.1.7.

### Steps to reproduce
    **It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. php artisan migrate:refresh
    2. php artisan migrate:reset
    3. php artisan migrate:fresh

### Expected result
    **Any of the above steps should work after running migrations.**

### Actual result
    **Gives query exceptions as expected.**

**Comment by laurenwilliams92** [comment]
Migrations to be fixed:
packages/Webkul/Attribute/src/Database/Migrations/2018_07_05_130148_create_attributes_table.php

packages/Webkul/Attribute/src/Database/Migrations/2018_07_05_135150_create_attribute_families_table.php
 packages/Webkul/Attribute/src/Database/Migrations/2018_07_05_135152_create_attribute_groups_table.php

packages/Webkul/Category/src/Database/Migrations/2018_07_05_142820_create_categories_table.php

packages/Webkul/Checkout/src/Database/Migrations/2018_09_05_150444_create_cart_table.php

packages/Webkul/Core/src/Database/Migrations/2018_07_10_055143_create_locales_table.php

packages/Webkul/Core/src/Database/Migrations/2018_07_20_054502_create_currencies_table.php

packages/Webkul/Core/src/Database/Migrations/2018_07_20_064849_create_channels_table.php

packages/Webkul/Core/src/Database/Migrations/2018_12_05_132625_drop_foreign_key_core_config_table.php

packages/Webkul/Core/src/Database/Migrations/2018_12_05_132629_alter_core_config_table.php

packages/Webkul/Customer/src/Database/Migrations/2018_07_24_082635_create_customer_groups_table.php

packages/Webkul/Customer/src/Database/Migrations/2018_07_24_082930_create_customers_table.php

packages/Webkul/Discount/src/Database/Migrations/2019_05_13_024326_create_cart_rule_table.php

packages/Webkul/Discount/src/Database/Migrations/2019_05_13_024419_create_cart_rule_customer_groups_table.php

packages/Webkul/Discount/src/Database/Migrations/2019_05_23_175727_create_cart_rule_customers_table.php

packages/Webkul/Discount/src/Database/Migrations/2019_05_23_180457_create_cart_rule_coupons_table.php

packages/Webkul/Discount/src/Database/Migrations/2019_05_24_113949_create_cart_rule_coupons_usage_table.php

packages/Webkul/Discount/src/Database/Migrations/2019_05_30_141207_create_cart_rule_cart_table.php

packages/Webkul/Discount/src/Database/Migrations/2019_08_08_130583_create_catalog_rule_products_price_table.php

packages/Webkul/Product/src/Database/Migrations/2018_07_27_065727_create_products_table.php

packages/Webkul/Product/src/Database/Migrations/2019_01_25_124522_add_updated_at_column_in_product_flat_table.php

packages/Webkul/Tax/src/Database/Migrations/2018_08_30_064755_create_tax_categories_table.php

packages/Webkul/Tax/src/Database/Migrations/2018_08_30_065042_create_tax_rates_table.php

packages/Webkul/Tax/src/Database/Migrations/2018_08_30_065840_create_tax_mappings_table.php

**Comment by prashant-webkul** [comment]
@laurenwilliams92 As you can see the issue is tagged with Hacktober fest, so you can contribute a PR regarding this issue.
