### ISSUE TITLE
Catalog Rule not working

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1546]
# Bug report

### Title
    Catalog Rule not working

### Issue Description
    I am not sure if I used it wrong or the system actually has a bug, but I believe it doesn't work the way it should be

### Preconditions
    1. Version: 0.1.8, 0.1.7
    2. Fresh Install on code and database.

### Steps to reproduce
    1. Create a catalog rule in management end. With the config of Active, General Customer Group, apply to category "Root", and set the action of adjust price to 30%.
    2. The item on the page doesn't change or the item in the cart has the same price. (Never made it work, so I am not sure what it should looks like.)
### Expected result
    Expect to have the item showing 30% off or the price with 30% off on the page or in the cart.

### Actual result
    Nothing changed.

**Comment by rahulshukla-webkul** [comment]
Hi @lYesterdaYl 

We are Re-Developing this package with some extended feature and it may completed in next month.

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
