### ISSUE TITLE
Cart Rule not properly applied

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1547]
# Bug report

### Issue Description
    The Cart Rule doesn't apply properly for items from different categories.

### Preconditions
    Version: 0.1.8, 0.1.7 etc

### Steps to reproduce
    1. Create 2 different categories, Lets say Fruit and Office.
    2. Assign 2 items to the category(Apple: $10, Chair: $5).
    3. Create a cart rule to give 30% off for Fruit category.
    4. Add both items to the cart.

### Expected result
    Total should be 10*0.7 + 5 = 8

### Actual result
    it shows total is (10+5)*0.7 = 10.5

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

------------------------------------------

Not fixed

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
