### ISSUE TITLE
App version is not updated in .env file.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1553]
# Bug report
App version is not updated in .env file.

### Issue Description
    App version is not updated in .env file.Latest release is 0.1.8 and its showing 0.1.7
### Preconditions

    1. framework Version-0.1.8
    
### Steps to reproduce

    1. step1- Install new framework and check the app version in env file
 
### Expected result
   App version should get updated
### Actual result
  App version is not updated in .env file.

**Comment by prashant-webkul** [comment]
Done in PR #1554

**Comment by bhanu-webkul** [comment]
framework Version-0.1.8

Done
