### ISSUE TITLE
Bagisto Sliders Should be linkable 

### ISSUE THREAD

**Issue by haggag** [bagisto/bagisto#1556]
Almost all e-Commerce sites use the front page Slide show (i..e Carousel) to show latest offers and highlight some products. This means the user should be able to click the slider and go some page in Bagisto (ex. a product page or category page). 

Currently Bagisto Sliders seems to be just showing static images without a way to link each slider to a URL. Which makes them not very useful.

A optional new field should be added in the Slider form which accepts either an external URL or relative URL. If the field isn't filled the slider can function as just a static image.

Thanks.

**Comment by prashant-webkul** [comment]
@haggag That form already have WYSIWYG editor, please use that and you could achieve what you have asked for.

**Comment by haggag** [comment]
@prashant-webkul I have added a link in the content field, and now I see the link appearing in the middle of the image:
![Uploading Screenshot from 2019-10-09 10-49-44.png…]()


Is there a way to make the whole slider image clickable and make it redirect to the provided link?

**Comment by prashant-webkul** [comment]
Yes you can override slide.blade.php in order to cut the hassle.

Here below is the frontend code:

<section class="slider-block">
    <custom></custom>
</section>

@push('scripts')
    <script type="text/x-template" id="custom">
        <div class="slider-content" v-if="images.length > 0">
            <ul class="slider-images">
                <li v-for="(image, index) in images" :key="index" v-bind:class="{'show': index == currentIndex}">
                    <a :href="public_path + '/' + content[index].url_key">
                        <img class="slider-item" :src="image" />

                        <div class="show-content" v-bind:class="{'show': index==currentIndex}" :key="index" v-html="content[index].content"></div>
                    </a>
                </li>
            </ul>

            <div class="slider-control" v-if="images_loaded">
                <span class="icon dark-left-icon slider-left" @click="changeIndexLeft"></span>
                <span class="icon light-right-icon slider-right" @click="changeIndexRight"></span>
            </div>
        </div>

        {{-- <div class="slider-content" v-if="images.length>0">
            <ul class="slider-images">
                <li v-for="(image, index) in images" :key="index" v-bind:class="{'show': index==currentIndex}">
                    <img class="slider-item" :src="image" />

                    <div class="show-content" v-bind:class="{'show': index==currentIndex}" :key="index" v-html="content[index]"></div>
                </li>
            </ul>

            <div class="slider-control" v-if="images_loaded">
                <span class="icon dark-left-icon slider-left" @click="changeIndexLeft"></span>
                <span class="icon light-right-icon slider-right" @click="changeIndexRight"></span>
            </div>

        </div> --}}
    </script>

    <script>
        Vue.component('custom', {
            template: '#custom',

            data: function () {
                return {
                    data: [],
                    images: [],
                    public_path: "{{ url()->to('/') }}",
                    currentIndex: -1,
                    content: [],
                    current: false,
                    images_loaded: false
                }
            },

            mounted() {
                this.data = @json($sliderData);

                for (i in this.data) {
                    this.images.push(this.public_path + '/storage/' + this.data[i].path);

                    this.content.push({'content': this.data[i].content, 'url_key': this.data[i].url_key});
                }

                this.currentIndex = 0;

                if(this.images.length == 0) {
                    this.images.push = "vendor/webkul/shop/assets/images/banner.png";
                } else {
                    this.images_loaded = true;
                }
            },

            methods: {
                changeIndexLeft: function() {
                    if (this.currentIndex > 0) {
                        this.currentIndex--;
                    } else if(this.currentIndex == 0) {
                        this.currentIndex = this.images.length-1;
                    }
                },

                changeIndexRight: function() {
                    if(this.currentIndex < this.images.length-1) {
                        this.currentIndex++;
                    } else if(this.currentIndex == this.images.length-1) {
                        this.currentIndex = 0;
                    }
                }
            }
        });
    </script>
@endpush

**Comment by lYesterdaYl** [comment]
Hi, could you tell me how to use this chunk of code? I tried to pasted in the slide.blade.php file, but the slider just crash.

**Comment by akassama** [comment]
Hi, the Velocity sliders already have an option to add a link under "**Slider Path**". The path name is added to your domain, for example, if you add "shoes", it would be https://your-site.com/shoes.

If you still want to manually edit the slider links, you can go to: 
`\resources\themes\velocity\views\home\slider.blade.php`

You can edit the link in this section:
![slider-path-shoes](https://user-images.githubusercontent.com/32126102/102171820-71d2cb80-3ea8-11eb-9459-e3b97a32e0b2.jpg)

```
 <slide slot="slide-{{ $index }}">
     <a @if($slider['slider_path']) href="{{ $slider['slider_path'] }}" @endif>
            <img
                      class="col-12 no-padding banner-icon"
                       src="{{ url()->to('/') . '/storage/' . $slider['path'] }}" />

                 <div class="show-content" v-html="'{{ $textContent }}'">
                  </div>
       </a>
</slide>
```
