### ISSUE TITLE
Change the button name of recover password page as well as logo is not coming on reset password mail 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1559]
Bug report: -
Title:  Change the button name of recover password page as well as logo is not coming on reset password mail 

Issue Description
in place of "email password reset link" give "submit" button . 

Preconditions
1. framework Version-0.1.8
Steps to reproduce
1. step1- Click on forgot password at admin end .
2- step2- repeat step1 at customer end and then enter mail id and click on submit.
3- step3- check reset password mail  
Expected result: Submit button as given at customer end and in mail channel logo should be visible  

Actual result: button name written as email password reset link, and instead of logo Blisss is written.  

![Screenshot (6)](https://user-images.githubusercontent.com/52821836/66468786-5ef28900-eaa4-11e9-87b2-6a052ebeeb1a.png)
![Screenshot from 2019-10-09 14-57-39](https://user-images.githubusercontent.com/52821836/66469463-80a04000-eaa5-11e9-807d-d1ee4b1d25c4.png)

**Comment by prashant-webkul** [comment]
@bhanu-webkul The button text seems fine.

**Comment by bhanu-webkul** [comment]
framework Version-0.1.8

issue fixed
