### ISSUE TITLE
Old password check in edit profile ain't working for customers

### ISSUE THREAD

**Issue by prashant-webkul** [bagisto/bagisto#157]
When customer tries to change the password from the edit profile page it doesn't check the old password and the new password is applied.

**Comment by prashant-webkul** [comment]
commit c9f7d61705006d56d1b2b15013e7f0572c1d51e1 by @prashant-webkul  has fixed the issue.

**Comment by prashant-webkul** [comment]
wait for the new release to see the result.

**Comment by Jyoti-Singh1** [comment]
Not fixed. Displaying incorrect message.
Test Steps:
1. Enter new password without entering any data in Old Password field and click on Update Profile.
Its displaying success message that password is updated. However user is not able to login with updated credential.

**Comment by prashant-webkul** [comment]
I have tested the issue, the functionality seems be intact but the validation and notification messages are not correctly displaying in this case.
Will get it fixed.

**Comment by prashant-webkul** [comment]
duplicated issue with new issue #398
