### ISSUE TITLE
Bagisto with built in Affiliate system

### ISSUE THREAD

**Issue by AkkuFresh** [bagisto/bagisto#159]
First of all, congratulation for the start of this project.

It is a feature request & suggestion.
It would be great if the Bagisto is empowered with a built in Affiliate system, but in ONE account (not like as Opencart different registration for the Affiliate).
It should be a simple Button on the Customer area to join to the Affiliate system of the shop.

**Comment by prashant-webkul** [comment]
Hi @AkkuFresh ,
We have acknowledged your concern on giving the subsystem inside customer for affiliate marketing system.
Currently we do not have this in our line up but our core team will have a discussion to do it.
And we will let you know.

**Comment by folkevil** [comment]
+1 for this feature
