### ISSUE TITLE
Export information is not limit by search options.

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1594]
# Bug report

### Issue Description
    Export function always export everything.

### Preconditions
    1. 0.1.8

### Steps to reproduce
    Use any export function.

### Expected result
    Expect to export a file that only contains result from filter
### Actual result
    Whole table information is inside the excel file.

**Comment by lYesterdaYl** [comment]
Hi, any updates on this issue?

**Comment by rahulshukla-webkul** [comment]
Hi @lYesterdaYl 

Right Now, this issue has not been fixed, but we will soon solved it.

**Comment by rahulshukla-webkul** [comment]
Hi @lYesterdaYl 

We have solved this issue, you can take pull from master branch.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

------------------------------------------

Fixed
