### ISSUE TITLE
Getting Exception on running php aritsan migrate

### ISSUE THREAD

**Issue by simplysaif** [bagisto/bagisto#160]
Got error in creation of users table when running **php artisan migrate** .
here is the details terminal output
**$ php artisan migrate
Migration table created successfully.

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

  at /opt/lampp/htdocs/project/bagisto/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
      /opt/lampp/htdocs/project/bagisto/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  2   PDOStatement::execute()
      /opt/lampp/htdocs/project/bagisto/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  Please use the argument -v to see more details.
`**

**However after a bit of searching i was able to fix it as its a common issue by adding few lines in** `App\Providers\AppServiceProvider.php` . Final file looks like this:

`<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
`

**Comment by prashant-webkul** [comment]
Yeah this problems comes when you work with Laravel, to my opinion you had been doing the setup on windows.

Please feel free to continue any of your problems here at discussion [Bagisto Forums](https://forums.bagisto.com/)

**Comment by simplysaif** [comment]
now windows... its on linux mint

**Comment by prashant-webkul** [comment]
I will update the readme.md for it. Thanks for raising the issues.
I hope you find more of them soon.

**Comment by prashant-webkul** [comment]
> now windows... its on linux mint

I will update the readme.md for it. Thanks for raising the issues.
I hope you find more of them soon.
