### ISSUE TITLE
Inappropriate validation message 

### ISSUE THREAD

**Issue by ssi-anik** [bagisto/bagisto#161]
https://demo.bagisto.com/products/apple-iphone-7
<img width="662" alt="screen shot 2018-11-25 at 12 55 38 pm" src="https://user-images.githubusercontent.com/2676602/48976418-840b2280-f0b1-11e8-9b4f-fd5a8b30ac30.png">

**Comment by prashant-webkul** [comment]
We know about this issue.
@jitendra-webkul  will surely provide a work around for this in next release which is also coming soon.

**Comment by Jyoti-Singh1** [comment]
Fixed
Framework Version:0.1.2
![screenshot 2](https://user-images.githubusercontent.com/45203177/49431361-528e0780-f7d3-11e8-8cb5-d69fd430cbaa.png)
