### ISSUE TITLE
massaction-type on DataGrid

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1612]
I have a question regarding to the mass actions in the DataGrid. What are the types for the mass actions? I only see "update" and "delete". I wanna perform an action of getting all table items' id. Are there any other better choice for the type? I can see update type gives an addition selector, and delete type can do what I need, but I just wanna make sure if there is a better option. Thanks.

**Comment by prashant-webkul** [comment]
Just think mass action as selection of multiple records and doing some action on them.
We had done some tasks like generating QR code for products in our POS mod using them apart from generic update and delete.
