### ISSUE TITLE
link name is not  getting  saved in ar and pt_BR locale in downloadable product 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1620]
# Bug report

### Title
link name is not  getting  saved in ar and pt_BR locale in downloadable product 

### Issue Description:
link name is not getting save in downloadable product
### Preconditions
    1. framework Version.v0.1.8
    

### Steps to reproduce

    1. step1: create  a downloadable product 
    2. step2: edit same product in ar locale and give link name 

### Expected result
   link name should be saved
### Actual result
   link name disappear after saving the product

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

------------------------------------------

Fixed
