### ISSUE TITLE
Mysql port field length issue

### ISSUE THREAD

**Issue by webkul-suranjan** [bagisto/bagisto#1632]
# Bug report

### Title
Can not proceed with web installation, if mysql port is greater than 4 digits.

### Issue Description
In web installation, if mysql port length is greater than 4 digits, it won't allow installation going to next step.
### Steps to reproduce
1. Setup a mysql server with custom port with port length greater than 4 digits.
2. Proceed with web installation.
 
![bagisto-mysql](https://user-images.githubusercontent.com/50675889/66826870-14bd4c00-ef6b-11e9-9ba9-cbf545467d0c.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

--------------------------------------------

Fixed

**Comment by ccoeder** [comment]
Are we sure that this issue has been fixed? 

<img width="519" alt="Screen Shot 2019-11-27 at 19 14 58" src="https://user-images.githubusercontent.com/10330468/69740297-3b65c980-114a-11ea-8dd0-eba363b0a8c5.png">

**Comment by rahulshukla-webkul** [comment]
Hi @ccoeder 

Which version of bagisto you are using because this issue has been fixed.
You can see PR above - https://prnt.sc/q36tuc
