### ISSUE TITLE
Fail to redirect to a pdf url

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1636]
# Bug report

### Issue Description
    I am trying to add an action icon that redirects to a pdf url.

### Preconditions
    1. 0.1.8

### Steps to reproduce
    1. Add this to OrderDataGrid
```
        $this->addAction([
            'title' => 'Get Label',
            'method' => 'GET',
            'route' => 'admin.sales.shipments.get_label',
            'icon' => 'icon import-icon'
        ]);
```
   2. Add this line to get_label function.
```
        return redirect()->away($url);
```
    $url is an url to a shipping label, which is pdf file.
### Expected result
    The page will redirect to the pdf file page.

### Actual result
    Nothing happens and this warning shows in the console. no redirect or new tab.
```
Resource interpreted as Document but transferred with MIME type application/pdf: XXXXXXX
```

Is the framework active some kind of cross-region or file setting?

**Comment by prashant-webkul** [comment]
@lYesterdaYl For the away URLs and adding some extra functionality, please over ride the blade files of Datagrid present in UI package. And do what ever you need.

**Comment by lYesterdaYl** [comment]
It turns out a kinda stupid mistake that when the console is active, redirect not working properly.
