### ISSUE TITLE
Getting exception while adding /editing  product using those attribute families which consists newly created checkbox type attribute. 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1638]
# Bug report

### Title
    Getting exception while adding/editing  product using those attribute families which consists newly created checkbox type attribute. 

### Issue Description
   if admin has created any check box type attribute and added that attribute with any attribute family, then while adding/editing  product getting exception
### Preconditions
    1. framework Version.v0.1.8

### Steps to reproduce

    1. step1: create checkbox type attribute and add within attribute family 
    2. step2: try to add product by selecting any option of that attribute. 

### Expected result:
product should be added successfully 
### Actual result:
getting exception
![Screenshot from 2019-10-16 16-32-20](https://user-images.githubusercontent.com/52821836/66914664-ea37c580-f034-11e9-9e39-7aba32294b4d.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

-----------------------------------------------------------

Fixed

![Screenshot (21)](https://user-images.githubusercontent.com/45203177/67851709-048f9a00-fb31-11e9-954e-0b154d5fc3cb.png)
