### ISSUE TITLE
Create Product upload image failed

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1641]
# Bug report

### Issue Description
    Unable to upload image for products. The upload was successful, which is stored under storage/app/public/product, but the image is like 404 on the page.

PS: Already run 'php artisan storage:link' which generated a shortcut on public folder to storage folder(the one on the root dir).

The image source link is like this: http://laravel.bagsito_dev/storage/product/3/D72bUUrvqzqUp2vUeweoahNGCXKIl0TuEMC8wYOF.jpeg

### Preconditions
    1. 0,1.8

### Steps to reproduce
    1. Create a product.
    2. Choose a jpg file for image.
    3. Save Product.
    4. Edit Product
### Expected result
    Image should display inside edit function.
### Actual result
    front-end and edit page show blank image.

**Comment by prashant-webkul** [comment]
@lYesterdaYl Have you run the command: **php artisan storage:link** ?

**Comment by lYesterdaYl** [comment]
Yes, I did. It generated a something like storage shortcut folder under public directory.

**Comment by prashant-webkul** [comment]
@jyoti-webkul Please verify this.

**Comment by rahulshukla-webkul** [comment]
Hi @lYesterdaYl 

Please follow the link for solution - https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions

**Comment by prashant-webkul** [comment]
@lYesterdaYl Have you set the APP_URL parameter in your **.env** file?

**Comment by lYesterdaYl** [comment]
This is my setting:

in env:
APP_URL=http://laravel.bagsito_dev

host file:
127.0.0.1       laravel.bagisto_dev

xampp vhost file:
<VirtualHost *:80>
    DocumentRoot "C:/xampp/htdocs/bagisto/public/"
    ServerName laravel.bagisto_dev
</VirtualHost>

broken image link:
http://laravel.bagsito_dev/storage/product/3/5jZTcdkCbOu16T7lmQpS0XHZYgE6nHHmFrI1b4f1.jpeg

path also stored in the database, but I am not sure why the image doesn't display.

**Comment by lYesterdaYl** [comment]
Found out the problem. I think what causes this problem is I set the domain name too long. I changed to laravel.ca which solves the problem, which is kinda strange D:
