### ISSUE TITLE
Getting exception after clicking delete button  at customer profile page  

### ISSUE THREAD

**Issue by shaiv-webkul** [bagisto/bagisto#1642]
# Bug report

### Title
Getting exception after clicking delete button  at customer profile page  
### Issue Description:
once customer is trying to delete profile, getting exception. 

### Preconditions
    1. framework Version.v0.1.8
   

### Steps to reproduce

    1. step1: sign in customer 
    2. step2: click on delete button 

### Expected result
  profile should get deleted 
### Actual result:
getting exception 
![Screenshot from 2019-10-17 09-59-26](https://user-images.githubusercontent.com/50437232/66977884-4518fd80-f0c5-11e9-81d7-c16942d9c2ef.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.7

-------------------------------------
Fixed
