### ISSUE TITLE
Showing incorrect message after clicking on apply coupon button without entering any value 

### ISSUE THREAD

**Issue by shivam-webkul** [bagisto/bagisto#1643]
# Bug report

### Title
 Showing incorrect message after clicking on apply coupon button without entering any value 
### Issue Description
 if customer has not enter any value in coupon code, and hitting on button apply coupon then getting incorrect message
### Preconditions
    1. framework Version. v0.1.8

### Steps to reproduce
    1. step1: visit at shop, and try to buy any product 
    2. step2: on order complete page click on apply coupon button without entering any value. 

### Expected result:
message should be like, enter coupon code  something like this 
### Actual result:
![Screenshot from 2019-10-17 10-11-03](https://user-images.githubusercontent.com/50355852/66978352-41867600-f0c7-11e9-85a8-1b9629f30640.png)

**Comment by jitendra-webkul** [comment]
Revamped entire discount system.
