### ISSUE TITLE
Need to add show password option in the admin-end and customer-end login page

### ISSUE THREAD

**Issue by shivam-webkul** [bagisto/bagisto#1647]
Bug report
Title
Need to add show password option in the admin-end and customer-end login page
Issue Description
Need to add show password option in the admin-end and customer-end login page
Preconditions: 

1. framework Version. v.0.1.8
Steps to reproduce
1. step1- visit admin and customer login page
Expected result:
there should be show password icon
Actual result
not getting any option to show password

**Comment by jitendra-webkul** [comment]
No need in web UI, can be added in PWA
