### ISSUE TITLE
Validation error in Phone Field while Adding Address

### ISSUE THREAD

**Issue by aayush-webkul** [bagisto/bagisto#1656]
# Bug report

### Title
    **No proper validation while adding phone numbers in the address section.**

    

### Issue Description
    1. User can add alphabets and characters in the phone field which should not be there. 
    2. Also there is no limit of adding numbers till an extend. 

### Preconditions
    **Please provide as detailed information about your environment as possible.**

    1. framework Version. Bagisto v 0.1.8 
    2. Commit id. 

### Steps to reproduce
    **It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Login as a Customer.
    2. In the left hand side menu. Find "Address" tab.
    3. Try to add and address from there and you'll find the issue 

### Expected result
    1. Customer should not able to add alphabets and special characters in phone field.
    2. There should be a limit of adding the mobile number till an extend.
![Screenshot from 2019-10-18 15-44-39](https://user-images.githubusercontent.com/53482391/67087608-e46eeb00-f1c0-11e9-92be-54884f92cbcd.png)

*    [Screenshots, logs or description]

**Comment by pathak-vikash** [comment]
Assigning to myself.
