### ISSUE TITLE
Not getting email for any action i.e, invoice,shipment,refund,order success.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1658]
# Bug report

### Title
    Not getting email for any action i.e, invoice,shipment,refund,order success.
### Issue Description
  Not getting email for any action i.e, invoice,shipment,refund,order success.
### Preconditions
   
    1. framework Version.- 0.1.8

### Steps to reproduce
   
    1. step1- Place an order
    2. step2- Generate invoice,shipment and refund

### Expected result
    Customer should receive email for all these action
### Actual result
    Not getting email

**Comment by lYesterdaYl** [comment]
It is not a bug. Email function is working on my end. Maybe your email setting is wrong.
