### ISSUE TITLE
Product doesn't get removed automatically from wish list after adding the same product from product page to cart -- bagisto-web-api

### ISSUE THREAD

**Issue by asif-webkul** [bagisto/bagisto#1662]
# Bug report

###Product doesn't get removed automatically from the wishlist,  after adding the same product from product page to cart bagisto-web-api

    after adding the product to the wishlist, when we add the product to the cart from the home page, the product doesn't get removed from the wishlist.

### Steps to reproduce
  

    1. step1  --- add the product to the wishlist
    2. step2  --- go to home page 
    3. step3  --- add the product to the cart.
    4  step4  --- check the wishlist for the customer  

### Expected result
   the same product shouldn't be in the wishlist

### Actual result
    the product is in the wishlist

**Comment by rumansaleem** [comment]
I will be working on this.

**Comment by lYesterdaYl** [comment]
should just implement the function as adding product directly from the wish list. Like adding a button, it is easier and more reasonable.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

----------------------------------------------
Currently Product  get removed automatically from all customer wishlist after adding the same product from product page to cart for any one customer-- bagisto-web-api

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

-------------------------------------------

Fixed
