### ISSUE TITLE
Category create action does not create category_translation records.

### ISSUE THREAD

**Issue by thejrace** [bagisto/bagisto#1671]
When creating categories, if there are other locales, system does not create category_translations records for other locales other than english. Therefore, when changing locales in the shop, categories is not shown in the nav bar.

Bagisto ver: 0.1.7
PHPVer: 7.3.10

**1 - Created a new category called Test. It's parent is Root.**

<img width="1610" alt="cattt1" src="https://user-images.githubusercontent.com/7458663/67145236-6c6bf800-f288-11e9-8b43-22c2ce2e5e27.png">

**When locale is English, it's seen on the shop nav bar.**

<img width="582" alt="catteo" src="https://user-images.githubusercontent.com/7458663/67145264-a89f5880-f288-11e9-94d0-ee72e331489d.png">

**2 - Now I edit the category for other locale.**

<img width="553" alt="catt2" src="https://user-images.githubusercontent.com/7458663/67145271-c7055400-f288-11e9-9747-ee9292d7b3c9.png">

**For DE locale, I save the changes.**

<img width="483" alt="catt3" src="https://user-images.githubusercontent.com/7458663/67145277-d4224300-f288-11e9-862b-fc49a4b75c0b.png">

**Got the success message afterwards.**

<img width="1816" alt="catt4" src="https://user-images.githubusercontent.com/7458663/67145280-ddabab00-f288-11e9-95f9-8878503f393d.png">

**3 - Now, I check the Shop if changes are applied or not. I change the locale from footer.**
<img width="614" alt="dasfda" src="https://user-images.githubusercontent.com/7458663/67145297-0338b480-f289-11e9-9b15-09a49d724727.png">

**But, category bar is empty as you can see from the screenshot below.**
<img width="534" alt="10-19-2019 3-53-27 PM" src="https://user-images.githubusercontent.com/7458663/67145303-121f6700-f289-11e9-838f-b99d84d73f6a.png">

**4 - When I check the category_translation table, it does not have the other locale records other than english. If I add the records manually it works.**

<img width="817" alt="catt6" src="https://user-images.githubusercontent.com/7458663/67145312-3713da00-f289-11e9-897e-4b7534079877.png">

I searched the issues in github and also the Bagisto forums. But did not find anything. I don't know if I missed anything or not.

Thank you in advance.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

-------------------------------------------
Fixed

**Comment by erandadava** [comment]
so how is it fixed? or how to do it correctly? i still cant do it

**Comment by jyoti-webkul** [comment]
Hi @erandadava 
Please take a latest pull from master, it's working now
