### ISSUE TITLE
Getting error message while running composer create-project. 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1676]
# Bug report

### Title
 Getting error message while running composer create-project. 
### Issue Description
   after git clone, when running command composer create-project, getting error message  

### Preconditions
    1. framework Version. v 0.1.8
  
### Steps to reproduce
    1. step1: git clone from master  
    2. step2: run command composer create-project 

### Expected result: 
command should execute successfully 
### Actual result:
getting error message;
![Screenshot from 2019-10-21 19-41-19](https://user-images.githubusercontent.com/52821836/67213177-2e630580-f43b-11e9-907f-8093ecdeef2d.png)

**Comment by lYesterdaYl** [comment]
you need to setup the database config in .env

**Comment by bhanu-webkul** [comment]
@lYesterdaYl  

we used to setup database config in .env post this command.

**Comment by bhanu-webkul** [comment]
framework Version. v 0.1.8

issue fixed
