### ISSUE TITLE
Responsiveness issue on iphone

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1679]
# Bug report

### Title
    Responsiveness issue on iphone
 
### Preconditions
    1. framework Version- 0.1.8

### Steps to reproduce

    1. step1- Open menu
 
### Expected result
Menu should be visible.
### Actual result
   Menu is not visible

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
 the shop is fully responsive in the latest version 1.1.x

Thanks.
