### ISSUE TITLE
php artisan route:list gives error

### ISSUE THREAD

**Issue by shivanikoko** [bagisto/bagisto#1684]
# Bug report

### Title
>**In fresh installation `php artisan route:list` gives an error as given in image**

### Issue Description
>** I just wanted to go through the routes list with artisan command `php artisan route:list` but giving me error in image.**

### Preconditions
>**bagisto fresh setup.**

    1. Latest.

### Steps to reproduce
>**Fresh Bagisto setup **

    1. hit `php artisan route:list`

### Expected result
>**It should return the list of routes**

### Actual result
 
![image](https://user-images.githubusercontent.com/12964707/67353438-37092800-f570-11e9-937d-30bc398fcfdf.png)

**Comment by rahulshukla-webkul** [comment]
Hi @shivanikoko 

Thanks for reporting this Issue. We have created PR for the same.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.7

-------------------------------------------

Fixed

![Screenshot from 2019-10-24 18-54-17](https://user-images.githubusercontent.com/45203177/67489792-c0fbe280-f68f-11e9-9671-138e814f6830.png)
