### ISSUE TITLE
moved site to https caused errors

### ISSUE THREAD

**Issue by mikeyapina** [bagisto/bagisto#1692]
I just moved my website to https when it worked perfectly prior. Now we are getting errors everywhere. What do I have to change to make this work?

M.

**Comment by rumansaleem** [comment]
I'm not sure, but forcing https scheme in the `boot` method of your `AppServiceProvider` should do the job. 

```
\URL::forceScheme('https');
```

**Comment by mikeyapina** [comment]
I am sorry I am nt seeing how to do this .. I looked up the idea of boot method for app.. but do not see an explanation on how to do this in larval.

**Comment by mikeyapina** [comment]
what I am getting is a site that has many references to http when AWS EC2 is forwarding the site to https withe load balancer.

**Comment by mikeyapina** [comment]
Mixed Content: The page at 'https://store.regenics.com/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://store.regenics.com/search'. This endpoint should be made available over a secure connection.
(index):151 Mixed Content: The page at 'https://store.regenics.com/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://store.regenics.com/search'. This endpoint should be made available over a secure connection.

**Comment by rumansaleem** [comment]
Okay, seems like the links are being generated with `http` scheme instead of `https` this can be solved using what I told before.
In your `app/Providers/AppServiceProvider.php` file add this line in the boot method so that it looks like so:
```php
    public function boot()
    {
        \URL::forceScheme('https');
    }
```

**Comment by jitendra-webkul** [comment]
I am closing this issue, I hope the above reply solved your problem.
