### ISSUE TITLE
Incorrect product price conversion for v.0.1.8

### ISSUE THREAD

**Issue by DivOverlow** [bagisto/bagisto#1704]
# Bug report

 Incorrect product price conversion for v.0.1.8

A conversion problem occurs when Base Currency and Currencies  coincide and not USD and not multicurrency option front end.
An error appears when choosing a locale English. 
For all other locales, conversion works correctly.

there were no problems for the version 0.1.7

**Comment by jyoti-webkul** [comment]
@DivOverlow 

Please mention the proper steps to reproduce this issue.

**Comment by DivOverlow** [comment]
Step by Step
1.
![image](https://user-images.githubusercontent.com/22732739/67983094-9defa680-fc2c-11e9-8f21-4aa0efd689ee.png)
2.
![image](https://user-images.githubusercontent.com/22732739/67983167-d0999f00-fc2c-11e9-8bf5-2d34c563247e.png)
3.
![image](https://user-images.githubusercontent.com/22732739/67983257-fd4db680-fc2c-11e9-8cac-473f4e3332b0.png)
4.
![image](https://user-images.githubusercontent.com/22732739/67983460-659c9800-fc2d-11e9-8cea-7af0cb2d9be5.png)
5. Front-end for all languages except English

**Comment by DivOverlow** [comment]
Price $5 * 25 (Exchange Rates) = 125  OK!

**Comment by DivOverlow** [comment]
![image](https://user-images.githubusercontent.com/22732739/67983723-f4111980-fc2d-11e9-81c8-77caca1d48d2.png)
6. For language English - Ups!
![image](https://user-images.githubusercontent.com/22732739/67983837-2d498980-fc2e-11e9-935e-981af2b07e82.png)

**Comment by jyoti-webkul** [comment]
@DivOverlow 
I have followed the steps provided by you to reproduce this issue, but at my end everything is working fine.Please take a pull from master.

**Comment by jitendra-webkul** [comment]
hi @DivOverlow 

In the edit channel page, that's not actually a Base Currency, it is channel default currency. If you want to set Base Currency, please refer to the following file.

https://github.com/bagisto/bagisto/blob/master/config/app.php

**Comment by bhanu-webkul** [comment]
Framework version v0.1.8

issue fixed
