### ISSUE TITLE
Unable to save/fetch the Categories with locale

### ISSUE THREAD

**Issue by rashidfornajah** [bagisto/bagisto#1714]
# Bug report

### Unable to save/fetch the Categories with locale
* Issue is regarding locale in Categories in Admin Panel 
  From the admin panel in saving the title,description in other language(ar) is not working. It is giving success but information is not getting saved. 

* http://domain.com/api/categories?locale=en
 http://domain.com/api/categories?locale=ar
 Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;locale&#039; in &#039;where clause&#039; (SQL: select * from categories where locale in (ar) order by id desc) in file /var/www/sites/domain.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 664
Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;locale&#039; in &#039;where clause&#039; in file /var/www/sites/domain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 63*

**Comment by rashidfornajah** [comment]
Version 0.1.8
And It was working fine on 0.1.6

**Comment by jitendra-webkul** [comment]
Please pull from master branch

**Comment by rashidfornajah** [comment]
Which commit is fixing this issue? Because pulling without release cased issues last time when we puled.

**Comment by jitendra-webkul** [comment]
Check the following PR.

https://github.com/bagisto/bagisto/pull/1681

**Comment by rashidfornajah** [comment]
Admin issue is fixed but the API issue mentioned below is still there

http://domain.com/api/categories?locale=en
http://domain.com/api/categories?locale=ar
Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'locale' in 'where clause' (SQL: select * from categories where locale in (ar) order by id desc) in file /var/www/sites/ec.e-sealed.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 664
Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'locale' in 'where clause' in file /var/www/sites/ec.e-sealed.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 63*

**Comment by rashidfornajah** [comment]
@jitendra-webkul  Any fix for this available?

**Comment by jitendra-webkul** [comment]
@rashidfornajah 

The issue has been fixed, please pull from the master branch.

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

---------------------------------------

Fixed
