### ISSUE TITLE
Discount amount doesn't get removed if cart rule is created for guest user and at time of checkout customer logged in.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1717]
# Bug report

### Title
Discount amount doesn't get removed if cart rule is created for guest user and at time of checkout customer logged in.
### Issue Description
Discount amount doesn't get removed if cart rule is created for guest user and at time of checkout customer logged in.

### Preconditions

    1. framework Version.- 0.1.8

### Steps to reproduce
    1. step1- Create a cart rule for customer group Guest
    2. step2- At time of checkout sign-in

### Expected result
Discount amount should get removed

### Actual result

Discount not removed

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
