### ISSUE TITLE
Cart rule not getting applies if any Category is selected in "How to Choose Product" while creating cart rule.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1723]
# Bug report

### Title
Cart rule not getting applies if any Category is selected in "How to Choose Product" while creating cart rule.
### Issue Description
Cart rule not getting applies if any Category is selected in "How to Choose Product" while creating cart rule.

### Preconditions

    1. framework Version-0.1.8
   
### Steps to reproduce

    1. step1- Create a cart rule and select any Category from "How to Choose Product section"
 
### Expected result
Discount should get applied on product belongs to that category.

### Actual result

Discount not getting applied.

**Comment by prashant-webkul** [comment]
Not getting this issue.

**Comment by inimist** [comment]
Any update on this?? Cart rules not been applied at all!! Very frustrating :(

**Comment by jyoti-webkul** [comment]
@inimist 
Which bagisto version you are using?

**Comment by inimist** [comment]
v0.1.0

**Comment by inimist** [comment]
I installed it using `composer create-project bagisto/bagisto`. I am not sure whether I should try to update it to latest stable version. I am also not sure how to do that. Can you please help me with this? I really need to let client know whether we should stay with bagisto as a ecommerce platform for his  business.

**Comment by jyoti-webkul** [comment]
@inimist 
Please use our latest version 0.2.2 from here.
https://github.com/bagisto/bagisto/releases/tag/v0.2.2

**Comment by inimist** [comment]
How to update it?

**Comment by jyoti-webkul** [comment]
Have you installed 0.1.7 version through zip file?

**Comment by inimist** [comment]
Please message above:

I installed it using `composer create-project bagisto/bagisto`. I am not sure whether I should try to update it to latest stable version. I am also not sure how to do that. Can you please help me with this? I really need to let client know whether we should stay with bagisto as a ecommerce platform for his business.

**Comment by inimist** [comment]
Should I download zip and replace in `packages/Webkul`?? Should I also update composer.json in root for :

```
"replace": {
      "bagisto/laravel-user": "v0.1.0",
      "bagisto/laravel-admin": "v0.1.0",
      "bagisto/laravel-ui": "v0.1.0",
      "bagisto/laravel-core": "v0.1.0",
      "bagisto/laravel-attribute": "v0.1.0",
      "bagisto/laravel-checkout": "v0.1.0",
      "bagisto/laravel-customer": "v0.1.0",
      "bagisto/laravel-inventory": "v0.1.0",
      "bagisto/laravel-category": "v0.1.0",
      "bagisto/laravel-product": "v0.1.0",
      "bagisto/laravel-shop": "v0.1.0",
      "bagisto/laravel-theme": "v0.1.0",
      "bagisto/laravel-shipping": "v0.1.0",
      "bagisto/laravel-payment": "v0.1.0",
      "bagisto/laravel-sales": "v0.1.0",
      "bagisto/laravel-tax": "v0.1.0",
      "bagisto/laravel-api": "v0.1.0",
      "bagisto/laravel-paypal": "v0.1.0",
      "bagisto/laravel-discount": "v0.1.0"
    },
```

??

**Comment by jyoti-webkul** [comment]
Install new one and use your existing database

**Comment by inimist** [comment]
Installed and Cart rules are working! (u)

However Currencies are not working now :(

I created new currency and set exchange rate for it. But it does not show the currency dropdown in header now. Is there a new bug?

**Comment by jyoti-webkul** [comment]
Have you selected that currency in channel?

**Comment by inimist** [comment]
Installed v0.2.2 and cart rules are working now! :+1:

**Comment by inimist** [comment]
> Have you selected that currency in channel?

Yes sorry I had not select it in Channel. It is working fine now.

Ps. I did a fresh install (created new db) with v0.2.2 to avoid any conflicts. All looks good now. Thanks! :+1:

**Comment by jitendra-webkul** [comment]
Revamped the entire discount system.
