### ISSUE TITLE
Getting exception on Buy Now, if cart rule have created using action "Adjust whole cart to fixed amount " or "Adjust whole cart to percentage" is selected.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1728]
# Bug report

### Title
Getting exception on Buy Now.
### Issue Description
Getting exception on Buy Now.

### Preconditions
    1. framework Version-0.1.8

### Steps to reproduce

    1. step1- Create a cart rule using  "Adjust whole cart to fixed amount " or "Adjust whole cart to percentage"
    2. step2- Click on Buy Now for any Product.

### Expected result
User should redirect to checkout page
### Actual result

![Screenshot from 2019-11-01 16-56-10](https://user-images.githubusercontent.com/45203177/68022070-3b001d00-fcc9-11e9-81ed-fc75d68f6513.png)

**Comment by bhanu-webkul** [comment]
framework Version-0.1.8

issue fixed
