### ISSUE TITLE
 Could not scan for classes inside bagisto/vendor/phpunit/phpunit/src/

### ISSUE THREAD

**Issue by senbai** [bagisto/bagisto#1731]
PHP version: 7.2.24
laravel 5.6.*
bagisto v 0.1.
composer 1.6.3

would you help me with this issue:
when i run composer dump-autoload after installing bagisto i got this:

In ClassMapGenerator.php line 69:
                                                                               
  Could not scan for classes inside "/xx/xx//bagisto/ven
  dor/phpunit/phpunit/src/" which does not appear to be a file nor a folder

**Comment by rahulshukla-webkul** [comment]
Hi @senbai 

Delete your vendor folder and once again run 

`composer install`

at root of your project and then check.

**Comment by jitendra-webkul** [comment]
Closing this issue, I hope the above reply solved your problem.
