### ISSUE TITLE
Get Categories API not working with Locale

### ISSUE THREAD

**Issue by rashidfornajah** [bagisto/bagisto#1732]
# Bug report

### Get Categories API not working with Locale
**Trying to get All Categories API not working with Locale en or ar**

### Preconditions
**Create  some categories with English and Arabic Locale**

    1. framework Version 0.1.8.

### Steps to reproduce
**http://domain.com/api/categories?locale=en**
**http://domain.com/api/categories?locale=ar**

### Expected result
**All Categories should come**

*   [Screenshots, logs or description]

### Actual result
Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'locale' in 'where clause' (SQL: select * from categories where locale in (ar) order by id desc) in file /var/www/sites/domain.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 664
Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'locale' in 'where clause' in file /var/www/sites/domain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 63*

**Comment by rahulshukla-webkul** [comment]
Hi @rashidfornajah 

Categories is not locale based, each categories has parent category and it can be used as root category for any channel and channel has default locales including other locales.

**Comment by rashidfornajah** [comment]
@jitendra-webkul Thanks a lot

**Comment by rashidfornajah** [comment]
@jitendra-webkul  Why above fix is not working for ??
 http(s)://example.com/public/api/wishlist?locale=en
 http(s)://example.com/public/api/wishlist?locale=ar

**Comment by jitendra-webkul** [comment]
I checked it is working with locales, please check out the following attached image.

![Screenshot from 2019-11-06 10:24:33](https://user-images.githubusercontent.com/39991107/68269447-dd305400-007f-11ea-85b0-80fb40ef5b9f.png)


I

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.8

--------------------------------------
Fixed

![Screenshot from 2019-11-07 13-57-49](https://user-images.githubusercontent.com/45203177/68372319-9e28fe00-0166-11ea-9114-574942b591b9.png)
