### ISSUE TITLE
Get Wishlist API returning all wishlist of other users also

### ISSUE THREAD

**Issue by rashidfornajah** [bagisto/bagisto#1742]
# Bug report

### Preconditions
**Other users should also have some wishlist**
    1. Framework Version 0.1.8.

### Steps to reproduce
**Make some list of wishlist for multiple users**
    1. http(s)://example.com/public/api/wishlist

### Expected result
**Wishlist for the particular user only**

**Comment by jitendra-webkul** [comment]
Hi @rashidfornajah 

You can pass current customer_id, in order to get particular customer's wishlist.

http(s)://example.com/public/api/wishlist?customer_id=1

**Comment by jitendra-webkul** [comment]
Closing this issue, I hope the above reply solved your problem.

**Comment by rashidfornajah** [comment]
Yes. Thanks
