### ISSUE TITLE
ValidateForm returns false

### ISSUE THREAD

**Issue by Bilgee** [bagisto/bagisto#1746]
When saving a billing address, ValidateForm returns false value and does not show any error messages. Also the continue button does not work.
I checked ValidateForm function. 
this.$validator.validateAll(scope).then(function (result) {
                        console.log(result);
});
It shows false value. Also I cannot find validation rules. 
How do you change validation rules?

**Comment by bhanu-webkul** [comment]
Framework version: 0.1.8

issue fixed
