### ISSUE TITLE
Install css like font-awesome for the project

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1751]
Maybe this is a noob question. How do I properly install font awesome into the project?

And also, how to change current css and recompile them into new scss?

**Comment by shaiv-webkul** [comment]
To install the font awesome you to override the following file webkul/shop/src/resources/views/layouts/header/master.blade.php and in the head tag you can add font awesome cdn.
To change the current css you can create your own theme, for theme creation please visit this link
https://bagisto.com/en/create-custom-theme-in-bagisto/

**Comment by jitendra-webkul** [comment]
I am closing this issue, I hope the above reply solved your problem.
