### ISSUE TITLE
Carousel slider for bootstrap not working

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1752]
https://getbootstrap.com/docs/4.0/components/carousel/

How do I make this work? I directly copied code from above link and paste into the project, but all images show at the same time.
![image](https://user-images.githubusercontent.com/5135163/68436301-7f306900-0172-11ea-8d61-f84b1f831685.png)

**Comment by rahulshukla-webkul** [comment]
Hi @lYesterdaYl 

Did you included  JS and CSS of bootstrap 4 and one more thing that you can create different sliders in our application  for a particular channel.

Thanks

**Comment by jitendra-webkul** [comment]
I am closing this issue, I hope the above reply solved your problem.
