### ISSUE TITLE
Add Codeception as testing framework

### ISSUE THREAD

**Issue by bosix** [bagisto/bagisto#1754]
Bagistos repository does not contain tests or a configured testing framework.

**Suggesstion**
Add codeception (https://codeception.com) as the testing framework and add some example tests to be able to check functionality of bagisto via an automated test framework.

_Note_: I'll add the necessary changes to this issue by myself. You can have a look through it and decide if codeception will be used for bagisto.

**Comment by rahulshukla-webkul** [comment]
Hi @bosix 

Thanks for your suggestions, you we will check and then decide.

**Comment by bosix** [comment]
Hi @rahulshukla-webkul 

thank you for your patience.

I've prepared a pr with all needed changes needed to add codeception to bagisto. You can also find two tests inside it: one to check if a product can be created proper via admin backend and one to check if the `hasVariants()` works correctly. 

Keep in mind that codeception devides tests into multiple suites. The basic ones are unit, functional and acceptance. If you'd like to have more information about them, just let me know or take a look at the codeception [documentation](https://codeception.com/docs/01-Introduction).

If you agree with this pr I suggest that tests for checkout and price-calculation should be written first. Bagisto is a huge application and it will take some time to get a nice test-coverage.

**Comment by SteffenMahler** [comment]
It would be nice to see codeception as testing framework in bagisto.

**Comment by bosix** [comment]
Hi @rahulshukla-webkul,

since the corresponding pr ist merged, this issue can be closed.

Thank you.
