### ISSUE TITLE
Error when AFK at OnePage pages for a while

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1756]
# Bug report

### Issue Description
Error occurs when user afk at the onepage pages for a while, system logs him out and the cart has nothing which has exception of "Trying to get property of non-object"

![image](https://user-images.githubusercontent.com/5135163/68611710-9a032600-046f-11ea-9efe-9cc8d51486a0.png)

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. 0.1.8

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. add an item in the cart while login
    2. press checkout, then wait at any of first 3 pages
    3. not sure how long it should wait, but you wait until system logs user out.
    4. refresh and get the error

**Comment by rahulshukla-webkul** [comment]
Hi @lYesterdaYl 

Thanks for notifying this to us.

**Comment by jitendra-webkul** [comment]
Fixed in master
