### ISSUE TITLE
Getting translation issue while moving configurable and simple product from wishlist to cart. 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1764]
# Bug report

### Title
Getting translation issue while moving configurable/simple product from wishlist to cart. 

### Issue Description:
Getting translation issue while moving configurable& simple product from wishlist to cart. 
### Preconditions:
    1. framework Version. -master

### Steps to reproduce
    1. step1: add configurable/simple product to wishlist 
    2. step2: move to cart from wishlist

### Expected result:
correct message should be displayed
### Actual result
translation issue

configurable product:- 
![Screenshot (83)](https://user-images.githubusercontent.com/52821836/68761229-aa66fc80-0639-11ea-9fdc-2934fdef2ad7.png)

Simple Product:-

![Screenshot - 2019-12-11T152907 474](https://user-images.githubusercontent.com/52821836/70611393-22214a80-1c2b-11ea-8621-bbaad68a55a9.png)

**Comment by bhanu-webkul** [comment]
same issue found while moving product to wishlist from cart.

![Screenshot - 2019-12-14T130906 146](https://user-images.githubusercontent.com/52821836/70845301-fbedeb80-1e72-11ea-9fd7-ed0a9c7f6ec4.png)

**Comment by jitendra-webkul** [comment]
Fixed in master

**Comment by bhanu-webkul** [comment]
Still same issue in master

**Comment by bhanu-webkul** [comment]
Fixed in master
