### ISSUE TITLE
I think that is a bugs.

### ISSUE THREAD

**Issue by silasyao** [bagisto/bagisto#1771]
# Bug report

just browse the
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Product/src/Listeners/ProductFlat.php#L34

line 235, 
you will see:

`$attributeOption = $this->attributeOptionRepository->find($product->{$attribute->code});`

the attributeOptionRepository 's find method, there need a parameter for ID key.  but the `$product->{$attribute->code})` the $product is the product object, which not have attribute code column( just like color,size attribute). so the result will always the null value.

**Comment by jitendra-webkul** [comment]
We are getting product attribute value from product_attribute_value table. Please follow the following link

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Product/src/Models/Product.php#L259
