### ISSUE TITLE
Master and versioning out of sync

### ISSUE THREAD

**Issue by traceyjas** [bagisto/bagisto#1772]
# Bug report

Good Day,

I am trying to use your project however i realize what is on master and what is installed as the latest version 0.18 is different?

Is this a bug or am i doing something wrong?

**Comment by jitendra-webkul** [comment]
This is not a bug, 0.1.8 is our recent stable version.

In master branch contains code for our upcoming major release which will include a bunch of new features and a more stable code structure.

**Comment by traceyjas** [comment]
Ok thanks
