### ISSUE TITLE
Disallow guest checkout

### ISSUE THREAD

**Issue by traceyjas** [bagisto/bagisto#1773]
How to prevent user from checkout if he is not not signed in or doesn't have account?

**Comment by rahulshukla-webkul** [comment]
Hello @traceyjas 

Find 'onepage.blade.php' file is in shop package's checkout folder, first you need to override this page for which you can follow the given article- https://forums.bagisto.com/topic/221/how-to-override-view-file-in-bagisto, this file is responsible for all checkout process.

If you see this file , then you will find a component called as 'checkout' which is working without any condition whether is guest or customer.

So, you can apply check on this component like -    

` @if (auth()->guard('customer')->user())
        <checkout></checkout>
    @else
        <h3> 'Please sign IN' </h3>
    @endif`

In above sections else method you can provide button for sign In or message according to need.

**Comment by bhanu-webkul** [comment]
Feature added in Master, Now admin can allow/disallow guest checkout product wise .

![Screenshot - 2020-01-24T092749 792](https://user-images.githubusercontent.com/52821836/73043580-cf72b980-3e8b-11ea-8093-0e27e80e04b6.png)
