### ISSUE TITLE
Calendar format

### ISSUE THREAD

**Issue by JuanSinmiedo466** [bagisto/bagisto#1776]
Hello, and thanks for this fantastic product.

It is possible to show the calendar in other formats other than English?

In Spanish for example, the format is DD-MM-YYYY.

Tanks!
![Selección_438](https://user-images.githubusercontent.com/57934466/69121516-d4d31280-0a9c-11ea-9f18-3b8e1229503a.png)

**Comment by rahulshukla-webkul** [comment]
Hello @JuanSinmiedo466 

We have used Flat-picker for date , so you can change the date format and can get it to desired language.
Please follow the given article - https://flatpickr.js.org/localization/.

Thanks

**Comment by shdehnavi** [comment]
Hi
Which file contains flatpickr configurations in bagisto ?

**Comment by michael-arif** [comment]
I need to localize flatpickr to Japanese language.
Where should I put the ja.ts file?

**Comment by rahulshukla-webkul** [comment]
Hi @michael-arif 

You don't need put this file any where as **flatpicker** already consist this language file, you just need to change locale after including this file.

Just read the given article.

**Comment by jitendra-webkul** [comment]
I am closing this issue, I hope the above reply solved your issue
