### ISSUE TITLE
Tax is not getting applied according to assigned tax category assigned to particular variant 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1780]
# Bug report

### Title
Tax is not getting applied according to assigned tax category to particular variant 

### Issue Description
if we have multiple tax categories and while creating configurable product admin has been assigned different tax categories to all variants. then while checkout tax is not getting applied according to assigned tax category to that variant 

### Preconditions

    1. framework Version. 0.1.8
### Steps to reproduce
    1. step1: create multiple tax rates and tax categories 
    2. step2: create  a configurable product and assign different tax category to all variant. 
    3. step3: add to cart any variant and select shipping address accordingly 

### Expected result:
should  get applied according to individual tax category assigned to variant.  
### Actual result:
 not applied

**Comment by dejavuejs** [comment]
Variant cannot be assigned with a tax category, only parent will do it.

**Comment by jitendra-webkul** [comment]
Tax will work only for parent products.
