### ISSUE TITLE
Password should be mandatory field on checkout page  in case email id already registered. 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1784]
# Bug report

### Title:
Password should be mandatory field on checkout page  in case email id already registered. 
### Issue Description:
if customer has already registered with that email id then password should be mandatory
### Preconditions
    1. framework Version: 0.1.8
### Steps to reproduce:

    1. step1: Register a customer 
    2. step2:use same mail for shopping as guest user 

### Expected result:
should ask to enter password
### Actual result:
able to proceed further with out login with registered mail id

![Screenshot - 2019-11-22T151908 422](https://user-images.githubusercontent.com/52821836/69416229-2816c080-0d3c-11ea-84b0-f00150375d6c.png)

**Comment by ghermans** [comment]
Fixed in master branch.

## Screenshot
![aaaaaaa](https://user-images.githubusercontent.com/1594411/104794027-6293b600-57a5-11eb-91ad-553742da4f44.PNG)
