### ISSUE TITLE
Slider image is not working fine 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1786]
# Bug report

### Title
Slider image is not working fine 
### Issue Description:

With some pictures, slider image is not coming properly 
### Preconditions
    1. framework Version.0.1.8
### Steps to reproduce
    1. step1: create slider 
    2. step2: visit shop

### Expected result:
![Screenshot - 2019-11-22T170650 172](https://user-images.githubusercontent.com/52821836/69422749-7e8afb80-0d4a-11ea-9c0a-00ee9cb4acf1.png)

### Actual result
![Screenshot - 2019-11-22T170210 371](https://user-images.githubusercontent.com/52821836/69422760-864aa000-0d4a-11ea-88e7-b76d3ab0da94.png)

**Comment by muhammadasimhamza** [comment]
I am uploading slider images but they are not loading at all. Seems like the path is not working.

**Comment by jitendra-webkul** [comment]
@muhammadasimhamza please refer to the following link

https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions/4

**Comment by bhanu-webkul** [comment]
Fixed in master
