### ISSUE TITLE
Session Timeout Redirection Error

### ISSUE THREAD

**Issue by hirenreshamwala** [bagisto/bagisto#1787]
# Session Timeout Redirection Error

Hello,

After long time inactive on admin, when user click on any link the expected result should be session goes timeout and redirect to login page. In this system I found session goes timeout but error page appears with exception 
    
    "Route [auth.login] not defined."

This error looks like route not found. When I backtrack the exception I found on exception handler page while exception throws it redirects to "auth.login"

### Exception page: packages/Webkul/Admin/src/Exceptions/Handler.php:59

    protected function unauthenticated($request, AuthenticationException $exception)
    {
        if ($request->expectsJson()) {
            return response()->json(['error' => $this->jsonErrorMessages[401]], 401);
        }

        return redirect()->guest(route('auth.login'));
    }

But I never found any routing rule in hole application like "auth.login"

#### Screenshot
[https://drive.google.com/file/d/1tt5tA5BPKEpHhnSPDSWoFjFE7FRLLWHl/view?usp=sharing](url)

**Comment by rahulshukla-webkul** [comment]
Hi @hirenreshamwala 

We have fixed this one. Thanks for notifying to us.
