### ISSUE TITLE
Update to laravel 6

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#1790]
is there any chance that this package and project will move to laravel 6 ?? or if we move it to laravel 6 will any features break or not ??
 thanks

**Comment by thyseus** [comment]
concord (https://github.com/artkonekt/concord/blob/master/Changelog.md) just released v1.4.0 which is a major dependency on making the jump to laravel 6.

**Comment by farshadff** [comment]
@thyseus  thanks i am going to contribute to it so we can make it faster and sorry havent seen them before opening this issue
