### ISSUE TITLE
Revenue is always $0.00 in dashboard section of "Customer with most sales"

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1792]
# Bug report

### Title
Revenue is always $0.00 in dashboard section of "Customer with most sales"
### Issue Description
Revenue is always $0.00 in dashboard section of "Customer with most sales"
### Preconditions

    1. framework Version.-0.1.8

### Steps to reproduce

    1. step1- Place an order by logging in with any user, generate invoice and shipment.
    2. step2- Go to dashboard and check Customer with most sales section.

### Expected result

It should show the amount of order placed by that customer
### Actual result

Always shows zero.
![Screenshot (37)](https://user-images.githubusercontent.com/45203177/69524064-445c6c80-0f8b-11ea-87b3-ecbf7ac1d2c5.png)

**Comment by bhanu-webkul** [comment]
framework version: 0.1.9

issue fixed
