### ISSUE TITLE
Bootstrap Layout got mass up by ui.css

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1794]
# Bug report

### Title
ui.css massed up bootstrap grid layout.

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. 0.1.8

### Steps to reproduce

```
        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" style="background-color:red;">Span 5</div>
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3" style="background-color:blue">Span 3</div>
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-2" style="padding:0px">
                    <div class="short-div" style="background-color:green">Span 2</div>
                    <div class="short-div" style="background-color:purple">Span 2</div>
                    <div class="short-div" style="background-color:purple">Span 2</div>

                </div>
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-2" style="background-color:yellow;">Span 2</div>
            </div>
        </div>

```

### Expected result

![image](https://user-images.githubusercontent.com/5135163/69567576-81fecc80-0f6e-11ea-92be-0c97d32f6e9e.png)

### Actual result

![image](https://user-images.githubusercontent.com/5135163/69567532-68f61b80-0f6e-11ea-804c-37812cd9dbdf.png)

**Comment by dejavuejs** [comment]
Yeah obviously it could happen as there is possibility of classes used in TWBS and Bagisto are same.

**Comment by jitendra-webkul** [comment]
I am closing this, I hope your issue gets resolved
