### ISSUE TITLE
Grammatical errors In Bagisto's documentation .

### ISSUE THREAD

**Issue by AayushB18** [bagisto/bagisto#1796]
# Bug report

### Title
**English grammatical errors in Bagisto's documentation**

### Issue Description
**There are many grammatical and spelling errors in the documentation of Bagisto**

### Preconditions
**detailed information about the environment**

    1. version 0.1.8

### Steps to reproduce

    1. Open https://devdocs.bagisto.com/

### Expected result
**Grammatical and spelling errors should not be there**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.
![grammererrors](https://user-images.githubusercontent.com/38464980/69612215-412db300-1055-11ea-8c4a-41a3d7e3a178.png)
**

* [points....]

**Comment by bhanu-webkul** [comment]
Please raise doc related issues here -https://github.com/bagisto/bagisto-docs/issues
