### ISSUE TITLE
How to change slider to support video?

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1799]
I want to use a slider that supports video, but the backend doesn't support uploading video. How do I remove this limit? I tried to change the image-item.vue, but it doesn't work for me.

**Comment by dejavuejs** [comment]
You need to override create and edit form of slider and create a field for video upload instead of image and you need to override the slider component present in shop package also in order to autoplay the video by using JS or Vue.

**Comment by lYesterdaYl** [comment]
> You need to override create and edit form of slider and create a field for video upload instead of image and you need to override the slider component present in shop package also in order to autoplay the video by using JS or Vue.

Yes, I know that. Sorry,  I meant to ask how to change the back-end file uploading code, so it allows me to upload video extension file, like mp4. I tried to change the image-item.vue which controls the invalid file format, but it doesn't work. Do I need to run some commands to update the changed image-item.vue file?

**Comment by lYesterdaYl** [comment]
any helps on this?

**Comment by rahulshukla-webkul** [comment]
Hi @lYesterdaYl 
 
First create a package, override view file of slider (edit and create) to provide field for video upload, then will call your controllers, write your code to upload video file here.

Then you need to override 'silder.blade.php' file of shop package, and need to create your view which can play video file.

For this you need to override slider model, you can follow this one for the same - https://devdocs.bagisto.com/override-core-model.html.

**Note** -  Slider edit and create will be done from your packages controller.
