### ISSUE TITLE
Event listener not getting called for text change

### ISSUE THREAD

**Issue by rashidfornajah** [bagisto/bagisto#1801]
# Bug report

### Event listener not getting called for text change
**Create Address (create.blade.php) id="phone-number" addEventListener("change",function ()  is not being called

### Issue Description
**Create Address blade file (create.blade.php) id="phone-number" having addEventListener("change",function ())  is not being called in javascript**
**Is there something consuming the event before reaches my code?**

### Steps to reproduce
*Write a javascript code to add event listener*

*window.onload = function() {
       document.getElementById('phone-number').addEventListener('change', updateSignInButtonUI);
}*

https://www.codeproject.com/Articles/1256245/Integrate-Firebase-Phone-Authentication-With-Larav

### Expected result
**Registered handler should get called.**

### Actual result

>    **Registered handler not getting called**

**Comment by jitendra-webkul** [comment]
I checked and it's working fine.
