### ISSUE TITLE
change admin panel language in setting

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#1803]
hi i want to know how can i change the language in my admin panel and shop i want to set for ex . ar the default lang now here is what i have tried :
```
https://forums.bagisto.com/topic/15/language-translations/2
```
but no luck with it my language in site and admin panel wont change !!! any idea ??

**Comment by shivam-webkul** [comment]
hi @farshadff 

You can follow guide for admin as well as shop translations 
https://bagisto.com/en/ecommerce-language-translation-in-bagisto/

**Comment by jitendra-webkul** [comment]
I hope you have found the solution, so I am closing this issue.
