### ISSUE TITLE
Error Front End View CMS-page NewsLetter Subscription selected on

### ISSUE THREAD

**Issue by DivOverlow** [bagisto/bagisto#1804]
# Bug report
framework Version 0.1.8

### Title
Error Front End View CMS-page NewsLetter Subscription selected on

### Issue Description
When subscription is disabled no problemm. 
If you enable the admin panel NewsLetter Subscription
![image](https://user-images.githubusercontent.com/22732739/69763904-4f73f000-1177-11ea-8202-04f9cd931e21.png)
Any CMS page is not view, results empty page view example
![image](https://user-images.githubusercontent.com/22732739/69764138-fbb5d680-1177-11ea-903d-ad718b55d923.png)

The source code of the page is there maybe a reason in this block?
![image](https://user-images.githubusercontent.com/22732739/69764519-3ff5a680-1179-11ea-927e-65a3b4680705.png)

**Comment by dejavuejs** [comment]
Please specify your APP_URL param in .env file properly and the CMS pages and end points will work properly after that.

I see your url -> **bagisto/page/about-us** is not a valid URL format.

**Comment by DivOverlow** [comment]
Here are my param APP_URL=http://bagisto. 
After all, the page is fully rendered, only the browser doesn’t like something in the block body

**Comment by DivOverlow** [comment]
O found this bug!
in file
packages/Webkul/Shop/src/Resources/views/cms/page.blade.php
comment out line 28
    <script src="{{ asset('themes/default/assets/js/shop.js') }}" type="text/javascript"></script>
this code duplicates layouts\master.blade.php

Thanks to All :)

**Comment by DivOverlow** [comment]
add comment out line 20
    <link href="{{ asset('themes/default/assets/css/shop.css') }}" rel="stylesheet" />
this code duplicates layouts\master.blade.php
everything is fine now )

**Comment by DivOverlow** [comment]
add comment line 20 - this code duplicates layouts\master.blade.php
Now everything is fine!

**Comment by jitendra-webkul** [comment]
Fixed in #2026
