### ISSUE TITLE
Bagisto API is not versioned

### ISSUE THREAD

**Issue by thyseus** [bagisto/bagisto#1805]
Currently, the API endpoints of the bagisto e commerce application are not versioned. This is bad when having an application that already has consumers attached to their API and want to do breaking changes or introduce new features.

I propose to use a solution like described in this blog post:
https://medium.com/@juampi92/api-versioning-using-laravels-resources-b1687a6d2c22

what are your opinions about this ?

**Comment by farshadff** [comment]
i think its better to use dingo package for this and easily version your api its so clean and easy to work with :
```
https://github.com/dingo/api
```

**Comment by thyseus** [comment]
Dingo looks great - didnt knew it yet (thanks for that) - but i fear that all the already existing API endpoints needs to be rewritten to use the dingo library ? 

```
$ php artisan route:list | grep API | wc -l
> 60
```

**Comment by farshadff** [comment]
no you just need to change some simple routes syntax  and put them in some middlle ware like below : 
```
$api->version('v1', function (Router $api) {
    $api->group(['prefix' => 'v1'], function(Router $api) {
        $api->group(['middleware' => 'bindings'], function(Router $api) {
```
and some change in syntax like this : 
```
  $api->post
```
the documentaion of that package is really clear and complete

**Comment by rahulshukla-webkul** [comment]
Hi @thyseus @farshadff 

Thanks for your suggestions, we will soon update API with version.

**Comment by farshadff** [comment]
@rahulshukla-webkul i need a way to contact you if possible send me your email or some thin i need to talk to you about contributing to this project thanks ,

**Comment by rahulshukla-webkul** [comment]
Hi @farshadff 

As you know, this project is opensource so you can directly contribute in this project with PR request, if you do have any suggestions are query or anything related to this project, then we can communicate here or you can raise the same at our forums -  https://forums.bagisto.com

Thanks for showing interest in our project.

**Comment by phillipcodes** [comment]
+1 when do you plan to implement api versioning?

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I am just checking out this issue. I haven't seen any major changes in the API, even we have not changed even a single key except additions of the new key.

Versioning can only be possible if the existing project is broken due to the current version release.

Otherwise i am not seeing any point of versioning the API because this will increase the route groupings.
