### ISSUE TITLE
costum theme not showing up

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#1809]
i have created new theme and made changed on cofig file like below :
```
<?php

return [
    'default' => 'bootstrap',

    'themes' => [
        'default' => [
            'views_path' => 'resources/themes/default/views',
            'assets_path' => 'public/themes/default/assets',
            'name' => 'Default'
        ],

         'bootstrap' => [
             'views_path' => 'resources/themes/bootstrap/views',
             'assets_path' => 'public/themes/bootstrap/assets',
             'name' => 'bootstrap',
         ]
    ]
];
```
but yet again application refers to default theme i tried `config:clear` and  `cache:clear` but none work . any idea how to call new theme or even how to add boostrap to the default theme ??

**Comment by farshadff** [comment]
I ended up commenting the default theme so the new theme can be loaded .

**Comment by Asef00** [comment]
In my case I used the following commands:
`
php artisan view:clear
php artisan config:cache
php artisan serve
`
