### ISSUE TITLE
Grammatical error in welcome message in terminal at Bagisto installation.

### ISSUE THREAD

**Issue by AayushBhatt-webkul** [bagisto/bagisto#1810]
# Bug report

### Title
Double "top of" in welcome message in terminal at installation i.e. ( top of top of )

### Issue Description
After running the command "composer create-project" a welcome message appears which says:
Welcome to the Bagisto project! Bagisto Community is an open-source e-commerce ecosystem 
which is built on **_top of top of_** Laravel and Vue.js

### Preconditions

    1. framework Version: Laravel 5.6.39 | Bagisto 0.1.8

### Steps to reproduce

    1. Clone the Bagisto project and run the command "composer create-project".
    2. Check for the welcome message at the bottom.

### Expected result

Welcome to the Bagisto project! Bagisto Community is an open-source e-commerce ecosystem 
which is built on **_top of_** Laravel and Vue.js.

### Actual result

Welcome to the Bagisto project! Bagisto Community is an open-source e-commerce ecosystem 
which is built on **_top of top of_** Laravel and Vue.js.

![installbug](https://user-images.githubusercontent.com/38464980/69865998-d97f9e00-12c8-11ea-838d-5d90d4d0fdc8.png)

**Comment by bhanu-webkul** [comment]
Done
