### ISSUE TITLE
Remove laravel web console (negative scenarios possible with SAAS)

### ISSUE THREAD

**Issue by prashantblr** [bagisto/bagisto#1819]
# Bug report

### Title
**Remove the Laravel web console dependency.**

### Issue Description
**Remove this immediately. No one needs SSH from admin panel. It will also void the scenarios when using SAAS as all tenants would be able to use SSH.

It automatically creates security issue when SAAS is used with current master builds..**

### Preconditions

    1. Master branch.

### Steps to reproduce
**Install Bagisto with SAAS, throughout each tenant when created through admin panel any admin can access the server.**

**Comment by thyseus** [comment]
Please see https://github.com/bagisto/bagisto/pull/1791

**Comment by prashantblr** [comment]
Issue resolved, thanks.
