### ISSUE TITLE
The dependency nwidart/laravel-modules is not used anywhere

### ISSUE THREAD

**Issue by popperhead** [bagisto/bagisto#1820]
# Bug report

### Title
**On my lookup in this repository the package nwidart/laravel-modules is listed in composer.json but i cannot see its use anywhere throughout the core packages.**

Please close issue if its used anywhere.

**Comment by rahulshukla-webkul** [comment]
Hi @prashantblr 

You are right, this dependency is not used anywhere, we will remove this one.
Thanks for notifying to us.

**Comment by jitendra-webkul** [comment]
Removed in #2025
