### ISSUE TITLE
Getting exception after clicking on developement. 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1823]
# Bug report

### Title
Getting exception after clicking on developement. 

### Preconditions
    1. framework Version.0.1.8
### Steps to reproduce

    1. step1: visit admin panel click on setting>development 

 

### Expected result
there should not be any exception 
### Actual result
getting exception 
![Screenshot - 2019-12-03T155916 566](https://user-images.githubusercontent.com/52821836/70043352-528f3600-15e6-11ea-9d7a-fc07b0fef725.png)

**Comment by rahulshukla-webkul** [comment]
Hi @bhanu-webkul 

Web console has been removed. Kindly close this issue.
