### ISSUE TITLE
In Target Currency dropdown , currencies for which rate has already been set should not display in dropdown.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#183]
Framework Version: 0.1.1
![screenshot 16](https://user-images.githubusercontent.com/45203177/49084850-a306e180-f276-11e8-9bc0-fd40e782286d.png)

**Comment by rahulshukla-webkul** [comment]
Changed it according to mentioned title.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
