### ISSUE TITLE
Mass Action Crashes the system

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1844]
# Bug report

### Title
Mass Action Crash the system

### Issue Description
This occurs to all mass actions.

### Preconditions

    1. 0.1.8

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. get to a page that has mass action, for example, product page.
    2. click the check box that do the all select.
    3. choose a mass action, for example, update status -> active. BUT DO NOT SUBMIT NOW
    4. Now, click the all select check box again to deselect all items.
    5. finally, select any row will active the action update status -> active again, now press submit. The system will crash and show error 500.

**Comment by rahulshukla-webkul** [comment]
Hi @lYesterdaYl 

Thanks for raising this issue, we will soon fix this one.

**Comment by rahulshukla-webkul** [comment]
Hi @lYesterdaYl 

We have fixed this issue, you can pull from master branch.

**Comment by bhanu-webkul** [comment]
framework version: 0.1.8

issue fixed
