### ISSUE TITLE
Wrong order id is coming after placing order if admin has configured order setting.

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1848]
# Bug report

### Title

Wrong order id is coming after placing order if admin has configured order setting.
### Preconditions
    1. framework Version. 0.1.8
### Steps to reproduce

    1. step1: configure order setting 
    2. step2: place an order and check order id

### Actual result:
![Screenshot from 2019-12-05 12-09-04](https://user-images.githubusercontent.com/52821836/70210504-de28d400-1758-11ea-8f7f-69268f3be00f.png)

**Comment by thyseus** [comment]
I assume this could be because of my refactoring attempt at:

 https://github.com/bagisto/bagisto/pull/1775 ?

If this is true, possibly the unit test in there could be enhanced to reflect the errornous situation you ran into.

**Comment by bhanu-webkul** [comment]
Framework version : 0.1.8
issue fixed
