### ISSUE TITLE
Got exceptions while creating refund

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1850]
# Bug report

### Title
exception while creating refund 
### Preconditions
    1. framework Version. 0.1.8
### Steps to reproduce
    **unable to reproduce**
### Actual result:
1-
![Screenshot from 2019-12-03 19-56-50](https://user-images.githubusercontent.com/52821836/70212682-c30c9300-175d-11ea-8b06-0925a78b1f4d.png)
2-
![Screenshot from 2019-12-04 13-40-21](https://user-images.githubusercontent.com/52821836/70212716-d61f6300-175d-11ea-8952-366ce79c8efc.png)

**Comment by rahulshukla-webkul** [comment]
Hi @bhanu-webkul 

We can not reproduce this issue, so we are closing it.
