### ISSUE TITLE
Got exception while generating invoice. 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1851]
# Bug report

### Title:

Got exception while generating invoice. 
### Preconditions

    1. framework Version. 0.1.8

### Steps to reproduce
unable to reproduce 
### Expected result:
invoice should be generated 
### Actual result
![Screenshot - 2019-12-05T124604 222](https://user-images.githubusercontent.com/52821836/70212936-3d3d1780-175e-11ea-8f4c-314cf6939bd6.png)

**Comment by rahulshukla-webkul** [comment]
Hi @bhanu-webkul 

Unable to reproduce this issue.
