### ISSUE TITLE
Cannot setup new Bagistro projects on Windows 10

### ISSUE THREAD

**Issue by bvqbao** [bagisto/bagisto#1865]
# Bug report

### Issue Description
I follow the manual installation process and `php artisan vendor:publish` aborted. I cannot press 0.

My environment:
* Apache 2.4.41
* PHP 7.3.12
* MariaDB 10.4.10
* Composer 1.9.1

### Screenshot

![Screenshot (8)](https://user-images.githubusercontent.com/4357219/70372955-f11cdf00-18e5-11ea-9dbb-976379c6c527.png)

**Comment by bvqbao** [comment]
Ok. There is a bug on PHP 7.4: https://bugs.php.net/bug.php?id=78883

**Comment by jasobanta** [comment]
php artisan vendor:publish --all --force
