### ISSUE TITLE
Category saves on en local no matter what you selected in admin

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#1867]
consider having a bagisto app with 2 locals and you want to make a new category , if you have for example `fa` and `en` locales and currently you want to add a category , there is no option to select which local this category is belonging to and when you add it , it automatically will be added to the default local which means en and you cant see that in your categories unless you manually change it from database to `fa` .

**Comment by jyoti-webkul** [comment]
@farshadff 
This issue has been already fixed in our master branch.Please take a pull.
