### ISSUE TITLE
Exception while applying catalog rule "adjust to percentage"

### ISSUE THREAD

**Issue by AnnikaWolff** [bagisto/bagisto#1869]
# Bug report

Got an exception while applying a catalog rule, that should adjust the price to a given percentage: 

```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Webkul\Discount\Actions\Catalog\AdjustToPercent' not found
Open: /var/www/packages/Webkul/Discount/src/Helpers/Catalog/Apply.php > Line 432
```

### Preconditions
Framework Version: Bagisto v.0.1.8
Latest commit [3eb7d86](https://github.com/bagisto/bagisto/commit/3eb7d862b1c7c38a2e2f03b8fcdd8fec9ffb4ba1)

### Steps to reproduce

1. Create Catalog Rule
    - Customer Group: General
    - Channel: Default
    - Is Active: Yes
    - Start / End: left empty
    - Condition: Select by Categories -> select any
    - Actions: Apply -> **Adjust price to percentage**
    - Discount Amount: 10% (or any)
    - End other rules: No
2. Save the Rule
3. On Catalog Rule Overview: Click Button "Apply"

### Expected result
After clicking the Apply button, a success message should appear. 
The catalog rule should be applied to the chosen category, i.e. the price of that category's products should be decreased by the given percentage.

*   Log: [environment_and_details.txt](https://github.com/bagisto/bagisto/files/3939952/environment_and_details.txt)
![Exception_AdjustToPercentage_2019-12-09 14-57-05](https://user-images.githubusercontent.com/57894757/70441229-4991df00-1a94-11ea-8da5-31f84c359bd9.jpg)

### Actual result

After clicking the Apply button, the rule is not applied, but an exception occurs:

```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Webkul\Discount\Actions\Catalog\AdjustToPercent' not found
Open: /var/www/packages/Webkul/Discount/src/Helpers/Catalog/Apply.php > Line 432
```

**Comment by jitendra-webkul** [comment]
@AnnikaWolff 

We are revamping the entire cart rule and catalog rule. By this month we will release new version with more stable cart rule and catalog rule.

**Comment by AnnikaWolff** [comment]
Hello @jitendra-webkul 

Alright, thanks for the answer. I am looking forward to it :)
If you want to close this issue, it is fine by me.

Best regards!
