### ISSUE TITLE
We can add column "Group Name" instead of Group Id and also add this column in filter in Customers Grid.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#187]
Framework Version: 0.1.1
![screenshot 17](https://user-images.githubusercontent.com/45203177/49133830-81096f80-f307-11e8-9058-3db41614dae6.png)

**Comment by rahulshukla-webkul** [comment]
Added a column group name instead of group id. ( https://prnt.sc/locrye )

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
