### ISSUE TITLE
Utf-8 currency code make all prices broken

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#1872]
i want to add a utf-8 based currency code like : `ریال` from code it is not possible because it wont let you do it and when you make it from database all prices will be broken and gone as below :
![price](https://user-images.githubusercontent.com/17511289/70515789-27a76380-1b4b-11ea-9cac-2f77b5f509d9.jpg)
as you can see all prices in site will dissapear . i want to know if there is any way to add the custom code for my currency or not ?? thanks

**Comment by rahulshukla-webkul** [comment]
Hi @farshadff 

Please refer this one -https://github.com/bagisto/bagisto/issues/1814
