### ISSUE TITLE
how to change currency seperators

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#1873]
this is simple i want my currency not to have any separators  so instead of `1240,00` i would want to have `1240` is there any way to customize the separator of currency >>

**Comment by rahulshukla-webkul** [comment]
Hi @farshadff 

Please refer this one - https://github.com/bagisto/bagisto/issues/1814

**Comment by rahulshukla-webkul** [comment]
Hi @farshadff 

Can we close this one.

**Comment by farshadff** [comment]
oh yes sorry didnt mentioned that
