### ISSUE TITLE
Class Webkul\Core\Repositories\SliderRepository does not exist

### ISSUE THREAD

**Issue by KyawNaingTun** [bagisto/bagisto#1874]
# Bug report

### Issue Description
**I have been trying to deploy on digital ocean server. Application was woking well on local machine but still getting errors on production ubuntu server.**

### Preconditions
    1. version 0.1.6
![Screen Shot 2019-12-10 at 16 28 56](https://user-images.githubusercontent.com/6079250/70520112-706f1480-1b6b-11ea-84f4-877c918acc67.png)

**Comment by jyoti-webkul** [comment]
@KyawNaingTun 
Please use our latest version - https://github.com/bagisto/bagisto/releases/tag/v0.1.8

**Comment by KyawNaingTun** [comment]
Thanks @jyoti-webkul  I have been fixed this issue by replacing prettus/l5-repository version 2.6(old version). I guess (bagisto)v0.1.6 doesn't compatible with (l5-repository) version 2.6.32.
