### ISSUE TITLE
Customer Wishlist Crashing

### ISSUE THREAD

**Issue by iftikharalinaeem** [bagisto/bagisto#1877]
# Bug report

### Title
**When a customer goes to his wishlist it crashes.**

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Login as a customer
    2. Add a product to the wish-list
    3. Click on the wish-list from the top right drop-down

### Expected result
**Shows laravel Error**

*   [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/4716273/70605998-a1ebec80-1c0c-11ea-8f26-581ceb02f3f1.png)

### Fixing

>    **There is a function name averageRating in packages/Webkul/Product/src/Helpers/Review.**
>    **In the line  return $avgRating[$product->id] = number_format(round($product->reviews()->where('status', 'approved')->average('rating'), 2), 1);change the function call from average to avg**

**Comment by jyoti-webkul** [comment]
@iftikharalinaeem 
Please mention your framework version .

**Comment by iftikharalinaeem** [comment]
0.1.8

**Comment by rahulshukla-webkul** [comment]
Hi @iftikharalinaeem 

We have changed it. 
Thanks

**Comment by bhanu-webkul** [comment]
Fixed in master
