### ISSUE TITLE
Front-End conflicts with most of jquery custom theme

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#1881]
I am trying to apply a custom theme to the front-end of bagisto, but I think Vue has conflict with most jquery theme. Any good idea to avoid this problem?

**Comment by rahulshukla-webkul** [comment]
Hi @lYesterdaYl 

Please check any plugin in not included twice.

**Comment by lYesterdaYl** [comment]
> Hi @lYesterdaYl
> 
> Please check any plugin in not included twice.

hi, there shouldn't be duplicate plugin cause the custom theme ui doesn't work at all if I don't include the js the theme requires to include.

**Comment by jitendra-webkul** [comment]
Recently we have added a new velocity theme using bootstrap, you can take a reference from that.
