### ISSUE TITLE
Product's created but not showing on the table and frontend side

### ISSUE THREAD

**Issue by buddyy93** [bagisto/bagisto#1896]
so itried to insert a simple product, it says succesfully created, but it doesn't show on product table.

![Snipaste_2019-12-14_16-40-01](https://user-images.githubusercontent.com/22981271/70846061-7a0cbb00-1e90-11ea-80e9-2105195813c5.png)

but it shows on my dashboard page.

![Snipaste_2019-12-14_16-40-18](https://user-images.githubusercontent.com/22981271/70846064-80029c00-1e90-11ea-9350-977774f3d483.png)

i added a jp locale, i wonder if it has something to do with it
anyway any helps is much appreciated, thank you

**Comment by thes01** [comment]
You need to go to the current channel settings (i.e. /admin/channels/edit/1) and enable the localisations there. After that the adding should be working fine ;)
