### ISSUE TITLE
Paypal payment keeps giving me "We're sorry, things don't appear to be working at the moment. Please try again later."

### ISSUE THREAD

**Issue by buddyy93** [bagisto/bagisto#1897]
i've added my business account email in admin setting but it keeps showing me that error.
does it have to do with my paypal account setting ?
and how can i switch the payment mode between sandbox and live mode ?
thank you

**Comment by rahulshukla-webkul** [comment]
Hi @buddyy93 

Please follow the given link - https://docs.easydigitaldownloads.com/article/2030-paypal-error-things-dont-appear-to-be-working-at-the-moment

**Comment by buddyy93** [comment]
my Encrypted Website Payments is already set to off, but i still get the errors.
and i'm not sure where to find this setting "Downloads →Settings → Payment Gateways → PayPal Standard", is it inside paypal account setting ?

**Comment by rahulshukla-webkul** [comment]
Hi @buddyy93 

We have always set sandbox as true, i think that's why its returning this error.
Now we have added configuration for it so that user can use both live and sandbox account.
kindly take pull from our master branch.

Thanks for reporting this one.

**Comment by jitendra-webkul** [comment]
I am closing this issue, I hope the above solution works for you.
