### ISSUE TITLE
Product not visible on storefront if you first inactive the product from product grid and then update the status to Active.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1916]
# Bug report

### Title
Product not visible on storefront if you first inactive the product from product grid and then update the status to Active.

### Issue Description
Product not visible on storefront if you first inactive the product from product grid and then update the status to Active.

### Preconditions
    1. framework Version.-0.1.9

### Steps to reproduce

    1. step1- Create a product and update the status to inactive
    2. step2-Now update the status to active.

### Expected result
On updating the status to active product should display on storefront.
### Actual result
Product is not visible on storefront.

**Comment by rahulshukla-webkul** [comment]
duplicate - #1806
