### ISSUE TITLE
compact(): Undefined variable: operator

### ISSUE THREAD

**Issue by buddyy93** [bagisto/bagisto#1925]
i got this error when i tried to view a product in frontend.

![Snipaste_2019-12-20_01-51-45](https://user-images.githubusercontent.com/22981271/71196862-4e903300-22cb-11ea-8bc0-88f596ca8e42.png)

**Comment by rahulshukla-webkul** [comment]
Hi @buddyy93 

Please use Laravel 5.6 , I think you are using Laravel 5.4.

Thanks

**Comment by buddyy93** [comment]
I'm already using laravel 5.6, but it still shows the errors

**Comment by rabol** [comment]
use php 7.2, not 7.3 and not 7.4

**Comment by MujahidAbbas** [comment]
is there any other way to resolve this issue? instead of downgrading PHP version?

**Comment by jitendra-webkul** [comment]
Which Bagisto version you are using?

**Comment by MujahidAbbas** [comment]
0.1.8

**Comment by jitendra-webkul** [comment]
Fixed in master
