### ISSUE TITLE
Actual product amount and discounted amount both should display on product page for configurable product

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1929]
# Bug report

### Title
Actual product amount and discounted amount both should display on product page for configurable product
### Issue Description
Actual product amount and discounted amount both should display on product page for configurable product

### Preconditions

    1. framework Version.-0.1.9

### Steps to reproduce

    1. step1- Create a catalog rule for configurable product
    2. step2- Check the discounted amount on frontend.

### Expected result
Actual product price should also display along with discounted amount.
### Actual result
Only discounted amount of product displayed.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have **attached** a screenshot [Here](https://prnt.sc/2c2mtHQkjGN3), for future **reference**.
