### ISSUE TITLE
Hhow change theme 

### ISSUE THREAD

**Issue by atta1234** [bagisto/bagisto#1946]
i don't see any templates file in laravel default resources view,look like framework inside a framework

**Comment by rahulshukla-webkul** [comment]
Hi @atta1234 

All view are inside the respective package like for shop, it is inside shop package and for Admin, it is inside admin package.

You can follow given article to create theme -  https://bagisto.com/en/create-custom-theme-in-bagisto/  and https://devdocs.bagisto.com/create_theme.html.
