### ISSUE TITLE
Message need to be changed on mouse hover on cross symbol next to applied coupon. 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1955]
# Bug report

### Title
Message need to be changed on mouse hover on cross symbol next to applied coupon. 

### Preconditions
    1. framework Version. 0.1.9
### Steps to reproduce
    1. step1: apply any cart rule coupon while check out 
    2. step2: mouse hover on cross symbol

### Expected result:
message should be "Remove coupon code"

### Actual result
message getting "coupon code removed successfully"

![Screenshot from 2019-12-21 16-20-34](https://user-images.githubusercontent.com/52821836/71307167-59a0ab80-2410-11ea-8996-06d34d49c652.png)

**Comment by bhanu-webkul** [comment]
After removing coupon, same message coming "Remove Coupon", which should be coupon code removed successfully.

**Comment by jyoti-webkul** [comment]
Now option to remove coupon code disappear instantly after applying coupon code.

![Screenshot (29)](https://user-images.githubusercontent.com/45203177/73159961-c5f88400-410d-11ea-9692-998f8b7e8639.png)

**Comment by jitendra-webkul** [comment]
> Now option to remove coupon code disappear instantly after applying coupon code.
> 
> ![Screenshot (29)](https://user-images.githubusercontent.com/45203177/73159961-c5f88400-410d-11ea-9692-998f8b7e8639.png)

Duplicate to issue #2219
