### ISSUE TITLE
When customer is paying through paypal, discount amount is not getting minus from total.  

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1956]
# Bug report

### Title
When customer is paying through paypal, discount amount is not getting minus from total.  
### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version. 0.1.9
### Steps to reproduce
    1. step1: add to cart any product, apply cart rule.

    2. step2: select payment method as a paypal standard 

### Expected result:
total should come including discount 

### Actual result
total coming excluding discount on paypal payment page while in order section total is showing including discount.

**Comment by jitendra-webkul** [comment]
Fixed in master 

![Screenshot from 2020-01-09 19-54-02](https://user-images.githubusercontent.com/39991107/72075589-1607d600-331a-11ea-9248-d10603cac232.png)
