### ISSUE TITLE
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home2/***.com/public_html/public/index.php on line 71

### ISSUE THREAD

**Issue by mahbubrajiv** [bagisto/bagisto#1960]
It work fine my local server(wamp) but when i upload on real server.. it show this error.

**Comment by rahulshukla-webkul** [comment]
Hi @mahbubrajiv 

Did your local and sever had same versions of required dependencies like php, laravel etc versions ?

**Comment by jitendra-webkul** [comment]
No answer since 21 Dec. I hope, your issue got resolved.
