### ISSUE TITLE
Cart rule is not working properly if admin has created any other customer group apart from default.

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#1968]
# Bug report

### Title
Cart rule is not working properly if admin has created any other customer group apart from default.
### Issue Description:
if any customer belongs to newly created group and admin has set only set all default groups in cart rule then also cart rule is getting applied and if admin has set only new group then cart rule is not getting applied for that customer. 

### Preconditions

    1. framework Version. 0.1.9

### Steps to reproduce
    1. step1:Create customer groups and assign to any customer in that group. 
    2. step2: create a cart rule and do not select that group and try to order for that customer. 

### Expected result:
should work according to selected group 

### Actual result
not working properly

**Comment by jitendra-webkul** [comment]
Can not reproduce this issue
