### ISSUE TITLE
Product not added in cart according to added quantity when doing buy now

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#197]
Framework Version: 0.1.1
Test Steps:
1. Click on product and go to product page.
2. Update the quantity of Product.
3. Click on Buy Now.
4. Check the quantity of product in cart.

**Comment by prashant-webkul** [comment]
The buynow functionality is currently only capable of checking out using single click and single quantity of the product is added to the existing cart.
