### ISSUE TITLE
Route [auth.login] not defined error

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#1974]
Accessing API routes that require authentication throws Route [auth.login] not defined. This might also be the case for shop and admin routes as well. The **"unauthnticated"** methods in **"/Users/adrian/Projects/fiwimarket_b2c/packages/Webkul/Admin/src/Exceptions/Handler.php"** and **"/Users/adrian/Projects/fiwimarket_b2c/packages/Webkul/Shop/src/Exceptions/Handler.php"** have this route being called but the route is not defined anywhere.

**Comment by rahulshukla-webkul** [comment]
Hi @emperorjm 

I think, you have missed to pass Content-Type (application/json) in header that's why it is returning this error.
Kindly pass this field in header, then check.

Thanks

**Comment by emperorjm** [comment]
I had to use both Content-Type and Accept as application/json and I got back the correct response.
