### ISSUE TITLE
get erro whie try to run composer update [Composer\Downloader\TransportException].

### ISSUE THREAD

**Issue by dipeshsukhia** [bagisto/bagisto#1975]
![Selection_050](https://user-images.githubusercontent.com/34036367/71398235-ce106000-2645-11ea-858a-8eeb6e284a0a.png)
get erro whie try to run composer update [Composer\Downloader\TransportException].

**Comment by popperhead** [comment]
Try composer install.

**Comment by rahulshukla-webkul** [comment]
Hi @dipeshsukhia 

Please follow the given article - https://github.com/composer/composer/issues/7782#issuecomment-438585301

**Comment by jitendra-webkul** [comment]
Closing this issue, I hope the above reply solved your issue.
