### ISSUE TITLE
UI issue in cart on changing locale.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1980]
# Bug report

### Title
UI issue in cart on changing locale.
### Issue Description
UI issue in cart on changing locale.

### Preconditions

    1. framework Version.-0.2.1

### Steps to reproduce

    1. step1- Add a product in cart
    2. step2- open the cart page and check the remove button.

### Expected result
Remove button should be visible properly

### Actual result
Remove button is not visible properly.

![Screenshot (5)](https://user-images.githubusercontent.com/45203177/71465400-8d018280-27e2-11ea-89a9-0de884aed2c4.png)

**Comment by jitendra-webkul** [comment]
Fixed in master branch

**Comment by jyoti-webkul** [comment]
Fixed in master
