### ISSUE TITLE
If customer update his address at time of checkout and save this address then address doesn't get save and also on checkout page old address displays.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1981]
# Bug report

### Title
If customer update his address at time of checkout and save this address then address doesn't get save and also on checkout page old address displays.

### Issue Description
If customer update his address at time of checkout and save this address then address doesn't get save and also on checkout page old address displays.
### Preconditions

    1. framework Version.-0.2.1

### Steps to reproduce

    1. step1- Login with your account and proceed to checkout after shipping method go back to your information page and update the address, also select the option to save this address and proceed to checkout.
    2. step2- On checkout page check the address

### Expected result
Updated address should display on checkout page

### Actual result
Updated address doesn't appear on checkout page.

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
This issue is not exist now, you can check for the same in latest version.
