### ISSUE TITLE
Broken logo image on bagisto admin, configure->customer->design

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1982]
# Bug report

### Title
Broken logo image on bagisto admin, configure->customer->design
### Issue Description
Broken logo image on bagisto admin, configure->customer->design

### Preconditions
    1. framework Version.-master

### Steps to reproduce

    1. step1- Go to configure->customer->design  and add logo for admin panel.
    2. step2- Getting broken logo image.

### Expected result
Added logo should be visible
### Actual result
Broken logo image

![Screenshot from 2019-12-27 16-50-44](https://user-images.githubusercontent.com/45203177/71515502-86016f80-28c9-11ea-9421-7293eb94d755.png)

**Comment by jyoti-webkul** [comment]
Working fine now.
![Screenshot from 2020-01-09 13-42-04](https://user-images.githubusercontent.com/45203177/72049868-d9ba8280-32e5-11ea-816e-8683afe81b7b.png)

**Comment by aroon9002ahmed** [comment]
I have same problem ...can you tell me how did ou fix this problem?

**Comment by bengaliyoutubers** [comment]
hello help me

**Comment by Sanjaybhattwebkul** [comment]
> I have same problem ...can you tell me how did ou fix this problem?

Hi @aroon9002ahmed 
**Yes** please,  please let me know what **issue** are you facing. I will **provide** you with a **better** **solution** asap

**Comment by Sanjaybhattwebkul** [comment]
@aroon9002ahmed 
Hope your issue will be resolved if still, you are getting the same issue, then feel free to reopen
