### ISSUE TITLE
Subscribe to newsletter does not work

### ISSUE THREAD

**Issue by rabol** [bagisto/bagisto#1986]
# Bug report

### Title
In the latest version - master branch -  subscribing to newsletter does not work

### Issue Description
Enable Newsletter subscription, then go to the front page to try to sign up.
You will get an error saying that emails could not be send.

### Preconditions
**Please provide as detailed information about your environment as possible.**

master branch

### Steps to reproduce
Enable Newsletter subscription
go to the front page to try to sign up.

### Expected result
messages that you are subscribed

*   [Screenshots, logs or description]

### Actual result
You will get an error saying that emails could not be send.

to fix:

in file /packages/Webkul/Shop/src/Mail/SunscriptionMail.php, build() method
change from 
```
 return $this->to($this->subscriptionData['email'])
                ->from(config('mail.from'))
                ->subject(trans('shop::app.mail.customer.subscription.subject'))
                ->view('shop::emails.customer.subscription-email')->with('data', ['content' => 'You Are Subscribed', 'token' => $this->subscriptionData['token']]);

```

to 

```

 return $this->to($this->subscriptionData['email'])
                ->from(config('mail.from.address'),config('mail.from.name'))
                ->subject(trans('shop::app.mail.customer.subscription.subject'))
                ->view('shop::emails.customer.subscription-email')->with('data', ['content' => 'You Are Subscribed', 'token' => $this->subscriptionData['token']]);
```

**Comment by emperorjm** [comment]
If you look in the config -> mail.php file you will see:

`'from' => [
        'address' => env('SHOP_MAIL_FROM'),
        'name' => env('MAIL_FROM_NAME')
    ],`

You just need to set the SHOP_MAIL_FROM and MAIL_FROM_NAME variables in your .env file.

**Comment by rabol** [comment]
I have both set in my .env, but still get the messages

**Comment by rabol** [comment]
and a log on the execption

**Comment by rabol** [comment]
sorry, closed by mistake

**Comment by rahulshukla-webkul** [comment]
Hi @rabol 

This issue has been solved, kindly take pull from master branch.

**Comment by jyoti-webkul** [comment]
- Fixed in master branch

**Comment by its-soa** [comment]
good afternoon @jyoti-webkul @rahulshukla-webkul @rabol ,  

Also encountering this error. I can't find the commit id or where to cross check my code from

please help!

**Comment by vaishaliwebkul** [comment]
@its-soa 
may I know which version of bagisto you're currently using?? or the exact error you're facing

**Comment by its-soa** [comment]
thanks @vaishaliwebkul. i am using bagisto 1.1.2  will send a screen shot of the error
![Screenshot (226)](https://user-images.githubusercontent.com/33020032/96551050-a875d680-12a9-11eb-87f1-20ddade2eb67.png)

**Comment by vaishaliwebkul** [comment]
@its-soa 
the error alert saying that mail configuration is not correctly set, please once check the .env file and setup mailer details.
for more details check this https://forums.bagisto.com/topic/1513/when-a-customer-buy-a-product-admin-should-get-email-gmail-how-to-setup-this

**Comment by its-soa** [comment]
Much thanks @vaishaliwebkul , checking it out already. In the image above, Do have any idea as to why my logo doesn't show on the front page? i have updated it countlessly, but it still doesn't display. Also searched and followed this guide i saw online, but the problem still persists [https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions/2](url)

**Comment by yura20066** [comment]
> и журнал выполнения
