### ISSUE TITLE
MySQL query very slow if products in category is around 3000 

### ISSUE THREAD

**Issue by rashidfornajah** [bagisto/bagisto#1987]
# Bug report

### MySQL query very slow if products in category is around 3000  
**Loading products is very slow maybe few minutes if the products are more **

### Issue Description
**MySQL query taking huge time**
**Below are the two queries being used to fetch products**

1. 
select distinct `product_flat`.*, IF( product_flat.special_price_from IS NOT NULL
AND product_flat.special_price_to IS NOT NULL , IF( NOW( ) >= product_flat.special_price_from
AND NOW( ) <= product_flat.special_price_to, IF( product_flat.special_price IS NULL OR product_flat.special_price = 0 , product_flat.price, LEAST( product_flat.special_price, product_flat.price ) ) , product_flat.price ) , IF( product_flat.special_price_from IS NULL , IF( product_flat.special_price_to IS NULL , IF( product_flat.special_price IS NULL OR product_flat.special_price = 0 , product_flat.price, LEAST( product_flat.special_price, product_flat.price ) ) , IF( NOW( ) <= product_flat.special_price_to, IF( product_flat.special_price IS NULL OR product_flat.special_price = 0 , product_flat.price, LEAST( product_flat.special_price, product_flat.price ) ) , product_flat.price ) ) , IF( product_flat.special_price_to IS NULL , IF( NOW( ) >= product_flat.special_price_from, IF( product_flat.special_price IS NULL OR product_flat.special_price = 0 , product_flat.price, LEAST( product_flat.special_price, product_flat.price ) ) , product_flat.price ) , product_flat.price ) ) ) AS final_price from `product_flat` left join `products` on `product_flat`.`product_id` = `products`.`id` left join `product_categories` on `products`.`id` = `product_categories`.`product_id` left join `product_flat` as `flat_variants` on `product_flat`.`id` = `flat_variants`.`parent_id` and `flat_variants`.`channel` = ? and `flat_variants`.`locale` = ? left join `products` as `variants` on `products`.`id` = `variants`.`parent_id` where `product_flat`.`channel` = ? and `product_flat`.`locale` = ? and `product_flat`.`url_key` is not null and `product_categories`.`category_id` = ? and `product_flat`.`status` = ? and `product_flat`.`visible_individually` = ? group by `product_flat`.`id` limit 9 offset 0

2. 
select count(*) as aggregate from `product_flat` left join `products` on `product_flat`.`product_id` = `products`.`id` left join `product_categories` on `products`.`id` = `product_categories`.`product_id` left join `product_flat` as `flat_variants` on `product_flat`.`id` = `flat_variants`.`parent_id` and `flat_variants`.`channel` = ? and `flat_variants`.`locale` = ? left join `products` as `variants` on `products`.`id` = `variants`.`parent_id` where `product_flat`.`channel` = ? and `product_flat`.`locale` = ? and `product_flat`.`url_key` is not null and `product_categories`.`category_id` = ? and `product_flat`.`status` = ? and `product_flat`.`visible_individually` = ? group by `product_flat`.`id`

### Preconditions
**You should have good amount of products in category around 3000**

    1. framework Version=0.1.8

### Steps to reproduce
**Add more products to the categories around 3000**

### Expected result
**Results should be much faster**

### Actual result

>    **Products are taking minutes to  come**

**Comment by rahulshukla-webkul** [comment]
Hi @rashidfornajah 

Thanks for your concern but we have optimised it in our latest release, kindly install latest one  and check on this.

**Comment by GayanPriyankara** [comment]
can't we fix the problem without updating the version
