### ISSUE TITLE
Country and City Names in Create Address is not coming based on Locale

### ISSUE THREAD

**Issue by rashidfornajah** [bagisto/bagisto#1988]
# Bug report

### Country and City Names in Create Address is not coming based on Locale
**It is just bringing the default name in the "countries" Table**
****

### Preconditions
**Make the website in English & Arabic too**
**Fill the data in country_translations too**

    1. framework Version=0.1.8

### Steps to reproduce
**Make the website in Arabic and try to create the address**

### Expected result
**Country  and city should come in Arabic**

*   [Screenshots, logs or description]

### Actual result
**Country and city name coming with the default name in "countries"**

**Comment by jitendra-webkul** [comment]
Run this following command to insert translations into the DB

php artisan db:seed --class=Webkul\\Core\\Database\\Seeders\\CountryStateTranslationSeeder

**Comment by jyoti-webkul** [comment]
- Fixed
