### ISSUE TITLE
Dynamic filters based on products shown on Category and Search pages

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#1990]
Currently, the filters shown on the Category page is determined by the list of **"Filterable Attributes"** set within the category page within the admin portal.

It would be nice for the filters to be displayed (and the available filter options) based on those actually being used in the products returned in the resultset. Currently, if I add the **"colour"** attribute to the category filter and the products shown within that category have not used that attribute the filters won't be useful. The filter also returns all the options and for the colour attribute example if products within the category have only used the red colour then only that option should be shown.

It would also be nice to have these filters added to the **"Search"** page as well.

**Comment by rahulshukla-webkul** [comment]
HI @emperorjm 

We really appreciate your suggestion and sure change the process of filtration on category page and add this filter on search page as well.

**Comment by rahulshukla-webkul** [comment]
Hi @emperorjm 

We can not implement this one,  if you need then you can customise it.
