### ISSUE TITLE
Layout issue at catalog add product page

### ISSUE THREAD

**Issue by asif-webkul** [bagisto/bagisto#1993]
# Bug report

### Issue Description
filter and the pagination drop-down are overlapped

    1. framework Version -- 0.1.8.

**Comment by asif-webkul** [comment]
![issue_on_add_product](https://user-images.githubusercontent.com/56350185/71817486-05522880-30ac-11ea-991b-bc1c4d7bbf02.png)

**Comment by jitendra-webkul** [comment]
You did not publish assets.
