### ISSUE TITLE
Showing product sale amount as zero when creating a product, and a existing catalog rule apply on it.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1998]
# Bug report

### Title
Showing product sale amount as zero when creating a product, and a existing catalog rule apply on it.

### Issue Description
Showing product sale amount as zero when creating a product, and a existing catalog rule apply on it.
### Preconditions

    1. framework Version.-0.2.1

### Steps to reproduce
    1. step1- Create a catalog rule by condition "All condition are true" and did not select any condition.
    2. step2- Now create a product and go to frontend to check the product.

### Expected result
Product should get updated according to catalog rule or it should display with its actual price
### Actual result
Showing sale amount as zero.
![Screenshot (17)](https://user-images.githubusercontent.com/45203177/71711477-4b4a8a80-2e27-11ea-837b-c32aac546b42.png)

**Comment by jitendra-webkul** [comment]
Fixed in 0.2.2

**Comment by bhanu-webkul** [comment]
Fixed in 0.2.2 & master.
