### ISSUE TITLE
How to authenticate Api request /api/checkout/cart/add/1

### ISSUE THREAD

**Issue by richard457** [bagisto/bagisto#1999]
This repository is only for reporting bugs or issues. If you need support, please use:

I need to call endPoint in android, I know I need to authenticate the API using bearer token but it is not working how can I do that?

**Comment by rahulshukla-webkul** [comment]
Hi @richard457 

Please follow this one - https://forums.bagisto.com/topic/149/i-need-to-deliver-the-api-token-from-the-json-response-not-the-header/4

**Comment by richard457** [comment]
@rahulshukla-webkul thank you for your kind help.

**Comment by jitendra-webkul** [comment]
Closing this issue, I hope the above reply solved your problem.
