### ISSUE TITLE
latest release: composer create-project bagisto/bagisto

### ISSUE THREAD

**Issue by rabol** [bagisto/bagisto#2004]
when creating a new installation with release 0.2.2

composer create-project bagisto/bagisto

I get the following error:

Failed to execute unzip -qq  '/home/vagrant/code/bagisto//6d75307cecbe812e8bc8db09b41f2ff1' -d '/home/vagrant/code/vendor/composer/a680d635'

replace /home/vagrant/code/vendor/composer/a680d635/bagisto-bagisto-20d61d1/packages/Webkul/Shop/publishable/assets/images/arrow-down.svg? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emaphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by jyoti-webkul** [comment]
@rabol 
Please mention your php version

**Comment by rabol** [comment]
I'm using Laravel Homestead v9

PHP 7.4.0 (cli) (built: Nov 28 2019 07:27:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0, Copyright (c), by Zend Technologies

**Comment by jitendra-webkul** [comment]
Hi @rabol ,

I am closing this issue for now. If this is still an issue for you, feel free to reopen.
