### ISSUE TITLE
Saving channel converts text

### ISSUE THREAD

**Issue by rabol** [bagisto/bagisto#2005]
# Bug report

### Title
If you want to change the currency of the 'default' channel, then one have to enter meta data and then save.
Saving mess up the html for the quick links - Footer Content

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. 0.2.2
   

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. edit default channel
    2. change currency
    3. save

### Expected result
That the footer content is saved and can be used

### Actual result
The footer get like this:

```

<div class="list-container"><span class="list-heading">Quick Links</span>
   <ul class="list-group">
   <li><a href="@php echo route(" shop="" cms="" page="" about-us="" endphp="">About Us</a></li>
   <li><a href="@php echo route(" shop="" cms="" page="" return-policy="" endphp="">Return Policy</a></li>
   <li><a href="@php echo route(" shop="" cms="" page="" refund-policy="" endphp="">Refund Policy</a></li>
   <li><a href="@php echo route(" shop="" cms="" page="" terms-conditions="" endphp="">Terms and conditions</a></li>
   <li><a href="@php echo route(" shop="" cms="" page="" terms-of-use="" endphp="">Terms of Use</a></li>
   <li><a href="@php echo route(" shop="" cms="" page="" contact-us="" endphp="">Contact Us</a></li>
   </ul>
   </div>

```

**Comment by jyoti-webkul** [comment]
This issue has been fixed in master
