### ISSUE TITLE
Loggable models

### ISSUE THREAD

**Issue by alkhachatryan** [bagisto/bagisto#2007]
### Description of problem
Hello colleagues! We are using the Bagisto in our big project back office.
We have a 20 data-managers, who works on multiple BREAD structures - Posts, Media files, Documents, etc.
So we decided to track them and see which person worked on which model, what did and how.

### Proposed solution
I created the package, which will log in the files and in DB the BREAD changes from current user.
Checkout the table structure, so you can understand the way logger works (user ID can be null, because other cron jobs or daemons can modify the data).
![image](https://user-images.githubusercontent.com/22774727/71817875-b783f300-30a0-11ea-9f49-c01f3d701f63.png)

### Additional context
This is the package I created for Laravel:
https://github.com/alkhachatryan/laravel-loggable

Check it out please, and let me know, do we need it included in Bagisto so I can start PR creation

**Comment by fg** [comment]
seems like https://github.com/owen-it/laravel-auditing, isn't it?

**Comment by alkhachatryan** [comment]
@fg 

Yes, it like the package you sent, but there are many differences.
We could use it, but I want to specify the models I want to log and columns I want to log from the specific model.

For example, I want to log only Create action from Post model, and Edit action in Comment model, but log only comments.body column changes.

I don't think you can do it with the package you sent, dear.

**Comment by rahulshukla-webkul** [comment]
Hi @alkhachatryan 

We appreciate your solution but we can not add this as it basically depends on specific need and this is a generalise product.
You can create its extension and if any customers requires then they can use it.

**Comment by fg** [comment]
@alkhachatryan 

You can do it also using laravel-auditing.

```php
class User extends Model 
{
    protected $auditEvents = ['restored', 'deleted']

    protected $auditInclude = ['title', 'content'];
}
```

**Comment by alkhachatryan** [comment]
> but im watching your project for new improvements and features.

Thank you

**Comment by alkhachatryan** [comment]
> Hi @alkhachatryan
> 
> We appreciate your solution but we can not add this as it basically depends on specific need and this is a generalise product.
> You can create its extension and if any customers requires then they can use it.

I can modify it and you can use it as product changes history. It's useful.

**Comment by alkhachatryan** [comment]
@rahulshukla-webkul 
Any news?
