### ISSUE TITLE
Using AWS S3 for storage

### ISSUE THREAD

**Issue by MostafaAttia** [bagisto/bagisto#2009]
I'm using S3 cloud storage for storing images as it's not a good idea to store files on the server itself.
So I can upload product image successfully to S3 when creating/updating a product, But now I can't get images to show because it's being cached.

In `Webkul\Product\Helpers\ProductImage`  I found that the image url is pointing to `/cache/`:
```
public function getProductBaseImage($product)
    {
        $images = $product ? $product->images : null;

        if ($images && $images->count()) {
            $image = [
                'small_image_url' => url('cache/small/' . $images[0]->path),
                'medium_image_url' => url('cache/medium/' . $images[0]->path),
                'large_image_url' => url('cache/large/' . $images[0]->path),
                'original_image_url' => url('cache/original/' . $images[0]->path),
            ];
        } else {
            $image = [
                'small_image_url' => asset('vendor/webkul/ui/assets/images/product/small-product-placeholder.png'),
                'medium_image_url' => asset('vendor/webkul/ui/assets/images/product/meduim-product-placeholder.png'),
                'large_image_url' => asset('vendor/webkul/ui/assets/images/product/large-product-placeholder.png'),
                'original_image_url' => asset('vendor/webkul/ui/assets/images/product/large-product-placeholder.png'),
            ];
        }

        return $image;
    }
```

Is there a way to store images on S3 and use the cache as well?
Help is much appreciated.

**Comment by rahulshukla-webkul** [comment]
Hi @MostafaAttia 

We have used intervention package for resizing product images into different size and this images are not uploading on s3 bucket so product images are not appearing on shop.

For right now, if you want then you need to write code to upload these resize images on s3 bucket and need to get this images on shop.

We will soon update these things to provide fully s3 bucket support to our system until you can wait.

**Comment by jesusnazarethgh** [comment]
Hey! I´m "dockerizing" an pplication and I had a similar issue and solved it using Redis for cache and a StreamWrapper...

First setup redis. 

config/cache.php

    'stores' => [
            // ...

            'redis' => [
                'driver' => 'redis',
                'connection' => 'default',
            ],
        ],
    ], //...


config/database.php

    // ...
        'redis' => [

            'client' => 'predis',

            'default' => [
                'host' => env('REDIS_HOST', '127.0.0.1'),
                'password' => env('REDIS_PASSWORD', null),
                'port' => env('REDIS_PORT', 6379),
                'database' => 0,
            ],

        ],
    // ...

Then, register a StreamWrapper in app/Providers/AppServiceProvider.php 

    // ...
    use Aws\S3\StreamWrapper;
    use Aws\S3\S3Client;

    class AppServiceProvider extends ServiceProvider
    {
        // ...

        /**
        * Bootstrap any application services.
        *
        * @return void
        */
        public function boot()
        {
            //...

            $options = [
                'credentials' => [
                    'key' => env('AWS_ACCESS_KEY_ID'),
                    'secret' => env('AWS_SECRET_ACCESS_KEY')
                ],
                //'endpoint' => env('AWS_URL'),
                'region' => env('AWS_DEFAULT_REGION'),
                'version' => '2006-03-01'
            ];

            $s3 = new S3Client($options);
            StreamWrapper::register($s3, 's3');
        }
        //...

And finally add a storage path in config/imagecache.php

    //...
    /*
    |--------------------------------------------------------------------------
    | Storage paths
    |--------------------------------------------------------------------------
    |
    | The following paths will be searched for the image filename, submited
    | by URI.
    |
    | Define as many directories as you like.
    |
    */

    'paths' => array(
        storage_path('app/public'),
        public_path('storage'),
        "s3://<yourbucket-here>"
    ),
    //...

Imagecache search in these paths the images and store in cache.

Well... for all in the same situation I hope it helps. Good coding!

**Comment by jitendra-webkul** [comment]
I hope that solved you issue. I am closing this issue, feel free to reopen any time.

**Comment by raulidavid** [comment]
@jesusnazarethgh estoy con el mismo problema dame una manito Jesús ya llevo algunos días tratando de hacer eso solo que mi storage no es Amazon sino Google cloud

**Comment by mikeyapina** [comment]
NO this makes no sense I went to cache.php and there are many parameters here what am I suppose to change to fix your issue?

https://github.com/bagisto/bagisto/issues/2009#issuecomment-571433310

**Comment by mikeyapina** [comment]
There is no such file In Webkul\Product\Helpers\ProductImage I found that the image url is pointing to /cache/
<img width="1474" alt="Screen Shot 2022-01-25 at 11 00 52 PM" src="https://user-images.githubusercontent.com/18667035/151106691-2437cee0-5aa7-4aef-ac52-266bfb883a44.png">
:

**Comment by mikeyapina** [comment]
Next, are we supposed to use this contributor's solution to fix your issue?

https://github.com/bagisto/bagisto/issues/2009#issuecomment-617432956

**Comment by mikeyapina** [comment]
> I hope that solved you issue. I am closing this issue, feel free to reopen any time.

I go to the issue and the issue says to use local and not use adding a file! What is the solution here and why has the vendor not properly saying how to fix it?

**Comment by ghermans** [comment]
Good morning @mikeyapina : as @devansh-webkul already explained, the issue will be resolved in the upcoming release.

**Comment by mikeyapina** [comment]
It was always my intention to buy tis plugin because I wanted it easy access at the admin plugin now I bought the plugin in the app that makes sense. But to intentionally break your app to use it too force people to buy the plugin now that is deceptive. It shows me that your company is not so honest.  A red flag of how your company is operating. Something I did not expect and something I had not experienced before with you guys.  Which in many ways was why hI decided to work wit you and Laravel.  But as it is I paid the extra to have someone administrate within this build the tool this is  to  deep in the forest at this point. You paid $xxxx USD
to Webkul Software Private LimitedDetails
Paid with

**Comment by mikeyapina** [comment]
> 
I. am using 1.3.1.  because that is the. only module the droop-ship module works. I literally spent 2 weeks figuring that issue out. SO your future release doesn't help me.

**Comment by ghermans** [comment]
> It was always my intention to buy tis plugin because I wanted it easy access at the admin plugin now I bought the plugin in the app that makes sense. But to intentionally break your app to use it too force people to buy the plugin now that is deceptive. It shows me that your company is not so honest. A red flag of how your company is operating. Something I did not expect and something I had not experienced before with you guys. Which in many ways was why hI decided to work wit you and Laravel. But as it is I paid the extra to have someone administrate within this build the tool this is to deep in the forest at this point. You paid $xxxx USD to Webkul Software Private LimitedDetails Paid with

What I understand from your previous messsages on multiple channels is that you purchased a plugin from our colleagues at Webkul to simplify the configuration for S3 and having problems with it? It's true that it was developed to simplify the configuration so that you would have to change it less manually, but it was not developed to fix a mistake made by Bagisto.
In case you want support related to this plugin you can (and most probably already did) contact [Webkul](https://bagisto.uvdesk.com/en/customer/create-ticket) because we do not provide any support on Github for these packages.

Bagisto is an open source application and is maintained by more people than just Webkul.
The accusation that we create certain issues and then charge you for them makes no sense.
Daily / weekly people report issues or feature requests and if you look at the number of pull requests you see that we solve the most problems quickly without charging anyone for this or selling the solution as a separate module.

**Comment by mikeyapina** [comment]
> > It was always my intention to buy tis plugin because I wanted it easy access at the admin plugin now I bought the plugin in the app that makes sense. But to intentionally break your app to use it too force people to buy the plugin now that is deceptive. It shows me that your company is not so honest. A red flag of how your company is operating. Something I did not expect and something I had not experienced before with you guys. Which in many ways was why hI decided to work wit you and Laravel. But as it is I paid the extra to have someone administrate within this build the tool this is to deep in the forest at this point. You paid $xxxx USD to Webkul Software Private LimitedDetails Paid with
> 
> What I understand from your previous messsages on multiple channels is that you purchased a plugin from our colleagues at Webkul to simplify the configuration for S3 and having problems with it? It's true that it was developed to simplify the configuration so that you wouldn't have to change things manually, but it was not developed to fix a mistake made by Bagisto. In case you want support related to this plugin you can (and most probably already did) contact [Webkul](https://bagisto.uvdesk.com/en/customer/create-ticket) because we do not provide any support on Github for these packages.
> 
> Bagisto is an open source application and is maintained by more people than just Webkul. The accusation that we create certain issues and then charge you for them makes no sense. Daily / weekly people report issues or feature requests and if you look at the number of pull requests you see that we solve the most problems quickly without charging anyone for this or selling the solution as a separate module.

Lots of talks.. I pair money now please fix this issue with s3. Sadly before the plugin I Purchased to fix this issue, s3 worked perectly.

**Comment by devansh-webkul** [comment]
@ghermans and @jitendra-webkul,

I have started working on this.
