### ISSUE TITLE
Bagisto #1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation

### ISSUE THREAD

**Issue by mahbubrajiv** [bagisto/bagisto#2015]
Bagisto 0.2.2
Work absolutely fine in Wamp Sever locally.
But, When I upload the project on Shared Hosting, The database file (bagisto.sql) in phpmyadmin on cpanel it says:
#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation.
and can't upload sql file in phpmyadmin on cpanel.
Oviously we don't have Super Privilege on Shared Hosting, what can we do?

![report](https://user-images.githubusercontent.com/20956733/72010383-f45b1000-3281-11ea-8115-0f2879aee261.png)

**Comment by popperhead** [comment]
The user of the database that @mahbubrajiv is using is not having root level permissions for the database.

**Comment by rahulshukla-webkul** [comment]
Hi @mahbubrajiv 

Please follow the given link - https://stackoverflow.com/questions/31315660/1227-access-denied-you-need-at-least-one-of-the-super-privileges-for-thi

**Comment by mahbubrajiv** [comment]
I also change DEFINER acordinding my username which in the .env file but it does not work!

**Comment by popperhead** [comment]
> 
> 
> I also change DEFINER acordinding my username which in the .env file but it does not work!

It will not work the implementation of slugs using triggers has caused slight inconsistency in data reusability.

**Comment by mahbubrajiv** [comment]
Hi @rahulshukla-webkul
Thanks a lot.. 

This issue might be close because after go to this link-
https://stackoverflow.com/questions/31315660/1227-access-denied-you-need-at-least-one-of-the-super-privileges-for-thi

I read it carefully and at last I can understand that I am tring to change DEFINER (e.g. root) acording to my .env file but it should be according to my cpanel username.

![issue 1](https://user-images.githubusercontent.com/20956733/72159893-8a5c7b00-33e7-11ea-9135-c9a7d1e53fb4.png)

At last I can successfully upload my database.

![issue 2](https://user-images.githubusercontent.com/20956733/72159939-9d6f4b00-33e7-11ea-8e4f-18dca780d9a9.png)

Thank you All.
