### ISSUE TITLE
Create Product Bug on PHP version 7.4

### ISSUE THREAD

**Issue by RahulDey12** [bagisto/bagisto#2021]
# Bug report

### Product Creation Bug on PHP 7.4
**After Creating a product on PHP 7.4 I am getting an error message Trying to access array offset on value of type null**

### Issue Description
![image](https://user-images.githubusercontent.com/26340814/72105406-867f1900-3353-11ea-8efb-fc728cd2eb17.png)

### Preconditions

    1. framework Version is v0.1.0
    2. PHP version 7.4.1

### Steps to reproduce

    1. Login To The Admin Dashboard
    2. Add New Product

### Expected result
**A product should be add**

*   [Screenshot is attached already]

### Actual result

>    **Trying to access array offset on value of type null**

**Comment by jyoti-webkul** [comment]
Hi @RahulDey12 
Please take a pull from master

**Comment by jitendra-webkul** [comment]
Fixed in #2013
