### ISSUE TITLE
API route for products throws error

### ISSUE THREAD

**Issue by estabanz** [bagisto/bagisto#2033]
route /api/product throws:

"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'product_id' in 'field list' (SQL: select `product_id` from `products` where `products`.`parent_id` = 33 and `products`.`parent_id` is not null)"

Tracked down to Line 110 in \packages\Webkul\Product\src\Helpers\Price.php

Change
->whereIn('product_id', $product->variants()->pluck('product_id')->toArray())

To 
->whereIn('product_id', $product->variants()->pluck('id')->toArray())

Not sure if the error is driven by my data or its a bug. I assume this was tested but its unclear since the api isn't versioned.

**Comment by rahulshukla-webkul** [comment]
Hi @estabanz 

Can you tell me , which version of bagisto you are using.

**Comment by jitendra-webkul** [comment]
Mixed in master

**Comment by jyoti-webkul** [comment]
- Fixed

-------------------------------
