### ISSUE TITLE
A pop-up confirmation should display before deleting an address.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#204]
Framework Version: 0.1.1
If user click on delete for the saved address then it gets deleted without any confirmation.

**Comment by rahulshukla-webkul** [comment]
When a user delete address then a pop up will display for confirmation.
![address](https://user-images.githubusercontent.com/42834394/49588525-eb1bb780-f98c-11e8-85a2-bb91491c9f5a.png)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
![screenshot from 2018-12-21 17-26-32](https://user-images.githubusercontent.com/45203177/50341654-ae7fbc80-0545-11e9-9b58-826192681158.png)
