### ISSUE TITLE
composer create-project bagisto/bagisto bagisto fails

### ISSUE THREAD

**Issue by rabol** [bagisto/bagisto#2040]
I have noticed that after the latest release, the installation is having a issue

I'm using Laravel homestead
I have created a new site and specified the php version to be 7.2
On the command line I execute this:

composer create-project bagisto/bagisto bagisto

It starts downloading v 0.2.2
  - Installing bagisto/bagisto (v0.2.2): Loading from cache
    Failed to execute unzip -qq  'bagisto//42eb53d8e2b1a8735d3dd57e44159190' -d '/home/vagrant/code/vendor/composer/c4747b87'

replace /home/vagrant/code/vendor/composer/c4747b87/bagisto-bagisto-20d61d1/packages/Webkul/Shop/publishable/assets/images/arrow-down.svg? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class

Any hints ?

**Comment by jyoti-webkul** [comment]
@rabol 
 composer create-project bagisto/bagisto it will install the latest stable version in your system.
If you want to install master please write only composer create-project

**Comment by rabol** [comment]
Sorry, i'm not sure I completely understand what you mean

composer create-project 
```
Composer could not find a composer.json file in /home/vagrant/code
  To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

composer create-project bagisto

```
[InvalidArgumentException]
  Could not find package bagisto with stability stable.
```

**Comment by rahulshukla-webkul** [comment]
Hi @rabol 

Can you tell about your environment, where you are running this command as we are running this on our localhost and not getting this kind of error.

May be there is problem with environment as it seems that you are using vagrant.

**Comment by jitendra-webkul** [comment]
@rabol,

There is no reply here from the last 19 days so I am closing this issue.

**Comment by wilbyang** [comment]
I have the same problem: symptom are: 
``` [RuntimeException]
  The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)```

**Comment by devmaster0322** [comment]
I also met this error

**Comment by devansh-webkul** [comment]
@devmaster0322,

Looks like a permission issue in your instance.
