### ISSUE TITLE
Category not updating

### ISSUE THREAD

**Issue by traceyjas** [bagisto/bagisto#2043]
# Bug report

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master branch

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Try to update category

### Expected result
**Tell us what should happen.**

*  Updated category

### Actual result

Got an error

SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update `categories` set `position` = 2, `updated_at` = 2020-01-14 03:24:24 where `id` = 2)

**Comment by monter08** [comment]
hey, its was fixed? i have identical problem :/

**Comment by rahulshukla-webkul** [comment]
Hi @monter08 

create Database using this one - 

`CREATE DATABASE DATABASE-NAME CHARACTER SET utf8 COLLATE utf8_unicode_ci;`

**Comment by monter08** [comment]
Thats works, thanks!
