### ISSUE TITLE
Issue in checkout.Not able to checkout getting error message "Something went wrong"

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2044]
# Bug report

### Title
Issue in checkout.Not able to checkout getting error message "Something went wrong"
### Issue Description
Issue in checkout.Not able to checkout getting error message "Something went wrong"
### Preconditions

1.Framework-Master
    
### Steps to reproduce

    1. step1- Try to checkout.
   
### Expected result
Customer should be able to checkout.
### Actual result
Getting error message.
![Screenshot from 2020-01-14 10-41-28](https://user-images.githubusercontent.com/45203177/72315928-7ac88500-36ba-11ea-9649-23f9d0b17820.png)

**Comment by popperhead** [comment]
With saved address too, there are some issues.

**Comment by rahulshukla-webkul** [comment]
Hi @jyoti-webkul @popperhead 

Please run php artisan migrate then check.

**Comment by jyoti-webkul** [comment]
Working fine after running migrate command.
