### ISSUE TITLE
Forgot password not working due to recent changes in mail keys

### ISSUE THREAD

**Issue by popperhead** [bagisto/bagisto#2051]
# Bug report

In this file below:

https://github.com/bagisto/bagisto/blob/a7fe03602ff65a76b0087df18f32e397629f2c0a/packages/Webkul/Customer/src/Notifications/CustomerResetPassword.php#L24

**Change config('mail.from') to config('mail.from.address')**

**Comment by jyoti-webkul** [comment]
- Fixed
