### ISSUE TITLE
Do you have A Seeder for Product?

### ISSUE THREAD

**Issue by goldcoders** [bagisto/bagisto#2053]
Ive notice , there is no product seeder then i run php artisan migrate:fresh --seed

If by any change do you have a productseeder for demo?

I would like to quickly populate a demo site with dummy data like you have on your site...

can you share the databaseseeder for product thanks

**Comment by thyseus** [comment]
You can do:

`php artisan bagisto:generate product 100`

to generate 100 random products.

**Comment by goldcoders** [comment]
i tried running that command but its stuck or its just freeze and nothing happen

**Comment by goldcoders** [comment]
ive notice it is creating product non stop,
it should create 4k and counting products
if you specified 100 products, it should only create 100 products
but it keeps creating non-stop number of products
it appears freezing but, the reality is , it is not stopping creating products
seems the issue is with the event listener
i tried returning  it earlier by DD 
and the issue is DD wont even be reach
after this line 135 Webkul\Product\Repositories\ProductRepositor
` Event::fire('catalog.product.create.after', $product);
`

**Comment by rahulshukla-webkul** [comment]
Hi @goldcoders 

Right now we did't have any seeder for product but you can create using above command and we are checking this commands issue.

**Comment by goldcoders** [comment]
at least tell me what version has a working product generator thanks

**Comment by jitendra-webkul** [comment]
@goldcoders You can check out the following repository:

https://github.com/bagisto/laravel-data-faker

**Comment by rahulshukla-webkul** [comment]
Hi @goldcoders 

We have checked that command and its working perfectly, you can use our master branch to test it.

**Comment by jitendra-webkul** [comment]
@goldcoders I am closing this issue. I hope, you problem has been solved.
