### ISSUE TITLE
Automatically 1st item of bundle is getting selected as a default after saving product.

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#2054]
# Bug report

### Title
automatically 1st item of bundle is getting selected as a default after saving product.
### Issue Description:
while creating product if admin didn't select any item as a default in bundle and save the product then automatically 1st item of that bundle is getting selected.    
### Preconditions
    1. framework Version. master

### Steps to reproduce
    1. step1: create a bundle type product, do not select any item as a default and save the product 
    2. step2: edit that product

### Expected result:
no item should get selected 
### Actual result:
1st item is getting selected after saving the product.

**Comment by jyoti-webkul** [comment]
- Not fixed

-----------------------
![Screenshot from 2020-01-27 12-19-47](https://user-images.githubusercontent.com/45203177/73155022-55e30180-40ff-11ea-8033-0a721177126d.png)

**Comment by jyoti-webkul** [comment]
- Fixed
