### ISSUE TITLE
Image validation is not working properly on editing slider.  

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#2070]
# Bug report

### Title
Image validation is not working properly on editing slider.  
### Issue Description:
after removing slider image if admin save the slider then there is no validation even previous image does not remove.
### Preconditions
    1. framework Version. -master
    

### Steps to reproduce
    1. step1: Create a slider 
    2. step2: edit that and remove image and save  

### Expected result:
after removing image while saving slider,it should give validation msg 
### Actual result
removed image gets saved again

**Comment by vaishaliwebkul** [comment]
Fixed,
Now the slider image is mandatory
