### ISSUE TITLE
Webkul\Core\Repositories\SliderRepository does not exist

### ISSUE THREAD

**Issue by rufw91** [bagisto/bagisto#2073]
### Webkul\Core\Repositories\SliderRepository does not exist
I get this error in a fresh install
**Please assist**

**Comment by prateek-webkul** [comment]
Hello rufw91,

Please use our latest version [Bagisto 0.2.2](https://github.com/bagisto/bagisto/tree/v0.2.2)

Thanks

**Comment by jitendra-webkul** [comment]
Fixed in new release

**Comment by rufw91** [comment]
Thanks
