### ISSUE TITLE
Configurable Product API not returning Attributes of Variants

### ISSUE THREAD

**Issue by rashidfornajah** [bagisto/bagisto#2077]
# Configurable Product API not returning Attributes of Variants

### Preconditions
**You should have at-least one Configurable product with multiple variants**
    1. 0.1.8

### Expected result
**For each variant, attributes should come in API**

**Comment by rashidfornajah** [comment]
Same issue exists in latest release version v0.2.2

**Comment by jyoti-webkul** [comment]
@rashidfornajah 
You will get the attribute under super attribute section
![Screenshot(4)](https://user-images.githubusercontent.com/45203177/72802465-e0e07980-3c71-11ea-9258-f93a85c01d95.png)

**Comment by rashidfornajah** [comment]
@jyoti-webkul super attribute section is having all the attributes for the product. But what about variant wise attributes . Because every variant is having different attributes. Right?

**Comment by rashidfornajah** [comment]
@jitendra-webkul  @jyoti-webkul Have you checked it? I hope my issue is clear to you

**Comment by jitendra-webkul** [comment]
Hi @rashidfornajah 

You can use the following endpoint in order get configurable attribute information:

https://www.example.com/api/product-configurable-config/{id}

**Comment by rashidfornajah** [comment]
@jitendra-webkul ok thanks. but my suggestion it is better to have variants attributes in same products API

**Comment by jitendra-webkul** [comment]
@rashidfornajah ,

I order to improve performance for product fetch, we separated both API.
