### ISSUE TITLE
Custom Attributes are not shown in the Website for Configurable products variants

### ISSUE THREAD

**Issue by rashidfornajah** [bagisto/bagisto#2078]
# Custom Attributes are not shown in the Website for Configurable products variants

### Custom Attributes are not shown in the Website for Configurable products variants
**A new Attribute family with custom attribute is not getting displayed in website**
**Although it is visible in Admin and working fine there**

### Preconditions
    1.Framework version 0.1.8.

### Steps to reproduce
    1. Create one Attribute family
    2. Add one custom attribute to that new family
    3. Create one Configurable product using that attribute family
    4. Check that product in website

**Comment by bhanu-webkul** [comment]
Hi @rashidfornajah ,

Could you please mention Custom Attribute Type

**Comment by rashidfornajah** [comment]
Custom Attribute Type is "select" same like color and size

**Comment by rahulshukla-webkul** [comment]
Hi @rashidfornajah 

There is a field called 'Visible on Product View Page on Front-end' while creating and editing attribute, set yes to this field. ( https://prnt.sc/qqkdct )

**Comment by rashidfornajah** [comment]
@rahulshukla-webkul Yes it is already set "YES"

**Comment by rahulshukla-webkul** [comment]
Hi @rashidfornajah 

Can you attach your dump of database so that we can check.

**Comment by jitendra-webkul** [comment]
No reply from the last 16 days, I hope your issue got resolved. So i am closing this issue for now. Feel free to open this issue.
