### ISSUE TITLE
Hide unused attribute values

### ISSUE THREAD

**Issue by ms-gsp** [bagisto/bagisto#2079]
Hello,
if i have a Color filter in layered navigation, when i dont have products i can see all options. How i can hide unused options from Color?

**Comment by rahulshukla-webkul** [comment]
Hi @ms-gsp 

Right now all attributes value are showing but soon we will change this one so that only used attributes value will be show.

**Comment by ms-gsp** [comment]
Hello again,
can you give me some function to check for options that are not used in products.
I cant find any
attributes_options is the table but... i need that asap

**Comment by ms-gsp** [comment]
Any update?

**Comment by rahulshukla-webkul** [comment]
Hi @ms-gsp 

We can not implement this one as we need this attributes but if you need then you can customise it.
