### ISSUE TITLE
Getting exception while adding configurable/bundle/grouped/Downloadable Type product to cart

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#2087]
# Bug report

### Title
getting exception while add configurable product to cart
### Preconditions
    1. framework Version.Master

### Steps to reproduce
    1. step1: create a configurable product
    2. step2:try to add to cart that product 

### Expected result:
product page should get open 
### Actual result:
getting exception
![Screenshot from 2020-01-21 17-56-34](https://user-images.githubusercontent.com/52821836/72804956-c0b3b900-3c77-11ea-8c8a-d35075d09afd.png)

**Comment by bhanu-webkul** [comment]
Error message needs to be change for bundle type products.

![Screenshot - 2020-01-24T092246 759](https://user-images.githubusercontent.com/52821836/73043462-304dc200-3e8b-11ea-972f-cfdd4134506c.png)

**Comment by jyoti-webkul** [comment]
- Fixed

------------------------

**Comment by jyoti-webkul** [comment]
- Still getting this error message

-----------------------------------------------

![Screenshot from 2020-01-27 16-07-36](https://user-images.githubusercontent.com/45203177/73168795-9606ac00-4120-11ea-9e43-57fb5f152ab4.png)

**Comment by jyoti-webkul** [comment]
- Fixed

----------------------

![Uploading Screenshot from 2020-01-28 11-46-14.png…]()
