### ISSUE TITLE
Installation issue, getting exception on migrate command.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2118]
# Bug report

### Title
Installation issue, getting exception on migrate command.

### Issue Description
Installation issue, getting exception on migrate command.

### Preconditions
    1. framework Version.- master

### Steps to reproduce

    1. step1- Run php artisan migrate after installation.

### Expected result
Migration should be completed

### Actual result

Getting exception
![Screenshot from 2020-01-22 13-36-08](https://user-images.githubusercontent.com/45203177/72876448-88b28180-3d1c-11ea-86e5-1d48f8a32488.png)

**Comment by bosix** [comment]
Hi @jyoti-webkul  

it seems that there is a table missing when creating the trigger. Since migrations are working in the pipeline, it might be an error at your setup.

Do you have used `php artisan migrate` or `php artisan migrate:fresh`? If it's the first one: at which commit was your setup before?

**Comment by rahulshukla-webkul** [comment]
Hi @bosix 

Actually, it is problem with database prefix as table name is given in trigger without prefix.

**Comment by bosix** [comment]
Hi @rahulshukla-webkul 

Alright. Do you want some help in order to fix this? Theoretically you just have to fetch the prefix from config in the migration and add it to the table name at the beginning and inside the queries itself.

**Comment by rahulshukla-webkul** [comment]
Hi @bosix 

If you wish then, you can create PR for the same as we need much contributor to our repository.

**Comment by bosix** [comment]
Hi @rahulshukla-webkul @jyoti-webkul 

I fixed the problems inside the migrations but this does not fix the problem at all. Tests are still failing and manual testing verifies that no category can be saved when DB_PREFIX is set (see the picture below). It seems that kalnoy/nestedset (the extension bagisto is using for category-tree) does not support db-prefixes.

![image](https://user-images.githubusercontent.com/26360670/73140818-5f2b8a00-407d-11ea-80a6-e3986d820bba.png)

**Comment by bosix** [comment]
Well... there was a layer 8 issue at my side. Long story short: I missed one trigger.

See related pr for the fix.
