### ISSUE TITLE
Click on add attribute, error is thrown.

### ISSUE THREAD

**Issue by iamgraeme** [bagisto/bagisto#2128]
# Bug report

### Title
Cant add or edit product attributes

### Issue Description
Click on add attribute, or edit color for example and error is thrown.

Trying to access array offset on value of type null (View: /Users/*****/Sites/bag_purp/packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php)

### Steps to reproduce
Click on add attribute, or edit color for example and error is thrown.

<img width="1680" alt="Screenshot 2020-01-23 at 13 01 41" src="https://user-images.githubusercontent.com/47456146/72986854-02ac3e80-3de1-11ea-8908-74bfdbc4fbd9.png">
<img width="1680" alt="Screenshot 2020-01-23 at 13 01 56" src="https://user-images.githubusercontent.com/47456146/72986855-0344d500-3de1-11ea-92f5-27aa2ba4955e.png">

**Comment by rahulshukla-webkul** [comment]
Hi @iamgraeme 

Which version of bagisto you are using.

**Comment by jitendra-webkul** [comment]
Fixed in master, thanks for notifying us.

**Comment by jyoti-webkul** [comment]
Not getting this issue in master
