### ISSUE TITLE
View all link is not required on Rating and Review page.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#213]
Framework Version: 0.1.1
![image](https://user-images.githubusercontent.com/45203177/49147197-0736ad80-f32a-11e8-94db-b42b71c0183c.png)

**Comment by rahulshukla-webkul** [comment]
Removed View all link from Rating and Review page.
![view-all](https://user-images.githubusercontent.com/42834394/49205415-f0996080-f3d4-11e8-81e6-c53f82fe55a2.png)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
