### ISSUE TITLE
Logic error in exchange rate calculation

### ISSUE THREAD

**Issue by adavie1** [bagisto/bagisto#2139]
# Bug report

### Title
When having mutiple exchange rates, other than the base currency, the display values are way off: for example: USD112 product in MYR(4.20) the price shown RM1991. The actual value should RM474.

### Issue Description
What's is happening is the `Core::convertPrice` method is being called twice, the first time it gets the right price, the second time it's using the already converted price and applying the same rate to that price.

### Preconditions
Current master code as at commit #2137

### Steps to reproduce
Create an exchange rate under admin, then in the shop change to that exchange rate.

### Expected result
Correct calculation of rate.

*   I've already solved this in the Core.php. 

### Fix
Because the DOM is loaded twice, the `convertPrice` is called twice as well. the first time, with the correct values returned. 

The next call to `convertPrice` uses the already converted price, and converts it again.

Before the constructor of Core.php:

```
protected $lastCurrencyCode ;

    /**
     * Create a new instance.

```

Then modify `convertPrice` as follows:
```
/**
    * Converts price
    *
    * @param float  $amount
    * @param string $targetCurrencyCode
    * @return string
    */
    public function convertPrice($amount, $targetCurrencyCode = null)
    {

      if (!$this->lastCurrencyCode)
         $this->lastCurrencyCode = $this->getBaseCurrency()->code ;

        $targetCurrency = ! $targetCurrencyCode
                        ? $this->getCurrentCurrency()
                        : $this->currencyRepository->findOneByField('code', $targetCurrencyCode);

        if (! $targetCurrency)
            return $amount;

        $exchangeRate = $this->exchangeRateRepository->findOneWhere([
            'target_currency' => $targetCurrency->id,
        ]);

        if (null === $exchangeRate || ! $exchangeRate->rate)
            return $amount;

        $result = (float) $amount * (float) ($this->lastCurrencyCode == $targetCurrency->code ? 1.0 : $exchangeRate->rate);
//        Log::info("convertPrice ($amount, $targetCurrency->code, $this->lastCurrencyCode, $exchangeRate->rate) = $result");

        if ($this->lastCurrencyCode != $targetCurrency->code)
           $this->lastCurrencyCode = $targetCurrency->code ;

        return $result;
    }
```

**Comment by adavie1** [comment]
As you can see, the invoices also are wrong. The actual order value USD112 and the exchange rate to MYR is set at 4.2.

Because the DOM is loaded twice, the exchange rate calculation is done once (correctly) then the returned number is passed back to the exchange rate calculation on the second reload.

From my logging of the function:
```
Log::info("convertPrice ($amount, $targetCurrency->code, $this->lastCurrencyCode, $exchangeRate->rate) = $result") = 474.22

Log::info("convertPrice ($amount, $targetCurrency->code, $this->lastCurrencyCode, $exchangeRate->rate) = $result") = 1,991.73  which 474.22 * 4.2
```

![image](https://user-images.githubusercontent.com/3030402/73623143-f2188580-4676-11ea-8c3b-4d17b8a7cf53.png)

**Comment by rahulshukla-webkul** [comment]
Hi @adavie1

Thanks for raising this one and providing solution.

**Comment by jyoti-webkul** [comment]
- Fixed
