### ISSUE TITLE
 SQLSTATE[42S02]: Base table or view not found: 1146 Table '[DB_PREFIX].category_translations' doesn't exist

### ISSUE THREAD

**Issue by lucky1968** [bagisto/bagisto#2141]
When using a DB_PREFIX all tables are created correctly bu in the code it looks for '[DB_PREFIX].category_translations' instead of '[DB_PREFIX]category_translations' (without the dot '.').

**Comment by bosix** [comment]
Hi @lucky1968 

it seems that your issue is related with #2118.

Can you please add the exception/stack trace of the error? I'll have a look at it then.

**Comment by bosix** [comment]
Hi @lucky1968 

please add the complete exception/stack trace to this issue.

**Comment by rahulshukla-webkul** [comment]
Hi @lucky1968 

This issue has been fixed in master branch, kindly take pull from master branch.

**Comment by 3bkry** [comment]
this problem because of DB_PREFIX in env
