### ISSUE TITLE
Attributes filterable checkbox - those who do not know will think that a bug!

### ISSUE THREAD

**Issue by DivOverlow** [bagisto/bagisto#2143]
When creating a product filter by checkbox. There was a problem with filterable. I admit that I can intentionally cut the rights of the checkbox. But what is he worse - multiselect.

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Attribute/src/Repositories/AttributeRepository.php

`  /**
     * @param array $data
     * @return array
     */
    public function validateUserInput($data)
    {
        if ($data['is_configurable']) {
            $data['value_per_channel'] = $data['value_per_locale'] = 0;
        }

        if (! in_array($data['type'], ['select', 'multiselect', 'price'])) {
            $data['is_filterable'] = 0;
        }

        if (in_array($data['type'], ['select', 'multiselect', 'boolean'])) {
            unset($data['value_per_locale']);
        }

        return $data;
    }`

**Comment by rahulshukla-webkul** [comment]
Hi @DivOverlow 

Your concern is definitely right, we have added checkbox too.
Thanks for your valuable suggestion.

**Comment by jyoti-webkul** [comment]
- Fixed

-------------------------

![Screenshot (67)](https://user-images.githubusercontent.com/45203177/73832677-a4467d80-482e-11ea-91dd-3659fb9fc03c.png)
