### ISSUE TITLE
Emails don't work on registration

### ISSUE THREAD

**Issue by adavie1** [bagisto/bagisto#2145]
# Bug report

### Title
When registering, no email is received with the password.

### Preconditions
Using the current master version of the repo.

### Steps to reproduce
Register, check email.

### Expected result
An email with the password, as per the RegistrationController code.

In the past, Laravel had a jobs table, which I don't see my table list. Not sure if this changed in Laravel 6.0

My `.env` looks like this:

```
APP_NAME=Bagisto
APP_ENV=local
APP_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost:8000

LOG_CHANNEL=single
APP_LOG_LEVEL=info

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=bagisto
DB_USERNAME=XXXXX
DB_PASSWORD=XXXXXXX

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=4968a68dd4e3a8
MAIL_PASSWORD=XXXXXXXXXXX
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=support@XXXXX
MAIL_FROM_NAME="${APP_NAME}"
SHOP_MAIL_FROM=support@XXXX

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

```

**Comment by jyoti-webkul** [comment]
- Working fine

----------------------------------

![Screenshot (30)](https://user-images.githubusercontent.com/45203177/73235313-e9760a00-41b3-11ea-9d24-364d87ca6dee.png)

**Comment by bosix** [comment]
Hi @adavie1 

the current master also contains improved logging. You may update your bagisto, try again to register and have a look at `storage/logs/laravel.log`

**Comment by adavie1** [comment]
The issue was the `MAIL_ENCRYPTION=ssl` That messed things up.

**Comment by sohaib12296** [comment]
MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=xxxxxxxxxxxx
MAIL_PASSWORD=xxxxxxxxxxxx
MAIL_ENCRYPTION=tls


this is my .env setup and iam not recieving mails on any event.

**Comment by devansh-webkul** [comment]
Hi @sohaib12296,

- Check your laravel logs, `storage/logs/laravel.log`.
- One more thing change your shop email from the admin panel. Don't use the `example.com` domain as this does not comply.
