### ISSUE TITLE
Got exception once on removing product from cart.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2154]
# Bug report

### Title
Got exception once on removing product from cart.
### Issue Description
Got exception once on removing product from cart.

### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Add a bundle product in cart by selecting multiple option
    2. step2- Remove one option from cart.

### Expected result
Product should get removed from cart.

### Actual result

![Screenshot from 2020-01-27 15-04-39](https://user-images.githubusercontent.com/45203177/73163843-c3e6f300-4116-11ea-8210-ab12b8a614d7.png)

**Comment by jitendra-webkul** [comment]
Can't reproduce this issue
