### ISSUE TITLE
[shipping/invoicing] address handling has major flaws

### ISSUE THREAD

**Issue by thyseus** [bagisto/bagisto#2155]
# Bug report

### Steps to reproduce

1. register a new customer with firstname F1 and lastname N1
2. login as this customer
3. in profile menu: add a invoicing address - F1 and N1 are filled automatically because
customer_addresses has no dedicated first_name and last_name fields (there is a "name" column but this one is broken and is _always_ NULL)
4. Buy something in the store and add a secondary invoicing or shipping address. Enter a different first (F2) and last name (F2)
5. The second address is inserted correctly but the F2 and N2 name is completely forgotten by the system. The Invoice/Shipment would go wrongly to F1 and N1.

### Expected result
The F2 and N2 should have been saved in the new address in its own dedicated database fields.

### Actual result

The F2 and N2 data is not saved. The generated order is linked to the wrong address.

### Solution:

Add a migration that _renames_ the "name" column to last_name and create a field first_name in the customer_addresses table. Then link the order controller logic in the OnePageController to handle the fields correctly.

Is this Bug known ? Do you want me to create a PR that fixes this issue or do you already have in on your monitor ?

Thanks a lot.

**Comment by rahulshukla-webkul** [comment]
Hi @thyseus 

Thanks for notifying this to us.

**Comment by thyseus** [comment]
@rahulshukla-webkul @jitendra-webkul thanks a lot for the very quick fix !
