### ISSUE TITLE
Taking more time to load product details in shopping cart.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2159]
# Bug report

### Title
Taking more time to load product details in shopping cart.
### Issue Description
Taking more time to load product details in shopping cart.
### Preconditions
    1. framework Version.-master

### Steps to reproduce

    1. step1- Add product to cart
    2. step2- Click on view shopping cart

### Expected result
Product data should load instantly.

### Actual result

Take more time to load the data.

![Screenshot from 2020-01-27 17-42-32](https://user-images.githubusercontent.com/45203177/73173895-72496300-412c-11ea-81d5-cb5262338ac2.png)

**Comment by jitendra-webkul** [comment]
We are using Vue component to render quantity box and It waits for page to load completely thats Its taking more time.
