### ISSUE TITLE
product's special price should not greater than price

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2162]
# Bug report

### Title
Special price should always be less than the normal price

### Issue Description
When adding products that contain a price of $100 & a special price of $500 than in front end greater price value is showing instead of the minimum price if the product is under sale.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version- master

### Steps to reproduce

    1. step1- add product, insert price $100, special price $500
    2. step2- now, check the product price in the front end

### Expected result

-  show the minimum value of price or special price
or
-  we can add validation in the backend that special price can't be greater than the price 

### Actual result

>    
![Screenshot (15)](https://user-images.githubusercontent.com/43210406/73240669-a91f8780-41c5-11ea-8c58-4b6f12c0f085.png)
![Screenshot (16)](https://user-images.githubusercontent.com/43210406/73240725-d409db80-41c5-11ea-945d-d66e95b0966a.png)

**Comment by jyoti-webkul** [comment]
- Fixed
