### ISSUE TITLE
Left to right scroller of installer doesn't work.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2163]
# Bug report

### Title
Left to right scroller of installer doesn't work.

### Issue Description
Left to right scroller of installer doesn't work.
### Preconditions

    1. framework Version.- master

### Steps to reproduce

    1. step1- Installer framework through installer
    2. step2- Check after all commands run successfully

### Expected result
user should be able to scroll
### Actual result
![Screenshot from 2020-01-28 12-02-47](https://user-images.githubusercontent.com/45203177/73241237-7aa2ac00-41c7-11ea-9755-d210d0173fb1.png)

**Comment by ghermans** [comment]
Actually the fact that you use the installer on a desktop means that there shouldn't have to be a scroll bar inside the content div. a better title would be, **Make the installer responsive **

**Comment by ghermans** [comment]
@jyoti-webkul @rahulshukla-webkul i will fix this issue tonight, with some other minor css issues that the web installer has.
