### ISSUE TITLE
Redirect to incorrect url when click on finish button after installing through installer.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2164]
# Bug report

### Title
Redirect to incorrect url when click on finish button after installing through installer.

### Issue Description
Redirect to incorrect url when click on finish button after installing through installer.
### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Install bagisto through installer
    2. step2- Click on finish button

### Expected result

It should redirect to admin panel.
### Actual result

Redirecting to incorrect url.

![Screenshot from 2020-01-28 12-22-10](https://user-images.githubusercontent.com/45203177/73241902-77102480-41c9-11ea-91ef-fe00ac28053b.png)

![Screenshot from 2020-01-28 12-22-14](https://user-images.githubusercontent.com/45203177/73241907-7e373280-41c9-11ea-8d07-fa55c32db5d7.png)

**Comment by rahulshukla-webkul** [comment]
Hi @jyoti-webkul 

Please check using domain.

**Comment by jyoti-webkul** [comment]
ok, working fine with localhost
