### ISSUE TITLE
Category image can be add from anywhere

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2177]
# Bug report

### Title
able to select a category image from anywhere in the image section

### Issue Description
able to add a category image from anywhere in the image section

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add a category
    2. step2- select a category image by clicking anywhere in the image grid instead of the image box

### Expected result

-  an image can only be selected when we click on the image box

### Actual result

>    
![Screenshot from 2020-01-28 16-47-32](https://user-images.githubusercontent.com/43210406/73259574-18a96d00-41ee-11ea-8eae-046183516234.png)

**Comment by jyoti-webkul** [comment]
This issue exist for Channel also

**Comment by vaishaliwebkul** [comment]
Fixed
