### ISSUE TITLE
Seperate streetname and number

### ISSUE THREAD

**Issue by Tune389** [bagisto/bagisto#2178]
This report is not directly a technical bug, I'm currently writing a simple package for DHL Shipment in Germany, it's required to separate the street name and number since 2019 on the API from DHL. So my main issue here is the order addresses, they are saved with street name and number in the same field. I separate them at the moment via regex but it would be a way better to already separate it on the user input and database because there are a lot of variations.

**Comment by rahulshukla-webkul** [comment]
Hi @Tune389 

You can create your custom package for same. In this package add field in database according to your need and override the order address model.
Read this to override model - https://devdocs.bagisto.com/override-core-model.html

Add fillable  attributes in this model, now you need to override view file (checkout) to add your field and you can do it as follows-  https://forums.bagisto.com/topic/221/how-to-override-view-file-in-bagisto

**Comment by jitendra-webkul** [comment]
Hi @Tune389 ,

You can set "Lines in a Street Address" in Configuration > Customer > Settings menu. This will create multiple street lines for customer addresses.

**Comment by jitendra-webkul** [comment]
For now, I am closing this issue, feel free to reopen this issue. If that does not solve your issue.
