### ISSUE TITLE
missing option in Customer's Gender at admin end

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2182]
# Bug report

### Title
One option is missing in gender field

### Issue Description
In the customer panel, 3 options available(male, female, other) in the gender field but in the admin end, there are only two options(male, female) available.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version-master

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug. If relevant please include code samples.**

    1. step1- go to the admin end, view customer's gender drop down options.
    2. step2- go to the customer end, view customer's gender drop down options

### Expected result

*  In both panels, equal options should be available in the gender field.

### Actual result
  
![Screenshot from 2020-01-28 17-25-34](https://user-images.githubusercontent.com/43210406/73262092-6eccdf00-41f3-11ea-8f64-60519451cb91.png)

![Screenshot from 2020-01-28 17-26-03](https://user-images.githubusercontent.com/43210406/73262131-85733600-41f3-11ea-8dea-ecd25262d59e.png)

**Comment by vaishaliwebkul** [comment]
by default, other options get select in the gender field at admin end

**Comment by vaishaliwebkul** [comment]
gender field warning translation issue exist

![Screenshot (2)](https://user-images.githubusercontent.com/43210406/73631733-dd8cbb00-467f-11ea-811d-33a44501c038.png)

**Comment by jyoti-webkul** [comment]
- Fixed

-----------------------

![Screenshot from 2020-02-05 14-29-56](https://user-images.githubusercontent.com/45203177/73826570-064db580-4824-11ea-8975-30d3efaf2a72.png)
