### ISSUE TITLE
sku should be shown in product list if new product created

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2190]
# Bug report

### Title

Product SKU is not showing in the product list 

### Issue Description
When the product is created, the SKU field is mandatory but it's not showing in the list once product gets saved.

### Preconditions

    1. framework Version-master

### Steps to reproduce

    1. step1- create a product with the field, {product type,sku, attribute family,}
    2. step2- Now save the product and check the SKU column in the product list

### Expected result

*   SKU should be shown in the list if it's a mandatory field and already saved in DB

### Actual result

![Screenshot (23)](https://user-images.githubusercontent.com/43210406/73269543-07b72680-4203-11ea-8bab-8a0c029009c9.png)

![Screenshot (21)](https://user-images.githubusercontent.com/43210406/73269495-ece4b200-4202-11ea-97e3-0163025eaca3.png)

**Comment by jyoti-webkul** [comment]
- Fixed
