### ISSUE TITLE
Two dropdown option should be available when customer filter downloadable product according to Status.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2191]
# Bug report

### Title
Two dropdown option should be available when customer filter downloadable product according to Status.
### Issue Description
Two dropdown option should be available when customer filter downloadable product according to Status.

### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- From customer account filter product according to status.

### Expected result
Option Available and Expired should be given

### Actual result

![Screenshot from 2020-01-29 11-00-56](https://user-images.githubusercontent.com/45203177/73330391-a89af580-4286-11ea-9717-4683575b82bf.png)

![Screenshot from 2020-01-29 11-01-01](https://user-images.githubusercontent.com/45203177/73330402-b05a9a00-4286-11ea-9e58-3317ae14c52a.png)

**Comment by rahulshukla-webkul** [comment]
Hi @jyoti-webkul 

You can enter text there to search.
