### ISSUE TITLE
Change default datepicker

### ISSUE THREAD

**Issue by shdehnavi** [bagisto/bagisto#2197]
Hi
I want to replace default datepicker with Jalali datepicker
How I can?

**Comment by rahulshukla-webkul** [comment]
Hi @shdehnavi 

We have created component for date picker so you can also create your date picker and replace all default date picker with yours.
Replacing would be done by view override.

**Comment by michael-arif** [comment]
Can you please let me know when this is completed?
I need to customize datepicker (both on user's and admin's screen) to Japanese.
