### ISSUE TITLE
saved categories are not checked in condition of catalog/cart rule

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2203]
# Bug report

### Title
catalog/cart rule select condition as categories not get checked once saved in DB

### Issue Description
catalog/cart rule select condition as categories not get checked once saved in DB

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add & save a catalog rule condition based on selected categories
    2. step2- now edit the catalog rule again and observe the categories that selected are not marked.

### Expected result

*   categories whether root or child should be selected once saved in DB.

### Actual result

![Screenshot (3)](https://user-images.githubusercontent.com/43210406/73355577-70afa480-42be-11ea-9c54-531d6c324aca.png)

**Comment by jyoti-webkul** [comment]
- Not fixed

--------------------------

![Screenshot from 2020-02-05 13-59-42](https://user-images.githubusercontent.com/45203177/73824266-db616280-481f-11ea-8875-ee86e3329aae.png)

**Comment by jyoti-webkul** [comment]
- Fixed

----------------------

![Screenshot from 2020-02-05 15-59-52](https://user-images.githubusercontent.com/45203177/73833800-942f9d80-4830-11ea-9400-9e6a460e7a62.png)
