### ISSUE TITLE
category tree view doesn't visible in catalog rule condition

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2204]
# Bug report

### Title
category tree does not view in the catalog rule condition

### Issue Description

category tree does not view in the catalog rule condition if the existing condition by SKU update, once the rule is saved then it will get visible.

### Preconditions

    1. framework Version- master

### Steps to reproduce the issue

    1. step1- create a catalog rule & add a condition by selecting SKU attribute
    2. step2- save a catalog rule
    3. step3- edit a catalog rule and existing condition update by selecting a category
    4. step4- Now observe that the category tree will be missing.

### Expected result

*   category tree should be on each condition or cases

### Actual result

![Screenshot (4)](https://user-images.githubusercontent.com/43210406/73356873-50cdb000-42c1-11ea-8956-6d56259690ed.png)

![Screenshot (5)](https://user-images.githubusercontent.com/43210406/73356875-51664680-42c1-11ea-8eb2-82fae1aa233f.png)

**Comment by jyoti-webkul** [comment]
- Fixed

------------------------

![Screenshot from 2020-02-05 14-21-51](https://user-images.githubusercontent.com/45203177/73825928-e36ed180-4822-11ea-8667-778ec455d772.png)
