### ISSUE TITLE
 ErrorException (E_ERROR) Impossible to create the root directory 

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2206]
![Screenshot from 2020-01-30 01-23-34](https://user-images.githubusercontent.com/30912144/73419963-c8bacb00-42ff-11ea-94d0-fde74f1e4339.png)

**Comment by rahulshukla-webkul** [comment]
Hello @marcelowu 

Please follow this one - https://github.com/bagisto/bagisto/issues/826

**Comment by marcelowu** [comment]
Ok, thanks
