### ISSUE TITLE
Priority functionality of Inventory is not working.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2209]
# Bug report

### Title
Priority functionality of Inventory is not working.

### Issue Description
Priority functionality of Inventory is not working.

### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Set the priority of inventory as 0 of newly created inventory and 1 to default inventory.
    2. step2- But everywhere default inventory displays first.

### Expected result
Inventory with highest priority should display first while creating product and shipment.

### Actual result
Default inventory is displaying first.

![Screenshot from 2020-01-30 16-54-40](https://user-images.githubusercontent.com/45203177/73445993-f6485880-4381-11ea-943d-abcc1d3b5f66.png)

**Comment by jitendra-webkul** [comment]
Currently, there is no use Priority but in the future, this will be used in auto inventory source selection algo
