### ISSUE TITLE
SQL error for products variants

### ISSUE THREAD

**Issue by bastos71** [bagisto/bagisto#2210]
# Bug report

### Title
SQL Error in the getVariantMinPrice function

### Issue Description
File : `packages/Webkul/Product/src/Helpers/Price.php`
Method : `getVariantMinPrice`
Line : `110`

When searching  a product which has variants in the front office, an error occures : 
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'product_id' in 'field list' (SQL: select `product_id` from `products` where `products`.`parent_id` = 1 and `products`.`parent_id` is not null) (View: packages/Webkul/Shop/src/Resources/views/products/price.blade.php) (View: packages/Webkul/Shop/src/Resources/views/products/price.blade.php) (View: packages/Webkul/Shop/src/Resources/views/products/price.blade.php)
```

Seems like the column specified should be `id` instead of `product_id` 

****

### Preconditions

Version : `0.2.2`

### Steps to reproduce

I reproduced the error on the live demo, simply by searching for "Leather" (for the product "Leather Shoes")

**Comment by rahulshukla-webkul** [comment]
Hi @bastos71 

This issue has been fixed in master.

**Comment by bastos71** [comment]
Hello @rahulshukla-webkul yep I saw it but it stills exists for those who use numbered versions :/ 
We cannot use `master` as a base for new "real" projects

Anyway I suppose the version 1.0.0 is near and will integrate many fixes, any information about it ?

**Comment by rahulshukla-webkul** [comment]
Hi @bastos71 

In end of this week or may be in next week, we will release our 1.0.0 version.
