### ISSUE TITLE
Applied coupon code tag gets removed from the checkout page until page refresh

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2219]
# Bug report

### Title
Applied Coupon code is not showing on the checkout page.

### Issue Description
When the new coupon code is applied in the cart then it's calculated in price but removed from the page.

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add product in the cart
    2. step2- apply coupon code while checkout, now observe that it will get removed from the current page until the page refresh.

### Actual result
 
![Checkout](https://user-images.githubusercontent.com/43210406/73521708-b68a7b00-442c-11ea-9352-bf7a4e21838a.png)

**Comment by jyoti-webkul** [comment]
- Fixed

-----------------------

![Screenshot from 2020-02-05 15-13-41](https://user-images.githubusercontent.com/45203177/73830158-2c765400-482a-11ea-8680-24403060ca4d.png)
