### ISSUE TITLE
how to pass the price to gateway

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#2221]
hi i am trying to write a custom gateway for this package and here is what i have done :
i added this in config in payment module 
```
  'bank_pasargad' => [
        'code' => 'bank_pasargad',
        'title' => 'costum bank',
        'description' => 'bank',
        'class' => 'Webkul\Pasargad\Payment\Pasargad',
        'sandbox' => true,
        'active' => true,
        'business_account' => 'test@webkul.com',
        'sort' => 1
    ],
```
i made a package for my gateway and like below i added the method :
```
   protected $code  = 'bank_pasargad';

    public function getRedirectUrl()
    {
        return route('pasargad.request');
    }
```
now every thing is working fine just i dont know how to pass the price to my controller to give it to gate way and then i success the order . is there any documentation to that ??

**Comment by rahulshukla-webkul** [comment]
Hi @farshadff 

In your controller, you can get whole cart from which you will get all the necessary details about cart.

`Cart::getCart()`  

You can use below function to prepare data for order.

`Cart::prepareDataForOrder()`

**Comment by jitendra-webkul** [comment]
No reply from the last 10 days. I hope the above reply solved your issue.
