### ISSUE TITLE
After editing the product if we change the inventory of a product for particular locale then inventory of other locales also get updated with same quantity.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2224]
# Bug report

### Title
After editing the product if we change the inventory of a product for particular locale then inventory of other locales also get updated with same quantity.
### Issue Description
After editing the product if we change the inventory of a product for particular locale then inventory of other locales also get updated with same quantity.

### Preconditions

    1. framework Version.- master

### Steps to reproduce

    1. step1- Create a product for all inventory.
    2. step2- Now edit the product for any particular locale and update the inventory.
    3.step3- other locale inventory will also get updated.

### Expected result
Inventory should get updated only for the particular locale.

### Actual result

Inventory get updated for all locale.

**Comment by dejavuejs** [comment]
Inventory is not a locale dependent thing.
