### ISSUE TITLE
Error when trying to login with app.php locale set to ja

### ISSUE THREAD

**Issue by michael-arif** [bagisto/bagisto#2237]
# Bug report

### Title
Error occurred when trying to login to admin screen after setting app.php locale to ja.

### Issue Description
I'm trying to create a Japanese translation of Bagisto. After finalizing Bagisto' installation,
I changed the locale of the \bagisto\config\app.php from en to ja. Then, try to login into
the Admin screen. That's when this error occurred. If I set the locale to en, the error disappeared.
I guess that master.blade.php and anonymous-master.blade.php will always assume that the locale
set in the app.php is available. If it's not available, the error occurred.

### Preconditions
    1. framework Version: 0.2.2
    2. Commit id.

### Steps to reproduce
    1. Set \bagisto\config\app.php locale to ja.
    2. Browse http://ip-address/bagisto/public/admin/login

### Expected result
Login screen should appear and user can enter user id and password.

### Actual result
>    ErrorException (E_ERROR)
Trying to get property 'direction' of non-object (View: C:\xampp\htdocs\bagisto\packages\Webkul\Admin\src\Resources\views\layouts\master.blade.php)

**Comment by jitendra-webkul** [comment]
Hi @michael-arif ,

You can refer to the #2238 PR. This will fix your issue.
