### ISSUE TITLE
Getting exception when save a category with category logo

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2241]
# Bug report

### Title
Getting exception when saving a category with category logo

### Issue Description
Getting exception when saving a category with category logo

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add a category, upload category logo image

### Expected result

category logo should be saved

### Actual result

![Screenshot (5)](https://user-images.githubusercontent.com/43210406/73742115-b31b2a80-4771-11ea-8714-d5c18901e45c.png)

**Comment by jyoti-webkul** [comment]
- Fixed

-----------------
