### ISSUE TITLE
Velocity Header content status should be enabled by default

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2242]
# Bug report

### Title
Header content status should be enabled by default

### Issue Description
Header content status should be enabled by default

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Go to velocity section
    2. step2- add a new header content
    3. step3- check status is inactive 

### Expected result

status should be active by default

### Actual result

![Screenshot (6)](https://user-images.githubusercontent.com/43210406/73742505-90d5dc80-4772-11ea-8fb0-65e389a2b9b5.png)

**Comment by jyoti-webkul** [comment]
- Fixed

--------------------

![Screenshot (74)](https://user-images.githubusercontent.com/45203177/73847656-bdf6bd80-484c-11ea-86d3-2ff091a60fae.png)
