### ISSUE TITLE
slider content is not showing in velocity theme

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2245]
# Bug report

### Title
slider content is not showing

### Issue Description
slider content is not showing in the velocity theme

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add slider by adding the content description
    2. step2- check the slider content in a theme

### Expected result

slider content should be shown in the theme

### Actual result
 
![Screenshot (7)](https://user-images.githubusercontent.com/43210406/73744571-0d6aba00-4777-11ea-9f45-58a782334248.png)

![Screenshot (8)](https://user-images.githubusercontent.com/43210406/73744572-0d6aba00-4777-11ea-98a9-8f5bbbaec6fc.png)

**Comment by jyoti-webkul** [comment]
- Not fixed

-----------------------------

![Screenshot (76)](https://user-images.githubusercontent.com/45203177/73847905-2c3b8000-484d-11ea-9514-fecdda5c3214.png)

![Screenshot (75)](https://user-images.githubusercontent.com/45203177/73847922-31003400-484d-11ea-809a-de9d6681f950.png)

**Comment by jyoti-webkul** [comment]
- Fixed

---------------------

![Screenshot (80)](https://user-images.githubusercontent.com/45203177/73915962-7589df00-48e2-11ea-846c-249f481249e4.png)
