### ISSUE TITLE
slider disable functionality is not working

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2246]
# Bug report

### Title
slider disable functionality is not working

### Issue Description

When try to disable the slider by metadata configuration then a slider is not disabled.

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- velocity->meta data->disable activated slider button
    2. step2- Now check the slider should be disabled.

### Expected result

slider should disabled if the slider activates button is disabled.

### Actual result

![Screenshot (10)](https://user-images.githubusercontent.com/43210406/73745390-ee6d2780-4778-11ea-9443-b544dc4e7747.png)

![Screenshot (11)](https://user-images.githubusercontent.com/43210406/73745392-ee6d2780-4778-11ea-9735-8d5cad209aa2.png)

**Comment by jyoti-webkul** [comment]
- Fixed

--------------------

![Screenshot from 2020-02-05 20-01-36](https://user-images.githubusercontent.com/45203177/73850765-56dc0780-4852-11ea-972a-70d25486b914.png)

![Screenshot from 2020-02-05 20-01-32](https://user-images.githubusercontent.com/45203177/73850777-5c395200-4852-11ea-9a1e-9c744cd9d2ee.png)
