### ISSUE TITLE
show the warnings & mark all mandatory fields in customer profile

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2249]
# Bug report

### Title
show the warnings & mark all mandatory fields in the customer profile

### Issue Description

When saving a customer profile, unable to recognize which field is mandatory as no warning is showing when set theme velocity

### Preconditions

    1. framework Version- master
    2. theme- velocity

### Steps to reproduce

    1. step1- log in as a customer and save a customer profile with blank data

### Expected result
 
 1.  fields should be marked as mandatory
 2.  warnings should be highlighted for the blank fields

### Actual result

![Profile](https://user-images.githubusercontent.com/43210406/73746283-d8f8fd00-477a-11ea-8323-a9c170702738.png)

**Comment by jyoti-webkul** [comment]
- Fixed

-----------------------

![Screenshot from 2020-02-05 20-04-44](https://user-images.githubusercontent.com/45203177/73851002-cbaf4180-4852-11ea-9a3c-df5513122283.png)

**Comment by vaishaliwebkul** [comment]
1. Gender field is also mandatory, so it should also be marked *
2. warnings messages for gender field, password, confirm password validations are not working
3. show an alert if user input old password is incorrect
