### ISSUE TITLE
Order not filterable according to order id, when prefix or suffix is used in order setting.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2250]
# Bug report

### Title
Order not filterable according to order id.

### Issue Description
Order not filterable according to order id.

### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Go to order section of customer
    2. step2- Apply filter according to order id by selecting condition equals to.

### Expected result
Order should get filtered according to order id

### Actual result
![Screenshot from 2020-02-04 18-18-41](https://user-images.githubusercontent.com/45203177/73746365-0a71c880-477b-11ea-93ea-5014a2d1983e.png)

![Screenshot from 2020-02-04 18-18-29](https://user-images.githubusercontent.com/45203177/73746370-0f367c80-477b-11ea-89a1-660480a8d4eb.png)

**Comment by vaishaliwebkul** [comment]
Fixed
