### ISSUE TITLE
configurable product options could not get select

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2251]
# Bug report

### Title
Not able to select the configurable product variants options

### Issue Description
Not able to select the configurable product variants options

### Preconditions

    1. framework Version- master
    2. Theme- Velocity

### Steps to reproduce

    1. step1- go to the config product page and select an option available

### Expected result

variant options should be able to get select

### Actual result

![Screenshot (13)](https://user-images.githubusercontent.com/43210406/73746771-fa0e1d80-477b-11ea-814d-e0134e7f17a7.png)

**Comment by jyoti-webkul** [comment]
- Fixed

-------------------
