### ISSUE TITLE
Customer is not able to update his/her profile in velocity theme.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2253]
# Bug report

### Title
Customer is not able to update his/her profile in velocity theme.
### Issue Description
Customer is not able to update his/her profile in velocity theme.

### Preconditions

    1. framework Version.- master

### Steps to reproduce

    1. step1- Go to customer profile and update it.

### Expected result
Customer profile should get updated

### Actual result

Customer profile is not updating.

**Comment by jyoti-webkul** [comment]
- Fixed

----------------
Working fine now

**Comment by its-soa** [comment]
@jyoti-webkul @shubhwebkul @jitendra-webkul 

How was this fixed please? Also encountering the same issue here. Using Bagisto V1.1.2

**Comment by vaishaliwebkul** [comment]
@its-soa 
it's working fine on bagisto v1.1.2, could you please add some screenshot or steps to reproduce so that we can check again.
