### ISSUE TITLE
Fix layout for remove button in cart page for guest customer

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2254]
# Bug report

### Title

Fix layout for remove button in the cart page for guest customer

### Issue Description

Fix layout for remove button in the cart page for guest customer

### Preconditions

    1. framework Version- master
    2. Theme- Velocity

### Steps to reproduce

    1. step1- go to cart page without logged in
    2. step2- check the remove button 

### Expected result

remove button should be left-aligned

### Actual result

![Screenshot (14)](https://user-images.githubusercontent.com/43210406/73747873-58d49680-477e-11ea-8f28-92c269fc778e.png)

**Comment by jyoti-webkul** [comment]
- Fixed

---------------------

![Screenshot (79)](https://user-images.githubusercontent.com/45203177/73849956-da94f480-4850-11ea-9edf-31b82e7fe035.png)
