### ISSUE TITLE
Theme page search bar passing string value

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2255]
# Bug report

### Title

Theme page search bar passing a string value

### Issue Description
pass any string containing spaces in the search bar, in which spaces count as a string values

### Preconditions

    1. framework Version- master
    2. Theme- Velocity

### Steps to reproduce

    1. step1- search a product by passing two keys in search bar

### Expected result

spaces should not replace by + sign

### Actual result

>  
![Screenshot (15)](https://user-images.githubusercontent.com/43210406/73748478-8d951d80-477f-11ea-813f-e123aa54a382.png)

**Comment by jyoti-webkul** [comment]
- Fixed

--------------------------

![Screenshot from 2020-02-05 19-18-47](https://user-images.githubusercontent.com/45203177/73847484-61939e00-484c-11ea-9d7f-3c1c049594be.png)
