### ISSUE TITLE
close previous popup if clicks on another item

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2256]
# Bug report

### Title
close previous popup if clicks on another 

### Issue Description
close previous popup if clicks on another 

### Preconditions

    1. framework Version- master
    2. Theme- Velocity

### Steps to reproduce

    1. step1- click on the cart icon
    2. step2- now click on the user profile icon

### Actual result

![Screenshot (16)](https://user-images.githubusercontent.com/43210406/73748863-4eb39780-4780-11ea-81d3-fc0d0e793810.png)

**Comment by jyoti-webkul** [comment]
- Not fixed

-----------------------
![Screenshot from 2020-02-05 20-10-15](https://user-images.githubusercontent.com/45203177/73851667-e33afa00-4853-11ea-8263-a6cf315ebf4c.png)

**Comment by jyoti-webkul** [comment]
- Fixed

-----------------------------
