### ISSUE TITLE
User profile drop down option should be highlighted on mouse hover

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2257]
# Bug report

### Title
User profile drop-down option should be highlighted on mouse hover

### Issue Description
User profile drop-down option should be highlighted on mouse hover

### Preconditions

    1. framework Version- master
    2. Theme- Velocity

### Steps to reproduce

    1. step1- click on user profile icon and hover over any option

### Expected result

all drop-down options should be highlighted

### Actual result
 
![Screenshot (17)](https://user-images.githubusercontent.com/43210406/73749562-a56da100-4781-11ea-8bd8-38009bc9f1ef.png)

**Comment by jyoti-webkul** [comment]
- Fixed

---------------------

![Screenshot from 2020-02-05 19-12-49](https://user-images.githubusercontent.com/45203177/73847048-876c7300-484b-11ea-92a3-eef7a391d93a.png)
