### ISSUE TITLE
Not getting category image on category page in velocity theme.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2259]
# Bug report

### Title
Not getting category image on category page in velocity theme.
### Issue Description
Not getting category image on category page in velocity theme.

### Preconditions
    1. framework Version.- master

### Steps to reproduce

    1. step1- Add a category image.
    2. step2- Go to that category on frontend.

### Expected result
Category image should be visible on storefront.
### Actual result
Category image is not visible on category page.

![Screenshot (61)](https://user-images.githubusercontent.com/45203177/73751084-59702b80-4784-11ea-86af-a53f2345d725.png)

![Screenshot from 2020-02-04 19-27-21](https://user-images.githubusercontent.com/45203177/73751107-655bed80-4784-11ea-8f7b-c5b5c20f6282.png)

**Comment by jyoti-webkul** [comment]
Not fixed

------------------------------

**Comment by jyoti-webkul** [comment]
- Fixed

--------------------

![Screenshot from 2020-02-06 13-09-12](https://user-images.githubusercontent.com/45203177/73915691-e4b30380-48e1-11ea-8082-66e4655c9951.png)

**Comment by nizartcht** [comment]
>     * Fixed
> 
> 
> ![Screenshot from 2020-02-06 13-09-12](https://user-images.githubusercontent.com/45203177/73915691-e4b30380-48e1-11ea-8082-66e4655c9951.png)

same issues please how did you fix that

**Comment by vaishaliwebkul** [comment]
Hi @nizartcht 
Run these commands below from the root

- cd  public

- unlink storage

- cd ..

- php artisan storage:link

**Comment by nizartcht** [comment]
Fixed
just change APP_URL=https://127.0.0.1:8000
 to APP_URL=http://127.0.0.1:8000
