### ISSUE TITLE
Issue with multiple images of same product

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2262]
# Bug report

### Title
An issue with multiple images of the same product

### Issue Description

An issue with multiple images of the same product

### Preconditions

    1. framework Version- master
    2. theme- velocity

### Steps to reproduce

    1. step1- add more than 4 images of a single product
    2. step2- go to the product page 

### Expected result
next and the previous button be available if a product has multiple images

### Actual result

![Screenshot (18)](https://user-images.githubusercontent.com/43210406/73754655-b66ee000-478a-11ea-84ca-74cc440b4731.png)

**Comment by jyoti-webkul** [comment]
- Fixed

------------------

![Screenshot from 2020-02-06 13-39-24](https://user-images.githubusercontent.com/45203177/73917782-1cbc4580-48e6-11ea-9762-fabf24ee6c7f.png)
