### ISSUE TITLE
Fix issue at review page

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2263]
# Bug report

### Title
In the review page, duplicate review show for each single review comment

### Issue Description
In the review page, duplicate review show for each single review comment

### Preconditions

    1. framework Version- master
    2. Theme- Velocity

### Steps to reproduce

    1. step1- open a product page
    2. step2- write a review & then check the review page again
 

### Actual result

![Screenshot (19)](https://user-images.githubusercontent.com/43210406/73755882-ba9bfd00-478c-11ea-89d6-485d045fb0c9.png)

![Screenshot (20)](https://user-images.githubusercontent.com/43210406/73756129-1a92a380-478d-11ea-928a-a2cdaa40119a.png)

**Comment by jyoti-webkul** [comment]
- Fixed

------------------------

![Screenshot (72)](https://user-images.githubusercontent.com/45203177/73845513-d5cc4280-4848-11ea-9f3d-9439b36d8c4d.png)
