### ISSUE TITLE
Getting internal server error when place an order

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2264]
# Bug report

### Title
Getting internal server error when placing an order

### Issue Description
Getting internal server error when placing an order

### Preconditions

    1. framework Version- master
    2. Theme- Velocity

### Steps to reproduce

    1. step1- add to cart & place an order by following all the steps
   
### Actual result

![Screenshot from 2020-02-04 20-45-28](https://user-images.githubusercontent.com/43210406/73757494-4f075f00-478f-11ea-83f7-0179bc32cf4e.png)

**Comment by vaishaliwebkul** [comment]
Fixed

**Comment by christiandesantis** [comment]
I'm having this problem, how can I fix it? (I'm using the latest bagisto version with laravel aliexpress dropship)

**Comment by christiandesantis** [comment]
> Fixed

How id you fix it? I'm having this problem (I'm using the latest bagisto version)
