### ISSUE TITLE
Migrate issues with Velocity

### ISSUE THREAD

**Issue by adavie1** [bagisto/bagisto#2265]
# Bug report

### Latest build has errors on migrate.
When running `php artisan migrate` I get the following error:
![image](https://user-images.githubusercontent.com/3030402/73796189-8d306d00-47e7-11ea-8f97-a4c676cf8a7a.png)

I've checked, the file is there, in the directory.

**Comment by shubhwebkul** [comment]
Hey @adavie1 ,
Thanks for mentioning the issue. you just need to run composer dump-autoload before executing migration.

**Comment by adavie1** [comment]
Yeah, figured that out, by doing `composer install`. Thanks for the reply though.
