### ISSUE TITLE
Admin: Invoice and Shipping Order creation very slow

### ISSUE THREAD

**Issue by adavie1** [bagisto/bagisto#2266]
# Bug report

### Title
From the admin side- creating an invoice takes about 1.5 secs.
The shipping side takes at least 3 secs.

### Issue Description
Given this is all on my development machine, which has decent specs, this doesn't bode well for production.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Current master branch as at 1 Feb 2020

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Create and order as customer
    2. Go to admin
3.  Create invoice
4. Create shipping order

### Possible Solution
The system doesn't create indexes other than primary keys. It uses created_at for searches, and has a few joins along the way. Indexing will definitely help.

**Comment by jitendra-webkul** [comment]
@adavie1 

During invoice and shipment creation, the system sends emails to the customers and sending emails is slow.

You can cross-check by commenting on the following lines:

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Admin/src/Listeners/Order.php#L83

**Comment by jitendra-webkul** [comment]
I am closing this issue, for now, feel free to reopen this issue

**Comment by Mohammedalasaad** [comment]
Hi @jitendra-webkul 
I have same problem and its very slow when we submit the order but its fast when we disable "Send Order Confirmation E-mail",, is there a way to keep it fast and enable send order email?

How is it working on demo site? its fast and email is enabled.
