### ISSUE TITLE
Possible data duplication and redudancy & interantionalizion issues

### ISSUE THREAD

**Issue by adavie1** [bagisto/bagisto#2267]
# Bug report

### Title
With the recent changes to the customer_addresses table, putting first_name and last_name there is not a good idea. Which is valid? The customer record? Or the address record?

If a customer changes their name, gets married for example. They have to change all these different places in the system. Very error prone.

The company name is very good.

### Internationalisation Issues
Plus have first_name and last_name only works for Western names.
I live in an Asia, Chinese names start with Family name and personal name
Malaysian Indian names start with personal name a/l fathers name
Malay names follow Indian pattern: personal name bin/binte father's name

### Possible solution
Just have `full_name` and `greeting` (for emails,  logins) fields. Keep them in the customer table only.

For invoices and shipping, it's correct to store the name data there, because it's the legal record of the the transaction at the time.

**Comment by jitendra-webkul** [comment]
It's not possible for now but can be done with customization
