### ISSUE TITLE
Not able to proceed for checkout after checkout/onepage in case of downloadable product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2274]
# Bug report

### Title
Not able to proceed for checkout in case of downloadable product.
### Issue Description
Not able to proceed for checkout after checkout/onepage in case of downloadable product.

### Preconditions
    1. framework Version.- master

### Steps to reproduce
    1. step1- Add a downloadable product in cart and place order for it.
    2. step2- Enter your billing information.

### Expected result
After billing information provide a button to proceed further.
### Actual result
After billing information there is no option for checkout.
![Screenshot from 2020-02-05 12-06-46](https://user-images.githubusercontent.com/45203177/73817395-d0530600-4810-11ea-9a1e-2ae20e2e82a4.png)

**Comment by vaishaliwebkul** [comment]
Fixed
