### ISSUE TITLE
Not able to place order for virtual product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2275]
# Bug report

### Title
Not able to place order for virtual product.
### Issue Description
Not able to place order for virtual product.

### Preconditions

    1. framework Version.- master

### Steps to reproduce
    1. step1- Place an order for virtual product.
    2. step2- From checkout/onepage no option to proceed further.

### Expected result
Customer should be able to place order for virtual product.

### Actual result
Not able to place order for virtual product.

![Screenshot from 2020-02-05 13-10-42](https://user-images.githubusercontent.com/45203177/73821144-4a878880-4819-11ea-89f8-9a35b434600e.png)

**Comment by vaishaliwebkul** [comment]
Fixed
