### ISSUE TITLE
Add a section in category to view all product assigned to that category.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2278]
# Bug report

### Title
Add a section in category to view all product assigned to that category.
### Issue Description
Add a section in category to view all product assigned to that category.
### Preconditions

    1. framework Version.- master

### Steps to reproduce

    1. step1- Create a product and select category for that product.
    2. step2- Go to Category section and edit the category to view the assigned product.

### Expected result
Product under that category should be visible on edit the category.
### Actual result
No option to view the assigned product from category.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this **enhancement is done**. so I am **closing** this enhancement.
And I have attached a screenshot [Here](https://prnt.sc/OUoGzI4eEi1g). for future reference.
