### ISSUE TITLE
bagisto icon should be clickable and by clicking on it, it should redirect to dashboard.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#228]
Framework Version : 0.1.1
![image](https://user-images.githubusercontent.com/45203177/49148768-47982a80-f32e-11e8-99f6-60c8ba32da0c.png)

**Comment by rahulshukla-webkul** [comment]
Changed Icon to clickable and now it is redirecting to dashboard.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
