### ISSUE TITLE
Not getting any validation error message if current date of birth is selected in customer profile.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2282]
# Bug report

### Title
Not getting any validation error message if current date of birth is selected in customer profile.
### Issue Description
Not getting any validation error message if current date of birth is selected in customer profile.

### Preconditions
    1. framework Version.- master

### Steps to reproduce
    1. step1- Go to customer profile
    2. step2- Update the date of birth by selecting current date.

### Expected result
It should throw validation error message as in default theme

### Actual result
Not getting any validation error message if current date of birth is selected in customer profile.

**Comment by vaishaliwebkul** [comment]
Not fixed.

**Comment by jyoti-webkul** [comment]
- Fixed  
-----------------------

![Screenshot from 2020-02-07 10-50-34](https://user-images.githubusercontent.com/45203177/74003188-c0b1f980-4997-11ea-9a16-7ccd31f5612c.png)
