### ISSUE TITLE
Bitcoin Payment Method

### ISSUE THREAD

**Issue by ckmirafss** [bagisto/bagisto#2283]
Hello All,

Does anyone tried to integrate bitcoin as payment on Bagisto? Im just wondering if it is possible. Should I install Bitcoin core on my server side also? Or just integrate some of the packages available for Laravel.

**Comment by rahulshukla-webkul** [comment]
Hi @ckmirafss 

You can follow this devdocs for integrating payment method in bagisto -https://devdocs.bagisto.com/create_payment_method.html

**Comment by ckmirafss** [comment]
Hello, Would you recommend best package for this?

**Comment by jitendra-webkul** [comment]
You can create your own package, please follow the following document link:

https://devdocs.bagisto.com/create_payment_method.html

I am closing this issue for now. Feel free to reopen this issue if needed.
