### ISSUE TITLE
Existing groups in the attribute families are not translatable yet.

### ISSUE THREAD

**Issue by michael-arif** [bagisto/bagisto#2308]
# Bug report

### Title
Existing groups in the attribute families are not translatable yet.

### Issue Description
General, Meta Description, Price, Shipping, and their attributes are not translatable.

### Preconditions
    1. framework Version:0.2.2

**Comment by rahulshukla-webkul** [comment]
Hi @michael-arif 

This all will show at admin end only, so we don't need translation for this.

**Comment by michael-arif** [comment]
Hi @rahulshukla-webkul 

It would be nice if there is a way to translate it.
I can't speak for administrators in this country
but my administrator friends prefer General, Meta Description, Price, Shipping written in Japanese.
I guess it is necessary for them when they need to show the screen to higher level officers who cannot understand the words.

Thank you.

**Comment by EgyptianM** [comment]
> Hi @michael-arif
> 
> This all will show at admin end only, so we don't need translation for this.

I don't think that there is a single word in any script that can be used in different countries that doesn't need a translation.

Please provide a way to translate everything in the framework because we need this and it's necessary.

Thank you in advance

**Comment by ghermans** [comment]
@EgyptianM @michael-arif Sorry for the silence around this feature request, we will discuss this internally with the team and get back to you later.

**Comment by EgyptianM** [comment]
@ghermans Thank you very much

**Comment by lain1936** [comment]
Quick way, add lang files （ for consistent with the additional view's  title , add strtolower to name）
`<accordian :title="'{{ __('admin::app.catalog.products.' . strtolower($attributeGroup->name)) }}'"`


            'general'=>'General',
            'description'=>'Description',
            'meta description'=>'Meta Description',
            'price'=>'Price',
            'shipping'=>'Shipping',
            'videos'=>`Videos',

The attribute name is also not translatable.
`{{ $attribute->name?$attribute->name:$attribute->admin_name }}`
