### ISSUE TITLE
UI issue when customer redirect to reset password page through received email.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2319]
# Bug report

### Title
UI issue when customer redirect to reset password page through received email.

### Issue Description
UI issue when customer redirect to reset password page through received email.

### Preconditions

    1. framework Version.- master

### Steps to reproduce

    1. step1- Go to Forgot password link
    2. step2- Enter your email and click on send reset password link.
    3. step3- Go to email and click the received link.

### Expected result
Ui should be correct.
### Actual result
![Screenshot from 2020-02-06 13-30-44](https://user-images.githubusercontent.com/45203177/73917394-5476bd80-48e5-11ea-8611-8fed4258a03a.png)

**Comment by vaishaliwebkul** [comment]
Fixed
