### ISSUE TITLE
Add sorting functionality in column "Name" of Inventory Grid.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#232]
Framework Version: 0.1.1

![image](https://user-images.githubusercontent.com/45203177/49148845-8332f480-f32e-11e8-9ec2-1190b8fbea00.png)

**Comment by Jyoti-Singh1** [comment]
Fixed
Framework Version: 0.1.2
![screenshot 13](https://user-images.githubusercontent.com/45203177/49504336-74ed5700-f89f-11e8-9aee-b4cabdd37fb2.png)
