### ISSUE TITLE
Change the view of customer profile, when customer log in profile section open as form.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2322]
### Title
Change the view of customer profile, when customer log in profile section display as form.
### Issue Description
Change the view of customer profile, when customer log in profile section display as form.

### Preconditions
    1. framework Version.- master

### Steps to reproduce

    1. step1- Log in as a customer

### Expected result
Profile should display as in default bagisto.

### Actual result
![Screenshot from 2020-02-06 15-25-18](https://user-images.githubusercontent.com/45203177/73925989-e89c5100-48f4-11ea-9b11-a709621d588f.png)

**Comment by vaishaliwebkul** [comment]
Not Fixed.

**Comment by vaishaliwebkul** [comment]
Update the delete button alignment
![Screenshot (5)](https://user-images.githubusercontent.com/43210406/74235542-41088f80-4cf5-11ea-8cd9-0f7559ed1766.png)

**Comment by vaishaliwebkul** [comment]
Fixed
