### ISSUE TITLE
After clicking on New address at time of checkout, billing information form should be open.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2323]
# Bug report

### Title
After clicking on New address at time of checkout, billing information form should be open.

### Issue Description
After clicking on New address at time of checkout, billing information form should be open.

### Preconditions

    1. framework Version.- master

### Steps to reproduce

    1. step1- Add a product in cart, proceed for checkout.
    2. step2- Click on New Address button.

### Expected result
Billing Information form should get open when user click on New Address.

### Actual result
![Screenshot from 2020-02-06 15-38-05](https://user-images.githubusercontent.com/45203177/73927035-b12ea400-48f6-11ea-84e3-199291618e01.png)

**Comment by vaishaliwebkul** [comment]
Fixed
