### ISSUE TITLE
Left arrow should be out of the image area.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2325]
# Bug report

### Title
Left arrow should be out of the image area.

### Issue Description
Left arrow should be out of the image area.
### Preconditions

    1. framework Version.- master

### Steps to reproduce

    1. step1- Add multiple image for a product
    2. step2- Go upto last image and check the left arrow.

### Expected result
Left arrow should be out of the image area.

### Actual result
![Screenshot (84)](https://user-images.githubusercontent.com/45203177/73927695-d8d23c00-48f7-11ea-9e0b-b6329d3b64a3.png)

**Comment by vaishaliwebkul** [comment]
Not fixed.

**Comment by vaishaliwebkul** [comment]
1. Now next and previous button issue fixed
2. an icon will place on an image, this is ok in a real scenario
![Screenshot (26)](https://user-images.githubusercontent.com/43210406/74005088-cdd1e700-499d-11ea-9f3e-493012a57fee.png)
