### ISSUE TITLE
Only first three viewed product display in recently viewed section, when customer view 4th product it doesn't get updated.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2328]
# Bug report

### Title
Only first three viewed product display in recently viewed section, when customer view 4th product it doesn't get updated.
### Issue Description
Only first three viewed product display in recently viewed section, when customer view 4th product it doesn't get updated.
### Preconditions
    1. framework Version- master

### Steps to reproduce
    1. step1- View three product one by one and check the recently viewed section.
    2. step2- Now view the fourth product and check the  recently viewed section.

### Expected result
Recently Viewed product section should get updated with the latest viewed product.

### Actual result

Only first three viewed product display in recently viewed section, when customer view 4th product it doesn't get updated.

**Comment by vaishaliwebkul** [comment]
Not fixed

**Comment by jyoti-webkul** [comment]
- Fixed
