### ISSUE TITLE
Getting exception on frontend after updating meta data.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2329]
# Bug report

### Title
Getting exception on frontend after updating meta data.
### Issue Description
Getting exception on frontend after updating meta data.
### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Go to velocity grid and in meta data section add images and update it.
    2. step2- Go to frontend.

### Expected result
Home page should display.

### Actual result

![Screenshot from 2020-02-06 16-26-30](https://user-images.githubusercontent.com/45203177/73931291-0c17c980-48fe-11ea-86d8-cb64419f4fe4.png)

**Comment by vaishaliwebkul** [comment]
Fixed

**Comment by jestainternetsolutions** [comment]
This Bug occurs again on version 1.1.0

**Comment by vaishaliwebkul** [comment]
Hi @jestainternetsolutions 
Could you please mention reproduce steps. 
In which section of advertisement images(one,two,,three) you are getting this issue.
Also mention your php version.

**Comment by jestainternetsolutions** [comment]
@vaishaliwebkul 

Running on PHP 7.2.19
The problem occurs on all sections

Steps to reproduce
1. Navigate to Velocity => Meta data => images
2. Add images to one of the sections
3. Save the changes
4. Open front-end (then the changes are vissible)
5. Navigate to Velocity => Meta data => images (now there are no images in none of the sections)
6. Add images to another section
7. Save the changes
On this point all previous settiings are overwritten

https://www.loom.com/share/d321953cb37c4d5ca466415ea00aa4c7

**Comment by jestainternetsolutions** [comment]
@vaishaliwebkul can you give us an update on this issue?

**Comment by vaishaliwebkul** [comment]
@jestainternetsolutions
As I have checked exception is not occurs right now, instead of the actual issue is advertisement images are not saved in the asset.
This issue will fix soon OR by tomorrow.
Thanks.

**Comment by vaishaliwebkul** [comment]
@jestainternetsolutions 
Now Issue has been fixed in master.
Take pull from the master branch and check again.
