### ISSUE TITLE
Selected content type is not showing in Content Pages List

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2339]
# Bug report

### Title
Selected content type is not showing in Content Pages List
### Issue Description
Selected content type is not showing in Content Pages List

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Create a header content.
    2. step2- Go to header content grid and check the content type column.

### Expected result
Selected content should display.
### Actual result

![Screenshot (86)](https://user-images.githubusercontent.com/45203177/73936656-52265a80-4909-11ea-9229-5f51f0b84d8c.png)

**Comment by vaishaliwebkul** [comment]
Fixed
