### ISSUE TITLE
Correct the success message on deleting content.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2340]
# Bug report

### Title
Correct the success message on deleting content.

### Issue Description
Correct the success message on deleting content.
### Preconditions

    1. framework Version-master

### Steps to reproduce

    1. step1- Select all header content and delete it.

### Expected result
Success message should be correct.

### Actual result

![Screenshot from 2020-02-06 17-52-31](https://user-images.githubusercontent.com/45203177/73936958-f0b2bb80-4909-11ea-9634-a879f92b84c6.png)

**Comment by vaishaliwebkul** [comment]
fixed
