### ISSUE TITLE
possible integrate this payment

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2354]
https://github.com/michaeldouglas/laravel-pagseguro

Thanks!

**Comment by marcelowu** [comment]
payment for brazil.

https://github.com/LucienCorreia/PicPay
https://ecommerce.picpay.com/doc/

**Comment by marcelowu** [comment]
payment for china - alipay and wechat pay
https://github.com/yansongda/laravel-pay

**Comment by adavie1** [comment]
[OmniPay](https://omnipay.thephpleague.com/gateways/community/) is a great payment gateway API tool.

**Comment by ghermans** [comment]
In addition to the fact that this discussion would better placed on the forum instead here, you can add a payment method yourself by creating a customized package

https://devdocs.bagisto.com/create_package.html
https://devdocs.bagisto.com/create_payment_method.html

**Comment by marcelowu** [comment]
https://github.com/michaeldouglas/laravel-pagseguro
