### ISSUE TITLE
UI issue when update product policy 

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2355]
# Bug report

### Title
UI issue when update product policy 

### Issue Description
UI issue when update product policy 

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- go to the velocity metadata 
    2. step2- update the product policy guidelines by adding one more policy

### Expected result

All guideline should be shown

### Actual result
  
![Screenshot (24)](https://user-images.githubusercontent.com/43210406/74003227-dfb08b80-4997-11ea-8ee4-3c5d76083262.png)

![Screenshot (25)](https://user-images.githubusercontent.com/43210406/74003226-dde6c800-4997-11ea-9052-5ee62b84bfe4.png)

**Comment by shubhwebkul** [comment]
You need to write proper html with required css in the source code inside the editor.
checkout:- https://prnt.sc/qyrl7e
