### ISSUE TITLE
Add translation for Recently viewed product ar and pt_BR.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2358]
# Bug report

### Title
Add translation for Recently viewed product ar and pt_BR.
### Issue Description
Add translation for Recently viewed product ar and pt_BR.
### Preconditions

    1. framework Version- master

### Expected result
Translation should be added for static words
### Actual result

![Screenshot from 2020-02-07 12-07-37](https://user-images.githubusercontent.com/45203177/74007028-569f5180-49a3-11ea-98bd-cbfdfbf96124.png)

**Comment by vaishaliwebkul** [comment]
Translation added in both locale

![Screenshot (15)](https://user-images.githubusercontent.com/43210406/74329667-3eba3a00-4db6-11ea-9bd3-ccefc0b73ed3.png)
