### ISSUE TITLE
Address of customer not getting added in Customer->Address section when customer save it at time of checkout.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2364]
# Bug report

### Title
Address of customer not getting added in Customer->Address section when customer save it at time of checkout.

### Issue Description
Address of customer not getting added in Customer->Address section when customer save it at time of checkout.

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Add a product in cart
    2. step2- Enter your address and also select the option save as address and proceed to checkout.
    3. step3- After successful order go to customer address section.

### Expected result
Added address should display in address section of customer.

### Actual result

Address of customer not getting added in Customer->Address section when customer save it at time of checkout.

**Comment by vaishaliwebkul** [comment]
Fixed
