### ISSUE TITLE
Provide a mass selection option to approve a review.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#238]
Framework Version: 0.1.1
![screenshot 28](https://user-images.githubusercontent.com/45203177/49154336-23444a00-f33e-11e8-84a7-3df80b11e267.png)

**Comment by prashant-webkul** [comment]
Mass selection feature were removed due to some time limits and some clarity from user's perspective is required how they want to use them.
This is surely the best way to use them and this will taken into consideration directly.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
![screenshot 39](https://user-images.githubusercontent.com/45203177/50341458-e4707100-0544-11e9-81dd-14cec5508dfe.png)
