### ISSUE TITLE
If customer use shipping address other than billing address then also its showing the billing address in shipping address section.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2382]
# Bug report

### Title
If customer use shipping address other than billing address then also its showing the billing address in shipping address section.

### Issue Description
If customer use shipping address other than billing address then also its showing the billing address in shipping address section.

### Preconditions
    1. framework Version- 1.0.0

### Steps to reproduce

    1. step1- Checkout with a product
    2. step2- use different shipping address and billing address.
    3. step3- check the shipping address on checkout page and in order after placing an order 

### Expected result
Shipping address should be correct.
### Actual result
Getting billing address in shipping address also

![Screenshot from 2020-02-07 18-51-37](https://user-images.githubusercontent.com/45203177/74033090-6d619a80-49db-11ea-8421-db81b3f361ac.png)

![Screenshot from 2020-02-07 18-51-32](https://user-images.githubusercontent.com/45203177/74033101-73577b80-49db-11ea-9389-d7aef331641c.png)

![Screenshot from 2020-02-07 18-55-54](https://user-images.githubusercontent.com/45203177/74033125-7e121080-49db-11ea-9238-a78e2a47b8ec.png)

**Comment by vaishaliwebkul** [comment]
Fixed
