### ISSUE TITLE
Provide space between amount and (-).hyphen

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2389]
# Bug report

### Title
Provide space between amount and (-)hyphen.

### Issue Description
Provide space between amount and (-)hyphen.
### Preconditions

    1. framework Version- 1.0.0

### Steps to reproduce

    1. step1- Go to Invoice section of customer account.

### Expected result
Space should be provided.
### Actual result
![Screenshot (94)](https://user-images.githubusercontent.com/45203177/74081153-d398fc80-4a71-11ea-8160-5f3921815fe5.png)

**Comment by vaishaliwebkul** [comment]
Fixed
