### ISSUE TITLE
Getting exception on adding grouped product to cart.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2393]
# Bug report

### Title
Getting exception on adding grouped product to cart.

### Issue Description
Getting exception on adding grouped product to cart.
### Preconditions

    1. framework Version- 1.0.0

### Steps to reproduce

    1. step1- Add group product in cart.

### Expected result
Product should get added in cart.

### Actual result

![Screenshot from 2020-02-08 13-18-08](https://user-images.githubusercontent.com/45203177/74081496-a2223000-4a75-11ea-971d-1b947ea8c867.png)

**Comment by vaishaliwebkul** [comment]
Fixed
