### ISSUE TITLE
Company Name field is not available in Billing Address form in velocity theme.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2397]
# Bug report

### Title
Company field is not available in Billing Address form in velocity theme.

### Issue Description
Company field is not available in Billing Address form in velocity theme.

### Preconditions

    1. framework Version- 1.0.0

### Steps to reproduce

    1. step1- Add a product in cart as a guest user
    2. step2- Check the Billing Address form.

### Expected result
Company Name field should be available.
### Actual result

![Screenshot from 2020-02-08 13-53-49](https://user-images.githubusercontent.com/45203177/74081970-dc420080-4a7a-11ea-8ac9-79f1430f5c60.png)

![Screenshot from 2020-02-08 13-54-38](https://user-images.githubusercontent.com/45203177/74081976-ef54d080-4a7a-11ea-9aef-73eee7298bb9.png)

**Comment by vaishaliwebkul** [comment]
fixed
