### ISSUE TITLE
Layout issue in bundle product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2399]
# Bug report

### Title
Layout issue in bundle product.
### Issue Description
Layout issue in bundle product.

### Preconditions

    1. framework Version-1.0.0

### Steps to reproduce

    1. step1- Create a bundle product with radio button.
    2. step2- Do not make that option as required.

### Expected result
Layout should be correct.
### Actual result
![Screenshot (96)](https://user-images.githubusercontent.com/45203177/74082121-d0efd480-4a7c-11ea-8cee-4eaf63408032.png)

**Comment by vaishaliwebkul** [comment]
fix layout as all options are not equal
![Screenshot (6)](https://user-images.githubusercontent.com/43210406/74237558-dad23b80-4cf9-11ea-8360-fd0aa0e1d7f5.png)

**Comment by vaishaliwebkul** [comment]
Fixed
