### ISSUE TITLE
Whole product price should be in bold in bundle product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2400]
# Bug report

### Title
Whole product price should be in bold in bundle product.

### Issue Description
Whole product p[rice should be in bold in bundle product.

### Preconditions

    1. framework Version- 1.0.0

### Steps to reproduce

    1. step1- Create a bundle product.
    2. step2- Check the price of that product on front-end.

### Expected result
Whole product price should be in bold in bundle product.
### Actual result

![Screenshot (97)](https://user-images.githubusercontent.com/45203177/74082726-df40ef00-4a82-11ea-9b09-8cade82fbb4f.png)

**Comment by vaishaliwebkul** [comment]
Fixed
