### ISSUE TITLE
error button update cart

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2410]
![Screenshot from 2020-02-09 23-27-58](https://user-images.githubusercontent.com/30912144/74116825-0509e900-4b94-11ea-8d8e-5853a9d76d1b.png)
![Screenshot from 2020-02-09 23-27-11](https://user-images.githubusercontent.com/30912144/74116842-0f2be780-4b94-11ea-8ea3-c0bf8d408cad.png)

Thanks!

**Comment by vaishaliwebkul** [comment]
Issue exists when responsive layout change

**Comment by vivek-webkul** [comment]
@vaishaliwebkul try after clearing cache, It's working fine.

**Comment by vaishaliwebkul** [comment]
@vivek-webkul 
now it's working

**Comment by vaishaliwebkul** [comment]
@marcelowu 
The issue has been resolved.
feel free to reopen this issue if still not resolved.

**Comment by marcelowu** [comment]
bagisto v 0.2.2 not resolved.

**Comment by vaishaliwebkul** [comment]
@marcelowu 
this issue is resolved in the latest v1.1.2, please check
![Screenshot (17)](https://user-images.githubusercontent.com/43210406/84126081-15a37080-aa5b-11ea-98ae-db8d55bbab5a.png)
