### ISSUE TITLE
 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2411]
![Screenshot from 2020-02-09 23-33-29](https://user-images.githubusercontent.com/30912144/74117091-2cad8100-4b95-11ea-8899-2ecb6a0386c8.png)

Thanks!

**Comment by jyoti-webkul** [comment]
Hi
@marcelowu 
Please write step to reproduce this issue, also mention your bagisto version and php version.

**Comment by marcelowu** [comment]
ubuntu php7.2 bagisto 1.0 beta,

**Comment by jitendra-webkul** [comment]
Please write steps to reproduce this issue.
