### ISSUE TITLE
The content of the Invoice's PDF contains garbled characters.

### ISSUE THREAD

**Issue by michael-arif** [bagisto/bagisto#2412]
# Bug report

### Title
The content of the Invoice's PDF contains garbled characters.

### Issue Description
If app.php's locale is set to ja (Japanese), and all language files are provided, 
and then try to print invoice. The content of the PDF are all garbled.
Can I set a flag in webkul/admin/src/resources/views/sales/invoices/pdf.blade.php to support UTF8?
I have tried to add <meta http-equiv="Cache-control" content="no-cache" charset="UTF-8"> or
font-family: Arial but the result is just the same.

### Preconditions
    1. framework Version:0.2.2

**Comment by jitendra-webkul** [comment]
@michael-arif ,

Could you please create a PR with a Japanese translation so that we can check the issue.

**Comment by jitendra-webkul** [comment]
No reply since 11 Feb, I am closing this issue. I hope your issue got resolved
