### ISSUE TITLE
Company name entered by customer should display in checkout page, in order grid and in customer address list.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2415]
# Bug report

### Title
Company name entered by customer should display in checkout page, in order grid and in customer address list.

### Issue Description
Company name entered by customer should display in checkout page, in order grid and in customer address list.

### Preconditions
    1. framework Version- master

### Steps to reproduce

    1. step1- Add a product in cart and proceed to checkout.
    2. step2- Enter company name also and place an order.
    3. step3- Check the billing information.

### Expected result
Company name should display.

### Actual result
![Screenshot (98)](https://user-images.githubusercontent.com/45203177/74132986-99646200-4c0d-11ea-800f-5638727034bc.png)
![Screenshot from 2020-02-10 13-59-54](https://user-images.githubusercontent.com/45203177/74133037-b26d1300-4c0d-11ea-8ff4-76cdab985610.png)

**Comment by vaishaliwebkul** [comment]
fixed
