### ISSUE TITLE
Add to Cart not working

### ISSUE THREAD

**Issue by adavie1** [bagisto/bagisto#2418]
# Bug report

### Title
In the current master release- add to cart not working. Not sure if this a duplicate of #2410

1. Go to main shop page
2. Click Add to Cart on a product
3. Check Cart - empty!

Alternate flow-
1. Login in a user
2. Click Add to Cart on a product
3. Check cart- empty

### Expected result
The product selected should be added to the cart.
![image](https://user-images.githubusercontent.com/3030402/74149350-8324c900-4c42-11ea-9bfc-f5d667b17a73.png)

After clicking add...

![image](https://user-images.githubusercontent.com/3030402/74149266-553f8480-4c42-11ea-85ab-3574c62a7d6a.png)

### Actual result

Product not added to cart.

**Comment by jitendra-webkul** [comment]
Please write step to reproduce this issue.

**Comment by adavie1** [comment]
@jitendra-webkul already updated my comments above.

**Comment by adavie1** [comment]
Having done a complete deleted and rebuild using the current master,  this is issue has disappeared. Must have been stale code somewhere.
