### ISSUE TITLE
currency BRL default erro

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2434]
![Capturar](https://user-images.githubusercontent.com/30912144/74278604-3dc2d300-4cf8-11ea-90ac-974a8df6da91.PNG)
![Capturar1](https://user-images.githubusercontent.com/30912144/74278610-40bdc380-4cf8-11ea-8138-305f911d2bfa.PNG)
![Capturar2](https://user-images.githubusercontent.com/30912144/74278612-40bdc380-4cf8-11ea-83b5-bc25a2946ba3.PNG)
![Capturar3](https://user-images.githubusercontent.com/30912144/74278632-4adfc200-4cf8-11ea-8f35-e0597a4d5568.PNG)

![Capturar4](https://user-images.githubusercontent.com/30912144/74278881-aa3dd200-4cf8-11ea-8161-056c2064064f.PNG)
![Capturar5](https://user-images.githubusercontent.com/30912144/74278884-aad66880-4cf8-11ea-9f14-2e91a74d80b4.PNG)

Thanks!

**Comment by vaishaliwebkul** [comment]
@marcelowu 
  Always check the default currency in an incognito window to reflect changes in currency and locale.

This is not an issue

![Screenshot (9)](https://user-images.githubusercontent.com/43210406/74305075-dc951100-4d84-11ea-9724-68dfcc62879d.png)


![Screenshot from 2020-02-12 10-43-21](https://user-images.githubusercontent.com/43210406/74304967-9344c180-4d84-11ea-8c58-f07bd06fbd31.png)

**Comment by marcelowu** [comment]
start as default BRL?
