### ISSUE TITLE
Login form validation message is not translatable yet.

### ISSUE THREAD

**Issue by michael-arif** [bagisto/bagisto#2437]
# Bug report

### Title
Login form validation message is not translatable yet.

### Issue Description
On the Login screen, if email and/or password are left blank and user press the Login button,
validation messages will be shown under the related textboxes in red color.
For email, 'The Email value is not valid.' For password, 'The Password value is not valid.'
If I set Japanese as the default locale, It will show, 'The "メールアドレス" value is not valid.'
I have been searching for the phrase only to find it in admin.js or shop.js.
Is there a way to translate these messages?

### Preconditions
    1. framework Version: 0.2.2

### Steps to reproduce
    1. Change app.php's locale to 'ja'.
    2. Go to Customer Login screen
    3. Press Login button (leave the email address and password blank)

![Login](https://user-images.githubusercontent.com/60635370/74306615-61dced80-4da6-11ea-9c22-7afbbc7f175a.PNG)

### Expected result
The messages that appear under the email addres and password textboxes should be shown in the Japanese language.

**Comment by jitendra-webkul** [comment]
@michael-arif 

You need to write the translation for validation too. Please take a look at the following file:

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Shop/src/Resources/assets/js/lang

**Comment by michael-arif** [comment]
@jitendra-webkul 

I already added Japanese translation to the /Webkul/Shop/src/Resources/assets/js/lang/locales.js.
It looks like the following:
```javascript
export const messages = {
    ja: {
        required : (field) => 'フィールド ' + field + ' は必須です。',
        alpha : (field) => field + ' は文字のみを含める必要があります。',
        alpha_num : (field) => field + ' は文字と数字のみを含めることができます。',
        min : (field) => 'フィールド ' + field + ' 少なくとも{length}文字を含める必要があります。',
        ...
    },
    ar: {
        required : (field) => 'حقل' + field + ' مطلوب',
        alpha : (field) => field + ' يجب ان يحتوي على حروف فقط',
        alpha_num : (field) => field + ' قد يحتوي فقط على حروف وارقام',
        min : (field) => 'الحقل ' + field + ' يجب ان يحتوي على {length} حروف على الأقل',
        ...
    }
}
```

And then, I also modify /Webkul/Shop/src/Resources/assets/js/app.js as follows:
```javascript
Vue.use(VeeValidate, {
    dictionary: {
        ja: { messages: locales.messages.ja },
        ar: { messages: locales.messages.ar }
    }
});
```

Maybe I miss something. Please let me know. Thank you.

**Comment by jitendra-webkul** [comment]
I think you didn't compile assets.

Go to bagisto/packages/Webkul/Shop directory and install npm packages with "npm install" command and then run "npm run watch" command.

**Comment by michael-arif** [comment]
I did as you suggested:
1. npm install (in the /bagisto/Webkul/Shop directory
    This creates node_modules with lots of subfolders and files 129MB.
2. npm run watch
    This failed.

Then, I found out that /bagisto/packages/Webkul/publishable/assets/js/admin.js contains the above-mentioned non-translatable message (value is not valid.)
If I translated it, the message will be shown correctly in japanese.

**Comment by rahulshukla-webkul** [comment]
Hi @michael-arif 

Just take a new pull of bagisto, install npm in shop packages and do the following changes in app.js file of Shop package.

Import validation language file of Japanese language.

`import ja from 'vee-validate/dist/locale/ja';`

and add it, like - 

`Vue.use(VeeValidate, {
    dictionary: {
        ar: ar,
        de: de,
        **ja: ja**
    },
    events: 'input|change|blur',
});`

and it will start working - https://prnt.sc/riewgc

Thanks

**Comment by jitendra-webkul** [comment]
I hope above reply solved your issue. I am closing this issue for now. Feel free to reopen this issue if needed.
