### ISSUE TITLE
Velocity theme is not loading on fresh instance

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2453]
# Bug report

### Title
Velocity theme & its icon is not loading on a fresh instance

### Issue Description

On fresh instance when select velocity theme, in front it's still set to default.

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Install a new master instance
    2. step2- Velocity theme selected from a channel
    3. step3- Check the theme in a front end

### Actual result

![Screenshot (4)](https://user-images.githubusercontent.com/43210406/74410048-27cf2280-4e5e-11ea-96da-185cee929d04.png)

![Screenshot (5)](https://user-images.githubusercontent.com/43210406/74410050-29004f80-4e5e-11ea-990e-633580717775.png)

**Comment by shubhwebkul** [comment]
Hello @vaishaliwebkul 
you need to run `php artisan vendor:publish` command once.

**Comment by Mohamadkabalan** [comment]
I have the same issue  , i have appied the above command , and still velocity the is not loading
