### ISSUE TITLE
Edit product: don't show added categories

### ISSUE THREAD

**Issue by autn** [bagisto/bagisto#2464]
# Bug report

### Title
**When editing a product, all added categories are empty**

### Issue Description
**Create a product, add to categories, then edit that product, the added categories are empty (the checkboxes are unchecked)**

### Preconditions

    1. Bagisto v0.2.2.

### Steps to reproduce

    1. Create a product
    2. Add product to category (categories)
    3. Save product
    4. Edit above product
    5. The checkboxes in Categories section are empty

### Expected result
**Should to show added categories.**

![Screenshot from 2020-02-14 15-37-34](https://user-images.githubusercontent.com/10827140/74515019-4f96b700-4f40-11ea-9863-e21eb44d7cc7.png)

**Comment by khanhgg** [comment]
@autn . I have same issues

**Comment by rahulshukla-webkul** [comment]
Hi @autn 

This issue has been fixed in master.

**Comment by autn** [comment]
Thanks @rahulshukla-webkul, was it released? Or when it will be released?

**Comment by rahulshukla-webkul** [comment]
Hi @autn 

It is already released.

**Comment by autn** [comment]
@rahulshukla-webkul what is the version? I'm using v0.2.2 and can not find newer versions.

**Comment by vivek-webkul** [comment]
Hi @autn 

You can use v1.0.0-BETA1 version in this version this issue has been fixed.
https://github.com/bagisto/bagisto/tree/v1.0.0-BETA1

**Comment by autn** [comment]
@vivek-webkul thanks
