### ISSUE TITLE
Displaying wrong amount for bundle product in cart.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2469]
# Bug report

### Title
Displaying wrong amount for bundle product in cart.
### Issue Description
Displaying wrong amount for bundle product in cart.

### Preconditions

    1. framework Version- master

### Steps to reproduce
    1. step1- Create a bundle product
    2. step2- selected any option from bundle that have default quantity 1.

### Expected result
Price of selected product should display in cart.
### Actual result

Showing product price as zero.

![Screenshot from 2020-02-15 17-03-20](https://user-images.githubusercontent.com/45203177/74587160-37dd3280-5015-11ea-9cbf-5a7a7f96060d.png)
![Screenshot from 2020-02-15 17-03-34](https://user-images.githubusercontent.com/45203177/74587161-40356d80-5015-11ea-8258-de50f3eabf9a.png)
![Screenshot from 2020-02-15 17-04-03](https://user-images.githubusercontent.com/45203177/74587165-462b4e80-5015-11ea-90d3-2784dceea798.png)

**Comment by jyoti-webkul** [comment]
- Fixed

**Comment by vaishaliwebkul** [comment]
Fix this issue for the velocity theme also.

**Comment by vaishaliwebkul** [comment]
Fixed
