### ISSUE TITLE
Issue with filter in RTL in both front-end and admin end.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2470]
# Bug report

### Title
Issue with filter in RTL in both front-end and admin end.
### Issue Description
Issue with filter in RTL in both front-end and admin end.
### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Change the admin section to RTL

### Expected result
Filter option should be visible properly.

### Actual result

![Screenshot (11)](https://user-images.githubusercontent.com/45203177/74588451-9826a100-5022-11ea-9ee9-60ab78b17a6f.png)

**Comment by vaishaliwebkul** [comment]
Fixed
