### ISSUE TITLE
When deleting an image- it's not removed from storage.

### ISSUE THREAD

**Issue by adavie1** [bagisto/bagisto#2471]
# Bug report

### Title
When an image is deleted, for example, a product image, the database loses the reference to the file, but the file itself is not removed from `public/product/<prod #>`

### Issue Description
The file should also be deleted from storage.

### Steps to reproduce

    1. Upload an image, to a product for example.
    2. Check storage dir
    3. Delete image in Admin > Catalog
    4. The image is taken out of the UI, but the physical file is still on disk.

### Expected result
That when a image is deleted, it should also be deleted from storage.

For small systems, not much of an issue, but with a fast moving e-commerce site, a lot of wasted space can accumulate very quickly.

**Comment by rahulshukla-webkul** [comment]
Hi @adavie1 

Image gets deleted but folder name in which image is stored, does not gets deleted.

**Comment by adavie1** [comment]
@rahulshukla-webkul the actual image doesn't get deleted from storage directory.

**Comment by rahulshukla-webkul** [comment]
Hi @adavie1 

Can you mention version of bagisto ?

**Comment by adavie1** [comment]
Current master, just updated 3 days ago.

**Comment by rahulshukla-webkul** [comment]
Hi @adavie1 

You can check APP_VERSION in .env file and we are not getting this issue at our end.

**Comment by adavie1** [comment]
What seems to be happening with many the errors I'm experiencing, Velocity issues, etc. Because I've being to git pull and php artisan migrate calls, from a clean install two weeks ago, things aren't being updated correctly. I've been using the same database connection though.

With a totally fresh install, including the database, no issues found.
