### ISSUE TITLE
Can't get email from any controller

### ISSUE THREAD

**Issue by SamiXSous** [bagisto/bagisto#2474]
# Bug report

### Title
Can't get mail from any controllers!

### Issue Description
I can't get the mailing functionalities to work. I can't get any mail for registering, for forgot password etc.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Bagisto V0.1.0
    1. Laravel V5.6.*
    2. Homestead V10.3.0

![Screenshot 2020-02-17 at 16 07 19](https://user-images.githubusercontent.com/10419603/74665772-9aaf0500-51a0-11ea-82db-68cb2329dac2.png)

Username & Password are consciously left out!

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Set allow email verification to "Yes"
    2. Register user
    3. Resend verification mail

### Expected result
I should get an email in mailtrap

### Actual result
![Screenshot 2020-02-17 at 16 06 49](https://user-images.githubusercontent.com/10419603/74665969-efeb1680-51a0-11ea-919b-8bf2c613193f.png)

**Comment by SamiXSous** [comment]
Just updated to latest bagisto [v1.0.0-BETA1](https://github.com/bagisto/bagisto/releases/tag/v1.0.0-BETA1) and emails are working perfectly

**Comment by CesarObedFL** [comment]
hello, i'm having the same issue...

my bagisto version is 1.4.5

my .env file is : 
`
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=cesarobedfl@gmail.com
MAIL_PASSWORD=xxxxxxxxxxxxxxxx
MAIL_ENCRYPTION=tls

SHOP_MAIL_FROM=cesarobedfl@gmail.com
ADMIN_MAIL_TO=
MAIL_FROM_NAME=
`

and i'm getting this error in the reset password page: 

` Email &quot;&quot; does not comply with addr-spec of RFC 2822.`

please help...
