### ISSUE TITLE
Category locale issue

### ISSUE THREAD

**Issue by monter08** [bagisto/bagisto#2476]
# Bug report

### Title
Cannot edit category on other locale.

### Issue Description
The error occurs when add new locale and try edit existing category using new locale, if we add category after create locale all work good.

### Preconditions

    1. Bagisto v1.0.0-BETA1
    2. Laravel Framework 5.6.39

### Steps to reproduce

    1. Create category
    2. Create new locale
    3. Try edit category using new locale

### Actual result
![Zrzut ekranu 2020-02-17 o 17 16 21](https://user-images.githubusercontent.com/9307881/74670823-3db84c80-51aa-11ea-826e-c392d626d07d.png)

**Comment by vivek-webkul** [comment]
Hi @monter08 

Bagisto v1.0.0-BETA1 version is compatible with Laravel Version 6.x.
https://github.com/bagisto/bagisto/releases/tag/v1.0.0-BETA1

And I checked this issue on Laravel 6, working fine.

**Comment by monter08** [comment]
I found the reason, the error occurs on php version 7.4

**Comment by jitendra-webkul** [comment]
I am closing this issue, this issue has been already resolved in new version.
