### ISSUE TITLE
Trying to get property 'code' of non-object (Velocity Theme)

### ISSUE THREAD

**Issue by SamiXSous** [bagisto/bagisto#2482]
# Bug report

### Title
Trying to get property 'code' of non-object in /views/UI/particals.blade.php line nr 308

### Issue Description
There is something wrong with the "$currency->code" that can't get the property

### Preconditions

    1. Bagisto V1.0.0-BETA

### Steps to reproduce

    1. Set Channel -> Design -> Theme to Velocity

### Expected result

*   Should see the Velocity Theme

### Actual result
![Screenshot 2020-02-18 at 10 23 44](https://user-images.githubusercontent.com/10419603/74722412-2d02e780-5239-11ea-8afd-d35b8538f263.png)

**Comment by vaishaliwebkul** [comment]
Hi @SamiXSous 
 This issue has been fixed in the master branch.

**Comment by SamiXSous** [comment]
@rahulshukla-webkul Just tested again after pull from master and problem is resolved!
