### ISSUE TITLE
Can't add content to Velocity

### ISSUE THREAD

**Issue by SamiXSous** [bagisto/bagisto#2483]
# Bug report

### Title
**Can't add new content to content pages list in velocity**

### Issue Description
**Once I click on the "Add New Content" button in /admin/velocity/content I get an error**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Bagisto V1.0.0-BETA

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Sign In to Admin
    2. Click on "Velocity"
    3. Click on "Add New Content" button

### Expected result
**I should be able to see a form to add new content**

### Actual result

![Screenshot 2020-02-18 at 10 35 37](https://user-images.githubusercontent.com/10419603/74723174-6ee05d80-523a-11ea-9493-2d0059052d2f.png)

**Comment by rahulshukla-webkul** [comment]
Hi @SamiXSous 

This issue has been fixed. Kindly pull from master branch.
Please see this one - https://github.com/bagisto/bagisto/issues/2378

**Comment by SamiXSous** [comment]
@rahulshukla-webkul Just tested again after pull from master and problem is resolved!
