### ISSUE TITLE
UI CSS interfers with custom blade on home page.

### ISSUE THREAD

**Issue by adavie1** [bagisto/bagisto#2485]
# Bug report -  **Default theme!**

### Title
The CSS of of the default theme overwrites the `@include('...')` on the shop home page.

### Issue Description
I want to have a simple calculator on the home page. I found this [one](https://webdevtrick.com/basic-javascript-calculator-source-code/), copied CSS and HTML to a Blade view.

### Expected result
![image](https://user-images.githubusercontent.com/3030402/74724457-40cd3e80-5277-11ea-939d-3b3d953eb6d5.png)

It actually appears correctly, briefly on page load, then it goes to that actual result below.

### Actual result
![image](https://user-images.githubusercontent.com/3030402/74724555-5fcbd080-5277-11ea-9c29-b71db295b973.png)

**Comment by adavie1** [comment]
@jitendra-webkul  this might help- [Tailwind CSS](https://tailwindcss.com/) - I've checked out the UI CSS it seems largely abandoned and it's very opinionated  CSS! The good thing about it: very clean UI, and semi-mobile friendly.

However, the downside something is overriding the CSS in my blade, not sure if UI CSS or Laravel.

My personal feeling, is that go with a CSS framework that is under active use, and has a good following.

The nice thing about Tailwind, it's that it makes it very easy to customise the look and feel without changing CSS everywhere. Much easier to create themes. Hope this helps.

There seems to be a lot of UX issues with the Velocity theme, which why I'm not using it currently.

**Comment by shubhwebkul** [comment]
Hi @adavie1 
Could you please share blade file you've created and the screenshot, where you've included that file.

**Comment by jitendra-webkul** [comment]
I hope above reply solved your issue. I am closing this issue for now. Feel free to reopen this issue if needed.
