### ISSUE TITLE
Update download instructions and files

### ISSUE THREAD

**Issue by SamiXSous** [bagisto/bagisto#2486]
**After adding a few issues on Github I realised that all my issues had to do with outdated versions of Bagisto.** 
How is it possible that I have an outdated version of Bagisto If a followed both instructions step by step to installing Bagisto. Both the .zip file and the composer create-project bagisto/bagisto install outdated files. 
1. It would be nice & handy that both these ways of installation get updated to install the latest version of Bagisto.
2. Or add in Github to get the latest version of Bagisto to clone and pull this Repo.

**Comment by rahulshukla-webkul** [comment]
Hi @SamiXSous 

In this week, we are going yo release our stable version. So when you will use above process, you will get stable one.

**Comment by jitendra-webkul** [comment]
I am closing this issue, I hope all your issues get resolved in a new version.
