### ISSUE TITLE
ErrorException When Editing product in different language

### ISSUE THREAD

**Issue by SamiXSous** [bagisto/bagisto#2488]
# Bug report

### Title
**ErrorException when trying to edit product in different locale**

### Issue Description
**I receive an issue with the ProductController on line nr 189**
**Trying to get property 'code' of non-object**

### Preconditions

    1. Bagisto Latest Pull from Master 

### Steps to reproduce

    1. Add a new locale
    2. Edit product
    3. Select another locale

### Expected result
**Show form to edit product in English locale.**

### Actual result
![Screenshot 2020-02-18 at 11 38 22](https://user-images.githubusercontent.com/10419603/74728526-3729e380-5243-11ea-8ccb-4aee88951918.png)

**Comment by vaishaliwebkul** [comment]
This issue has been fixed.
