### ISSUE TITLE
Database reset fails

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#2500]
# Bug report

### Issue Description
When using `artisan migrate:reset` you get integrity constrain violations.

### Preconditions
    1. clone the master branch.
    2. install bagisto

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Execute artisan migrate:reset after installing Bagisto
    2. See the result.

### Expected result
it should reset all the tables from the database.

### Actual result
In Connection.php line 669:

 SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails (SQL: drop table if exists `cart_rules`)

In PDOStatement.php line 119:

 SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails

In PDOStatement.php line 117:

 SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails

**Comment by rahulshukla-webkul** [comment]
Hi @ghermans 

We have fixed this issue, thanks for notifying us.
