### ISSUE TITLE
Category Creation crashes on fresh install of v1.0.0-BETA1

### ISSUE THREAD

**Issue by iftikharalinaeem** [bagisto/bagisto#2505]
# Bug report

### Title
**Category Creation crashes on fresh install of v1.0.0-BETA1.**
**Category Creation crashes on fresh install of v1.0.0-BETA1.**

### Issue Description
**I installed fresh bagisto and did the setup usual way. But when I try to create category, the category is created but web crashes with error**

### Preconditions
    1.v1.0.0-BETA1.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Install fresh bagisto v1.0.0-BETA1 (using the normal steps described in the installation guide)
    2. Login with admin user
    3. Create Category

### Expected result
**Category should be created without any error.**

*   [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/4716273/74821747-1fbb2b00-5315-11ea-84a7-6a4e3c228008.png)

### Actual result

>    **The page crashes with error.**

**Comment by jyoti-webkul** [comment]
@iftikharalinaeem 
This issue has been fixed in master. Please take a pull
