### ISSUE TITLE
Add dutch translations

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#2512]
@rahulshukla-webkul or @jitendra-webkul i will add these in the next couple hours.

**Comment by adavie1** [comment]
@ghermans it's open source! :-P The files you need are in 
`packages/Webkul/Admin/src/Resources/lang/nl/app.php` - For **Admin** pages
`packages/Webkul/Shopsrc/Resources/lang/nl/app.php` - For **Shop** pages

Note: **_nl_** - is [2 letter ISO code](https://www.sitepoint.com/iso-2-letter-language-codes/) for the Dutch language.

I've been updating the Spanish ones, which seem to be Google Translate efforts, but a good start.
