### ISSUE TITLE
Currency from seeder is not added

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#2518]
# Bug report

### Issue Description
After completing the installation and logging in to the admin interface i noticed that the Euro currency isn't added to the currency table.

### Preconditions

    1. master branch.

### Steps to reproduce

    1. Do a clean Bagisto install
    2. Login to the admin interface
    3. Go to the currency list    

### Expected result
You should see 2 currencies (USD and Euro).

### Actual result
You only see the USD currency.

**Comment by jitendra-webkul** [comment]
@ghermans 

Fixed in #2688 PR.
