### ISSUE TITLE
Weird currency output when using translations

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#2537]
# Bug report

### Preconditions

    1. master branch.

### Steps to reproduce

![currencyKnipsel](https://user-images.githubusercontent.com/1594411/75031639-fdf1ad80-54a6-11ea-8d8b-ff97d2d986a3.PNG)

### Expected result
**Tell us what should happen.**

it should return € in this case instead of US$

**Comment by ghermans** [comment]
this also occurs in the admin interface, @rahulshukla-webkul if you have some spare time could you check this please?

**Comment by ghermans** [comment]
So i found the root cause of this issue when you define in the .env file `APP_CURRENCY=EUR` and that currency isn't added to the default channel then it will display US$ in front of each price.

**Comment by jitendra-webkul** [comment]
Implemented in #2551 PR
