### ISSUE TITLE
Invoices aren't legally valid.

### ISSUE THREAD

**Issue by adavie1** [bagisto/bagisto#2549]
# Bug report

### Title
In most countries for an invoice to be legally valid, it needs the address and company or personal name of the issuer. Without that- the client is not obliged to pay.

### Issue Description
See above.

### Steps to reproduce
Create an invoice- there's no issuer name or address.

### Expected result
The invoice should have a company or personal name and an address, in some countries you also need company registration no and tax ID and contact details like phone, fax or email.

### Actual result

![image](https://user-images.githubusercontent.com/3030402/75149617-6fe32480-573d-11ea-9a4e-521a67a9edc8.png)

This is from the PDF, the e-mail also doesn't have the address.

**Comment by jyoti-webkul** [comment]
- Fixed

--------------------------------

Company logo and address field added in invoice setting

https://prnt.sc/rjg52s
