### ISSUE TITLE
error mysql 8

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2552]
![捕获](https://user-images.githubusercontent.com/30912144/75216151-d4b87200-5771-11ea-8581-42606702a165.PNG)

Thanks!

**Comment by SteffenMahler** [comment]
Check your database settings in .env

**Comment by lotarbo** [comment]
@marcelowu or mb problem in mysql8, new version changed default auth.
So u need do something like 
`mysqld --default-authentication-plugin=mysql_native_password`
https://stackoverflow.com/questions/52864853/how-to-get-mysql-8-to-run-with-laravel

**Comment by marcelowu** [comment]
![批注 2020-02-25 230732](https://user-images.githubusercontent.com/30912144/75305036-ab581e80-5823-11ea-90b9-2c59980ede77.png)

**Comment by marcelowu** [comment]
![批注 2020-02-25 234440](https://user-images.githubusercontent.com/30912144/75307009-6505be00-5829-11ea-9da8-10e9c1b0697f.png)
![批注 2020-02-25 2344401](https://user-images.githubusercontent.com/30912144/75307012-6800ae80-5829-11ea-9817-113eae89c42e.png)

**Comment by marcelowu** [comment]
![批注 2020-02-25 234440](https://user-images.githubusercontent.com/30912144/75307166-cded3600-5829-11ea-9436-a51604a5cdcc.png)
![批注 2020-02-25 2344401](https://user-images.githubusercontent.com/30912144/75307168-cf1e6300-5829-11ea-9933-a8c6f64d43e2.png)
