### ISSUE TITLE
Logo and favicon broken

### ISSUE THREAD

**Issue by grath1** [bagisto/bagisto#2556]
My images are being stored in public/storage/channel/1/iSsLkakQKaqnCFzvxJdx2bHQAKjfiJ0RqmE85Ypg.png but it doesn't show in the front end (store). I've linked the storage to public, cleared cache and still comes up broken.

**Comment by prateek-webkul** [comment]
Hello grath1,

Refer link https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions 

Thanks

**Comment by jitendra-webkul** [comment]
I am closing this issue, I hope the above reply solved your issue
