### ISSUE TITLE
Filter price is not working for default theme

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2558]
# Bug report

### Title
Filter price is not working for the default theme

### Issue Description
Filter price is not working for the default theme

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Open shop view
    2. step2- filter product based on price(issue)

### Expected result

*   should filter all product based on price range

### Actual result

![Screenshot (8)](https://user-images.githubusercontent.com/43210406/75336858-e739c500-58b1-11ea-9b0d-2703675cf640.png)

**Comment by jyoti-webkul** [comment]
- Fixed

------------------------
https://prnt.sc/rjfd18

**Comment by vaishaliwebkul** [comment]
This issue is still exist, please fix
