### ISSUE TITLE
Related categories tree should be shown in product page

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2559]
# Bug report

### Title
Related categories tree should be shown on the product page

### Issue Description
Related categories tree should be shown on the product page

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- open shop view
    2. step2- click on any product (on this product page unable to understand that product lies under which of the category/subcategory)
    

### Expected result

In the header of the product page, the related product's category tree should be shown.

### Actual result

![Screenshot (9)](https://user-images.githubusercontent.com/43210406/75337704-7d221f80-58b3-11ea-889d-0dd34d51f913.png)

**Comment by jitendra-webkul** [comment]
We will be doing this on a brand new frontend.
