### ISSUE TITLE
error catalog/categories/create

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2562]
![批注 2020-02-26 214616](https://user-images.githubusercontent.com/30912144/75404183-8e395380-58e8-11ea-8bcc-d68bd58b914c.png)

Thanks!

**Comment by rahulshukla-webkul** [comment]
Hi @marcelowu 

Check the collation type of each table, and make sure that they have the same collation.

After that check also the collation type of each table field that you have use in operation.

I had encountered the same error, and that tricks works on me.

You either need to add COLLATE to the WHERE clause,

or add it to the IN parameter definition,

or alter the field itself:

`ALTER TABLE tableA CHARACTER SET utf8 COLLATE utf8_unicode_ci;`

as the default collation for stored procedure parameters is utf8_general_ci and you can't mix collations.

Unless you need to sort data in Unicode order, I would suggest altering all your tables to use utf8_general_ci collation.

Thanks

**Comment by marcelowu** [comment]
ALTER DATABASE bagisto CHARACTER SET utf8 COLLATE utf8_unicode_ci;

**Comment by marcelowu** [comment]
![Sem título](https://user-images.githubusercontent.com/30912144/75577821-8f31c880-5a41-11ea-8ea1-6abd74cdcbf2.png)

**Comment by marcelowu** [comment]
does not work

**Comment by marcelowu** [comment]
is ok, Thanks!

CREATE DATABASE bagisto CHARACTER SET utf8 COLLATE utf8_unicode_ci;

**Comment by hcyildirim** [comment]
I still have the same problem.

```
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '=' (SQL: update categories set _lft = case when _lft >= 14 then _lft`+2 else `_lft end, _rgt = case when _rgt >= 14 then _rgt`+2 else `_rgt end where (`_lft` >= 14 or _rgt >= 14))
```

**Comment by gabelatendai** [comment]
thank you it worked for I just created a table with utf8_unicode_ci colllection

**Comment by pira998** [comment]
> is ok, Thanks!
> 
> CREATE DATABASE bagisto CHARACTER SET utf8 COLLATE utf8_unicode_ci;

it is worked for me
