### ISSUE TITLE
Impossible to create the root directory

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2578]
![Capturar1](https://user-images.githubusercontent.com/30912144/75585685-6b767e80-5a51-11ea-8faf-2b03f3954dad.PNG)

Thanks!

**Comment by chomnit** [comment]
Any update on this issue? I still facing this issue on my site.

**Comment by jhapali9** [comment]
I had same problem..
One simple solution would be re-run the migration...

**Comment by vaishaliwebkul** [comment]
@chomnit @jhapali9 
Don't need to migrate again, Simply go to the storage/app folder and create a public folder by replacing public txt file

**Comment by jhapali9** [comment]
@vaishaliwebkul thank u..
