### ISSUE TITLE
error menu mobile

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2579]
![Capturar](https://user-images.githubusercontent.com/30912144/75585733-88ab4d00-5a51-11ea-8ca8-e7af7c589714.PNG)

Thanks!

**Comment by DevBala-6** [comment]
hi, i have also facing this issue,how can i solve ? help me

**Comment by vaishaliwebkul** [comment]
@DevBala-6 
do the following

    pull the latest upate from the master branch
    run php artisan vendor:publish --force
    run php artisan config:cache

Now open the url in mobile and reload the page again.
Thanks,

**Comment by vaishaliwebkul** [comment]
Hi @shubhwebkul 
 Header is not showing in mobile view

![Screenshot from 2020-03-23 10-12-45](https://user-images.githubusercontent.com/43210406/77288740-79d95280-6cfe-11ea-9386-0ee3574ea54a.png)

**Comment by vaishaliwebkul** [comment]
fixed
