### ISSUE TITLE
Display 3D product preivew image 

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2583]
Display 3D product preivew image
Using SpriteSpin [http://spritespin.ginie.eu/](url)

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by shubhwebkul** [comment]
Hi @marcelowu ,
Thanks for your suggestion and we will surely look into this.
