### ISSUE TITLE
Not getting root category name, in categories.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2584]
# Bug report

### Title
Not getting root category name.
### Issue Description
Not getting root category name.
### Preconditions

    1. framework Version- master

### Steps to reproduce
    1. step1- Install bagisto from master
    2. step2- Go to categories section .

### Expected result
Name should display for root category.

### Actual result
Doesn't getting name for root category.
![Screenshot (10)](https://user-images.githubusercontent.com/45203177/75652059-22f0d800-5c80-11ea-8d39-b593e837c93c.png)

**Comment by jyoti-webkul** [comment]
- Fixed

**Comment by shokki96** [comment]
Does this issue fixed on master branch? Facing same on master

**Comment by yosirn** [comment]
Still having the same issue.
on latest dev verssion
