### ISSUE TITLE
APP_TIMEZONE and APP_LOCALE values should be available in env file.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2586]
# Bug report

### Title
APP_TIMEZONE and APP_LOCALE values should be available in env file.

### Issue Description
APP_TIMEZONE and APP_LOCALE values should be available in env file.
### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- After installation check the env file.

### Expected result
APP_TIMEZONE and APP_LOCALE values should be available in env file.
### Actual result

![Screenshot from 2020-03-02 12-38-45](https://user-images.githubusercontent.com/45203177/75653084-c5aa5600-5c82-11ea-9afe-f3e5cf0f0495.png)

**Comment by ghermans** [comment]
Did you use the console command **bagisto:install** or the web installer ?

**Comment by jyoti-webkul** [comment]
No, I had cloned the project and run the following commands
1.composer create-project 
2.php artisan migrate
3.php artisan db:seed
4.php artisan storage:link
5.php artisan vendor:publish

**Comment by ghermans** [comment]
That is the reason why APP_TIMEZONE & APP_LOCALE are missing. 
More info can be found [here](https://github.com/bagisto/bagisto/issues/2525)

**Comment by vaishaliwebkul** [comment]
Fixed
