### ISSUE TITLE
hi everyone i'm wondering if customers after register could give a referral code ?? 

### ISSUE THREAD

**Issue by axelnazemi** [bagisto/bagisto#2590]
This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by jyoti-webkul** [comment]
Hi @axelnazemi 
Currently this is not possible, but we will add this feature soon in bagisto.

**Comment by jitendra-webkul** [comment]
You can create custom package for this
