### ISSUE TITLE
Allow Email Verification field is given twice, once in Configure->Customers->Setting and in Configure->Admin->Email.Currently if field is enable from any one grid and disable from other grid, then its not working.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2596]
# Bug report

### Title
Allow Email Verification field is given twice, once in Configure->Customers->Setting and in Configure->Admin->Email.

### Issue Description
Allow Email Verification field is given twice, once in Configure->Customers->Setting and in Configure->Admin->Email.

### Preconditions

    1. framework Version- master

### Expected result
Field should available only once.
### Actual result

currently if field is enable from any one grid and disable from other grid, then its not working.

**Comment by rahulshukla-webkul** [comment]
Hello @jyoti-webkul 

These two are different according to their purpose.
First states that, whether customer need verification or not and second one states that whether mail will send for verification purpose or not.
