### ISSUE TITLE
Delete option not appeared when attribute is added in family.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#261]
Framework Version: 0.1.2
![screenshot 4](https://user-images.githubusercontent.com/45203177/49434468-48233c00-f7da-11e8-81c9-bfd9301bcd4a.png)

**Comment by rahulshukla-webkul** [comment]
After adding attribute to family, u need to click on save button (Save Family) to save it & only user defined attribute can be deleted.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot 82](https://user-images.githubusercontent.com/45203177/52161819-19014c00-26f1-11e9-8fe0-bbbf8e61beea.png)
