### ISSUE TITLE
some of the attribute values aren't visible in comparison page

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2610]
# Bug report

### Title
some of the attribute values aren't visible in comparison page

### Issue Description
some of the attribute values aren't visible in comparison page

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- guest_checkout & custom attribute value add-in product
    2. step2- now make this product as comparable
    3. step3- check the attribute values above

### Expected result
  all the attribute which selected as comparable should show in the comparison page

### Actual result

>  Guest_checkout & specification attribute value is not present.

![Screenshot (8)](https://user-images.githubusercontent.com/43210406/75854129-72b4d800-5e15-11ea-80cb-c07789ac8bc9.png)

**Comment by jyoti-webkul** [comment]
- Not Fixed

----------------------------------------------------------------

https://prnt.sc/rjlw34

**Comment by vaishaliwebkul** [comment]
@shubhwebkul 
getting this issue in console

steps to reproduct
1. add a product in compare list as login user
2. allow guest_checkout attribute to make as comparable
3. reload the compare page again

TypeError: "product.product is undefined"
    anonymous http://localhost/bagisto/public/themes/velocity/assets/js/velocity.js line 1 > Function:3

**Comment by vaishaliwebkul** [comment]
fixed
