### ISSUE TITLE
installer error

### ISSUE THREAD

**Issue by seirralanzce** [bagisto/bagisto#2611]
# Bug report

### Title
during install migration, hit error

### Preconditions

    1. After clicking migrate & seed it run to error.

### Steps to reproduce

    1. after get from composer and put up in php artisan serve, go to localhost:8000 
    2. key in app name and db.
    3. save and continue
    4. migrate & seed
    5. error occured

### Expected result
Not sure what next?

### Actual result

![image](https://user-images.githubusercontent.com/1050583/75854942-2fb22f00-5e2c-11ea-8cc4-0b2ad5dbc9db.png)

**Comment by rahulshukla-webkul** [comment]
Hi @seirralanzce 

Can you mentioned your database and its version and make sure that you have created database and provided all the required database credentials in .env file.
