### ISSUE TITLE
Propaganistas/Laravel-Intl is abandoned

### ISSUE THREAD

**Issue by marvinrabe** [bagisto/bagisto#2613]
Hello,

Your Package is dependent on Propaganistas/Laravel-Intl (see `packages/Webkul/Core/composer.json`) which is abandoned.

I decided to take over the maintenance because I use this package myself in many projects. The migration process will take you less than 5 minutes.

https://github.com/marvinrabe/laravel-intl

If you have any issues, feature request or you need help integrating my package, feel free to [create an issue](https://github.com/marvinrabe/laravel-intl/issues/new). I will help you in any way possible.

Best,

– Marvin

**Comment by rahulshukla-webkul** [comment]
Hi @marvinrabe 

We have removed this dependency from our project, right now we are using php (intl).
