### ISSUE TITLE
shipping & payment always set to default value in checkout page

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2614]
# Bug report

### Title
shipping & payment always set to the default value in the checkout page

### Issue Description

Selected shipping & payment method in checkout page reset to the default one when going back to the order summary step to the previous step.

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- follow all the process in checkout till the last step
    2. step2- go back to the shipping step again, you will see by default "flat rate" is selected.

### Expected result

In the shipping & payment step, selected option should be shown when going back to the previous step.

**Comment by jitendra-webkul** [comment]
Value gets reset because if a user is going back to the previous step that means they want to update the previously selected value
