### ISSUE TITLE
Tiny Bug on Admin Pages

### ISSUE THREAD

**Issue by adavie1** [bagisto/bagisto#2616]
# Bug report

### Title
When you click on the pencil icon to edit a page- clicking the < icon to go back to the table doesn't work.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. all versions

### Steps to reproduce

    1. Login to Admin Dashboard, go to CMS Pages
    2. Click on the "pencil" to edit a page
    3. Click the < to go back to the page grid

### Expected result
As per the rest of the system- clicking the < should take you back to the previous table.

### Actual result
Nothing happens when you click the <.

**Comment by vaishaliwebkul** [comment]
Hi @adavie1 
Thanks for notifying this bug, this is resolved now.
