### ISSUE TITLE
i create a site and it is up kind of noting works

### ISSUE THREAD

**Issue by mikeyapina** [bagisto/bagisto#2621]
I created the sire http://ov3rt.com and noting clicks

**Comment by mikeyapina** [comment]
You sent me notes. That now that i created the sites i can add content. But i cannot evne get to the login either. What are you talking about! I described the issue perfectly. I cannot click on anything not even that admin button!

**Comment by vivek-webkul** [comment]
Hi @mikeyapina 

I think now your site is working, there was some permission related issue.
I am closing this issue. In case you faced this issue again, you can revert back.
