### ISSUE TITLE
Tax rates zipcode is still required when enable zip range is disabled

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#2626]
# Bug report

### Issue Description
When you don't enable zip range the zip code field is still required.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master branch.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Go to the admin interface
    2. Click on settings
    3. Click on Taxes
    4. Create a tax rate and see the result

### Expected result
The zip code field should not be required when zip range is disabled.

![TaxRateKnipsel](https://user-images.githubusercontent.com/1594411/76098153-3e821880-5fc9-11ea-9fba-725137508c8d.PNG)

**Comment by jyoti-webkul** [comment]
Hi @ghermans 
This is not an issue, zip code and zip range both are different thing.
When you will enable zip range you have to provide the range i.e(from and to) in which tax rate will be applied and in case of Zip code you have to provide only particular zip where tax rate will be applicable
