### ISSUE TITLE
Some Admin panel blank pages after translation v1.0.0

### ISSUE THREAD

**Issue by aladinlandolsi** [bagisto/bagisto#2628]
I translated the whole app to Frensh, Ui and customer works fine. The probleme is that i'm getting some blank pages in the Admin panel
![image](https://user-images.githubusercontent.com/61437724/76143411-88c1d300-6077-11ea-91fc-c3c10b4bd6ce.png)

PS: i'm using Bagisto v1.0.0 
And this is the full Frensh translation download link : https://mirr.re/d/1fXs

**Comment by jitendra-webkul** [comment]
@aladinlandolsi 

Can you elaborate more, with step to reproduce this issue?

**Comment by jitendra-webkul** [comment]
I hope your problem get solved. I am closing this issue for now. Feel free to reopen this issue if needed.
