### ISSUE TITLE
Filter for visible in menu is not working in Category grid.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#263]
Framework Version: 0.1.2
![screenshot 1](https://user-images.githubusercontent.com/45203177/49438501-845b9a00-f7e4-11e8-9800-e13436bfea50.png)

**Comment by prashant-webkul** [comment]
It works for with the values of 0 and 1, those values have been altered on the front for proper representation and better understanding for admin users.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
