### ISSUE TITLE
product moved to cart still showing in wishlist

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2640]
# Bug report

### Title
product moved to cart still exist in wishlist

### Issue Description
product moved to cart from the wishlist still showing in wishlist

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1 - log in as a customer
    2. step2 - move to cart any product from the wishlist page
    3. step3 - the product still exists in the wishlist.

### Expected result

*   product should be removed from the wishlist if moved from the wishlist page
 
### Actual result

>    product not removed from the wishlist page once move to cart a product

**Comment by jyoti-webkul** [comment]
- Not Fixed

-------------------------------------------------------------------------------

Product still available in  wishlist if there is only one product in wishlist.

**Comment by jyoti-webkul** [comment]
Last product doesn't removed from wishlist until we refresh the page

**Comment by vaishaliwebkul** [comment]
fixed
