### ISSUE TITLE
Add an option to set encryption to none during installation

### ISSUE THREAD

**Issue by SamiXSous** [bagisto/bagisto#2644]
# Bug report

### Title
Add an option for blank encryption option during install 

### Issue Description
When installing bagisto locally and you want to use mailtrap.io in you configuration I see that tere is no option for no encryption. There is only a choice between SSL and TLS and none of these are the correct configuration for mailtrap.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. V.1.0.0
    2. Stable Release via composer

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Get bagisto package
    2. Go thru installation till you get too Email configuration

### Expected result
**Tell us what should happen.**

It should show an extra option "None" for no encryption.
This will result in me not having to change this manually afterwards in the dot env file.

<img width="732" alt="Screenshot 2020-03-12 at 3 06 11 PM" src="https://user-images.githubusercontent.com/10419603/76529872-2f8ce180-6473-11ea-86a8-6f203686bdb5.png">

### Actual result
**Tell us what happens instead.**

After installing bagisto I have to go into my dot env file and remove the Mail_Encryption line or set it to blank

**Comment by vaishaliwebkul** [comment]
Hi @SamiXSous 
 Thanks for notifying this, the issue has been resolved.
You can reopen this issue if found again.
