### ISSUE TITLE
Error on adding product to cart

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#2645]
On clicking the "**Add to Cart**" button the following error is shown:

Error ! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'custom_price' in 'field list' (SQL: update `cart` set `custom_price` = ?, `cart`.`updated_at` = 2020-03-12 19:53:56 where `id` = 3).

The product is still added to the cart.

    1. framework Version: 1.0.0

**Comment by emperorjm** [comment]
I found that the error is due to a listener within the **"Marketplace"** module which is not compatible with version 1.0.0 of Bagisto.

Event::dispatch('checkout.cart.add.after', $cart);

I had to comment the sections that added the **"custom_price"** field:

`/**
     * Product added to the cart
     *
     * @param mixed $cartItem
     */
    public function cartItemAddAfter($cartItem)
    {
        if (isset($cartItem->additional['seller_info']) && !$cartItem->additional['seller_info']['is_owner']) {
            $product = $this->productRepository->find($cartItem->additional['seller_info']['product_id']);
            if ($product) {
                $cartItem->price = core()->convertPrice($product->price);
                $cartItem->base_price = $product->price;
                //$cartItem->custom_price = $product->price;
                $cartItem->total = core()->convertPrice($product->price * $cartItem->quantity);
                $cartItem->base_total = $product->price * $cartItem->quantity;

                $cartItem->save();
            } else {
                //$cartItem->custom_price = NULL;
            }

            $cartItem->save();
        } else {
            //$cartItem->custom_price = NULL;

            $cartItem->save();
        }
    }`

**Comment by jyoti-webkul** [comment]
hi @emperorjm 
Marketplace is not compatible with bagisto 1.0.0, we are working on it and will update it soon.

**Comment by jitendra-webkul** [comment]
I am closing this issue as this issue is not related to Bagisto core
