### ISSUE TITLE
Rental booking added to cart without selecting date in velocity

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2674]
# Bug report

### Title
Rental booking added to cart without selecting a date in velocity

### Issue Description
Rental booking added to cart without selecting a date in velocity

### Preconditions

    1. framework Version-  master

### Steps to reproduce

    1. step1- go to a product page of rental booking
    2. step2- add to cart item without selecting date

### Expected result

*   date picker should be validated before adding to cart item

### Actual result

![Screenshot (18)](https://user-images.githubusercontent.com/43210406/76830271-eb228c80-684a-11ea-9f5d-c6e690df45c0.png)

**Comment by vaishaliwebkul** [comment]
Rental booking per daily basis not able to add into cart, please check once

![rental](https://user-images.githubusercontent.com/43210406/77140221-f53cc900-6a9e-11ea-87f1-57a11ca15de7.png)

**Comment by shubhwebkul** [comment]
please try after clearing browser's cache.

**Comment by vaishaliwebkul** [comment]
still getting the same.

**Comment by vaishaliwebkul** [comment]
getting this issue in velocity only
![Screenshot(4)](https://user-images.githubusercontent.com/43210406/77422708-eeda8400-6df3-11ea-87bd-8e3f4b7313c5.png)

**Comment by vaishaliwebkul** [comment]
fixed
