### ISSUE TITLE
Price format gets changed on editing product

### ISSUE THREAD

**Issue by melorbany** [bagisto/bagisto#2675]
# Bug report

### Title
The format of product price gets changed on updating the product.

### Issue Description
The format of product price gets changed on updating the product.  The decimal precision for the numbers get converted to 4 numbers example 189.**0000**, and on saving it gives an error "The price must be valid."

### Preconditions
Framework Version : 1.0

### Steps to reproduce

    1. Create a product
    2. Edit the created product.
    3. Click save

![image](https://user-images.githubusercontent.com/6257614/76830608-a7be2300-6836-11ea-82d5-eb60952444b6.png)

**Comment by jyoti-webkul** [comment]
Hi @melorbany 
We are unable to reproduce this issue can you provide a video for the same?

**Comment by melorbany** [comment]
I found the issue related to migrating the old bagisto database from 0.18 to version 1.0. The decimal for product attributes was decimal(12,4), which creates the above issue.
