### ISSUE TITLE
Weight of Product is displaying in negative.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#269]
Framework Version: 0.1.2

![screenshot 14](https://user-images.githubusercontent.com/45203177/49507174-e4fedb80-f8a5-11e8-9280-51f9214a0e65.png)
![screenshot 15](https://user-images.githubusercontent.com/45203177/49507208-fb0c9c00-f8a5-11e8-82d0-b8bcd9771eda.png)

**Comment by jitendra-webkul** [comment]
FYI,

It's not a negative sign, it is a separator.

**Comment by Jyoti-Singh1** [comment]
Then separator should come just after the label.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed. Now specification is removed.
