### ISSUE TITLE
Shipping and Payment methods automatically selected on Checkout oage

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#2691]
**Bagisto**: 1.0.0
**Theme**: Velocity

After selecting the Billing/Shipping address the Shipping section is shown with the first option selected by default which then automatically displays the Payment section which sets the first option by default. 

The user should be allowed to select an option for each section so as not load all sections in one go which can be confusing.

It would also be great to show a Loading widget when a selection is made which in turns makes an ajax request to the server.

**Comment by vaishaliwebkul** [comment]
@emperorjm 
Thanks for notifying this. Now it has been implemented for Velocity theme.

**Comment by vaishaliwebkul** [comment]
@emperorjm 
No response from last 14 days, so Hope your issue has been resolved.
Feel Free to reopen this issue again.
