### ISSUE TITLE
Booking product page - add to cart button js error

### ISSUE THREAD

**Issue by khards** [bagisto/bagisto#2693]
# Bug report

### Title
When adding a rental product to the cart there is a JS error

### Issue Description
I have set up a rental product. When I click Add to cart I get the following js error:
velocity.js:1 Uncaught (in promise) TypeError: t.target.submit is not a function
    at velocity.js:1

### Preconditions

    1. dev-master 18th March 2020 22:28 GMT
    2. Commit id. 7faf5bb97f18a4f2fd77cd6b44b974343f006571

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Create a new simple Rental booking product
    2. Navigate to its product page, enter the date and press add to cart.

### Expected result
The product should be added to the cart

### Actual result
Javascript error. 

I'm not sure where the bug is in the code as it's minified in the browser.

t.target.submit fails in the following minified code:

                    onSubmit: function(t) {
                        var e = this;
                        this.toggleButtonDisability({
                            event: t,
                            actionType: !0
                        }),
                        "undefined" != typeof tinyMCE && tinyMCE.triggerSave(),
                        this.$validator.validateAll().then(function(n) {
                            n ? t.target.submit() : (e.toggleButtonDisability({
                                event: t,
                                actionType: !1
                            }),
                            eventBus.$emit("onFormError"))
                        })
                    },

**Comment by shubhwebkul** [comment]
Hello @khards ,
thanks for pointing down the issue. Issue has been resolved.

**Comment by jyoti-webkul** [comment]
- Fixed

**Comment by khards** [comment]
Thank you
