### ISSUE TITLE
Getting broken image for products and category.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2702]
# Bug report

### Title
Getting broken image for products and category.

### Issue Description
Getting broken image for products and category.
### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Create a product or category and add image.
    2. step2- Edit the created category and product and check the image.

### Expected result
Added image should display

### Actual result

Getting broken image.

https://prnt.sc/rjedt5

**Comment by jyoti-webkul** [comment]
Working fine

**Comment by greenlevel** [comment]
What was Wrong then?
For me also the image not showing
