### ISSUE TITLE
Getting exception on editing category for pt_BR locale in php 7.4

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2706]
# Bug report

### Title
Getting exception on editing category for pt_BR locale in php 7.4
### Issue Description
Getting exception on editing category for pt_BR locale in php 7.4
### Preconditions

    1. framework Version.-master
    
### Steps to reproduce

    1. step1- Create a locale
    2. step2- Update category for this locale

### Expected result
Category should be updated

### Actual result

https://prnt.sc/rjfpjk

**Comment by vaishaliwebkul** [comment]
fixed
