### ISSUE TITLE
Able to create booking product from back date.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2708]
# Bug report

### Title
Able to create booking product from back date.
### Issue Description
Able to create booking product from back date.
### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Create booking product by selecting booking type default
    2. step2- Select back date

### Expected result
Booking product should not create with back date

### Actual result

https://prnt.sc/rjgul5

**Comment by vaishaliwebkul** [comment]
fixed
