### ISSUE TITLE
After saving the default booking time product selected time for date range changes to 00:00:00 ,because of which not able to book appointment on frontend.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2716]
# Bug report

### Title
After saving the default booking time product selected time for date range changes to 00:00:00 ,because of which not able to book appointment on frontend.
### Issue Description
After saving the default booking time product selected time for date range changes to 00:00:00 ,because of which not able to book appointment on frontend.
### Preconditions

    1. framework Version.-master
  
### Steps to reproduce

    1. step1- Create a default booking product by selecting many booking for one day and select date range and save the product.
    2. step2- Edit the product and check the time.

### Expected result
Time should be same as selected.
### Actual result

![Screenshot (31)](https://user-images.githubusercontent.com/45203177/77222167-d9a4f180-6b76-11ea-8e42-bb392bbc44a9.png)
![Screenshot (32)](https://user-images.githubusercontent.com/45203177/77222183-048f4580-6b77-11ea-8c59-e6df90a9927c.png)

**Comment by vaishaliwebkul** [comment]
fixed
