### ISSUE TITLE
Getting error message on adding rental product in cart if rental booking is not available for that day.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2717]
# Bug report

### Title
Getting error message on adding rental product in cart if rental booking is not available for that day.
### Issue Description
Getting error message on adding rental product in cart if rental booking is not available for that day.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-master

### Steps to reproduce

    1. step1- Add a product for date on which rental is not available

### Expected result
Display a correct erorr message
### Actual result
![Screenshot (35)](https://user-images.githubusercontent.com/45203177/77224191-21cd0f80-6b89-11ea-8857-24b05591ade0.png)

**Comment by vaishaliwebkul** [comment]
fixed
