### ISSUE TITLE
Show error message "No booking available" if booking is not available for selected date.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2718]
# Bug report

### Title
Show error message "No booking available" if booking is not available for selected date.
### Issue Description
Show error message "No booking available" if booking is not available for selected date.
### Preconditions

    1. framework Version.-master

### Steps to reproduce
    1. step1- Select any date for which booking is not available.

### Expected result
Error message should throw

### Actual result

![Screenshot (37)](https://user-images.githubusercontent.com/45203177/77224588-43c89100-6b8d-11ea-8574-e8cf4f7bf223.png)
![Screenshot (38)](https://user-images.githubusercontent.com/45203177/77224592-4b883580-6b8d-11ea-8c67-b0778fb6ecfe.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now this enhancement **is done**  so I am **closing** this enhancement
And have attached a screenshot [Here](https://prnt.sc/JwjmxPT-tO9Z) for **future** **reference**
