### ISSUE TITLE
Error during migration on php artisan migrate

### ISSUE THREAD

**Issue by ahmadsaeedchdev** [bagisto/bagisto#2720]
![Screenshot from 2020-03-21 16-32-53](https://user-images.githubusercontent.com/59611858/77225512-a91e8100-6b91-11ea-9aba-26ac51033bb5.png)

Thanks!
![Screenshot from 2020-03-21 16-32-53](https://user-images.githubusercontent.com/59611858/77225538-d5d29880-6b91-11ea-837a-a25db67efd4c.png)
when i run this command php artisan migrate then after some migrations i got this error mention on pic

**Comment by rahulcs0082** [comment]
Hi @ahmadsaeedchdev 

Can you mentioned about your database and its version so that we can check.

**Comment by jitendra-webkul** [comment]
I am closing this issue, I hope your issue got resolved.
