### ISSUE TITLE
Compare product icon on header showing counts of compare product but there are no product in compare list.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2723]
# Bug report

### Title
Compare product icon on header showing counts of compare product but there are no product in compare list.
### Issue Description
Compare product icon on header showing counts of compare product but there are no product in compare list.
### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-master
    

### Expected result
Counts for compare product should not display

### Actual result

![Screenshot (41)](https://user-images.githubusercontent.com/45203177/77226621-b5a9d600-6b9f-11ea-8cda-c08829d4493c.png)

**Comment by shubhwebkul** [comment]
@jyoti-webkul , please mention steps to reproduce this bug.
