### ISSUE TITLE
Variants should not be created if cofigurable product created failed

### ISSUE THREAD

**Issue by gfd6th** [bagisto/bagisto#2725]
f you start to create a new cofigurable product, and select the cofigurabale attributes, you will open a new page to edit it and its variants. Then you close the page, the variants will be exist, but their parent product doesnot exist

**Comment by jyoti-webkul** [comment]
@gfd6th 
Can u please attach a screenshot.

**Comment by gfd6th** [comment]
step 1: Create a new configurable product

![image](https://user-images.githubusercontent.com/6814715/77283164-aee9a300-6d06-11ea-9dd2-ebc62c77ff17.png)

step 2: Before you config its variants, you could see these variants in databases already. 

![image](https://user-images.githubusercontent.com/6814715/77283451-55ce3f00-6d07-11ea-9d34-23c6442208fa.png)


step 3: close the edit product page or go to other page without click save button.
![image](https://user-images.githubusercontent.com/6814715/77283494-6ed6f000-6d07-11ea-8066-0887a38c3c33.png)

step 4: There are no the parent configurable product only variants in product list

![image](https://user-images.githubusercontent.com/6814715/77283728-063c4300-6d08-11ea-83c3-2c6c6414853e.png)

**Comment by rahulcs0082** [comment]
Hi @gfd6th 

Configurable product creation does not get fails actually it did not gets complete.
We have added some checks that's why it is not showing here, we will remove that one.
