### ISSUE TITLE
is shop.js the vue framework ??

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#2726]
as title says i have a question about the 10k line shop.js because it conflicts with slick slider jquery plugin and i want to add that now i want to know how can i edit the shop.js or even ui.js are they vuejs framwork? ? because they are so heavily coded like 10k lines each . thanks in advance

**Comment by gfd6th** [comment]
It seems like a bundle of Vue, jquery, accounting, Sizzle libraries. See shop.js.LICENSE

**Comment by farshadff** [comment]
@gfd6th  thanks for the help but can i ask one more question i cant see shop.js.LICENSE where is that file located ?? thanks

**Comment by vaishaliwebkul** [comment]
@farshadff 
shop.js.LICENSE file located here

**packages/Webkul/Shop/publishable/assets/js/shop.js.LICENSE**

**Comment by farshadff** [comment]
@vaishaliwebkul thanks for the help i just saw that :)

**Comment by ariadoos** [comment]
@farshadff  How to remove the jquery from shop.js ?
