### ISSUE TITLE
Seeder: SQL Error: Duplicate entry for '1' key 'PRIMARY'

### ISSUE THREAD

**Issue by sagarpatel9697** [bagisto/bagisto#2762]
**when run seeder on existing database using `php artisan db:seed`, throws error like below **
1. CategoryTableSeeder :
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' (SQ
  L: insert into category_translations`

2. ChannelTableSeeder
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-1' for key 'PRIMARY' (
  SQL: insert into channel_currencies`

I think, you should add line `DB::table('channel_currencies')->delete();` for **channel_currencies** table and for other tables as well in **CategoryTableSeeder** & **ChannelTableSeeder**.

**Comment by vaishaliwebkul** [comment]
@sagarpatel9697 
We are closing the issue, Feel free to reopen anytime if it's not resolved.
