### ISSUE TITLE
Can't delete Exchange Rates data

### ISSUE THREAD

**Issue by sagarpatel9697** [bagisto/bagisto#2769]
**Step to reproduce**
Go to `/admin/exchange_rates` path, try to delete data from the list. I can't delete data.

**Comment by vaishaliwebkul** [comment]
@sagarpatel9697 

Atleast one exchange rate is required in list, so you're not able to delete.

**Comment by sagarpatel9697** [comment]
Thank you, Going to close. Sorry for taking your time
