### ISSUE TITLE
charged per(table/guest) detail should be shown in front of table booking

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2772]
# Bug report

### Title
charged per(table/guest) detail should be shown in front of table booking

### Issue Description
charged per(table/guest) detail should be shown in front of table booking

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add table booking charged per table
    2. step2- show the product page,their is no instruction set, how would we charge??

### Expected result

 1. accroding to me, add the label "Charged per table(2 guest)" / "Charged per Guest" just below the product price.

### Actual result

![Screenshot(6)](https://user-images.githubusercontent.com/43210406/77621070-ba84d600-6f61-11ea-9377-9300c5074f71.png)

**Comment by jitendra-webkul** [comment]
You can add that information in description or in name.
