### ISSUE TITLE
How to add new icon in bagisto admin panel?

### ISSUE THREAD

**Issue by testforpostman7** [bagisto/bagisto#2774]
Hello,

How to add a new icon in bagisto admin panel. Please guide me on how to add a new icon.

Thanks.

**Comment by vaishaliwebkul** [comment]
Hello @testforpostman7 
please let us know where do you want to add a icon? share the screenshot as well.

**Comment by testforpostman7** [comment]
Hello @vaishaliwebkul 

I have to add icons in bagisto admin panel. Please check the screenshot where we have to add a new icon. Please suggest me a solution.
![Selection_001](https://user-images.githubusercontent.com/61349669/77678653-78867f00-6fb7-11ea-9dfb-cacebb435e34.png)


Thanks

**Comment by ghermans** [comment]
@testforpostman7 a article on the [dev docs](https://devdocs.bagisto.com/create_package.html#add-menu) explains this.

**Comment by vaishaliwebkul** [comment]
@testforpostman7
Yes, solution provided by @ghermans is right.

**Comment by vaishaliwebkul** [comment]
@testforpostman7 
No reply since last 10 days so we are assuming that your issue has been resolved.
Please feel free to reopen this issue.

**Comment by aaccxxyy99** [comment]
@ghermans the link give is expired.  do you have another reference?

**Comment by vaishaliwebkul** [comment]
@aaccxxyy99 
You may check this link https://devdocs.bagisto.com/1.x/packages/add_menu_in_admin.html

**Comment by aaccxxyy99** [comment]
@vishal-webkul  can we add our own icon to admin panel?

**Comment by BzayBst** [comment]
Add icon in shipments methods how can we do it.

**Comment by nuwanchamp** [comment]
If you need to use a new Icon, listen to the bagisto render event "bagisto.admin.layout.head" and hook your admin styles to it
```
Event::listen('bagisto.admin.layout.head', function($viewRenderEventManager) {
            $viewRenderEventManager->addTemplate('template::admin.layouts.style');
  });
```
