### ISSUE TITLE
Issue in customer profile dropdown.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2778]
# Bug report

### Title
Issue in customer profile dropdown.
### Issue Description
Issue in customer profile dropdown.

### Preconditions

    1. framework Version.1.1.

### Steps to reproduce

    1. step1-Sign in
    2. step2- Click on welcome dropdown.

### Expected result
User should not need to scroll down to use option.
### Actual result

Need ro scroll to see other option

![Screenshot (25)](https://user-images.githubusercontent.com/45203177/77722716-8d453000-7014-11ea-8b97-9845f6b31d0f.png)

**Comment by vaishaliwebkul** [comment]
fixed
