### ISSUE TITLE
Issue on checkout page, email should ask first as in default theme.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2779]
# Bug report

### Title
Issue on checkout page, email should ask first as in default theme.
### Issue Description
Issue on checkout page, email should ask first as in default theme.

### Preconditions

    1. framework Version.-1.1.0

### Steps to reproduce

    1. step1- During checkout enter email of existing account
    2. step2- Check, it ask for password just after company field

### Expected result
Email should ak first
### Actual result

![Screenshot (21)](https://user-images.githubusercontent.com/45203177/77723990-dfd41b80-7017-11ea-8b20-0b43c4663625.png)

**Comment by vaishaliwebkul** [comment]
Not fixed Yet, Now passwords is not asking for the existing customer in guest_checkout page in velocity theme

here is default theme
![Screenshot(4)](https://user-images.githubusercontent.com/43210406/78574787-23186080-7848-11ea-949c-6f77aa3108c3.png)

velocity theme,
![Screenshot(5)](https://user-images.githubusercontent.com/43210406/78574880-42af8900-7848-11ea-9706-ab9d346fab8a.png)

**Comment by vaishaliwebkul** [comment]
fixed https://prnt.sc/rvxtd9
