### ISSUE TITLE
Sidebar layout issue.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2780]
# Bug report

### Title
Sidebar layout issue.
### Issue Description
Sidebar layout issue.
### Preconditions

    1. framework Version.-1.1.0

### Expected result
Layout should be proper
### Actual result

![Screenshot (26)](https://user-images.githubusercontent.com/45203177/77724938-2b87c480-701a-11ea-9caf-4853d06ae6e3.png)

**Comment by vaishaliwebkul** [comment]
fixed
