### ISSUE TITLE
Mobile menu is not showing correct sub-menu

### ISSUE THREAD

**Issue by amit-viacon** [bagisto/bagisto#2781]
# Bug report

### Issue Description
If I expand one menu item, collapse and then again expand another item on the menu it will still show the sub-menu of the previous one.

### Preconditions
Tested on the latest copy
    1. Commit id: 6902057

### Steps to reproduce
    1. Expand menu item on the mobile side panel
    2. Collapse and expand another menu item

### Expected result
Show the sub-menu of the clicked menu item

### Actual result
Shows the sub-menu of the previous menu item

**Comment by shubhwebkul** [comment]
Hi @amit-viacon ,
 - please share screenshot and mention which version you are using.

Also, try after clearing cache of browser.

thanks!

**Comment by shubhwebkul** [comment]
Feel free to reopen this issue if you are still facing, as we are not facing such issue and query is  resolved on [forum](https://forums.bagisto.com/topic/1282/mobile-navigation-menu-is-not-showing-up/14) as well.

thanks!
