### ISSUE TITLE
No Am/Pm option in timepicker fields in booking product

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2782]
# Bug report

### Title
No Am/Pm option in timepicker fields in booking product

### Issue Description
No Am/Pm option in timepicker fields in booking product

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Edit booking product, select time

### Expected result
  While select time, AM/PM time format should be available

### Actual result
 While select time, AM/PM time format should be available
![Screenshot(2)](https://user-images.githubusercontent.com/43210406/77728648-ecaa3c80-7022-11ea-8238-cd61bbd244b5.png)

**Comment by rahulcs0082** [comment]
HI @vaishaliwebkul 

This is 24 hrs format so in this one , there is no need of AM or PM.
