### ISSUE TITLE
Product channel and locale dropdowns in the admin dashboard not working

### ISSUE THREAD

**Issue by bugsworld85** [bagisto/bagisto#2789]
# Bug report

### Product channel and locale dropdowns in the admin dashboard not working
**when you create 2 channels and move products to different channels, the "All" should mean all. And its not doing that.** 

### Issue Description
**I'll make this short, the channel dropdown, if it's `All`, it does not show anything. Same goes to the Locale dropdown, `All` does not work either**

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. login to admin dashboard
    2. go to Catalog->Products
    3. If you don't have products, add probably 2 with different channels each
    4. Try changing the dropdowns right beside the title "Products", you'll see what I mean.

**Comment by rahulcs0082** [comment]
HI @bugsworld85 

This issue has been fixed, kindly take pull from the master branch.
