### ISSUE TITLE
Minicart disable when use new languages only velocity theme

### ISSUE THREAD

**Issue by psasquatch** [bagisto/bagisto#2790]
# Bug report

### Title
Minicart disable when use new languages only velocity theme

### Issue Description
Minicart disable when use new languages only velocity theme
English language is ok

### Preconditions
1. framework Version- master

### Steps to reproduce
1. step1- add a new locale
2. step2- select this locale in channel
3. step3- reload the velocity theme
4. step4- deselect that locale from channel again
5. step5- Now check the shop view

![screenshot (1)](https://user-images.githubusercontent.com/62790264/77821019-0f9e2480-70e7-11ea-9300-9959e798d907.png)
![annotazione-2020-03-27-144432 (1)](https://user-images.githubusercontent.com/62790264/77821020-1036bb00-70e7-11ea-9acb-db3ce3d6a543.jpg)
![annotazione-2020-03-27-144511 (1)](https://user-images.githubusercontent.com/62790264/77821021-10cf5180-70e7-11ea-959e-74889b4ba58c.jpg)

**Comment by vaishaliwebkul** [comment]
@psasquatch 
Hope the issue is resolve for you.
No response from the last 1month so we are closing this ,Feel free to reopen if still exist.
