### ISSUE TITLE
Something I think about channel and locale

### ISSUE THREAD

**Issue by 0xuhe** [bagisto/bagisto#2791]
I think the locale should used for change language only, not select products by language right now.

eg: I have a product with English and French informations. If my browser language is French or my ip from France, I should be redirected to French product page(http://shop.com/fr/sample-product), otherwise I should be see the page(http://shop.com/sample-product) with default language, that is English.

At the catalog page, I should see all the products in selected channel. If I prefer French language, I should see the products with French informations, if the French informations are missing, I should see the fallback English informations. Cause I create this product with default language ,English , already.

So maybe you could see two languages on one page, but that's not a big deal, it reminds administrator and custom to change language .

As for channel, I don't know what it does right now. It has hostname when it created, but I don't know where it works

**Comment by jitendra-webkul** [comment]
Bagisto localization system don't work that way but this can be done with customization
