### ISSUE TITLE
Weight Validation Inconsistencies

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#2792]
Weight Validations differ between Simple and Configurable Products but should be consistent across the application.

Steps to Reproduce:
1. Create a new Simple Product.
2. Weight is validated as numeric.
3. Create a new Configurable Product.
4. Under variants, Weight is validated as numeric > 0.0001.

**Comment by vaishaliwebkul** [comment]
@richmondnursery 
This issue has been fixed, If you're still getting same issue feel free to reopen.
