### ISSUE TITLE
Stock Check Incorrect for Configurable Items

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#2793]
# Bug report

### Title
Stock checking incorrect for configurable items.

### Issue Description
When viewing a configurable item in the store front, it is always shown In Stock even if all variants have inventory levels of zero.

### Preconditions
    1. framework Version - master

### Steps to reproduce

    1. Log into admin
    2. Catalog->Add Product
    3. Select Product Type->Configurable
    4. Save Product and continue
    5. Under Variants create 1 or more with inventory as zero. Ensure status is enabled/visible.
    6. Save Product
    7. Visit the store front and view the product.

### Expected result
Viewing a configurable item with no inventory should display "Out Of Stock".

### Actual result
The configurable item shows "In Stock" even if all variants have zero stock.

When the view calls $product->haveSufficientInventory(1) it should return true for items in-stock or the setting of config->backorders. Configurable products always return true regardless of inventory levels of the variants.

**Comment by richmondnursery** [comment]
That fix didn't work for me. I used the following in Type/Configurable.php which may or may not be correct but seems to address the In Stock/Out of Stock as well as enabling the cart/buy buttons:

```
public function haveSufficientQuantity($qty)
{
  $backorders = core()->getConfigData('catalog.inventory.stock_options.backorders');
                
  foreach ( $this->product->variants as $variant )
  {
	if ( $variant->haveSufficientQuantity( $qty ) ) return true;
   }        		

   return $backorders;
}

public function isSaleable()
{
   foreach ( $this->product->variants as $variant )
   {
    	if ( $variant->isSaleable() ) return true;
    }
    	
    return false;
}
```

**Comment by rahulcs0082** [comment]
HI @richmondnursery 

I did not know, why it is not working for you but your way seems more perfect.
I have implemented it.

**Comment by vaishaliwebkul** [comment]
@richmondnursery 
Hope the above solution worked for you.
No response from the last 27 days so we are closing this now, Feel free to reopen if still exist
