### ISSUE TITLE
When allow backorder is enabled, display a message available for order rather than in stock.

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#2794]
When Allow Backorders is configured, items with no stock still display as In Stock. Alternatively, it would be nice to display a message if it's not in stock but available.

I made the following change to packages/Webkul/Shop/src/Resources/views/products/view/stock.blade.php and added an approproate field in my lang file:

`--   {{ $product->haveSufficientQuantity(1) ? __('shop::app.products.in-stock') : __('shop::app.products.out-of-stock') }}`

`++        @if ( $product->haveSufficientQuantity(1) === true )`
`++                {{ __('shop::app.products.in-stock') }}`
`++        @elseif ( $product->haveSufficientQuantity(1) > 0 )`
`++               {{ __('shop::app.products.pre-order') }}`
`++        @else`
`++	                {{ __('shop::app.products.out-of-stock') }}`
`++        @endif`

**Comment by rahulcs0082** [comment]
Hi  @richmondnursery 

Thanks for your precious suggestions and way.
We have implemented this one.

**Comment by richmondnursery** [comment]
@rahulcs0082 
Thanks. As I find more tweaks or suggestions, I'll post them here. 
I like to help, but I'm not a great programmer.

**Comment by vaishaliwebkul** [comment]
@rahulcs0082 
Could you please update the **available** tag to **Available For Orders** https://prnt.sc/sgh4gs

**Comment by vaishaliwebkul** [comment]
Fixed https://prnt.sc/shfmbx
