### ISSUE TITLE
Cart error merging if you authenticate having items with low stock

### ISSUE THREAD

**Issue by Triztan** [bagisto/bagisto#2795]
# Bug report

Cart error while merging if you authenticate having items with low stock

### Issue Description
Being "guest" and adding an item for example with 1 item in stock, then you go to checkout and try to login at the checkout page(the checkout page already is handling the authentication with the method in OnepageController, which authenticates you, and then merges the Cart with the "mergeCart" method)
Normally if everything is going well this page will handle a reload of the page so you get the new overview of the cart, that's ok
But, if you do as i described below with a product with only 1 item at stock it will give the following exception:
`Call to a member function update() on null`
It's called at the line 38 of the CartItemRepository
Checking the code from the "mergeCart" method i found that it's because you are already checking if the item have stock enough
```
$cartItem->quantity = $newQuantity = $cartItem->quantity + $guestCartItem->quantity;

if (!$this->isItemHaveQuantity($cartItem)) {
    $this->cartItemRepository->delete($guestCartItem->id);

    continue;
 }
```
The issue is, quantity is updated with the number of items you had in the cart before you authenticated and it adds the number of items you had also in your personal cart(i could simply try to purchase yesterday and then i decided to wait to buy tomorrow or something like that)
In the end, it's requiring 2 items in stock, as the "isItemHaveQuantity" is checking if i have enough stock it will be deleted, and then in the next lines
```
$this->cartItemRepository->update([
     'cart_id' => $cart->id,
], $guestCartItem->id);
```
So you are trying to update the item which was deleted already

I can create a pull request with a fix if needed

**Comment by rahulcs0082** [comment]
Hi @Triztan 

Your concern is absolutely right, we are getting this issue.
You can freely create a PR for this one as it is an open-source project.

**Comment by rahulcs0082** [comment]
Hi @Triztan 

This issue has been fixed, you can take a pull from master branch.

**Comment by vaishaliwebkul** [comment]
@Triztan 
It's resolved now.

Feel free to reopen this issue anytime if still exist.
