### ISSUE TITLE
Try to create category in windows 10 getting exception

### ISSUE THREAD

**Issue by john7851** [bagisto/bagisto#2796]
# Bug report

### Title
**unable to create a category in windows system.**

### Issue Description
**php version 7.3.1**
**os windows 10**
**bagsito master**

### Steps to reproduce
**install bagisto from master**

    1. login in admin panel
    2. try to create a category

### Expected result
**category should be created.**

### Actual result

>    **Tell us what happens instead.**

* getting exception
![Screenshot](https://user-images.githubusercontent.com/34475818/77825879-1605be00-7132-11ea-9d59-461fff438bdd.png)

**Comment by vaishaliwebkul** [comment]
Hi @john7851 

refer this issue for same
https://github.com/bagisto/bagisto/issues/2562

**Comment by jitendra-webkul** [comment]
Create db with  utf8_general_ci collation

**Comment by shubhwebkul** [comment]
Feel free to reopen this, if you're still facing issue.

Thanks!
