### ISSUE TITLE
Setup error 

### ISSUE THREAD

**Issue by mengheangsok** [bagisto/bagisto#2797]
# Bug report

### Title

In ModelProxy.php line 69:,, Return value of Konekt\Concord\Proxies\ModelProxy::targetClass() must be of, the type string, null returned,,

### Issue Description
this error happen while installing

### Steps to reproduce

    1. setup app 

### Expected result
it should be done successfully and go to home page

### Actual result
In ModelProxy.php line 69:,, Return value of Konekt\Concord\Proxies\ModelProxy::targetClass() must be of, the type string, null returned,,

**Comment by rahulcs0082** [comment]
Hello @mengheangsok 

Can you tell me, which version of bagisto you are using and what is environment details like - OS, PHP and Database.

**Comment by jitendra-webkul** [comment]
I hope your issue got resolved. I am closing this issue for now. Feel free to reopen this issue if needed.

**Comment by flatof** [comment]
Same problem.
Bagisto v2.3.1, Ubuntu 24.04.2 LTS, PHP 8.3.6, MySQL 8.0.41

`root@eshop:~/bagisto# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package paypal/paypal-checkout-sdk is abandoned, you should avoid using it. Use paypal/paypal-server-sdk instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ModelProxy.php line 70:

  Konekt\Concord\Proxies\ModelProxy::targetClass(): Return value must be of type string, null returned


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**Comment by devansh-webkul** [comment]
@flatof,

May I know why you're running composer update here? Please use the provided lock file for the current version and run `composer install` instead.

**Comment by flatof** [comment]
> [@flatof](https://github.com/flatof),
> 
> Могу ли я узнать, почему вы запускаете здесь composer update? Пожалуйста, используйте предоставленный файл блокировки для текущей версии и запустите `composer install`вместо этого.

Commands: composer install, composer dump-autoload, php artisan vendor:publish --all --force, and php artisan optimize:clear.
Output:
`In ModelProxy.php line 70:

  Konekt\Concord\Proxies\ModelProxy::targetClass(): Return value must be of type string, null returned`

**Comment by flatof** [comment]
root@eshop:/opt/eshop# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package paypal/paypal-checkout-sdk is abandoned, you should avoid using it. Use paypal/paypal-server-sdk instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ModelProxy.php line 70:

  Konekt\Concord\Proxies\ModelProxy::targetClass(): Return value must be of type string, null returned


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by flatof** [comment]
Version 2.2.6 don't have this problem.
This problem is only on 2.3

**Comment by devansh-webkul** [comment]
Could you please share the steps you are following? There might be a possibility that you are using an incompatible package.

**Comment by flatof** [comment]
> Could you please share the steps you are following? There might be a possibility that you are using an incompatible package.

1. Installed these packages:
apt update -y && apt upgrade -y && apt install nano -y && apt install mc -y && apt install curl -y && apt install php -y && apt install composer -y && apt install npm -y && apt install mysql-server -y && apt install apache2 -y && apt install php-intl -y && apt install php-gd -y && apt install unzip -y && apt install php-xml -y && apt install php-mysql -y
2. Run: composer create-project bagisto/bagisto
3. Installed Bagisto domain.com/install
4. In the command line after the second run of the command: php artisan vendor:publish --all --force or composer dump-autoload -  error:
`root@eshop:/var/www/html/bagisto# php artisan vendor:publish --all --force

   INFO  Publishing assets.

  Copying directory [vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/views] to [resources/views/errors] ......................... DONE
  Copying directory [vendor/laravel/framework/src/Illuminate/Notifications/resources/views] to [resources/views/vendor/notifications] ......... DONE
  Copying directory [vendor/laravel/framework/src/Illuminate/Pagination/resources/views] to [resources/views/vendor/pagination] ............... DONE
  Copying file [vendor/astrotomic/laravel-translatable/src/config/translatable.php] to [config/translatable.php] .............................. DONE
  Copying directory [vendor/astrotomic/laravel-translatable/src/lang] to [lang/vendor/translatable] ........................................... DONE
  Copying file [vendor/barryvdh/laravel-debugbar/config/debugbar.php] to [config/debugbar.php] ................................................ DONE
  Copying file [vendor/barryvdh/laravel-dompdf/config/dompdf.php] to [config/dompdf.php] ...................................................... DONE
  Copying file [vendor/konekt/concord/config/config.php] to [config/concord.php] .............................................................. DONE
  Copying file [vendor/laravel/octane/config/octane.php] to [config/octane.php] ............................................................... DONE
  Copying directory [vendor/laravel/sanctum/database/migrations] to [database/migrations] ..................................................... DONE
  Copying file [vendor/laravel/sanctum/config/sanctum.php] to [config/sanctum.php] ............................................................ DONE
  Copying file [vendor/maatwebsite/excel/src/Console/stubs/export.model.stub] to [stubs/export.model.stub] .................................... DONE
  Copying file [vendor/maatwebsite/excel/src/Console/stubs/export.plain.stub] to [stubs/export.plain.stub] .................................... DONE
  Copying file [vendor/maatwebsite/excel/src/Console/stubs/export.query.stub] to [stubs/export.query.stub] .................................... DONE
  Copying file [vendor/maatwebsite/excel/src/Console/stubs/export.query-model.stub] to [stubs/export.query-model.stub] ........................ DONE
  Copying file [vendor/maatwebsite/excel/src/Console/stubs/import.collection.stub] to [stubs/import.collection.stub] .......................... DONE
  Copying file [vendor/maatwebsite/excel/src/Console/stubs/import.model.stub] to [stubs/import.model.stub] .................................... DONE
  Copying file [vendor/maatwebsite/excel/config/excel.php] to [config/excel.php] .............................................................. DONE
  Copying file [vendor/prettus/l5-repository/src/resources/config/repository.php] to [config/repository.php] .................................. DONE
  Copying file [vendor/spatie/laravel-responsecache/config/responsecache.php] to [config/responsecache.php] ................................... DONE
  Copying file [vendor/spatie/laravel-sitemap/config/sitemap.php] to [config/sitemap.php] ..................................................... DONE
  Copying directory [vendor/spatie/laravel-sitemap/resources/views] to [resources/views/vendor/sitemap] ....................................... DONE
  Copying directory [vendor/laravel/framework/src/Illuminate/Mail/resources/views] to [resources/views/vendor/mail] ........................... DONE
  Copying file [vendor/diglactic/laravel-breadcrumbs/config/breadcrumbs.php] to [config/breadcrumbs.php] ...................................... DONE
  Copying directory [vendor/diglactic/laravel-breadcrumbs/resources/views] to [resources/views/vendor/breadcrumbs] ............................ DONE
  Copying file [vendor/laravel/tinker/config/tinker.php] to [config/tinker.php] ............................................................... DONE
  Copying file [vendor/openai-php/laravel/config/openai.php] to [config/openai.php] ........................................................... DONE

root@eshop:/var/www/html/bagisto# php artisan vendor:publish --all --force

In ModelProxy.php line 70:

  Konekt\Concord\Proxies\ModelProxy::targetClass(): Return value must be of type string, null returned


root@eshop:/var/www/html/bagisto# php artisan vendor:publish --all --force^C
root@eshop:/var/www/html/bagisto# composer dump-autoload
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ModelProxy.php line 70:

  Konekt\Concord\Proxies\ModelProxy::targetClass(): Return value must be of type string, null returned


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
root@eshop:/var/www/html/bagisto#`

**Comment by flatof** [comment]
> bagisto:install

bagisto:install - works.
bagisto:install works but the problem is that command "php artisan vendor:publish --all --force" shows an error, I need this command to apply changes in the code

**Comment by flatof** [comment]
> Hello there,
> 
> It looks like you're running some additional commands like `vendor:publish --all --force`. Please avoid running any extra commands. Just run bagisto:install and that should be sufficient.

bagisto:install works, but the problem is that command "php artisan vendor:publish --all --force" shows an error, I need this command to apply changes in the code

**Comment by devansh-webkul** [comment]
In 2.x series, we are not using any publishers. Instead --all, publish only the package which you needed.

**Comment by flatof** [comment]
> In 2.x series, we are not using any publishers. Instead --all, publish only the package which you needed.

Thank you, you helped.
