### ISSUE TITLE
If description is different for variants products then that description should display on front-end for that variant.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#280]
Framework Version: 0.1.2

![screenshot 26](https://user-images.githubusercontent.com/45203177/49565181-56916500-f94c-11e8-86df-b75862c1bd2e.png)
![screenshot 27](https://user-images.githubusercontent.com/45203177/49565192-5c874600-f94c-11e8-8000-b993655a7c67.png)

**Comment by jonathanptk** [comment]
Was he going to report this problem now because he was marked invalid? The same error happens with the size variant (as an example).

**Comment by jitendra-webkul** [comment]
Only the main products description will be displayed, only the price and images will be changed if you select any variants.

**Comment by jonathanptk** [comment]
But in my example about size, if my variant has a different size than the default, is it okay to not change it in the view when selecting the variant?
