### ISSUE TITLE
Address with more than 2 lines is not added correctly to the cart_address table

### ISSUE THREAD

**Issue by cagartner** [bagisto/bagisto#2801]
# Bug report

### Title
Address with more than 2 lines is not added correctly to the cart_address table

### Issue Description
Here in Brazil we have 4 lines of address, so when I add a new address in the checkout page the address is added right in the `cart_address` table, but when I already have any address with more than 2 lines created, the address is added wrongly to `cart_address` table:

### Preconditions

    1. Bagisto last version
    2. Configure the qty address lines to 4

### Steps to reproduce

    1. Configure the address lines to 4
    2. Create a user and address in the customer account
    3. Add any product to cart
    4. Go to checkou and select the registered address

### Expected result
Your address needs to be added right in the cart_address table with the \n line breaker:

### Actual result
The address does not get any information:

![image](https://user-images.githubusercontent.com/4007696/77861522-e4e9c400-71eb-11ea-8fc7-e597cff24f0f.png)
![image](https://user-images.githubusercontent.com/4007696/77861534-ed41ff00-71eb-11ea-930d-5e961bf73270.png)
![image](https://user-images.githubusercontent.com/4007696/77861541-f6cb6700-71eb-11ea-8cdc-6fab757b0d66.png)

**Comment by vaishaliwebkul** [comment]
Hi @cagartner 
This issue has been fixed in master, 
you can update the project with master branch.

refernce: https://github.com/bagisto/bagisto/issues/2785

**Comment by vaishaliwebkul** [comment]
@cagartner 
Hope this issue has been resolved for you as well, If you still getting this issue, Feel free to reopen again.
