### ISSUE TITLE
the sku should be all in caps

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2805]
# Bug report

### Title
the sku should be all caps.

### Issue Description
the product sku should be all caps. 
PRST-0507 is an example of an SKU which should be acceptable in same format.

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1
    2. step2

### Expected result

SKU should save in caps , also accept hypen -

**Comment by baijii** [comment]
At my company, SKU are using lowercase characters. As both are common, the validation should allow both, lower and uppercase.

**Comment by AnnikaWolff** [comment]
The same here. And please consider [this comment](https://github.com/bagisto/bagisto/pull/2907#issuecomment-624455441) as well.
