### ISSUE TITLE
Illegal mix of collations

### ISSUE THREAD

**Issue by senbai** [bagisto/bagisto#2807]
# Bug report

### Illegal mix of collations
Bagisto Version: 0.1.0

when i'm adding a new category with position 2 and a parent category.
i got this issue 
`SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update `categories` set `_lft` = case when `_lft` >= 16 then `_lft`+2 else `_lft` end, `_rgt` = case when `_rgt` >= 16 then `_rgt`+2 else `_rgt` end where (`_lft` >= 16 or `_rgt` >= 16))`

Any Help with that, i will be appreciated
Thanks in advance.

**Comment by rahulcs0082** [comment]
Hi @senbai 

Create db with utf8_general_ci collation or follow this one - https://github.com/bagisto/bagisto/issues/2562

**Comment by shubhwebkul** [comment]
Feel free to reopen this, if you are still facing issue.

**Comment by Aziz-tripleA** [comment]
> Hi @Senbai
> 
> Create db with utf8_general_ci collation or follow this one - #2562

after changed my db collation still this error

**Comment by devansh-webkul** [comment]
Hi @Aziz-tripleA,

Its `utf8_unicode_ci`.

**Comment by Aziz-tripleA** [comment]
> Hi @Aziz-tripleA,
> 
> Its `utf8_unicode_ci`.

before i change it yes  `utf8_unicode_ci`

**Comment by devansh-webkul** [comment]
Hi @Aziz-tripleA,

This is a very old thread, I suggest you try the latest version with ` utf8_unicode_ci`.
