### ISSUE TITLE
Correct the spelling on registration page.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2808]
# Bug report

### Title
Correct the spelling on registration page.

### Issue Description
Correct the spelling on registration page.

### Preconditions

    1. framework Version.- master
    
### Steps to reproduce

    1. step1- Go to sign up page in velocity theme.
    
### Expected result
It should be glad.

### Actual result
![Screenshot (86)](https://user-images.githubusercontent.com/45203177/78107142-8bafa980-7412-11ea-972d-d63c0477b1be.png)

**Comment by vaishaliwebkul** [comment]
fixed
