### ISSUE TITLE
getting timezone error while setup 

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2812]
# Bug report

### Title
getting timezone error while setup 

### Issue Description
getting timezone error while setup 

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- setup the latest bagisto
    2. step2- run the command php artisan config:cache

### Actual result

>   C:\Bitnami\wampstack-7.4.3-1\apache2\htdocs\bagisto>php artisan config:cache
Configuration cache cleared!

In LoadConfiguration.php line 49:

  date_default_timezone_set(): Timezone ID '' is invalid

**Comment by the-hardik-sisodia** [comment]
configure your .env

APP_TIMEZONE=Asia/Kolkata

**Comment by vaishaliwebkul** [comment]
fixed.
Thanks @rahulcs0082 & @the-hardik-sisodia.
