### ISSUE TITLE
Ui issue if there is only one product in compare page.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2813]
# Bug report

### Title
Ui issue if there is only one product in compare page.

### Issue Description
Ui issue if there is only one product in compare page.

### Preconditions

    1. framework Version- 1.1.0

### Steps to reproduce

    1. step1- Add only one product in compare page.

### Expected result
Name and description should be visible properly

### Actual result
![Screenshot (92)](https://user-images.githubusercontent.com/45203177/78125246-62047b80-742e-11ea-825b-8ba9424f1c98.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
This issue has been fixed in master.

**Comment by jyoti-webkul** [comment]
ok
