### ISSUE TITLE
variant product's name aren't update when select their options in Front

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2814]
# Bug report

### Title
variant product's name aren't update when select their options in Front

### Issue Description
variant product's name aren't update when select their options in Front

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add configurable product with at least having 2 options
    2. step2- now from the product page, select any variant
    3. step3- observe that selected variant option name is not replace with product name

### Expected result
 when select config variant options, related product's name should update

### Actual result
  
![Screenshot(1)](https://user-images.githubusercontent.com/43210406/78134166-52d8fa00-743d-11ea-84eb-56cada5d0ea2.png)

**Comment by richmondnursery** [comment]
Should stock levels also update? Maybe easy to implement at the same time as product name update.

**Comment by vaishaliwebkul** [comment]
@richmondnursery 
Currently, stock level will not update, if the stock is unavailable then that variant will removed from the option list.
But this idea is good to show the inventory stock level at frontend instead of removing options.

**Comment by richmondnursery** [comment]
True, but if you allow backorders on your site, then variants are not removed from the option list. In such case you can have some variants in stock and others on backorder.
