### ISSUE TITLE
Not able to view menu in velocity theme on storefront

### ISSUE THREAD

**Issue by soodankush** [bagisto/bagisto#2818]
# Bug report

### Title
Hi,
I am not able to view the menu in the velocity theme on the storefront.

### Issue Description
In the default theme, I am able to view the menu but not in the velocity theme.

### Actual result

Menu not displayed

![image](https://user-images.githubusercontent.com/12609531/78256042-b0407a00-7515-11ea-9895-6d5398e6c714.png)

**Comment by shubhwebkul** [comment]
Hi @soodankush ,
Could you please mention that about which menu are you talking ?

**Comment by soodankush** [comment]
The categories which have been shown in the navbar. I have added categories but does not display on the navbar.

**Comment by soodankush** [comment]
![image](https://user-images.githubusercontent.com/12609531/78333822-32797e80-75a8-11ea-86ae-faae028d55f4.png)
In the image, you can see wires category is present but does not display on the navbar

**Comment by shubhwebkul** [comment]
Hi @soodankush ,
This [navbar](https://prnt.sc/rs5ayt) is for header content in velocity. You could set navbar content by adding content in
->admin->velocity->header content -> add content

Navbar doesn't show categories in there, although you could set url to the category there but at the end you need to set it manually.

thanks!

**Comment by soodankush** [comment]
Thanks! Issue has been resolved
