### ISSUE TITLE
Template overrides not working properly since upgrading to 1.1.0

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#2819]
I have a theme in "resources/themes/newtheme/views/<all the view files>" with all the files from the Shop package and the following email include gives an error that the file cannot be found: @include ('shop::emails.layouts.footer'). The problem is that some files are not being found while some are as the following is found: @include ('shop::emails.layouts.logo').

File that exist are not being overridden by file is my new theme folder.

**Comment by prateek-webkul** [comment]
Hey @emperorjm ,

Within shop package, there is no any file at the path you included in your theme folder i.e., @include ('shop::emails.layouts.footer') . And, it may be because you may have created that file in core and after upgrading that file has been lost.

Thanks

**Comment by emperorjm** [comment]
Hi @prateek-webkul. I am having the issue with other templates as well. For example the **"Cancel Order"** email template at "resources/themes/newtheme/views/emails/sales/order-cancel.blade.php" is not being used but instead, the "packages/Webkul/Shop/src/Resources/views/emails/sales/order-cancel.blade.php" is being used but the other sales email templates are being overridden just fine.

**Comment by prateek-webkul** [comment]
@emperorjm ,
We're looking regarding this & will update you soon.

Thanks.

**Comment by prateek-webkul** [comment]
Hii @emperorjm,

**Comment by prateek-webkul** [comment]
Hi @emperorjm ,

For overriding the "Cancel Order" email template, you need to define the order-cancel file at root path as "resources/views/vendor/shop/emails/sales/order-cancel.blade.php".

**Comment by shubhwebkul** [comment]
Feel free to reopen if you still face this issue.
