### ISSUE TITLE
Add a validation that weight of product should be numeric only. Also add measure of weight (kg,gm or lbs)

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#282]
Framework Version: 0.1.2

![screenshot 29](https://user-images.githubusercontent.com/45203177/49569089-f48b2c80-f958-11e8-90ee-e1d232cf4272.png)

**Comment by jitendra-webkul** [comment]
Validation can be added from the attribute validation section

![screenshot from 2018-12-06 13 38 37](https://user-images.githubusercontent.com/39991107/49570383-8c3e4a00-f95c-11e8-8082-66deff9f4bdd.png)
