### ISSUE TITLE
Address Line is Null in Emails

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#2821]
Bagisto Version: 1.0.0+

When an order is executed, invoice or shipping generated the address line 1 is coming back blank.

I've traced the issue to when the Address is selected in check out and saved the call to add the address to the Cart in "**packages/Webkul/Checkout/src/Cart.php**" function **"gatherBillingAddress"** uses an array_merge that overwrites the address 1 value with an empty value.

**Comment by shubhwebkul** [comment]
Hi @emperorjm ,
Yes we got that issue and it has already been resolved in master branch.

Thanks!
