### ISSUE TITLE
set login on mobile number for costumer

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#2822]
hi , i want to know if there is any way to add login with mobile for costumer i have added mobile field to the table but from login what i see is this :
```
   if (! auth()->guard('customer')->attempt(request(['email', 'password']))) {
            session()->flash('error', trans('shop::app.customer.login-form.invalid-creds'));

            return redirect()->back();
        }
```
can you please describe how it logs in user and how can i change that to mobile field instead of email ?? thanks

**Comment by rahulcs0082** [comment]
Hi @farshadff

You can follow the given article for this one -
https://www.twilio.com/blog/implement-account-verification-login-by-phone-laravel-php
https://medium.com/@jagadeshanh/laravel-5-4-login-with-email-or-phone-cac9a3855cda

To implement this one, you may need to override the same views and route, then change it 
in your package and call your controller corresponds to the route.

**Comment by farshadff** [comment]
@rahulcs0082 thanks for your answer but my problem was i didnt find the login controller to change the `credentials` trait i thout maybe u use some special way to login or some how changed that so i should know where to look for 
```
protected function credentials(Request $request)
```
instead of login controller . thanks for your answer

**Comment by rahulcs0082** [comment]
HI @farshadff 

You can use the below function for login with mobile.
`     
 
        if (! auth()->guard('customer')->attempt(request(['phone', 'password']))) {
            session()->flash('error', trans('shop::app.customer.login-form.invalid-creds'));

            return redirect()->back();
        }

        if (auth()->guard('customer')->user()->status == 0) {
            auth()->guard('customer')->logout();

            session()->flash('warning', trans('shop::app.customer.login-form.not-activated'));

            return redirect()->back();
        }

        if (auth()->guard('customer')->user()->is_verified == 0) {
            session()->flash('info', trans('shop::app.customer.login-form.verify-first'));

            Cookie::queue(Cookie::make('enable-resend', 'true', 1));

            Cookie::queue(Cookie::make('email-for-resend', request('email'), 1));

            auth()->guard('customer')->logout();

            return redirect()->back();
        }

        //Event passed to prepare cart after login
        Event::dispatch('customer.after.login', request('phone'));

        return redirect()->intended(route($this->_config['redirect']));
`
Now , override the login viw file and pass mobile number instead of email.

**Comment by farshadff** [comment]
actually i did that but didnt work i will try it again . thanks for the answer 👍

**Comment by jitendra-webkul** [comment]
I am closing this issue, I hope your issue get resolved. Feel to open any time.

**Comment by cakeph** [comment]
is this issue resolve i need the same

**Comment by vaishaliwebkul** [comment]
@cakeph 
you need to implement it if you want this feature as instructed above.
You may also buy this plugin https://bagisto.com/en/extensions/laravel-ecommerce-login-by-mobile-number
