### ISSUE TITLE
PHP Notice: 

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2825]
PHP Notice:  date_default_timezone_set(): Timezone ID '' is invalid in /var/www/html/bagisto-1.1.0/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 49

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by vaishaliwebkul** [comment]
Hi @marcelowu 
issue fixed in master.

refernce https://github.com/bagisto/bagisto/issues/2812
