### ISSUE TITLE
Not able to view cart icon

### ISSUE THREAD

**Issue by soodankush** [bagisto/bagisto#2826]
I am not able to view cart icon on frontend

**Comment by vaishaliwebkul** [comment]
@soodankush 
Describe the bagisto version and some screenshots of the issue where the cart icon is not visible.

**Comment by soodankush** [comment]
@vaishaliwebkul

It is in the version 1.1.0 . I have removed that version from my laptop

**Comment by vaishaliwebkul** [comment]
@soodankush 
Please describe the issue in details, if it's not install then kindly re-install to verify the issue.

Thanks.

**Comment by soodankush** [comment]
Ok I will add the screenshot.
