### ISSUE TITLE
currency change error on velocity theme 

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#2828]
ok so when i make the currency For Iranian rial like below :
![2020-04-05_12-44-35](https://user-images.githubusercontent.com/17511289/78470013-3be72000-773b-11ea-9a42-2ad54b1b79a0.jpg)
and when i change the default channel currency to be `rial` the store gives this error : 
```
Trying to get property 'code' of non-object (View: C:\wamp64\www\vnicolas\resources\themes\velocity\views\UI\header.blade.php) (View: C:\wamp64\www\vnicolas\resources\themes\velocity\views\UI\header.blade.php) (View: C:\wamp64\www\vnicolas\resources\themes\velocity\views\UI\header.blade.php) (View: C:\wamp64\www\vnicolas\resources\themes\velocity\views\UI\header.blade.php)
```

**Comment by zakybaraq** [comment]
Same here, please help

**Comment by sathishpurumani** [comment]
@farshadff same error here, please help.

**Comment by vaishaliwebkul** [comment]
@sathishpurumani 

try to select all the currency in channel->currency https://prnt.sc/sl1g2x

**Comment by haljeshi** [comment]
Same issue with me.
No matter how many currencies I select in the default channel, if USD is not one of them, I will receive the same error.

**Comment by andrewdaluz** [comment]
You must clean the browser caches/session and the reload the page. Try acessing it trough incognito tab first so you can see it working.
I hope it helps.

**Comment by Deepanjali-Singh** [comment]
> @sathishpurumani
> 
> try to select all the currency in channel->currency https://prnt.sc/sl1g2x

I selected all the currencies in the channel and selected my default as INR, but the frontend displays USD only
![image](https://user-images.githubusercontent.com/40621333/90857855-a45d3380-e3a2-11ea-8f44-de3dfb40d0f7.png)

**Comment by vaishaliwebkul** [comment]
@Deepanjali-Singh 
try to check in the incognito mode.
