### ISSUE TITLE
Illegal mix of collations

### ISSUE THREAD

**Issue by vasudevanEP** [bagisto/bagisto#2832]
Hi 
While creating new categroies from the admin panel im getting the error.
![image](https://user-images.githubusercontent.com/12250861/78540116-4542bc00-7811-11ea-95df-7d6c63669577.png)

Please find the image for your information

**Comment by prateek-webkul** [comment]
Hi @vasudevanEP

Create db with utf8_general_ci collation or follow this one - [#2562](https://github.com/bagisto/bagisto/issues/2562)

Thanks

**Comment by vasudevanEP** [comment]
Thank you got fixed
