### ISSUE TITLE
how to get the custom attribute in product cart

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#2836]
hi ,   i added a custom attribute in products named `discount` i want operator to be able to set a discount amount for configurable product as long as its not possible to set an static number for it and i want to label that in front end home page in card i wonder to know how can i access that because i am only having `product` in the card not the relationship which is the `attribute` . thanks

**Comment by rahulcs0082** [comment]
Hello @farshadff 

From the cart, you can get the model of the product and using this one you can get the attribute family for the given product (e.g `$product->attribute_family`).

Now using this, you can get all attributes for the given family.

**Comment by farshadff** [comment]
@rahulcs0082  thanks for the , saying from cart means user must add it to card first or i get that wrong ??? because i want to show it in home page products and before user adds them in cart . i will try what you said . thanks

**Comment by rahulcs0082** [comment]
Hi @farshadff 

Without adding it to the cart, you can achieve this as products are used to show on the home page using the product model and you can get its attribute family and then all attributes for product.

**Comment by farshadff** [comment]
thanks for the help but 1 more question . i have added one attribute named `homediscount` to the default family and using this in product now i inter to achive it like below :
```
    @dd($product->attribute_family->homediscount)
```
it returns null . i have dont any thing wrong ?

**Comment by rahulcs0082** [comment]
Hi @farshadff 

use this one -  

`$product->attribute_family->getCustomAttributesAttribute() `

It will return all attributes for the given product.

**Comment by jitendra-webkul** [comment]
I hope above reply solved your issue. I am closing this issue for now. Feel free to reopen this issue if needed.

**Comment by farshadff** [comment]
@jitendra-webkul  thanks for the notice i forgot to update post i got the attribute but actually what i was looking for was the value of that . i am trying to get that and post it here so others may use it
