### ISSUE TITLE
Velocity theme is not available on fresh install

### ISSUE THREAD

**Issue by manatech** [bagisto/bagisto#2840]
# Bug report

### Title
**I can not find the Velocity theme on fresh install**
**I have a fresh bagisto installation. But I can not see the Velocity option when I go to the edit channel page. I'm not sure if that is a bug or I am doing something wrong. I followed the steps provided in docs**

**Comment by vaishaliwebkul** [comment]
@manatech 
which bagisto version you are trying to be install?
Also please tell us steps you follow while installation.

Also make sure you have run the below command to load configurations:-

- run composer dump-autoload

- php artisan vendor:publish --force

- php artisan config:cache

**Comment by manatech** [comment]
I am using composer to create the project
composer create-project bagisto/bagisto
Then going through the following steps (Running on localhost):
```
php artisan migrate
php artisan db:seed
php artisan vendor:publish
composer-dump-autoload
```

**Comment by shubhwebkul** [comment]
what directories do you have under resources -> themes ?
