### ISSUE TITLE
adding the bulk discount amount on configurable product

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#2842]
hi , 
in configurable product it would be very nice if we can add a field next to price for each product to set the discount for it for a limit amount of time or permanently , actually  i am trying to add it if i got to the point i would make a pull request about it .

**Comment by shubhwebkul** [comment]
Hey @farshadff 
We will surely look into this and that would be great if you do PR otherwise we'll look into this feature.

Thanks! 
Happy Coding ;)

**Comment by jitendra-webkul** [comment]
@farshadff You can create cart rule or catalog for discount purpose.  This feature is already exist in our system. I am closing this issue for now, feel free to reopen if needed.
