### ISSUE TITLE
Implement custom RegistrationController

### ISSUE THREAD

**Issue by manatech** [bagisto/bagisto#2845]
Hi.
How can I implement my own RegisterationController and replace it with the default Bagisto's Controller without touching the core?

**Comment by ghermans** [comment]
You can create a custom package for this https://devdocs.bagisto.com/create_package.html#how-to-create-package

**Comment by rahulcs0082** [comment]
Hi @manatech 

As @ghermans suggested, create your package and in this package, create the same name route which calls your controller.
By this way, your controller will be called for the given route.
