### ISSUE TITLE
Class 'Faker\Factory' not found 

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#2847]
Bagisto: version 1.1.0

In Bagisto v1.0.0 the faker class was a part of the require section in the composer.json file now it has been moved to the require-dev section which in my mind should be the correct setting for production environments but there is a Helper file in the CORE package that uses the Faker class for some reason (packages/Webkul/Core/src/Helpers/Laravel5Helper.php).

**Comment by rahulcs0082** [comment]
Hi @emperorjm 

We have reverted this these dependency.
Thanks for notifying us.

**Comment by vaishaliwebkul** [comment]
@emperorjm 
We are closing this issue. Feel free to reopen this bug if not resolved
Thanks.
