### ISSUE TITLE
Can not add my stylesheet to Velocity theme

### ISSUE THREAD

**Issue by manatech** [bagisto/bagisto#2849]
Hi. I am following the guides in this link to implement a HelloWorld package:
https://devdocs.bagisto.com/create_package.html#how-to-create-package

When I use the following code to add the stlesheeto to admin template everything is OK (HelloWorldServiceProvider.php):

```
use Illuminate\Support\Facades\Event;
public function boot()
{
    Event::listen('bagisto.admin.layout.head', function($viewRenderEventManager) {
        $viewRenderEventManager->addTemplate('helloworld::helloworld.layouts.style');
    });
}
```

But when I change the code to use velocity temmplate the page does not load completely:

```
public function boot()
{
    Event::listen('bagisto.shop.layout.head', function($viewRenderEventManager) {
        $viewRenderEventManager->addTemplate('helloworld::helloworld.layouts.style');
    });
}
```

Here is my /views/helloworld/helloworld.blade.php :
```
@extends('shop::layouts.master')
@section('full-content-wrapper')
<h1>Hello World</h1>
@endsection
```

**Comment by manatech** [comment]
I noticed that when the following code causes the shop.css file to crash.
```
Event::listen('bagisto.admin.layout.head', function($viewRenderEventManager) {
        $viewRenderEventManager->addTemplate('helloworld::helloworld.layouts.style');
    });
```
when I navigate to other pages everything is OK but in case of http://localhost:8000/hello-world the rendered page tries load shop.css file from a wrong location. Actually I should get:
`<link rel="stylesheet" href="http://localhost:8000/themes/default/assets/css/shop.css">`
But I am getting:
`<link rel="stylesheet" href="http://localhost:8000/css/shop.css">`

**Comment by shubhwebkul** [comment]
Hello @manatech 
If you're trying to access theme, you should after following:-

 - provide middleware to your routes
`Route::group(['middleware' => ['theme']], function () { 
    Route::get('/hello-world', 'Webkul\TestPackage\Http\Controller\HelloWorldController@helloWorld')
        ->defaults('_config', [
            'view' => 'test::shop.index'
        ]);
});`

 - Your view files should be under directory: - `Resources/views/shop/theme_name/index.blade.php`

[This](https://github.com/shubhwebkul/TestPackage) could also help.

This must resolve your issue, get back to us with your response.
Thanks!

**Comment by manatech** [comment]
Thank you. But now there is another problem. this approach causes duplication of velociy.css file. Now I see this two times in the header:
<link rel="stylesheet" href="http://127.0.0.1:8000/themes/velocity/assets/css/velocity.css">

I wonder why this problem is not occur when attaching the css to admin template. It can attach any style to the admin template without a single modification.

**Comment by shubhwebkul** [comment]
@manatech , Have you tried installing [this](https://github.com/shubhwebkul/TestPackage) package ?

**Comment by manatech** [comment]
Thank you. Your package  works like a charm but when using a non-english locales it gives me this error:
"Trying to get property 'locale_image' of non-object (View: \resources\themes\velocity\views\UI\header.blade.php)

**Comment by shubhwebkul** [comment]
Feel free to reopen this if you're still facing issue.

Thanks!
