### ISSUE TITLE
admin crash on save configration

### ISSUE THREAD

**Issue by Mohammedalasaad** [bagisto/bagisto#2850]
# Bug report

### Title
Admin crash once we save general settings.

### Issue Description
if you try to save the admin settings.. on this page: 
/admin/configuration/general/general , The whole site crash.. 

```
Open: /home/bagisto/packages/Webkul/Core/src/Repositories/CoreConfigRepository.php
 /**
     * @param  array  $formData
     * @param  string  $method
     * @return array
     */
    public function recuressiveArray(array $formData, $method) {
        static $data = [];
```

"Argument 1 passed to Webkul\Core\Repositories\CoreConfigRepository::recuressiveArray() must be of the type array, string given, called in /home/bagisto/packages/Webkul/Core/src/Repositories/CoreConfigRepository.php on line 37 ◀"
![Screenshot 2020-04-08 at 22 14 32](https://user-images.githubusercontent.com/48674512/78829314-66103a80-79e6-11ea-8601-248ef2e85353.png)

Not sure really if this fix it.. But I check and I can see we pass 'q' to the function recuressiveArray and its string.. thats why its crash.. I added this code to unset the 'q' and I think its working now.. 

Any one could check it... I could push this but would be good to know how to do if this fix the problem :)

 ```
  if ($data['locale'] || $data['channel']) {
           $locale = $data['locale'];
           $channel = $data['channel'];

           unset($data['locale']);
           unset($data['channel']);
           unset($data['q']);      <===== This how I unset the q.
        }
```

Regards

**Comment by rahulcs0082** [comment]
Hello @Mohammedalasaad 

Can you tell me which version of bagisto you are using and what is your environment as we are not getting this issue?

**Comment by Mohammedalasaad** [comment]
Hi @rahulcs0082 
Running v1.1.0 , and Iam using laravel/homestead box https://app.vagrantup.com/laravel/boxes/homestead

php artisan bagisto:version
v1.1.0

<img width="756" alt="Screenshot 2020-04-10 at 11 09 43" src="https://user-images.githubusercontent.com/48674512/78979289-d5d41180-7b1b-11ea-9343-15e558fbe327.png">

**Comment by SpareShade** [comment]
I can second that...
It is the "q" index of the payload that, as far as I can see, is always a string.
eg. ```[q] => /admin/configuration/sales/paymentmethods```

This is the payload sent when "Saving" the Configuration
```
Array
(
    [sales] => Array
        (
            [paymentmethods] => Array
                (
                    [cashondelivery] => Array
                        (
                            [title] => Cash On Delivery
                            [description] => Cash On Delivery
                            [active] => 1
                            [sort] => 1
                        )

                    [moneytransfer] => Array
                        (
                            [title] => Money Transfer
                            [description] => Money Transfer
                            [active] => 1
                            [sort] => 2
                        )

                    [paypal_standard] => Array
                        (
                            [title] => Paypal Standard
                            [description] => Paypal Standard
                            [business_account] => test@webkul.com
                            [active] => 1
                            [sandbox] => 1
                            [sort] => 3
                        )

                )

        )

    [q] => /admin/configuration/sales/paymentmethods
)
```
and the "q" index also get evaluated, and thus throws an error

**Comment by SpareShade** [comment]
as a temporary workaround I've just added
```
if ($method === 'q') continue;
$recurssiveData = $this->recuressiveArray($fieldData, $method);
```
seems to work fine

**Comment by Mohammedalasaad** [comment]
Hi @SpareShade,
Yes thats looks good.. Hope we see this fixed on the next version :)

**Comment by Mohammedalasaad** [comment]
Hi @SpareShade ,
I think we have the same problem if we try to save the Inventory Source.
<img width="736" alt="Screenshot 2020-04-12 at 23 48 57" src="https://user-images.githubusercontent.com/48674512/79080799-552e3480-7d18-11ea-9e56-d9d91dfa8b85.png">
<img width="1425" alt="Screenshot 2020-04-12 at 23 50 10" src="https://user-images.githubusercontent.com/48674512/79080803-5eb79c80-7d18-11ea-9ce7-0d9e57bc46b4.png">

**Comment by Mohammedalasaad** [comment]
debugging it a bit.. got this has q as well.. 

```
/home/bagisto/packages/Webkul/Inventory/src/Http/Controllers/InventorySourceController.php:133:
array (size=19)
  '_token' => string 'D9fptKz2j7xc97YWjhqPCWzm8lDiE0oAy6KVHcqS' (length=40)
  '_method' => string 'PUT' (length=3)
  'code' => string 'default' (length=7)
  'name' => string 'Default' (length=7)
  'description' => string '' (length=0)
  'latitude' => string '' (length=0)
  'longitude' => string '' (length=0)
  'priority' => string '0' (length=1)
  'status' => int 1
  'contact_name' => string 'Detroit Warehouse' (length=17)
  'contact_email' => string 'warehouse@example.com' (length=21)
  'contact_number' => string '1234567899' (length=10)
  'contact_fax' => string '' (length=0)
  'country' => string 'US' (length=2)
  'state' => string 'MI' (length=2)
  'city' => string 'Detroit' (length=7)
  'street' => string '12th Street' (length=11)
  'postcode' => string '48127' (length=5)
  'q' => string '/admin/inventory_sources/edit/1' (length=31)
```

**Comment by Mohammedalasaad** [comment]
Ok @SpareShade ... I think I found the problem finally 👍 ... Well its not from the code and you dont need to add if ($method === 'q') continue;.. the problem from my nginx config..

In my sites-available/site configration file..
```
 location / {
       # try_files $uri $uri/ =404;
       try_files $uri $uri/ /index.php?q=$uri&$args;
     }
```
Change it to be like this:
```
  location / {
       # try_files $uri $uri/ =404;
       try_files $uri $uri/ /index.php?$query_string;
     }
```
