### ISSUE TITLE
Fix date picker icon layout at dashboard

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2851]
# Bug report

### Title
Fix date picker icon layout at the dashboard

### Issue Description
Fix date picker icon layout at dashboard

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- check the admin panel dashboard 

### Actual result
![Screenshot (5)](https://user-images.githubusercontent.com/43210406/78868603-d8bdfc00-7a60-11ea-953d-0a236596f0da.png)

**Comment by Mohammedalasaad** [comment]
Hi @jitendra-webkul,
I think you fixed the date that exist when u add new product type booking.
The reported issue still not fixed, the date need to be fix showing directly on the dashboard page.
To fix it we need to remove the position:abusloute;
/bagisto/packages/Webkul/Ui/src/Resources/assets/sass/app.scss

   ```
 &.date, &.datetime {
        &::after {
            background-image: url("../images/Icon-Calendar.svg");
            width: 24px;
            height: 24px;
            content: '';
            display: inline-block;
            vertical-align: middle;
            margin-left: -34px;
            pointer-events: none;
            position: absolute;        <=====Remove this. 
            left: 70%;                       <=====Remove this. 
            top: 50%;                       <=====Remove this. 
        }
    }
```

I fixed it bascially. but I did not know how to complie the Ui and minify it.. I tried npm run prod but it does not make it minified.. just npm run dev works but its not minified as its dev.
/bagisto/packages/Webkul/Ui
run npm dev
run npm prod

**Comment by vaishaliwebkul** [comment]
@jitendra-webkul 
This issue has been fixed for me.

**Comment by Mohammedalasaad** [comment]
I think its fixed for me too!
