### ISSUE TITLE
Issue with Sort by functionality, when open any category it by defaults show Newest First but after changing sort by when again select newest first it shows different product. 

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#2856]
# Bug report

### Title
Issue with Sort by functionality, when open any category it by defaults show Newest First but after changing sort by when again select newest first it shows different product. 

### Issue Description
Issue with Sort by functionality, when open any category it by defaults show Newest First but after changing sort by when again select newest first it shows different product. 

### Preconditions

    1. framework Version.-1.1.0

### Steps to reproduce
    1. step1- Open any category.
    2. step2- Select any option for sort by
    3. Step3- Now select Newest First

### Expected result
Sort by functionality should work properly

### Actual result

![Screenshot - 2020-04-09T161509 146](https://user-images.githubusercontent.com/45203177/78888014-84c21000-7a7e-11ea-8bb3-681e1e01246d.png)
![Screenshot - 2020-04-09T161634 441](https://user-images.githubusercontent.com/45203177/78888017-868bd380-7a7e-11ea-869e-03ebb82e2e01.png)

**Comment by vaishaliwebkul** [comment]
fixed
