### ISSUE TITLE
Search Product Name and Description

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#2863]
I find sometimes it would be good for customers to find items based on either short description or product name/title. The following change works to search both fields. Sorry for my formatting.

File: pacakges/Webkul/Products/src/Repositories/ProductRepository.php
Line 316:
```
--  ->where( 'product_flat.name', 'like', '%' . urldecode( $term ) . '%')

++ ->where( function( $sub_query ) use ( $term ) {  
++      $sub_query->where('product_flat.name', 'like', '%' . urldecode($term) . '%')
++      ->orWhere('product_flat.short_description', 'like', '%' . urldecode($term) . '%');
++ } )
```

**Comment by rahulcs0082** [comment]
Hi @richmondnursery 

Thanks for your suggestion, we have implemented this one.
