### ISSUE TITLE
Save order taking so long time 30s

### ISSUE THREAD

**Issue by Mohammedalasaad** [bagisto/bagisto#2865]
Hi,
Any idea why save order request taking so long time, Around 30s. Iam running laravel/homestead and all site working fast and good just when saving order o frontend or backend
![Screenshot 2020-04-11 at 00 36 51](https://user-images.githubusercontent.com/48674512/79027540-eec8db00-7b8c-11ea-87d0-0604f5b372b0.png)
 "admin" its taking long time.

**Comment by ghermans** [comment]
you can try the steps below to speed up the application:

1. open **.env**
2. change **APP_ENV=local** to **APP_ENV=production**

**Comment by Mohammedalasaad** [comment]
Hi @ghermans 
I already tried that.. Did not help really.. still same 30s when it save order.

**Comment by Mohammedalasaad** [comment]
Hi @ghermans 
I think I fixed the problem, The problem is email sending issue as I am testing it locally and email not working locally.. I disabled the email notification and its fast again :)
https://github.com/bagisto/bagisto/issues/2266

Thanks

**Comment by SpareShade** [comment]
Perhaps you should try sending emails asynchronously, eg. using a cron worker.
I'd also be using an external API eg. Mailgun for email delivery... unless there is a really good reason to use a local email server...

**Comment by Mohammedalasaad** [comment]
Thanks @SpareShade , I am trying to config smtp gmail.. locally just to see everything works.. seems to be faster when we have smtp info at least :).. oh I got the email working now :) just with smtp.gmail :D thats nice!
