### ISSUE TITLE
Updating "Velocity meta data" throws QueryException

### ISSUE THREAD

**Issue by SpareShade** [bagisto/bagisto#2869]
# Bug report

### Title
Updating "Velocity meta data" throws Illuminate\Database\QueryException

### Issue Description
When attempting to update/modify the "Velocity meta data" in the admin, an SQL exception is thrown:
```SQL
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'q' in 'field list' (SQL: update `velocity_meta_data` set `q` = /admin/velocity/meta-data/1, `velocity_meta_data`.`updated_at` = 2020-04-13 02:39:22 where `id` = 1)
```

### Clues
Metadata seems to be updated using a "fill" (```$model->fill($attributes)```) ;

Using the models "guard" prop can be a temporary hack/fix, eg.
```PHP
Webkul\Velocity\Models\VelocityMetadata::$guarded = ['q']
```

**Comment by shubhwebkul** [comment]
Hi,
Could you please mention steps to reproduce the exception?

**Comment by shubhwebkul** [comment]
Feel free to reopen this if you're still facing issue.

Thanks!
