### ISSUE TITLE
Transactions and Rollbacks not being implemented

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#2873]
Bagisto Version: 1.0.0+

In an application that involves creating transactions and saving multiple records in multiple tables with any given action should require the use of database transactions and exception handling to rollback all actions if an error occurs. This is currently not the case.

I am receiving a 500 error when executing a checkout request and emails are being generated that the order was executed but no order was actually created within the system and the items are still in the cart. This means that there are no failsafe especially with the prospects of the community creating packages to tap into various areas of code execution.

I would suggest that some refactoring be done to accommodate for failsafe execution with the use of Database Transactions.

**Comment by SpareShade** [comment]
@emperorjm I think you've pointed out a rather important design flaw.
Transaction is implemented indeed (at least for the checkout process), but the events are fired within the transaction itself, which can lead to unpredictable issues/corrupted data states (depending on what the event listeners do).
Am I wrong here @shubhwebkul  @vaishaliwebkul ?

@vaishaliwebkul also, what I think is more troubling is that the information about the payment is committed within the same transaction as creating/saving the order
```php
$order->payment()->create($data['payment']);
```
meaning that if the payment was successful, but a minor, payment-unrelated error was thrown, all the information about the payment is lost as if it never happened.

Payment and order creation are two separate processes, and should really be implemented as saga, or a long running process.

Make sure 100% that the payment information is persisted, and then let a background process deal with the event of it.

**Comment by vaishaliwebkul** [comment]
@SpareShade @emperorjm 

We're looking into the feasibility regarding this & will update you soon.
till then you could raise the PR if you willing to implement this.

Thanks.

**Comment by dejavuejs** [comment]
This has been ignored for very long. I suggest list this as bug not as enhancement. The current payment system does not support any provision for later of subscription based payments.

**Comment by SpareShade** [comment]
I'd be happy to help at some point, but I am not currently too familiar with the whole system.

In this particular instance I am not sure about the purpose for the event listeners "before" the order is committed. If they alter database state, then I am not really positive it is happening within the same transaction. 

It would certainly be good to have a bit of open discussion with the developers about the overall design; we can only help if we understand how the system is supposed to work.

**Comment by ghermans** [comment]
@rahulshukla-webkul this is also related to #4102
