### ISSUE TITLE
Order, payment process and payment metadata

### ISSUE THREAD

**Issue by SpareShade** [bagisto/bagisto#2874]
I have checked out the forum, but for the sheer amount of questions/discussion there some important questions that cannot get a proper attention.
I do apologise in advance for placing this query here.

1. Payment (order payments) should allow for extra information to be provided (eg. PayPal's receipt id), so that a non-technical backend user can troubleshoot it. I do understand that this should be in domain of custom payment method service, but the order should have certain abstractions to provide extra information for the end-user.

2. the built-in standard PayPal method should, upon successful payment, mark the order as paid. It is quite confusing to find it as pending. When I see 'pending' I am thinking "pending what?", payment? shipment? refund?.

3. Payment status should be obvious, and not obscured by the "order status"; shipping is dependent on the product type, but could be either "shipped"/"downloaded"

I'll be happy to help grow and improve the Bagisto once I am more familiar with the logic behind it. Thank you for all your hard work :)

**Comment by cagartner** [comment]
I think we can create some table to store payment details information, for one of my payment extensions I created a table for this but would be good to have something in the core.

Another thing that would be good is to have a order_comments to the admin user can put some custom comments and send to the customer.

**Comment by jitendra-webkul** [comment]
Implemented in master branch.
