### ISSUE TITLE
Deleting brands that have been assigned to products causes checkout error

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#2875]
Bagisto Version: 1.1.0

I have quite few products linked to a brand which was deleted from the Brand listing and it seems that there is no cascading effect to remove the brand from the products and so when I try to checkout with any of those products I get the following error:

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db123`.`order_brands`, CONSTRAINT `order_brands_brand_foreign` FOREIGN KEY (`brand`) REFERENCES `attribute_options` (`id`) ON DELETE CASCADE) (SQL: insert into `order_brands` (`order_item_id`, `order_id`, `product_id`, `brand`, `updated_at`, `created_at`) values (38, 12, 101, 13, 2020-04-12 21:01:19, 2020-04-12 21:01:19))

Order emails are sent but the order is not created. Once I resave the products this and then checkout the error is no longer thrown. I have quite a lot of products in the database and would be difficult to go through each product just to update the brand attribute. The brand attribute should be removed from the product when the selected brand is deleted from the brand attribute.

**Comment by emperorjm** [comment]
Due to this error the Order ID and Increment ID are now different. So order with Order ID being 14 for instance actually has an Increment ID of 12. The orders page shows the order id as being 12 but the ID in the URL is 14. This seems to be an issue.

**Comment by emperorjm** [comment]
After a few more orders the Order ID and Increment ID are now the same.

**Comment by shubhwebkul** [comment]
feel free to reopen this if you are still facing issue
