### ISSUE TITLE
Add filter according to Customer name in Customer Grid.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#288]
Framework Version: 0.1.2

![screenshot from 2018-12-06 15-43-55](https://user-images.githubusercontent.com/45203177/49577657-e85d9a00-f96d-11e8-801a-7bbf3df67c84.png)

**Comment by rahulshukla-webkul** [comment]
![filter-name](https://user-images.githubusercontent.com/42834394/50809969-07649880-132d-11e9-9fac-a465e32d0716.png)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot from 2019-02-02 16-39-50](https://user-images.githubusercontent.com/45203177/52163523-36daab00-2709-11e9-92c5-6195a5b97686.png)
