### ISSUE TITLE
bagisto and redis

### ISSUE THREAD

**Issue by Mohammedalasaad** [bagisto/bagisto#2881]
Hi,
Do we need to make a custom coding to let bagisto work with redis cache ?
I have checked this https://bagisto.com/en/how-to-use-redis-with-laravel/

But I wonder do we need to change/add code to make redis work? or it will work and we dont need to add any more code?

Regards

**Comment by vaishaliwebkul** [comment]
Hi @Mohammedalasaad 
You need to add the configuration to interact with REDIS as describe in the guide https://bagisto.com/en/how-to-use-redis-with-laravel/
For sure, the bit of code require to add.

Thanks.
