### ISSUE TITLE
Configuration option for Compare

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#2886]
In our store, product comparisons are not of use.
I think it would be a nice enhancement if it's possible to enable/disable compare in the configuration settings similar to the way in which reviews can be enabled or disabled.

**Comment by vaishaliwebkul** [comment]
Hi @richmondnursery 
It has been implemented.

Feel free to reopen if still having any doubts.
Thanks

**Comment by ashish-axat** [comment]
how to turn on and off compare feature ?

**Comment by vaishaliwebkul** [comment]
@ashish-axat 
Compare configuration is available in Admin Configuration -> General-> Content section https://prnt.sc/u5etx7

**Comment by ashish-axat** [comment]
iam using  bagisto verison 1.1.0 .. is there anyother which i can do to disable without changing the version as there is no option in this version

![image](https://user-images.githubusercontent.com/64404802/91146914-2fa53480-e6d5-11ea-9dc6-2de1989cd708.png)

**Comment by vaishaliwebkul** [comment]
@ashish-axat 
This option is available in latest version **1.2.0- Beta** or higher version so either install the latest release or you can also manually change in your code as mention in this PR https://github.com/bagisto/bagisto/commit/29223cca7d0b907bd58f17006a45a6bbbb12160e

**Comment by ashish-axat** [comment]
ok got it ,thank you
