### ISSUE TITLE
Always Default locale should be selected when add new product for each channels

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2888]
# Bug report

### Issue Description

When the default locale set to 'pt_BR', and I am going to add new product then i have to change 'en' to 'pt_BR' locale for add my new product.

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- default channel-> set locale to 'pt_BR'
    2. step2- Now add new product, where i have to change the locale for default channel.

### Actual result

![Screenshot(16)](https://user-images.githubusercontent.com/43210406/79228865-c805ef80-7e7f-11ea-874b-a7c2f00ff78f.png)

 
![Screenshot(15)](https://user-images.githubusercontent.com/43210406/79228850-c0464b00-7e7f-11ea-8f3a-97280e39f3a7.png)

**Comment by rahulcs0082** [comment]
Hi @vaishaliwebkul 

This default locale is for the shop not for admin, if you change for the config ( app.php ) or .env ( APP_LOCALE), it will work accordingly.

**Comment by vaishaliwebkul** [comment]
Hi @rahulcs0082 
Thanks for the update, Now I changed the default locale in .env and run php artisan config: cache

![Screenshot (2)](https://user-images.githubusercontent.com/43210406/81793569-2c6fa980-9527-11ea-88bb-78ed331c4fe4.png)
