### ISSUE TITLE
Problem exporting to xls and csv

### ISSUE THREAD

**Issue by CesarMdz** [bagisto/bagisto#2891]
### I have the problem that when I want to export data to xls or csv it does nothing, it does not export anything, the window to choose the format appears to me, but when clicking on the export button it does nothing. I hope you can help me...

**Comment by rahulcs0082** [comment]
Hi @CesarMdz 

Can you tell about your environment so that we can check on that kind of environment?

**Comment by CesarMdz** [comment]
Hello, I hope and this is what you mean:
  locahost environment, xampp server,
     Apache / 2.4.41 (Win64) OpenSSL / 1.1.1c PHP / 7.4.3
     Database client version: libmysql - mysqlnd 7.4.3
     PHP extension: mysqli Documentation curl Documentation mbstring Documentation
     PHP version: 7.4.3
Server version: 10.4.11-MariaDB - mariadb.org binary distribution

### If it is not what you mean, could you tell me what information you need, please, I am something new in this

**Comment by rahulcs0082** [comment]
Hi @CesarMdz 

This issue has been fixed, kindly take a pull from the master.

**Comment by vaishaliwebkul** [comment]
@CesarMdz 
Hope the issue is resolved, Feel free to reopen the issue again if still exist.

Thanks.
