### ISSUE TITLE
When creating a shipment, display items invoiced

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#2893]
Assuming the standard procedure is Order -> Invoice -> Ship, it would be nice to see the quantity of items invoiced when creating the shipment so items shipped match items invoiced should  there be multiple invoices/shipments. That way items aren't shipped that haven't been invoiced.

My suggestions:
Webkul/Admin/src/Resouces/lang/en/app.php line 411:
```
    'qty-ordered' => 'Qty Ordered',
+++ 'qty-invoiced' => 'Qty Invoiced',
    'qty-to-ship' => 'Qty to Ship',
```

Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php line 265:
```
                          <th>{{ __('admin::app.sales.shipments.qty-ordered') }}</th>
+++                       <th>{{ __('admin::app.sales.shipments.qty-invoiced') }}</th>
                          <th>{{ __('admin::app.sales.shipments.qty-to-ship') }}</th>
```

Line 291:
```
                                   <td>{{ $item->qty_ordered }}</td>
+++                                <td>{{ $item->qty_invoiced }}</td>
                                   <td>{{ $item->qty_to_ship }}</td>
```

I also modified Line 329 to default the quantity shipped from 0 to the invoiced quantity, though that may not be appropriate for all:
```
--- <input type="text" v-validate="'required|numeric|min_value:0|max_value:{{$sourceQty}}'" class="control" id="{{ $inputName }}" name="{{ $inputName }}" value="0" data-vv-as="&quot;{{ __('admin::app.sales.shipments.qty-to-ship') }}&quot;" :disabled="source != '{{ $inventorySource->id }}'"/>
+++ <input type="text" v-validate="'required|numeric|min_value:0|max_value:{{$sourceQty}}'" class="control" id="{{ $inputName }}" name="{{ $inputName }}" value="{{ $item->qty_invoiced }}" data-vv-as="&quot;{{ __('admin::app.sales.shipments.qty-to-ship') }}&quot;" :disabled="source != '{{ $inventorySource->id }}'"/>
```

**Comment by rahulcs0082** [comment]
Hi @richmondnursery 

Thanks for your suggestion, we have implemented this one.

**Comment by vaishaliwebkul** [comment]
Hi @richmondnursery 
No response from last 1month so we are closing this.

Feel free to reopen in case of any query.
