### ISSUE TITLE
The type hint of view in this blade file is 'address' - there is no tag in any provider which loads view with this type hint.

### ISSUE THREAD

**Issue by dejavuejs** [bagisto/bagisto#2895]
https://github.com/bagisto/bagisto/blob/cce548f2cd674db7f4973e7738a48bd5667b6e92/packages/Webkul/Admin/src/Resources/views/customers/addresses/orders/index.blade.php#L1

**Comment by rahulcs0082** [comment]
Hello @dejavuejs 

Yes, you are right, there is no such a type hint for view.
Thanks for notifying this one.
