### ISSUE TITLE
There are two fields with having same value of name attribute one is hidden and other is of its desired type - is this redundant code or its solving any purpose?

### ISSUE THREAD

**Issue by dejavuejs** [bagisto/bagisto#2896]
https://github.com/bagisto/bagisto/blob/cce548f2cd674db7f4973e7738a48bd5667b6e92/packages/Webkul/Admin/src/Resources/views/customers/groups/edit.blade.php#L36

https://github.com/bagisto/bagisto/blob/cce548f2cd674db7f4973e7738a48bd5667b6e92/packages/Webkul/Admin/src/Resources/views/customers/groups/edit.blade.php#L37

**Comment by rahulcs0082** [comment]
Hi @dejavuejs 

The above one is not redundant, as you know disabled attribute can not be submitted with the form that's why second one is used.
It holds the value for the disabled attribute.
