### ISSUE TITLE
Inventory status field should be passed through validation for boolean in its backend controller.

### ISSUE THREAD

**Issue by dejavuejs** [bagisto/bagisto#2897]
https://github.com/bagisto/bagisto/blob/cce548f2cd674db7f4973e7738a48bd5667b6e92/packages/Webkul/Admin/src/Resources/views/settings/inventory_sources/create.blade.php#L72

https://github.com/bagisto/bagisto/blob/cce548f2cd674db7f4973e7738a48bd5667b6e92/packages/Webkul/Inventory/src/Http/Controllers/InventorySourceController.php#L79

No validation in controller done for status its validation should be passed as **boolean**.

**Comment by rahulcs0082** [comment]
Hi @dejavuejs 

We don't need validation for this one, simply, if we get this field from view at controller then it is active otherwise not.
