### ISSUE TITLE
error when viewing a category and then wanting to change the language of the page in mobile view 

### ISSUE THREAD

**Issue by CesarMdz** [bagisto/bagisto#2898]
# Bug report

### Title
Error when viewing a category and then wanting to change the language of the page in mobile view 

### Issue Description
In mobile view, when viewing a category and then wanting to change the language or currency type, it displays the menu of the last viewed category.

### Preconditions
**Please provide as detailed information about your environment as possible.**
v.1.1.1.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

   1. mobile view
   2. open the side menu
   3. select a category
   4. now try to change the language or currency type

### Expected result
show configured languages or type of currencies configured

*   [Screenshots, logs or description]

### Actual result

shows the last viewed category

* [points....]

**Comment by jitendra-webkul** [comment]
Please attach screenshot if possible

**Comment by CesarMdz** [comment]
if I access the option to change language first if it shows them
<img src="https://ibb.co/Gvxbs2P">
but if I choose a category and then I want to change the language it shows me the last selected category
<img src="https://ibb.co/375HzKT">

**Comment by shubhwebkul** [comment]
Hello there,

Thanks for notifying us, we've already fixed this issue in master.

**Comment by CesarMdz** [comment]
Tanks :D
