### ISSUE TITLE
showing the configured products as radio button

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#2899]
hi i wanted to know if its possible to show the configurable products attribute like size in a radio button style becuase i saw its looping all to show them in a select format . thanks

**Comment by dejavuejs** [comment]
Use swatch in attributes to have more better point of view.

**Comment by farshadff** [comment]
@dejavuejs  thanks for the answer but unfortunately i didnt understand that could you please explain a bit more ?

**Comment by dejavuejs** [comment]
@farshadff The attributes that you have used to create the configurable product which is by default color and size. Try editing them in admin and fill the swatch information.

![image](https://user-images.githubusercontent.com/57795630/79450888-3fb05780-8003-11ea-9758-91f4c0ff639f.png)

**Comment by rahulcs0082** [comment]
Hi @farshadff 

You can do that, first of all, you need to override **configurable-options.blade.php**  and then according to your need, you can change it from select to radion button with some logic.

**Comment by farshadff** [comment]
@rahulcs0082 thanks my point was actually if i can make radio button on a certain attribute like size because i saw in the code is rendering all the attributes together in a loop

**Comment by farshadff** [comment]
@dejavuejs thanks bro i will check it out i wanted to make the size this way and put the size value inside that i will check this any way thanks a lot

**Comment by rahulcs0082** [comment]
Hi @farshadff 

Please follow the above answer and maybe you need to change some logic for that.

**Comment by jitendra-webkul** [comment]
I hope your problem get resolved, I am closing this issue for now. Feel free to reopen any time.
