### ISSUE TITLE
getting different variant of a configurable product in front end

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#2900]
hi in the home page i want to receive the images and some other attributes of all variants of a configurable product in homepage in velocity theme . any idea how can i get that . thanks

**Comment by dejavuejs** [comment]
Sample code to do so on blade:
@if (Webkul\Product\Helpers\ProductType::hasVariants($product->type))
@foreach($product->variants as $key => $variant)
$variantImage = $variant->images;
@endforeach
@endif

@farshadff Hope this helps.

**Comment by farshadff** [comment]
@dejavuejs  thanks mate i will let you know the result as soon as i try that . thanks a lot <3

**Comment by rahulcs0082** [comment]
Hello @farshadff 

You can also get product variants using relationship.

` $product->variants `

Return empty collection in case of no variant.

**Comment by shubhwebkul** [comment]
Feel free to reopen this if you still have any query.
