### ISSUE TITLE
unify address tables

### ISSUE THREAD

**Issue by bosix** [bagisto/bagisto#2902]
## Status quo
There are several tables that save addresses (customer_addresses, cart_addresses, order_addresses) with almost the same columns and only a few differences (e.g. `billing` or `shipping` as type in order_address).

## Suggestion
Create a table `addresses` with an additional field `address_type` which holds addresses of all types. To ensure all existing functions to work proper database-views for the old tables should be added.

**Notice:** I'll provide the source code by myself later this week.

**Comment by dejavuejs** [comment]
Eloquent's morphToMany?

**Comment by SteffenMahler** [comment]
@dejavuejs I'm not sure what you want to say with your comment.

**Comment by rahulcs0082** [comment]
HI @bosix 

Thanks for your suggestion, we will add this one in future.

**Comment by dejavuejs** [comment]
@dejavuejs A central address table and who so ever uses the addresses can establish the relationship using polymorphic relations.

https://laravel.com/docs/6.x/eloquent-relationships#one-to-many-polymorphic-relations

**Comment by bosix** [comment]
Hi,

@rahulcs0082 your welcome. I'll have a look at the implementation soon.

@dejavuejs I see what your idea is and I have a few ideas about how relations can be managed when implementing this feature and polymorphs are one option. I am also thinking about scopes.
