### ISSUE TITLE
A class is missing from the Velocity ProductRepositiry file

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#2908]
Bagist: v1.1.0

"Class 'Webkul\Velocity\Repositories\Product\ProductAttributeValue' not found" is not found in the "packages/Webkul/Velocity/src/Repositories/Product/ProductRepository.php" file.

`foreach($aliases as $table => $alias) {
                    $query1 = $query1->orWhere(function($query2) use ($query, $table, $alias) {
 
                        foreach ($this->attributeRepository->getProductDefaultAttributes(array_keys(request()->input())) as $code => $attribute) {
                            $aliasTemp = $alias . $attribute->code;
 
                            $query = $query->leftJoin('product_attribute_values as ' . $aliasTemp, $table . '.id', '=', $aliasTemp . '.product_id');
 
                            $column = ProductAttributeValue::$attributeTypeFields[$attribute->type];
 
                            $temp = explode(',', request()->get($attribute->code));
 
                            if ($attribute->type != 'price') {
                                $query2 = $query2->where($aliasTemp . '.attribute_id', $attribute->id);
 
                                $query2 = $query2->where(function($query3) use($aliasTemp, $column, $temp) {
                                    foreach($temp as $code => $filterValue) {
                                        if (! is_numeric($filterValue))
                                            continue;`

**Comment by emperorjm** [comment]
Adding the following use statement corrected the issue:

`use Webkul\Product\Models\ProductAttributeValue;`

**Comment by vaishaliwebkul** [comment]
@emperorjm 
Thanks for notifying this bug. We have updated the code. 
We are closing this. Feel free to reopen it again if still not resolved.
