### ISSUE TITLE
PauUmoney payment gateway integration

### ISSUE THREAD

**Issue by testforpostman7** [bagisto/bagisto#2913]
Hello,
  
    I have to integrate payUmoney payment gateway in bagisto store. SO can anyone guide me about how to integrate payUmoney payment gateway?

Thanks.

**Comment by ghermans** [comment]
You can find the guide to integrate custom payments on the developer documentation site https://devdocs.bagisto.com/create_payment_method.html

**Comment by testforpostman7** [comment]
Hello,

   In https://bagisto.com/en/a-complete-guide-about-payment-gateways/ docs some payment gateway provides by bagisto. Likewise, can we integrate payumoney payment gateway using that package.

Thanks.

**Comment by ghermans** [comment]
No

**Comment by rahulcs0082** [comment]
Hi @testforpostman7 

You can integrate pauUmoney payment gateway in bagisto.
Just follow this link - https://devdocs.bagisto.com/create_payment_method.html
