### ISSUE TITLE
filters are missing on mobile view.

### ISSUE THREAD

**Issue by irisda** [bagisto/bagisto#2915]
[#](url) Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

<img width="1440" alt="Screenshot 2020-04-18 at 3 17 09 PM" src="https://user-images.githubusercontent.com/24676063/79639014-26d1ae80-8189-11ea-9f1b-40badc095897.png">
<img width="1440" alt="Screenshot 2020-04-18 at 3 17 09 PM" src="https://user-images.githubusercontent.com/24676063/79639021-2e915300-8189-11ea-9ac1-4d0f3ba86fa3.png">
<img width="1440" alt="Screenshot 2020-04-18 at 3 33 37 PM" src="https://user-images.githubusercontent.com/24676063/79639145-0bb36e80-818a-11ea-84b1-e80a35004baf.png">

**Comment by shubhwebkul** [comment]
Feel free to reopen this if you are still facing this issue.
