### ISSUE TITLE
Minute tweak for breaking of theme assets.

### ISSUE THREAD

**Issue by dejavuejs** [bagisto/bagisto#2916]
**Replace this:**
https://github.com/bagisto/bagisto/blob/ef622b9e9bf9ca0bdcf63ae4f5c3443836b39285/packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php#L14

**With this:**

@php
        $storeCSSPath = "themes/". core()->getCurrentChannel()->theme ."/assets/css/shop.css";
@endphp

<link rel="stylesheet" href="{{ bagisto_asset($storeCSSPath) }}">

--------------------------------------------------------------------------------------------------------------
**Replace this:**
https://github.com/bagisto/bagisto/blob/ef622b9e9bf9ca0bdcf63ae4f5c3443836b39285/packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php#L109

**With this:**

@php
        $storeJSPath = "themes/". core()->getCurrentChannel()->theme ."/assets/js/shop.js";
@endphp

<script type="text/javascript" src="{{ asset($storeJSPath) }}"></script>

**Comment by shubhwebkul** [comment]
Hey @dejavuejs ,
I think, getting assets via bagisto_asset helper already provides us path according to the selected theme. Please have a look [here](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Theme/src/Http/helpers.php#L15)

**Comment by dejavuejs** [comment]
Try extending shop package's master.blade.php from any other package and use the route apart from shop package also.

Ex: Define route in Admin package that loads shop package's homepage view.

**Comment by jitendra-webkul** [comment]
You need to add theme middleware to your route.
