### ISSUE TITLE
Overview of sold booking products in Admin panel

### ISSUE THREAD

**Issue by AnnikaWolff** [bagisto/bagisto#2918]
When a customer has bought any kind of a booking product, is there a way to see the booked time slots in the Admin backend, except as items in the order and invoice section?

I can imagine a data grid showing all saleable booking products with quantities left and how many times it has been booked yet. Even a calendar view may be possible.

Is something of that kind planned or even in progress yet?

**Comment by jitendra-webkul** [comment]
Hi @AnnikaWolff,

Yes It is planned for future. We will surely add this in our upcoming releases

**Comment by ghermans** [comment]
@jitendra-webkul i would suggest to add a calendar view

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
The translation is missing for Bookings. Please find the screenshot [Here](https://prnt.sc/Bl120pMvRrlA).

**Comment by jitendra-webkul** [comment]
@ghermans added calendar view

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
The **calendar** icon is **not showing.** Please find the screenshot [Here](https://prnt.sc/t7JNeLWGuPQz),

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
The booking date should be highlighted on the calendar view.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
The booking **date should be correct**. Please find the screenshot [Here](https://prnt.sc/ZfDwI8E5JLXH).
