### ISSUE TITLE
Header Content not working on other languages

### ISSUE THREAD

**Issue by kduqi** [bagisto/bagisto#2919]
# Bug report

### Title
**Header Content error with other languages**

### Issue Description
**When I add more than one Header Contents in two different languages, and then go to homepage, in the primary language it is showing correctly. But if I choose other language the last header content shows twice instead of showing both contents.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

![image](https://user-images.githubusercontent.com/13215092/79793631-30a60e00-8351-11ea-8938-f7eba3e03d62.png)

### Actual result

>    **Tell us what happens instead.**

![image](https://user-images.githubusercontent.com/13215092/79793692-487d9200-8351-11ea-9793-3842b447ae14.png)

**Comment by vaishaliwebkul** [comment]
@kduqi 
Issue is resolved.
Feel free to reopen the issue if still exist.
