### ISSUE TITLE
Create Refund call Payment Method

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#2922]
I am writing a custom Payment Method which is nearly complete.
With my processor, I'm able to store transaction data like ID, auth number, order number and issue refunds against a sale without requiring the customer's credit card details. It would be nice if the Admin RefundController were able to call the Payment method and check for a refund function. In that way, the Refunds could potentially be processed directly in the admin section and processed immediately.

**Comment by rahulcs0082** [comment]
Hi @richmondnursery 

You can create your own controller for the same with an overriding refund route, so when refund route will be called then call your controller and do necessary action in this controller for calling payment method.

**Comment by richmondnursery** [comment]
Thanks @rahulcs0082 
I will look into that. 
I just thought it would be a handy feature for other payment methods as well. More like a plug-in architecture rather than each payment method needing an override.

**Comment by rahulcs0082** [comment]
Hello  @richmondnursery 

Instead of this, we have also fired an event called - **sales.refund.save.after** after the refund creation, you can also listen to this event and can take necessary actions.

**Comment by richmondnursery** [comment]
@rahulcs0082 

I implemented a listener in my payment processor and it works perfectly.

However, I do see a potential caveat if you have multiple payment methods available. You'd have to create a Listener for each refund method and then determine if that particular method was originally used or not to handle the refund processing. I check $refund->order->payment->method to see if my payment method was used.

An idea would be to have the refund process look for that payment method and fire a refund function in the payment method if it exists?

**Comment by rahulcs0082** [comment]
Hi @richmondnursery 

You don't need to create multiple listeners, you can create a single listener which will listen to **sales.refund.save.after** and get all refund data here and call anything according to payment method check.

**Comment by vaishaliwebkul** [comment]
Hi @richmondnursery 
Hope the above solution works for you.

Feel free to ask any further query.
