### ISSUE TITLE
bagisto_asset function not able to find files in custom package

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#2926]
Bagisto: v1.1.0

I created a package and added a view file **"Resources/views/confirm.blade.php"** which extends the Shop master layout file by adding the following to the top of the file:

**@extends('shop::layouts.master')**

The master file is extended and all included files (css and javascript) are loaded except those that use the **"bagisto_asset"** function for example:

**<link rel="stylesheet" href="{{ bagisto_asset('css/shop.css') }}">**

It seems it's unable to find the selected theme.

**Comment by rahulcs0082** [comment]
Hi @emperorjm 

Make sure that your views route is passing through theme middleware.

**Comment by jitendra-webkul** [comment]
I hope above reply solved you issue, for now I am closing this issue. Feel free to open.

**Comment by elite-digital** [comment]
> Hi @emperorjm
> 
> Make sure that your views route is passing through theme middleware.

Hi @rahulcs0082 Rahul where I will find theme middleware?

**Comment by messiisgreat** [comment]
Could you open this ticket again?
I made new package but can't access asset files using bagisto_asset function.
Here is my asset file structure

packagename
> Shop
> > src
> > > Resources
> > > > assets
> > > > image.svg

**Comment by messiisgreat** [comment]
I did rebuild using npm run build because vite is not working in customized package.
And now bagisto_asset is working for images that were existing before build.
And bagisto_asset is not working for images that I added after build.

**Comment by devansh-webkul** [comment]
At the theme level, if you don't provide an argument, bagisto_asset will detect the current theme and provide the assets. However, in the case of modules, sometimes it's not theme-dependent. In that case, you can provide a second argument, where you specify the name of the module registered in the config/viters file.

**Comment by devansh-webkul** [comment]
For example, let's say you are working on the theme blade files and the current theme is 'shop'. In this case, if you use the following code:

~~~php
bagisto_asset('images/product-placeholders/front.svg');
~~~

This code will check the current theme based on the 'theme' middleware and provide you with the URL. If this middleware is not used, then you will either get a null URL or an exception.

Now, let's consider the second case. Suppose you are working on a module, and there are some assets that are not dependent on the themes, and you want to load them. In this scenario, you can register them in the `config/bagisto-vite.php` file:

~~~php
return [
    /*
    |--------------------------------------------------------------------------
    | Bagisto Vite Configuration
    |--------------------------------------------------------------------------
    |
    | Please add your Vite registry here to seamlessly support the `bagisto_assets` function.
    |
    */

    'viters' => [
        ...

        'module_1' => [
            'hot_file'                 => 'module-1-vite.hot',
            'build_directory'          => 'modules/module-1/build',
            'package_assets_directory' => 'src/Resources/assets',
        ],
    ],
];
~~~

Now, you can use the second argument to get the assets from your configured directory:

~~~php
bagisto_asset('images/product-placeholders/front.svg', 'module_1');
~~~

Once you add the second argument, the function will detect that it's not theme-dependent assets and will check your configured directory for them.
