### ISSUE TITLE
How can set global value for items per page in datagrid

### ISSUE THREAD

**Issue by sagarpatel9697** [bagisto/bagisto#2929]
What should i do for change items per page 20 from 10 for all admin datagrid tables?

1. Indeed, I have overridden one datagrid class and checked, it shows 20 records but i don't think its perfect way to create bunch of files & override all admin datagrid class for changing single variable value.
2. When i overrode datagrid class with `protected $itemsPerPage = 20;` it shows 20 rows but items per page select box isn't displaying perfect value on admin UI

![ipp](https://user-images.githubusercontent.com/25764632/80087540-da1b1880-8578-11ea-9ffc-576e2c678ac6.png)

**Comment by rahulcs0082** [comment]
Hello @sagarpatel9697 

Open the **table.blade.php** file in UI package and find the below line -  **perPage: 10**.
Change this 10 according to your global items data per page.

In the same file, search for the below one - 
`<div class="dropdown-filters per-page">
                  
                            <select id="perPage" name="perPage" class="control" v-model="perPage" v-on:change="paginate">
                                <option value="10"> 10 </option>
                                <option value="20"> 20 </option>
                                <option value="30"> 30 </option>
                                <option value="40"> 40 </option>
                                <option value="50"> 50 </option>
                            </select>
                        `

and change this option value and loop accordingly.

**Comment by jitendra-webkul** [comment]
No reply from last 20 days, so I am closing this issue for now, feel free to open any time.
