### ISSUE TITLE
change the admin route for another

### ISSUE THREAD

**Issue by CesarMdz** [bagisto/bagisto#2936]
Can you change the admin route to a custom prestashop type route? Example: mysite.com/admin by mysite.com/admin1322112.

sorry if it's not the right way to ask my question

**Comment by jitendra-webkul** [comment]
For now there is no way to achieving this by not changing to the core files.

Please take a look at the following file:

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Admin/src/Http/routes.php#L4

Surely we will implement this is our future release.
