### ISSUE TITLE
Extend Model Class

### ISSUE THREAD

**Issue by cutemonster** [bagisto/bagisto#2938]
What is the proper way to extend User Model relationship in a separate package?
I want to make User hasMany Item.

**Comment by rahulcs0082** [comment]
Hi @cutemonster 

You can follow the given article to override any Model - https://devdocs.bagisto.com/override-core-model.html

**Comment by jitendra-webkul** [comment]
I hope above reply solved you problem. I am closing this issue for now, feel free to reopen.
