### ISSUE TITLE
get product description for API without html tags

### ISSUE THREAD

**Issue by MostafaAttia** [bagisto/bagisto#2939]
Hi,

I'm working on API and when I get the flat product, the description/short_description fields are returned as HTML, even if I use `strip_tags()` function, still some HTML markup like \n \t  exist.

any suggestions to fix this?
Isn't it better if saved as text on the database, not as HTML?

**Comment by rahulcs0082** [comment]
Hi @MostafaAttia 

You can override products edit page and can remove the editor (tinymce).
So, now the data will be saved like plain text instead of HTML.

**Comment by jitendra-webkul** [comment]
I hope above reply solved you problem. I am closing this issue for now, feel free to reopen.
