### ISSUE TITLE
how to remove the magnifier from product .

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#2941]
i want to remove the magnifier from the product page because it prevents me from clicking on shopping basket . but when i remove the code it removes the whole image from gallery , i want to know if there is any way to remove this from code

**Comment by shubhwebkul** [comment]
you could directly call image instead of passing it in the magnify-image component in [this](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/views/shop/products/view/gallery.blade.php#L12) file

**Comment by jitendra-webkul** [comment]
I am closing this issue for now, feel free reopen anytime.
