### ISSUE TITLE
Randomize New and Featured Products

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#2942]
I wanted to give visitors more interaction visiting our site. Rather than displaying simply 4 featured products and new products in the same order, I thought it would be good to display a randomized collection of Featured and New products. Here are my changes:

packages/Webkul/Products/src/Repositories/ProductRepository.php near Line 265
```
-- ->orderBy('product_id', 'desc');

++ ->inRandomOrder();
```

Line 290:
```
-- ->orderBy('product_id', 'desc');

++ ->inRandomOrder();
```

With those changes, you can also have more than 4 catalog items listed as new or featured so more items get promoted over time.

**Comment by rahulcs0082** [comment]
Hi @richmondnursery 

Thanks for your suggestion, we will implement this one.

**Comment by vaishaliwebkul** [comment]
@richmondnursery 
Thanks,
We have implement this. Feel free to reopen the issue if any query regarding this.
