### ISSUE TITLE
Scroll images is not working

### ISSUE THREAD

**Issue by irisda** [bagisto/bagisto#2943]
# Bug report

### Title
Scroll image on the image product page
### Issue Description
If i have more than 4 images inside a prodcut i can not show all of this images becuase the scroll function on thumbnail images is not working, on Velocity Theme
<img width="616" alt="Screenshot 2020-04-26 at 1 34 45 PM" src="https://user-images.githubusercontent.com/24676063/80311362-9413be00-87df-11ea-9095-89c4cab37f58.png">

**Comment by vaishaliwebkul** [comment]
@irisda 
This bug has been fixed in latest release 1.1.2
No response from the last 13days so We are closing this issue, Feel free to reopen it again.
