### ISSUE TITLE
How to remove Velocity Logo from admin

### ISSUE THREAD

**Issue by digiapps** [bagisto/bagisto#2948]
This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by digiapps** [comment]
I am asking for velocity logo coming in admin please see screenshot highlighted area
![image](https://user-images.githubusercontent.com/8210369/80372424-220ba980-88b1-11ea-8308-a00cbccf78a2.png)

**Comment by shubhwebkul** [comment]
Hello there,
you could change velocity configuration from [here](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Config/admin-menu.php#L5)

**Comment by digiapps** [comment]
I have added currency Indian Rs but still its showing $ in admin while its changed on front end how to change that, I am adding a simple product but there are mandatory attributes like color, Size while in some products We don't need these fields like If  I am adding a deodorant then whats the need of color and size.

**Comment by digiapps** [comment]
For example I added a product in which color and size not required but in form color red and Size default selected

![image](https://user-images.githubusercontent.com/8210369/80375436-ede6b780-88b5-11ea-96aa-b611d167a7f0.png)

**Comment by vaishaliwebkul** [comment]
-  For change currency in the admin panel, you have to set the default currency from the config/app.php file 'currency' => env('APP_CURRENCY', 'INR')

-  Color & size are the custom attribute, if you don't want these attributes then you can delete them from the attribute list and create your own attribute.
Also if you can remove these attribute from the default family.

**Comment by digiapps** [comment]
I created a new theme following your document but how to add all features like ajax add to cart, add to wish list, products filters and checkout functionalities.
