### ISSUE TITLE
Unable to change gender of customers from Edit Customer Page.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#295]
Framework version: 0.1.2

**Comment by prashant-webkul** [comment]
We should remove the gender field from the customer edit form from the admin panel as the provision for setting gender for customer comes only when they edit their profile from account section.

**Comment by rahulshukla-webkul** [comment]
Made gender editable.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
