### ISSUE TITLE
Getting error Base table channel not found

### ISSUE THREAD

**Issue by digiapps** [bagisto/bagisto#2951]
I have installed latest version and some times Getting error Base table channel not found and when refreshing its work

**Comment by rahulcs0082** [comment]
Hi @digiapps 

Can you tell the exact scenario when it has happened?

**Comment by digiapps** [comment]
Some times when landing on home page

**Comment by rahulcs0082** [comment]
Hi @digiapps 

We have never experienced this error, once seeder has been successfully run that's why want an exact scenario so that we can fix.

**Comment by digiapps** [comment]
On product detail page its showing booking view path. How to hide that?

![image](https://user-images.githubusercontent.com/8210369/80578939-d67b0c00-8a26-11ea-818d-9c1d50d8c6cb.png)

**Comment by shaztradify** [comment]
i have installed bagisto using composer. but i get this error when :
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bagisto.channels' doesn't exist (SQL: select * from `channels` where `code` = default)
Previous exceptions
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bagisto.channels' doesn't exist (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bagisto.channels' doesn't exist (42S02)

**Comment by rahulcs0082** [comment]
Hi @shaztradify 

KIndly run following commands - 

`php artisan migrate`

`php artisan db:seed`

**Comment by jitendra-webkul** [comment]
I hope your issue get resolved, I am closing this issue for now. Feel free to reopen anytime.

**Comment by bistanil98** [comment]
> Hi @shaztradify
> 
> KIndly run following commands -
> 
> `php artisan migrate`
> 
> `php artisan db:seed`

C:\xampp\htdocs\bagisto-standard>php artisan migrate
Migrating: 2018_06_13_055341_create_roles_table

In Connection.php line 669:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
  n your SQL syntax; check the manual that corresponds to your MySQL server v
  ersion for the right syntax to use near 'json null, `created_at` timestamp
  null, `updated_at` timestamp null) default cha' at line 1 (SQL: create tabl
  e `roles` (`id` int unsigned not null auto_increment primary key, `name` va
  rchar(191) not null, `description` varchar(191) null, `permission_type` var
  char(191) not null, `permissions` json null, `created_at` timestamp null, `
  updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_
  unicode_ci' engine = InnoDB ROW_FORMAT=DYNAMIC)


In PDOConnection.php line 63:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
  n your SQL syntax; check the manual that corresponds to your MySQL server v
  ersion for the right syntax to use near 'json null, `created_at` timestamp
  null, `updated_at` timestamp null) default cha' at line 1


In PDOConnection.php line 61:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
  n your SQL syntax; check the manual that corresponds to your MySQL server v
  ersion for the right syntax to use near 'json null, `created_at` timestamp
  null, `updated_at` timestamp null) default cha' at line 1

**Comment by vaishaliwebkul** [comment]
@bistanil98 
could you mention the version of your DB server whichever you're currently using MYSQL/MARIADB Version
