### ISSUE TITLE
The merging cart function does not work when already added all items of product into customer cart

### ISSUE THREAD

**Issue by autn** [bagisto/bagisto#2954]
# Bug report

### Title
**Can not merge cart if the number of cart is maximum of inventory**

### Issue Description
**The product ABC has 10 items, I added 10 items into my cart, then I logged out and add this product into cart. When I logged again to my account, the 500 error is shown**

### Preconditions

    1. framework Version: 1.1.1.

### Steps to reproduce

    1. Admin adds product with inventory is 10
    2. Customer logins to account
    3. Customer adds 10 items of product into cart
    4. Customer logs out
    5. Customer adds 1 item of above product into cart (guest cart)
    6. Customer logs in again to account
    7. The 500 error is shown

### Expected result
**Merging cart function should be work well**

### Actual result

>    **Server error.**

![Screenshot from 2020-04-28 10-46-57](https://user-images.githubusercontent.com/10827140/80445170-cb987c80-893d-11ea-96b3-37ff17d5c816.png)

**Comment by vaishaliwebkul** [comment]
@autn 
No response from the last 16 days, so we are closing this issue. Feel free to reopen this if still exist.

**Note:** Always make sure the inventory should be available in case you merge product as a guest_user then attempt to login again,else the qty will not updated.

**Comment by autn** [comment]
@vaishaliwebkul I see
