### ISSUE TITLE
Exception when buying non stockable item via API

### ISSUE THREAD

**Issue by AnnikaWolff** [bagisto/bagisto#2964]
# Bug report

### Title
Getting an exception when buying a non stockable item via API/CheckoutController

### Issue Description
Function validateOrder() in api/CheckoutController.php does not check if the cart has stockable items before checking shipping address and selected shipping rate.
And if the cart contains no stockable items, it does not have a shipping address or shipping rate.
Thus, an exception is thrown.

### Preconditions

    1. framework Version: v1.1.2
    2. Commit id: c88ca31b9460ea096b453bb62b8c6fa894558f7d

### Steps to reproduce

    1. use the api/CheckoutController in the shop's checkout process
    2. buy any non-stockable item, e.g. a downloadable product

### Expected result
The function validateOrder() in api/CheckoutController.php only should check for existing shipping address and shipping rate, if the cart contains stockable items.

### Actual result
Getting an exception when buying a non stockable item via API/CheckoutController.

### I will provide an according PR asap.

**Comment by vaishaliwebkul** [comment]
@AnnikaWolff 
Thanks for the reporting this bug and providing the solution.
