### ISSUE TITLE
Need to add the possibility to translate velocity metadata

### ISSUE THREAD

**Issue by Dmytrosubbotin** [bagisto/bagisto#2971]
### Title
Need to add the possibility to translate velocity metadata
### Description
If you have multiple locales, it would be nice to have the metadata from velocity admin settings to be translated (Subscription bar Content, Footer Left Content etc.)

### Steps to reproduce:

- go to admin panel ->Velocity -> Meta Data
- scroll to Footer section
- there is no option for adding a locale for meta data

**Comment by vaishaliwebkul** [comment]
@shubhwebkul 
add the default locale icon with each field which are support for multi-locale in the metadata.
https://prnt.sc/t2sf5b

**Comment by dmytrosubbotinCH** [comment]
@jitendra-webkul any update on this? :-)

**Comment by jyoti-webkul** [comment]
- Framework Version: master

-------------------------------------------------

Fixed

![Screenshot (57)](https://user-images.githubusercontent.com/45203177/89096214-8713f580-d3f2-11ea-9d54-b1ba3f27917b.png)
