### ISSUE TITLE
 can add to homescreen on mobile device in velocity theme

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2972]
can add to homescreen on mobile device in velocity theme ?

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by jitendra-webkul** [comment]
You can use our PWA app for bagisto, pleae checkout the following repository:

https://github.com/bagisto/laravel-pwa
