### ISSUE TITLE
force the execution of the shipping methods trigger

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2973]
after fill phone field, need click tab key for show shipping methods.

![Captura de tela de 2020-04-30 00-03-00](https://user-images.githubusercontent.com/30912144/80667968-f2a69980-8a76-11ea-8f03-cca309d5ab21.png)

![Captura de tela de 2020-04-30 00-01-47](https://user-images.githubusercontent.com/30912144/80667957-e7ec0480-8a76-11ea-8851-d432f37139f4.png)

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by shubhwebkul** [comment]
Hello there,

Currently the feature is, when you change value of phone number or any other field, it automatically tries to validate form with validateForm [method](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php).

So if you want to call this function on the press of tab button, you could call this method on press of tab key.

Let me know if you've any further query.

**Comment by marcelowu** [comment]
when you finish writing the form, the freight calculation does not appear, it only appears when I click the mouse or TAB key

**Comment by marcelowu** [comment]
force the execution of the shipping methods trigger

**Comment by ghermans** [comment]
@marcelowu  please provide more details

**Comment by marcelowu** [comment]
does not work on dev-master

**Comment by ghermans** [comment]
fixed in master branch.
