### ISSUE TITLE
Thumbnails are not generating on mobile ifproduct has more than 4 photos

### ISSUE THREAD

**Issue by irisda** [bagisto/bagisto#2974]
# Bug report

### 
Thumbnails are not generating on mobile ifproduct has more than 4 photos

- Scroll arrows is not working if product has more than 4 photos uploaded 

- On Mobile we can not see thumbnails of product's photo

**Comment by vaishaliwebkul** [comment]
@irisda 
Bug is fixed now. 
No response from last 13 days so we are closing this , feel free to reopen if still exist
