### ISSUE TITLE
how to get  api authorization ?

### ISSUE THREAD

**Issue by Mizan-Rifat** [bagisto/bagisto#2975]
in api login i'm not getting any token.how to get token how to pass it with every request??

**Comment by rahulcs0082** [comment]
Hello @Mizan-Rifat 

You can follow the given link - https://forums.bagisto.com/topic/149/i-need-to-deliver-the-api-token-from-the-json-response-not-the-header/4

**Comment by Mizan-Rifat** [comment]
how to send the token with request?with authorization header??

**Comment by Mizan-Rifat** [comment]
ok i get it.but now  customer/addresses endpoint sends me 'resource not found'.how to solve this??

**Comment by rahulcs0082** [comment]
Hi @Mizan-Rifat 

Which version of bagisto you are using?

**Comment by Mizan-Rifat** [comment]
v 1.1.2

**Comment by rahulcs0082** [comment]
Hi @Mizan-Rifat 

We will update the API package according to latest changes soon.

**Comment by ghermans** [comment]
We started to improve the documentation related to API authentication you can follow this at https://github.com/bagisto/bagisto-docs/issues/214
