### ISSUE TITLE
When paying with Paypal the user can change the amounts of the products

### ISSUE THREAD

**Issue by CesarMdz** [bagisto/bagisto#2981]
# Bug report

### Title
Before it redirects you to paypal, the malicious user can change the amounts from the browser's code inspector

### Issue Description
When selecting the PayPal option as a payment method, it forwards you to a redirection window to paypal, but in this window, users can see the source code and manipulate the amounts and when redirected to the paypal app, it appears with the prices that the user It could have changed and paypal charges that price. There is no validation that the amount sent to paypal is correct.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version. V1.1.0

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

 

### Expected result
<a href="https://ibb.co/pJKSLFx"><img src="https://i.ibb.co/nz1FLJb/bug-1.jpg" alt="bug-1" border="0"></a>
<a href="https://ibb.co/RCwc3fS"><img src="https://i.ibb.co/FBTz52W/bug-2.jpg" alt="bug-2" border="0"></a>
<a href="https://ibb.co/3Cm20Yc"><img src="https://i.ibb.co/QKvL6jM/bug-3.jpg" alt="bug-3" border="0"></a>
<a href="https://ibb.co/rf9DW5V"><img src="https://i.ibb.co/BKk01T9/bug-4.jpg" alt="bug-4" border="0"></a>
<a href="https://ibb.co/B6XyjsS"><img src="https://i.ibb.co/vd73mzK/bug-5.jpg" alt="bug-5" border="0"></a>
<a href="https://ibb.co/SvKRHpr"><img src="https://i.ibb.co/WKcg71t/bug-6.jpg" alt="bug-6" border="0"></a>
<a href="https://ibb.co/b5ZYzcB"><img src="https://i.ibb.co/YBMJpHk/bug-7.jpg" alt="bug-7" border="0"></a>

**Comment by CesarMdz** [comment]
Still no solution for this big problem?

**Comment by jitendra-webkul** [comment]
Hi @CesarMdz ,

If use changed order amount, we do not create invoice for that perticular transaction. You can check the following code:

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Paypal/src/Helpers/Ipn.php#L103

**Comment by CesarMdz** [comment]
Right, now that I see it there was the answer and I didn't see it, sorry. Although I would add:

session()->flash('error', '...text');
                return redirect()->route('shop.checkout.onepage.index');

thanks!
