### ISSUE TITLE
Column not found: 1054 Unknown column 'default_name' in 'field list' (v1.1.2)

### ISSUE THREAD

**Issue by iateadonut** [bagisto/bagisto#2982]
# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

When running php artisan db:seed, mysql throws errors because tables were not created correctly.

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. 1.1.2
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. composer create-project bagisto/bagisto (v1.1.2)
    2. php artisan bagisto:install

### Expected result
**Tell us what should happen.**

it should install bagisto with seeds, views, etc

### Actual result

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'default_name' in 'field list' (SQL: insert into `country  
  _state_translations` (`country_state_id`, `default_name`, `locale`) values (1, ألاباما, ar), (2, ألاسكا, ar), (3  

* [points....]

**Comment by rahulcs0082** [comment]
Hi @iateadonut 

Can you check that migration takes place properly in your system ?

**Comment by iateadonut** [comment]
sorry i didn't update this.
the problem was my mysql config and some other things, including the user not having SUPER privileges on the database, so some triggers were not created.

**Comment by ryanboc** [comment]
did someone fixed this already? I still encounter this error.
