### ISSUE TITLE
Product category is not saving

### ISSUE THREAD

**Issue by Mizan-Rifat** [bagisto/bagisto#2985]
![Untitled](https://user-images.githubusercontent.com/26627242/80804106-f7ce2a80-8bd5-11ea-9db7-5f1dcb622c19.png)
when i set a category for any product and try to save the product it shows:

> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`bagisto`.`product_categories`, CONSTRAINT `product_categories_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE) (SQL: insert into `product_categories` (`category_id`, `product_id`) values (, 13))

**Comment by vaishaliwebkul** [comment]
Hi @Mizan-Rifat 
run **composer dump-autoload**
**php artisan config:cache**

**Comment by vaishaliwebkul** [comment]
@Mizan-Rifat 
Feel free to reopen the issue, Hope the query is resolved.
