### ISSUE TITLE
How to enable Vue debug

### ISSUE THREAD

**Issue by cutemonster** [bagisto/bagisto#2986]
I cannot use the Vue dev tool in Chrome.
Can you tell me how to enable them?

**Comment by vaishaliwebkul** [comment]
Hi @cutemonster 
go to this page https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en and click Add to Chrome

**Comment by cutemonster** [comment]
it already work with other Laravel project with Vue enabled.
My question is that why I cannot get Bagisto to use Vue Debug.

This is the message from Chrome.
**Vue.js is detected on this page.
Devtools inspection is not available because it's in production mode or explicitly disabled by the author.**

Thanks

**Comment by vaishaliwebkul** [comment]
To make it work for pages, you need to check "Allow access to file URLs" for this extension in Chrome's extension management panel.
then restart the chrome.

If still not resolve please check the solution at vue community https://github.com/vuejs/vue-devtools/issues/190

**Comment by cutemonster** [comment]
it looks like maybe the minified Vue.  it's showing now. Thx.
