### ISSUE TITLE
mult address

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2987]
back add new address same empty, update page 

![Captura de tela de 2020-05-01 22-49-43](https://user-images.githubusercontent.com/30912144/80852634-7fc92a00-8c00-11ea-822d-105783a9188c.png)

# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by bosix** [comment]
Hi @vaishaliwebkul ,

do you already know if it's a frontend or a backend bug?

**Comment by rahulcs0082** [comment]
Hi @marcelowu 

We have fixed this issue, thanks for notifying us.

**Comment by gustavorglima** [comment]
This is a serious bug... It is possible to tag it? I downloaded current version and had the same bug. Thanks!

**Comment by vaishaliwebkul** [comment]
@gustavorglima 
It's already resolved in the master branch, will soon new release will come out till then you can check above mention PR.
