### ISSUE TITLE
Facebook Customer Chat for Laravel

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2988]
A simple Laravel library that wraps the Facebook customer chat plugin in your website.

https://github.com/ltsochev-dev/laravel-fb-chat

![23423329_322601184884475_7886446887677460480_n](https://user-images.githubusercontent.com/30912144/80896184-350fe680-8cc2-11ea-9577-69367bd98228.png)

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by jitendra-webkul** [comment]
You can create custom module for that.
