### ISSUE TITLE
Social OAuth authentication for Laravel 5 & 6. Drivers: Facebook, Twitter, Google, LinkedIn, Github, Bitbucket.

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2989]
https://github.com/mckenziearts/laravel-oauth
Included service implementations:

OAuth2
Facebook
GitHub
Google
Instagram
LinkedIn
Bitbucket
Twitter
Dribbble
Pinterest
Youtube
Gitlab

Laravel | laravel-oauth
-- | --
<=5.5 | ^1.0
6.0 | ^1.1

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by jitendra-webkul** [comment]
You can create custom module for that.
