### ISSUE TITLE
Filters not showing in small devices

### ISSUE THREAD

**Issue by digiapps** [bagisto/bagisto#2991]
Hi There,

Filters in left menu on product category page and search page not showing in mobile devices. Please check screenshot of demo site.

![image](https://user-images.githubusercontent.com/8210369/80911942-3c350400-8d57-11ea-92b0-8b9598389a41.png)

**Comment by vaishaliwebkul** [comment]
Hi @digiapps 
This issue is already fixed in Bagisto version 1.1.2.
![Screenshot from 2020-05-04 10-16-26](https://user-images.githubusercontent.com/43210406/80936815-5f5fc200-8df0-11ea-8294-d39e666c1473.png)

**Comment by digiapps** [comment]
I have downloaded latest code from your site and this screenshot is from your demo website.

Which file I should update as I have created copy of velocity theme and working in that theme?

**Comment by vaishaliwebkul** [comment]
@digiapps 
In demo website is running with version 1.1.0.
Also you check update your code by changing this files mention in this commit https://github.com/bagisto/bagisto/pull/2917/commits/76a9ed1085037a687f0d61f0797117df64abbfdb

**Comment by digiapps** [comment]
Have you updated CSS file also?

**Comment by vaishaliwebkul** [comment]
No you don't need to update CSS.

**Comment by digiapps** [comment]
I updated these 2 files fut still filters not showing

**Comment by vaishaliwebkul** [comment]
run the below commands
- composer dump-autoload
- php artisan vendor:publish --force then press  0
- php artisan config:cache

**Comment by digiapps** [comment]
Not resolved did all steps

**Comment by digiapps** [comment]
Let me know how to update to latest version

**Comment by vaishaliwebkul** [comment]
Hi,
refer this guide https://devdocs.bagisto.com/migrate_version.html

**Comment by autn** [comment]
@digiapps these are the steps I did to upgrade Bagisto:
 
- Download Bagisto release version
- Copy into my project (replace old files)
- Use git to show the changes
- Compare and correct the files (keep my old files or update to new files or combine both)
- For my case, I created my theme base on Velocity theme, so I need to update my theme follow the changes of Webkul Velocity
- Run composer update, migrations, vendor publish

Hope can be help you, thanks!

**Comment by vaishaliwebkul** [comment]
@digiapps 
Hope your filter issue in mobile view has been fixed with latest version 1.1.2
So We're closing this issue. if you still got the same Feel Free to Reopen it again.

Thanks.
