### ISSUE TITLE
How to create jewelry website using Bagisto? 

### ISSUE THREAD

**Issue by digiapps** [bagisto/bagisto#2993]
Hi Team,
I want to use bagisto for jewelry website but challenge is there would not be fixed price of any product. Product's price will vary on gold price , diamond price and and weight.

Could you pleas let me know If this is possible in bagisto or I have to create this from scratch without using bagisto.
Your help would be valuable.

Thank You

**Comment by rahulcs0082** [comment]
Hi @digiapps 

You can create this from bagisto and you need to add **Task Scheduling** which will update product price at fix interval of time.

**Comment by digiapps** [comment]
In which table I have to update price using scheduler and in which file I will calculate price? and How to overwrite price that is available in product add form?

**Comment by rahulcs0082** [comment]
Hi @digiapps 

You need to update the price in **product_flat** table.
When you will add Scheduler, you can call any file to calculate price and update it.
You don't need to override price just give any dummy price of that time and scheduler will update it automatically.

**Comment by digiapps** [comment]
Thanks for the update from which table I will take other information of products that are fix and added with product like gold weight, diamond weight and diamond price

**Comment by digiapps** [comment]
Ho to get all product's other attributes value to calculate final price in scheduler?
