### ISSUE TITLE
filter is not showing when search product from search bar

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#2995]
# Bug report

### Title
filter is not showing when search product from search bar

### Issue Description
filter is not showing when search product from search bar

### Preconditions

    1. framework Version- master 

### Steps to reproduce

    1. step1- select category from the search bar
    2. step2- now search the related product

### Expected result
**Tell us what should happen.**

### Actual result

> 
![Screenshot (1)](https://user-images.githubusercontent.com/43210406/80952547-749c1700-8e17-11ea-9d85-5a9b50ebce5b.png)

**Comment by jitendra-webkul** [comment]
No need for filters if customer searching with search term
