### ISSUE TITLE
Incomplete products JSON when type is grouped or bundled

### ISSUE THREAD

**Issue by mdfh** [bagisto/bagisto#2996]
# Bug report

### Issue
In API, The product JSON has no information about bundled items or grouped products which I have added while creating bundled or grouped product. However, website is working fine and its showing those items properly in product detail page. I have tried both the below APIs and issue is still the same.
```
http(s)://example.com/public/api/products
http(s)://example.com/public/api/products/1
```

### Steps to reproduce
    1. In admin create grouped product 
    2. Add some simple products in Grouped Products section
    3. Check the API, it will not have the products added in STEP 2

Do the same for bundled products.

### Expected result
Either return bundled items, grouped products in same API or create a new API to get more information about this product. 

Please see what Magento platform is doing : [Grouped products tutorial](https://devdocs.magento.com/guides/v2.3/rest/tutorials/grouped-product/create-and-manage-grouped-products.html)

### Actual result
See the below JSON, there is no information about bundled_items
```
{
    "data": {
        "id": 80,
        "type": "bundle",
        "name": "Bundled Product",
        "url_key": "bundle1",
        "price": null,
        "formated_price": "SAR0.00",
        "short_description": "<p>Short description</p>",
        "description": "<p>Description</p>",
        "sku": "bundle1",
        "images": [],
        "base_image": {
            "small_image_url": "https://test.com/vendor/webkul/ui/assets/images/product/small-product-placeholder.png",
            "medium_image_url": "https://test.com/vendor/webkul/ui/assets/images/product/meduim-product-placeholder.png",
            "large_image_url": "https://test.com/vendor/webkul/ui/assets/images/product/large-product-placeholder.png",
            "original_image_url": "https://test.com/vendor/webkul/ui/assets/images/product/large-product-placeholder.png"
        },
        "variants": [],
        "in_stock": true,
        "super_attributes": [],
        "reviews": {
            "total": 0,
            "total_rating": 0,
            "average_rating": 0,
            "percentage": []
        },
        "is_saved": false,
        "created_at": "2020-05-04T08:51:39.000000Z",
        "updated_at": "2020-05-04T08:51:39.000000Z"
    }
}
```

**Comment by mdfh** [comment]
@jitendra-webkul @shivam-webkul Any update on this issue.

**Comment by shivam-webkul** [comment]
be3fc8d2c10c51482feb4fc5350006fd39475a8e

added all types product and their options.

**Comment by shubhwebkul** [comment]
Feel free to reopen this if you still face issue.
