### ISSUE TITLE
Category show sidebar

### ISSUE THREAD

**Issue by ruospo** [bagisto/bagisto#2997]
# Bug report

### Title
The left sidebar not show all categories.

### Issue Description
When you have more of 9 root category each category after the 9 not show.
This bug is only on desktop version.
In mobile version show all categories.

### Preconditions

    1. framework Version v1.1.2

### Steps to reproduce
Insert 10 root category 

### Expected result
show all category

### Actual result

show only 9 category

**Comment by vaishaliwebkul** [comment]
Hi @ruospo 
To show more than 9 categories in the category sidebar at the front store,  make sure in **Velocity->Meta data-> Sidebar categories** should be more than 9.

Regarding the mobile view by default 9 categories should be shown, we will fix this issue soon.
Thanks for notifying us.

**Comment by vaishaliwebkul** [comment]
@ruospo 
It's resolved now.

We are closing the issue, feel free to reopen it anytime.
