### ISSUE TITLE
arabic product in home page Not lined up in one format

### ISSUE THREAD

**Issue by Tayeb-Ali** [bagisto/bagisto#3000]
# Bug report

### Title
**arabic product in home page Not lined up in one format**
- The product appears in small cards, and larger card.
- width and height  are not consistent

### Issue Description
**When presenting Arabic content, it appeared untidy on the main page of the site in Velocity Theme**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version. last version v1.1.2
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

* <a href="https://ibb.co/DC7RV0n"><img src="https://i.ibb.co/vPJjw08/Screenshot-from-2020-05-05-06-38-24.png" alt="Screenshot-from-2020-05-05-06-38-24" border="0"></a>
<a href="https://ibb.co/Br5xkBP"><img src="https://i.ibb.co/NmdPRK3/Screenshot-from-2020-05-05-06-38-30.png" alt="Screenshot-from-2020-05-05-06-38-30" border="0"></a>
*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by Tayeb-Ali** [comment]
any update ..?

**Comment by shubhwebkul** [comment]
Hello there,

Basically I suggest you need to add images of same size, that will make your site look better.

**Comment by Tayeb-Ali** [comment]
i try did that.
But the problem still exists.
In addition to a demo site, it carries the same problem when converting to Arabic

**Comment by shubhwebkul** [comment]
Have you tried setting up the height fix of product images displaying in card ?

**Comment by vaishaliwebkul** [comment]
Hi @Tayeb-Ali 
We aren't getting any response from the last 20 days, so we're closing this.

Feel free to reopen it anytime.

Thanks
