### ISSUE TITLE
Buggggggg iOS Safari images are stretched 

### ISSUE THREAD

**Issue by irisda** [bagisto/bagisto#3002]
# Bug report

**On mobile view on Safari product images are are stretched**

### Issue Description
when we try to change images of a product on mobile to check, images are stretched and very hight.This happen also when we try to change colors, only in Safari Browser.

    1. The latest Bagisto version
   
![Image from iOS (2)](https://user-images.githubusercontent.com/24676063/81057105-14b37800-8ecc-11ea-9e11-955e03997eb3.jpg)
![Image from iOS (2)](https://user-images.githubusercontent.com/24676063/81057108-15e4a500-8ecc-11ea-8544-85261b731e6f.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/24676063/81057116-19782c00-8ecc-11ea-84f1-3d9e2c841539.png)

**Comment by irisda** [comment]
Hello @jitendra-webkul  is any update on this issue??

**Comment by akhtarkhan1** [comment]
Dear Irisda You can easily fix this stretching of product images by adding height on your product image through this class which I mentioned through a red rectangular box. You can set the height of the product image as per your requirement.
If you are getting any issue while fixing it then you can comment us. Currently, there are some issues on the ios platform & we are working on it. We will fix it very soon. 
![Screenshot_1](https://user-images.githubusercontent.com/67889091/87149421-cd7fa400-c2cd-11ea-8631-692082f67ce4.png)

**Comment by vaishaliwebkul** [comment]
@irisda 
Hope the above solution works for you, closing this issue.

In case of any doubt, feel free to reopen it anytime

**Comment by vaishaliwebkul** [comment]
this bug still exists for ios device, kindly fix it.
