### ISSUE TITLE
Category Deactivation not working

### ISSUE THREAD

**Issue by pbhavesh45** [bagisto/bagisto#3004]
![image](https://user-images.githubusercontent.com/4070745/81090618-a72f3800-8f1b-11ea-88e1-2417a8fdfdf0.png)

I have latest version of bagisto, where I found issue while update or create new Category and changed the status of visible menu.

**Comment by rahulcs0082** [comment]
Hi @pbhavesh45 

Can you tell about your environment so that we can check?

**Comment by pbhavesh45** [comment]
> Hi @pbhavesh45
> 
> Can you tell about your environment so that we can check?

I am using master branch code.

**Comment by rahulcs0082** [comment]
Hi @pbhavesh45 

I want to know your server environment like - database, its version, php etc,
because we are unable to generate this issue.

**Comment by pbhavesh45** [comment]
> Hi @pbhavesh45
> 
> I want to know your server environment like - database, its version, php etc,
> because we are unable to generate this issue



> Hi @pbhavesh45
> 
> I want to know your server environment like - database, its version, php etc,
> because we are unable to generate this issue.

 *PHP*

PHP 7.4.5 (cli) (built: Apr 16 2020 17:13:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

*Database*

mysql  Ver 14.14 Distrib 5.7.30, for Linux (x86_64) using  EditLine wrapper

*Server*

Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

**Comment by SteffenMahler** [comment]
Hi @pbhavesh45 

did all your migrations run properly?

**Comment by yograj00** [comment]
@SteffenMahler it was exactly this issue - when you clone a project from existing and import the db dump functions didn't get created.
Added functions again and everything works fine.
