### ISSUE TITLE
One page checkout creating new address in profile every time.

### ISSUE THREAD

**Issue by pbhavesh45** [bagisto/bagisto#3005]
I have latest version of bagisto with default theme. 

during checkout option, Selected address from my list of address and selected use same as shipping address for billing address. But during checkout I found it create new address every time.

![image](https://user-images.githubusercontent.com/4070745/81091221-874c4400-8f1c-11ea-9c9d-411278a10544.png)

**Comment by vaishaliwebkul** [comment]
Hi @pbhavesh45 
This bug is already raised https://github.com/bagisto/bagisto/issues/2987

**Comment by pbhavesh45** [comment]
> Hi @pbhavesh45
> This bug is already raised #2987

*PHP*

PHP 7.4.5 (cli) (built: Apr 16 2020 17:13:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies
