### ISSUE TITLE
Featured product slider and new product slider is not working

### ISSUE THREAD

**Issue by neyazahmad83** [bagisto/bagisto#3009]
Hi Team,

I am using velocity theme and i  have 14 products as featured products. The same thing is happening with new product.

**Comment by rahulcs0082** [comment]
Hi @neyazahmad83 

Can you little bit explain more? I mean which kind of not working -  whether it is not showing on the shop or some errors or something else.

**Comment by vaishaliwebkul** [comment]
@neyazahmad83 
Hope your issue is being resolved.
We are closing this , Feel free to reopen anytime,

**Comment by Aziz-tripleA** [comment]
hello, after installing nodejs to the marketplace package and did npm run prod  Featured product slider and new product did not work and no products at two sections

**Comment by ghermans** [comment]
@Aziz-tripleA i suggest that you create a support ticket for this on https://bagisto.uvdesk.com/en/customer/create-ticket/ because the marketplace package is a paid module from [Webkul ](https://webkul.com)
