### ISSUE TITLE
The product is in cart or not

### ISSUE THREAD

**Issue by Mizan-Rifat** [bagisto/bagisto#3011]
is there any way to know the product is in cart or not ?? especially for product api???

**Comment by rahulcs0082** [comment]
Hi @Mizan-Rifat 

You can call the cart API to check whether the product exists in cart or not.

**Comment by Mizan-Rifat** [comment]
@rahulcs0082  i know.but want it for product api.so that i can show "product already is in cart" or "Add to Cart".

**Comment by rahulcs0082** [comment]
Hi @Mizan-Rifat 

Right now this thing is not there, you can create it on your own to achieve it.
