### ISSUE TITLE
This line does nothing, Theme::current() always return null.

### ISSUE THREAD

**Issue by dejavuejs** [bagisto/bagisto#3012]
https://github.com/bagisto/bagisto/blob/adaeaf7087c8ee20d1f8f5866ee5c1901465e2a2/packages/Webkul/Theme/src/ThemeViewFinder.php#L30

core()->getCurrentChannel()->theme can be used for this.

**Comment by dejavuejs** [comment]
This is still not fixed in this.

**Comment by shivam-webkul** [comment]
Hi @dejavuejs ,

you are correct if you are using `core()->getCurrentChannel()->theme` outside `Webkul\Theme `  it returns the current theme name but when you are in the `Webkul\Theme` directory you can use 
`Themes::current();` for the themes and related value  
![theme](https://user-images.githubusercontent.com/50355852/84002463-1c13e880-a986-11ea-91c0-444943141c96.png)


Thanks.

**Comment by jitendra-webkul** [comment]
No response from last 9 days. I am closing this issue, feel free to reopen any time.
