### ISSUE TITLE
Support for Responsive Admin Panel

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#3014]
Support for Responsive Admin Panel
add products smartphone

This repository is only for reporting bugs or issues. If you need support, please use

other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by ghermans** [comment]
No new feedback has been provided in this issue so i'm closing it.
@marcelowu please provide more info when you open/reopen a issue report.
