### ISSUE TITLE
Email field become blank after saving the inventory.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#302]
Framework Version: 0.1.2
Test Steps:
1. Create a inventory and save it.
2. Now edit the inventory.

![screenshot 37](https://user-images.githubusercontent.com/45203177/49712934-ba799d80-fc6c-11e8-8d4c-6b79bc97a67a.png)

**Comment by prashant-webkul** [comment]
Cannot reproduce this bug.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot 73](https://user-images.githubusercontent.com/45203177/52115641-1d682f00-2635-11e9-9492-d551c984b8d9.png)
