### ISSUE TITLE
Deactivating the last category of level1 renders only level2 etc. from deactivated category 

### ISSUE THREAD

**Issue by yograj00** [bagisto/bagisto#3021]
# Bug report

### Title
Deactivating the last category of level1 in bagisto installation renders only level2, level3 etc. of that deactivated category.

### Issue Description
Instead of showing the active categories in frontend it show the sublevels of that inactive category. But it only happens for the last category of level1.

#### Menu looks like this
![image](https://user-images.githubusercontent.com/33759651/81340887-ddea8700-90b0-11ea-9cb6-148fbc4ffea4.png)

#### Deactivating level1 (Food) works fine
![image](https://user-images.githubusercontent.com/33759651/81340973-11c5ac80-90b1-11ea-824e-eaf1a790369e.png)

#### Deactivating level1 (Wein & ...) shows sublevel
![image](https://user-images.githubusercontent.com/33759651/81341128-50f3fd80-90b1-11ea-8a5e-3f4f9f9a33eb.png)

![image](https://user-images.githubusercontent.com/33759651/81341159-61a47380-90b1-11ea-96d9-395f9bcf1f87.png)

### Preconditions
**Please provide as detailed information about your environment as possible.**

PHP 7.4.5 (cli) (built: Apr 16 2020 17:13:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

mysql Ver 14.14 Distrib 5.7.30, for Linux (x86_64) using EditLine wrapper

Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. create categories with multiple level1, level2 and level3
    2. deactivate the last level1 category

### Expected result
**Tell us what should happen.**

* That the active categories will be show on frontend

![image](https://user-images.githubusercontent.com/33759651/81341479-e7c0ba00-90b1-11ea-9559-a0944e2585f7.png)

### Actual result

>    **Tell us what happens instead.**

![image](https://user-images.githubusercontent.com/33759651/81341128-50f3fd80-90b1-11ea-8a5e-3f4f9f9a33eb.png)

**Comment by vaishaliwebkul** [comment]
@yograj00 
The issue is resolve now, take pull from the master then check the issue.

Thanks

**Comment by vaishaliwebkul** [comment]
Hi @yograj00 
No response from the last 12 days so we're closing this.

Feel free to reopen it if still exist.
