### ISSUE TITLE
storage/ should not be included in .gitignore

### ISSUE THREAD

**Issue by iateadonut** [bagisto/bagisto#3022]
# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**
storage/ should not be included in the base .gitignore

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**
if you create a project, and then clone it, the cloned project does not have the necessary storage directory, because storage/ is a line in the base .gitignore.  this is unnecessary, because each subdirectory in storage already contains its own .gitignore file.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version. 1.1.0

**Comment by rahulcs0082** [comment]
HI @iateadonut 

Thanks for your concern, we will change this.

**Comment by dejavuejs** [comment]
> 
> 
> HI @iateadonut
> 
> Thanks for your concern, we will change this.

Storage folder contains system specific temporary view files other than for storage puposes. And its strongly not recommended to do so.

And most of all what is the benefit of ignoring?

**Comment by jitendra-webkul** [comment]
No, Storage folder should not be excluded. By excluding Storage folder you will get the following error.

file_put_contents(storage/framework/sessions/fxmkNWHeTJGrSLikVMDEFA06TCG1qkyfc4AZv8vp): failed to open stream: No such file or directory

**Comment by iateadonut** [comment]
> No, Storage folder should not be excluded. By excluding Storage folder you will get the following error.
> 
> file_put_contents(storage/framework/sessions/fxmkNWHeTJGrSLikVMDEFA06TCG1qkyfc4AZv8vp): failed to open stream: No such file or directory

each subdirectory in storage already contains its own .gitignore file - this was done on purpose by the developers of the laravel framework.  each session file would NOT be committed since that .gitignore file is there.

**Comment by jitendra-webkul** [comment]
Yes, I see that I will remove storage folder from base  .gitignore file.

Thanks for pointing out

**Comment by jitendra-webkul** [comment]
Fixed in mster
