### ISSUE TITLE
velocity theme not fully responsive

### ISSUE THREAD

**Issue by Ashish26bhati** [bagisto/bagisto#3029]
![12](https://user-images.githubusercontent.com/16515060/81391591-fbfcc980-913a-11ea-8023-a1a6c4a77a50.png)
hello,
 i amusing bagisto framework for ecom-website but while i am using velocity theme ist not an fully responsive theme..like other responsive website we work on it and resized the dessktop window it will automatically adjust the menubar and other thing, but with this velocity theme it is not happen the menu bar shows only wishlist cart other things has been hidden it is look like very mess.

 the second concern abut menu bar kindly create menubar fully responsive with submenu and third level menu too on desktop view moblie view is ok ...

pls make it  fully responsive as like other responsive theme

**Comment by shubhwebkul** [comment]
Hello there,

Thanks for reporting the issue and as I can check the screenshot, this issue will be resolved when you'll refresh the page after making the page as mobile view or you could check on real device.

Please let us know if you're still getting this issue.

**Comment by shubhwebkul** [comment]
Feel free to reopen this if you're still facing this issue.

Thanks!
