### ISSUE TITLE
Api for coupons..

### ISSUE THREAD

**Issue by Mizan-Rifat** [bagisto/bagisto#3030]
there is no api routes for applying coupon.can you add this feature??

**Comment by vaishaliwebkul** [comment]
@Mizan-Rifat 
Thanks for suggesting this.
We will implement this soon.

**Comment by alnouirah** [comment]
IMO , they should label this as critical Enhancement because its an essential feature for using this system in different platform 👍 . 
Thanks for the great works you have done 😄

**Comment by shivam-webkul** [comment]
45b904810fc02d3d969b6d270ca5392114371add

added the PR.
