### ISSUE TITLE
error mysql 8.0.20 bagisto v 1.1.2

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#3037]
![2020-05-09 22-26-19屏幕截图](https://user-images.githubusercontent.com/30912144/81488816-8f6df180-9244-11ea-8034-b391c7308898.png)
![2020-05-09 22-26-33屏幕截图](https://user-images.githubusercontent.com/30912144/81488820-9563d280-9244-11ea-9691-88c0f4fe6bae.png)

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by marcelowu** [comment]
![2020-05-10 17-18-37屏幕截图](https://user-images.githubusercontent.com/30912144/81509637-55ebc380-92e2-11ea-806e-202f556ff7cb.png)

**Comment by rahulcs0082** [comment]
Hi @marcelowu 

Kindly make sure that your database user has SUPER privileges on the database and triggers were created.

**Comment by marcelowu** [comment]
root and user

**Comment by rahulcs0082** [comment]
HI @marcelowu 

They will have to SUPER privileges.

**Comment by vickybanti** [comment]
What's SUPER privileges?

**Comment by vickybanti** [comment]
![Command Prompt 13-May-20 2_52_24 PM](https://user-images.githubusercontent.com/42158599/81824224-1e248c00-952d-11ea-8e20-215777d93116.png)
i got this error using the php artisan migrate

**Comment by marcelowu** [comment]
CREATE DATABASE bagisto;

CREATE USER 'wpdbuser'@'localhost' IDENTIFIED BY 'new_password_here';

GRANT ALL ON bagisto.* TO 'wpdbuser'@'localhost' WITH GRANT OPTION;

Finally, save your changes and exit.

FLUSH PRIVILEGES;

**Comment by marcelowu** [comment]
how do you do SUPER privileges

**Comment by rahulcs0082** [comment]
> CREATE DATABASE bagisto;
> 
> CREATE USER 'wpdbuser'@'localhost' IDENTIFIED BY 'new_password_here';
> 
> GRANT ALL ON bagisto.* TO 'wpdbuser'@'localhost' WITH GRANT OPTION;
> 
> FLUSH PRIVILEGES;

Whats migration result when using this user name and password, we also use the same way.

**Comment by marcelowu** [comment]
![image](https://user-images.githubusercontent.com/30912144/81942268-4a451900-95d0-11ea-8aa7-adc3ec4bfd3a.png)


> > CREATE DATABASE bagisto;
> > CREATE USER 'wpdbuser'@'localhost' IDENTIFIED BY 'new_password_here';
> > GRANT ALL ON bagisto.* TO 'wpdbuser'@'localhost' WITH GRANT OPTION;
> > FLUSH PRIVILEGES;
> 
> Whats migration result when using this user name and password, we also use the same way.



> > CREATE DATABASE bagisto;
> > CREATE USER 'wpdbuser'@'localhost' IDENTIFIED BY 'new_password_here';
> > GRANT ALL ON bagisto.* TO 'wpdbuser'@'localhost' WITH GRANT OPTION;
> > FLUSH PRIVILEGES;
> 
> Whats migration result when using this user name and password, we also use the same way.

**Comment by marcelowu** [comment]
I tested it in the mysql version 5.7 I get the same thing

**Comment by marcelowu** [comment]
resolved..

sudo mysql -u root -p
set global log_bin_trust_function_creators=1;
FLUSH PRIVILEGES;
EXIT;
