### ISSUE TITLE
Trying to get property 'code' of non-object

### ISSUE THREAD

**Issue by zakybaraq** [bagisto/bagisto#3038]
Hello, i have a problem here.

I just add new Indonesian Rupiah currency and update default currency in my channel, but i got this problem.

![image](https://user-images.githubusercontent.com/21286084/81510297-e524c580-933a-11ea-8c93-cc66ab633be6.png)

![image](https://user-images.githubusercontent.com/21286084/81510276-cf170500-933a-11ea-872b-2ee9ed2686ee.png)

Please help me :(

**Comment by zakybaraq** [comment]
OMG, finally i realized that the currency option in channel : Channel->Currency should be all selected, @vivek-webkul i think you should change your User Interface for that, it seem old style.

**Comment by L200180024** [comment]
can you give me some pictures example to solve this thing ?

**Comment by vaishaliwebkul** [comment]
@L200180024 
If you are using latest version 1.3.1 then you will not face this error anymore as it has already resolved here https://github.com/bagisto/bagisto/pull/4014
