### ISSUE TITLE
If a current user want to delete his account then in this case a password verification should be required before deleting the user.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#304]
Framework Version: 0.1.2

Test Step: 
1. Click on delete button to delete the logged in user.
2. After a confirmation pop-up user gets deleted.

Expected: Password confirmation should required before deleting the account.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Now delete functionality has been removed

**Comment by prashant-webkul** [comment]
This issue was already fixed but due to extreme refactoring in datagrid, the delete icon seemed to missing in this user's grid.
But in this commit https://github.com/prashant-webkul/bagisto/commit/4eb752cd10e8a40e13da27150a5e60b7bd9b0e56 the delete button had been put back on the user's datagrid.
