### ISSUE TITLE
Getting exception when click on view shopping cart if adding group product in cart that contains variants of configurable product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3044]
# Bug report

### Title
Getting exception when click on view shopping cart if adding group product in cart that contains variants of configurable product.

### Issue Description
Getting exception when click on view shopping cart if adding group product in cart that contains variants of configurable product.
### Preconditions

    1. framework Version.-1.1.1
    

### Steps to reproduce

    1. step1- Add a simple product in cart, then add grouped product that contains child product of configurable product.
    2. step2- Click on View shopping cart

### Expected result
Getting exception on view shopping cart
### Actual result

![Workspace 1_123](https://user-images.githubusercontent.com/45203177/81585932-77c47380-93d2-11ea-9405-3b6e52057e55.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
It's Now fixed. Please take pull from the master branch & run php artisan vendor:publish --force
Feel free to reopen the issue if still exist.
