### ISSUE TITLE
The qty of configurable product is 0 when merging cart

### ISSUE THREAD

**Issue by autn** [bagisto/bagisto#3047]
# Bug report

### Title
**The qty of configurable product is 0 when merging cart**

### Issue Description
**Adding an already configurable product to cart will reset the qty to 0**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: 1.1.2

### Steps to reproduce

    1. Login to customer account
    2. Add a configurable product to cart with one option (i.e. Size S, Color Red), qty 1
    3. Login customer account
    4. Add above product to cart (step 2) with same option (Size S, Color Red), qty 1
    5. Login again to customer account

### Expected result
**The qty of item need to show 2**

### Actual result

>    **The qty is 0**

The issue is happened because your team removed the `totalQuantity` function of Configurable Type (packages/Webkul/Product/src/Type/Configurable.php) in version 1.1.2, please revert that file to 1.1.1 please

**Comment by vaishaliwebkul** [comment]
Hi @autn 
Thanks for notifying the bug. Now it's resolved
For now i am closing this issue , feel free to open if still exist.
