### ISSUE TITLE
"nwidart/laravel-modules": "^3.2", is the wrong version for laravel 6.*

### ISSUE THREAD

**Issue by iateadonut** [bagisto/bagisto#3048]
it should be: "nwidart/laravel-modules": "^6", in composer.json

**Comment by jitendra-webkul** [comment]
We have removed this dependency, we are not using this anymore.

**Comment by iateadonut** [comment]
it seems that your entire system is built on it.

if anyone else wants to build a module for bagisto, they will encounter this bug and have to fix it.
