### ISSUE TITLE
Cannot Registering ModuleServiceProvider in config/concord.php 

### ISSUE THREAD

**Issue by khanhgg** [bagisto/bagisto#3049]
# Bug report

### Title
**Cannot Register ModuleServiceProvider in config/concord.php **

### Issue Description
**ModuleServiceProvider in config/concord.php was removed after run php artisan vendor:publish --force**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: 1.1.1

### Steps to reproduce
    1. Add ModuleServiceProvider in config/concord.php
    2. Run php artisan vendor:publish --force
    3. ModuleServiceProvider in config/concord.php was removed
### Expected result
** ModuleServiceProvider  is not removed in the in config/concord.php**

**Comment by vaishaliwebkul** [comment]
@khanhgg 
As 2nd step. --force publish will remove the provider from concord.php 
so try with the **php artisan vendor:publish** and press index 0
