### ISSUE TITLE
Displaying incorrect role name in account.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#305]
Framework Version: 0.1.2

Displaying role name as administrator always.
![screenshot 38](https://user-images.githubusercontent.com/45203177/49713830-6a9cd580-fc70-11e8-929e-bd1b3a5549bf.png)

**Comment by rahulshukla-webkul** [comment]
Fetched Role n
![role](https://user-images.githubusercontent.com/42834394/49998741-086b0a00-ffbb-11e8-83da-4dece0871b38.png)
ame  from database , Now its showing Properly.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
