### ISSUE TITLE
Can't override models

### ISSUE THREAD

**Issue by rspenc29** [bagisto/bagisto#3050]
# Bug report

https://devdocs.bagisto.com/override-core-model.html

You layout the process for overriding models in that article but then seem to ignore your own conventions by directly referencing the models throughout many of your packages.

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Category/src/Repositories/CategoryRepository.php#L9-L10
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Category/src/Http/Controllers/CategoryController.php#L7
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Product/src/Repositories/ProductRepository.php#L12
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Product/src/Repositories/ProductAttributeValueRepository.php#L8

That's just a few examples. There are way more.

Shouldn't you be using the proxy models instead and retrieving the models via `ModelProxy::modelClass()` ?

**Comment by rahulcs0082** [comment]
Hi @rspenc29 

We have implemented this one, thanks for notifying us.
