### ISSUE TITLE
showing product type name in admin panel in catalog

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#3052]
hi ,
i changed the product type names in `config/product_types.php` and after that when i am trying to make a product it shows my custom names fine for product type but in catalog index method it shows them as the before name because it stores the keys in` product table` is there any way to change that ??

**Comment by rahulcs0082** [comment]
Hi @farshadff 

You can create a migration file and write a SQL query there to update the product type according to your condition.
Once this migration will run, the new product type will be updated in the product table.

For reference, see this one - https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Core/src/Database/Migrations/2020_04_16_185147_add_table_addresses.php

**Comment by vaishaliwebkul** [comment]
Hi @farshadff 
Hope the above solution will help you.

Feel free to reopen in case of any further query.
