### ISSUE TITLE
[Velocity] Checkout: Shipping/Billing Address Name, email does not get updated

### ISSUE THREAD

**Issue by chemisax** [bagisto/bagisto#3053]
# Bug report

### Issue Description
The shipping/billing name and email data is decided on this line:
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php#L163-L165

It only changes if the user inputs a new address.
There is the case that the user name, shipping name and billing name are different, so the address should respect the value entered in the name, last name, email form.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master

### Steps to reproduce
1. Make an order with different shipping and billing contact details other than the user id data. (With pre saved data)

### Expected result
1. The user can save different names with different addresses, so the one page checkout should respect those names. The order is made with different names. It can be a problem because you can get to ship an order with an incorrect name. 

### Actual result
Respect the name, last_name, email information recorded on the saved address.

**Comment by vaishaliwebkul** [comment]
Hi @chemisax 
Thanks for notifying the issue, it's resolved now

We are closing the issue, feel free to reopen anytime.
