### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#3061]
bagisto PWA - CORS errors in version 1.1.2
![2020-05-13 10-10-22屏幕截图](https://user-images.githubusercontent.com/30912144/81816764-2c10e780-9502-11ea-924b-9887c4f7dffc.png)

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by rahulcs0082** [comment]
Hi @marcelowu 

Kindly use your domain name in APP_URL in .env file.

**Comment by marcelowu** [comment]
![2020-05-13 10-28-43屏幕截图](https://user-images.githubusercontent.com/30912144/81818545-8b6ff700-9504-11ea-968a-75c5a4e866e0.png)

**Comment by marcelowu** [comment]
![2020-05-13 10-30-38屏幕截图](https://user-images.githubusercontent.com/30912144/81818764-d2f68300-9504-11ea-9928-75ca655ba98f.png)

**Comment by rahulcs0082** [comment]
Hi @marcelowu 

Your domain is **bagistopwa.local** and you are using **bagisto.local**.

**Comment by marcelowu** [comment]
sorry..
![2020-05-13 10-41-36屏幕截图](https://user-images.githubusercontent.com/30912144/81819966-5e244880-9506-11ea-9485-57c935e6545f.png)

**Comment by marcelowu** [comment]
![2020-05-13 10-48-43屏幕截图](https://user-images.githubusercontent.com/30912144/81820725-5a44f600-9507-11ea-9c98-8a24c0bf7259.png)
