### ISSUE TITLE
Edit Attribute -> Add Option or Swatch Item Error 404 for Indonesia(id) country code

### ISSUE THREAD

**Issue by otheriz** [bagisto/bagisto#3070]
# Bug report

### Title
Edit Attribute -> Add Option or Swatch Item Error 404 for Indonesia(id) country code

### Issue Description
Edit Attribute -> Add Option or Swatch Item Error 404 for Indonesia(id) country code

### Preconditions

    1.  framework Version- master

### Steps to reproduce
    1. add new locale with parameter Code : id
    2. add new option item on "Catalog -> attributes -> any item with type 'select'" then save

### Expected result
*   Save Successfully
![image](https://user-images.githubusercontent.com/11325840/81961816-1b18c100-963d-11ea-8333-4225f65640f7.png)

### Actual result

* Error 404 Page Not Found
![image](https://user-images.githubusercontent.com/11325840/81961896-31268180-963d-11ea-8bb0-54c68e49ffcb.png)

**Comment by vaishaliwebkul** [comment]
Hi @otheriz 
As reported on [forums](https://forums.bagisto.com/topic/1408/edit-attribute-add-option-or-swatch-item-error-404/14), issue is resolved.

So We're closing this.
