### ISSUE TITLE
HTML entities are not being decoded when editing attribute options

### ISSUE THREAD

**Issue by MattApril** [bagisto/bagisto#3073]
# Bug report

### Issue Description
When saving some text with an HTML entity (for example double quotes) in the admin forms (for example an attribute value), the values get saved to the database as an HTML entity. However, when loading that same value to edit, it does not get properly decoded back to its original character, instead it will load "10&quot;" in the text field. And if I save that value again without correcting, it will get encoded again in the database as "10&amp;quot;"

### Preconditions
    1. framework Version 1.1.2

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

1. Log in as admin
2. Edit an attribute
3. Go to "Options" section
4. save one of the name fields with a character that gets converted to an HTML entity (&, ", >, etc)
5. save the attribute
6. edit the attribute again

### Expected result
The HTML entity character should be loaded in its decoded form.

### Actual result

The character gets loaded into the form an as HTML entity, which causes it to get saved incorrectly.

**Comment by vaishaliwebkul** [comment]
@MattApril 
The issue is resolved now https://prnt.sc/sk8bhs.
Feel free to reopen the issue if it still exists.

**Comment by MattApril** [comment]
Thank you
