### ISSUE TITLE
after installation, first product registration does not open detailed page, I only opened from the second product

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#3087]
after installation, first product registration does not open detailed page, I only opened from the second product

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by rahulcs0082** [comment]
Hi @marcelowu 

Can you little bit explain more and it would be better for us if you will attach some screenshot?

**Comment by marcelowu** [comment]
![Screenshot from 2020-05-19 10-48-33](https://user-images.githubusercontent.com/30912144/82334661-a936d380-99be-11ea-8c9e-f3265c405351.png)
![Screenshot from 2020-05-19 10-50-56](https://user-images.githubusercontent.com/30912144/82334702-b653c280-99be-11ea-9eb0-cd372fbb99f2.png)
