### ISSUE TITLE
not getting price after changing configurable options

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#3089]
hi when every i change the color or size in a configurable product i get this error in my console :
```
velocity.js:2170 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'style' of null"

found in

---> <ProductOptions>
       <ProductView>
         <Root>
```
i checked i am getting the error because of this line : in configurable-options.blade.php
```
                 //on this line the element does not exit on page and causes error
          var priceLabelElement = document.querySelector('.price-label');
                            var priceElement = document.querySelector('.final-price');

                            if (this.childAttributes.length == selectedOptionCount) {
                                priceLabelElement.style.display = 'none';

                                priceElement.innerHTML = this.config.variant_prices[this.simpleProduct].final_price.formated_price;

                                eventBus.$emit('configurable-variant-selected-event', this.simpleProduct)
                            } else {
                        //this line        priceLabelElement.style.display = 'inline-block';

                                priceElement.innerHTML = this.config.regular_price.formated_price;

                                eventBus.$emit('configurable-variant-selected-event', 0)
                            }
```
is there any way that by chance i removed some tag unwanted and caused this error ?? thanks in advance

**Comment by vaishaliwebkul** [comment]
Hi @rahulcs0082 
I am still getting the same issue when update the configurable options
![Screenshot from 2020-05-20 11-07-21](https://user-images.githubusercontent.com/43210406/82408895-2e3aef00-9a8a-11ea-913d-e167ddbdfac6.png)

**Comment by rahulcs0082** [comment]
Hi @vaishaliwebkul 

Once run **php artisan vendor: publish** and then check for velocity.

**Comment by vaishaliwebkul** [comment]
@rahulcs0082 
previous error is removed but now getting this error

![Screenshot from 2020-05-21 16-36-24](https://user-images.githubusercontent.com/43210406/82553213-3de92f00-9b81-11ea-8766-53bb2cd288cd.png)

**Comment by vaishaliwebkul** [comment]
fixed
