### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by blackyzero** [bagisto/bagisto#3108]
Hello,

I did fresh install Bagisto, and got this error issue in browser console. The JS on website doesn't work.

> DevTools failed to load SourceMap

Please advice how to fix it. Thank you.

**Comment by vaishaliwebkul** [comment]
Hello @blackyzero 

Could you share the screenshot of website error ? 

Also this error will not break the functionality still if you want to remove the error go through with with this guide https://stackoverflow.com/questions/35002087/disable-source-maps-in-chrome-devtools

**Comment by jitendra-webkul** [comment]
No reply from last 14 days, I am closing this issue. Feel free to reopen
