### ISSUE TITLE
Product attributes/variant and specific quantities and prices

### ISSUE THREAD

**Issue by guestisp** [bagisto/bagisto#311]
For each product, support for attributes/variants each one with its own specific prices and quantities should be added.

In example, a product "T-Shirt" is sold in "red", "green" and "blue".
The red price is +2 USD than green price and there are 30 reds, 11 green and 4 blue in stock

**Comment by prashant-webkul** [comment]
I am getting a terrible feeling that you haven't used our **configurable product** in add new product form.

1. Login as **Admin**.
2. Click on **Catalog** from the side menu.
3. The click on **Products** find **Add Product** button in the content section.
4. A form with three fields will open up first:
a) Look for the field product type and select configurable product by default simple product is selected in that select box.
b) Then use attributes and create variants with default or custom attributes also.
c) All after you click on create button the list of the variants will be at the very bottom the screen.
d) Therefore each variant that you have created will be asking for name, price, weight, inventory quantities and status.

And then click on **Update Product**

**Comment by prashant-webkul** [comment]
Please be feel free to extend the conversation until your doubts are cleared.

**Comment by guestisp** [comment]
You are right, my mistake. I didn't use the configurable product. Usually, a configurable product is a different thing, in other ecommerce, so I didn't look at that.

**Comment by prashant-webkul** [comment]
Just keep it coming in future also.
Thanks for asking @guestisp
