### ISSUE TITLE
adding bulk discount on configurable variants

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#3111]
hi , i wanted to know the case where i want to add discount to all variants of a configurable product . i wonder to know how to do that because if i update the `product_flat` it just change the show of price and when user wants to pay it would be the same old price and i dont understand how its adding it in `product_attribute_values` in `float_value` coloumn i mean how the system detects which one is the special price or the original price . thanks in advance

**Comment by rahulcs0082** [comment]
Hi @farshadff 

You can create Catalog rule for the same ( Under Promotions Section ) using a required condition like name, SKU etc by which discount will be automatically applied on products and its variants.

**Comment by jitendra-webkul** [comment]
I hope above reply solved you problem. I am closing this issue
