### ISSUE TITLE
what are supper attributes

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#3114]
i need to make discount for all variants of a configurable product together in edit page i saw code i realized that super attributes comes to that page if they exist .so wonder to see if i can set the discount amount and from and to in all products super attribute so i can edit them from the same configurable product page , or in alternative way any way to add this 3 or any other field to that  rows of editing the simple variants in configurable admin  page . thanks

**Comment by vaishaliwebkul** [comment]
Hi @farshadff 
you can create catalog rule for configurable product or for it's variants by adding condition.
