### ISSUE TITLE
minify the velocity.js for gtmetrix

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#3115]
hi , i am running a site on bagisto velocity theme but when i inspect it in gtmetrix this 2 files show huge load time because they are not minified :
```
themes/velocity/assets/js/velocity.js
themes/velocity/assets/js/jquery.ez-plus.js
```
i wonder to know to minify them . can i minify them mannualy if they dont change on vue components or should i run` npm run pro`d in any special directory

**Comment by shubhwebkul** [comment]
You need to run **npm run watch** command inside the directory **packages/Webkul/Velocity** to watch your  vue-component changes.

**Comment by farshadff** [comment]
@shubhwebkul  thanks for the answer,
 but i needed to minify the `velocity.js`  for the performance of gtmetrix.
 if possible minifying other files too like jquery or other thing i can do it manually but if i do after every build it returns to unminified version.
