### ISSUE TITLE
Home page doesn't display categories and language bar doesn't work.

### ISSUE THREAD

**Issue by spyro-dennis** [bagisto/bagisto#3118]
# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by spyro-dennis** [comment]
I already add category and product on the admin panel but I can not see it on the frontend.

**Comment by vaishaliwebkul** [comment]
Hi @spyro-dennis 
please make sure the mail categories should be assign to root category else it will not display in front.

Also regarding the language bar could you show the screenshot.

**Comment by ilyasokay** [comment]
Language bar and category problem would be also because of the channel. You should link default channel with languages and categories. That will solve the problem.

**Comment by ilyasokay** [comment]
Actually, while enabling languages and adding categories, all should be added to default channel automatically, otherwise it will not be shown anywhere. Go check Settings -> Channels -> Edit Default and check if all languages are selected or not...

**Comment by vaishaliwebkul** [comment]
@spyro-dennis 
Hope above solution will work for you, we are closing this.

Feel free to reopen it anytime if still not resolved.
