### ISSUE TITLE
Shipments?

### ISSUE THREAD

**Issue by guestisp** [bagisto/bagisto#312]
Sorry for the silly question but.... where are shipments in backoffice ?
I didn't find any shipment management.......

**Comment by prashant-webkul** [comment]
@guestisp Please check the side menu, it is a sought of main subject wrapper.
There is a icon for sales click on it and you will find 3 more sub menu items for orders, shipments and invoices.

In the sales section you can manage orders like cancel or complete them, shipments will manage where to ship and how many quantities will get shipped while invoices will be same as of shipments but invoices just be a total of shipments costs and items delivered costs.

**Comment by guestisp** [comment]
Ok but how can I add a new carrier to use as shipment ?

**Comment by guestisp** [comment]
this one in the frontend:

![image](https://user-images.githubusercontent.com/3944655/49731756-ab9ae700-fc7c-11e8-9157-9e861326241e.png)

**Comment by ersaurav36** [comment]
@guestisp Currently we have these two options available. We will be very soon adding Aramex and Shipping Configuration Section in the next release.

**Comment by ersaurav36** [comment]
@guestisp Most probably by the end of next week we will be releasing the next release. The carriers are not hard coded. You can go on this file:https://github.com/bagisto/bagisto/blob/v0.1.2/config/carriers.php and just put 'active' => false, under free. In the next release, we will provide you with the UI to activate/deactivate the carriers.
