### ISSUE TITLE
 admin panel multi locale

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#3120]
This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by rahulcs0082** [comment]
Hi @marcelowu 

Kindly change language from .env file ( APP_LOCALE=en ) then test.

**Comment by marcelowu** [comment]
I want said language each user

**Comment by rahulcs0082** [comment]
Hi @marcelowu 

You can set the language for channel rather than for each user ( for front) and for backend need to follow the above solution and it could not be set for each user.

**Comment by marcelowu** [comment]
ok,  thanks
