### ISSUE TITLE
css files and js files not found

### ISSUE THREAD

**Issue by kamhawy4** [bagisto/bagisto#3129]
when finsh install wepsite .  css files and js files not found

http://bagisto.local/css/shop.css
http://bagisto.local/vendor/webkul/ui/assets/css/ui.css
//
http://bagisto.local/js/shop.js
http://bagisto.local/vendor/webkul/ui/assets/js/ui.js

![Screenshot (3)](https://user-images.githubusercontent.com/25951080/83072924-ddba2780-a06f-11ea-81a4-b9cf47ee2c3e.png)

**Comment by vaishaliwebkul** [comment]
Hi @kamhawy4 

run the following
>> npm i
>> npm run watch-poll
>> php artisan view:clear
>> php artisan route:cache
>> php artisan config:cache

**Comment by rahulcs0082** [comment]
Hi @kamhawy4 

Kindly run following command at Admin, Shop and UI packages.

`npm install`
 
once it gets completed, please run below one - 

`npm run watch-poll`

**Comment by kamhawy4** [comment]
@rahulcs0082  @vaishaliwebkul  These solutions did this but they don't work

**Comment by jitendra-webkul** [comment]
I hope above reply solved your issue. I am closing this issue for now, feel free to reopen.

**Comment by CesarObedFL** [comment]
hi, i have a similar issue with my page, css and js files don't work properly and when i try to install with npm install an error apears... 


`
.../packages/Webkul/Admin# npm install
loadDep:vee-validate → af ▄ ╢████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDevDep:vue-template-c ▐ ╢████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 4.15.0
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG
`

my site is : https://www.ceelaestiloyjoyeria.com/

please help
