### ISSUE TITLE
Lighthouse score is low

### ISSUE THREAD

**Issue by Sshuichi** [bagisto/bagisto#3130]
# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
Performance is a key metric for conversion. Right now, Lighthouse score is very low for the product page and the homepage. 
We could really improve our scores using lazy loading, new generation images, deferring JS and other.. 
https://demo.bagisto.com/bagisto-common/mens-polo-t-shirt

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Just run lighthouse on any page. 

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Go to https://demo.bagisto.com/bagisto-common/mens-polo-t-shirt
    2. Just run lighthouse on any page. 

### Expected result
**Tell us what should happen.**

Have +90 score for performance

### Actual result

>    30 as result

* [points....]

**Comment by sgatrip** [comment]
+1

https://demo.bagisto.com/bagisto-common/mens-polo-t-shirt    Performance 41%
it's bad

https://demo.bagisto.com/pwa-2a01e0a1156760c4eeb2f575ee5da7/mobile     51%
for the PWA version, the SEO is good....but performance must be increased

I have done a compare with vuestorefront / bagisto : for performance and SEO : vuestorefront is better

Thanks team to increase theses points

**Comment by vaishaliwebkul** [comment]
@Sshuichi @sgatrip 
Thanks for reporting the performance measure report.
We will implement this.

Also hope for your contribution(PR) for the same to implement it together.
