### ISSUE TITLE
Velocity theme responsiveness issue after changing the language to Arabic RTL

### ISSUE THREAD

**Issue by aayush-webkul** [bagisto/bagisto#3131]
# Bug report

### Responsiveness issue after changing the locale to Arabic RTL
**After opening the website in chrome browser in mobile, I am not able to swipe the products from right to left In the homepage product section**
**Even after enabling "Desktop Mode" the browser, it's not working the way it is supposed to work.**
**Same issue is in the, Address page.**

### Preconditions

    1. Bagisto v1.0.0 or above.

### Steps to reproduce
**To reproduce the issue**

    1. Open Bagisto in your mobile ( Chrome browser ).
    2. In the velocity theme front end, change the language to Arabic RTL.
    3. Scroll down to product section and try to swipe the products from right to left.

### Expected result
**It should get swiped from right to left without an issue. **

### Actual result

>    **https://www.dropbox.com/s/5ffx56chdowp36a/VID_20200527_003346.mp4?dl=0**

**Comment by vaishaliwebkul** [comment]
fixed
