### ISSUE TITLE
How can I cad comment box in checkout form.

### ISSUE THREAD

**Issue by akshaypitale** [bagisto/bagisto#3135]
Hi,

How can I add comment box on checkout page so that customer can add comment for every order he/she place. And want to show the comment on admin panel sales dashboard so that admin can check comment for every order.

Thanks in advance.

![image](https://user-images.githubusercontent.com/23078428/83145349-48bc3a80-a112-11ea-9880-4ec923232020.png)

**Comment by rahulcs0082** [comment]
Hi @akshaypitale 

First of all, you need to override view file to add comment field, follow the given link for same - https://forums.bagisto.com/topic/221/how-to-override-view-file-in-bagisto/2

Add a '**comment**' column in the addresses table and override this table to add fillable value.

The second way is to create a new table for the same, override view files and create the same name route for save address (LIke Shop ) which calls your packages controller and insert value in the newly created table along with save address functionality.

**Comment by akshaypitale** [comment]
Thanks for the help.


> Hi @akshaypitale
> 
> First of all, you need to override view file to add comment field, follow the given link for same - https://forums.bagisto.com/topic/221/how-to-override-view-file-in-bagisto/2
> 
> Add a '**comment**' column in the addresses table and override this table to add fillable value.
> 
> The second way is to create a new table for the same, override view files and create the same name route for save address (LIke Shop ) which calls your packages controller and insert value in the newly created table along with save address functionality.

Thanks for the help.
