### ISSUE TITLE
configurable product variant name gets removed from the catalog list

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3136]
# Bug report

### Title
configurable product variant name gets removed from the catalog list

### Issue Description
configurable product variant name gets removed from the catalog list

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- create configurable product with min 4 variant options
    2. step2- edit and back to the product list again.

### Expected result
All variants name should be visible 

### Actual result
   
![Screenshot (4)](https://user-images.githubusercontent.com/43210406/83157666-7fe61800-a121-11ea-87ad-f9eb99ca4403.png)

**Comment by shubhwebkul** [comment]
same as #3207
