### ISSUE TITLE
Is there any way to add "Order sample product" functionality?

### ISSUE THREAD

**Issue by akshaypitale** [bagisto/bagisto#3137]
Hi There,

I have added "Order sample product button" button below add to cart button.
I am setting sample product price through attributes.
When a customer clicks on order sample product the same product should added to cart but different price.

Thanks in advance.

![bagisto-add-to-cart](https://user-images.githubusercontent.com/23078428/83229064-f415cf80-a1a4-11ea-931f-d3cab8702316.PNG)

**Comment by shubhwebkul** [comment]
Feel free to reopen if you still have any query.
