### ISSUE TITLE
While creating a category , it gives an error

### ISSUE THREAD

**Issue by dhirraj** [bagisto/bagisto#3139]
# Bug report

### Title
While creating a category , it gives an error

### Issue Description
through Admin Account: 
Go to catalogue -> Add Category

After saving, it gives an error 
Screenshot attached [
![Screenshot 2020-05-29 at 8 17 01 PM](https://user-images.githubusercontent.com/60727983/83273137-c56e1800-a1e9-11ea-8d23-d94b79e65c93.png)
](url)

**Comment by alessiobulfaro** [comment]
I encountered the same mistake ...
The problem is the collation of your database.
Create the database in utf8_general_ci and see that you should no longer have this error.

**Comment by vaishaliwebkul** [comment]
Hi @dhirraj 
you can follow above solution it will work, also for more help go through with this solution https://github.com/bagisto/bagisto/issues/2562

**Comment by vaishaliwebkul** [comment]
Hi @dhirraj 
Hope your issue is resolved.

Feel free to reopen it anytime if still not resolved.

**Comment by mzakirhossain** [comment]
Here is my experienced how I resolved .. 

taken list of all table with append alter script to convert ..

`SELECT CONCAT('ALTER TABLE ', TABLE_NAME, ' CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;') FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'mydatabasename' AND TABLE_TYPE != 'VIEW';
`

and run scripts here is all of table alter scripts..

`ALTER TABLE velocity_meta_data CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_images CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_downloadable_sample_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE booking_product_event_tickets CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE refund_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE invoices CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE mp_delivery_time_slots_orders CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE dropship_ali_express_products CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE tax_categories CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE booking_product_appointment_slots CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE attributes CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_cross_sells CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_rule_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE booking_product_table_slots CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE customer_addresses CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_ordered_inventories CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE wishlist CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_reviews CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_flat CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE password_resets CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE currency_exchange_rates CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_rule_customers CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE admins CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_bundle_option_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE refunds CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_attribute_values CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_inventories CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE shipment_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_rules CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE attribute_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE channel_currencies CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE catalog_rule_customer_groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_bundle_option_products CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_shipping_rates CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cms_pages CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_downloadable_link_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE category_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_order_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE pre_order_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cms_page_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_rule_customer_groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE customer_groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE core_config CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE booking_products CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_rule_coupon_usage CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE dropship_ali_express_orders CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE channel_inventory_sources CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE tax_rates CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE dropship_ali_express_attribute_options CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_rule_channels CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_relations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE shipments CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE migrations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE attribute_options CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE orders CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE country_state_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE attribute_groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE users CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE roles CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE tax_categories_tax_rates CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_sellers CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE downloadable_link_purchased CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_refunds CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cms_page_channels CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE locales CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE sliders CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE velocity_contents_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_address CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE channel_locales CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_refund_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_bundle_options CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_up_sells CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE currencies CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE catalog_rule_products CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE attribute_option_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_categories CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_orders CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE order_payment CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE dropship_ali_express_product_reviews CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE catalog_rule_product_prices CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE order_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_shipment_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE velocity_customer_compare_products CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE channels CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE country_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_product_images CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_downloadable_samples CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE attribute_group_mappings CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE dropship_ali_express_product_images CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE subscribers_list CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE admin_password_resets CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE products CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE dropship_ali_express_attributes CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE country_states CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE bookings CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE order_brands CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE categories CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_grouped_products CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE invoice_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE category_filterable_attributes CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_downloadable_links CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_transactions CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_invoices CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE booking_product_rental_slots CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_item_inventories CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE customer_password_resets CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_seller_reviews CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE dropship_ali_express_order_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE inventory_sources CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_products CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE booking_product_event_ticket_translations CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE product_super_attributes CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE countries CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE catalog_rule_channels CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE order_address CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE booking_product_default_slots CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_invoice_items CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE customers CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE mp_delivery_time_slots CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_payment CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE marketplace_shipments CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE attribute_families CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE catalog_rules CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE cart_rule_coupons CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE velocity_contents CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;	
ALTER TABLE push_notifications CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
`
