### ISSUE TITLE
error if selecting only one currency

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#3144]
error if selecting only one currency

![Screenshot from 2020-05-30 01-11-30](https://user-images.githubusercontent.com/30912144/83319274-6624fd80-a213-11ea-87d3-8fb7f2c837ae.png)
![Screenshot from 2020-05-30 01-12-38](https://user-images.githubusercontent.com/30912144/83319278-6a511b00-a213-11ea-9394-249903944d0f.png)

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by alnouirah** [comment]
i had this problem before . and the solution was to choose all the currency from Currencies menu select and with Default Currency select menu choose the currency that you want to use in your website 👍 .

**Comment by marcelowu** [comment]
I didn't want multi Currencies , BRL only

**Comment by alnouirah** [comment]
In this case there's a bug . you can delete unwanted currency from mysql directly but it's not a good idea. I think if they solved this issue it will be better.

**Comment by marcelowu** [comment]
This problem needs to be solved，I only need one currency，BRL

**Comment by marcelowu** [comment]
php7.3 to php7.2 solved .

**Comment by marcelowu** [comment]
is work, have to exclude other currencies

**Comment by marcelowu** [comment]
delete other currencies and registered product, Default domain  it works.
other domain it doesn't work,(multi canal)

![Captura de tela de 2020-06-04 23-08-06](https://user-images.githubusercontent.com/30912144/83828992-4b8dd100-a6b8-11ea-8376-6ba5bc71530d.png)
