### ISSUE TITLE
Attribute not showing on the creating new configurable product page

### ISSUE THREAD

**Issue by IvalinV** [bagisto/bagisto#3150]
# Bug report

### Title
Attribute not showing on the creating new configurable product page

### Issue Description
When I create new attribute and set the "Use To Create Configurable Product" option
![image](https://user-images.githubusercontent.com/20267863/83352915-937ac400-a357-11ea-83cd-68e98e03963e.png)

It does not show when I try to create new configurable product

![image](https://user-images.githubusercontent.com/20267863/83352950-d5a40580-a357-11ea-953e-2eb6f052fd5a.png)

### Preconditions

    1. Version v1.1.2

**Comment by vaishaliwebkul** [comment]
Hi @IvalinV 
create select type attribute to create configurable options, then it will be showing on configurable product page.

**Comment by IvalinV** [comment]
Hi @vaishaliwebkul that is exactly what I'm doing, I can use already created attributes and they indeed  are showed on the create product page, when I create **new select type** attribute and choose the option  "Use To Create Configurable Product" it did not show up on the products page when I creating it.

**Comment by vaishaliwebkul** [comment]
@IvalinV 
have you added that select type attribute in attribute family??

**Comment by IvalinV** [comment]
@vaishaliwebkul  No, I did not added and that was the one thing I was missing, it is working properly now, thank you for your help !

**Comment by jitendra-webkul** [comment]
Did you add that attribute to attribute family?

**Comment by IvalinV** [comment]
@jitendra-webkul Yes and now is working as expected
