### ISSUE TITLE
Tax rate not being applied

### ISSUE THREAD

**Issue by tabonedaryl** [bagisto/bagisto#3155]
A tax rate and tax category have been created in the online portal, however when retrieving data using the products API call the tax rate is always 0 and the base_tax_total is always 0 as well.

**Comment by SteffenMahler** [comment]
@tabonedaryl can yyou provide more information?

How is the:
- tax category
- tax rate
- product
configured?

What is your config/app.php key 'default_country' looks like?

**Comment by tabonedaryl** [comment]
I have updated the default_country field in the app.php and the tax rate is now working. However, when using the checkout/save-address call, the tax rate is being reset to 0. This problem does not happen when using the checkout/save-payment call.

**Comment by SteffenMahler** [comment]
If you call save-address, does the customers country code and postcode matches the configured tax rate?

**Comment by vaishaliwebkul** [comment]
@tabonedaryl 
No response from last too many days so we are closing this.

Feel free to reopen it anytime.
