### ISSUE TITLE
checkout/save-address always creating new address

### ISSUE THREAD

**Issue by tabonedaryl** [bagisto/bagisto#3156]
I am using the checkout/save-address call, however, when a user is logged in the user is choosing an already existing address but a new address is always being created. This results with a new address in the address book every time this method is used.

**Comment by vaishaliwebkul** [comment]
Hi @tabonedaryl 
you need to update/pull the bagisto with master branch to resolve this issue.

**Comment by tabonedaryl** [comment]
> Hi @tabonedaryl
> you need to update/pull the bagisto with master branch to resolve this issue.

I have installed the Bagisto API only a couple of weeks ago so I am using the latest version (v1.1.2).

**Comment by vaishaliwebkul** [comment]
@tabonedaryl 
this is fixed in master branch so you can update the code with this commit https://github.com/bagisto/bagisto/commit/b42ccbfa9e719c8526b249bbfef1951a894d0705

**Comment by tabonedaryl** [comment]
I have updated the code with that commit and the original issue has been solved. However, when using the checkout/save-address call the tax-rate is always being reset to 0% in the order.

**Comment by vaishaliwebkul** [comment]
@tabonedaryl 
In this case, address zip code should be matched with the tax rate, else it will get reset to 0%

**Comment by vaishaliwebkul** [comment]
@tabonedaryl 
Hope this will work for you!

Feel free to reopen the issue if still not fixed.
