### ISSUE TITLE
 Column not found: 1054 Unknown column 'symbol' in 'field l

### ISSUE THREAD

**Issue by RishikantSri** [bagisto/bagisto#3158]
# Bug report

In Connection.php line 669:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'symbol' in 'field l
  ist' (SQL: insert into `currencies` (`code`, `id`, `name`, `symbol`) values
   (USD, 1, US Dollar, $), (EUR, 2, Euro, €))

In PDOConnection.php line 63:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'symbol' in 'field l
  ist'

In PDOConnection.php line 61:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'symbol' in 'field l
  ist'

**Comment by shubhwebkul** [comment]
Same as #/3159
