### ISSUE TITLE
On hitting this command we got this issue :

### ISSUE THREAD

**Issue by RishikantSri** [bagisto/bagisto#3159]
$ php artisan db:seed
Seeding: Webkul\Admin\Database\Seeders\DatabaseSeeder
Seeding: Webkul\Category\Database\Seeders\DatabaseSeeder
Seeding: Webkul\Category\Database\Seeders\CategoryTableSeeder
Seeded:  Webkul\Category\Database\Seeders\CategoryTableSeeder (0.41 seconds)
Seeded:  Webkul\Category\Database\Seeders\DatabaseSeeder (0.43 seconds)
Seeding: Webkul\Inventory\Database\Seeders\DatabaseSeeder
Seeding: Webkul\Inventory\Database\Seeders\InventoryTableSeeder
Seeded:  Webkul\Inventory\Database\Seeders\InventoryTableSeeder (0.24 seconds)
Seeded:  Webkul\Inventory\Database\Seeders\DatabaseSeeder (0.26 seconds)
Seeding: Webkul\Core\Database\Seeders\DatabaseSeeder
Seeding: Webkul\Core\Database\Seeders\LocalesTableSeeder
Seeded:  Webkul\Core\Database\Seeders\LocalesTableSeeder (0.3 seconds)
Seeding: Webkul\Core\Database\Seeders\CurrencyTableSeeder

In Connection.php line 669:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'symbol' in 'field list' (SQL: insert into `currencies` (`code`, `id`, `name`, `symbol`) values (USD, 1, US Dollar, $), (EUR, 2, Eur
  o, €))

In PDOConnection.php line 63:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'symbol' in 'field list'

In PDOConnection.php line 61:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'symbol' in 'field list'

**Comment by shubhwebkul** [comment]
Execute command **_php artisan migrate_** before executing _**php artisan db:seed**_ command.

Let me know if you're still facing issue.

**Comment by shubhwebkul** [comment]
Feel free to reopen this if you still face issue
