### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by wasifiqbal1990** [bagisto/bagisto#3161]
# Bug report

### Title
**When any seller tries to create a product in the system from the frontend i got this error**
****

### Issue Description
**I checked on the issues and it was mentioned to update it to the latest version and till will fix the issue, i did updated to the latest version but its still showing me the same error**

### Preconditions
**Please provide as detailed information about your environment as possible.**

- PHP v7.4
- Bagisto updated to latest

### Steps to reproduce
**You can re-product this by doing the following**

    1. create any new seller
    2. Go to his profile 
    3. Add product (this will be saved after validation on SKU)
   4. Fill the second form and this will generate the error. 

### Expected result
**Expected result should be it create the product**

*   [Screenshots, logs or description]
![screenshot-multivendor test-2020 06 02-12_29_36](https://user-images.githubusercontent.com/25728571/83492642-03f72180-a4cd-11ea-9d25-fa04c9015453.png)

![screenshot-multivendor test-2020 06 02-12_31_23](https://user-images.githubusercontent.com/25728571/83492665-0b1e2f80-a4cd-11ea-9934-d752077f61e4.png)

**Comment by vaishaliwebkul** [comment]
Hi @wasifiqbal1990 
You can raise the support ticket regarding this query here https://bagisto.uvdesk.com/en/customer/create-ticket/

Thanks

**Comment by wasifiqbal1990** [comment]
I have submitted the ticket but i checked and this issue was reported earlier and was asked to update bagisto to latest version and this will be fixed. I did that but I am still facing that issue.

**Comment by vaishaliwebkul** [comment]
@wasifiqbal1990 
Yes right the same issue is already raised here many times, and resolved when update to the bagisto v1.1.2  but in your case marketplace is also installed which also need to be update.

Thanks

**Comment by vaishaliwebkul** [comment]
@wasifiqbal1990 
Hope your query is being resolved at https://bagisto.uvdesk.com/en/
so we are closing this issue.

Thanks.
