### ISSUE TITLE
Edit Cart Item

### ISSUE THREAD

**Issue by ymymym** [bagisto/bagisto#3170]
Is there any way to edit a cart item after it's added to the cart?

**Comment by vaishaliwebkul** [comment]
@ymymym 
you can update the item quantity or remove item from cart once it's added to the cart.

**Comment by ymymym** [comment]
Is there any way to edit a bundle item? Not just the quantity

**Comment by shubhwebkul** [comment]
No, you need to readd the product to the cart.

Let me know if you've any further query.
