### ISSUE TITLE
Custom Attributes not showing on product detail page.

### ISSUE THREAD

**Issue by sandeep-ed** [bagisto/bagisto#3182]
Hello There,

I am creating a store for jewellery product and added around 20 new attributes and assigned that in default family attributes showing in admin when adding or editing product bit not showing on front end in default theme also I created a scheduler to update product price on the basis of daily gold price but when fetching attributes to calculate price its not showing my custom attributes I am using productRepository to fetch  all products with ita attributes

**Comment by rahulcs0082** [comment]
Hi @elite-digital 

While creating or editing attributes, set yes to **Visible on Product View Page on Front-end** to show it on front-end (https://prnt.sc/svo9e1).

You can get attribute family using the product model and from it, can get custom attributes for the given family while updating the price.

**Comment by elite-digital** [comment]
I want custom attribute for every product based on that I will calculate final price of jewelry product and update in product flat table. 

Please let me know how I will get all products with all its attributes.

Thank You

**Comment by elite-digital** [comment]
Hi Rahul,

As per your suggestion, First I update attribute show in flat table then its started showing product repository and I updated the final price in product_flat table and in admin product listing page its showing updated price while when editing product its showing different price also its showing different price on frontend too. Please check screenshots
![image](https://user-images.githubusercontent.com/8210369/84461343-ddce4000-ac89-11ea-8f68-d17195fd49ff.png)
![image](https://user-images.githubusercontent.com/8210369/84461774-e8d5a000-ac8a-11ea-931a-de9f8ae10def.png)
