### ISSUE TITLE
Site showing blank page on 404 

### ISSUE THREAD

**Issue by elite-digital** [bagisto/bagisto#3184]
Hi ,

When some one typing wrong URL of my site its showing Blank page with 404 in title bar

**Comment by vaishaliwebkul** [comment]
Hi @elite-digital 

could you please attach the screenshot.

**Comment by elite-digital** [comment]
![image](https://user-images.githubusercontent.com/8210369/84012323-fe01b480-a994-11ea-9265-dc8ade08b980.png)

**Comment by shubhwebkul** [comment]
Hello there,

We are not facing such kind of issue in any theme

![Screenshot from 2020-06-09 11-32-38](https://user-images.githubusercontent.com/41280839/84111677-116c5880-aa45-11ea-829a-e833b834ccc4.png)
![Screenshot from 2020-06-09 11-32-34](https://user-images.githubusercontent.com/41280839/84111684-13ceb280-aa45-11ea-9fdf-adf09e4ff592.png)

**Comment by vaishaliwebkul** [comment]
@elite-digital 
Hope the provided solution worked for you.
