### ISSUE TITLE
succespage, After a transaction, where it changes?

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#3185]
where it changes
After a transaction, we will redirect the traffic to this URL. For example: 'https://demo.vuestorefront.io/succespage'
--

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by shubhwebkul** [comment]
After placing successful order
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php#L479

**Comment by marcelowu** [comment]
thanks
