### ISSUE TITLE
Implement a functionality of customer view in admin account, so that by just clicking on it front-end for that account will open.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#319]
Framework Version: 0.1.2

![screenshot 1](https://user-images.githubusercontent.com/45203177/50005790-9e119400-ffd1-11e8-903c-35a4ba4b114a.png)

**Comment by prashant-webkul** [comment]
This had been implemented and will come up in the next release.

**Comment by Jyoti-Singh1** [comment]
Framework Version:0.1.4
Implemented
