### ISSUE TITLE
Bagisto v1.1.2 velocity responsive theme issue on iPhone and iPads 

### ISSUE THREAD

**Issue by DevBala-6** [bagisto/bagisto#3191]
![897D463C-7EC4-4501-BDC6-E11C45C2E027](https://user-images.githubusercontent.com/55074296/84059574-76d63000-a9d8-11ea-9754-1f5f2d56dea1.png)

Bagisto v1.1.2 velocity responsive theme layout not working perfectly on iPad and iPhone ..anyone??

**Comment by vaishaliwebkul** [comment]
@DevBala-6 
this is the actual design in responsive layout, we are not getting any design issue in the attached screenshot.

Thanks
