### ISSUE TITLE
Getting exception when click on product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3199]
# Bug report

### Title
Getting exception when click on product.

### Issue Description
Getting exception when click on product.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-master

### Steps to reproduce

    1. step1- click on product to view

### Expected result
Product page should get open

### Actual result

![Workspace 1_045](https://user-images.githubusercontent.com/45203177/84152242-01bf3500-aa82-11ea-9936-7304cf814cd1.png)

**Comment by shivam-webkul** [comment]
b8c1985beb8b9a3bf173279755050270371263e7

fixed

**Comment by jyoti-webkul** [comment]
- Fixed

--------------------

![Workspace 1_084](https://user-images.githubusercontent.com/45203177/84568664-9f767500-ad9e-11ea-99f2-7baa01791590.png)
