### ISSUE TITLE
Getting exception in creating grouped product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3202]
# Bug report

### Title
Getting exception in creating grouped product.

### Issue Description
Getting exception in creating grouped product.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.- master
   

### Steps to reproduce

    1. step1- create a grouped product

### Expected result

Product should create

### Actual result

![Workspace 1_046](https://user-images.githubusercontent.com/45203177/84163184-d1ca5e80-aa8e-11ea-86bb-524e67ae8b31.png)

**Comment by jyoti-webkul** [comment]
- Not fixed

-------------------------------------

![Workspace 1_088](https://user-images.githubusercontent.com/45203177/84569244-adc69000-ada2-11ea-90fe-40f356b7befb.png)

**Comment by vaishaliwebkul** [comment]
fixed
