### ISSUE TITLE
Getting translation issue in price field of downloadable product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3203]
# Bug report

### Title
Getting translation issue in price field of downloadable product.

### Issue Description
Getting translation issue in price field of downloadable product.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-master

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1-Create a downloadable product 
    2. step2- Leave price field blank in customer group section and save.

### Expected result
Error message should be correct

### Actual result

![Workspace 1_047](https://user-images.githubusercontent.com/45203177/84164818-9af54800-aa90-11ea-8c6e-aa0acb31a93f.png)

**Comment by jyoti-webkul** [comment]
- Not fixed

----------------------

![Screenshot (41)](https://user-images.githubusercontent.com/45203177/84569468-72c55c00-ada4-11ea-9be6-0a46ba303ea5.png)

**Comment by vaishaliwebkul** [comment]
fixed
