### ISSUE TITLE
Getting exception when changing currency from search page.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3204]
# Bug report

### Title
Getting exception when changing currency from search page.

### Issue Description
Getting exception when changing currency from search page.

### Preconditions
    1. framework Version.- master

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1- Search a product.
    2. step2- change the currency

### Expected result
Currency should get changed

### Actual result
Getting exception
![Workspace 1_048](https://user-images.githubusercontent.com/45203177/84165431-528a5a00-aa91-11ea-89d0-44a51c449327.png)

**Comment by jyoti-webkul** [comment]
- Not fixed

---------------------

![Workspace 1_086](https://user-images.githubusercontent.com/45203177/84568797-86ba8f00-ad9f-11ea-8cbb-6e7ae339edab.png)

**Comment by shubhwebkul** [comment]
Have you executed **php artisan vendor:publish --force** command ?

**Comment by jyoti-webkul** [comment]
- Fixed

------------------------

![Workspace 1_109](https://user-images.githubusercontent.com/45203177/84898075-4bcc9a00-b0c4-11ea-97b2-753095574870.png)
