### ISSUE TITLE
Filter cart UI issue when Searching in any datagrid.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#321]
Framework Version: o.1.2
Unable to search product if exact name is not entered in search box.
If there is space between the product name then in search field it displays %20 in place of space
![screenshot 12](https://user-images.githubusercontent.com/45203177/50041946-bd1c2e80-0082-11e9-98ae-de81f320134e.png)

**Comment by prashant-webkul** [comment]
This issue will be system wide in all the datagrids when we search some string with spaces or whitespaces.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot 78](https://user-images.githubusercontent.com/45203177/52122003-94a6be80-2647-11e9-8223-6d11e8da4c85.png)
