### ISSUE TITLE
Taking more time to update the product status.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3211]
# Bug report

### Title
Taking more time to update the product status.

### Issue Description
Taking more time to update the product status.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-master

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1-Go to product grid and select 3 to 4 product 
    2. step2- click on mass update

### Expected result
Product status should get update within seconds

### Actual result
Taking more time than expected

**Comment by vaishaliwebkul** [comment]
https://github.com/bagisto/bagisto/issues/3280 memory issue
