### ISSUE TITLE
virtual product not shipping step..

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#3218]
# Bug report
![Captura de tela de 2020-06-10 19-05-57](https://user-images.githubusercontent.com/30912144/84324548-3f3dc400-ab4f-11ea-93ce-3b8a3d882543.png)

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by vaishaliwebkul** [comment]
@marcelowu 
virtual products don't have physical existence so their is no shipping.

**Comment by marcelowu** [comment]
but the velocite theme does not go to payment without shipping

**Comment by vaishaliwebkul** [comment]
@marcelowu 
please mention the bagisto version in which you're facing such kind of issue.

Also Is there any console error in the checkout?

**Comment by marcelowu** [comment]
bagisto-standard
