### ISSUE TITLE
Guest coupon code cannot be used for general users

### ISSUE THREAD

**Issue by ymymym** [bagisto/bagisto#3227]
Guest coupon code shows 'Coupon code is invalid.' after using for general user.

**Comment by vaishaliwebkul** [comment]
Hi @ymymym 

select 'guest' group in cart rule to allow coupons for guest users.

https://prnt.sc/t0ukei

https://prnt.sc/t0ukoj

**Comment by ymymym** [comment]
Hi @vaishaliwebkul ,

Thanks for replying. Try to log in an account and apply the coupon code again.

**Comment by vaishaliwebkul** [comment]
@ymymym 
for login user, the coupon code will work if a customer group or cart rule group should be matched.

Feel free to ask any query! 
Thanks
