### ISSUE TITLE
Redirect to my profile from checkout page after login

### ISSUE THREAD

**Issue by elite-digital** [bagisto/bagisto#3230]
Hi Team, 
I think its not customer friendly and business owner loos customer that system suddenly redirect to my profile from checkout page after login. It should be on same page so that users could complete their order. Please help me to solve this issue user must redirect same page from where he loggedin.

Thank you

**Comment by vaishaliwebkul** [comment]
Hi @elite-digital 
This is working as expected.
![Screenshot (45)](https://user-images.githubusercontent.com/43210406/84876886-66dbe180-b0a5-11ea-9ed8-5a228201e840.png)
