### ISSUE TITLE
homepage is showing 404 error page in both theme

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3232]
# Bug report

### Title
homepage is showing 404 error page in both theme

### Issue Description
homepage is showing 404 error page in both theme

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- visit shop

### Actual result

![Screenshot from 2020-06-12 21-39-45](https://user-images.githubusercontent.com/43210406/84523022-469ed200-acf5-11ea-9951-6ee2be4d908c.png)

**Comment by ghermans** [comment]
@vaishaliwebkul  I can not reproduce this issue, see screenshot below

![HomePageKnipsel](https://user-images.githubusercontent.com/1594411/84606699-8a860880-aea8-11ea-9db0-e571f2e42bfc.JPG)

**Comment by vaishaliwebkul** [comment]
Not getting this issue on fresh installation.
