### ISSUE TITLE
Product image zoom on  hover Effect not working.

### ISSUE THREAD

**Issue by musabibnusiraj** [bagisto/bagisto#3233]
# Bug report

Product image zoom on hover Effect not working.
### Expected result

![image](https://user-images.githubusercontent.com/47845204/84552902-f85af480-ad2f-11ea-81fe-3280644ac2c2.png)

### Actual result

![image](https://user-images.githubusercontent.com/47845204/84552799-ce093700-ad2f-11ea-98ec-5f7e22ff01cc.png)

**Comment by shubhwebkul** [comment]
Hello there,

We are not facing such type of issue. please share your website url if you are still facing issue.

**Comment by musabibnusiraj** [comment]
Bagisto Demo -  Site

**Comment by shubhwebkul** [comment]
https://www.loom.com/share/2d13fd25988a48839eb0dd4b7faf39a2

please check

**Comment by musabibnusiraj** [comment]
Yes, It's working fine.
