### ISSUE TITLE
Options of attribute not display as per its position

### ISSUE THREAD

**Issue by elite-digital** [bagisto/bagisto#3237]
Hi There,

I added a new option for blank value in Color attribute and given position 1 to is but when adding products its by default selected a value that is on top in backend. While it should show Select option which has first position. Please check screen shot.

![image](https://user-images.githubusercontent.com/8210369/84589627-8aa4ea80-ae4d-11ea-92ab-87171e1c9bdf.png)

![image](https://user-images.githubusercontent.com/8210369/84589637-9db7ba80-ae4d-11ea-8fb3-0d4bce2d4d06.png)

Please let me know how we can fix that

**Comment by jitendra-webkul** [comment]
Fixed in #3258

**Comment by vaishaliwebkul** [comment]
@elite-digital 
it's fixed.

Feel free to reopen it anytime.
