### ISSUE TITLE
Change the Button title "Create Tax Rate" to "Save Tax Rate" on Tax Rate page.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#324]
Framework Version: 0.1.2
![screenshot 13](https://user-images.githubusercontent.com/45203177/50042130-b7741800-0085-11e9-8c90-e043091c33db.png)

**Comment by rahulshukla-webkul** [comment]
Changed Button title.

**Comment by Jyoti-Singh1** [comment]
Not Fixed
Framework Version: 0.1.3

**Comment by Jyoti-Singh1** [comment]
Framework Version:0.1.4
Fixed
