### ISSUE TITLE
Email settings are empty in backend

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3243]
# Bug report

### Issue Description
When going to **Configure** the **email settings** fields are empty.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master branch.

### Steps to reproduce

    1. Login to the backend
    2. Go to Configure
    3. You will notice that the email settings fields are empty

### Expected result
The fields should contain the same info from **config/mail.php**

### Actual result

![EmailKnipsel2](https://user-images.githubusercontent.com/1594411/84636960-816f5880-aef5-11ea-9b86-22078279ca9a.PNG)

**Comment by vaishaliwebkul** [comment]
@ghermans 
It's fixed now.

Feel free to reopen it if it's not resolved.
Thanks
