### ISSUE TITLE
Pass valid variable when dispatch an event

### ISSUE THREAD

**Issue by autn** [bagisto/bagisto#3264]
# Bug report

### Title
**Pass array to an event dispatch by right way**

### Issue Description
**The current variables are passed to dispatch function by wrong way, please change to right way**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: 1.1.2

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Dispatch an event, and pass an array into that, i.e. Event::dispatch('checkout.order.orderitem.save.before', $data);
    2. Listen above event

### Expected result
**Receive the $data as an array**

### Actual result

>    **Just receive the first param of the array**

* Please change to something like Event::dispatch('checkout.order.orderitem.save.before', [$data]);

**Comment by jitendra-webkul** [comment]
Not feasible
