### ISSUE TITLE
showing configurable product base on catalog rule price

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#3269]
hi , i want to make like 30% percent discount for all products in site which i do it with catalog rule but when i come to home page or category page for all configurable products i see the old price without any discount applied to it .
now when i go to product page and choose variants the discount is now applied to the price . 
now my question is can i show the discounted price before user selects variants so he/she understand that this prodoct has discount and  the old price place a line on it and under that show the price on discount  . thanks in advance

**Comment by vaishaliwebkul** [comment]
@farshadff 
Currently this functionality for configurable product is not possible.

Thanks

**Comment by irisda** [comment]
Do you have any estimation when this feature will be present?

**Comment by farshadff** [comment]
i my self am working on it if i could achieve this i update this thread so you can use it

**Comment by irisda** [comment]
What happens if we add as special price for configurable product?are you looking on this solution too?

**Comment by farshadff** [comment]
that would be nice too because many stores like mine all the color and sizes are the same price :)

**Comment by irisda** [comment]
yes, but are you looking on this?have you done anything?

**Comment by farshadff** [comment]
i guess adding special price for configurable product is not good because it may conflict with the rest logic of system . currently i am working on it if i can add the configurable id to catelogRuleproduct 
```
 public function getMatchingProductIds($rule, $product = null)
    {
        $qb = $this->productRepository->scopeQuery(function($query) use($rule, $product) {
            $qb = $query->distinct()
                        ->addSelect('products.*')
                        ->leftJoin('product_flat', 'products.id', '=', 'product_flat.product_id')
                        ->leftJoin('channels', 'product_flat.channel', '=', 'channels.code')
                        ->whereIn('channels.id', $rule->channels()->pluck('id')->toArray());

            if ($product) {
                $qb->where('products.id', $product->id);
            }

            if (! $rule->conditions) {
                return $qb;
            }

            $appliedAttributes = [];

            foreach ($rule->conditions as $condition) {
                if (! $condition['attribute']
                    || ! isset($condition['value'])
                    || is_null($condition['value'])
                    || $condition['value'] == ''
                    || in_array($condition['attribute'], $appliedAttributes)
                ) {
                    continue;
                }
                
                $appliedAttributes[] = $condition['attribute'];

                $chunks = explode('|', $condition['attribute']);

                $qb = $this->addAttributeToSelect(end($chunks), $qb);
            }

            return $qb;
        });

        $validatedProductIds = [];

        foreach ($qb->get() as $product) {
            if (! $product->getTypeInstance()->priceRuleCanBeApplied()) {
                continue;
            }

            if ($this->validator->validate($rule, $product)) {
                if ($product->getTypeInstance()->isComposite()) {
                    $validatedProductIds = array_merge($validatedProductIds, $product->getTypeInstance()->getChildrenIds());
                } else {
                    $validatedProductIds[] = $product->id;
                }
            }
        }

        return array_unique($validatedProductIds);
    }
``` 
then i can have the configurable product id saved in catalog rule so i can show the price in frontend

**Comment by farshadff** [comment]
dont know if its gonna work or not but i am now trying this.

**Comment by irisda** [comment]
Does this solution works on your end or not?

**Comment by farshadff** [comment]
dont know yet i am trying it

**Comment by irisda** [comment]
It is not working. yet

**Comment by irisda** [comment]
Hello @farshadff  do you have any news?

**Comment by farshadff** [comment]
hi @irisda the last thing i have done here is :
```
{!! view_render_event('bagisto.shop.products.price.before', ['product' => $product]) !!}

{{--<span class="discount"> 20% </span>--}}
@inject ('configurableOptionHelper', 'Webkul\Product\Helpers\ConfigurableOption')

@php
    $config = $configurableOptionHelper->getConfigurationConfig($product);

    $productPrice = $config['variant_prices'];
        dd($config)
@endphp
{{--<span class="discount"> 20% </span>--}}
<div class="product-price">
    {!! reset($productPrice)['final_price']['formated_price'] !!}

    {!! $product->getTypeInstance()->getPriceHtml() !!}

{{--    @dd($product)--}}
{{--   {{ $product->attribute_family->getHomeDiscount()}}--}}

</div>

{!! view_render_event('bagisto.shop.products.price.after', ['product' => $product]) !!}
```
this is price.blade.php it shows one variant final price which in my case because all variants are the same it works for me . but i see one problem is that it only returns the first product price so i should move it in Helper.php in velocity directory

**Comment by irisda** [comment]
Hello @farshadff this doesn't work for my solution.we need to have discount % and based on that % to calculate price.

**Comment by irisda** [comment]
hey @farshadff  have you done any kind of imporovment on this issue ?

**Comment by IvalinV** [comment]
Hello @vaishaliwebkul is there any estimate when this feature will be implemented ?

**Comment by parasbhadauria** [comment]
Hi @vaishaliwebkul 
**Discount & by default minimum price selection is Missing in Configurable Products: How it can be added?**
For getting more clarity, I am raising the issue again which I have raised on the forum.

<img width="832" alt="configurable-product-discount-missing" src="https://user-images.githubusercontent.com/75558471/104457789-7d610180-55d0-11eb-89da-7b3f7bb2b618.png">

Please let us know how long we can expect this feature?

Thanks

**Comment by rahulshukla-webkul** [comment]
Hi @farshadff @IvalinV @irisda @parasbhadauria 

We have created PR for this one - https://github.com/bagisto/bagisto/pull/4530
You can take pull when its gets merged.

**Comment by vaishaliwebkul** [comment]
Hi @farshadff @IvalinV @irisda @parasbhadauria 
the reported bug has been fixed, you can pull from the master branch.

Closing this issue, feel free to reopen anytime if still exist.
