### ISSUE TITLE
Installer Blank Page After Migration

### ISSUE THREAD

**Issue by eslourad** [bagisto/bagisto#3274]
![Capture](https://user-images.githubusercontent.com/51907594/84984424-5db64780-b16d-11ea-9aee-5c5974523a94.JPG)

**Comment by eslourad** [comment]
fixed. it turns out i did not put proper permission on database user.

**Comment by raulidavid** [comment]
SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "special_price" cannot be cast automatically to type numeric
  HINT:  You might need to specify "USING special_price::numeric(12,4)". error postgres 12

**Comment by LuckyDude68** [comment]
Hi! I have the same problem but a my database user has All Privileges.
![Screenshot 2020-10-28 at 07 07 42](https://user-images.githubusercontent.com/73575652/97398894-4857e380-18ec-11eb-9331-405ef539dd97.png)

**Comment by vaishaliwebkul** [comment]
@LuckyDude68 
instead of GUI, you can check setup the bagisto using command line.

check if .env exist then add the database credentials and run the below command
php artisan bagisto:install

**Comment by LuckyDude68** [comment]
@vaishaliwebkul 
I installed it using CLI,
.env exists,
I did 'php artisan bagisto:install',
and with or without 'php artisan serve'
it still remains the same
![Screenshot 2020-10-28 at 21 25 10](https://user-images.githubusercontent.com/73575652/97492616-14200980-1964-11eb-947d-a2f0cdab4fb4.png)

**Comment by vaishaliwebkul** [comment]
@LuckyDude68 
Is php artisan bagisto:install command executed successfully??

**Comment by LuckyDude68** [comment]
@vaishaliwebkul I did a full reinstall and now it seems to work.

**Comment by elitedigitaltech** [comment]
Getting below error
![image](https://user-images.githubusercontent.com/8210369/102360684-549d1a80-3fd8-11eb-8200-2d287521ec3b.png)

**Comment by vaishaliwebkul** [comment]
@elitedigitaltech 
you may follow this https://forums.bagisto.com/topic/1913/base-table-or-view-not-found/2

**Comment by elitedigitaltech** [comment]
Follow that for fresh migration but still same error base table channel not found

![image](https://user-images.githubusercontent.com/8210369/102361431-3a177100-3fd9-11eb-8943-4fd46ae6b3da.png)

**Comment by vaishaliwebkul** [comment]
@elitedigitaltech 
may I know your database version? Also check the total number of table created in database.

**Comment by elitedigitaltech** [comment]
No table created

**Comment by Aziz-tripleA** [comment]
> Follow that for fresh migration but still same error base table channel not found
> 
> ![image](https://user-images.githubusercontent.com/8210369/102361431-3a177100-3fd9-11eb-8943-4fd46ae6b3da.png)

I have this error with a fresh install 
how can solve it
