### ISSUE TITLE
Header content category always redirect to 404 error page

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3298]
# Bug report

### Title
Header content category always redirects to 404 error page

### Issue Description

Header content category always redirects to 404 error page

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version- master
  

### Steps to reproduce

    1. step1- Velocity-> header content-> add valid slug
    2. step2- go to shop, then click on custom category

### Expected result

when clicking on a custom category then it should redirect to category page

### Actual result

![Screenshot (59)](https://user-images.githubusercontent.com/43210406/85123397-d38de200-b245-11ea-84ec-a9df22de23af.png)

![Screenshot (60)](https://user-images.githubusercontent.com/43210406/85123440-e7394880-b245-11ea-93e8-5eef7a14aa6d.png)

**Comment by BrandBean** [comment]
Is ready the error?

**Comment by vaishaliwebkul** [comment]
@BrandBean 
this is not a bug, you may verify it. make sure the valid category slug should be passed.

**Comment by keyideas** [comment]
I have just setup the bagisto v1.20 via composer. It setup fine.
but having the same issue for category page shows on 404 page. I have re-verified the category slug, all are fine. 
Can any one help me how to resolve this.

**Comment by keyideas** [comment]
We are getting issue while update the category table value from mysql
#1267 - Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='

I have checked the collations are the same for all category.
Can anyone help me how to fix this?
