### ISSUE TITLE
Add packages under require key in Admin Package

### ISSUE THREAD

**Issue by ankitjain28may** [bagisto/bagisto#330]
As I can see that You are using `Sales, Channel, Product and other packages` but you haven't added these packages as a dependency in `composer.json` of `Admin` Package unlike `UI, Core, User` package.

**Comment by prashant-webkul** [comment]
Hello @ankitjain28may you are really right about the things you said, be are working on a better dependency resolving system in the new releases of Bagisto in the coming time.

Wait till next two releases to get this thing done and more so ever you would have seen the composer file with the version names of these packages that are used.

**Comment by ankitjain28may** [comment]
@prashant-webkul Great :)
