### ISSUE TITLE
Getting exception on changing locale when customer has opened downloadable products grid from his account

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3303]
# Bug report

### Title

Getting exception on changing locale when customer has opened downloadable products grid from his account

### Issue Description
If customer has opened downloadable products from account section and applied any filter then if he changes locale then getting exception

### Preconditions

    1. framework Version. - master 
   

### Steps to reproduce

    1. step1 - vissit customer account section, click on downloadable products and use any filter 
    2. step2 - then change the locale 

### Expected result:
same page should be displayed in changed locale 

### Actual result
getting exception

![Screenshot 2020-06-20 10:01:42](https://user-images.githubusercontent.com/52821836/85191951-611d1080-b2de-11ea-9fbd-a22b58838d3b.png)

**Comment by vaishaliwebkul** [comment]
Fixed in this https://github.com/bagisto/bagisto/issues/3307
