### ISSUE TITLE
Getting incorrect message on delete all from wishlist in case of guest user only 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3304]
# Bug report

### Title
Getting incorrect message on delete all from wishlist 
### Issue Description

Getting incorrect message on delete all from wishlist, in message in place of wishlist compare list is coming 

### Preconditions

    1. framework Version. - master

### Steps to reproduce

    1. step1 - add product to wishist of guest user 
    2. step2- click on delete all

### Expected result
item successfully removed from wishlist 

### Actual result

![Screenshot 2020-06-20 11:18:27](https://user-images.githubusercontent.com/52821836/85193828-11901200-b2e9-11ea-819a-3449de772ea1.png)

**Comment by ghermans** [comment]
@bhanu-webkul did you get that message only when using Velocity or also with the Bliss (old default) theme?
