### ISSUE TITLE
"search by name" doesn't work in rest api

### ISSUE THREAD

**Issue by ToghrolRc** [bagisto/bagisto#3306]
# Bug report

### Issue Description
hi there. i'm using bagisto on localhost without any problem , but today i found an issue. when i pass product name to api address like " localhost:8000/api/products?name='PRODUCT_NAME' " result is "All products object in JSON format" like i send  "localhost:8000/api/products"
but i can search with product id , sku , url ...

how can i search product by name or part of name?
anyone have this problem too?
(Sorry for my bad english)

**Comment by shivam-webkul** [comment]
Hello @ToghrolRc ,

Then you need to put the query for your requirement into the product get api, like product name .

Thanks

**Comment by vaishaliwebkul** [comment]
@ToghrolRc 
No response from last 1month so we are closing this issue.

Feel free to reopen it anytime
