### ISSUE TITLE
Terrible performance for displaying bundle product price

### ISSUE THREAD

**Issue by MattApril** [bagisto/bagisto#3308]
# Bug report

### Issue Description
Calculating the price of complex bundle products is extremely poor performing. And as a result loading category pages with those bundle products is extremely slow. For me, every category page that includes a bundle is taking over 5 seconds before the back-end finishes rendering.

### Preconditions
**Please provide as detailed information about your environment as possible.**
    1. framework Version: 1.1.2

### Steps to reproduce

    1. Create a complex bundle product (lets say 5+ options, each containing 3-5 products).
    2. Load a page that displays its price (product page or category page)

This obviously becomes even slower when loading a category page with 9+ complex bundle products.

**Comment by MattApril** [comment]
# The Problem
Bundle prices are being calculated on the fly every single time it is requested.

# Proposed Solution
Calculate the bundle price only when it gets saved, or when a product attached to it gets saved. Then retrieve the bundle price from the product_flat table.

**Comment by devansh-webkul** [comment]
Hi @MattApril,

Could you verify this in the latest version? As some queries have been enhanced in the master and latest versions.
