### ISSUE TITLE
500 error when loading /search with "term" in query string

### ISSUE THREAD

**Issue by MattApril** [bagisto/bagisto#3309]
# Bug report

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version 1.1.2
    2. Commit id.

### Steps to reproduce 

    1. navigate to /search without any query string

**Comment by vaishaliwebkul** [comment]
Hi @MattApril 
Could you please specify this issue in more details as I am not able reproduce this issue.

Thanks.

**Comment by MattApril** [comment]
Yes sorry my title is wrong. It should ready "Without term".
You can recreate by performing a search and then editing the URL to remove everything after the "?". Which should be "?term={your searched text}"

**Comment by MattApril** [comment]
This is not a velocity specific bug, and was not fixed by this commit.

**Comment by shubhwebkul** [comment]
Hello @MattApril 
This issue has been fixed in master

**Comment by jyoti-webkul** [comment]
- Framework Version: Master

---------------------------------------------

Fixed

![Workspace 1_104](https://user-images.githubusercontent.com/45203177/89095089-f59f8600-d3e7-11ea-893f-fe8dbc315156.png)
