### ISSUE TITLE
Editing product title should not change URL if it has already been set

### ISSUE THREAD

**Issue by MattApril** [bagisto/bagisto#3310]
# Bug report

### Issue Description
Editing a product name after a product URL has already been set causes the URL to be changed to match the product name. This feature is only desirable if no URL Key has been defined yet. This is a bug because it can cause unintentional changes to URL's without realizing it.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version 1.1.2

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Editing an existing product
    2. Change the name
    3. Save

### Expected result
Only the name should have changed

### Actual result

The name and URL have changed.

**Comment by rahulcs0082** [comment]
Hi @MattApril 

We have fixed this one. Thanks for raising it.

**Comment by vaishaliwebkul** [comment]
@MattApril 
It's fixed now.

Feel free to reopen if still exist.
