### ISSUE TITLE
Mobile Bug - Filters disappear when no products match filters

### ISSUE THREAD

**Issue by MattApril** [bagisto/bagisto#3311]
# Bug report

### Issue Description
When filtering on mobile, if you choose a filter combination that does not match any products the filters completely disappear, forcing you to use the back button to correct it.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: master
    2. Theme: default
    3. Phone or low resolution.

### Steps to reproduce
    1. navigate to a category page
    2. apply filters that do not match any products

### Expected result
No products should be visible, but filters should still be visible.

### Actual result

No products or filters are visible, just a blank page with an message about the category being empty.

**Comment by vaishaliwebkul** [comment]
@asif-webkul 
filter is still getting disappear https://prnt.sc/te6o1y

**Comment by MattApril** [comment]
Confirmed, thanks
