### ISSUE TITLE
In cart, in place of only qty, quantity and price both are coming in ar.

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3313]
# Bug report

### Title
in cart, in place of qty, quantity and price both are coming in ar.

### Issue Description
in cart, in place of qty, quantity and price both are coming in ar.

### Preconditions

    1. framework Version. Master

### Steps to reproduce
    1. step1 - add product to cart
    2. step2 - click on dropdown to view cart

### Expected result
show the quantity with product image then price 

![Screenshot (21)](https://user-images.githubusercontent.com/52821836/85248708-4c23b700-b46f-11ea-9340-20443c18815f.png)

### Actual result
![Screenshot (21)](https://user-images.githubusercontent.com/52821836/85248727-5b0a6980-b46f-11ea-9bdb-1514e5f52f59.png)

**Comment by bhanu-webkul** [comment]
Issue fixed but still there are  area of improvements - https://prnt.sc/tdtngi

**Comment by jyoti-webkul** [comment]
- Framework Version: master

-------------------------------------

Fixed

![Workspace 1_105](https://user-images.githubusercontent.com/45203177/89095414-6005f580-d3eb-11ea-9680-442fa9787d16.png)
