### ISSUE TITLE
Database Migration Failed using Postgres 12

### ISSUE THREAD

**Issue by rhzs** [bagisto/bagisto#3318]
# Bug report

### Issue Description
During the first time setup, I encountered failed database migration.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1.  PHP version 7.2.31
    2. Bagisto version v1.1.2
    3. Commit SHA: [490c6ff64c828a395f8a1276aeb4e5be283ea190](https://github.com/bagisto/bagisto/commit/490c6ff64c828a395f8a1276aeb4e5be283ea190)
    4. Postgres 12 

### Steps to reproduce

    1. Clone Bagisto repo at the commit SHA.
    2. Run `php artisan serve` and go to installation setup (it hangup at the last step), no success screen.
    3. Perform database migration using Postgres, `php artisan migrate`

### Expected result
It should success.

### Actual result

<img width="799" alt="Screen Shot 2020-06-22 at 13 34 03" src="https://user-images.githubusercontent.com/5300674/85255744-11c91280-b48d-11ea-9ca5-92e4758f8254.png">

<img width="1101" alt="Screen Shot 2020-06-22 at 13 32 02" src="https://user-images.githubusercontent.com/5300674/85255791-273e3c80-b48d-11ea-8ca2-d73e31e347fd.png">

Error is shown:
```shell
In Connection.php line 669:

  SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "special_price" cannot be cast automatically to type numeric
  HINT:  You might need to specify "USING special_price::numeric(12,4)". (SQL: ALTER TABLE product_flat ALTER special_price TYPE NUMERIC(12, 4))


In PDOStatement.php line 119:

  SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "special_price" cannot be cast automatically to type numeric
  HINT:  You might need to specify "USING special_price::numeric(12,4)".


In PDOStatement.php line 117:

  SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "special_price" cannot be cast automatically to type numeric
  HINT:  You might need to specify "USING special_price::numeric(12,4)".
```

**Related Issue**
https://github.com/laravel/framework/issues/28963

**Comment by vaishaliwebkul** [comment]
Hi @rhzs 
please check this once, same issue https://github.com/bagisto/bagisto/issues/3274

**Comment by rhzs** [comment]
@vaishaliwebkul  I believe I have given root user permission. You can reproduce my issue by performing rollback and migrate again. Make sure you have postgres 12. 

@vaishaliwebkul will be helpful if Bagisto has database migration testing on various db in its CI pipeline.

**Comment by jorgebeserra** [comment]
Hi, 

The problem is that the master developer does not have POSTGRES as an option, when I do my migrations I see where it is giving an error and I change it within the migrations, simpler, I'm just getting some time to adjust this in the migrations and open a request for see if they accept... 

Requirements

    OS: Ubuntu 16.04 LTS or higher / Windows 7 or Higher (WampServer / XAMPP).
    SERVER: Apache 2 or NGINX.
    RAM: 3 GB or higher.
    PHP: 7.2.0 or higher.
    Processor: Clock Cycle 1 Ghz or higher.
    For MySQL users: 5.7.23 or higher.
    For MariaDB users: 10.2.7 or Higher.
    Node: 8.11.3 LTS or higher.
    Composer: 1.6.5 or higher.

**Comment by raulidavid** [comment]
@jorgebeserra Pana cuales son los pasos a seguir estoy con el mismo error  Datatype mismatch: 7 ERROR:  la columna «special_price» no puede convertirse automáticamente al tipo numeric

**Comment by jorgebeserra** [comment]
Folks,

If you want to install BAGISTO using postgres this will not be the only error, there are more things to fix ... several TRIGGERS and FUNCTION, I have one that I am implementing at the same time, to install via POSTGRES, as soon as it is OK, I I do a PUL, in my following commercial repository https://github.com/Sabidos/bagisto.git, for now I can try to solve the errors that appear ... My commands still don't check which database is, yet I want to put this to run until the 1st of July, I have deadlines here .. rs rs


```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddMinPriceAndMaxPriceColumnInProductFlatTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {

        Schema::table('product_flat', function (Blueprint $table) {
            $table->decimal('min_price', 12, 4)->nullable();
            $table->decimal('max_price', 12, 4)->nullable();
            //$table->decimal('special_price', 12, 4)->nullable()->change(); <-- Comentar essa linha
        });
        // Adicionar essa linha
        DB::statement('ALTER TABLE product_flat ALTER COLUMN special_price TYPE DECIMAL(12,4) USING CASE WHEN special_price = false THEN 0 ELSE 1 END;');
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('product_flat', function (Blueprint $table) {
            $table->dropColumn('min_price');
            $table->dropColumn('max_price');
        });
    }
}
```

**Comment by devansh-webkul** [comment]
Currently, Bagisto not supports Postgress due to the triggers and routines. As this PR has been implemented,
https://github.com/bagisto/bagisto/pull/2008

If someone wants to give support for Postgress then need an alternative to the above PR.
