### ISSUE TITLE
Unable to change the status of user.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#332]
Framework Version: 0.1.2
Test Steps:
1. Create a user and check his account as active.
2. Edit the created user and and Uncheck the status and save.

Result- Status of User will be still Active

**Comment by prashant-webkul** [comment]
more information is needed on this where in Admin panel or which user?

**Comment by Jyoti-Singh1** [comment]
In admin section ,User grid

**Comment by prashant-webkul** [comment]
This issue had been fixed and will appear to show up in next release.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.3
Fixed
