### ISSUE TITLE
Getting exception on frontend when opening a category in which brand is selected as filterable attribute.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3320]
# Bug report

### Title
Getting exception on frontend when opening a category in which brand is selected as filterable attribute.
### Issue Description
Getting exception on frontend when opening a category in which brand is selected as filterable attribute.

### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Create a category and select brand as filterable attribute
    2. step2- on frontend click on that ctaegory

### Expected result
category should get open

### Actual result
Getting exception
![Workspace 1_127](https://user-images.githubusercontent.com/45203177/85259416-a67c4200-b486-11ea-839d-f4f36c724823.png)

**Comment by vaishaliwebkul** [comment]
fixed
