### ISSUE TITLE
Comapre button should come between wishlist and cart in arabic also. 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3321]
# Bug report

### Title
Comapre button should come between wishlist and cart in arabic also. 

### Issue Description
in ar compare button is coming immediate left to search bar while in en it comes in 
between wishlist and cart
### Preconditions

    1. framework Version. Master

### Expected result
in ar also it should in middle like this - 
![Screenshot 2020-06-22 14:03:38](https://user-images.githubusercontent.com/52821836/85266272-450da080-b491-11ea-89ae-f0c6f314df57.png)

### Actual result

![Screenshot 2020-06-22 14:04:00](https://user-images.githubusercontent.com/52821836/85266301-4dfe7200-b491-11ea-9503-d51d2eaf33cd.png)

**Comment by vaishaliwebkul** [comment]
able to reproduce the same issue again in the master 
![Screenshot_38](https://user-images.githubusercontent.com/43210406/91828453-c89bf880-ec5d-11ea-9d1c-c453546f8714.png)
