### ISSUE TITLE
User is able to login in his account even if his status is not selected as active.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#333]
Framework Version: 0.1.2
Test Steps:
1. Create a user and did not select his account as active.
2. Login with created user detail.

Result: Able to login

**Comment by prashant-webkul** [comment]
Issue has been addressed and on investigating , it was found that the custom role admin is not even saving or updating the status column in the database.

**Comment by prashant-webkul** [comment]
This issue is fixed wait till next release to see the results.
The commit hash for this fix is 489dcf0b54adc795885d174105ba01cde7dc6f9c
