### ISSUE TITLE
How to access more information about the user on checkout page in calculate method in a new shipping method

### ISSUE THREAD

**Issue by Xoshbin** [bagisto/bagisto#3332]
Hi, Is there anyway to access more information at checkout page. I'm making a new shipping method calculating based on the cities. But it looks like I can't access all the fields of the billing address or shipping address forms to grab the city in "calculate" method in the "cart" object. There should be more information to access at the calculate method level because shipping methods change based on the form.
Thanks

**Comment by Xoshbin** [comment]
Hi Guys, It's been seven days since my question and my pull request. and no one answered my question or looked at my pull request yet. 
anyway, when I'm looking at the design of the application the shipment method or any new shipment package should have access to the billing or shipment form data like city and product information like product weight and height and width and depth. because we all know tat some shipment companies work based on these calculations.
That day after posting the issue I did look around the code and did logging to find away to get these info but I could not access any of these data that I mentioned above. so I did search again to find away to access it and I found out that I have to store these information in the cart table then access it like in the pull request. 
So I'm asking if I'm wrong or no, if there's access to theses data please can anyone mention it somewhere. if no then I think we have to store more information about the shipment and product like weight in cart table.
Thank you for this great application.

**Comment by shubhwebkul** [comment]
Hello there,

We really appreciate your support and patience.

You will be able to access city of shipping address with the help of **$cart->shipping_address->city**

Let us know if you have any further query.

**Comment by Xoshbin** [comment]
Thank you very much, That was so bad that I didn't see that.
