### ISSUE TITLE
customer group price maximum quantity validation is not working while customer add to cart item

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3334]
# Bug report

### Title
customer group price maximum quantity validation is not working while customer add to cart item

### Issue Description
customer group price maximum quantity validation is not working while customer add to cart item

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add customer group price qty =1 in any product (which means offer will applied only for single quantity purchase.)
    2. step2- now add to cart with 2 qty(shouldn't able to add to cart for 2 qty)

### Expected result

customer allow purchasing only the mention qty of customer  group price

### Actual result

![Screenshot (66)](https://user-images.githubusercontent.com/43210406/85386201-eadc1080-b560-11ea-8f98-1e11f068270c.png)

![Screenshot (67)](https://user-images.githubusercontent.com/43210406/85386282-047d5800-b561-11ea-9645-35470280b8b0.png)

**Comment by jitendra-webkul** [comment]
Qty field is not for max qty, it's for minimum qty to be purchased in order to get discount.
