### ISSUE TITLE
New Label is missing in VelocityTheme

### ISSUE THREAD

**Issue by irisda** [bagisto/bagisto#3335]
In Vleocity theme for new products the label "new" is missing.

**Comment by vaishaliwebkul** [comment]
Hi @irisda 
mention the bagisto version as we are not getting this issue.

**Comment by irisda** [comment]
V1.1.0

**Comment by vaishaliwebkul** [comment]
@irisda 
it's also visible in the 1.1.0, please check it https://prnt.sc/t4w8pl

try php artisan vendor:publish --force then check again

**Comment by irisda** [comment]
No i am talking for new label inside the product

**Comment by irisda** [comment]
@vaishaliwebkul how can you help me to  show where i can add the "new" label on the fornt part?

**Comment by vaishaliwebkul** [comment]
@irisda 
It would be helpful if you can attach the screenshot where you want to add "new" label.

**Comment by irisda** [comment]
Inside of a product the same as label sale

**Comment by irisda** [comment]
@vaishaliwebkul did you find a solution?

**Comment by vaishaliwebkul** [comment]
Hi @shubhwebkul 
This feature is only implemented for the home page. We should also add this on search page, category page.

**Comment by irisda** [comment]
Okay @vaishaliwebkul  thnx

**Comment by vaishaliwebkul** [comment]
@shubhwebkul 
new tag is still not visible from the search page https://prnt.sc/tdylvk

**Comment by bhanu-webkul** [comment]
same issue in case of linked products
