### ISSUE TITLE
My Account Grid displays blank after the bagisto 0.1.2 installation.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#334]
Framework Version: 0.1.2
https://prnt.sc/lwcmt2

**Comment by prashant-webkul** [comment]
This issue had been fixed and will you will get to see it in next release build.

Till then you can use the zip file for using bagisto.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot 6](https://user-images.githubusercontent.com/45203177/52275842-aacdbb00-2976-11e9-91f4-23c5f0086bfe.png)
