### ISSUE TITLE
Dispatch event before Payment redirect when an order is placed

### ISSUE THREAD

**Issue by emperorjm** [bagisto/bagisto#3342]
When a custom payment method is implemented using a Redirect URL the user is redirected to this payment page once the **"Place Order"** button. All of this is done within the "**Webkul\Shop\Http\Controllers\OnepageController@saveOrder**" function but no events are dispatched before the Redirect is done:

```
if ($redirectUrl = Payment::getRedirectUrl($cart)) {
            return response()->json([
                'success'      => true,
                'redirect_url' => $redirectUrl,
            ]);
        }
```

The "**checkout.order.save.before**" event is dispatched in the call below the above IF statement which does not get called because the redirect is done.

I am requesting that an Event is dispatched before the redirect is done. I need this so that I can set certain session variables that I want to check for on the payment page to make sure the request is coming from the user clicking the Place Order button on the checkout page.

**Comment by rahulcs0082** [comment]
Hello @emperorjm 

This event ( **checkout.order.save.before** ) is dispatched at order repository's create method, so still, before redirection, this event will be dispatched as the order will be created from the repository. 
If you need an event in the controller then you need to customise it.

**Comment by vaishaliwebkul** [comment]
Hello @emperorjm 
Hope above solution worked for you! We are not getting any response from the last 21 days so We're closing this issue.

Feel free to reopen your query at any time in case of further doubts.

**Comment by sreekuttykabmate** [comment]
hi
