### ISSUE TITLE
what library for icons you are using?

### ISSUE THREAD

**Issue by irisda** [bagisto/bagisto#3344]
This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by shubhwebkul** [comment]
We are using material design in velocity theme included [here](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/assets/sass/app.scss#L14)

**Comment by ghermans** [comment]
@vaishaliwebkul this one can be closed too, since the question has been answered

**Comment by vaishaliwebkul** [comment]
@irisda 
Hope your query gets resolved.
