### ISSUE TITLE
"Add some provision to check which version of bagisto is currently installed on the system"

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#335]

**Comment by prashant-webkul** [comment]
Command: **php artisan bagisto:version** added to know the currently installed version of **Bagisto**.

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Implemented

**Comment by rahulanand77** [comment]
Is there any way we can add it in the Migration file like check the version first before running the Migration script? Version 1.3.1 and Version 1.2.1 has some columns difference. So for extensions, it would better to check bagisto version first to run accordingly.

**Comment by jyoti-webkul** [comment]
Hi @rahulanand77 
For now we don't have such feature to check version before running migration. But we will check and if possible we will surely add this and will update you.

**Comment by rahulanand77** [comment]
Thanks @jyoti-webkul . What if I want to contribute in Bagisto development? How can I?

**Comment by jyoti-webkul** [comment]
@rahulanand77 
Fork the master branch of bagisto and create your own branch on your local,update your code in your local branch and create a merge request in master branch.

**Comment by rahulanand77** [comment]
Thanks. Will follow. In the mean time, what if someone wants to download a specific bagisto version like 1.2, 1.1? The bagisto download from your website is always latest.
