### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by wontone18** [bagisto/bagisto#3352]
Hi

I am facing a error it may be a bug https://prnt.sc/t5pqxk. It stuck with the installation and moving forward or finishing up the installation.

Regards
saju

**Comment by vaishaliwebkul** [comment]
Hi @wontone18 
you may add the database credentials .env file then run **php artisan migrate** with fresh DB

If any error attempts while executing migration then show the screenshot.

Thanks.

**Comment by wontone18** [comment]
lol  let me try that way to.

**Comment by wontone18** [comment]
@vaishaliwebkul its both same actually either migrate or run from installation.

https://prnt.sc/t62o9m now i am getting this issue.

**Comment by wontone18** [comment]
yes its fix.
