### ISSUE TITLE
filter and items per page is getting collapsed in ar 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3360]
# Bug report

### Title
filter and items per page is getting collapsed in ar 
### Issue Description
filter and items per page is getting collapsed in order and downloadable products  grid at customer end 
### Preconditions

    1. framework Version. master
  

### Steps to reproduce

    1. step1- visit customer account, click on order  and downloadable products grid 
 

### Expected result
should come like as come in en 
### Actual result
![Screenshot (24)](https://user-images.githubusercontent.com/52821836/85706435-d2562c80-b6ff-11ea-9a2d-2785e0ef2aa3.png)

**Comment by vaishaliwebkul** [comment]
fixed
