### ISSUE TITLE
Cart Rule Not working on particular category

### ISSUE THREAD

**Issue by testforpostman7** [bagisto/bagisto#3361]
Hello,

  I create one cart rule and apply it on a specific category but it is applied in all categories instead of a specific category. So please give me a solution to apply cart rule on specific category only.

Thanks.

**Comment by vaishaliwebkul** [comment]
Hi @testforpostman7 
could you mention the bagisto version?

Thanks

**Comment by testforpostman7** [comment]
@vaishaliwebkul I am using 0.1.6 bagisto version

**Comment by vaishaliwebkul** [comment]
@testforpostman7 

this bug is resolved in bagisto 1.1.0 or higher version, please check this 
https://prnt.sc/t8hhd7 
https://prnt.sc/t8hhp3 
https://prnt.sc/t8hr3y

Kindly update your bagisto version or you can check this on live [demo ](https://demo.bagisto.com)

**Comment by vaishaliwebkul** [comment]
@testforpostman7 
Hope this is resolved.

Feel free to reopen if you're still getting this.

**Comment by arooba499** [comment]
i created a cart rule to enable free shipping if cart price > 100 but when i enable this rule this is applied on all items even cart price is less than 100
