### ISSUE TITLE
On mobile responsive on ios sign up button is missing

### ISSUE THREAD

**Issue by irisda** [bagisto/bagisto#3365]
On mobile version the sign up button is missing

**Comment by vaishaliwebkul** [comment]
Hi @irisda 
sign up icon is visible https://prnt.sc/t6td8n on iphone XS so let me know on which model you're getting this issue.
Also will be helpful if you can show the screenshot.

**Comment by irisda** [comment]
I mean on the menu

**Comment by vaishaliwebkul** [comment]
@irisda 
sign up button is added now on master branch https://prnt.sc/tx1sei, kindly check

Feel free to reopen if this is still not resolved.
Thanks.
