### ISSUE TITLE
Getting exception when unsubscribing from subscription emails, if subscription is already deleted from newsletter grid of admin.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#337]
Framework Version: 0.1.2
Test Steps:
1. subscribe to news letter from shop
2. then go to admin and go to customers and click newsletter
3.  delete that email which was subscribed from the grid.
4. open the subscription email in the inbox of email
5. click unsubscribe

**Comment by prashant-webkul** [comment]
Issue fixed in PR #338

**Comment by Jyoti-Singh1** [comment]
Framework Version
Fixed, now not getting exception.
