### ISSUE TITLE
How can I get 5 recent orders from admin datagrid.

### ISSUE THREAD

**Issue by akshaypitale** [bagisto/bagisto#3370]
How can I get 5 recent orders from admin datagrid.
I have made separate datagrid as RecentOrderDataGrid but I am stuck at getting 5 recend orders from SQL.

**Comment by ghermans** [comment]
take a look at the laravel query builder docs
https://laravel.com/docs/7.x/queries#ordering-grouping-limit-and-offset

**Skip / take**

To limit the number of results returned from the query, or to skip a given number of results in the query, you may use the skip and take methods:
```php
$users = DB::table('users')->skip(10)->take(5)->get();
```

**Comment by akshaypitale** [comment]
> ```
> ->take(5)
> ```

Hi ghermans,

Thanks for the reply,

I tried below two queries but it still giving me the same results.
1) First One
$queryBuilder = DB::table('orders')
            ->leftJoin('addresses as order_address_shipping', function($leftJoin) {
                $leftJoin->on('order_address_shipping.order_id', '=', 'orders.id')
                         ->where('order_address_shipping.address_type', OrderAddress::ADDRESS_TYPE_SHIPPING);
            })
            ->leftJoin('addresses as order_address_billing', function($leftJoin) {
                $leftJoin->on('order_address_billing.order_id', '=', 'orders.id')
                         ->where('order_address_billing.address_type', OrderAddress::ADDRESS_TYPE_BILLING);
            })
            ->addSelect('orders.id','orders.increment_id', 'orders.base_sub_total', 'orders.base_grand_total', 'orders.created_at', 'channel_name', 'status')
            ->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_billing.first_name, " ", ' . DB::getTablePrefix() . 'order_address_billing.last_name) as billed_to'))
            ->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_shipping.first_name, " ", ' . DB::getTablePrefix() . 'order_address_shipping.last_name) as shipped_to'))
            ->orderBy('id', 'DESC')
            ->take(5);

2) 2nd one
$queryBuilder = DB::table('orders')
            ->leftJoin('addresses as order_address_shipping', function($leftJoin) {
                $leftJoin->on('order_address_shipping.order_id', '=', 'orders.id')
                         ->where('order_address_shipping.address_type', OrderAddress::ADDRESS_TYPE_SHIPPING);
            })
            ->leftJoin('addresses as order_address_billing', function($leftJoin) {
                $leftJoin->on('order_address_billing.order_id', '=', 'orders.id')
                         ->where('order_address_billing.address_type', OrderAddress::ADDRESS_TYPE_BILLING);
            })
            ->addSelect('orders.id','orders.increment_id', 'orders.base_sub_total', 'orders.base_grand_total', 'orders.created_at', 'channel_name', 'status')
            ->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_billing.first_name, " ", ' . DB::getTablePrefix() . 'order_address_billing.last_name) as billed_to'))
            ->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_shipping.first_name, " ", ' . DB::getTablePrefix() . 'order_address_shipping.last_name) as shipped_to'))
            ->orderBy('id', 'DESC')
            ->limit(5);

**Comment by shivam-webkul** [comment]
Hello, 

Try this it will return the 5 orders and if you want to increase limit simply change the value of limit.

$queryBuilder->limit(5)->get();

here is the example.
https://prnt.sc/tl6pai

**Comment by akshaypitale** [comment]
Hello Shivam,
Thanks for reply. But the solution is not working. It giving me 500 Internal server error.

Can you please check below code. 

`<?php

namespace Webkul\Admin\DataGrids;

use Illuminate\Support\Facades\DB;
use Webkul\Sales\Models\OrderAddress;
use Webkul\Ui\DataGrid\DataGrid;

class RecentOrderDataGrid extends DataGrid
{
    protected $index = 'id';

    protected $sortOrder = 'desc';

    public function prepareQueryBuilder()
    {
        $queryBuilder = DB::table('orders')
            ->leftJoin('addresses as order_address_shipping', function($leftJoin) {
                $leftJoin->on('order_address_shipping.order_id', '=', 'orders.id')
                         ->where('order_address_shipping.address_type', OrderAddress::ADDRESS_TYPE_SHIPPING);
            })
            ->leftJoin('addresses as order_address_billing', function($leftJoin) {
                $leftJoin->on('order_address_billing.order_id', '=', 'orders.id')
                         ->where('order_address_billing.address_type', OrderAddress::ADDRESS_TYPE_BILLING);
            })
            ->addSelect('orders.id','orders.increment_id', 'orders.base_sub_total', 'orders.base_grand_total', 'orders.created_at', 'channel_name', 'status')
            ->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_billing.first_name, " ", ' . DB::getTablePrefix() . 'order_address_billing.last_name) as billed_to'))
            ->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_shipping.first_name, " ", ' . DB::getTablePrefix() . 'order_address_shipping.last_name) as shipped_to'))
            ->orderBy('id', 'DESC');
            
        $this->addFilter('billed_to', DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_billing.first_name, " ", ' . DB::getTablePrefix() . 'order_address_billing.last_name)'));
        $this->addFilter('shipped_to', DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_shipping.first_name, " ", ' . DB::getTablePrefix() . 'order_address_shipping.last_name)'));
        $this->addFilter('increment_id', 'orders.increment_id');
        $this->addFilter('created_at', 'orders.created_at');

        $this->setQueryBuilder($queryBuilder);
    }

    public function addColumns()
    {
        $this->addColumn([
            'index'      => 'increment_id',
            'label'      => trans('admin::app.datagrid.id'),
            'type'       => 'string',
            'searchable' => false,
            'sortable'   => false,
            'filterable' => false,
        ]);

        // $this->addColumn([
        //     'index'      => 'base_sub_total',
        //     'label'      => trans('admin::app.datagrid.sub-total'),
        //     'type'       => 'price',
        //     'searchable' => false,
        //     'sortable'   => false,
        //     'filterable' => false,
        // ]);

        $this->addColumn([
            'index'      => 'base_grand_total',
            'label'      => trans('admin::app.datagrid.grand-total'),
            'type'       => 'price',
            'searchable' => false,
            'sortable'   => false,
            'filterable' => false,
        ]);

        $this->addColumn([
            'index'      => 'created_at',
            'label'      => trans('admin::app.datagrid.order-date'),
            'type'       => 'datetime',
            'sortable'   => false,
            'searchable' => false,
            'filterable' => false,
            'wrapper'  => function ($data) {
                return date_format(date_create($data->created_at), 'd-m-Y h:i:s');
            }
        ]);

        // $this->addColumn([
        //     'index'      => 'channel_name',
        //     'label'      => trans('admin::app.datagrid.channel-name'),
        //     'type'       => 'string',
        //     'sortable'   => false,
        //     'searchable' => false,
        //     'filterable' => false,
        // ]);

        $this->addColumn([
            'index'      => 'status',
            'label'      => trans('admin::app.datagrid.status'),
            'type'       => 'string',
            'sortable'   => false,
            'searchable' => false,
            'closure'    => true,
            'filterable' => false,
            'wrapper' => function ($value) {
                if ($value->status == 'processing') {
                    return '<span class="badge badge-md badge-success">'. trans('admin::app.sales.orders.order-status-processing') .'</span>';
                } elseif ($value->status == 'completed') {
                    return '<span class="badge badge-md badge-success">'. trans('admin::app.sales.orders.order-status-success') .'</span>';
                } elseif ($value->status == "canceled") {
                    return '<span class="badge badge-md badge-danger">'. trans('admin::app.sales.orders.order-status-canceled') .'</span>';
                } elseif ($value->status == "closed") {
                    return '<span class="badge badge-md badge-info">'. trans('admin::app.sales.orders.order-status-closed') .'</span>';
                } elseif ($value->status == "pending") {
                    return '<span class="badge badge-md badge-warning">'. trans('admin::app.sales.orders.order-status-pending') .'</span>';
                } elseif ($value->status == "pending_payment") {
                    return '<span class="badge badge-md badge-warning">'. trans('admin::app.sales.orders.order-status-pending-payment') .'</span>';
                } elseif ($value->status == "fraud") {
                    return '<span class="badge badge-md badge-danger">'. trans('admin::app.sales.orders.order-status-fraud') . '</span>';
                }
            },
        ]);

        $this->addColumn([
            'index'      => 'billed_to',
            'label'      => trans('admin::app.datagrid.billed-to'),
            'type'       => 'string',
            'searchable' => false,
            'sortable'   => false,
            'filterable' => false,
        ]);

        // $this->addColumn([
        //     'index'      => 'shipped_to',
        //     'label'      => trans('admin::app.datagrid.shipped-to'),
        //     'type'       => 'string',
        //     'searchable' => false,
        //     'sortable'   => false,
        //     'filterable' => false,
        // ]);
    }

    public function prepareActions()
    {
        $this->addAction([
            'title'  => trans('admin::app.datagrid.view'),
            'method' => 'GET',
            'route'  => 'admin.sales.orders.view',
            'icon'   => 'icon eye-icon',
        ]);
    }
}`

**Comment by devansh-webkul** [comment]
Hi @akshaypitale,

I really an apology for the late reply. Does the problem still persist? If not then let me know, I will help you.

**Comment by akshaypitale** [comment]
Hi @devansh-webkul , 

Yes, The problem is still persist.

**Comment by devansh-webkul** [comment]
Hi @akshaypitale,

Can you share with me your error log and steps on how you created your Datagrid.

**Comment by akshaypitale** [comment]
> Hi @akshaypitale,
> 
> Can you share with me your error log and steps on how you created your Datagrid.

Hi @devansh-webkul ,

I tried below two queries but it still giving me the same results.
1) First One
$queryBuilder = DB::table('orders')
->leftJoin('addresses as order_address_shipping', function($leftJoin) {
$leftJoin->on('order_address_shipping.order_id', '=', 'orders.id')
->where('order_address_shipping.address_type', OrderAddress::ADDRESS_TYPE_SHIPPING);
})
->leftJoin('addresses as order_address_billing', function($leftJoin) {
$leftJoin->on('order_address_billing.order_id', '=', 'orders.id')
->where('order_address_billing.address_type', OrderAddress::ADDRESS_TYPE_BILLING);
})
->addSelect('orders.id','orders.increment_id', 'orders.base_sub_total', 'orders.base_grand_total', 'orders.created_at', 'channel_name', 'status')
->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_billing.first_name, " ", ' . DB::getTablePrefix() . 'order_address_billing.last_name) as billed_to'))
->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_shipping.first_name, " ", ' . DB::getTablePrefix() . 'order_address_shipping.last_name) as shipped_to'))
->orderBy('id', 'DESC')
->take(5);


2) 2nd one
$queryBuilder = DB::table('orders')
->leftJoin('addresses as order_address_shipping', function($leftJoin) {
$leftJoin->on('order_address_shipping.order_id', '=', 'orders.id')
->where('order_address_shipping.address_type', OrderAddress::ADDRESS_TYPE_SHIPPING);
})
->leftJoin('addresses as order_address_billing', function($leftJoin) {
$leftJoin->on('order_address_billing.order_id', '=', 'orders.id')
->where('order_address_billing.address_type', OrderAddress::ADDRESS_TYPE_BILLING);
})
->addSelect('orders.id','orders.increment_id', 'orders.base_sub_total', 'orders.base_grand_total', 'orders.created_at', 'channel_name', 'status')
->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_billing.first_name, " ", ' . DB::getTablePrefix() . 'order_address_billing.last_name) as billed_to'))
->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_shipping.first_name, " ", ' . DB::getTablePrefix() . 'order_address_shipping.last_name) as shipped_to'))
->orderBy('id', 'DESC')
->limit(5);

**Comment by devansh-webkul** [comment]
Hi @akshaypitale,

May I know why are you using take or limit in Datagrid? Because if you are using data grid then this file i.e. `https://github.com/bagisto/bagisto/blob/5b493cd456ccc0e428d4ea0012adeb572371c3c6/packages/Webkul/Ui/src/DataGrid/DataGrid.php#L322` will automatically do for you everything.

**Comment by akshaypitale** [comment]
> Hi @akshaypitale,
> 
> May I know why are you using take or limit in Datagrid? Because if you are using data grid then this file i.e.,
> https://github.com/bagisto/bagisto/blob/5b493cd456ccc0e428d4ea0012adeb572371c3c6/packages/Webkul/Ui/src/DataGrid/DataGrid.php#L322
> will automatically do for you everything.

For display recent 5 orders on dashboard.

**Comment by devansh-webkul** [comment]
Ok!

Can you share with me the full file where you have added this query?

**Comment by akshaypitale** [comment]
> Ok!
> 
> Can you share with me the full file where you have added this query?

I don't have file right now but will share with you as soon as possible.

But the thing is I don't even change that much in the file, it is a query which giving me the issue.

**Comment by devansh-webkul** [comment]
> > Hi @akshaypitale,
> > Can you share with me your error log and steps on how you created your Datagrid.
> 
> Hi @devansh-webkul ,
> 
> I tried below two queries but it still giving me the same results.
> 
>     1. First One
>        $queryBuilder = DB::table('orders')
>        ->leftJoin('addresses as order_address_shipping', function($leftJoin) {
>        $leftJoin->on('order_address_shipping.order_id', '=', 'orders.id')
>        ->where('order_address_shipping.address_type', OrderAddress::ADDRESS_TYPE_SHIPPING);
>        })
>        ->leftJoin('addresses as order_address_billing', function($leftJoin) {
>        $leftJoin->on('order_address_billing.order_id', '=', 'orders.id')
>        ->where('order_address_billing.address_type', OrderAddress::ADDRESS_TYPE_BILLING);
>        })
>        ->addSelect('orders.id','orders.increment_id', 'orders.base_sub_total', 'orders.base_grand_total', 'orders.created_at', 'channel_name', 'status')
>        ->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_billing.first_name, " ", ' . DB::getTablePrefix() . 'order_address_billing.last_name) as billed_to'))
>        ->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_shipping.first_name, " ", ' . DB::getTablePrefix() . 'order_address_shipping.last_name) as shipped_to'))
>        ->orderBy('id', 'DESC')
>        ->take(5);
> 
>     2. 2nd one
>        $queryBuilder = DB::table('orders')
>        ->leftJoin('addresses as order_address_shipping', function($leftJoin) {
>        $leftJoin->on('order_address_shipping.order_id', '=', 'orders.id')
>        ->where('order_address_shipping.address_type', OrderAddress::ADDRESS_TYPE_SHIPPING);
>        })
>        ->leftJoin('addresses as order_address_billing', function($leftJoin) {
>        $leftJoin->on('order_address_billing.order_id', '=', 'orders.id')
>        ->where('order_address_billing.address_type', OrderAddress::ADDRESS_TYPE_BILLING);
>        })
>        ->addSelect('orders.id','orders.increment_id', 'orders.base_sub_total', 'orders.base_grand_total', 'orders.created_at', 'channel_name', 'status')
>        ->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_billing.first_name, " ", ' . DB::getTablePrefix() . 'order_address_billing.last_name) as billed_to'))
>        ->addSelect(DB::raw('CONCAT(' . DB::getTablePrefix() . 'order_address_shipping.first_name, " ", ' . DB::getTablePrefix() . 'order_address_shipping.last_name) as shipped_to'))
>        ->orderBy('id', 'DESC')
>        ->limit(5);

These queries can be executed anywhere but make sure you have imported all the classed which are required,

~~~php
use Illuminate\Support\Facades\DB;
use Webkul\Sales\Models\OrderAddress;
~~~

**Comment by devansh-webkul** [comment]
Please refer to the above and let me know.

**Comment by devansh-webkul** [comment]
Does the thing work for you?

**Comment by devansh-webkul** [comment]
Hi @akshaypitale,

Any update on this?

**Comment by akshaypitale** [comment]
> Hi @akshaypitale,
> 
> Any update on this?

Will try solution today and update you on the same.

**Comment by devansh-webkul** [comment]
Hi @akshaypitale,

Any update?

**Comment by devansh-webkul** [comment]
As this is not an issue, I am closing this. If any query please use the below channel,

https://forums.bagisto.com/
