### ISSUE TITLE
Easy bug: incorrect PL lang file

### ISSUE THREAD

**Issue by mwl4** [bagisto/bagisto#3371]
# Bug report

Missing some characters in https://github.com/bagisto/bagisto/blame/master/packages/Webkul/Ui/src/Resources/lang/pl/app.php#L34
it breaks whole file I believe.

**Comment by vaishaliwebkul** [comment]
Hi @mw14

Thanks for reporting

![Screenshot (81)](https://user-images.githubusercontent.com/43210406/85996469-6d157a80-ba22-11ea-8f8b-52a8c958325f.png)
