### ISSUE TITLE
Social Login Error

### ISSUE THREAD

**Issue by raulidavid** [bagisto/bagisto#3374]
Target [Webkul\SocialLogin\Contracts\CustomerSocialAccount] is not instantiable while building [Webkul\SocialLogin\Http\Controllers\LoginController]
![issue](https://user-images.githubusercontent.com/10199628/85952430-d6b45c80-b92e-11ea-8482-1cb38ab2e314.PNG)

**Comment by jitendra-webkul** [comment]
Hi @raulidavid , please run the following command:

composer dump-autoload

**Comment by jitendra-webkul** [comment]
Take a pull from master and run the following command:

php artisan vedor:publish --force

**Comment by raulidavid** [comment]
Thanks it is resolved 

php artisan vendor:publish --force

It was the solution

**Comment by shahirWebo** [comment]
its not work for me

**Comment by vaishaliwebkul** [comment]
@shahirWebo 
May I know on which Bagisto version you're getting this issue?
