### ISSUE TITLE
Getting error on migration command.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3379]
# Bug report

### Title
Getting error on migration command.

### Issue Description
Getting error on migration command.
### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-master

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1- take a pull from latest master
    2. step2- run migrate command

### Expected 
command should be executed
### Actual result

Getting error
![Workspace 1_138](https://user-images.githubusercontent.com/45203177/86002787-7a386680-ba2e-11ea-8bc4-fe4408c3d096.png)

**Comment by ghermans** [comment]
This issue was already reported in #3373
