### ISSUE TITLE
Layout issues on mobile view in ar locale 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3380]
# Bug report

### Title
Layout issues on mobile view in ar locale 

### Preconditions

    1. framework Version. Master
 

### Steps to reproduce
    1. step1 - open front end in mobile view 
    2. step2- change the locale to ar

### Actual result

https://prnt.sc/t8gkm8

**Comment by vaishaliwebkul** [comment]
@shubhwebkul 
we can also fix the number indicator showing in ar mobile view as all the icons available in header are getting hidden.

![Screenshot (3)](https://user-images.githubusercontent.com/43210406/86255489-cc1af100-bbd4-11ea-80f0-5ff9ce4cd54b.png)

**Comment by vaishaliwebkul** [comment]
fixed
