### ISSUE TITLE
Getting exception when trying to login with any social sites.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3388]
# Bug report

### Title
Getting exception when trying to login with any social sites.
### Issue Description
Getting exception when trying to login with any social sites.
### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Click on any social signin button
  

### Expected result
It should redirect for login
### Actual result

Getting exception

![Workspace 1_141](https://user-images.githubusercontent.com/45203177/86131588-77f40c00-bb03-11ea-981f-11e46630e91b.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
follow this solution https://github.com/bagisto/bagisto/issues/3369

**Comment by rahulcs0082** [comment]
Hi @jyoti-webkul 

Kindly run **composer install** at the root of project than check.
