### ISSUE TITLE
Getting broken image link for Invoice Slip Design.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3389]
# Bug report

### Title
Getting broken image link for Invoice Slip Design.
### Issue Description
Getting broken image link for Invoice Slip Design.
### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- go to configure->sales->order setting

### Expected result
Uploaded image should display

### Actual result

Getting broken image link

![Screenshot (83)](https://user-images.githubusercontent.com/45203177/86137258-b640f980-bb0a-11ea-9b04-53f310bcf967.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
this is working fine as expected https://prnt.sc/t98iyv
