### ISSUE TITLE
Getting broken image link for locales in mobile view.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3393]
# Bug report

### Title
Getting broken image link for locales in mobile view.
### Issue Description
Getting broken image link for locales in mobile view.
### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- change locale to arabic
    2. step2-go to mobile view

### Expected result
Locale should visible as in desktop mode

### Actual result

![Screenshot (84)](https://user-images.githubusercontent.com/45203177/86210724-b4bb1400-bb92-11ea-9b58-08d6eae8bb3c.png)

**Comment by rahulcs0082** [comment]
Hi @jyoti-webkul 

Kindly upload images in locale than check as it working fine at my end.

**Comment by vaishaliwebkul** [comment]
@rahulcs0082 
default en locale image is added but in mobile view it's broken.
 
Also the locale without logo should be not visible with broken image

https://prnt.sc/tdz6xc
https://prnt.sc/tdz7f0

**Comment by vaishaliwebkul** [comment]
fixed https://prnt.sc/tq08dp
