### ISSUE TITLE
Not able to open menu in mobile view having locale arabic.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3394]
# Bug report

### Title
Not able to open menu in mobile view having locale arabic.
### Issue Description
Not able to open menu in mobile view having locale arabic.

### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Go to mobile view
    2. step2- change locale to arabic and click on menu

### Expected result
Menu bar should get open
### Actual result

![Workspace 1_142](https://user-images.githubusercontent.com/45203177/86212252-4e83c080-bb95-11ea-8544-e1ea0479c4d0.png)

**Comment by bhanu-webkul** [comment]
fixed in master
