### ISSUE TITLE
Not getting any response after uploading picture in search field of product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3397]
# Bug report

### Title
Not getting any response after uploading picture in search field of product.
### Issue Description
Not getting any response after uploading picture in search field of product.
### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1-Go to Search Product here and upload a product to search.

### Expected result
After uploading picture it should show any response

### Actual result
Not getting any response after uploading picture

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
As I have checked it's working fine.

![Screenshot (11)](https://user-images.githubusercontent.com/43210406/86456309-7f075e00-bd3f-11ea-92cc-c6a7f40eaded.png)
