### ISSUE TITLE
Compare option is not available in locale other than english.From wishlist also add to compare option is not available.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3398]
# Bug report

### Title
Compare option is not available in locale other than english.
### Issue Description
Compare option is not available in locale other than english.
### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Change locale to any other than english
    2. step2- Check compare section in header

### Expected result

Compare option should be available
### Actual result

![Screenshot (87)](https://user-images.githubusercontent.com/45203177/86242127-d253a200-bbc1-11ea-9f63-88cfd99d45bd.png)
![Screenshot (86)](https://user-images.githubusercontent.com/45203177/86242133-d41d6580-bbc1-11ea-8758-a3758a3ae96d.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
make sure the compare feature should be available for all locale in the configuration else it will not show in Interface.
