### ISSUE TITLE
Remove from wishlist button is displaying as 1 when mouse not hover on product, this occur in all locale except English.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3399]
# Bug report

### Title
Remove from wishlist button is displaying as 1 when mouse not hover on product, this occur in all locale except English.
### Issue Description
Remove from wishlist button is displaying as 1 when mouse not hover on product, this occur in all locale except English.
### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Add a product in wishlist
    2. step2- Change locale to other than english, and check by moving mouse from product to any blank space

### Expected result
Button should display as in english locale

### Actual result

![Screenshot (85)](https://user-images.githubusercontent.com/45203177/86243024-3f1b6c00-bbc3-11ea-81a8-598e14df7ebd.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
it's resolved now https://prnt.sc/tl46na
