### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by ktrofimov** [bagisto/bagisto#3401]
# Bug report

### Title
Both Web and CLI install issues

### Issue Description
Web install stuck at database step - "Save & Continue" does nothing
CLI fails at table creation if .env contains anything in DB_PREFIX variable

### Preconditions
    1. framework 1.1.2
    2. Commit c88ca31

### Steps to reproduce
1. Run Web installer:
  Check prerequisites - OK
  Fill App name, URL, currency timezone and locale - OK
  Fill Mysql DB parameters - Can't save and continue, no error messages

2. Run CLI installer (https://devdocs.bagisto.com/index.html#installation)
If .env file contains any DB_PREFIX then 
    #php artisan migrate 
fails with the following message:
...
Migrating: 2020_04_16_185147_add_table_addresses

In Connection.php line 669:
                                                                                                                                             
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bagisto.customers' doesn't exist (SQL:             INSERT INTO mwzh_addresses(  
                  address_type,                                                                                                              
                  customer_id,                                                                                                               
                  first_name,                                                                                                                
                  last_name,                                                                                                                 
                  gender,                                                                                                                    
                  company_name,                                                                                                              
                  address1,                                                                                                                  
                  address2,                                                                                                                  
                  postcode,                                                                                                                  
                  city,                                                                                                                      
                  state,                                                                                                                     
                  country,                                                                                                                   
                  email,                                                                                                                     
                  phone,                                                                                                                     
                  default_address,                                                                                                           
                  additional,                                                                                                                
                  created_at,                                                                                                                
                  updated_at                                                                                                                 
              )                                                                                                                              
              SELECT                                                                                                                         
                  "customer",                                                                                                                
                  customer_id,                                                                                                               
                  first_name,                                                                                                                
                  last_name,                                                                                                                 
                  (SELECT gender FROM customers c WHERE c.id=ca.customer_id),                                                                
                  company_name,                                                                                                              
                  address1,                                                                                                                  
                  address2,                                                                                                                  
                  postcode,                                                                                                                  
                  city,                                                                                                                      
                  state,                                                                                                                     
                  country,                                                                                                                   
                  null,                                                                                                                      
                  phone,                                                                                                                     
                  default_address,                                                                                                           
                  JSON_INSERT('{}', '$.old_customer_address_id', id),                                                                        
                  created_at,                                                                                                                
                  updated_at                                                                                                                 
              FROM customer_addresses ca;)
In PDOConnection.php line 43:
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bagisto.customers' doesn't exist 
In PDOConnection.php line 41:
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bagisto.customers' doesn't exist

**Comment by vaishaliwebkul** [comment]
Hello @ktrofimov 
this issue has been resolved in the master branch.
you can resolve by updating files mention in the below PR

Issue : https://github.com/bagisto/bagisto/issues/3051
PR : https://github.com/bagisto/bagisto/pull/3060

**Comment by thinklifepot** [comment]
@vaishaliwebkul Please help i get this error, when trying to run the app

Trying to get property 'default_locale' of non-object

**Comment by vaishaliwebkul** [comment]
@thinklifepot 

run the db seeder: 

**php artisan db:seed**
**composer dump-autoload**

**Comment by thinklifepot** [comment]
this is what i get when i run db:seed

Column not found: 1054 Unknown column 'default_name' in 'field list' (SQL: insert into `dbcountr  
  y_state_translations` (`country_state_id`, `default_name`, `locale`) values (1, ألاباما, ar), (2, ألاسكا, ar), (3  
  , ساموا الأمريكية, ar), (4, أريزونا, ar), (5, أركنساس, ar), (6, القوات المسلحة أفريقيا, ar), (7, القوات المسلحة ا  
  لأمريكية, ar), (8, القوات المسلحة الكندية, ar), (9, القوات المسلحة أوروبا, ar), (10, القوات المسلحة الشرق الأوسط,  
   ar), (11, القوات المسلحة في المحيط الهادئ, ar), (12, كاليفورنيا, ar), (13, كولورادو, ar), (14, كونيتيكت, ar), (1  
  5, ديلاوير, ar), (16, مقاطعة كولومبيا, ar), (17, ولايات ميكرونيزيا الموحدة, ar), (18, فلوريدا, ar), (19, جورجيا,   
  ar), (20, غوام, ar), (21, هاواي, ar), (22, ايداهو, ar), (23, إلينوي, ar), (24, إنديانا, ar), (25, أيوا, ar), (26,  
   كانساس, ar), (27, كنتاكي, ar), (28, لويزيانا, ar), (29, مين, ar), (30, جزر مارشال, ar), (31, ماريلاند, ar), (32,  
   ماساتشوستس, ar), (33, ميشيغان, ar), (34, مينيسوتا, ar), (35, ميسيسيبي, ar), (36, ميسوري, ar), (37, مونتانا, ar),  
   (38, نبراسكا, ar), (39, نيفادا, ar), (40, نيو هامبشاير, ar), (41, نيو جيرسي, ar), (42, المكسيك جديدة, ar), (43,   
  نيويورك, ar), (44, شمال كارولينا, ar), (45, شمال داكوتا, ar), (46, جزر مريانا الشمالية, ar), (47, أوهايو, ar), (4  
  8, أوكلاهوما, ar), (49, ولاية أوريغون, ar), (50, بالاو, ar), (51, بنسلفانيا, ar), (52, بورتوريكو, ar), (53, جزيرة  
   رود, ar), (54, كارولينا الجنوبية, ar), (55, جنوب داكوتا, ar), (56, تينيسي, ar), (57, تكساس, ar), (58, يوتا, ar),  
   (59, فيرمونت, ar), (60, جزر فيرجن, ar), (61, فرجينيا, ar), (62, واشنطن, ar), (63, فرجينيا الغربية, ar), (64, ولا  
  ية ويسكونسن, ar), (65, وايومنغ, ar), (66, ألبرتا, ar), (67, كولومبيا البريطانية, ar), (68, مانيتوبا, ar), (69, ني  
  وفاوندلاند ولابرادور, ar), (70, برونزيك جديد, ar), (71, مقاطعة نفوفا سكوشيا, ar), (72, الاقاليم الشمالية الغربية,  
   ar), (73, نونافوت, ar), (74, أونتاريو, ar), (75, جزيرة الأمير ادوارد, ar), (76, كيبيك, ar), (77, ساسكاتشوان, ar)  
  , (78, إقليم يوكون, ar), (79, Niedersachsen, ar), (80, بادن فورتمبيرغ, ar), (81, بايرن ميونيخ, ar), (82, برلين, a  
  r), (83, براندنبورغ, ar), (84, بريمن, ar), (85, هامبورغ, ar), (86, هيسن, ar), (87, مكلنبورغ-فوربومرن, ar), (88, ن  
  وردراين فيستفالن, ar), (89, راينلاند-بفالز, ar), (90, سارلاند, ar), (91, ساكسن, ar), (92, سكسونيا أنهالت, ar), (9  
  3, شليسفيغ هولشتاين, ar), (94, تورنغن, ar), (95, فيينا, ar), (96, النمسا السفلى, ar), (97, النمسا العليا, ar), (9  
  8, سالزبورغ, ar), (99, Каринтия, ar), (100, STEIERMARK, ar), (101, تيرول, ar), (102, بورغنلاند, ar), (103, فورارل  
  برغ, ar), (104, أرجاو, ar), (105, Appenzell Innerrhoden, ar), (106, أبنزل أوسيرهودن, ar), (107, برن, ar), (108, ك  
  انتون ريف بازل, ar), (109, بازل شتات, ar), (110, فرايبورغ, ar), (111, Genf, ar), (112, جلاروس, ar), (113, غراوبون  
  دن, ar), (114, العصر الجوارسي أو الجوري, ar), (115, لوزيرن, ar), (116, في Neuenburg, ar), (117, نيدوالدن, ar), (1  
  18, أوبوالدن, ar), (119, سانت غالن, ar), (120, شافهاوزن, ar), (121, سولوتورن, ar), (122, شفيتس, ar), (123, ثورجو,  
   ar), (124, تيتشينو, ar), (125, أوري, ar), (126, وادت, ar), (127, اليس, ar), (128, زوغ, ar), (129, زيورخ, ar), (1  
  30, Corunha, ar), (131, ألافا, ar), (132, الباسيتي, ar), (133, اليكانتي, ar), (134, الميريا, ar), (135, أستورياس,  
   ar), (136, أفيلا, ar), (137, بطليوس, ar), (138, البليار, ar), (139, برشلونة, ar), (140, برغش, ar), (141, كاسيريس  
  , ar), (142, كاديز, ar), (143, كانتابريا, ar), (144, كاستيلون, ar), (145, سبتة, ar), (146, سيوداد ريال, ar), (147  
  , قرطبة, ar), (148, كوينكا, ar), (149, جيرونا, ar), (150, غرناطة, ar), (151, غوادالاخارا, ar), (152, بجويبوزكوا,   
  ar), (153, هويلفا, ar), (154, هويسكا, ar), (155, خاين, ar), (156, لاريوخا, ar), (157, لاس بالماس, ar), (158, ليون  
  , ar), (159, يدا, ar), (160, لوغو, ar), (161, مدريد, ar), (162, ملقة, ar), (163, مليلية, ar), (164, مورسيا, ar),   
  (165, نافارا, ar), (166, أورينس, ar), (167, بلنسية, ar), (168, بونتيفيدرا, ar), (169, سالامانكا, ar), (170, سانتا  
   كروز دي تينيريفي, ar), (171, سيغوفيا, ar), (172, اشبيلية, ar), (173, سوريا, ar), (174, تاراغونا, ar), (175, تيرو  
  يل, ar), (176, توليدو, ar), (177, فالنسيا, ar), (178, بلد الوليد, ar), (179, فيزكايا, ar), (180, زامورا, ar), (18  
  1, سرقسطة, ar), (182, عين, ar), (183, أيسن, ar), (184, اليي, ar), (185, ألب البروفنس العليا, ar), (186, أوتس ألب,  
   ar), (187, ألب ماريتيم, ar), (188, ARDECHE, ar), (189, Ardennes, ar), (190, آردن, ar), (191, أوب, ar), (192, اود  
  , ar), (193, أفيرون, ar), (194, بوكاس دو رون, ar), (195, كالفادوس, ar), (196, كانتال, ar), (197, شارانت, ar), (19  
  8, سيين إت مارن, ar), (199, شير, ar), (200, كوريز, ar), (201, سود كورس-دو-, ar), (202, هوت كورس, ar), (203, كوستا  
   دوركوريز, ar), (204, كوتس دورمور, ar), (205, كروز, ar), (206, دوردوني, ar), (207, دوبس, ar), (208, DrômeFinistèr  
  e, ar), (209, أور, ar), (210, أور ولوار, ar), (211, فينيستير, ar), (212, جارد, ar), (213, هوت غارون, ar), (214, ا  
  لخيام, ar), (215, جيروند, ar), (216, هيرولت, ar), (217, إيل وفيلان, ar), (218, إندر, ar), (219, أندر ولوار, ar),   
  (220, إيسر, ar), (221, العصر الجوارسي أو الجوري, ar), (222, اندز, ar), (223, لوار وشير, ar), (224, لوار, ar), (22  
  5, هوت-لوار, ar), (226, وار أتلانتيك, ar), (227, لورا, ar), (228, كثيرا, ar), (229, الكثير غارون, ar), (230, لوزر  
  , ar), (231, مين-إي-لوار, ar), (232, المانش, ar), (233, مارن, ar), (234, هوت مارن, ar), (235, مايين, ar), (236, م  
  ورت وموزيل, ar), (237, ميوز, ar), (238, موربيهان, ar), (239, موسيل, ar), (240, نيفر, ar), (241, نورد, ar), (242,   
  إيل دو فرانس, ar), (243, أورن, ar), (244, با-دو-كاليه, ar), (245, بوي دي دوم, ar), (246, البرانيس ​​الأطلسية, ar)  
  , (247, أوتس-بيرينيهs, ar), (248, بيرينيه-أورينتال, ar), (249, بس رين, ar), (250, أوت رين, ar), (251, رون [3], ar  
  ), (252, هوت-سون, ar), (253, سون ولوار, ar), (254, سارت, ar), (255, سافوا, ar), (256, هاوت سافوي, ar), (257, باري  
  س, ar), (258, سين البحرية, ar), (259, سيين إت مارن, ar), (260, إيفلين, ar), (261, دوكس سفرس, ar), (262, السوم, ar  
  ), (263, تارن, ar), (264, تارن وغارون, ar), (265, فار, ar), (266, فوكلوز, ar), (267, تارن, ar), (268, فيين, ar),   
  (269, هوت فيين, ar), (270, الفوج, ar), (271, يون, ar), (272, تيريتوير-دي-بلفور, ar), (273, إيسون, ar), (274, هوت   
  دو سين, ar), (275, سين سان دوني, ar), (276, فال دو مارن, ar), (277, فال دواز, ar), (278, ألبا, ar), (279, اراد, a  
  r), (280, ARGES, ar), (281, باكاو, ar), (282, بيهور, ar), (283, بيستريتا ناسود, ar), (284, بوتوساني, ar), (285, ب  
  راشوف, ar), (286, برايلا, ar), (287, بوخارست, ar), (288, بوزاو, ar), (289, كاراس سيفيرين, ar), (290, كالاراسي, ar  
  ), (291, كلوج, ar), (292, كونستانتا, ar), (293, كوفاسنا, ar), (294, دامبوفيتا, ar), (295, دولج, ar), (296, جالاتي  
  , ar), (297, Giurgiu, ar), (298, غيورغيو, ar), (299, هارغيتا, ar), (300, هونيدوارا, ar), (301, ايالوميتا, ar), (3  
  02, ياشي, ar), (303, إيلفوف, ar), (304, مارامريس, ar), (305, MEHEDINTI, ar), (306, موريس, ar), (307, نيامتس, ar),  
   (308, أولت, ar), (309, براهوفا, ar), (310, ساتو ماري, ar), (311, سالاج, ar), (312, سيبيو, ar), (313, سوسيفا, ar)  
  , (314, تيليورمان, ar), (315, تيم هو, ar), (316, تولسيا, ar), (317, فاسلوي, ar), (318, فالسيا, ar), (319, فرانتشا  
  , ar), (320, Lappi, ar), (321, Pohjois-Pohjanmaa, ar), (322, كاينو, ar), (323, Pohjois-كارجالا, ar), (324, Pohjoi  
  s-سافو, ar), (325, Etelä-سافو, ar), (326, Etelä-Pohjanmaa, ar), (327, Pohjanmaa, ar), (328, بيركنما, ar), (329, س  
  اتا كونتا, ar), (330, كسكي-Pohjanmaa, ar), (331, كسكي-سومي, ar), (332, Varsinais-سومي, ar), (333, Etelä-كارجالا,   
  ar), (334, Päijät-Häme, ar), (335, كانتا-HAME, ar), (336, أوسيما, ar), (337, أوسيما, ar), (338, كومنلاكسو, ar), (  
  339, Ahvenanmaa, ar), (340, Harjumaa, ar), (341, هيوما, ar), (342, المؤسسة الدولية للتنمية فيروما, ar), (343, جوغ  
  فما, ar), (344, يارفا, ar), (345, انيما, ar), (346, اني فيريوما, ar), (347, بولفاما, ar), (348, بارنوما, ar), (34  
  9, Raplamaa, ar), (350, Saaremaa, ar), (351, Tartumaa, ar), (352, Valgamaa, ar), (353, Viljandimaa, ar), (354, رو  
  ايات Salacgr novvas, ar), (355, داوجافبيلس, ar), (356, يلغافا, ar), (357, يكاب, ar), (358, يورمال, ar), (359, ياب  
  ايا, ar), (360, ليباج أبريس, ar), (361, ريزكن, ar), (362, ريغا, ar), (363, مقاطعة ريغا, ar), (364, فالميرا, ar),   
  (365, فنتسبيلز, ar), (366, روايات Aglonas, ar), (367, Aizkraukles novads, ar), (368, Aizkraukles novads, ar), (36  
  9, Aknīstes novads, ar), (370, Alojas novads, ar), (371, روايات Alsungas, ar), (372, ألكسنس أبريز, ar), (373, روا  
  يات أماتاس, ar), (374, قرود الروايات, ar), (375, روايات أوسيس, ar), (376, بابيت الروايات, ar), (377, Baldones الر  
  وايات, ar), (378, بالتينافاس الروايات, ar), (379, روايات بالفو, ar), (380, Bauskas الروايات, ar), (381, Beverīnas  
   novads, ar), (382, Novads Brocēnu, ar), (383, Novads Burtnieku, ar), (384, Carnikavas novads, ar), (385, Cesvain  
  es novads, ar), (386, Ciblas novads, ar), (387, تسو أبريس, ar), (388, Dagdas novads, ar), (389, Daugavpils novads  
  , ar), (390, روايات دوبيليس, ar), (391, ديربيس الروايات, ar), (392, ديربيس الروايات, ar), (393, يشرك الروايات, ar  
  ), (394, Garkalnes novads, ar), (395, Grobiņas novads, ar), (396, غولبينيس الروايات, ar), (397, إيكافاس روايات, a  
  r), (398, Ikškiles novads, ar), (399, Ilūkstes novads, ar), (400, روايات Inčukalna, ar), (401, Jaunjelgavas novad  
  s, ar), (402, Jaunpiebalgas novads, ar), (403, روايات Jaunpiebalgas, ar), (404, Jelgavas novads, ar), (405, جيكاب  
  يلس أبريز, ar), (406, روايات كاندافاس, ar), (407, Kokneses الروايات, ar), (408, Krimuldas novads, ar), (409, Krus  
  tpils الروايات, ar), (410, Krāslavas Apriņķis, ar), (411, كولدوغاس أبريز, ar), (412, Kārsavas novads, ar), (413,   
  روايات ييلفاريس, ar), (414, ليمباو أبريز, ar), (415, روايات لباناس, ar), (416, روايات لودزاس, ar), (417, مقاطعة ل  
  يجاتني, ar), (418, مقاطعة ليفاني, ar), (419, مادونا روايات, ar), (420, Mazsalacas novads, ar), (421, روايات مالبل  
  ز, ar), (422, Mārupes novads, ar), (423, نوفاو نوكشنو, ar), (424, روايات نيريتاس, ar), (425, روايات نيكاس, ar), (  
  426, أغنام الروايات, ar), (427, أولينيس الروايات, ar), (428, روايات Ozolnieku, ar), (429, بريسيو أبرييس, ar), (43  
  0, Priekules الروايات, ar), (431, كوندادو دي بريكوي, ar), (432, Pärgaujas novads, ar), (433, روايات بافيلوستاس, a  
  r), (434, بلافيناس مقاطعة, ar), (435, روناس روايات, ar), (436, Riebiņu novads, ar), (437, روجاس روايات, ar), (438  
  , Novads روباو, ar), (439, روكافاس روايات, ar), (440, روغاجو روايات, ar), (441, رندلس الروايات, ar), (442, Radzek  
  nes novads, ar), (443, Rūjienas novads, ar), (444, بلدية سالاسغريفا, ar), (445, روايات سالاس, ar), (446, Salaspil  
  s novads, ar), (447, روايات سالدوس, ar), (448, Novuls Saulkrastu, ar), (449, سيغولداس روايات, ar), (450, Skrundas  
   novads, ar), (451, مقاطعة Skrīveri, ar), (452, يبتسم الروايات, ar), (453, روايات Stopiņu, ar), (454, روايات Stre  
  n novu, ar), (455, سجاس روايات, ar), (456, روايات تالسو, ar), (457, توكوما الروايات, ar), (458, Tērvetes novads,   
  ar), (459, Vaiņodes novads, ar), (460, فالكاس الروايات, ar), (461, فالميراس الروايات, ar), (462, مقاطعة فاكلاني,   
  ar), (463, Vecpiebalgas novads, ar), (464, روايات Vecumnieku, ar), (465, فنتسبيلس الروايات, ar), (466, Viesītes N  
  ovads, ar), (467, Viļakas novads, ar), (468, روايات فيناو, ar), (469, Vārkavas novads, ar), (470, روايات زيلوبس,   
  ar), (471, مقاطعة أدازي, ar), (472, مقاطعة Erglu, ar), (473, مقاطعة كيغمس, ar), (474, مقاطعة كيكافا, ar), (475, A  
  lytaus Apskritis, ar), (476, كاونو ابكريتيس, ar), (477, Klaipėdos apskritis, ar), (478, Marijampol's apskritis, a  
  r), (479, Panevėžio apskritis, ar), (480, uliaulių apskritis, ar), (481, Taurag's apskritis, ar), (482, Telšių ap  
  skritis, ar), (483, Utenos apskritis, ar), (484, فيلنياوس ابكريتيس, ar), (485, فدان, ar), (486, ألاغواس, ar), (48  
  7, أمابا, ar), (488, أمازوناس, ar), (489, باهيا, ar), (490, سيارا, ar), (491, إسبيريتو سانتو, ar), (492, غوياس, a  
  r), (493, مارانهاو, ar), (494, ماتو جروسو, ar), (495, ماتو جروسو دو سول, ar), (496, ميناس جريس, ar), (497, بارا,   
  ar), (498, بارايبا, ar), (499, بارانا, ar), (500, بيرنامبوكو, ar), (501, بياوي, ar), (502, ريو دي جانيرو, ar), (5  
  03, ريو غراندي دو نورتي, ar), (504, ريو غراندي دو سول, ar), (505, روندونيا, ar), (506, رورايما, ar), (507, سانتا   
  كاتارينا, ar), (508, ساو باولو, ar), (509, سيرغيبي, ar), (510, توكانتينز, ar), (511, وفي مقاطعة الاتحادية, ar), (  
  512, Zagrebačka زوبانيا, ar), (513, Krapinsko-zagorska زوبانيا, ar), (514, Sisačko-moslavačka زوبانيا, ar), (515,  
   كارلوفيتش شوبانيا, ar), (516, فارادينسكا زوبانيجا, ar), (517, Koprivničko-križevačka زوبانيجا, ar), (518, بيلوفا  
  رسكو-بيلوجورسكا, ar), (519, بريمورسكو غورانسكا سوبانيا, ar), (520, ليكو سينيسكا زوبانيا, ar), (521, Virovitičko-p  
  odravska زوبانيا, ar), (522, Požeško-slavonska županija, ar), (523, Brodsko-posavska županija, ar), (524, زادارسك  
  ا زوبانيجا, ar), (525, Osječko-baranjska županija, ar), (526, شيبنسكو-كنينسكا سوبانيا, ar), (527, Virovitičko-pod  
  ravska زوبانيا, ar), (528, Splitsko-dalmatinska زوبانيا, ar), (529, Istarska زوبانيا, ar), (530, Dubrovačko-neret  
  vanska زوبانيا, ar), (531, Međimurska زوبانيا, ar), (532, غراد زغرب, ar), (533, جزر أندامان ونيكوبار, ar), (534,   
  ولاية اندرا براديش, ar), (535, اروناتشال براديش, ar), (536, أسام, ar), (537, بيهار, ar), (538, شانديغار, ar), (53  
  9, تشهاتيسجاره, ar), (540, دادرا ونجار هافيلي, ar), (541, دامان وديو, ar), (542, دلهي, ar), (543, غوا, ar), (544,  
   غوجارات, ar), (545, هاريانا, ar), (546, هيماشال براديش, ar), (547, جامو وكشمير, ar), (548, جهارخاند, ar), (549,   
  كارناتاكا, ar), (550, ولاية كيرالا, ar), (551, اكشادويب, ar), (552, ماديا براديش, ar), (553, ماهاراشترا, ar), (55  
  4, مانيبور, ar), (555, ميغالايا, ar), (556, ميزورام, ar), (557, ناجالاند, ar), (558, أوديشا, ar), (559, بودوتشيري  
  , ar), (560, البنجاب, ar), (561, راجستان, ar), (562, سيكيم, ar), (563, تاميل نادو, ar), (564, تيلانجانا, ar), (56  
  5, تريبورا, ar), (566, ولاية اوتار براديش, ar), (567, أوتارانتشال, ar), (568, البنغال الغربية, ar))

**Comment by vaishaliwebkul** [comment]
@ktrofimov 
Hope your issue is being resolved.

Feel free to reopen if get you stuck anywhere.

Thanks
