### ISSUE TITLE
Create product via code instead of UI

### ISSUE THREAD

**Issue by francesco-taioli** [bagisto/bagisto#3407]
Hi,
it's available some api or other method to create downloadable product directly **from code**?

I want to populate the db based on data in another site and, for now, the only option is to manually populate the table with the `DB::raw `facades,
 such as ` DB::insert("Insert into products ( sku, type) values ( '...', '...')");`

**Comment by fhferreira** [comment]
I think you should use the BULK Upload, it's very confuse, but it is an option. Ps.: It's lazy

**Comment by vaishaliwebkul** [comment]
@francesco-taioli 
Hope above solution works for you! 

Feel free to reopen in case of any doubt.
