### ISSUE TITLE
Wrong validation when remove variant(s) of configurable product

### ISSUE THREAD

**Issue by autn** [bagisto/bagisto#3409]
# Bug report

### Title
**The validation is wrong when remove variant(s) of a configurable product**

### Issue Description
**When create/edit configurable product, remove a variant (not last variant), then the validation is wrong**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: 1.1.2

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Go to admin site
    2. Go to Catalog > Product > Add product
    3. Add configurable product
    4. Remove a variant (not last variant)
    5. Save product (note that do not fill variants name)

### Expected result
**The right validation for each variant**

### Actual result

>    **The validation is wrong**

![Screenshot from 2020-07-03 11-31-29](https://user-images.githubusercontent.com/10827140/86432382-bf57e380-bd21-11ea-92c3-011cf7ce3727.png)

**Comment by nguyenmi** [comment]
I also encountered this error, please help me

**Comment by autn** [comment]
After a few days for detecting, I found the reason. You need to change the `key` of `variant-item` from `index` to something like `variant.id`.

In the file `packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php`, use:

```
<variant-item v-for='(variant, index) in variants' :variant="variant" :key="variant.id" :index="index" @onRemoveVariant="removeVariant($event)"></variant-item>
```
instead of:

```
<variant-item v-for='(variant, index) in variants' :variant="variant" :key="index" :index="index" @onRemoveVariant="removeVariant($event)"></variant-item>
```

See more: https://michaelnthiessen.com/force-re-render/

**Comment by rahulcs0082** [comment]
Hi @autn 

Thanks for the solution.

**Comment by autn** [comment]
@rahulcs0082 Glad to contribute to Bagisto. I see that we are using `:key="index"` in the many templates, so I think it will be better if the team check the whole project.

**Comment by vaishaliwebkul** [comment]
fixed
