### ISSUE TITLE
Getting exception while creating product

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3412]
# Bug report

### Title
Getting exception while creating  product

### Preconditions

    1. framework Version. Master
 

### Steps to reproduce

    1. step1 - try to create product
    

### Expected result
shoudd be able to create 

### Actual result
after entering sku, when clicking on save product getting exception 

![Screenshot (28)](https://user-images.githubusercontent.com/52821836/86436855-c3373600-bd20-11ea-8575-5ef95161ee45.png)

**Comment by jitendra-webkul** [comment]
Algolia credentials are not saved in config/scout.php file. Save null under driver if you are not using alogolia.
