### ISSUE TITLE
Getting Fatal error in taking pull from latest master.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3413]
# Bug report

### Title
Getting Fatal error in taking pull from latest master.

### Issue Description
Getting Fatal error in taking pull from latest master.
### Preconditions
    1. framework Version.-master

### Expected result
Code should get updated
### Actual result

![Workspace 1_150](https://user-images.githubusercontent.com/45203177/86438815-e49a2100-bd24-11ea-9507-46c9437ffda2.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
run **composer install**
