### ISSUE TITLE
Install failed with MariaDB

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3420]
# Bug report

### Issue Description
Bagisto fails to install on [Plesk](https://www.plesk.com/) that has switched from Mysql to MariaDB 10.2.

### Preconditions

    1. master branch.

### Steps to reproduce

    1. Setup a Plesk server / hosting subscription
    2. Deploy Bagisto
    3. run **artisan migrate** and see the result.

### Expected result
Installation should complete.

### Actual result

```
/opt/plesk/php/7.3/bin/php artisan migrate
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.16 seconds)
Migrating: 2014_10_12_100000_create_admin_password_resets_table
Migrated:  2014_10_12_100000_create_admin_password_resets_table (0.13 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.14 seconds)
Migrating: 2018_06_12_111907_create_admins_table
Migrated:  2018_06_12_111907_create_admins_table (0.14 seconds)
Migrating: 2018_06_13_055341_create_roles_table

In Connection.php line 671:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corr
  esponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `update
  d_at` timestamp null) default cha' at line 1 (SQL: create table `roles` (`id` int unsigned not null auto_increment prima
  ry key, `name` varchar(191) not null, `description` varchar(191) null, `permission_type` varchar(191) not null, `permiss
  ions` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb
  4_unicode_ci' engine = InnoDB ROW_FORMAT=DYNAMIC)


In PDOConnection.php line 63:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corr
  esponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `update
  d_at` timestamp null) default cha' at line 1


In PDOConnection.php line 61:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corr
  esponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `update
  d_at` timestamp null) default cha' at line 1
```

**Comment by vaishaliwebkul** [comment]
Hi @ghermans 
could you upgrade the MARIADB version higher than 10.2 then please check if you're still getting the same.
As we have checked the same in 10.3 and didn't get this.

Thanks

**Comment by ghermans** [comment]
@vaishaliwebkul i just noticed that MariaDB was already upgraded to 10.3.23, however the issue still occurs when doing a fresh Bagisto install.

**Comment by vaishaliwebkul** [comment]
@ghermans 
this issue an MariaDB issue which doesn't support JSON type for 10.1, make sure you have correctly upgraded it to the higher version.
Follow this link https://stackoverflow.com/questions/44027926/update-xampp-from-maria-db-10-1-to-10-2

Duplicate issues: 
https://github.com/bagisto/bagisto/issues/1551
https://github.com/bagisto/bagisto/issues/1099
https://github.com/bagisto/bagisto/issues/1159

**Comment by ghermans** [comment]
@vaishaliwebkul this has nothing todo with with the version as i said , MariaDB has been updated to the latest version.
Instead read this article on the MariaDB knowledgebase https://mariadb.com/kb/en/json-data-type/
