### ISSUE TITLE
getting exception when view order of deleted customer

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3422]
# Bug report

### Title
getting an exception when view order of deleted customer

### Issue Description
getting an exception when view order of deleted customer

### Preconditions

**Please provide as detailed information about your environment as possible.**

    1. framework Version-  master

### Steps to reproduce

    1. step1- place customer order
    2. step2- admin delete the customer
    3. step3- now admin check the order

### Expected result

- able to view all order when the customer is deleted

- admin shouldn't able to delete customer until their pending/processing order are exist

### Actual result

getting an exception when view order of a deleted customer

![Screenshot (13)](https://user-images.githubusercontent.com/43210406/86464877-1a073480-bd4e-11ea-828c-b7ab5b369bf7.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: Master

-------------------
Fixed

![Workspace 1_109](https://user-images.githubusercontent.com/45203177/89383646-788f4c00-d71a-11ea-857e-0c836e0e3711.png)
