### ISSUE TITLE
Cannot change account password

### ISSUE THREAD

**Issue by MattApril** [bagisto/bagisto#3423]
# Bug report

### Issue Description
Unable to change account password because "passwords do not match", even though they do.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: 1.1.2 and master

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

1. sign up for a new account
2. log in
3. edit profile
4. change password & submit

**Comment by bhanu-webkul** [comment]
fixed in default theme but still issue persists in velocity theme.

**Comment by vaishaliwebkul** [comment]
fixed
