### ISSUE TITLE
How to extend repository to add functions without edit core packages inside vendor folder

### ISSUE THREAD

**Issue by MostafaAttia** [bagisto/bagisto#3424]
Hi,

I'm trying to add my features to your framework, I can edit blade views without editing the core packages by copying the file to "app/resources". But don't know how to add new functions to a repository "packages/Webkul/Category/src/Repositories/CategoryRepository.php". Docs only mentioned "overriding core models".

Is there any way to extend the repository or controller outside the vendor folder?

**Comment by shivam-webkul** [comment]
Hello,

Please take a look of above link 
ref - [forum](https://forums.bagisto.com/topic/320/how-to-override-your-webkul-controllers-repository-and-classes)

**Comment by MostafaAttia** [comment]
@shivam-webkul  Thanks for your reply, I already saw this forum post before I write this issue. Also, I went through the docs but can't find what I'm looking for.

For example, if I want to add a 'top_categories' field to channel model, I can create a migration to add this field to the database, Also I can extend views easily in `resources` with the same file directory structure/name, **BUT**:

- [ ] How to extend `packages/Webkul/Core/src/Models/Channel.php`  to add `top_categories` to `$casts` and `$fillable` arrays:

```php
class Channel extends Model implements ChannelContract
{
    protected $casts = [
        'top_categories' => 'array'
    ];

    protected $fillable = ['code', 'name', 'description', 'theme', 'home_page_content', 'footer_content', 'hostname', 'default_locale_id', 'base_currency_id', 'root_category_id', 'top_categories'];
```

- [ ] How to Extend `packages/Webkul/Category/src/Repositories/CategoryRepository.php` to add a function to get top_categories of a channel:
```php
 public function getChannelTopCategories($ids)
    {
        $categories = $this->model->whereIn('id', $ids)->get();
        $trimmed = array();

        foreach ($categories as $key => $category) {
            if (($category->name != null || $category->name != "")
                && $category->id != core()->getCurrentChannel()->root_category_id) {
                $trimmed[$key] = [
                    'id' => $category->id,
                    'name' => $category->name,
                    'slug' => $category->slug,
                    'image' => [
                        'small' => url('cache/small/' . $category->image),
                        'medium' => url('cache/medium/' . $category->image),
                        'large' => url('cache/large/' . $category->image),
                        'original' => url('cache/original/' . $category->image)
                    ]

                ];
            }
        }

        return $trimmed;
    }
```

How to extend files in core packages without editing files directly.

I hope we can make this issue a reference for this kind of situation, because I saw many questions about it in blog/forums/github/facebook page, but can't find a clear answer.

Help Much Appreciated
Thanks

**Comment by rahulcs0082** [comment]
Hi @MostafaAttia 

You can use this one to override model in bagisto - https://devdocs.bagisto.com/override-core-model.html
After overriding the model, In your packages model, you can add **$casts** and **$fillable** properties as you did above.

**About Repository**
To add new method in the repository what we can do - We can simply create the same name route for the given one and now this route will call your packages controller (new controller in your package).
Now, in our package, we will create a new repository with same name in which we want to add method and our controller (controller in the package which we have created) will use this repository (For Dependency) instead of the old one and can add any number of method in this repository.

Thanks

**Comment by vaishaliwebkul** [comment]
@MostafaAttia 
Hope you're query is resolved, We are not getting any activity from the last 21 days over this, so we are closing this issue.

Feel free to reopen the issue.
Thanks

**Comment by nikhilbhatia22** [comment]
@rahulcs0082, With Laravel 7 and above, multiple routes with the same names are not supported, so how are we planning the L7 or above upgrade, if to override anything, we have to use the same route name pattern?

**Comment by devansh-webkul** [comment]
Hi @nikhilbhatia22,

I have checked the Laravel threads and discussion. For Laravel 7, there is a way to ignore the routes registry. If you need to overwrite package routes you need to explicitly define them in your own routes file and prevent the route registration of the package.

They have done in the Cashier package as well. It's up to the package implementation as well.

https://github.com/laravel/cashier-stripe/blob/11.x/src/Cashier.php#L133-L143

**Comment by nikhilbhatia22** [comment]
Okay, Thanks @devansh-webkul!

I believe we will be taking care of this, in the manner you suggested, when upgrading to upcoming Laravel versions.

**Comment by devansh-webkul** [comment]
> Okay, Thanks @devansh-webkul!
> 
> I believe we will be taking care of this, in the manner you suggested, when upgrading to upcoming Laravel versions.

Yes! Every new version comes with its own standards and recommendation. We will check accordingly.
