### ISSUE TITLE
Impossible to connect, please check your Algolia Application Id.

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3425]
# Bug report

### Issue Description
When creating a new product the error message **Impossible to connect, please check your Algolia Application Id.** returns

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master branch.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Create a new product
    2. Enter the Product Type, attribute family, SKU and press save product.
    3. See the result.

**Comment by vaishaliwebkul** [comment]
Hi @ghermans 
It's already reported here https://github.com/bagisto/bagisto/issues/3412, you may follow this.

Thanks

**Comment by vaishaliwebkul** [comment]
@ghermans 
This bug is resolved, Kindly check.
