### ISSUE TITLE
Getting exception putting perPage[eq]=0 in url wherever items per page has been used 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3426]
# Bug report

### Title
Getting exception putting perPage[eq]=0 in url wherever items per page has been used 

### Preconditions

    1. framework Version. Master
 
### Steps to reproduce

    1. step1-use items per page filter  
    2. step2-then put  perPage[eq]=0 in url 

### Actual result

![Screenshot 2020-07-06 10:36:06](https://user-images.githubusercontent.com/52821836/86558224-6c2a9e80-bf76-11ea-9f85-0898779b45df.png)

**Comment by bhanu-webkul** [comment]
Fixed in Master

**Comment by bhanu-webkul** [comment]
still getting same issue if we have already applied any filter for any column and then repeat the steps  ---
 step1-use items per page filter  
 step2-then put  perPage[eq]=0 in url 

![Screenshot 2020-07-13 17:06:34](https://user-images.githubusercontent.com/52821836/87300492-8e4e8e80-c52b-11ea-9c24-a7475b7c58e1.png)

**Comment by bhanu-webkul** [comment]
every where getting above error but while doing same for automatic generated coupons in cart rule then getting below screen- 

![Screenshot 2020-07-22 16:42:33](https://user-images.githubusercontent.com/52821836/88169981-80d78980-cc3a-11ea-8270-e8b9ef89d5c4.png)

**Comment by vaishaliwebkul** [comment]
fixed in both customer end as well as on admin end
