### ISSUE TITLE
'Cart Rule' with 'No Coupon' not getting applied

### ISSUE THREAD

**Issue by AshishGupta001** [bagisto/bagisto#3428]
# Bug report

### Title
Defined a 'Cart Rule' "100OFF" with 'No Coupon' required option. 

### Issue Description
Rule applicable for all the groups (including non logged in users). 
Created a new cart by adding products. 

Expected that the cart rule to be get applied automatically.

![image](https://user-images.githubusercontent.com/10075598/86564267-8dde5280-bf83-11ea-9946-3fa81e4368d3.png)

Also is there a way to trace whether any particular rule is getting applied or not. And if not why?

**Comment by vaishaliwebkul** [comment]
@AshishGupta001 
Please mention the bagisto version?

**Comment by AshishGupta001** [comment]
V1.1.2 (bagisto-bagisto-v1.1.2-0-gc88ca31)

**Comment by rahulcs0082** [comment]
Hi @AshishGupta001 

Can you attach dump of your database so that we can check because it is working properly at our end.

**Comment by SteffenMahler** [comment]
@AshishGupta001 
What condition have you configured for your cartRule?

**Comment by vaishaliwebkul** [comment]
@AshishGupta001 
We are not getting any activity by you since last 22 days, We assume your issue is resolved so closing this issue.

Feel free to reopen if still not resolved.
