### ISSUE TITLE
Notice: date_default_timezone_set(): Timezone ID 'Asia/AdenAsia/Kolkata' is invalid in D:\kuliah\PLI\bagisto-1.1.2\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\LoadConfiguration.php on line 49

### ISSUE THREAD

**Issue by mando0673** [bagisto/bagisto#3446]
Please help..

thankyou

**Comment by ghermans** [comment]
Can you please explain the steps you did to get this error so that we can verify it?

**Comment by mando0673** [comment]
> Can you please explain the steps you did to get this error so that we can verify it?

![image](https://user-images.githubusercontent.com/49507906/86902149-c4f56500-c137-11ea-8a0b-a8c923c6d01e.png)
when i chose asia timezone
and when i run "php artisan serve"

**Comment by mando0673** [comment]
![image](https://user-images.githubusercontent.com/49507906/86902421-20bfee00-c138-11ea-80bd-8b99ba4a7e2d.png)
like this

**Comment by vaishaliwebkul** [comment]
@mando0673 
this is resolved in master branch https://github.com/bagisto/bagisto/issues/3067, you can update your files mention in this PR https://github.com/bagisto/bagisto/commit/cce91676695bd52c3a2242388e090709ba8ae9b5

**Comment by mando0673** [comment]
> @mando0673
> this is resolved in master branch #3067, you can update your files mention in this PR [cce9167](https://github.com/bagisto/bagisto/commit/cce91676695bd52c3a2242388e090709ba8ae9b5)

oke thank you.
