### ISSUE TITLE
Change request regarding shipments

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3451]
# Change request report

### Request Description
When the admin clicks on the ship button the track&trace field should be optional since not all carriers provide a track&trace or when you pay more for that service.

If the customers wants to pickup the order from a store no track&trace or carrier is required, the validation for these fields should be removed.

**Comment by jitendra-webkul** [comment]
Hi @ghermans, 

Yes, you are right. It will be done today.

**Comment by ghermans** [comment]
@jitendra-webkul is there any update on this? because i didn't notice any commits regarding this issue.

**Comment by jitendra-webkul** [comment]
Hi @ghermans, done in this PR #3537

**Comment by vaishaliwebkul** [comment]
@ghermans 
Thanks.

Feel free to reopen if it's not done.

**Comment by ghermans** [comment]
@vaishaliwebkul i didn't had the time yet to try the commit that @jitendra-webkul pushed, however i did checked the code and it seems that this is resolved. if not i will reopen this one.
