### ISSUE TITLE
Invoice state is always set to paid

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3453]
# Bug report

### Issue Description
When the admin creates a invoice, the state is always set to paid.

**Comment by rahulcs0082** [comment]
Hi @ghermans 

We assume that Invoice will be created only if full payment is done that's why we set its status to paid but according to need it can be customized.

**Comment by ghermans** [comment]
@rahulcs0082 assumptions are never good :) The order can only be paid if a payment gateway is used.
At this moment when the customer places his order, he currently only receives a confirmation email of his order without any bank details etc, so without an invoice, the customer cannot pay for his order.

**Comment by ghermans** [comment]
Reopened this issue because of https://github.com/bagisto/bagisto/pull/3851
