### ISSUE TITLE
shipping rules at checkout 

### ISSUE THREAD

**Issue by CesarMdz** [bagisto/bagisto#3454]
Suggested improvements

When deactivating the free shipping option from the admin, on the checkout page, the shipping option must be checked even though there is only one option.

It should include the option of adding other shipping methods, not just one, for example DHL and FedEx and that the user chooses the package.

In the cart rules when defining that when the cart subtotal is May at X price the shipping is free, on the checkout page the shipping price appears, when it should appear at 0 or a legend that the shipping is free, in the summary of the purchase if you check it, as this confuses the customer.

<a href="https://ibb.co/TWmR1nN"><img src="https://i.ibb.co/fD4t9KT/1.png" alt="1" border="0"></a>

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 

The shipping method should be **selected** if there is **only one** shipping method.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/63f7548193ea2803a9461f33), for future reference.
