### ISSUE TITLE
 The image does not appear when changing the logo

### ISSUE THREAD

**Issue by mando0673** [bagisto/bagisto#3455]
![test](https://user-images.githubusercontent.com/49507906/87012641-be2c2800-c1f3-11ea-952c-b29b08c436bd.JPG)

help..
thank you

**Comment by vaishaliwebkul** [comment]
@mando0673 
you need to link storage folder

run this command from the root directory
**php artisan storage:link**

**Comment by mando0673** [comment]
> @mando0673
> you need to link storage folder
> 
> run this command from the root directory
> **php artisan storage:link**

ok work, thank you
