### ISSUE TITLE
not able to add (virtual,booking etc.) product to compare list by logged in user

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3458]
# Bug report

### Title
not able to add (virtual,booking etc.) product to compare list by logged in user

### Issue Description
not able to add (virtual,booking etc.) product to compare list by logged in user

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- logged in with customer
    2. step2- add to compare (virtual,downloadable,grouped,booking ) products

### Expected result

All type of product should be added to compare

### Actual result

>   only simple, or configurable added to compare, rest of them are not added currently.

* [points....]

**Comment by vaishaliwebkul** [comment]
working now.

**Comment by sandeep-elitedigital** [comment]
I am also unable to add product to compare after login
