### ISSUE TITLE
order summary should contain the applied coupon code details

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3459]
# Bug report

### Title
order summary should contain the applied coupon code details

### Issue Description
order summary should contain the applied coupon code details

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version- master

### Steps to reproduce

    1. step1- place an order by applying to coupon code
    2. step2- go to customer-> view order (their is no detail about applied coupon code)

### Expected result
applied coupon code should be display with discount amount in customer order summary

### Actual result
coupon code details is not display in customer order summary
![Screenshot(38)](https://user-images.githubusercontent.com/43210406/87040954-1a507580-c20f-11ea-9253-22ff112fc116.png)

![Screenshot(39)](https://user-images.githubusercontent.com/43210406/87040958-1c1a3900-c20f-11ea-9c72-3659dfff2680.png)

>    **Tell us what happens instead.**

* [points....]

**Comment by vaishaliwebkul** [comment]
need to be implemented for velocity theme also https://prnt.sc/thltpg

**Comment by devansh-webkul** [comment]
This issue is already fixed in the velocity theme as well.

**Comment by bhanu-webkul** [comment]
Fixed in master - https://prnt.sc/tqzx0m
