### ISSUE TITLE
Add address option should come below in velocity theme

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3460]
# Bug report

### Title
Add address option should come below

### Preconditions

    1. framework Version.  - Master
 
### Steps to reproduce

    1. step1 - visit customer profile and click on address 
    2. step2- make sure there s not saved address

### Expected result
https://prnt.sc/teqbjm

### Actual result
![Screenshot (29)](https://user-images.githubusercontent.com/52821836/87044338-03605200-c214-11ea-82cc-390311062fd8.png)

**Comment by rahulcs0082** [comment]
Hi @bhanu-webkul 

This is not a bug, velocity theme has different design and default have different.

**Comment by bhanu-webkul** [comment]
@rahulcs0082 

Then we need to change the text "below"

**Comment by bhanu-webkul** [comment]
Fixed in master
