### ISSUE TITLE
Pagination Lost the Style

### ISSUE THREAD

**Issue by fhferreira** [bagisto/bagisto#3468]
In the category it still ok:
![image](https://user-images.githubusercontent.com/140686/87234098-16099100-c3a4-11ea-9b63-1babc73b5f6d.png)
but on the search result page no:
![image](https://user-images.githubusercontent.com/140686/87234108-32a5c900-c3a4-11ea-9581-3806694b12e4.png)

Version: v1.1.2

**Comment by vaishaliwebkul** [comment]
Hi @fhferreira 
could you mention your System Environment to reproduce this issue?
As we have tested it on Ubuntu 16.04 LTS on Chrome Browser and didn't get this issue.

**Comment by fhferreira** [comment]
My env is a docker + ubuntu + php 7.4

**Comment by vaishaliwebkul** [comment]
Hi @fhferreira 
you can check out [Bagisto Demo](https://demo.bagisto.com ) built on docker.
We are not getting this issue https://prnt.sc/ti3khk

**Comment by fhferreira** [comment]
Hi @vaishaliwebkul
I will reinstall and try it again.

**Comment by vaishaliwebkul** [comment]
@fhferreira 
Hope your issue will get resolved on latest installation,We are closing this right now.

Feel free to reopen it anytime still getting the same.

Many Thanks!!
