### ISSUE TITLE
Cannot remove a layered navigation attribute from product

### ISSUE THREAD

**Issue by MattApril** [bagisto/bagisto#3469]
# Bug report

### Issue Description
If a product has been created with a multi-select attribute used in the layered navigation, I cannot de-select all of the options.

### Preconditions
    1. framework Version. 1.1.12

### Steps to reproduce
    1. Edit a product with layered navigation multi-select attribute.
    2. de-select all of the attribute options
    3. Save

### Expected result
The layered navigation attribute should be removed

### Actual result

Changes are not saved.

**Comment by vaishaliwebkul** [comment]
@MattApril 
this bug is now, kindly take a pull from the master branch.
