### ISSUE TITLE
Addresses being duplicated automatically in checkout page

### ISSUE THREAD

**Issue by MostafaAttia** [bagisto/bagisto#3470]
# Bug report

### Issue Description

When the user is logged in, If he wants to checkout and selects an address, this address being duplicated, now there are 3 instances off the same address. I looked to the database/addresses table and see that the same address is being created three times, differs only in the field address_type=customer/cart_billing/cart_shipping. But the same address is being shown three times in front-end. and if another checkout in-process and the same address selected, it is shown 5 times!!

### Preconditions

    1. v1.1.2

### Steps to reproduce

    1. Sign in to bagisto online demo
    2. Add products to cart
    3. Proceed to checkout
    4. Select the billing address
    5. Go to your profile->addresses
    6. You will find there are 3 addresses of the same details
    7.  If you selected the same address again in the checkout, it will be duplicated again, and so on

![bug2](https://user-images.githubusercontent.com/12887130/87257838-cbb90a80-c49e-11ea-9fd9-8933b4845567.png)
![bug1](https://user-images.githubusercontent.com/12887130/87257854-ea1f0600-c49e-11ea-9499-e1363366cb6a.png)
![bug0](https://user-images.githubusercontent.com/12887130/87257857-ed19f680-c49e-11ea-9688-4e5dc27ca59a.png)
![bug00](https://user-images.githubusercontent.com/12887130/87257858-ef7c5080-c49e-11ea-8c59-8f1f35c26647.png)

*   [Screenshots, logs or description]

**Comment by vaishaliwebkul** [comment]
@MostafaAttia 
Hope your issue get resolved. No response from last 11 days, so we are closing this .

Feel free to reopen it any time.
