### ISSUE TITLE
layout issue in order and downloadable grid at customer end in mobile view 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3472]
# Bug report

### Title
layout issue in order and downloadable grid at customer end in mobile view 

### Preconditions

    1. framework Version. Master
### Steps to reproduce

  1. step1 - check/downloadable grid in mobile view 
  

### Actual result
![Screenshot (30)](https://user-images.githubusercontent.com/52821836/87300796-28aed200-c52c-11ea-8d86-7159b43d8f66.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: master

------------------------------------

Fixed

![Screenshot (60)](https://user-images.githubusercontent.com/45203177/89096633-c98b0180-d3f5-11ea-8e75-a0be6ec87b22.png)
![Screenshot (59)](https://user-images.githubusercontent.com/45203177/89096636-cabc2e80-d3f5-11ea-9be4-638597f289d4.png)
