### ISSUE TITLE
Add image column in configurable products for variants

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3477]
For variants products, there should be an image column must be available in parent/configurable product

![Screenshot (18)](https://user-images.githubusercontent.com/43210406/87400933-176ecf80-c5d7-11ea-9f29-fc7a1e245875.png)

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by AliRazaLilani** [comment]
Same Issue and it is **mandatory**

**Comment by musawirjon** [comment]
Hi @vaishaliwebkul on choosing variations images need to be change according to chosen variation. Is their any way to do so. Currently I have tried to do it but I can find any clue to do that.

**Comment by vaishaliwebkul** [comment]
@musawirjon 
please specify your current bagisto version?

**Comment by musawirjon** [comment]
it's latest one. v1.2.0

**Comment by musawirjon** [comment]
Please see the screenshot for what functionality I need in here.
https://prnt.sc/ya5fp1

**Comment by vaishaliwebkul** [comment]
@musawirjon 
Thanks for reporting this, could you please raise a new issue which you're getting right now, as this issue in which you have commented is different and marked as enhancement.

**Comment by musawirjon** [comment]
Those are products I imported from aliexpress. and also for variation url key and images aren't importing. If I want to change something in variation then I have to manually do that with description, url_slug, images, and any other required by editing variation. 
But I have tons of products and most product has more then 10 variants. So would be much ease if bagisto aliexpress dropship extension could import those things as well.

**Comment by musawirjon** [comment]
> @musawirjon
> Thanks for reporting this, could you please raise a new issue which you're getting right now, as this issue in which you have commented is different and marked as enhancement.

Yes please add a ticket for it. As this is what I am trying to do it by my-self from almost 6 days.

**Comment by vaishaliwebkul** [comment]
@musawirjon 
please get an update with this issue link https://github.com/bagisto/bagisto/issues/4558 in which I have mentioned the issue you're getting.
