### ISSUE TITLE
 slider image does not appear 

### ISSUE THREAD

**Issue by mando0673** [bagisto/bagisto#3479]
![image](https://user-images.githubusercontent.com/49507906/87408111-3710f280-c5ed-11ea-9e49-1ddfcdb4e9f1.png)
Please help..

**Comment by vaishaliwebkul** [comment]
@mando0673 
solution link https://forums.bagisto.com/topic/1277/on-live-server-my-slider-is-not-working/9

**Comment by mando0673** [comment]
work, thank you
