### ISSUE TITLE
Tax is still fully charged when a cart-discount-rule is applied

### ISSUE THREAD

**Issue by jtepe-sedna** [bagisto/bagisto#3480]
# Bug report

### Title
Tax is still fully charged when a cart-discount-rule is applied

### Issue Description
When you add a cart-rule to give 10% discount to users in a specific user-group the tax is still being calculated over the full cart amount instead of the cart amount - discount

### Preconditions

    1. Bagisto v1.1.1

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Add a user group called wholesale
    2. Add yourself to the wholesale user-group
    3. Add a cart-rule to give users in the wholesale user-group a discount of 10% (without using a coupon code)
    4. Log in as yourself
    5. Add a product to the cart
    6. Fill in your address in the checkout until the tax is being calculated

### Expected result
GIVEN a user that is in the user-group wholesale
AND the tax rate for this user is 21%
AND his cart contains products worth €10,- (excluding TAX)
WHEN this user proceed to checkout
THEN the calculation should be as followed:

cart total = €10,00
discount = 10%
tax = 21%

(cart total - discount) + tax

### Actual result

cart total = €10,00
discount = 10%
tax = 21%

cart total + tax

**Comment by SteffenMahler** [comment]
The question is whether it is a bug or a feature.
When we saw this behavior, we thought it was supposed to behave this way. But our expectations were different. So we changed that logic in our Bagisto installation.

**Comment by ghermans** [comment]
Hi first of all sorry for the very late response on this issue report,
The tax amount is still charged because discounts are offered directly by the merchant, which reduces the amount of the sale price and not the tax amount.
