### ISSUE TITLE
can't edit color attributes

### ISSUE THREAD

**Issue by mando0673** [bagisto/bagisto#3481]
![image](https://user-images.githubusercontent.com/49507906/87419861-6da33900-c5fe-11ea-8969-8e4391554b77.png)
Help..
thank you

**Comment by vaishaliwebkul** [comment]
@mando0673 
kindly describe this issue in detail?

**Comment by mando0673** [comment]
> @mando0673
> kindly describe this issue in detail?

When I want to add another color to the color attribute section, and when I want to save it, an error message appears 404 page not found

**Comment by vaishaliwebkul** [comment]
Hi @mando0673 
Kindly check the same in [bagisto demo](https://demo.bagisto.com) , We are not getting this issue.

**Comment by vaishaliwebkul** [comment]
@mando0673 
response is due from the last 8 days so we are closing issue, Hope your issue is resolved now.

Feel free to reopen anytime!
