### ISSUE TITLE
layout issue on category page for filterable attributes

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3485]
# Bug report

### Title
layout issue on category page for filter attributes

### Issue Description
layout issue on the category page for filter attributes

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add custom category with more options
    2. step2- go to the category page and open all filterable attributes

### Actual result

>  
![Screenshot (20)](https://user-images.githubusercontent.com/43210406/87432926-510aff00-c606-11ea-874f-80be9073ca5e.png)

**Comment by devansh-webkul** [comment]
May I know on which browser this is happening because I have tested this in Mozilla and Chrome and in both browser, the layout is looking fine.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
could you please check by minimizing the window resolution size 80% or less.
