### ISSUE TITLE
Compare feature shows wrong attribute value

### ISSUE THREAD

**Issue by MostafaAttia** [bagisto/bagisto#3486]
# Bug report

### Issue Title
**The compare feature doesn't show the label for an attribute (specifically the drop-down attributes)**

### Issue Description
The compare feature doesn't show the label for an attribute (specifically the drop-down attributes), it shows values as numbers instead, for example for the "Brand" attribute, it shows numbers, not strings as it should. I looked to the file `resources/themes/velocity/views/guest/compare/compare-products.blade.php`  I was able to add "_label" for some attributes but not all, as these attributes exist as numbers in the source `product` array. screenshots provided below

### Preconditions

    1. v1.1.2.

 screenshot from my localhost
![compare bug 01](https://user-images.githubusercontent.com/12887130/87494406-36a94380-c64f-11ea-804e-6e89aa08cfa1.png)

 screenshot  from demo.bagisto.com:
![compare bug 00](https://user-images.githubusercontent.com/12887130/87494364-17aab180-c64f-11ea-9362-3643de4111fb.png)

Actual product array, note the brand value is a number
![compare bug 02](https://user-images.githubusercontent.com/12887130/87494432-46c12300-c64f-11ea-97e1-8b4d216f037e.png)

**Comment by vaishaliwebkul** [comment]
@MostafaAttia 
Thanks for notifying this bug

**Comment by bhanu-webkul** [comment]
Same issue with checkbox type attributes

**Comment by bhanu-webkul** [comment]
Fixed in master
