### ISSUE TITLE
Velocity RTL product image zoom floats right - not showing

### ISSUE THREAD

**Issue by MostafaAttia** [bagisto/bagisto#3487]
# Bug report

### Title
Velocity RTL product image zoom floats right - not showing

### Issue Description
when hovering over product image in the product details page, the zoom container floats right in RTL layout

### Preconditions

    1. framework Version: v1.1.2.
![velocity bug 00](https://user-images.githubusercontent.com/12887130/87504658-66fcdc00-c667-11ea-84ce-feccc6f5e444.png)

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
when we hover a product image in ar then zoom image is should not show with spaces from the actual image https://prnt.sc/tp94rg

**Comment by devansh-webkul** [comment]
Fixed this issue https://github.com/bagisto/bagisto/pull/3586

**Comment by vaishaliwebkul** [comment]
need to fix for multiple images as well https://prnt.sc/vhh3sb
