### ISSUE TITLE
Compare feature is not working properly for newly created select and multiselect type attribute 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3493]
# Bug report

### Title
Compare feature is not working properly for newly created select type attribute 
### Issue Description
in place of selected option random numbers are coming in compare list

### Preconditions
    1. framework Version. Master

### Steps to reproduce
    1. step1: create a select type attribute select any swatch type and select yes in Attribute is comparable
    2. step2: add that attribute to attribute family
    3. step3: then create a product  and visit front end and add that product to compare  list

### Expected result: 
selected option should display
### Actual result
![Screenshot (32)](https://user-images.githubusercontent.com/52821836/87540518-773fa600-c6bd-11ea-8eed-1d6e225c331b.png)
![Screenshot (31)](https://user-images.githubusercontent.com/52821836/87540537-7e66b400-c6bd-11ea-89eb-e84abd1a503e.png)

**Comment by vaishaliwebkul** [comment]
duplicate issue https://github.com/bagisto/bagisto/issues/3486, so closing this
