### ISSUE TITLE
compare feature is not working properly if admin creates a image type attribute and give attribute code and name "image"

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3494]
# Bug report

### Title
compare feature is not working properly if admin creates a image type attribute and give attribute code and name "image"

### Issue Description
if image type attribute has created by admin named as image then in compare list, in place of that image which is uploaded for image attribute,its showing product image 

### Preconditions

    1. framework Version. Master

### Steps to reproduce
    1. step1: create a image type attribute make sure name and code should be image 
    2. step2: then add that attribute to family and create product upload any image for that attribute as well as upload product image 

### Expected result
actual image should be displayed for that attribute in compare list 
### Actual result

https://prnt.sc/ti8y3p
https://prnt.sc/ti8yyt

**Comment by vaishaliwebkul** [comment]
Duplicate issue https://github.com/bagisto/bagisto/issues/3495

**Comment by bhanu-webkul** [comment]
@vaishaliwebkul 

Both are different issues

**Comment by vaishaliwebkul** [comment]
@vishal-webkul 
the bug is not resolved yet, in both case if image attribute code is 'image' type as well as if simple image type attribute is also not visible, it's showing as a link https://prnt.sc/tugok3

**Comment by vaishaliwebkul** [comment]
@rahulcs0082 
please check the size of the images in compare list
![Screenshot_12](https://user-images.githubusercontent.com/43210406/89788429-c520c000-db3c-11ea-9792-652e8e858d9b.png)

**Comment by vaishaliwebkul** [comment]
fixed in both case when attribute have image code attribute as well as random code https://prnt.sc/txa0b8
