### ISSUE TITLE
showing values in compare list of those attribute which has been removed from attribute family

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3496]
# Bug report

### Title
showing values of those attribute which has been removed from attribute family in compare list

### Preconditions

    1. framework Version. Master

### Steps to reproduce

    1. step1: remove existing comparable attributes from attribute family  
    2. step2 :then  check compare list

### Expected result
removed attributes values should not be display 
### Actual result
https://prnt.sc/ti9zxd
https://prnt.sc/ti9z5j

**Comment by vaishaliwebkul** [comment]
fixed in both theme.
