### ISSUE TITLE
No.of items in compare should be displayed with compare tab in default theme

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3498]
# Bug report

### Title
No.of items in compare should be displayed in default theme

### Preconditions

    1. framework Version. Master
   
### Steps to reproduce
    1. step1 - add products in compare list

### Expected result

https://prnt.sc/tioqus

### Actual result
![Screenshot (35)](https://user-images.githubusercontent.com/52821836/87628118-e4028100-c74d-11ea-89f9-27bafc1fc95a.png)

**Comment by vaishaliwebkul** [comment]
@bhanu-webkul 
Implemented compare number indicator option in default theme https://prnt.sc/tx9v9i
