### ISSUE TITLE
unable to download files while comparing products

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3501]
# Bug report

### Title
unable to download files while comparing products

### Issue Description
If admin has used any file type attribute in product then while comparing that product at front end customer should be able to download that uploaded file

### Preconditions

    1. framework Version. Master

### Steps to reproduce

    1. step1 - create a file type comparable attribute and add that in family 
    2. step2- then create a product and upload any file for that attribute and visit front end add that product into compare list

### Expected result
customer should be able to download the product 
### Actual result
unable to download

**Comment by vaishaliwebkul** [comment]
fixed
