### ISSUE TITLE
No message on removing products or deleting all from compare list in default theme

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3505]
# Bug report

### Title
No message on removing products or deleting all from compare list

### Preconditions

    1. framework Version. Master
### Steps to reproduce

    1. step1- remove products from compare list
### Expected result
should get mesege 
### Actual result
no message

**Comment by bhanu-webkul** [comment]
After removing all  products directly by clicking on "delete all" button message should be like this - https://prnt.sc/tjjdma

**Comment by shivam-webkul** [comment]
https://prnt.sc/tl936k

**Comment by bhanu-webkul** [comment]
@shivam-webkul 

Now getting same message on removing only single item from compare list - https://prnt.sc/tntzz0

**Comment by vaishaliwebkul** [comment]
alert is not displaying when removing the compare product as guest user

**Comment by bhanu-webkul** [comment]
Fixed in master
