### ISSUE TITLE
layout issue in order information in default theme at customer end 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3521]
# Bug report

### Title
layout issue in order information in default theme at customer end 

### Preconditions

    1. framework Version. Master
    2. Commit: https://github.com/bagisto/bagisto/commit/c6e7ef3e5f64d307a1eff33ca36b646f194ed966

### Steps to reproduce
    1. step1- place order and check order information in default locale

### Expected result
![Screenshot 2020-07-17 17:13:18](https://user-images.githubusercontent.com/52821836/87782834-e39ede80-c850-11ea-887c-721181c6c7a0.png)

### Actual result
![Screenshot 2020-07-17 17:13:35](https://user-images.githubusercontent.com/52821836/87782851-ebf71980-c850-11ea-8d60-2166111b8893.png)

**Comment by vaishaliwebkul** [comment]
@akhtarkhan1 
Also fix the layout of cancel button icon in Arabic RTL for default theme https://prnt.sc/tn323x

**Comment by bhanu-webkul** [comment]
Not fixed in master
