### ISSUE TITLE
Admin is not getting mail when customer cancels order 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3522]
# Bug report

### Title
Admin is not getting mail when customer cancels order 
### Preconditions

    1. framework Version. Master
### Steps to reproduce
    1. step1: Place order and cancel that by customer

### Expected result
admin should get mail when customer cancels order 
### Actual result
Not getting mail

**Comment by biru2042** [comment]
Someone help me to login via social media in bagisto eccomerce. I faced problem this 
Illuminate \ Contracts \ Container \ BindingResolutionException
Target class [encrypter] does not exist. When i register SocialiteProvider in config/app.php
thanks in advance

**Comment by vaishaliwebkul** [comment]
@biru2042 
your application key is missing .env, to resolve this. Kindly follow this link https://forums.bagisto.com/topic/1544/illuminate-contracts-container-bindingresolutionexception-target-class-encrypter-does-not-exist-previous-exceptions-class-encrypter-does-not-exist-1/4

**Comment by biru2042** [comment]
@vaishaliwebkul  i have app key 
![ss](https://user-images.githubusercontent.com/13455393/87855824-897a4800-c93a-11ea-8840-5786aca9145e.PNG)

**Comment by vaishaliwebkul** [comment]
@biru2042 
>Remove the SocialiteProvider in config/app.php
>run composer dump-autoload
>now again register the SocialiteProvider & execute composer dump-autoload

have you created your own social login package?

**Comment by biru2042** [comment]
Now i am doing as you said

**Comment by biru2042** [comment]
please help me in administration section product listing page 
![ss1](https://user-images.githubusercontent.com/13455393/87856430-dcee9500-c93e-11ea-8a0c-c79a67402377.PNG)

![ss2](https://user-images.githubusercontent.com/13455393/87856439-ea0b8400-c93e-11ea-85db-a7bcfb5dcd84.PNG)

i want model for editing price in same page like first picture

**Comment by vaishaliwebkul** [comment]
@biru2042 
Kindly raise a new bug/topic for this query, it will be helpful for all to discuss over an separate issue regarding this query.

**Comment by bhanu-webkul** [comment]
@shivam-webkul 

Its not working properly, admin and customer both are getting same mail in both case either admin cancels order or customer.

**Comment by vaishaliwebkul** [comment]
fixed
