### ISSUE TITLE
auth()->guard('admin')->user() return Null

### ISSUE THREAD

**Issue by ahmad753** [bagisto/bagisto#3523]
I extended the product model and registered it by following the steps in the documentation. And I'm trying to add a global scope in the new product model booted method and trying to check the user role like this

if(auth()->guard('admin')->user()->role->name != 'Administrator'){
            static::addGlobalScope('********', function (Builder $builder) {
                ...................
            });
}

and auth()->guard('admin')->user() keeps return null.

**Comment by rahulcs0082** [comment]
Hi @ahmad753 

Can you tell me about your bagisto version so that we can check as we are not getting this one?

**Comment by ahmad753** [comment]
Hi @rahulcs0082 

I'm using the master branch.
