### ISSUE TITLE
Error when creating an invoice

### ISSUE THREAD

**Issue by wasllot** [bagisto/bagisto#3524]
# Bug report

### Exception when creating an invoice 

Method: store/invoiceController. 

### Description

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`flaya_import`.`bagistoinvoices`, CONSTRAINT `invoices_order_address_id_foreign` FOREIGN KEY (`order_address_id`) REFERENCES `bagistoorder_address` (`id`) ON DELETE SET NULL) (SQL: insert into `bagistoinvoices` (`order_id`, `total_qty`, `state`, `base_currency_code`, `channel_currency_code`, `order_currency_code`, `order_address_id`, `updated_at`, `created_at`) values (3, 1, paid, USD, USD, USD, 13, 2020-07-19 00:28:12, 2020-07-19 00:28:12))

    1. Bagisto V1.1.2
    2. PHP V7.3,18
    3, Composer V1.10.9

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Go to orders details
    2. Invoice
    3. Save Invoice

### Expected result

The invoice cannot be saved because of  exception. 

Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`flaya_import`.`bagistoinvoices`, CONSTRAINT `invoices_order_address_id_foreign` FOREIGN KEY (`order_address_id`) REFERENCES `bagistoorder_address` (`id`) ON DELETE SET NULL) (SQL: insert into `bagistoinvoices` (`order_id`, `total_qty`, `state`, `base_currency_code`, `channel_currency_code`, `order_currency_code`, `order_address_id`, `updated_at`, `created_at`) values (3, 1, paid, USD, USD, USD, 13, 2020-07-19 00:40:29, 2020-07-19 00:40:29)) in file C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 669

Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`flaya_import`.`bagistoinvoices`, CONSTRAINT `invoices_order_address_id_foreign` FOREIGN KEY (`order_address_id`) REFERENCES `bagistoorder_address` (`id`) ON DELETE SET NULL) in file C:\Users\user\Desktop\bagisto-flaya\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php on line 119

Caused by
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`flaya_import`.`bagistoinvoices`, CONSTRAINT `invoices_order_address_id_foreign` FOREIGN KEY (`order_address_id`) REFERENCES `bagistoorder_address` (`id`) ON DELETE SET NULL) in file C:\Users\user\Desktop\bagisto-flaya\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php on line 117
Stack trace:
  1. Illuminate\Database\QueryException-&gt;() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Connection.php:669
  2. Doctrine\DBAL\Driver\PDOException-&gt;() C:\Users\user\Desktop\bagisto-flaya\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:119
  3. PDOException-&gt;() C:\Users\user\Desktop\bagisto-flaya\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:117
  4. PDOStatement-&gt;execute() C:\Users\user\Desktop\bagisto-flaya\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:117
  5. Doctrine\DBAL\Driver\PDOStatement-&gt;execute() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Connection.php:463
  6. Illuminate\Database\Connection-&gt;Illuminate\Database\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Connection.php:662
  7. Illuminate\Database\Connection-&gt;runQueryCallback() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Connection.php:629
  8. Illuminate\Database\Connection-&gt;run() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Connection.php:464
  9. Illuminate\Database\Connection-&gt;statement() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Connection.php:416
 10. Illuminate\Database\Connection-&gt;insert() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php:32
 11. Illuminate\Database\Query\Processors\Processor-&gt;processInsertGetId() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:2695
 12. Illuminate\Database\Query\Builder-&gt;insertGetId() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:1366
 13. Illuminate\Database\Eloquent\Builder-&gt;__call() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:839
 14. Illuminate\Database\Eloquent\Model-&gt;insertAndSetId() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:804
 15. Illuminate\Database\Eloquent\Model-&gt;performInsert() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:667
 16. Illuminate\Database\Eloquent\Model-&gt;save() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:765
 17. Illuminate\Database\Eloquent\Builder-&gt;Illuminate\Database\Eloquent\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Support\helpers.php:422
 18. tap() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:766
 19. Illuminate\Database\Eloquent\Builder-&gt;create() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:23
 20. Illuminate\Database\Eloquent\Model-&gt;forwardCallTo() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1620
 21. Illuminate\Database\Eloquent\Model-&gt;__call() C:\Users\user\Desktop\bagisto-flaya\packages\Webkul\Sales\src\Repositories\InvoiceRepository.php:104
 22. Webkul\Sales\Repositories\InvoiceRepository-&gt;create() C:\Users\user\Desktop\bagisto-flaya\packages\Webkul\Admin\src\Http\Controllers\Sales\InvoiceController.php:114
 23. Webkul\Admin\Http\Controllers\Sales\InvoiceController-&gt;store() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
 24. call_user_func_array() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
 25. Illuminate\Routing\Controller-&gt;callAction() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
 26. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\Route.php:219
 27. Illuminate\Routing\Route-&gt;runController() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\Route.php:176
 28. Illuminate\Routing\Route-&gt;run() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\Router.php:681
 29. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:130
 30. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\packages\Webkul\User\src\Http\Middleware\Bouncer.php:27
 31. Webkul\User\Http\Middleware\Bouncer-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
 32. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
 33. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
 34. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:76
 35. Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
 36. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php:39
 37. Illuminate\Session\Middleware\AuthenticateSession-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
 38. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
 39. Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
 40. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:105
 41. Illuminate\Pipeline\Pipeline-&gt;then() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\Router.php:683
 42. Illuminate\Routing\Router-&gt;runRouteWithinStack() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\Router.php:658
 43. Illuminate\Routing\Router-&gt;runRoute() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\Router.php:624
 44. Illuminate\Routing\Router-&gt;dispatchToRoute() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Routing\Router.php:613
 45. Illuminate\Routing\Router-&gt;dispatch() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:170
 46. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:130
 47. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php:65
 48. Barryvdh\Debugbar\Middleware\InjectDebugbar-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
 49. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:56
 50. Illuminate\Session\Middleware\StartSession-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
 51. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
 52. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
 53. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:66
 54. Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
 55. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:63
 56. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:171
 57. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:105
 58. Illuminate\Pipeline\Pipeline-&gt;then() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:145
 59. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() C:\Users\user\Desktop\bagisto-flaya\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:110
 60. Illuminate\Foundation\Http\Kernel-&gt;handle() C:\Users\user\Desktop\bagisto-flaya\public\index.php:74
 61. require_once() C:\Users\user\Desktop\bagisto-flaya\server.php:21

**Comment by devansh-webkul** [comment]
As we are not getting this issue in the master branch, kindly take a pull from the master branch.

**Comment by vaishaliwebkul** [comment]
@wasllot 
Hope you're getting this fixed.

Feel free to reopen in case of any doubt.
