### ISSUE TITLE
Error when changing currency in front end except in the home page.

### ISSUE THREAD

**Issue by GiannosSazos** [bagisto/bagisto#3527]
So when i change currency in the home page of the store everything is ok, but when i am at the product page and trying to change currency it throws this.

![image](https://user-images.githubusercontent.com/32360330/87924608-c7d14d80-ca87-11ea-80f4-c2a42ecb0721.png)

Maybe i did not configured something correctly in the admin dashboard?!

Thanks!

**Comment by vaishaliwebkul** [comment]
@GiannosSazos 
This bug is exist in bagisto 1.1.2, it's resolved in the [master branch](https://github.com/bagisto/bagisto/pull/3206) and will soon be released in new version.
Issue link https://github.com/bagisto/bagisto/issues/3204.

**Comment by vaishaliwebkul** [comment]
@GiannosSazos 
duplicate issue& it's resolved so closing this.
