### ISSUE TITLE
layout issue at shop end on opening any product

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3528]
# Bug report

### Title
layout issue at shop end on opening any product

### Preconditions

    1. framework Version. Master
    2. Commit id. https://github.com/bagisto/bagisto/commit/a0407595824bb4553f3acebb4363482f7eac0d53

https://prnt.sc/tl5czi

**Comment by shivam-webkul** [comment]
it works fine.

please check

![download](https://user-images.githubusercontent.com/50355852/87941138-48a83d80-cab8-11ea-9385-d4c2f2873473.png)

**Comment by bhanu-webkul** [comment]
don't know why it was not working, but now after running npm commands its working fine
