### ISSUE TITLE
Products Per Page configuration is not working properly 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3533]
# Bug report

### Title
Products Per Page configuration is not working properly 
### Issue Description
on giving comma separated values its showing products only according to first value at every page 

### Preconditions
    1. framework Version. Master

### Steps to reproduce
    1. step1 at admin end set products per page like:2,1,4
    2. steps: check on front end category page

### Expected result:
should work according to given values 

### Actual result
i have given 2,1,4 but at 2nd page its showing 2 product
![Screenshot 2020-07-20 19:22:36](https://user-images.githubusercontent.com/52821836/87946776-17337000-cac0-11ea-9d65-f56f6fb26278.png)

**Comment by vaishaliwebkul** [comment]
@bhanu-webkul 
comma-separated value will be populated in the dropdown, as shown here https://prnt.sc/tlvh3p , If you will select 2 as an option then per page 2 product will be visible.

So the functionality is working fine.

**Comment by bhanu-webkul** [comment]
then what is the meaning to mention  comma separated there

**Comment by bhanu-webkul** [comment]
what if i give 0 in comma separated value

**Comment by vaishaliwebkul** [comment]
@bhanu-webkul 
When set 0 , then no value will be visible in front.

Still thanks for mentioning this, we are getting the issue when set 0 in configuration

![Screenshot (35)](https://user-images.githubusercontent.com/43210406/88069183-c3dc2300-cb8e-11ea-945a-b900af744637.png)

**Comment by bhanu-webkul** [comment]
fixed in master
