### ISSUE TITLE
Sort By configuration from admin end is not working properly 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3535]
# Bug report

### Title
Sort By configuration from admin end is not working properly 

### Preconditions
    1. framework Version. Master

### Steps to reproduce
    1. step1: select expensive first/cheapest first from admin
    2. step2: check on category page at front end(make sure all type of products are available)

### Expected result:
![Screenshot 2020-07-20 19:52:44](https://user-images.githubusercontent.com/52821836/87949061-28ca4700-cac3-11ea-8bef-997e406e8916.png)

### Actual result
![Screenshot 2020-07-20 19:53:06](https://user-images.githubusercontent.com/52821836/87949094-37186300-cac3-11ea-9e00-49a830e7db0a.png)

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
kindly fix this issue https://github.com/bagisto/bagisto/issues/3562

**Comment by bhanu-webkul** [comment]
fixed in master
