### ISSUE TITLE
How to integrate Virtual Product, Bundle Product, Grouped Product, Downloadable Product etc. functionality in old bagisto version.

### ISSUE THREAD

**Issue by testforpostman7** [bagisto/bagisto#3541]
Hello,
   
    I have to integrate Virtual Product, Bundle Product, Grouped Product, Downloadable Product, etc. functionality in my old bagisto version without upgrading bagisto version because there is so much customization done in this version. So anyone guides me regarding this customization.

Thanks.

**Comment by vaishaliwebkul** [comment]
@testforpostman7 
same query https://github.com/bagisto/bagisto/issues/3346 , so closing this.
