### ISSUE TITLE
how to remove root category When insert or edit product

### ISSUE THREAD

**Issue by biru2042** [bagisto/bagisto#3544]
![gg](https://user-images.githubusercontent.com/13455393/88044833-f1fd3b00-cb6d-11ea-978e-a1695c8c93dc.PNG)
I tried in many way to remove or hide root category when insert or edit product, but not enabled to do that. I want to display only root's children only not root, Please help someone who did before

**Comment by shivam-webkul** [comment]
Hello,
But if you remove root category then, 
How can you add category beginning of category creation.

**Comment by biru2042** [comment]
@shaiv-webkul 
if not possible to remove, can we hide the root category.
is this possible, Please help me

**Comment by vaishaliwebkul** [comment]
@biru2042 
root category will not visible on front end, only the child will be shown on the front.
so there is no need to hide or remove root category.

**Comment by vaishaliwebkul** [comment]
@biru2042 
Hope this query is resolved.

Feel free to reopen the issue in case of any further doubt..
