### ISSUE TITLE
checkout country null issue

### ISSUE THREAD

**Issue by arooba499** [bagisto/bagisto#3547]
Hi! I was testing my project and i noticed one thing that country name on billing and shipping address on checkout is null when i check user address section and addresses table countries present there but on checkout it show nothing i also verified by printing addresses array following are ss of issue.
![30d8b088-069d-4c18-8b0c-80b8db7f58c7-image](https://user-images.githubusercontent.com/55804838/88047783-95991c00-cb6b-11ea-95b4-f74c466d9093.png)
<img width="676" alt="adddddd" src="https://user-images.githubusercontent.com/55804838/88047790-99c53980-cb6b-11ea-97dd-f1308332445a.png">

**Comment by bhanu-webkul** [comment]
As well as city is missing on final checkout page -https://prnt.sc/tn12ne

**Comment by vaishaliwebkul** [comment]
Hi @arooba499 
the country is added on checkout kindly check as shown below
![Screenshot (46)](https://user-images.githubusercontent.com/43210406/88643027-cda9dd00-d0de-11ea-8415-7ac6955aa334.png)
