### ISSUE TITLE
Cart Rule Issue

### ISSUE THREAD

**Issue by arooba499** [bagisto/bagisto#3554]
I created a cart rule to enable free shipping if cart price > 100 but when i enable this rule this is applied on all items even cart price is less than 100

**Comment by arooba499** [comment]
Hi @devansh-webkul  i am getting this error when i enable this rule for guest users
<img width="947" alt="guest" src="https://user-images.githubusercontent.com/55804838/88454054-09963580-ce86-11ea-89e8-8bf223063cdd.png">

**Comment by arooba499** [comment]
Even i am getting this error on login after updating CartRule.php

**Comment by vaishaliwebkul** [comment]
@arooba499 
can you check again by run **composer dump-autoload;php artisan config:cache** once updating the cart.php as mention in PR.

**Comment by arooba499** [comment]
@vaishaliwebkul  i removed cache now working fine but still in case of cart item attribute[cart price ] it is not working as expected  and simply ignore the condition and set the shipping price to zero but  i tested it for cart attribute[subtotal] in this condition it is working fine.

**Comment by vaishaliwebkul** [comment]
@arooba499 
can you display the condition in screenshot which is working fine as expect or which is not working??

**Comment by arooba499** [comment]
I am talking about this condition when i set condition for cart price it is not working
<img width="660" alt="cart issue" src="https://user-images.githubusercontent.com/55804838/88535206-fcfb1400-d022-11ea-97fb-88c080c04d09.png">
as cart price must be greater than 200 for this condition and  in this case cart price is 300 but rule is not working,,,correct me if i am wrong 
<img width="252" alt="cart issue price" src="https://user-images.githubusercontent.com/55804838/88535592-a4784680-d023-11ea-97f0-08b397a8e998.png">
<img width="914" alt="checkout cart rule" src="https://user-images.githubusercontent.com/55804838/88535602-ac37eb00-d023-11ea-9bed-21e70cf80510.png">

**Comment by vaishaliwebkul** [comment]
@arooba499 
I also tested this with the same condition in the master by updating code with this [PR](https://github.com/bagisto/bagisto/pull/3573)
seems to be working fine, kindly check all the condition as shown below

![Screenshot (47)](https://user-images.githubusercontent.com/43210406/88653010-25e5dc80-d0e9-11ea-9f54-6b5531e93927.png)

![Screenshot (48)](https://user-images.githubusercontent.com/43210406/88653017-27afa000-d0e9-11ea-9c0a-7f9f83c50169.png)

![Screenshot (49)](https://user-images.githubusercontent.com/43210406/88653022-27afa000-d0e9-11ea-8397-e34099e770c7.png)
