### ISSUE TITLE
shipping charge stays in inventory even when inventory item were taken out of cart

### ISSUE THREAD

**Issue by mikeyapina** [bagisto/bagisto#3560]
# Bug report

shipping charge stays in inventory even when inventory item was taken out of cart

shipping charge stays in inventory even when inventory items were taken out of cart I had one Downloadable and one merchandise in the cart. I took out the merchandise and still there was a $10 delivery charge for the downloadable and no way to take it out.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. 1.1.0.
    2. dunno

### Steps to reproduce

    1. add a downloadable and merchandise with a shipping charge
    2. take out the merchandise
    3. you still have the shopping and no way to take it out 

### Expected result
obvious no shipping charge.

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by devansh-webkul** [comment]
Please check this issue, https://github.com/bagisto/bagisto/issues/3560.
