### ISSUE TITLE
getting exception if admin uploads higher size image in image swatch while editing/adding attribute

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3564]
# Bug report

### Title
getting exception if admin uploads higher size image in image swatch while editing/adding attribute

### Preconditions

    1. framework Version. Master

### Steps to reproduce
    1. step1: edit color attribute 
    2. step2: select image swatch and upload one image of 3.5 mb

### Expected result:
should give warning if not supports 
### Actual result
https://prnt.sc/tn3mv4

**Comment by bhanu-webkul** [comment]
Fixed in master

**Comment by vaishaliwebkul** [comment]
the same issue exist when upload image in custom file type attribute

https://prnt.sc/tvjo7m

https://prnt.sc/tvjnyx

**Comment by vaishaliwebkul** [comment]
fixed
