### ISSUE TITLE
No info about other discounts in case there is multiple group pricing exist in same product

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3572]
# Bug report

### Title
No info about other discounts in case there is multiple group pricing exist in same product for group
### Issue Description
for example: if there is 10 % discount on purchase of 1 item and 30% on purchase of 2 items, then 2nd discount should also be displayed there.

### Preconditions

    1. framework Version. Master

### Steps to reproduce
    1. step1: set 2 customer group pricing and check on front end
https://prnt.sc/tnwswz
### Expected result:
https://prnt.sc/tnwv1q
### Actual result
https://prnt.sc/tnwu01
as well in case 2nd discount got applied then don't show 1st discount in cart- https://prnt.sc/tnx1cy

**Comment by vaishaliwebkul** [comment]
@rahulshukla-webkul 
when applying a fixed amount to customer group pricing, then the percent amount should display till two decimal points.
![Screenshot_238](https://user-images.githubusercontent.com/43210406/106441649-534c8200-64a0-11eb-9314-b0a953f237c5.png)
