### ISSUE TITLE
One page Checkout loader hits on adding single digit in phone number

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3574]
# Bug report

### Title
One page Checkout loader hits on adding single digit in phone number

### Issue Description
One page Checkout loader hits on adding single digit in phone number

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- go to the checkout process 
    2. step2-  add the billing address form till the phone number's 1st digit

### Expected result

loader should come when billing address phone number is entered properly or on user click action

### Actual result
![Screenshot (39)](https://user-images.githubusercontent.com/43210406/88455931-3f8fe580-ce97-11ea-8e26-de85c0261942.png)

![Screenshot (40)](https://user-images.githubusercontent.com/43210406/88455960-7cf47300-ce97-11ea-9f79-ebb9bff2df18.png)

**Comment by jhapali9** [comment]
go to        =>       resources\themes\velocity\checkout\onepage.blade.php
comment or remove       =>       this.$root.showLoader(); 
![screenshot](https://user-images.githubusercontent.com/34573743/88456742-f4c69b80-ce9f-11ea-81ce-6490385a925d.png)

**Comment by vaishaliwebkul** [comment]
fixed
