### ISSUE TITLE
Getting exception while using layered navigation filters on category page

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3591]
# Bug report

### Title
Getting exception while using layered navigation filters on category page

### Preconditions

    1. framework Version. Master

### Steps to reproduce

    1. step1: go to category page and try to use filters - color and size(*use db prefix before migration command, eg: fb_)

### Expected result:
filter should work properly
### Actual result:
![Screenshot 2020-07-29 11:32:47](https://user-images.githubusercontent.com/52821836/88763416-baefe080-d190-11ea-9c9e-024ca2a73770.png)

**Comment by vaishaliwebkul** [comment]
fixed
