### ISSUE TITLE
I would like like to change the admin route or url

### ISSUE THREAD

**Issue by thinklifepot** [bagisto/bagisto#3595]
Please is it Possible for me to change the admin Route or Url?
for example
**https://example.com/admin** takes me to the admin page.
this url can easily be guessed by anyone .
I would love to change it to something different or move it to a sub-domain

**Comment by devansh-webkul** [comment]
Hi @thinklifepot,

Please check this link https://forums.bagisto.com/topic/1609/i-would-like-like-to-change-the-admin-route-or-url/3.

**Comment by rahulcs0082** [comment]
For now there is no way to achieving this by not changing to the core files.

Please take a look at the following file:

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Admin/src/Http/routes.php#L4

Surely we will implement this is our future release.
