### ISSUE TITLE
showing different number of star in velocity and default theme for same rating

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3606]
# Bug report

### Title
showing different number of star in velocity and default theme

### Preconditions
    1. framework Version. Master
### Expected result
https://prnt.sc/tr5sq1 - source amazon.com
### Actual result
https://prnt.sc/tr5mur- showing 3 star 
https://prnt.sc/tr5nih -showing 4 star for same rating

**Comment by jyoti-webkul** [comment]
- Fixed

-------------------------

![Screenshot (67)](https://user-images.githubusercontent.com/45203177/89408452-04669f80-d73e-11ea-8daa-ed3823c6353a.png)
![Screenshot (66)](https://user-images.githubusercontent.com/45203177/89408458-06c8f980-d73e-11ea-9733-728ae048117b.png)
