### ISSUE TITLE
The content of CMS page is cropped

### ISSUE THREAD

**Issue by autn** [bagisto/bagisto#3611]
# Bug report

### Title
**Bagisto does not show full content of CMS page**

### Issue Description
**The long content of CMS page should not to crop**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: 1.1.2

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Edit a CMS page
    2. Fill the long content to `Content` field
    3. Save the CMS page

### Expected result
**The full content should be saved**

### Actual result

 **The content is cropped**

* I see your team used `longtext` in `cms_pages` table, but then change to `text` in `cms_page_translations` table, it should be kept as `longtext`

P/s: I wanna to contribute to Bagisto, but when I push the code, I got 403. Would you like to add me to the contributors list?
Updated: I found the way to contribute and created the PR, please help me to review and merge, thanks!

**Comment by vaishaliwebkul** [comment]
@autn 
Thanks.
