### ISSUE TITLE
Getting exception while uploading favicon image if image is of high size 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3615]
# Bug report

### Title
Getting exception while uploading favicon image if image is of high size 
### Preconditions

    1. framework Version. Master

### Steps to reproduce
    1. step1: first upload any image in logo
    2. step2: after that try to upload any high size(eg.3.5mb) image in favicon

### Expected result:
should get validation message
### Actual result:
https://prnt.sc/trqrnb

**Comment by vaishaliwebkul** [comment]
fixed
