### ISSUE TITLE
Ui issue when applying filter in mobile view

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3621]
# Bug report

### Title
Ui issue when applying filter.

### Issue Description
Ui issue when applying filter.

### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- Go to mobile view and open order grid.
    2. step2.-Select any option from filter.
### Expected result

Dropdown should be visible properly to select option
### Actual result

Dropdown field hide behind items per page field

![Screenshot (58)](https://user-images.githubusercontent.com/45203177/89096755-841b0400-d3f6-11ea-8239-90a9cf038578.png)

**Comment by vaishaliwebkul** [comment]
@shubhwebkul 
Item per page label is missing in UI https://prnt.sc/tu9ie9

**Comment by vaishaliwebkul** [comment]
fixed
