### ISSUE TITLE
Out of stock child products should not be visible in grouped product

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3624]
# Bug report

### Title
Out of stock child products should not be visible in grouped product

### Preconditions

    1. framework Version. Master

### Steps to reproduce
    1. step1: create a grouped type product, add any out of stock product in grouped products

### Expected result:
out of stock child products should not display 
### Actual result:
https://prnt.sc/ts6yi0

**Comment by vaishaliwebkul** [comment]
fixed in this issue : https://github.com/bagisto/bagisto/issues/3575
