### ISSUE TITLE
Correct the Success message after updating content in velocity meta data.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3628]
# Bug report

### Title
Correct the Success message after updating content in velocity meta data.

### Issue Description
Correct the Success message after updating content in velocity meta data.

### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- update content in meta data section
    2. step2-check the success message

### Expected result
Success message should be Velocity meta data is updated successfully.
### Actual result

![Workspace 1_107](https://user-images.githubusercontent.com/45203177/89100403-547af480-d414-11ea-8360-22c01ac96066.png)

**Comment by vaishaliwebkul** [comment]
fixed https://prnt.sc/tt02zi
