### ISSUE TITLE
Unable to delete last tax rate.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#363]
Framework Version: 0.1.3

**Comment by prashant-webkul** [comment]
yes atleast one tax rate is required to be there.

**Comment by Jyoti-Singh1** [comment]
If I have not created any tax then what is the use of tax rate.

**Comment by prashant-webkul** [comment]
No tax will be applied on cart when checking out, it will always be zero.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
