### ISSUE TITLE
Correct the Ui of profile in mobile view,there is no difference in field name test and field data.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3636]
# Bug report

### Title
Correct the Ui of profile in mobile view,there is no difference in field name test and field data.

### Issue Description
Correct the Ui of profile in mobile view,there is no difference in field name test and field data.

### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1-In mobile view check the profile grid of customer.

### Actual result
![Screenshot (62)](https://user-images.githubusercontent.com/45203177/89103097-ed1d6e80-d42c-11ea-8819-23109c62737b.png)

**Comment by vaishaliwebkul** [comment]
fixed https://prnt.sc/tu9djg
