### ISSUE TITLE
No records founds text in downloadable product section of customer should display in centre, in mobile view.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3637]
# Bug report

### Title
Correct the Ui of profile in mobile view,there is no difference in field name test and field data.
### Issue Description
Correct the Ui of profile in mobile view,there is no difference in field name test and field data.
### Preconditions

    1. framework Version.-master

### Steps to reproduce

    1. step1- In Mobile view, go to Downloadable Product section

### Expected result
Text should display in centre.

### Actual result

![Screenshot (63)](https://user-images.githubusercontent.com/45203177/89103262-18548d80-d42e-11ea-8886-8081e2a424c3.png)

**Comment by vaishaliwebkul** [comment]
fixed https://prnt.sc/tueyqq
