### ISSUE TITLE
Invoices should contain the company/store data 

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3643]
# Bug report

a invoice should contain the: store name, VAT number, address, contact, bank details.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
 Copy of invoice should be the same at both end customer & admin.
-  hash # is removed from the order ID, Invoice ID in the customer invoice

- date format at customer invoice is not updated

Translation Issue in Invoice when generating in any other locale eg; Arabic
![Screenshot_33](https://user-images.githubusercontent.com/43210406/91582631-b411e480-e96d-11ea-80ec-8ae39ec14b98.png)

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
Still, the minor bug is left, grand total is not encoded in ar https://prnt.sc/u8tvoj

**Comment by vaishaliwebkul** [comment]
Implementation done and working fine.
