### ISSUE TITLE
Favicon option should be available for admin section also.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3646]
This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
It's already done in this PR https://github.com/bagisto/bagisto/pull/2978
Kindly check with  master branch.

**Comment by ghermans** [comment]
Closing this one since this is a duplicate issue.
