### ISSUE TITLE
Order status is pending after generating the invoice.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3654]
# Bug report

### Title
Order status is pending after generating the invoice.
### Issue Description
Order status is pending after generating the invoice.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version- master

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1- Create an invoice of any order
    2. step2-check the status of order

### Expected result
Status should be processing

### Actual result
Showing status in pending state.

![Screenshot (65)](https://user-images.githubusercontent.com/45203177/89383466-2b12df00-d71a-11ea-8bd7-d5d000a76b77.png)
![Screenshot (64)](https://user-images.githubusercontent.com/45203177/89383484-3108c000-d71a-11ea-9693-f1cc0978a707.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
this is not a bug, currently, this is the latest feature added in this [PR](https://github.com/bagisto/bagisto/pull/3590), you can update the invoice status by editing it . https://prnt.sc/tub1gv
