### ISSUE TITLE
Product name gets blank each time we refresh the product page.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3656]
# Bug report

### Title
Product name gets blank each time we refresh the product page.

### Issue Description
Product name gets blank each time we refresh the product page.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-master

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1- Refresh the page and check the created product name

### Expected result
Product name should display always.
### Actual result

![Workspace 1_113](https://user-images.githubusercontent.com/45203177/89386558-dde53c00-d71e-11ea-8473-1d0b2224ac9d.png)
![Workspace 1_112](https://user-images.githubusercontent.com/45203177/89386560-dfaeff80-d71e-11ea-8d64-2193a970ef22.png)
![Workspace 1_111](https://user-images.githubusercontent.com/45203177/89386563-e0479600-d71e-11ea-8a6e-7793d652149a.png)

**Comment by vaishaliwebkul** [comment]
not working fine, still by default, various products are missing, when set ENGLISH filter then all products are visible
![Screenshot (9)](https://user-images.githubusercontent.com/43210406/89776954-749f6780-db28-11ea-9790-d1729a99d149.png)

**Comment by jyoti-webkul** [comment]
Still getting this issue in version 1.2.0


[screencast-demo.bagisto.com-2020.09.15-20_22_40.webm.zip](https://github.com/bagisto/bagisto/files/5225827/screencast-demo.bagisto.com-2020.09.15-20_22_40.webm.zip)

**Comment by bhanu-webkul** [comment]
Fixed in master
