### ISSUE TITLE
Auth user can see all users info by id

### ISSUE THREAD

**Issue by megalightfm** [bagisto/bagisto#3657]
# Bug report

When I log in via API call with ?token=true, then with that token I can get all users info, like this...
http(s)://example.com/public/api/customers/10, but my login user is 3
 Please fix it

**Comment by megalightfm** [comment]
Are you fix this bug, if yes how can get an update??

**Comment by megalightfm** [comment]
Hey, any news one my ticket??

**Comment by devansh-webkul** [comment]
Hi @megalightfm,

PR is open & ready to review. Once it will be merged you can check.

**Comment by vaishaliwebkul** [comment]
@megalightfm 
This is fixed now, kindly update your code with the commit https://github.com/bagisto/bagisto/commit/5b05e5744f06a098950278dc6185ec11724d58c4 or you can take pul from the master branch.

Feel free to reopen the issue if still exist.
Thanks
