### ISSUE TITLE
Customer should get mail on changing invoice state

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3669]
# Bug report

### Title
Customer should get mail on changing invoice state

### Preconditions
    1. framework Version. master

As of now customer is not getting nay mail on changing invoice state.

**Comment by ghermans** [comment]
@bhanu-webkul  can you explain why a email should be send to the customer when we change the invoice state?
Customers already receive a email when the invoice is created & when the order is shipped.
Most companies will not ship your order before its payed, so the shipping mail is actually your confirmation that the invoice is payed, or am i missing something?

**Comment by bhanu-webkul** [comment]
@ghermans   How would customer get information about overdue if he is not getting mail on changing invoice state, So it would be more customer friendly if we provide info of each steps performed on their order either through mail or in order details

**Comment by ghermans** [comment]
I added this to issue #3644
