### ISSUE TITLE
If products are added in shopping cart and those product get deleted from admin section then it still displays in cart.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#368]
Framework Version: 0.1.3
Test Steps:
1. Add a product in cart.
2. Delete that product from admin.
3. Now view cart.
4. Click on view and edit cart.
5. Even after clicking on checkout product displays in cart.

![screenshot from 2018-12-21 13-55-18](https://user-images.githubusercontent.com/45203177/50332557-7a49d300-0528-11e9-8d00-49fda16180e5.png)

**Comment by prashant-webkul** [comment]
The previous issue #281 was duplicated due to same action of deleting product that is already added in the cart of the customer.

**Comment by Jyoti-Singh1** [comment]
Framework Version:0.1.4
Not Fixed
Now after deleting the product from admin grid its not displaying in minicart but on cart page order summary is visible.
![screenshot 77](https://user-images.githubusercontent.com/45203177/52121721-9ae86b00-2646-11e9-86ae-c6c72d82ffb4.png)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
