### ISSUE TITLE
Velocity theme does not support on  Internet Explorer

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3683]
# Bug report

### Title
Velocity theme does not support on Internet Explorer

### Issue Description
Velocity theme does not support on Internet Explorer

### Preconditions

    1. framework Version- master
    2. Browser- Internet explorer
    3. OS- Windows
    
### Steps to reproduce

    1. step1- Open velocity on Internet explorer
  
### Expected result

 header, sidebar menu category should come in velocity theme

### Actual result
![Screenshot_7](https://user-images.githubusercontent.com/43210406/89551333-77e4db80-d828-11ea-9638-3b7c6a157c09.png)

**Comment by stanliwise** [comment]
Encountered same error too, I think the script is kinda failling. with something like 
'MutationObserver' is undefined

**Comment by devansh-webkul** [comment]
This is working fine on IE Edge below IE Edge it is not working. And compilling the whole js in a blade files is a very time consuming. They don't even support back tick operators and callback function.

Even microsoft is not support below IE Edge.

I personally feel this enhancement should be closed.

**Comment by ghermans** [comment]
as @devansh-webkul mentioned, providing support for older browsers like Internet Explorer is takes to much time for what it's worth, also Microsoft is forcing everyone to use Edge instead IE.

Because of that i am closing this issue.

**Comment by croeber** [comment]
Yall should at least tell the user to use a better browser, how would I accomplish this in the bagisto framework.

**Comment by ghermans** [comment]
We actually don't have to do anything.. and certainly not supporting software that is end of life. 
The fact that you continue to use internet explorer is not our responsibility.
