### ISSUE TITLE
Select icons should be in right side in RTL on payment page in default theme

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3688]
# Bug report

### Title
Select icons should be in right side in RTL 

### Preconditions
    1. framework Version. Master
### Steps to reproduce
    1. step1: select ar locale and try to place order(make theme should be default)

### Actual result
https://prnt.sc/tvmeol

**Comment by bhanu-webkul** [comment]
need to correct this as well -- https://prnt.sc/tvn23y

**Comment by vaishaliwebkul** [comment]
fixed https://prnt.sc/txt3uh
