### ISSUE TITLE
Logout when not active for a set of time.

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#3696]
Version: 0.1.8

Can anyone tell how can I change the timeout time for inactive? I was trying to edit a product page, but I took longer than usual. When I finish editing. The system log me out. How can I change it to longer time?

**Comment by devansh-webkul** [comment]
Hi @lYesterdaYl,

**1st Way**: There is a file in the project root directory named '**.env**'. In that file search for the key '**SESSION_LIFETIME**'. Update that value.

**OR**

**2nd Way**: If somehow key is not present then just add the key and add value.

**OR**

**3rd Way**: Go to '**config/session.php**' and search for the key '**lifetime**' and value theirs.

**Important Note**: Value should be filled in respect of minutes.

**Comment by jitendra-webkul** [comment]
I hope the above reply fixed your issue. I am closing this issue, feel free to reopen.
