### ISSUE TITLE
Undefined Variable 'attribute' Error

### ISSUE THREAD

**Issue by stanliwise** [bagisto/bagisto#3697]
# Bug report

### Title
**New Category with slug 'iphone' throws attribute error** 

### Issue Description
I created a new category 'Iphone' as soon as I clicked the drop down category menu and clicked on the new category url on the homepage which should have taken me to the category page I guess but, it had an error with message

ErrorException thrown with message "Undefined variable: attributes (View: C:\Users\STANLIWISE\Desktop\Bagisto\resources\themes\velocity\views\products\list\layered-navigation.blade.php) (View: C:\Users\STANLIWISE\Desktop\Bagisto\resources\themes\velocity\views\products\list\layered-navigation.blade.php)"

version 1.1.2

### Screenshot
*   [Screenshots, logs or description]
![error](https://user-images.githubusercontent.com/31096369/89743766-38bfc000-da9e-11ea-8bc1-a2e40ca3a480.png)

### updates
I just fixed the issue by changing category attribute from brand to price and it works fine. I don't know what that means

**Comment by vaishaliwebkul** [comment]
Hi @stanliwise 
this bug exists in bagisto 1.1.2 version which is already resolved in the **master** branch, you may check this here https://github.com/bagisto/bagisto/issues/3320, 

You can fix it by updating the files as mention in this PR https://github.com/bagisto/bagisto/commit/85aed162b2ab0b9320eaf8d278d974a4d87c9b7e

**Comment by stanliwise** [comment]
Ok thanks
