### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError  : syntax error, unexpected ';', expecting ']'

### ISSUE THREAD

**Issue by mando0673** [bagisto/bagisto#3716]
![image](https://user-images.githubusercontent.com/49507906/89855003-90a21800-dbbf-11ea-8115-ba798f584593.png)

Please Help

**Comment by shubhwebkul** [comment]
Hello there,

We are not getting this type of exception, Have you done any changes in [this](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shipping/src/Config/system.php) file.

In your project there is exception @ line 270 but we don't have that in our file.
please check once again:-
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shipping/src/Config/system.php

Let me know if you are facing any further doubt.
Thanks!
