### ISSUE TITLE
getting exception on comparison page of default theme

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3725]
# Bug report

### Title
getting exception on comparison page of default theme

### Issue Description
getting exception on comparison page of default theme

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add products to compare
    2. step2- view compare page

### Expected result

all product should be view in the comparison list

### Actual result
![Screenshot (13)](https://user-images.githubusercontent.com/43210406/89905960-63c62300-dc08-11ea-8bd1-775e8fab3754.png)

**Comment by bhanu-webkul** [comment]
Fixed in master
