### ISSUE TITLE
compare page layout issue for logged in user

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3727]
# Bug report

### Title
compare page layout issue for logged in user

### Issue Description
compare page layout issue for logged in user

### Preconditions

    1. framework Version- master
    
### Steps to reproduce

    1. step1- login with customer & add products to compare having attribute image type
    2. step2- open the compare product page

### Expected result
the design should be fixed

### Actual result

![Screenshot (14)](https://user-images.githubusercontent.com/43210406/89912214-eacac980-dc0f-11ea-8e64-48f0fc1ddf11.png)

**Comment by bhanu-webkul** [comment]
Fixed in master
