### ISSUE TITLE
Order status should not be completed until invoice state is pending 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3734]
# Bug report

### Title
Order status should not be completed until invoice state is pending 

### Preconditions
    1. framework Version. Master

### Steps to reproduce

    1. step1: place order, create invoice and shipment  
    2. step2: check order status

### Expected result:::::
if invoice state is not paid  and shipment is also not created then it should be pending and if shipment has been generated then it should be processing .   
### Actual result
https://prnt.sc/tyc3qf
https://prnt.sc/tyc4gk

**Comment by ghermans** [comment]
We also have the order status **pending payment** for pending invoices

**Comment by vaishaliwebkul** [comment]
@bhanu-webkul 
This should be closed according to the current scenario of Invoice flow.
