### ISSUE TITLE
category adding error

### ISSUE THREAD

**Issue by gabelatendai** [bagisto/bagisto#3736]
# Bug report

SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update `categories` set `image` = category/4/Oj3BgsKahChyRQpU994lCaU9XrI77vd36c47ik7g.jpeg, `categories`.`updated_at` = 2020-08-12 17:56:43 where `id` = 4)

**Comment by rahulcs0082** [comment]
HI @gabelatendai 

Please follow this one - https://github.com/bagisto/bagisto/issues/2562

**Comment by vaishaliwebkul** [comment]
@gabelatendai 
hope the above solution worked for you, so closing this.

Feel free to reopen it anytime

**Comment by gabelatendai** [comment]
am now on it ,let me work on it , Thank you .. Will Tell you if it worked
