### ISSUE TITLE
Id of already created product changes after creating configurable product.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#374]
Framework Version: 0.1.3

When the product was created its id was 6.After creating the configurable product its id changes to 14.
![screenshot 42](https://user-images.githubusercontent.com/45203177/50341976-04a12f80-0547-11e9-9d45-36e4f55898a4.png)

**Comment by prashant-webkul** [comment]
Cannot find the conclusive evidence of this thing and the product grid had been refactored moderately.
