### ISSUE TITLE
Velocity theme layout not responsive

### ISSUE THREAD

**Issue by itdeed** [bagisto/bagisto#3754]
Hello,

Velocity theme layout not coming responsive in different devices. 

Issue thread was going on the forum at the following link
https://forums.bagisto.com/topic/1666/velocity-theme-layout-not-responsive/12

I have check lots of time in the Firefox & chrome browser after refreshing in mobile size but still issue is there.

So the issue is there. For explaining more I am sharing code difference which is coming in different browsers for demo bagisto.

 Please review the following images for chrome and firefox. you will get clear both browsers showing different HTML code thus responsive issue coming.
![chrome](https://user-images.githubusercontent.com/33649099/90169549-59e52100-ddbc-11ea-89f8-6986b3d35264.jpg)
![FF](https://user-images.githubusercontent.com/33649099/90169572-66697980-ddbc-11ea-90ea-b8dc0f5b1915.jpg)

Really I need it to fix the responsive issue ASAP.  Please help.

**Comment by vaishaliwebkul** [comment]
@itdeed 
the responsive issue is fixed now, Kindly take a pull from the master branch,

Feel free to reopen the issue if it's still exist.
Thanks

**Comment by itdeed** [comment]
I have customization bagisto at my end so cannot update setup directly. 

I will thank full, if you can suggest what things need to update. 

Please suggest.

**Comment by vaishaliwebkul** [comment]
@itdeed 
Ya sure, you can manually do these changes in your file as mention in this commit https://github.com/bagisto/bagisto/commit/38c3b507724f6439323ec80add3775f8cf6a2b77 , once done run the following command from the root directory
`php artisan config:cache`
`php artisan vendor:publish --force`

**Comment by itdeed** [comment]
Thanks for your quick reply.
I have updated these changes but the issue not fixed in my setup. Following is site URL:

http://www.noisemerch.com/store/public/

Can you please review it and suggest about the issue?

Many Thanks
