### ISSUE TITLE
Webinstall - SMTP port is not set 

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3755]
# Bug report

### Issue Description
When you set the SMTP port to 25 the port is still defined to 2525

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master branch

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Setup a new Bagisto installation and use the web installer.
    2. Set the SMTP port to a custom number.

### Expected result
The correct port should be defined.

*   [Screenshots, logs or description]

### Actual result
The port is still defined to 2525 as this is set in **.env_example**

**Comment by vaishaliwebkul** [comment]
fixed in master.
