### ISSUE TITLE
Customer should not get invoice until invoice state is not paid

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3763]
# Bug report

### Title
Customer should not get invoice until invoice state is not paid

### Preconditions
    1. framework Version. Master

### Steps to reproduce
    1. step1: place order and create invoice

### Expected result:
Without payment customer should not get invoice
### Actual result:
Customer is getting invoice before payment

**Comment by ghermans** [comment]
This issue makes no sense, in case you select money transfer as payment method you will need a invoice since this contains the bank account number and amount that the customer needs to pay,
How can the customer pay a invoice if he does not receive it?
