### ISSUE TITLE
Header-nav on mobile view seem buggy on search item

### ISSUE THREAD

**Issue by otheriz** [bagisto/bagisto#3767]
# Bug report

### Title
Header-nav on mobile view seem buggy on search item

### Issue Description
Nav style seems not right

### Preconditions
the latest version (or demo website)

### Steps to reproduce
1. go to the mobile view
2. do a search filter for any items

### Expected result
On Demo Web
![image](https://user-images.githubusercontent.com/11325840/90316209-d7d73280-df4a-11ea-8334-4e5ddd342d22.png)

On My Site
![image](https://user-images.githubusercontent.com/11325840/90316273-487e4f00-df4b-11ea-9de0-5874969447e5.png)

### Actual result
On Demo Web
![image](https://user-images.githubusercontent.com/11325840/90316222-ea516c00-df4a-11ea-813b-4abb6f0a9318.png)

On My Site
![image](https://user-images.githubusercontent.com/11325840/90316287-5e8c0f80-df4b-11ea-9726-8b64ab9ecdf8.png)

**Comment by vaishaliwebkul** [comment]
@otheriz 
could you please mention your bagisto version?

**Comment by otheriz** [comment]
@vaishaliwebkul ,

i always pull latest version from github...yesterday is my latest pull from the master version
and always run necessary command like "vendor:publish, etc"

Only get this when you do 'search filter'...i think it's load a different template because the 'inspect' show a 'search-container' class div...
