### ISSUE TITLE
Unable to add more than 4 products in related products

### ISSUE THREAD

**Issue by elite-digital** [bagisto/bagisto#3772]
I have created store using latest version of Bagisto.

When editing a product to add linked products like related product in drop down I am able to add any number of products and after click save button its showing success message but when again editing same product its showing only 4 product saved in related product selector box.

**Comment by rahulcs0082** [comment]
Hi @elite-digital 

We used to show only 4 products for the linking products if you need then you can change from the product model.

**Comment by vaishaliwebkul** [comment]
@elite-digital 
Hope the query is resolved so we are closing this.

Feel free to reopen in case of any doubt.

**Comment by elite-digital** [comment]
How to enable breadcrumb in velocity theme?

Best Regards,

Sandeep Yadav
Mobile: 9891568630
Skype: ysandeep10
https://www.elitedigital.co.in

**Comment by vaishaliwebkul** [comment]
@elite-digital 
This feature is yet not added & already raised here https://github.com/bagisto/bagisto/issues/2559
