### ISSUE TITLE
Getting exception on frontend after installation.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3781]
# Bug report

### Title
Getting exception on frontend after installation.
### Issue Description
Getting exception on frontend after installation.
### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-v1.2.0-BETA1

### Expected result
Home page should open

### Actual result

Getting exception
![Workspace 1_141](https://user-images.githubusercontent.com/45203177/90494366-0fb7c300-e161-11ea-902c-c42f89e96af8.png)

**Comment by vaishaliwebkul** [comment]
fixed in master by PR https://github.com/bagisto/bagisto/pull/3796
