### ISSUE TITLE
Getting error on running php artisan migrate if db_prefix contains decimal value    

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3782]
# Bug report

### Title
Getting error on running php artisan migrate if db_prefix contains decimal value   

### Preconditions
    1. framework Version. Master
### Steps to reproduce
    1. step1: enter numeric value in db_prefix such as 1.2
    2. step2: run php artisan migrate

### Actual result:
bhanu.pratap@bhanu214:~/www/html/masnew$ php artisan migrate

In Str.php line 174:

Maximum function nesting level of '256' reached, aborting!

bhanu.pratap@bhanu214:~/www/html/masnew$

**Comment by deepaksinghgusain227** [comment]
@bhanu-webkul 
Can you share the screenshot of error you are getting.

**Comment by bhanu-webkul** [comment]
![screenshot_from_2020_08_20_19_36_28](https://user-images.githubusercontent.com/52821836/90782601-ab416300-e31c-11ea-8f16-f93cafec5f20.png)

**Comment by bhanu-webkul** [comment]
Fixed in Master
