### ISSUE TITLE
Not able to find product through image.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3788]
# Bug report

### Title
Not able to find product through image.
### Issue Description
Not able to find product through image.

### Preconditions

    1. framework Version.-v1.2.0-BETA1

### Expected result

If product image is uploaded then product  should display on search it it is available.
### Actual result

Product is available but doesn't display

![Screenshot (27)](https://user-images.githubusercontent.com/45203177/90521870-a77cd780-e188-11ea-838e-365225e6d68c.png)

![Screenshot (26)](https://user-images.githubusercontent.com/45203177/90521887-ac418b80-e188-11ea-9b0e-ad1bb9693366.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
The image search feature will detect the object from the given image and provide you all the analyzed keywords for that object.
In your example; you have uploaded the Headset then TensorFlow will detect all the objects in this image "mike" "radio" and giving you all the keyword, which will helps customer to easily search the product by the related image.
