### ISSUE TITLE
Add Category Option Giving  500 Server Error on Live demo

### ISSUE THREAD

**Issue by prafful-panwar-ayur** [bagisto/bagisto#3790]
# Bug report

### Title
**Add Category Option Giving  500 Server Error on https://demo.bagisto.com/bagisto-157-37-128-230/**

**Comment by vaishaliwebkul** [comment]
@prafful-panwar-ayur 
Thanks for reporting this. we will revert back to you soon once the demo will be updated.

**Comment by FreezeS** [comment]
Found the solution. In my.cnf:

collation-server=utf8mb4_unicode_ci
