### ISSUE TITLE
Recently viewed product is not working for Locales other than default.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3792]
# Bug report

### Title
Recently viewed product is not working for Locales other than default.

### Issue Description
Recently viewed product is not working for Locales other than default.
### Preconditions

    1. framework Version.-v1.2.0-BETA1

### Steps to reproduce

    1. step1- Change locale on frontend
    2. step2- Click on product to view and check the recently viewed product

### Expected result

Viewed product should display in recently viewed product.

### Actual result

![Workspace 1_147](https://user-images.githubusercontent.com/45203177/90621708-b2d80d80-e231-11ea-9f33-ef71acb6f158.png)

**Comment by bhanu-webkul** [comment]
Fixed in master
