### ISSUE TITLE
On front-end currency symbol display only for Indian Rupee and USD. If code is selected other than these two in currency then code displays before price.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#381]
Framework Version: 0.1.3
![screenshot 36](https://user-images.githubusercontent.com/45203177/50372971-daf70f80-05fd-11e9-953d-67e6fbbd406c.png)
![screenshot 37](https://user-images.githubusercontent.com/45203177/50372975-e0ecf080-05fd-11e9-9118-81ee5ce43da8.png)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Not Fixed
![screenshot 6](https://user-images.githubusercontent.com/45203177/52465685-7a1f9880-2ba5-11e9-95d6-3cdd96037de5.png)

**Comment by prashant-webkul** [comment]
This was deliberately left as we don't have currency symbols to apply for the other currencies.
Yet a fix will be provided for it shortly.

**Comment by jitendra-webkul** [comment]
you have saved wrong currency code
