### ISSUE TITLE
Add feature to link Google Analytics in bagisto.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3810]
This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by vaishaliwebkul** [comment]
referenced PR https://github.com/bagisto/bagisto/pull/3880

**Comment by vaishaliwebkul** [comment]
done
