### ISSUE TITLE
Export Function not working in Firefox/Linux

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#3819]
Clicking the Export button in DataGrids using Firefox/Linux dismisses the dialogue without exporting the data.

### Preconditions

    1. Bagisto v1.1.2 
    2. Firefox 68.11 (on Linux)

### Steps to reproduce

1. Navigate to a DataGrid View (sales, catalogue, etc.)
2. Click Export Link
3. Select CSV or XLS
4. Click Export Button

### Expected result

File should be exported downloaded.

### Actual result

Export Window closes without downloading any data.

It appears dismissing the window immediately after the submit in Firefox prevents the export from being downloaded. Removing this line from Webkul\Admin\src\Resources\views\export\export.blade.php restores the export functionality and does not dismiss the dialogue when using Firefox. I don't know JavaScript enough to offer any other alternatives.

`this.$root.$set(this.$root.modalIds, 'downloadDataGrid', false);`

**Comment by vaishaliwebkul** [comment]
@richmondnursery 
the bug is fixed now, you may review by taking the pull from the master branch.

Feel free to reopen the issue if the bug still exist.
