### ISSUE TITLE
how to show the shopping cart as modal after adding an item to it

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#3820]
hi i want to show a modal to my user with the content of the shopping cart after he adds a product to the cart . as i saw the page is reloaded after the submit of form . i wanted to know how can i do or try this . i fell i should add the code after the alert here in add-t-cart.vue
```
 window.showAlert(`alert-success`, this.__('shop.general.alert.success'), response.data.message);
``` 
thanks in advance

**Comment by rahulcs0082** [comment]
HI @farshadff 

You can add modal in this file's **addToCart** method and also need to write code for this in an **add-to-cart.blade.php** file.

**Comment by farshadff** [comment]
thanks but i  think i have to add some js or vue code to show it after the form submit because adding that to this file will show it when page loads or just before submit of form . beside this is partial and cant add script tag to it i think

**Comment by rahulcs0082** [comment]
Hi @farshadff 

Definitely you need to add some js code.

**Comment by farshadff** [comment]
thanks for the answer i will try to figure out how to do that and update the thread
