### ISSUE TITLE
Class 'Barryvdh\Debugbar\ServiceProvider' not found during composer install

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3821]
# Bug report

### Issue Description
When running the command **composer install** on a plesk server it returns
```
In ProviderRepository.php line 208:

Class 'Barryvdh\Debugbar\ServiceProvider' not found
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

### Preconditions
1. Bagisto 1.2.0-beta1

**Comment by rahulcs0082** [comment]
Hi @ghermans 

We have not experienced this issue when running this command at the given bagisto version and moreover we have released 1.2.0-BETA1.

**Comment by ghermans** [comment]
oops i made a typo but it was indeed 1.2.0-beta

**Comment by ghermans** [comment]
@rahulcs0082 
![pleskInstall](https://user-images.githubusercontent.com/1594411/94064880-97d95a00-fdea-11ea-97e9-5209af54a36c.JPG)
