### ISSUE TITLE
social icons are not visible in footer 

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3831]
# Bug report

### Title
social icons are not visible in footer 

### Issue Description
social icons are not visible in footer 

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Go to default theme shop view in the footer
    2. step2- see the social links icon are not visible

### Expected result

![Screenshot (18)](https://user-images.githubusercontent.com/43210406/91164286-72bed200-e6ec-11ea-8cf6-33f5ca026ed3.png)

### Actual result

![Screenshot_28](https://user-images.githubusercontent.com/43210406/91164320-7eaa9400-e6ec-11ea-9653-1ccdaca9facd.png)

**Comment by jyoti-webkul** [comment]
- Fixed

----------------------------

![Screenshot (41)](https://user-images.githubusercontent.com/45203177/91420997-03bfb580-e873-11ea-864b-4afbd0e369b8.png)
