### ISSUE TITLE
Trying to sort by product updated_at

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#3838]
Hi, I am trying to sort the product by its updated_at. I already change the database type to timestamp, but I notice the updated_at only updated when I change info from the general section. It doesn't update at all when I change information in like description. How should I modify that?

**Comment by vaishaliwebkul** [comment]
@lYesterdaYl 
could you mention your bagisto version?

**Comment by vaishaliwebkul** [comment]
Not getting any activity from the last 11 days so closing this issue.

Feel free to reopen anytime,
