### ISSUE TITLE
Login option not showing on Checkout page when Guest Checkout enabled

### ISSUE THREAD

**Issue by sandeep-ed** [bagisto/bagisto#3842]
Hello Team,

When I enabled Guest Checkout its disabled login option on front end Completely and showing billing detail form only. While there would be option for user If he want to checkout as Guest user or loggedin User and and If clicked on Login user it should show login form.

Thank You

**Comment by vaishaliwebkul** [comment]
Hi @elite-digital 
could you please show the screenshot whatever you're facing while turn on Guest checkout option

**Comment by ghermans** [comment]
Steps to reproduce

1. Create a product and allow guest checkout.
2. Add the product to your cart.
3. Checkout your cart and you will directly see the form to enter your address etc.

Instead there should be a option to checkout as a user or guest.

**Comment by ghermans** [comment]
Issue is resolved ![resolved](https://user-images.githubusercontent.com/1594411/122629533-015a7080-d0be-11eb-8348-0eb1955674cb.PNG)
