### ISSUE TITLE
Add editable data by administrators

### ISSUE THREAD

**Issue by zangarmarsh** [bagisto/bagisto#3843]
Hi, this is my first project with bagisto and there's one thing I actually don't understand how can be handled. I need to realize the templates of several pages like the homepage, contacts, about...these templates data structure is way more complex than the simple title and body, but at the same time I need them to be editable by the administrators dashboard. How can I handle that? It's a sort of dynamic metadata associated on different templates/pages, something like ACF if you know the Wordpress environment.

Thank you in advance for your response.

**Comment by zangarmarsh** [comment]
Any tip?

**Comment by devansh-webkul** [comment]
@zangarmarsh,

Sorry for the late response but may I know what you want to edit from the admin because if you can check the CMS pages then you will see that page title, body, and meta data are already editable.

**Comment by devansh-webkul** [comment]
I am closing this issue. If something wrong please feel free to open the issue.
