### ISSUE TITLE
SWOOLE support

### ISSUE THREAD

**Issue by fhferreira** [bagisto/bagisto#3846]
Add SWOOLE support to make it fast

**Comment by cristiansoftlead** [comment]
Any updates here?

**Comment by jitendra-webkul** [comment]
Version 2.0.0 will have the support for octane.

**Comment by dheerajqa-webkul** [comment]
Please check the following documentation to configure Laravel Octane, 
This guide covers installation and setup instructions to fine-tune the performance.

Link: https://devdocs.bagisto.com/performance/configure-laravel-octane.html
