### ISSUE TITLE
QTY not returned to inventory when canceling an order after shipping

### ISSUE THREAD

**Issue by otheriz** [bagisto/bagisto#3847]
# Bug report

### Title
QTY is not returned to inventory when canceling an order after shipping

### Issue Description
When i try to cancel order after shipped status...the QTY not returned to the inventory...

### Preconditions
Latest pull master & bagisto demo site

### Steps to reproduce
    1. change the order status to 'shipped' then do the shipping (QTY deducted)
    2. somehow customer cancel the order after shipping/address not found
    3. cancel the order (QTY not returned)

### Expected result
QTY returned back to inventory after canceling the 'shipped' order

### Actual result
QTY is not returned back to inventory

**Comment by vaishaliwebkul** [comment]
@otheriz 
the shipped qty is returned back to inventory when the order cancels, Kindly check again.

**Comment by vaishaliwebkul** [comment]
@otheriz 
closing this issue.

Feel free to reopen if still exist.
