### ISSUE TITLE
Fix Payment Instruction view in checkout page

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3862]
# Bug report

### Title
Each Payment Instruction should be shown in a separate line

### Issue Description
Each Payment Instruction should be shown in a separate line

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- sales-> payment-> add instructions in payment method

### Expected result

> Heading should be in bold
Show each point in the new line
![Screenshot_39](https://user-images.githubusercontent.com/43210406/91872887-074da500-ec96-11ea-9f3f-a20122a85fa9.png)

### Actual result

![Screenshot_40](https://user-images.githubusercontent.com/43210406/91873004-2cdaae80-ec96-11ea-902d-380f7ff8a533.png)

**Comment by ghermans** [comment]
Also 2 times displaying the same payment method is useless.
For example: 
```
Cash On Delivery
Cash On Delivery
```
or 
```
Cash On Delivery - Cash On Delivery
```

**Comment by vaishaliwebkul** [comment]
@ghermans 
This is the Payment Method description if need we can change this from sales-> payment section

**Comment by vaishaliwebkul** [comment]
still not fixed in velocity theme
![Screenshot_41](https://user-images.githubusercontent.com/43210406/91958079-812c6f80-ed24-11ea-89cf-560f7e8ac1bd.png)
![Screenshot_42](https://user-images.githubusercontent.com/43210406/91958344-d8cadb00-ed24-11ea-8a5d-1bdda32cb369.png)

**Comment by vaishaliwebkul** [comment]
https://prnt.sc/udebsg fixed
