### ISSUE TITLE
Cart Rules have some 'wrong' output

### ISSUE THREAD

**Issue by otheriz** [bagisto/bagisto#3877]
# Bug report

### Title
Cart Rules have some 'wrong' output

### Issue Description
Cart rules did not get the correct "true" condition 

### Preconditions

    1. latest pull master
    2. Bagito demo site

### Steps to reproduce

Scenario 1. 
- create a cart rule with the condition (All Condition True)
- condition 1 : Category->contain->Topwear(bagisto demo item)
- condition 2 : Cart Attribute->Total item QTY(ex. 5)
- Action : Anything

Screnario 2. 
- create a cart rule with the condition (All Condition True)
- condition 1 : Category->contain->Topwear(bagisto demo item)
- condition 2 : Cart Item Attribute->QTY in cart(ex. 5)
- Action : Anything

    

### Expected result
Scenario 1: when in the cart, 3 Topwear and 2 other items..the discount should not apply
**Scenario 1 or 2: when in the cart, 3 Topwear A and 2 Topwear B..the discount should apply**

Note: 
if the current condition/output is correct from bagisto perspective, maybe need to add another mechanism(Cart Type) to achieve this condition?
or maybe i set up the wrong condition for the expected scenario please advice...

### Actual result
The condition apply differently(the condition like 'semi OR' instead of 'absolute AND')
Scenario 1: as long as total QTY item is 5 and there's a Topwear, the discount is applied..which is shouldn't
Ex. 3 Topwear + 2 Hat = 5 QTY..current bagisto, this condition applied the discount..which is shouldn't

Scenario 2: as long a Topwear item QTY is 5, the discount is applied..which is shouldn't
Ex. 2 Topwear A + 3 Topwear B = 5 QTY..discount not applied..which is should be applied
Ex. 5 Topwear A + 3 Hat = 8 QTY..discount applied..which is shouldn't

**Comment by bhanu-webkul** [comment]
Hi @otheriz , 
qty in cart indicates the qty of one item in cart and Total item indicates, total no. of products in cart.
so in scenario one if one item is matching category condition and total number of products matches total item condition, then cart rule will be applied and as per action customer will get discount on that item which matches category.
for scenario 2, item that matches category condition must match the qty in cart condition to get cart rule apply.

**Comment by otheriz** [comment]
Hi @bhanu-webkul ,
so how to achieve the expected result scenario?
3 Topwear A + 2 Topwear B = Discount applied... ?

i also aware of how bagisto handled this condition..
Maybe need to add "Total QTY" in "Cart Item Attribute" ?

Btw, which method did this occurred(Cart rule applied to cart or order)...?
i want to add another condition "Total QTY" in  "Cart Item Attribute"..and handled it like the expected result scenario.
