### ISSUE TITLE
Search by name doesn't work when sending a request via API

### ISSUE THREAD

**Issue by Dmytrosubbotin** [bagisto/bagisto#3878]
# Bug report

I'm trying to get the filtered products list with a request with the Name parameter, but it's getting all products, no matter if they have the requested title.

### Steps to reproduce
I reproduced this in Bagisto demo using these Axios requests:

axios.get(“https://demo.bagisto.com/bagisto-134-249-231-7/api/products?name='Striped Tshirt’“) axios.get(“https://demo.bagisto.com/bagisto-134-249-231-7/api/products”)

Both got the same amount of products for me

### Expected result
API requests by name should filter the products list

### Actual result

Name parameter doesn't affect the number of products in query

**Comment by ghermans** [comment]
Hi, thank you for reporting this, we are aware that the devdocs are incomplete or sometimes buggy. that's why we're currently improving the documentation and doing our best to be ready by the next release

**Comment by devansh-webkul** [comment]
This issue has been fixed in master. Please refer to this PR i.e. https://github.com/bagisto/bagisto/pull/3839.

**Comment by vaishaliwebkul** [comment]
@Dmytrosubbotin 
Closing this as it's already fixed, You may check with the mentioned PR.

Feel free to reopen it anytime.
