### ISSUE TITLE
Cart item not bound to the account when login with social login

### ISSUE THREAD

**Issue by otheriz** [bagisto/bagisto#3886]
# Bug report

### Title
Cart item not bound to the account when login with social login

### Issue Description
Cart item not bound to the account when login with social login

### Preconditions
Latest

### Steps to reproduce
1. add to cart some view item
2. checkout/direct login with a social account(google for example)
3. cart item not carried to the logged account

But when using a normal registered account is bound to the logged account

### Expected result
Cart Items should be carried to the logged account with social login as a normal account does

### Actual result
Cart Items not carried to the logged account with social login

**Comment by otheriz** [comment]
Found some solution...
There's some Event:dispatch with a comment in
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Customer/src/Http/Controllers/SessionController.php#L82

Just copy the line to this file, after the login script
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/SocialLogin/src/Http/Controllers/LoginController.php#L76

don't forget to include this..
`use Illuminate\Support\Facades\Event;`

it's worked for me...

**Comment by vaishaliwebkul** [comment]
@otheriz 
Thanks, It's resolved now.

Feel free to reopen it anytime.
