### ISSUE TITLE
social share icon should be enable by default

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3888]
# Bug report

### Title
social share icon should be enabled by default

### Issue Description
social share icon should be enabled by default

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- admin-> configuration-> catalog-> social icons

### Expected result

should be enabled by default

### Actual result

not enabled by default
![Screenshot_48](https://user-images.githubusercontent.com/43210406/92299088-fd18f880-ef6c-11ea-9cdc-554ca6c3be7a.png)

**Comment by vishal-webkul** [comment]
@vaishaliwebkul 
It is an external package so we can't enable it by default from our end.
