### ISSUE TITLE
Available Downloads is not coming correclty if customer has placed order of more than one qty in case admin has generated invoice only for 1 qty

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3893]
# Bug report

### Title
Available Downloads is not coming correclty if customer has placed order of more than one qty in case admin has generated invoice only for 1 qty
### Issue Description
For eg. if customer has placed order of 5 qty which allows 5 times total to download and admin generates invoice of only , still customer is able to download 5 times 

### Preconditions
    1. framework Version. Master

### Steps to reproduce
    1. step1: create a downloadable product
    2. step2:order more than1 qty, and then generate invoice of only 1 then check at customer end in downloadable products grid

### Expected result:
available downloads should come according to invoiced qty only 
### Actual result
https://prnt.sc/ubys0c-ordered 5,invoiced 1
customer has already downloaded 3 qty - https://prnt.sc/ubyrvf

**Comment by bhanu-webkul** [comment]
As well  as on cancelling 1qty out of them status should not changed to expired

**Comment by vaishaliwebkul** [comment]
this bug still able to reproduce, need to be fix
