### ISSUE TITLE
Duplicate Order number getting generated when placed order simultaneously 

### ISSUE THREAD

**Issue by rahulanand77** [bagisto/bagisto#3902]
# Bug report

### Title
**Place order from 2 different users at the same time generating the same order number**

### Issue Description
**Place orders from 2 different machines or browsers at the same time. In the sale season, people will place orders simultaneously. Bagisto is generating the same order number for the customers.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version. - 1.2.0
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Browse the website from 2 different machines
    2. Add item into cart.
    3. Place the order at the same time from both of the machines.

### Expected result
**Both users must get different Order ID's**

*   [Screenshots, logs or description]
![Bagistor-order-bug](https://user-images.githubusercontent.com/363711/92310225-e5bc2880-efc9-11ea-9274-008ce463ef98.png)
s or description]

### Actual result

>    **Same order number got generated for 2 different customers.**

**Comment by rahulanand77** [comment]
Hi Webkul Team,

This is not a solution, which you have provided. This has yielded another issue. Now, if we are placing an order from multiple devices at the same time, only 1 device gets success and all other devices are getting "Something went wrong" and the place order button will remain "disabled" after that on other devices. I have to reload the page to place the order again.

![Screenshot_20200907-234110](https://user-images.githubusercontent.com/363711/92411247-abd35980-f164-11ea-9077-72d471a4138b.jpg)

**Comment by rahulanand77** [comment]
Hi Webkul,

Any update on the issue? This issue is very critical for those eCommerce websites, which is receiving a good volume of orders.

**Comment by rahulanand77** [comment]
Hi @devansh-webkul ,

The loop which you have added it absolutely wrong code. It is trying for 30 seconds even the order is created in 5 seconds. The do, while loop is not the solution for this issue. I am really disappointed that we are getting a workaround not a solution for the issue.

**Comment by devansh-webkul** [comment]
Hi @rahulanand77 ,

Already added return statement in the loop. So if order is placed in 5 seconds then it won't go for 30 seconds. This PR is still in testing phase.

**Comment by rockgold22** [comment]
Hi @devansh-webkul 
Any update on same, i am having the same issue any idea, when this patch is rolling out ?

**Comment by devansh-webkul** [comment]
Hi @rockgold22,

This PR is still in the testing phase well needs to check some parameters and adjusting. Whether it wants to rely on certain attempts or PHP timed out scripts.

**Comment by rockgold22** [comment]
> Hi @rockgold22,
> 
> This PR is still in the testing phase, well needs to check some parameters and adjusting. Whether it wants to rely on certain attempts or PHP timed out scripts.

hi @devansh-webkul any update, Just wanted to know if it still is in the testing phase or ready to roll out? please let me know.

**Comment by devansh-webkul** [comment]
Hi @rockgold22,

This PR is still in the testing phase. Well if you have urgent you can use this code. I have tested this on 25 threads with zero ramps uptime and its working fine.

Till now we are trying to do with different approaches also. So it will take time. Maybe this PR will not merge so currently I cannot assure you about this.

**Comment by rahulanand77** [comment]
Hi @devansh-webkul ,

Any update on the PR? it's been a month, is it still under testing? 

Also, I installed bagisto using Composer. I can't download or clone from github. What is the way to update these updates through composer? There is no guidance to update existing Bagisto using composer.

**Comment by devansh-webkul** [comment]
Hi @rahulanand77,

1. Yes, it's still in the testing phase. Well if you have an urgent requirement you can copy from my PR. I have done with both methods i.e. `recursive` and `do while` as well. Just check the last two commits.

However, I cannot assure you about this that this PR will merge or not.

2. If you have downloaded from the composer then there is a `composer.json` file. You need to update the version of the package and run `composer update`.

### Important Note: Before update please take a backup of your whole project and DB as well.

**Comment by lYesterdaYl** [comment]
Hi, I am having similar issue for 0.1.8 version. And what PR are you guys referring to?
