### ISSUE TITLE
Duplicate address

### ISSUE THREAD

**Issue by sha443** [bagisto/bagisto#3903]
# Bug report

### Duplicate address
** During each checkout, the address is duplicated.

    1. framework Version: v1.2.0-BETA1
    2. Commit id: 80bd331123bfd24b87f5926afe7f90599b14e27c

### Steps to reproduce
    1. Checkout with a new address and check save address
    2. Next time select the address and checkout
    3. Try another checkout, you'll see the address has been duplicated

### Expected result

*   Saved address should not be copied to save again.

**Comment by vaishaliwebkul** [comment]
@sha443 
It seems you are using the bagisto v1.1.2 as the reported bug is already fixed in our Beta release 1.2.0. please check here https://github.com/bagisto/bagisto/issues/2987
Take the Pull from this PR then check again.

**Comment by vaishaliwebkul** [comment]
@sha443 
Hope your query is resolved now, so closing this.

Feel free to reopen it any time.
