### ISSUE TITLE
product is not visible in datagrid when only SKU is saved

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3909]
# Bug report

### Title
product is not visible in Datagrid when only SKU is saved

### Issue Description
product is not visible in datagrid when only sku is saved

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add all the three fields ( SKU, FAMILY, PRODUCT TYPE) while create product 
    2. step2- after the redirection on edit page, go back to the product list again without saving any details

### Expected result

Product should be visible in the datagrid

### Actual result

product is not visible on datagrid in case only sku is saved

**Comment by bhanu-webkul** [comment]
Fixed in Master
