### ISSUE TITLE
Web Installer continue button is not working

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3916]
# Bug report

### Title
Web Installer continue button is not working

### Issue Description
Web Installer continue button is not working

### Preconditions

    1. framework Version- v1.2.0

### Steps to reproduce

    1. step1- download zip file
    2. step2- hit on browser

### Expected result
continue button should be work

### Actual result

![Screenshot_57](https://user-images.githubusercontent.com/43210406/92454586-491ea400-f1de-11ea-8186-9513216f0e9a.png)

**Comment by ghermans** [comment]
This seems like a local issue as i can not reproduce this on a fresh setup :

![installerIssueKnipsel](https://user-images.githubusercontent.com/1594411/92487667-d9181a00-f1ed-11ea-8c9a-18df184c4bf0.PNG)

**Comment by vaishaliwebkul** [comment]
same as https://github.com/bagisto/bagisto/issues/3848
so closing this.

**Comment by amerhamdan3** [comment]
same problem here .. is there any solutions ?

**Comment by vaishaliwebkul** [comment]
@amerhamdan3 
you can complete the setup using command  `php artisan bagisto:install ` 
or follow the step as mention here https://devdocs.bagisto.com/1.x/introduction/installation.html#install-bagisto-using-command-line
