### ISSUE TITLE
Issue in searchbar in default theme.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3917]
# Bug report

### Title
Issue in searchbar in default theme.
### Issue Description
Issue in searchbar in default theme.

### Preconditions

    1. framework Version.-1.2.0

### Steps to reproduce

    1. step1- Go to default theme.
    2. step2- upload picture to search and check the searchbar.

### Expected result
It should be same as in velocity theme

### Actual result

![Screenshot (65)](https://user-images.githubusercontent.com/45203177/92469219-141c4c80-f1f2-11ea-9b70-cde4539f1f54.png)

**Comment by vaishaliwebkul** [comment]
fixed in master
