### ISSUE TITLE
Any auth user can get all orders

### ISSUE THREAD

**Issue by megalightfm** [bagisto/bagisto#3919]

**Comment by megalightfm** [comment]
Each logged-in user who has a token regardless of his privileges can take all the user's orders.
Please fix this bug, Only the super admin can get all orders, not any auth user

**Comment by megalightfm** [comment]
Any news? I need this to be solved asap.

**Comment by vishal-webkul** [comment]
@ghermans 
Could you please mention the version because this is working fine with master branch.

**Comment by megalightfm** [comment]
hey, will you fix your bug or not? any comment on this? any news? it is extra urgent

**Comment by vishal-webkul** [comment]
@megalightfm 
I have checked this issue, It is working fine with master branch

**Comment by megalightfm** [comment]
I create a customer new customer with admin@example.com email , then login with token true with API, and after that call all orders with this api/orders?token='''''''', 
that call returns all orders ( guest users orders to)

**Comment by vishal-webkul** [comment]
Hi @megalightfm 
Please provide more information because i have checked it again but did not face any problem as you mention in your previous comment.
Also specify the Bagisto version that you have currently using.

**Comment by megalightfm** [comment]
See, I create a new customer via api. Then when I login my account via api, I can see other users' orders as well on my profile page in orders tab.
I am using 1.1.2 version of bagisto.

**Comment by ghermans** [comment]
@megalightfm as my colleagues have pointed out, this problem has been resolved in the latest version.
Therefore, we recommend to upgrade to the latest version v1.2.0

**Comment by megalightfm** [comment]
How to update to the last version, only change in composer version and composer update or another way???

**Comment by ghermans** [comment]
You can find the upgrade procedure at https://devdocs.bagisto.com/upgrade_to_latest_bagisto.html
