### ISSUE TITLE
Layout should be responsive in all cases whether its rely on user agent or not.

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#3929]
# Bug Report
As I have noticed for the mobile agent site is responsive but this should also work for web agent also.

If we start shrinking the browser screen then layout is not responsive.

# Steps To Reproduce
Just decrease the width of the browser.

# Actual Result
![Screenshot from 2020-09-11 17-30-03](https://user-images.githubusercontent.com/68321766/92923301-de2ad280-f454-11ea-9c1f-d2ed4b7f9241.png)

# Expected Result
It should be responsive.

**Comment by samer94s** [comment]
Yes that's right
I have the same issue

**Comment by devansh-webkul** [comment]
Working on carousel adjustment on media widths.
