### ISSUE TITLE
As low as is missing from category page for configurable product.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#393]
Framework Version: 0.1.3

**Comment by rahulshukla-webkul** [comment]
"As low as" will not display for simple product, it will display for configurable product & displaying for configurable product on category page.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot 8](https://user-images.githubusercontent.com/45203177/52163764-ed8c5a80-270c-11e9-83bd-8e4acadebe8f.png)
