### ISSUE TITLE
When copying a product, replicating the image causes it to be volatile.

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#3932]
After you copy a product, the image record is replicated so the original and copy share the same path. The original product's image becomes destroyed when updating the image in the copy.

### Preconditions
Standard installation

    1. framework Version 1.2.0

### Steps to reproduce

    1. Create a product and upload an image.
    2. Copy the product.
    3. Change the image of the copy by uploading a new image.
    4. Save the copy

### Expected result
The original product and the copied product should have two different images.

### Actual result
The copied product has the newly uploaded image, but the original product has a broken image link.

By replicating the image record in product_images table from the original to the copy, the upload image routine deletes the image from the original when uploading a new image to the copy. Instead of simply replicating the table entry, the image should be copied to a new location based on the typical storage schema and a new image record should be created.

The following changes to Webkul/Product/src/Repositories/ProductRepository.php near line 701 appears to work:

```
+++                $originalImage = substr( $image->path, strrpos( $image->path, '/' ));
+++                $newImage = 'product/' . $copiedProduct->id . $originalImage;
+++                Storage::copy( $image->path, $newImage );
+++                $copiedProduct->images()->create( [ 'path' => $newImage  ] );
---                $copiedProduct->images()->save($image->replicate());
```

The storage facade needs to be pulled in for this to work.

**Comment by vaishaliwebkul** [comment]
getting an exception when remove image or video from the copy product then view the original product in frontend 
![Screenshot_137](https://user-images.githubusercontent.com/43210406/100053555-4aa75200-2e46-11eb-9d11-d75fea5513c6.png)

**Comment by vaishaliwebkul** [comment]
@richmondnursery 
now separate directory is created for storing copy product media, please check and update your code with the master branch.

feel free to reopen if the issue still exists.
