### ISSUE TITLE
getting exception when login with social icons eg. facebook, linkdin

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3933]
# Bug report

### Title
getting exception when login with social icons eg. facebook, linkdin

### Issue Description
getting exception when login with social icons eg. facebook, linkdin

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- login via facebook or linkdin

### Expected result

When customer login by adding product into cart or without having any product into cart in both case it should work

### Actual result

![Screenshot_68](https://user-images.githubusercontent.com/43210406/93051430-17945580-f682-11ea-8748-beed0478bc04.png)

**Comment by vishal-webkul** [comment]
Working fine
