### ISSUE TITLE
Category page returning page 404

### ISSUE THREAD

**Issue by Flavius96** [bagisto/bagisto#3937]
Hi,

When I try to get to category page the site is returning 404 page and I don't understand why, the category appears in menu and is active.
I have a root category called Test and the child is named Test 1 and the 404 page appears if I go on the parent or the child, same error page.

![image](https://user-images.githubusercontent.com/8420464/93322492-0a12d300-f81c-11ea-89f4-c6b7abafc291.png)

I don't have htaccess in the root of site, I go on the site with domain.com/public/

Thank you!

**Comment by vaishaliwebkul** [comment]
@Flavius96 
could you please show the screenshot of that place from where you have clicked on the category called "Test1" .

**Comment by Flavius96** [comment]
![image](https://user-images.githubusercontent.com/8420464/93325763-798ac180-f820-11ea-9482-045393d764e0.png)

**Comment by Flavius96** [comment]
It works now, I set up a root category in channel called Products and Test is the child of Products, and Test 1 is the child of Test.
Is necessary to have a root category in default channel?

**Comment by vaishaliwebkul** [comment]
@Flavius96 
Yes, if you are having an multiple category on root level then you should first select that category in the channel.

**Comment by Flavius96** [comment]
@vaishaliwebkul thank you!
