### ISSUE TITLE
Third level of categories

### ISSUE THREAD

**Issue by Flavius96** [bagisto/bagisto#3939]
Hey,

I added a category on third level of tree (skipping root category which not appear on the site), [root] -> parent -> child 1 ->child 2, when I try to access the child 2 returns 404 page, url: parent/child-1/child-2, and if I remove parent from the url it works and I don't understand why.
My current website has 3 levels of caterogies and I use for testing the first/default theme.
I checked the table, in db, called categories_translation and in the collumn called url_path is inserted a link consisting from 2 pieces for child 2: child-1/child-2, missing the parent.

Thank you!

**Comment by vaishaliwebkul** [comment]
@Flavius96 
could you please mention the bagisto version so that we can check the issue.

**Comment by Flavius96** [comment]
@vaishaliwebkul is version 1.2.0, recently I downloaded it

**Comment by vaishaliwebkul** [comment]
@Flavius96 
It's working fine please see this https://prnt.sc/uiwmic, here when I clicked on the 3rd level category in the URL parent-> child -> subchild slug is correctly passed, backend category structure https://prnt.sc/uiwojk .

**Comment by Flavius96** [comment]
Maybe the path is not saving correctly in db (in collumn url_path).
I need something to set to access the child 2? What are the neccesary settings for this to work? 
Is very weird, I try to access child 2 and don't work, only if I delete the parent.
![image](https://user-images.githubusercontent.com/8420464/93473248-76660300-f8fe-11ea-8e61-3fa879490072.png)

**Comment by bhanu-webkul** [comment]
@Flavius96 
As Vaishali has mentioned user is able to access child2 and as per your concern you can access child 2 until its immediate parent category's slug is not removed from url.
