### ISSUE TITLE
bagisto:install defines APP_URL to localhost by default

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3940]
# Bug report

### Issue Description
**bagisto:install** defines APP_URL to localhost by default. 
 https://github.com/bagisto/bagisto/blob/e0940edbb4eb50ea2e04244819457d438c291494/packages/Webkul/Core/src/Console/Commands/Install.php#L96

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Bagisto v1.2.0

### Steps to reproduce
1. Run the command **bagisto:install** and complete the installation.
2. Open .env and verify **APP_URL**.

### Expected result
A question should be asked what the env_url should be.

**Comment by vaishaliwebkul** [comment]
@ghermans 
It's working now.

Thanks.
Feel free to reopen the issue anytime.
