### ISSUE TITLE
Key generate command is missing when someone already have .env file

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#3953]
# Bug Report

### Title
The key generate command is missing when someone already have .env file

### Issue Description
`php artisan key:generate` command is missing, when user already have `.env` file. Let's say I am Laravel Developer and I know that, we need to create `.env` file. Then after hitting `php artisan bagisto:install`. I need to manually hit `php artisan key:generate`.

### Preconditions
    1. Master.

### Steps To Reproduce
    1. On fresh setup create `.env` file.
    2. Then run `php artisan bagisto:install`

### Expected Result
   1. `php artisan key:generate` command should be there.

### Actual Result
   1. Key is not generating.

**Comment by ghermans** [comment]
I just tried to reproduce this issue but it directly works on my end

```sh
vagrant@homestead:~/bagisto$ php artisan key:generate
Application key set successfully.
```

**Comment by devansh-webkul** [comment]
@ghermans,

It seems like you have manually entered the command. Just try to run 'php artisan bagiso:install'.

**Important Note**: `.env` file should be present. For e.g. if I take a clone of a fresh project, the first thing developer always does is either taking a copy of '.env.example' or run `composer install`. So if I take a copy of `.env.example` and renamed it as `.env` and filled all required parameters. Still, the key generate command will left.

The main motive is that `php artisan key:generate` command should be present in `bagisto:install` whether `.env` present or not.
