### ISSUE TITLE
Featured New Product Adding Special Price the 2 columns in mobile version is broken

### ISSUE THREAD

**Issue by trsihiadev** [bagisto/bagisto#3954]
In the Featured product or new product.

Adding special price to a product or prormo price the mobile version of 2 columns are not even or the result is broken, the other column is being cut out .

Try to add new product and add special price for you to see the results

Thank you

**Comment by trsihiadev** [comment]
With special price
![Uploading Screenshot at Sep 22 14-40-09.png…]()
without special price
![Uploading Screenshot at Sep 22 14-42-37.png…]()

**Comment by vaishaliwebkul** [comment]
@trsihiadev 
media is getting broken, please attach a valid screenshot.
also mention the bagisto version.

**Comment by trsihiadev** [comment]
Version v1.2.0. Downloaded directly from bagisto not in Github

With special price
<img width="412" alt="Screenshot at Sep 22 14-40-09" src="https://user-images.githubusercontent.com/34658417/93852486-ad645c00-fce4-11ea-81a2-a9f07f7b2dc1.png">

without special price. 
<img width="409" alt="Screenshot at Sep 22 14-42-37" src="https://user-images.githubusercontent.com/34658417/93852555-cbca5780-fce4-11ea-973a-3de31b7dbf50.png">

**Comment by vaishaliwebkul** [comment]
@trsihiadev 
Thanks for reporting this we will fix this soon.
Also there is a carousel, so you may slide the products to see the next item.

**Comment by kniferdev** [comment]
Yes, I have slide which is working. The only problem I've encountered, adding special price it will break the mobile version 2 columns ..

**Comment by trsihiadev** [comment]
Yes, the only problem I had mobile version 2 columns was broken. Slide is working fine.

**Comment by trsihiadev** [comment]
Hey, Id fork it and request a PR. just wondering if , I did it correctly? I am new to github. Thank you

**Comment by vaishaliwebkul** [comment]
@trsihiadev 
Yes, first fork a bagisto github repo as you already did https://github.com/trsihiadev/bagisto, next clone this repo and all is ready to do the changes into your local system.
for more details you may follow these guidelines https://opensource.com/article/19/7/create-pull-request-github

**Comment by trsihiadev** [comment]
I did that already but it seems, there is no changes. 

Can you give me the final zip files because my client is urging me to deploy his website. 

When I clone the repo into my local system. still the width:  9rem is in comment.

in this fixed I saw it is uncommented out.
https://github.com/bagisto/bagisto/pull/3960/commits/c437cb0ba917db5c8218c747e9c6972d05af6cbf


All i need is the ziz which has already with the merged of changes. 


Thank you

**Comment by trsihiadev** [comment]
*updated zip. Thank you

**Comment by trsihiadev** [comment]
.product-card-view
//19 rem;

The repo I have on my local computer..

**Comment by trsihiadev** [comment]
oh, I got it working now. Thank you

**Comment by vaishaliwebkul** [comment]
@trsihiadev 
Thanks for the update.

Feel free for any further query!
