### ISSUE TITLE
Show detail variant of product type configurable (with theme velocity)

### ISSUE THREAD

**Issue by nguyenthanhtuanIT** [bagisto/bagisto#3956]
# Bug report

### Title
- Error: Undefined offset: 0. When click to show detail **variant** of product type configurable in home page (theme velocity)
### Issue Description
- With role admin, when we created product with type "configurable" and variants (_not add image_). Then we go to home page in velocity theme and click variants created. final, errors appear **Undefined offset: 0** 
### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version we are using is 1.2.0.
    2. Commit id.

### Steps to reproduce

1-create a configurable product 
2-edit any variant of this product like simple product and do not upload image
3-then search same variant on front end 
4-and click on product to view that

### Actual result
 **Tell us what happens instead.**
![Screenshot from 2020-09-22 15-28-30](https://user-images.githubusercontent.com/35143673/93860554-75134c80-fce9-11ea-99d9-9d812ec22e4b.png)

**Comment by vaishaliwebkul** [comment]
@nguyenthanhtuanIT 
Thanks for reporting this.

I verified this and working now, so closing this.

Feel free to reopen it anytime.
