### ISSUE TITLE
pay with paypal smart button is missing in checkout

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3964]
# Bug report

### Title
pay with paypal smart button is missing in checkout

### Issue Description
pay with paypal smart button is missing in checkout

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- configuration-> sales-> paypal smart button configuration enabled
    2. step2- go to the checkout page and select paypal smart button

### Expected result

pay with Paypal button should be visible in checkout

### Actual result

![Screenshot_4](https://user-images.githubusercontent.com/43210406/94110842-e0335f00-fe60-11ea-8f8c-d7b1e1a485f8.png)

**Comment by bhanu-webkul** [comment]
fixed in master
