### ISSUE TITLE
Trying to get property of non object.

### ISSUE THREAD

**Issue by JESUDAWN** [bagisto/bagisto#3967]
Please how do I solve this bug?

trying to get property 'default_locale' of non-object.

This is located in bagisto/packages/webkul/shop/src/http/middleware/locale.php file, in line 
44 

[app()->setLocale(core()->getDefaultChannel()->default_locale->code);]

Please help.
My LORD JESUS CHRIST Bless you. Hoping you believe In HIM.

**Comment by vaishaliwebkul** [comment]
@JESUDAWN 
have you tried to changed the default locale??
Please open the shop again in incognito browser and then check.

**Comment by ghermans** [comment]
@vaishaliwebkul i think that this is indeed happening when you enable any other currency **and** disable US dollar

**Comment by vaishaliwebkul** [comment]
@ghermans 
Yes currency change will reproduce this error to as discussed https://github.com/bagisto/bagisto/issues/3038

**Comment by JESUDAWN** [comment]
> @JESUDAWN
> have you tried to changed the default locale??
> Please open the shop again in incognito browser and then check.

I tried, but I don't even understand what to do and how to.

Thanks

**Comment by vaishaliwebkul** [comment]
@JESUDAWN 
could you please show the screenshot of your error? also go to **channels->** and share the screenshot of the currency section.

**Comment by JESUDAWN** [comment]
> @JESUDAWN
> could you please show the screenshot of your error? also go to **channels->** and share the screenshot of the currency section.

Am not with my laptop now I 'II send it later, however even with my Android phone am having error too. 


Warning: mysqli::close(): Couldn't fetch mysqli in /data/data/com.termux/files/home/bagisto/public/installer/install.php on line 67

Warning: Cannot modify header information - headers already sent by (output started at /data/data/com.termux/files/home/bagisto/public/installer/install.php:67) in /data/data/com.termux/files/home/bagisto/public/index.php on line 16

Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /data/data/com.termux/files/home/bagisto/bootstrap/app.php:14 Stack trace: #0 /data/data/com.termux/files/home/bagisto/public/index.php(57): require_once() #1 /data/data/com.termux/files/home/bagisto/server.php(21): require_once('/data/data/com....') #2 {main} thrown in /data/data/com.termux/files/home/bagisto/bootstrap/app.php on line 14

**Comment by ghermans** [comment]
@vaishaliwebkul 
![ChannelKnipsel](https://user-images.githubusercontent.com/1594411/94247325-3d8ce600-ff1d-11ea-9b8c-d0ee77d0874c.PNG)

**Comment by vaishaliwebkul** [comment]
@ghermans 
for now, the error will be gone when selecting all the currency from the currencies box.

Still, this should be resolved.

**Comment by JESUDAWN** [comment]
See attached screenshot and snapped shot from my phone and laptop
respectively.

Blessed morning from my LORD JESUS CHRIST.

**Comment by JESUDAWN** [comment]
![Screenshot_20200926-105905](https://user-images.githubusercontent.com/67759019/94338238-8f4e7280-ffe8-11ea-9a1d-e0bb6d25f7a6.png)

**Comment by JESUDAWN** [comment]
I didn't. It exactly the way it came I installed it.

However, can you please show me what to do. Am a newbie to programming .

**Comment by ghermans** [comment]
@JESUDAWN this is a known issue and will be resolved.

**Comment by JESUDAWN** [comment]
Ok, patiently waiting

**Comment by vaishaliwebkul** [comment]
@JESUDAWN 
this bug is fixed now, please check

Feel free to reopen the issue if still not resolved,

**Comment by Fukitsune** [comment]
Bonjour,
J'ai un problème similaire : 
Notice: Trying to get property 'language' of non-object in D:\Dureau\Local\Shop\classes\controller\Controller.php on line 196

Fatal error: Uncaught Error: Call to a member function getLocale() on null in D:\Dureau\Local\Shop\classes\controller\Controller.php:196 Stack trace: #0 D:\Dureau\Local\Shop\classes\controller\FrontController.php(283): ControllerCore->init() #1 D:\Dureau\Local\Shop\modules\everpsquotation\controllers\front\validation.php(40): FrontControllerCore->init() #2 D:\Dureau\Local\Shop\classes\controller\Controller.php(287): EverpsquotationValidationModuleFrontController->init() #3 D:\Dureau\Local\Shop\classes\Dispatcher.php(518): ControllerCore->run() #4 D:\Dureau\Local\Shop\index.php(28): DispatcherCore->dispatch() #5 {main} thrown in D:\Dureau\Local\Shop\classes\controller\Controller.php on line 196

Voici le Controller.php
`
        $localeRepo = $this->get(self::SERVICE_LOCALE_REPOSITORY);
        $this->context->currentLocale = $localeRepo->getLocale(
            $this->context->language->getLocale()
        );`

Et voici le fichier Language.php
`    /**
     * @return string return the language locale, or its code by default
     */
    public function getLocale()
    {
        return !empty($this->locale) ?
            $this->locale :
            $this->language_code;
    }`

Savez-vous pourquoi il ne retourne rien ?

Bien à vous

Cordialement
