### ISSUE TITLE
Flash notification reappears when clicking back button in Admin interface or Chrome browser

### ISSUE THREAD

**Issue by HuynhHungManh** [bagisto/bagisto#3968]
# Bug report

### Title
**Flash notification reappears when clicking back button in Admin interface or Chrome browser**

### Issue Description
**When add/edit/delete the product successfully then go to product create/edit page and click back button, flash notification appears.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: v1.2.0 (on https://demo.bagisto.com)

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Go to admin site
    2. Go to Catalog > Product > Add product
    3. Fill out the required information and click save product (add the product successfully)
    4. Click add Product button (go to add Product page)
    5. Click back button

### Expected result

*   Flash notification not displaying after click back button

### Actual result

>    **Flash notification reappears for the second time after click back button.**

![flash-message](https://user-images.githubusercontent.com/18205279/94233905-e3971b00-ff32-11ea-8ba4-519332941fe2.png)

### Reason
Use `history.go (-1)` method so when clicking back it doesn't reload the page but loads data from disk cache of chrome browser.

### Suggest fixing
Use `window.location = document.referrer` instead of `history.go (-1)`.

```
<i class="icon angle-left-icon back-link" onclick="history.length > 1 ? history.go(-1) : window.location = '{{ route('admin.dashboard.index') }}';"></i>
```
to
```
<i class="icon angle-left-icon back-link" onclick="history.length > 1 ? window.location = document.referrer : window.location = '{{ route('admin.dashboard.index') }}';"></i>
```
or
```
<i class="icon angle-left-icon back-link" onclick="window.location = history.length > 1 ? document.referrer : '{{ route('admin.dashboard.index') }}'"></i>
```

This suggestion isn't the most optimal, but I hope to help the bagisto community.

**Comment by autn** [comment]
I agree with you, I have the same issue when edit or delete content. I saw your PR and I think it's a good solution.

**Comment by vaishaliwebkul** [comment]
@HuynhHungManh 
Verify it and it's working now.

Thanks
