### ISSUE TITLE
Not getting logo on invoice, getting broken link on saving logo.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3969]
# Bug report

### Title
Not getting logo on invoice, getting broken link on saving logo.
### Issue Description
Not getting logo on invoice, getting broken link on saving logo.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-1.1.1

### Steps to reproduce
    1. step1- Save logo for invoice slip
    2. step2-Print invoice

### Expected result
Logo should display on invoice

### Actual result
![Workspace 1_392](https://user-images.githubusercontent.com/45203177/94260192-58774e80-ff4d-11ea-829e-b00a911a5d0e.png)

![download (35)](https://user-images.githubusercontent.com/45203177/94260254-75ac1d00-ff4d-11ea-8d14-a8a8bceb3aa5.png)

**Comment by bhanu-webkul** [comment]
Hi @jyoti-webkul  This issue has been fixed in master.

**Comment by jyoti-webkul** [comment]
ok
