### ISSUE TITLE
Increase the length of the box on Product page and review page so that text appears clearly.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#397]
Framework Version: 0.1.3
![screenshot 48](https://user-images.githubusercontent.com/45203177/50375011-dee65a00-061c-11e9-864b-b7f811c20a2e.png)

**Comment by prashant-webkul** [comment]
This issue is fixed as whole datagrid had been refactored.

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Fixed
![Screenshot from 2019-03-20 14-33-43](https://user-images.githubusercontent.com/45203177/54672044-382b3000-4b1d-11e9-9ca7-57a4b3f2f524.png)
