### ISSUE TITLE
Getting question mark symbol instead of currency symbol in invoice pdf for currency BDT (Taka).

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3970]
[invoice-25-09-2020 (2).pdf](https://github.com/bagisto/bagisto/files/5282404/invoice-25-09-2020.2.pdf)

**Comment by ghermans** [comment]
@devansh-webkul isn't this related to the same issue that we had with invoices in arabic?

**Comment by ghermans** [comment]
@jyoti-webkul  are you using the latest version of the master branch?

**Comment by devansh-webkul** [comment]
@ghermans I guess this issue has already been fixed.

**Comment by jyoti-webkul** [comment]
> @jyoti-webkul are you using the latest version of the master branch?

I am using 1.1.2 version

**Comment by ghermans** [comment]
@jyoti-webkul can you please verify this with the master branch (version 1.2.0), as we think that this issue has already been resolved.

**Comment by ghermans** [comment]
Closing this one since there has been no response for 25days.
