### ISSUE TITLE
Event checkout.cart.add.after should provide added product instead of full cart

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#3971]
### Title
Event checkout.cart.add.after should provide added product instead of full cart

### Issue Description
When adding and item to the cart, the Event checkout.cart.add.before sends the product ID of item being added.
When the Event checkout.cart.add.after is dispatched, the full cart is sent, not the product added. 

### Preconditions

    1. framework Version - 1.2.0

### Steps to reproduce

    1. Add item to Cart
    2. Listen for checkout.cart.add.after event

### Expected result
The associated product that has been added should be dispatched with the event.

### Actual result
The entire cart is dispatched with the event instead of the item just added.

Since the process of adding a product to a cart is dependant on the product, it would be expected the checkout.cart.add.after dispatches similar data to checkout.cart.add.before. Having the entire cart returned makes it difficult to watch for a particular product successfully added to the cart. If one needs the full cart, the Event checkout.cart.collect.totals.after sends the complete cart and is called during the Cart::addProduct function and would seem to be the appropriate event to listen for when the full cart is required. 

I would suggest the following change to packages/Webkul/Checkout/src/Cart.php on line 189:
```
-- Event::dispatch('checkout.cart.add.after', $cart);
++ Event::dispatch('checkout.cart.add.after', $parentCartItem);
```

(Note: This change is present in the Webkul/PreOrder add-on module but it would seem appropriate as part of the master.)

**Comment by jitendra-webkul** [comment]
Hi @richmondnursery 

We can not change event data because there are some custom solutions that are listening to this event and expecting cart in return. You can get the product id with the request() helper function.
