### ISSUE TITLE
Response issues in APIs

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#3973]
# Bug report
There are some issues in API.

### Issue Description

While writing the documentation, I came to know the following points,

1. Whenever I re-register the user with the same email address. It's giving me the error.
2. In cart checkout update API, if the cart item is not present then still it gives the success message that the cart has been updated successfully.
3. I noticed in some routes whenever there is a case of sending the forbidden or error response instead of that it gives the real error.
4. Even if I send some invalid JSON, it's giving the exception error whereas it needs to give the invalid JSON type error.

### Preconditions

    1. Framework Version: Master

### Steps to reproduce

    1. Register the user in which emails have already been taken.
    2. For cart, add the item to the cart by API then update the cart with the different cart item id.

### Expected result

    1. If this is an API request then all error should be in API response with a valid status code.

#### 1. I have sent some invalid JSON, notice the `qty` in the request. This request should be converted to bad request rather than 500.
![Screenshot from 2020-09-28 11-56-55](https://user-images.githubusercontent.com/68321766/94397613-d4f27300-0181-11eb-9146-783939878877.png)

#### 2. Registering customer with an already registered email address, 
![Screenshot from 2020-09-28 11-38-25](https://user-images.githubusercontent.com/68321766/94397136-ce173080-0180-11eb-9bb1-bfb024fabb2f.png)

#### 3. When I am unnecessarily hitting logged out API,
![Screenshot from 2020-09-28 11-38-48](https://user-images.githubusercontent.com/68321766/94397137-d0798a80-0180-11eb-93dd-739e095cb5ac.png)

**Comment by devansh-webkul** [comment]
Fixed in master.

**Comment by mandar238** [comment]
2. Registering customer with an already registered email address,? I am facing the same issue may i know the solutions
