### ISSUE TITLE
No validation message shown on updating customer profile page

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#3974]
# Bug report

When I am trying to update a customer with API and I am not filling the required parameters. Then, it gives me the user details instead of the validation error message.

- If somehow I am able to update the profile. It gives me the message for account creation instead of account updation,

    ![Screenshot from 2020-09-28 14-14-15](https://user-images.githubusercontent.com/68321766/94410438-0163ba80-0195-11eb-849f-3e9f8e348b11.png)

### Preconditions

    1. Framework Version: Master

### Steps to reproduce

    1. Try to update the customer profile with API.

### Expected result

   1. If I am not filling the required parameters then it should give me the validation error message with proper status code.
   2. Update message should be shown.

**Comment by JunaidJaved8461** [comment]
@devansh-webkul @ghermans Please review my this pull request!! Thanks

**Comment by JunaidJaved8461** [comment]
@devansh-webkul Have you reviewed my pull request!! If You are reviewing yet then let me know when it will be done

**Comment by devansh-webkul** [comment]
Hi @JunaidJaved8461,

Please check your PR, I already reviewed that yesterday.

**Comment by devansh-webkul** [comment]
Hi @JunaidJaved8461,

Please, check this https://github.com/bagisto/bagisto/pull/4009#issuecomment-706038340.

**Comment by devansh-webkul** [comment]
@JunaidJaved8461,

Please check you PR, just small changes needed from your side.
