### ISSUE TITLE
Add product number

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3978]
As already discussed with Saurav, a `product number` field should be added under `products` and admins should be able to filter products based on the product number.

**Comment by Anoop01234** [comment]
Can you guide me what am I suppose to do?

**Comment by ralphlagumen** [comment]
Let me help on this.

**Comment by ghermans** [comment]
Currently we only can add a SKU number to Bagisto

But for example if you want to add a new product like Macbook pro, then you will have to enter the correct product number
because there are many macbook pro's

![exampleKnipsel](https://user-images.githubusercontent.com/1594411/95974013-aa0c4e00-0e14-11eb-89ba-2d5743adb4d4.PNG)

**Comment by bhanu-webkul** [comment]
automatically new product number should be generated on copying product like sku,name and url.
