### ISSUE TITLE
Lots of fake accounts has been created in my website.

### ISSUE THREAD

**Issue by akshaypitale** [bagisto/bagisto#3982]
Hi There,

Lots of fake accounts are getting generated on my website.
The one who is doing this maybe is bots because of below 2 reasons.
1) I disabled the registration page but still, fake registrations are showing up.
2) The time difference between Get and Post request of customer/registration page is 2-3 seconds which is not human behavior.

I tried using captcha V2 but it not stopping the fake registrations.
Note:- I don't want to use social media login or otp confirmation features.

Is there any way I can stop this registration?

Thanks in advance

**Comment by vaishaliwebkul** [comment]
@akshaypitale 
could you please provide your website URL?

**Comment by devansh-webkul** [comment]
@akshaypitale,

Captcha V2 is fine. Maybe the problem is coming from the API. Did you disable the register route in API?

**Comment by akshaypitale** [comment]
> @akshaypitale,
> 
> Captcha V2 is fine. Maybe the problem is coming from the API. Did you disable the register route in API?

No.

**Comment by akshaypitale** [comment]
> @akshaypitale
> could you please provide your website URL?

**Comment by akshaypitale** [comment]
> @akshaypitale
> could you please provide your website URL?

https://naturaltilestone.co.uk/

**Comment by devansh-webkul** [comment]
@akshaypitale,

I am able to register my account via. API. You just need to disable the registered route via API. In `API` routes just comment the customer's register route.

![Screenshot from 2020-10-01 11-05-43](https://user-images.githubusercontent.com/68321766/94771987-39a60b80-03d6-11eb-9653-3dd76957d8a0.png)

**Comment by akshaypitale** [comment]
> @akshaypitale,
> 
> I am able to register my account via. API. You just need to disable the registered route via API. In `API` routes just comment the customer's register route.
> 
> ![Screenshot from 2020-10-01 11-05-43](https://user-images.githubusercontent.com/68321766/94771987-39a60b80-03d6-11eb-9653-3dd76957d8a0.png)
> 
Thanks for the reply. 
But it can't be API because I checked the access logs where it shows at the time of fake registrations there is get request on `customer/register` and after 2-3 seconds there is post request on the same route.

**Comment by devansh-webkul** [comment]
@akshaypitale,

It's look like google captcha V2 has not been integrated properly. I am able to register the user without verifying the robot section.

Please check the integration as well.

**Comment by akshaypitale** [comment]
> @akshaypitale,
> 
> It's look like google captcha V2 has not been integrated properly. I am able to register the user without verifying the robot section.
> 
> Please check the integration as well.

@devansh-webkul thanks for the reply.
I have not integrated captcha V2. I will observe registrations a couple of days for a fake account.

Thanks again for the help.

**Comment by devansh-webkul** [comment]
@akshaypitale,

Well, this is not the problem with the code. To avoid spamming and bots google captcha are used but in your case captcha v2 has not been integrated properly, please check your integration.
