### ISSUE TITLE
same event fired two times one on customer edit page and other in general blade 

### ISSUE THREAD

**Issue by asif-webkul** [bagisto/bagisto#3983]
bagisto -1.2.0
same event fired two times one on customer edit page and other in general blade 

step-1
add the customer document module
step-2
edit the customer in admin panel

bagisto.admin.customer.edit.after -- getting my view render two times as i am using the event to add more columns two the edit page of customer

**Comment by vaishaliwebkul** [comment]
@asif-webkul 
this is fixed now in master so closing this.
