### ISSUE TITLE
Cart has limit of maximum of 100 million. This   is the max amount it displays when cart amount greater than 100                                                  millions.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#3984]
You can reproduce this issue by creating two products with total price of more than 100 millions of the selected currency.

![screenshot-bagisto uvdesk com-2020 09 30-14_10_19](https://user-images.githubusercontent.com/45203177/94662958-bc6f8d80-0326-11eb-90a7-e49ac245c872.png)

**Comment by masoudmoghaddari** [comment]
Hi Jyoti,
Thanks for creating this issue for my report.
I found out that the problem goes back to database structure. The the "base_grand_total" column in "Cart" table has 'decimal(12,4)' datatype, which is causing the limit.
I am able to solve this issue for my project by modifying the migration of this table, however I think this should be resolved for some other fields too in future releases.
Thanks again
![dataType](https://user-images.githubusercontent.com/59832132/94670160-0eacb080-031f-11eb-8935-4bb6ea6ce238.png)

**Comment by Boorinio** [comment]
It's not just cart, it's invoices, products table etc. I just made a pull request for it.

**Comment by dejavuejs** [comment]
Decimal(24,12) is the current format for currency columns. And current limit is way more than any payment gateway accept payments.

**Comment by masoudmoghaddari** [comment]
I fixed it manually in my project by changing the database migrations. Decimal(24,12) may be enough for USD or Euros, but there other currencies that may exceed that limit. I personally was working on Iranian Rials and 100,000,000 was not anywhere near enough.

**Comment by devansh-webkul** [comment]
Hi,

Well, this is a requirement that is up to the developer. Well in normal cases the current migration can work. MySQL database structure can be altered later also if users feel that now it's time for updating the table structure. Because 24, 12 in the starting phase not needed.

**Comment by devansh-webkul** [comment]
I am removing the bug label as this is the requirement which can be scaled according to users' need.

**Comment by devansh-webkul** [comment]
There should be some feature in admin, to give the user the ability to scale this according to their need. But don't know whether it's good or bad but altering can be done on a user prompt basis as well.

**Comment by devansh-webkul** [comment]
Closing this issue as this issue can be scale according to user needs.
