### ISSUE TITLE
slider path should also work in default theme 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#3987]
As velocity theme, on clicking on slider customer should get redirected to given slider path in slider

**Comment by vaishaliwebkul** [comment]
@jaseelbavu 
this is not working as expected, while clicking on slider image, the path is added to the URL instead of redirected to link

![Screenshot_17](https://user-images.githubusercontent.com/43210406/95330631-70908b80-08c6-11eb-91ae-58a79897d665.png)

**Comment by jaseelbavu** [comment]
Hi @vaishaliwebkul,
I think you are adding the full url. You only need to add the required url segments in slider path.

**Example**
By clicking the slider image you need to redirect to http://localhost:8800/customer/login. Adding only _customer/login_ in slider path will solve this issue. 
Please check it. Thank you.

**Comment by vaishaliwebkul** [comment]
@jaseelbavu 
slider path is not restricted to add the only specific routes into the URL, instead of it, we can redirect the website from the slider to the particular link or any website as well likewise Velocity theme.

**Comment by jaseelbavu** [comment]
@vaishaliwebkul 
Oh i didn't know that, let me check on that. Thanks for the info.

**Comment by vaishaliwebkul** [comment]
@jaseelbavu 
still, I am getting the same issue, please put any link in slider path like https://bagisto.com/en/ then when you click on slider it should redirect to the https://bagisto.com/en/ link

you may also check this https://www.loom.com/share/245a26b0463a4d90a46f2560629e0c07

**Comment by jaseelbavu** [comment]
Hi @vaishaliwebkul 
It is working as expected for me. Please check it again.

Please have a look.
https://www.loom.com/share/5ca46504997b4990ad08bc9a96f959ad

**Comment by jaseelbavu** [comment]
@vaishaliwebkul 
I got the issue, I completely forgot to run the npm production command. Apologies for that. I hope everything will work as expected after this. Thank you.

**Comment by vaishaliwebkul** [comment]
@jaseelbavu 
It's working now.
Thanks.
