### ISSUE TITLE
is the master branch most updated branch ?

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#3991]
actually my question is simple i pulled bagisto while ago i did lots of changes and now i want to update the bagisto but keep my changes so i want to pull the most updated branch and resolve the conflicts . i dont know how possible is that but i want to give it a try so i wanted to know what is the most updated branch on your git now . does master branch has all the latest changes ?? thanks in advance for this great product

**Comment by ghermans** [comment]
The master branch is always up-to-date.
