### ISSUE TITLE
add support svg logo

### ISSUE THREAD

**Issue by CrazyBoy49z** [bagisto/bagisto#3993]
Svg logo not support The "Logo Image" field must have a valid file type

**Comment by vaishaliwebkul** [comment]
@CrazyBoy49z 
currently, the SVG extension is not allowed, if you want to allow this extension type then go to the file https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Admin/src/Config/system.php#L124 and add SVG support.

**Comment by CrazyBoy49z** [comment]
![image](https://user-images.githubusercontent.com/3448603/97268763-0ddf3f80-1835-11eb-8e82-163f3e189a81.png)
Not work in admin dashboard

**Comment by CrazyBoy49z** [comment]
> @CrazyBoy49z
> currently, the SVG extension is not allowed, if you want to allow this extension type then go to the file https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Admin/src/Config/system.php#L124 and add SVG support.

Thanks

**Comment by devansh-webkul** [comment]
Hi @CrazyBoy49z,

Please check this PR `https://github.com/bagisto/bagisto/pull/4106`. I have added support for the `.webp` extension everywhere. You can use the exact same replica and just add your extension there.
