### ISSUE TITLE
Adding special price both mobile and desktop version are broken

### ISSUE THREAD

**Issue by knif3rdev** [bagisto/bagisto#3995]
Version master

Mobile and desktop version  adding special price will break the display

It should be even and the display of each images in mobile version are broken too. What is exactly the size of the product thumbnail? 

Adding special price
<img width="1298" alt="Screenshot at Oct 04 21-50-22" src="https://user-images.githubusercontent.com/34658417/95017573-b5c97900-068c-11eb-8579-dfdf7f50f806.png">

Thumbnail for multiple images is not responsive
![mobile-version](https://user-images.githubusercontent.com/34658417/95017696-77808980-068d-11eb-8863-4d90e38526ed.jpg)
![mobiler version 2](https://user-images.githubusercontent.com/34658417/95017698-794a4d00-068d-11eb-8250-b285494a0e60.jpg)

![mobile -version 3](https://user-images.githubusercontent.com/34658417/95017715-94b55800-068d-11eb-8baf-c9b91390a842.jpg)

**Comment by trsihiadev** [comment]
CURRENCY CODE causing this issue. I have issue posted here. In order this to be fix is to fix the currency symbol to display properly not the currency code.

**Comment by trsihiadev** [comment]
But the multiple thumbnail in the mobile version still a problem. It is not responsive.

**Comment by trsihiadev** [comment]
The only fix of this is to correct the currency symbol to display properly. Causing the issue is the currency code that being display. Try to change into USD currency it will display properly. I hope they can fix it ASAP

**Comment by vaishaliwebkul** [comment]
@knif3rdev 
the bug is verified and fixed., you may take the pull from the master branch and then check.


Feel free to reopen the issue anytime.
