### ISSUE TITLE
Wrong validation message on entering non numeric data in rate while creating tax rate

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4021]
# Bug report

### Title
Wrong validation message on entering non numeric data in rate while creating tax rate

### Preconditions
    1. framework Version.Master
### Steps to reproduce
    1. step1: create tax rate and enter any character in rate field 

### Expected result:
The "Rate" field must be numeric and may contain decimal points

### Actual result
https://prnt.sc/uur63u

**Comment by g1dra** [comment]
Hi. Can you assign it to me?

**Comment by vaishaliwebkul** [comment]
Resolved in master.
