### ISSUE TITLE
filter issue in cart rule & product grid

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4023]
# Bug report

### Title
filter issue in cart rule & product grid

### Issue Description
1. when select any channel inside product grid then selected value is not set in the filter dropdown.
2. In cart rule grid selected channel, customer group filters are not selected

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- go to the product grid and select the channel( channel should be selected in drop down as well)
    2. step2- go to the cart rule and filter based on customer group/channel( both value should be selected)

### Expected result
value which is passed in the URL should also selected in the dropdown

### Actual result

![Screenshot_19](https://user-images.githubusercontent.com/43210406/95338248-5fe51300-08d0-11eb-9bab-660de05f3ade.png)

![Screenshot_20](https://user-images.githubusercontent.com/43210406/95338286-67a4b780-08d0-11eb-94c8-99dc97ebe9e7.png)

**Comment by paresh27** [comment]
@vaishaliwebkul , I am interested in it, can you assign it to me?

**Comment by vaishaliwebkul** [comment]
fixed now in master.
