### ISSUE TITLE
customer group price discount is not applied when product price and discount amount is same

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4024]
# Bug report

### Title
customer group price discount is not applied when product price and discount amount is same

### Issue Description
customer group price discount is not applied when product price and discount amount is the same

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- edit any product, add product price $50
    2. step2- add customer group price ( all group-> 1 qty-> 50 discount)

### Expected result

according to the rule, 50% discount should be applied on product price which is then $25

### Actual result

![Screenshot_21](https://user-images.githubusercontent.com/43210406/95347146-34672600-08da-11eb-8e00-796875501f21.png)

![Screenshot_22](https://user-images.githubusercontent.com/43210406/95347170-3b8e3400-08da-11eb-8888-6d12517ca869.png)

**Comment by paresh27** [comment]
@vaishaliwebkul , I can help you with this, can you assign it to me?

**Comment by vaishaliwebkul** [comment]
fixed
