### ISSUE TITLE
Layout Issue in Product View Page in Velocity Theme

### ISSUE THREAD

**Issue by AayushBhatt-webkul** [bagisto/bagisto#4035]
# Bug report

### Layout Issue
When description or the name of a product is long enough, It breaks the layout design of the product View Page

### Preconditions

    1. Bagisto 1.2.0.

### Steps to reproduce

    1. Create a product with large description.
    2. Open Product View Page with Velocity Theme.

### Actual result

>    https://prnt.sc/uvfmgg

**Comment by vishal-webkul** [comment]
Working Fine

![image](https://user-images.githubusercontent.com/68368328/95551703-ead92100-0a28-11eb-9980-441d7f53b9b8.png)

![image](https://user-images.githubusercontent.com/68368328/95551918-57542000-0a29-11eb-8ebf-6854d4f738ce.png)

![image](https://user-images.githubusercontent.com/68368328/95551828-25db5480-0a29-11eb-95b4-832141b868f3.png)

**Comment by vaishaliwebkul** [comment]
@AayushBhatt-webkul 
It's fixed now, please check https://prnt.sc/uxouth

**Comment by vaishaliwebkul** [comment]
While adding description with paragraphs then it will show in header of default theme
![Screenshot_33](https://user-images.githubusercontent.com/43210406/95820067-0a33bf00-0d45-11eb-8040-abdd44cba2e8.png)

**Comment by vaishaliwebkul** [comment]
fixed
