### ISSUE TITLE
cann't install bagisto

### ISSUE THREAD

**Issue by yannnaingoo** [bagisto/bagisto#4036]
# Bug report

### Title
** I can not install with these command composer create-project bagisto/bagisto-standard**

### Issue Description
** Problem 1
    - Installation request for bagisto/bagisto v1.1.2 -> satisfiable by bagisto/bagisto[v1.1.2].
    - bagisto/bagisto v1.1.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 2
    - Installation request for phpoffice/phpspreadsheet 1.13.0 -> satisfiable by phpoffice/phpspreadsheet[1.13.0].
    - phpoffice/phpspreadsheet 1.13.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
  Problem 3
    - phpoffice/phpspreadsheet 1.13.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - maatwebsite/excel 3.1.18 requires phpoffice/phpspreadsheet ^1.10 -> satisfiable by phpoffice/phpspreadsheet[1.13.0].
    - Installation request for maatwebsite/excel 3.1.18 -> satisfiable by maatwebsite/excel[3.1.18].
**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by ghermans** [comment]
You need to install the PHP curl & zip extension

```
ext-curl 
ext-zip
```

**Comment by yannnaingoo** [comment]
Thanks Bagisto/Bagisto. I solved.
