### ISSUE TITLE
Responsive Issues in Velocity

### ISSUE THREAD

**Issue by AayushBhatt-webkul** [bagisto/bagisto#4042]
# Bug report

### Title
The theme is not Mobile Responsive in any locale.

### Issue Description
The layout of every page breaks when I open the site in Mobile view.

### Preconditions

    1. Bagisto version: 1.2.0.

### Steps to reproduce
    1. Open the website in Mobile View.
    2. Browse the pages

### Actual result

>    https://prnt.sc/uvj4zc

**Comment by devansh-webkul** [comment]
Work already in progress on this issue https://github.com/bagisto/bagisto/issues/3929.
