### ISSUE TITLE
Actual name is not showing on search if name contains any special character in Velocity theme

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4049]
# Bug report

### Title
Actual name is not showing on search if name contains any special character 

### Preconditions
    1. framework Version. Master

### Steps to reproduce 
    1. step1 search product name(i.e. H&M) 

### Expected result:
https://prnt.sc/uvxhe1
### Actual result
https://prnt.sc/uvx9wv

**Comment by vishal-webkul** [comment]
@bhanu-webkul 
It is working fine

**Comment by bhanu-webkul** [comment]
fixed in master
