### ISSUE TITLE
search icon in velocity theme is not clickable

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4062]
# Bug report

### Title
search icon in the velocity theme is not clickable

### Issue Description
search icon in the velocity theme is not clickable

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- click on the search icon when the term exists and click on search icon (should show the result)

### Expected result

search icon should be respond 

### Actual result
   
![Screenshot_30](https://user-images.githubusercontent.com/43210406/95602338-690de580-0a72-11eb-8389-c64c5d6bacfb.png)

**Comment by vaishaliwebkul** [comment]
@ghermans 
In version 1.2.0 this is added https://prnt.sc/uw8vn4 but now it's now working so I just raised to fix it.

As per your suggestions, we can add onfocus instead of required field here.

**Comment by jitendra-webkul** [comment]
@vaishaliwebkul , I don't think validation msg on top search would be suitable

**Comment by vaishaliwebkul** [comment]
@jitendra-webkul 
Ok required is not necessary, but the search icon should work when the user adds input to the search bar and click on the search icon to execute search query then it should show the resultant products.

**Comment by tspencer244** [comment]
I am unable to reproduce this issue. Clicking the search icon performs a search result as expected for me.

Which browser are you experiencing this issue on? Are there any errors in the browser console before or after clicking the search icon?

**Comment by devansh-webkul** [comment]
This is because of the overlapping of the right side div and z-index on the left side div. Just inspect the element and decrease the left side row width, the icon will available for the click but a strange validation is showing on it.
