### ISSUE TITLE
input box error mismatch

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#4064]
# Bug report

### Issue Description
I might made some arrangement to the customer-info file. In what way the error will mismatch?

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. 0.1.8

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

![image](https://user-images.githubusercontent.com/5135163/95614718-cd518a80-0a1b-11eb-9c9f-576016acf134.png)

**Comment by JunaidJaved8461** [comment]
@lYesterdaYl 
I want to fix this issue!!! Please let me know in which theme file, you are facing this issue!!

**Comment by vaishaliwebkul** [comment]
@lYesterdaYl 
this bug does not exist in the latest release(v1.2.0) as well as on the current updated master branch, please check the respective file and compare changes from the master branch to resolve the issue.
