### ISSUE TITLE
Social login not working

### ISSUE THREAD

**Issue by elitedigitaltech** [bagisto/bagisto#4068]
# Bug report

### Title
Created app on facebook for login add that API id and secrete in .env file and when click on login using facebook it asked for permission then again returned to same login page on our website after giving permission.

### Issue Description
Created app on facebook for login add that API id and secrete in .env file and when click on login using facebook it asked for permission then again returned to same login page on our website after giving permission.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by vaishaliwebkul** [comment]
@elitedigitaltech 
could you the screenshot of page while asking for permission?

**Comment by elitedigitaltech** [comment]
Please check

![image](https://user-images.githubusercontent.com/8210369/95718985-d6955e00-0c8c-11eb-8bf3-0b4275fbd20a.png)

**Comment by vaishaliwebkul** [comment]
@elitedigitaltech 
When you click on continue as Sandeep then what is the error shown by Facebook??

**Comment by elitedigitaltech** [comment]
No error Its redirect back to my shop login page

**Comment by vaishaliwebkul** [comment]
@elitedigitaltech 
try to refresh the page again then check whether now the user is logged in or still the same?
 else check once in the incognito mode.

**Comment by elitedigitaltech** [comment]
Its same only showing login page without any session.

**Comment by vaishaliwebkul** [comment]
@elitedigitaltech 
It's working fine at my end.
Make sure you have added a Valid callback_url in facebook Apps-> Settings-> Advance https://prnt.sc/uyj16a

**Comment by elitedigitaltech** [comment]
I have given valid url

![image](https://user-images.githubusercontent.com/8210369/95939770-77555c00-0dfa-11eb-921e-7fafa7dee643.png)


![image](https://user-images.githubusercontent.com/8210369/95939659-33faed80-0dfa-11eb-88a3-ae95878953d5.png)

**Comment by vaishaliwebkul** [comment]
@elitedigitaltech 
closing this as it seems to be working fine as well as fixed on the ticket.
