### ISSUE TITLE
after installation , database have only 5 tables. where is the complete database or migration

### ISSUE THREAD

**Issue by zarifkhanafridi** [bagisto/bagisto#4072]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bagisto.channels' doesn't exist (SQL: select * from `channels` where `code` = default)

**Comment by ghermans** [comment]
We will need more details from you before we can answer this:

1. What version of Bagisto are you using?
2. How are you installing Bagisto?
3. Do you receive any errors during the installation?

**Comment by zarifkhanafridi** [comment]
i installed the latest version from https://bagisto.com/en/download/ using download .

**Comment by zarifkhanafridi** [comment]
and also installed using composer but the problem is same. database have only 5 tables. 
did not received any error during the installation .

**Comment by vaishaliwebkul** [comment]
@zarifkhanafridi 
follow this https://forums.bagisto.com/topic/1563/error-while-installinghttps-forums-bagisto-com-post-2388/5
Hope this will solve your issue.

**Comment by ghermans** [comment]
@zarifkhanafridi have you been able to resolve your issue with the solution provided by @vaishaliwebkul ?

**Comment by vaishaliwebkul** [comment]
@zarifkhanafridi 
I hope the above solution worked for you.
