### ISSUE TITLE
allow many user payment when the product is out of stock

### ISSUE THREAD

**Issue by Nghiait123456** [bagisto/bagisto#4074]
# Bug report

### Title
alow many user payment when the product is out of stock

### Issue Description
1 create one product with total =1. I test with 10 user add product to cart and checkout. Wait for 10 user done go to url checkout/onepage.   
At this time, all 10 users are successful with paypal and create 10 order pending.
What if 10,000 users successfully pay together for a product that cannot be produced or imported, and I will have to manually deal with a pile of users that are out of stock.
Obviously there is no key when clicking the placer Order button, only one key when entering the checkout /onepay url checkout, but it does not cover this case.
I think there is an extra key when clicking placeOrder, and that would only be the fastest user paying,
   I already have the idea of this, would be happy to contribute to the bagisto source code
### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version. 1.2.0
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1: create product with total = 1;
    2. step2: create 2 user , every user add 1 product to cart
    3. step3:   2 user come together  to checkout ( onepage/checkout)  
    4. step4: user 1 done input and click placr order, payment with paypal,  done 
    5. step5: user 2 done input and click place order, payment with paypal, done
   6. step6. have a problem, stock have 1 product but two order pendding,   and What if 100,000 users successfully pay together for a product that cannot be produced or imported,

### Expected result
**Tell us what should happen.**

 will have to manually deal with a pile of users that are out of stock.

### Actual result
 will have to manually deal with a pile of users that are out of stock.

* [points....]

**Comment by devansh-webkul** [comment]
@ghermans,

This is enhancement as currently in Bagisto, products are subtracted from inventory when the shipment is done.
