### ISSUE TITLE
Adding other component into the project

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#4075]
Hi, I need some helps on the add new component into the project. I think the new components come with vue component and scss. I have successfully compile the component after the command npm install and npm dev run under the theme directory, but I realize the components are missing the scss. Can anyone help me out on how to make the components to load the scss? Thanks.

**Comment by devansh-webkul** [comment]
There are two options internally or externally,

**1. Internally,**

~~~
<style lang="scss">
.test {
    border: 5px solid black;
}
</style>
~~~

**2. Externally**

~~~
import 'style.scss';
~~~

**Comment by devansh-webkul** [comment]
Closing this issue. If you have any query please post it in the forum.
