### ISSUE TITLE
Homepage content images are broken in default channel

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4079]
# Bug report

### Title
broken images of homepage content at default channel

### Issue Description
When edit channel, in the Homepage content, the advertisement images are broken and it's visible perfectly on front end of default theme

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- Admin-> Settings-> channels
    2. step2- now check home page content images

### Expected result

images should visible

### Actual result

![Screenshot_49](https://user-images.githubusercontent.com/43210406/95966104-5efc3600-0e28-11eb-9ac1-4a1d0e097746.png)

**Comment by vaishaliwebkul** [comment]
fixed

**Comment by vaishaliwebkul** [comment]
able to reproduce the same issue again https://prnt.sc/yj6ah7

**Comment by ghermans** [comment]
@vaishaliwebkul i verified this issue with a fresh install of 1.3.0 and couldn't reproduce this issue.
Please check below screenshots

### Default theme
![DefaultThemeKnipsel](https://user-images.githubusercontent.com/1594411/108146960-641b0b80-70ce-11eb-9555-bcc8f2c467fe.PNG)

### Velocity theme
![VelocityThemeKnipsel2](https://user-images.githubusercontent.com/1594411/108146991-7006cd80-70ce-11eb-9f79-a316b018854b.PNG)
