### ISSUE TITLE
wishlist or compare product icons are not visible on product for responsive view

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4080]
# Bug report

### Title
wishlist or compare product icons are not visible on product for responsive view

### Issue Description
At homepage when hover over a product then wishlist and compare icons are not visible

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- open velocity homepage in mobile view
    2. step2- hover over any product 

### Expected result

wishlist or compare icon should visible like in web view

### Actual result

when hover over any product, the wishlist or compare icons are visible

![Screenshot_50](https://user-images.githubusercontent.com/43210406/95969110-f1ea9f80-0e2b-11eb-8db8-87413ebc73cf.png)

**Comment by devansh-webkul** [comment]
In a web responsive view, it is visible but for mobile hovering is not possible. There should be some click event for mobile to active icons.

**Comment by ghermans** [comment]
Closing this issue since no feedback has been giving within 29days, neither can i reproduce this issue 

![Knipsel](https://user-images.githubusercontent.com/1594411/104793437-d1234480-57a2-11eb-8896-c42f12f536bf.PNG)
