### ISSUE TITLE
short description is not visible fully in quick view

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4083]
# Bug report

### Title
short description is not visible fully in quick view

### Issue Description
short description is not visible fully in quick view

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add short description in product with more than 500 words
    2. step2- open product quick view

### Expected result

full short description should be visible

### Actual result

![Screenshot_54](https://user-images.githubusercontent.com/43210406/95996993-ecec1700-0e50-11eb-93c7-804aded29fb8.png)

**Comment by ghermans** [comment]
Well it is like you say a **short description** however if i look at the screenshot it seems that this isn't a real "short description" ?

**Comment by devansh-webkul** [comment]
@vaishaliwebkul It should be bounded with a number of characters limit.

**Comment by vaishaliwebkul** [comment]
@ghermans 
Thanks, the content should be less for short descriptions.
@devansh-webkul 
We couldn't add validation in a short description as it supports text editor with HTML code and images also.

Closing this.
