### ISSUE TITLE
Add to Cart button is not coming completely on compare page

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4086]
# Bug report

### Title
Add to Cart button is not coming completely on compare page
### Preconditions

    1. framework Version. Master

### Actual result
https://prnt.sc/uzniy2

**Comment by devansh-webkul** [comment]
@bhanu-webkul,

The button is coming properly, its a text issue.

**Comment by vaishaliwebkul** [comment]
fixed in master https://prnt.sc/v21ix7
