### ISSUE TITLE
how can i change bagisto featured products heading

### ISSUE THREAD

**Issue by owaisali6666** [bagisto/bagisto#4090]
how can i change bagisto featured products heading on home page

**Comment by vaishaliwebkul** [comment]
@owaisali6666 
you may check the answer here https://forums.bagisto.com/topic/1840/how-can-i-change-bagisto-featured-products-heading

**Comment by vaishaliwebkul** [comment]
@owaisali6666 
I hope your query is resolved now so closing this.

Feel free to ask a further queries.
