### ISSUE TITLE
Layout issue on compare page in default theme(RTL)

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4092]
# Bug report

### Title
Layout issue on compare page in default theme(RTL)

### Preconditions
    1. framework Version. Master

### Steps to reproduce
    1. step1: use default theme,add product in compare
    2. step2: set locale ar
### Actual result
cross icon and delete all button is not coming at right place

![Screenshot from 2020-10-15 15-02-44](https://user-images.githubusercontent.com/52821836/96105836-1e6bed80-0ef8-11eb-84f3-97e113798237.png)

**Comment by sharik709** [comment]
can I work on this?

**Comment by vaishaliwebkul** [comment]
@sharik709 
The PR is already opened on this issue, you may freely work on any other issue.

Thanks

**Comment by bhanu-webkul** [comment]
fixed in master
