### ISSUE TITLE
reverted characters in ar or fa (RTL fonts) invoice prints,exp: true[سلام] not be [م ا ل س]

### ISSUE THREAD

**Issue by roham96** [bagisto/bagisto#4097]
# Bug report

### Title
**Tcpdf invoice print results RTL writings.**
**Tcpdf problem around invoice print results RTL writings.**

### Issue Description
**Tcpdf problem around invoice print results RTL writings.**

* [points....]

**Comment by vaishaliwebkul** [comment]
@roham96 
please provide more details about this issue
- bagisto version
- steps to reproduce

**Comment by vaishaliwebkul** [comment]
@roham96 
no response from last 12 days so closing this.
