### ISSUE TITLE
Add a payment history for orders

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4102]
Add a payment history for each order, so that store admins have a overview if a payment has been made or not.
This can also be useful for most of the payment gateways since they have some callback/webhook function to update your application regarding payments.
It can also be used later for reporting.

**Comment by kian92** [comment]
Look forward to this feature to be launched soon. :)

**Comment by kian92** [comment]
@ghermans @saurav-webkul 
Hi all, can I have any target completion date for this feature?

We plan to launch e-commerce by next month, and also thanks for the awesome framework. 

If you have any interim solution, please share it with me as well. 

Thank you in advance :)

**Comment by ghermans** [comment]
@saurav-webkul @jitendra-webkul can one of you follow this up?

**Comment by ghermans** [comment]
@kian92 we have first been investigating what would be the best approach for this, we will start asap with implementing this feature and keep you up to date regarding the progress

**Comment by kian92** [comment]
Hi all, any updates so far?

**Comment by ghermans** [comment]
@kian92 sorry for the late response, we are currently working on this and it will be available within the next release.

**Comment by ghermans** [comment]
https://devdocs.bagisto.com/1.x/api/transactions.html

**Comment by mezzat11** [comment]
it is rest api to list transaction
I am talking about Webhook to use it with payment gateway to update invoice status to paid automatically
