### ISSUE TITLE
Issue with total due in cash on delivery

### ISSUE THREAD

**Issue by rockgold22** [bagisto/bagisto#4105]
# Bug report

### Issue with total due in cash on delivery in case of order cancellation
**If cancellation is done and order is placed via COD, then the due amount shown should not be there**

### Issue Description
**If the admin is canceling the order and the mode of payment is COD, then it should not be shown the due payment as payment is not yet arrived. Since order never gets dispatched. **

### Preconditions
**Step1: Order a product
Step2: Choose payment method as cash on delivery
Step 3: From admin panel cancel the order**

    1. framework Version: laravel version: 6.18.23, app version: 1.2.0
    2. Commit id.

### Steps to reproduce
Step1: Order a product
Step2: Choose payment method as cash on delivery
Step 3: From the admin panel cancel the order

### Expected result
**Since it is not the case of pre-payment, the payment due must be zero after cancelation **

*   [Screenshots, logs, or description]

### Actual result

>    **Right now, even after the cancelation, I can see the amount due is there. to support my argument please find this screenshot
![screen2](https://user-images.githubusercontent.com/16397436/96378367-1d151c00-11a9-11eb-880e-21d879cb22cd.png)
![screen1](https://user-images.githubusercontent.com/16397436/96378368-1ededf80-11a9-11eb-93c7-a93089bc0302.png)

**Comment by ghermans** [comment]
@rockgold22 the issue should be resolved now, in case you still experience any issues please let us know.
