### ISSUE TITLE
image is showing in outer div box in cart page

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4109]
# Bug report

### Title
image is showing out of div box in cart page

### Issue Description
image is showing out of div box in cart page

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add a product image with max-height
    2. step2- now add to cart the product and go to the cart page

### Expected result

the image should not out from the div box

### Actual result

![Screenshot_76](https://user-images.githubusercontent.com/43210406/96443453-4033e000-122a-11eb-9dfe-a6b333aaa4c1.png)

**Comment by georgioupanayiotis** [comment]
Hello @vaishaliwebkul  Can you assign me this ticket ?

**Comment by devansh-webkul** [comment]
Fixed in master.

**Comment by vaishaliwebkul** [comment]
https://prnt.sc/v9yccs fixed
