### ISSUE TITLE
layout issue while edit product in RTL for multiselect type attribute

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4112]
# Bug report

### Title
layout issue while editing product in RTL for the select type attribute

### Issue Description
layout issue while editing product in RTL for the select type attribute

### Preconditions

    1. framework Version- master
    
### Steps to reproduce

    1. step1- set the admin locale to ar .env(make sure ar locale should be added in settings->locale(RTL)
    2. step2- now add select type attribute in attribute family
    3. step3- catalog-> create product 

### Expected result

the select type field should be started from right

### Actual result

![Screenshot_84](https://user-images.githubusercontent.com/43210406/96466762-cb6f9e80-1247-11eb-9e56-a3c906f742b5.png)

**Comment by asif-webkul** [comment]
working on it

**Comment by vaishaliwebkul** [comment]
fixed in master
