### ISSUE TITLE
Wrong tooltip coming on few places 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4116]
# Bug report

### Title
Wrong tooltip coming on few places 

### Preconditions
    1. framework Version. Master

### Steps to reproduce
    1. use more than one slider images
    2. use multiple images in product and quick view  

### Expected result:
there is not requirement of tooltip
### Actual result:
1st
![Screenshot from 2020-10-20 14-15-13](https://user-images.githubusercontent.com/52821836/96562744-bd209180-12de-11eb-9538-4f5dd948268c.png)

2nd

![Screenshot from 2020-10-20 14-00-49](https://user-images.githubusercontent.com/52821836/96562659-a1b58680-12de-11eb-86f0-59ee472a50bb.png)

**Comment by devansh-webkul** [comment]
This issue faced by many users in vue carousel.

Reference: https://github.com/SSENSE/vue-carousel/issues/488

**Comment by bhanu-webkul** [comment]
Fixed in master
