### ISSUE TITLE
Advertisement images are not visible in safari browser 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4118]
# Bug report
Advertisement images are not visible in safari browser 
### Preconditions
    1. framework Version. Master

### Expected result
![Screenshot from 2020-10-20 15-18-24](https://user-images.githubusercontent.com/52821836/96570302-d24dee00-12e7-11eb-9a4d-4a9ae082d445.png)

### Actual result
![Screenshot from 2020-10-20 14-41-19](https://user-images.githubusercontent.com/52821836/96570331-dc6fec80-12e7-11eb-9612-f225193abe9f.png)

**Comment by devansh-webkul** [comment]
Safari browser doesn't support the `.webp` extension till Safari Version 12. WebP official support has been added to Safari 14.

**Comment by vaishaliwebkul** [comment]
@bhanu-webkul 
please check this in Safari version 14 as mention by @devansh-webkul
