### ISSUE TITLE
Admin should not be able to create multiple cart rule using same coupon code 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4119]
# Bug report

### Title
Admin should not be able to create multiple cart rule using same coupon code 

### Preconditions
    1. framework Version. Master

### Steps to reproduce
    1. step1: create one cart rule with specific coupon
    2. step2: create next cart rule with specific coupon and use same coupon code in both 

### Expected result:
there should be validation for coupon code 
### Actual result
no validation

**Comment by bhanu-webkul** [comment]
not getting any validation message on using same coupon code while creating cart rule

**Comment by vaishaliwebkul** [comment]
@bhanu-webkul 
implemented https://prnt.sc/vqiofl, so closing this.
