### ISSUE TITLE
Getting Exception if there is no record in Review grid and mass deletion and mass update operation is performed.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#412]
Framework Version: 0.1.3

![screenshot from 2018-12-26 19-47-35](https://user-images.githubusercontent.com/45203177/50448408-220b3a80-0947-11e9-9c37-261d1562c84e.png)

**Comment by prashant-webkul** [comment]
Mass selection features are now programmed to come only when there are records in the datagrid, if there are no records in the datagrid then mass selection features will not come up.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
