### ISSUE TITLE
fix compare icon in RTL 

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4121]
# Bug report

### Title
fix compare icon in RTL 

### Issue Description
fix compare icon in RTL 

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- change the store theme to "default"
    2. step2- now check the compare icon in RTL on home page

### Expected result

the icon should be same as in LTR

### Actual result

![Screenshot_94](https://user-images.githubusercontent.com/43210406/96581807-04674c00-12f8-11eb-9a26-98e36c2e7892.png)

**Comment by asif-webkul** [comment]
working on it

**Comment by vaishaliwebkul** [comment]
https://prnt.sc/v3xsag fixed in master
