### ISSUE TITLE
Client Side validation issue in Special Price for ticket booking Product

### ISSUE THREAD

**Issue by AayushBhatt-webkul** [bagisto/bagisto#4124]
# Bug report

### Issue
**Special price is not giving any client side validation error even if we enter string instead of numbers**

### Preconditions
**I used below preconditions**

    1. Bagisto 1.2.0

### Steps to reproduce

    1. Create a booking product.
    2. edit the product and go to create tickets and insert some alphabets in special price section. No client side validation error.

### Expected result
**It should be showing a warning under the input box**

### Actual result
https://prnt.sc/v31sa4

**Comment by vaishaliwebkul** [comment]
fixed in master
