### ISSUE TITLE
Header Content Count should be set by default for all locale 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4127]
# Bug report

### Title
Header Content Count should be set by default for all locale 

### Preconditions
    1. framework Version.  Master

### Steps to reproduce
    1. step1: change locale on Velocity meta data page

### Expected result:
Header Content Count should be set by default for all locale 
### Actual result:
on changing locale there is no value 
![Screenshot from 2020-10-20 19-10-06](https://user-images.githubusercontent.com/52821836/96594095-e0ac0200-1307-11eb-98db-4d42615176ea.png)

**Comment by asif-webkul** [comment]
working on it

**Comment by bhanu-webkul** [comment]
fixed in master
