### ISSUE TITLE
Velocity Meta Data Advertisement images Issue

### ISSUE THREAD

**Issue by aayushbhatt-18** [bagisto/bagisto#4128]
# Bug report

### Title
**Advertisement images are not getting removed even if you remove them from Meta Data**

### Preconditions

    1. Bagisto version 1.2.0

### Steps to reproduce

    1. Go to Velocity Meta Data from Admin
    2. Try to remove advertisement images.

### Expected result
**the images should get removed**

### Actual result

>    **The images are not getting removed**

**Comment by vaishaliwebkul** [comment]
@AayushBhatt-webkul 
these are the default image for advertisement, you can only update them for velocity.

**Comment by praem90** [comment]
These images were hard coded and this can be moved to database seeds. Will this work?

**Comment by jitendra-webkul** [comment]
Images can be changed from the admin back office
