### ISSUE TITLE
Category Slug should be select type field 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4129]
# Bug report

### Title
Category Slug should be select type field 
### Issue Description:
As currently admin need to enter category slug which can be difficult task to remember or copy slug from category page, and any single misspelling can cause 404 error on front end, so it would be better that we make that field as select type and display the tree of slugs 

### Preconditions
    1. framework Version. Master

### Steps to reproduce
    1. step1: create header content for velocity theme

### Expected result:
should be select type filed as like we have in cart rule where we display complete tree of category 
### Actual result:
admin needs to enter value

**Comment by jitendra-webkul** [comment]
Not feasible
