### ISSUE TITLE
Velocity meta Data Advertisement images are getting removed even if you don't remove them.

### ISSUE THREAD

**Issue by AayushBhatt-webkul** [bagisto/bagisto#4131]
# Bug report

### Title
**When you try to remove one image from the four advertisement images, and add a custom image there. rest three images are getting deleted and your custom image is getting broken.**

### Preconditions

    1. Bagisto 1.2.0

### Steps to reproduce

    1. Go to velocity meta data -> Advertisement four images.
    2. Remove one image and add your custom image.
    3. Now when you save the settings. It removes the rest three images and your custom image also gets broken.

### Expected result
**Rest 3 images should not get deleted.**

https://prnt.sc/v35huf https://prnt.sc/v35ihd

### Actual result

>    **Rest 3 images are getting deleted and custom image is getting broken.**

**Comment by vaishaliwebkul** [comment]
@AayushBhatt-webkul 
the uploaded 3 or 4 advertisement images are hardcoded, if you want to add more than you have to first remove all the images then upload new images.
