### ISSUE TITLE
fix sale icon in customer wishlist page for RTL

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4133]
# Bug report

### Title
fix sale icon in customer wishlist page for RTL

### Issue Description
fix sale icon in customer wishlist page for RTL

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- change store view to RTL
    2. step2- add the sales product to the wishlist 

### Expected result

sale icon should place on the product's right end

### Actual result

![Screenshot_98](https://user-images.githubusercontent.com/43210406/96608309-d9402500-1316-11eb-9815-59d0dacc3625.png)

**Comment by asif-webkul** [comment]
working on it

**Comment by vaishaliwebkul** [comment]
fixed in master https://prnt.sc/v3xquf
