### ISSUE TITLE
ar locale translation missing in backend

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4134]
# Bug report

### Title
ar locale translation missing in backend

### Issue Description
ar locale translation missing in backend

### Preconditions

    1. framework Version - master

### Steps to reproduce

    1. step1- change admin locale to ar from the .env 

### Expected result

Translate all the field in ar locale

### Actual result

 1. Order summary
![Screenshot_99](https://user-images.githubusercontent.com/43210406/96611874-bf084600-131a-11eb-8073-837395a9cdf1.png)
![Screenshot_100](https://user-images.githubusercontent.com/43210406/96611880-c0d20980-131a-11eb-85b9-abe9b70e5f66.png)

2. Velocity->Meta data

![Screenshot_101](https://user-images.githubusercontent.com/43210406/96612135-08589580-131b-11eb-8d80-3f6778fbff5c.png)

3.  configuration -> general-> email settings

![Screenshot_102](https://user-images.githubusercontent.com/43210406/96612305-3b028e00-131b-11eb-8d29-5d09d5dd2f4c.png)

4. configuration-> general -> content

![Screenshot_103](https://user-images.githubusercontent.com/43210406/96612582-8a48be80-131b-11eb-93bf-51672c421ef1.png)

![Screenshot_104](https://user-images.githubusercontent.com/43210406/96612677-ab111400-131b-11eb-8732-05a98b0de202.png)

**Comment by ghermans** [comment]
This has already been mentioned in https://github.com/bagisto/bagisto/issues/1265

**Comment by vaishaliwebkul** [comment]
@ghermans 
Yes but in perivous most of the string are already translated now and this is related to admin panel
