### ISSUE TITLE
Uneven Grid in both the themes

### ISSUE THREAD

**Issue by AayushBhatt-webkul** [bagisto/bagisto#4137]
# Bug report

### Title
**Grids of the products at homepage are uneven and based on the size of the product image and how big the name of a product is.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Baggto version 1.2.0

### Steps to reproduce

    1. Create few products with different size of product images and size of the name of the product.
    2. Check the homepage of both the themes i.e default and velocity.

### Expected result
**Grid must be even like what we see on Amazon and flipkart.**

* https://prnt.sc/v3j6az

### Actual result

>    **The grids are not even**

* https://prnt.sc/v3j2kz https://prnt.sc/v3j3cg

**Comment by vaishaliwebkul** [comment]
@aayush-webkul 
this is already raised https://github.com/bagisto/bagisto/issues/4114
