### ISSUE TITLE
Product image gets broken after editing the product from Admin

### ISSUE THREAD

**Issue by AayushBhatt-webkul** [bagisto/bagisto#4138]
### Broken Product Image
**Image of the product gets brojken after you edit the product from the Admin and save it.
When you re open it. You see a broken image. Although original image is still visible in front end.**

### Preconditions
**I used the following preconditions**

    1. Bagisto: 1.2.0 (Master).

### Steps to reproduce

    1. Create a product.
    2. Edit the product, put an image and save.
    3. Now scroll down to see your product image on edit page.

### Expected result
**The product image should not get broken.**

### Actual result

>    **Showing a broken product image at admin end.**
https://prnt.sc/v3jar4

**Comment by vaishaliwebkul** [comment]
@AayushBhatt-webkul 
you should follow the solution provided here for broken image https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions/1

Images are showing correctly at my end please see https://prnt.sc/v3jfei

**Comment by AayushBhatt-webkul** [comment]
I have not changed APP_URL after storage:link command.
Also this is happening with some of the images and not with all of'em.

**Comment by vaishaliwebkul** [comment]
@AayushBhatt-webkul 
please mention the image format you're trying to upload so that we can check with same.

**Comment by AayushBhatt-webkul** [comment]
.png

**Comment by vaishaliwebkul** [comment]
@AayushBhatt-webkul 
it's working fine for .png format also, so closing this for now.

**Comment by akshaypitale** [comment]
> I have not changed APP_URL after storage:link command.
> Also this is happening with some of the images and not with all of'em.

Hi did you find the solution for this?
