### ISSUE TITLE
Channel hostname is empty

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4162]
# Bug report

### Issue Description
After a fresh install the channel hostname is empty

### Preconditions
    1. master branch

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Setup a fresh install
    2. Go to Admin / Settings / Channels / default 
    3. Check the hostname field

### Actual result

![hostKnipsel](https://user-images.githubusercontent.com/1594411/96879727-aca61d80-147c-11eb-8c6f-c529802270bf.PNG)

**Comment by praem90** [comment]
What is the expected value for default channel's hostname?

**Comment by ghermans** [comment]
The default channel hostname should be your APP_URL
