### ISSUE TITLE
bug  if bundle product exist with sale price in default theme

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4165]
# Bug report

### Title
bug exist if bundle product exist with sale price in default theme

### Issue Description
bug exist if bundle product exist with sale price in default theme

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add bundle product with product existing in sale

### Expected result
regular price should be crossed

### Actual result
![Screenshot_111](https://user-images.githubusercontent.com/43210406/96892664-7d58d600-14a7-11eb-94e8-969b58e86454.png)

**Comment by devansh-webkul** [comment]
@vaishaliwebkul 

This is because of my PR, which is merged in master. This bug not exist in default because method in which i added class belongs to both theme thats why it got reflected here as well. I will fix it in the morning.

**Comment by vaishaliwebkul** [comment]
fixed
