### ISSUE TITLE
Issue in text color when updating middle footer content for other locales.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4170]
![download - 2020-10-23T135953 295](https://user-images.githubusercontent.com/45203177/96975435-0ddef700-1538-11eb-9f8e-da6da9383623.png)

**Comment by nicobi83** [comment]
Hi, if I have correctly understood you have add these 4 chars "yygy" and the browser has loaded them with another color.

**Comment by jyoti-webkul** [comment]
> Hi, if I have correctly understood you have add these 4 chars "yygy" and the browser has loaded them with another color.

yes

**Comment by nicobi83** [comment]
Ok, I'm configuring the platform in my local environment.
Do you know if anyone has fixed this issue or not?

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
please mention the steps to reproduce this issue to help and faster resolution of this bug.
Also, it's working on the master branch https://prnt.sc/v70dor

@nicobi83 
if you're also facing such kind of issue, feel free to mention the steps to reproduce.
once it will be verified then you are free to open a PR for this issue.

Thanks

**Comment by nicobi83** [comment]
@vaishaliwebkul 

So the problem is not existent if in master it's working correctly.

**Comment by vaishaliwebkul** [comment]
@nicobi83 
Yes, master branch is the most updated and development branch, if the bug does not exist in this branch then no need to fix it.

**Comment by jyoti-webkul** [comment]
Working fine in master branch
