### ISSUE TITLE
Disorganized pages after installation please help

### ISSUE THREAD

**Issue by rajexact** [bagisto/bagisto#4173]
I have install bagisto on windows 10 , xampp v3.2.4
After successful installation i found every page disorganized like menubars and other settings.
please help

![new](https://user-images.githubusercontent.com/72779769/96997288-21e22300-154f-11eb-90dc-c777a80f0ad3.png)

**Comment by devansh-webkul** [comment]
Hi @rajexact,

Please run `php artisan vendor:publish --all --force`.

**Comment by rajexact** [comment]
Thanks Devansh
ITS A PERFECT SOLUTION I HAVE RUN COMMAND AND ITS WORKING FINE NOW!
GREAT 
THANK YOU VERY MUCH

**Comment by rajexact** [comment]
Thanks Devansh
ITS A PERFECT SOLUTION I HAVE RUN COMMAND AND ITS WORKING FINE NOW!
GREAT
THANK YOU VERY MUCH
