### ISSUE TITLE
Orders Api "Route [auth.login] not defined."

### ISSUE THREAD

**Issue by amit643** [bagisto/bagisto#4176]
Hi,
Below is the my curl call request for get all orders. $access_token is the value which i get from admins table and api_token column. I want to get all orders with admin users token not as customer. please help me on this please let us know if any changes required in below code. (I installed bagisto on wamp server ).

$url = 'http://localhost/bagisto_fresh/public/api/orders';
$access_token = 'qu8vfY3xFPHwnOXntTtN65ETCnjRAE8uGwzVlw6SFjCbxpe0qGHFHNLPCovxwXk0HdmxalYhNeC3bfeY';
	
$token = $access_token;
//setup the request, you can also use CURLOPT_URL
$ch = curl_init($url);
// Returns the data/output as a string instead of raw data
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
//Set your auth headers
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
   'Content-Type: application/json',
   'Authorization: Bearer ' . $token
   ));
// get stringified data/output. See CURLOPT_RETURNTRANSFER
$data = curl_exec($ch);
// get info about the request
$info = curl_getinfo($ch);
// close curl resource to free up system resources
curl_close($ch);
print_r($data);

**Comment by vaishaliwebkul** [comment]
@amit643 
Hope the solution provided here will hell you
https://github.com/bagisto/bagisto/issues/1974

**Comment by amit643** [comment]
Hi

Thanks for reply i did as per the #1974 but didnt work for me.

My basics requirements like below

**Comment by amit643** [comment]
> @amit643
> Hope the solution provided here will hell you
> #1974

Hi

Thanks for reply i did as per the #1974 but didnt work for me. as per the 1974 i passed application/json in header.

My basics requirements like below.

Get Access token for admin user. (admin@example.com/admin123 as per the demo)
Call GET /api/orders(?limit,page,pagination) for fetch all orders.
Thank in Advance

**Comment by amit643** [comment]
`<?php function CurlSendPostRequest($url,$request)
    {
        $ch = curl_init($url);
        $options = array(
                CURLOPT_RETURNTRANSFER => true,         // return web page
                CURLOPT_HEADER         => false,        // don't return headers
                CURLOPT_FOLLOWLOCATION => false,         // follow redirects
                CURLOPT_AUTOREFERER    => true,         // set referer on redirect
                CURLOPT_CONNECTTIMEOUT => 20,          // timeout on connect
                CURLOPT_TIMEOUT        => 20,          // timeout on response
               
				CURLOPT_SSL_VERIFYHOST => 0,            // don't verify ssl
                CURLOPT_SSL_VERIFYPEER => false,        //
                CURLOPT_VERBOSE        => 1,
        );
		
		if(count($request) > 0 && !array_key_exists('api_token',$request)){
			$options[CURLOPT_POST]       = 1;            // i am sending post data
			$options[CURLOPT_POSTFIELDS] = $request;    // this are my post vars
		}
		$options[CURLOPT_HTTPHEADER][0] = 'Accept:application/json';
		//$options[CURLOPT_HTTPHEADER][1] = 'Content-Type: application/json';
		if(array_key_exists('api_token',$request)){
			$options[CURLOPT_HTTPHEADER][2] = 'Authorization: Bearer '.$request['api_token'];
		}	

        curl_setopt_array($ch,$options);
        $data = curl_exec($ch);
        $curl_errno = curl_errno($ch);
        $curl_error = curl_error($ch);
        curl_close($ch);
        return $data;
    }
	
	$username='test@test.com';
	$password='Test@123';
	
	$url = 'http://local.bagistomainstore.com/api/customer/login?token=true'; 
	$data['email']    = $username;
	$data['password'] = $password;
	$res = json_decode(CurlSendPostRequest($url,$data),true);
	echo "<pre>";
	print_r($res);
	echo "</pre>";
	
	$url = 'http://local.bagistomainstore.com/api/orders';
	$datas = array('api_token' => $res['token']);
	$res = CurlSendPostRequest($url,$datas);
	echo "<pre>";
	print_r($res);
	echo "</pre>";
	?>`

**Comment by nicobi83** [comment]
@amit643 

Hi, 
orders must return the "orders" done by logged user?
If is it $res['token'] what does it return?

**Comment by amit643** [comment]
@nicobi83 

orders must return the "orders" done by logged user? no.. its admin user not a customer order.

want to achive like below.

**Comment by devansh-webkul** [comment]
Hi @amit643,

We don't have an API for admin users. You need to customize this from your end.

The error you are getting is of `unauthorized access`. Means you are trying to login admin from customer API.

**Comment by amit643** [comment]
Hi @devansh-webkul

**Comment by devansh-webkul** [comment]
Hi @amit643,

This will help you https://jwt-auth.readthedocs.io/en/docs/quick-start/.

Just implement the JWT interface on the model you required.

**Comment by devansh-webkul** [comment]
For any queries, you can revert to the same forum you have created.
