### ISSUE TITLE
Quick View button margin glitch in wishlist

### ISSUE THREAD

**Issue by AayushBhatt-webkul** [bagisto/bagisto#4178]
# Bug report

### Issue Description
**The margin of quick view button in wishlist page is not at the center of the image, rather it is coming at the bottom of it.**

### Preconditions

    1. Bagisto 1.2.0

### Steps to reproduce

    1.Add a product to wishlist.
    2.Go to wishlist and hover over the product image. 

### Expected result
**The quick view button should come into the center of the product image irrespective of the image size.**

### Actual result
![f](https://user-images.githubusercontent.com/38464980/97176063-6a514900-17ba-11eb-8f9a-091494d7ad9c.png)

**Comment by devansh-webkul** [comment]
The 'Quick View Icon' already aligned to the div just 5 to 10 px above. The thing is image is auto-adjusted inside div. I didn't think this is an issue. Unless and until the quick view icon position changed on increasing or decreasing the window width.
