### ISSUE TITLE
category menu layout issue exist if 3rd level category added

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4181]
# Bug report

### Title
category menu layout issue exist if 3rd level category added

### Issue Description
category menu layout issue exist if 3rd level category added

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add 3 level category in format **default-> women -> dresses**

### Actual result

![Screenshot_115](https://user-images.githubusercontent.com/43210406/97187717-bb683980-17c8-11eb-963c-eeac11ef285c.png)

**Comment by nicobi83** [comment]
@vaishaliwebkul 

Do you have add the third category as admin?
