### ISSUE TITLE
db connection failed at first time when setup using bagisto:install

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4192]
# Bug report

### Title
connection fails at first time when setup bagisto using command php artisan bagisto:install with valid database credentials.

### Issue Description
connection fails at first time when setup bagisto using command php artisan bagisto:install with valid database credentials.
When again run the same command then migration gets start

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- setup bagisto using php artisan bagisto:install
    2. step2- enter valid database name, username, password and etc.

### Expected result
migration should be started if all values are valid

### Actual result
![Screenshot_117](https://user-images.githubusercontent.com/43210406/97324047-6c3d0a00-1897-11eb-89f4-a4c939ea9ecd.png)

**Comment by nicobi83** [comment]
Hi,
I have tested in these days this command in my local environment but it does not give anyone of this errors.

**Comment by vaishaliwebkul** [comment]
getting same issue again on master branch

![Screenshot_182](https://user-images.githubusercontent.com/43210406/103344569-f894c480-4ab4-11eb-9f63-09d64154c34c.png)

**Comment by devansh-webkul** [comment]
@vaishaliwebkul and @ghermans,

It's very strange because all test case is passing but still on installation it's not making a connection.

Will update you on this :sunglasses:.

**Comment by vaishaliwebkul** [comment]
fixed
