### ISSUE TITLE
Shop By Category and change language not work

### ISSUE THREAD

**Issue by nicobi83** [bagisto/bagisto#4193]
Hi,
In my local environment of Bagisto Shop By Category and the dropdown change language not work.
I have searched the problem using tools of developer of Chrome but no errors found.
This is not a bug because in production they work but I don't understand why they are broken.
Any suggestions?
Thank you!

![velocity](https://user-images.githubusercontent.com/18639300/97344027-80c5d600-1888-11eb-8cb0-824fd22ec84f.png)

**Comment by vaishaliwebkul** [comment]
@nicobi83 
1. select the root category as the parent category inside the categories to show them under **shop By category** 
2. same for locales dropdown, add locales from the settings->locale and select all the locale inside setting->channels https://prnt.sc/v8fsqa

**Comment by nicobi83** [comment]
> @nicobi83
> 
> 1. select the root category as the parent category inside the categories to show them under **shop By category**
> 2. same for locales dropdown, add locales from the settings->locale and select all the locale inside setting->channels https://prnt.sc/v8fsqa

**Comment by nicobi83** [comment]
Ok, I have fixed the point 2 but under categories I have already set Root as parent category
