### ISSUE TITLE
Locale at bottom index page is not visible

### ISSUE THREAD

**Issue by nicobi83** [bagisto/bagisto#4201]
I have added a new locale (German) from admin panel following the guide from tutorial but the LOCALE dropdown is not visible in the Velocity main page.

**Comment by ghermans** [comment]
Did you also selected the local in your channel?
![localKnipsel](https://user-images.githubusercontent.com/1594411/97478737-a1a62e00-1951-11eb-9e11-120c0e066f5f.JPG)

**Comment by nicobi83** [comment]
Ok, yesterday the new language did not function after having added it. Now I have done a new login in bagisto, readded the new language in "Channels/Currencies and Locales" and now it works. It's strange that now it works but yesterday did not work.
