### ISSUE TITLE
sql_require_primary_key 

### ISSUE THREAD

**Issue by robinflyhigh** [bagisto/bagisto#4203]
# Bug report

When running migration in MySQL 8

Migrating: 2014_10_12_100000_create_admin_password_resets_table

APP_VERSION=1.2.0

In Connection.php line 671:
                                                                               
  SQLSTATE[HY000]: General error: 3750 Unable to create or change a table wit  
  hout a primary key, when the system variable 'sql_require_primary_key' is s  
  et. Add a primary key to the table or unset this variable to avoid this mes  
  sage. Note that tables without a primary key can cause performance problems  
   in row-based replication, so please consult your DBA before changing this   
  setting. (SQL: create table `ynadmin_password_resets` (`email` varchar(191)  
   not null, `token` varchar(191) not null, `created_at` timestamp null) defa  
  ult character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB ROW_  
  FORMAT=DYNAMIC)                                                              
                                                                               

In PDOStatement.php line 119:
                                                                               
  SQLSTATE[HY000]: General error: 3750 Unable to create or change a table wit  
  hout a primary key, when the system variable 'sql_require_primary_key' is s  
  et. Add a primary key to the table or unset this variable to avoid this mes  
  sage. Note that tables without a primary key can cause performance problems  
   in row-based replication, so please consult your DBA before changing this   
  setting.                                                                     
                                                                               

In PDOStatement.php line 117:
                                                                               
  SQLSTATE[HY000]: General error: 3750 Unable to create or change a table wit  
  hout a primary key, when the system variable 'sql_require_primary_key' is s  
  et. Add a primary key to the table or unset this variable to avoid this mes  
  sage. Note that tables without a primary key can cause performance problems  
   in row-based replication, so please consult your DBA before changing this   
  setting.

**Comment by vaishaliwebkul** [comment]
@robinflyhigh 
I hope this will work, same query https://github.com/bagisto/bagisto/issues/3448

**Comment by lucduong** [comment]
@vaishaliwebkul  it doesn't work. I have same issue, do you have any idea on this?
