### ISSUE TITLE
Third level category internal server error

### ISSUE THREAD

**Issue by nicobi83** [bagisto/bagisto#4205]
# Bug report

### Title
Third level category internal server error

### Issue Description
Error 500 at creation of a third level category
https://demo.bagisto.com/bagisto-common/admin/catalog/categories/create

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework master Version.

### Steps to reproduce

    1. Enter as admin
    2. Go in "Catalog"
    3. Go in "Category"
    4. Create a new third level category inside a node secondary level(i.e. Yoga)

### Expected result
A visible third level category

### Actual result
500 | Server Error

**Comment by vaishaliwebkul** [comment]
@nicobi83 
this issue exists in demo, please check the same in your local instance.
In case you're getting the same on your local instance, please let me know.

**Comment by nicobi83** [comment]
Few days ago I had added a new third level category and I didn't have any issue.
In my local environment I wanted test if it was fixed bug #4183 after last pull done yesterday.

**Comment by vaishaliwebkul** [comment]
@nicobi83 
are you testing on bagisto latest version or from master branch??

as the third level category is working fine with latest version.

**Comment by nicobi83** [comment]
From master branch.
What is the latest version? 1.2.0?

**Comment by vaishaliwebkul** [comment]
@nicobi83 
The PR is already opened by @devansh-webkul and soon it will be merged.
You may freely work on any other issue.

Thanks

**Comment by vaishaliwebkul** [comment]
@nicobi83 
Closing this as we are not getting any internal server error on third level category.

Hope this is fix at your end.

**Comment by martinie** [comment]
I keep getting this error...image size doesn't seem to be a factor

**Comment by martinie** [comment]
nodejs wasn't installed 🤣
