### ISSUE TITLE
During queue:work and trying to send email ErrorException: Trying to get property 'uri' ThemeViewFinder.php:23

### ISSUE THREAD

**Issue by olegrosa** [bagisto/bagisto#4209]
When running `php artisan queue:work` command for sending emails in ShouldQueued class we got next error:

`ErrorException: Trying to get property 'uri' of non-object in \packages\Webkul\Theme\src\ThemeViewFinder.php:23`

Here is our code to send an email:
```php
return $this->from(core()->getSenderEmailDetails()['email'], core()->getSenderEmailDetails()['name'])
            ->to($order->customer_email, $order->customer_full_name)
            ->subject('TLIST - Your tickets')
            ->view('shop::emails.sales.new-invoice', ['invoice' => $this->sellerInvoice])
            ->attach($path);
```

**Comment by devansh-webkul** [comment]
Hi @olegrosa,

Can you provide more info on this? From the given information, I am only able to figure out that the object has not been passed to the `ThemeViewFinderClass`.

**Comment by vaishaliwebkul** [comment]
@olegrosa 
closing this as no response from last 12 days
