### ISSUE TITLE
Error uninstall developer dependencies going into production mode

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4212]
composer install --no-dev
  - Removing barryvdh/laravel-debugbar (v3.3.3)
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
In ProviderRepository.php line 208:                                                       
  Class 'Barryvdh\Debugbar\ServiceProvider' not found  
![Captura de tela de 2020-10-31 22-49-12](https://user-images.githubusercontent.com/30912144/97793493-62831180-1bcb-11eb-8ad6-954f5af5bc4c.png)

**Comment by vaishaliwebkul** [comment]
@marcelowu 
May I know the composer version installed on your platform??

**Comment by marcelowu** [comment]
Composer 1.10.1

**Comment by devansh-webkul** [comment]
Hi @marcelowu,

Just fixed the 'barryvdh/laravel-debugbar' issue.

The remaining warning you are seeing because of the third party dependency. So it won't impact you.

**Comment by marcelowu** [comment]
generated successfully.
