### ISSUE TITLE
adding one active item when user enter product page

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#4215]
when user visits the product page i want one item to be active on default is there any possibility to do this ?? thanks

**Comment by vaishaliwebkul** [comment]
@farshadff 
what type of item you want to active? please provide some more detail.

**Comment by farshadff** [comment]
@vaishaliwebkul thanks for reply . consider a configurable product when opens i want to to be on `black` color on default and my user just selects size or if he/she wants change color otherwise the `black` color would be default .

**Comment by vaishaliwebkul** [comment]
@farshadff 
You may set the default value as a variant option value by doing changes in this file https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php

**Comment by vaishaliwebkul** [comment]
@farshadff 
I hope the provided solution worked for you..

closing this as no response from last 13 days.

**Comment by farshadff** [comment]
> @farshadff
> You may set the default value as a variant option value by doing changes in this file https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php

i searched but could not find any thing named option value or default value can you please tell me what is it called or which line is written . thanks in advance
