### ISSUE TITLE
Mysql cpu usage goes up to 1000% in WHM

### ISSUE THREAD

**Issue by GayanPriyankara** [bagisto/bagisto#4216]
hello i am facing a problem after the launch of my web MySQL is query very slow
MySQL query taking huge time
with the two queries being used to fetch products

mysql cpu usage goes up to 1000%
![img1](https://user-images.githubusercontent.com/5396993/97807118-0977b400-1c85-11eb-887a-e3150b08cb71.jpg)
![img2](https://user-images.githubusercontent.com/5396993/97807122-0d0b3b00-1c85-11eb-8b43-bb58e41e4df4.PNG)
![img3](https://user-images.githubusercontent.com/5396993/97807123-0e3c6800-1c85-11eb-8b64-ad0af98628b8.png)

i have already launched the website

**Comment by Debakash01** [comment]
how to fix it
![Screenshot (17)](https://user-images.githubusercontent.com/121277992/209277216-118e41a9-de1b-48b5-9a9d-05649edfa99a.png)
![Screenshot (16)](https://user-images.githubusercontent.com/121277992/209277240-a30bd905-8444-47b0-9dc4-c5f5b9f2d72f.png)

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please take a **reference** from [Here](https://github.com/bagisto/bagisto/pull/4315)
