### ISSUE TITLE
Failed to extract bagisto

### ISSUE THREAD

**Issue by MattWithCurls** [bagisto/bagisto#4218]
So when i create a new project its complaining about arrow-down.svg cause there is another file in the images folder with the same name but with different capitalisation and fails to unzip. Im guessing one of those files have to be deleted. 

Snippet of error is attached.
![Screenshot 2020-11-01 at 19 00 56](https://user-images.githubusercontent.com/36450476/97809478-c9f59b80-1c75-11eb-9e64-8b7979666a25.png)

**Comment by vaishaliwebkul** [comment]
@MattWithCurls 
This bug is already reported here https://github.com/bagisto/bagisto/issues/4220 , and fixed, you may take pull from the referenced PR.
