### ISSUE TITLE
Paypal Smart error

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4219]
Client Id Use "sb" for testing.

![Captura de tela de 2020-11-01 23-15-59](https://user-images.githubusercontent.com/30912144/97823582-397c8280-1c98-11eb-85d9-c322e5518ac2.png)

**Comment by nicobi83** [comment]
@marcelowu 
Hi, In my local environment this bug does not exist and when I click on PayPal it starts correctly. I have not tested the payment but any issues as this are present when I click on payment button and the id is correct.

**Comment by marcelowu** [comment]
the id is test, sandbox

**Comment by marcelowu** [comment]
Error : Expected an order id to be passed

**Comment by marcelowu** [comment]
erro paypal smart

![paypal](https://user-images.githubusercontent.com/30912144/99152978-2304fc80-2684-11eb-94ab-ec5cd2be9dae.PNG)

**Comment by ghermans** [comment]
@marcelowu you closed this issue 3days ago, so could you please provide us some details why this issue has been reopened?
Thanks in advance

**Comment by marcelowu** [comment]
switched button, sandbox vs production

**Comment by marcelowu** [comment]
and error

![Captura de tela de 2020-11-23 13-13-42](https://user-images.githubusercontent.com/30912144/99986761-5fc0aa00-2d8e-11eb-96d7-d0819b1288d3.png)
