### ISSUE TITLE
Some image is same name just difference lowercase and uppercase.

### ISSUE THREAD

**Issue by minhnc12** [bagisto/bagisto#4220]
# Bug report

### Title
Some image is same name just difference lowercase and uppercase.

### Issue Description
When I try to clone new source code from master, it's show warning because some file image same same name, just difference uppercase.
I am cloning on MacOS, so default can't show both file(file name lowercase and uppercase).
I saw it's same content, file size.

You can see at (I show on latest tag 1.2.0),  it's same on master:
https://github.com/bagisto/bagisto/blob/v1.2.0/packages/Webkul/Shop/publishable/assets/images/Arrow-Down.svg
https://github.com/bagisto/bagisto/blob/v1.2.0/packages/Webkul/Shop/publishable/assets/images/arrow-down.svg

https://github.com/bagisto/bagisto/blob/v1.2.0/packages/Webkul/Shop/publishable/assets/images/Logo.svg
https://github.com/bagisto/bagisto/blob/v1.2.0/packages/Webkul/Shop/publishable/assets/images/logo.svg

https://github.com/bagisto/bagisto/blob/v1.2.0/packages/Webkul/Shop/src/Resources/assets/images/Arrow-Down.svg
https://github.com/bagisto/bagisto/blob/v1.2.0/packages/Webkul/Shop/src/Resources/assets/images/arrow-down.svg

https://github.com/bagisto/bagisto/blob/v1.2.0/packages/Webkul/Shop/src/Resources/assets/images/Logo.svg
https://github.com/bagisto/bagisto/blob/v1.2.0/packages/Webkul/Shop/src/Resources/assets/images/logo.svg

What is the reason to keep going? If it's same should we merge it to one file?
Thank you so much.

**Comment by devansh-webkul** [comment]
On checking the assets, duplicated files are found. This will get merged to avoid duplicacy.

**Comment by MattWithCurls** [comment]
Doesn't seem like this bug is fixed yet.

**Comment by vaishaliwebkul** [comment]
@MattWithCurls 
How did you install the project again please mention step?

**Comment by ghermans** [comment]
> 
> 
> Doesn't seem like this bug is fixed yet. Created a new project and its the same issue.

@MattWithCurls since this has only been fixed in our GitHub repository you need to clone the Github repository once that is done execute
```
composer install
```
When the new release is out the fix will be available when using composer create-project or when you download Bagisto from our website.

**Comment by MattWithCurls** [comment]
@ghermans I did clone the repository and moved the cloned repository to the MAMP server and  executed composer install but getting this hardware instruction in the terminal. All the correct details are provided in the .env file.
![Screenshot 2020-11-03 at 16 47 09](https://user-images.githubusercontent.com/36450476/97999740-62b22580-1df4-11eb-8763-548a0e8ea89a.png)

**Comment by MattWithCurls** [comment]
@ghermans I've done all the steps that was required but when I execute  `php artisan migrate` it fails to migrate 2019_11_21_194541_add_column_url_path_to_category_translations. All the other tables are migrated but it stops at that one.

Thanks in advance.
![Screenshot 2020-11-03 at 16 57 54](https://user-images.githubusercontent.com/36450476/98001316-2a134b80-1df6-11eb-9ba6-39c3b6dc166f.png)

**Comment by MattWithCurls** [comment]
> @MattWithCurls
> How did you install the project again please mention step?

@vaishaliwebkul Thanks for your help though.

**Comment by vaishaliwebkul** [comment]
@MattWithCurls 
please raise a new bug if you're facing the issue in migration as the raised issue here is resolved now.

@minhnc12 closing this for now as it has been resolved.

Thanks
