### ISSUE TITLE
Bagisto versioning issue

### ISSUE THREAD

**Issue by purveshclone** [bagisto/bagisto#4226]
Hey there,

Nice package, had a small query regarding versioning of the same.

When, I am doing `php artisan bagisto:version`, then I am getting version as `1.2.0`), like shown below, (I have very recently fresh installed, bagisto/bagisto-standard repository as suggested in manual,
![image](https://user-images.githubusercontent.com/63946969/97982477-e02c6480-1df9-11eb-9fd7-c03aa34beac1.png)

But, when I check the same through composer (through `composer show bagisto/bagisto`), I am getting version as `1.1.2`, like shown below,
![image](https://user-images.githubusercontent.com/63946969/97982435-cbe86780-1df9-11eb-8809-da01f2a36fb1.png)

If my repository is at `v1.1.2`, then help me, how can I upgrade the same to `v1.2.0`

**Comment by vaishaliwebkul** [comment]
@purveshclone 
Hopefully, this guide will help you to upgrade the bagisto to the latest version https://devdocs.bagisto.com/1.x/introduction/upgrade_to_latest_bagisto.html

**Comment by purveshclone** [comment]
Thank you for your quick response,

Now, How can I Upgrade it through composer ?   
The page although lacks proper information, but as far as i have been able to understand, it suggests, replacing the complete project files and rebuilding it. This is good, when we are not customizing the application, but what if we have customized certain modules of the application.
A complete guide is missing I guess.

And why such difference of the version in application and in composer installation?

**Comment by devansh-webkul** [comment]
Hi @purveshclone,

There are several ways to install a project may I know how you installed your project like cloning from git or directly downloaded the zip from the site.

**Comment by purveshclone** [comment]
Hi,

I have just installed it by creating a project through composer, as specified in the docs, like below


![image](https://user-images.githubusercontent.com/63946969/97996644-0956f000-1e0e-11eb-9dbb-928614e17408.png)

**Comment by devansh-webkul** [comment]
Hi,

As I am seeing you are using the Bagisto standard. For that, you just need to edit the file `composer.json` and change the version.

~~~js
"bagisto/bagisto": "v1.2.0"
~~~

**Before executing anything just take a backup of your whole project and DB.**

Now, after editing the `composer.json` file have two options i..e,

1. Run `composer update`.

    **OR**

1. Delete or move `vendor` and `composer.lock` file somewhere else and then run `composer install`.

2. Then after run `php artisan migrate`.

3. Then run `php artisan vendor:publish --force`, this will give the listing of your all modules. Just type the number which you have not customized.

**Comment by purveshclone** [comment]
Hello, 
Are there any breaking changes, that I should take note of during the upgrade process?

**Comment by devansh-webkul** [comment]
Hi @purveshclone,

As such no breaking changes, but make sure to take all backup of your project and DB as well.

And please do the last step carefully as you have customized.

**Comment by devansh-webkul** [comment]
Hi @purveshclone,

Is your problem solved?

**Comment by purveshclone** [comment]
Hello,

I did the backup as specified and then ran `composer update`, but after its completion, I am facing following error,
![image](https://user-images.githubusercontent.com/63946969/98268547-a9e61500-1fb2-11eb-9a67-ab3d48c8d001.png)

Please guide me through.

**Comment by devansh-webkul** [comment]
Hi @purveshclone,

Just go to `bootstrap/cache` and delete all files except `.gitignore`. Then try again.

**Comment by purveshclone** [comment]
Hi,

I tried it but still getting the same error.

**Comment by devansh-webkul** [comment]
Hi,

Can you share your `composer.json` file?

**Comment by purveshclone** [comment]
Hi @devansh-webkul ,

this turns out to be a **legit bug**.

### Steps to reproduce, 
1. `composer create-project bagisto/bagisto-standard`
2. `php artisan bagisto:install`
3. Change version of `"bagisto/bagisto"` from `"v1.1.2"` to `"v1.2.0"` in `composer.json`
4. `composer update` (Tried with, clearing `bootsrap\cache\*`, deleting `vendor` and `composer.lock` as specified in the thread above.).

### Solution
The error mentioned in the thread occurs, because, of **Laravel's version upgrade from `v6` to `v7`**. With this upgrade, it is required for us to update `App\Exceptions\Handler` file, as mentioned in the [docs ](https://laravel.com/docs/7.x/upgrade#symfony-5-related-upgrades):
> First, the `report`, `render`, `shouldReport`, and `renderForConsole` methods of your application's `App\Exceptions\Handler` class should accept instances of the `Throwable` interface instead of `Exception` instances
I request to mention the same in the upgrade guide, as this is a breaking change.
> ```
> use Throwable;
> 
> public function report(Throwable $exception);
> public function shouldReport(Throwable $exception);
> public function render($request, Throwable $exception);
> public function renderForConsole($output, Throwable $exception);
> ```

### Other problems, we encountered,
1. Errors relating to missing packages in `dev` env after doing the `composer update`, 
1.1. **Debugbar**, `In ProviderRepository.php line 208: Class 'Barryvdh\Debugbar\ServiceProvider' not found`, when `composer update` is performed, within `php artisan package:discovery`.
1.2 **Faker\Factory**, `In DatabaseServiceProvider.php line 88: Class 'Faker\Factory' not found' not found`, when `composer update` is performed, within `php artisan package:discovery`.
**The packages mentioned above were somehow **removed**, when `composer update` was triggered**
**Now, to solve these**, I had to explicitly install the following two packages again, using,
A. `composer require barryvdh/laravel-debugbar --dev`
B. `composer require fzaninotto/faker --dev`
3. At last, we faced another breaking change, relating to `admin` login, earlier, the admin login took place at URL `/admin`, while, now, it's working at `/login` itself.

There should be a legit solution for problems we faced relating to missing packages, they should have removed ideally. Hence please, look onto the same and guide for the same.

Also, we need to update bagisto version either in `.env.example` from which the `.env` file is being generated and resulting version `1.2.0` when one does `php artisan bagisto:version` or `bagisto\bagisto-standard`'s `composer.json` file to avoid contradictions.

**Comment by devansh-webkul** [comment]
Hi @purveshclone,

So, your problem is solved now.

Please refer to this thread as well https://github.com/bagisto/bagisto/pull/4227.

And all these changes have already been done in master.

**Comment by purveshclone** [comment]
Yes, the problem has now been solved. 

I'd request you to please, update the upgrade guide, to contain, changes regarding `L7` upgrade, and `/admin` URL.

Regarding packages, since, patches are being merged on regular basis, I think, we should release them as soon as possible with newer versions, like, `v1.2.1`, `v1.2.2`, etc. And should update the upgrade guide to update `"bagisto\bagisto": "^1.2"` instead of `"bagisto\bagisto": "v1.2.0"`

**Comment by devansh-webkul** [comment]
Yeah sure!
