### ISSUE TITLE
I need to remove wishlist button from top header

### ISSUE THREAD

**Issue by Arafat-Thabet** [bagisto/bagisto#4237]
This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by jeanlinux** [comment]
@Arafat-Thabet pull from bagisto master branch, wishlist has been removed for now

**Comment by Arafat-Thabet** [comment]
I mean .
bagisto we need option in admin to controle show or hide wishlist  from site

**Comment by vaishaliwebkul** [comment]
@Arafat-Thabet 
As per your requirement this is already implemented , please check this https://github.com/bagisto/bagisto/issues/4136
to get the code you can pull from the master branch
