### ISSUE TITLE
Route [velocity.product.guest-wishlist] not defined.

### ISSUE THREAD

**Issue by jeanlinux** [bagisto/bagisto#4238]
# Bug report

### Guest Wishlist route not defined 
** I am running bagisto version 1.2.0 and everything seems to be working fine, I just pulled from bagisto master into my codebase and bagisto wont run any longer.**

### Expected result
** After pulling from bagisto master and fixing conflicts, I expected bagisto to run without errors**

### Actual result

>    **Loading bagisto after server started fails with error 
https://prnt.sc/vezn0d
**

* [points....]

**Comment by devansh-webkul** [comment]
Hi @jeanlinux,

Please run `php artisan route:cache`. Because wishlist for guest has been removed from master and your project's route loading from cache.

**Comment by jeanlinux** [comment]
I did, but I am still facing the same issue, I actually tried `php artisan route:cache` before posting the issue. I also did a search for velocity.product.guest-wishlist string in my project to see where the route was defined but nothing under route definition.

**Comment by devansh-webkul** [comment]
@jeanlinux 

Did you published your package's view files.

If you have not customized your themes, then simply run `php artisan vendor:publish --all --force`.

Otherwise you need to manually remove that route from the view.

**Comment by jeanlinux** [comment]
Thanks, that fixed it.
