### ISSUE TITLE
as leading open-source e-commerce, You must provide a mega menu

### ISSUE THREAD

**Issue by AkashWeybee** [bagisto/bagisto#4239]
as leading open-source e-commerce, You must provide a mega menu
![image](https://user-images.githubusercontent.com/53002296/98433231-16fcc600-20eb-11eb-8bb9-588f85c2a73f.png)

**Comment by zainawanworktech** [comment]
Please add mega menu - textarea with image upload and file manager - improve documentation (important vue js)

**Comment by AkashWeybee** [comment]
Why this is in Low priority?

**Comment by vaishaliwebkul** [comment]
@AkashWeybee 
Priority always says to fix application bugs first, as there is already a lot of enhancement & features reported day by day, Which for sure implemented as soon as possible by us.
You will get this feature soon & surely get implemented before the next release.

**Comment by asad561** [comment]
@vaishaliwebkul 
Mam, now it's been a year we developer didn't receive any updates for the mega menu as nowadays it is necessary for almost all websites have a mega-menu so please update priority low to high thanks. @AkashWeybee hey do you find any solution for this if yes so please share with me I'm damn sucked in this thing thanks

**Comment by jitendra-webkul** [comment]
This will not be included in the core package, we will implement this as a new package in the future.

**Comment by AkashThoriya** [comment]
> @vaishaliwebkul Mam, now it's been a year we developer didn't receive any updates for the mega menu as nowadays it is necessary for almost all websites have a mega-menu so please update priority low to high thanks. @AkashWeybee hey do you find any solution for this if yes so please share with me I'm damn sucked in this thing thanks

Yes I already solved for me

**Comment by yogicodex** [comment]
why is it labeled as won't be fixed!!

**Comment by devansh-webkul** [comment]
This is already provided in v2.x veriosn.

**Comment by yogicodex** [comment]
is it in core package, if not how can i add in my store! please provide a guide

**Comment by devansh-webkul** [comment]
It is by default their. You just need to arrange your category.
