### ISSUE TITLE
Make better UI

### ISSUE THREAD

**Issue by alighasemzadeh** [bagisto/bagisto#424]
Hello
I think Bagisto need better UI.
Please make modern UI for it.

**Comment by prashant-webkul** [comment]
@alighasemzadeh For sure.
We are making it better day by day on both frontend and backends, check for new releases.

**Comment by alighasemzadeh** [comment]
@prashant-webkul 
no it is really old.
sth like digikala.com is good

**Comment by prashant-webkul** [comment]
@alighasemzadeh We are understanding your concern. But if you see the code there is a separate module in packages called "Themes". By using this package you can make your own theme and publish it separately for your own storefront.

**Comment by twf-nikhila** [comment]
@prashant-webkul Theme looks good to me...Which theme is used here? Is it production ready?
