### ISSUE TITLE
Can I just refund an amount not an item?

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#4241]
for example, I have an order with phone and ipad. total is $1000. I just want to refund $50, Any ways I can do it? For now, when I change refund amount to all 0. I can't refund any more. I have to refund some amount from an item, but the amount refunded will be 1 or something.

**Comment by bhanu-webkul** [comment]
Hi @lYesterdaYl ,
As of now you can refund only shipping amount without refunding items, but its good point and should be implemented
so we need to add one more button to update totals like like we have update quantities and accordingly we can add this feature  like:

![Screenshot from 2020-11-09 12-55-35](https://user-images.githubusercontent.com/52821836/98511757-3b8fa400-228b-11eb-92bd-f1708b00785c.png)

**Comment by ghermans** [comment]
@rahulcs0082 do you have any update on this enhancement?

**Comment by ghermans** [comment]
@rahulshukla-webkul do you have any update on this enhancement?

**Comment by rahulshukla-webkul** [comment]
Hi @ghermans @lYesterdaYl 

Right now, this thing is not in our product.
As this is a user specific requirement so a user can customise it accordingly.
