### ISSUE TITLE
option to add video in advertisement and product gallery

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4250]
https://forums.bagisto.com/topic/225/video-in-product-gallery

**Comment by vaishaliwebkul** [comment]
video section added for products https://prnt.sc/vp80n8 , so closing this.

**Comment by tsaini530** [comment]
@vaishaliwebkul   could you guide to me add this section to my project. I cant see this section in my product module  as well as  in the seller product module

**Comment by vaishaliwebkul** [comment]
@tsaini530 
Yes of course, this functionality has been added in master/development branch.
May I know you Bagisto version?

**Comment by tsaini530** [comment]
1.2.0

**Comment by tsaini530** [comment]
I can't find the video section in my project. I used the bagisto multi-vendor package.

**Comment by vaishaliwebkul** [comment]
@tsaini530 
if you are using the multivendor package as well then you need to wait till the next release comes as the video feature will be added in next release.
