### ISSUE TITLE
Incorrect currency format showing comma instead of dot

### ISSUE THREAD

**Issue by tarkumar** [bagisto/bagisto#4252]
Having issue with money format Incorrect currency format showing comma instead of dot.

**Comment by bhanu-webkul** [comment]
@tarkumar  could you please mention currency name which you are using

**Comment by tarkumar** [comment]
@bhanu-webkul i am using INR

**Comment by bhanu-webkul** [comment]
@tarkumar it's working fine in master as well as in version 1.2.0 - https://prnt.sc/vh99l3

**Comment by ghermans** [comment]
Closing this one since there has been no response during the last 10days.
