### ISSUE TITLE
BUG CACHE in news controllers

### ISSUE THREAD

**Issue by vitorhugosg** [bagisto/bagisto#4258]
Hello, how are you?
I bought the marketplace not being able to enter the support platform, I already sent an email sending the purchase ID but without success.

I have a CACHE problem in the new controllers that I need to do.

How do I disable this cache that comes embedded in the product and seelers tables.

If you can contact me at: vitorhugosg@levantelab.com.br

To solve the support issue, as we bought the software a while ago, however, we only started the development of the tool now. Thanks in advance.

**Comment by saurav-webkul** [comment]
HI @vitorhugosg 

Could you please raise a support ticket here and also do mention the Order ID: https://bagisto.uvdesk.com/en/customer/create-ticket/
