### ISSUE TITLE
exception while updating with master branch

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4260]
# Bug report

![Screenshot_127](https://user-images.githubusercontent.com/43210406/99230086-e0265e80-2814-11eb-9dc2-ecbbc534a63a.png)

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Please run `composer dump-autoload`.

**Comment by vaishaliwebkul** [comment]
fixed
