### ISSUE TITLE
Category Insert issue

### ISSUE THREAD

**Issue by zainawanworktech** [bagisto/bagisto#4273]
![b5400b94-1b0e-4fd3-b050-c27bc60d13e8-image](https://user-images.githubusercontent.com/72428261/99558175-45c94500-29e5-11eb-972f-0c099158458e.png)
![a7ac4e2b-c34a-494b-9029-47bf2ab56941-image](https://user-images.githubusercontent.com/72428261/99558183-46fa7200-29e5-11eb-8a05-3820772dc0bb.png)
![587015f9-c6a6-4d44-b2a4-b1f4ead5d52d-image](https://user-images.githubusercontent.com/72428261/99558185-47930880-29e5-11eb-8577-bc8e543a8804.png)

**Comment by mo7amedmamdouh** [comment]
@zainawanworktech can u check if the DB has get_url_path_of_category
![image](https://user-images.githubusercontent.com/15470492/99592931-8d59cc00-29f9-11eb-9c6d-76d764ed360e.png)

**Comment by devansh-webkul** [comment]
Hi @zainawanworktech,

May, I know what you are trying to do?

Are you creating a new database or something else?

If you are creating a new one please use `utf8_unicode_ci` collation.

**Comment by zainawanworktech** [comment]
I m try all solution  you have provide the bagisto forum .Sent from my Galaxy
-------- Original message --------From: Devansh <notifications@github.com> Date: 11/19/20  12:01 PM  (GMT+05:00) To: bagisto/bagisto <bagisto@noreply.github.com> Cc: zainawanworktech <zain.awan@work-tech.co>, Mention <mention@noreply.github.com> Subject: Re: [bagisto/bagisto] Category Insert issue (#4273) 
Hi @zainawanworktech,
May, I know what you are trying to do?
Are you creating a new database or something else?
If you are creating a new one please use utf8_unicode_ci collation.

**Comment by devansh-webkul** [comment]
Hi @zainawanworktech,

I have checked the forum, please share steps what you are doing so that I can reproduce the issue.

**Comment by zainawanworktech** [comment]
Please send the all steps with details Sent from my Galaxy
-------- Original message --------From: Devansh <notifications@github.com> Date: 11/19/20  12:25 PM  (GMT+05:00) To: bagisto/bagisto <bagisto@noreply.github.com> Cc: zainawanworktech <zain.awan@work-tech.co>, Mention <mention@noreply.github.com> Subject: Re: [bagisto/bagisto] Category Insert issue (#4273) 
Hi @zainawanworktech,
I have checked the forum, please share steps what you are doing so that I can reproduce the issue.

**Comment by vaishaliwebkul** [comment]
@zainawanworktech 
As reported on the support ticket this is resolved now, so closing this.
