### ISSUE TITLE
Getting wrong price and currency when we change currency on place order

### ISSUE THREAD

**Issue by testforpostman7** [bagisto/bagisto#4282]
Hello,

   When I am adding item into cart at that time i am selecting currency to dollar and then I am changing that currency to rupees and place order. After successfully place order I am getting wrong total in customer orders as well as in customer email template.

Please check attached screen shot of customer order screen.

![ecommorder](https://user-images.githubusercontent.com/61349669/99767589-4c60d500-2b29-11eb-9222-35252405a978.png)

In that I am adding Man Tshirt product with 2 quantity of price 8 dollar with dollar currency after that we change currency to rupees and place order but I am getting wrong currency symbol and wrong price in customer order. 

Anyone please suggest me a solution.

Thanks.

**Comment by bhanu-webkul** [comment]
@testforpostman7 
Could you please mention bagisto version ?

**Comment by testforpostman7** [comment]
@bhanu-webkul I am using v0.1.0 version of bagisto.

**Comment by vaishaliwebkul** [comment]
@testforpostman7 
Please cross-check with the master branch or bagisto v1.2.0, this error doesn't exist and working fine.
