### ISSUE TITLE
product zoom issue for some images

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4283]
# Bug report

### Title
When trying to zoom in image vertically then zoom is not working properly

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- try to zoom the image vertically

### Expected result

image zoom should work properly for all type of uploaded image

### Actual result
currently not working as expected

**Comment by vaishaliwebkul** [comment]
product zoom functionality is removed https://prnt.sc/vouw26 , please check

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
zoom event is not working when changing mouse hover from video to image.

**Comment by vaishaliwebkul** [comment]
video moves to the header when click on it https://prnt.sc/vzh7by , kindly fix this.

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

I am not able to reproduce that.
