### ISSUE TITLE
Newsletter module understanding

### ISSUE THREAD

**Issue by agamitest** [bagisto/bagisto#4286]
I enabled newsletter subscription from Admin panel (Configure > Customer > Settings > Allow NewsLetter Subscription). Once enabled, it allows users to subscribe for Newsletter. Now i tried to find how to send the newsletter (from admin panel) to all subscribed users on their email but i could not find it. Please let me know how to send NewsLetter to all subscribed users from admin panel.

Thanks

**Comment by ghermans** [comment]
Hi @agamitest we are improving the newsletter feature and will provide proper documentation with the next release.

https://github.com/bagisto/bagisto/pull/4429

**Comment by vaishaliwebkul** [comment]
Hi @agamitest 
As @ghermans stated, this feature has been added to the master branch & available with the next release.

Closing this as implemented now.

Thanks.
