### ISSUE TITLE
277 duplicate query runs when loading 21 product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4289]
![Workspace_1_087](https://user-images.githubusercontent.com/45203177/99936543-639dfd80-2d89-11eb-8b14-4118d53e683e.png)

**Comment by waqar-ahmed** [comment]
Hi, I am new to bagisto and would like to contribute as well to get deeper understanding. Could I get a bit more explanation so, maybe I can create a pull request for this issue? Thank you.

**Comment by rahulcs0082** [comment]
HI @waqar-ahmed 

You can follow our documentation to get a deeper understanding of bagisto - https://devdocs.bagisto.com/
and we are expecting to see your PR soon.

You can also raise your query at - https://forums.bagisto.com/ and can also join our Facebook group- https://www.facebook.com/groups/bagisto/

Thanks
Rahul Shukla

**Comment by jyoti-webkul** [comment]
- Fixed
