### ISSUE TITLE
121 duplicate query when adding product in wishlist.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4290]
![Workspace 1_093](https://user-images.githubusercontent.com/45203177/99949386-f302db00-2da0-11eb-8f82-3ebd9313ee06.png)

**Comment by devansh-webkul** [comment]
The problem is not with adding a wishlist because when adding a wishlist page is refreshing. Duplicated queries only found whenever the product is loading whether it's from `category-slug` or the normal home page.

**Comment by jyoti-webkul** [comment]
- Fixed

--------------------------------------
