### ISSUE TITLE
Warning! Minimum order amount is R$ 0,00.

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4292]
![Captura de tela de 2020-11-23 14-08-05](https://user-images.githubusercontent.com/30912144/99992777-8f26e500-2d95-11eb-890e-d470ba16388f.png)

# Bug report
### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by devansh-webkul** [comment]
@marcelowu,

Please update with the master. This issue has been fixed.

**Comment by marcelowu** [comment]
English is ok, pt_BR not

**Comment by devansh-webkul** [comment]
Currency is checking with the float values so there is no point to check with the string as well. Please check these issues already fixed.

**Comment by marcelowu** [comment]
![Captura de tela de 2020-11-24 01-51-14](https://user-images.githubusercontent.com/30912144/100050153-9e3e7f00-2df7-11eb-8d9c-e485343c2d44.png)

**Comment by marcelowu** [comment]
![Captura de tela de 2020-11-24 01-52-21](https://user-images.githubusercontent.com/30912144/100050241-ba422080-2df7-11eb-9e52-f31c77811a16.png)

**Comment by marcelowu** [comment]
![Captura de tela de 2020-11-24 01-53-49](https://user-images.githubusercontent.com/30912144/100050318-ea89bf00-2df7-11eb-84f1-a852ef248e9a.png)

**Comment by vaishaliwebkul** [comment]
@marcelowu 
please confirm if this resolve??

**Comment by marcelowu** [comment]
sometimes it appears, every other hour,

![Captura de tela de 2020-11-26 02-31-20](https://user-images.githubusercontent.com/30912144/100311996-d8428900-2f8f-11eb-88a3-ec2c988c6d49.png)

**Comment by devansh-webkul** [comment]
Are you working in git different branches? It seems like one of your branches is not up to date with the master.

**Comment by marcelowu** [comment]
https://github.com/bagisto/bagisto/archive/master.zip today

**Comment by devansh-webkul** [comment]
@marcelowu,

I am not able to reproduce this in master. Please check your caches.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
open the storefront in an incognito window then checkout for any product, you will get the same issue as reported by @marcelowu 
![Screenshot_158](https://user-images.githubusercontent.com/43210406/100366341-bb0cc980-3026-11eb-8d87-efb339612aed.png)
