### ISSUE TITLE
❌ color_label return null on Product Resources (API)

### ISSUE THREAD

**Issue by kian92** [bagisto/bagisto#4293]
In the product_flat table, each product will have size, color, and so on so forth. 

/Webkul/API/Http/Resources/Catalog/Product.php

In this Product.php file, by default, it never displays color and size.

So I manually added, and the color_label return null even though there is color in the product_flat table
`'color'                  => $this->color_label,`
`'size'                   => $this->size_label,`

Attached is the screenshot of the code I added, to reproduce you can add the code as I did, and make sure the product has a color selection

<img width="846" alt="Screenshot 2020-11-24 at 9 49 16 AM" src="https://user-images.githubusercontent.com/6831009/100036113-8c320000-2e3a-11eb-93cf-2db5ed2b67a0.png">

**Comment by rahulcs0082** [comment]
Hi @kian92

You don't need to add it, we are already fetching super attributes of product in the given file (line - 52,53).

`$this->mergeWhen($product->getTypeInstance()->isComposite(), [
                'super_attributes' => Attribute::collection($product->super_attributes),
            ]),`

It will fetch all attributes of product etc-size, colour.

**Comment by kian92** [comment]
> Hi @kian92
> 
> You don't need to add it, we are already fetching super attributes of product in the given file (line - 52,53).
> 
> `$this->mergeWhen($product->getTypeInstance()->isComposite(), [ 'super_attributes' => Attribute::collection($product->super_attributes), ]),`
> 
> It will fetch all attributes of product like-size, colour.

hi @rahulcs0082 , thanks for the reply.

**I don't think the super attributes are very useful. Please take a look at my API response. It displays all the colors instead.**
<img width="846" alt="Screenshot 2020-11-24 at 1 44 53 PM" src="https://user-images.githubusercontent.com/6831009/100053706-8ef11d00-2e5b-11eb-88e1-aa700b9930b4.png">

**For my product id = 25, I only have 2 variants which are Red & Purple.**
![Screenshot 2020-11-24 at 1 45 21 PM](https://user-images.githubusercontent.com/6831009/100053780-b0ea9f80-2e5b-11eb-9dcc-6dbe69427434.png)

**Comment by kian92** [comment]
hi @rahulcs0082 , I able to get the data after I restart my computer. I will close this for now. thanks
