### ISSUE TITLE
add video error

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4294]
video mp4 10.4MB

![Captura de tela de 2020-11-24 01-55-39](https://user-images.githubusercontent.com/30912144/100050466-3fc5d080-2df8-11eb-8a30-6d54791890b0.png)
![Captura de tela de 2020-11-24 01-55-24](https://user-images.githubusercontent.com/30912144/100050471-40f6fd80-2df8-11eb-99db-81a31aae9343.png)

# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by rahulcs0082** [comment]
Hi @marcelowu 

In php. ini file search the keyword upload_max_file size and update its value to the desired file size of a single attachment of largest size. By default, its value is set to 2 MB maximum.

and you need to remove the validation as well in **ProductForm.php** in Product package.

**Comment by marcelowu** [comment]
![Captura de tela de 2020-11-24 02-08-14](https://user-images.githubusercontent.com/30912144/100051141-ee1e4580-2df9-11eb-8c02-2c215e8866d2.png)

**Comment by rahulcs0082** [comment]
Hi @marcelowu 

`upload_max_filesize` sets the max file size that a user can upload while  `post_max_size` sets the maximum amount of data that can be sent via a POST in a form.

So you can set `upload_max_filesize` to 1 meg, which will mean that the biggest single file a user can upload is 1 megabyte, but they could upload 5 of them at once if the `post_max_size` was set to 5.

**Comment by marcelowu** [comment]
ok.

![Captura de tela de 2020-11-24 11-10-19](https://user-images.githubusercontent.com/30912144/100105055-b0470e80-2e45-11eb-9abf-b8a04576cfd5.png)

**Comment by rahulcs0082** [comment]
Hi @marcelowu

We have added maximum upload file size validation from the configuration, now you can set it from admin panel. ( https://prnt.sc/vp9dhg )

**Comment by marcelowu** [comment]
good
