### ISSUE TITLE
Simple address from Laravel

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4303]
https://github.com/fndmiranda/simple-address

![Captura de tela de 2020-11-24 15-15-42](https://user-images.githubusercontent.com/30912144/100135114-f2814780-2e67-11eb-8a9d-3ae7642995b9.png)
![Captura de tela de 2020-11-24 15-15-19](https://user-images.githubusercontent.com/30912144/100135122-f4e3a180-2e67-11eb-836e-4a6ad5ab9401.png)

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by devansh-webkul** [comment]
Hi @marcelowu,

It will be nice to share some explanation about how it will help to improve the package.

**Comment by marcelowu** [comment]
address search by postcode read in Brazilian

**Comment by devansh-webkul** [comment]
Hi @marcelowu,

For searching, we have already given an elastic search and algolia.  But this is a specific requirement and varies according to the user. Users can self customize this.

**Comment by marcelowu** [comment]
do not search, is address filling
![Captura de tela de 2020-11-26 02-49-40](https://user-images.githubusercontent.com/30912144/100312892-340e1180-2f92-11eb-8d8d-cfe409c052da.png)
https://github.com/adevecchi/consulta-cep-laravel

**Comment by marcelowu** [comment]
enter zip code and address appears

**Comment by ghermans** [comment]
Unfortunately, this feature request does not fit in the standard version of Bagisto as this does not offer added value for **all end users**.

If you still want us to develop this as an extension, you can always create a ticket https://bagisto.uvdesk.com/en/customer/create-ticket/
