### ISSUE TITLE
possible integrate this custom shipping method in bagisto

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4304]
https://github.com/flyingluscas/correios-php

https://m.correios.com.br/enviar-e-receber/ferramentas/calculador-remoto-de-precos-e-prazos/pdf/manual-de-implementacao-do-calculo-remoto-de-precos-e-prazos

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by ghermans** [comment]
@marcelowu we do not integrate third party shipping methods by default, you can create a ticket for this type of customization at https://bagisto.uvdesk.com/en/customer/create-ticket/ or you can write your own package https://devdocs.bagisto.com/1.x/packages/create_package.html
