### ISSUE TITLE
need a hand on making all same attributes get the same image for variants

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#4308]
hi , the problem starts from when u have a configurable product with like 40 variants . 4 color and 10 size on each .
now on images consider that the one who is inserting the images should probably insert 9 extra image on each color and on high number of products that would be waste of hours .
now what i want to do is these steps :
1-to take a product from database .
2- get the products in a same color .
3-check if one of that products has image 
4- and finally set the image for all other products in that color
so when the operator just insert image for 1 color he can pres a bottun and the same images will be set for other sizes : 
if i can find step 1-2 it would be fine too i think and i would make pr for that

**Comment by devansh-webkul** [comment]
Hi @farshadff,

For step 1, you can get from the `Product` model. But can you explain what step 2 is? You want all products of the same color or something else.

**Comment by farshadff** [comment]
Thanks for the answer. Consider I have an specific product like I'd 20 which is a configurable product. This product have some variants. I want to get the variants with the same color

**Comment by devansh-webkul** [comment]
Hi @farshadff,

Why don't you fetch all variants at the same time and place in a variable? Then use laravel collection's method and filter the color on the basis of key so that you don't want to go again to the database.

**Comment by farshadff** [comment]
@devansh-webkul let me please explain you completly what i want to do
