### ISSUE TITLE
new product home page  undefined 404 (Not Found)

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4311]
new product home page 
undefined 404 (Not Found)

![Captura de tela de 2020-11-25 11-35-22](https://user-images.githubusercontent.com/30912144/100241791-dc7c9100-2f12-11eb-956a-77f6e6a653ba.png)
![Captura de tela de 2020-11-25 11-35-37](https://user-images.githubusercontent.com/30912144/100241869-f0c08e00-2f12-11eb-9de5-2c83ae08fd03.png)
![Captura de tela de 2020-11-25 11-39-40](https://user-images.githubusercontent.com/30912144/100241915-fb7b2300-2f12-11eb-836e-883e87eb6b78.png)
![Captura de tela de 2020-11-25 11-36-01](https://user-images.githubusercontent.com/30912144/100241996-1057b680-2f13-11eb-8bbb-5112b770af78.png)

# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by devansh-webkul** [comment]
@marcelowu,

Please scroll down to the bottom and check new products are loading or not because this is not an issue.

**Comment by marcelowu** [comment]
![Captura de tela de 2020-11-26 01-19-28](https://user-images.githubusercontent.com/30912144/100307765-72e99a80-2f85-11eb-89b2-ec44d244705f.png)

**Comment by marcelowu** [comment]
ok,
