### ISSUE TITLE
save-order 500 Internal Server Error

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4312]
payment plugins were normal, https://github.com/cagartner/bagisto-pagseguro
I don't know why this error appeared

![Captura de tela de 2020-11-25 12-13-25](https://user-images.githubusercontent.com/30912144/100246716-4481a600-2f18-11eb-8a3e-68390100a9a6.png)

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by marcelowu** [comment]
tested with other plugins is the same

![Captura de tela de 2020-11-25 13-26-06](https://user-images.githubusercontent.com/30912144/100255208-fffb0800-2f21-11eb-91a9-e4bbf95c086f.png)

**Comment by devansh-webkul** [comment]
Hi @marcelowu,

I need steps for what you are doing. So that I can reproduce this.

**Comment by marcelowu** [comment]
plugins payment not work

**Comment by devansh-webkul** [comment]
@marcelowu,

Then there is something wrong with integrating this. Please check the backend or send some logs so that it can be reproducible.

**Comment by marcelowu** [comment]
2020-11-26 10:44:39] local.ERROR: Route [pagseguro.redirect] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [pagseguro.redirect] not defined. at /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:420)
[stacktrace]
#0 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(768): Illuminate\\Routing\\UrlGenerator->route()
#1 /var/www/html/bagisto/vendor/cagartner/bagisto-pagseguro/src/Payment/PagSeguro.php(275): route()
#2 /var/www/html/bagisto/packages/Webkul/Payment/src/Payment.php(69): Cagartner\\Pagseguro\\Payment\\PagSeguro->getRedirectUrl()
#3 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Webkul\\Payment\\Payment->getRedirectUrl()
#4 /var/www/html/bagisto/packages/Webkul/Shop/src/Http/Controllers/OnepageController.php(190): Illuminate\\Support\\Facades\\Facade::__callStatic()
#5 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Webkul\\Shop\\Http\\Controllers\\OnepageController->saveOrder()
#6 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#9 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#10 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/html/bagisto/packages/Webkul/Shop/src/Http/Middleware/Currency.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Webkul\\Shop\\Http\\Middleware\\Currency->handle()
#13 /var/www/html/bagisto/packages/Webkul/Shop/src/Http/Middleware/Theme.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Webkul\\Shop\\Http\\Middleware\\Theme->handle()
#15 /var/www/html/bagisto/packages/Webkul/Shop/src/Http/Middleware/Locale.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Webkul\\Shop\\Http\\Middleware\\Locale->handle()
#17 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#19 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#21 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#23 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#25 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#27 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#28 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#29 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#30 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#31 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#32 /var/www/html/bagisto/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#34 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#36 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#37 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#39 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#41 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#43 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#45 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#46 /var/www/html/bagisto/public/index.php(74): Illuminate\\Foundation\\Http\\Kernel->handle()
#47 {main}
"}

**Comment by devansh-webkul** [comment]
@marcelowu,

For the error log, it's not an issue with the Bagisto. Please check your integration.

**Comment by marcelowu** [comment]
ok

**Comment by marcelowu** [comment]
problem is in laravel-pwa installed

**Comment by marcelowu** [comment]
no pwa, is works
