### ISSUE TITLE
get all product variants with the same color (attribute value) 

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#4314]
hi in `configurableOption.php` helper i am making some changes . i have 1 variant id and i need to get all the other variants or that product with the same color . i want to know if there any relation for that so i can get the `configurable` product and then loop on variants and find the same variants on color . thanks in advance

**Comment by devansh-webkul** [comment]
You already raised this in one issue, please follow one thread for better communication.

**Comment by devansh-webkul** [comment]
Communication is going on this issue #4308.
