### ISSUE TITLE
Implement buy now functionality in velocity theme

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4321]
# Bug report

### Title
There should be a 'Buy Now' Button available along with 'Add to cart' button in velocity theme which is already implemented in default theme.

### Preconditions

    1. framework Version- master

### Expected result
Add buy now button on product page

### Actual result
![Screenshot_160](https://user-images.githubusercontent.com/43210406/100451278-2022f680-30dd-11eb-97d1-1925fc0122bc.png)

**Comment by ghermans** [comment]
@vaishaliwebkul what do you think about making this optional so that the admin can choose if he wants to display this button or not

**Comment by vaishaliwebkul** [comment]
@ghermans 
Yes, great to have an option in the backend to show/hide this button for both theme.
