### ISSUE TITLE
how do add a shortcut bagisto on  smartphone

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4323]
exemple:
![Captura de tela de 2020-11-27 23-27-14](https://user-images.githubusercontent.com/30912144/100492171-7eb19a00-3108-11eb-8a76-dfa27f20ba20.png)

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by saurav-webkul** [comment]
Hi @marcelowu 

Are you referring to use bagisto eCommerce as PWA so as to create a shortcut on the home screen?

**Comment by marcelowu** [comment]
really bagisto, not laravel / pwa

**Comment by ghermans** [comment]
As @saurav-webkul mentioned we have [Bagisto PWA](https://github.com/bagisto/laravel-pwa) or the [Bagisto mobile app](https://store.webkul.com/bagisto-laravel-mobile-app.html) that you can use for this.
