### ISSUE TITLE
vue-social-chat

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4324]
https://github.com/ktquez/vue-social-chat

![Captura de tela de 2020-11-28 00-27-54](https://user-images.githubusercontent.com/30912144/100492941-a442a180-3110-11eb-9127-f9240f629a84.png)

![Captura de tela de 2020-11-28 00-27-21](https://user-images.githubusercontent.com/30912144/100492936-9856df80-3110-11eb-8fd7-04e2d235e789.png)

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by ghermans** [comment]
We will implement this feature in the upcoming Bagisto releases, as it can provide added value for users.

**Comment by ghermans** [comment]
an extension for Whatsapp is available https://bagisto.com/en/extensions/laravel-ecommerce-whatsapp-contact/
for Facebook messenger you can follow https://developers.facebook.com/docs/messenger-platform/discovery/facebook-chat-plugin/
