### ISSUE TITLE
payment plugins do not discount the coupon amount

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4328]
this payment plugins do not discount the coupon amount, https://github.com/cagartner/bagisto-pagseguro

![Captura de tela de 2020-11-30 16-41-30](https://user-images.githubusercontent.com/30912144/100658635-29ef6880-332e-11eb-8e76-d34dc279af08.png)

![Captura de tela de 2020-11-30 16-43-17](https://user-images.githubusercontent.com/30912144/100658665-35429400-332e-11eb-9cbc-81adc163d04c.png)
 
paypal is ok.

![Captura de tela de 2020-11-30 17-00-27](https://user-images.githubusercontent.com/30912144/100658705-44c1dd00-332e-11eb-8cda-4da7d49b81da.png)

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by ghermans** [comment]
Please report the issue at the repository of bagisto-pagseguro https://github.com/cagartner/bagisto-pagseguro/issues
