### ISSUE TITLE
i got error Linking Storage directory..

### ISSUE THREAD

**Issue by raic0d3r** [bagisto/bagisto#4336]
This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!
Step: Linking Storage directory...

In Filesystem.php line 265:

  symlink(): No such file or directory

**Comment by ghermans** [comment]
I guess that you are using something like homestead or vagrant?

1.Try to run powershell as administrator
2. Go to the directory where you put your installation of Bagisto and run the following command
```
php artisan storage:link
```

**Comment by raic0d3r** [comment]
one more thing how i change domain.com/public to
domain.com

**Comment by ghermans** [comment]
You can do that by updating the document root folder for your virtualhost 

http://httpd.apache.org/docs/current/mod/core.html#documentroot
https://www.nginx.com/resources/wiki/start/topics/examples/server_blocks/
