### ISSUE TITLE
Class 'Webkul\DebugBar\Providers\DebugBarServiceProvider' not found

### ISSUE THREAD

**Issue by aio-software** [bagisto/bagisto#4339]
# Bug report

### Title
Class 'Webkul\DebugBar\Providers\DebugBarServiceProvider' not found

### Issue Description
After running `php artisan config:cache` I get this error message:

In ProviderRepository.php line 208:

  Class 'Webkul\DebugBar\Providers\DebugBarServiceProvider' not found

### Preconditions
I updated till Commit 963191b3f

**Comment by devansh-webkul** [comment]
@aio-software 

Please run `composer install` and then try again.

**Comment by aio-software** [comment]
Thanks!
