### ISSUE TITLE
How to clone the database

### ISSUE THREAD

**Issue by Xoshbin** [bagisto/bagisto#4340]
Hi, I have a Bagisto app with more than a thousand products, Now I'm trying to clone the database to a new server. but the SQL query preventing to clone the app. I can export the SQL file, But I can't import it, it gives many errors with "foreign keys" starting with categories and the routing functions and then channels table and products table and customers and many more. I have tries to manually create some tables through SQL query or manually adding the tables. but it's useless because I can't recreate the foreign keys.
is there any solutions please?

**Comment by rahulshukla-webkul** [comment]
Hi @Xoshbin 

Can you provide your MySQL version ?

**Comment by Xoshbin** [comment]
Hi @rahulshukla-webkul It's:
1:10.2.33+maria~bionic

**Comment by devansh-webkul** [comment]
Hi @Xoshbin,

Please check with the version 10.2.7 or higher?
