### ISSUE TITLE
 A Laravel Nova Google Maps Field.

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4343]
https://github.com/mauricewijnia/nova-maps-address
Nova Maps Address is a Nova field that allows the user to select an adress using the Google Places API and store it in a JSON column.

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by ghermans** [comment]
This feature request does not fit in the standard version of Bagisto as we don't use [Nova](https://nova.laravel.com)
