### ISSUE TITLE
Attribute option positioning not working (Front-end)

### ISSUE THREAD

**Issue by kukocrunch** [bagisto/bagisto#4344]
# Bug report

### Title
**Positions of attribute options does not apply on front-end**

### Issue Description
**Re-arranging attribute positioning is working on admin product creation. but on the front-end, it does not follow the new arrangement**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1.  Bagisto v1.2.0

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

Admin : 
    1. Catalog > Attributes > Brand > Edit
    2. Add new option
    3. Change position of new option to '1'
   
Shop : 
    1. Go to Shop by Category
    2. Look for Brand
    3. You will notice that new position does not reflect with front-end

### Expected result
Re-arranged position should follow the new position to front-end selection.
![image](https://user-images.githubusercontent.com/7022294/101454786-7a894600-396c-11eb-81cf-9a8b3ec5da6a.png)

### Actual result

New Brand should be on top not at the bottom where all new options are placed.
![image](https://user-images.githubusercontent.com/7022294/101454345-cbe50580-396b-11eb-9b59-770ab62257bb.png)
![image](https://user-images.githubusercontent.com/7022294/101454630-3e55e580-396c-11eb-9f8b-3fe0e01b384c.png)

edit :: updated steps to reproduce

**Comment by bhanu-webkul** [comment]
@kukocrunch   

could you please mention bagisto version as its working absolutely fine in master

**Comment by kukocrunch** [comment]
@bhanu-webkul I'm using bagisto version version 1.2.0 
the screenshot is from the [Bagisto Demo](https://demo.bagisto.com) version 1.2.0 also.

I have also downloaded my version [here](https://bagisto.com/en/download/)
The position order does not sort on front-end

**Comment by ghermans** [comment]
Could you please try to install Bagisto from our master branch https://github.com/bagisto/bagisto/archive/master.zip and verify if you still experience this issue?

**Comment by kukocrunch** [comment]
@ghermans I tried master branch and did a clean setup, the problem is gone. Thank you!

I have upgraded my existing Bagisto 1.2.0 setup to master branch,

Upgrade was a success but I had error `Table product_videos doesn't exist` when viewing a product 
I ran `php artisan migrate` then the error went away.

**Comment by kukocrunch** [comment]
Hello! I upgraded from master [62b3aa99](https://github.com/bagisto/bagisto/commit/62b3aa99df1796a8cc7aff13ec418a18aae1814e)
to new version 1.3.0. The attribute arrangement problem is present again.

So I tried to do a clean installation of Bagisto 1.3.0.
Please see the screenshot below.

Admin Attribute Positioning 
![image](https://user-images.githubusercontent.com/7022294/108683314-6ba63e80-752c-11eb-81c2-cd1896785307.png)

Brand (EN) | Position
------------ | -------------
Uniqlo| 2
Bench | 3
Adidas | 4
Nike | 6
H&M | 5
Generic | 1


So here I added a new product.
![image](https://user-images.githubusercontent.com/7022294/108683071-1702c380-752c-11eb-9eaf-8a452e943a90.png)
![image](https://user-images.githubusercontent.com/7022294/108685933-b2496800-752f-11eb-85a0-55e7b6d3f433.png)

The expected result should be: 
_Adidas_ and _Nike_ brand must be below _Generic_ (according to Admin Attribute Position)

**Comment by rahulshukla-webkul** [comment]
Hi @kukocrunch 

We have fixed this one - https://github.com/bagisto/bagisto/pull/4667 and now options will be show according to their product avavilability.
