### ISSUE TITLE
Getting issue in category url generation

### ISSUE THREAD

**Issue by akshaypitale** [bagisto/bagisto#4347]
Hi,

I am getting issue in category url generation it gets when trying to create a new category.

It is working on local system.
I debug the issue , it seems I don't have proper permissions on database Function which creates category URL.
I talk to the hosting provider but they are saying they will not provide permission on MySQL Database Function because of security reasons.

Is there any work around for this ?

**Comment by vaishaliwebkul** [comment]
@akshaypitale 
could you please show the screenshot of the error getting while creating new category?

**Comment by akshaypitale** [comment]
> @akshaypitale
> could you please show the screenshot of the error getting while creating new category?

@vaishaliwebkul 

Below is the screenshot of the database function. 


![download](https://user-images.githubusercontent.com/23078428/101813413-b544d700-3b42-11eb-8555-83e379f24d2c.jpg)

**Comment by ghermans** [comment]
Hi @akshaypitale as @vaishaliwebkul asked, is it possible to also provide us the error you receive so that we can investigate this?

**Comment by akshaypitale** [comment]
> Hi @akshaypitale as @vaishaliwebkul asked, is it possible to also provide us the error you receive so that we can investigate this?

@ghermansError: MySQL said: #1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation IF NOT EXISTS ( SELECT id FROM categories WHERE id = categoryId AND parent_id IS NULL

**Comment by vaishaliwebkul** [comment]
@akshaypitale 
may I know your Mysql version?

**Comment by rahulshukla-webkul** [comment]
Hi @akshaypitale 

Either remove the `DEFINER=..` statement from your sqldump file, or replace the user values with `CURRENT_USER.`

The MySQL server provided by RDS does not allow a `DEFINER` syntax for another user (in my experience).

You can use a `sed` script to remove them from the file:

`sed 's/\sDEFINER=`[^`]*`@`[^`]*`//g' -i oldfile.sql`

**Comment by akshaypitale** [comment]
Thanks for the help @rahulshukla-webkul .
Replacing value with CURRENT_USER worked for me.

**Comment by elitedigitaltech** [comment]
I remove definer from phpmyadmin abut still its showing same error
