### ISSUE TITLE
Translation for persian language farsi

### ISSUE THREAD

**Issue by wikiccu** [bagisto/bagisto#4349]
Hello
I would ask you is there any plan for translation to the Persian/farsi language ?

**Comment by ghermans** [comment]
Translations for all other languages besides **English** are provided by contributors.
Please check https://bagisto.com/en/ecommerce-language-translation-in-bagisto/ in case you want to start translating it yourself.

**Comment by wikiccu** [comment]
it's ok thank you, so can I send my translated files with a PR for Persian translation here?

**Comment by ghermans** [comment]
Sure @wikiccu we are looking forward to your pull request.
