### ISSUE TITLE
after changing locale it is not returning to default english language

### ISSUE THREAD

**Issue by Zibon1992** [bagisto/bagisto#4351]
# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]
![locale_issue](https://user-images.githubusercontent.com/55887424/101909602-eaefcb80-3be7-11eb-97fe-834f4f448595.png)
![locale-issue](https://user-images.githubusercontent.com/55887424/101909607-ed522580-3be7-11eb-82b5-4e9fec70043a.png)

**Comment by ghermans** [comment]
@Zibon1992  please update the issue template with the requested information so that we can investigate this.

**Comment by vaishaliwebkul** [comment]
@Zibon1992 
once you changed the locale from admin configuration then to display in the front end you need to reopen the website URL in a private window or you can also restart chrome browser etc. to check the changes.
Although We have already fixed some issue on locale changes which will come in the next release, you can check this https://github.com/bagisto/bagisto/issues/3967
