### ISSUE TITLE
Swift is a modern programming language focused on safety, performance, and expressivity.

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4352]
https://github.com/swiftmailer/swiftmailer

![Captura de tela de 2020-12-11 12-22-09](https://user-images.githubusercontent.com/30912144/101921229-857de980-3bab-11eb-89d7-0fd79a9e717a.png)

This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by ghermans** [comment]
https://laravel.com/docs/7.x/mail#introduction
