### ISSUE TITLE
use postfix mail server on Ubuntu. how to configure

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4353]
![Captura de tela de 2020-12-11 13-50-28](https://user-images.githubusercontent.com/30912144/101931188-db588e80-3bb7-11eb-9a34-388b6f2d9b57.png)

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by ghermans** [comment]
Postfix provides a sendmail command for compatibility with the original sendmail (https://en.wikipedia.org/wiki/Sendmail).
As i already mentioned in your previous issue report #4352 you can follow the mail section from the Laravel documentation website https://laravel.com/docs/7.x/mail#configuration
