### ISSUE TITLE
Guest Checkout sucess add register 

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4356]
# Description
- [ ] Add a button on the order success page that redirects guests to the customer registration page
- [ ] Add previous orders that have been made as a guest to the customer after registration.

![Capturar](https://user-images.githubusercontent.com/30912144/101989802-99941a80-3c81-11eb-91a7-53fe0c88d026.PNG)

**Comment by marcelowu** [comment]
and also guest can add account future with purchases made before

**Comment by Sanjaybhattwebkul** [comment]
@ghermans 
This feature is **not implemented properly.** because the user is **not able to view the previous order**

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul  
Please look into it.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
Thanks, now this **issue is fixed**. so I am **closing** this issue.
And I have attached a **screenshot [Here](https://prnt.sc/xlWK6YAcJ_c6),** for future reference.
