### ISSUE TITLE
Admin Product copy returns 404

### ISSUE THREAD

**Issue by kukocrunch** [bagisto/bagisto#4358]
# Bug report

### Issue Description
**After upgrading bagisto to master branch. I can't use copy action from Admin Product.**

### Preconditions
    1. Bagisto version 1.2.0.
    2. commit id : 62b3aa99df1796a8cc7aff13ec418a18aae1814e

### Steps to reproduce
    1. Go to Admin , Select Catalog, Products 
    2. Select a product you want to copy
    3. On actions column click copy icon

![image](https://user-images.githubusercontent.com/7022294/102039027-b22c3e00-3e03-11eb-8fed-0a3a10447e4f.png)

![image](https://user-images.githubusercontent.com/7022294/102038911-709b9300-3e03-11eb-9740-be6ac79639c5.png)

Here's an exception thrown when 404 appears
```No query results for model [Webkul\Attribute\Models\Attribute].```
![image](https://user-images.githubusercontent.com/7022294/102038844-45b13f00-3e03-11eb-9b14-374fc8b1a94c.png)

### Expected result
> From website download version of bagisto, clicking copy would go to product creation with copied values from original product.

**Comment by vaishaliwebkul** [comment]
@kukocrunch 
Is there any custom attributes or heavy size image inside the original product?? or what type of product you are trying to copied?
as this feature seems to be working fine in master https://prnt.sc/w23q3s

**Comment by kukocrunch** [comment]
I don't have heavy size image with the original product and it's a simple type product. 
And the products that I am trying to copy have custom attribute family am I missing something?

**Comment by vaishaliwebkul** [comment]
@kukocrunch 
make sure you have done the below command after upgrading to master

- composer dump-autoload

- php artisan migrate

- php artisan vendor:publish --force & press 0 to continue.

- php artisan config:cache

**Comment by kukocrunch** [comment]
I have executed the commands you mentioned earlier, but I still got 404 problem.

- composer dump-autoload
``Generated optimized autoload files containing 7584 classes``

- php artisan migrate
``Nothing to migrate.``

- php artisan vendor:publish --force
``Publishing complete.``

- php artisan config:cache
``Configuration cache cleared!
Configuration cached successfully!``

**Comment by vaishaliwebkul** [comment]
@kukocrunch 
if all the above command are working then please tell us the steps to reproduce the steps this issue.

**Comment by kukocrunch** [comment]
@vaishaliwebkul 
I think this caused the error when I upgraded from official download version to master. 

My custom attribute family doesn't have `product_number` , `tax_category_id`, `guest_checkout`, 

![image](https://user-images.githubusercontent.com/7022294/102160351-3d6b0980-3ec0-11eb-9812-c77b6652c27d.png)

I can't reproduce the attribute family I have migrated to master version.

**Comment by kukocrunch** [comment]
below is the custom attribute family I currently have

Code | Name | Type 
------------ | ------------- |  ------------- 
sku | SKU | text
name | Name | text	
url_key | URL Key | text	
new | New | boolean	
featured | Featured | boolean	
visible_individually | Visible Individually | boolean	
status | Status | boolean	
ProductSeries | Series | select	
CoreWidth | Core Width | select	
QtyPerBundle | Qty/Bundle | select

**Comment by vaishaliwebkul** [comment]
@kukocrunch 
Kindly update if the mentioned bug has resolved?

**Comment by kukocrunch** [comment]
@vaishaliwebkul I'm still finding out how to resolve this issue I also tried downloading a recent commit from the master branch but the issue is still there.

**Comment by vaishaliwebkul** [comment]
@kukocrunch 
I would recommend you to download the separate application from the master branch https://github.com/bagisto/bagisto/tree/master then verify the issue if you're still experiencing the same issue.

As in master, there are various system attribute has been added which are not added in your custom family.

**Comment by kukocrunch** [comment]
Hello @vaishaliwebkul 

I did compare missing fields from website-download and master

I'm missing `Product Number` and `Brand` so I did add those two to 
admin/catalog/attributes now copy is working! 😅
