### ISSUE TITLE
GeneaLabs/laravel-model-caching

### ISSUE THREAD

**Issue by robinflyhigh** [bagisto/bagisto#4362]
Has anyone tried using GeneaLabs/laravel-model-caching library?

Bagisto is using kalnoy/nestedset which is not compatible with GeneaLabs/laravel-model-caching 

Is there a workaround?

**Comment by devansh-webkul** [comment]
@robinflyhigh,

Currently, Bagisto is on Laravel 7, and the `GeneaLabs/laravel-model-caching` docs say that its need to be on Laravel 8 as there repo has lots of bug in lower versions.

Not now but we will look into this once after the upgrade.
