### ISSUE TITLE
Customers phone not save

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4366]
![捕获2](https://user-images.githubusercontent.com/30912144/102264423-5db4bb80-3ef4-11eb-9b16-c897c1602783.PNG)

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by ghermans** [comment]
@marcelowu please use the issue template when you report a issue, as this helps us to investigate issues.

**Comment by devansh-webkul** [comment]
@ghermans,

It's working in master, may I know where it is not working.

![Screenshot from 2020-12-16 13-23-57](https://user-images.githubusercontent.com/68321766/102320277-1422aa00-3fa2-11eb-8a2e-ec4f4b8dbd65.png)

**Comment by ghermans** [comment]
@devansh-webkul i remember that this bug came up a while ago, but it has something todo with how the customer is created (admin,shop or velocity)

**Comment by marcelowu** [comment]
master, language pt_BR, and gender error

**Comment by marcelowu** [comment]
![捕获](https://user-images.githubusercontent.com/30912144/102364492-4548ad80-3f95-11eb-9d0d-8286185989e1.PNG)
![捕获2](https://user-images.githubusercontent.com/30912144/102364495-45e14400-3f95-11eb-8395-4f3354452e27.PNG)

**Comment by vaishaliwebkul** [comment]
@marcelowu 
once a new customer registered, phone number & gender fields need to fill out again by editing customer or by customer itself from profile.

**Comment by marcelowu** [comment]
![捕获](https://user-images.githubusercontent.com/30912144/102394999-53a8c080-3fb9-11eb-942f-0c411e4ca501.PNG)
![捕获2](https://user-images.githubusercontent.com/30912144/102395003-55728400-3fb9-11eb-8a9c-3fc302e66732.PNG)
![捕获3](https://user-images.githubusercontent.com/30912144/102395005-57d4de00-3fb9-11eb-860f-57f6d13f30b6.PNG)

**Comment by marcelowu** [comment]
![捕获](https://user-images.githubusercontent.com/30912144/102398956-b81a4e80-3fbe-11eb-9a29-0cc72b7e07ff.PNG)

**Comment by vaishaliwebkul** [comment]
@marcelowu 
once the customer is registered then the admin needs to fill out their phone number & gender by editing customer details.
I hope this has been fixed at your end.

Right now closing this as this is an invalid issue.
