### ISSUE TITLE
registered customer already has a name, so they can register again

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4367]
![捕获](https://user-images.githubusercontent.com/30912144/102297454-1519f400-3f2e-11eb-8f24-33d13ae9caa0.PNG)

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by ghermans** [comment]
This is already implemented, please use the master branch to verify.
