### ISSUE TITLE
Product filter [Shop By]

### ISSUE THREAD

**Issue by AkashWeybee** [bagisto/bagisto#4369]
# Bug report

### Issue Description
* As shown in screenshot - this particular attribute does not belong to any products.
![image](https://user-images.githubusercontent.com/53002296/102346143-6674c280-3fc4-11eb-8c53-9ccaeac7b966.png)

### Important things to remember 
* I did not select attributes in combination.
* Only one attribute is selected.

### Expected result
**Display only those attributes who belong to at least one or more products**
**This will directly affect user experience**
**Nowadays major e-commerce platform follows this pattern - You can check on Flipkart**

**Comment by devansh-webkul** [comment]
Hi @AkashWeybee,

Please refer to this issue,
https://github.com/bagisto/bagisto/issues/3950

**Comment by AkashWeybee** [comment]
> Hi @AkashWeybee,
> 
> Please refer to this issue,
> #3950

Not working in demo.
kindly check demo

**Comment by devansh-webkul** [comment]
Hi @AkashWeybee,

The demo is not updated with the master. Please refer to the above issue.

**Comment by AkashWeybee** [comment]
> Hi @AkashWeybee,
> 
> The demo is not updated with the master. Please refer to the above issue.



> Hi @AkashWeybee,
> 
> The demo is not updated with the master. Please refer to the above issue.

we cannot replace our entire code with master branch, 
can you tell me - what was the change?

**Comment by devansh-webkul** [comment]
Hi @AkashWeybee,

Please  refer to this PR i.e.,
https://github.com/bagisto/bagisto/pull/4017

**Comment by AkashWeybee** [comment]
A high level of dedication.
Thank you.

**Comment by AkashWeybee** [comment]
> Hi @AkashWeybee,
> 
> Please refer to this PR i.e.,
> #4017

A high level of dedication.
Thank you.

**Comment by AkashWeybee** [comment]
@ghermans @devansh-webkul 
The issue is resolved now but - it is not optimized at all.

Because currently, we have 10k products and the one category has approximate 3.5k to 4.5k products. Each attribute may have 1k+ values. [Electrical products]

we are targeting for 80k to 1 lakh products. [Electrical]
Each category will have approximate 10k products. Each attribute may have 2k+ values.

And you've used brute force approach to scan all products in the respective category.

Think innovative sir.

We are working on our side, I think, Together we will solve this issue.

**Comment by ghermans** [comment]
@AkashWeybee thanks for the feedback, i will reopen this issue so we can further investigate this.

**Comment by devansh-webkul** [comment]
Link: https://github.com/bagisto/bagisto/pull/4315

**Comment by devansh-webkul** [comment]
As the optimization thing is a different case that can be enhanced with time.

**Comment by devansh-webkul** [comment]
Hi @AkashWeybee,

One more thing you can remove this line from the view i.e. https://github.com/bagisto/bagisto/blob/b6a30fc015c7468792eafcf0181e844cb358a1a2/packages/Webkul/Velocity/src/Resources/views/shop/products/list/layered-navigation.blade.php#L10 and same for shop.

As this is the main source of duplicacy, I have removed it in the above mentioned PR.

**Comment by devansh-webkul** [comment]
I am closing this issue, as the main issue is fixed. If you want you can raise another PR for optimization.

**Comment by devansh-webkul** [comment]
Tested myself on 3000 plus products, page taking more time to load on category filter. So this needs to be optimized to some extent as well. Really apology for closing this.
