### ISSUE TITLE
 error save-order, 

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4370]
with pwa extension installed first, installing payment plugins does not work, error save-order, only works if you install payment plugins first and then the pwa extension
https://github.com/bagisto/laravel-pwa/issues/112

![99704142-bc625300-2a76-11eb-8caa-2d8606237bf2](https://user-images.githubusercontent.com/30912144/102366378-5a264080-3f97-11eb-8191-a538bc8f3d02.png)

# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by vaishaliwebkul** [comment]
@marcelowu 
could you show the error log?

**Comment by marcelowu** [comment]
local.ERROR: Route [pagseguro.redirect] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [pagseguro.redirect] not defined. at /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:420)
[stacktrace]
#0 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(768): Illuminate\\Routing\\UrlGenerator->route()
#1 /var/www/html/bagisto/vendor/cagartner/bagisto-pagseguro/src/Payment/PagSeguro.php(275): route()
#2 /var/www/html/bagisto/packages/Webkul/Payment/src/Payment.php(69): Cagartner\\Pagseguro\\Payment\\PagSeguro->getRedirectUrl()
#3 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Webkul\\Payment\\Payment->getRedirectUrl()
#4 /var/www/html/bagisto/packages/Webkul/Shop/src/Http/Controllers/OnepageController.php(190): Illuminate\\Support\\Facades\\Facade::__callStatic()
#5 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Webkul\\Shop\\Http\\Controllers\\OnepageController->saveOrder()
#6 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#9 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#10 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/html/bagisto/packages/Webkul/Shop/src/Http/Middleware/Currency.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Webkul\\Shop\\Http\\Middleware\\Currency->handle()
#13 /var/www/html/bagisto/packages/Webkul/Shop/src/Http/Middleware/Theme.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Webkul\\Shop\\Http\\Middleware\\Theme->handle()
#15 /var/www/html/bagisto/packages/Webkul/Shop/src/Http/Middleware/Locale.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Webkul\\Shop\\Http\\Middleware\\Locale->handle()
#17 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#19 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#21 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#23 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#25 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#27 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#28 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#29 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#30 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#31 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#32 /var/www/html/bagisto/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#34 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#36 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#37 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#39 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#41 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#43 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#45 /var/www/html/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#46 /var/www/html/bagisto/public/index.php(74): Illuminate\\Foundation\\Http\\Kernel->handle()
#47 {main}
"}

**Comment by vaishaliwebkul** [comment]
@marcelowu 
first, remove PWA extension then check if the error still persists.
