### ISSUE TITLE
Web install should return details when failing

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4371]
Currently when the GUI hangs due any reason you just see a empty box.
It would be more user friendly if it should return the error or reason why it is failing.

![GUIKnipsel](https://user-images.githubusercontent.com/1594411/102427600-f55bfc00-4011-11eb-8ce3-28b1c7591d9d.JPG)

**Comment by ghermans** [comment]
Marked this as a enhancement & bug report as both are valid for it.

**Comment by ghermans** [comment]
@devansh-webkul 
![empty](https://user-images.githubusercontent.com/1594411/103309203-c5025d80-4a14-11eb-946d-7986b7fe873c.JPG)

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I need the steps where it is not showing logs like on migration or seeding or something else. Because right now I am able to see the error logs.

https://prnt.sc/wdi9ca
