### ISSUE TITLE
The brand attribute should be deletable

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4372]
# Bug report

Admins should be able to remove the **brand attribute** when creating a new **attribute family**.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Go to Catalog -> Attribute Families
    2. Create a new attribute family
    3. Try to remove the brand attribute from the table.

### Expected result
![delKnipsel](https://user-images.githubusercontent.com/1594411/102434176-89c75e00-4014-11eb-95e6-eb1aed8d7398.JPG)

### Actual result
![FamKnipsel](https://user-images.githubusercontent.com/1594411/102434199-91870280-4014-11eb-9e07-d055d7b159b3.JPG)

**Comment by devansh-webkul** [comment]
Hi @ghermans,

The brand is a system attribute it can't be deleted.

**Comment by kukocrunch** [comment]
I'm sorry for butting in, but I think brand should be removeable because
custom family attributes from version 1.2.0 might break some function when migrating to master branch. see #4358 

The current master have lots of attributes that are non-removable 
![image](https://user-images.githubusercontent.com/7022294/102467320-1c0a4900-408b-11eb-8746-55548746e380.png)

**Comment by devansh-webkul** [comment]
Hi @kukocrunch,

Yes these attributes can't be removed as these are systems value. For `brand` i will let you know.

**Comment by YK-cbl** [comment]
there is a option to select brand but I didn't find any page to add brand. can you provide link?

**Comment by vaishaliwebkul** [comment]
@YK-cbl 
To add brand options, go to admin/catalog/attributes and search for brand attributes https://prnt.sc/w76lg4

**Comment by YK-cbl** [comment]
@vaishaliwebkul thanks for this also I need 1 help. I want to create a product in which user can also add other product. For ex. I want to add pizza and also provide option to check box to select sauce( not added, chilly, tomato etc.) if user check chilly sauce than some amount added to base price. How to add these type of products

**Comment by ghermans** [comment]
@YK-cbl please read the following blog https://bagisto.com/en/how-to-create-configurable-product-in-bagisto/

**Comment by YK-cbl** [comment]
@ghermas I need it like add-ons not configurable product. like if any vendor want to show 'add sauce'  option in pizza on product page than we enable it from back-end. so he just check "Add Chili Sauce" and price updated. similar if anyone don't want this option than we disable it for that product.
I need just like Simple Pizza S, M, L and add sauce option

not like  pizza s chili sauce, pizza s tomato sauce,  pizza m chili sauce, pizza m tomato sauce

**Comment by devansh-webkul** [comment]
Hi @YK-cbl,

The first phase you can easily make i.e. you need to add an attribute named as `is_chilli_sauce_added` or some other name. Then you need to add that attribute to your attribute family. Now you have a record of which product has sauce added or which product not.

The second phase is something that you need to customize at your end.

**Comment by vaishaliwebkul** [comment]
@kukocrunch @YK-cbl 
the main bug is already resolved in the master branch so I am closing this issue. 
If you have any support query, feel free to post a new topic here https://forums.bagisto.com/
