### ISSUE TITLE
On mobile category products are shown as empty until loaded

### ISSUE THREAD

**Issue by howdu** [bagisto/bagisto#4374]
Only visible on a very slow connection/docker but the 'whoops/empty' message is displayed by default until the products request has finished.

Problem is with this code in the velocity theme:
resources/themes/velocity/views/products/index.blade.php

Without the 'Loading...' code I've added below it reaches the end else statement first.

```
<shimmer-component v-if="isLoading && !isMobile()" shimmer-count="4"></shimmer-component>

<div v-if="isLoading && isMobile()" class="loader-ellips infinite-scroll-request">
    Loading...
</div>

<template v-else-if="products.length > 0">
    ...
</template>

<div class="product-list empty" v-else>
    <h2>{{ __('shop::app.products.whoops') }}</h2>
    <p>{{ __('shop::app.products.empty') }}</p>
</div>
```

**Comment by devansh-webkul** [comment]
Hi @howdu,

Please refer to this issue i.e. https://github.com/bagisto/bagisto/issues/4269.
