### ISSUE TITLE
All users given when i get customer (user) details with addresses.

### ISSUE THREAD

**Issue by giovannefc** [bagisto/bagisto#4379]
# Bug report

### Title
All users given when i get customer (user) details with addresses.

### Issue Description
i use:
`auth('customer')->user()->with('addresses')->get();`
and i get a array with all stored user in database.
logged in.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: 1.2.0

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. i run that command in a blade template (onepage.blade.php)

### Expected result
logged user details with addresses.

**Comment by devansh-webkul** [comment]
Hi, please check this issue, it seems like this has been fixed in master.

https://github.com/bagisto/bagisto/issues/3657

**Comment by ghermans** [comment]
@giovannefc thank you for reporting this issue, i would like to ask if you also experience this with the master branch?

**Comment by ghermans** [comment]
Closing this issue since no feedback has been provided
