### ISSUE TITLE
Velocity theme includes css for both bootstrap 3 and 4

### ISSUE THREAD

**Issue by howdu** [bagisto/bagisto#4381]
I presume this is a bug but removing either of these causes major styling issues to the theme. 

Bootstrap 3 is compiled and included via sass
packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";

Bootstrap 4 linked separately from master
packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php
<link rel="stylesheet" href="{{ asset('themes/velocity/assets/css/bootstrap.min.css') }}" />

**Comment by farshadff** [comment]
any idea for that ?? plus i find t hat every time you run `npm run prod` on this directory:  
```
/packages/webkul/velocity
```
in case to build the change of your css and vue file you get a huge uncompressed js file  . even though you have runned `prod` and that causes the site to go very very slow .

**Comment by vaishaliwebkul** [comment]
@howdu 
velocity theme is now on only bootstrap 4, you may check with the master branch.

Closing this right now, you have any other issue related to this topic feel free to reopen the issue.
