### ISSUE TITLE
Seller should be able to add product attributes

### ISSUE THREAD

**Issue by YK-cbl** [bagisto/bagisto#4384]
1. framework Version. v1.1.2
 
I am using bagisto market place, so vendors can register on my website to sell their products. After login they are able to create products but  they can't create the product category. Every vendor has different types of products so why they are not able to create own categories

**Comment by YK-cbl** [comment]
admin can manage the permission for this

**Comment by ghermans** [comment]
Hi @YK-cbl thank you for reporting your issue.  

The extension that you are referring to is build by Webkul they don't provide support for this on Github as this is not a open source extension.  
We kindly suggest to create a support ticket on https://bagisto.uvdesk.com/en/customer/create-ticket
