### ISSUE TITLE
set default value for variant option in product page

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#4390]
is there any way to set a default value for the color option ?? for example when user visits the a configurable product ,
by default the first color is selected and the user just need to select size or change color if he/she wants . i searched this file :
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/views/shop/products/view/configurable-options.blade.php
but i could not find any variable to set . can i get a hint please ? thanks

**Comment by devansh-webkul** [comment]
Hi @farshadff,

Well, currently there is no feature like that. But that's not tough you need to first start with the admin portion. In the admin portion on the color, you need to add one more field some kind of `is_default`.

Now you have a record of the default value just marked as selected on the basis of that.

**Comment by farshadff** [comment]
@devansh-webkul thanks for the answer . but i didnt explained the full feature and now i see you got it wrong let me say . 
i am developing this feature that instead of color it shows a thumbnail of the variant image . now if a user click on that image the gallry brings just that variant (color) images  and the url will be like below :
```
https://localhost:8000/product-link?color_id=668-variant-31-40
```
and from the sku i get the images u can see a working version here : 
```
https://nicolasleather.com/nicolas-women-boot-668?color_id=668-variant-31-40
```
now what is my problem : 
i can submit the form with vujs so when a user clicks on a thumbnail it send this sku to url and shows images but that would not be selectable for purchace so i want to make an active item from url `sku` or `id` of `optionid`
 i hope i could explain that well

**Comment by devansh-webkul** [comment]
Hi @farshadff,

It looks like you have made some customization.

I think you are looking for this, I guess,
https://github.com/bagisto/bagisto/blob/3c49cd9fff1100f4d6d6aec1daf7f7fef6e2dd14/packages/Webkul/Velocity/src/Resources/views/shop/products/view.blade.php#L246

**Comment by devansh-webkul** [comment]
I am closing this. Use Bagisto forum for discussion i.e. https://forums.bagisto.com/.
