### ISSUE TITLE
Multiple cart rule is getting applied in case condition matches on applying only one coupon 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4392]
# Bug report

### Title
Multiple cart rule is getting applied in case condition matches on applying only one coupon 

### Preconditions
    1. framework Version. master

### Steps to reproduce
    1. step1 : create 2 cart rules with same condition  
    2. step2 : on front end apply any one coupon, then both cart rule is getting applied 

### Expected result:
only one cart rule should get applied based on coupon code used by customer
### Actual result:
both are getting applied

**Comment by vaishaliwebkul** [comment]
working fine now, so closing this.

**Comment by vaishaliwebkul** [comment]
getting duplicate code error alert when edit and update existing cart rule even if no duplicate coupon code exist. https://prnt.sc/wmfvbf

**Comment by vaishaliwebkul** [comment]
fixed
