### ISSUE TITLE
composer test in windows

### ISSUE THREAD

**Issue by robinflyhigh** [bagisto/bagisto#4393]
# Bug report

### Title
composer test in does not work on windows 10

### Issue Description
Below code in composer.json does not work

"test": [
            "set -e",
            "@php artisan migrate:fresh --env=testing",
            "vendor/bin/codecept run unit",
            "vendor/bin/codecept run functional",
            "vendor/bin/codecept run trigger"
        ]

We can submit a pull request to make it work on windows by adding a new composer script.

"test-win": [
            "@set -e",
            "@php artisan migrate:fresh --env=testing",
            "vendor\\bin\\codecept.bat run unit",
            "vendor\\bin\\codecept.bat run functional",
            "vendor\\bin\\codecept.bat run trigger"
        ]

**Comment by devansh-webkul** [comment]
Hi @robinflyhigh,

Yeah, for Windows, it's not working. We are looking forward to seeing the pull request.
