### ISSUE TITLE
maintenance mode status is not working in channel section

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4394]
# Bug report

### Title
maintenance mode status is not working

### Issue Description
maintenance mode status enable/disable value is not saved 

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- settings->channels-> enable maintenacne mode status

### Expected result

status always disabled

### Actual result

status value should be enabled

https://prnt.sc/w91wj9

**Comment by vaishaliwebkul** [comment]
fixed

**Comment by sameer-kumar-jain** [comment]
I've installed this yesterday and when I turn maintenance mode on, it doesnt save any details, message and ip, and does not stop the front end from serving content. The checkbox state seems to be saved. Am I missing something? What is the proper process to start maintenance mode?
