### ISSUE TITLE
merry christmas

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4398]
![merry-christmas-tree-with-lettering-decoration_23-2148386159](https://user-images.githubusercontent.com/30912144/103095473-6b96ca80-45df-11eb-949e-9af251b51cc8.jpg)

**Comment by vaishaliwebkul** [comment]
![maxresdefault-1-1080x675](https://user-images.githubusercontent.com/43210406/103096055-ac670180-4628-11eb-9dca-e37639eb2915.jpg)
