### ISSUE TITLE
composer install --no-dev , gives error

### ISSUE THREAD

**Issue by scchethu** [bagisto/bagisto#4401]
# Bug report

### Title
**composer install --no-dev  Gives Error**

### Preconditions
**Please provide detailed information about your environment as possible.**

    1. Laravel 7
    2. Php 7.4

### Steps to reproduce

    1. composer install --no-dev
  

### Expected result

Composer should install without a development library.

### Actual result

![image](https://user-images.githubusercontent.com/44344282/103139067-798f3d00-46fe-11eb-85ac-5e8f3b78a687.png)

**Comment by robinflyhigh** [comment]
But barryvdh/laravel-debugbar should only be in Dev mode and not in production. Correct?

**Comment by devansh-webkul** [comment]
Hi @robinflyhigh,

I know that and I have read the documentation as well. But there is a package using that alias. Even though these dependencies can be turned off with the environment variable i.e. `.env` as well. So not a big problem in this.

**Comment by robinflyhigh** [comment]
No problem. Let's handle debug bar with .env

**Comment by scchethu** [comment]
i have one solution 
by adding this code 
`    public function register()
    {
        if(!$this->app->environment('production'))
        {
            Debugbar::addCollector(app(ModuleCollector::class));
        }
    }`

in DebugBarServiceProvider (Webkul package)
so that we can keep  **barryvdh/laravel-debugbar** in require-dev, and we can run **composer install --no-dev in only production mode**

**Comment by devansh-webkul** [comment]
I already mention this here https://github.com/bagisto/bagisto/pull/4406#issue-545945436. But still this solution is good i don't want any traces thats why i haven't added this. But still i will discuss and will update you.

**Comment by vaishaliwebkul** [comment]
@scchethu
the reported bug is found to be resolved so closing this issue.

@robinflyhigh  If you have better solutions, feel free to open the PR.
