### ISSUE TITLE
material-icons display in Velocity theme

### ISSUE THREAD

**Issue by Arafat-Thabet** [bagisto/bagisto#4402]
material-icons display in Velocity theme
display as text like that 
![image](https://user-images.githubusercontent.com/61386894/103143450-3f866100-4727-11eb-9b09-01b567591f59.png)

**Comment by vaishaliwebkul** [comment]
@Arafat-Thabet 
it seems you are trying to translate this page using google translate, make sure the product translation added in ar locale from the backend https://prnt.sc/wa4jdp

**Comment by devansh-webkul** [comment]
Hi @Arafat-Thabet,

Any update on this, is it worked or not?

**Comment by Arafat-Thabet** [comment]
not work

**Comment by vaishaliwebkul** [comment]
@Arafat-Thabet 
it will be helpful if you could share your website URL.

**Comment by ghermans** [comment]
Closing this issue since no feedback has been provided within 12 days
