### ISSUE TITLE
Identical file names with difference capitalization

### ISSUE THREAD

**Issue by cdburgess** [bagisto/bagisto#4405]
# Bug report
Install Error: The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
    Install of bagisto/bagisto failed

### Title
Different files with the same name

### Issue Description
While trying to install on MacOSx, I get this error. While I don't see specific support for MacOSx, it seems to me using the same name for files with different capitalization to keep them "different" will potentially cause issues. Naming conventions are important.

### Preconditions
Latest release

### Steps to reproduce
Using MacOSX:
composer create-project bagisto/bagisto-standard

### Expected result
The install would work allowing me to run:
artisan install bagisto

### Actual result
Failed to extract bagisto/bagisto: (1) unzip -qq

The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
    Install of bagisto/bagisto failed

The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems): ZipArc  
  hive::extractTo(/Users/{username}/Documents/GitHub/bagisto/vendor/composer/ea9d2d0c/bagisto-bagisto-c88ca31/bin/codecept): failed to open stream: No such file or directory

**Comment by smartameer** [comment]
Getting the same error with v1.1.2

**Comment by devansh-webkul** [comment]
Hi @cdburgess,

This issue has been fixed in master. Please refer to this issue,
https://github.com/bagisto/bagisto/issues/4220

You can download Bagisto from here,
https://bagisto.com/en/download/

For PR you can check this,
https://github.com/bagisto/bagisto/pull/4221

Because all these changes can only available in the next release.

**Comment by cdburgess** [comment]
Thank you so much for the update. I will watch patiently for the next release. Closing bug as resolved in a future release.
