### ISSUE TITLE
use Redis for cache img product not work

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4407]
![Captura de tela de 2020-12-28 12-32-28](https://user-images.githubusercontent.com/30912144/103225489-c6defa80-4908-11eb-8380-a08098e4c6f4.png)

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by ghermans** [comment]
@marcelowu please provide more info so we can investigate this.

**Comment by vaishaliwebkul** [comment]
@marcelowu 
closing this as not getting any activity since last one month.
