### ISSUE TITLE
silder image not work

### ISSUE THREAD

**Issue by shubham110019** [bagisto/bagisto#4408]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ch.name' in 'field list' (SQL: select `sl`.`id` as `slider_id`, `sl`.`title`, `sl`.`locale`, `ch`.`name`, `ch`.`code` from `sliders` as `sl` left join `channels` as `ch` on `sl`.`channel_id` = `ch`.`id` order by `slider_id` desc limit 10 offset 0) (View: C:\wamp64\www\ecom2\packages\Webkul\Admin\src\Resources\views\settings\sliders\index.blade.php)

**Comment by vaishaliwebkul** [comment]
@shubham110019 
could you mention the bagisto version on which you're getting this.

**Comment by shubham110019** [comment]
1.2.0

**Comment by devansh-webkul** [comment]
Hi @shubham110019,

Please complete the issue template and mention the steps, how you reproduce that issue. So that we can further help. Because an error looks like some columns are missing from the table.

**Comment by vaishaliwebkul** [comment]
getting the same issue in master branch https://prnt.sc/wcannt

**Comment by vaishaliwebkul** [comment]
@shubham110019 
the issue has been fixed, you may with the master branch.
