### ISSUE TITLE
product images not showing due to cache .

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#4414]
i am hosting my website on nginx and phpfpm . the problem is the product images are not showing because of the below error 

 ```
GET http://shopgeram.com/cache/medium/product/4922/20fGFwNVrZQ6EPVZD3dgjs8ZRCMPSLcxvcySSQRL.jpg 404 (Not Found)
```
and the directory does not exists . i have 2 questions 
1-is there any possibility to run a command and cache all images again ? because i moved the files from local to server
2-does that cache actually make that directory ?? if not how nginx must serve that . thanks in advance

**Comment by devansh-webkul** [comment]
Hi @farshadff,

It's just a linking issue. Just go to the `public` directory and delete the `storage` link and then back to root and run `php artisan storage:link`.

**Comment by farshadff** [comment]
@devansh-webkul i did that but no luck for that the storage is working because my slider and other images are loading just not the products image . in case you want to checkout here is the link :`http://shopgeram.com/`

**Comment by devansh-webkul** [comment]
Does your hosting have the `library` that is mentioned by the Laravel Intervention Cache?

**Comment by farshadff** [comment]
@devansh-webkul its a virtual server so i can install it i think let me see if i can find the library

**Comment by farshadff** [comment]
@devansh-webkul yes Gd library is installed and its on .
```
root@vm8998633870:~# php -i | grep 'GD\|ImageMagick'
GD Support => enabled
GD headers Version => 2.3.0
GD library Version => 2.2.5
```

**Comment by farshadff** [comment]
the problem for me was the nginx configuartion as explained in the offical documentation you have to add this part to nginx config : 

```
# where "cache" is {route}
location ~* ^\/(?!cache).*\.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|webp|woff|woff2)$ {
  expires max;
  access_log off;
  add_header Cache-Control "public";
}
```

**Comment by devansh-webkul** [comment]
@farshadff,

Yeah, Nginx won't allow that.
