### ISSUE TITLE
UPS Shipping fails when you click 'ship to this address' on onepage checkout

### ISSUE THREAD

**Issue by iateadonut** [bagisto/bagisto#4421]
using Bagisto v1.1.0

If you have the UPS Shipping enabled, and click 'ship to this address' when checking out on the onepage checkout screen, you have to click 'submit' twice, and it saves the address an extra time.

The error occurs here:
packages/Webkul/UpsShipping/src/Helpers/ShippingMethodHelper.php(181)

**Comment by vaishaliwebkul** [comment]
Hi @iateadonut
this repository is only for raising bagisto core issues.
if you are getting issue with other extensions then kindly raise the support ticket here https://bagisto.uvdesk.com/en/customer/create-ticket/

**Comment by iateadonut** [comment]
Can I get in contact with the developer of the plugin?  I'm a contributor to the bagisto source code.

If I had access to the UPS source code with it's tests, I may be able to extend them.

I wrote a test that captures my problem:
$controller = app( OnepageController::class );
$r = $controller->saveAddress( $request );
$r = $controller->saveAddress( $request );

When we saveAddress() twice, which happens if a user abandons their cart mid-order, we get this error:

1) Webkul\UpsShipping\Tests\SaveAddressTest::testSaveAddress
ErrorException: Trying to get property 'first_name' of non-object


bagisto/packages/Webkul/UpsShipping/src/Helpers/ShippingMethodHelper.php:199
bagisto/packages/Webkul/UpsShipping/src/Helpers/ShippingMethodHelper.php:113
bagisto/packages/Webkul/UpsShipping/src/Carriers/Ups.php:35
bagisto/packages/Webkul/Shipping/src/Shipping.php:41
bagisto/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
bagisto/packages/Webkul/Shop/src/Http/Controllers/OnepageController.php:140
bagisto/packages/Webkul/UpsShipping/src/Tests/SaveAddressTest.php:137

**Comment by ghermans** [comment]
Hi @iateadonut as my colleague @vaishaliwebkul already explained, issues created on this repository are only related to Bagisto. 
 The extension that you are having issues with is not open source and is maintained by [Webkul](https://webkul.com).
If you want to get in contact with them, then you can create a support ticket at https://bagisto.uvdesk.com/en/customer/create-ticket/
