### ISSUE TITLE
Trying to get property 'code' of non-object 

### ISSUE THREAD

**Issue by shubham110019** [bagisto/bagisto#4431]
# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by shubham110019** [comment]
Trying to get property 'code' of non-object (View: C:\wamp64\www\bagisto\resources\themes\velocity\views\UI\header.blade.php) (View: C:\wamp64\www\bagisto\resources\themes\velocity\views\UI\header.blade.php) (View: C:\wamp64\www\bagisto\resources\themes\velocity\views\UI\header.blade.php) (View: C:\wamp64\www\bagisto\resources\themes\velocity\views\UI\header.blade.php)
Previous exceptions

    Trying to get property 'code' of non-object (View: C:\wamp64\www\bagisto\resources\themes\velocity\views\UI\header.blade.php) (View: C:\wamp64\www\bagisto\resources\themes\velocity\views\UI\header.blade.php) (View: C:\wamp64\www\bagisto\resources\themes\velocity\views\UI\header.blade.php) (0)
    Trying to get property 'code' of non-object (View: C:\wamp64\www\bagisto\resources\themes\velocity\views\UI\header.blade.php) (View: C:\wamp64\www\bagisto\resources\themes\velocity\views\UI\header.blade.php) (0)
    Trying to get property 'code' of non-object (View: C:\wamp64\www\bagisto\resources\themes\velocity\views\UI\header.blade.php) (0)
    Trying to get property 'code' of non-object (0)

**Comment by vaishaliwebkul** [comment]
@shubham110019 
run `php artisan config:cache`
then check the website in the private window.
