### ISSUE TITLE
Getting error when adding new categories

### ISSUE THREAD

**Issue by sandeep-elitedigital** [bagisto/bagisto#4444]
Hi There,

I am getting below error when adding new categories

Illuminate \ Database \ QueryException (HY000)
SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('admin'@'localhost') does not exist (SQL: update `categories` set `_lft` = case when `_lft` >= 14 then `_lft`+2 else `_lft` end, `_rgt` = case when `_rgt` >= 14 then `_rgt`+2 else `_rgt` end where (`_lft` >= 14 or `_rgt` >= 14))

    1. framework Version- bagisto-1.2.0

**Comment by elitedigitaltech** [comment]
Error only display when adding any category under root category without assigning root category its added category without any eerror

**Comment by vaishaliwebkul** [comment]
please check this https://github.com/bagisto/bagisto/issues/2901

**Comment by elitedigitaltech** [comment]
I followed above guide but still getting same error SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('admin'@'localhost') does not exist

**Comment by devansh-webkul** [comment]
Hi @elitedigitaltech,

Please refer to this link,

https://github.com/bagisto/bagisto/issues/4347#issuecomment-744276804
