### ISSUE TITLE
ErrorException (E_ERROR) Target class [Webkul\Product\Helpers\ProductVideo] does not exist

### ISSUE THREAD

**Issue by elitedigitaltech** [bagisto/bagisto#4445]
There is no ProductVideo Helper file present in v1.2.0(Check Screenshot) Which is suggested by your team but product detail page on front end showing error for missing this helpar and I rework again on this version to integrate B2B market extension but this version have lots of issue and Client getting angry 

![image](https://user-images.githubusercontent.com/8210369/103751018-a7914d00-502d-11eb-9870-8661059fba5f.png)

![image](https://user-images.githubusercontent.com/8210369/103751422-4ae26200-502e-11eb-8a9b-29fc6d32ba24.png)

**Comment by rahulshukla-webkul** [comment]
Hi @elitedigitaltech 

Product video feature is not in 1.2.0 version and will be added in next release and now it is in master branch.
Kindly see this PR - https://github.com/bagisto/bagisto/pull/4276
