### ISSUE TITLE
Product listing on category pages

### ISSUE THREAD

**Issue by scchethu** [bagisto/bagisto#4448]
The below query is executed 4 times on the category listing page which has around 10k products.

Each query takes around 2 secs which totals up to 8 secs.

Filename: packages\Webkul\Product\src\Repositories\ProductRepository.php

Function name: public function getAll($categoryId = null)

Is there any way we can avoid multiple query requests?

SELECT Count(*) AS aggregate 
FROM   (SELECT DISTINCT `product_flat`.* 
        FROM   `product_flat` 
               INNER JOIN `product_flat` AS `variants` 
                       ON `product_flat`.`id` = Coalesce(variants.parent_id, 
                                                variants.id) 
               LEFT JOIN `product_categories` 
                      ON `product_categories`.`product_id` = 
                         `product_flat`.`product_id` 
               LEFT JOIN `product_attribute_values` 
                      ON `product_attribute_values`.`product_id` = 
                         `variants`.`product_id` 
        WHERE  `product_flat`.`channel` = 'default' 
               AND `product_flat`.`locale` = 'en' 
               AND `product_flat`.`url_key` IS NOT NULL 
               AND `product_categories`.`category_id` = {category-id} 
               AND `product_flat`.`status` = 1 
               AND `product_flat`.`visible_individually` = 1 
        GROUP  BY `product_flat`.`id` 
        ORDER  BY `name` DESC) c

**Comment by devansh-webkul** [comment]
Hi @scchethu,

We are already working on it. The two queries already removed. Still its in progress.

**Comment by scchethu** [comment]
Just making field change is reducing the query execution time to half

SELECT DISTINCT `ar_product_flat`.* 

vs

SELECT DISTINCT `ar_product_flat`.id, `ar_product_flat`.name 

Since we are counting the data we can skip ORDER BY name as well which will avoid one more column in select query for DISTINCT

**Comment by devansh-webkul** [comment]
The thing you are telling i have added everything, and i have 1 million products in the category. So still we are checking for some alternative.

**Comment by scchethu** [comment]
still not solved this issue, this query takes lots of time we need to solve this issue with high priority.

**Comment by devansh-webkul** [comment]
Hi @scchethu,

Yeah this is not solved, yet the reason behind closing is that there is already one more issue opened related to this. So following one thread can be helpful.

The problem is comming from the filters portion i.e. `attribute_values` table as this table contains the value. So joining making the query slow.
