### ISSUE TITLE
 Logo Image and Favicon icon not upload

### ISSUE THREAD

**Issue by shubham110019** [bagisto/bagisto#4450]
![Screenshot_2](https://user-images.githubusercontent.com/28014753/103890928-f367f300-510e-11eb-807a-f5d25e00e2a3.png)

**Comment by vaishaliwebkul** [comment]
@shubham110019 
follow this guide https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions/1

**Comment by vaishaliwebkul** [comment]
@shubham110019 
I hope the above guide helps you to resolve the issue.

Closing this, Feel free to reopen if you still have any further query.
