### ISSUE TITLE
products are not visible on homepage if filter based on ar locale

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4452]
# Bug report

### Title
products are not visible on the homepage if filter based on ar locale

### Issue Description
products are not visible on the homepage if filter based on ar locale

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add product in ar locale
    2. step2- go to default theme homepage, select ar locale from the locale dropdown

### Expected result
all the available product in ar locale should be visible

### Actual result

product are not visible on ar locale in default theme

![Screenshot_193](https://user-images.githubusercontent.com/43210406/103910876-5c5d6400-512b-11eb-93ae-14112ef46fb6.png)

![Screenshot_194](https://user-images.githubusercontent.com/43210406/103910910-6717f900-512b-11eb-804c-7f99b3727dac.png)

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

This is not an issue by default 4 locales i.e. en, fr, tr & dutch are supported in the channel. For Arabic, you need to fill in the data as channel content is now locale wise.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
if we create a new locale let's say AR then for ar locale the default data should be saved.
you may check the same for the velocity channel.

**Comment by vaishaliwebkul** [comment]
fixed
