### ISSUE TITLE
Generating order shipment is slow

### ISSUE THREAD

**Issue by ImTheRealOne** [bagisto/bagisto#4453]
Hi generating order shipment from the admin portal is slow. I have around over 3k in products. All items have a color attribute. We have around 20 colors.

Preconditions
Please provide as detailed information about your environment as possible.

1. v1.2.0
Steps to reproduce
It is important to provide a set of clear steps to reproduce this bug. If relevant please include code samples.

1. Import 3k+ items all with a common attribute (i.e. color)
2. Create an order, sales invoice, then create a shipment

It took around 100 seconds to generate the order shipment. Many duplicate queries.
![image](https://user-images.githubusercontent.com/9104404/103934051-2c857080-50d9-11eb-9309-ae3ea07b38ff.png)
![image](https://user-images.githubusercontent.com/9104404/103934351-acabd600-50d9-11eb-86cb-106a6ccdf317.png)

**Comment by ghermans** [comment]
Hi @ImTheRealOne, thank you for reporting this, we are already improving / removing duplicated query's, you can follow the progress in this pull request #4315
