### ISSUE TITLE
Error on accessing Supplier's inner pages

### ISSUE THREAD

**Issue by sandeep-elitedigital** [bagisto/bagisto#4460]
Hello Team,
I am getting below error when accessing any inner pages after supplier login

ErrorException (E_ERROR)
Call to undefined function array_get() (View: /home/domainname/public_html/demo/packages/Webkul/B2BMarketplace/src/Resources/views/supplier/layouts/nav-aside.blade.php)

**Comment by rahulshukla-webkul** [comment]
Hi @sandeep-elitedigital 

We don't have any B2BMarketplace package in this repository.
Kindly create a ticket at - https://bagisto.uvdesk.com/en/customer/create-ticket/

**Comment by sandeep-elitedigital** [comment]
Hello @rahulshukla-webkul  I am using https://github.com/bagisto/bagisto/tree/v1.2.0 this version and this version was suggested by support team when I created ticket and I was confirmed that this version support B2B marketplace extension too. I have already added data 3 times on my previous builds and its taking time.

**Comment by saurav-webkul** [comment]
Hi @sandeep-elitedigital 

Yes, it's right that this version support B2B marketplace but this is opensource place. You are having the paid B2B module, not the opensource one. That's why requesting you to please let us know the query on the ticket so as to provide you dedicated support for the same. 

This Github portal you can use to raise the query regarding opensource bagisto project. If you need help regarding any paid extension, kindly raise ticket for the same.

**Comment by sandeep-elitedigital** [comment]
I have already raised ticket. And after waiting full day received message that Now I will get update on Monday.

**Comment by sandeep-elitedigital** [comment]
Hello Rahul,

I raised ticket but not getting any reply there. I installed https://github.com/bagisto/bagisto/tree/v1.2.0 this version again on my localhost and installed b2b extension successfully but getting same error.

**Comment by ghermans** [comment]
HI @sandeep-elitedigital as my team members already explained, issues created on this repository are only related to Bagisto.
The extension that you are having issues with is not open source and is maintained by Webkul. The community is not involved with the development neither the support of these extensions.
This is why Webkul only provides support for its paid extensions on https://bagisto.uvdesk.com/en/customer/create-ticket/

As i notice in your previous reply Webkul said they would provide you a update today, so please give them time to answer your ticket
