### ISSUE TITLE
Show prices with or without taxes

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4463]
Allow the admin to display prices with or without taxes.

**Comment by jnikhil652** [comment]
yes, this feature should e added immediately

**Comment by parasbhadauria** [comment]
Hi @ghermans 
I agree with @jnikhil652 this should be sorted out on a high priority basis.
**For example:**
As per the current User Flow:
User comes to website > Visit product page with Price showing as $100 > User takes action for buying the product > During checkout, Addition of extra 10% ($10) of excluded tax increased the total price to $110 which in turn reduces the chances of buying the product.
So for a better conversion rate, It is very important to provide an inclusive of all taxes option on the product page itself.
It should be like
![discount](https://user-images.githubusercontent.com/75558471/106283326-ccad6000-6267-11eb-823f-818c2f5e66e5.JPG)
Thanks

**Comment by ghermans** [comment]
Hi @parasbhadauria,  

As we have already mentioned, this feature request will be added to the upcoming releases.  
Since this is a **community request**,  we also want to give **contributors** the opportunity to provide this functionality.  
This is why we do not provide a schedule when it will be implemented and mark it as low priority.

If you still want this to be treated with high priority, the functionality can still be developed faster by our team with a schedule for a fee.  
You can create a ticket on https://bagisto.uvdesk.com/en/customer/create-ticket/, we will then make a quote for you.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I am starting to work on it.
