### ISSUE TITLE
Making change in /resources/themes/velocity/views/products/list/card.blade.php as no effect

### ISSUE THREAD

**Issue by krishanujadiya** [bagisto/bagisto#4465]
When you do vendor publish then /resources/themes/velocity/views/products/list/card.blade.php is published in the theme folder.

However when we make changes in it then it does not making change on the website. We did php artisan view:clear and it does not help at all.

Now the only changes that affect is when we make changes in /packages/Webkul/Velocity/src/Resources/assets/js/UI/components/*.vue files and then run npm run dev or watch

Do we really need /resources/themes/velocity/views/products/list/card.blade.php

Also what is the best way to override /packages/Webkul/Velocity/src/Resources/assets/js/UI/components/*.vue in our own theme file. We could not find any documentation for the same.

**Comment by devansh-webkul** [comment]
Hi @krishanujadiya,

This is nothing just a cached issue, please check your caches. Basically all views are fetched from this directory. Are you sure you are making changes that won't reflect?

If you check the Laravel package guide, Laravel will first look into the resources folder if not found then it will move to package resources file.

You can check here also,
https://laravel.com/docs/8.x/packages#overriding-package-views

**Comment by krishanujadiya** [comment]
Hi @devansh-webkul,
 
![cart](https://user-images.githubusercontent.com/77289533/104295886-03088280-54e7-11eb-878f-06f2360b370d.png)


![card blade php](https://user-images.githubusercontent.com/77289533/104296110-45ca5a80-54e7-11eb-965c-3c58a000d7ca.png)

This is code I want to remove Be the first to write a review. I deleted the code in raw bagisto card.blade.php removed everything but page is still loading. Just installed and run these commands php artisan bagisto:install  and after that I cleared all the cache using php artisan config:clear, php artisan cache:clear and all the view and route no cache in my local but still not reflecting in Front-End.

If we will change in assets/js/UI/components/*.vue file than It will works. Please check this, I am attaching screenshot for reference.  


                @if ($totalReviews)
                    <div class="product-rating col-12 no-padding">
                        <star-ratings ratings="{{ $avgRatings }}"></star-ratings>
                        <span class="align-top">
                            {{ __('velocity::app.products.ratings', ['totalRatings' => $totalReviews ]) }}
                        </span>
                    </div>
                @else
                    <div class="product-rating col-12 no-padding">
                        <span class="fs14">{{ __('velocity::app.products.be-first-review') }}</span>
                    </div>
                @endif

Thank You.

**Comment by devansh-webkul** [comment]
This is because these changes are coming from components.

When you run `dev or watch` all files are directly moved to the public directory. That's why when you are not getting results.

Just compiled your assets and published your files will give permanent changes.

**Comment by krishanujadiya** [comment]
Okay I agree with you. I run npm run dev then Home Page is working fine. my question is this do we really need card.blade.php in velocity theme?
If not need then we should remove publish [26] Provider: Webkul\Velocity\Providers\VelocityServiceProvider

Because changes in card.blade.php has no reflect. Every time when I need to change in Component Files then No need of theme card.blade.php.

Thank You.

**Comment by devansh-webkul** [comment]
Hi @krishanujadiya,

Yes, it's needed, just check search pages and category pages.

**Comment by krishanujadiya** [comment]
Understood, thank you.

Will these card.blade.php continue to be a laravel blade files or it will be converted into vue component in future?

We can close this issue.

**Comment by devansh-webkul** [comment]
Thanks for the update!
