### ISSUE TITLE
hide out of stock items from homepage

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4468]
items which inventory gets 0 should automatically get hidden from the homepage

**Comment by ghermans** [comment]
i recommend to make this optional, some stores will work with backorders

**Comment by vaishaliwebkul** [comment]
@ghermans 
Agree! there should be a configuration to allow/disallow out of stock items on the homepage.

**Comment by rahulshukla-webkul** [comment]
Hi @ghermans  @vaishaliwebkul 

I think, when backorders will be enable , it will show all product without quantity restrictions otherwise not .
What do you suggest ?

**Comment by vaishaliwebkul** [comment]
@rahulshukla-webkul 
implement this for velocity theme also.
