### ISSUE TITLE
Category Image broken

### ISSUE THREAD

**Issue by vivek-webkul** [bagisto/bagisto#447]
![edit category](https://user-images.githubusercontent.com/28401696/51109800-68eca180-181c-11e9-800e-6a1e69a52175.jpg)

![food mania](https://user-images.githubusercontent.com/28401696/51109858-93d6f580-181c-11e9-8f50-611b929b0aad.jpg)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot 4](https://user-images.githubusercontent.com/45203177/52274703-786e8e80-2973-11e9-8901-a783199599d4.png)
![screenshot 5](https://user-images.githubusercontent.com/45203177/52274708-7c9aac00-2973-11e9-85d7-0a92fe6e3be4.png)

**Comment by mahabubxtra** [comment]
how do i fix this?

**Comment by vaishaliwebkul** [comment]
@mahabubxtra 
refer to this guide https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions
