### ISSUE TITLE
Regarding to Shop View Path

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#4470]
Hi,
I am using version 0.1.8. And I am trying to get the rendered html of a view. 
For example
`
 $html = view('shop::emails.sales.new-order', compact('order'))->render();
`
I am trying to run this at `packages\Webkul\Admin\src\Http\Controllers\Sales\OrderController`

However, the html I got was actually rendered from shop directory view instead of the view in the theme. I got the current view from the Order Mail Listener class. Why?

**Comment by devansh-webkul** [comment]
Hi,

From your example, the view is calling in the shop package thats why its gettting called.

**Comment by lYesterdaYl** [comment]
> Hi,
> 
> From your example, the view is calling in the shop package thats why its gettting called.

Yes, I want to know why it is calling the shop package when I have a custom theme. For that chunk of code, it gets the view from the theme package instead of the shop package in the Order Mail Listener class.

**Comment by devansh-webkul** [comment]
Hi @lYesterdaYl,

I am sharing the full info about that, actually if you check the Laravel documentation i.e.,
https://laravel.com/docs/8.x/packages#views

Here it is showing that, when you use `view('shop::emails.sales.new-order', compact('order'))->render();`, then Laravel actually registers two locations for your views: the application's `resources/views/vendor/shop/emails/sales/new-order.blade.php` directory and the directory you specify i.e. `packages/Webkul/Shop/src/Resources/views/emails/sales/new-order.blade.php`.

In your case you must be putting in themes folder i guess.

**Comment by devansh-webkul** [comment]
Hope your problem get solved.

I am closing this as this channel is only for reporting issue. Please use Bagisto forum for discussions,
https://forums.bagisto.com/
