### ISSUE TITLE
Social Login Links not in vendor:publish

### ISSUE THREAD

**Issue by krishanujadiya** [bagisto/bagisto#4473]
packages/Webkul/SocialLogin/src/Resources/views/shop/customers/session/social-links.blade.php not in vendor:publish

We want to override social-links.blade.php in our file but it is not publised velocity resource.

In SocialLoginServiceProvider $this->publishes() is only for assets and do not publish Resources/views/shop
Is this intentional or we missed to add it?

**Comment by devansh-webkul** [comment]
Hi @krishanujadiya,

Just create the exact same path in the resources and place your file their. Laravel will first look into that place then iit will move to the package one. I already provided you the reference. :wink:

**Comment by devansh-webkul** [comment]
I am closing this as this channel is only for reporting issue. Please use Bagisto forum for discussions,
https://forums.bagisto.com/
