### ISSUE TITLE
Incorrect currency being set for PayPal

### ISSUE THREAD

**Issue by nikhilbhatia22** [bagisto/bagisto#4474]
### Issue Description
**When checking out with PayPal Standard, with a currency other than USD, the PayPal gateway receives USD as transaction currency, with amount same as was in cart.**
So for example, I add an item to the cart of say $75, and then one the checkout page, I change the currency to EUR (hence totals it to ~ €65) and then checkout with PayPal Standard, then paypal page shows the amount as **$65**, 

### Producible at 
1. `master` of `bagisto/bagisto-standard`
2. https://demo.bagisto.com

### Steps to reproduce
1. Go to demo.bagisto.com
2. Quick add any item to the cart
3. Go to checkout page
4. Change currency to any other currency (than USD).
5. Checkout with PayPal Standard
6. On PayPal page, you will find the total amount to be correct, but the currency as USD.

### Expected result
It should show currency as was set on cart/checkout page.

### Sample shots
On checkout page
![image](https://user-images.githubusercontent.com/12022338/104426008-5fcb7200-55a7-11eb-8742-03a939dffd7a.png)

On PayPal Page
![image](https://user-images.githubusercontent.com/12022338/104426065-6fe35180-55a7-11eb-80a9-3c61e2d1d9ba.png)

**Comment by vaishaliwebkul** [comment]
Hi @nikhilbhatia22 
 The mentioned bug is already fixed in the master branch, please have a look into this issue https://github.com/bagisto/bagisto/issues/3269, 

It works fine as expected in master branch.
![Screenshot_211](https://user-images.githubusercontent.com/43210406/104464097-92da2980-55d8-11eb-8a30-7697e407871e.png)

![Screenshot_212](https://user-images.githubusercontent.com/43210406/104464120-98d00a80-55d8-11eb-805d-8547dd3dcd4a.png)

**Comment by nikhilbhatia22** [comment]
Did you try to produce the bug with possible producible(s) again as specified in the description above?

The bug may have been solved, but it seems to be unsolved at `master` of `bagisto/bagsito-standard`. Plus, probably hence the same is being seen at https://demo.bagisto.com (which is why I have put the URL in the screenshot).

Also, at many issues, I have seen, many asking the similar, that, **please update the `bagisto/bagisto-standard` repository with periodical bug patches**, so that, the people using that repository as composer dependencies, can make `composer update` to receive bug patches.

**Comment by nikhilbhatia22** [comment]
**Also, the mentioned issue #3269, is not at all related to the issue described here.** If I am missing anything, do let me know.

**Comment by ghermans** [comment]
Hi @nikhilbhatia22  i would like to recommend you to use the repository **bagisto/bagisto** instead of bagisto/bagisto-standard.
bagisto/bagisto-standard is a experimental repository, we are planning to update this repository but unfortunately this will not take place in the upcoming days or weeks since we are currently busy to release the next version of Bagisto.

**Comment by nikhilbhatia22** [comment]
Thanks @ghermans for prompt reply.

If `bagisto/bagisto-standard` isn't going to be updated in upcoming few days/weeks, then, I think the `bagisto/bagisto`'s readme should caution the same, or better, it should be updated to use `bagisto/bagisto` instead of `bagisto/basgisto-standard` as in screenshot below.

![image](https://user-images.githubusercontent.com/12022338/104497829-ee201200-5600-11eb-9ef2-4953a89c92e7.png)

Because you as well must be aware, we as developers are used to (or prefer to) install any package or project through the console, which is what we did in the first place, expecting bug patches in the future (since it uses bagisto as composer dependency).

**Comment by nikhilbhatia22** [comment]
Also, if the mentioned bug has been fixed, then please specify the correct issue/pr through which it was merged. Additionally, if the PR contains many other patches, then I would request to specify the exact changes made to fix this bug, so that, the same we can do by overriding the files in our project. 

Hope you understand the matter, since we can not scrap the ongoing project and use `bagisto/bagisto` instead in the mid of the project completion.

**Comment by devansh-webkul** [comment]
Hi @nikhilbhatia22,

Yes, the standard docs already has been removed,
Link: https://github.com/bagisto/bagisto-docs/pull/215

Although we are linking the issue with the PR as well.

**Comment by vaishaliwebkul** [comment]
@nikhilbhatia22 
Yes, I have test with the same steps as you mentioned in the bug description, also Bagisto Demo https://demo.bagisto.com is always running on the latest release 1.2.0 so the bug exists in demo site.
Kindly verify your query with this repo https://github.com/bagisto/bagisto/tree/master

**Note: Apologies for providing the wrong issue link, please check this issue link https://github.com/bagisto/bagisto/issues/4246**
