### ISSUE TITLE
Customer Group price feature is not working for guest user, if price for guest user is more than actual product price.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4479]
# Bug report

### Title
Customer Group price feature is not working for guest user, if price for guest user is more than actual product price.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-1.2.0

### Steps to reproduce

    1. step1- In customer group price set price for guest user than than actual product price.
    2. step2- Add product in cart as guest user.

### Expected result
On product page and cart page prize that is set for guest user should display

![download - 2021-01-14T141946 906](https://user-images.githubusercontent.com/45203177/104566427-940c6480-5673-11eb-883f-e8d597cd85db.png)

![download_-_2021-01-12T200530 236](https://user-images.githubusercontent.com/45203177/104566454-9cfd3600-5673-11eb-83a6-eb85e8a0a92e.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
customer group price feature is providing for allowing a discount on the actual price, so as expected the if the discount amount is greater than the actual price then this will always show the minimum price from both amounts.

So as per me, this is not a bug.
