### ISSUE TITLE
Custom authentication

### ISSUE THREAD

**Issue by Bobach22** [bagisto/bagisto#4491]
Hi, first of all thanks for this great product. So how can i override auth providers(want to make mobile OTP provider),or do i manually hardcode my own provider into root config file and register it in AuthServiceProvider,or can i ceate a package to override it .

**Comment by devansh-webkul** [comment]
Hi @Bobach22,

Well, it's better if you have a separate provider for Mobile OTP, where you register all your configs related to mobile OTP.

Then you can create some services. After that, you just need to override some login and registers method.

**Comment by ghermans** [comment]
As this is not a issue i'm closing this, if you want to discuss this more you can use our community forum https://forums.bagisto.com
