### ISSUE TITLE
How to change taxation process

### ISSUE THREAD

**Issue by rohan7chaudhary** [bagisto/bagisto#4492]
Hi I want to change the taxation process (showing products with taxes). 
Should I change the code in webkul package ?
Please suggest how to do changes.

**Comment by vaishaliwebkul** [comment]
Hi @rohan7chaudhary 
This feature request is already raised https://github.com/bagisto/bagisto/issues/4463.

**Comment by rohan7chaudhary** [comment]
> Hi @rohan7chaudhary
> This feature request is already raised #4463.

Hi @vaishaliwebkul , Thanks for your prompt response. 
My next question is can we change the code in webkul package ?
What could be the consequences.?
If there is some more elegant way of doing this, please suggest.

**Comment by devansh-webkul** [comment]
Hi @rohan7chaudhary,

If you change the package, then maybe you face some problems during an upgrade if conflicts occur.

The better way is to override the class. So that you can define your custom functionalities.
