### ISSUE TITLE
Only load the locales that are enabled on the channel

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4495]
# Bug report

### Issue Description
In admin all locales are always being displayed in the dropdown menu when for example adding products.
Instead the dropdown should only output the locales that are enabled for the specific channel.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master branch.
### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Only enable one locale for channel default
    2. Create a new product and check the channel locales above,  check below screenshot.

### Actual result
The dropdown is populated with all locales instead of only one.
![locales](https://user-images.githubusercontent.com/1594411/104987617-6c702000-5a16-11eb-9833-865998174ded.PNG)

**Comment by vaishaliwebkul** [comment]
Hi @ghermans 
Admin panel is not channel based so all the locale will be visible to admin added in locales table.
Locales enabled in channels used for the storefront only.

**Comment by ghermans** [comment]
@vaishaliwebkul i send you a DM on Slack that provides more details regarding this.

**Comment by vaishaliwebkul** [comment]
Hi @ghermans 
please verify this issue again if this is fixed as expected.

**Comment by ghermans** [comment]
@vaishaliwebkul sure, i will verify this during the day

**Comment by vaishaliwebkul** [comment]
@ghermans 
this is working fine, so closing this issue.

Feel free to reopen anytime if issue still exist.

**Comment by vaishaliwebkul** [comment]
@rahulshukla-webkul 
channel-based locale filter for the configuration section also need to be added https://prnt.sc/yyh77q

**Comment by vaishaliwebkul** [comment]
fixed in this PR https://github.com/bagisto/bagisto/pull/4595
