### ISSUE TITLE
Cant delete attribute

### ISSUE THREAD

**Issue by simantverma** [bagisto/bagisto#4505]
The attribute is created and has been added to the attribute family.
Now create a configurable product, once the SKU is entered click on Save product now the newly added attributes will be visible there.
If we delete the whole attribute from there then still the attribute is visible while creating a product when we enter details regarding the product.
Once the attribute is deleted from the previous page it should be visible while creating a product.

**Comment by vaishaliwebkul** [comment]
@simantverma 

if you delete the attribute from the variant options https://prnt.sc/xaj0bl then this will not show at the time of adding variant details, but the deleted attribute will exist in the product https://prnt.sc/xahk4v as it's added in the attribute family.

So this is not a bug.
