### ISSUE TITLE
Wishlist and Cart key in Product API

### ISSUE THREAD

**Issue by AliRazaLilani** [bagisto/bagisto#4510]
# No Wishlist key in Product API 

### Title
I want to check whether the product is in wishlist or in cart or not so that I can place label on product in my api endpoint.

### Issue Description
There should be a key in Product Api with 'Wishlist' True or False and 'Cart' True or False. How can I check that whether the current product is added to wishlist or not ? or is the product is in cart or not ? 

### Expected result
data {
(....),
"itemInWishlist" : true,
"itemInCart" : false
}

*   [Screenshots, logs or description]

### Actual result

>    No Keys

**Comment by devansh-webkul** [comment]
I am marking this as an enhancement as changes are minor and it is not a bug.

**Comment by AliRazaLilani** [comment]
Any Update ?

**Comment by AliRazaLilani** [comment]
Thanks a lot. Stay Blessed.

**Comment by devansh-webkul** [comment]
@AliRazaLilani,

PR is still in testing phase only close this issue when PR is merged.
