### ISSUE TITLE
API Response Time

### ISSUE THREAD

**Issue by AliRazaLilani** [bagisto/bagisto#4511]
API Response time is very slow. How to Optimize or fasten the api response time. I have deployed on aws and testing on postman also problem in android and ios apps.

it's taking more than 5 seconds and sometimes even more than 15 seconds for a 500kb data.
![image](https://user-images.githubusercontent.com/62008807/105357412-9e4fd500-5c16-11eb-9972-3102c96abef0.png)

**Comment by devansh-webkul** [comment]
Hi @AliRazaLilani,

Can you share with us which API route, you are calling so that I can check in the Bagisto instance and how much data you have?

Please share the full request body and response.

**Comment by AliRazaLilani** [comment]
Is there any method to minimize the query response time of bagisto. My web is also very slow. Have a look on this URL : https://shopsees.com/

**Comment by AliRazaLilani** [comment]
API recalling is slow may be because of lack of eager loading and DB Queries instead of eloquent.
