### ISSUE TITLE
Custom theme changes not reflecting

### ISSUE THREAD

**Issue by sandeep-elitedigital** [bagisto/bagisto#4515]
Hi Sir,

I created a custom theme named polpo copying all code from packeges/webkul/shop view files and activated that from admin but any thing I am changing in my theme's layout or header its not reflecting when I am doing changes in packeges/webkul/shop view files then its reflecting.
Website url is to show my css and js I included files in packege/webkul/shop's layout file then its show else not showing

**Comment by devansh-webkul** [comment]
Hi @sandeep-elitedigital,

Did you follow this guide?

https://devdocs.bagisto.com/1.x/themes/create_theme.html

Did you change your view path from the config?

**Comment by sandeep-elitedigital** [comment]
Yes I have did all steps mentioned in doc. Please see screenshot of theme.php

![image](https://user-images.githubusercontent.com/8210369/105489861-f0a5fa00-5cd9-11eb-8f63-2669b0365210.png)

**Comment by sandeep-elitedigital** [comment]
As per screenshot all view files must be used from polpo theme but its using packege/shop/resources/view files

**Comment by devansh-webkul** [comment]
Hi @sandeep-elitedigital,

Did you run the command `php artisan config:cache` as sometimes changes won't reflect?

If still not working then could you share with me the screenshot of the directory structure where you have placed all your themes files so that I can check further?

**Comment by sandeep-elitedigital** [comment]
Yes I run all php artisan  commands like php artisan config:cache  with composer dump-autoload 
Theme files path

![image](https://user-images.githubusercontent.com/8210369/105491779-df122180-5cdc-11eb-89e2-6bd005d9f765.png)

Theme assets path 
![image](https://user-images.githubusercontent.com/8210369/105491821-fb15c300-5cdc-11eb-9057-d80a5bfa324f.png)

**Comment by devansh-webkul** [comment]
@sandeep-elitedigital,

It looks like a small thing is missing, maybe a path or cache. Did you activate your theme from the channel?

I am sharing the screencast please check.

https://user-images.githubusercontent.com/68321766/105496229-36b38b80-5ce3-11eb-803e-c211de24d629.mp4

Video: https://file.re/2021/01/22/theme-check/?download&st=1611321900

**Comment by sandeep-elitedigital** [comment]
Yes its same theme also changing when I am changing from admin but its using layout and partials from default theme

**Comment by sandeep-elitedigital** [comment]
Either I am enabling default theme or Polpo from admin its only calling view from default theme. I have already shared my theme.php file all paths are correct and folder structures also ok I cleared all cache but still same issue.

**Comment by devansh-webkul** [comment]
Hi @sandeep-elitedigital,

I just reverified again on all layouts even with the header as well,
https://prnt.sc/xgazd2

It's working fine. Something small change is missing, please take a look. Even a small folder variation can be redirected to the package path.

**Comment by sandeep-elitedigital** [comment]
But I have did all required changes and given you screenshots

**Comment by sandeep-elitedigital** [comment]
So it can not be solved?

**Comment by sandeep-elitedigital** [comment]
Have you checked my folder structure and config file screenshots

**Comment by sandeep-elitedigital** [comment]
Even    <link rel="stylesheet" href="{{ bagisto_asset('css/shop.css') }}">
    <link rel="stylesheet" href="{{ bagisto_asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ bagisto_asset('css/webflow.css') }}"> These lines calling css from my custom theme folder but issue is only calling view and layout from shop folder

**Comment by ghermans** [comment]
> 
> 
> So it can not be solved?

Yes it can however this is not a bug of Bagisto, instead it is related to your custom theme.  
Because of that i would suggest to continue this conversation on our forum https://forums.bagisto.com so that the community can help you with your issue.
If you still want us to investigate the cause of the issue please create a ticket on https://bagisto.uvdesk.com/en/customer/create-ticket
