### ISSUE TITLE
Adding images for the variant of Configurable product via bulk upload.

### ISSUE THREAD

**Issue by simantverma** [bagisto/bagisto#4517]
Right now we are not able to add images for the variants of the configurable product via bulk upload.
This is must when we are using bulk upload for configurable product.

**Comment by ghermans** [comment]
Hi thank you for your suggestion, It could be a good idea to mention this on the repository of [bagisto-bulk-upload](https://github.com/bagisto/bagisto-bulk-upload) instead of the default Bagisto repository.
