### ISSUE TITLE
Show product price discount percentage

### ISSUE THREAD

**Issue by jnikhil652** [bagisto/bagisto#4518]
Product price should be shown with discount percentage

**Comment by devansh-webkul** [comment]
Yeah, this can be added. I am marking this as an enhancement.

**Comment by vaishaliwebkul** [comment]
Hi @jnikhil652 
Please refer to this issue https://github.com/bagisto/bagisto/issues/3572 implemented in master branch & soon available in next release. you can use customer group pricing where the discount will show in terms of percentage. https://prnt.sc/xt9d0f

**Comment by parasbhadauria** [comment]
Hi @vaishaliwebkul  @jnikhil652 
I think the price format should be like
![discount](https://user-images.githubusercontent.com/75558471/106282021-08dfc100-6266-11eb-9a70-69fb282fbbc2.JPG)

**Comment by vaishaliwebkul** [comment]
@parasbhadauria 
Thanks for the suggestion.
source code is fully opened, the user can customize the format/design as per their need.

**Comment by parasbhadauria** [comment]
@vaishaliwebkul 
I know that. I just gave a suggestion.
I think we all are here to make Bagisto as better as a fully functional e-commerce portal should be.

**Comment by vaishaliwebkul** [comment]
@parasbhadauria 
Yes, appreciate your suggestion,
we will check this and try to implement it when working on tax-inclusive feature https://github.com/bagisto/bagisto/issues/4463

Right now closing this issue as this has been fixed as mentioned above.
@jnikhil652 Feel free to reopen the issue anytime if you have any further query.
