### ISSUE TITLE
Tax should not be state or Pincode-dependent. It should be product category dependent.

### ISSUE THREAD

**Issue by parasbhadauria** [bagisto/bagisto#4519]
Currently, In many countries, GST/VAT is not either state or Pincode-dependent. It is category dependent.
So, it does not make sense that the state or locality pincodes are mandatory.

For example:
Let's say we have two categories of "Electronic Product" and "Home Decor".
Electronic Product carries 28% GST/VAT for all states and pincodes.
The home decor category carries 18% GST/VAT for all states and pincodes.

So there could be two solutions:
1. Pincode and state dependency of taxes must be removed.
2. An extra functionality could be added for supporting both requirements.

Thanks

**Comment by devansh-webkul** [comment]
Hi @parasbhadauria,

If you check the taxes configuration, you will see that there is also a tax category that can be helpful to you. You can create multiple tax categories with different taxes and assigned that tax category to the product.

**Comment by parasbhadauria** [comment]
@devansh-webkul 
I wanted to say that there are two cases here while creating tax rates:
1. With Enabled zip code range
2. With disabled zip code range.
In both cases, Filling of state & zip code/zip code range is mandatory while creating tax rates.
So in other words we can say that tax rates are state & zip code dependent.
There is no need to fill the zip code & state while creating tax rates. In most of the countries, it is product category dependent only.
For further clarification, you can have a look at the attached screenshot.
<img width="900" alt="taxrate" src="https://user-images.githubusercontent.com/75558471/105993934-f716e600-60cc-11eb-8e3e-d826c217653b.png">

**Comment by vaishaliwebkul** [comment]
@parasbhadauria 
the tax rate is always applied to the geographical region, so the zip code field is mandatory here.
If you have any summary where the tax rate is not applicable based on zip code kindly share the doc here so that we can check for the same.

**Comment by ghermans** [comment]
@vaishaliwebkul thinking that the zip code field is mandatory for tax rate is not correct, for example in most EU countries tax rates are not assigned to zip codes but indeed in different categories.

**Comment by parasbhadauria** [comment]
@ghermans @vaishaliwebkul 
That's what I wanted to say.
Let's take India as an example.
Here, We have GST as product category dependent tax and the same everywhere.
So, 
Keeping zip code & state field mandatory is not correct

**Comment by ghermans** [comment]
## Optimization task
- [ ] Make the field `Zip Code` not mandatory in case **Enable Zip Range** is not enabled.

**Comment by ghermans** [comment]
@parasbhadauria as you can see above we will resolve this.  
In the meanwhile you can use the following package [bagisto-europe/tax-rates](https://github.com/bagisto-europe/tax-rates) and create a new seeder file for example `AsianTaxRatesSeeder.php` with the following content

```php
<?php

namespace Bagisto\TaxRates\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class AsianTaxRatesSeederextends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tax_rates')->insert([
            [
                'identifier' => 'India (standard)',
                'is_zip'     => 0,
                'country'    => 'IN',
                'tax_rate'   => '0'
            ], [
                'identifier' => 'India (5%)',
                'is_zip'     => 0,
                'country'    => 'IN',
                'tax_rate'   => '5'
            ], [
                'identifier' => 'India (12%)',
                'is_zip'     => 0,
                'country'    => 'IN',
                'tax_rate'   => '12'
            ],
           ]);
    }
```
Open DatabaseSeeder.php and add `$this->call(AsianTaxRatesSeeder::class);`
### Example
```php
<?php

namespace Bagisto\TaxRates\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();
        $this->call(AsianTaxRatesSeeder::class);
        $this->call(EuropeTaxRatesSeeder::class);
        Model::reguard();
    }
}
```
Run the following command in your terminal
```sh
php artisan db:seed --class="Bagisto\TaxRates\Database\Seeders\DatabaseSeeder"
```
Once that is done you should see the tax rates in the admin panel.

**Comment by parasbhadauria** [comment]
@ghermans 
Making zip Code not mandatory will not be enough. **Also, We have to remove the state field from the required field.**
In India, we have single tax rates (with four tax slabs as 5%, 12%, 18%, 28%) in all states.
And we have more than 27 states here.
Suppose a vendor offers only one product category which comes under the 12% tax slab.
In that case, he has to fill the tax creation form more than 27 times (as we have more than 27 states) for a single tax rate.
**So, We will have to remove the state field as a mandatory input.**

**Comment by ghermans** [comment]
Hi @parasbhadauria sorry for the late response, this problem will be resolved in the next release.
