### ISSUE TITLE
Inclusion/exclusion of Pincode range for shipping must be there: Product availability must be showing up on every product page.

### ISSUE THREAD

**Issue by parasbhadauria** [bagisto/bagisto#4520]
Hi,
We have many locations where we can not ship our product.
So, we should have inclusion/exclusion of Pincode range for shipping.
And the option of product availability on pincodes must be showing up on every product page.
Nowadays, Almost all the e-commerce portal giving this option to the customer so that they can be able to check the product availability around their locality.
Kindly look into it.
Thanks

**Comment by jitendra-webkul** [comment]
This can be done with customization or we will create a module for this
