### ISSUE TITLE
Display discounted price(catalog rule discount) for configurable product on home page 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4523]
# Bug report

### Title
Display discounted price(catalog rule discount) for configurable product on home page 

### Preconditions
    1. framework Version. master, 1.2.0

### Steps to reproduce
    1. step1:create a configurable product and one  catalog rule(make sure that get applied on that configurable  product)
    2. step2:check on home page and product page
### Expected result:
discounted price should get displayed on home page 
### Actual result
https://prnt.sc/xp87pl ,   https://prnt.sc/xp89rh

**Comment by musawirjon** [comment]
Is their any progress on the issue above. When it will be done.

**Comment by ghermans** [comment]
hi @musawirjon i would like to inform you that yesterday one of the developers has been assigned to resolve this issue.  
You can follow the progress in this issue report when there is a update.

**Comment by musawirjon** [comment]
Hi @ghermans sure I am following along, Hope to see this fix little early.

**Comment by rahulshukla-webkul** [comment]
Hi @musawirjon 

It has been fixed, the PR is under review, once it get done, PR will be merge.

**Comment by musawirjon** [comment]
Hi @rahulshukla-webkul surprised, I am actively waiting for this great fix. thank you!

**Comment by musawirjon** [comment]
Hi @rahulshukla-webkul I can see Fix Proposed tag, How long will merge be expected!

**Comment by vaishaliwebkul** [comment]
@musawirjon 
I will update you here once PR gets merged, we are reviewing the proposed changes.

Thanks

**Comment by musawirjon** [comment]
@vaishaliwebkul perfect! thank you.

**Comment by musawirjon** [comment]
I pulled it, still the same thing no promotion cat rules are applying. still same as it was. @vaishaliwebkul

**Comment by musawirjon** [comment]
Still same as it was, discount and actual prices are not showing on home and other pages. and on product page only applied once selecting variation.
happening for dropshipping products.

**Comment by musawirjon** [comment]
and their is one edition issue while I navigating to configuration page. it's through error on dropship configurations.
https://prnt.sc/xsppw4

**Comment by rahulshukla-webkul** [comment]
Hi @musawirjon 

Still this PR is under review process and did not gets merged , did you change your code according to commit ?
and for the configurable product it will shows its minimal price ( of any variant ) rather than discount and actual prices.

**Comment by musawirjon** [comment]
Yes I did pulled the code. OK but I told to support guy to show the minimal but with discount and actual prices. This enhancement will be very great feature for catalogue rules.

**Comment by rahulshukla-webkul** [comment]
Hi @musawirjon 

We have a created a separate PR  - https://github.com/bagisto/bagisto/pull/4530
This PR will be show discount and actual prices.

Thanks for suggestions.

**Comment by musawirjon** [comment]
Hi @rahulshukla-webkul  I have pulled latest code from main repo, as I can see it's updated an hour ago. I am just running new migration as I have already data in my database. Now I am facing some issues.
1) I can't see channel any where https://prnt.sc/xt0ejy
2) I can't open configuration on admin as it's throughing errors  https://prnt.sc/xsppw4
Note: I have existing DB, and I adding new migration from the latest updates. I can't figure these two issues.

**Comment by rahulshukla-webkul** [comment]
Hi @musawirjon 

Can you provide us your database so that we can check.

**Comment by musawirjon** [comment]
I just sent on support id #1501. I mentioned to provide it to you.

**Comment by rahulshukla-webkul** [comment]
Hi @musawirjon 

Is it ticket number as i don't get any dump when opening to this one ? https://prnt.sc/xt5o91

**Comment by ghermans** [comment]
@rahulshukla-webkul this is probably indeed a ticket number on uvdesk

**Comment by vaishaliwebkul** [comment]
Hi @musawirjon 
the issue raised issue has been fixed now so closing this.
