### ISSUE TITLE
Download link on https://bagisto.com/en/download/ not working

### ISSUE THREAD

**Issue by dvagere** [bagisto/bagisto#4525]
# Bug report

### Download link on https://bagisto.com/en/download/ not working
**Tried to download the installation zip but the link is not dowing anything.**

### Issue Description
**I tried to download the installation archive and the link didn't wasn't triggering a download, I then inspected the link and the href = javascript:void(0) which I am assuming is a bug.**

![Screen Shot 2021-01-27 at 13 02 41](https://user-images.githubusercontent.com/17473721/105982690-4abf0a80-60a0-11eb-95f1-838a9b0a4e6c.png)

### Preconditions

    1. No prior installation 
    2. Mac OS
    3. Chrome Browser

### Steps to reproduce

    1. Visit https://bagisto.com/en/download/
    2. Click download.

### Expected result
 Should download the bagisto zip

### Actual result
No download started.
>

**Comment by ghermans** [comment]
Hi @dvagere thank you for bringing this to our attention, we are investigating the cause of this issue and will provide feedback once it is resolved.

**Comment by ghermans** [comment]
@dvagere the issue should be resolved.
