### ISSUE TITLE
Setting Channel Default Currency Issue

### ISSUE THREAD

**Issue by DubStepMad** [bagisto/bagisto#4528]
# Bug report

### Title
**New Currency issue.**
**On a fresh install of the project, I am given this error when trying to change the default currency on a channel `The base currency id field does not exist in currencies.` .**

### Issue Description
**Give the following error when changing the default currency on a channel `The base currency id field does not exist in currencies.`. This curreny is a new one that I added**

### Preconditions
**Please provide as detailed information about your environment as possible.**

Latest Version

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Add currency with the following:
        
    Code: GBP
    Name: Pound Sterling
    Symbol: £
    
    2. change the default channel's default currency to this.

### Expected result
**Tell us what should happen.**

*   For the curreny to be changed to GBP

### Actual result

>    **Tell us what happens instead.**

* [points....]
![image](https://user-images.githubusercontent.com/13799856/106206129-7b459800-61b7-11eb-8cba-55f4de57f748.png)

![image](https://user-images.githubusercontent.com/13799856/106206201-944e4900-61b7-11eb-94d8-0f7c021b0d62.png)

Order:

1: 
![image](https://user-images.githubusercontent.com/13799856/106206387-e1cab600-61b7-11eb-89ae-3357fd1b1612.png)

2: 
![image](https://user-images.githubusercontent.com/13799856/106206541-2bb39c00-61b8-11eb-8658-1dcb59bb76ce.png)

**Comment by vaishaliwebkul** [comment]
@DubStepMad 
to add the GBP as the base currency, select this currency under the currencies in channel https://prnt.sc/xslj1z
