### ISSUE TITLE
Coupon API - Cannot apply the coupon if the start date is today regardless the time.

### ISSUE THREAD

**Issue by kian92** [bagisto/bagisto#4542]
# Bug report

Steps to reproduce :
1) Add a new coupon code on the admin side ({domain}/admin/promotions/cart-rules/create)
2) Change the start date to **today date** for example (2 Feb 2021 12 pm) as I am writing
3) Change the end date to more than 1 month away for example (28 Feb 2021)
4) After input all the mandatory fields for the new coupon code form, click the Save Cart Rule button.
5) Next, go to the Postman to test the apply button API ({domain}/api/checkout/cart/coupon) 
6) **You will receive a message like a coupon code is invalid.**

Another scenario,
1) Change the start date of the coupon to past days like last month for example (15 Jan 2021, 12 pm)
2) Next, go to the Postman to test the apply button API ({domain}/api/checkout/cart/coupon) 
3)  **You will receive a message like success apply the coupon code.**

I think the issue is related to the start date of the coupon code.

Let me know if you need more info, thanks :)

**Comment by devansh-webkul** [comment]
@kian92,

Thanks for reporting this. I am checking this If any info needed I will ping you.

**Comment by kian92** [comment]
Thanks @devansh-webkul, it looks good now.
