### ISSUE TITLE
multiple same item as a distinct item in an order 

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#4547]
# Bug report

### Issue Description
I found there is an order that has multiple item not stack together. For example, cake x1 and cake x1 instead of cake x2. I wonder if you guys have this issue before and fixed?

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: 0.1.8

### Steps to reproduce
Not sure why

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**
![image](https://user-images.githubusercontent.com/5135163/106839657-85521580-6653-11eb-9e9c-90af529fe17e.png)

**Comment by vaishaliwebkul** [comment]
Hi @lYesterdaYl 
this issue does not exist anymore on bagisto latest version, kindly upgrade your version or you may also verify the same on Bagisto demo site https://demo.bagisto.com/

**Comment by lYesterdaYl** [comment]
> Hi @lYesterdaYl
> this issue does not exist anymore on bagisto latest version, kindly upgrade your version or you may also verify the same on Bagisto demo site https://demo.bagisto.com/

Hi, I am developing a custom version of bagisto. Is it possible that you can find the fix commit? I can fix it according to it. Or can you tell me why this happen so I can fix on mine?

**Comment by ghermans** [comment]
Hi @lYesterdaYl  since this has been fixed a while ago you can find the fix in the [commit history](https://github.com/bagisto/bagisto/commits/master).
if you still want us to provide more help regarding this please create a ticket on https://bagisto.uvdesk.com/en/customer/create-ticket/
