### ISSUE TITLE
Razorpay payment gateway integration request

### ISSUE THREAD

**Issue by sunmughan** [bagisto/bagisto#4549]
Razorpay integration would be helpful for indian customers to payout easily. Kindly add if possible.

**Comment by ghermans** [comment]
Hi @sunmughan, thank you for your feature request, we always try to integrate functions that can be useful for many users. Unfortunately Razorpay is mainly known in India, therefore the target audience for this integration is too small.

However it is still possible to integrate this payment option.  

1. a package for Razorpay is already provided by a community member https://github.com/ramlashkar/BagistoRazorpay s.
2. You can check [this post](https://forums.bagisto.com/topic/205/is-it-possible-to-integrate-razorpay-payment-gateway-in-bagisto-e-commerce) on our Forum if you want to integrate it yourself.
