### ISSUE TITLE
issue with login API

### ISSUE THREAD

**Issue by naveedfazal** [bagisto/bagisto#4551]
# Bug report

### Title
Issue with the login API

### Issue Description

http://127.0.0.1:8000/api/customer/login

I am facing issue while using the login api - response 
{
    "error": "Resource not found"
}

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

Using Postman  - following the steps mentioned in the API documents
GET http://127.0.0.1:8000/api/customer/login

Key | Value
-- | --
Accept | application/json

    
### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/74982356/106963747-7c983700-675a-11eb-8265-2b7cbbfb9af0.png)

### Actual result

Should have returned value

* [points....]

**Comment by devansh-webkul** [comment]
Hi @naveedfazal,

You are trying to use GET request whereas login API needed POST request. That's why you are getting an error.

**Comment by naveedfazal** [comment]
Thanks- but in API documentation its mentioned as GET so i used the same

**Comment by devansh-webkul** [comment]
@namvarii,

Thanks for reporting this I have fixed the documentation after merge it will get reflected.

**Comment by ghermans** [comment]
@naveedfazal , @devansh-webkul  the documentation has been updated
