### ISSUE TITLE
Save Order API Error - Paypal - Trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by AliRazaLilani** [bagisto/bagisto#4554]
# Bug report

### Title
**Save Order API Error - Paypal - Trying to get property 'id' of non-object**

### Issue Description
**I am using jwt_auth for API authorization but on hitting save-order API it gives me this error on web** 
```
{"status":401,
"message":"Trying to get property 'id' of non-object (View: \/var\/www\/html\/shopsees-web-laravel\/packages\/Webkul\/Paypal\/src\/Resources\/views\/standard-redirect.blade.php)"}
```

### My Working
**I have added a token parameter with Url and after adding jwt token with url it is like**
```
{
    "success": true,
    "redirect_url": "http://localhost/my-project-name/public/paypal/standard/redirect?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL3Nob3BzZWVzXC9wdWJsaWNcL2FwaVwvY3VzdG9tZXJcL2xvZ2luIiwiaWF0IjoxNjExOTM2OTk4LCJuYmYiOjE2MTE5MzY5OTgsImp0aSI6InU2elk0MmxKSXFXTmRwT0oiLCJzdWIiOjMyLCJwcnYiOiI4ZmNhMDg4YWJhZTJmOWE4Zjg0YTVmMGJmNmE2NTI0NDkwNTViZTAwIn0.TTxR6_HUpA1pHjOtcfpICUsXxlqfBXZYowXNBwf60To"
}
```

### My Understanding
**My understanding is : 
Either I'm sending response incorrectly
or
Middleware for paypal is accepting 'web' as session that's why it's not recognizing my jwt token and when he tries to get cart it prompts the error because object is null where laravel trying to pull ID.**

### Also I tried
**For testing, I replaced middleware in packages\Webkul\Paypal\src\Http\routes.php**
`Route::group(['middleware' => ['web']], function ()`
with
`Route::group(['middleware' => ['auth.jwt']], function ()`
and it showing these errors : 
![image](https://user-images.githubusercontent.com/62008807/106977135-89795280-677b-11eb-8ae9-19efa204c2ba.png)
and on replacing with 
`Route::group(['middleware' => ['api]], function ()`
displaying same error when middleware was 'web'.

### Steps to reproduce

    1. Adding token in param 
    2. hitting save-order API

### Expected result
**should redirect to paypal **

### Actual result

>    **Showing Error**

**Comment by rahulshukla-webkul** [comment]
Hi @AliRazaLilani 

Can you mentioned your bagisto version.

**Comment by AliRazaLilani** [comment]
my bagisto version is **v1.2.0**

**Comment by AliRazaLilani** [comment]
I resolved this .. Just Sharing if it helps anyone .. 

**Problem Solution**
The Cart Model doesn't know when the user is from api that's why when you return to paypal redirect page by save-order api it prompts error of id because it is trying to get customer id and customer is null.

**Solution**
Just make user reachability to the Cart Model. 

File ( namespace ) : 
**packages\Webkul\Checkout\src\Cart.php**

Add this to constructor 
 ```
$this->guard = request()->has('token') ? 'api' : 'customer';

        auth()->setDefaultDriver($this->guard);
```

Add this extra if clause for API user in this method 
**public function getCart(): ?\Webkul\Checkout\Contracts\Cart**

```
if(auth('api')->user() !== null){
            $cart = $this->cartRepository->findOneWhere([
                'customer_id' => auth('api')->user()->id,
                'is_active'   => 1,
            ]);
        }
```

It resolved .. ;)

Additionally, If you want to auto authenticate customer from api regardless of sending token in param so you can use this constructor block in your every constructor file.
