### ISSUE TITLE
Bagisto Reporting Exception if not Seeded

### ISSUE THREAD

**Issue by godadada** [bagisto/bagisto#4555]
# Bug report

### Issue Description
Download, install, and configure the Bagisto according to document https://webkul.com/blog/laravel-ecommerce-website/ , but skip the step of db seeding, 'php artisan db:seed'; browse to http://localhost:8000; it fails and gives Error/Exception. Please see the attached image for the error details.

### Preconditions
none

    1. framework Version.
        v1.20 master branch

### Steps to reproduce
Check above description

### Expected result
no error

*   [Screenshots, logs or description]
![Screenshot from 2021-02-05 08-45-48](https://user-images.githubusercontent.com/6087668/106992030-7d5cb780-67b2-11eb-88d2-4e923114cd24.png)

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by vaishaliwebkul** [comment]
Hi @godadada 
 If you don't run the seeder command `php artisan db:seed` then it will show you the error obviously.
You should follow all the step.

**Comment by godadada** [comment]
Hey,
  Thanks for the response.There are cases the tables may need to be altered, so the default seeders can not be used. I would expect graceful redirect to register page if db/seeding is absent and allow manual entrance of data.

Best Wishes,   Chunde Shi
godadada@yahoo.com 

    On Friday, February 5, 2021, 1:09:24 PM GMT+8, Vaishali Agarwal <notifications@github.com> wrote:  
 
 


Hi @godadada
If you don't run the seeder command php artisan db:seed then it will show you the error obviously.
You should follow all the step.
