### ISSUE TITLE
automatic tag generation using machine learning

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4556]
This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by jitendra-webkul** [comment]
This issue needs more information
