### ISSUE TITLE
getting exception on admin interface when setup using webinstaller

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4564]
# Bug report

### Title
getting exception on admin interface when setup using webinstaller

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- go to url http://localhost:8000
    2. step2- setup & go to site interface

### Expected result
No exception should come 

### Actual result

![Screenshot_252](https://user-images.githubusercontent.com/43210406/107111247-82823b00-6874-11eb-8c02-abff50c689aa.png)

**Comment by bhanu-webkul** [comment]
getting same issue again.
steps -
clone from master, run below commands
composer create-project
php  artisan migrate
php artisan db:Seed
php artisan storage:link
php artisan vendor:publish and press 0
composer dump-autoload

**Comment by ghermans** [comment]
@bhanu-webkul i really doubt that this is related to the webinstaller since you are installing bagisto manually from the console.

**Comment by ghermans** [comment]
@vaishaliwebkul can you confirm this?

**Comment by bhanu-webkul** [comment]
yes this is not related to webinstaller but i commented here just because of same exception i am getting now post installing manually from console

**Comment by vaishaliwebkul** [comment]
@ghermans
I just installed by following all the steps mentioned above by @bhanu-webkul but didn't get this issue.

**Comment by devansh-webkul** [comment]
Hi @ghermans, @bhanu-webkul, and @vaishaliwebkul,

This is generally happening due to some modules. If in starting phase channel is not caught then this will throw an error. I just additionally handled errors as well so that this can be used with other modules as well.
