### ISSUE TITLE
wrong attribute are visible on layered navigation

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4566]
# Bug report

### Title
wrong attribute are visible on layered navigation

### Issue Description
In layered Navigation, only those attribute should be visible that match the below condition
https://prnt.sc/yi8fo7
https://prnt.sc/yi8ifn

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- create a category & select only one attribute(price) inside the category under layered navigation
    2. step2- add product inside this category.
    3. step3- go to the category page

### Expected result
- only one attribute (price) should be visible under the category filter

### Actual result

>   all the attribute are visible that exist in the product 
![Screenshot_254](https://user-images.githubusercontent.com/43210406/107115952-321bd500-6896-11eb-972e-3fa7aef61714.png)
![Screenshot_255](https://user-images.githubusercontent.com/43210406/107115954-347e2f00-6896-11eb-9ffa-2eabd10db3a8.png)

**Comment by rahulshukla-webkul** [comment]
Hi @vaishaliwebkul 

The attribute will show there according to product and category that's why two attributes are visible.

**Comment by vaishaliwebkul** [comment]
@rahulshukla-webkul 
Then what is the use of Filterable Attribute inside category?????

**Comment by ghermans** [comment]
i agree with @vaishaliwebkul only attributes that are defined in the category should be displayed in the **filter section**.
