### ISSUE TITLE
getting exception on product page when social shares are enabled

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4576]
# Bug report

### Title
getting exception on product page when social shares are enabled

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- enable social share from backend
    2. step2- go to product page

### Expected result

social share option should be visible without any error

### Actual result

![Screenshot_266](https://user-images.githubusercontent.com/43210406/107199033-e6933380-6a1b-11eb-8454-5a97b0941ed6.png)

**Comment by devansh-webkul** [comment]
@vaishaliwebkul and @ghermans,

As the latest support is to be given in the used repo so I added PR there. Because overriding can't possible because package name in provider is different as compared to the directory name.

https://github.com/bagistobrasil/bagisto-product-social-share/pull/1
