### ISSUE TITLE
wrong tax calculation when delivery charges added

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4578]
# Bug report

### Title
wrong tax calculation when delivery charges added

### Issue Description
wrong tax calculation when delivery charges added

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- go to checkout & select delivery charge

### Expected result
tax should be calculated on product amount

### Actual result
![Screenshot_268](https://user-images.githubusercontent.com/43210406/107209215-88208200-6a28-11eb-9a0d-23de9a97311d.png)

**Comment by rahulshukla-webkul** [comment]
Hi @vaishaliwebkul 

Tax is applying on both product price and shipping charges and whether it should be apply or not , its depends on govt rule and policy and country.

**Comment by vaishaliwebkul** [comment]
@rahulshukla-webkul 
ok thanks
