### ISSUE TITLE
Cart Catalog is not working if I add the conditions like SKU or name or others that available in dropdown

### ISSUE THREAD

**Issue by kian92** [bagisto/bagisto#4582]
Steps to reproduce :
1) Go to {domain}/admin/promotions/catalog-rules
2) Click to Add to Catalog button
3) Make sure to key in all the mandatory fields
4) Under conditions sections:
 i) For example, select SKU as a condition 
5) Action type, you can select either fixed amount or percentage, and click Save.

Go to frontend, and you will see the price of the product never change.

**Comment by vaishaliwebkul** [comment]
@kian92 
It's working fine at master branch as well as on latest release.
Kindly verify the customer group also for which you have created the rule.

See the below attachment, Here I have followed all the steps mentioned by you & seems to be working fine.
![Screenshot_271](https://user-images.githubusercontent.com/43210406/107318747-793add80-6ac3-11eb-8468-486d2b63c7cc.png)

![Screenshot_272](https://user-images.githubusercontent.com/43210406/107318762-8061eb80-6ac3-11eb-9326-9bbce0f9bf4c.png)

![Screenshot_273](https://user-images.githubusercontent.com/43210406/107318776-8657cc80-6ac3-11eb-9287-a75b0b6175c5.png)

**Comment by kian92** [comment]
hi @vaishaliwebkul, please try the product type is bundle, thanks

**Comment by vaishaliwebkul** [comment]
@kian92 
catalog discount will not allow for bundle product If you will edit the bundle item check that the price section is not available because the bundle own price doesn't exist, it includes the simple product, so you should apply the catalog rule for simple products.

**Comment by kian92** [comment]
Thank you, @vaishaliwebkul for the explanation. Please take note if I remove all the conditions, and I go to front end page, I still can see the discounted price if the product type is bundle. So it is kinda confusing.

**Comment by vaishaliwebkul** [comment]
@kian92 
the discount which is visible on bundle product is showing because the catalog rule is still applied on simple product, so to remove this, check the respective simple product should do not have special price added inside or catalog rule doesn't exist for the same.
