### ISSUE TITLE
Layout issues on front end 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#4592]
# Bug report
### Preconditions

    1. framework Version. Master

### Steps to reproduce:
    1-  on product view page - https://prnt.sc/yxj9kh
    2-  search product in mobile view, images are not coming properly - https://prnt.sc/yxkzdm while actual image is -https://prnt.sc/yxl8rh

**Comment by devansh-webkul** [comment]
Starting with these two,

- [ ]  On product view page -> https://prnt.sc/yxj9kh
- [ ]  Search product in mobile view, images are not coming properly -> https://prnt.sc/yxkzdm while the actual image is -> https://prnt.sc/yxl8rh

**Comment by bhanu-webkul** [comment]
product search option is not working properly in mobile view 
open shop in mobile view 
search any random keyword 
it will show all products while in web it will show Whoops!
No Results Found

**Comment by vaishaliwebkul** [comment]
@devansh-webkul please fix wishlist or remove icon alignment in cart https://prnt.sc/z6jut5

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

This seems to be working fine.
