### ISSUE TITLE
Admin can select disabled locale when adding products

### ISSUE THREAD

**Issue by GiovanniMounir** [bagisto/bagisto#4604]
# Bug report

### Title
Admin can select disabled locale when adding products, although the product is never added to the selected locale.

### Issue Description
The store admin panel allows admins to select locales that are disabled while adding products. When the first locale that is selected by default, "English", is disabled by the store, trying to add a product without adjusting the locale fails. Some users may find this confusing.

### Preconditions
Using the latest release, but this issue was also present as of commit 4f92ca602fc15ffb038dde1db1d153ce90503f4e

### Steps to reproduce

1. Go to **Settings > Channels > default**
2. Select **Locales > "French"** and disable all other locales.
3. Set **Default Locale** to **French**
4. Go to **Catalog > Products > Add Product**
5. Supply product type/attribute/SKU and then click on **Save Product**
6. In the **Edit Product** page, notice that "English" is selected, although it is disabled. Fill the product details and then click on **Save Product**
7. Go back to **Catalog > Products**, the product is shown when **All Locales** or **French** is selected but has an empty name. The product is not shown when **English** is selected.

### Expected result

1. Product should be added under "English" with the details submitted, or notify user that a disabled locale was selected and prevent submission.

### Actual result

1. Product is added under "French" locale with an empty name (attached screenshot)

![Screenshot](https://user-images.githubusercontent.com/2548819/107558845-f65d7400-6be3-11eb-9bf4-1918510ecc3b.jpg)

### Suggestions

Perhaps implementing any of the following may be more user-friendly?
1. User should not be able to select disabled locale, or notify user that a disabled locale is selected.
2. Default selected locale should be the locale defined as **Default Locale** at **Settings > Channels > default** instead of **English**

Thank you!

**Comment by vaishaliwebkul** [comment]
@GiovanniMounir 
We have implemented this feature in master branch, you will get this in next release soon.
Here this the referenced issue https://github.com/bagisto/bagisto/issues/4495

**Comment by GiovanniMounir** [comment]
I had no idea this was already fixed, sorry for duplicating. Thanks a lot!
