### ISSUE TITLE
duplicate paypal smart button added in checkout 

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4609]
# Bug report

In shop package, go to checkout till the place order step then again go back to the previous step and continue to place order

![Screenshot_291](https://user-images.githubusercontent.com/43210406/107629848-b56b6b00-6c88-11eb-9cf0-8417e9803c79.png)

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

I am putting this on the same PR,
https://github.com/bagisto/bagisto/pull/4559

Will update you once it will be fixed.

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Mentioned changes have been done!
