### ISSUE TITLE
[Feature Request] Improvements and changes in REST API

### ISSUE THREAD

**Issue by nikolayandreev** [bagisto/bagisto#4616]
Hello,

Thanks for the great extension, I want to use it to build headless Ecommerce, I have a list of improvements that in my opinion are applicable outside of just my scenario of usage, but I guess this can be argued. Let me just point out that I would love to make contributions myself, but I am not familiar with the code of conduct so I will just limit this to feature request for now, also your code is really well structured since I was able to apply those changes locally.

1. When you set special price and say a product regular price is 12$, and the special price is 8$, the promotion is active, the REST API returns:
```
price: 8.0000,
formated_price: $8.00,
special_price: 8.0000,
formated_special_price: $8.00
```
I think instead of duplicating the special price, the REST API should be returning both prices so you can style it in your UI:
```
price: 12.0000,
formated_price: $12.00,
special_price: 8.0000,
formated_special_price: $8.00
```

This comes from the config files at Webkul/Product/Types where there is a method defined getMaximamPrice() and it returns the getMinimalPrice() method, which in terms will return the special_price, getMaximamPrice should be returning $this->product->price instead in my opinion.

2. Filtering by category_id is possible only for one category, this can easily be extended without interupting the current flow, by accepting multiple values like categories=1,2,3 I was able to do this by changing the file in Webkul/Products/Repositories/ProductRepository at line 146 to ```
```
if ($categoryId) {
    $categories = explode(',', $categoryId);
    $qb->whereIn('product_categories.category_id', $categories);
}
```

3. Might be an issue just on my instance, but currently when product is out of stock, and backorders are turned off I can see in the code there is check for that and it shouldn't be visible in the listings, but it is with in_stock set to false, since it's not working for me I was thinking if there was an additional parameter which you should set if you want to show out of stock products, and default to only in_stock ones or vice versa would be great.

**Comment by devansh-webkul** [comment]
Hi @nikolayandreev,

Thanks for reporting this. We will look into this and will update the API if needed. If you want you can contribute also. We will review it.

**Comment by nikolayandreev** [comment]
Fixed with https://github.com/bagisto/bagisto/pull/4617
