### ISSUE TITLE
$cart->shipping_address->city is null

### ISSUE THREAD

**Issue by Xoshbin** [bagisto/bagisto#4626]
# Bug report

After updating to the latest version I have this error:

> Trying to get property 'city' of non-object

I've created my own shipment package which calculates the rates of the shipment price based on cities. I was using checkout package form Webkul to access the city info with this code:

```
use Webkul\Checkout\Facades\Cart;
$cart = Cart::getCart();
$cart->shipping_address->city
```

My package was working well before, but now it's stopped working.  and I just checked it now it looks like I can't access the city of shipping_addrees anymore.
if this is not a bug how can I access the city inside shippind_address in the cart please.

HINT:
This happens only when no address is connected to the cart. so to connect the address to the cart I have to go to the checkout page and connect the address to the cart and comeback to the cart page to delete the items in the list. And for the same reason it happens only when there's more than one item in the cart and no address is selected. because when there's only one item in the cart and you delete it, it throughs no error because ther's no need for doing calculations anymore and the cart is empty.
thank you

**Comment by devansh-webkul** [comment]
Hi @Xoshbin,

But you will not get `shipping_address` unless and until you will connect to the checkout page and this flow is ok.

I think you must be looking for the customer's address.

**Comment by Xoshbin** [comment]
Hi @devansh-webkul, I think the flow can be better, think about the scenario I have mentioned above, what if the customer don't have address yet at the cart page or the user is not signed up yet or don't want to be a customer just wanted to buy some stuff.
So I think it's better to put the shipping calculation in the checkout page. I'm using Bagisto API for a mobile app. in the mobile app you have to make to make two different screens for the cart and checkout page. so there's no need for the shipping calculation in the cart page. that way even if the user didn't login or if he is a customer and don't have an address yet he/she can delete items in the cart. then he can go to the checkout page and link and address to the cart.
hope I'm clear
Thank you

**Comment by devansh-webkul** [comment]
Hi, I understand you concerned but still users need to give their address whether they want to buy as a guest or customer. Currently, this is just a handling portion.
