### ISSUE TITLE
No relevant keywords suggestions in Image search 

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#4627]
# Bug report

### Title
**When you search an image, it shows analysed keywords. But these keywords are nowhere related to that image**

### Issue Description
**In this case I uploaded a picture of GTA 5 Retail DVD. But the keyword suggestions were like "tobacco shop, tobacco etc." **

### Preconditions

    framework Branch: Master.

### Steps to reproduce

    1. search an image
    2. Check the analysed keywords

### Expected result
**It must show relevant keywords**

### Actual result

>    **It's showing non-relevant keywords**
![Screenshot from 2021-02-15 11-41-36](https://user-images.githubusercontent.com/53482391/107911530-c9fa7c80-6f82-11eb-999f-81d6dbb88965.png)

**Comment by vaishaliwebkul** [comment]
@aayush-webkul 
All the suggestion are coming after analyzing images automatically by machine learning, you can try to add some tshirt images to see the relevant analyze keyword.

**Comment by ghermans** [comment]
@aayushbhatt18 as @vaishaliwebkul mentioned, images are being analyzed by a third party (TensorFlow), image models can be trained (you can find more info on https://www.tensorflow.org/tutorials), however i don't directly see what we can do from our side to improve this.
