### ISSUE TITLE
If an image is already added to a product, and you search that exact same image. It should directly show the product result instead of showing analysed keywords.

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#4628]
# Bug report

### Title
If an image is already added to a product, and you search that exact same image. It should directly show the product result instead of showing analysed keywords.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    framework Branch: Master.

### Steps to reproduce

    1. Create a product and add an image to it.
    2. Now search that exact image

### Expected result
If the image is already added to a product, It should directly show the product instead of showing analysed keyword.

### Actual result

>    It's showing analysed keywords.

**Comment by ghermans** [comment]
Hi @aayushbhatt18 we investigated your request but are currently unable to provide this since the images are analyzed by Tensorflow.
