### ISSUE TITLE
A wallet system (like Amazon Pay) should be there, where a user can add money to the wallet and use it while paying for a product.

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#4631]
This repository is only for reporting bugs or issues. If you need support, please use
other channels:

1. Write an email - mailto:support@bagisto.com

2. Create support ticket on https://bagisto.uvdesk.com

3. Visit forums to get support from our community (https://forums.bagisto.com)

Alternatively, you may use Facebook (https://www.facebook.com/groups/bagisto/).

We promise that more channels are coming soon!!!

**Comment by ghermans** [comment]
This will not be integrated in the core version of Bagisto, we will make a separate extension for this.
