### ISSUE TITLE
Captcha must be implemented on User Registration so that Bot Registration can be eliminated. 

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#4632]
It's very easy to create a script for automated registration.
In order to eliminate that thing. A captcha system is required.

**Comment by aayushbhatt18** [comment]
It's also required on forget password page.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I just discussed this with the team. This feature will be in the 1.3.2 release. I am changing the milestone.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I have started working on this.
