### ISSUE TITLE
Product Images broken in admin panel

### ISSUE THREAD

**Issue by akshaypitale** [bagisto/bagisto#4637]
Hi,

When I upload product image in admin panel and hit save. After that when the page reloads images showing broken. But on website (customer view) images are showing properly.

Thanks in advance.

**Comment by vaishaliwebkul** [comment]
@akshaypitale 
check all the possible solution here https://forums.bagisto.com/topic/1548/logo-not-showing/7

**Comment by digitalgriho** [comment]
hello, sir please help me with anyone, my admin panel image also not showing properly. what can I do about that? that's showing like that I mentioned below.

**Comment by Sanjaybhattwebkul** [comment]
Hi @digitalgriho 
Can you please let me **know** which **version** of **bagisto** are you using?

**Comment by Sanjaybhattwebkul** [comment]
@digitalgriho 
Hope your issue will be resolved, if you are still getting the issue, then feel free to reopen
