### ISSUE TITLE
Checkout Process can't see further steps while placing orders

### ISSUE THREAD

**Issue by musawirjon** [bagisto/bagisto#4640]
# Bug report

### Title
**Checkout Process can't see any futher steps while placing orders.**

### Issue Description
**While proceed to checkout process I filled all the details and here is no continue/next button to move the next step.**

### Preconditions

    1. Latest.
    2. 4636.

### Steps to reproduce
    1. user fill addresses details
    2. A button to continue next step need already be there but will disabled till user fill required fields.

### Expected result
**Will be great if here is an option button of continue to next step and this button will be disabled till user fill required fields.**

*  https://prnt.sc/zp9bmc

**Comment by musawirjon** [comment]
Hello @vaishaliwebkul, can you please have a look into it.

**Comment by vaishaliwebkul** [comment]
@musawirjon 
please mention your bagisto version and check the error on console if you're getting any error show the screenshot.

**Comment by musawirjon** [comment]
Hi @vaishaliwebkul 
I checked I have no error in console, My version is the latest one 1.3. 
Their is no error, I saw by clicking outside the last input field, then I can see other steps. but it's not UX friendly as user don't know about this. 
Will be better if have a button ( Continue ) instead.

**Comment by vaishaliwebkul** [comment]
@musawirjon 
On one page checkout when the last phone number is entered correctly then automatically the loader will be showing and the next step(Shipping) will show to continue.

**Comment by musawirjon** [comment]
@vaishaliwebkul 
My client wanted me to make it working with continue button. I also suggest a continue button will be good. As it's signal customers for filling and moving on to next steps. I tried myself but no success. Any help regard this. Or make it in the core. As this will be a good enhancement regarding UX things.

**Comment by musawirjon** [comment]
As in case of guest checkout, most users don't want to fill whole form. and they just put dummy data on the fields like phone number and others. So in that case user will not be able to proceed to checkout.

**Comment by musawirjon** [comment]
Hi @vaishaliwebkul,
Is their any progress on this issue. Or this need to be done individually. As this will be good in bagisto store it self as well.

**Comment by vaishaliwebkul** [comment]
@musawirjon 
Currently, I have marked this with enhancement.
the developer will look into it.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 

As we **discuss** there is **no need** for the **next button**. so I am closing this enhancement.
