### ISSUE TITLE
Getting data in client id "sb" by default.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4641]
# Bug report

### Title
Getting data in client id "sb" by default.
### Issue Description
Installed bagisto and go to Configure->sales->payment methods
### Preconditions

    1. framework Version.-1.3.0

### Actual result
Getting data in client id "sb" by default.

![download (22)](https://user-images.githubusercontent.com/45203177/108072068-72483800-708c-11eb-8573-163533d9d055.png)

**Comment by devansh-webkul** [comment]
@jyoti-webkul,

Paypal also provides client id `sb` for faster development. So, `sb` will also work. What is the expected result? Should I remove sb or leave it as it is.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
"sb" is used for development in this case we don't need to add client secret, so the client ID or client secret should not be mandatory field

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

Client ID and Client Secret is needed for business account detection. So displaying user friendly message as per the discussion.
