### ISSUE TITLE
Getting exception when admin change the status of subscribed user to false.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4643]
# Bug report

### Title
Getting exception when admin change the status of subscribed user to false.

### Issue Description
Getting exception when admin change the status of subscribed user to false.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-1.3.0

### Steps to reproduce

    1. step1- Go to Email Marketing->Newsletter Subscription
    2. step2- Change the status to false.

### Expected result
Status should be updated
### Actual result
Getting exception when admin change the status of subscribed user to false.

![Workspace 1_066](https://user-images.githubusercontent.com/45203177/108073334-ee8f4b00-708d-11eb-9294-d71aaafa4c99.png)

**Comment by ghermans** [comment]
@jyoti-webkul i have just verified this with a fresh setup

### Subscriped set to true
![1](https://user-images.githubusercontent.com/1594411/108077810-3d78b880-706d-11eb-9aa5-0246e59f3120.PNG)
### Subscriped set to false
![2](https://user-images.githubusercontent.com/1594411/108077817-3fdb1280-706d-11eb-8af3-bf0585c3919d.PNG)

**Comment by ghermans** [comment]
@vaishaliwebkul can you verify if you can reproduce the issue?

**Comment by vaishaliwebkul** [comment]
@ghermans 
Yes, Getting this issue when the guest users subscribed https://prnt.sc/ztfekq and the admin tries to unsubscribed them.
