### ISSUE TITLE
On updating the direction of locale,direction of admin panel should not changed.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4644]
# Bug report

### Title
On updating the direction of locale,direction of admin panel should not changed.
### Issue Description
On updating the direction of locale,direction of admin panel should not changed.
### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-1.3.0

### Steps to reproduce

    1. step1- Go to setting->locale
    2. step2- Update the direction to RTL of any locale

### Expected result
Direction of admin panel should not changed

### Actual result

Direction of admin panel changed

![Workspace 1_067](https://user-images.githubusercontent.com/45203177/108082460-21d6d780-7098-11eb-86f6-3ba0f1ba4e98.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul @ghermans 
If you will change the default locale of admin in RTL then admin panel will also change in RTL locale.
This is working fine as expected.

**Comment by jyoti-webkul** [comment]
@vaishaliwebkul 
I don't want to change the direction for admin panel, I only want to change the direction for website.
How can we achieve this?

**Comment by rahulshukla-webkul** [comment]
Hi @jyoti-webkul 

You have changed admins defaults (eg-en)  locale's direction to RTL that's why admin panel gets changed.
Every channel has a default locale and set this locale's direction to RTL, it will automatically changed for website.
