### ISSUE TITLE
/api/products returns trying to get property 'product' of non-object

### ISSUE THREAD

**Issue by nikolayandreev** [bagisto/bagisto#4645]
Steps to reproduce:

Install a fresh copy of Bagisto v1.3.0
```
$ composer create-project bagisto/bagisto

set the values in .env and run

$ php artisan bagisto:install
$ php artisan bagisto:generate product 10
$ php artisan serve
```

Visit: http://127.0.0.1:8000/api/products

Result:
![image](https://user-images.githubusercontent.com/26118671/108083724-0f4ea500-707c-11eb-9178-8109b13f01e9.png)

**Comment by nikolayandreev** [comment]
@ghermans `GET /api/categories` also return error:

![image](https://user-images.githubusercontent.com/26118671/108086498-20e57c00-707f-11eb-8839-a8059e7538bf.png)

**Comment by ghermans** [comment]
@nikolayandreev thank you for reporting this issue, we will investigate the cause of this and provide a fix.

**Comment by nikolayandreev** [comment]
Hello @ghermans don't mean to pressure, but you have an idea if there is a workaround for this or a PR about it so I can edit the code and keep working on the integration?

Thanks!

**Comment by rahulshukla-webkul** [comment]
Hi @nikolayandreev 

Thanks for reporting this one, we have fixed this issue - https://github.com/bagisto/bagisto/pull/4660
But we are unable to generate it for categories, can you provide more info for category.

**Comment by nikolayandreev** [comment]
@rahulshukla-webkul That's great news and it seems like categories was something on my end, because I cannot reproduce it either. I guess we can close this issue?
