### ISSUE TITLE
Getting issue in editing events in Email Marketing.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4649]
# Bug report

### Title
Getting issue in editing events in Email Marketing.

### Issue Description
Getting issue in editing events in Email Marketing.

### Preconditions

    1. framework Version.-1.3.0

### Steps to reproduce

    1. step1- Go to Promotion->Email Marketing->Events
    2. step2- Try to edit an event

### Expected result
Admin should be able to edit events.

### Actual result
Getting issue in editing events in Email Marketing.
![Workspace 1_069](https://user-images.githubusercontent.com/45203177/108186534-7bd8ab00-7133-11eb-8c61-712d126590fa.png)

**Comment by rahulshukla-webkul** [comment]
Hi @jyoti-webkul 

This is default event of system and it can't be changed. It is used to send wishes to subscribe customers on their birthday.

**Comment by jyoti-webkul** [comment]
ok
