### ISSUE TITLE
Product number should not accept negative values.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4651]
# Bug report

### Title
Product number should not accept negative values.

### Issue Description
Product number should not accept negative values.

### Preconditions

    1. framework Version.-1.3.0

### Expected result
Product number should not accept negative values.
### Actual result

Product number accepting negative values
![download (24)](https://user-images.githubusercontent.com/45203177/108208142-a7b55a00-714e-11eb-9732-1fab5ea48d22.png)

**Comment by ghermans** [comment]
Product numbers can be like that actually, for example 

MSI Gaming GF75 has a product number: MSI-GF7510SCS443BE 
Microsoft WIndows 10 Home has product number KW9-00152
