### ISSUE TITLE
Added product video is not working on front-end.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4652]
# Bug report

### Title
Added product video is not working on front-end.

### Issue Description
Added product video is not working on front-end.
### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-1.3.0

### Steps to reproduce

    1. step1- Add a video for product
    2. step2- Check the added video on store.

### Expected result
Video should play on front-end
### Actual result
Added product video is not working on front-end.

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
 product videos are working fine, please check https://prnt.sc/103nuj8

**Comment by devansh-webkul** [comment]
@vaishaliwebkul and @jyoti-webkul,

I am closing this as the product video is working fine.
