### ISSUE TITLE
Making billing address informations optional

### ISSUE THREAD

**Issue by Xoshbin** [bagisto/bagisto#4653]
Since most of the shops made is local or used in a range of a country or a small area I think it's better to make some fields optional to be visible in the checkout page.

**Comment by luharuka** [comment]
hey @ghermans can you assign it to me under hactoberfest tag

**Comment by naresh-webkul** [comment]
i'am working  on this

**Comment by naresh-webkul** [comment]
you can check the related view files at the following path:
resources/theme/velocity/views/checkout

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I have started working on this.
