### ISSUE TITLE
Composer error with khaled.alshamaa/ar-php version

### ISSUE THREAD

**Issue by cagartner** [bagisto/bagisto#4654]
# Bug report

### Composer error with khaled.alshamaa/ar-php version
Error after trying to install any composer package on the last version on bagisto

### Issue Description
After you try to add any package on Bagisto we have this error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package khaled.alshamaa/ar-php (locked at v5.5.2, required as ^6.0.0) is satisfiable by khaled.alshamaa/ar-php[v5.5.2] but these conflict with your requirements or minimum-stability
```

The problem is that, on composer.json the version is 6.0.0, but on composer.lock the version still on 5.5.2, you need to upgrade your composer.lock to the last version of `khaled.alshamaa/ar-php`

### Preconditions

    1. Version 1.3.0

### Steps to reproduce

    1. Install the last version of Bagisto
    2. Try to add any composer package

### Expected result
The package is installed without the problem

### Actual result

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package khaled.alshamaa/ar-php (locked at v5.5.2, required as ^6.0.0) is satisfiable by khaled.alshamaa/ar-php[v5.5.2] but these conflict with your requirements or minimum-stability.
```

**Comment by ghermans** [comment]
@cagartner thank you for reporting this, we will provide a fix for this asap.
