### ISSUE TITLE
Incorrect error message if invalid client id and secret id is provided for paypal smart button.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4655]
# Bug report

### Title
Incorrect error message if invalid client id and secret id is provided for paypal smart button.

### Issue Description
Incorrect error message if invalid client id and secret id is provided for paypal smart button.
### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-1.3.0

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1- Add any random data in client id and secret key.
    2. step2- Checkout with paypal smart button.

![Workspace 1_070](https://user-images.githubusercontent.com/45203177/108219085-60819600-715b-11eb-8097-23203c1e95ab.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
Any invalid or random credentials in the client id or client secret will show the error alert.

Kindly add the valid client ID and secret in payment method along with valid currency Accept eg INR,USD https://prnt.sc/zv8mf2
check the paypal smart button payment flow here https://bagisto.com/en/whats-new-in-bagisto-v1-3-0/

**Comment by ghermans** [comment]
@vaishaliwebkul what @jyoti-webkul is trying to say is that when you enter invalid data that the alert window is displaying the wrong error message.

**Comment by rahulshukla-webkul** [comment]
Hi @ghermans @jyoti-webkul 

The error message is return from paypal itself.

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
the error alert is now updated with reference to PR https://github.com/bagisto/bagisto/pull/4669
