### ISSUE TITLE
api/products return null in 1.3.0

### ISSUE THREAD

**Issue by Xoshbin** [bagisto/bagisto#4656]
# Bug report

After updating to V1.3.0 the the api url is not working for products, it's giving error:
`"message": "Trying to get property 'product' of non-object",`

**Comment by ghermans** [comment]
Closing this one since another issue report already exists #4645.
Please try to verify on the [Issues page](https://github.com/bagisto/bagisto/issues) if a issue has already been reported before submitting a new issue report.
