### ISSUE TITLE
Online Demo throws 500err

### ISSUE THREAD

**Issue by lostdesign** [bagisto/bagisto#4657]
# Bug report

### Title
Demo does not load, throws an 500err after provisioning

### Issue Description
After visiting https://demo.bagisto.com/, validating I am not a Robot and waiting for a Demo to be prepared, I am redirected to https://demo.bagisto.com/bagisto-common/ which shows laravels default 500 HTTP Error.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Open https://demo.bagisto.com/
    2. Request Demo
    3. See error at https://demo.bagisto.com/bagisto-common/

### Expected result
Wanted to try the demo.

### Actual result
Error was shown.

**Comment by vaishaliwebkul** [comment]
@lostdesign 
We are working on it , will revert you when get fix.

**Comment by vaishaliwebkul** [comment]
Hi @lostdesign 
Bagisto Demo has been updated now, please check.
