### ISSUE TITLE
rango font is missing 

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4658]
# Bug report

### Preconditions

1. master branch

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

1. The file is instead located in packages/Webkul/Velocity/src/Resources/assets/sass/ but the fonts are missing from the asset folder

**Comment by devansh-webkul** [comment]
Hi @ghermans,

If you check the publishable folder in Velocity's package, you will indeed find the fonts folder. Maybe for avoiding duplicate files not given in the assets folder.
