### ISSUE TITLE
Argument 3 passed to Lcobucci\\JWT\\Signer\\Hmac::doVerify() must be an instance of Lcobucci\\JWT\\Signer\\Key, null given

### ISSUE THREAD

**Issue by Xoshbin** [bagisto/bagisto#4663]
# Bug report

V1.3
When using JWT "?token=true" with the API routes, Most of the routes that need Authentcation give this error.
I tried with addresses and orders.
`Argument 3 passed to Lcobucci\\JWT\\Signer\\Hmac::doVerify() must be an instance of Lcobucci\\JWT\\Signer\\Key, null given`

**Comment by Xoshbin** [comment]
Can anyone confirm if it's a bug or just me having this error please?

**Comment by devansh-webkul** [comment]
Hi @Xoshbin,

This is not a bug. You need to run `php artisan jwt:secret`. And then again login with `?token=true`.

**Comment by Xoshbin** [comment]
@devansh-webkul  Thank you
