### ISSUE TITLE
override theme issue for mail

### ISSUE THREAD

**Issue by dhruv1998** [bagisto/bagisto#4665]
We are trying to override from  \packages\Webkul\Shop\src\Resources\views\emails  in our \resources\themes  channels folder for our multi-channel site for first channel emails are overriding from our  \resources\themes\ar  folder but when we are trying from our \resources\themes\yn  this channel also overriding from \resources\themes\ar  folder but we made different email templates in both channels it’s only happening when emails are getting trigger from the queue without queue emails are coming from respective email channels.

**Comment by devansh-webkul** [comment]
Hi @dhruv1998,

I am not getting this. You have two channels i.e. the first channel is coming from the `ar` folder and the second one is from the `yn` folder which is not working.

It's better if you share some code or screencast so that I can further check.

**Comment by dhruv1998** [comment]
We are using bagisto  for two different projects from the same codebase and both projects have different email templates so the first project ar email override is working perfectly but when it comes to the second project yn it should override from yn folder but this is also overriding from ar folder which is not correct

**Comment by devansh-webkul** [comment]
Hi @dhruv1998,

That means something wrong in the `yn` folder. Please check the paths and locations properly.

**Comment by devansh-webkul** [comment]
Hi @dhruv1998,

I am closing this as this seems to be the problem with personal setup and code structure.
