### ISSUE TITLE
No Respond when view logo.blade.php is loaded

### ISSUE THREAD

**Issue by Ruixian1006** [bagisto/bagisto#4674]
# Bug report

### Title
No Respond when view logo.blade.php is loaded

### Issue Description
**Description helps the developers to understand the bug. It describes the problem encountered or some after effect of some kind.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version: 1.2.0

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug. If relevant please include code samples.**

    1. When I'm trying to save an Invoice from the admin Panel if there is an error "maximum execution time of 60 seconds exceeded" that occurred. I will need to Kill the Port and restart the Server. 
    2. After I kill the Port and restart the Server, there will be an issue when the system is generating the email template.
    3. So when I track back, it is caused by the image in  packages\Webkul\Shop\src\Resources\views\emails\layouts\logo.blade.php. 
    4. So when I remove the "src" attribute in "img" element, it works.
 Original Code 
```
@if (core()->getConfigData('general.design.admin_logo.logo_image'))
    <img src="{{ \Illuminate\Support\Facades\Storage::url(core()->getConfigData('general.design.admin_logo.logo_image')) }}" alt="{{ config('app.name') }}" style="height: 40px; width: 110px;"/>
@else
    <img src="{{ asset('vendor/webkul/ui/assets/images/logo.png') }}" alt="{{ config('app.name') }}"/>
@endif
```
My changed
```
@if (core()->getConfigData('general.design.admin_logo.logo_image'))
    <img src="" alt="{{ config('app.name') }}" style="height: 40px; width: 110px;"/>
@else
    <img src="{{ asset('vendor/webkul/ui/assets/images/logo.png') }}" alt="{{ config('app.name') }}"/>
@endif
```
I suspect it is cause by this line of code :
```
{{ \Illuminate\Support\Facades\Storage::url(core()->getConfigData('general.design.admin_logo.logo_image')) }}
```

I hope there will be a solution for this, as I will need to logo to appear in my email template. 
Thank You.

**Comment by devansh-webkul** [comment]
Hi @Ruixian1006,

This issue has been fixed in the latest version.

https://github.com/bagisto/bagisto/blob/c4148f31faae0de6761ef871863b89bfc57adc5c/packages/Webkul/Shop/src/Resources/views/emails/layouts/logo.blade.php#L1

**Comment by Ruixian1006** [comment]
Hi @devansh-webkul  thanks for your help !
