### ISSUE TITLE
Catalog rules and product price filter

### ISSUE THREAD

**Issue by howdu** [bagisto/bagisto#4682]
If you add a catalog rule for all products then the category product filtering price does not match this. 

Tested with latest version and reproduced on demo website. 

<img width="1144" alt="Screenshot 2021-02-24 at 08 19 37" src="https://user-images.githubusercontent.com/533658/108970636-e7fa6800-7679-11eb-8cb5-5a129444f2f3.png">

**Comment by vaishaliwebkul** [comment]
@devansh-webkul I am also getting the same issue while product on price filtration based on catalog rule

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

The product needs to be saved one more time for filter working. Otherwise, if the product price is edited on the basis of catalog rule then this will go n times.

**Comment by rahulshukla-webkul** [comment]
Hi @howdu 

We have fixed this isssu - https://github.com/bagisto/bagisto/pull/4689

**Comment by devansh-webkul** [comment]
Hi @howdu,

Right now fix is proposed. Please don't close until PR gets merged.
