### ISSUE TITLE
configurable item is still visible on search page when out of stock is disabled

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4686]
# Bug report

### Title
configurable item is still visible on the search page when out of stock is disabled

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- set 0 inventory  for configurable product
    2. step2- disable out of stock item
    3. step3- search the item on frontpage

### Expected result
 on search page configurable item is still visible

### Actual result

![Screenshot_307](https://user-images.githubusercontent.com/43210406/109134366-f8930700-777b-11eb-8b17-ea00a4935c6a.png)

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
The out of stock item should not visible in related or link product section as well if configuration is disabled
![Screenshot_312](https://user-images.githubusercontent.com/43210406/109168857-3e17fa00-77a5-11eb-9fa1-00b8cd665c24.png)

**Comment by nikolayandreev** [comment]
It would be best if you can specify weather you want to show out of stock products via a parameter when making API calls to products, example use case would be if you want to show out of stock in the search or in "People also bought" slider etc.. Also wishlist products.. I am talking from the perspective of a headless API usage, but it will also be good for velocity theme
