### ISSUE TITLE
Variation Product does not show individually 

### ISSUE THREAD

**Issue by gaganrocky** [bagisto/bagisto#4687]
Hi there ,
                  i make variation product visible individually  from back end but does not come in product list. How can i make variation available individually also?

Regards,
Gagandeep Singh

**Comment by vaishaliwebkul** [comment]
@gaganrocky 
do you want to display each variant in the shop?

**Comment by gagandeep007** [comment]
Yes Need to display individually also.

**Comment by vaishaliwebkul** [comment]
@gagandeep007 
 Enable each variant from backend or set "visible individually" to true for showing on frontend https://prnt.sc/10fz9nt

**Comment by gaganrocky** [comment]
Hi @vaishaliwebkul  i did try but still product is not coming in product api  even in detail api.
