### ISSUE TITLE
HERE IS THE BEST EXAMPLE. The image resizing is really not correct it stops staying within the DIV from what I am seeing. It is resizing and actually being warped by the div dimensions not adjusting. See the small image below the big one that shows it exactly.

### ISSUE THREAD

**Issue by mikeyapina** [bagisto/bagisto#4691]
# Bug report

https://drive.google.com/file/d/1roGLMXJn5nVLXFYfw0G1IGGvynohCs32/view?usp=sharing

### Issue Description
The image resizing is really not correct it stops staying within the DIV from what I am seeing.  
It is resizing and actually being warped by the div dimensions not adjusting. See the small image below the big one that shows it exactly.

The VUE carousel implementation in 1.3.0 is not working the same as in 1.2.0 the above link shows how it is very contorted

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. bagisto verion 1.3.0
    2. the latest since launch

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug. If relevant please include code samples.**

1. Go to the website [beta.ov3rt.com](https://beta.ov3rt.com) and just go from mobile view to www view and you will see the images render horribly
2. Same as above it is the same also in any grid format
3. It appears the DIV is not adjusting so the images stay the same but the div never changes through the framework

### Expected result
**Tell us what should happen.**

The images and div should adjust depending on the WWW size

https://drive.google.com/file/d/1roGLMXJn5nVLXFYfw0G1IGGvynohCs32/view?usp=sharing

### Actual result

>    **Tell us what happens instead.**

* images resize but the DIV does not
* this then causes the images to warp
* this didn't happen in 1.2.0

**Comment by mikeyapina** [comment]
The issue is bad! How do I turn off the carrousel when I am in Mobil? It is embarrassing at this point! Until you gusy figure out what you changed from 1.2 to 1.3 this is really bad. I am glad I didn't put that in my production environment,.

**Comment by devansh-webkul** [comment]
Hi @mikeyapina,

https://drive.google.com/file/d/1roGLMXJn5nVLXFYfw0G1IGGvynohCs32/view?usp=sharing. This is not working, it will need google account access.

Can you share via. light shot (if screenshot) or by loom (if video).

**Comment by mikeyapina** [comment]
Here is a loom of the same video

https://www.loom.com/share/6ee38cca8a2340ca954456e8c681edec?sharedAppSource=personal_library

**Comment by devansh-webkul** [comment]
Hi @mikeyapina,

OK! Got the point. You are mentioning the product view page.

**Comment by devansh-webkul** [comment]
Hi @mikeyapina,

I just check your instances and there are several bugs which have been fixed after 1.2.0, one of the critical ones is this,
https://github.com/bagisto/bagisto/issues/4065

And most of the responsive issues has been fixed,
https://github.com/bagisto/bagisto/pull/4099

From your videos, it looks like the image is not carrying the div, but the problem is the image is locked at a certain width and height to maintain the aspect ratio so to overcome this I centered the image also.

Even though your image is resized in the mobile version but we cannot neglect the major issues also.

**Comment by mikeyapina** [comment]
Ok well, then I had 1.2.0 .. I did not do an upgrade. I did a complete "new" install the overlapping issue glad is gone as it had been present in past builds. But, now we have a warped image issue in 1.3.0. This issue is so bad I can not deploy the 1.30 version please check our beta.ov3rt.com the images are so bad that it's embarrassing. Yes, the overlapping is fixed but the images are a nightmare. Of course, I showed you the 1.2.0 version does not have this issue. I have done your update on the 1.2.o site ov3rt.com. Please let's understand the issue. I sent you a line of the exact issues. This is affecting the landing page warped in the carousel.

It appears you are trying to say it is a previous issue. Not it is not it is a 1.3.0 issue. New just crept up in this version because I did it twice now. check our eddiebarber.ov3rt.com same exact issue on the landing page! In the carousel.

Whereas in the 1.2.0 landing page there has never been this issue. Check out 1.2.0 ov3rt.com once again no issue on the landing pages. No updates anywhere that were not the exact same changes made in 1.2.0 with no issues.

It appears to be something forcing the image size. ZBZecaseu when you go to the mobile it stakes a 1080 height of the screen and contorts the image. I looked at it and it appears the Carousel JScript is forcing this. Why what is happening that this would be something not in 1.2 but exist in 1.3?

**Comment by vaishaliwebkul** [comment]
@mikeyapina 
I found some fixes when adding changes as referenced PR https://github.com/bagisto/bagisto/pull/4704, so requesting you also to have a look into it and just pull these changes in 1.3 then let us know if your expected issues have been resolved or not?

**Comment by mikeyapina** [comment]
Sadly there are not the same files or correlate to the same ones .. so have no idea if the changes should be made ...

... this the old 

{
    "/js/velocity.js": "/js/velocity.js?id=a45dba1beb5c6f79193d",
    "/css/velocity-admin.css": "/css/velocity-admin.css?id=4322502d80a0e4a0affd",
    "/css/velocity.css": "/css/velocity.css?id=2ee191136dd475471b01"
}


this is the change as per

 4  packages/Webkul/Velocity/publishable/assets/mix-manifest.json


https://github.com/bagisto/bagisto/pull/4704/commits/ecccbdea23e533f387c613bfbb9585001aeef81b

please advice ..

**Comment by mikeyapina** [comment]
also this does not compile without an error 

 4  packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss 
@@ -75,6 +75,10 @@
        top: -48px;
    }

    .sticky-header {
        display: none !important;
    }

    .vc-full-screen {
        display: none !important;
    }

**Comment by mikeyapina** [comment]
Please lets get this done this looks bad and trying to use these new 1.3.0 upgrade since it has some important upgrades that makes the product more sustainable as a product in market. But this vue, carousel, whatever you have done different in 1.3 that wasn't an issue in 1.3 is disastrous as a product rollout.

**Comment by mikeyapina** [comment]
THIS IS NOT FIXEWD .. THIS IS ABSOLTUELY NOT TRUE! NVM the product pages are not working .. please look at the the distortion .. this is horrible this WAS NOT AN ISSUE IN 1.2.0 YOU NEED TO GO BACK TO THE VERSION THAT WORKED WHNE IT COMES TO THE VUE IMAGE CONTROLLER THIS IS A NIGHTMARE!!1=

**Comment by devansh-webkul** [comment]
Hi @mikeyapina,

The image which you have uploaded is actually a distorted image, have a look,
https://eddiebarber.ov3rt.com/cache/large/product/6/oinUbsdHHqQPqtWDmUiBovfSxKosLe7TCBxeV3Ka.png

**Comment by mikeyapina** [comment]
No they are not they were uploaded not distrorted this is my point as well. I upladied the saem 600 px image on the other site - 1.2 with no distrotation
