### ISSUE TITLE
linked products are not visible on checkout

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4692]
# Bug report

### Title
linked products are not visible on checkout

### Issue Description
linked products are not visible on checkout

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- add linked product in any simple product
    2. step2- add the product in cart

### Expected result

linked product are not visible

### Actual result

linkend product should be visible

![Screenshot_316](https://user-images.githubusercontent.com/43210406/109300693-dd4bf880-785c-11eb-9f3a-6bc90ba3cce0.png)

**Comment by rahulshukla-webkul** [comment]
Hi @vaishaliwebkul 

Only cross sells  are used to visible in cart page.
