### ISSUE TITLE
Possible bugs in the API

### ISSUE THREAD

**Issue by Xoshbin** [bagisto/bagisto#4694]
# Bug report

V1.3.1

1- the locale is not working on the cart api 
'/checkout/cart?token=true&locale=ku&currency=iqd'.
2- the search is not working for Kurdish or Arabic in the API
'/products?search=برنج&page=1&limit=10&locale=ku&currency=iqd'

**Comment by devansh-webkul** [comment]
Hi @Xoshbin,

Does this locale, you have created in your project?

**Comment by Xoshbin** [comment]
Hi @devansh-webkul Yes I created Kurdish "ku" locale in my project, but the error is same for Arabic too.

**Comment by devansh-webkul** [comment]
Hi @Xoshbin,

Can you share some samples? So that I can verify this.

**Comment by Xoshbin** [comment]
Sure the examples are below, since my default locale in my channel is Kurdish. so for both English and Arabic it's returning The Kurdish one.
<img width="1361" alt="Screen Shot 2021-03-03 at 9 58 47 AM" src="https://user-images.githubusercontent.com/1606070/109766677-8bfa8b00-7c07-11eb-9d40-86abdbdc3448.png">
<img width="1361" alt="Screen Shot 2021-03-03 at 9 59 54 AM" src="https://user-images.githubusercontent.com/1606070/109766690-9026a880-7c07-11eb-8799-8ea8a678d352.png">

**Comment by devansh-webkul** [comment]
At @Xoshbin,

OK, I am checking this with the Arabic locale.

**Comment by devansh-webkul** [comment]
Hi @Xoshbin,

After checking all the code, I came to the conclusion that this is because of the `locale` key. `locale` key is not found in the request because it is removed by the middleware i.e. your results fallback to the default locale.

https://github.com/bagisto/bagisto/blob/ee75f42c0248476a816d7d59bb3242471e0deec8/packages/Webkul/Shop/src/Http/Middleware/Locale.php#L48

If you want you can comment this, but right now I need to check this impact also. So not changing this.

**Comment by Xoshbin** [comment]
Hi @devansh-webkul 
Thanks for following it, anyway what about the search one:

2- the search is not working for Kurdish or Arabic in the API
'/products?search=برنج&page=1&limit=10&locale=ku&currency=iqd'

**Comment by devansh-webkul** [comment]
Hi @Xoshbin,

This is because maybe the locale key got removed and searching takes place on the `en` locale. I am just assuming I can give you a full explanation once this issue is fixed.

**Comment by devansh-webkul** [comment]
Hi @Xoshbin,

Actually, I just verified this with a team and this is the default behavior. Searching can only take place on the default locale. So if you want, you need to customize this at your end.

**Comment by Xoshbin** [comment]
Hi @devansh-webkul 
What do you mean by customizing it at my end, I'm adding the locale in the route when searching if you mean that.

**Comment by devansh-webkul** [comment]
I want to say that you cannot search by the `locale` key. You need to override the method from where searching takes place and then you need to create one more key in your overridden method and search by that.
