### ISSUE TITLE
category slug should not translation based

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4698]
# Bug report

### Title
category slug should not translation based

### Issue Description
category slug should not translation based

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- rename(men-> men fashion) category and save
    2. step2- add other cateogry with older name(men)

### Expected result
the url key should be updated for all locale when it gets update only for single locale

### Actual result

![Screenshot_317](https://user-images.githubusercontent.com/43210406/109477899-977e7280-7a9e-11eb-89e2-d2bd7ad13e6b.png)

**Comment by vaishaliwebkul** [comment]
fixed

**Comment by roccomilluzzo** [comment]
Honestly it does not make any sense, any locale should have his own path prefix, example (site.com/en/category), but besides that it was correct that the category url was localized, better for seo, for google shopping, for campaigns, I can't understand why you're messing this up, just look at shopify, magento, woocommerce, prestashop and avoid reinventing the wheel
