### ISSUE TITLE
getting exception when update inactive item on cart

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4709]
# Bug report

### Title
getting exception when update inactive item on cart

### Issue Description
getting exception when update inactive item on cart

### Preconditions

    1. framework Version- 1.3.1
    2. referenced PR - https://github.com/bagisto/bagisto/pull/3138
  
### Steps to reproduce

    1. step1- add to product in cart (simple or configurable)
    2. step2- inactive config item from backend
    3. step3- now update the cart again

### Actual result

https://www.loom.com/share/4410777bc98d42bfbe076f28319022a4

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

Not able to reproduce in the master. Maybe this gets fixed from this PR,
https://github.com/bagisto/bagisto/pull/4696

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
Thanks for updating, seems to be working fine in master, so closing this.
