### ISSUE TITLE
search with image problem

### ISSUE THREAD

**Issue by blackWhaleDev** [bagisto/bagisto#4723]
# Bug report

### Title
**In searching with the image I'm facing with this error**

`Uncaught (in promise) TypeError: this.__ is not a function`

**after that I logged the error and cache this**

```
Error: Requested texture size [0x0] is invalid.
    at tfjs:17
    at _V (tfjs:17)
    at tfjs:17
    at e.t.createUnsignedBytesMatrixTexture (tfjs:17)
    at e.t.acquireTexture (tfjs:17)
    at t.n.acquireTexture (tfjs:17)
    at t.n.uploadToGPU (tfjs:17)
    at t.n.getTexture (tfjs:17)
    at Object.kernelFunc (tfjs:17)
    at n (tfjs:17)
```

![Capture](https://user-images.githubusercontent.com/66624615/110781715-4b3dea00-8277-11eb-9341-f9f1ef555564.PNG)

**Comment by devansh-webkul** [comment]
Hi,

It seems to be the problem with your local. Please check the path, urls, and storage linking.

**Comment by blackWhaleDev** [comment]
@devansh-webkul 
Thank you yes that was for my config
in my server, APP_URL was server IP and when I change it to my real URL it fixed

and in my local wrongly APP_URL was https.... so I change it to http and fixed
