### ISSUE TITLE
Pending order issue 

### ISSUE THREAD

**Issue by naumcei** [bagisto/bagisto#4724]
The following issue appears on bagisto version 1.3,1

**Steps to reproduce**
When **checkout** stage **fails** then the orders automatically are with status pending, the system reports
![image](https://user-images.githubusercontent.com/10113045/110788272-b20ad580-826e-11eb-97ee-11664a211434.png)
Webkul\Shop\Http\Controllers\OnepageController@saveOrder

Admin dashboard is down as well
![image](https://user-images.githubusercontent.com/10113045/110787667-ef229800-826d-11eb-8b90-28446c49953b.png)

**Comment by devansh-webkul** [comment]
Hi @naumcei,

Please share some steps so that I can further check. Like how the transaction failed and which product type you are trying to purchase.

**Comment by naumcei** [comment]
Thanks @devansh-webkul 

In order to reproduce the bug Please take a look at the following image 
![Uploading image.png…]()

When the user tries to create an order the **checkout** section is buggy

**Comment by devansh-webkul** [comment]
Hi @naumcei,

We will check and let you know.

**Comment by vaishaliwebkul** [comment]
@naumcei 
the screenshot provided by you are not much very helpful, would be helpful if you could share error log 
I have verified with the same steps but not getting this error 
https://www.loom.com/share/4811e63ae68d49e0b5d2673f4a6b450f

**Comment by naumcei** [comment]
Thanks, @vaishaliwebkul  for the supported video 

Here is the error log
![image](https://user-images.githubusercontent.com/10113045/110921714-2c932e00-831f-11eb-9145-3633eae91093.png)

**Comment by vaishaliwebkul** [comment]
@naumcei 
Please let me know, Is there any value added inside configuration->sales->order settings-> minimum order amount ????

**Comment by naumcei** [comment]
Hi @vaishaliwebkul,

Nope, please take a look at the screenshot, Do we miss something

![image](https://user-images.githubusercontent.com/10113045/110944950-6c690e00-833d-11eb-9237-993515d1e2f3.png)

**Comment by devansh-webkul** [comment]
Hi @naumcei,

Not able to reproduce that. I have followed all your steps. Can you take a fresh clone and try with that.

**Comment by naumcei** [comment]
@devansh-webkul 
 
 Thanks for the update, The support team is helping me in https://bagisto.uvdesk.com/ so we can close the issue here 
 
 Thanks
