### ISSUE TITLE
All products are getting deleted when associated category is deleted

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#4730]
## Preconditions
Framework version - 1.3.1 (master)
PR: https://github.com/bagisto/bagisto/pull/4153

## Bug
Products are getting deleted when the associated category is deleted.

## Steps
- Add product to a category
- Then delete the category.

**Comment by ghermans** [comment]
I could see the benefits from the current approach, in case you want to delete all products in a category it is useful to simply delete the category and let Bagisto remove all products within this category.  

Maybe it should be optimized to give the admin the option to only remove the category, or category & all products assigned to it.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

But this is too risky. We need to implement another approach but no this because suppose if I am having 100 products and I want to delete the category then linking should break rather than deleting 100 products.

Bulk deleting should be a different feature that we can implement.

**Comment by vaishaliwebkul** [comment]
fixed
