### ISSUE TITLE
Affiliate/External Product Type

### ISSUE THREAD

**Issue by RikkiMasters** [bagisto/bagisto#4736]
It would be great if we had the ability to create affiliate products similar to the functionality in WooCommerce.

Instead of an add-to-cart button, it would redirect the customer to the supplier using the affiliate link. This would be logged like a sale for reporting.

WooCommerce screenshot:
![image](https://user-images.githubusercontent.com/11843864/111053766-88180580-845e-11eb-8d72-2cb795bcba21.png)

**Comment by jitendra-webkul** [comment]
This will be implemented as a separate package
