### ISSUE TITLE
Add product categories availability to attribute's option form

### ISSUE THREAD

**Issue by tlchrkv** [bagisto/bagisto#4741]
I have many product categories. But brands for laptops and basketball balls are different. Choose from very long list is not comfortable, and it is a problem for find needed brand. Create many attributes like: "Basketball balls brand", "Laptops brand", I think it is not real decision.
Need to add select with product categories to attribute option create form (you can see option create form on the attachment; in menu: Catalog -> Attributes -> edit/add -> see "Options" title).
![Screenshot from 2021-03-15 17-15-20](https://user-images.githubusercontent.com/30752949/111168460-21f0c700-85b3-11eb-8bfb-b349a16536ec.png)

**Comment by jitendra-webkul** [comment]
Need more information
