### ISSUE TITLE
image not appear in the sliders

### ISSUE THREAD

**Issue by ibrahim99jamal** [bagisto/bagisto#4746]
I faced this problem when I added image in the slider the image not appear in the frontend but I ca see image in the storage file 
How could I fixe that ?
Thank you

**Comment by devansh-webkul** [comment]
Hi @ibrahim99jamal,

Can you share some more details like Bagisto Version and also please fill the issue template.

I am not able to reproduce that in my instance,
Image Link: https://prnt.sc/10ppg77

Please check your storage linking also.

**Comment by vaishaliwebkul** [comment]
@ibrahim99jamal 
Hope this link will help you https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions/1

**Comment by ibrahim99jamal** [comment]
Hi @vaishaliwebkul 
Think you so much, I solved this issue by run these commends:

php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan clear-compiled
php artisan config:cache
composer dump-autoload
php artisan vendor:publish
php artisan storage:link
