### ISSUE TITLE
 Class 'Company' not found

### ISSUE THREAD

**Issue by KalimeroMK** [bagisto/bagisto#4747]
# Bug report

### Title
**Installing SASS package in new bagisto project.**

### Issue Description
**In several class in SAASCustomizer package  use Company class is use,  but the class is not existing and is showing an error all the logic in bagisto is under namespace Webkul in package folder so why use Company is called 4 classes are avelable 

```
use Webkul\SAASCustomizer\Contracts\Company;
use Webkul\SAASCustomizer\Company;
use Webkul\SAASCustomizer\Facades\Company;
use Webkul\SAASCustomizer\Models\Company;
```

.**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Laravel 8 and 7 (tested on both version )

### Steps to reproduce
use tutorial in bagisto doc and in the end just run composer dump
1. https://webkul.com/blog/laravel-ecommerce-multi-tenant-saas-module/
2. composer dump-autoload
### Expected result
**Tell us what should happen.**
```
Zorans-MacBook-Pro:bookmark-ecommerce zoranbogoevski$ composer dump-autoload
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Helper.php line 110:
                             
  Class 'Company' not found  
                             

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
Zorans-MacBook-Pro:bookmark-ecommerce zoranbogoevski$ Company
```

**Comment by devansh-webkul** [comment]
Hi @KalimeroMK,

This is a paid module please raise a support ticket here,
https://bagisto.uvdesk.com/en/member/login
