### ISSUE TITLE
address is not saved on checkout

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4748]
# Bug report

### Title
saved address on checkout getting removed when removing product from the cart

### Issue Description
saved address on checkout getting removed when removing product from the cart

### Preconditions

    1. framework Version- 1.3.1 Version (master)

### Steps to reproduce

    1. step1- add product to cart 
    2. step2- add new billing address and save
    3. step3- now remove item from cart
    4. step4- go to customer address

### Expected result

the address should be added in address table once saved

### Actual result

not getting any address
https://www.loom.com/share/445b90727c3645ad9a2e9c304a061c9f

**Comment by AkashWeybee** [comment]
Save addresses to cart API is not working,

Says,

ErrorException: Array to string conversion

**Comment by rahulshukla-webkul** [comment]
Hi AkashWeybee

Can you attach screenshot with your data while calling API.

**Comment by AkashWeybee** [comment]
> Hi AkashWeybee
> 
> Can you attach screenshot with your data while calling API.

Apologies, the Issue is from our side.

It's working as expected.
