### ISSUE TITLE
side bar menu icon should be removed from admin

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4751]
# Bug report

### Title
side bar menu icon should be removed from admin

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- go to admin panel

### Expected result
the newly icon added in admin panel should be removed as currently it has no use

### Actual result

https://prnt.sc/10sjrsy

**Comment by rahulshukla-webkul** [comment]
HI @vaishaliwebkul 

I think it should be more often like this - https://prnt.sc/10sjqkl

**Comment by vaishaliwebkul** [comment]
@rahulshukla-webkul 
Yes, it should be by default open for all menus but right now there is no need to have this as "right-icon" are already present along with each sub-menu https://prnt.sc/10sk8kq
you may also check this https://www.loom.com/share/51ee7a69847d4f03a84c6dac8ff519d0

**Comment by ghermans** [comment]
@vaishaliwebkul the right icon in the sub menu does not have the same functionality, it just mentions which page is active further it has no value, the reason why you think that this does the same is because it reloads the page, in that case the menu is gone hidden.

### Suggestions

- [ ] Hide the icon from the dashboard or when no sub menu exists.
- [ ] Display the sub menu by default

**Comment by devansh-webkul** [comment]
Hi @ghermans, @vaishaliwebkul, and @rahulshukla-webkul 

I can enhance this furthermore. I personally feel this should not be removed.

As mentioned by @rahulshukla-webkul,
https://prnt.sc/10sjqkl (This is far better.)

**Comment by ghermans** [comment]
Goodmorning @devansh-webkul as you can see on the dashboard it has no value here, but it is tempting to click on the icon 😄
![valueKnipsel](https://user-images.githubusercontent.com/1594411/112091485-c798cd00-8b95-11eb-9120-dd5c6d8094e1.PNG)

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I have checked your checklist for the empty list we can hide.

I was just talking about the second one the icon flow.

**Comment by devansh-webkul** [comment]
I will start working on this, just taking the confirmation for default behaviour and the icon placement.

**Comment by devansh-webkul** [comment]
Working on these parameters,

- [ ] https://prnt.sc/10sjqkl
- [ ] Display the submenu by default
- [ ] Hide the icon from the dashboard or when no sub-menu exists.

**Comment by devansh-webkul** [comment]
Hi @ghermans, @rahulshukla-webkul, and @vaishaliwebkul,

Done changes with all your requirements. Let me know if any further improvement is needed.
