### ISSUE TITLE
BUG When adding an item twice in the cart from the API

### ISSUE THREAD

**Issue by Xoshbin** [bagisto/bagisto#4758]
When adding an item twice in the cart in separate times instead of adding by quantity. the cart returns a string in one of the objects in the json the first time, and the second time the same object is returning integer.

### Steps to reproduce

1. add an item with quantity of 1 to the cart.
2. do a request to checkout/cart, 
you get the json below; the quantity is string:
```json
    "additional": {
         "token": "true",
          "product_id": "2727",
          "quantity": "1",
          "is_configurable": "false"
     }
```

3. add the same item again to the cart;
4. now when you do another request to the checkout/cart
you get an integer for quantity:
```json
    "additional": {
           "token": "true",
          "product_id": "2727",
         "quantity": 2,
         "is_configurable": "false"
    }
```

**Comment by devansh-webkul** [comment]
Hi @Xoshbin,

I am checking this will update you soon.
