### ISSUE TITLE
Checkout Form Combine Customer Info, Shipping Method and Payment Method on 1st step and summary on 2nd step

### ISSUE THREAD

**Issue by priyamns** [bagisto/bagisto#4760]
I am trying to combine Customer Info, Shipping Method and Payment Method, On single page that is on the 1st step but when I am trying to do so, Blank Page Appears when I try to merge all the views, can anyone please help me with this.

**Comment by devansh-webkul** [comment]
Hi @priyamns,

This repository is for reporting the bug. Please raise the same query in the forum,
https://forums.bagisto.com/

Also, please share the steps of implementation so that we can investigate further.
