### ISSUE TITLE
sub menu is not displayed on admin pages

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4761]
# Bug report

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master branch.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Open the admin panel
    2. Click on Sales
    

### Expected result
The sub menu should be displayed

### Actual result
![missing](https://user-images.githubusercontent.com/1594411/112400442-ac9a9a00-8d08-11eb-91cb-f3d25dc592c6.PNG)

**Comment by devansh-webkul** [comment]
@ghermans,

Looking into this. Will update you soon.

**Comment by devansh-webkul** [comment]
@ghermans,

I just checked this in the latest master. not able to reproduce that.

Screenshot: https://prnt.sc/10usx8t

Did you publish your package?

**Comment by ghermans** [comment]
@devansh-webkul i will do a clean install to verify this again.

**Comment by ghermans** [comment]
Update: not able to reproduce this on a clean install.
