### ISSUE TITLE
Just requesting to handle category URL generation from the code

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#4762]
## Enhancement
I am just raising this to know the point of view of this because the current URL generation is happening from the triggers and function. I know that handling the URLs from SQL is robust but it is creating problems for most of the users.

## Problems
- When I try to import and export the data then some times trigger functions not came which results in an error.
- Explicitly defining the definers and host for the URL generations.
- Not having good support in other platforms like Postgres, etc.

## Related Issues
- https://github.com/bagisto/bagisto/issues/4368
- https://github.com/bagisto/bagisto/issues/3318

**Comment by xalexslx** [comment]
May I suggest to be able to use category as prefix instead of each product having their direct slug as URL? I know there is SEO issues and that, but turning it configurable should help with some specific user cases.

**Comment by devansh-webkul** [comment]
Yes if we add a prefix, this will create SEO issues. Well if you want you can customize your project. The point of this discussion is about whether should we handle category names via database trigger or project itself.

Because by database, user needs a root previlidge atleast one time at the time of installation.

**Comment by devansh-webkul** [comment]
Already added in the discussion, so closing this.
