### ISSUE TITLE
issue after migration 

### ISSUE THREAD

**Issue by Shiam-Chowdhury** [bagisto/bagisto#4769]
# Bug report

### Title
**after install with composer or zip download, problem in migration
![19](https://user-images.githubusercontent.com/11739738/112752000-9df70000-8ff2-11eb-8acd-79ddc369cbb0.JPG)
**
**Please be calm, short and emphasize on points.**

### Issue Description
**In Connection.php line 671:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
   corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp nul
  l, `updated_at` timestamp null) default cha' at line 1 (SQL: create table `roles` (`id` int unsigned not null auto_
  increment primary key, `name` varchar(191) not null, `description` varchar(191) null, `permission_type` varchar(191
  ) not null, `permissions` json null, `created_at` timestamp null, `updated_at` timestamp null) default character se
  t utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB ROW_FORMAT=DYNAMIC)

In PDOConnection.php line 63:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
   corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp nul
  l, `updated_at` timestamp null) default cha' at line 1

In PDOConnection.php line 61:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
   corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp nul
  l, `updated_at` timestamp null) default cha' at line 1**

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.
    2. Commit id.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1
    2. step2

### Expected result
**Tell us what should happen.**

*   [Screenshots, logs or description]

### Actual result

>    **Tell us what happens instead.**

* [points....]

**Comment by devansh-webkul** [comment]
Hi @Shiam-Chowdhury, 

May i know your maria db version.

**Comment by Shiam-Chowdhury** [comment]
> Hi @Shiam-Chowdhury,
> 
> May i know your maria db version.

10.1.38-MariaDB - mariadb.org binary distribution

**Comment by devansh-webkul** [comment]
Hi @Shiam-Chowdhury 

Please use 10.2.7 or higher.

![Screenshot_20210328-225241_Chrome.jpg](https://user-images.githubusercontent.com/68321766/112824657-72cee800-90a8-11eb-80c7-0fbecce657d8.jpg)

**Comment by devansh-webkul** [comment]
Hi @Shiam-Chowdhury,

I am closing this as this is not an issue. Please check the mentioned DB versions.
