### ISSUE TITLE
Error when you create or update a new catalog categories under root

### ISSUE THREAD

**Issue by inirav** [bagisto/bagisto#4778]
Bagisto Version: 1.3.1

when i'm adding a new category with position 2 and a parent category.
i got this issue
`SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update `categories` set `_lft` = case when `_lft` between 15 and 16 then `_lft`-1 when `_lft` between 14 and 16 then `_lft`+2 else `_lft` end, `_rgt` = case when `_rgt` between 15 and 16 then `_rgt`-1 when `_rgt` between 14 and 16 then `_rgt`+2 else `_rgt` end where (`_lft` between 14 and 16 or `_rgt` between 14 and 16))`

The similar issue comes on demo site as well.

Any Help with that, i will be appreciated
Thanks in advance.

**Comment by rahulshukla-webkul** [comment]
Hi @inirav 

Please follow this one - https://github.com/bagisto/bagisto/issues/2562

**Comment by inirav** [comment]
I've tried and still the error exists.

**Comment by rahulshukla-webkul** [comment]
Hi @inirav 

Create a new database using this one -   CREATE DATABASE bagisto CHARACTER SET utf8 COLLATE utf8_unicode_ci;

**Comment by inirav** [comment]
Thanks a lot this worked !!!
