### ISSUE TITLE
image search is not working when out of stock is disabled

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4779]
# Bug report

### Title
image search is not working when out of stock is disabled

### Issue Description
image search is not working when out of stock is disabled

### Preconditions

    1. framework Version- master or 1.3.1

### Steps to reproduce

    1. step1- configuration-> catalog-> disable out of stock item option
    2. step2- go to storefront and search product by uploading image

### Expected result

Image search feature should work

### Actual result

![Screenshot_346](https://user-images.githubusercontent.com/43210406/113847029-af8b9500-97b4-11eb-9284-82456ac9c12c.png)

**Comment by devansh-webkul** [comment]
Need to reopen this,
Ref: https://github.com/bagisto/bagisto/issues/4977
