### ISSUE TITLE
Getting error when we click remove button 2 times to remove product from cart

### ISSUE THREAD

**Issue by Anmol-Chauhan** [bagisto/bagisto#4782]
# Bug report

### Title
Getting error when we click remove button 2 times to remove product from cart

### Issue Description
Getting error when we click remove button 2 times to remove product from cart

### Preconditions

    1. framework Version- master or 1.3.1.

### Steps to reproduce

    1. add product to cart
    2. Open View Shopping Cart --> https://prnt.sc/116hftz
    3. Now click remove button 2 times continuously.

### Expected result

*  Product should remove from the cart without occurring any error

### Actual result
![Screenshot from 2021-04-07 17-58-35](https://user-images.githubusercontent.com/79086253/113867070-b376e180-97cb-11eb-9d6e-ff42ce426717.png)

*

**Comment by devansh-webkul** [comment]
Hi @Anmol-Chauhan,

Not able to reproduce that. On a single click, it's getting a prompt and I am not able to click twice.
