### ISSUE TITLE
Unable to upload profile picture

### ISSUE THREAD

**Issue by AkashWeybee** [bagisto/bagisto#4787]
# Bug report

### Preconditions

    1. Latest

### Steps to reproduce

    1. Go to user profile
    2. Click on edit profile

### Expected result
**User can upload their photo**

![image](https://user-images.githubusercontent.com/53002296/114131321-12e60600-9920-11eb-9384-961f40d010fb.png)

**Comment by rahulshukla-webkul** [comment]
Hi @AkashWeybee 

Right now, this functionality is not in bagisto. This is a static text written there.

**Comment by AkashWeybee** [comment]
Will you accept pull request for this feature?
Need to add a column in the customer table.

**Comment by rahulshukla-webkul** [comment]
Hi @AkashWeybee 

You can create PR for the same but make sure to create new migration for the new column.

**Comment by apoorvpal01** [comment]
Is this still open? I can work on this if it is.

**Comment by devansh-webkul** [comment]
Sure! It's open. Go ahead.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
I am reopening this issue because this feature is not implemented in the default theme.Please find the screenshot [Here](https://prnt.sc/gGe6bdjs_Gjm)

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
As we discuss this feature is **only for the velocity theme**, so I am closing this issue
