### ISSUE TITLE
Mail function down

### ISSUE THREAD

**Issue by ModernAmusements** [bagisto/bagisto#4798]
# Bug report

### Mail function not working throughout the whole webshop it self.
**No Newsletter verfication**
**No Order Confirmation**

### Issue Description
**Im working on the lastest version of bagisto v 1.3.1 **

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. edit .env
      DB_HOST=127.0.0.1
      DB_PORT=3306
      DB_DATABASE=bagisto
      DB_USERNAME=root
      DB_PASSWORD=root
    2. composer create-project bagisto/bagisto
    3. APP_KEY=base64:xAT1X6hzlUUZWV10vCP+Fxva3EKeqI1LiHPnwQdgMTk=
    3. php artisan bagisto:install
    4. php artisan serve

### Expected result
**Terminal says everythings success log in please**
Error Log 

[2021-04-15 22:17:14] local.ERROR: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [] does not comply with RFC 2822, 3.6.2. at /Users/shady/Desktop/bagisto-1.3.1/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)

![Bildschirmfoto 2021-04-15 um 19 03 11](https://user-images.githubusercontent.com/63150622/114909278-4263a980-9e1d-11eb-8102-9934837f38ae.png)

im very confused since everything worked fine for me since now.

thank u :)

**Comment by devansh-webkul** [comment]
Hi, @ModernAmusements,

This is not an issue. Mail is working properly just check your email. Whether the current email is valid or not.

Don't use `example.com`.

**Comment by ModernAmusements** [comment]
Thanks

Glenn Hermans ***@***.***> schrieb am Fr. 16. Apr. 2021 um
05:58:
