### ISSUE TITLE
filter is not working in customer grid

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4800]
# Bug report

### Title
Status filter is not working in customer grid 

### Preconditions

    1. framework Version- 1.3.1 or master

### Steps to reproduce

    1. step1- go to admin-> customer list
    2. step2- select true/active filter

### Expected result
only active result should visible

### Actual result
![Screenshot_349](https://user-images.githubusercontent.com/43210406/114979997-679df980-9ea9-11eb-8615-b0b8db6bc388.png)

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

On checking came to know that this is the core Datagrid issue as this impacted all Datagrid when using active.

I am fixing this with this PR i.e. https://github.com/bagisto/bagisto/pull/4796.
