### ISSUE TITLE
Compare product in velocity theme showing duplicated attribute after adding a new attribute family

### ISSUE THREAD

**Issue by mikaeldiok** [bagisto/bagisto#4813]
# Bug report

### Title
Compare product in velocity theme showing duplicated attribute after adding a new attribute family

### Issue Description
Product attribute is duplicated when comparing after adding new attribute family. is this a bug, or not?

### Preconditions

    1. master v 1.3.1

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Create new attribute family (with or without new attribute)
    2. Compare two product regardless their attribute family
   

*   [Screenshots, logs or description]
![admin_compare_bug](https://user-images.githubusercontent.com/60207273/115647093-6eb38480-a34d-11eb-8271-b67d7df3d962.png)
![bug-compare](https://user-images.githubusercontent.com/60207273/115647119-770bbf80-a34d-11eb-842b-4d926a7a4193.png)

**Comment by devansh-webkul** [comment]
Yeah! I also noticed this. Thanks for reporting this.

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

This one is the same which you mentioned earlier.

**Comment by devansh-webkul** [comment]
Hi @mikaeldiok,

The bus has been fixed in master. Can you verify this?

**Comment by mikaeldiok** [comment]
sorry for late replies. it is fine. thank you.
