### ISSUE TITLE
Date component disable, enable options not working

### ISSUE THREAD

**Issue by theliscsevity** [bagisto/bagisto#4816]
I want to use the date component inside my custom package.The problem is that I have dates that I want to be disabled, but the data-disable is give me an error.I know the data-disable value must be an array.
The error is :TypeError: t.slice().map is not a function.
The Bagisto version is 1.2.0.

` <date @onChange="dateSelected($event)">`

`<input type="text" data-min-date="today" data-disable="['2021-05-12', '2021-05-13']" v-validate="'required'" name="amepheas[tour][date]" class="form-style" data-vv-as="&quot;{{ __('amepheasproduct::app.shop.products.date') }}&quot;"/>`

`</date>`

**Comment by devansh-webkul** [comment]
Hi @theliscsevity,

I checked the component, Flatpicker has been used but we haven't given the disable option in the component. In version 1.2.0, only the `name` and `value` pair is there.

In the latest version, only `maxDate` and `minDate` are present.

I am marking this as enhancement, as disable specific date can also be helpful for developer when building modules.
