### ISSUE TITLE
Aramex shipping option is not displayed 

### ISSUE THREAD

**Issue by aboeldhab74** [bagisto/bagisto#4820]
I have purchased a "Laravel eCommerce Marketplace Aramex Shipping" And After the successful installation of the module And adjust the settings from the dashboard. The shipping method is not displayed and the Aramex shipping option is not displayed in frontend
![Laravel-Aramex-Shipping-Method](https://user-images.githubusercontent.com/70381640/115874620-95081b80-a444-11eb-940f-5e26fb3ec64d.png)

**Comment by vaishaliwebkul** [comment]
@aboeldhab74 
This is the paid module so you may get support from https://bagisto.uvdesk.com/en/customer/create-ticket/ or mail to support@bagisto.com
