### ISSUE TITLE
Shop by category dissapears on hover

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4827]
# Bug report

### Issue Description
When you hover on the section the categories are being shown, but a lot of times when i want to go to a category the menu goes away
When i hover of category section a couple times the category menu stays and i can click on the categories

https://youtu.be/57nzPjeGUu4

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master branch

**Comment by EgyptianM** [comment]
Still happens in latest release 1.3.2
