### ISSUE TITLE
How can I disable modal.scss?

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#4830]
Hi, I want to use a custom css for my modals, but modal.scss is overwriting the css. Any helps are appreciate.

**Comment by ghermans** [comment]
Hi @lYesterdaYl [Issues](https://github.com/bagisto/bagisto/issues) on this repository are only being used for reporting bugs or feature suggestions.  
In this case i would suggest to post these kind of questions on our forum https://forums.bagisto.com/ or create a support ticket at https://bagisto.uvdesk.com/en/customer/create-ticket/
