### ISSUE TITLE
Searching getting empty result set

### ISSUE THREAD

**Issue by msankar1991** [bagisto/bagisto#484]
After fresh installation getting error while searching on it.

![whoops there was an error](https://user-images.githubusercontent.com/8719413/51733746-59851800-20a8-11e9-89e5-09200e8f9627.png)

**Comment by prashant-webkul** [comment]
@msankar1991 I have checked this issue was persisting for last two releases but in [0.1.4-Beta](https://github.com/bagisto/bagisto/tree/v0.1.4-BETA1 ) this had been fixed and you can download it ryt now.
