### ISSUE TITLE
ErrorException Attempt to read property "default_locale" on null

### ISSUE THREAD

**Issue by Riu-Project** [bagisto/bagisto#4842]
Someone help me :

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
C:\xampp\htdocs\bagisto\packages\Webkul\Shop\src\Http\Middleware\Locale.php:44

 /**
    * Handle an incoming request.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \Closure  $next
    * @return mixed
    */

    public function handle($request, Closure $next)
    {
        $locale = request()->get('locale');
        if ($locale) {
            if ($this->locale->findOneByField('code', $locale)) {
                app()->setLocale($locale);
                session()->put('locale', $locale);
            }
        } else {
            if ($locale = session()->get('locale')) {
                app()->setLocale($locale);
            } else {
                app()->setLocale(core()->getDefaultChannel()->default_locale->code);
            }
        }
        unset($request['locale']);
        return $next($request);
    }
}

**Comment by ghermans** [comment]
Hi, @Riu-Project  it seems that your installation didn't completed successful
Try to run the following commands
````
php artisan migrate
php artisan db:seed
php artisan optimize
```

**Comment by Riu-Project** [comment]
Hi @ghermans , Thanks Sir my issue solved, by the way 1 more question, how to upload to live server? as ussual in Laravel just replace url adress in config>>app.php
  
 'url' => env('APP_URL', 'http://mydomain.com'),

How about Bagisto? could u give me a link or video? all tutorial in Bagisto official site nobody tell us how to upload bagisto to online hosting. I need help, Thanks!

**Comment by businsolution** [comment]
same error
![image](https://user-images.githubusercontent.com/80008111/173192763-3c6bef5b-0296-456b-8f52-222456bb3634.png)

**Comment by diusazzad** [comment]
php artisan optimize:clear
