### ISSUE TITLE
resizeCanvas() accepts only integer values as argument 1.

### ISSUE THREAD

**Issue by Arsivpro** [bagisto/bagisto#4843]
resizeCanvas() accepts only integer values as argument 1.

Hello small product pictures are not coming. I copied the image path to the address bar and went, and this error message comes to me.
(intervention)

![image](https://user-images.githubusercontent.com/65822345/116917177-fa36ea80-ac56-11eb-8500-17ca935c7565.png)

**Comment by devansh-webkul** [comment]
Hi @Arsivpro,

This is a dependency issue not specific to the types, just make sure you have all dependencies on which the intervention package rely on for e.g lib-png, lib-jpg, libfreetype6-dev, libicu-dev, libjpeg62-turbo-dev, libpng-dev, libzip-dev, etc.  I am just sharing sample however these depedencies varies acccording to OS.

**Comment by harmonizerblinks** [comment]
> Hi @Arsivpro,
> 
> This is a dependency issue not specific to the types, just make sure you have all dependencies on which the intervention package rely on for e.g lib-png, lib-jpg, libfreetype6-dev, libicu-dev, libjpeg62-turbo-dev, libpng-dev, libzip-dev, etc. I am just sharing sample however these depedencies varies acccording to OS.

Pls can u share links to install these on a cloud server?

**Comment by devansh-webkul** [comment]
I already mentioned these dependencies vary according to OS.

Please use the forum for discussions, don't reply on the closed issues,
https://forums.bagisto.com/
