### ISSUE TITLE
filtering customer address page is always redirect to customer profile tab

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4854]
# Bug report

### Title
filtering customer address page is always redirected to customer profile tab

### Issue Description
Admin goes to customer list and filter addresses then he redirects on customer profile instead of staying at the same page.

### Preconditions

    1. framework Version- master
  
### Steps to reproduce

    1. step1-Admin-> customer -> customer addresses
    2. step2- filter address by entering any key on the search filter

### Expected result

admin should stay on customer address tab when search anything.

### Actual result

https://www.loom.com/share/31ee53189c524c9bbaa1e5b0d5bea8e2

**Comment by devansh-webkul** [comment]
Hi @ghermans,

Are you working on this?

**Comment by ghermans** [comment]
Hi @devansh-webkul currently i'm not working on this one
