### ISSUE TITLE
Quantity to shipped need to be auto filled from qty ordered 

### ISSUE THREAD

**Issue by mezzat11** [bagisto/bagisto#4855]
Quantity to shipped need to be by default qty to order to avoid bad admin UX 
[image](https://user-images.githubusercontent.com/34794248/117550495-fcc38680-b040-11eb-8b19-77f11b6f94db.png)

**Comment by ghermans** [comment]
This actually works as mentioned above when you first create the invoice for the order

**Comment by mezzat11** [comment]
Must an invoice be created before shipment? 
I create an order .. create shipment ..

**Comment by ghermans** [comment]
You can create a shipment without creating a invoice first, however in that case you will need to manually enter the products that you will ship.

**Comment by ghermans** [comment]
As you probably noticed i have marked this as a feature request / optimization so it is possible that we will fix this in the upcoming releases, also Bagisto is open source so nobody of us is stopping you to improve it yourself and create a pull request.

**Comment by mezzat11** [comment]
Thank you
