### ISSUE TITLE
Error 500 when create refund for order that dons't have invoice

### ISSUE THREAD

**Issue by mezzat11** [bagisto/bagisto#4857]
# Bug report

### Title
**Just a quick sentence to brief your trouble with Bagisto or something associated with it.**
**Please be calm, short and emphasize on points.**

### Issue Description
**Error 500 when create refund for order that doesn't have invoice " 

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version. : 1.3.1 ( demo.bagisto.com ) 

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. open catalog, orders, refunds , create a refund 
    2. Get Error 500 page

### Expected result
Expect: Getting a message: The order should have payment or invoice first before you can refund. 
![image](https://user-images.githubusercontent.com/34794248/117593607-958afc80-b13c-11eb-939a-dbafb3a7bf09.png)

### Actual result

>    **ERROR 500 **

**Comment by ghermans** [comment]
Well, it is kinda normal that you can not refund something when you didn't get paid yet

**Comment by mezzat11** [comment]
but I think admin should not get this exception

**Comment by ghermans** [comment]
i'm not able to reproduce this in the master branch , so this is most probably an issue on the demo site

**Comment by devansh-webkul** [comment]
Hi, @ghermans and @mezzat11,

First of all, I would like to mention that refund will only visible when an invoice is generated. This means someone hit the refund URL which is a natural behaviour that will show 500 pages.

But i think, this should be 404.

**Comment by mezzat11** [comment]
Issue on demo website
