### ISSUE TITLE
Bagisto roadmap is not updated

### ISSUE THREAD

**Issue by mezzat11** [bagisto/bagisto#4863]
# Bug report

### Title
Bagisto roadmap is not updated

### Issue Description
**Roadmap is not updated .. you need to update the roadmap to know the coming updates / features 

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Master

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1.Open Bagisto Roadmap : https://bagisto.com/en/roadmap/
    2. Not updated

### Expected result
Updated Roadmap to help the community to know the coming updates, features.

### Actual result

>   Not updated Roadmap

**Comment by ghermans** [comment]
@mezzat11 i forwarded this to the right department, they will update this asap.
Also please use the forum (https://forums.bagisto.com) for these kind of reports

**Comment by mezzat11** [comment]
can you add support multi-language(LOCAL) as header parameter  in API in your roadmap
also handling online payment with API as webview solution
THANKS

**Comment by mezzat11** [comment]
Api need work to be ready to use please add it in your roadmap 
Ex : https://forums.bagisto.com/topic/2421/product-api-behaving-strangely-cannot-fetch-data-for-a-single-product
Also currency switcher : https://forums.bagisto.com/topic/2351/how-to-use-local-and-currency-switcher-api
