### ISSUE TITLE
Buy 2 Get 1 Free Irrespective of Brand

### ISSUE THREAD

**Issue by fahadkhan1740** [bagisto/bagisto#4864]
# Bug report

### Title
Buy 2 Get 1 Free Irrespective of any Brand. It should also be based on Product also.

### Issue Description

I have same brand offer buy 2 get 1 free for same brand only.
If products (i.e.A and B) are under same brand then:
Only Getting 2 A will get one A free. Same product for same product only!
But getting A+B will not get free A or B. While they have same brand!
And 2A will not get free B.
This is not reflecting brand offer!
It get same product 2+1 offer only

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. v1.2.0

### Steps to reproduce

I have same brand offer buy 2 get 1 free for same brand only.
If products (i.e.A and B) are under same brand then:
Only Getting 2 A will get one A free. Same product for same product only!
But getting A+B will not get free A or B. While they have same brand!
And 2A will not get free B.
This is not reflecting brand offer!
It get same product 2+1 offer only

### Expected result
**Tell us what should happen.**

Ideally there should be a provision to have Buy 2 Get 1 on any product.

### Actual result

As of now, it is only for one brand only.

**Comment by bhanu-webkul** [comment]
@fahadkhan1740  As mentioned by you currently this type of cart rule works for same product only, But keeping in mind your suggestion we can implement this enhancement in future.

**Comment by fahadkhan1740** [comment]
Any update on this?

**Comment by devansh-webkul** [comment]
I have started working on this.

**Comment by devansh-webkul** [comment]
Due to some discussion with the team, this is on hold.

**Comment by devansh-webkul** [comment]
This can't be done as this will create problems in the existing flow. This should be handled by creating a new module or something. As this is not a physical shop.
