### ISSUE TITLE
PayPal Checkout / Alternative Payment Methods

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4866]
PayPal Smart Button is work in Alternative Payment Methods Mercado Pago | Brazil ?
https://developer.paypal.com/docs/checkout/integration-features/alternative-payment-methods/
Thanks!

**Comment by ghermans** [comment]
This repository is only for reporting bugs or problems. In this case you can better ask your question on our forum https://forums.bagisto.com
