### ISSUE TITLE
category create Error

### ISSUE THREAD

**Issue by maddrid** [bagisto/bagisto#4868]
Error on creating category

There is no info  about  creating a database  with specific collation

### Preconditions
create database  with utf8mb4_general_ci collation

![Screenshot_2021-05-15 Whoops There was an error ](https://user-images.githubusercontent.com/5124319/118336195-7829aa00-b511-11eb-8973-d3ee976b3351.png)

* [points....]

**Comment by vaishaliwebkul** [comment]
@maddrid 
Check the solution here 
https://github.com/bagisto/bagisto/issues/2901

**Comment by devansh-webkul** [comment]
I am closing this as this issue came many times and resolution also provided.
