### ISSUE TITLE
Features documentations 

### ISSUE THREAD

**Issue by karim20160300** [bagisto/bagisto#4870]
is there is any features documentations because i am not familiar with ecommerce websites ?

**Comment by vaishaliwebkul** [comment]
Hi @karim20160300 
Bagisto has so many blogs and article published which explain each feature.
You may explore the guide here 
https://bagisto.com/en/blog/ 
https://devdocs.bagisto.com/

If you have any query, feel free to post your query with forum community
https://forums.bagisto.com/
