### ISSUE TITLE
configurable product in product details page frontend

### ISSUE THREAD

**Issue by aboeldhab74** [bagisto/bagisto#4880]
# Bug report

### Title
in product details page 
if product is configurable product
when select  color and size 
The price disappears and image not changed 

### Preconditions

    1. framework Version. 
    1.0 V.

![prod configurable](https://user-images.githubusercontent.com/70381640/118706441-a7922c80-b819-11eb-9f3f-9b5a82560529.PNG)

**Comment by vaishaliwebkul** [comment]
Hi @aboeldhab74 
you are using older version, I just recommend you to update your version as this is already fixed [here](https://github.com/bagisto/bagisto/issues/4558)  on latest version.
