### ISSUE TITLE
Hide shipping for virtual products

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4885]
# Bug report

### Issue Description
When creating a virtual product the shipping category is getting displayed with a field named length, 

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. master branch.

### Expected result
The category shipping should be excluded for virtual products.

### Actual result
- The category is being displayed

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I am not able to reproduce this in master and I also checked the code, attributes are already skipped,
https://github.com/bagisto/bagisto/blob/cf2881d0c3181bca584be215571ef9b8a5e40324/packages/Webkul/Product/src/Type/Virtual.php#L12

**Comment by devansh-webkul** [comment]
Ok got it just need to add the length

**Comment by devansh-webkul** [comment]
The reason for not reproducing, I am having the attribute `depth` rather than `length`. :smile:
