### ISSUE TITLE
Make Sample optional for downloadable products

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4886]
# Bug report

### Issue Description
When creating a downloadable product, it is currently always required to provide sample 

### Preconditions

    1. master branch.

### Expected result
- Add a option **None**
![noneKnipsel](https://user-images.githubusercontent.com/1594411/118840135-66585600-b8c7-11eb-892d-c3a8436d5496.PNG)

### Actual result
![SelectionKnipsel](https://user-images.githubusercontent.com/1594411/118838647-25ac0d00-b8c6-11eb-9d22-b0e816a728a8.PNG)

**Comment by rahulcs0082** [comment]
Hi @ghermans 

The sample field is not a required fied.
