### ISSUE TITLE
cURL error 6: Could not resolve host: .algolia.net

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4888]
# Bug report

### Issue Description
When trying to save a product or an order the following error occurs
```
cURL error 6: Could not resolve host: .algolia.net (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://.algolia.net/1/indexes/products_index/batch
```

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1.  master branch.

**Comment by ghermans** [comment]
Issue seems to be resolved

**Comment by ashourms** [comment]
> Issue seems to be resolved

@ghermans I am still getting this error when saving the product even after setting SCOUT_DRIVER to null in my .env file. I am exploring and using version 1.3.1.

**Comment by devansh-webkul** [comment]
Hi @ashourms,

Just make sure you run `php artisan optmize` also because changes are always cached.

**Comment by ashourms** [comment]
> Hi @ashourms,
> 
> Just make sure you run `php artisan optmize` also because changes are always cached.

Hi @devansh-webkul 
Thanks for the response. I am still working in the development environment and nothing is cached yet.

**Comment by devansh-webkul** [comment]
In Bagisto, by default config are cached whether its production or development. That's why I am saying.

**Comment by ashourms** [comment]
Done as suggested but I am still getting the same error the moment you try to save the product

**Comment by devansh-webkul** [comment]
I just reverified again, on putting `algolia` i am getting the error but on setting `null` not reproducible. So it's not a bug please check your instance,
https://github.com/bagisto/bagisto/blob/80651ed483712bc6f4b787f78e16a2e3636a9572/config/scout.php#L18

**Comment by ashourms** [comment]
The value is set to null in the config file you mentioned above and removed from .env and still I am getting the same error

**Comment by Soomrojb** [comment]
I am still having same issue, tried everything mentioned above.

`GuzzleHttp\Exception\ConnectException
cURL error 6: Could not resolve host: .algolia.net (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://.algolia.net/1/indexes/products_index/batch`

**Comment by abraham-yusuf** [comment]
> Worked after updating:
> 
> ```
> bagisto/config/scout.php
> ```
> 
> ```
>     /*
>     'driver' => env('SCOUT_DRIVER', 'algolia'),
>     */
> 
>     'driver' => env('SCOUT_DRIVER', null), 
> ```
> 
> then:
> 
> ```
> php artisan config:clear
> php artisan config:cache
> php artisan optimize
> composer dump-autoload
> ```

it's working in the backend as admin, but in frontend as guest / user its the same
