### ISSUE TITLE
Fixed Amount to whole cart rule based on condition doesn't work

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4891]
# Bug report

### Title
Fixed Amount to whole cart rule based on condition doesn't work

### Issue Description
Set cart rule by adding any condition like "name" is equal to "xyz" then action is fixed amount to whole cart, in this case when adding a different item which doesn't match with the condition, still discount is applied on that.

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- set cart rule based on condition and action is equal to "Fixed Amount to Whole Cart"
    2. step2- Add two item in cart, Let's A item which is match with condition & B item which doesn't match with condition
    3. step3- Check the discount applied on cart

### Expected result
Fixed amount should be added 

### Actual result
Invalid amount added

![Screenshot_371](https://user-images.githubusercontent.com/43210406/119091990-7ab56380-ba2b-11eb-9412-0218141effb7.png)

![Screenshot_372](https://user-images.githubusercontent.com/43210406/119092008-8143db00-ba2b-11eb-9f73-1e687ad66694.png)

**Comment by mezzat11** [comment]
Hope you tests cover all cart/ catalog rules
