### ISSUE TITLE
WEBP is preferred over JPEG  by top e-commerce giant due to its superior compression at equivalent quality - When can we expect it in bagisto?

### ISSUE THREAD

**Issue by parasbhadauria** [bagisto/bagisto#4893]
Dear Team,
WebP is a modern image format that provides smaller, richer images that make the web faster.
WebP images are 26-34% smaller in size compared to PNG & JPEG.
**When can we expect it in Bagisto?**

**Comment by devansh-webkul** [comment]
Hi @parasbhadauria,

We already enable the `webp` extension. It's up to the admin.
