### ISSUE TITLE
Feature to Implement Google tag manager for each page to manage all kind of user tracking code (like AdWords, Google Analytics & Facebook pixel code).

### ISSUE THREAD

**Issue by parasbhadauria** [bagisto/bagisto#4895]
Dear Team,
User tracking code is important for each page while:
1. Running an ad campaign on the search engine (google, bing, etc) & social media (Facebook, Linkedin Twitter).
2. Tracking user metrics via Goole analytics code.

Google Tag Manager plays an important role to manage all kinds of tracking code as mentioned above.
When can we expect this feature in Bagisto?

**Comment by devansh-webkul** [comment]
Hi @parasbhadauria,

These all (i.e. google, bing, etc) rely on some small js snippets. For js, we have given a custom js code feature in the admin panel.

But still i will verify with team.

**Comment by devansh-webkul** [comment]
@parasbhadauria

As this feature can be integrated according to user need, you can use this section,

  ![Screenshot](https://user-images.githubusercontent.com/68321766/120753642-1dd8a380-c529-11eb-8bf5-dc317cc6052d.png)

If this section is not working, then feel free to raise an issue.
