### ISSUE TITLE
How to Send Emails Using Twilio Sendgrid in Bagisto

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4898]
How to Send Emails Using Twilio Sendgrid in Bagisto ?

This repository is only for reporting bugs or issues. If you need support, please use:

1. Create support ticket on https://bagisto.uvdesk.com

Thanks!

**Comment by ghermans** [comment]
This repository is only for reporting bugs or issues, you can ask your support questions on our forum https://forums.bagisto.com or  create a support ticket on https://bagisto.uvdesk.com
