### ISSUE TITLE
Sendgrid Send your email using the API, Basic Authentication is no longer accepted; you must use an API key

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#4900]
Send your email using the API
Please note that Basic Authentication is no longer accepted; you must use an API key.

https://sendgrid.com/docs/for-developers/sending-email/api-getting-started/#how-to-send-an-api-email

**Comment by devansh-webkul** [comment]
Hi @marcelowu,

We are using all emails API which is coming from Laravel by default itself, if someone wants to use it, it is their choice.
