### ISSUE TITLE
Issue in Configurable Product Addition

### ISSUE THREAD

**Issue by dev-einn** [bagisto/bagisto#4901]
When we are creating configurable product then we only entered few fields of variants like sku,name,price,qty. After saving the product we can see the variants are made automatically but when we edit any one of product like inventories we need to add for a variant , on saving its gives error on URL_key, description etc to input that field. If these fields are required then you should have made entered while creating the product.
Please find the attachment of screenshots.
![Screenshot from 2021-05-20 09-21-14](https://user-images.githubusercontent.com/72020482/119769095-77145780-bed7-11eb-8684-8b88afa62ec7.png)
![Screenshot from 2021-05-20 09-24-01](https://user-images.githubusercontent.com/72020482/119769107-7bd90b80-bed7-11eb-8895-8d9b5f02eff8.png)
![Screenshot from 2021-05-20 09-24-09](https://user-images.githubusercontent.com/72020482/119769133-8d221800-bed7-11eb-9d94-157f9b961b84.png)

Also if I migrate my data of configurable variants products with visible individually off in database table product_attribute_values , still its showing in home page as well as if we do it from admin site , it work for searching the product

**Comment by vaishaliwebkul** [comment]
@dev-einn 
We can consider the first suggestion as an enhancement and implement it soon.

About the visible individually functionality, for configurable product it's works fine on latest version please do let me know your bagisto version?

**Comment by dev-einn** [comment]
@vaishaliwebkul 
We are using v1.2.0

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul and @ghermans,

Is this in the current milestone?

**Comment by vaishaliwebkul** [comment]
@dev-einn 
Variants all required fields are now auto-filled while product generation, You may check the changes with PR https://github.com/bagisto/bagisto/commit/49f3be17e1ef01cbf776e28e7f3478e30fc2ec33

**Comment by dev-einn** [comment]
Hy, we have merged the pr but I think your file **packages/Webkul/Product/src/Repositories/ProductImageRepository.php** is not compatible to v1.2 and the second **configurable.php** we have mereged but still getting the same issue.
I have made the video you can take help from this https://www.loom.com/share/440a5fc4a0a249a3bc790021a95f04f5

Thanks

**Comment by devansh-webkul** [comment]
Hi @dev-einn,

This is not an issue, either this is a cache issue or you must be missing something.
