### ISSUE TITLE
By default variant selection is not there in the configurable product

### ISSUE THREAD

**Issue by parasbhadauria** [bagisto/bagisto#4911]
Hi,
By default variant selection is not there in the configurable product.
Suppose we have:
2 parent variation of a product as A1 & A2
3 child variation (for each parent variation) as B1, B2 & B3
We want to make a default option enabled when a user arrives on the website i.e. by default parent-child option should be visible to the user (let's say A1>B1)
**Screenshot attached**
![Screenshot](https://user-images.githubusercontent.com/75558471/120911455-3cfc4000-c6a5-11eb-98a6-2585728d8dfa.JPG)

**Comment by vaishaliwebkul** [comment]
@parasbhadauria 
By default, the configurable variant options can't be selected, You need to make it customized.

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

I think we can give an admin a privilege in the backend to select the default variant. If the default variant is not present then no selection should be made.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
Agree with you!! 

The option can be added while creating configurable product.

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul and @ghermans,

I have started working on this.
