### ISSUE TITLE
Bagisto Tensorflow issue

### ISSUE THREAD

**Issue by narayanwork92** [bagisto/bagisto#4916]
# Bug report

### Issue Description
Page loading too slow due to tensorflow cdn.
https://cdn.jsdelivr.net/npm/@tensorflow/tfjs got 500 error.

#### Bagisto version
- [1.3.1

### Steps to reproduce
It's better if we use this package local instead of using cdn.

**Comment by devansh-webkul** [comment]
Hi @narayanwork92,

We are using the pre-trained model provided by the TensorFlow i.e. `mobilenet`. If you have trained your model then you can feel free to do this at your instance.

Currently, it will rely on the CDN.

And tensorflow js is already  in the footer at very bottom so it won't impact the load.

**Comment by narayanwork92** [comment]
Thank you. For sometime CDN is down, so got this error.
