### ISSUE TITLE
Hide free shipping method when a cart rule for shipping exists

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4920]
Even though that this can be done with a cart rule it would be more user friendly if we add a option to the free shipping method to set the minimum amount for free shipping.  
so for example when the admin mentions on his website Free Shipping on order above $100 no shipping cost is calculated when the order is for example 100 or higher

Currently the shipping costs gets removed by the cart rule but the shipping method **free shipping** is always displayed during the checkout process, this can become confusing.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

- I think free shipping can also disable from the backend.
- If the user really wants to apply free shipping on some condition then the cart rule can do this. That means the user doesn't want to do free shipping so he can disable that also.
