### ISSUE TITLE
not able to add multiple coupon code if end other rule value set to false in cart rules

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4925]
# Bug report

### Issue Description
not able to add multiple coupon code if end other rule value set to false in cart rules

### Preconditions
should have two valid cart rules with coupon code like A and B 

#### Bagisto version
- [X]  master branch

### Steps to reproduce

1.  Add two valid cart rule with specific coupon code.
2.  add an item to cart
3.  apply coupon code one by one

### Expected result
Both coupon code should be applied in cart if **condition** is true and **end other rule** is set to **false**

### Actual result
![Screenshot_387](https://user-images.githubusercontent.com/43210406/121705529-57457c00-caf2-11eb-9122-c1930b523b30.png)

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul and @ghermans,

Multiple coupons feature is not available in Bagisto Core. If someone really wants that it will be available through customization.
