### ISSUE TITLE
Allow admin to set a invoice prefix and the first invoice number

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4926]
- [x] Allow the admin to set a prefix for invoices numbers
- [ ] Allow the admin to set the first invoice number for example 1000, 1001, ...

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I have started working on this.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I just want to confirm should we go with the second point also, as this will change the auto incrementer of the column. As this is an only one-time use case, auto incrementer can be set from MySQL also.

If we give this admin should also need to consider that id should not conflict with the previous one.
