### ISSUE TITLE
slider list is not getting filter when admin locale is arabic

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4929]
# Bug report

### Issue Description
slider list is not getting filter when admin locale is arabic

#### Bagisto version
- [X] master branch

### Steps to reproduce

1. Create slider in ar or en locale
2. set admin locale in ar
3. filter the slider based on en or ar locale

### Expected result

slider list should be visible based on requested locale

![Screenshot_390](https://user-images.githubusercontent.com/43210406/121842624-52edae80-ccfe-11eb-94fc-1aa1a1a57ab0.png)

### Actual result

![Screenshot_389](https://user-images.githubusercontent.com/43210406/121842660-639e2480-ccfe-11eb-9e9f-50e27a5986bd.png)

**Comment by devansh-webkul** [comment]
Whenever a new locale is added channel should be saved in that locale also. In the mentioned issue channel is not saved in the ar locale that's why the result is not there.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 
I have saved the channel again for the ar locale but still not able to filter result if admin change locale to ar

**Comment by vaishaliwebkul** [comment]
Once save the channel's details in ar local, the filter is working fine.
