### ISSUE TITLE
Image Resolution Suggestion

### ISSUE THREAD

**Issue by ersaurav36** [bagisto/bagisto#493]
We should add recommended image resolution everywhere we are taking images either in the logo, banner of product, seller, shop etc. We can either text below the fields or reference icon kind of.

![aad6d98edb1c9f048c8ef4621f961979 1](https://user-images.githubusercontent.com/32482149/51833697-2d72cc80-231e-11e9-9fa4-e885f497abfe.png)

**Comment by prashant-webkul** [comment]
Duplicate issue, already present #492
