### ISSUE TITLE
Add rules to shipping & payment methods

### ISSUE THREAD

**Issue by mezzat11** [bagisto/bagisto#4930]
I think you should add rules to shipping & payment methods
Rules like : 
Min cart amount 
Maximum cart amount
Working only with selected  cities 
exclude products/categories 
like other e-commerce systems

**Comment by vaishaliwebkul** [comment]
Hi @mezzat11 
You can create your own custom rules based on the cart attributes, product attributes using the Cart Rule feature https://prnt.sc/15eicgx
You may also set the minimum order amount from the configuration->sales->orders section https://prnt.sc/15eifzx
