### ISSUE TITLE
Root category name is missing when admin locale is not en

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4931]
# Bug report

#### Bagisto version
- [X] master branch

### Steps to reproduce

1. Change the locale to Dutch
2. Go to Catalogus -> Categorieën 
3. Check the naam (name) column

![category root](https://user-images.githubusercontent.com/1594411/121978183-f1722200-cd87-11eb-974e-6c0bd30ad236.PNG)

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I just checked in the backend, dutch locale translation is not present in DB. So I am adding the seeders for the default locales only. If user is adding new locale, then user  need to save the categories also.
