### ISSUE TITLE
Getting method not defined issue

### ISSUE THREAD

**Issue by musawirjon** [bagisto/bagisto#4937]
# Bug report
The method fetchAttributes() is not defined error
### Issue Description

path to controller Controller path (laravel-pwa/src/Http/Controllers/Shop/API/APIController.php)
method name: fetchAttributes()

#### Bagisto version
1.3.1

### Steps to reproduce

1. In PWA  version: 1.2.0, Navigate to mobile app, open a category, Error will be thrown, Error content is undefined method fetchAttributes();
2. Controller path (laravel-pwa/src/Http/Controllers/Shop/API/APIController.php).
3. I can't see any method name fetchAttributes(), Is this method changed, or completely removed.

**Comment by ghermans** [comment]
You already reported this on https://github.com/bagisto/laravel-pwa/issues/198
