### ISSUE TITLE
Virtual products are not buyable without inventory stock

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4943]
# Bug report

### Issue Description

When i create a new virtual product without any inventory it can not be added to the cart.

#### Bagisto version
- [X] master branch

### Steps to reproduce

1. Create a new virtual product with inventory qty 0
2. Go to the store and try to order the product.

### Expected result

No inventory qty should be required for virtual products

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I just discussed with the team, the virtual products also having quantity. So it's not a bug.

**Comment by ghermans** [comment]
https://bagisto.com/en/how-to-create-a-virtual-product-in-bagisto/
Please check this line: 

`However, a Virtual Product is different from a downloadable product. It is not something that you can download but rather a virtual product is a service that you can offer to your customer.`

**Comment by vaishaliwebkul** [comment]
@ghermans 
Exactly as said in the mentioned line, virtual product will provide the service like membership, warranty card which also required quantity, so the quantity is must for this type of product.
Major differences for Virtual products are much like simple products but they don't have weight so they can't be shipped.
