### ISSUE TITLE
filesystem not support oss

### ISSUE THREAD

**Issue by ruan11223344** [bagisto/bagisto#4946]
# Bug report

### Issue Description
filesystem not support oss （Object Storage Service） ,when i change the config/filesystems.php then can't access product images

### Preconditions
php 7.3.26

#### Bagisto version
- 1.3.1

### Steps to reproduce

1.
![image](https://user-images.githubusercontent.com/5679023/122701381-b6885680-d27f-11eb-9379-51046e84b4cf.png)

2. 
![image](https://user-images.githubusercontent.com/5679023/122700672-4af1b980-d27e-11eb-8924-1280f0e4fb1b.png)
3.installed composer package by https://github.com/jacobcyl/Aliyun-oss-storage
![image](https://user-images.githubusercontent.com/5679023/122700962-db2ffe80-d27e-11eb-86dd-e73982b07600.png)

### Expected result
product and velocity meta images can be access

### Actual result
can't access all images

**Comment by devansh-webkul** [comment]
Hi @ruan11223344,

May I know, are you facing this in any specific place or everywhere because we have used Laravel `Storage` facade and all the config adapters should work fine because there is no bagisto stuff.

**Comment by ruan11223344** [comment]
yes it work ! i rewrite this file 
![image](https://user-images.githubusercontent.com/5679023/122845898-49d09300-d337-11eb-8bb9-1c3492bca4ec.png)
