### ISSUE TITLE
translation issue for the minimum order at cart checkout 

### ISSUE THREAD

**Issue by asif-webkul** [bagisto/bagisto#4948]
# Bug report

### Issue Description
getting English translation while app is set to ar locale

### Preconditions
1. add products to cart

#### Bagisto version
- [ ] 1.3.1

### Steps to reproduce

1.add products to cart 
2. click checkout on min cart

### Expected result
It should show ar message for minimum order

### Actual result
showing english translation 
https://firebasestorage.googleapis.com/v0/b/tara-cloud.appspot.com/o/orgs%2Ffahad-khan-space%2Ftasks%2F153%2Fimage-662f36fd-4c11-48f7-9187-284abdc6e0c5.png?alt=media&token=2117e3af-b608-456e-ba00-0571ae680222

**Comment by devansh-webkul** [comment]
Hi @asif-webkul,

Usually when we complete enhancement, most of the time we provide English locale in all the locale files.

I have provided translation for minimum order only, project is  opensource any one can provide us translation also.
