### ISSUE TITLE
Duplicated queries on Cart

### ISSUE THREAD

**Issue by jovicacosmic** [bagisto/bagisto#4952]
# Bug report

### Issue Description
When we add/remove/update product to Cart, there are too many duplicated queries

#### Bagisto version
- [ ] master branch
- [x] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce
1. Click add to cart button
2. Update quantity on cart item
3. Remove item from cart
4. Apply/remove coupon

### Expected result
No duplicate queries

### Actual result
400+ duplicated queries, the flow is really slow
![Screenshot from 2021-06-21 13-39-53](https://user-images.githubusercontent.com/78356988/122756637-f6a70380-d296-11eb-86c4-2d21ff66690a.png)

**Comment by devansh-webkul** [comment]
Hi @jovicacosmic,

In carts and checkout pages mostly considered a fresh value that's why it looks like a duplicate. Even though debug bar itself causes slowness in the project.

But i will check and let you know what best can be done on this. I am marking this as optimization.

**Comment by devansh-webkul** [comment]
Hi @jovicacosmic,

As already one issue is open on this i.e.,
https://github.com/bagisto/bagisto/issues/4680

I am closing this one. Keep a track on the mentioned issue.
