### ISSUE TITLE
getting exception when merge guest cart with customer cart with configurable item

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4959]
# Bug report

### Issue Description
Getting error when guest cart is going to added in login customer cart.

#### Bagisto version
- [X] master branch
- [ ] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

1. Login as customer and add configurable item in cart
2. Logout and add same item as guest user
3. Login again with same user

### Expected result
guest user cart item should be added in customer cart 

### Actual result
![Screenshot_416](https://user-images.githubusercontent.com/43210406/123099275-aaeb8a00-d44f-11eb-94c2-683fef80db03.png)

**Comment by jitendra-webkul** [comment]
I am reopening this issue as PR #4961 was causing issues with bundle product #6134 so I have to revert previous changes.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Not fixed,** getting the **error 500** after login in as a user. Please find the below screenshot.

![erroe-5](https://user-images.githubusercontent.com/86394952/160336222-e94e5ece-847e-4394-b839-2c820dd27fe2.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Thanks**, now this issue i**s fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/Dg9NNNLa2Nwb).for future reference.
