### ISSUE TITLE
Can't run "npm run dev/watch etc."

### ISSUE THREAD

**Issue by JoysticK1337** [bagisto/bagisto#4974]
/closed

**Comment by dejavuejs** [comment]
Which package are you compiling?

**Comment by JoysticK1337** [comment]
> Which package are you compiling?

This: Webkul/Velocity

**Comment by JoysticK1337** [comment]
![image](https://user-images.githubusercontent.com/20798838/123543729-a0373a80-d758-11eb-9152-6be64e794f08.png)
Now i'm on this error :/

**Comment by dejavuejs** [comment]
Reinstall node dependencies.

**Comment by JoysticK1337** [comment]
![image](https://user-images.githubusercontent.com/20798838/123544055-2607b580-d75a-11eb-9157-fdae02d767c9.png)
![image](https://user-images.githubusercontent.com/20798838/123544065-2dc75a00-d75a-11eb-9f8a-b19a5f607c4f.png)


> Reinstall node dependencies.
