### ISSUE TITLE
i want to contribute to bagitso, can i add RTL language support and jalali date?

### ISSUE THREAD

**Issue by farsh1d** [bagisto/bagisto#4979]
Hi,
My name is  farshid, im a Laravel developer with 4 years experience in business projects.
I will be happy if I can add RTL languages support and Jalali date  (Solar Calendar) without major changing structure to project.
because 100 millions Persian speaking people can use this free and open source awesome software for sell their products and services, that's amazing
I will be happy to know your opinions about this.
Thanks.

**Comment by ghermans** [comment]
Hi, thank you for your interest to crontibute to Bagisto you can follow our contribution guide https://github.com/bagisto/bagisto/blob/master/.github/CONTRIBUTING.md for more info.
