### ISSUE TITLE
Add RTL language support and jalali date 

### ISSUE THREAD

**Issue by farsh1d** [bagisto/bagisto#4984]
Hi,
My name is farshid, im a Laravel developer with 4 years experience in business projects.
I will be happy if I can add RTL languages support and Jalali date (Solar Calendar) without major changing structure to project.
because 100 millions Persian speaking people can use this free and open source awesome software for sell their products and services, that's amazing
I will be happy to know your opinions about this.
Thanks.

**Comment by devansh-webkul** [comment]
Hi @farsh1d,

Thanks for your interest, we already reverted you here,
https://github.com/bagisto/bagisto/issues/4979#issuecomment-869945775

If you want to contribute, you just need to follow the contribution guide.

I am closing this.
