### ISSUE TITLE
Core Concord is removing all other custom moduleproviders - vendor:publish --all --force

### ISSUE THREAD

**Issue by rahulanand77** [bagisto/bagisto#4987]
# Bug report

### Issue Description
All the custom moduleProviders are removed after vendor:publish command with --all. As it is publishing core/config/concord.php file onto the root file without verifying all the custom module entries.  

### Preconditions
Create any custom module to add ModuleServiceProvider in your Concord.php file. 

1.3.1

### Steps to reproduce

1. Install any custom module package/abs/module1
2. Define ModuleServiceProvider and add models into it
\abs\module1\Models\Model::class,
3. edit the root Config/Concord.php  file and add your provider into it. 
\abs\module1\Providers\ModuleServiceProvider::class,

4. Now run the below command:
PHP artisan vendor:publish --all --force

It will overwrite the file and remove all the custom extensions providers. 

### Expected result
It should not remove all the custom modules providers from it. 

### Actual result
All the custom modules entries will be wiped out from the concord.php file as it will publish the core module concord.php file.

**Comment by devansh-webkul** [comment]
Hi @rahulanand77,

This is the default behavior, the `--all` tag is not recommended especially when you are making modules. Instead, just use the specific provider which you want to publish.

`---all` is used only in starting phase to setup Bagisto. After that, if you have created any modules you need to use the `--provider=<your-provider>` tag .
