### ISSUE TITLE
Target class [Webkul\Shipping\Helper\Rate] does not exist

### ISSUE THREAD

**Issue by stevechai** [bagisto/bagisto#4988]
Hi,

Is the index.php file inside Webkul/Shop/src/Resources/views required?

I got the error Target class [Webkul\Shipping\Helper\Rate] does not exist after install spatie/laravel-cookie-consent package. The error goes away once i remove the index.php from resources/themes/default/views.

**Comment by devansh-webkul** [comment]
Hi, this seems to be a problem with your integration.

Just verify if classes are autoloaded or not.

Please use the forum for any queries. This channel is only for reporting issues.

https://forums.bagisto.com/

**Comment by stevechai** [comment]
Hi,

I found that the file /Webkul/Shipping/src/Helpers/Rate.php was removed since Sep 20, 2018, could I safely remove the /Webkul/Shop/src/Resources/views/index.php file?

**Comment by devansh-webkul** [comment]
Which version are you using?

**Comment by stevechai** [comment]
I'm using the master branch

**Comment by devansh-webkul** [comment]
If you are using the master branch, then this should not happen. Either you have recently moved from some version to the master branch. In that case, just republish your package (if you have not customized anything).

**Comment by stevechai** [comment]
I reinstalled from scratch using master branch, still facing the same issue.

**Comment by devansh-webkul** [comment]
There is something wrong with your instance, I am using the Bagisto master and I am not facing any issue.

**Comment by stevechai** [comment]
From fresh installed Bagisto master, composer require spatie/laravel-cookie-consent, after following the installation instructions from https://github.com/spatie/laravel-cookie-consent, either by adding @include('cookie-consent::index') to Velocity theme's master.blade.php or adding \Spatie\CookieConsent\CookieConsentMiddleware::class, to Kernel.php. The error appear after refresh.

**Comment by devansh-webkul** [comment]
This is some customization which you are trying. If you want some support you can contact webkul for that.

**Comment by stevechai** [comment]
Thanks @devansh-webkul

**Comment by arslan-talib** [comment]
hi @stevechai!
i am also facing this issue, did you get the solution how to resolve it
