### ISSUE TITLE
In Sales module Create refund Subtotal is showing different

### ISSUE THREAD

**Issue by swatikmr2103** [bagisto/bagisto#4989]
# Bug report

### Issue Description
In Bagisto sales module check any of the products and create a refund for that product, in creating a refund, you will find section products ordered there you will have subtotals at two different places at both the places value of subtotal is showing different.

#### Bagisto version
- [x] master branch
- [ ] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

1. Go to the sales module.
2. Create a Refund for any of the products.
3. Check the Refund.
4. Go to the products ordered section.
5. You will find two subtotals there.
6. Check those subtotals they are different

### Expected result
Subtotal should not be different they must be the same at each place.

### Actual result
Subtotals are showing differently
![image_2021_06_21T11_03_31_328Z](https://user-images.githubusercontent.com/76533488/124265458-5339d680-db53-11eb-8aa5-93daa081a888.png)
 in both the palces.

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

I think its a name issue,

`sub total` -> `price
`
`grand total` -> `sub total`

**Comment by swatikmr2103** [comment]
Hello,

No, you can check in order information sub total -> Sub totals
![image](https://user-images.githubusercontent.com/76533488/124274227-9fd6df00-db5e-11eb-8246-279ea92ae9ea.png)
 it's not priced anywhere.

**Comment by swatikmr2103** [comment]
Hello,

As we had a discussion the other day if your team will find this was a bug
you are going to give me a reward.

Please make a response.

Regards
Swati Kumari

**Comment by ghermans** [comment]
> 
> Hello, As we had a discussion the other day if your team will find this was a bug you are going to give me a reward. Please make a response. Regards Swati Kumari

Hi @swatikmr2103, Bagisto is a open source project, this means that it is kinda normal that the community (people who are using Bagisto) report issues or contribute to the project with fixes or enhancements, we don't directly see any reason to work with some reward system for these contributions

**Comment by swatikmr2103** [comment]
Okay @ghermans.
