### ISSUE TITLE
getting error on webinstaller when setup admin credential with default email and password

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4991]
# Bug report

### Issue Description
getting error on web installer when setup admin credential with default email and password

#### Bagisto version
- [X] master branch
- [ ] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

1. - setup bagisto using web installer
2. - add admin default credentials (admin@example.com/admin123)

### Expected result
Should proceed further without any error

### Actual result
![Screenshot_12](https://user-images.githubusercontent.com/43210406/124297807-197bc680-db79-11eb-8db5-e12fc0174ef1.png)

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul,

This seems like you are trying to do in the existing database. If this error occurs then all test cases should be failing also.
