### ISSUE TITLE
can't install  using composer "InvalidArgumentException"

### ISSUE THREAD

**Issue by muhgad** [bagisto/bagisto#5002]
# Bug report
can't install Bagisto using the composer command line 
### Issue Description
Error when installing new project using the composer command line  "composer create-project bagisto/bagisto"

php version 7.3

#### Bagisto version
- [x] 1.3.1

### Steps to reproduce

1.create new project with command "composer create-project bagisto/bagisto"

### Actual result

[InvalidArgumentException]
Could not find package bagisto/bagisto with stability stable in a version installable using your PHP version, PHP extensions and Composer version.

**Comment by ghermans** [comment]
It seems that your environment doesn't matches the requirements to run Bagisto.
Please verify https://devdocs.bagisto.com/1.x/introduction/requirements.html

**Comment by muhgad** [comment]
All requirements are satisfy
PHP version 7.4
MariaDB: 10.5.10
laravel/homestead' version '11.3.0

**Comment by ghermans** [comment]
@vaishaliwebkul can you please verify this ?

**Comment by vaishaliwebkul** [comment]
@muhgad 
can you please mention your composer version ??

**Comment by vaishaliwebkul** [comment]
@muhgad 
Environment is fine based on the requirement, kindly try to setup by installing the Bagisto zip once from here https://bagisto.com/en/download/ and after unzip file, run **composer install** inside the bagisto directory.

**Comment by ghermans** [comment]
I just verified this on a windows & linux machine  to ensure it is not a bug and couldn't reproduce this issue.
Please use the forum https://forums.bagisto.com for further support regarding this issue
