### ISSUE TITLE
Velocity checkout page changing address doesn't update select shipping method section

### ISSUE THREAD

**Issue by stevechai** [bagisto/bagisto#5004]
# Bug report

### Issue Description

On velocity theme checkout page, if client has multiple addresses, the options for "Select Shipping Method" should be updated every time the client select a different address. 

### Preconditions

I have created a shipping method package to retrieve shipping rate from my courier service provider. For unsupported destinations, I set the shipping method to return false. 

However, If the client have multiple addresses, when they select an address that supported by the courier service provider, the shipping method section return the option correctly, but when client switch to another address which is not supported by courier, the option of the unsupported courier still remain on the shipping method section and allowed client to proceed to checkout with the unsupported courier service.

#### Bagisto version
- [x] master branch
- [ ] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

1.
2. 

### Expected result

Update shipping method section every time client switch address.

**Comment by vaishaliwebkul** [comment]
@stevechai 
Yes, while switching b/w addresses then shipping rates are not updated in my case also.

We will fix this soon.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

This is some kind of enhancement and I am removing this from milestone as this will need some extra shipment methods setup.
