### ISSUE TITLE
Issue with Installation of Bagisto Locally 

### ISSUE THREAD

**Issue by akashthakur05** [bagisto/bagisto#5006]
Server version: 10.4.16-MariaDB
PHP 
PHP 7.4.12 (cli) (built: Oct 27 2020 17:18:47) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group

This installation not moving from this point.
![12](https://user-images.githubusercontent.com/29923859/125532221-b76515f7-900f-4d2c-9888-2c139f60ecd2.JPG)

**Comment by devansh-webkul** [comment]
Hi @akashthakur05,

Can you just share the error log?

-- OR --
 
Just type the command in terminal `php artisan bagisto:install` and share whats the error there.

**Comment by akashthakur05** [comment]
@devansh-webkul Thanks for the help its working with the terminal . Not in the browser
