### ISSUE TITLE
Product editing issue

### ISSUE THREAD

**Issue by zulqarnain07** [bagisto/bagisto#5007]
Hi, When  we try to edit item I get this message.
![image](https://user-images.githubusercontent.com/86829369/125742331-038f189b-5c48-40b3-bb12-dfdd551068a9.png)

**Comment by devansh-webkul** [comment]
Hi @zulqarnain07,

Please fill up the full issue format. And provide all the details.

**Comment by zulqarnain07** [comment]
When I click edit icon 

![image](https://user-images.githubusercontent.com/86829369/125746732-7ac48b8d-c590-4904-be1c-3ce5d2c57cce.png)

page redirected to above attached screenshot.
