### ISSUE TITLE
Child categories item should display in parent category

### ISSUE THREAD

**Issue by zulqarnain07** [bagisto/bagisto#5010]
# Bug report

### Issue Description

child category items not display in parent category if we did not select parent category in item but I think child categories items should display in parent categories also like magneto 
#### Bagisto version
- [x] master branch
- [ ] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

1.
2.

**Comment by vaishaliwebkul** [comment]
@zulqarnain07 
This is up to the user's requirement whether they want to show the child item under the parent category or not if the parent's child is selected only so that the user can customize it.

**Comment by devansh-webkul** [comment]
I am closing this as this is not an issue, for further discussion you can use the forums,
https://forums.bagisto.com/
