### ISSUE TITLE
admin filter options are not working in Safari

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#5011]
# Bug report

### Issue Description
admin filter options are not working in Safari

### Preconditions

Safari 12
Mac 10.14

#### Bagisto version
- [x] master branch
- [X] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

1. login to admin
2. filter grid based on available option in dropdown

### Expected result
filter option should be working

### Actual result
https://www.loom.com/share/614f1971ff924f468a0866fc426cf3ac

**Comment by devansh-webkul** [comment]
Hi, @ghermans and @vaishaliwebkul,

This is probably a bug with Safari not with the project. Sometimes click event won't work in the safari browser and a bunch of issues has been opened related to this.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul can you share the reference here related to this issue with Safari?

**Comment by devansh-webkul** [comment]
@vaishaliwebkul,

https://github.com/vuejs/vue/issues/11014
https://github.com/vuejs/vue/issues/11272
https://stackoverflow.com/questions/68132512/vue-2-6-not-working-correctly-on-safari-ios


I am updating the vue js for admin package also. As they have fixes more in their patch numbers.
