### ISSUE TITLE
Invoice ID is not recognized in Transaction when invoice id contains custom prefix/suffix

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#5018]
# Bug report

### Issue Description
Invoice ID is not recognized in Transaction when invoice id contains custom prefix/suffix

#### Bagisto version
- [X] master branch
- [ ] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

1. Set invoice settings from the configuration
2. generate invoice
3. generate transaction

### Expected result
In transaction, invoice ID should be recognized

### Actual result
![Screenshot_17](https://user-images.githubusercontent.com/43210406/126493043-08b0dfc1-4803-44a0-a0ee-4be2ed5ff9a6.png)
![Screenshot_18](https://user-images.githubusercontent.com/43210406/126493049-bf22e9f4-16c8-4529-b866-653263490abe.png)

**Comment by nguyen123** [comment]
I test on version 1.4.3 but still bug, please check help me
