### ISSUE TITLE
Set Multi Channel based on country

### ISSUE THREAD

**Issue by aboeldhab74** [bagisto/bagisto#5025]
Hi guys,
I'm trying to use multi channel based on country. how i can redirect to hostname based on user country.
Can you help me ?
Thanks!

**Comment by devansh-webkul** [comment]
Hi @aboeldhab74,

You already asked here,
https://forums.bagisto.com/topic/2564/set-multi-channel-based-on-country

Please use forums for discussion. This channel is only for reporting bugs and enhancement.
