### ISSUE TITLE
Date set as 00-00-0000

### ISSUE THREAD

**Issue by xalexslx** [bagisto/bagisto#5035]
# Bug report

### Issue Description
When someone (me) develop a new theme, and use local date format on input, the backend do not parse the date correctly. Maybe we need an option to change parse format?

### Preconditions
Changing date_of_birth input to something like dd/mm/YYYY

#### Bagisto version
- [X] master branch
- [ ] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

1. change theme input to dd/mm/YYYY
2. try to register or edit user

### Expected result
System should be able to parse date and save it 

### Actual result
Save as 00-00-0000

**Comment by devansh-webkul** [comment]
Hi @xalexslx,

I just verified, it is parsing correctly and also save in the correct format,

**Comment by devansh-webkul** [comment]
I am closing this, if you see something broken in existing themes then feel free to raise the issue.

Please use the forum for discussions, this channel is only for reporting bugs and enhancement,
https://forums.bagisto.com/
