### ISSUE TITLE
Separate saveCustomerAddress method on Cart.php

### ISSUE THREAD

**Issue by xalexslx** [bagisto/bagisto#5036]
Hello,

I'm trying to write my own controller to change some behavior. One thing I noticed, currently it is impossible to make my checkout process address split into billing and shipping. That occurs because of the saveCustomerAddress which requires me to have the both billing and shipping process at the same time.

It is possible to change saveCustomerAddress or split it so I can save billing and shipping addresses in different times (such as two forms submit).

**Comment by devansh-webkul** [comment]
HI @xalexslx,

You can create a custom route and controller in your new theme to override the default behavior.

**Comment by devansh-webkul** [comment]
I am closing this, if you see something broken in existing themes then feel free to raise the issue.

Please use the forum for discussions, this channel is only for reporting bugs and enhancement,
https://forums.bagisto.com/
