### ISSUE TITLE
cancel button should not visible if automatic invoice is generated with pending status

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#5041]
# Bug report

### Issue Description
cancel button should not visible if automatic invoice is generated with pending status

#### Bagisto version
- [ ] master branch
- [X] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce
1. go to configuration-> COD payment-> set automatic generated invoice with order/invoice status to "pending" 
2. place an order
3. At customer end, cancel the order.

### Expected result
At admin or customer end, cancel button should not visible if invoice is generated.

### Actual result
![Screenshot_37](https://user-images.githubusercontent.com/43210406/128359233-d9e14c72-ef7f-47ae-975b-6f17098a0d84.png)
![Screenshot_38](https://user-images.githubusercontent.com/43210406/128359239-bd2447fc-8704-44fc-8ca5-850ce07c755d.png)

**Comment by devansh-webkul** [comment]
It should not be visible and not executable also. Because hiding is not a solution because users may execute that by the postman or something.
