### ISSUE TITLE
Mismatch in grand total and sub total in HKD currency in cart summary

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#5051]
# Bug report

### Issue Description
Mismatch in grand total and sub total in HKD currency 
 -
#### Bagisto version
- [ ] master branch
### Steps to reproduce
1.give product price like 32.3456
2. give special price like 28.7657
3. add to cart that product
### Expected result:
both should be same 
### Actual result:
difference in sub total and grandtotal
![screenshot_from_2021_08_04_11_24_46](https://user-images.githubusercontent.com/52821836/128518627-1f951bb2-c3e6-43e8-b3fa-86b4900e2108.png)

**Comment by devansh-webkul** [comment]
This is a very rare case. I am marking this a low priority. As I need to check the test case as well.
