### ISSUE TITLE
Home banners sizes are missed up in the RTL layout

### ISSUE THREAD

**Issue by EgyptianM** [bagisto/bagisto#5056]
# Bug report

### Issue Description

![image](https://user-images.githubusercontent.com/12565380/128627099-5aa55a98-ebc5-4280-9916-e27f1f98fcde.png)

### Preconditions

Fresh install of latest release 1.3.2

#### Bagisto version
- [x] 1.3.2

### Steps to reproduce

1. Fresh install latest release
2.  Add any RTL language
3. Switch to RTL language

### Expected result

![image](https://user-images.githubusercontent.com/12565380/128628239-84206d01-5f1b-4ed8-bf9a-56d7ac32115d.png)

### Actual result

![image](https://user-images.githubusercontent.com/12565380/128627099-5aa55a98-ebc5-4280-9916-e27f1f98fcde.png)

**Comment by EgyptianM** [comment]
Fixed by removing this outer `div`

![image](https://user-images.githubusercontent.com/12565380/128629251-dde95f21-f8e0-475e-8c58-a2c0e19b792d.png)

**Comment by devansh-webkul** [comment]
If a parent div block already have a `col-*` classes then no need of any further `col-*` or `row` classes.

Best practice is always add those classes in div and we can remove from the inline block classes.

While resolving conflictions may be these classes again added. Sad to see that. I will fix that tomorrow morning.
