### ISSUE TITLE
Mysqli error on local by flywheeel install

### ISSUE THREAD

**Issue by xhostcom** [bagisto/bagisto#5057]
! ) Notice: Undefined index: DB_PREFIX in /home/anton/Local Sites/larapp/app/public/installer/index.php on line 98
Call Stack
#	Time	Memory	Function	Location
1	0.0001	367064	{main}( )	.../index.php:0

Can it be installed via the Laravel migration? As the web install hangs. It migrates fine, I tried that before I realised it had an installer?  Error somewhere here, can we delete the installer and migrate tables instead?

 if (!$conn->connect_error) {
                        // retrieving admin entry
                        $prefix = $databaseData['DB_PREFIX'].'admins';
                        $sql = "SELECT id, name FROM $prefix";
                        $result = $conn->query($sql);

                        if ($result) {
                            $installed = true;
                        }
                    }

Thanks

# Bug report

#### Bagisto version
- [ ] master branch
- [ ] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

1.
2.

**Comment by devansh-webkul** [comment]
Hi, @xhostcom,

Its looks like the DB prefix case is not handled. Thanks for reporting this.

**Comment by xhostcom** [comment]
OK I will try when bug fixed if anyone can let me know, Many Thanks

**Comment by devansh-webkul** [comment]
Hi, @xhostcom,

Here is the referenced PR,
https://github.com/bagisto/bagisto/pull/5058

**Comment by xhostcom** [comment]
Hi is there a composer command to create project? Thanks

**Comment by xhostcom** [comment]
Sorry I note there is composer command, Thanks

**Comment by xhostcom** [comment]
Hi I got it working using installer, except on create admin it denies
access? Any way around that?   Thanks

**Comment by devansh-webkul** [comment]
The installer is working fine now. Please check your configuration for the second one.

**Comment by xhostcom** [comment]
OK will test new one Thanks
