### ISSUE TITLE
GuzzleHttp\Exception\ConnectException when editing products

### ISSUE THREAD

**Issue by EgyptianM** [bagisto/bagisto#5060]
# Bug report

### Issue Description

when I try to edit a product I get this exception

```
cURL error 6: Could not resolve host: .algolia.net (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://.algolia.net/1/indexes/products_index/batch
C:\Wamp.NET\sites\bagisto\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php#210
GuzzleHttp\Exception\ConnectException

```

#### Bagisto version
- [ ] master branch
- [x] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

1.   Edit any product.

**Comment by devansh-webkul** [comment]
Hi @EgyptianM,

This seems to be the problem with your instance as Bagisto by default doesn't use any third-party indexing.

**Comment by EgyptianM** [comment]
@devansh-webkul 
OK 
A fresh install of v1.3.2 doesn't have the problem but an upgrade from 13.1 to 13.2 does.
Although  the 1.3.1 isn't modified by any means and still working fine.
I'm not a laravel dev so I can't do minor changes to the script, only translations and some simple ui changes.

I think it's related to the upgrade process.
If you have time try to upgrade from 1.3.1 to 1.3.2 to test it.
Thank you very much

**Comment by devansh-webkul** [comment]
There are several factors that depend on upgrades as the new version is on Laravel 8. If you are trying to upgrade then you should be familiar with Laravel as well.

**Comment by suyashcyber94** [comment]
Hello Team,

Seems like a real error, I have also upgraded to bagisto version 1.3.3 as well as I tried fresh installation, still, the issue is being faced in both cases.

I am using:
Bagisto 1.3.3
PHP 7.4.24
serving through artisan

Even tried multiple internet connections.
![image](https://user-images.githubusercontent.com/10935095/150007101-d1d5ed6f-2484-42bc-8647-ea25242bb6e3.png)


When I comment the following line in the mentioned file then the error gets resolved:
![image](https://user-images.githubusercontent.com/10935095/150008034-e6bab3aa-b2b1-4c90-be90-a2484a38402f.png)

**Comment by suyashcyber94** [comment]
**I have traced the issue back to the below file.**
I feel like this will give you more insights into this issue.


![image](https://user-images.githubusercontent.com/10935095/150010135-358c1ca8-dec3-414a-b2f1-cfc40df0e390.png)

**Comment by devansh-webkul** [comment]
Hi @suyashcyber94,

Just check this file,
https://github.com/bagisto/bagisto/blob/f4cbc59f8124da1e06a41c94aec3dba6154402da/config/scout.php#L18

This driver should be set to `null`.

**Comment by suyashcyber94** [comment]
Okay, I was able to change this to null and it is working but I don't understand why this was not set to null by default.

I noticed in my another bag133 installation it is null there.

I also noticed that in packages/webkul scout.php is published but how come it is not working?

**Comment by devansh-webkul** [comment]
Maybe during your time of installation, it is not forced which is the main reason that `scout.php` is not overridden.

**Comment by suyashcyber94** [comment]
I suspected so, I did force publish using webkul core provider.

Thanks for the instant response.
