### ISSUE TITLE
Multi Vendor Marketplace Installation Issue

### ISSUE THREAD

**Issue by cerohawke88** [bagisto/bagisto#5063]
# Bug report

### Issue Description

I currently installing multi vendor marketplace extension following this tutorial https://webkul.com/blog/laravel-multi-vendor-marketplace/, i encounter a problem where the db cannot be seeded with error `Class WebkulMarketplaceDatabaseSeedersDatabaseSeeder does not exist`. I suppose i followed the tutorial thoroughly so i didn't notice what mistake i've made. 

### Preconditions

PHP 7.4.15
Laravel Framework 7.30.4
Composer 2.0.9

#### Bagisto version
- [x] 1.3.1

### Steps to reproduce

1. Following this [tutorial](https://webkul.com/blog/laravel-multi-vendor-marketplace/)
2. Enter the `php artisan db:seed --class=Webkul\Marketplace\Database\Seeders\DatabaseSeeder` command

### Expected result

The database successfully seeded

### Actual result

Error showed below
![image](https://user-images.githubusercontent.com/32832956/128984278-02e794c8-2b86-468d-9e15-990620cda929.png)

**Comment by devansh-webkul** [comment]
Hi @cerohawke88,

This is a paid extension, please raise a support ticket,
https://bagisto.uvdesk.com/en/
