### ISSUE TITLE
Delete option does not work

### ISSUE THREAD

**Issue by mreduar** [bagisto/bagisto#5065]
# Bug report

### Issue Description
I just did a clean install locally. When I try to delete anything in backoffice with the trash icon I get an error on console: `Property or method "doAction" is not defined on the instance but referenced during render.`

I tried twice to do a clean install and in both cases I get this error.

### Preconditions

Windows 10 Pro 20H2 19042.1165
Laragon MYSQL 5.7, PHP 7.4.15 apache/httpd-2.4.35-win64-VC15

#### Bagisto version
1.3.2

### Steps to reproduce

1. Doing a clean install with composer create-project bagisto/bagisto or downloading the .zip file in both cases gives the same error.
2. Then try to create a product and try to delete it.
3. Or go to languages and try to delete it
4. Also you can go to users and try to delete it

### Expected result
The expected result would be the alert as in the demo application.

### Actual result

Console Error: 
```[Vue warn]: Property or method "doAction" is not defined on the instance but referenced during render.
found in
---> <DatagridFilters>
           <Root>
TypeError: doAction is not a function
```
![image](https://user-images.githubusercontent.com/22550119/129105259-532bb7d0-bc2c-44b8-8fa9-f9a29985d820.png)

**Comment by devansh-webkul** [comment]
Hi @mreduar,

I just check with the latest version and I am not able to reproduce that and the demo is still not updated.

![Screenshot](https://user-images.githubusercontent.com/68321766/129139526-6da35aed-16fa-4e4d-92ae-aac3d5fa36f0.png)

**Comment by devansh-webkul** [comment]
I am able to reproduce this when I am using the `dev` or `watch` mode. In `prod` it's working fine. So in my opinion behavior should be the same in both modes.
