### ISSUE TITLE
Products is_wishlisted attribute is always false on API

### ISSUE THREAD

**Issue by merdiano** [bagisto/bagisto#5067]
# Bug report

### Issue Description

Products is_wishlisted attribute is always false when you get products list from api
#### Bagisto version
- [x] master branch
- [X] 1.3.2
- [X] 1.3.1
- [ ] 1.3.0

### Steps to reproduce

1. add product to wishlist
2. get product

### Expected result

is_wishlisted attribute should be true
### Actual result

is_wishlisted attribute is always false

**Comment by ghermans** [comment]
@devansh-webkul can you please verify this?

**Comment by merdiano** [comment]
I think I found problem is in getWishlistProduct function. Where guard is hardcoded to customer.
```
namespace Webkul\Customer\Helpers;

class Wishlist
{
    /**
     * Returns wishlist products for current customer.
     *
     * @param  \Webkul\Product\Contracts\Product  $product
     * @return boolean
     */
    public function getWishlistProduct($product)
    {
        $wishlist = false;

        if ($customer = auth()->guard('customer')->user()) {
            $wishlist = $customer->wishlist_items->filter(function ($item) use ($product) {
                return $item->channel_id == core()->getCurrentChannel()->id && $item->product_id == $product->product_id;
            })->first();
        }

        if ($wishlist) {
            return $wishlist;
        }

        return null;
    }
}
```

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I will let you know.

**Comment by devansh-webkul** [comment]
Hi, @ghermans and @merdiano,

Wishlist is only for customers, so if you fetching the product just make sure you should have a bearer token in your header, and in the query param `?token=true` needs to be a pass. And this thing is important otherwise again it will get the session guard.

**Comment by devansh-webkul** [comment]
@merdiano and @ghermans,

I just reverified in the fresh instance and it seems to be an issue. I am really sorry actually the helper method is calling as mentioned by you.

Really appollogy for this. I will fix it in a moment.

**Comment by merdiano** [comment]
This issue come back in version 1.4.1 with new rest api

**Comment by ghermans** [comment]
@devansh-webkul can you investigate this?

**Comment by devansh-webkul** [comment]
I will check and let you know.

**Comment by devansh-webkul** [comment]
Hi, @ghermans and @merdiano,

For sanctum API, this must be set,
https://github.com/bagisto/bagisto/blob/bd626a4050160cc3218cc78f7171ac1c212a2fb4/config/auth.php#L5

Have you added a default guard?

**Comment by devansh-webkul** [comment]
Because the new rest API is not session based it's only token-based so we have not bounded auth function with any key so that the user can change from the config or at the time of development default auth driver can also be set.

**Comment by devansh-webkul** [comment]
Hi @merdiano,

We are removing is_wishlisted from product listing as product listing is the public route and we won't mess things with `customer` middleware.

Instead of this, we will provide `isWishlisted` API in the customer middleware and we will provide this in `v1.4.3`.
