### ISSUE TITLE
Unable to create cache directory.Required php version for that is 7.2

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#507]
Framework Version:0.1.4
![screenshot 64](https://user-images.githubusercontent.com/45203177/52050934-13342b00-2578-11e9-9ab3-e3a975438146.png)

**Comment by prashant-webkul** [comment]
On reviewing this issue we found out that you must have switched PHP versions frequently.
Sometimes PHP versions on the command line doesn't change until you restart your system and during it you installed Bagisto due to which this installation error came.
