### ISSUE TITLE
Inclusive of all taxes is not correct or working properly

### ISSUE THREAD

**Issue by parasbhadauria** [bagisto/bagisto#5078]
@devansh-webkul @vaishaliwebkul 
Currently, We have a Price Input field as Price, Cost, Special Price

For example, Let's take a 28% tax slab for the product
Price: $100 (Visible at the front end as $128)
Special Price: $80 (Visible at the front end as $102.40)

Data input for the price field is complex in the current scenario as this is not the right way to implement inclusive of all taxes functionality. 

The price of $100 should be visible as $100 at the front end.
Special Price of $80 should also be visible as $80 at the front end.

i.e. all the calculations should be adjusted within the listing price.
All the big e-commerce portals follow the same thing as I mentioned above.

**Comment by devansh-webkul** [comment]
Hi @parasbhadauria,

- The default behavior of Bagisto doing the Same.

- Tax inclusion is provided and you can enable/disable it from the backend.

For e.g,
- If tax inclusion is enabled, then a 28% tax slab for the product,

    Price: $100 (Visible at the front end as $128)
    Special Price: $80 (Visible at the front end as $102.40)

- If tax inclusion is disabled,

    Price: $100 (Visible at the front end as $100)
    Special Price: $80 (Visible at the front end as $80)

**Comment by parasbhadauria** [comment]
Hi @devansh-webkul 
You got it wrong. 
Actually, we want Tax-inclusive enabled but tax value should be adjusted within the listed price.
If the Product Price is $100 (Inclusive of all taxes, let's say 28% tax), the same should be visible at the front-end.
But instead of $100, it is showing as $128.
Tax adjustment should be done by web application itself as ($78.12 + 28% = $100)
I hope you get it.

**Comment by devansh-webkul** [comment]
@parasbhadauria,
- This is not the case you need to adjust that amount as per your need.
- Functionality is already there.

**Comment by devansh-webkul** [comment]
I am closing this as this is not an issue.
