### ISSUE TITLE
I can't rate the product price to tax

### ISSUE THREAD

**Issue by Arsivpro** [bagisto/bagisto#5079]
I add 18% tax to a 10tl product, it shows 10.01. I'm writing the raw tax-free version of the price 8.4745 comes the same way

![232118957_1454424984915174_3432465970423139938_n](https://user-images.githubusercontent.com/65822345/129547280-04c4a46f-a3b0-4809-a33d-577ea19cf628.jpg)

**Comment by devansh-webkul** [comment]
Hi @Arsivpro,

Please fill in the issue format and please elaborate more. With actual results and expected results so that I can further help you.

**Comment by devansh-webkul** [comment]
Hi @Arsivpro,

Any update on this?

**Comment by devansh-webkul** [comment]
I am closing this as this is not an issue. This can be enable/disable from the backend.
