### ISSUE TITLE
When caching static files on nginx, product images does not show.

### ISSUE THREAD

**Issue by merdiano** [bagisto/bagisto#5085]
# Bug report

### Issue Description
When i add caching for static files on nginx conf product images give 404 not found.
Here is error on log file:
```
2021/08/17 11:08:10 [error] 278986#278986: *3642 open() "/var/www/website/public/cache/medium/product/347/rC0dMIdOJIJNSmpKgm9pVqKVE59HKAl8SKujwxHF.jpg" failed (2: No such file or directory), client: 95.85.108.178, server:website.tm, request: "GET /cache/medium/produ
ct/347/rC0dMIdOJIJNSmpKgm9pVqKVE59HKAl8SKujwxHF.jpg HTTP/2.0", host: "www.website.tm", referrer: "https://www.website.tm/"
```

#### Bagisto version
- [ ] master branch
- [ ] 1.3.2
- [x ] 1.3.1
- [ ] 1.3.0

### Steps to reproduce

1.Add caching to nginx conf
```
location ~* \.(?:css|cur|js|jpg|jpeg|webp|gif|htc|ico|png|html|xml|otf|ttf|eot|woff|woff2|svg)$ {

                expires 1y;
                access_log off;
                add_header Cache-Control "public";
}
```
2.  refresh page

### Expected result
cache product images

### Actual result
product images gone

**Comment by devansh-webkul** [comment]
This is not an issue with the Nginx config, we are using an intervention package for images. So please check whether you have proper dependencies or not.

**Comment by merdiano** [comment]
Sorry my fault! Right, this is not issue. I fixed problem by adding
```
location ~* ^/cache.+\.(jpg|jpeg|gif|png|bmp|JPG)$ {
	try_files $uri $uri/ /index.php?$query_string;
	log_not_found off;
}
```
to nginx conf
