### ISSUE TITLE
non-cancelled order status

### ISSUE THREAD

**Issue by Arsivpro** [bagisto/bagisto#5087]
In the attached video, you can see that the order I pressed the cancel button was processed.

https://drive.google.com/file/d/17hmfJUHgrwTsSG8qKT4tFeoAd3PwfakP/view?usp=sharing

bagisto 1.3.2 version

**Comment by devansh-webkul** [comment]
Hi @ghermans,

I think it must be related to this https://github.com/bagisto/bagisto/issues/5041.

**Comment by devansh-webkul** [comment]
I am marking this duplicate and closing this as another issue is already there.
