### ISSUE TITLE
on clinking Buy Now button cart items should not carried in checkout 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#5089]
# Bug report
### Issue Description

if there are already few items in cart and user navigate to product page and click on but now then user should be able to place an order only that product individually.
#### Bagisto version
- [ ] master branch

### Steps to reproduce

1. add any item to cart 
2. go to product page and click on but now 

### Expected result:
user should be able to place an order only that product individually.
### Actual result:
all cart items are getting processed to checkout

**Comment by devansh-webkul** [comment]
Actually, the actual flow is adding the cart and redirecting the page on buy now click. So this pretty much seems obvious that the behavior is not exact.

I marking this as an enhancement for buy now functionality because some changes are required in the code and flow.
