### ISSUE TITLE
Not able to add slider on second channel's domain.

### ISSUE THREAD

**Issue by AayushBhatt-webkul** [bagisto/bagisto#5095]
How to reproduce:

Create a second channel.
Create a slider from the admin for second channel.

Slider will not be visible on second channel's domain.

**Comment by devansh-webkul** [comment]
Hi @AayushBhatt-webkul,

I just tested in the three channels, and I am getting sliders in all the channels.

So this is not an issue.

**Comment by devansh-webkul** [comment]
After setting all the channels to the default theme I am able to reproduce this bug.

**Comment by devansh-webkul** [comment]
@ghermans and @AayushBhatt-webkul,

The reason why the slider is not coming in the new channel is because of the new `Home Page Content` field. When you are creating a new channel, `Home Page Content` can be copied from the default one.

So this is nothing with the code.

**Comment by devansh-webkul** [comment]
I am closing this, as this is as per the user's need.
