### ISSUE TITLE
Getting Exception while creating a Category, but category gets created and if we create product using this category then also getting Exception.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#510]
Framework Version:0.1.4
![screenshot 67](https://user-images.githubusercontent.com/45203177/52052855-bdfb1800-257d-11e9-9a30-54ec205d6efa.png)

**Comment by prashant-webkul** [comment]
This is not the problem with the category system as it had been cross checked.
This issue seemed to be coming due to insufficient file storage permissions given 
to Bagisto in your system.
