### ISSUE TITLE
Not render paypal-button-container with PayPal Smart Button

### ISSUE THREAD

**Issue by Mercadoeiea** [bagisto/bagisto#5108]
# Bug report

### Issue Description
When the Paypal Smart Button payment method is selected, the PayPal form does not appear to make the payment. The end of order button also does not appear.

### Preconditions
With the latest version of Bagisto 1.3.2 + Marketplace packages, when I place an order and select the PayPal Smart Button payment method, the form to make the payment with PayPal should appear on the last screen, but nothing comes out, only:
`<div class="button-group"><!----> <div class="paypal-button-container"></div></div>`

#### Bagisto version
- [ ] 1.3.2
+ Marketplace

### Steps to reproduce
1. Add item to cart
2. Open the basket
3. Continue with payment
4. Select billing address
5. Select shipping method
6. Select payment method: Paypal Smart Button
7. The PayPal payment form does not appear

### Expected result
Paypal form apear

### Actual result
Paypal form NOt apear

![2021-08-23 10_07_12-Order - Checkout - One Page - Paypal](https://user-images.githubusercontent.com/77110329/130412911-14a22196-7a47-4806-b7e0-6b2b47e7493c.png)

**Comment by ghermans** [comment]
@Mercadoeiea thank you for reporting this, i would like to ask if you can verify if you get the same issue with a clean bagisto install without the marketplace module?

**Comment by Mercadoeiea** [comment]
I install clean Bagisto 1.3.2 and PayPal is OK, with Default Theme (NO Velocity)
Marketplace packages crash PayPal package?

Extra Packages:
Marketplace 15 for Bagisto v1.3.1
Marketplace bulk upload 2
Marketplace per product shipping 4
Marketplace tablerate shipping v1.3.1

![2021-08-23 18_47_11-Revisar](https://user-images.githubusercontent.com/77110329/130485831-24b03476-07dd-4391-943d-4b8f04249a7e.png)

**Comment by Mercadoeiea** [comment]
I have installed all 4 Marketplace packages in the clean installation of Bagisto 1.3.2 and it works Ok, only if the shipping method is selected (Marketplace Per Product Shipping). if some other method is selected, such as Flat Rate or Free Shipping, the PayPal buttons do not work, not apear.

**Comment by Mercadoeiea** [comment]
The problem is the Marketplace versions. No compatible with new Bagisto 1.3.2.
Thanks x all
