### ISSUE TITLE
Admin is not getting mail on customer registration 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#5109]
# Bug report
#### Bagisto version
- [ ] master branch
### Steps to reproduce

1.sign up customer

### Expected result:
admin should get an mail
### Actual result
no mail to admin on customer sign up

**Comment by devansh-webkul** [comment]
Hi @ghermans and @bhanu-webkul,

May I know did you change your email from the admin panel?

Because by default `admin@example.com` is non-compliant.

Just try to use genuine mail and let me know.

**Comment by ghermans** [comment]
@devansh-webkul i used Mailhog https://github.com/mailhog/MailHog which comes with Homestead to test this.  
So it wouldn't matter what e-mail address is being used.

**Comment by devansh-webkul** [comment]
Okay! I will check this.

**Comment by devansh-webkul** [comment]
I just checked the code, code is only written for customers. For admin, it should be a separate template without a password. This should be an enhancement.

Rest I just found one bug in a key which I am fixing.
