### ISSUE TITLE
I cann`t see my orders after updating from 1.3.1 to 1.3.2

### ISSUE THREAD

**Issue by rsabzaali** [bagisto/bagisto#5118]
# Bug report

### Issue Description
In new bagisto version I`m manually updated my version. After updating I dont see my orders.

#### Bagisto version
- [ ] master branch
- [x] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

### Steps to reproduce

1. 
2.

**Comment by rsabzaali** [comment]
Hi @devansh-webkul 
The issue still persist on my side.

**Comment by devansh-webkul** [comment]
Did you added this PR,
https://github.com/bagisto/bagisto/pull/5124

**Comment by rsabzaali** [comment]
> Did you added this PR,
> #5124

Yes,

**Comment by devansh-webkul** [comment]
I am just checking, compiled file is missing.

**Comment by rsabzaali** [comment]
Also I find that I can`t see customers Address, Invoices and Orders.

**Comment by devansh-webkul** [comment]
Yeah, 4 new `datagrid-plus` have been placed, which is in the testing phase. When it will become stable, we will use it.

**Comment by devansh-webkul** [comment]
@rsabzaali,

Add this PR also,
https://github.com/bagisto/bagisto/pull/5139
