### ISSUE TITLE
Addresses duplicated on the checkout page

### ISSUE THREAD

**Issue by aboeldhab74** [bagisto/bagisto#5119]
Hi Dears,
Addresses being duplicated automatically on the checkout page
Plz help me

**Comment by devansh-webkul** [comment]
Hi @aboeldhab74,

Need some more info to reproduce this.

**Comment by devansh-webkul** [comment]
Hi @ghermans,

Are you able to reproduce this?

**Comment by ghermans** [comment]
@devansh-webkul i will setup a test server to verify this now and will provide feedback in a moment

**Comment by ghermans** [comment]
Unable to reproduce this.

Screenshot
![image](https://user-images.githubusercontent.com/1594411/132311027-7b570fc5-d132-4f56-930d-e22665384b7c.png)

screenshot 2
![image](https://user-images.githubusercontent.com/1594411/132311107-7631fc9a-9a05-47c4-a8cd-518804bfe759.png)

**Comment by devansh-webkul** [comment]
Seems to be an issue at the user end.
