### ISSUE TITLE
Product images not loading - storage:link removal and re-executing is not working

### ISSUE THREAD

**Issue by rockgold22** [bagisto/bagisto#5121]
# Product images are not loading with the latest bagisto version 1.3.2

### Issue Description
Product images are not appearing on the wesbite. We have tried below commands, still no luck
unlink public/storage
php artisan storage:link
php artisan config:cache

### Preconditions
Bagisto 1.3.2 should be installed

#### Bagisto version
- master branch
- 1.3.2

### Steps to reproduce

1) Install new bagisto version 1.3.2 from github. 
2) Create product
3) check product image on the website. 

### Expected result
1. Images should come on the website

### Actual result
Images are not coming on the website. 
![bagisto-error](https://user-images.githubusercontent.com/16397436/131257010-8660822a-4622-4a43-a1e9-fa52f7036e14.png)

**Comment by rockgold22** [comment]
I have tried all the commands listed on 

https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions/42
https://forums.bagisto.com/topic/1367/images-no-showing-in-the-front-store-error-this-is-the-solution-tested-and-works

but noting is working and still no images coming.

**Comment by rockgold22** [comment]
@vaishaliwebkul is there any update. can you please let me know

**Comment by prateek-webkul** [comment]
@rockgold22, 

We tried to reproduce the issue but it is working fine, we are getting the product images in default as well as velocity theme. Can you share the site url so that we can check at our end. 

Also, please go to the .env and check that app_url should be valid.

**Comment by rockgold22** [comment]
Hi @prateek-webkul ,

You can check it on our website "https://shareyourgist.com/". The app_url is also set in the env file. 

APP_URL=https://shareyourgist.com

Even in admin after upload, it is not working. 

![error](https://user-images.githubusercontent.com/16397436/131455745-d1ac11dc-7bc9-4359-91a9-40f73eb6b02a.png)

**Comment by rockgold22** [comment]
The config/imagecache.php file has the below code for your referene.


`return [

    /*
    |--------------------------------------------------------------------------
    | Name of route
    |--------------------------------------------------------------------------
    |
    | Enter the routes name to enable dynamic imagecache manipulation.
    | This handle will define the first part of the URI:
    |
    | {route}/{template}/{filename}
    |
    | Examples: "images", "img/cache"
    |
    */

    'route' => null,

    /*
    |--------------------------------------------------------------------------
    | Storage paths
    |--------------------------------------------------------------------------
    |
    | The following paths will be searched for the image filename, submitted
    | by URI.
    |
    | Define as many directories as you like.
    |
    */

    'paths' => [
        public_path('upload'),
        public_path('images')
    ],

    /*
    |--------------------------------------------------------------------------
    | Manipulation templates
    |--------------------------------------------------------------------------
    |
    | Here you may specify your own manipulation filter templates.
    | The keys of this array will define which templates
    | are available in the URI:
    |
    | {route}/{template}/{filename}
    |
    | The values of this array will define which filter class
    | will be applied, by its fully qualified name.
    |
    */

    'templates' => [
        'small' => 'Intervention\Image\Templates\Small',
        'medium' => 'Intervention\Image\Templates\Medium',
        'large' => 'Intervention\Image\Templates\Large',
    ],

    /*
    |--------------------------------------------------------------------------
    | Image Cache Lifetime
    |--------------------------------------------------------------------------
    |
    | Lifetime in minutes of the images handled by the imagecache route.
    |
    */

    'lifetime' => 43200,

];
`

**Comment by rockgold22** [comment]
I have executed `php artisan vendor:publish --provider="Webkul\Product\Providers\ProductServiceProvider" --force` command and my config/imagecache.php file is updated but now below error is coming for image access. 

```
Intervention\Image\Exception\InvalidArgumentException
resizeCanvas() accepts only integer values as argument 1.
```

**Comment by rockgold22** [comment]
I got the issue. The Small, Medium and Large files were old and not had the updated code. I set the dimensions and now it is working.
