### ISSUE TITLE
wrong order status showing at admin and customer end

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/bagisto#5125]
# Bug report

### Title
 wrong order status showing at admin and customer end. 

### Preconditions
  
    1. framework Version.: master
 
### Steps to reproduce
 
    1. step1: place an order of 2 qty(same products)
    2. step2: generate invoice and then create shipment of both quantity and refund 1.

### Expected result
    order status should be completed 
### Actual result:
  showing processing

**Comment by devansh-webkul** [comment]
Is this related to an automatic invoice or in normal it is happening?

**Comment by devansh-webkul** [comment]
I am able to reproduce in normal also.
