### ISSUE TITLE
Column 'url_path' cannot be null in category_translations when adding category

### ISSUE THREAD

**Issue by swampthang** [bagisto/bagisto#5127]
# Bug report

### Issue Description
- Fresh install of Bagisto following this https://devdocs.bagisto.com/1.x/introduction/installation.html#install-bagisto-using-composer
- Logged in to admin.
- Tried to add a category and got the following error. 
`
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url_path' cannot be null (SQL: insert into `category_translations` (`locale`, `name`, `description`, `meta_title`, `slug`, `meta_description`, `meta_keywords`, `locale_id`, `category_id`) values (en, Flexible Music Tracks, <p>Flexible Music Tracks</p>, , flexible-music-tracks, , , 1, 2)) 
`

The url-path column is not in the SQL insert statement. I suppose I could go in to the category_translations table and set it to allow a NULL value. 

### Preconditions
Mac Pro (Late 2013)
OS Version 10.13.6
Using Valet
php 7.4
mySql Ver 14.14 Distrib 5.7.9, for osx10.9 (x86_64) using  EditLine wrapper
MySql Encoding - utf-8

#### Bagisto version
- [x] master branch
- [x] 1.3.2

### Steps to reproduce

Steps provided in Issue Description

### Expected result
Successfully add category

### Actual result
Illuminate\Database\QueryException Error listed above. Here's the flare share
https://flareapp.io/share/Rmr9QOq5#F63

A category record was inserted but the description, name, slug and attributes were not stored since the category_translations record was not added.
![Screen Shot 2021-09-02 at 5 48 33 PM](https://user-images.githubusercontent.com/428757/131926075-43c8d22c-b533-4f6a-aa4b-78f8c00ddd92.png)

**Comment by devansh-webkul** [comment]
Hi @swampthang,

Could you try with the clone one because it looks like migration is not done properly?

**Comment by devansh-webkul** [comment]
Hi @swampthang,

Any update on this?

**Comment by devansh-webkul** [comment]
Not, getting any revert from the last 7 days. Looks like the user resolved at their end. Closing this issue.
