### ISSUE TITLE
Rest API Enhancement In Sanctum

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#5143]
## Enhancement
- API versioning.
- Only JWT token-based authentication in the new API version (Removal of session-based authentication).
- API for admin endpoints in the new API version.

## Info
- Currently in the API we are using both ways session-based and token-based. In the new API version, only JWT will be there.
- Endpoints for the full system. Currently, we don't have admin endpoints. In the new API version, the admin endpoint will be there.

**Comment by AmooAti** [comment]
Hi @devansh-webkul 
is this change affect guest cart API?

**Comment by devansh-webkul** [comment]
It will no impact as the existing version will leaved as it is.

**Comment by vpankeev** [comment]
Good point, but I prefer sanctum instead of jwt. Maybe you should think about it?

**Comment by devansh-webkul** [comment]
Well, it depends. As the project is already build up on JWT.

We are moving ahead with this. Maybe in the future, we will implement this.

**Comment by devansh-webkul** [comment]
All the old APIs moved to separate packages for the backward support,
https://github.com/bagisto/bagisto/pull/5341

Proceeding with the Laravel Sanctum to give a fresh and good start to the APIs portion.

**Comment by devansh-webkul** [comment]
Hi @jitendra-webkul and @ghermans,

Added full phase maybe some keys and false case left, I will add it at the time of documenting the API.
