### ISSUE TITLE
Review option not showing

### ISSUE THREAD

**Issue by mmrtonmoybd** [bagisto/bagisto#5149]
Review option not showing in product view page on my local environment.

But review page show in demo mode in https://demo.bagisto.com/bagisto-333-77-99-88/

I attach a image of my local environment. 
Version : Latest

![Web capture_12-9-2021_155426_127 0 0 1](https://user-images.githubusercontent.com/40266584/132983459-066501a9-d9ef-4206-95c3-baf63cbc8ee2.jpeg)

**Comment by 4bdullatif** [comment]
Hi Moshiur,
Make sure you activate "Guest Review" in Configuration>Catalog>Product or you are logged in as a customer.

**Comment by devansh-webkul** [comment]
I am not able to reproduce this, please check whether you have enabled it from the configuration or not.
