### ISSUE TITLE
Queued Email Notifications not working

### ISSUE THREAD

**Issue by yaliya** [bagisto/bagisto#5159]
# Bug report

### Issue Description
NewOrderNotification fails with error 

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order_items.company_id' in 'where clause' (SQL: select * from 'products' where 'products'.'company_id' = 1 and 'order_items'.'company_id' = 1 and 'products'.'id' in (8))`

#### Bagisto version
- [x] master branch

### Steps to reproduce
1. Make new order
2. Check for jobs using telescope
3. NewOrderNotification fails

### Expected result
Job processed

### Actual result
Job failed with error

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order_items.company_id' in 'where clause' (SQL: select * from 'products' where 'products'.'company_id' = 1 and 'order_items'.'company_id' = 1 and 'products'.'id' in (8))`

**Comment by ghermans** [comment]
@devansh-webkul i will setup a demo server tomorrow to verify this issue

**Comment by yaliya** [comment]
@devansh-webkul and @ghermans 

I forgot to mention that this is happening with the SAAS plugin installed.

**Comment by ghermans** [comment]
Ooh ok @yaliya since the SAAS plugin is a paid solution by Webkul i would like to ask/suggest you to please create a support ticket on https://bagisto.uvdesk.com/en/customer/create-ticket/
