### ISSUE TITLE
Disable product stock management

### ISSUE THREAD

**Issue by AmooAti** [bagisto/bagisto#5160]
Hi, Hope your doing well
It's good if we can disable stock management for products because some products are available always and no need to keep track of stock availability.
Thank you.

**Comment by adnanebrahimi** [comment]
We have the same issue.

**Comment by jitendra-webkul** [comment]
Implement in https://github.com/bagisto/bagisto/pull/8461 PR, will be available in Bagisto 2.0

**Comment by AmooAti** [comment]
Thank you very much. That feature is quite useful.
