### ISSUE TITLE
In front page there should be a arrow to scroll product

### ISSUE THREAD

**Issue by Anmol-Chauhan** [bagisto/bagisto#5162]
When we scroll new and feature product using the mouse then some time product gets click so there should an option to scroll product using arrow
https://storyxpress.co/video/ktt6dt2ab1n7hot8o

**Comment by luharuka** [comment]
HEY @ghermans CAN you assign it to me

**Comment by luharuka** [comment]
hey @devansh-webkul can you tell me the path to open in the vs code to see (host) my changes

**Comment by ghermans** [comment]
@deepaksinghgusain227 can you give us an update?
