### ISSUE TITLE
Write All Factories In Laravel 8 Pattern

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#5165]
## Info
- As of now, we are using all factories by legacy support for the Laravel 8. We should implement the class-based factories to reduce the dependency of the legacy support.

## Expected Result
- All factories should be class-based and follow the Laravel 8 compliant.

## Current Result
- Currently, all factory is having legacy support.

**Comment by AbdullahFaqeir** [comment]
Is it okay if I handle this task?

**Comment by ghermans** [comment]
Yes of course, we are looking forward to your pull request

**Comment by AbdullahFaqeir** [comment]
Great, I've already started, almost 50% through 🤙🏻
