### ISSUE TITLE
Pl language - category create blank page

### ISSUE THREAD

**Issue by omenomn** [bagisto/bagisto#5169]
<img width="489" alt="Screen Shot 09-24-21 at 11 47 PM" src="https://user-images.githubusercontent.com/17022624/134743108-59a7112b-def1-40f9-9acc-3b085886de6c.PNG">
<img width="321" alt="Screen Shot 09-24-21 at 11 47 PM 001" src="https://user-images.githubusercontent.com/17022624/134743130-83c5b4ae-3360-450f-b57d-12af850c7959.PNG">

**Comment by devansh-webkul** [comment]
Hi @omenomn,

Please check your lang file and escape the string.

And please use the forum,
https://forums.bagisto.com/
