### ISSUE TITLE
Scroller should only be applicable for filter option.This issue exists for ever grid where filter is used.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#517]
Framework Version:0.1.4
Scroller is working for page also.
![screenshot 68](https://user-images.githubusercontent.com/45203177/52108403-e4718f80-261f-11e9-8f79-e41e1519bc16.png)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed.Now Scroller is removed from filter

**Comment by jyoti-webkul** [comment]
Framework Version: o.1.5
Fixed
