### ISSUE TITLE
Cart handle guest user ( API )

### ISSUE THREAD

**Issue by aboeldhab74** [bagisto/bagisto#5171]
How can i use cart using api while session not working with api how can i save the session to complete my action or how can i generate a temporary token for guest so he can use the application as logged in user

**Comment by devansh-webkul** [comment]
Hi @aboeldhab74,

For guests currently, you need to use cookies so that the Laravel session gets detected. Already we have raised an issue for Rest API enhancement,
https://github.com/bagisto/bagisto/issues/5143

Please use forum,
https://forums.bagisto.com
