### ISSUE TITLE
product images not working

### ISSUE THREAD

**Issue by Arsivpro** [bagisto/bagisto#5172]
Hello, to try, install the latest version of bagisto, then add any product, no image is coming

when adding an image the product will go as follows http://127.0.0.1:8000/cache/small/product/6/4dpZJKnSMfux8AWyJz1LwbnAEQscTEjTF1BPvREd.png

  I need to change the image path to "storage" otherwise the product image is not coming how do I do this http://127.0.0.1:8000/storage/product/6/4dpZJKnSMfux8AWyJz1LwbnAEQscTEjTF1BPvREd.png

**Comment by devansh-webkul** [comment]
This is a dependency issue for the Laravel intervention package. I already suggested changes.

If still not work then go to the admin panel and set the size,
https://github.com/bagisto/bagisto/issues/5121#issuecomment-909017076

**Comment by devansh-webkul** [comment]
Hi @Arsivpro,

Any update on this?

**Comment by devansh-webkul** [comment]
Since not getting any reply for the last 7 days, I am closing this issue.
