### ISSUE TITLE
Typo in type hinting

### ISSUE THREAD

**Issue by DeH4eG** [bagisto/bagisto#5173]
As far as I understand there must be an array type hinted, not the string. I can make PR.

Only i have question, may i type hint argument as well as in DocBlock?

https://github.com/bagisto/bagisto/blob/c967c940957a24ea17b3563c1d42c9d539b56c48/packages/Webkul/Ui/src/DataGrid/DataGrid.php#L235-L239

**Comment by devansh-webkul** [comment]
Yes, this will be an array. Strange I didn't notice.

Thanks for reporting.

**Comment by DeH4eG** [comment]
Okay, i will do :slightly_smiling_face:

**Comment by devansh-webkul** [comment]
Hi @DeH4eG,

I am currently working on the data grid, if you want I can add in the existing PR. Otherwise, I will leave it as it is.

**Comment by DeH4eG** [comment]
Hi @devansh-webkul,

As you wish 🙂 If you are already in progress, then I think it will be better that you will do it. It is not a big issue, for making a separate PR. In my opinion
