### ISSUE TITLE
API for customers to cancel order

### ISSUE THREAD

**Issue by merdiano** [bagisto/bagisto#5178]
I couldn't find API to be able to cancel orders. But this cancel function appears on the web version when orders status is pending.
This is necessary for mobile applications.

**Comment by merdiano** [comment]
I know Admin API is not integrated. I'm asking it for customers to be able to cancel order via API.

**Comment by merdiano** [comment]
Get orders api should also be moved to OrdersController from ResourceController. Get orders with locale throws sql exception

**Comment by devansh-webkul** [comment]
H there,

It will be good if you raise the new issue with screenshots and log so that I can check.

Thanks for mentioning that.
