### ISSUE TITLE
Mobile View is Not loading at Initial 

### ISSUE THREAD

**Issue by MohanKestrel** [bagisto/bagisto#5181]
# Bug Report
Loading the website in mobile or mobile view.is not loading initailly.

## Issue Description
While Loading the website in mobile or mobile view. The Homepage is not loading initailly. Only the header and tailor with slider image is loaded initially and if any clicks in the ppage loading the  product lists

## Preconditions
SERVER: Apache 2
RAM: 4 GB
PHP: 7.4

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ ] 1.3.2

## Steps To Reproduce
Load the Site in Mobile or Mobile View in chrome

## Actual Result
Need to Load as expected

## Expected Result
Not loading the porduct lsit
![image](https://user-images.githubusercontent.com/28132547/135392786-d5f62a84-c0bc-4fe3-98a2-0c651b0572be.png)

**Comment by devansh-webkul** [comment]
This is due to the web vital. We have loaded a static content in front and on user interaction we are loading the rest of the components on the user interaction.

**Comment by devansh-webkul** [comment]
Please refer here,
https://github.com/bagisto/bagisto/pull/5020#issue-949787286

**Comment by MohanKestrel** [comment]
Cool. Thanks  for the response.
