### ISSUE TITLE
Issue is in checkbox type attribute

### ISSUE THREAD

**Issue by Anmol-Chauhan** [bagisto/bagisto#5191]
# Bug Report

## Issue Description

If we create checkbox type attribute **(is required - no)**  and tick options at the time of creating or editing a product then it saves successfully
after that edit the same product again and un-select all options then try to save product got saved but options will not get un-selected
at least one option must select to un-select all other

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce

Create Checkbox type attribute and after selecting the option in product creation time, try to un-select options

## Actual Result

Options is not getting un-select
## Expected Result

must get un-select all option

**Comment by radiantly** [comment]
Hi, could I take a go at this?

**Comment by devansh-webkul** [comment]
Hi @radiantly,

Sure.
