### ISSUE TITLE
UI Issue in search bar in order section at customer's end.

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#5210]
# Bug Report

## Issue Description
the "x" icon in the search bar is overlapping the "search icon" in order's section

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce
1. Place an order
2. Go to order section and type something in the search bar.

## Actual Result
![hacktoberfest2](https://user-images.githubusercontent.com/53482391/136557914-ab3026f2-5f50-4c6b-9b30-6f54a385b8f6.png)

## Expected Result
The "x" icon should not overlap

**Comment by AbdullahFaqeir** [comment]
Can't reproduce issue.
