### ISSUE TITLE
Error Class 'NumberFormatter' not found

### ISSUE THREAD

**Issue by habe90** [bagisto/bagisto#5212]
# Bug Report

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

**Comment by habe90** [comment]
Error
Class 'NumberFormatter' not found
http://127.0.0.1:8000/admin/dashboard

**Comment by devansh-webkul** [comment]
Please enable your `php-intl` extension or if not installed then please install first. Make sure you have all required extension,
https://devdocs.bagisto.com/1.x/introduction/requirements.html#php-extensions

**Comment by devansh-webkul** [comment]
I am closing this issue, as this is not an issue. Please use the Bagisto forum.

**Comment by habe90** [comment]
Ok thank you
