### ISSUE TITLE
Velocity Advertisement Images issue

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#5217]
## Issue Description

When we edit Advertisement  images 4 and edit any 2 images and add custom images out of 4 images, only 1 image remains there.
Same goes with Advertisement images 3. Edit only 2 images out of 3, only one 1 image remains after you save it. 

## Bagisto Version

- [x] master branch

## Steps To Reproduce

1. Go to Admin -> Velocity -> Meta Data
2. Go to Images Section
3. In Advertisement 4 images, change only 2 images and add your custom images.
4. In Advertisement 3 images, change only 2 images and add your custom images.
5. Save it, and check again.

## Actual Result

https://user-images.githubusercontent.com/53482391/136739463-d9f676d3-eaa8-46e0-8f72-0b8851d5b2cc.mp4

## Expected Result

All images should get updated as it is, No image should get removed automatically, even if it is default image.

**Comment by SanjanaSogimatt** [comment]
Hey I am new to open source. Can I work on this project?

**Comment by aayushbhatt18** [comment]
@SanjanaSogimatt We need to consider some scenarios here:

1. In Ad. 4 images section, if you edit only one image or maybe 2, then only those specific images should get changed and the rest images should be there as it is (even if the remaining images are default images).
2. Same goes with Ad. 3 and Ad. 2 images.
