### ISSUE TITLE
"Sort By" feature should be there for products section at Admin end

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#5221]
## Issue Description

There is no sort by functionality in products section at admin's end.
Sort by can include:
- Price high to low
- Price low to high
- Products with special price
- Alphabets (Descending and Ascending)
And other parameters. 

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce

1. Go to Admin -> Catalog -> Products (No option to sort the products, although we can filter products)
2. Go to Admin -> Sales -> Orders (No option to sort the orders)

## Actual Result

There is no "sort by" functionality as of now.

## Expected Result

There should be sort by

- Price high to low
- Price low to high
- Products with special price
- Alphabets (Descending and Ascending)

And other parameters to sort

**Comment by koffy1** [comment]
Please assign to me
