### ISSUE TITLE
UI - Responsiveness Issue in category page (Velocity theme)

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#5223]
# Bug Report

## Issue Description

When you go to any category page in Mobile view and try to scroll down, the  filter, sorting and view header gets scrolled down till the end of the page. (Even in footer section)
https://prnt.sc/1vxy7ch

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce

1. Create a category.
2. Go to that category in mobile view.
3. Scroll down to the bottom of the page

## Actual Result

https://prnt.sc/1vxy7ch

## Expected Result

https://prnt.sc/1vxy7ch
The above bar should gets fixed  at it's original position.

**Comment by devansh-webkul** [comment]
Hi @JunaidJaved248,

By commenting, the issue is booked, you can proceed further.
