### ISSUE TITLE
Message visible to admin for adding price of product

### ISSUE THREAD

**Issue by Anmol-Chauhan** [bagisto/bagisto#5225]
# Bug Report

Admin can add the large amount in price field but after storing product wrong price shows
so a message must visible to admin for the largest value he can fill in price

## Issue Description

find attached video
https://www.loom.com/share/e919240f936f43fbbdeef01087a9bf55

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

**Comment by devansh-webkul** [comment]
Hi @Anmol-Chauhan,

Follow this thread,
https://github.com/bagisto/bagisto/issues/3984

**Comment by devansh-webkul** [comment]
Ok got it this can be done.

**Comment by jitendra-webkul** [comment]
User needs to take care of this
