### ISSUE TITLE
Status column of review page remains blank if Status is change to disapprove(Mass update)

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#523]
Framework Version: 0.1.4
![screenshot 76](https://user-images.githubusercontent.com/45203177/52119647-b308bc00-263f-11e9-9ebc-cefa6ed158f2.png)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Now after disapproving the review it goes in pending state.It should display as disapproved
![screenshot 12](https://user-images.githubusercontent.com/45203177/52471281-87914e80-2bb6-11e9-916e-d031552653f6.png)

**Comment by prashant-webkul** [comment]
Noted, please wait till next release or update to get this thing reflected.

**Comment by prashant-webkul** [comment]
The functionality for disapproval of customer reviews had been implemented in commit https://github.com/prashant-webkul/bagisto/commit/4661e5b738b84d16866e432ccd1e231d20816baa
wait till next release or update to reflect.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
