### ISSUE TITLE
problem with product images #hacktoberfest

### ISSUE THREAD

**Issue by Arsivpro** [bagisto/bagisto#5230]
install the latest version of bagisto, make the necessary settings and add an official product

![image](https://user-images.githubusercontent.com/65822345/137162286-f972f78d-6651-4f82-8bef-313c908ef812.png)
![image](https://user-images.githubusercontent.com/65822345/137162333-8f43d82a-8717-4786-8242-f14601440858.png)

URL Attention: --->
![image](https://user-images.githubusercontent.com/65822345/137162411-88d174f0-eaff-4c0c-8907-78f2ab27108c.png)
![image](https://user-images.githubusercontent.com/65822345/137162465-608d7852-5892-47c9-abb3-f744ea54d9f2.png)

**Comment by Arsivpro** [comment]
@devansh-webkul I am using php 8 version with gd extension open

**Comment by devansh-webkul** [comment]
I have PHP 8 in my docker instance and it's still working fine. Do you need a docker file I can provide you?

**Comment by devansh-webkul** [comment]
Yes, in `.env` APP_DEBUG=true.

**Comment by devansh-webkul** [comment]
Run `php artisan optimize`.

And hit this url,
https://demo.arsivpro.com/cache/medium/product/2/s0C57vYbTSbnyw5ZsHUSprceyOTxZ4GUGZvXcFXI.png

**Comment by Arsivpro** [comment]
@devansh-webkul I followed the steps, what do we do now?

**Comment by devansh-webkul** [comment]
Still i am not seeing the error screen seems like debug mode in not on.

If you see this URL,
https://demo.arsivpro.com/cache/medium/product/2/s0C57vYbTSbnyw5ZsHUSprceyOTxZ4GUGZvXcFXI.png

Your page is redirecting which means some error occurs, check the error log if you don't want to open the debug mode.

**Comment by Arsivpro** [comment]
@devansh-webkul APP_DEBUG'da=true Are you sure debug mode is on?

**Comment by devansh-webkul** [comment]
I am closing this, please use the forum.

If still not resolved then you can raise a support ticket here,
https://bagisto.uvdesk.com/en/customer/create-ticket/
