### ISSUE TITLE
App `config.php` has bad reference to `ProductGrid::class`

### ISSUE THREAD

**Issue by funder7** [bagisto/bagisto#5232]
# Bug Report

## Issue Description
In the `config/app.php` file, there is a wrong reference to:

```php
Webkul\Ui\DataGrid\Facades\ProductGrid::class
```

By reading issue #1185 I guess that it should be removed.

## Preconditions
Nothing particular

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce
- Create project
- Open `config/app.php`
- Scroll to `EOF`

## Actual Result
Wrong ref.

## Expected Result
Fix or remove the wrong reference

**Comment by devansh-webkul** [comment]
Hi,

I am not seeing the wrong reference. Can you share the permalink of the file?

**Comment by devansh-webkul** [comment]
I am closing this as I have not found the mentioned reference.

**Comment by funder7** [comment]
Hi @devansh-webkul, sorry for the late reply, 

I though that I gave enough info to find it, anyway you can find it [here](https://github.com/bagisto/bagisto/blob/844b6809080740c9cf8b2127bc7eed69bcda2d63/config/app.php#L356)

`Webkul\Ui\DataGrid\Facades\` does not contain `ProductGrid` class.

cheers
