### ISSUE TITLE
Issue if create product for multiple channel

### ISSUE THREAD

**Issue by Anmol-Chauhan** [bagisto/bagisto#5233]
## Issue Description

Create a product for multiple channels but some field's value did not copy due to channel-based

All fields should create with the same value

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

**Comment by devansh-webkul** [comment]
It will handle on the displaying portion, fallback will be placed if no value is set.
