### ISSUE TITLE
Search functionality in admin panel

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#5241]
**Description**
There must be a search functionality in the Admin panel through which various settings and panels can be searched and accessed easily.

**For Example**
If I search "Allow Guest Checkout", then it should redirect me to  Config -> Catalog -> Products -> Guest Checkout Accordion.

This is same as what we see in any Android phone setting's search functionality.

**Comment by ILDaviz** [comment]
@devansh-webkul Add the search form next to the select language form. In case you can write an api that searches all config menus. Is this a good idea?

**Comment by devansh-webkul** [comment]
We will consider and discuss this. Thanks for the suggesstion. :smile:

**Comment by devansh-webkul** [comment]
As discussed with the team, we are not having that much amount of menus. So this is not in our road map as of now. May be in future we will see if we have more menus.
