### ISSUE TITLE
Responsive issue in user Profile - Velocity

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#5259]
## Issue Description

User Profile page in Velocity theme is not responsive.

## Bagisto Version

- [x] master branch

## Steps To Reproduce

1. Login in as customer.
2. Go to profile page in Mobile view

## Actual Result

https://user-images.githubusercontent.com/53482391/138274905-8aabf649-b638-4090-a2f7-66e4b34cd46c.mp4

## Expected Result

The page must be responsive.

**Comment by JunaidJaved248** [comment]
Thanks @devansh-webkul, I will open the pull request  for this issue, once you approve my existing open pull request #5243 & close it after successful merge.

**Comment by devansh-webkul** [comment]
Hi @JunaidJaved248,

Why you are waiting for one PR, you can create a different branch and can make a pull request from that branch.

I am just sharing with you the command, just run these,

- `git remote add upstream https://github.com/bagisto/bagisto`
- `git fetch --all`
- `git checkout -b <new-branch-name>`
- `git reset --hard upstream/master`

Now all set. Do your changes in that branch and commit all your changes and push.

After that create a pull request from that branch.
