### ISSUE TITLE
Some images are not comming when using S3 bucket

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#5284]
# Bug Report
- Some images are not coming when using the S3 bucket.

## Issue Description
- In the components file driver's storage URL is used which is the reason it is not coming.

## Bagisto Version
- [x] master branch
- [x] 1.3.3
- [x] 1.3.2
- [x] 1.3.1
- [x] 1.3.0

## Steps To Reproduce
- Change your driver to an S3 bucket.
- Upload slider images.
- Images won't show up.

## Actual Result
- When using the S3 driver image is broken because the URL is still coming for the file driver.

## Expected Result
- When changing the driver URL should be updated.

**Comment by devansh-webkul** [comment]
Hi @mikeyapina,

Slider images have been fixed. You can take a pull.

**Comment by mikeyapina** [comment]
This is not the issue I sated why is this closed!

**Comment by devansh-webkul** [comment]
This issue fixes the slider images which are coming from the S3 instance.
