### ISSUE TITLE
Some data grids are missing ProvideDataGridPlus trait

### ISSUE THREAD

**Issue by 4bdullatif** [bagisto/bagisto#5292]
# Bug Report

## Issue Description
In the latest release, I wonder why some Datagrids have a ProvideDataGridPlus trait, but others do not.

For example, OrderDataGrid has it, but AttributeDataGrid doesn't.

If there is no specific reason I can complete the upgrade to Datagrid plus for the missing ones.

**Comment by ghermans** [comment]
HI @4bdullatif in the latest release we indeed added datagridplus, this makes it possible to have multiple datagrids on one page. some datagrids have been converted during the development, yet the plan is to switch them all to datagridplus.
If you are willing to do this, go ahead 👍

**Comment by 4bdullatif** [comment]
Of course i'll be glad to work on it..

**Comment by devansh-webkul** [comment]
Hi @4bdullatif,

Yes, we have not added it by default because we are hitting a trial on some pages before executing in the whole app but looks like it's working fine.

I will provide a feedback on your pull request by todays evening.

**Comment by devansh-webkul** [comment]
Hi @ghermans and @jitendra-webkul,

I have started working on this.
