### ISSUE TITLE
Exception after login when product added to cart is out of stock

### ISSUE THREAD

**Issue by merdiano** [bagisto/bagisto#5296]
# Bug Report

## Issue Description

I get this exception in logs
[stacktrace]
#0 /var/www/ozan/packages/Webkul/Checkout/src/Cart.php(376): Webkul\\Checkout\\Cart->addProduct()
#1 /var/www/ozan/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Webkul\\Checkout\\Cart->mergeCart()
#2 /var/www/ozan/packages/Webkul/Checkout/src/Listeners/CustomerEventsHandler.php(19): Illuminate\\Support\\Facades\\Facade::__callStatic()
#3 /var/www/ozan/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(401): Webkul\\Checkout\\Listeners\\CustomerEventsHandler->onCustomerLogin()
#4 /var/www/ozan/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(226): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#5 /var/www/ozan/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Events\\Dispatcher->dispatch()
#6 /var/www/ozan/packages/Webkul/Customer/src/Http/Controllers/SessionController.php(82): Illuminate\\Support\\Facades\\Facade::__callStatic()
#7 /var/www/ozan/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Webkul\\Customer\\Http\\Controllers\\SessionController->create()
........

## Preconditions

Allow Backorders is disabled
guest checkout is disabled

## Bagisto Version

- [ ] master branch
- [ x] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce

1. add product to cart
2. logout.
3. remove product from stock
4. login.

## Actual Result

When product is out of stock or requested quantity is more than stock. Customers get exception after login if they had previously added that product to cart when stock was available. 

## Expected Result

Remove that cart item from cart or decrease quantity

**Comment by devansh-webkul** [comment]
Hi @merdiano,

I just follow the same steps but in my case, I logged in without any exception.

But I am aware that this issue exists.

Can you help me by providing the video so that I can reproduce this in my instance?

**Comment by merdiano** [comment]
Actually

> Hi @merdiano,
> 
> I just follow the same steps but in my case, I logged in without any exception.
> 
> But I am aware that this issue exists.
> 
> Can you help me by providing the video so that I can reproduce this in my instance?

Actually I read this logs on production app server logs and supposed this steps will reproduce it.
I may be wrong. Can you try with this new stpes.
1. add product to cart as guest.
2. remove product from stock
3. login
Sorry i cant provide you video now.

**Comment by devansh-webkul** [comment]
From the second point, `remove the product from stock` means the stock should be zero or completely remove the product?

**Comment by merdiano** [comment]
stock should be zero

**Comment by devansh-webkul** [comment]
Not getting any exception may be test case is different. Well, I am closing this if found then I will reopen this.
