### ISSUE TITLE
'rm' is not recognized as an internal or ...

### ISSUE THREAD

**Issue by amiria703** [bagisto/bagisto#5303]
# Bug Report
'rm' is not recognized as an internal or external command operable program or batch file.

## Issue Description
Trying to install bagisto in a Windows environment
Noticed that the developers used "rm" that is the remove command of Unix-like systems
But in windows, specially cmd, it's command is "del"

## Preconditions
Windows 7 Service Pack 1

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0
Not sure I'm using composer version

## Steps To Reproduce
Try to install the "bagisto" on a windows env using readme "original page of project" in github

## Actual Result
Error: 'rm' is not recognized as an internal or external command operable program or batch file.

## Expected Result
Install successfully without any errors.

**Comment by ghermans** [comment]
Are you installing bagisto from your browser or terminal?

**Comment by devansh-webkul** [comment]
Hi @ghermans and @amiria703,

I think this issue is fixed,
https://github.com/bagisto/bagisto/pull/5254

**Comment by devansh-webkul** [comment]
Please check with the latest master, this issue is fixed.
