### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by amiria703** [bagisto/bagisto#5304]
# Bug Report
Readme Typo

## Issue Description

**2. Or you can install Bagisto from your console.**

##### Execute these commands below, in order

~~~
1. composer create-project bagisto/bagisto
~~~

~~~
2. PHP artisan bagisto: install
~~~

As the code parts can be copy pasted it's better to separate the numbers and the original code,
Also in the second command in the front of "bagisto:" there a space which can make problems

I think this is better:

**2. Or you can install Bagisto from your console.**

##### Execute these commands below, in order:

~~~
composer create-project bagisto/bagisto
~~~

~~~
PHP artisan bagisto:install
~~~

## Bagisto Version

- [X] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

**Comment by devansh-webkul** [comment]
Hi @amiria703,

I am not getting what you are trying to say.

**Comment by devansh-webkul** [comment]
Okay, I checked thanks for reporting this, I will fix it as soon as possible.

**Comment by amiria703** [comment]
@devansh-webkul  Sorry for my bad English,
The second part fixed but still the first part remains
Look here:
![image](https://user-images.githubusercontent.com/54179379/140723111-3bc0b7b8-5d05-4568-a3dc-128afc26b444.png)
By clicking the button I mentioned you can easily copy the code and then paste it in the terminal
But, the first part of code ("1. " I mean) that is number doesn't let you use this functionality
And the numbers will also be copied
