### ISSUE TITLE
Cart Set Shipping API

### ISSUE THREAD

**Issue by AmooAti** [bagisto/bagisto#5305]
# Bug Report
Hi,
There's a bug with setting shipping method API, if you send a deactivated shipping method code to this API it will be set and there's no checker about status of requested shipping method.

## Bagisto Version

- [X] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce
disable a shipping method and then try to set this shipping method on cart using `<HOST>/api/checkout/save-shipping`

## Actual Result
The shipping method will be set.

## Expected Result
throws an error. (400)

**Comment by amiria703** [comment]
I'm not moderator nor related to this but in GitHub for checking the version part; Simply, add a "X" there. E.g. [X]
