### ISSUE TITLE
Flat Rate calculation type in admin configurations

### ISSUE THREAD

**Issue by AmooAti** [bagisto/bagisto#5307]
# Bug Report
Hi, 
Flat rate shipping calculation type not showing in admin configuration when method status is enabled.

## Bagisto Version

- [X] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce
1. Go to admin panel -> configuration
2. Go to the Sales menu and select the Shipping methods tab
3. enable Flat Rate shipping and there's no type selection for cost calculation.

## Actual Result
![Screen Shot 2021-11-07 at 3 18 37 PM](https://user-images.githubusercontent.com/36756531/140643650-19f64b42-5a1a-492e-adb0-1d0c3e9264da.png)

## Expected Result
![Screen Shot 2021-11-07 at 3 18 24 PM](https://user-images.githubusercontent.com/36756531/140643659-50842e60-3bb5-4479-9ddb-8f1514477edf.png)

**Comment by devansh-webkul** [comment]
Hi @AmooAti,

Thanks for reporting this.
