### ISSUE TITLE
In Front end Order details, Order id is having a lot of space.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#5316]
# Bug Report
Unnecessary Space at the Order ID.

## Issue Description
When we check the order details at the front end and there in the Order ID, there is unnecessary space is visible which looks slightly odd.

## Bagisto Version
v1.3.3

## Steps To Reproduce
1. Login with customer id.
2. Order a product and then check the order details on the customer's dashboard.
3. There we will be able to see the unnecessary space.

## Actual Result
The Space Image is below.
![Order ID space](https://user-images.githubusercontent.com/92721837/141112484-1f19da74-a7dd-4cb7-a611-60d8358a4a54.png)

## Expected Result
It would be much better if the space will be reduced so that the Date and time format also get properly adjusted.

**Comment by ghermans** [comment]
@deepaksinghgusain227 can you follow up this issue?
