### ISSUE TITLE
Price getting overlapped in a screen when INR is selected

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#5324]
# Bug Report
- I just checked in the demo also, so this issue exist since past versions also.
- Price getting overlapped in a screen when INR is selected.

## Issue Description
- Price getting overlapped in a screen when INR is selected.

## Bagisto Version
- [x] master branch
- [x] 1.3.3
- [x] 1.3.2
- [x] 1.3.1
- [x] 1.3.0

## Steps To Reproduce
- Check the homepage, cart wherever the price is there.

## Actual Result
- Have a look,

    ![Screenshot](https://user-images.githubusercontent.com/68321766/141413226-62b1fd6b-8d77-4585-8236-5cf568e4fe0e.png)

## Expected Result
- Should not be overlapped.

**Comment by JunaidJaved248** [comment]
@devansh-webkul I want to work on it

**Comment by devansh-webkul** [comment]
Sure!

**Comment by JunaidJaved248** [comment]
Thanks, @devansh-webkul  I just checked it from demo of bagisto live, But I didn't found any overlapped, can you show me via screenshot in which screen its getting overlapped

**Comment by devansh-webkul** [comment]
I already attached a screenshot, maybe this seems to be an issue with my browser.

**Comment by devansh-webkul** [comment]
I am closing this, if anyone found this. Feel free to comment I will reopen this.
