### ISSUE TITLE
Ability to set visibility for the individual product in the wishlist

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#5335]
## Enhancement
- There should be the ability to set visibility for the individual product in the wishlist by the customer.

**Comment by JunaidJaved248** [comment]
@devansh-webkul Can You explain it , I want to work on it,

**Comment by devansh-webkul** [comment]
This feature will be done internally.

**Comment by JunaidJaved248** [comment]
Okay Right!!
