### ISSUE TITLE
Billing Address must have a Correct Format

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#5337]
**Issue Description**

When we check the Admin end where we check the sales details, there when we check the details of Billing Address which we found slightly unsystematic in order.

**Bagisto Version**
- [ ] master branch
- [ ] 1.3.3

**Steps To Reproduce**
1. Go to admin -> Sales -> Orders -> Actions
2. Now look at the invoice.
3. Check the address details. These details are not as required.

**Actual Result**

![Address Enchancement](https://user-images.githubusercontent.com/92721837/142408805-f504bd85-883d-4c9e-bf59-33ce3c307dd1.png)

**Expected Result**
No abbreviations must be allowed at the state and city-related concerns. 
The correct format must be :
1. NAME  2. Place or City 3. District 4. State 5. PIN Code 6. Country

**Comment by ghermans** [comment]
The address format really depends on the country / area https://en.wikipedia.org/wiki/Address#Format_by_country_and_area
if we really want to optimize / change this, then i would like to suggest to make it possible to change the format from the admin panel instead of having to manually edit all the blade files

**Comment by ghermans** [comment]
We will discuss this during a meeting and provide feedback.

**Comment by JunaidJaved248** [comment]
Right @devansh-webkul @ghermans

**Comment by ghermans** [comment]
@devansh-webkul, we had a meeting regarding this and agreed that the admin should have an option in the admin panel to configure the addresss format.
