### ISSUE TITLE
Product is displaying as out of stock if default Inventory is zero, while other Inventory sources have products.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#534]
Framework Version: 0.1.4
![screenshot 85](https://user-images.githubusercontent.com/45203177/52162977-33dbbc80-2701-11e9-9678-19aceaa91a22.png)
![screenshot 86](https://user-images.githubusercontent.com/45203177/52162980-39d19d80-2701-11e9-8703-522fa87b82cd.png)

**Comment by prashant-webkul** [comment]
The other inventory 'First_Source' is surely not being selected as the inventory source in your channel.
Kindly goto edit of the channel and select the 'First_Source' in the inventories.

![inventorysourceissue](https://user-images.githubusercontent.com/41140572/52190837-4d971400-2867-11e9-88c8-9206f2062368.png)

**Comment by Jyoti-Singh1** [comment]
Getting this issue when Inventory Source is selected from channel.
![screenshot 97](https://user-images.githubusercontent.com/45203177/52202559-d11b2a00-2894-11e9-84d3-c504fd333940.png)
