### ISSUE TITLE
admin (RTL) - menu not apears

### ISSUE THREAD

**Issue by AmooAti** [bagisto/bagisto#5342]
# Bug Report
Hi,
If the Admin sets language to a RTL lang side menu does not appear.

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Actual Result
![Screen Shot 2021-11-19 at 7 59 41 PM](https://user-images.githubusercontent.com/36756531/142657784-a9e73691-eef3-4591-a314-de41d62b79bd.png)

## Expected Result
![Screen Shot 2021-11-19 at 7 58 41 PM](https://user-images.githubusercontent.com/36756531/142657752-64b5ed07-f6e9-4c5d-b5b1-2560421a48f8.png)

**Comment by devansh-webkul** [comment]
Thanks for reporting this.
