### ISSUE TITLE
The product price should be correct after exporting to excel.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5350]
**CRM Version:** V1.2.0

**Steps To reproduce**--

**1.** Log in as Admin/User.
**2.** Click on the product inside the category tab.
**3.** Try to export the products.
**4.** View the product's excel file.

**Actual result:** The product price is not correct after exporting to excel. Please find the below screenshot.

**Expected result:** The product price should be correct after exporting to excel.

![product_1](https://user-images.githubusercontent.com/86394952/143197714-13775212-b60d-450c-bf90-d9c468ea6673.png)

![price_is_incorrect_in_excel](https://user-images.githubusercontent.com/86394952/143197727-816c1614-3a1e-46f1-9c63-8323c3daf027.png)

**Comment by ghermans** [comment]
@Sanjaybhattwebkul did you verified this with the master branch?

**Comment by Sanjaybhattwebkul** [comment]
> @Sanjaybhattwebkul did you verified this with the master branch?

@ghermans   **Yes** I did
