### ISSUE TITLE
Shipping::rates protected variable is not cleared on Shipping::removeAllShippingRates()

### ISSUE THREAD

**Issue by derMart** [bagisto/bagisto#5353]
See title. In Shipping::collectRates() function, $this->rates is appended, e.g.:
https://github.com/bagisto/bagisto/blob/d00d166546207fba0b177ac7945887621cb96613/packages/Webkul/Shipping/src/Shipping.php#L37

However, this variable never gets cleared, which can cause side effects if collectRates is called multiple times, e.g. by removing items from the cart using cart()->removeItem().

$this->rates should be cleared correctly, e.g. in Shipping::removeAllShippingRates();

best
Martin

**Comment by devansh-webkul** [comment]
But if I am not wrong, in `removeItem` method `collectRate` is calling the mentioned method `removeAllShippingRates`,
https://github.com/bagisto/bagisto/blob/d00d166546207fba0b177ac7945887621cb96613/packages/Webkul/Checkout/src/Cart.php#L361

**Comment by derMart** [comment]
yes, sure, but removeAllShippingRates does not remove all shipping rates, as $this->rates is not cleared in that function.
consider this.
Call collectRates, this will populate $this->rates
Call removeItem, this will again call collectRates or just call collectRates a second time
this will call removeAllShippingRates, but that function does *not* clear $this->rates
Now collectRates will append to $this->rates.
$this->rates now has the rates of the first collectRates call *and* the second collectRates call, which will result in incorrect rates when calling getGroupedAllShippingRates
Is that understandable?

**Comment by devansh-webkul** [comment]
Okay got the point. Property is not clearing when removing the item.
