### ISSUE TITLE
The Input validation's dropdown should be according to attribute type.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5354]
**Steps To reproduce**--

**1.** Log in as Admin/.
**2.** Click on Attribute inside the catalog.
**3.** Create a new attribute with an image type.
**4.** Reach on the input validation section.

**Actual result:** The Input validation's dropdown is not according to attribute type. Please find the screenshot Here.

**Expected result:** The Input validation's dropdown should be according to attribute type.

![bagisto-bug](https://user-images.githubusercontent.com/86394952/143395358-70b45ffc-bb41-4f11-9f00-b21d58ca2c7f.png)

**Comment by jitendra-webkul** [comment]
Input validation will be visible only for text attribute type .

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this enhancement is **done**. so I am **closing** this enhancement.
And I have attached a screenshot [Here](https://prnt.sc/0yBn0T07VswN). for **future reference.**
