### ISSUE TITLE
General code syntax check + fix not closed html tags

### ISSUE THREAD

**Issue by funder7** [bagisto/bagisto#5361]
hi guys, by looking at the code, there are some unclosed html tags, and other minor upgrades that can be done (mostly due to syntax that now is deprecated).

**Comment by devansh-webkul** [comment]
I just checked the code but still for full review you need to pass all the test cases.

It looks like you have added a strict check to all over the place.

**Comment by funder7** [comment]
Yes, only on strings, or where the return type can be only of one type.

I left unchanged where it wasn not clear.

Before going further I pushed the updage to understand if you accept these kind of updates or not.

Thanks

**Comment by ShivanshuPandey007** [comment]
I want to fix this issue. Task to do:
1. check code for any open tags or any other mistake
2. close open html tags

**Comment by devansh-webkul** [comment]
Hi @ShivanshuPandey007,

Pull request already opened for this issue.

**Comment by funder7** [comment]
Hi everybody, 

I'm sorry but I will a bit busy until the next month, I'll do my best to find some time to continue this work and #5358 .
In the meanwhile if anybody wants to make this issue's tests pass, there is no problem on my side!
