### ISSUE TITLE
Issue in price filter if Catalogue rule is enabled.

### ISSUE THREAD

**Issue by tayyab2020** [bagisto/bagisto#5370]
# Bug Report
If I add catalogue rule (discount) than the product which is shown in filters without price filter in it is not shown when I add price filter in filters. I am attaching screenshots for reference. For example if I filter products with price filter after I add 10% discount to products prices than products does not show up in catalogue filter page with pricing filter.

![InkedScreenshot 2021-11-30 021610_LI](https://user-images.githubusercontent.com/61475588/144112432-5e4bed10-34e0-4206-8806-af9b3f85b2e2.jpg)
![Screenshot 2021-11-30 021511](https://user-images.githubusercontent.com/61475588/144112439-fbec2bea-496e-4a88-a51f-ffe9fc07a205.png)

## Bagisto Version

- [x] master branch
- [x] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

**Comment by devansh-webkul** [comment]
https://github.com/bagisto/bagisto/issues/5365

**Comment by Anmol-Chauhan** [comment]
Hi, @devansh-webkul Sir, Please check the word mention **If I add catalogue rule (discount) than**

**Comment by devansh-webkul** [comment]
I will check on the referenced link.

I just added a reference there as the main reason is the filtering issue.
