### ISSUE TITLE
There should be an option to remove all cart items at once

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5376]
**Steps To reproduce**--

**1.** Add multiple items to your cart.
**2.** Try to view your cart.
**3.** Try to delete all cart items at once

**Actual result:** There is no option to remove all cart items at once. Please find the screenshot Here.

**Expected result:** There should be an option to remove all cart items at once.

![cart-bagisto](https://user-images.githubusercontent.com/86394952/144378189-1d6ce051-c026-4b6c-8ed4-c05a2bf62807.png)

**Comment by ILDaviz** [comment]
I'll do the marge as soon as I'm ready 👍

**Comment by ghermans** [comment]
> Sounds like a good addition! I'll do the marge as soon as I'm ready 👍

@ILDaviz  do you have any update regarding this?

**Comment by ILDaviz** [comment]
Sorry for the silence busy months! For this / next month I make the marge request

**Comment by ILDaviz** [comment]
https://github.com/bagisto/bagisto/pull/5998
