### ISSUE TITLE
Validation required for coupon code 

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/bagisto#5381]
## Bagisto Version
- [ ] 1.3.3

## Steps To Reproduce
1. Add to cart product 
2. Checkout product -> select shipping method ->select payment method -> apply coupon (validation required)

**Image:**
![bagisto1](https://user-images.githubusercontent.com/92033944/144562282-08f0c725-704f-4f28-812b-f8f7b09fe201.png)

**Video:**

https://user-images.githubusercontent.com/92033944/144563159-5622631d-d528-4bbc-813c-9d2bc38c7c48.mp4

**Comment by Sanjaybhattwebkul** [comment]
When the user is clicking on Apply Coupon Code button the there should be a warning message for the same input field.

**Comment by devansh-webkul** [comment]
Hi @Sanjaybhattwebkul and @Nikitajoshi39,

When you verify this, please check in both themes i.e. default and velocity.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
This issue is **not fixed** 
I am getting the same issue in **default** themes.

**Comment by devansh-webkul** [comment]
@Sanjaybhattwebkul  and @Nikitajoshi39,

Mentioned changes have been done.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
**Thanks**, now this issue **is fixed.** 
I have attached some screenshots for reference.

![fixed](https://user-images.githubusercontent.com/86394952/144584198-bf7cfead-fa0f-480c-8426-845b9bd584ec.png)
![fixed-5](https://user-images.githubusercontent.com/86394952/144584210-a3067fb8-fb26-4971-9184-a540062a9dbb.png)
![fixed-4](https://user-images.githubusercontent.com/86394952/144584214-3266c82a-d6ea-406b-8f71-c950504516d6.png)
![fixed-3](https://user-images.githubusercontent.com/86394952/144584217-a9fcb3e9-6f0c-4851-93ff-3b7f8a925dd9.png)
