### ISSUE TITLE
The currency icon should be shown properly.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5396]
**Steps To reproduce**--

**1.** log in as a user
**2.** Create an order with the euro currency.
**3.** Complete the order process from the admin panel.
**4.** Try to see invoices from the user panel.

**Actual result:** The currency icon is not showing properly if the user is selecting the EURO currency. Please find the below screen recording.

**Expected result:** The currency icon should be shown properly on the invoice and in the admin panel.

**View screen recording [Here](https://www.awesomescreenshot.com/video/6323070?key=6ac5e0c23884d97f7d8936838c268c87).**

**Comment by devansh-webkul** [comment]
In the backend, it will come according to admin currency, not from the user currency.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
The currency icon is now showing properly on the downloaded invoice.
Please  go through on given video

**Comment by devansh-webkul** [comment]
I am not able to reproduce this,

![Uploading Screenshot from 2022-01-19 13-19-59.png…]()

**Comment by devansh-webkul** [comment]
I think for the customer end, that's why this enhancement is raised,
https://github.com/bagisto/bagisto/issues/5525

@ghermans please confirm.

**Comment by devansh-webkul** [comment]
I just reverified this, by default exchange rate is not set which is the main reason you are using only currency symbol change.

Just set the currency exchange rate 1 USD to 75 dollars something.

Place order in INR, you will see the converted rate in the admin panel.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
**Thanks**, now this **issue is fixed**, So i am closing this issue.
And i have attached a screenshot for future reference [Here](https://prnt.sc/26g2vk5)
