### ISSUE TITLE
The User should not be able to add the same product to the wishlist multiple times.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5398]
**Steps To reproduce**--

**1.** log in as a user
**2.** Try to add the same product to the wishlist multiple times

**Actual result:** The user is able to add the same product to the wishlist multiple times. Please find the below screenshot.

**Expected result:** The User should not be able to add the same product to the wishlist multiple times.

![core-isse](https://user-images.githubusercontent.com/86394952/145170378-ef320028-03f2-4a01-9ac9-1a32c0629573.png)
.

**Comment by devansh-webkul** [comment]
@Sanjaybhattwebkul,

Please share steps to reproduce because if the user clicks on the same wishlist icon product will get removed.

From where it is added.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
The product you are adding to the wishlist should be a configurable product.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
**Thanks**, now this issue **is fixed** so I am **closing** this issue.
Ans I have attached a screen recording for future reference.
Please find the screen recording [Here](https://www.awesomescreenshot.com/video/6409352?key=8c9ce66cc3211aee52f8d40a6d5ea039).
