### ISSUE TITLE
`DataGrid` refactoring, and related classess typings

### ISSUE THREAD

**Issue by funder7** [bagisto/bagisto#5400]
Hello team, 

Recently I've worked on this development: #5362 which gave me the chance to look almost at every class in the project.
I was doing the latest changes on that PR, which involved strict type checking. To do it properly, it was necessary to add types to many functions, and class attributes.

I ended on `\Webkul\Ui\DataGrid\Traits\ProvideCollection::getCollection`, and started to check every type from there. 
The trait works around a Query\Builder object, which is passed from one method to the other in order to build the final query, that returns the results to the DataGrid object. 

You can notice that the phpdoc is a bit confusing, by looking at `\Webkul\Ui\DataGrid\Traits\ProvideQueryResolver::resolveQuery` and `\Webkul\Ui\DataGrid\Traits\ProvideQueryResolver::resolveBooleanQuery`: the first works on a query builder object, while the latter has `$collection` as the first parameter. 
Ok, now if you follow `resolveBooleanQuery` `$collection` variable, you will see that it's fed into `checkFilterValueCondition`. again it's passed to `resolveFilterQuery` (`$collection` is still a `\Illuminate\Support\Collection` at this point). 

Finally `\Webkul\Ui\DataGrid\Traits\ProvideQueryResolver::resolveFilterQuery` is reached, and `where` is called on `$collection`, leading to the last method: `resolveQuery`. 

At this point, `resolveQuery` works on a generic `object`, and applies the filter. 

...In my opinion, this logic should lead to the right query, to return the right data to the DataGrid class which used the Trait. 
To do so, I would use a `Query\Builder` object from the begin, as it is intended for this purpose, and once every condition is set up, the query can be executed, and the data returned to the `DataGrid`. 

By fixing every object type in the code, to the effective one, the business logic would be clearer. Also it would be possible to use autocomplete features.

I will send  you soon a PR with a quite big refactoring on every class based on the abstract `\Webkul\Ui\DataGrid\DataGrid`. 

Please, let me know what do you think about it!

Regards

**Comment by devansh-webkul** [comment]
Linking here,
https://github.com/bagisto/bagisto/issues/5292
