### ISSUE TITLE
The same product should be added to the Wishlist which the user wants to add.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5402]
**Note:** The product type should be **configurable**

**Steps To reproduce**--

**1.** log in as a user
**2.** Try to Add the first product to the Wishlist

**Actual result:** The same product is not adding to the Wishlist which the user wants to add. Please find the below screen recording.

**Expected result:** The same product should be added to the Wishlist which the user wants to add.

**View the screen recording [Here](https://www.awesomescreenshot.com/video/6359480?key=9531a8c0515648a27cba8eef0fa6d0e8)**

**Comment by devansh-webkul** [comment]
Duplicate: https://github.com/bagisto/bagisto/issues/5398
