### ISSUE TITLE
There should be an option to delete a single item from the Wishlist.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5403]
**Steps To reproduce**--

**1.** log in as a user
**2.** Add multiple items on Wishlist.
**3.** Try to delete a single item from the Wishlist.

**Actual result:** There is no option to delete a single item from the Wishlist. Please find the below screenshot.

**Expected result:** There should be an option to delete a single item from the Wishlist.

![core-bug](https://user-images.githubusercontent.com/86394952/145364909-109cf50d-eba9-4dc0-a6d0-bccb55a2ba2a.png)

**Comment by devansh-webkul** [comment]
Not needed if you click on the same wishlist icon it will get removed.
