### ISSUE TITLE
The business details should be present in the invoice.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5407]
**Steps To reproduce**--

**1.** log in as a user
**2.** Click on orders inside profile on the top right corner
**3.** Try to print the invoice for your orders.

**Actual result:** The Business name is not present in the invoice when the user is trying to print the invoice of their orders. Please find the below screenshot.

**Expected result:** The Business name should be present in the invoice. 

![Screenshot from 2021-12-10 12-45-30](https://user-images.githubusercontent.com/86394952/145533618-44ae1529-3403-483e-a30e-4537f8290df8.png)

**Comment by ghermans** [comment]
Hi @Sanjaybhattwebkul have you also configured the company name / address etc at **Configure -> Sales -> Shipping** ?

![image](https://user-images.githubusercontent.com/1594411/145535474-540b0f05-788c-49d7-9dfd-8b9fe6b61cd3.png)

**Comment by Anmol-Chauhan** [comment]
Hi @ghermans , In case if we need or want to show company name and mobile information of the admin

**Comment by Sanjaybhattwebkul** [comment]
> Hi @Sanjaybhattwebkul have you also configured the company name / address etc at **Configure -> Sales -> Shipping** ?
> 
> ![image](https://user-images.githubusercontent.com/1594411/145535474-540b0f05-788c-49d7-9dfd-8b9fe6b61cd3.png)

@ghermans 
Yes, I have completed that process.

**Comment by ghermans** [comment]
@Sanjaybhattwebkul 
I verified this on a clean install from the master branch and i'm unable to replicate the issue.
Please check following screenshots
### Sales settings
![image](https://user-images.githubusercontent.com/1594411/145674516-35c50ae6-8a9a-4820-9c10-ce9b9119fb20.png)

### Invoice
![image](https://user-images.githubusercontent.com/1594411/145674502-eb0c1edc-9172-4c4b-b996-c0b4cd2cdcdc.png)
