### ISSUE TITLE
Multi currency price for product

### ISSUE THREAD

**Issue by Tofandel** [bagisto/bagisto#5411]
We should be able to specify a price for a product in a currency instead of relying on exchange rate

Lets assume the case we have both $ and € configured as currency
One product is priced at 9.99$
The exchange rate is 0.88 and would result in a price of 8.87€

So by default if the product has only a $ price that should be displayed, however it would be nice to be able to override this price per currency per product so that for instance the price could be set to 8.99€ for this particular product without having to change the exchange rate

**Comment by jitendra-webkul** [comment]
Not feasible, you can customize if you want
