### ISSUE TITLE
The image search is not working properly.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5412]
**Steps To reproduce**--

**1.** log in as a user
**2.** Try to search the products by the image.

**Actual result:** The image search is not working properly. Please find the below screenshot.

**Expected result:** The image search should work properly

![image-01](https://user-images.githubusercontent.com/86394952/145575353-e4d0b95f-e73c-4763-915e-d252f903d38c.png)
![imag1-1](https://user-images.githubusercontent.com/86394952/145575364-86c380f1-03ad-4b2c-a1c6-4b9d8ddc6997.png).

**Comment by devansh-webkul** [comment]
This is not a bug, search results come on the basis of analysis trained by the model. If keywords are not matched then the result may not come.
