### ISSUE TITLE
search icon / button in admin datagrids

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#5413]
# Bug Report

## Issue Description

The position of the search icon / button in each datagrid is displayed wrong.  
This only occurs in the admin interface

## Bagisto Version

- [X] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce

Go to a datagrid in the admin panel

## Actual Result

![image](https://user-images.githubusercontent.com/1594411/145674113-779bbc9a-48af-4508-a717-55744642b12e.png)

**Comment by devansh-webkul** [comment]
Not able to reproduce this.

**Comment by devansh-webkul** [comment]
![Screenshot](https://user-images.githubusercontent.com/68321766/145753212-dfe489d9-7828-4ebd-858d-7af2dc9c044b.png)
