### ISSUE TITLE
translating Bagisto not taking place

### ISSUE THREAD

**Issue by mtrf3** [bagisto/bagisto#5416]
I have bagisto 1.3.3 installed and I'm trying to edit 
packages/Webkul/Admin/src/Resources/lang/en/app.php

for example: replace the keyword "sign in" to "sign in now"

`'sessions' => [
            'title'                      => 'Sign In NOW',
            'email'                      => 'Email',
            'password'                   => 'Password',
            'forget-password-link-title' => 'Forget Password ?',
            'remember-me'                => 'Remember Me',
            'submit-btn-title'           => 'Sign In'
        ]
    ],`

<img width="507" alt="Screen Shot 2021-12-12 at 7 31 30 AM" src="https://user-images.githubusercontent.com/15853527/145732602-bc7f50f1-9d43-478a-8988-d8173b0d9070.png">

it is not showing in the frontend

any idea?

**Comment by devansh-webkul** [comment]
Not able to reproduce this, changed on the same key which you mentioned,
![Screenshot](https://user-images.githubusercontent.com/68321766/145755785-6b5e6599-845f-4c7b-aed7-412eab1921f1.png)

Please use bagisto forum for futher comunication,
https://forums.bagisto.com/
