### ISSUE TITLE
The product view page is not working properly for the configurable products.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5422]
**Steps To reproduce**--

**1.** log in as a user
**2.** Try to view the configurable product.
**3.** Try to filter the configurable product by color or size.

**Actual result:** The product view page is not working properly for the configurable products. Please find the below screen recording.

**Expected result:** The product view page should work properly for the configurable products.

**View screen recording** [Here](https://www.awesomescreenshot.com/video/6412991?key=2f351953731d6bca696fba65694f2f5a).

![configurable-product](https://user-images.githubusercontent.com/86394952/145791009-81686206-1c79-455d-97fd-e1e04f316e76.png)

**Comment by devansh-webkul** [comment]
If a parent has images then parent product images should be visible.

**Comment by devansh-webkul** [comment]
Working fine.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
As we discuss. I checked the same on the other instance. and it is working fine.
So I am closing this issue.
