### ISSUE TITLE
 The cart items should not be removed from the cart when the user is trying to buy any product directly.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5437]
**Steps To reproduce**--

**1.** log in as a user
**2.** Add multiple products into the cart
**3.** Go on the product list page
**4.** Try to buy any product without adding it to the cart

**Actual result:**  The cart items are removed from the cart when the user is trying to buy any product directly. Please find the below screen recording

**Expected result:** The cart items should not be removed from the cart when the user is trying to buy any product directly.

**Please find the screen recording** [Here](https://www.awesomescreenshot.com/video/6485803?key=0025f0985bcda36fea1c76ff5534befb).

**Comment by devansh-webkul** [comment]
Some issues are happening on the live instance that's why this is removed but will implement this later,
https://github.com/bagisto/bagisto/pull/5188#issue-1014749650

**Comment by devansh-webkul** [comment]
This is not an issue because the product will again add to the cart after buying is completed.

The previous cart is deactivated until the buy now the functionality is completed.

Ignore my last post, I was thought of a different issue.
