### ISSUE TITLE
There should be a confirmation alert before deleting items from the Wishlist

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5445]
**Steps To reproduce**--

**1.** Add multiple items to your Wishlist and Compare.
**2.** Try to delete items from Wishlist at a time.

**Note:**  Please reproduce this issue with the default theme.

**Expected result:** There should be a confirmation alert before deleting items from the Wishlist.

**Actual result:** There is no confirmation alert before deleting items from Wishlist. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/6520743?key=17140233f21f363f7284fc1ed3b64f94).

**Comment by devansh-webkul** [comment]
No need for any confirmation for the wishlist. The confirmation comes due to the universal method so adding confirmation for only move to cart.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul
It is **working fine**. **but** when the user is trying to move the item to the cart then the item should be removed from the wishlist
Please find the screen recording [Here](https://www.awesomescreenshot.com/video/6522640?key=94c62eb82e9ead31a4c828e4e53b4138).

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
**Thanks**, now this issue **is fixed**. And I have attached a screenshot for future [Here](https://prnt.sc/23pbmgr).
