### ISSUE TITLE
There should be proper validation when the admin is creating grouped,bundle and booking products

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5449]
**Steps To reproduce**--

**1.** log in as an admin
**2.** Create booking product
**3.** log in as a user.
**4.** Try to book the boking product

**Expected result:** The user should be able to book the booking product.

**Actual result:** There is a warning when the user is trying to book the booking product. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/6536317?key=197c63c9bfd683884e6fcb6354b9f6ef).

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
I am getting the same issue on **grouped** and bundle **products**. these should be proper validation when the admin is creating these types of products.

**Comment by devansh-webkul** [comment]
This is not an issue user needs to select an option from the product view page.
