### ISSUE TITLE
Multiple Datagrids only is working on Firefox

### ISSUE THREAD

**Issue by AlexR1712** [bagisto/bagisto#5458]
# Bug Report
## Issue Description
When applying multiple datagrids based on what is stated in the documentation we find that it is only being displayed in Firefox for some strange reason while in the other browsers the component is not rendered.

## Preconditions
A new Bagisto module is implemented which modifies the Profile -> Orders section by adding 2 new datagrids based on bagisto documentation.
Route: /customer/account/orders

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [x] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce
Follow this documentation to create multiple datagrids: 
https://devdocs.bagisto.com/1.x/advanced/datagrid.html#multiple-datagrids

## Actual Result
No multiple datagrids are rendered
![image](https://user-images.githubusercontent.com/8460736/147155296-05e5174d-2d7f-4278-8993-a67e142e50d1.png)

## Expected Result
Expected result like the image but actually only is working on Firefox
![image](https://user-images.githubusercontent.com/8460736/147155509-83d4ddd0-53e7-4595-9c7c-f55367bbe920.png)

**Comment by devansh-webkul** [comment]
Hi @AlexR1712,

This issue has been fixed in the latest version.

**Comment by devansh-webkul** [comment]
This is already fixed so i am closing this. Please verify with latest version.

**Comment by AlexR1712** [comment]
Thank you! @devansh-webkul
