### ISSUE TITLE
The user should not be able to create an order with an invalid quantity.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5459]
**Steps To reproduce**--

**1.** log in as admin
**2.** Create a configurable product add 3 quantities of each variant
**3.** log in as a user.
**4.** Try to order a configurable item with 2 quantities.
**5.** And Again try to order the same item with 3 quantities.

**Expected result:** The user should not be able to create an order with an invalid quantity.

**Actual result:** The is able to create an order with an invalid quantity. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/6569509?key=16032d1c9ce4d7ee010f10d93be1f998).

**Comment by devansh-webkul** [comment]
I already reverted pull request so closing this because one issue is already open.

**Comment by devansh-webkul** [comment]
Reference Link: https://github.com/bagisto/bagisto/issues/5451
