### ISSUE TITLE
Getting Exception while uploading category image after installing project using installer

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#546]
Framework Version: 0.1.4-BETA4
![screenshot from 2019-02-04 18-57-44](https://user-images.githubusercontent.com/45203177/52211278-6fb48480-28af-11e9-8c5e-5ebd368c9501.png)

**Comment by prashant-webkul** [comment]
This is the issue due to incomplete file system permissions given to Bagisto.

**Comment by prashant-webkul** [comment]
#546 Issue was due to php artisan storage:link command was not getting executed properly inside the exec function of php.

**Comment by Jyoti-Singh1** [comment]
Framework version: 0.1.4
Not fixed

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
