### ISSUE TITLE
There should be an option for placing an order if the user is selecting the PayPal Smart Button payment method.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5467]
**Steps To reproduce**--

**1.** log in as a user
**2.** Try to place an order by **PayPal Smart Button** payment method.

**Expected result:** There should be an option for placing an order if the user is selecting the **PayPal Smart Button** payment method.

**Actual result:** There is no option for placing an order if the user is selecting the **PayPal Smart Button** payment method. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/6614670?key=89f2087cfe0068965377ad7c09cecdd9).

**Comment by devansh-webkul** [comment]
@Sanjaybhattwebkul,

You need to add client id and client secret key from the backend,

![Screenshot](https://user-images.githubusercontent.com/68321766/147628559-4865e581-4553-4933-a9b8-05575baacdce.png)

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
This is not an issue. so I am closing this issue.
