### ISSUE TITLE
there must be dimension fixed for category image like category logo 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5469]
## Issue Description

there must be dimension fixed for category image like category logo 

## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. Go to catalog 
2.  Then add categories 
3.  upload  category images and category logo 

## Actual Result

https://user-images.githubusercontent.com/96044834/147535803-9bbcdf68-b58d-4fce-b891-da46ad1cc41b.mp4

**Comment by Sanjaybhattwebkul** [comment]
@singhgagan03 
image size like category logo **doesn't feel good here**. maybe it is not an issue.
@devansh-webkul   can you please verify it.


![logo](https://user-images.githubusercontent.com/86394952/147558756-4adfa6f9-0785-40b0-b927-18cdf1100787.png)

**Comment by devansh-webkul** [comment]
@Sanjaybhattwebkul and @singhgagan03,

This is the category image so not need anything here and for the logo one, that is coming from the side menu.
