### ISSUE TITLE
The review should  update if a user is adding a review for the same product multiple times

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5476]
**Bagisto Version :** Master

**Steps To reproduce**--

**1.** log in as a user
**2.** Write a review for any product multiple times.
**3.** Try to view your reviews.

**Actual result:** The review is not updating if a user is adding a review for the same product multiple times Please find the below screenshot.

**Expected result:** The review should  update if a user is adding a review for the same product multiple times

![REVIEW-ONE](https://user-images.githubusercontent.com/86394952/147630343-d21d38ec-c31b-4220-9a1f-a48e2f5b7185.png)

![REVIEW-TWO](https://user-images.githubusercontent.com/86394952/147630346-92604e0d-472e-4b43-adf3-04b11b935c50.png)

**Comment by devansh-webkul** [comment]
You already raised this issue,
https://github.com/bagisto/bagisto/issues/5393
