### ISSUE TITLE
languages logo is not visible in mobile view 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5483]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to mobile section
2. then go to languages and select differenet languages  

## Actual Result

https://user-images.githubusercontent.com/96044834/147654523-5e4f0c17-d920-4b2f-b360-64d1ed3c06d2.mp4

**Comment by singhgagan03** [comment]
the issue is not solve logos is not visible 

![Screenshot from 2021-12-30 10-56-27](https://user-images.githubusercontent.com/96044834/147724178-936a8159-9415-4352-9516-7e0662a7cc4d.png)

**Comment by devansh-webkul** [comment]
Checking...

**Comment by devansh-webkul** [comment]
Will fix the main logo in mobile soon.
