### ISSUE TITLE
Category should be open when needed in mobile just like locales and currencies tabs

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5489]
## Bagisto Version
- [ ] master branch

## Steps To Reproduce
 1. login as customer 
 2. then go to category section

## Actual Result
![Screenshot from 2021-12-29 18-15-15](https://user-images.githubusercontent.com/96044834/147665342-dab1ebfd-6f30-4085-9812-927c19e54596.png)

expected result 

![Screenshot from 2021-12-29 18-15-34](https://user-images.githubusercontent.com/96044834/147722683-a6fed40a-ce69-49d3-b624-25adc03008dd.png)

**Comment by devansh-webkul** [comment]
Will try to make like currency and locale so that users can only load categories when the user actually needs to see them.

**Comment by jitendra-webkul** [comment]
The mobile category menu is as per the design so no need to fix.
