### ISSUE TITLE
validation not working in inventory page 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5503]
## Bagisto Version
- [ ] master branch

## Steps To Reproduce
1. go to admin panel

2. then go to inventory sources

## Actual Result

![validation ](https://user-images.githubusercontent.com/96044834/147804998-7a53d233-9f99-44e6-a6df-32bc8fbe9cf2.png)

**Comment by ghermans** [comment]
@singhgagan03 I have installed a fresh setup of Bagisto (master branch) and could not reproduce this.
These fields are not required so no validation is set.
- Latitude
- Longitude
- Priority

The contact number does have a validation set
![image](https://user-images.githubusercontent.com/1594411/147811774-26e3fa10-a522-48bc-9905-45a23a6cef6b.png)

**Comment by singhgagan03** [comment]
@ghermans  character should not be insert  in longitute, latitue , priority and also in contact no fields

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
**Thanks**, now this **issue is fixed**. And I have attached a screenshot for future reference.

![Fixed-envntry](https://user-images.githubusercontent.com/86394952/147907102-35ecba09-28b8-4f01-95a0-2c30e7292d33.png)
