### ISSUE TITLE
ui issue  when  we save inventory sources 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5504]
## Bagisto Version
- [ ] master branch

## Steps To Reproduce

1. go to admin panel 
2. then save inventories 

## Actual Result

![inventory](https://user-images.githubusercontent.com/96044834/147805501-d536f497-465d-4807-8e4d-10f3f1e6268f.png)

**Comment by devansh-webkul** [comment]
I think its not needed, its mostly negligible.
