### ISSUE TITLE
CHARACTER SHOULD NOT BE ENTERED IN CONTACT NO 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5506]
## Bagisto Version
- [ ] master branch

steps to produce 
 1. GO TO COFIG PAGE IN ADMIN PANEL 
 
 2. THEN SALES ->SHIPPING 

![Screenshot from 2021-12-31 14-01-01](https://user-images.githubusercontent.com/96044834/147812712-b68321e3-a7a2-4b85-a3e6-e094db78d992.png)

**Comment by ghermans** [comment]
This has already been reported https://github.com/bagisto/bagisto/issues/5503#issuecomment-1003307180
