### ISSUE TITLE
By default All sliders should be listed in the table.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5507]
**Steps To reproduce**--

**1.** log in as an admin
**2.** Click on SlidersCreate inside the settings tab.
**3.** Try to view all sliders

**Actual result:** The Default slider is selected by default. Please find the below screenshot.

**Expected result:** By default All sliders should be listed in the table.

![slider-bug](https://user-images.githubusercontent.com/86394952/147814780-18c7f223-8fd1-468e-bc54-b69851b68016.png)

**Comment by devansh-webkul** [comment]
Sliders will come on the basis of the current channel.
