### ISSUE TITLE
UI issue in product list page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5511]
**Steps To reproduce**--

**1.** log in as an admin.
**2.** Add a special price for any product.
**3.** log in as a user.
**4.** Select the french locale.
**5.** Try to view the product list page.

**Expected result:** There should not any UI issue on the product list page.

**Actual result:** There is a UI issue on the product list page when the user is selecting the french locale. Please find the screenshot [Here](https://prnt.sc/25s8ifc)

**Comment by devansh-webkul** [comment]
@Sanjaybhattwebkul,

Pull request has been merged, you can directly take a pull.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
**Thanks**, now this issue **is fixed**. so I am **closing** this issue. And I have attached a screenshot for future reference.

![fixed-2](https://user-images.githubusercontent.com/86394952/148011304-dd032029-218a-431f-9b98-2fec34c6a4ec.png)
![fixed-ui](https://user-images.githubusercontent.com/86394952/148011309-1a78f000-8e9e-4411-a7f7-91dbb1fc2aa3.png)
