### ISSUE TITLE
Admin package the manifest.php files are missing

### ISSUE THREAD

**Issue by cloud-arrow** [bagisto/bagisto#5513]
# Bug Report

## Issue Description

Run` php artisan concord:modules `to report an error

because the manifest.php files are missing
<img width="1148" alt="截屏2022-01-03 14 09 42" src="https://user-images.githubusercontent.com/52516729/147903439-da97dc93-f593-49a2-9676-4ef6c53ddf90.png">

## Preconditions

php 7.4.26

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce

Run` php artisan concord:modules `

## Actual Result

report an error

## Expected Result

List the list of modules

**Comment by cloud-arrow** [comment]
Please take a look at this question @devansh-webkul

**Comment by devansh-webkul** [comment]
Yeah! These are removed by me. I just thought, this folder is not is used because already two `resources` folders present in each package which really looks like a mess.

I will put it back again if this is really causing the issue.

**Comment by devansh-webkul** [comment]
I am putting this in low priority because I will follow a consistent pattern and provide a proper fix so that all folders only have one `resource` folder. Will do it in the end.
