### ISSUE TITLE
The filters should work properly if the user is trying to filter the products.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5515]
**Steps To reproduce**--

**1.** log in as an admin.
**2.** Click on products inside the catalog
**3.** Try to filter the products by order id

**Expected result:** The filters should work properly if the user is trying to filter the products.

**Actual result:** The filters are not working properly if the user is trying to filter the products. Please find the below screen recording [Here](https://www.awesomescreenshot.com/video/6673839?key=22af27fadbeddf465c8990eea682ae75)

**Comment by devansh-webkul** [comment]
To avoid so much work duplicacy i am linking this issue to new datagrid. Will fix it all these issues when new datagrid code implemented all over the project.

Link: https://github.com/bagisto/bagisto/issues/5292
