### ISSUE TITLE
DataGrid without pagination

### ISSUE THREAD

**Issue by AmooAti** [bagisto/bagisto#5519]
# Bug Report
Hi,
The problem is when we set the `paginate` attribute of Datagrid to false, it causes two errors.
First, because result will be a collection so it won't have totals() method.
Second, After fixing the first issue because of the checker at top of the table body template records won't show

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce
You can set a Datagrid $paginate attribute to false and see that

**Comment by devansh-webkul** [comment]
Linking to this enhancement,
Link: https://github.com/bagisto/bagisto/issues/5292
