### ISSUE TITLE
When i Run Commond php artisan migrate 

### ISSUE THREAD

**Issue by odoogit** [bagisto/bagisto#552]
![screenshot from 2019-02-06 15-20-52](https://user-images.githubusercontent.com/22232100/52334944-e8881d80-2a22-11e9-8c76-4ea3cfeb0a12.png)

**Comment by prashant-webkul** [comment]
Hey @odoogit please read the readme.md file of this repository and check the requirements and the versions against them. Make sure you have got right versions also.

**Comment by odoogit** [comment]
@prashant-webkul i resolve this issue where you use ->json so i convert into ->text 
because my MariaDB 10.1.28 & it's not supported json formate ....
i convert json to text it's resolve my issue ..
but not check in future it's give me error or not  ...

**Comment by yaser-alazem** [comment]
@odoogit where exactly did you change the json to text ? in which directory ?

**Comment by prashant-webkul** [comment]
> @odoogit where exactly did you change the json to text ? in which directory ?

Check out the migrations we have used json columns in few. Changing them to text will make your way into Bagisto.
Also I recommend you to upgrade your DB versions to the requirements. It will automatically solve this type of issue.
