### ISSUE TITLE
Showing error on wrong field while using country type field in case of required.

### ISSUE THREAD

**Issue by vivek-webkul** [bagisto/bagisto#553]
- 1) If you used any form fields just before the country type field, then you will get the required field issue on the field which is used just before country field, only if you didn't provide the required value for country field.
- 2) There is one extra double quote in **data-vv-as custom attribute** in:
 bagisto/packages/Webkul/Admin/src/Resources/views/configuration/**field-type.blade.php**

![configuration](https://user-images.githubusercontent.com/28401696/52340431-c21fad80-2a35-11e9-92f4-c47a3f21bb76.jpg)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot 21](https://user-images.githubusercontent.com/45203177/52900503-7f6f8980-321c-11e9-87a0-0612523b4b85.png)
