### ISSUE TITLE
there should be an cross icon  in blisss theme so that customer can delete product from cart 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5530]
## Bagisto Version
- [ ] master branch

## Steps To Reproduce

1. login as customer

2.  click on add to cart 

##Actual result#

![Screenshot from 2022-01-04 16-19-03](https://user-images.githubusercontent.com/96044834/148051433-16de9824-266d-4dba-9a07-ee43ae2c9911.png)

## Expected Result

![Screenshot from 2022-01-04 16-08-15](https://user-images.githubusercontent.com/96044834/148051460-c2fb5e5e-02b7-4e6d-aa80-427564344750.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this enhancement **is done**. so I am **closing** this enhancement.
And I have attached a screenshot [Here](https://prnt.sc/VZYwrfgxmJNP) for future reference.
