### ISSUE TITLE
there should be not any blank space in gender it may contain select gender 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5531]
## Bagisto Version
- [ ] master branch

## Steps To Reproduce

1. go to customers in admin panel 

## Actual Result
![Screenshot from 2022-01-04 17-16-10](https://user-images.githubusercontent.com/96044834/148055120-7035add1-62c8-4092-ac87-f26e51442952.png)

**Comment by singhgagan03** [comment]
@devansh-webkul  same issue in velocity theme in customer profile

https://user-images.githubusercontent.com/96044834/149732535-ce459d32-cb24-4585-9740-841943055381.mp4

**Comment by devansh-webkul** [comment]
@singhgagan03,

Mentioned changes has been done.

**Comment by singhgagan03** [comment]
@devansh-webkul  please look at in bliss theme 
https://prnt.sc/26g3789

**Comment by devansh-webkul** [comment]
Ok checking.
