### ISSUE TITLE
when we add characters in date of birth it  not show any error message 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5533]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce
 1. go to the admin panel 
2. then customers 

## Actual Result

![Screenshot from 2022-01-04 17-28-06](https://user-images.githubusercontent.com/96044834/148057493-7f7c509b-ba1d-45b3-9989-dda55ad4496d.png)

**Comment by devansh-webkul** [comment]
No need for an error message here as invalid characters automatically get deleted.
