### ISSUE TITLE
It would be nice if .env.testing is out of version control

### ISSUE THREAD

**Issue by derMart** [bagisto/bagisto#5535]
Hi,

currently .env.testing file is inside version control. That is not so nice, as it is a configuration file which needs to be changed for every checked out project.
As done with .env.example, I would propose to create a .env.testing.example in version control, and remove .env.testing from version control.
It should be documented to copy .env.testing.example to .env.testing (just like it has to be done for .env.example) and set the values accordingly. The initial copy may also be automated by the bagisto installation script.

best
Martin

**Comment by devansh-webkul** [comment]
I also have the same feeling because I also have to do changes again and again before pushing. I will manage it later.

**Comment by devansh-webkul** [comment]
No need for another example file. I have used the same default example file which is provided by Laravel.
