### ISSUE TITLE
There is a translation issue on the Datagrid of the admin panel

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5541]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** log in as an admin.
**2.** change the app locale 
**3.** Click on products inside catalog
**4.** Select any value from the per-page item dropdown.

**Expected result:** There should not any translation issue on the Datagrid of the admin panel

**Actual result:** There is a translation issue on the Datagrid of the admin panel. Please find the screenshot [Here](https://prnt.sc/263mecv)

**Comment by devansh-webkul** [comment]
Linking here,
https://github.com/bagisto/bagisto/issues/5292

As all Datagrid related issues can be solved at once.
