### ISSUE TITLE
navigation sliders not work properly 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5545]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce
1. go to front page of admin panel 

## Actual Result

https://user-images.githubusercontent.com/96044834/148230784-03c4f26f-6b2e-49f4-b43a-a49b8f86965f.mp4

**Comment by singhgagan03** [comment]
navigation sliders also not working in mobile view 


https://user-images.githubusercontent.com/96044834/149316131-0431684b-fdac-4a09-bcc1-91945be1a74d.mp4

**Comment by deepaksinghgusain227** [comment]
[
![category](https://user-images.githubusercontent.com/69623394/149949202-92e1e133-36eb-4064-aee2-7fab0380991f.png)
](url)

**Comment by Sanjaybhattwebkul** [comment]
@deepaksinghgusain227 
Now, this **issue is fixed**. so i am **closing** this issue.
And i have attached a screen recording for future reference [Here](https://www.awesomescreenshot.com/video/6958491?key=6d00667412515c9ffeb5bdb318ef9b4f)
