### ISSUE TITLE
Negative numbers and zero is not required in filter for Id.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#555]
Framework Version: 0.1.4
![screenshot 4](https://user-images.githubusercontent.com/45203177/52463059-83a40300-2b9b-11e9-8574-3b53b7ac3b38.png)
![screenshot 5](https://user-images.githubusercontent.com/45203177/52463067-8a327a80-2b9b-11e9-81e7-c3e3d416d911.png)

**Comment by prashant-webkul** [comment]
This issue had been fixed in the commit https://github.com/prashant-webkul/bagisto/commit/cd6d6c89a87da07e5abcb32ccec940cca51fe0ca and changes will actually reflect in next update of the release that is going to happen next week.
