### ISSUE TITLE
There should be an option to delete all addresses at a time.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5550]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** log in as a user.
**2.** Click on the address inside the profile tab
**3.** Try to delete all addresses at a time.

**Expected result:** There should be an option to delete all addresses at a time.

**Actual result:** There is no option to delete all addresses from the user panel. Please find the below screenshot.

![delte-address](https://user-images.githubusercontent.com/86394952/148367634-2a3fa60c-8965-4553-95a0-aab32f1f3d08.png)

**Comment by ghermans** [comment]
I understand that this feature can be useful however it should be optional as some companies will not allow you to change the primary address information because they want to do some validation first.

**Comment by jitendra-webkul** [comment]
I don't think there is a need for a Delete All button because one customer can only have 5-6 addresses max. In any situation, if they will delete one or maybe 2 addresses at a time for that reason this feature is not required.
