### ISSUE TITLE
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#5556]
# Bug Report

## Issue Description

When  compiling  the assets it returns deprecation warnings

## Bagisto Version

- [X] master branch

## Actual Result

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($toggleLine, 2) or calc($toggleLine / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
57 │       top: #{$toggleSize - $toggleLine / 2};
   │                            ^^^^^^^^^^^^^^^
   ╵
    src/Resources/assets/sass/partials/_mobile.scss 57:28  @import
    stdin 12:9                                             root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($offset, 1.5) or calc($offset / 1.5)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
67 │       box-shadow: 0 #{$offset / 1.5} 0 0 $toggleColor;
   │                       ^^^^^^^^^^^^^
   ╵
    src/Resources/assets/sass/partials/_mobile.scss 67:23  @import
    stdin 12:9                                             root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$offset, 1.5) or calc(-$offset / 1.5)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
71 │       box-shadow: 0 #{-$offset / 1.5} 0 0 $toggleColor;
   │                       ^^^^^^^^^^^^^^
   ╵
    src/Resources/assets/sass/partials/_mobile.scss 71:23  @import
    stdin 12:9                                             root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($toggleLine, 2) or calc($toggleLine / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
57 │       top: #{$toggleSize - $toggleLine / 2};
   │                            ^^^^^^^^^^^^^^^
   ╵
    src/Resources/assets/sass/partials/_mobile.scss 57:28  @import
    stdin 12:9                                             root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($offset, 1.5) or calc($offset / 1.5)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
67 │       box-shadow: 0 #{$offset / 1.5} 0 0 $toggleColor;
   │                       ^^^^^^^^^^^^^
   ╵
    src/Resources/assets/sass/partials/_mobile.scss 67:23  @import
    stdin 12:9                                             root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$offset, 1.5) or calc(-$offset / 1.5)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
71 │       box-shadow: 0 #{-$offset / 1.5} 0 0 $toggleColor;
   │                       ^^^^^^^^^^^^^^
   ╵
    src/Resources/assets/sass/partials/_mobile.scss 71:23  @import
    stdin 12:9                                             root stylesheet

**Comment by deepaksinghgusain227** [comment]
ok sir  i am wroking on this issue.
