### ISSUE TITLE
Getting Incorrect Grandtotal and delivery charge at checkout page if currency use is other than default.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#556]
Framework Version: 0.1.4
Test Steps:
1. Create another currency and add a currency rate for that.
2. On frontend select the currency that you have created and place order for the product.
3. Check the delivery charges and Grandtotal.

![screenshot 7](https://user-images.githubusercontent.com/45203177/52466423-3ed29900-2ba8-11e9-89ee-c421f703a155.png)

**Comment by prashant-webkul** [comment]
Make sure that you have used the exchange rate for the other currency that you are using, other wise no totals will be seen right.

**Comment by Jyoti-Singh1** [comment]
I have used the exchange rate for other currency

**Comment by prashant-webkul** [comment]
Ok, this issue had been assigned to @jitendra-webkul  he will surely look up into it.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot from 2019-02-16 20-36-58](https://user-images.githubusercontent.com/45203177/52901521-b351ab80-322a-11e9-9ec3-bc47b8e3f8cf.png)
