### ISSUE TITLE
Set a default exchange rate as 1 for default currency.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#557]
Framework Version: 0.1.4
If exchange rate is not set for default currency then price of product changes according to other exchange rates.
Test Step:
1. Create a new currency.
2. Create a exchange rate for this currency.
3. Select USD as default currency in Channel.
4. Check the product price on store front.
Result:It changes according to newly created exchanges rate for other currency

![screenshot 8](https://user-images.githubusercontent.com/45203177/52467005-08961900-2baa-11e9-9819-929275c045be.png)
![screenshot 9](https://user-images.githubusercontent.com/45203177/52467015-0c29a000-2baa-11e9-9634-419c654a6c09.png)
![screenshot 10](https://user-images.githubusercontent.com/45203177/52467020-0fbd2700-2baa-11e9-8255-a056845c20fa.png)

**Comment by jitendra-webkul** [comment]
This is not an issue, exchange rate  "USD" to "fre" is 10. On front, it is showing converted price.
