### ISSUE TITLE
ui issue in compare page 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5570]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce
1. go to compare page in velocity 

## Actual Result

![compare](https://user-images.githubusercontent.com/96044834/148727919-42579e6f-db98-4237-b911-113e9de84c40.png)

## Expected Result
![raise](https://user-images.githubusercontent.com/96044834/148730167-ba39675c-3796-45f0-9e89-57b3930bb96d.png)

**Comment by devansh-webkul** [comment]
Not needed here as that portion is breakable text.
