### ISSUE TITLE
there should be an icon of calender in velocity profile page of customer  

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5571]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go in profile page of velocity 
2. edit profile 

## Actual Result

![icon1](https://user-images.githubusercontent.com/96044834/148731056-bb100977-79b1-4d4c-bb20-92331767c9ca.png)

## Expected Result
![icon](https://user-images.githubusercontent.com/96044834/148731079-f7f1516c-64fd-472e-9578-c7c2138fd19a.png

**Comment by devansh-webkul** [comment]
Date component is part UI, which may get overrode also. I am assuming.
