### ISSUE TITLE
multiple  messages appear when we compare the  product 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5573]
## Bagisto Version
- [ ] master branch

## Steps To Reproduce
1 go to frond end 
2. try to compare the any  product  

## Actual Result

![compare1](https://user-images.githubusercontent.com/96044834/148736317-91e8c940-f983-4756-bca1-c72655945b1e.png)

**Comment by devansh-webkul** [comment]
This is not a bug, you clicked multiple times for each request then it gave the message. If you clicked a single time and got all these messages then it's a bug.
