### ISSUE TITLE
ui issue in when we select channel in product

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5574]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce
1. go to catalog section 

2. add a product -> then channels

## Actual Result

![channel](https://user-images.githubusercontent.com/96044834/148756315-b7b56e76-b775-4a57-9987-d9c9f260fd3f.png)

**Comment by singhgagan03** [comment]
@ghermans the issue is find in cart rule in customer groups 
![1](https://user-images.githubusercontent.com/96044834/151740117-3efda87f-e045-4cb5-aa94-1aa5d0058624.png)

**Comment by singhgagan03** [comment]
@ghermans  the issue also in settings ->channels 

![-1](https://user-images.githubusercontent.com/96044834/151740356-4a8dc9ac-0788-49fa-9f00-81116ddba155.png)


https://prnt.sc/26m74wp

**Comment by ghermans** [comment]
@deepaksinghgusain227 can you verify this?
