### ISSUE TITLE
by default price attribute is selected in category 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5575]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce
1. go to category 

2. add a new category 

## Actual Result
![category](https://user-images.githubusercontent.com/96044834/148761932-7f419230-7584-4858-ad38-af25685219f6.png)

**Comment by devansh-webkul** [comment]
It's not a by default, it is the first item that is selected and the attribute is a required field.
