### ISSUE TITLE
colour changes in  mobile view of admin panel 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5576]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce
1. go to catelog in admin panel

## Actual Result

https://user-images.githubusercontent.com/96044834/148765027-934a1d79-04dc-489a-b14b-6773b9957ce2.mp4

**Comment by shreshth3142857** [comment]
Can you please elaborate the problem?

**Comment by deepaksinghgusain227** [comment]
this issue is comming on updated crome vesion due to some changes in default setting. Please check the firefox it's working fine.
