### ISSUE TITLE
there should be logo of admin in dekstop view like mobile view 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5581]
## Bagisto Version

- [ ] master branch

## Actual Result
![logo](https://user-images.githubusercontent.com/96044834/148909443-b6933437-2fb2-4b21-abb1-5f2e2da55603.png)

## Expected Result
![logo1](https://user-images.githubusercontent.com/96044834/148909505-0cbee46c-9628-4e94-8526-81b411817fc8.png)

**Comment by Sanjaybhattwebkul** [comment]
@deepaksinghgusain227 
**Thanks**, now this issue **is fixed**. so i am **closing** this issue.
And i have attached a screenshot for future reference [Here](https://prnt.sc/26gptio)
