### ISSUE TITLE
filters should not attach with heading in category 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5585]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce
1. go to catalog 
2. then category 

## Actual Result

![14](https://user-images.githubusercontent.com/96044834/148940471-65a5e980-d5d1-4ac2-b3a0-a89e81a20bfe.png)

## mobile view 

![15](https://user-images.githubusercontent.com/96044834/148940493-fbca7f30-5714-4d3f-923b-eced21478b11.png)

## Expected Result

![16](https://user-images.githubusercontent.com/96044834/148940806-e4fec0f1-5e4f-4df5-9c83-01468848c5c0.png)

![17](https://user-images.githubusercontent.com/96044834/148940843-db270c75-ae07-4f9c-b1cf-10566c284a4f.png)

**Comment by deepaksinghgusain227** [comment]
@singhgagan03  Please take a master pull and test again.
![Uploading category.png…]()

**Comment by deepaksinghgusain227** [comment]
@singhgagan03  Please take a master pull and test again.

**Comment by deepaksinghgusain227** [comment]
![category](https://user-images.githubusercontent.com/69623394/149949496-f17ce59c-99dd-4917-b23d-b1448579a5ef.png)

**Comment by singhgagan03** [comment]
@deepaksinghgusain227  working fine now 

![g](https://user-images.githubusercontent.com/96044834/150070143-7d090715-e351-4b13-9ea4-086cfed1d9a3.png)
