### ISSUE TITLE
images in 1.3.1 keep showing itself in weird sizes

### ISSUE THREAD

**Issue by mikeyapina** [bagisto/bagisto#5586]
This has been so bad that I finally had to issue this CSS to name it look ok

also after all the images didn't (meaning they always seem out of focus or in the wrong shape). I could tell it was a problem with bootstrap. I added this css fix and it worked and I finally got it to work by adding this to the panel ... / fit images to container /
.container img {
max-width: 100%;
height: auto;
}

# Bug Report

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [x] 1.3.1
- [ ] 1.3.0

**Comment by devansh-webkul** [comment]
Please verify this with master version.

**Comment by mikeyapina** [comment]
This makes no sense?

**Comment by devansh-webkul** [comment]
We have fixed certain issues in version 1.3.3 and you can try with version 1.3.3.

**Comment by mikeyapina** [comment]
Yes, I have to use 1.3.1 because dropship does not work in 1.3.3
