### ISSUE TITLE
Buy Now Issue on Demo 

### ISSUE THREAD

**Issue by ersaurav36** [bagisto/bagisto#560]
Upon Clicking Buy Now, error page is coming . Check this link: https://demo.bagisto.com/marketplace-203-122-41-218/buynow/20

![sdsdvsdvfe](https://user-images.githubusercontent.com/32482149/52554534-26af8380-2e0d-11e9-8439-2d52ba4641a8.png)
![dfsdfe](https://user-images.githubusercontent.com/32482149/52554544-2f07be80-2e0d-11e9-8600-c9cef5018979.png)

**Comment by jitendra-webkul** [comment]
This issue is related to  Multivendor Marketplace module.
