### ISSUE TITLE
there should be an enhacement so that languages is not with locale heading 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5617]
## Bagisto Version

- [ ] master branch

## Actual Result

![18](https://user-images.githubusercontent.com/96044834/149507786-1e977e67-3845-4bb1-ac36-4e301512b5aa.png)

**Comment by deepaksinghgusain227** [comment]
here the lang show that this is the current locale of admin dashboard.

**Comment by ghermans** [comment]
@deepaksinghgusain227 the locale icon should be placed in the topnavbar next to the store & notifications icon

**Comment by deepaksinghgusain227** [comment]
@ghermans  Please tell me in mobile view locale should be in navigation bar or not.
