### ISSUE TITLE
there should be enhacement in button  colour so that it should be according to mode

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5620]
## Bagisto Version

- [ ] master branch

## Actual Result
![20](https://user-images.githubusercontent.com/96044834/149512997-c7b3bbc8-9694-44c3-b1b7-64c8a46ab358.png)

**Comment by Sanjaybhattwebkul** [comment]
@deepaksinghgusain227 
**Thanks**, now this  **issue is fixed.** so i am **closing** this issue.
And i have attached a screenshot for future reference.
![ss-deepak-one](https://user-images.githubusercontent.com/86394952/150330876-017ddf5e-14e5-403a-8105-5c8bbc1f9271.png)
