### ISSUE TITLE
The price filter is not working properly

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5623]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a user.
**2.** Add some simple products from admin panel
**3.** Search product by category.
**4.** Try to filter the products by price filter..

**Expected result:** The price filter should be work properly.

**Actual result:** The price filter is not working properly. Please find the screenshot [Here](https://prnt.sc/26ekeq3)

**Comment by devansh-webkul** [comment]
Hi @Sanjaybhattwebkul,

Please share the full steps.

How you reproduce, which product you have added.

**Comment by devansh-webkul** [comment]
It's working fine and I am not able to reproduce this.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
Please find the screen recording **[Here](https://www.awesomescreenshot.com/video/6878918?key=2651052d2e8915cab9ef3f30657dd5ad)** to reproduce this issue
