### ISSUE TITLE
newsletter email not working in demo

### ISSUE THREAD

**Issue by nationsahil** [bagisto/bagisto#5626]
# Bug Report

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Actual Result

Error! Error! Mail can not be sent currently, please try again later..

## Expected Result

email should be added

**Comment by devansh-webkul** [comment]
Maybe email quota limits get over or email driver configuration got missing. We will fix this.

Thanks for reporting this.

**Comment by devansh-webkul** [comment]
The email issue has been fixed.
