### ISSUE TITLE
New Left-Menu Issue - Not able to create direct menu item instead of nested menu

### ISSUE THREAD

**Issue by suyashcyber94** [bagisto/bagisto#5630]
# Bug Report
I have a custom module that does not have a nested menu but instead opens directly from the main menu item. It is working fine until 1.3.3 but as I fetched new updates from the master, I got the new menu with it with breaking changes

## Issue Description
As checked in menu generation code, It found to be hard-coded that only the dashboard will have a direct link

## Bagisto Version
- [x] master branch (This one)
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce
Menu Config:
return [
    [
        'key' => 'customModule',
        'name' => 'Custom Module',
        'route' => 'custom.admin.index',
        'sort' => 2,
        'icon-class' => 'any-icon',
    ]
];

## Expected Result
It is supposed to be dynamic as it is previously, all menu hierarchy was created by menu config.

**Comment by devansh-webkul** [comment]
Hi @suyashcyber94,

Currently, the master version is unstable due to the new admin UI theme and we are working on this.

I recommend you to not use master currently.
