### ISSUE TITLE
Error .env DB_PREFIX with underscore

### ISSUE THREAD

**Issue by donny26utama** [bagisto/bagisto#5631]
in .env file setup database configuration 
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=bagisto_ecommerce
DB_USERNAME=dbuser
DB_PASSWORD=dbpass
DB_PREFIX=bg_
```
go to console, then run `php artisan migrate`
result
```
The environment file is invalid!
Failed to parse dotenv file due to some invalid values. Failed at [bg_].
```

how to solve this? thanks before.

**Comment by devansh-webkul** [comment]
Thanks,

Actually, Laravel does not provide a DB prefix from the `.env`.,
https://github.com/laravel/laravel/blob/8d08717f15d1bddf3d28124b928ccc3a5cfdf84b/config/database.php#L57

So if you have something like this then I will recommend you to directly place it in the config file.

**Comment by donnyatabitech** [comment]
So, if we use web installer, can we use underscore to database prefix?
![image](https://user-images.githubusercontent.com/94879656/150307359-6273cae7-1b8d-4f91-9292-fca5ec4b4f87.png)
I have tried, and not working. I think from web installer has same problem. Because you will overwrite `.env` file with input from web installer. CMIIW

**Comment by donnyatabitech** [comment]
https://github.com/bagisto/bagisto/blob/69eff9dbdd55841e799b94c4a4fc47b0381f3884/config/database.php#L41
https://github.com/bagisto/bagisto/blob/69eff9dbdd55841e799b94c4a4fc47b0381f3884/config/database.php#L54
https://github.com/bagisto/bagisto/blob/69eff9dbdd55841e799b94c4a4fc47b0381f3884/config/database.php#L67

on `config/database.php`

**Comment by devansh-webkul** [comment]
Yeah, I know that may at the time of giving support we haven't been aware of this. That's why I recommend you to change in the config directly.

**Comment by devansh-webkul** [comment]
I detected the issue, will provide PR soon.

**Comment by devansh-webkul** [comment]
Hi @donny26utama,

Thanks for reporting this. And sorry for bothering you as I didn't check the core one.

I have fixed the issue.

**Comment by donny26utama** [comment]
Wow, you have made it. Super thankful for you @devansh-webkul . Nice job sir.
