### ISSUE TITLE
textbox margin colour issue in search bar in mobile view 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5632]
## Bagisto Version
- [ ] master branch
-
## Steps To Reproduce
1. go to search bar in velocity in mobile view 

## Actual Result
![-4](https://user-images.githubusercontent.com/96044834/149875370-6018f337-6d90-475a-8bcd-7c2e2000432b.png)

**Comment by devansh-webkul** [comment]
It's mostly negligible as margins in most of the devices are equal. So no need any change here.
