### ISSUE TITLE
there is a huge gap between products and add to cart in bliss theme  in mobile view 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5634]
## Bagisto Version
- [ ] master branch

## Steps To Reproduce
1.  go to bliss theme home page

## Actual Result

![-1](https://user-images.githubusercontent.com/96044834/149884228-3a871e0d-3cca-4a5a-a39a-e1cf0528d725.png)

**Comment by devansh-webkul** [comment]
Spaces are reserved for CLS. So no need for any changes here.
