### ISSUE TITLE
Right Problems: #1267 - Unerlaubte Mischung von Sortierreihenfolgen (utf8mb4_general_ci, COERCIBLE) und (utf8mb4_unicode_ci, COERCIBLE)

### ISSUE THREAD

**Issue by xedex1111** [bagisto/bagisto#5643]
# Bug Report

hi. if i try to set the permission or create a new user for the new database i get that error. i think the problem is the mix of information_shema, mysql, performance_shema, phpmyadmin Collection between utf8 and utf8mb4. please help how to solve that smart, thx

![fail_mysql_1](https://user-images.githubusercontent.com/51515279/149936000-2e6a5adb-536c-436a-ae7c-e1d1a946cf81.PNG)
![fail_mysql_2](https://user-images.githubusercontent.com/51515279/149936002-b9b8d266-80ab-4406-836f-0707bde9a5f1.PNG)
![fail_mysql_3](https://user-images.githubusercontent.com/51515279/149936004-e5930d28-6618-4068-a971-4970c64ce838.PNG)

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

**Comment by devansh-webkul** [comment]
Currently, we are only using the `utf8_unicode_ci` collation. So I suggest you to try with that database.

**Comment by xedex1111** [comment]
@devansh-webkul i did but its still the same error if i click under rights on the menü panel to create an new user for that database. my pj_main as exmple has the utf8_unicode_ci settings.

**Comment by devansh-webkul** [comment]
Just try to alter the default collation to `utf8_unicode_ci`.

**Comment by xedex1111** [comment]
@devansh-webkul you mean under (see picture) and not the shema and co tables. ok great thx it works. 
![fail_mysql_4](https://user-images.githubusercontent.com/51515279/149944193-1c063a3e-06b6-4b70-b4c0-3d774e26ab49.PNG)
