### ISSUE TITLE
wishlist and compare button  not properly allign  we search any product 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5651]
## Bagisto Version
- [ ] master branch

## Steps To Reproduce
1. go to velocity and search any product 

## Actual Result

https://user-images.githubusercontent.com/96044834/150078936-ba45235f-b22f-4e2f-873e-6ee9eaf34c6c.mp4

**Comment by singhgagan03** [comment]
same issue in mobile view 

![-1](https://user-images.githubusercontent.com/96044834/150079459-d9f1b239-c19b-4b95-9750-378a7b362465.png)

**Comment by devansh-webkul** [comment]
The card is bigger on the search and category page and that aligned correctly.
