### ISSUE TITLE
 delete button should be properly allign  in mobile view in compare page(blisss theme)

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5652]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce
1  go to compare page in blisss theme 

## Actual Result

![2](https://user-images.githubusercontent.com/96044834/150081566-cce3b8fc-c18a-4081-8e6c-dc19305e6637.png)

expected result

![-1](https://user-images.githubusercontent.com/96044834/150081913-c6b13a93-4792-4f71-8548-b50680b0d2cc.png)

**Comment by deepaksinghgusain227** [comment]
this is not a issue please check once again.

**Comment by deepaksinghgusain227** [comment]
![compare-delete](https://user-images.githubusercontent.com/69623394/150510569-d802c5ec-0cf1-4d3f-ab04-3c1edd2fbd89.png)
