### ISSUE TITLE
Only unread notification should be shown in the notification modal box.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5654]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** log in as a user.
**2.** Create a order from user panel
**3.** -Login as admin
**4.** Click on notification icon.
**5.** Click on all notification / mark as read.
**6.** Again click on the notification icon.

**Expected result:** The message that has been read should not show in the notification modal box.

**Actual result:** The message that has been read are showing in the notification modal box. Please find the screenshot [Here](https://prnt.sc/26fnul9).

**Comment by devansh-webkul** [comment]
I think the clear notification feature is good in this case. I just saw in most of the mobile apps to clear the notifications.

In this way, the database should also get cleaned up by the admin.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this **issue is fixed.** so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/CKUzNAvGIEsF). for future reference
