### ISSUE TITLE
ui issue in  customer  order view page in blisss theme in mobile view 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5661]
## Bagisto Version
- [ ] master branch

## Steps To Reproduce

go to customer profile page 

## Actual Result

![1](https://user-images.githubusercontent.com/96044834/150296425-79b762a2-ce17-4657-b064-4e1762361a4f.png)

**Comment by deepaksinghgusain227** [comment]
Please check this is working fine.

**Comment by deepaksinghgusain227** [comment]
![Uploading order-default-ui.png…]()

**Comment by deepaksinghgusain227** [comment]
![order-default-ui](https://user-images.githubusercontent.com/69623394/150482909-8c54d0c7-e7cb-4ab7-8b27-f24499319876.png)
