### ISSUE TITLE
By default the first submenu should be open, when the admin is clicking on any tab

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5671]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** log in as a admin
**2.** Click on dashboard
**3.** Click on sales
**4.** Click on catalog
**5.** Click on customer

**Expected result:** By default the first submenu should be open, when we are clicking on any tab

**Actual result:** Not any page is opening when the admin is clicking on any tab. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/6957062?key=5e3c8115403ba3888fbdfd87fc448b7c)

**Comment by devansh-webkul** [comment]
@ghermans,

Can you verify this with @deepaksinghgusain227?
