### ISSUE TITLE
PayPal Smart Button crashes in checkout with a js error 

### ISSUE THREAD

**Issue by sanaullah1985** [bagisto/bagisto#5672]
## Issue Description
PayPal Smart Button crashes in checkout with a js error. "Place Order" button does not show as a result.
## Preconditions
Enable PayPal Smart Button from bagisto backend.

## Bagisto Version
- [ ] master branch
- v1.3.1
- v1.3.3

## Steps To Reproduce
Enable paypal from bagisto backend. Go to checkout in frontend and select "Paypal smart button". On preview "Place order" button will not show. If you check console you will see this error "ReferenceError: Cannot access 'options' beforeinitialization in velocity-core.js:1"

## Actual Result
"Place order" button does not show.

## Expected Result
"Place order" button should show.

**Comment by devansh-webkul** [comment]
Hi there,

You need to add the `client-id` and `client-secret` keys in the admin panel.
