### ISSUE TITLE
dropdown buttons is not working properly in admin panel 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5696]
## Bagisto Version
- [ ] master branch

## Steps To Reproduce

1. go to admin panel 

## Actual Result

https://user-images.githubusercontent.com/96044834/151296804-45296d86-b668-4d5d-b3ef-e963c6496e09.mp4

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
**Thanks**, now this **issue is fixed**. so I am **closing** this issue.
And I have attached a screen recording for future reference [Here](https://www.awesomescreenshot.com/video/7648894?key=d52278d0e1ae46aca6e15619f62ba9a0)
