### ISSUE TITLE
side bar navigation not work properly in mobile view in admin panel 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5700]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to admin panel 

## Actual Result

https://prnt.sc/26k0ux5

**Comment by Sanjaybhattwebkul** [comment]
@ghermans  @prashant-webkul 
This is **not an issue** so I am **closing** this issue.
Please fine the **screenshot** [Here](https://prnt.sc/EPfCXO28pfb7)
