### ISSUE TITLE
ui issue when we try to edit the product in admin panel (mobile view)

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5702]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1.  go to products in catelog 
2.  then try  to edit the product 

## Actual Result
![1](https://user-images.githubusercontent.com/96044834/151490172-57f385eb-e63d-407a-9e90-0ba7d2ff755b.png)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul  @ghermans 
There is **no  UI issue on mobile view**. Please find the **screenshot [Here](https://prnt.sc/ZMjfrjvlKpfO)**
