### ISSUE TITLE
star ratings alligment should be in same line  in mobile view 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5703]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to reviews in profile section 

## Actual Result

![1](https://user-images.githubusercontent.com/96044834/151490573-b5152909-ecbc-469c-850d-39520c7ca8ad.png)

## Expected Result
https://prnt.sc/26kjgg2

**Comment by devansh-webkul** [comment]
This is not an issue star are wrapped when the width is below 360px.

**Comment by devansh-webkul** [comment]
All I can do is just reduce the star font if still want it in the same line.

**Comment by Sanjaybhattwebkul** [comment]
@deepaksinghgusain227 
**Thanks**, now **this issue is fixed**. so I am **closing** this issue. 
And I have attached a screenshot for future reference [Here](https://prnt.sc/26w4m0r)
