### ISSUE TITLE
proper  alligment should be done in order page (mobile view)

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5708]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to profile -> then orders in blisss theme 

## Actual Result

![1](https://user-images.githubusercontent.com/96044834/151506204-1d5897cc-e96c-4258-b394-e84fdd0787bd.png)

**Comment by deepaksinghgusain227** [comment]
This issue is fixed at PR - https://github.com/bagisto/bagisto/pull/5739
