### ISSUE TITLE
Wrong error messages when uploading video

### ISSUE THREAD

**Issue by dev-einn** [bagisto/bagisto#5709]
Not able to add video(s) while creating/editing product on your demo and on our configured environment of v1.3.3 .
I am attaching the bug screenshot from your demo only, please resolve this as soon as possible.
I have created the product and attached the video of size 626.6 kB 

![Screenshot from 2022-01-28 13-53-00](https://user-images.githubusercontent.com/72020482/151512561-6fd31a23-b1ec-4f16-b849-628e8acc0c4b.png)

**Comment by devansh-webkul** [comment]
Please fill full issue format and provide us with the steps also (and what video type you added). So that we can verify.

**Comment by dev-einn** [comment]
I have edited one simple product in which I have attached mp4 type video but on clicking save button it is showing the error - **"The video1 must be a file type of: mov, mp4 "** as you can see in the screenshot

**Comment by devansh-webkul** [comment]
I tested with MP4 video and it's getting saved.

**Comment by dev-einn** [comment]
Have you checked this on your demo too ?

**Comment by devansh-webkul** [comment]
Yes working fine,

![Screenshot](https://user-images.githubusercontent.com/68321766/151542172-0d568f6d-3d78-416d-8367-5cb37b501aa7.png)

**Comment by dev-einn** [comment]
I am attaching the video of the bug in your demo. Please check it and let me know.
**Video Link :-** https://www.loom.com/share/f6eacfa4b4364aceb82a0d447aae5ef4

**Comment by devansh-webkul** [comment]
Can you share that video?

**Comment by dev-einn** [comment]
Please click on the link.

**Comment by devansh-webkul** [comment]
Can you try with a different video may be error message is wrong because I am not able to reproduce this in both environment.

**Comment by dev-einn** [comment]
Yes, it is working with another video but you should change the error message. It is not showing right message

**Comment by devansh-webkul** [comment]
Alright, I will check this.

**Comment by devansh-webkul** [comment]
Hi, thanks!

Can you please update the issue with all the steps?

**Comment by dev-einn** [comment]
This error was produced on version 1.3.3 demo.
Steps to reproduce :-

1. Go to admin panel
2. Go to catalog
3. Edit the product and attach the video 
4. Click on save button
5. And then the error message will display

I am attaching the video file for which I was facing the issue.

https://user-images.githubusercontent.com/72020482/151546321-78ecbcfd-d384-4ca0-abbc-0f35c75ee404.mp4
