### ISSUE TITLE
Can't able to view the downloadable products in mobikul application

### ISSUE THREAD

**Issue by dev-einn** [bagisto/bagisto#5710]
I have created one Downloadable product in the demo but unable to view product detail screen for that product in the Mobile Application of demo.
I am attaching the screenshot here.

![WhatsApp Image 2022-01-28 at 1 59 45 PM](https://user-images.githubusercontent.com/72020482/151513929-f304edd0-6b4f-486d-994c-29e1ff1fa4d1.jpeg)

**Comment by devansh-webkul** [comment]
I am not getting it. Are you getting issues on the web or creating a new mobile app by using API.

**Comment by dev-einn** [comment]
I have created one downloadable product on website demo ( https://bagisto.com/en/laravel-ecommerce-app/ ) which is also connected with mobile app then I have searched the product and click on it to view the product detail screen of that product to checkout through Mobile App but after clicking on the product error displayed on the screen for which I have attached the screenshot

**Comment by ghermans** [comment]
@naresh-webkul can you verify this please?

**Comment by devansh-webkul** [comment]
On the web, everything seems fine, seems to be an issue at the mobile end.
