### ISSUE TITLE
Marketing Section -> Catalog Rule is getting expired in 2 Days Even after setting the dates in months

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#5712]
**Description**
When applying the catalog rule in the marketing section and checking the product price we can see that it is working fine accordingly. But after 48 hrs we can see that the catalog rule is not working. 
We have applied the catalog rule for 3 months and still, it is getting expired.

**Bagisto Version - V1.3.3**

**Steps To Reproduce**
**1.** Add catalog rule from the admin-marketing section -> Set the Date for about 3 months -> Fill the details in the action.
**2.** Check the products after 48 hrs and we will be able to see that the catalog rule is not working.

**Expected Result**
The Catalog rule must be applicable till the date that the admin has set. It must not get expire after 48 hrs.

**Comment by devansh-webkul** [comment]
Hi, @ghermans and @ashishkumar-webkul,

This is not a bug, cron job needs to be run every day to reindex the price by running the command,

~~~php
php artisan product:price-rule:index
~~~
