### ISSUE TITLE
when we are try to book slots it should not take sunday as by default value i n booking product 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5720]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to catelog -> then booked products 

## Actual Result

![1](https://user-images.githubusercontent.com/96044834/151742542-fe144295-092c-463d-a78d-fa29d20caa93.png)

**Comment by devansh-webkul** [comment]
No need for this.
