### ISSUE TITLE
user is not able to update quanity in checkout cart page in veloicity theme 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5728]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. add any product then go to checkout page 

## Actual Result

https://user-images.githubusercontent.com/96044834/151921082-959cb15b-1149-4904-9cc6-aea29ad69b7d.mp4

**Comment by devansh-webkul** [comment]
@deepaksinghgusain227 

Reference Link: https://github.com/bagisto/bagisto/pull/5693

Two input elements are present in velocity due to which the second one i.e. mobile always gets the latest value.

**Comment by ghermans** [comment]
@prateek-webkul has the fix already been merged?

**Comment by prateek-webkul** [comment]
@ghermans ,

PR is still open. Not merged in master.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this issue **is fixed**. please find the screenshot [Here](https://prnt.sc/lHaNGIU56Jar).
