### ISSUE TITLE
ui issue when we are try to book only booking product in bliss theme in checkout page (mobile view )

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5729]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. try to book  booking product then go to checkout page 

## Actual Result

![1](https://user-images.githubusercontent.com/96044834/151923279-59456e00-0a2c-4ec6-b87c-1cc279d54c3e.png)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
**Thanks**, now this **issue is fixed**, so I am closing this issue.
And I have attached a screenshot for future reference [Here](https://prnt.sc/clvMFQKohbfo)
