### ISSUE TITLE
there is an option to increase quanity  when user is try to booked product in both themes 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5730]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

 1. go to front page of any booking product 

## Actual Result

![1](https://user-images.githubusercontent.com/96044834/151926147-8b84bee2-c3f9-406f-b0b2-05a013670156.png)

## Expected Result
![2](https://user-images.githubusercontent.com/96044834/151926217-fd5046d4-6b40-4f94-adb0-8e2d4743ae44.png)

**Comment by singhgagan03** [comment]
the same issue please check in  bliss theme at time of checkout  and in velocity there is option to  increase quanity at time of checkout 
![1](https://user-images.githubusercontent.com/96044834/151926672-2905a96e-be69-4531-b957-1124f271e506.png)

**Comment by prateek-webkul** [comment]
@singhgagan03 @Sanjaybhattwebkul ,

Same issue [#5728](https://github.com/bagisto/bagisto/issues/5728)
