### ISSUE TITLE
TestDataGrid does not exist

### ISSUE THREAD

**Issue by kenng** [bagisto/bagisto#575]
Thanks for creating an ecommerce laravel, have been looking for one eternally!

Still trying to play with it but have some issue at start. 

There's error when try to do 
` php artisan route:list`

```
   ReflectionException  : Class Webkul\Admin\DataGrids\TestDataGrid does not exist

  at bagisto/vendor/laravel/framework/src/Illuminate/Container/Container.php:826
    822|
    823|             // If the class is null, it means the dependency is a string or some other
    824|             // primitive type which we can not resolve since it is not a class and
    825|             // we will just bomb out with an error since we have no-where to go.
  > 826|             $results[] = is_null($dependency->getClass())
    827|                             ? $this->resolvePrimitive($dependency)
    828|                             : $this->resolveClass($dependency);
    829|         }
    830|

  Exception trace:

  1   ReflectionParameter::getClass()
      /bagisto/vendor/laravel/framework/src/Illuminate/Container/Container.php:826

  2   Illuminate\Container\Container::resolveDependencies()
      bagisto/vendor/laravel/framework/src/Illuminate/Container/Container.php:795
```

**Comment by kenng** [comment]
I think the error happens at
`packages/Webkul/Admin/src/Http/Controllers/DataGridController.php`

```
    public function __construct(TestDataGrid $testgrid)
    {
        $this->middleware('admin');

        $this->_config = request('_config');

        $this->testgrid = $testgrid;
    }
```

**Comment by prashant-webkul** [comment]
Thank @kenng for pointing out the obselete routes came due to components testing during development.
This issue had been fixed in commit https://github.com/prashant-webkul/bagisto/commit/f68c4e482c9a40dd3bd77e2f5c520802880b062d and will surely be updated in next release or update.

**Comment by kenng** [comment]
this is out of scope for this thread, i can delete this comment later if you think it should. 
Just curious if there is plan to upgrade to laravel 5.7 soon? as it got the super nice telescope.

**Comment by kenng** [comment]
this is out of scope for this thread, i can delete this comment later if you think it should. 
Just curious if there is plan to upgrade to laravel 5.7 soon? as it got the super nice telescope.

**Comment by prashant-webkul** [comment]
Of course we will do it on Laravel 5.7 and we already know about the telescope capabilities. Till now we have relied on XDebug and Debugbar. Our first major release will have bumped up Laravel version but it may take some time.
Till then take flavors of Bagisto with Laravel 5.6

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
