### ISSUE TITLE
different button ui for simple and booking product  in compare section  in velocity 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5750]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to compare section 

## Actual Result

![0](https://user-images.githubusercontent.com/96044834/152527568-f24d995d-0063-412d-9e51-0fc3b83676ed.png)

**Comment by Sanjaybhattwebkul** [comment]
@ghermans 
This is not an issue. the button size will be according to the text
