### ISSUE TITLE
in mobile view  wishlist option is not there in checkout page 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5752]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to checkout page in velocity theme 

## Actual Result

https://user-images.githubusercontent.com/96044834/152726643-c6331c1e-31f5-4a28-b36d-fa2428c7e99c.mp4

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
**Thanks**, now this **issue is fixed**. so I am **closing** this issue. 
ANd I have attached  a screenshot for future reference [Here](https://prnt.sc/-WdkF56iBkKA)
