### ISSUE TITLE
products is not show when we click on  velocity in mobile view 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5753]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to velocity then click on any product and then go back to home page of velocity 

## Actual Result

https://user-images.githubusercontent.com/96044834/152729945-f0b6e195-0898-4630-bf39-53c8610c8cb9.mp4

**Comment by Sanjaybhattwebkul** [comment]
@ghermans  @prateek-webkul 
This is **not an issue**. Please take a reference from [Here](https://github.com/bagisto/bagisto/issues/5181)
