### ISSUE TITLE
there should be a space between update quantities in mobile view in admin panel 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5755]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. try to refund any product 

## Actual Result

![0](https://user-images.githubusercontent.com/96044834/152768822-13e95976-a093-444a-afc7-07cfcb1f4be8.png)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
Now, this issue **is fixed**. so I am **closing** this issue.
And i have attached a screenshot for future reference [Here](https://prnt.sc/K71t3Vqd25jR)
