### ISSUE TITLE
auto change local

### ISSUE THREAD

**Issue by mtrf3** [bagisto/bagisto#5757]
while in admin panel with local EN and then navigate to Velocity button, it goes to AR local (which is the default in .env)

please check the video

https://watch.screencastify.com/v/7r6HakAJVS5hjCQb7T4Q

also in tenant button

**Comment by devansh-webkul** [comment]
Hi @mtrf3,

We are not able to reproduce this.

**Comment by singhgagan03** [comment]
not getting this issue 

https://user-images.githubusercontent.com/96044834/152990294-379090e2-15c7-4f98-bb71-167d04d51f48.mp4
