### ISSUE TITLE
Tax Rates, Tax Rules, Shipping Taxes Previlidiges

### ISSUE THREAD

**Issue by derMart** [bagisto/bagisto#5758]
# Bug Report

Have a look here:

https://github.com/bagisto/bagisto/blob/c1dceb0a011df016562c3d5461be6130375e3145/packages/Webkul/Checkout/src/Cart.php#L582-L591

`$shipping->price` is the total shipping amount of the cart in total.
If the shipping method has specified `is_calculate_tax`, then each `$item->tax_amount` will contain the tax of the shipping costs as a whole (calculated with the tax_rate of the item).

To calculate cart total `tax_amount` the Tax helper then adds up all `$item->tax_amount`'s:

https://github.com/bagisto/bagisto/blob/c1dceb0a011df016562c3d5461be6130375e3145/packages/Webkul/Tax/src/Helpers/Tax.php#L73

So the cart/order `tax_amount` and `grand_total` will potentially include shipping taxes more than once.
E.g.: You have two different items in your cart, say with identical tax_rate, then you will pay twice the amount of shipping tax. But you should only pay it once.

So the calculation for the tax_amount for the order is incorrect, or did I miss someting? Btw. we can reproduce this when placing orders.

This is a conceptual problem however. Bagisto does not specify which tax_rate to use for shipping.
In some countries inside the EU shipping tax calculation for carts with different tax_rates goes like this: Total net shipping amount will be split to each item, depending on their net amount ratio with respect to total net amount of cart. Then you have a net shipping amount per item. Then, the tax for this item net shipping amount is multiplied by the tax_rate of the item to obtain gross shipping amount for this item. Add up all gross shipping amounts and you end up with gross shipping amount of total cart. Should be easily implementable with the current system, though I am not sure if all countries in the world do it like this!

Example: 
cart item 1, net price: 10 €, tax_rate: 0.2
cart item 2, net price: 20 €, tax_rate: 0.1
cart shipping_net: 10€
-> shipping_item1 -> net: 10 / 30 * 10 = 3.33€, gross: 3.33€ * 1.2 = 4€
-> shipping_item1 -> net: 20 / 30 * 10 = 6.66€, gross: 6.66€ * 1.1 = 7.33€
-> cart shipping gross: 11.33€

Also I am not sure when to round in that case...

## Bagisto Version
-  master branch

**Comment by devansh-webkul** [comment]
@derMart,

I just verified the whole scenario actual for the free shipping price is zero and for the flat shipping price is added to individual items. So tax is then calculated accordingly.

And it mostly varies from country to country, policies, and rules, etc.

Can you share the sample for the actual result and expected result. So that I can check what is best suited.

**Comment by derMart** [comment]
> Can you share the sample for the actual result and expected result. So that I can check what is best suited.

Sorry, I do not understand what you mean. Actual result currently is that the tax amount of shipping is added more than once into grand_total if you have more than one item in cart. Expected should be that the tax amount of shipping is there only once.
Example:
Assume tax_rate for all items including shipping should be 10
- cart item 1: total = 10, tax_rate: 10
- cart item 2: total = 20, tax_rate: 10
- shipping carrier returns $shipping->price = 10
  - independent of the carrier type, I understood this price to be the shipping amount of the whole cart, not just of one item (that's how flat shipping is calculating $shipping->price)

Then currently following happens (if I am not mistaken):
- cart item 1: tax_amount = (10 + 10) * 10 / 100 = 2
- cart item 2: tax_amount = (20 + 10) * 10 / 100 = 3
cart tax_amount = 5 -> that is wrong: 10% of shipping price is included twice in there, not once
cart grand_total = 10 + 20 + 10 + 5 = 35
cart net total is 10 + 20 + 10 = 30
if you apply 10% of 30 you get 33 not 35
-> cart tax amount is wrong

How you wanna fix this depends on what kind of tax calculation you like to support for shipping. That is country specific and I can not make this decision for Bagisto which countries they like to support in their tax calculation or if there is a way to design this so flexible that each user can incorporate its own shipping tax calculation.

**Comment by devansh-webkul** [comment]
All right I will check and fix this. This will take some time. Currently, you can override the behavior if you want.

I will try to make it a flexible for shipping calculations.

**Comment by devansh-webkul** [comment]
This is due to my pull request, I just added as per the flat tax rate basis,
https://github.com/bagisto/bagisto/pull/4360#pullrequestreview-555118566

And I was not aware of this I just thought tax should be added to the item price as shipping prices are individually added.

I will provide the fix for this also and will try to make it flexible also but this will take some time.

As currently bunch of issues are open which needs to be fixed as well.

**Comment by derMart** [comment]
sure, then why not add Bug label until it is fixed?

**Comment by devansh-webkul** [comment]
Yes! Because it totally varies on the basis of country policies, rules, etc.

That's why we have given enable/disable the feature so that if anything went wrong then the developer can simply disable the feature and override the core functionality.

**Comment by devansh-webkul** [comment]
I just checked and researched, this is itself a big enhancement like defining tax rules, tax classes, whether include taxes or not, etc.

I am reverting my previous pull request,
https://github.com/bagisto/bagisto/pull/4360

**Comment by jitendra-webkul** [comment]
Fixed on #9711
