### ISSUE TITLE
allignment should be done proper in calender icon in mobile view in admin panel 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5759]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to  dashboard ->then admin panel then calendor icon 

## Actual Result

![0](https://user-images.githubusercontent.com/96044834/152922882-5b686112-59f8-4910-86a4-03c0a09b1f14.png)

**Comment by Sanjaybhattwebkul** [comment]
@ghermans 
This is **not an issue.** all alignments are correct. Please find the screenshot [Here](https://prnt.sc/9BBWhquw9u23).

@prateek-webkul  Can you please verify this issue?
