### ISSUE TITLE
ui issue in category in calender icon  in mobile view 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5760]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1.  go to category section 

## Actual Result

![Screenshot from 2022-02-08 11-02-14](https://user-images.githubusercontent.com/96044834/152925061-be0f4217-e885-4fcc-b34e-e101cb027463.png)

**Comment by Sanjaybhattwebkul** [comment]
@deepaksinghgusain227  @prateek-webkul 
There is not any UI issue. Please find the screenshot [Here](https://prnt.sc/KNQGBQhOqp9V)
