### ISSUE TITLE
not able to add slider images in velocity theme 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5762]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to sliders and try to add  new sliders 

## Actual Result

https://user-images.githubusercontent.com/96044834/152937924-186a0b1b-1410-4dc9-8499-50d91dd510f8.mp4

**Comment by devansh-webkul** [comment]
Not able to reproduce this.

**Comment by devansh-webkul** [comment]
Getting issue when multiple images uploaded.
