### ISSUE TITLE
even after updating the check product marked not remove 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5763]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to product section in catalog 

## Actual Result

https://user-images.githubusercontent.com/96044834/152945089-38259a02-b6ee-40fb-9133-9b62f26d85e7.mp4

**Comment by devansh-webkul** [comment]
Fixed with this,
https://github.com/bagisto/bagisto/pull/5756
