### ISSUE TITLE
not able to select options in LTR ENGLISH

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5764]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. GO TO CATALOG 

https://user-images.githubusercontent.com/96044834/152946310-457445ef-803c-413f-94a2-5e7687936516.mp4

**Comment by prateek-webkul** [comment]
@Sanjaybhattwebkul 

Please verify this issue..

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
Change edit the ENGLISH  locale with RTL  then try to edit any 2 products by mass action.
**Please take a reference from [Here](https://prnt.sc/c4wmzcprYejH).**

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
The issue with the **Mozilla browser** only.

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
**Thanks**, now this issue **is fixed**. so I am **closing** this issue.
And I have attached a screens recording for **future reference** [Here](https://www.awesomescreenshot.com/video/7594649?key=6716a1525608830ea366c43a6c8ad6e2).
