### ISSUE TITLE
Zoomlens in product page overlap sidebar category menu

### ISSUE THREAD

**Issue by Ruchika-Chhetri** [bagisto/bagisto#5768]
# Bug Report

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

**Comment by devansh-webkul** [comment]
Hi @Ruchika-Chhetri,

Please provide full information so that we can further check.

**Comment by Anmol-Chauhan** [comment]
![Uploading Screenshot from 2022-02-09 10-03-26.png…]()

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
This **issue is fixed.** so I am **closing** this issue.
ANd I have attached a screenshot [Here](https://prnt.sc/NURQA3_H6ZyS)
