### ISSUE TITLE
Layout shifting in admin ui

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#5770]
# Bug Report
- Found layout shifting in admin panel.

## Issue Description
- Found layout shifting in admin panel.

## Bagisto Version
- [x] master branch

**Comment by devansh-webkul** [comment]
@deepaksinghgusain227,

Layout shifting found here,
![Screenshot (1)](https://user-images.githubusercontent.com/68321766/153373491-e7782643-1e08-433d-89e9-f5e6e4e7af88.png)

**Comment by deepaksinghgusain227** [comment]
ok sir i am working on this issue

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Thanks**, now this **issue is fixed.** so I am **closing** this issue.
