### ISSUE TITLE
issue in french lanugage in navigation bar 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5772]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. change locale to french 

## Actual Result

![0](https://user-images.githubusercontent.com/96044834/153121830-b9645139-12f6-4a47-82f9-10f53520cddc.png)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
**Thanks**, now this **issue is fixed.** so I am **closing** this issue.
And I have attached a screenshot for future reference [Here](https://prnt.sc/wRXjB-sr12Ov).

**Comment by Sanjaybhattwebkul** [comment]
Hi @prateek-webkul 
I am **reopening** this issue. because I am getting the **same issue again**.
Please find the screenshot [Here](https://prnt.sc/UvTnkk5JDdTM).

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Not fixed.** still **getting** the **same issue.**
Please find the screen recording [Here](https://www.awesomescreenshot.com/video/8237683?key=6907707d6243b0cc7e4a2de6b320360e).

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Thanks**, now this **issue is fixed**. so I am **closing** this issue.
And I have attached a screenshot [here](https://prnt.sc/i93_yB-q2fHZ). for future reference.
