### ISSUE TITLE
translations not working in navigation in admin panel 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5775]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to navigation bar in admin panel 

## Actual Result

![0](https://user-images.githubusercontent.com/96044834/153138385-6f1944b4-293b-4022-8570-f3b0aca185c1.png)

- [ ] same issues found in marketing
- [ ] email
- [ ]  marketing
- [ ] taxes in configuration

**Comment by Sanjaybhattwebkul** [comment]
This issue is **fixed by this [PR]( https://github.com/bagisto/bagisto/pull/5871)**
So I am **closing** this issue. And I have attached a screenshot for future [Here](https://prnt.sc/3t5H62FYGfQM)
