### ISSUE TITLE
scroll bar is not working in  arabic language 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5776]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1.  go to admin panel of bagisto 

## Actual Result

https://user-images.githubusercontent.com/96044834/153140800-7b92a069-e7a4-470b-b0df-bb5099380502.mp4

**Comment by prateek-webkul** [comment]
@Sanjaybhattwebkul ,

Please Verify this issue as working fine in my instance.

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul  @deepaksinghgusain227 
There is not an issue. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/7576089?key=0eb47d360f41d6cfac0b3ac3a3b3ffc8)
