### ISSUE TITLE
Catalog storefront configuration for per product page is not working for Marketplace extension

### ISSUE THREAD

**Issue by pushparajbhatta** [bagisto/bagisto#5796]
# Bug Report
This bug is the same as https://github.com/bagisto/bagisto/issues/3113
The bug is on multi-vendor marketplace extension. Please apply a similar fix at:
packages/Webkul/Marketplace/src/Repositories/ProductRepository.php

**Comment by prateek-webkul** [comment]
Hello @pushparajbhatta ,

Thanks for suggestion. We will be update the extension as well. And, in future release of multi-vendor marketplace, this issue will be fixed.
