### ISSUE TITLE
there should be proper space when customer is try to add address

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5797]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. there should be proper space  in add address when customer is try to checkout 

## Actual Result

![0](https://user-images.githubusercontent.com/96044834/153804989-66c4839f-e28e-4dba-8a08-990df199eecc.png)

## Expected Result

![1](https://user-images.githubusercontent.com/96044834/153805017-c33550bf-74fc-40c1-b395-5a29af4fd745.png)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
**Thanks**, now this **issue is fixed**. so I am **closing** this issue.
And I have attached a screenshot for future reference [Here](https://prnt.sc/26xmme5)
