### ISSUE TITLE
 ui issues in arabic language  when we try to add booking product 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5799]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to catalog -> try to add booking product 

## Actual Result

![Screenshot from 2022-02-14 11-45-45](https://user-images.githubusercontent.com/96044834/153810635-ae80c41b-5e87-47db-b3cb-d206fdc8e6e6.png)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
**Thanks**, now the issue **is fixed**. so I am **closing** this issue.
And I have attached a screenshot for future reference [Here](https://prnt.sc/q9gQVZ0-miwC)
