### ISSUE TITLE
admin is not able to upload high mega pixel images in advertisement  

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5800]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to  settings -> velocity 

## Actual Result

https://user-images.githubusercontent.com/96044834/153818907-6a1feacb-a3b4-4d92-99ba-3d8df534de34.mp4

**Comment by singhgagan03** [comment]
it should be done for all areas where the images options come

**Comment by devansh-webkul** [comment]
This is not a bug, this all depends on `php.ini` settings.
