### ISSUE TITLE
Maximum video uploading size should be mentioned when we create product 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5801]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to catalog  and make a product 

## Actual Result

![Screenshot from 2022-02-14 13-04-18](https://user-images.githubusercontent.com/96044834/153821408-7524b5f5-a70c-4499-afbb-1561df1e2697.png)

**Comment by singhgagan03** [comment]
it should be done in whole bagisto where the vedios options come

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul  Fixed  https://tinyurl.com/2aldvu3z
