### ISSUE TITLE
alligment  issue  when we make a configurable product in delete and edit button 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5803]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1.  t go to catalog and try to make a configuration product 

## Actual Result

![0](https://user-images.githubusercontent.com/96044834/153826309-6ecd6875-0d11-4f43-9498-43eac8b8bc6c.png)

## Expected Result

![Screenshot from 2022-02-14 13-52-21](https://user-images.githubusercontent.com/96044834/153826487-7a6b30a4-cc2e-4c4e-aabf-b24a912aa9b7.png)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
There is also an issue near the **delete icon.** Please find the screenshot [Here](https://prnt.sc/26ws3sd)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
**Thanks**, now this **issue is fixed.** so I am closing this issue.
ANd I have attached a screenshot for future reference [Here]( Please find the screenshot [Here](https://prnt.sc/26xmk7d)
