### ISSUE TITLE
ui issue when admin  try to click on search  order in notification  in mobile view

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5809]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to notification bar and try to search 

## Actual Result

![Screenshot from 2022-02-14 18-51-45](https://user-images.githubusercontent.com/96044834/153994098-a33d221c-6adb-4dc7-bf48-9f8e1ad4b88a.png)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
I am getting this issue **on desktop view also**. Please find the screenshot [Here](https://prnt.sc/26w8c7k)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
**Thanks**, now this **issue is fixed**. so I am **closing** this issue.
And I have attached a screenshot for future reference [Here](https://prnt.sc/hrr1XWQtITgU)
