### ISSUE TITLE
Translation issues when switching between any two languages, specifically categories in nav does not revert back.

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#581]
1)**product category name  not change while changing the language.**
![issue1](https://user-images.githubusercontent.com/47665137/52859299-55ea2b80-3152-11e9-8538-c72de0471bfb.png)

2)**when we mark default  locale Arabic and set locale arabic, then front end was not change in arabic**
![issue2](https://user-images.githubusercontent.com/47665137/52859766-98f8ce80-3153-11e9-9449-d0d92fc45762.png)
![issue 2 front end2](https://user-images.githubusercontent.com/47665137/52859914-09075480-3154-11e9-9327-ba48bba86b0e.png)

**Comment by jitendra-webkul** [comment]
Please confirm, if you saved locale with code "ar". If not then it will not work.

**Comment by prashant-webkul** [comment]
Yups i tested it.

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot 13](https://user-images.githubusercontent.com/45203177/53495260-97b99100-3ac5-11e9-83b2-a12ba3cdd924.png)
