### ISSUE TITLE
admin is not able to hover over navigations  when there is a table 

### ISSUE THREAD

**Issue by singhgagan03** [bagisto/bagisto#5810]
## Bagisto Version

- [ ] master branch

## Steps To Reproduce

1. go to navigation bar in admin panel 

## Actual Result

https://user-images.githubusercontent.com/96044834/153996239-cfe40b37-12c5-4f58-8262-55de60492325.mp4

**Comment by Sanjaybhattwebkul** [comment]
@ghermans  @singhgagan03 
This is **not an issue**, the admin is able to hover the navigations. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/7401462?key=e1337336b53d4bce315b3a37feeb2e3b)
