### ISSUE TITLE
Promotion - discount on global cart

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#5822]
Hi,
i'm not sure if is possible to discount cart globally.
So I suggest it as new feature.

regards.

**Comment by Sanjaybhattwebkul** [comment]
hi @ghena 
can you please elaborate the feature that you want ?

**Comment by ghena** [comment]
Apply a discount to the whole cart in percentual on products only or whole cart.

**Comment by Sanjaybhattwebkul** [comment]
@ghena 
Thanks for reporting.
We will i**mplement this in the upcoming release**

**Comment by jitendra-webkul** [comment]
You can achieve this by creating a cart rule with "Percentage of Product Price" by adding conditions that accept all the products on the cart. 

If you want to include shipping then set "Apply to Shipping" to "Yes".

**Comment by ghena** [comment]
I suppose should be better use just one option to do this.

**Comment by devansh-webkul** [comment]
As this can't be implemented and we have suggested an alternative as well. 

Closing this issue.
