### ISSUE TITLE
There should not be much space between product and add to cart button in mobile view

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5823]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Try to view any product in the mobile view on the default theme

**Expected result:** There should not be much space between the product and the **add to cart** button.

**Actual result:** There is too much space between product and add to cart button. Please find the screenshot [Here](https://prnt.sc/26w9a7s).

**Comment by prateek-webkul** [comment]
@Sanjaybhattwebkul ,

unable to reproduce the issue. It's working fine. (see https://prnt.sc/ZGgkVg8gazyF )

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
I have taken a pull from the master. and after it.
This is working please find a screenshot [Here](https://prnt.sc/AJV0NNO-1CuN). Maybe it's fixed with some other pr  So I am closing this issue.
