### ISSUE TITLE
MAMP syntax error, unexpected 'ENDPATH' (T_STRING) (View: /bagisto/resources/themes/velocity/views/home/index.blade.php)

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#5833]
# Bug Report
## Issue Description
after installation on home page MAMP we get 
syntax error, unexpected 'ENDPATH' (T_STRING) (View: /bagisto/resources/themes/velocity/views/home/index.blade.php)

## Bagisto Version
1.3.2

**Comment by Sanjaybhattwebkul** [comment]
hi @ghena 
can you please elaborate?

**Comment by Sanjaybhattwebkul** [comment]
@ghena 
I guess there is some issue with your instance.

**Comment by ghena** [comment]
of course, I close it.
Sorry.
