### ISSUE TITLE
Bagisto in print not working

### ISSUE THREAD

**Issue by vishaldamasiya** [bagisto/bagisto#5852]
my controller code:

    public function print($id)
    {
        $invoice = $this->invoiceRepository->findOrFail($id);

        $html = view('admin::sales.invoices.pdf', compact('invoice'))->render();

            PDF::loadHTML($this->adjustArabicAndPersianContent($html))
            ->setPaper('a4')
            // ->setWarnings(false)->save('myfile.pdf');
            ->download('invoice-' . $invoice->created_at->format('d-m-Y') . '.pdf');
    }

    private function adjustArabicAndPersianContent($html)
    {
        $arabic = new \ArPHP\I18N\Arabic();

        $p = $arabic->arIdentify($html);

        for ($i = count($p) - 1; $i >= 0; $i -= 2) {
            $utf8ar = $arabic->utf8Glyphs(substr($html, $p[$i - 1], $p[$i] - $p[$i - 1]));
            $html   = substr_replace($html, $utf8ar, $p[$i - 1], $p[$i] - $p[$i - 1]);
        }

        return $html;
    }
-----------------------------------------------------------------------------------------------------------------------------------
 view file code

 <div class="page-action">
     {!! view_render_event('sales.invoice.page_action.before', ['order' => $order]) !!}

     <a href="{{ route('admin.sales.invoices.print', $invoice->id) }}" class="btn btn-lg btn-primary">
         {{ __('admin::app.sales.invoices.print') }} 
     </a>

     {!! view_render_event('sales.invoice.page_action.after', ['order' => $order]) !!}
 </div>
----------------------------------------------------------------------------------------------------------------------------------
Route code

            Route::get('/invoices/view/{id}', 'Webkul\Admin\Http\Controllers\Sales\InvoiceController@view')->defaults('_config', [
                'view' => 'admin::sales.invoices.view',
            ])->name('admin.sales.invoices.view');

            Route::get('/invoices/print/{id}', 'Webkul\Admin\Http\Controllers\Sales\InvoiceController@print')->defaults('_config', [
                'view' => 'admin::sales.invoices.print',
            ])->name('admin.sales.invoices.print');
----------------------------------------------------------------------------------
why my invoice not download....??
--------------------------------------------------------------------------------
and error -
Symfony\Component\ErrorHandler\Error\FatalError
Maximum execution time of 60 seconds exceeded
----------------------------------------------------------------------------------------
how to solve...??

**Comment by Sanjaybhattwebkul** [comment]
Hi. @vishaldamasiya 
Can you please share the steps which you have followed for downloading the invoice?

**Comment by Sanjaybhattwebkul** [comment]
@vishaldamasiya 
Please do not raise multiple issues for the same report. 
You can reply on the same issue.

**Comment by vishaldamasiya** [comment]
![image](https://user-images.githubusercontent.com/99727207/154888277-199dac4a-9591-4301-a4ba-07b86748848d.png)

**Comment by Sanjaybhattwebkul** [comment]
@vishaldamasiya 
I am not getting any issues while trying to download the invoice. Please find the screen recording [here](https://www.awesomescreenshot.com/video/7500438?key=a7c69098882be9732e50d7d2d8509c05).

**Comment by vishaldamasiya** [comment]
![image](https://user-images.githubusercontent.com/99727207/154888357-e44a482e-639e-4e8b-bb02-3b92c6fe158e.png)

**Comment by vishaldamasiya** [comment]
![image](https://user-images.githubusercontent.com/99727207/154888455-8fb8847c-fce5-4b96-a2f8-a3a3c92587b5.png)

**Comment by Sanjaybhattwebkul** [comment]
@vishaldamasiya 
I guess you have done some customization right?

**Comment by vishaldamasiya** [comment]
no

**Comment by vishaldamasiya** [comment]
bagisto install step by step 

all function working but invoice print not working

**Comment by vishaldamasiya** [comment]
admin and user both side invoice not print

**Comment by Sanjaybhattwebkul** [comment]
@vishaldamasiya 
This plate form is **only for reporting bugs.**
If you want any help/support then **please raise a ticket [Here](https://help.uvdesk.com/en/customer/create-ticket/).**
We will sort out your issue as soon as possible.

**Comment by vishaldamasiya** [comment]
please give me advice how to run invoice print
