### ISSUE TITLE
bagisto invoice not print

### ISSUE THREAD

**Issue by vishaldamasiya** [bagisto/bagisto#5853]
my controller code:

public function print($id)
{
    $invoice = $this->invoiceRepository->findOrFail($id);

    $html = view('admin::sales.invoices.pdf', compact('invoice'))->render();

        PDF::loadHTML($this->adjustArabicAndPersianContent($html))
        ->setPaper('a4')
        // ->setWarnings(false)->save('myfile.pdf');
        ->download('invoice-' . $invoice->created_at->format('d-m-Y') . '.pdf');
}

private function adjustArabicAndPersianContent($html)
{
    $arabic = new \ArPHP\I18N\Arabic();

    $p = $arabic->arIdentify($html);

    for ($i = count($p) - 1; $i >= 0; $i -= 2) {
        $utf8ar = $arabic->utf8Glyphs(substr($html, $p[$i - 1], $p[$i] - $p[$i - 1]));
        $html   = substr_replace($html, $utf8ar, $p[$i - 1], $p[$i] - $p[$i - 1]);
    }

    return $html;
}

**Comment by vishaldamasiya** [comment]
Route::get('/invoices/view/{id}', 'Webkul\Admin\Http\Controllers\Sales\InvoiceController@view')->defaults('_config', [
            'view' => 'admin::sales.invoices.view',
        ])->name('admin.sales.invoices.view');

        Route::get('/invoices/print/{id}', 'Webkul\Admin\Http\Controllers\Sales\InvoiceController@print')->defaults('_config', [
            'view' => 'admin::sales.invoices.print',
        ])->name('admin.sales.invoices.print');

**Comment by vishaldamasiya** [comment]
view file

            <div class="page-action">
                {!! view_render_event('sales.invoice.page_action.before', ['order' => $order]) !!}

                <a href="{{ route('admin.sales.invoices.print', $invoice->id) }}" class="btn btn-lg btn-primary">
                    {{ __('admin::app.sales.invoices.print') }} 
                </a>

                {!! view_render_event('sales.invoice.page_action.after', ['order' => $order]) !!}
            </div>

**Comment by vishaldamasiya** [comment]
![image](https://user-images.githubusercontent.com/99727207/154896317-0510790c-9e63-455b-88d5-15f93b1b024b.png)

**Comment by Sanjaybhattwebkul** [comment]
Hi
@vishaldamasiya 
This platform is **only for reporting bugs.**
If you want any help/support then **please raise a ticket [Here](https://help.uvdesk.com/en/customer/create-ticket/).**
We will sort out your issue as soon as possible.

**Comment by vishaldamasiya** [comment]
in this not ticket created
bcz my web is localhost:8000

**Comment by Sanjaybhattwebkul** [comment]
@vishaldamasiya 
Please raise a ticket form : https://help.uvdesk.com/en/customer/create-ticket/
Regarding the same
We will sort out your issue as soon as possible

**Comment by vishaldamasiya** [comment]
plz help me slove my error

**Comment by vishaldamasiya** [comment]
![image](https://user-images.githubusercontent.com/99727207/154896676-fddf95cc-de0a-4ed5-be9c-b11b952a1217.png)

**Comment by Sanjaybhattwebkul** [comment]
> ![image](https://user-images.githubusercontent.com/99727207/154896676-fddf95cc-de0a-4ed5-be9c-b11b952a1217.png)

No need to fill in the website URL. you can submit without the web URL

**Comment by vishaldamasiya** [comment]
ok

**Comment by vishaldamasiya** [comment]
![image](https://user-images.githubusercontent.com/99727207/154898311-49bc7aec-eb6a-48ad-bfb4-745953c0cd32.png)

**Comment by Sanjaybhattwebkul** [comment]
@vishaldamasiya 
Please create ticket from here : https://bagisto.uvdesk.com/en/customer/create-ticket/

**Comment by Sanjaybhattwebkul** [comment]
@vishaldamasiya 
Have you done ??

**Comment by vishaldamasiya** [comment]
yes sir
plaese as soon as possible response

**Comment by vishaldamasiya** [comment]
can you answer

**Comment by Sanjaybhattwebkul** [comment]
> can you answer
sure. 
now please continue with the ticket. our team will reply/provide a solution over the ticket

**Comment by vishaldamasiya** [comment]
ok

**Comment by prateek-webkul** [comment]
@vishaldamasiya ,

We have received your ticket and we are having a conversation over there. Please check ticket for messages.

Thanks
