### ISSUE TITLE
The categories name should be shown in all locales

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5855]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Visite on the shop
**2.** Change the app locale to Arabic.
**3.** Try to view all categories

**Expected result:** The categories name should be shown in all locales

**Actual result:** The category's name is not showing in the Arabic locale. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/7502851?key=07691586825dc1079d769706301fd5f1)

**Comment by prateek-webkul** [comment]
@Sanjaybhattwebkul ,

Please check if you have provided the data for arabic locale category.

**Comment by Sanjaybhattwebkul** [comment]
> @Sanjaybhattwebkul ,
> 
> Please check if you have provided the data for Arabic locale category.

@prateek-webkul 
The categories are added for the Arabic locale. Please find the screenshot [Here](https://prnt.sc/ShFPBSPDxPpS)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
Now, this **issue is fixed.** so I am **closing** this issue.
And i have attached a screen recording for future reference [Here](https://www.awesomescreenshot.com/video/7570595?key=ad9adef3721afcba33ca74d390feba9c)
