### ISSUE TITLE
bagisto invoice download in error Mpdf\MpdfException

### ISSUE THREAD

**Issue by vishaldamasiya** [bagisto/bagisto#5859]
bagisto laravel in invoice in click to print then not download 

error =

Mpdf\MpdfException
Incorrect zoom display mode:

how can solve this......???

**Comment by Sanjaybhattwebkul** [comment]
Hi @vishaldamasiya 

Please create a ticket from here: https://bagisto.uvdesk.com/en/customer/create-ticket/
If the issue is the same then you can reply on the same ticket. no need to raise again
Thanks.

**Comment by vishaldamasiya** [comment]
ok
