### ISSUE TITLE
bagisto laravel in invoice download

### ISSUE THREAD

**Issue by vishaldamasiya** [bagisto/bagisto#5860]
my bagisto laravel project in invoice downloading time error

Mpdf\MpdfException
Incorrect zoom display mode:

how to slove....??

**Comment by Sanjaybhattwebkul** [comment]
@vishaldamasiya 
Please raise a ticket for the same. [Here](https://bagisto.uvdesk.com/en/customer/create-ticket/).
Our team will provide a solution as soon as possible
