### ISSUE TITLE
The calendar should hide automatically after selecting the date.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5862]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** log in as admin/
**2.** Click on promotions. inside the marketing tab
**3.** CLick on the cart rules tab.
**4.** Try to create a new cart rule.
**5.** Select the date for the rule.

**Expected result:** The calendar should hide automatically after selecting the date.

**Actual result:** The calendar is not hiding automatically after selecting the date. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/7524832?key=dc79ffe3dfaa84f2cabee2cad9c7817f)

**Comment by prateek-webkul** [comment]
@Sanjaybhattwebkul ,

With a simple click outside the calendar closes the calendar or pressing the enter  I see no issues here going forward.
