### ISSUE TITLE
bagisto invoice pdf download

### ISSUE THREAD

**Issue by vishaldamasiya** [bagisto/bagisto#5863]
![image](https://user-images.githubusercontent.com/99727207/155097002-85e1a123-fce8-49cd-9940-524123558291.png)

then click print button

![image](https://user-images.githubusercontent.com/99727207/155097177-fc1c55a8-76e7-41b9-96c3-fa2cddb58c2f.png)

error display

my controller code 
-------------------------------------------------
    public function print($id)
    {
        $invoice = $this->invoiceRepository->findOrFail($id);
        // return $invoice;
        $html = view('admin::sales.invoices.pdf', compact('invoice'))->render();
        // return $html;

            return PDF::loadHTML($this->adjustArabicAndPersianContent($html))
            ->setPaper('a4')
            ->download('invoice-' . $invoice->created_at->format('d-m-Y') . '.pdf');
    }

    private function adjustArabicAndPersianContent($html)
    {
        $arabic = new \ArPHP\I18N\Arabic();

        $p = $arabic->arIdentify($html);

        for ($i = count($p) - 1; $i >= 0; $i -= 2) {
            $utf8ar = $arabic->utf8Glyphs(substr($html, $p[$i - 1], $p[$i] - $p[$i - 1]));
            $html   = substr_replace($html, $utf8ar, $p[$i - 1], $p[$i] - $p[$i - 1]);
        }

        return $html;
    }

---------------------------------------------------------------------

my view file

            <div class="page-action">
                {!! view_render_event('sales.invoice.page_action.before', ['order' => $order]) !!}

                <a href="{{ route('admin.sales.invoices.print', $invoice->id) }}" class="btn btn-lg btn-primary">
                    {{ __('admin::app.sales.invoices.print') }} 
                </a>

                {!! view_render_event('sales.invoice.page_action.after', ['order' => $order]) !!}
            </div>

----------------------------------------------------------------
my route:

                Route::get('/invoices/view/{id}', 'Webkul\Admin\Http\Controllers\Sales\InvoiceController@view')->defaults('_config', [
                    'view' => 'admin::sales.invoices.view',
                ])->name('admin.sales.invoices.view');

                Route::get('/invoices/print/{id}', 'Webkul\Admin\Http\Controllers\Sales\InvoiceController@print')->defaults('_config', [
                    'view' => 'admin::sales.invoices.print',
                ])->name('admin.sales.invoices.print');

--------------------------------------------------------------------

how to slove my error..??

**Comment by prateek-webkul** [comment]
Hello @vishaldamasiya ,

Already we are having a discussion over the ticket regarding this issue. Please raise your concern there as well. 

Thanks

**Comment by vishaldamasiya** [comment]
but sr i apply QR code and my invoice download in not there 
![image](https://user-images.githubusercontent.com/99727207/155100491-f617f3c2-407f-455e-bb26-30610e7480d5.png)


but sr i apply 

    public function print($id)
    {
        $invoice = $this->invoiceRepository->findOrFail($id);
        // return $invoice;
        $html = view('admin::sales.invoices.pdf', compact('invoice'))->render();
        return $html;

            return PDF::loadHTML($this->adjustArabicAndPersianContent($html))
            ->setPaper('a4')
            ->download('invoice-' . $invoice->created_at->format('d-m-Y') . '.pdf');
    }

------------------vireable return then invoice show my QR code

![image](https://user-images.githubusercontent.com/99727207/155100864-d879c30c-ba9b-458c-a161-84f639672d72.png)


how to slove this

**Comment by Sanjaybhattwebkul** [comment]
@vishaldamasiya 
Please raise your concern over the ticket. we will provide the solution over the ticket.

**Comment by vishaldamasiya** [comment]
ok
