### ISSUE TITLE
bagisto instalation

### ISSUE THREAD

**Issue by hamza-saqib** [bagisto/bagisto#5867]
# Bug Report
nothing happening after click on install

## Issue Description
i just clone the code and composer update and all that stuff, after running server provide data for instalation and click on intall button which show installation log but nothing happening and recivienving error in console log of server. 

## Bagisto Version
latest version i just cloned it

## Actual Result
stuck on instalation log screen

## Expected Result
should install file and move to next page

**Comment by ghermans** [comment]
Hi @hamza-saqib thank you for reporting this.
Is it possible to also provide the errors that you receive during the installation so that we can further investigate the cause of this issue ?

**Comment by hamza-saqib** [comment]
Uncaught Error: Class 'Illuminate\Foundation\Application' not found in C:\xampp\htdocs\bagisto\bootstrap\app.php:14

**Comment by ghermans** [comment]
@hamza-saqib i did multiple fresh installations on different servers but can not reproduce the error

![image](https://user-images.githubusercontent.com/1594411/155301895-2e90e6b4-8425-4f21-9230-e8e2c5c23f9b.png)
