### ISSUE TITLE
There is a UI issue on the Tax Rates page

### ISSUE THREAD

**Issue by merdiano** [bagisto/bagisto#5904]
**Bagisto Version:** Master

**Steps To reproduce-**-

**1.** log in as an admin.
**2.** Go Settings **>** Taxes **>** Tax Rates

**Expected result:** List of tax rates

**Actual result:** Empty page

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
There should be only one **export** option. Please find the screenshot [here](https://prnt.sc/hWS1RLi00BQh)
