### ISSUE TITLE
error during migrate

### ISSUE THREAD

**Issue by programmer11111** [bagisto/bagisto#591]
when i try to migrate then it says:  

 SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1 (SQL: create table `roles` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `description` varchar(191) null, `permission_type` varchar(191) not null, `permissions` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB ROW_FORMAT=DYNAMIC)

  at D:\xampp\htdocs\bagisto\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664

**Comment by prashant-webkul** [comment]
Please check the requirements and make sure that you have correctly installed versions for all of the required programs.
In this case your MariaDB version is older than its requires.
I am closing this issue straight away as you haven't checked your program versions.

**Comment by prashant-webkul** [comment]
You can find which versions and programs are required for Bagisto: https://github.com/bagisto/bagisto/blob/master/README.md

**Comment by programmer11111** [comment]
here is details of my server https://ibb.co/PZD02Zg   i hv all req. on windows

**Comment by prashant-webkul** [comment]
Please upload the media file in the comments.

**Comment by prashant-webkul** [comment]
And check these versions for databases:
1. For MySQL users: 5.7.23 or higher.
2. For MariaDB users: 10.2.7 or Higher.

**Comment by programmer11111** [comment]
https://ibb.co/khk1Ddh

https://ibb.co/wQ0FSCf

https://ibb.co/qyJKjP8

**Comment by prashant-webkul** [comment]
Please upload these media files in comments here. Look below when you write comments there is option to attach files by dragging & dropping........

**Comment by programmer11111** [comment]
ersion: '10.1.8-MariaDB'  socket: ''  port: 3306  mariadb.org binary distribution

**Comment by programmer11111** [comment]
![comp](https://user-images.githubusercontent.com/46997482/52946531-0b58f100-3396-11e9-988a-490af23ef64d.PNG)
![er2kk](https://user-images.githubusercontent.com/46997482/52946532-0bf18780-3396-11e9-9d2c-d0b41f68e37e.PNG)
![node](https://user-images.githubusercontent.com/46997482/52946533-0c8a1e00-3396-11e9-825b-4c6f78b85030.PNG)
![win](https://user-images.githubusercontent.com/46997482/52946534-0c8a1e00-3396-11e9-990b-6e3d919379e2.PNG)

**Comment by prashant-webkul** [comment]
> ersion: '10.1.8-MariaDB' socket: '' port: 3306 mariadb.org binary distribution

@programmer11111 You need MariaDB users: 10.2.7 or Higher.

**Comment by programmer11111** [comment]
ok
