### ISSUE TITLE
The user is not able to copy the product 

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5914]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as admin
**2.** Create a new user
**3.** Give permission to copy the product
**4.** Log in as a new user
**5.** Try to copy the product.

**Expected result:** The user should be able to copy the product if the user has permission for the same.

**Actual result:** The user is not able to copy the product if the user has permission for the same. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/7669042?key=378c97c31781005c645fbcfb941f8371)

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
I think, there should not be an option for a **copy** If the user has no permission to edit the product.

**Comment by jitendra-webkul** [comment]
Admin has to set up permission in a way that this won't happen. If the admin user has no permission to edit the product then they shouldn't have permission to copy the product.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**As we discuss** this is **not an issue.** so I am closing this issue.
