### ISSUE TITLE
 Notification should be received without page refresh

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5921]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Login as a user.
**2.** Create an order.
**3.** Login as admin.
**4.** Try to view current notifications.

**Expected result:**  Notification should be received without page refresh

**Actual result:** Notification is not receiving without page refresh. Please find the screenshot [Here](https://www.awesomescreenshot.com/video/7674185?key=58cad03febe187452e52c1f29947d171).

**Comment by Sanjaybhattwebkul** [comment]
@prateek-webkul 
Any Update ??

**Comment by devansh-webkul** [comment]
## Information
- Setup configuration from the pusher.
- After that run queue listener command i.e. `php artisan queue:work --queue=broadcastable`
- Done :100:
