### ISSUE TITLE
"Multiselect" Attribute type issue, when we select multiple option then numeric value is showing on the front end

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#596]
1)when we select multiple option then it will be showing numeric value on the front end
![attribute issue1](https://user-images.githubusercontent.com/47665137/52997754-74e50800-3447-11e9-9010-9f13e69a5f43.png)
![attribute issue 2](https://user-images.githubusercontent.com/47665137/52997820-9c3bd500-3447-11e9-9e21-58c6ee97b6f8.png)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot 50](https://user-images.githubusercontent.com/45203177/53238120-808e3400-36be-11e9-8627-171bccfb1d26.png)
