### ISSUE TITLE
There should be an option for a sitemap generator.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5960]
**Bagisto Version:** Master

**Expected result:** There should be an option for a sitemap generator.
**Actual result:** There is no option for a sitemap generator.

**Comment by soodankush** [comment]
Can I update the code for this enhancement??

**Comment by Sanjaybhattwebkul** [comment]
Hi @soodankush 
**Yes**, **You can** update.

**Comment by saurav-webkul** [comment]
Hi @soodankush 

Are you working on this feature?

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this **enhancement is done.** so I am **closing** this enhancement.
And I have attached a screenshot [Here](https://prnt.sc/hTf94-M9gZ0j), for future reference
