### ISSUE TITLE
Filters doesn't work properly

### ISSUE THREAD

**Issue by anardil** [bagisto/bagisto#5961]
Hello,

I've got a question about attributes displayed on Layered navigation.
Example: I've got 2 products in the category Tshirt:
- 1 Tshirt color red with size S
- 1 Tshirt color blue with size XL

My question is why when I make a filter with the color "red" I can see the sizes S and XL? 
Normally it should have only the size S.

<img width="501" alt="Capture d’écran 2022-03-04 à 09 38 59" src="https://user-images.githubusercontent.com/471437/156730537-6dc8e724-3723-4fcc-b6c9-9ac0240117c3.png">

How can I have only the size S show in filter attribute size?

Thanks for your help.

**Comment by Sanjaybhattwebkul** [comment]
Hi @anardil 
Which **version** of Bagisto are you using?

**Comment by Sanjaybhattwebkul** [comment]
@anardil 
The enhancement is **already raised [Here](https://github.com/bagisto/bagisto/issues/5962),** for the same
So we will implement it and **reflect it** in an **upcoming release**.

**Comment by anardil** [comment]
Hello,

Great news ! 
Hope it will release soon.

Thanks.
