### ISSUE TITLE
The next filters should be according to the previously selected filter.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5962]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Go to the shop.
**2.** Search any product by category.
**3.** Try to apply the color and size filter to the product.

**Expected result:** The next filters should be according to the previously selected filter.

**Actual result:** The next filter is not according to the previously selected filter. Please find the screenshot [Here](https://prnt.sc/Yo841OCD7OE8)

**Comment by jitendra-webkul** [comment]
Can't be implemented, this will add performance overheads to the page as we have to filter out all the products for possible combinations just to show attribute options.

**Comment by anardil** [comment]
Hello,

A good system of filtering it's very important for customers.
Other e-commerce solution did it already like Prestashop and Magento.
