### ISSUE TITLE
Upgrade to Laravel 9

### ISSUE THREAD

**Issue by AmooAti** [bagisto/bagisto#5963]
Hi, I hope you are well 
Since Laravel 9 has been released for almost two weeks, do you have any plans to upgrade to Laravel 9?

**Comment by Sanjaybhattwebkul** [comment]
Hi @AmooAti 
We will update bagisto  with Laravel-9

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Thanks**, now **Laravel 9 upgraded.** so I am closing this enhancement.
