### ISSUE TITLE
Maximum Password length is 18 characters in velocity theme, which is way too short to be secure

### ISSUE THREAD

**Issue by derMart** [bagisto/bagisto#5965]
# Bug Report

It seems at least in the php controllers of the shop frontend there is no maximum length which is good (as we currently do not use it). However, in velocity theme frontend validators, I have seen 18 characters maximum length, which is not good for anyone trying to use that theme. 18 Characters are way too short for certain password patterns (long passwords which are easy to remember, but hard to break). I can only advise the famous xkcd comic on this topic: https://xkcd.com/936/
Please increase maximum password length in velocity to at least 100 characters, or even better remove the upper limit as this matches php controllers validation.

best

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this **issue is fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/auyGj7_nsilM). for future reference.
