### ISSUE TITLE
"Boolean" Attribute type issue , when we select yes then 1 is showing on front end

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#597]
1)"Boolean" attribute type issue, when we select yes then 1 showing on the front end, it should be "yes"
![boolean issue 1](https://user-images.githubusercontent.com/47665137/53020805-c01a0d80-347d-11e9-9e06-f0e77ea4737a.png)
![boolean issue 2](https://user-images.githubusercontent.com/47665137/53020855-da53eb80-347d-11e9-9e1f-661ac3d2e480.png)

2)when we set "No" then attribute is not displaying on the front end
![setno boolean](https://user-images.githubusercontent.com/47665137/53020942-125b2e80-347e-11e9-9086-97f49547e725.png)
![issue boolean 2](https://user-images.githubusercontent.com/47665137/53021067-5c441480-347e-11e9-81e2-59e89cfe778a.png)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Fixed
![screenshot 49](https://user-images.githubusercontent.com/45203177/53237549-f85b5f00-36bc-11e9-9ae7-ba7a0b519587.png)
