### ISSUE TITLE
The filters should work properly. if the user is trying to filter the products by the color filter.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5995]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer
**2.** Search products by category.
**3.** Try to filter any configurable product by the color filter.

**Expected result:** The filters should work properly. if the user is trying to filter the products by the color filter.

**Actual result:** The filters should work properly. if the user is trying to filter the products by the color filter. Please find the below screenshot

![bug-one](https://user-images.githubusercontent.com/86394952/157829561-af2aa721-726e-4ef9-9610-c62785d539b3.png)

![bug-2](https://user-images.githubusercontent.com/86394952/157829564-b82bb0a5-abfe-4ba4-9e08-58f97b405624.png)

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
Any update ??

**Comment by rumensys** [comment]
Hi, filter is working for only one attribute option. If you choose both SIZE and COLOR, it doesn't work. Can you please make it working for all available attribute option?

**Comment by devansh-webkul** [comment]
@ghermans,

This is working fine and I am not able to reproduce this.

![Screenshot](https://user-images.githubusercontent.com/68321766/159435051-0439d6e7-49f7-428c-81ab-800443b3e1e7.png)

**Comment by Sanjaybhattwebkul** [comment]
Hi @rumensys  @ghermans 
This is **working fine,** we have to enable **Visible Individually**. for **all** products.
Please take a **reference** form **[Here](https://prnt.sc/BI4w3Ftx5tAr).**

**Comment by rumensys** [comment]
Added Visible individually for all configurable products and also for all variants through query in phpmyadmin for both product_flat table and product_attributes_values table. Filter still not working.

**Comment by Sanjaybhattwebkul** [comment]
Hi @rumensys 
Can we please continue [Here](https://bagisto.uvdesk.com/en/member/ticket/view/2376).
