### ISSUE TITLE
The wishlist and compare options are not showing in the velocity theme

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#5997]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer
**2.** Change app locale into Hindi.
**3.** Add any item to the wishlist/compare.
**4.** Try to view compare and wishlist products

**Expected result:** The wishlist and compare options should be shown in the velocity theme

**Actual result:** The wishlist and compare options are not showing in the velocity theme Please find the SCREENSHOT [Here](https://prnt.sc/uUMtzb_ntixT)

**Comment by prateek-webkul** [comment]
@Sanjaybhattwebkul,

You need to enable the wishlist and compare option from configuration for particular locale.
