### ISSUE TITLE
There is a UI issue if the admin is trying to update products by mass action.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6006]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin
**2.** Change the app locale in Mandarin.
**3.** Click on products inside the catalog.
**4.** Try to update/delete products by mass action.

**Expected result:** There should not any UI issue if the admin is trying to update products by mass action.

**Actual result:** There is a UI issue if the admin is trying to update products by mass action. Please find the screenshot [Here](https://prnt.sc/D8a8fuSPBOQ3)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
I am getting one more **UI issue** with the **Russian** locale in the **footer section** of the **velocity** theme.
Please find the screenshot [Here](https://prnt.sc/vgpa1ktTTORz).

**Comment by jitendra-webkul** [comment]
> **Bagisto Version:** Master
> 
> **Steps To reproduce**--
> 
> **1.** Log in as an admin **2.** Change the app locale in Mandarin. **3.** Click on products inside the catalog. **4.** Try to update/delete products by mass action.
> 
> **Expected result:** There should not any UI issue if the admin is trying to update products by mass action.
> 
> **Actual result:** There is a UI issue if the admin is trying to update products by mass action. Please find the screenshot [Here](https://prnt.sc/D8a8fuSPBOQ3)

Russian lang is not available for the admin package so can't produce this issue.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this issue **is fixed**. so I am **closing** this issue.
And I have attached a screenshot for future reference [Here](https://prnt.sc/vnIWl-3tUDbD_).
