### ISSUE TITLE
Root Category issue while root setting from channel

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#608]
Root Category issue while selecting the root category from the channel
Scenario 1:- select any new root except root(default) then subcategory is not displaying on the front end of the selected new root.
![screenshot 4](https://user-images.githubusercontent.com/47665137/53157931-8b769500-35e8-11e9-85d7-18069534ea82.png)
![root issue](https://user-images.githubusercontent.com/47665137/53158109-df817980-35e8-11e9-92cd-08224f6ba2d1.png)
![root issue 3](https://user-images.githubusercontent.com/47665137/53158311-4868f180-35e9-11e9-8f9f-c848b61f5594.png)

Scenario 2:- when we select the only Root(default) then It's subcategory is correct displaying on the front end

**Comment by Jyoti-Singh1** [comment]
Test Environment:
Framework Version: 0.1.4
Fixed
