### ISSUE TITLE
Multiple users can add to cart last quantity of a product

### ISSUE THREAD

**Issue by rumensys** [bagisto/bagisto#6100]
# Bug Report

## Issue Description

Add to Cart action should reduce quantity of a product in inventory source immediately, not when admin approve placed order with status "Delivered" in admin menu, because same product is still available to purchase by other user at this time.
## Bagisto Version

- [ ] master branch
- [X] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce

1. Add to cart the last available quantity of some product. 
2. In incognito mode or from other PC purchase same product again.
3. Repeat 2 multiple times - no problem.
4. Admin approve order of point 1 and set status do "Delivered"
5. Not able to purchase this product until edit quantity in catalog table, as it should be. 
## Actual Result

Last quantity of some product can be purchased by multiple users until order is in status "Pending" or "Waiting for payment" status.
## Expected Result

Product quantity should be reduced in inventory source immediately after clicking Add to Cart. If user do not complete order, or admin cancels order, quantity should be restored.

**Comment by ghermans** [comment]
Hey @rumensys i have checked your proposal and what I would suggest and agree to is that we reduce the quantity when an order is placed rather than after the order has been shipped.

**Comment by rumensys** [comment]
I agree. Reduce quantity after order is placed is a good solution. Restore quantity after order cancellation also.

**Comment by jitendra-webkul** [comment]
First of all, multiple users can add to cart the last quantity of a product if the product has a sufficient quantity.

And we do not reduce the quantity from the product after placing an order but we do reserve the ordered quantity (Reserve quantity can not be available for add to cart and product will be out of stock immediately) until the order got shipped or canceled.

If admin shipped the order ordered quantity will be reduced from the product and if admin canceled the order reserve quantity will be released for add to cart and product will be in stock.

**Comment by jitendra-webkul** [comment]
There is one more reason not to reduce the quantity after placing an order as we can not decide which Inventory Source to choose from to fulfill the ordered quantity. And during the shipment generation, the admin can select the inventory source from where quantity will be reduced.

**Comment by rumensys** [comment]
When you create a product, you choose in which inventory source it is available and how much pcs you have. Because now, please reproduce:
1. Set quantity of some product to 1.
2. Go to store. Add to cart the same product. Complete the order.
3.  Go to store again. Purchase same product again. No problem.
4. How to explain to second client that he ordered already out of stock product.
Please, change the code to reduce quantity after placing order from inventory source set on product creation.

**Comment by jitendra-webkul** [comment]
It is working fine, please check the linked video

https://www.awesomescreenshot.com/video/8044793?key=d56c3edcf34457db0c9fee23b28d216d

**Comment by rumensys** [comment]
Can you please check with configurable product with some variants. Thank you!

**Comment by Sanjaybhattwebkul** [comment]
Hi @rumensys 
This is **working fine with** configurable products. Please find the **screen recording [Here](https://www.awesomescreenshot.com/video/8046088?key=5e639ec28d8a2efd6f4f75309dd270f0)**

**Comment by Sanjaybhattwebkul** [comment]
@rumensys 
This is working fine. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/8046855?key=59098a2b04d2b0b51e58d6a2e7a2de73)

**Comment by Sanjaybhattwebkul** [comment]
@rumensys 
In the case of a configurable product. only the size/color will be displayed in dropdown whose quantity will be greater than 0

**Comment by Sanjaybhattwebkul** [comment]
Hi @rumensys 
**Hope** your issue will be **resolved**.If you are still **getting** the **same** issue. please let **me know.**

**Comment by rumensys** [comment]
Hi, I'm still having same issue. Please try to order this model. It has only 1 in inventory source.
https://befado.bg/089m409

**Comment by Sanjaybhattwebkul** [comment]
@rumensys 
I guess the Allow Backorders is enabled from the backend. please verify and let me know.
Please take a reference from [here](https://prnt.sc/xLQjXiquqQHl)

**Comment by rumensys** [comment]
Hi, Allow backorders is NOT enabled, also Allow out of stock items is NOT enabled.

**Comment by Sanjaybhattwebkul** [comment]
@rumensys 
Have you done any customization ??

**Comment by rumensys** [comment]
In the main code NO! Only a few colors in CSS. Please, give me mail to give you all the credentials .

**Comment by Sanjaybhattwebkul** [comment]
@rumensys 
Please **raise** a **ticket** [Here](https://bagisto.uvdesk.com/en/customer/create-ticket/).
You can **share** all the **credentials** over the **ticket**.

**Comment by jitendra-webkul** [comment]
I hope your issue got resolved, I am closing this issue. Feel free to reopen anytime.
