### ISSUE TITLE
There should be an option to Increase/Decrease the font size of the website.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6104]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Visit to the shop
**2.** Try to Increase/Decrease the font size

**Expected result:** There should be an option to Increase/Decrease the font size of the website.

**Actual result:** There is no option to Increase/Decrease the font size of the website. 

**Please take a reference form [Here](https://prnt.sc/ov0R68pySufm).**

**Comment by saurav-webkul** [comment]
Here we need to have similar kind of UI as well as referred above: https://prnt.sc/ov0R68pySufm

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
as we discuss I am closing this enhancement.
