### ISSUE TITLE
Edit channel page is Blank if admin_locale=fr

### ISSUE THREAD

**Issue by Omarkhazri** [bagisto/bagisto#6114]
## Issue Description
When i try to edit the channel "default"  i get blank page without any error just the page appear for 1 ms and after that it disappear.

## Dev/Env
Windows 10 LTSC 
Largon Full 5.0.0
PHP 7.4.19
MariaDB 10.8.2

## Bagisto Version
v1.4.1
## Screenshot
![image](https://user-images.githubusercontent.com/39400866/159964898-faaa3f6a-055a-4c58-a153-f5c48262020f.png)

**Comment by jitendra-webkul** [comment]
@Omarkhazri can you share laravel exceptions log and browser console screenshot.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Thanks**, now this **issue is fixed,** so I am **closing** this issue.
And I have attached a **screenshot [Here](https://prnt.sc/DMnGI4fe5NW6).** for future **reference**.

**Comment by Sanjaybhattwebkul** [comment]
Hi @Omarkhazri 

Please **verify** from **your end**. if still, you are getting the **same issue**. you can **reopen** this.
