### ISSUE TITLE
The warning message should be correct if the user is trying to delete the account

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6121]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a user
**2.** Change app locale in hindi.
**3.** Click on the profile section.
**4.** Click on the delete button.
**5**. Click on the delete button without filling in the password.

**Expected result:** The warning message should be correct if the user is trying to delete the account

**Actual result:** The warning message is not correct if the user is trying to delete the account. Please find the screenshot [Here](https://prnt.sc/HhfAezFUCrey).

**Comment by jitendra-webkul** [comment]
Fixed in #6125

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Now**, this issue **is fixed**. so I am **closing** this issue./
And I have attached a screenshot [Here](https://prnt.sc/OrsP5hcVToBC). for future reference.
