### ISSUE TITLE
There is a UI issue on the header section

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6124]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Login as a user
**2.** Change the app locale in Arabic.
**3.** Click on profile on the top-left corner.

**Expected result:** There should not be any UI issue on the header section

**Actual result:** There is a UI issue on the header section in the Arabic locale. Please find the screenshot [Here](https://prnt.sc/1HYC3bugATM_).

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Not fixed**. now getting the **same issue** with the **English** locale.
Please find the screenshot [Here](https://prnt.sc/e93hYbf9n6Dy
).

**Comment by jitendra-webkul** [comment]
Fixed in #6131

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now the **issue is fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/bckExMgY7zl1). for future reference.
