### ISSUE TITLE
Constructor failed (View: price.blade.php

### ISSUE THREAD

**Issue by rsabzaali** [bagisto/bagisto#6139]
![debug](https://user-images.githubusercontent.com/39216384/160240393-8e3f7956-6863-4331-97dc-e52a63b85141.PNG)
# Bug Report

## Issue Description

Frontend not working. Added screen from debug.

## Bagisto Version

- [X] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce

Have add another currency and created product. 

## Actual Result

Frontend must be work.

**Comment by rsabzaali** [comment]
find another solution

**Comment by osama2june** [comment]
Hello,

I am facing the same issue please share the solution or link .

Thanks

**Comment by osama2june** [comment]
![image](https://user-images.githubusercontent.com/48173138/175481120-dade1397-f175-4944-916a-b721a6c6d47c.png)

**Comment by osama2june** [comment]
its working fine with USD and EUR . but when i changed to RUB or other currencies its took error fine the attachment

![image](https://user-images.githubusercontent.com/48173138/175481566-e3cf2b98-6149-40ab-aae6-5c45d89cdb50.png)
