### ISSUE TITLE
Payment methods page is Blank if admin_locale=fr

### ISSUE THREAD

**Issue by Omarkhazri** [bagisto/bagisto#6144]
## Issue Description
When i try to open the paymentmethods page 'admin/configuration/sales/paymentmethods' i get blank page .
the problem is in the view locate in \packages\Webkul\Admin\src\Resources\views\configuration\field-type.blade.php .

## Dev/Env
Windows 10 LTSC
Largon Full 5.0.0
PHP 7.4.19
MariaDB 10.8.2

## Bagisto Version
v1.4.1

## Screenshot
![image](https://user-images.githubusercontent.com/39400866/160256009-b74fde28-7d94-47fc-bb00-5b89696c4a72.png)

**Comment by Sanjaybhattwebkul** [comment]
Hi @Omarkhazri 
**Thanks** for **reporting**. we **will fix** it in the upcoming release.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Thanks,** now this issue is  **fixed**. so i am closing this issue
And I have attached a screenshot [Here](https://prnt.sc/rQmwAUNDVSXd) for future reference.
