### ISSUE TITLE
 General error: 1465 Triggers can not be created on system tables

### ISSUE THREAD

**Issue by parv2211** [bagisto/bagisto#6145]
getting error while setting up bagisto with **php artisan migrate**
 SQLSTATE[HY000]: General error: 1465 Triggers can not be created on system tables (SQL:
              CREATE TRIGGER trig_category_translations_insert
              BEFORE INSERT ON category_translations
              FOR EACH ROW
              BEGIN
                              DECLARE parentUrlPath varchar(255);
              DECLARE urlPath varchar(255);

              -- Category with id 1 is root by default
              IF NEW.category_id <> 1
              THEN

                  SELECT
                      GROUP_CONCAT(parent_translations.slug SEPARATOR '/') INTO parentUrlPath
                  FROM
                      categories AS node,
                      categories AS parent
                      JOIN category_translations AS parent_translations ON parent.id = parent_translations.category_i
  d
                  WHERE
                      node._lft >= parent._lft
                      AND node._rgt <= parent._rgt
                      AND node.id = (SELECT parent_id FROM categories WHERE id = NEW.category_id)
                      AND parent.id <> 1
                      AND parent_translations.locale = NEW.locale
                  GROUP BY
                      node.id;

                  IF parentUrlPath IS NULL
                  THEN
                      SET urlPath = NEW.slug;
                  ELSE
                      SET urlPath = concat(parentUrlPath, '/', NEW.slug);
                  END IF;

                  SET NEW.url_path = urlPath;

              END IF;
              END;)

In Exception.php line 18:

  SQLSTATE[HY000]: General error: 1465 Triggers can not be created on system tables

In PDOConnection.php line 55:

  SQLSTATE[HY000]: General error: 1465 Triggers can not be created on system tables

**Comment by Sanjaybhattwebkul** [comment]
Hi @parv2211 
is your database  **Collation**  is **_utf8mb4_unicode_ci_**

**Comment by parv2211** [comment]
ess

**Comment by parv2211** [comment]
@Sanjaybhattwebkul 
yess

**Comment by parv2211** [comment]
> Hi @parv2211 is your database **Collation** is **_utf8mb4_unicode_ci_** ?

**Comment by Sanjaybhattwebkul** [comment]
@parv2211 
Which database are you using ??

**Comment by parv2211** [comment]
@Sanjaybhattwebkul
MySQL

**Comment by Sanjaybhattwebkul** [comment]
Hi there.
Can you please share the steps which you are following?

**Comment by parv2211** [comment]
1. - download the zip file and then unzip it in the Xampp>htdocs folder.
2. - open the bagisto folder in cmd and run **composer install** but it shows some error and suggest to run **composer update**.
3. so after running composer update it shows  -> 

"Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - maatwebsite/excel[3.1.28, ..., 3.1.30] require phpoffice/phpspreadsheet 1.16.* -> satisfiable by phpoffice/phpspreadsheet[1.16.0].
    - maatwebsite/excel[3.1.31, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0].
    - maatwebsite/excel 3.1.27 requires phpoffice/phpspreadsheet ^1.16 -> satisfiable by phpoffice/phpspreadsheet[1.16.0, ..., 1.22.0].
    - maatwebsite/excel 3.1.26 requires phpoffice/phpspreadsheet ^1.15 -> satisfiable by phpoffice/phpspreadsheet[1.15.0, ..., 1.22.0].
    - phpoffice/phpspreadsheet[1.15.0, ..., 1.22.0] require ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - Root composer.json requires maatwebsite/excel ^3.1.26 -> satisfiable by maatwebsite/excel[3.1.26, ..., 3.1.x-dev].
To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-gd` to temporarily ignore these required extensions.
Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions."

4. so **composer update --ignore-platform-req=ext-gd** is successfully run.
5. then I run **php artisan migrate**, and it shows this error.

**Comment by Sanjaybhattwebkul** [comment]
@parv2211 
Please follow the below steps for installing the fresh bagisto.
[Bagisto Installation ](https://www.awesomescreenshot.com/video/8113728?key=15dba3c6eed084d77b561cbafc25ba9e
)

**Comment by Sanjaybhattwebkul** [comment]
@parv2211 
If you will still get the same issue. then please let me know.

**Comment by parv2211** [comment]
@Sanjaybhattwebkul
yes, it's work. but in the admin dashboard getting this error.
**Error
Class "NumberFormatter" not found**

**Comment by Sanjaybhattwebkul** [comment]
@parv2211 
Enable/Install the **php_intl extension** in the **php.ini** file, the issue will be resolved.

**Comment by Sanjaybhattwebkul** [comment]
Hi There,

Thanks for the update.

Also, if you like our support, you may give us the **review here:-** https://www.trustpilot.com/review/bagisto.com

That **would be grateful for us.**

Thanks

**Comment by Sanjaybhattwebkul** [comment]
@parv2211 
I hope your issue will be resolved. if still, you are getting the same issue. please let me know.

**Also, if you like our support, you may give us the review here:-** _https://www.trustpilot.com/review/bagisto.com_

That **would be grateful** for us.

**Comment by parv2211** [comment]
Thank you for your support
