### ISSUE TITLE
LINT ERROR IN EDIT PRODUCTS BLADE

### ISSUE THREAD

**Issue by soodankush** [bagisto/bagisto#6156]
# Bug Report
![bagisto_error](https://user-images.githubusercontent.com/12609531/160374823-a49ac1b9-258f-4242-ba9b-b03d09c86a8f.png)

## Issue Description
I am getting a linting error. I need the correct expression. Please see the screenshot attached.

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ * ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce
Go to packages/Webkul/Velocity/src/Resources/views/admin/content/content-type/edit-product.blade.php

## Actual Result
There is a linting error.

## Expected Result
Linting Error should be removed.

**Comment by Sanjaybhattwebkul** [comment]
Hi @soodankush 
**Thanks** for reporting we will fix it

**Comment by soodankush** [comment]
Please can you fix it as soon as possible?

**Comment by Sanjaybhattwebkul** [comment]
Hi @soodankush 
We will **fix** it as **soon** as possible. and will reflect in the **next release.**

**Comment by Sanjaybhattwebkul** [comment]
Hi @soodankush 
Now, this **issue is fixed**. Please **verify** from **your end.** 
If still, you are getting the same issue. Then please let me know.

**Comment by soodankush** [comment]
Hi @Sanjaybhattwebkul ,

Thank you. The issue has been fixed.
