### ISSUE TITLE
There should not be any UI issue on the orders page.if the user is trying to filter the orders

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6161]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Login as an user in mobile view
**2.** Click on orders inside the profiles section
**3.** Try to filter the orders

**Expected result:** There should not be any UI issue on the orders page.if the user is trying to filter the orders

**Actual result:** There is a UI issue on the orders page if the user is trying to filter the orders. Please find the screenshot [Here](https://prnt.sc/RvPR6uucKrse).

**Comment by ashishkumar-webkul** [comment]
@Sanjaybhattwebkul While checking the same UI issue, It can also be seen in the Downloadable Products Page Filters section also.
Kindly Check the Screenshot for reference.

**Screenshot**
![Screenshot from 2022-03-29 14-37-22](https://user-images.githubusercontent.com/92721837/160576574-2d8263bf-048e-4f59-ae3e-17018e94d4b0.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this **issue is fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/JZauaRW65p1I). for future reference.
