### ISSUE TITLE
UI Enhancement - Please Make the Information Text Bold in the Compare Product Page.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6162]
**Issue Description**
It would be better if the information Text on the compare page appears in bold. So that it will be better in appearance.

**Bagisto Version - Master**

**Steps To Reproduce**
1. Add Products to Compare -> Click on Compare Page -> Check the LHS Information text.

**Actual Result**
Check the Screenshot -> 
![UI](https://user-images.githubusercontent.com/92721837/160575642-07deb47e-9f70-453b-a56f-26587d8de1ae.png)

 **Expected Result**
Please Make it bold for better UI.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Now,** this enhancement **is done**. so I am **closing** this enhancement.
And I have attached a screenshot [Here](https://prnt.sc/uCv4aW6tvxu8), for future reference.
