### ISSUE TITLE
UI Enhancement - Please Add the separation Lines in the Heading section also in Orders and Downloadable Product Details.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6164]
**Issue Description**
In the Order and Downloadable Product section, there in the headings we cannot see the separating lines,  Please add the line for better UI.

**Bagisto Version - Master**

**Steps To Reproduce**
Go to the Order and Downloadable Product Section and check the headings.

**Actual Result**
Check the Screenshot
![Screenshot from 2022-03-29 15-32-34](https://user-images.githubusercontent.com/92721837/160588128-b3b824d5-a855-485d-92af-72dd00a11419.png)

 **Expected Result**
Check the screenshot
![Lines](https://user-images.githubusercontent.com/92721837/160588207-2fb1d334-a0d4-4c89-bd7c-bd3d3617d531.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this enhancement i**s done.** so I am **closing** this issue.
And I have attached a screenshot  [Here](https://prnt.sc/Z2OPEH2LKlRw).for future reference.
