### ISSUE TITLE
In Downloadable Product Section Unnecessary Column is present.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6165]
**Issue Description**
In the Downloadable Product Section, the Unnecessary Column is present when we check the ordered downloadable product details.

**Bagisto Version - Master**

**Steps To Reproduce**
1. Order any downloadable product -> Proceed with all the checkout processes.
2. Now Check the downloadable product section -> Extra Column Can be seen.

**Actual Result**
Check the screenshot
![Column](https://user-images.githubusercontent.com/92721837/160592028-896dd6cf-4219-491e-b0b9-4cd4a2334255.png)

 **Expected Result**
Please Remove the extra Column.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this **issue is fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/6rYyquWOFc1S).for future reference.
