### ISSUE TITLE
Suggestion - Can we have Delete all Button at the Checkout Cart.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6166]
**Suggestion Description**
When we look at the Checkout Main Cart, there can we have an option to delete all button.  So that if suppose anyone wants to delete or remove all the cart products, it would be easy if we can remove all of them with just a simple button. instead of pressing the delete tab button individually.

**Bagisto Version - Master**

**Steps To Reproduce**
**1.** Add more products to checkout -> There we can see individual delete options.
**2.** Can we add a delete all button over there?

**Actual Result**
Check the Video.
https://user-images.githubusercontent.com/92721837/160600517-472b4e66-e88c-40dd-b474-815c82cd10b5.mp4

 **Expected Result**
Check the screenshot
![delete all](https://user-images.githubusercontent.com/92721837/160600913-79c9209a-bd9f-4dfd-96b3-36a825f9848e.png)

**Comment by ghermans** [comment]
@ashishkumar-webkul  a pull request for this has already been made https://github.com/bagisto/bagisto/pull/5998

**Comment by ashishkumar-webkul** [comment]
@ghermans 
Acknowledged the concern. Thank You.
