### ISSUE TITLE
UI Enhancement - Please change the logo of locale selection at the admin panel.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6172]
**Issue Description**
At the admin panel when we select the language from RH top, there we can see the location logo, actually, that logo is for language. Please change the logo and add an appropriate logo.

**Bagisto Version - Master**

**Steps To Reproduce**
**1.** Go to Admin Panel - Right-Hand top Corner -> Location Logo.

**Actual Result**
Please check the screenshot 
![lang](https://user-images.githubusercontent.com/92721837/160755512-5830c0eb-b005-4ad5-86a5-3ceeefaad910.png)

**Expected Result**
Please check the sample Image 
![Sample ](https://user-images.githubusercontent.com/92721837/160755855-0fd78f96-49b4-4a5a-bc94-9511a836c6ff.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
**Thanks**, now this **enhancement is done**. so I am **closing** this enhancement 
And I have attached a screenshot [Here](https://prnt.sc/Q5XpZARXlKkt),for future reference
