### ISSUE TITLE
Layout issue on Changing Locale.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#618]
Framework Version: 0.1.4
Navigation bar issue

![screenshot 52](https://user-images.githubusercontent.com/45203177/53245902-29478e00-36d5-11e9-93c9-71a16c67a0f2.png)
![screenshot 53](https://user-images.githubusercontent.com/45203177/53245929-3b293100-36d5-11e9-9b59-12e0e5ca1ce1.png)

Navigation bar dropdown issue
![screenshot 54](https://user-images.githubusercontent.com/45203177/53245920-35cbe680-36d5-11e9-9e48-30c30ef4a08f.png)

**Comment by Jyoti-Singh1** [comment]
Framework Version: 0.1.4
Not fixed
![screenshot 6](https://user-images.githubusercontent.com/45203177/53485073-49979400-3aab-11e9-80eb-5d1b395af941.png)

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.4
Fixed
![screenshot from 2019-03-08 15-22-36](https://user-images.githubusercontent.com/45203177/54021383-0c6f8800-41b6-11e9-8070-f3c852f5b1e3.png)
