### ISSUE TITLE
The shopping cart goes empty after removing an item from the mini-cart.

### ISSUE THREAD

**Issue by vivek-webkul** [bagisto/bagisto#6192]
# Bug Report

The shopping cart goes empty after removing an item from the mini-cart.

## Issue Description

Add 2-3 products to the cart, and remove an item from the mini-cart. After removing the first item the shopping cart becomes empty.

## Bagisto Version

- [x] master branch

## Expected Result

The shopping cart should be empty, after removing all the items from the shopping cart.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this **issue is fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/PZUEAKnfZCsg), for future reference.
