### ISSUE TITLE
Mini-Cart sub-total is not updating after removing the cart's item.

### ISSUE THREAD

**Issue by vivek-webkul** [bagisto/bagisto#6195]
# Bug Report

Mini-Cart sub-total is not updating after removing the cart's item.

## Bagisto Version

- [x] master branch
- [x] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Expected Result

Mini-Cart subtotal must be updated after the removal of each cart item.

https://user-images.githubusercontent.com/28401696/161006610-8f8787fe-bac5-402b-931c-703136722cd9.mp4

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Mini-Cart sub-total is not updating for only guest users.

**Comment by jitendra-webkul** [comment]
Fixed in #6193

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, **this issue is fixed.** so I am **closing** this issue.
And I have attached a screen recording for future reference. [here](https://www.awesomescreenshot.com/video/8164567?key=81e1ab734268aa92e47f337c82cdc54b)
