### ISSUE TITLE
Link to frontend from admin product list or product detail page

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#6197]
Hi,

is possible to add a link inside admin product list and  admin product detail able to jump to front end product page ?
regards.

**Comment by Sanjaybhattwebkul** [comment]
Hi @ghena 
Can you please elaborate ??

**Comment by Sanjaybhattwebkul** [comment]
> Hi,
> 
> is possible to add a link inside admin product list and admin product detail able to jump to front end product page ? regards.

@ghena 
**Thanks** for your suggestion. we **will implement** it and will **reflect** it in the **upcoming** release.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this feature **is implemented**. so I am **closing** this. 
And I have attached a screenshot [Here](https://prnt.sc/9_7BH0F7iGZj). for future reference.
