### ISSUE TITLE
The product status should be Highlighted in product list page

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6208]
**Issue Description**
The Status of the product on the products page must be highlighted with the Background boxes as per the workflow, like active or inactive.  

**Bagisto Version - Master**

**Steps To Reproduce**
**1.** Click on products indie the catalog tab.
**2.** View the status of the products.

**Actual Result:** The status of the product is not Highlighted in the products table.

**Expected Result:** Please look at the screenshot for reference.

**Screenshot**
![Boxes](https://user-images.githubusercontent.com/92721837/161250072-989f0afe-8f24-4632-a315-3f9ae565e1d0.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this enhancement **is done**. so I am **closing** this enhancement. 
And I have attached a screenshot [Here](https://prnt.sc/7047r3h1xs-5), for **future reference**
