### ISSUE TITLE
Command For Bagisto Publish

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#6213]
## Info
- There should be a command like `php artisan bagisto:publish --all --force` something like this so that we can avoid using `php artisan vendor:publish --all --force` because most of the time we don't wont to publish all providers.
-  Even `--all` also not needed just `--force`.
- In installation also we can change that. So that we don't need to rely on.

**Comment by devansh-webkul** [comment]
@jitendra-webkul and @ghermans,

I have started working on this.

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
**Thanks**, now this enhancement **is implemented**. so I am **closing** this enhancement.
And I have attached a screenshot [Here](https://prnt.sc/Pjm_7xCTz1JF), for future reference.
