### ISSUE TITLE
Constructor failed NumberFormatter

### ISSUE THREAD

**Issue by tufkan1** [bagisto/bagisto#6218]
![image](https://user-images.githubusercontent.com/30411352/161481859-fd2aae54-9008-4246-938e-96c8ed30f898.png)

I have already activated the relevant php plugins, but I am getting an error like this in ajax that brings products related to the category.

**Comment by Sanjaybhattwebkul** [comment]
Hi @tufkan1 
Please  enable **php intl extension**   on your **php.ini** file.
The issue **will be resolved**

**Comment by Sanjaybhattwebkul** [comment]
@tufkan1 
**After enabling** the PHP intl extension you are  getting the **same issue** then please **let me know**
