### ISSUE TITLE
The applied filter should be removed after page refresh. when the admin is trying to filter the orders

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6242]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Login as an admin.
**2.** Click on the orders inside the sales tab
**3.** Try to filter the orders. 
**4.** refresh the page.

**Expected result:** The applied filter should be removed after page refresh. when the admin is trying to filter the orders

**Actual result:** The applied filters are not removed after page refresh. when the admin is trying to filter the orders Please find the screenshot [Here](https://prnt.sc/iBQ8M-G3KVcl).

**Comment by devansh-webkul** [comment]
This is the default behavior, filter is persist on page refresh and page changes also.
