### ISSUE TITLE
The admin is not able to view the customer's review if the customer is creating a review with the moustache syntax Like: {{ url(' ') }} 

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6250]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Login as a customer.
**2.** Click on any product.
**3.** Write review for the product with mustache syntax  like {{ url('/') }}

**Expected result:** The admin should be  able to view the customer's review even the customer is creating a review with the mustache syntax like: {{ url('/') }}

**Actual result:** The admin is not able to view the customer's review if the customer is creating a review with the mustache syntax like: {{ url('/') }} Please find the screen recording [Here](https://www.awesomescreenshot.com/video/8263414?key=c26151f7affbe556f91cc46aea0ae81c).

**Comment by devansh-webkul** [comment]
Checking.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
Now, this **issue is fixed.** so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/58Sro8lkwiZm). for future reference.
