### ISSUE TITLE
There is a translation issue on the checkout page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6257]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer.
**2.** Change the app locale in Arabic
**3.** Click on any product.
**4.** Try to buy the product.

**Expected result:** There should not be any translation issue on the checkout page.

**Actual result:** There is a translation issue on the checkout page.Please find the screenshot [Here](https://prnt.sc/5Naol6_pIK7F).

**Comment by devansh-webkul** [comment]
This is not an issue, you have not added an Arabic language title from the configuration,
![Screenshot](https://user-images.githubusercontent.com/68321766/163775668-fb47e2b1-0ba3-4d25-97ed-d43a064a565a.png)
