### ISSUE TITLE
The Magnifier is not working properly if there are multiple images of any simple product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6264]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as admin.
**2.** Create a simple product with multiple images.
**3.**  Visit the shop.
**4.** Click on the created product.
**5.** Try to view all images of the product by  Magnifier.

**Expected result:** The Magnifier should work properly if there are multiple images of any simple product.

**Actual result:** The Magnifier is not working properly if there are multiple images of any simple product. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/8284620?key=fb699519c1ecea171908d0c365f8edc4).

**Comment by devansh-webkul** [comment]
Working fine not able to reproduce this,

https://user-images.githubusercontent.com/68321766/163779343-ff6b9a38-a517-45e2-8376-24863c214f5e.mp4
