### ISSUE TITLE
PRODUCT IMAGES ARE NOT BEING DISPLAYED AT THE FRONT END

### ISSUE THREAD

**Issue by soodankush** [bagisto/bagisto#6274]
# Bug Report
Images not being displayed in the store frontend.

## Issue Description
I am upgrading my ecommerce system from 1.2.0 to 1.3.2. I am using valet to secure the domain. Images of the products, various logo images are not being displayed in the store front. Images for product are displayed in the backend.

APP_URL=https://devshop.test
is what I am using. 

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ * ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Actual Result
![image](https://user-images.githubusercontent.com/12609531/162392529-8e1c20e4-4480-4bd5-a781-c8882195c381.png)

## Expected Result
Images should get displayed on the front end.

**Comment by Sanjaybhattwebkul** [comment]
Hi @soodankush 
Please run: _**php artisan vendor:publish --force**_   for the product **service provider only**

**Comment by soodankush** [comment]
Thank you. It solved my problem
