### ISSUE TITLE
Checkout redirects when a carrier has more than one shipping method

### ISSUE THREAD

**Issue by 00110000** [bagisto/bagisto#6277]
# Bug Report

## Issue Description

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shipping/src/Shipping.php#L150

This function is used to check whether a shipping method code exists, but unfortunately it assumes that each carrier only has a single method. If you have a carrier that returns more than one method/rate (e.g. for matrix rates), then the `isMethodCodeExists` function will return false.

## Preconditions

- Apache
- PHP 7.4
- MySQL 8
- Bagisto 1.4.2

## Bagisto Version

- [x] master branch
- [x] 1.4.2
- [x] 1.4.1
- [x] 1.4.0

## Steps To Reproduce

- Create a carrier that returns an array of shipping rates in its `calculate` function. Ensure that shipping rate has a unique method (e.g. `shipping_rate_1` and `shipping_rate_2`).
- Visit the checkout
- Select one of the carriers shipping rates
- Complete the checkout

## Actual Result

The order is not placed and the customer is redirected to their cart.

## Expected Result

The order is placed.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
