### ISSUE TITLE
Cancel already shipped order results in incorrect pending inventory amount

### ISSUE THREAD

**Issue by derMart** [bagisto/bagisto#6290]
# Bug Report

## Issue Description
Cancel an already shipped order results in incorrect pending inventory amount if there are other pending orders.

## Steps To Reproduce
- Set product inventory for product A to 10
- Let user order 5 amounts of product A in order1
- Let user order 2 amounts of product A in order2

now product inventory for A is still at 10
pending inventory for A is 7
(-> available amount A is 10 - 7 = 3)
- Create Shipment for order1 of 5 amounts of product A 

now product inventory for A is at 5
pending inventory for A is 2
(-> available amount A is 5 - 2 = 3)

- Cancel the order1

## Expected Result
product inventory for A is at 10
pending inventory for A is 2

The cancel action should just increase the product inventory for A and leave the pending inventory as is. The reason is, that the order1 already got shipped, so pending inventory was already reduced as well as normal product inventory.

So as end result available amount for A should be 8 (10 - 2).

## Actual Result
product inventory for A is at 10
pending inventory for A is 0

So as end result available amount for A currently is 10 (10 - 0).

Reason:
The pending inventory is changed for A even if it should not, as there already was a shipment for order1.
This is due to this line:
https://github.com/bagisto/bagisto/blob/28a81fb1ad3c6427f58ebec5b6c8564e83d92cee/packages/Webkul/Sales/src/Repositories/OrderItemRepository.php#L172

The `returnQtyToProductInventory` function in the `OrderItemRepository` correctly updates the inventory sources for A. It takes into account the shipment items. But the function needs to also account the shipment amounts to correctly calculate the orderedInventory qty for A.

As a sidenote, this part is a bit strange also: `$orderItem->qty_ordered ? $orderItem->qty_to_cancel : $orderItem->parent->qty_ordered`
Why is the qty_to_cancel been taken if qty_ordered is existing? Wouldn't it be logical to take qty_ordered instead? Anyway, this line probably needs to be changed as qty_ordered as well as qty_to_cancel do *not* reflect the correct amount to reduce the orderedInventory if there already was a shipment (as described above).

## Bagisto Version
1.4.1

I can only advertise and stress the importance of unit tests for these kind of things. Please create unit tests for core functionality like this! Please consider unit tests to have high priority! Such tests are very suitable to find such kind of problems as presented here and also prevent regressions when refactoring happens.

best
Martin

**Comment by derMart** [comment]
This is a Bug not an optimization!

**Comment by derMart** [comment]
@Sanjaybhattwebkul Why did you remove the Bug label?

**Comment by Sanjaybhattwebkul** [comment]
@derMart 
Please **verify** me at once. then I will update

**Comment by Sanjaybhattwebkul** [comment]
@derMart 
I am **not getting** any issues. Please find the screen **recording** [Here](https://www.awesomescreenshot.com/video/8367104?key=76eb7b26be1b17116a358007c7f077d3).

**Comment by Sanjaybhattwebkul** [comment]
@derMart 
If any step is missing, then please let me know.

**Comment by derMart** [comment]
@Sanjaybhattwebkul your video *is* actually showing the problem. After the cancel of the order, the available amount should be 8. But the amount in the video is 10! See above in the expected results section. I added the expected amount.

**Comment by Sanjaybhattwebkul** [comment]
@

> @Sanjaybhattwebkul your video _is_ actually showing the problem. After the cancel of the order, the available amount should be 8. That is 10 in total minus the 2 pending of the second order. But the amount in the video is 10! See above in the expected and actual results sections. I added expected and actual amount there.

@derMart 
The product inventory is 10 **because** the shipping  is **not generated for order 2**

**Comment by derMart** [comment]
@devansh-webkul Could you please have a look at this issue?

**Comment by derMart** [comment]
@Sanjaybhattwebkul for further explanation: The Quantity shown in the product list of the backend in the video is showing the (what I call) available amount of a product, so as stated above it shows: product inventory amount - pending inventory amount. The quantity is *NOT* just the product inventory amount.

**Comment by devansh-webkul** [comment]
Hi @derMart,

Product inventory is the actual inventory in which the quantity is deducted at the time of shipment.

For the remaining two quantities the value is held in the `product_ordered_inventories` table. In the shop end, it will be handled with `product_inventory - product_ordered_inventory` which is in actual (`10-2=8`).

And this is the default behavior product inventory will only update when the shipment is generated.

**Comment by devansh-webkul** [comment]
In the backend, it will show 10 because the shipment is not generated yet.

**Comment by derMart** [comment]
@devansh-webkul There are two orders in the issue description not just one. Please re read the issue description. If the backend does not show pending amounts, then the video is not a proof that eveything is working. Please try to order 9 after the end of the video. According to you it should not work, but according to me it will work because the orderedInventories are not correctly updated when cancelling order1.

**Comment by derMart** [comment]
Thanks for checking again and sorry for problem with misunderstanding. Again, if anyone reading this: Exchange pending inventory with product ordered inventory. This will match bagisto table naming (In my head it is a pending inventory, as it stores the amount of the orders in pending state, not all orders). Currently, we work around this problem by adding the additional amounts needed to the orderedInventory before cancel via listener (this should *not* be the way to implement it in bagisto code base. There, returnQtyToProductInventory could very well be modified). As usually done here, I would also be grateful if you link the pull request / commit which fixes the issue here. It will make it easier for us to see that we need to remove that listener (look at new code bagisto code base to identify what needs to be changed on our side).

**Comment by Sanjaybhattwebkul** [comment]
@devansh-webkul 
Now, this issue is **fixed**. so I am **closing** this issue.
And I have **attached** a screen **recording**  [Here](https://www.awesomescreenshot.com/video/8468336?key=387c392048fcf91c829f1e7f918cbc0f). for future reference.
