### ISSUE TITLE
Elasticsearch not supported??

### ISSUE THREAD

**Issue by merdiano** [bagisto/bagisto#6300]
Elasticsearch is installed and working on port 9200. Scout driver config set to elastic. Run artisan command

`php artisan scout:import Webkul\\Product\\Models\\ProductFlat`

Error: 
In Manager.php line 109:
                                   
  Driver [elastic] not supported. 

## Bagisto Version

- [ x ] master branch
- [ x ] 1.4.2

**Comment by jitendra-webkul** [comment]
Please install elastic scout driver first

https://github.com/babenkoivan/elastic-scout-driver
