### ISSUE TITLE
Virus Detect upon uploading

### ISSUE THREAD

**Issue by PanosMusicMan** [bagisto/bagisto#6301]
# Virus Issue

### Bagisto v 1.4.2.

**Comment by ghermans** [comment]
@PanosMusicMan please provide more info

**Comment by PanosMusicMan** [comment]
@ghermans Hi Glenn, Unfortunately I have just downloaded the script form both Github as well as from the official site, however upon uploading on server, the server responded virus detected... Just this ...

**Comment by ghermans** [comment]
![image](https://user-images.githubusercontent.com/1594411/163685727-48870ad9-f97a-4d67-b04f-3c2e2d98f06b.png)

**Comment by devansh-webkul** [comment]
Closing this as this is not an issue, please use Bagisto forum.
