### ISSUE TITLE
Composer Update Not Working

### ISSUE THREAD

**Issue by Seunakomolafe1** [bagisto/bagisto#6305]
Bagisto has detected that the required composer dependencies are not installed.
Go to the root directory of Bagisto and run "composer install".

**Comment by devansh-webkul** [comment]
Can you please share more info so that I can check and also please fill out the full issue form?

**Comment by Sanjaybhattwebkul** [comment]
Hi @Seunakomolafe1  
Is your issue **resolved**.?

**Comment by devansh-webkul** [comment]
I am closing this as this is not reproducable, please use the Bagisto forum.
