### ISSUE TITLE
Uploaded logo not reflect on Website its reflected on Admin Panel

### ISSUE THREAD

**Issue by edfapay** [bagisto/bagisto#6314]
# Bug Report

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

**Comment by edfapay** [comment]
Issue found on Versionv1.4.2

**Comment by Sanjaybhattwebkul** [comment]
Hi @edfapay 
Have you reproduced this in the master version?

**Comment by Sanjaybhattwebkul** [comment]
@edfapay 
I am not getting any issues with the uploaded logo. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/8470609?key=4a9d806afd1375d08e6bc5e023191f7f).

**Comment by devansh-webkul** [comment]
Closing this as this is not an issue, please use the Bagisto forum for further discussion.
