### ISSUE TITLE
There is no option to move products to compare & wishlist on the product view page

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6329]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer in the default theme.
**2.** Click on any product.
**3.** Try to move compare and wishlist.

**Expected result:** There should be an **option** on the product view page to **move products to compare & wishlist**.

**Actual result:** There is no option to move products to compare & wishlist on the product view page. Please find the screenshot [Here](https://prnt.sc/HRfbQTbatWCn)

**Comment by devansh-webkul** [comment]
In the default theme, this is the expected design.
