### ISSUE TITLE
the public installer doesn't take the port

### ISSUE THREAD

**Issue by abdulhamid-alattar** [bagisto/bagisto#633]
the public installer doesnt take the port to check for the connection. so basically if the server is loaded to another port, the installer will fail to connect and know its valid configuration

**Comment by prashant-webkul** [comment]
@abdulhamid-alattar Are you saying about database port?

**Comment by abdulhamid-alattar** [comment]
yes

**Comment by abdulhamid-alattar** [comment]
> @abdulhamid-alattar Are you saying about database port?

yes

**Comment by prashant-webkul** [comment]
@abdulhamid-alattar Thanks for notifying about this issue and we will surely implement this in the next update.

**Comment by jitendra-webkul** [comment]
Fixed thanks to @abdulhamid-alattar
