### ISSUE TITLE
In Admin Panel When we click on the checkbox for approval or any other concern - The Headings must not hide.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6330]
**Issue Description**
In the admin panel when we click on the checkbox for the approval/disapproval or any other concern, The Heading must not hide.

**Bagisto Version - Master**

**Steps To Reproduce**
**1.** Go to Admin Panel - Select Catalog Section -> Select the checkbox.
**2.** There we can see that the heading goes missing when we select the checkbox.

**Actual Result**
Please look at the video for a better understanding of the concern.

**Video - v1.3.3**
https://user-images.githubusercontent.com/92721837/164381120-3f68bf3c-4ee0-4402-a535-464da68cc3db.mp4

**Expected Result**
It would be better if the headings also appear when the checkbox is being clicked.

**Comment by devansh-webkul** [comment]
This is not an issue. It is expected behavior.
