### ISSUE TITLE
 The location and the calendar Icon should be slightly right side in the Arabic locale when the customer is trying to book any product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6331]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer.
**2.** Click on any booking product.

**Expected result:**  The location and the calendar Icon should be slightly right side in the Arabic locale when the customer is trying to book any product.

**Actual result:** The calendar and the location are not in **proper alignment** in the Arabic locale if the user is trying to book the product. Please find the screenshot [Here](https://prnt.sc/JUWguI4bnx8E)

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul  Fixed
