### ISSUE TITLE
The country dropdown should be  in the Ascending order when the customer is adding the delivery address on the checkout page.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6333]
**Issue Description**
When we proceed to the checkout and there we fill in the address and select the country, the country format is appearing in Z-A. It must be in A-Z format.

**Bagisto Version - ** Master

**Steps To Reproduce**

**1.** Add any product to cart **->** Proceed to checkout **- >** Fill the address manually -> **Select Country**
**2.** In Country Dropdown we can observe that the Z-A format is appearing.

**Actual Result:**  The country dropdown is in Descending order. Please find the screenshot [Here](https://user-images.githubusercontent.com/92721837/164388658-9da557fa-2dd8-4222-a310-2e1740487435.png)

**Expected Result:**  The country dropdown should be in **Ascending** order.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/LFBv4tlU1ia9), for future reference.
