### ISSUE TITLE
update bagisto core using composer 

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#6338]
I understand that to update bagisto is necessary finalize a procedure creating  a new project and then use the old db and run php migrate commands.

I took this information inside the docs 
(https://devdocs.bagisto.com/1.x/introduction/upgrade-to-latest-bagisto.html#bagisto-changes)
 maybe i dont understand, but seems it is necessary download the new package and the apply the old database to change the schema.
It seems a very old approuch and not help if you are using a continuous integration process.

Using drupal , normally is possible to use composer update to download the last package core.
So i'm suggesting this kind of approuch.

https://www.drupal.org/docs/updating-drupal/updating-drupal-core-via-composer.

Thanks.

**Comment by devansh-webkul** [comment]
Possibly already proposed but can't provide in the `1.x` versions.

https://github.com/bagisto/bagisto/issues/4744#issuecomment-808081695
