### ISSUE TITLE
Invoice Design Can Be Enhanced

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6345]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer.
**2.** Click on orders inside the profile section.
**3.** View any order.
**4.** Click on the invoice tab. 
**5.** Click on the print button
**6.** Open the downloaded pdf

**Expected result:** The Invoice **logo should be in the center** of the page if the user is downloading the invoice

**Actual result:** The Invoice logo is not in the center of the page if the user is downloading the invoice. Please find the screenshot [Here](https://prnt.sc/uia4FH9cDqPY)

**Comment by devansh-webkul** [comment]
No need for this issue, the existing design looks fine.

**Comment by devansh-webkul** [comment]
Considering this as an enhancement as is not breaking anything.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/Y7RgWYIErS8A), for future reference.
