### ISSUE TITLE
Product price shows four decimal places [0.0000] should be two [0.00], when the admin is trying to edit the product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6359]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on the products inside the catalog.
**3.** Try to edit any product.
**4.** Reach on price section.

**Expected result:** price shows four decimal places 0.0000 should be two 0.00 

**Actual result:** The product price is showing the four decimal values [0.0000 ]. when the admin is trying to edit the product.Please find the screenshot [Here](https://prnt.sc/_5TC017PqyC_)

**Comment by AmooAti** [comment]
Hi @Sanjaybhattwebkul 
regarding this issue, I think it's ok because some currencies can have up to 3 or even 4 decimals, for example, Kuwaiti Dinar and Bahraini Dinar decimal places are 3
You see currencies decimals [here](http://www.londonfx.co.uk/ccylist.html)

**Comment by Sanjaybhattwebkul** [comment]
@AmooAti 
I will **discuss** this with my **team** and will **update**

**Comment by Sanjaybhattwebkul** [comment]
@AmooAti 
**Thanks** for the **report**.  I am **closing** this issue.
