### ISSUE TITLE
BAGISTO 1.3.1 SES Security Vulnerability with AWS (BAGISTO CLEARLY HAS A BUG THAT HAS PENTETRATED THEIR SOFTWARE 4-26-2022)

### ISSUE THREAD

**Issue by mikeyapina** [bagisto/bagisto#6360]
your hacker has made your tool virtually useless ... for me .. plys mailgun has not verifed my doamin in over 10 dyas either!!!  What are my options?

Hello,

Thank you for contacting us with regard to your sending pause in AWS Region  US West (Oregon).

Unfortunately, after a thorough review of the issue present on your account, the repeating nature of the issue, the severe negative impact such sending can cause, and the information you have provided, we have determined that we are unable to continue to support further sending via your account. As such we have denied your request to use Amazon SES in the US West (Oregon) region. We made this decision to ensure that other customers can continue to use Amazon SES without experiencing service interruptions.

We cannot assist you further with this issue, and we will not respond to additional messages on this subject.

We value your feedback. Please share your experience by rating this correspondence using the AWS Support Center link at the end of this correspondence. Each correspondence can also be rated by selecting the stars in top right corner of each correspondence within the AWS Support Center.

Best regards,
AWS Trust & Safety
Amazon Web Services
and now I have someone from that region telling me they can help me with an alternative solution!! What is going on here!!!!!
2:15 PM
BAGISTO 1.3.1 SES Security Vulnerability with AWS (BAGISTO CLEARLY HAS A BUG THAT HAS PENTETRATED THEIR SOFTWARE 4-26-2022)

**Comment by devansh-webkul** [comment]
The conversation is going on the ticket, I am closing the issue. 

If also this is a case vulnerability then it is recommended to have a conversation privately rather than disclosing everything.

**Comment by devansh-webkul** [comment]
If still some issue then follow single thread don't open multiple issues,
https://github.com/bagisto/bagisto/discussions/6348
