### ISSUE TITLE
The percentage of the discount should be visible on the product view page if there is any discount for the product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6367]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer.
**2.** Click on any product.
**3.** Try to view the discount percentage of the product.

**Expected result:** The percentage of the discount should be visible on the product view page if there is any discount for the product. Please take a reference from [here](https://prnt.sc/mgwbd6chI-Zh)

**Actual result:** The percentage of the discount is not showing on the product view page if there is any discount for the product. Please find the screenshot [Here](https://prnt.sc/bNDSiJSvfvyj)

**Comment by papnoisanjeev** [comment]
Due to multiple updates with function name and calculation this PR will no longer work so closing it.
Will create a new one for the same.

**Comment by shivamtiwariwebkul** [comment]
please assign me this task
