### ISSUE TITLE
At least one shipping and payment method should be available.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6370]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click sales inside the configuration.
**3.** Click on the shipping methods tab.
**4.** Disabled all the shipping methods
**5.** Visit the shop.
**6.** Try to place an order.

**Expected result:** The admin should not be able to **disable** all **shipping methods.**

**Actual result:** The admin is able to **disable all the shipping methods.** Please find the screenshot [Here](https://prnt.sc/aV_mAgcz6B7Y)

**Comment by AmooAti** [comment]
Hi @ghermans @devansh-webkul  
The last pr is (#6564) not suitable for preventing this issue 
Assume that we have another method called pickup where enabled and disable free shipping and flat rate then the error will pop up

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is fixed. I have attached a screenshot [Here](https://prnt.sc/prKJ31ErC9hb), for future reference.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
I am reopening this issue because I am getting the same issue with **payment method,**
@papnoisanjeev 
Please **fix** the same for the **payment method.**

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/dOKbjOsLFrrR), for future **reference**.
