### ISSUE TITLE
Bought items in Recent Bought Item should be listed on the cart page after the cart items

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6373]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer.
**2.** Add some items into the cart.
**3.** Go to the shopping cart.
**4.** Try to view recently bought items.

**Expected result:**  Bought items in **Recent History** should be **listed** on the cart page **after** the cart items.

**Actual result:** Bought items in Recent History should be listed on the cart page. Please find the screenshot [Here](https://prnt.sc/6-zaLgxM6DVd)

**Comment by jitendra-webkul** [comment]
Can be done with customization
