### ISSUE TITLE
npm commands are throwing errors in Velocity package in bagisto version: 1.2.0

### ISSUE THREAD

**Issue by ArpitShar** [bagisto/bagisto#6374]
When we are trying to run npm commands like "npm run dev", "npm run prod", "npm run watch" , etc. we are getting the following errors. Kindly help in resolving this issue we are facing.

## Bagisto Version
We are using Bagisto version 1.2.0

## Steps To Reproduce
Go to packages/Webkul/Velocity 
Go to terminal and run  any of the following 
- npm run dev
- npm run prod
- npm run watch

## Actual Result
The npm commands are giving the following errors.
![Screenshot from 2022-04-29 15-03-17](https://user-images.githubusercontent.com/99473254/165922060-6d23bd8b-12af-4627-a10e-634e08d343af.png)
![Screenshot from 2022-04-29 15-03-28](https://user-images.githubusercontent.com/99473254/165922071-e91dbb90-a9b6-4543-bc37-dd1cf294bdae.png)
![Screenshot from 2022-04-29 15-03-33](https://user-images.githubusercontent.com/99473254/165922080-ff4ed196-b728-461a-bf5c-d58726ede8e1.png)

## Expected Result
There should not be any errors and result should look like the attachment
![Screenshot from 2022-04-29 15-15-39](https://user-images.githubusercontent.com/99473254/165921854-0ad2f56c-f46d-4f66-ad4f-0af8da163f73.png)

**Comment by devansh-webkul** [comment]
This is due to not properly setup configuration. Please check your NPM version.

**Comment by ArpitShar** [comment]
Our npm version is 6.14.11 and the other that we have bagisto module 1.33 is also 6.14.11 
Is there any other way to check our setup configuration?

**Comment by devansh-webkul** [comment]
Are you sure, you have installed dependency properly? If not then try deleting the lock file and node_modules folder and then reinstall the dependency and then run `npm run prod/watch`.

**Comment by ArpitShar** [comment]
I tried the solution provided. But the problem persists.

**Comment by devansh-webkul** [comment]
Can you try the mentioned version node version,
https://github.com/bagisto/bagisto/tree/v1.2.0#requirements
