### ISSUE TITLE
 The MRP and special price both should be shown on the product view page, if there is any special price for any variant of the configurable products.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6377]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on products inside the catalog tab.
**3.** Create a configurable product.
**4.** Add a special price for anyone variant of the same product.
**5.** Visit the shop.
**6.** Try to view the same variant of the configurable product.

**Expected result:** The **MRP** and **special price** both should be shown on the product view page if there is any special price for any variant of the configurable products.

**Actual result:** Only the special price is shown on the product view page if there is any special price for any variant of the configurable products. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/8663613?key=9d47a24499a5ad4e93c060ef9c89fb05)

**Comment by akathuria289** [comment]
Same issue raised - https://github.com/bagisto/bagisto/issues/1929
