### ISSUE TITLE
The share wishlist option is overlapping the product's image  In product view page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6379]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer in the default theme.
**2.** Click on any product.
**3.** Try to save the product on the wishlist.

**Expected result:** the share wishlist option should not overlap the product's image.

**Actual result:** the share wishlist option is overlapping the product's image. Please find the screenshot [Here](https://prnt.sc/2tAQxatE4a3K)

**Comment by devansh-webkul** [comment]
This is the expected result as per the design.
