### ISSUE TITLE
The warning message should be correct if the admin is trying to edit the slider with an invalid image extension.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6380]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on the slider inside the settings tab.
**3.** Edit any slider.
**4.** Upload .svg image for slider

**Expected result:** The warning message should be correct if the admin is trying to edit the slider with an invalid image extension.

**Actual result:** The warning message is not correct if the admin is trying to edit the slider with an invalid image extension.Please find the screenshot [Here](https://prnt.sc/dl1606Uljo-N)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Followed the steps above (uploaded svg image) and getting a proper error.
https://prnt.sc/xI9ZaK2hCnle
