### ISSUE TITLE
The filters should work properly if the Visible Individually is on for any variant of the configurable product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6382]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Create a configurable item and on **Visible Individually** for any variant.
**3.** Login as a customer.
**4.** Search the created product by category.
**5.** Try to filter the product by price.

**Expected result:** The filters should work properly if the **Visible Individually** is on for any variant of the configurable product.

**Actual result:** The filters are not working for the variant of any configurable product. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/8693747?key=37223615630d6e5ea283f5f3d36512d0)

**Comment by merdiano** [comment]
Sorting by price in ascending order also not working properly

**Comment by Sanjaybhattwebkul** [comment]
Hi @merdiano 
Thanks for reporting we will fix it and will reflect it in the upcoming released

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
I have taken a **pull from the master** and now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/642e9a8483d74a61f238748e), for future reference.
