### ISSUE TITLE
Package Overriding

### ISSUE THREAD

**Issue by ArpitShar** [bagisto/bagisto#6396]
Hi, we just wanted to know how can we override a package in bagisto:1.3.3.
We are updating our base module bagisto:1.2.0 and wanted to override the packages so that we do not lose our changes in the process of updating. So we decided to just leave the base code and override our functionality within the packages.

**Comment by Sanjaybhattwebkul** [comment]
Hi @ArpitShar 
Please follow [This](https://forums.bagisto.com/topic/2959/how-can-i-override-a-whole-package-like-i-want-to-override-velocity-package-with-my-custom-package/2) thread.

**Comment by devansh-webkul** [comment]
Closing this issue. Please use the forum for queries as this channel is only for reporting bugs.
