### ISSUE TITLE
The success message should not be shown multiple times if the user is trying to remove the applied coupon.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6400]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer in the default theme
**2.** Click on any product.
**3.** Click on the buy now, button.
**4.** Apply any coupon code.
**5.**  Click multiple times on the remove icon for removing the applied coupon.

**Expected result:** The **success message** should not be shown **multiple times** if the user is trying to remove the applied coupon.

**Actual result:** The success **message** is showing **multiple times** if the user is trying to **remove** the **applied coupon**. Please find the screenshot [Here](https://prnt.sc/CJF4WUdwldWq)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

As checked with **default** theme not facing this issue please let me know if it exist with any other case.
https://www.awesomescreenshot.com/video/10139237?key=537ab3bb24208cee0a6ccc76b83dfc17

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please find the screen recording [Here](https://www.awesomescreenshot.com/video/10139663?key=7d5347a8265121d1381c105d9d631902) for reproducing the issue

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/WN12qA5l2V9e), for future **reference**.
