### ISSUE TITLE
The user should not be able to place the order if the user is inactive.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6407]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer
**2.** Add any item to the cat.
**3.** Click on place order.
**4.** Select the payment method.
**5.** log in as admin.
**6.** Inactive the same user.
**7.** Go to the shop as a customer
**8.** continue the order process.

**Expected result:** The user should not be **able** to **place** the **order** if the user is **inactive**.

**Actual result:** The user is able to place the order while inactive. Please find the screen recording [Here](https://www.awesomescreenshot.com/video/8797143?key=042fdabc2c5b1e3437d55c1247990f25)

**Comment by dejavuejs** [comment]
Write logic in customer middleware and logout the user by killing the session.
