### ISSUE TITLE
Getting exception on search in Products, Categories, Shipments & Product Reviews datagrids.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#642]
Framework Version: 0.1.4
![screenshot from 2019-02-28 14-58-38](https://user-images.githubusercontent.com/45203177/53559552-5a5e0d80-3b70-11e9-9503-13cccdd5405e.png)

**Comment by prashant-webkul** [comment]
Issue had been acknowledged and it was found that the issue exists in four datagrids in admin currently i.e Order Shipments, Products, Categories, Reviews.
All these four grids were changed without properly configuring them.

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.4
Fixed
