### ISSUE TITLE
Want Image upload filed required in product catalog module on admin side

### ISSUE THREAD

**Issue by dev-einn** [bagisto/bagisto#6448]
I want to make image field required for every product, so that website looks eye catching with images if any seller try to create product

**Comment by Sanjaybhattwebkul** [comment]
Hi @dev-einn 
We are also discussing this over the bagisto forum, so please follow [This](https://forums.bagisto.com/topic/2973/to-make-image-accordian-required-while-creating-products/8)

**Comment by Sanjaybhattwebkul** [comment]
@dev-einn 
As we are **already** discussing **[Here](https://forums.bagisto.com/topic/2973/to-make-image-accordian-required-while-creating-products/10)**  for the same, I am **closing** this query from here.
If **still** you have any **doubt** then feel **free to open it**
