### ISSUE TITLE
 The admin is able to create a Downloadable product without adding the download link of the product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6449]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on products inside the catalog section
**3.** Create a downloadable product
**4.** Do not add any **download** link inside the Downloadable Information section 
**5.** Click on the save as product button

**Expected result:** The **Downloadable Information section** should be **required** when the admin is trying to create a **downloadable** product.

**Actual result:** The admin is **able** to create a **Downloadable** product without adding the **download link** of the product. Please find the screenshot [Here](https://prnt.sc/aBVV1-yp9t6Y)

**Comment by jitendra-webkul** [comment]
Maybe the user is thinking of adding links later after creating a product. This is not needed so closing this issue
