### ISSUE TITLE
Getting Exception while adding product images by gui installer

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#645]
getting an exception when we add the product images, the error is showing only by GUI installer
![product images issue](https://user-images.githubusercontent.com/47665137/53640462-438fe780-3c52-11e9-8282-23d2d2270457.png)
unable to add product images, once we will click on **save produc**t, the error is showing
![issue34](https://user-images.githubusercontent.com/47665137/53640572-7fc34800-3c52-11e9-9419-bb5044339b51.png)

**Comment by prashant-webkul** [comment]
@jyoti-webkul Please verify the issue is persisting in new installations as well?
