### ISSUE TITLE
 The order status should be complete/processing after creating a transaction for the order.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6450]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Enable **Automatically generate the invoice** from  **configuration/sales/payment methods**
**3.** Visit the shop
**4.** Place an order with multiple quantities of item
**5.** Go to the admin panel and create a **shipment** for the order 
**6.**  Create a **transaction** for the same order only with the amount of 1 quantity.
**7.** Try to see the order status from the sales tab.

**Expected result:** The order status should be **complete** after creating a **transaction** for the order.

**Actual result:**  The order status is **Pending Payment** after creating a **transaction** for the order. Please find the below screenshot

![ss-two](https://user-images.githubusercontent.com/86394952/170441197-df42d53b-d55f-4ad1-969f-4ec3b620be7e.png)

![ss-one](https://user-images.githubusercontent.com/86394952/170441213-308fee88-0040-495a-a738-f85f67a37819.png)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 
As we have checked the same process mentioned in above and created a transaction and it shows completed.
Please verify again and if there is some spacial case mention it here https://prnt.sc/0JHhKjEV5Mox
