### ISSUE TITLE
Tax Price override to 0 after saveAddress API is triggered

### ISSUE THREAD

**Issue by Ruixian1006** [bagisto/bagisto#6457]
# Bug Report

## Issue Description
I'm using bagisto as a E-commerce backend and NextJs for my frontend, I realised that there is an issue every-time when I call the `saveAddress` API the tax price will be override to 0. While when I added the product into cart the tax is updated in `carts` table, but only when I triggered the `saveAddress` API, the `tax_total` in `cart` table will be override with 0.

## Preconditions
- Test with provided API from bagisto
- There must have a tax product in cart
## Bagisto Version
- [ ] 1.3.2

## Steps To Reproduce
1. Add Tax Product into Cart with Bagisto API
2. Call bagisto `saveAddress` API
3. Check the `tax_total` in your database table `cart`

## Actual Result
- Tax total in Cart override to 0

## Expected Result
- Tax price being calculated accordingly

**Comment by Ruixian1006** [comment]
Hi @Sanjaybhattwebkul , may I know have you find the reason for this issue ?

**Comment by Sanjaybhattwebkul** [comment]
@Ruixian1006 
**Thanks** for reporting, we will **fix** this issue in the **upcoming** **release**.

**Comment by Ruixian1006** [comment]
Hi @Sanjaybhattwebkul thanks for your reply.  May I know have you try to reproduce the error on your end ? Cause I am not sure is this only apply to me.

**Comment by Sanjaybhattwebkul** [comment]
@Ruixian1006 
**yes**, this issue is on our **bagisto** version **V1.4.3**, and I have **raised** an [issue](https://github.com/bagisto/bagisto/issues/6499) for the same.

**Comment by Ruixian1006** [comment]
Noted with Thanks. Hope this can be fixed soon.

**Comment by Sanjaybhattwebkul** [comment]
Hi @Ruixian1006 
Which version of **bagisto** are you using

**Comment by Ruixian1006** [comment]
Hi @Sanjaybhattwebkul , my bagisto version is 1.3.2, and I'm implement with API to my frontend.

**Comment by Sanjaybhattwebkul** [comment]
Hi @Ruixian1006 
Please allow me some time I need to verify this with V1.3.2 because there is no issue with our latest version.

**Comment by Ruixian1006** [comment]
Hi @Sanjaybhattwebkul , is there any updates on this issue ? I have tested previously with the [demo account](https://demo.bagisto.com/) from bagisto also having the same issue which I think the version is 1.4.2

**Comment by Sanjaybhattwebkul** [comment]
@Ruixian1006 
We will fix this issue in our next release.

**Comment by Ruixian1006** [comment]
Hi @Sanjaybhattwebkul,noted with thanks. May I know when will be the next release ?

**Comment by papnoisanjeev** [comment]
@Ruixian1006  @Sanjaybhattwebkul 

Please verify your address (country/states) and re-check if tax applicable for the same **country/state**. 
If it differs Tax will be removed when you select a different address (country/states) other than the applicable tax region.
