### ISSUE TITLE
Warning: array_combine() expects parameter 1 to be array, null given ( install.php on line 32 )

### ISSUE THREAD

**Issue by DrAyman2016** [bagisto/bagisto#646]
Notice: Undefined variable: key in C:\laragon\www\bagisto\public\installer\install.php on line 32

Notice: Undefined variable: value in C:\laragon\www\bagisto\public\installer\install.php on line 32

Warning: array_combine() expects parameter 1 to be array, null given in C:\laragon\www\bagisto\public\installer\install.php on line 32

**Comment by prashant-webkul** [comment]
@DrAyman2016 Thank you for filing the issue. We will be soon doing a fix on this.

**Comment by jitendra-webkul** [comment]
Already fixed in the master branch. We will soon release the 0.1.5 version.

**Comment by AMAFsoft** [comment]
Any news on this??

**Comment by rahulshukla-webkul** [comment]
This issue has been fixed in master branch. Next Week, We will release  0.1.5 version. Right now you can download or clone master branch to avoid this issue.

**Comment by rahulshukla-webkul** [comment]
Hi @AMAFsoft  
We have released our new version.Please download new version of bagisto.
