### ISSUE TITLE
UI - In Table Booking Product, Special Request/Notes must be in Bold for Main Cart.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6464]
**Issue Description**
When we book a Table Booking Product there we fill the Special Request/Notes, It must appear Bold in the Main Cart.

**Bagisto Version - Master**

**Steps To Reproduce**
**1.** Go to Customer Profile -> Table Booking Product -> Enter the details of Special Request/Notes.
**2.** Now Book Now -> Check the Main Cart -> There it must appear in Bold.

**Actual Result**
For a better understanding of the concern please refer to the screenshot.

**Screenshot**
![Bold](https://user-images.githubusercontent.com/92721837/171796816-c660a29d-2c45-46d2-a9a0-3e781dc52374.png)

**Expected Result**
For a better appearance and for the Special Notes and Requests it will be clearly visible while booking. Hence it must be slightly bold.

**Comment by Sanjaybhattwebkul** [comment]
@ashishkumar-webkul 
The **customer attributes** can not be bold.

**Comment by ashishkumar-webkul** [comment]
@Sanjaybhattwebkul 
As per the **discussion**, Understood the reason for not implementing this.
