### ISSUE TITLE
Event Booking product is having Price Calculation Issue. Event Price is  getting multiplied as per Tickets QTY.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6466]
## Issue Description
When we Book the Event Booking Product there we can see that the calculation issue is found. The Event Price is getting added to the Tickets Price and also the Event Price is getting Multiplied as per the ticket QTY.

**See The Calculation**

**1. Event Price -** $150
**OneTicket Price -**  $8
**Two Ticket Price -** $16

**Total Subtotal comes Out** 
For One ticket - $150+$8 = $158
For Two tickets - (2 x$150) + $16 = $316 - **Issue is here**

## Bagisto Version
**Master**

## Steps To Reproduce
**1.** Visit the shop.
**2.** Add any **event product** to the cart with a **different-2 ticket quantity**.
**3.** View the shopping cart.

## Actual Result
Please Refer to the Screenshot for a better understanding of the issue.
https://prnt.sc/2JRnrkOaNtxO

## Expected Result
The Event Price must be applied once and the ticket price should be separated from the Event Price. The event Price must not involve in the Tickets QTY.

**Comment by prabhatkumaroc082** [comment]
Event price needs to be added per ticket, store owner could manage the event and ticket price accordingly.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
As we discuss this is not an issue, so closing this issue.
