### ISSUE TITLE
The pagination should work properly if the admin is trying to view all the notifications.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6468]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on the **notification** icon in the header.
**3.** Click on the view all **notifications** link
**4.** Click on **2 page** of **pagination**.

**Expected result:** The **pagination** should **work** properly if the admin is trying to view **all the notifications.**

**Actual result:** The **pagination** is **not** working properly if the admin is trying to **view** all the notifications. Please find the screenshot [Here](https://prnt.sc/duz1wAizN3pN)

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul It`s working fine as you can see in the reference video - https://www.awesomescreenshot.com/video/10120075?key=873f6922ab0fe9f7cb9714067c773623

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please check with different-different order status

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

We have tested and tried it with different-2 order status still not facing this issue if any case your are still facing it please mention test case.

https://www.awesomescreenshot.com/video/10244834?key=e1ec61cc8ab82902ad224e3e7f2b9cb5

**Comment by devansh-webkul** [comment]
This is working fine, please mentioned all steps when you reopen this.

Closing this issue for now.
