### ISSUE TITLE
Translation Issue in the Configure Section related to Number.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6469]
## Issue Description
In Configure Section at the Admin Panel, there we can see the text line "Allowed **No** of New Product in Homepage", here the text **No** should not be used, instead of that Please use **No. or Number** 

## Bagisto Version
**MASTER**

## Steps To Reproduce
**1.** Go To Admin -> Configure -> Catalog -> Products -> Hompage Configurations.

## Actual Result
For the issue Kindly Consider the Image for understanding the issue.

**Image**
![Translation](https://user-images.githubusercontent.com/92721837/171836413-0b21c25e-2db4-45ef-9870-37b01115c43f.png)

## Expected Result
Please use the abbreviation or complete text for the number. For correct reference, I am attaching a sample.

**Sample**
![abb](https://user-images.githubusercontent.com/92721837/171836544-3e64ec13-fd24-4f5e-807d-202df74f1e39.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue **is fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/KP8cl-4BV3rI), for future reference.
