### ISSUE TITLE
Special price not working

### ISSUE THREAD

**Issue by tousifhasanzai** [bagisto/bagisto#647]
Special price is showing on product page but on checkout and cart page special price doesn't work neither it is sowing
![image](https://user-images.githubusercontent.com/18395540/53759005-258be680-3ee1-11e9-866c-1e411a9f00f3.png)
but when you move to the cart page
![image](https://user-images.githubusercontent.com/18395540/53759044-3c323d80-3ee1-11e9-907e-8cd638fc1ba9.png)

**Comment by prashant-webkul** [comment]
Issue is fixed and had been merged in PR #650

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.4
Fixed
