### ISSUE TITLE
Error when adding product policy price in rupees sign (₹)

### ISSUE THREAD

**Issue by dev-einn** [bagisto/bagisto#6475]
I have tested this bug on your live demo - demo.bagisto.com/
and also on v1.3.3 of bagisto.

Scenario:
I have edited product policy first line (Free Shipping on Order $20 or More) in velocity meta data from admin in rupees sign (Free Shipping on Order ₹20 or More) and on the user side it is mixing the symbol with price I am attaching the screenshots for both user and admin side .

![Screenshot from 2022-06-07 23-41-43](https://user-images.githubusercontent.com/72020482/172453836-2ebbc341-b1d0-4dc1-8519-2111181dd4e4.png)

![Screenshot from 2022-06-07 23-41-32](https://user-images.githubusercontent.com/72020482/172453886-ec67b2ba-ebdf-4778-adb7-0a29d1c02d2a.png)

**Comment by Sanjaybhattwebkul** [comment]
This issue is duplicate: https://github.com/bagisto/bagisto/issues/5324

**Comment by dev-einn** [comment]
This issue has resolved product policy meta data error but in product card it is still there , the special price is coming right but original price is still being overlapped

![Screenshot from 2022-06-08 12-15-37](https://user-images.githubusercontent.com/72020482/172550072-297b4e59-004c-455a-be1a-a7750d86c289.png)
