### ISSUE TITLE
Receiving Object in Options

### ISSUE THREAD

**Issue by vtaskme** [bagisto/bagisto#6498]
# Bug Report
I'm sharing an image URL which is clear doubt what issue I faced.
I'm getting object on select option value in datagrid 

## Issue Description
please check this 
https://prnt.sc/959mFV1m_3A4

## Bagisto Version
- V. 1.4.1

## Steps To Reproduce
I have datagrid listing and I want select option value but value contain object

## Actual Result
getting object not value

## Expected Result
expecting value="update"/"delete" not [object object]

**Comment by Sanjaybhattwebkul** [comment]
Hi @vtaskme 

We are **already** talking about this **over the ticket.** so I am **closing** this issue from here.

**Comment by vtaskme** [comment]
Hello @Sanjaybhattwebkul ,
why did you close this ticket, I'm not satisfied with your answer, kindly solve my issue.
I'm expecting resolution not clarification.

**Comment by vtaskme** [comment]
Hello @Sanjaybhattwebkul 
[Link](https://webkul.uvdesk.com/en/customer/ticket/view/373918)
This is my issue related chats.
your support team is not suppoting, They are selling their services.

Kindly improve your support.
