### ISSUE TITLE
The tax price is overriding with 0 when the customer is saving the billing/shipping address.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6499]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer.
**2.** Add any taxable product into the cart.
**3.** Proceed to checkout.
**4.** Save the billing address.

**Expected result:** The **tax price** should not **override** with **0** when the customer is **saving** the **billing/shipping address.**

**Actual result:** The tax price is **overriding with 0** when the customer is saving the **billing/shipping address**. Please find the below screenshot.

![error-one](https://user-images.githubusercontent.com/86394952/174726514-92257d76-4d3d-4c45-8945-c3514eb212e4.png)

![error-two](https://user-images.githubusercontent.com/86394952/174726558-65bcd40f-559d-4809-91ec-7ed54f278fe7.png)

**Comment by papnoisanjeev** [comment]
@papnoisanjeev 

Logged in as a customer and added a product with tax and when saving my billing address tax is same as it is  in checkout process also showing in total amount after placing an order.

Please mention if there is any spacial case for the same so that we can reproduce again and check.

**Comment by Sanjaybhattwebkul** [comment]
This issue is duplicate : https://github.com/bagisto/bagisto/issues/6457
