### ISSUE TITLE
There should be an option to upload the image if the admin is trying to add velocity metadata in the footer left content section

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6510]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on velocity 
**3.** Reach  on footer-left-contant section.
**4.** Try to insert image 

**Expected result:** There should be an **option** to upload the **image** if the admin is trying to add **velocity** metadata in the **footer left content  section** 

**Actual result:** The admin is not able to upload for footer from the velocity footer-left-content section. Please find the screenshot [Here](https://prnt.sc/JA8ED3FoEVUc)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

It is not a bug as in source field you need to put image link.

**Comment by devansh-webkul** [comment]
Considering this as enhancmenet.
