### ISSUE TITLE
Setup crashes after installation

### ISSUE THREAD

**Issue by TheIceMagmaCube** [bagisto/bagisto#6512]
# Bug Report

## Issue Description

While installing Bagisto, after typing user informations, the setups crashes and does nothing. I can't access mailing setup, and so config the shop's adress.

![image](https://user-images.githubusercontent.com/38074756/177143168-c7a06353-124a-4410-bd54-6d80363faf3c.png)

After trying to manually edit settings in the .env file, nothing happens, or the message is deplayed when I try to reset a password.

![image](https://user-images.githubusercontent.com/38074756/177143496-43fd6561-6f26-45eb-94f4-45dc41dfe5dc.png)

## Preconditions

php8.1-fpm
Debian 11 (up to date 04/07/2022)
nginx 1.18

## Bagisto Version

1.4.3

## Steps To Reproduce

Just tried to installed bagisto by unpacking the .zip file, give permissions to www-data and run the GUI installer from the /public 
Setting up the db, and letting the system install.

At the end of install, setup ask user's informations. After putting everything in fields and click next, setup froze and doesn't ask for email information. After a while, it returns a 404 error, and ask to get back to main shop

## Expected Result

Prompt the wizard to setup the mail configuration.

Thanks for your help

**Comment by Sanjaybhattwebkul** [comment]
Hi there, 
Is it possible to share the **steps** which you follow to install **bagisto**?

**Comment by TheIceMagmaCube** [comment]
Hey,
Here's step by step what i'm doing
##Steps
1. Copy last version of bagisto to the folder /bagisto
2. unzip the file
3. cd .. and chown -r www-data:www-data bagisto
4. cd bagisto and composer install
5. Open the webinstaller and follow the steps

##SQL
I'm using alwaysdata for the database, so i'm entering my SQL informations and let everything install.

**Comment by Sanjaybhattwebkul** [comment]
Please follow the given steps.
1. git clone --branch v1.4.3 https://github.com/bagisto/bagisto.git
2. cd bagisto
3. **_composer create-project_**
4. Edit the .env file inside the bagisto folder  [ configure Database_Name, App_Url and email configuration ]
5. _**php artisan bagisto:install**_
6. **_php artisan serve_**

**Comment by TheIceMagmaCube** [comment]
Problem solved.
But I got another problem afterwards, when I try to add a profil picture, it displays succesfully, but the server can't load it.
![image](https://user-images.githubusercontent.com/38074756/177163013-9724ec5e-7b8b-44df-9b97-fa3ec8aa08b1.png)
![image](https://user-images.githubusercontent.com/38074756/177163030-fbb6eace-9c0c-4c30-a56a-689b5ba1f876.png)

More, the same bug is in the products page i can't add pictures to my products.
![image](https://user-images.githubusercontent.com/38074756/177163138-a503c124-5ab8-4000-91f7-7d5391601697.png)
![image](https://user-images.githubusercontent.com/38074756/177163206-771d7abc-354d-4377-a889-dd435d1b3d87.png)

Thanks for your help

**Comment by Sanjaybhattwebkul** [comment]
HI @TheIceMagmaCube 

I guess the image you are uploading is too large
