### ISSUE TITLE
There should not be an exception if the admin is trying to create a refund for any order.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6513]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on orders inside the sales tab.
**3.** View any order.
**4.** Try to create a refund for the order after creating shipping and invoice.

**Note:**  the **payment method** of the order should be **money transfer.**

**Expected result:** There should not be an **exception** if the admin is trying to **create a refund** for any order.

**Actual result:** There is an  **exception** if the admin is trying to **create a refund** for any order. Please find the below screen recording. 

https://user-images.githubusercontent.com/86394952/177253113-8f537584-e199-4242-a9a2-b8f2e6899160.mp4

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
I guess you didn't select the **money transfer payment method** for the order, **for which** you are creating the refund. please **follow the given steps**

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 
Selected **money transfer** as a payment method, Please check here:  https://prnt.sc/9x7NHPT3jxSo

**Comment by Sanjaybhattwebkul** [comment]
Ok, **my fault** I reverify this issue Actually the issue is occurring only while we are selecting the  PayPal Smart Button payment method.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Also tried with **PayPal Smart Button** payment method.
No error found during refund.

https://prnt.sc/BvAnucSiQdFB
https://prnt.sc/WCNv_3ty7i0b

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
OK, allow me some time I will reverify it again and let you know.
