### ISSUE TITLE
Black bar in Admin Dashboard

### ISSUE THREAD

**Issue by ersaurav36** [bagisto/bagisto#652]
In the latest version as installed from master, a black bar is coming on Admin Dashboard. 
![asdadfq](https://user-images.githubusercontent.com/32482149/53860096-dbe8ec00-4005-11e9-8a75-7372c3f40401.png)

**Comment by prashant-webkul** [comment]
This issue had been fixed in my commit https://github.com/prashant-webkul/bagisto/commit/17755bcc2d8edfe2a2f71f5a891844b552097774 and will be reflected upon the next merge #653
