### ISSUE TITLE
Swiftmailer abandoned, switching to symfony/mailer

### ISSUE THREAD

**Issue by seapandaio** [bagisto/bagisto#6543]
When running composer to install bagisto, this message appears-
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Shouldn't be a major issue for the near future, but perhaps an important consideration for future versions.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Can you please elaborate?  I guess you want to install Bagisto right ?

**Comment by seapandaio** [comment]
This is just a warning that appears when installing Bagisto. It doesn't prevent it from being installed and as of now doesn't pose a security threat or anything of the sort.

**Comment by devansh-webkul** [comment]
We are using Laravel 9 and by default, it is Symfony mailer. So please check your instance. Maybe you are using the old version.
