### ISSUE TITLE
Cart Rule -. Validation should be applied in Coupon Code uses per customer and used per coupon section.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6556]
## Issue Description
In Cart rule -> Coupon Code section there in uses per coupon and per customer, there we are able to fill and save the alphabetical and symbols. Hence Validation to be applied.

## Steps To Reproduce

**1.** Admin -> Marketing Section -> Cart rule .
**2.** Coupon Codes -> uses per customer and uses per coupon
**3.** They are accepting alphabets and symbols.

## Actual Result
Please consider the video for a better understanding of the issue.
**Video Link - https://www.awesomescreenshot.com/video/9937758?key=3e802a58c974648b7ab5d743fa42e07d**

## Expected Result
Only Numerical Values must be added here.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/c4JnjLNUFEBK), for future reference.
