### ISSUE TITLE
The attributes should be selected automatically if we have only one option for select

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6557]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Visit shop
**2.** Click on any configurable product
**3.** Select the variant which has only one attribute.

**Expected result:** The **attributes** should be **selected** **automatically** if we have **only one** option for select

**Actual result:** The attributes are **not selected** **automatically** if we have **only** **one** option for selection. Please find the screenshot [Here](https://prnt.sc/MBCJH9JSDPcB)

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul We can also use [is default](https://prnt.sc/4E-jz-afoc63) feature for the above issue
