### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by mihir1811** [bagisto/bagisto#660]
When click on "REGISTER" button it is also validates newsletter field and also same issue in Login screen.
http://prntscr.com/mux4t9

**Comment by rahulshukla-webkul** [comment]
@mihir1811  Thanks for raising issue.We will fix it soon.

**Comment by jay-thanki** [comment]
@rahulshukla-webkul can you please check my pull request so you can merge?

**Comment by prashant-webkul** [comment]
This issue had been fixed by the merge request of issue filer @jay-thanki in PR #662 #663
