### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by dr-roshyara** [bagisto/bagisto#6629]
# Bug Report
I got the following error while installing 
Fatal error: Uncaught mysqli_sql_exception: Table 'bagisto.admins' doesn't exist in 
\public\installer\install.php:61 Stack trace: #0 
\bagisto\public\installer\install.php(61): mysqli->query('SELECT id, name...') #1 
bagisto\public\index.php(19): 
require('C:\\xampp\\htdocs...') #2 
\bagisto\server.php(21): require_once('C:\\xampp\\htdocs...') #3 {main} thrown in 
\bagisto\public\installer\install.php on line 61

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Is it possible to **share** the **steps** which you followed for installing the **Bagisto**?

**Comment by Sanjaybhattwebkul** [comment]
**Closing** this issue as **not getting** any **response** from the **last 14 days.**

**Feel free** to **reopen** if you have any queries.
