### ISSUE TITLE
Manufacturer / Brand section

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#6634]
Prestashop has Manufacturer/ Brand entity able to add Manufacturer Logos, description, name.
This entity is related to product b default.

No need to create an attribute.
Brand is related to each product.

On the frontend there is a page list able to show all brands, and inside product page brand is displayed optionally.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Now, this is feature is **not available.** you can Create a **Custom** Module for the same
