### ISSUE TITLE
css issues after recent relase

### ISSUE THREAD

**Issue by tousifhasanzai** [bagisto/bagisto#664]
on cart page all images are messing up
![image](https://user-images.githubusercontent.com/18395540/54016177-ec36cd80-41a3-11e9-92a9-344242a3c802.png)

**Comment by rahulshukla-webkul** [comment]
@tousifhasanzai  Thanks for raising issue.Can you tell me how did you install bagisto & are using latest release?

**Comment by tousifhasanzai** [comment]
I did install using composer. it was working find until I pull the latest release #647. from your repo

**Comment by tousifhasanzai** [comment]
There should be a class on image src. "item-image"
[image: image.png]

**Comment by rahulshukla-webkul** [comment]
Do one thing-
Go inside public folder, delete default folder inside themes & webkul folder inside vendor & publish once again. (php artisan vendor:publish)

**Comment by tousifhasanzai** [comment]
Thank you soo much, you save my day!
