### ISSUE TITLE
Error when you create or update a new catalog categories

### ISSUE THREAD

**Issue by ahed666** [bagisto/bagisto#6642]
SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION medicame_db.get_url_path_of_category does not exist (SQL: update `categories` set `categories`.`updated_at` = 2022-08-11 11:40:02 where `id` = 67)

**Comment by devansh-webkul** [comment]
Your database is missing a function due to which this error occurs. Please check the forum for this as this issue is pretty common.
