### ISSUE TITLE
 The catalog rule is not applying after updating the product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6650]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on **promotion** inside the **marketing tab.**
**3.** Create a **catalog rule** for any **variant** of the **configurable** product.
**4.** Go to the **shop** and **view** the same configurable product.
**5.** Go to the **admin** panel and **update** the **price** of the **same** configurable product.
**6.** **Visit** the **shop** and view the **updated** product.

**Expected result:** The **catalog rule** should be **applied** if the admin is **updating** the product's price.

**Actual result:** The catalog rule is **not applying** after updating the product.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

We need to **re-index catalog rule** after **price** updates in product.

Please run below command:

`php artisan product:price-rule:index`

Command will automatically trigger using cron in case of production.
