### ISSUE TITLE
There should not be any exception if the admin is creating the configurable product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6651]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on the products inside the catalog.
**3.** Create a configurable product.

**Note: Upload image of all varients and main product.**

**Expected result:** There should not be any **exception** if the admin is **creating** the **configurable** product.

**Actual result:** There is an **exception** if the admin is **creating** the **configurable** product. Please find the screenshot [Here](https://prnt.sc/k5PKrfCeO3-S)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Not facing this issue on my system with latest updates.

Try below solution and hope it will help.

- Try simply rebooting Or restarting your server.
- Just provide **read/write** permission to folder.
- Check **php.ini** make sure that your **upload_max_filesize** is as big as your **post_max_size**.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
I **restarted** my **server** and now the admin is **able** to **create** the **configurable** product with **multiple** **variants** Please find the screenshot [Here](https://prnt.sc/C74w9nXXsFoZ).so I am **closing** this issue.
