### ISSUE TITLE
Bagisto on vapor file_put_contents(/tmp/storage/app/db-blade-compiler/views/92263d5a0f797): Failed to open stream: No such file or directory (View: /var/task/resources/themes/velocity/views/home/index.blade.php)

### ISSUE THREAD

**Issue by zielu92** [bagisto/bagisto#6653]
## Issue Description
I was trying to deploy bagisto on vapor. The homepage return error: 

`file_put_contents(/tmp/storage/app/db-blade-compiler/views/92263d5a0f7971979a9faaee5f4): Failed to open stream: No such file or directory (View: /var/task/resources/themes/velocity/views/home/index.blade.php)`

The admin page works correctly (there was some issue, but I found how to fix it). 
I think the issue might be with laravel-db-blade-compiler. 

## Bagisto Version
- [*] 1.4.3

## Steps To Reproduce
Deploy project on Vapor

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Which **version** of **bagisto** are you using?

**Comment by zielu92** [comment]
> Which **version** of **bagisto** 
1.4.3
Additionally, runtime on vapor is done via docker

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
I guess this is a **permission issue**

**Comment by Sanjaybhattwebkul** [comment]
Please verify all the **permissions**.

**Comment by zielu92** [comment]
It seems permissions are ok. Vapor runs on AWS, which makes it a bit more challenging.
Additionally, I checked the S3 drive locally for assets and this part works well. After it is deployed to ECR it seems there is an issue and it seems it is not a permission issue.

**Comment by Sanjaybhattwebkul** [comment]
Please **run** these **commands** once, 
If you will get the same issue after it then **please let me know.**

**_php artisan vendor:publish_**  Then press 0

**Comment by devansh-webkul** [comment]
Your storage folder is missing with db blade compiler. Please check if have you published all the assets properly.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please **run** this **command** the issue will be resolved:
_**php artisan bagisto:publish --force**_

**Comment by Sanjaybhattwebkul** [comment]
@zielu92 
Is your issue is **resolved**?

**Comment by zielu92** [comment]
Not yet, since it is in aws and based on vapor it is serverless, executing commands like bagisto:publish or vendor:publish will end up with error because the resource directory is read-only. Only one dir is writeable it is 'tmp'. Acording to article: [https://bagisto.com/en/whats-new-in-laravel-6-x/](https://bagisto.com/en/whats-new-in-laravel-6-x/) it seems the newer version of bagisto should also work on vapor am I right? Since admin page works correctly I still think the problem might be with themes.

**Comment by exodusanto** [comment]
Laravel vapor will only create these folders

```
Creating storage directory: /tmp/storage/app
Creating storage directory: /tmp/storage/logs
Creating storage directory: /tmp/storage/bootstrap/cache
Creating storage directory: /tmp/storage/framework/cache
Creating storage directory: /tmp/storage/framework/views
```

The only writable folder in Lambda is `/tmp`, Vapor knows that and the `storage_app` function is already prefixed with `/tmp`. But `storage/app/db-blade-compiler/views` is not created automatically in the container, so you will need to create it, this can be done in `AppServiceProvider.php`.

```php
...
class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
       // Create storage/app/db-blade-compiler/views directory if it doesn't exist
       if (!file_exists(storage_path('app/db-blade-compiler/views'))) {
         mkdir(storage_path('app/db-blade-compiler/views'), 0777, true);
       }
    }
}
```

**Comment by zielu92** [comment]
@exodusanto Thank You for providing this solution, maybe in the future I will test it but for now, I abandoned vapor.

**Comment by devansh-webkul** [comment]
Looks like db blade views folder is missing. Please check your instance as this is not reproducible and use the Bagisto forum channel.
