### ISSUE TITLE
Create possibility of choose the qty os address line

### ISSUE THREAD

**Issue by cagartner** [bagisto/bagisto#666]
Here in Brazil, we use four lines of address.

I think the better aproach for globalize the address line is change the column for a JSON (textarea input), and create a option to the user can define the quantity of street line, like works on Magento application.

What you guys think?

**Comment by jitendra-webkul** [comment]
Hi @cagartner ,

We are implementing this feature and it will be present in the next release.

Thanks for your suggestion.

**Comment by jyoti-webkul** [comment]
Framework version: 0.1.5
Implemented
![Screenshot (6)](https://user-images.githubusercontent.com/45203177/54531323-009c7680-49ab-11e9-8d13-6fab6dfe85c9.png)
![Screenshot (8)](https://user-images.githubusercontent.com/45203177/54531331-04c89400-49ab-11e9-9371-bc8c8bbcc69a.png)
