### ISSUE TITLE
Issue in migration add_min_price_and_max_price using PostgreMysql

### ISSUE THREAD

**Issue by hamza-saqib** [bagisto/bagisto#6660]
# Bug Report

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

**Comment by jitendra-webkul** [comment]
Can you please explain more on this issue

**Comment by devansh-webkul** [comment]
Closing this. Please use the Bagisto forum.
