### ISSUE TITLE
product attachments

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#6661]
I would to know if is possibile upload some documents to a product for example pdf or doc file.

there is already a way to solve this ?
regards.
.g

**Comment by Sanjaybhattwebkul** [comment]
Hi @ghena 
**No**, we **can not upload** the pdf and doc for any product.

**Comment by ghena** [comment]
I suppose it should be easy , cloning image model and edit the product repositories ? or not ?

**Comment by devansh-webkul** [comment]
You can create a custom attribute of the type file if you want.

If the requirement is still not matched then you can customize the product as per your need.
