### ISSUE TITLE
Getting composer error with 2Gb of RAM.

### ISSUE THREAD

**Issue by nsk99** [bagisto/bagisto#667]
When i try to install composer dependencies i get the following error:  
 
 - Installing symfony/polyfill-ctype (dev-master 82ebae0)
    Cloning 82ebae02209c21113908c229e9883c419720738a
The following exception is caused by a lack of memory and not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

The fix for this error is making a swap partition with ~1024Mb, so change the requirements for 3Gb of RAM.

Configs:
2Gb of RAM DDR2
Intel Atom N280
Ubuntu 16.04 LTS

**Comment by prashant-webkul** [comment]
Thanks for testing it out on a 2GB system for us.
We will surely update the requirements.
But i recommend you to create the swap memory for it to run on your system.

**Comment by nsk99** [comment]
Yeah, i did it.

**Comment by prashant-webkul** [comment]
@nsk99 So are you able to run it on your system now.

**Comment by pedroroccon** [comment]
You're using Linux?

**Comment by dungmediabridge** [comment]
Should composer.lock be committed to version control?

**Comment by prashant-webkul** [comment]
@dungmediabridge No, only composer.json had to be present in version control.
Lock file is meant for own system only and it shouldn't be either in VCS or Git.

**Comment by nsk99** [comment]
> You're using Linux?

yes.

**Comment by prashant-webkul** [comment]
> > You're using Linux?
> 
> yes.

Please create swap memory file and you will then be able to run Bagisto.

**Comment by pedroroccon** [comment]
Like @prashant-webkul said, I think that you have to create the swap memory. Probably in the installation, the swap wasn't be configured.

**Comment by nsk99** [comment]
> The fix for this error is making a swap partition with ~1024Mb, so change the requirements for 3Gb of RAM.

As i said, the solution is the creation of swap partition. You don't have to ask me to do what's already done.

**Comment by prashant-webkul** [comment]
@nsk99 We had updated our readme file with system RAM requirements atleast 3GB. And for low memory systems we all know that swap file is necessary.
