### ISSUE TITLE
CORS Policy issue while calling register API through react.

### ISSUE THREAD

**Issue by hamza-saqib** [bagisto/bagisto#6675]
# Bug Report
CORS Policy issue while calling register API through react. from postman its working. Bagisto Laravel is deployed on shared hosting, URL: http://bagisto.wayneincorporation.com/public/ and i am running react app on local.

## Bagisto Version
as per this commit 
https://github.com/bagisto/bagisto/tree/521eb9b2d8f6d9294bd87c22332844be8a3c9fcf

## Steps To Reproduce
install Bagisto on shared hosting. call register API through react.js APP.

## Actual Result
should be getting message "account created successfully"

## Expected Result
network error while calling API.
sign-up:1 Access to XMLHttpRequest at 'http://bagisto.wayneincorporation.com/public/api/customer/register' from origin 'http://localhost:3000/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Which **version** of **Bagisto** are you using?

**Comment by hamza-saqib** [comment]
@Sanjaybhattwebkul i'm not sure with version but i m using latest code from master branch. also i have mention the commit point in above on my question description.

**Comment by devansh-webkul** [comment]
Hi @hamza-saqib,

This is not an issue. Please check your cors header policy.
