### ISSUE TITLE
The captcha should work properly, on the login page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6678]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on the **configuration / customer / captcha**
**3.** Configure credentials
**4.** Visit the shop
**5.** Try to log in as a customer.

**Expected result:** The **captcha** should work properly, on the login page. 

**Actual result:** Captcha is **not working** if the customer is trying to **log in**. Please find the screenshot [Here](https://prnt.sc/qMw0ffQqKxzL)

**Comment by akathuria289** [comment]
![Desktop-screenshot (1)](https://user-images.githubusercontent.com/107393273/187909500-a6adbdbd-8d23-4ff0-af1b-becbc5530e92.png)
@Sanjaybhattwebkul Recheck

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
I am **closing** this issue because i have re **configure** the **credentials** and now it is **working fine** , please find the screenshot [Here](https://prnt.sc/lF25YzYgnmFR)
