### ISSUE TITLE
Cancel / Refund option should be present for admin if the Automatically invoice generate is enabled.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6680]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on **payment method** inside the **configuration/sales.**
**3.**   Enable **Automatically generate the invoice after placing an order**
**4.** Visit the shop and **place** an **order**.
**5.** Try to **cancel** the order

**Expected result:**  Cancel / Refund **option** should be **present** for admin if the **Automatically invoice generate** is enabled.

**Actual result:** The admin is not able to cancel the order if the **Automatically invoice generate** is enabled by admin. Please find the screenshot [Here](https://prnt.sc/qx5Q4VzrgDci)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

As per the issue and current flow, in case of auto invoice generation there will not be an option to cancel the invoice.
But in this case you need to create transactions for the same and after creating transaction you will be able to see **Refund** option.
