### ISSUE TITLE
Product List View not working in Demo

### ISSUE THREAD

**Issue by ersaurav36** [bagisto/bagisto#669]
List View Not Working
https://demo.bagisto.com/bagisto-common/categories/electronics
![sdfsdfas](https://user-images.githubusercontent.com/32482149/54070788-b3255880-428a-11e9-9442-9a8630bcd9a7.png)
![BdMpeEXgRNSQRBGfxLrJBQ](https://user-images.githubusercontent.com/32482149/54070790-b882a300-428a-11e9-87e2-dbad03f11dda.png)

**Comment by jitendra-webkul** [comment]
Fixed in master
