### ISSUE TITLE
There should be an option to give the product export permission to the user

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6691]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on **users** inside the settings tab.
**3.** Create a role and try to give **permission** to **export** products.

**Expected result:** There should be an **option** to give the product **export permission** to the user

**Actual result:** There is no **option** to give the product **export permission** to the user while the admin is **creating** the **role**.   Please find the screenshot [Here](https://prnt.sc/UWeY5KjSaVwK)

**Comment by devansh-webkul** [comment]
Currently, all exports are done from the same route, so it's not possible at this stage and this is time-consuming. We will enhance this in the new theme.
