### ISSUE TITLE
Convert textarea to Editor Wysiwyg in product view

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#6701]
There is a way to use editor instead  Wysiwyg simple textarea inside product page admin ?

Regards.
.g

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
**Yes**, you can change a **Wysiwyg editor** to a simple **text area** by editing any attribute,
Please take a **reference** from [Here](https://prnt.sc/yBB8FSJq3LYO) for the same

**Comment by ghena** [comment]
Solved :)
