### ISSUE TITLE
Cms pages datagrid not diplay any rows when Change locale

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#6703]
Changing env
APP_LOCALE=it
then clear cache configuration

then added a new translations for specific page: php artisan optimize:clear

The datagrid not diplay any rows
![image](https://user-images.githubusercontent.com/548424/189348505-86d49dfa-c3ea-4020-8120-9a87e5bde644.png)

this is my db for cms_page_translations
![image](https://user-images.githubusercontent.com/548424/189348335-b5f41a37-b5a0-411b-90a3-ac54aa6a6bba.png)

this is the results of datagrid query
![image](https://user-images.githubusercontent.com/548424/189348896-25338664-c835-4f43-81a2-14160d4db0d7.png)

Please could you check ?
Regards.
g.

**Comment by Sanjaybhattwebkul** [comment]
Hi there, 
I guess you **don't add** the pages for the **IT** locale, please take a **reference** from [Here](https://prnt.sc/c-Tq2Tl0a1Kf). and the issue will be **resolved**.

**Comment by ghena** [comment]
I did a small video.

https://drive.google.com/file/d/1ZjT9fLxSK1AWOjuAiwMhPL0QT6Rb3Zfv/view

The problem is not solved.
.g

**Comment by ghena** [comment]
I investigate further and:

Request URL: http://127.0.0.1:8000/admin/cms?v=1&page=1
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:8000
Referrer Policy: no-referrer-when-downgrade
Missing required parameter for [Route: shop.cms.page] [URI: page/{slug}] [Missing parameter: slug].

Please help.

**Comment by HermesZum** [comment]
Try this:

`packages/Webkul/Admin/src/DataGrids/CMSPageDataGrid.php`

```php
public function prepareQueryBuilder()
    {
        $queryBuilder = DB::table('cms_pages')
            ->select('cms_pages.id', 'cms_page_translations.page_title', 'cms_page_translations.url_key')
            ->leftJoin('cms_page_translations', function($leftJoin) {
                $leftJoin->on('cms_pages.id', '=', 'cms_page_translations.cms_page_id')
                         ->where('cms_page_translations.cms_page_id', app()->getLocale());
            });

        $this->addFilter('id', 'cms_pages.id');

        $this->setQueryBuilder($queryBuilder);
    }
```

remove the line:

`->where('cms_page_translations.cms_page_id', app()->getLocale())`

Will be like this:

```php
public function prepareQueryBuilder()
    {
        $queryBuilder = DB::table('cms_pages')
            ->select('cms_pages.id', 'cms_page_translations.page_title', 'cms_page_translations.url_key')
            ->leftJoin('cms_page_translations', function($leftJoin) {
                $leftJoin->on('cms_pages.id', '=', 'cms_page_translations.cms_page_id');
            });

        $this->addFilter('id', 'cms_pages.id');

        $this->setQueryBuilder($queryBuilder);
    }
```

**Comment by devansh-webkul** [comment]
This is a bug and I have added a PR for that. With that PR now you can able to filter the locale from the data grid itself.
