### ISSUE TITLE
Class "Webkul\Core\Console\Commands\Install" does not exist

### ISSUE THREAD

**Issue by hamza-saqib** [bagisto/bagisto#6707]
# Bug Report
getting this error while running composer install 
Class "Webkul\Core\Console\Commands\Install" does not exist

## Issue Description
Class "Webkul\Core\Console\Commands\Install" does not exist

## Preconditions
clone latest code from master branch on shared hosting. and run composer install.

## Bagisto Version

- [ ] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Can you please **elaborate**? When you are getting the **exception**.

**Comment by devansh-webkul** [comment]
Closing this as this is not an issue. Please use bagisto forum.
