### ISSUE TITLE
Add [_token] to fillable property to allow mass assignment on [Webkul\Velocity\Models\VelocityMetadata]

### ISSUE THREAD

**Issue by B2rana** [bagisto/bagisto#6708]
In the latest version of Bagisto v1.4.4, $guarded property is missing from 'Webkul\Velocity\Models\VelocityMetadata' file which throw an error when the user try to save velcoty meta-data.

Current code:
```
class VelocityMetadata extends Model implements VelocityMetadataContract
{
    protected $table = 'velocity_meta_data';
}
```

Previous version code:
```
class VelocityMetadata extends Model implements VelocityMetadataContract
{
    protected $table = 'velocity_meta_data';

    protected $guarded = [];

}
```

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Are you asking about this issue? :  https://github.com/bagisto/bagisto/issues/6687

**Comment by papnoisanjeev** [comment]
@B2rana @Sanjaybhattwebkul 

Already added: 
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Models/VelocityMetadata.php#L12

**Comment by Sanjaybhattwebkul** [comment]
@B2rana 

The issue is **fixed** in our **master** branch and it will **reflect** in our **upcoming release.**

**Comment by B2rana** [comment]
Got it but it will be help full for others if you update this on v1.4.4 too. This is a minor change and also you have released a new version a few days ago.
