### ISSUE TITLE
Undefined array key "sort" 

### ISSUE THREAD

**Issue by B2rana** [bagisto/bagisto#6709]
Hi,

During assigning custom permissions to a role, if the user selects only child permissions without its parent, then the system will throw an error to those users' accounts who are associated with this role. 

Please see attached image for reference.

![permission-issue](https://user-images.githubusercontent.com/1181404/189728039-afb3b197-9abd-449d-aa0c-1c50c7242c3c.gif)

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Which **version** of Bagisto are you using?

**Comment by B2rana** [comment]
I have found this issue on v1.4.3 & v1.4.4. 

Note: I have not tested this on previous versions.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
I have **verified** this with **our v1.4.4** but everything is **working fine**, you can verify in our demo [site](https://demo.bagisto.com/)

I **guess** you **skip** some **steps** while installing the **Bagisto**.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
**Thanks for reporting** we will **fix** this issue in our **next release.**
