### ISSUE TITLE
Having these errors  Undefined variable: key/value

### ISSUE THREAD

**Issue by bl4ckz0ul** [bagisto/bagisto#671]
<a href="https://ibb.co/Hh6Y6cF"><img src="https://i.ibb.co/KKd7dt0/Screenshot-19.png" alt="Screenshot-19" border="0"></a>

First time deploying bagisto ang having these errors. Tried on several local servers (Laragon, Wamp, Xampp) and migrating just fine without error on, mysql, or mariadb . but  still facing the same problem.

using the latest version 0.1.4

**Comment by rahulshukla-webkul** [comment]
Hi @bl4ckz0ul 

We have checked the issue and resolved that in the next version. If you want to check, you can download from our master branch: https://github.com/bagisto/bagisto/tree/master

This version will be released soon, so either you can wait for that after proper testing has been done or you can download from there.

**Comment by rahulshukla-webkul** [comment]
Hi @bl4ckz0ul 
We have released our new version.Please download new version of bagisto.
