### ISSUE TITLE
Drag and drop rows sorting

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#6716]
I'm creating a module using just 10 rows using a datagrid.
There is a way to sorting rows using drag and drop feature ?

Regards.
.g

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
We **will implement** this **feature** in our feature **release**.

**Comment by devansh-webkul** [comment]
This can't be implemented as a datagrid as this will create too much complexity. There can be some other way where you can make a component for dragging the limited content.

As datagrid can have 1 million rows also.

This can be good for a small amount of limited content.

**Comment by devansh-webkul** [comment]
My suggestion would be, if you have 10 rows then you can simply make a draggable component for that.
