### ISSUE TITLE
Datagrid filter not working properly

### ISSUE THREAD

**Issue by B2rana** [bagisto/bagisto#6717]
## Issue Description
In admin section, when user try to apply filters on datagrid, it's reset the value of other filters.

## Bagisto Version

- [ ] 1.4.4
- [ ] 1.4.3

## Steps To Reproduce
1. Apply "search text" & "items per page" filters with different values.
2. Then try to change the "locale" or "channel" filter value
3. It will reset the value of step 1 filter's values
4. If you try step 2 first and then step 1, the same thing happens

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/1181404/190224144-0ebf2164-6f8d-434e-99d2-90072ab01173.png">

## Actual Result
Currently, above & bottom filters are resetting the value of each other. Please see attached screenshot.

## Expected Result
All filters must be work together

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
For **this** please raise a **ticket** [Here](https://bagisto.uvdesk.com/en/)
Here we are **handling only** the issue related to **Bagisto core.**

**Comment by B2rana** [comment]
Hi, but how this is not related to Bagisto core? Most of the issues raised on GitHub are related to UI. This issue is occurring in all the sections in the admin. If you still thinking that this is not related to Bagisto core then no problem I will resolve this on my own in my projects.

Thanks & Regards
