### ISSUE TITLE
The guest user is not able to checkout.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6719]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Visit the shop.
**2.** Add any item to the cart.
**3.** Try to **checkout** the order.

**Expected result:** The **guest** user is **not** able to **checkout**.

**Actual result:** The page **redirects** to the **login page** if the guest user is **trying** to checkout.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Guest checkout toggle button was missing on product edit page due to attribute got deleted someway.
So due to this guest was not able to checkout and page was redirecting to customer login page.

Please run below command:
**php artisan db:seed**

It should work as expected.
