### ISSUE TITLE
ui-kit route hide or block using configuration

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#6723]
Hi,

http://127.0.0.1:8000/ui-kit

bagisto shows this:

![image](https://user-images.githubusercontent.com/548424/190582663-e8d6d966-79b1-431a-b4a9-1f24b6ea49c3.png)

or

http://127.0.0.1:8000/helper-classess

![image](https://user-images.githubusercontent.com/548424/190582822-a7bad585-308c-4122-b62f-f635167b5880.png)

there is a way to delete this route using configuration ?

regards.
g.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Can you please **elaborate**?

**Comment by ghena** [comment]
is not a issue bu a features i Suppose.

There is a way to hide or delete this troutes:

 http://127.0.0.1:8000/ui-kit
http://127.0.0.1:8000/helper-classes

using an admin configuration or using APP_ENV=production  ?

I Hope now is more clear.

.g
