### ISSUE TITLE
The category should not be updated for all locales if the admin is updating the category for any specific locale.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6725]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on the category inside the catalog section.
**3.** Click on edit any category. 
**4.** Change the locale and fill all required field
**5.** Try to view the same category for another locale.

**Expected result:** The category should **not** be **updated** for **all** locales if the admin is updating the category for any **specific** locale.

**Actual result:** The **category** is updating for **all locales** if the admin is updating the category for any **specific** locale.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

As checked data is saving fine (Name, Description) as per selected locale.
You need to refresh the page at front-end if making change in category slug form admin panel.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

As checked data is saving fine (Name, Description) as per selected locale.
You need to refresh the page at front-end if making change in category slug form admin panel.

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 

The **category slug** should be **differnent** for all **locales**.

**Comment by vivek-webkul** [comment]
@papnoisanjeev 
[Make check for the requested locale only.](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Category/src/Repositories/CategoryRepository.php#L289)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
