### ISSUE TITLE
The advertisement images should be clickable on the home page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6738]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Visit the shop
**2.** Try to click on the advertisement images.

**Expected result:** The **advertisement** images should be **clickable** on the home page.

**Actual result:** The advertisement images **are not clickable** on the home page. Please find the screenshot [Here](https://prnt.sc/WeLPU5Ox1i70)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Please assign this issue to me. Thanks

**Comment by saurabh042** [comment]
@Sanjaybhattwebkul could you please assign this to me if its not already assigned?

**Comment by iamakhileshmishra** [comment]
@Sanjaybhattwebkul Could you please assign this issue to me? I would love to solve this issue

**Comment by vivek-webkul** [comment]
@Sanjaybhattwebkul 

If you want to provide the link for each category under the category-with-custom-option template, you just need to provide the link in the Velocity theme header option, like:

For Link with category image:
@include('shop::home.category-with-custom-option', ['category' => [ 'men-collection' => '/page/refund-policy', 'kids' => '/page/privacy-policy', 'women-apparel' => '/page/shipping-policy', 'electronics' => '/page/whats-new' ]])

For without Link with category image:
@include('shop::home.category-with-custom-option', ['category' => ['men-collection', 'kids', 'women-apparel', 'electronics']])
