### ISSUE TITLE
The blank dropdown is showing on the shop by category section if there are no categories for any locale

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6743]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Create some **categories** only in English.
**3.** Visit on shop and **mouse over** on shop by category section.

**Expected result:**  The blank dropdown should not be visible if there is no category for any specific locale. 

**Actual result:** The **blank dropdown** is showing on the **shop by category** section if there are no categories for any **locale**. Please find the screenshot [Here](https://prnt.sc/TJxK2NYVZn27)

**Comment by the-kaushal-agrawal** [comment]
pls assign this issue to me
