### ISSUE TITLE
 There should be a mouse-hover effect for the admin submenu in the dark theme.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6744]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an **admin** in the dark theme
**2.** Mouse over and menu and submenu in the sidebar.

**Expected result:** There should be a **mouse-over** effect for the admin **submenu** in the **dark theme.**

**Actual result:** There is **no mouse-over** effect for **submenus** in the **admin panel.** Please find the screenshot [Here](https://prnt.sc/8UGUEOIuIasD)

**Comment by kb-s** [comment]
hey @Sanjaybhattwebkul, I guess It should be mouse-hover effect if I'm not wrong!
