### ISSUE TITLE
There is a translation issue if the customer is creating/editing the address.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6747]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer with the Arabic locale.
**2.** Click on the address inside the profile section.
**3.** Try to create / Delete any address.
**4.** Try to click save as the default address.

**Expected result:** There should not be any translation issue in the customer address section.

**Actual result:** There is a **translation** issue if the customer is **creating/editing** the **address**. Please find the screenshot [Here](https://prnt.sc/8Su_8QMZc6Zn)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Assign it to me if you have not started working on it

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/vAL1fx_STw1m), for **future** reference.
