### ISSUE TITLE
On Customer end other locale PDF is not translated properly 

### ISSUE THREAD

**Issue by akathuria289** [bagisto/bagisto#6749]
Bagisto Version: Master

Steps To Reproduce--

1. Log in as a customer with the Arabic locale.
2. Click on the orders inside the profile section.
3. Click on the Action icon and then the invoice section.
4. Then print the invoice
5. Then Translate ( by Google translator ) the text that is in Arabic

Expected result: There should not be any translation issue in the PDF

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
