### ISSUE TITLE
The cart summary should be on the left side of the order summary on the checkout page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6753]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer.
**2.** Change app locale to Arabic.
**3.** Add any item to the cart.
**4.**  Process for checkout.

**Expected result:** The **cart summary** should be on the **left side** of the **order** summary on the **checkout** page.

**Actual result:** The **cart summary** is below the **order** summary on the **checkout** page. Please find the **screenshot** [Here](https://prnt.sc/ycsHm0NrFVwl)

**Comment by JunaidJaved248** [comment]
Hi @Sanjaybhattwebkul If you have not started working on it, Please assign it to me. I will work on it

**Comment by shubh-mehrotra** [comment]
This issue should get fixed by this PR - https://github.com/bagisto/bagisto/pull/6805

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/onZXZ5f50H8_), for **future** reference.
