### ISSUE TITLE
There should not be any warning if the admin is creating the catalog rule with the product's name.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6755]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on **catalog rules** inside the promotions.
**3.** Create a new catalog rule.
**4.** Select the **Name** from the **condition** dropdown.

**Expected result:** There should not be any **warning** if the admin is creating the **catalog** rule with the **product's name.**

**Actual result:** There is a **warning message** when the admin is creating the **catalog rule** with the **product's name** Please find the screenshot [Here](https://prnt.sc/PC6FMR_scsxK)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul I want to work on this issue also. Assign it to me. 
I want to clarify one thing that when user select name is equal to then no warning should be shown Right? As you mentioned in screenshot..
