### ISSUE TITLE
The customer should not be able to view the product if the Visible Individually is disabled.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6756]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on products inside the catalog
**3.** Edit any product and disable **Visible Individually**
**4.** Try to view the updated product.

**Expected result:** The customer should not be able to **view** the **product** if the **Visible Individually** is **disabled**.

**Actual result:** The admin/ customer is **able** able to **view** the product if  **Visible Individually** is **disabled** for the same product. Please find the screenshot [Here](https://prnt.sc/pGVu8dpapnK8)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
I am reopening this issue because the user is able to view the product by **URL directly.**
Add the product's name in the site URL, to reproduce this issue

@papnoisanjeev 
Please look into it.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Please check now, If product individual view is disable then customer will not able to see product on front end (if pasting direct slug in URl).

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/GyM4HUIkXh-P), for future **reference**.
