### ISSUE TITLE
 The footer middle content should be visible on the velocity theme.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6757]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on velocity inside the settings.
**3.** Add footer middle content.
**4.** Try to view the added content on the velocity footer section.

**Expected result:** The **footer middle content** should be **visible** on the **velocity** theme.

**Actual result:** The **footer middle content** is not **visible** on the **velocity** theme. Please find the screenshot [Here](https://prnt.sc/S1N7Z0C5ZFAK)

![velocity](https://user-images.githubusercontent.com/86394952/192449290-ac6e7a00-4d42-4bc6-bffd-ef045ed49a15.png)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Assign it to me.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Please check: https://github.com/bagisto/bagisto/pull/6420 
No need to add as previously removed by team as per request (SEO).

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/IncQiqJ0ENff), for **future** reference.

**Comment by sheerazabbas** [comment]
is this issue fixed into **Version : v1.4.5** or into which version you are going to release it. 
thanks.
