### ISSUE TITLE
The filters are not working on the shop by category page

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6759]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an **admin**
**2.** Create a product and set the **Customer Group** price
**3.** Login as a customer.
**4.** Try to **shop by category.**
**5.** Filter the products by the **cheapest first**  filter

**Expected result:** The **filters** should be **working** properly on the **shop by category** page.

**Actual result:** The filters are **not working** on the **shop by category** page. Please find the screenshot [Here](https://prnt.sc/fgMsvR8H0W7K)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Assign it to me.

**Comment by asi309** [comment]
I can work on this issue

**Comment by Miyuru-Bhashitha-amarasiri** [comment]
Dear @Sanjaybhattwebkul. Please assign me to this.

**Comment by Sanjaybhattwebkul** [comment]
@asi309 
Are you working on this issue?

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
This issue is **fixed** by **this** Pull Request: https://github.com/bagisto/bagisto/pull/7127
So **closing** this issue.
