### ISSUE TITLE
Can't Filter by ID

### ISSUE THREAD

**Issue by nitishk72** [bagisto/bagisto#676]
https://demo.bagisto.com/bagisto-49-39-4-180/admin/sales/orders?id[gt]=20

![image](https://user-images.githubusercontent.com/15886737/54151747-8aa38700-4461-11e9-90c2-58f42b1de012.png)

**Comment by prashant-webkul** [comment]
@nitishk72 Thanks for filing the issue. But if you try our latest release 0.1.4 or download the latest master zip this bug won't be there.
The release on the demo is quite older and it had some bugs.
Please try our latest release or latest master.

**Comment by nitishk72** [comment]
Please update the demo website

**Comment by prashant-webkul** [comment]
@nitishk72 Yeah it will be done really soon and we will notify you.

**Comment by rahulshukla-webkul** [comment]
Hi @nitishk72 
We have released our new version.Please download new version of bagisto.
