### ISSUE TITLE
Cart item image have issue when child image not uploaded.

### ISSUE THREAD

**Issue by ilyas-yaqoob** [bagisto/bagisto#6765]
# Bug Report

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce

packages/Webkul/Product/src/Type/Configurable.php
Line# 804 
 public function getBaseImage($item)
    {
        if ($item instanceof \Webkul\Customer\Contracts\Wishlist) {
            if (isset($item->additional['selected_configurable_option'])) {
                $product = $this->productRepository->find($item->additional['selected_configurable_option']);
            } else {
                $product = $item->product;
            }
        } else {
            if ($item instanceof \Webkul\Checkout\Contracts\CartItem) {
                $product = $item->child->product;
            } else {
                if (count($item->child->product->images)) {
                    $product = $item->child->product;
                } else {
                    $product = $item->product;
                }
            }
        }

        return ProductImage::getProductBaseImage($product);

    }
    
   Step1: If there is no image/images for child product. Function does not load the parent product image.

## Actual Result

If no image uploaded for child product. mini cart/wishlist item does not show image.
If image uploaded for child product mint cart/wishist item show the image.

## Expected Result

If no image uploaded for child product. need to show the parent product image

**Comment by ilyas-yaqoob** [comment]
Replace the function with

    public function getBaseImage($item)
    {
        if ($item instanceof \Webkul\Customer\Contracts\Wishlist) {
            if (isset($item->additional['selected_configurable_option'])) {
                $product = $this->productRepository->find($item->additional['selected_configurable_option']);
            } else {
                $product = $item->product;
            }
        } else {
            if ($item instanceof \Webkul\Checkout\Contracts\CartItem) {
               // $product = $item->child->product;
                if (count($item->child->product->images)) {
                    $product = $item->child->product;
                } else {
                    $product = $item->product;
                }
            } else {
                if (count($item->child->product->images)) {
                    $product = $item->child->product;
                } else {
                    $product = $item->product;
                }
            }
        }

        return ProductImage::getProductBaseImage($product);

    }

**Comment by Sanjaybhattwebkul** [comment]
@ilyas-yaqoob 

As I **checked** on our **latest versio**n this is **working** fine, please find the screenshot [Here](https://tinyurl.com/2pqzgor6
)


![one](https://user-images.githubusercontent.com/86394952/192694285-b99d4a05-e30e-4528-a62e-e5e26df66bd1.png)


![two](https://user-images.githubusercontent.com/86394952/192694318-a0346ea3-caf8-4098-ac9f-6065de8b7ad9.png)

**Comment by ilyas-yaqoob** [comment]
@Sanjaybhattwebkul I'm using master branch.

Let me share you the screen short one child have image and one dont have.
<img width="1263" alt="Screen Shot 2022-09-28 at 10 21 53 AM" src="https://user-images.githubusercontent.com/61551102/192703480-7a8e62fc-7961-4f95-9e72-fb83d213a676.png">
<img width="555" alt="Screen Shot 2022-09-28 at 10 22 51 AM" src="https://user-images.githubusercontent.com/61551102/192703511-5c7a3c73-96b6-4cea-9324-a98cca2c7c26.png">


Now i'm going to change the code and check the image is show now.
<img width="788" alt="Screen Shot 2022-09-28 at 10 24 47 AM" src="https://user-images.githubusercontent.com/61551102/192703710-71354cb3-4c6b-4fff-bf30-30d17d8b106f.png">
<img width="829" alt="Screen Shot 2022-09-28 at 10 25 03 AM" src="https://user-images.githubusercontent.com/61551102/192703736-0dd3acd8-4afc-4c56-9445-eda8c1a66cfc.png">

**Comment by Sanjaybhattwebkul** [comment]
@ilyas-yaqoob 
**Thanks** for **reproting**, we will **fix** this issue in our **next** release.
