### ISSUE TITLE
 The address sequence should be correct on the checkout page

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6767]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as acustomer.
**2.** Add any item to the cart.
**3.** Process for checkout. 
**4.** Add a new billing address.

**Expected result:** The address **sequence** should be correct on the **checkout page**. please take a **reference** from the below screenshot.

**Actual result:** The address **sequence** is not in the **correct** format on the **checkout** page. Please find the screenshot [Here](https://prnt.sc/dc712X32YzmE)

![screen](https://user-images.githubusercontent.com/86394952/192716118-3efd6c71-c289-40c9-b391-ef25bf623dcc.png)

**Comment by tobiasrieper040147** [comment]
can I work on this?

**Comment by the-kaushal-agrawal** [comment]
pls assign this issue to me

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/o72MSuhe8Qnj), for **future** reference.
