### ISSUE TITLE
The inactive and out-of-stock products are also visible on the search result if the admin is adding products on group and bundle product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6770]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an **admin**.
**2.** Click on products inside the catalog tab.
**3.** Create a **bundle** product.
**4.** Try to add any inactive or **out-of-stock** product to **bundle** items.

**Expected result:** The **inactive** and **out-of-stock** products should **not** be **visible** on the **search** result if the admin is adding products on **groups** and **bundle** products.

**Actual result:** The **inactive** and **out-of-stock** products are also **visible** on the search **result** if the admin is adding products on **group** and **bundle** products. Please find the screenshot [Here](https://prnt.sc/g1-G03S-seTP)

**Comment by asi309** [comment]
I can work on this fix. Please assign it to me

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
