### ISSUE TITLE
The cart summary should be on the left side of the billing address on the checkout page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6775]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a **customer**.
**2.** Change the app locale to **Arabic**.
**3.** Add any items to the cart.
**4.** Process for **checkout** page.
**5.** Select the **billing** address.

**Expected result:** The **cart summary** should be on the **left side** of the billing **address** on the **checkout** page.

**Actual result:** The cart summary is **below** the **billing** address on the **checkout** page. Please find the screenshot [Here](https://prnt.sc/iqTOJOusg5O7)

**Comment by aniketh-varma** [comment]
Hi @Sanjaybhattwebkul, I would like to take up this issue.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/7k5G7mubat0U), for **future** reference.
