### ISSUE TITLE
Translation issue with per Page filter on the customer's order page

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6776]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer.
**2.** Click on orders inside the profile section.
**3.**  Try to filter the orders with the **per page** filter.

**Expected result:** There should not be any **translation** issue on the **customer** orders page.

**Actual result:** Translation issue with **per Page** filter on the customer's **order** page. Please find the screenshot [Here](https://prnt.sc/hELDtSKhu8qD)

**Comment by nooras** [comment]
Hi I wanted to work on this issue. Can you please assign it to me @Sanjaybhattwebkul  ? Thanks

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/bQXjBRLCPEzg), for **future** reference.
