### ISSUE TITLE
Clear all text should be in the center of the filter liable if the customer is trying to filter the orders.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6778]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in a customer.
**2.** Change app locale to **Arabic**.
**3.** Click on **orders** inside the **profile** section.
**4.** Apply **filter** on **orders**.
**5.** Try to **remove** all applied **filters**.

**Expected result:**  **_Clear all_** text should be in the center of the **filter liable** if the customer is trying to filter the **orders**.

**Actual result:** _**Clear all**_ is **not** in the **center** of the **filter liable** if the customer is trying to **filter** the **orders**. Please find the screenshot [Here](https://prnt.sc/3lld2SfAWVzT)

**Comment by Sanjaybhattwebkul** [comment]
The **mouse** **property** should a be **pointer** for the **clear all** text.

**Comment by saimaheshtaduri** [comment]
I can work on this. Assign it to me. @Sanjaybhattwebkul

**Comment by shikhar13012001** [comment]
I would like to work on this. Can you assign this to me? @Sanjaybhattwebkul

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/fNL5zHcDmxHt), for **future** reference.
