### ISSUE TITLE
UI issue on the trash and wishlist icons on the cart page in mobile view

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6779]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in a customer on mobile
**2.** Add some items to the cart.
**3.** View the shopping cart.
**4.** Try to remove the item from the cart.

**Expected result:** The **trash** and **wishlist** icons should be on a single row on the **mobile** view. 

Device name:  **iPhone SE**

**Actual result:**  UI issue on the **trash** and **wishlist** **icons** on the **cart** page in **mobile** view. Please find the screenshot [Here](https://prnt.sc/Lz4Honnvy-8Y)

**Comment by kazimsayed954** [comment]
assign this issue to me i will help you out with this issue

**Comment by Gbemi-m** [comment]
I'd like to be assigned to work on this

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/tuuFvsipVHdE), for **future** reference.
