### ISSUE TITLE
The checkbox should be just below the input box on the checkout page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6780]
**Bagisto Version:** Master

**Steps To Reproduce**--

**1.** Log in a customer on mobile
**2.** Change the app locale to Arabic.
**3.** Add some items to the cart.
**4.** Process for checkout.
**5.** Add a new billing address.

**Expected result:** The **checkbox** should be just **below** the **input** box on the **checkout** page.

**Device name:** iPhone SE

**Actual result:** The **Checkboxes** are getting **hidden** a bit in the **mobile** view if the customer is **adding** a billing **address** on the **checkout** page. Please find the screenshot [Here](https://prnt.sc/A5x9xqXVLQLb)

**Comment by rsarthak** [comment]
please assign this to me...

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
I am **closing** this issue because this issue is **fixed** by [This PR](https://github.com/bagisto/bagisto/pull/6808/), please find the **screenshot** [Here](https://prnt.sc/j5vQt0MUMtEQ)
