### ISSUE TITLE
The filters are not visible in the shop by category section.in mobile view

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6781]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer in the **mobile** view.
**2.** Shop by selecting any **category**.
**3.** Try to apply **per page** filter.

**Expected result:** The **filters** should be **visible** in the **shop by category** section in the **mobile** view.

**Actual result:** The **filters** are **not visible** in the **shop by category** section.in **mobile** view. Please find the screenshot [Here](https://prnt.sc/lpt9BzupwFao)

**Comment by nooras** [comment]
Hi I wanted to work on this. Can you please assign me ? Thanks

**Comment by Aniket-508** [comment]
Hi, I wanted to work on this issue. Can you please assign me @Sanjaybhattwebkul ?

**Comment by nooras** [comment]
Hi @Sanjaybhattwebkul 
I made changes for filters can you please confirm it?
Before:
![image](https://user-images.githubusercontent.com/30138146/194060952-6c988c58-d1cf-4267-9c0f-b4aa3a8236c0.png)
After
![image](https://user-images.githubusercontent.com/30138146/194053649-2883bdf1-5e24-49e2-a48c-63f9919302e1.png)

Let me know if any changes are required.

**Comment by nooras** [comment]
> Hi @Sanjaybhattwebkul
> 
> I have some doubts while pushing this Ui changes. I downloaded project through composer. I made some Ui changes in file **/bagisto/resources/themes/velocity/views/products/list/toolbar.blade.php**
> 
> while pushing this toolbar.blade.php file on git it says The following paths are ignored by one of your .gitignore files:
> 
> So i am not able to commit it. Please guide me how to push changes or If I made changes in wrong files. Thanks.

ANY UPDATED @Sanjaybhattwebkul @saurav-webkul

**Comment by nooras** [comment]
> Hi @Sanjaybhattwebkul
> 
> I have some doubts while pushing this Ui changes. I downloaded project through composer. I made some Ui changes in file **/bagisto/resources/themes/velocity/views/products/list/toolbar.blade.php**
> 
> while pushing this toolbar.blade.php file on git it says The following paths are ignored by one of your .gitignore files:
> 
> So i am not able to commit it. Please guide me how to push changes or If I made changes in wrong files. Thanks.

Hi @Sanjaybhattwebkul can you please guide me in this scenario ?

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
**Please**  follow the given **steps** to push the changes
**1.** Fork the [Bagisto repository](https://github.com/bagisto/bagisto).
**2.** clone the Bagisto from **your** repository
**3.** Create a new branch [ _**git checkout -b branchName**_ ]
**4.** Do the changes
**5.** _git add ._
**6.** _git commit -m "issue #ID fixed"_
**7.** _git push -u origin_ **branchName**
**8.** Go to your git repository 
**9.** Create a **Pull Request.**

**Comment by nooras** [comment]
Thanks @Sanjaybhattwebkul 

I forked & cloned latest project.

In local for me all filters showing are working fine in mobile view.
![image](https://user-images.githubusercontent.com/30138146/200111033-b4b1b1f2-6056-42d3-a0ef-b1249901bca2.png)

Is there any changes are required in this filters - mobile view ? @Sanjaybhattwebkul @saurav-webkul

**Comment by Sanjaybhattwebkul** [comment]
Issue fixed:  https://prnt.sc/6k55-YhXMwcc
