### ISSUE TITLE
Remove unnecessary labels while shoring the table in the admin panel.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6782]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Click on orders inside the catalog section.
**3.** Try to short the table.

**Expected result:** Remove **unnecessary** labels while shoring the **table** in the admin panel.

**Actual result:**  The **Extra** labels are **visible** after applying **shorting** on the **table** in the admin panel.Please find the screenshot [Here](https://prnt.sc/feiCs-IqTAXV)

**Comment by uzerjamal** [comment]
I can work on it and fix it

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/gWgJat7j_LQe), for **future** reference.
