### ISSUE TITLE
The total price of each product should be visible on the cart page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6786]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer in the **default theme.**
**2.**Add any item to the cart. with multiple quantities.
**3.** View the shopping cart.

**Expected result:** The **total price** of each product **should** be **visible** on the cart page.

**Actual result:** The **total price** of **each** product is **not visible** on the cart page.Please find the screenshot [Here](https://prnt.sc/LGiaMxs4O7kh)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Assign it to me. Please I am working on it.

**Comment by saimaheshtaduri** [comment]
I am ready to take up this issue, please assign it to me. @Sanjaybhattwebkul

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
As we discuss this is not in our design, so I am closing this issue.
