### ISSUE TITLE
There should be a proper space between the cross and wishlist icon on the compare product's page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6793]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a **customer**
**2.** Add any product to the compare.
**3.** Click on **compare** icon in the top right corner.

**Expected result:** There should be a proper **space** between the **cross** and **wishlist** icon on the **compare product's** page.

**Actual result:** The **space** between the **cross** and **wishlist** **icon** is not managed on the **compare** product's page. Please find the screenshot [Here](https://prnt.sc/54jAIg6W1Xdt)

**Comment by imanpalsingh** [comment]
Hey can I pick this up?

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please **fix** this issue for the **Dutch** locale **also**, this issue is **not fox for the Dutch** locale please find the **screenshot** [Here](https://prnt.sc/TpKIR-I5-I0K)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/nhlX7QhUqXhT), for **future** reference.
