### ISSUE TITLE
There should be a default image of the product on the product review page if no actual image for that product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6796]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Create a **configurable product.**
**3.** Do **not** upload **images** for the parent product.
**4.** Visit the **shop**.
**5.** Try to review the created product.

**Expected result:** There should be a d**efault image** of the product on the product **review page** if no actual image for that product.

**Actual result:**  Getting the **blank space** if there is no image of **parent product's** in configurable products. Please find the screenshot [Here](https://prnt.sc/VGIMVA7y-ad3)

**Comment by Hermes179** [comment]
Hey, @Sanjaybhattwebkul  I can give it a go can you assign this issue to me?

**Comment by seths10** [comment]
please has this issue been solved?

**Comment by akhtarkhan1** [comment]
@Sanjaybhattwebkul 
Not able to reproduce the issue. Click [Here](https://prnt.sc/RvKb_P1XgmFl)
