### ISSUE TITLE
All categories return 404 on server

### ISSUE THREAD

**Issue by GergoKormoczy** [bagisto/bagisto#6800]
# Bug Report

localhost is fine but after deployment for ubuntu server the categories return 404
product page is working but when I search for product "not found" - still working on localhost

APP_URL=https://dirrdurr.karmaxi.dev - set && off course set hostname on default channel: https://dirrdurr.karmaxi.dev.

## Bagisto Version

- [x] 1.4.3

## Steps To Reproduce

just deploy my server, setup ngnix and all working fine except this (customer/login, register, etc, working)

## Actual Result

all category 404 && yes my categories has "root category".
![screencapture-dirrdurr-karmaxi-dev-bruce-lee-tuzijatek-telep-2022-10-03-12_45_29](https://user-images.githubusercontent.com/84326426/193559248-dbd7c9d6-2022-4077-80f6-805bd659b4b9.jpg)
![screencapture-dirrdurr-karmaxi-dev-search-2022-10-03-12_44_24](https://user-images.githubusercontent.com/84326426/193559255-a2d14702-5ed8-4c8e-97c5-61b8396cadcb.jpg)
![screencapture-dirrdurr-karmaxi-dev-tuzijatek-telep-2022-10-03-12_44_10](https://user-images.githubusercontent.com/84326426/193559257-1b056451-6b75-455d-8164-ba5f5ad4d17f.jpg)

**Comment by GergoKormoczy** [comment]
> Hi there,
> Are the product's **visible** on the **admin** panel ?

Yes, sure.

![screencapture-dirrdurr-karmaxi-dev-admin-catalog-products-2022-10-03-12_51_44](https://user-images.githubusercontent.com/84326426/193560250-d3b2c4d3-e6ef-4798-bf12-423e9f3e6e98.jpg)

**Comment by Sanjaybhattwebkul** [comment]
@GergoKormoczy 
I guess you don't created the category for the selected locale.

**Comment by GergoKormoczy** [comment]
> 

I created my categories after set the language but now I created a new one same issue, not working. I cannot delete English, or how can I resolve this?

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please take a **reference** from [Here](https://prnt.sc/5LRQBT0EXP8R)

**Comment by GergoKormoczy** [comment]
> 

I already done before open this issue as you can see this image.


![screencapture-dirrdurr-karmaxi-dev-admin-catalog-categories-edit-4-2022-10-03-13_06_26](https://user-images.githubusercontent.com/84326426/193562715-bbad5e5d-0e9d-443e-8fcf-dac199f8d518.jpg)

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please **select** the **category** of the **products** inside the categories section, and the **issue** will be **resolved**.
Please take a **reference** from [Here](https://prnt.sc/ai4g6-6XHx-D)

**Comment by GergoKormoczy** [comment]
> Hi there,
> Please **select** the **category** of the **products** inside the categories section, and the **issue** will be **resolved**.
> Please take a **reference** from [Here](https://prnt.sc/ai4g6-6XHx-D)

already configured, anyway I really appreciate your help. I don't know why but maybe damaged my db (deleted English language?) I deleted, reinstall bagisto migration, configured again (most carefully) and now it is working same as expected.
