### ISSUE TITLE
Updates : New issue templates using .yml instead of .md 🛠

### ISSUE THREAD

**Issue by IAmTamal** [bagisto/bagisto#6810]
## What i am suggesting to update ? 

I am suggesting to update the Issue templates , currently we are using `.md` files instead of the brand new issue forms with `.yml` files which makes it more easier to fill in the data and raise an issue !

## Why to update it ? 

Adding an issue Template allows you to organize the issues made by folks in a much better way.
 - We can know if someone wants to write a test or maybe fix something in the website
 - The issue template forms makes writing details more efficient and quick
 - Also since there are `required` options, you can never miss on important values !
 - Here's a general idea : 

![image](https://user-images.githubusercontent.com/72851613/193460863-4c437e27-be39-4d55-b012-419a47a67af7.png)

![image](https://user-images.githubusercontent.com/72851613/193460887-49da7bd4-bec1-4ccb-a8c4-0ff07fd75a13.png)

## Can i work on it ? 

Yes, i will be glad to help an Opensource project grow more !

**Comment by Sanjaybhattwebkul** [comment]
Hi @IAmTamal 
**Thanks** for reporting. you can **contribute** to this.

**Comment by IAmTamal** [comment]
@Sanjaybhattwebkul Made the PR for the respective issue : #6818
Do let me know if something more needs to be changed.
