### ISSUE TITLE
Mobile View -> Product Special Price Default Text and Calendar Icon UI Issue.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6814]
## Issue Description
When creating a **new Product** and **Editing** a Product, while inspecting in **Mobile View**, the price section is having UI Issue. The **Default text** and **Calendar and cross icon** is not in proper position.

## Bagisto Version
**MASTER**

## Steps To Reproduce
**1.** Create or Edit a product -> Price Section -> Inspect in Mobile View.
**2.** There see the **Default Text** and **Calendar and Cross Icon**. UI issue found.

## Actual Result
Please check the screenshot for the issue.
![Core Issue](https://user-images.githubusercontent.com/92721837/193742152-3f5a3cbd-70f9-4cce-b54e-f5bcd8b8590a.png)

## Expected Result

**1.** Default text should appear at the Right Hand Side.
**2.** Calendar Icon and Cross Button should be together on Right Hand Side.

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul @ashishkumar-webkul can you please assign it to me. I can fix it

**Comment by Ishika414** [comment]
I would like to work on this issue. Please assign it to me
