### ISSUE TITLE
UI Issue -> Mobile Inspect View -> Customer Group Price adding details in price section is having less Space.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6820]
## Issue Description
When **creating** a Product or **Updating**, there in **price section** we add **Customer group Price**, inspect the detail in **mobile view** and there we can see the UI issue. **Customer Group, QTY and Price** is having **less space** and at the cross icon, we can see **unused space**. This can be used for Spacing for a better UI.

## Bagisto Version
**MASTER**

## Steps To Reproduce
**1.** Create or Update a Product -> Price Section -> Add Customer Group price -> There we can see the UI Issue.

## Actual Result
Please Consider the Issue Image for a better understanding of the UI Issue. Please find the screenshot [Here](https://prnt.sc/OPGYDYdB36C7)

## Expected Result
The group price input box can shift slightly right side in mobile view.

**Comment by Gbemi-m** [comment]
I'd like to work on this issue

**Comment by forMedusa** [comment]
I want to work on this.

**Comment by adicoder95** [comment]
I am willing to work on this issue

**Comment by Gbemi-m** [comment]
@Sanjaybhattwebkul @ashishkumar-webkul  fixed this issue
