### ISSUE TITLE
 The add page button should be slightly right side in the mobile view.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6821]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin on mobile.
**2.** Click on pages inside the **CMS tab.**
**3.** Try to add a new page.

Device name: **iPhone SE**

**Expected result:** The **add page** button should be **slightly** **right** side in the **mobile view.**

**Actual result:** The **add page** and **export** buttons are overlapping in the mobile view. Please find the screenshot [Here](https://prnt.sc/O8JBhjtT6_Fq)

**Comment by gagandeepp** [comment]
@Sanjaybhattwebkul  please assign

**Comment by Gbemi-m** [comment]
I'd like to work on this issue

**Comment by foreverabhi2002** [comment]
Hey @Sanjaybhattwebkul assign this to me I'd like to work on this issue

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul This Issue Fixed in #6827 PR. Please check it out
Thanks

**Comment by JunaidJaved248** [comment]
![image](https://user-images.githubusercontent.com/42333336/193888767-c4c40ebb-5e36-4815-8204-59b5cd74a067.png)
