### ISSUE TITLE
The invoice table should be responsive in customer panel on mobile view.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6822]
## Issue Description
In customer profile, when we check the order section, there in invoice when we inspect the details in mobile view, we cannot see the scroll bar below the table content. Entire page is responsive.

## Bagisto Version
**MASTER**

## Steps To Reproduce
**1.** Go to Customer Profile -> Orders Section -> View Order -> Invoice -> Inspect in mobile view -> Check the table -> Scroll Bar is missing.

## Actual Result
Please Check the screenshot for better understanding of the issue.

![Scroll Bar](https://user-images.githubusercontent.com/92721837/193796410-1c5ba27f-74d2-4dbd-a802-ec830bccc06c.png)

## Expected Result
Instead of entire page response, it will be much better if we add the scroll bar to the table.

**Comment by Gbemi-m** [comment]
I'd like to be assigned to this issue

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul @ashishkumar-webkul Issue Fixed in #6831 `Fix Proposed`

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Please check this #6839. I have closed existing due to merging issue. Surely This PR Fixed this Issue.
