### ISSUE TITLE
The product's image is cropped in mobile view in wishlist page.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6823]
## Issue Description
After adding the product to the wishlist and then inspecting the details in mobile view we can see the images are not appearing properly.

## Bagisto Version
**MASTER**

## Steps To Reproduce
Store Front -> Add Product to wishlist -> Go to wishlist -> Inspect the details in mobile view.

## Actual Result
Please check the screenshot for a better understanding of the issue.

![Wishlist](https://user-images.githubusercontent.com/92721837/193799500-b7634f01-e744-47a9-8f9d-80072b8feaa5.png)

## Expected Result

The images at the wishlist should look clear.

**Comment by forMedusa** [comment]
I want to work on this, if it isn't resolved yet. If not this, then anything else related to development

**Comment by Gbemi-m** [comment]
@Sanjaybhattwebkul @ashishkumar-webkul  issue fixed #6832

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/pPetImvI8uk-), for **future** reference.
