### ISSUE TITLE
Getting Exception, while the customer is trying to view all reviews of any product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6837]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as a customer.
**2.** Click on any product.
**3.** Try to view all reviews of the same products.

**Expected result:** There should not be any **Exception**, while the customer is trying to **view all reviews** of any product.

**Actual result:** **Exception**, while the customer is trying to **view all reviews** of any product. Please find the screenshot [Here](https://prnt.sc/RKBwmD0Wy3tI)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

As checked by giving some reviews to a product and approval from admin.
Not facing such issue in case there is some case please mention it here.
https://prnt.sc/XP3Bu1ERqpQP

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

As discussed and checked try to fetch latest updates using **(git fetch --all)** then reset your project using master branch, after publishing updates check again.
