### ISSUE TITLE
Invoice design can be enhanced.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6838]
### Invoice design can be enhanced

![invoice](https://user-images.githubusercontent.com/86394952/194283106-8c1d3e81-c057-4ec8-8189-e505a1d62135.png)

**Comment by Sanjaybhattwebkul** [comment]
@kaustav202 
Yes, sure you can contribute.

**Comment by Sanjaybhattwebkul** [comment]
@kaustav202  
Any update?

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul If its not done or pending yet? Then Assign it to me.
And If you can provide any prefer design or required changes reference then  it will be good for this enhancement.

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
This is in **Progress**, @papnoisanjeev  is working on this issue.

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Okay Right!!

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please **improve** the invoice **design** and take a **reference** from the below **screenshot**.

![Bagisto-Invoice](https://user-images.githubusercontent.com/86394952/199175500-eb79d5eb-352d-484c-acb3-275694551bf2.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
