### ISSUE TITLE
Need Space in Product details in Category List View.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6840]
## Issue Description
In Category Section when we check the products in list and Grid view, we can see the product details appear more clear in Grid view as compared to List View.
In list view we need Proper Space in Product Name, Price, Review and Add to Cart Options.

## Bagisto Version
**MASTER**

## Steps To Reproduce
**1.** Go to Store Front -> Shop by Category -> Select Any Category -> View the product in List View.

## Actual Result
Please check the images for better understanding of the issue.

![Grid View](https://user-images.githubusercontent.com/92721837/194480354-3a9e17f8-11b8-4a18-9d38-485b6151bfae.png)

![List view](https://user-images.githubusercontent.com/92721837/194480359-f0278ac2-9509-4617-b3b4-d95c857c0acd.png)

## Expected Result

In the Product Price, Name, Review  and  Add to cart details, proper space should be there, Same as the Grid View.

**Comment by sutirthverma** [comment]
Hey, I can work on this issue. Can you please assign it to me.

**Comment by ashishkumar-webkul** [comment]
Same Issue is found in the Wishlist Page. Please check the screenshot for the same.

**Screenshot**
![Wishlist](https://user-images.githubusercontent.com/92721837/194482374-15e3e86d-3553-420b-b609-6352aff3886f.png)

**Comment by sutirthverma** [comment]
Can you please tell me the source file in which I have to make changes

**Comment by sutirthverma** [comment]
Hey, can you share the source path of the stylesheet file in which I have to make changes

**Comment by avijain09** [comment]
Please assign this issue to me @ashishkumar-webkul

**Comment by Sambhav250703** [comment]
Can I work on this issue?

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/rka7MzsGPWu8), for **future** reference.
