### ISSUE TITLE
There is a UI issue on the product's view page if the customer is trying to select the booking slot.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6848]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Visit the shop.
**2.** Click on any rental booking product.
**3.** Try to select the booking slot.

**Expected result:** There should not be any **UI issue** on the product's **view page** if the customer is trying to select the **booking slot**.

**Actual result:** There is a UI issue on the product's view page if the customer is trying to select the booking slot. Please find the screenshot [Here](https://prnt.sc/5QrATo20AulB)

**Comment by shagun2405** [comment]
@Sanjaybhattwebkul assign this issue to me

**Comment by avijain09** [comment]
Please assign this issue to me @Sanjaybhattwebkul

**Comment by devansh-webkul** [comment]
Not getting an issue.
