### ISSUE TITLE
UI issue on shop by category page in Arabic locale.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6849]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Visit the shop on mobile.
**2.** Change app locale to Arabic.
**3.** Click on any category in the top left corner.
**4.** Try to filter by price.

**Expected result:**  There should not be any **UI issue** on the **shop by category** page in the **Arabic** locale.

**Actual result:** UI issue on shop by category page in Arabic locale. Please find the screenshot [Here](https://prnt.sc/CoAGcAplbQO3)

**Comment by shagun2405** [comment]
@Sanjaybhattwebkul assign this issue to me

**Comment by Amitk-webkul** [comment]
@peeyush-webkul 
Any update??

**Comment by peeyush-webkul** [comment]
> @peeyush-webkul Any update??
I'm working on this,
The actual issue doesn't exist as seen in the screenshot and description, but some issues exist related to this.

**Comment by Amitk-webkul** [comment]
@peeyush-webkul please add attachments.

**Comment by peeyush-webkul** [comment]
![galaxy ui arabic](https://user-images.githubusercontent.com/129033033/232694597-047d0e48-9d1b-40d9-87e1-f64fb987e13a.png)

It's working well, nothing to change

**Comment by Amitk-webkul** [comment]
@peeyush-webkul 
it is working fine. [Here](https://prnt.sc/bP-gfHLQmpWK)
