### ISSUE TITLE
Can I make polish translation?

### ISSUE THREAD

**Issue by KaminskiDaniell** [bagisto/bagisto#6858]
Hi, I would like to create a translation for your repository as part of the hacktoberfest action. Can I?

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
The **Polish** translation is **already added:** https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shop/src/Resources/lang/pl/app.php

**Comment by Sanjaybhattwebkul** [comment]
@KaminskiDaniell 

Please have a look at the **following** translations too and If you want to do any **corrections** then you can, it would be **appreciated**

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Admin/src/Resources/lang/pl

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Core/src/Resources/lang/pl

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Shop/src/Resources/lang/pl

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Velocity/src/Resources/lang/pl

**Comment by sarequl** [comment]
Can I translate this to Bangla (bn-BD)?
