### ISSUE TITLE
Grammer issue / Spelling mistakes in readme.md

### ISSUE THREAD

**Issue by AshwinSatyawan** [bagisto/bagisto#6861]
# Bug Report

## Issue Description
Grammer and spelling mistakes present on readme

## Bagisto Version

- [x] master branch
- [ ] 1.3.3
- [ ] 1.3.2
- [ ] 1.3.1
- [ ] 1.3.0

## Steps To Reproduce
go to readme.md 
*observe the spelling customisation in the headless commerce section (it should be customization)
*observe Commerce For Every Needs section there should be comma present at  "Multi-Tenants systems and many more."

**Comment by AshwinSatyawan** [comment]
assign to me

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
