### ISSUE TITLE
shop.js kills my custom js files and throw error

### ISSUE THREAD

**Issue by GergoKormoczy** [bagisto/bagisto#6879]
# Bug Report

Please clarify what I should do so if I don't want to use shop.js. I read the shop.js.license and put exactly the same packages in the code, but no matter what I do, if shop.js is not in use, the vue components not show up, but if I use it, everything else breaks (like filter.js, etc) and has this error.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'protocol') at shop.js:2:208607

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
If you don't want to use the **shop.js** file then you can **replace** the shop.js file with your **custom js** file in the **blade** file. And make **sure** all the **components** should be **imported** in your **custom js** file which is imparted in **shop.js.**

**Comment by GergoKormoczy** [comment]
> Hi there,
> If you don't want to use the **shop.js** file then you can **replace** the shop.js file with your **custom js** file in the **blade** file. And make **sure** all the **components** should be **compatible** in your **custom js** file which is used in **shop.js.**

Please check the video it is more simple way for tell you what is my problem: https://watch.screencastify.com/v/boSPfvpIO6NKioA0yGhs

I don't know what packages need for this component for working without custom.js. 

<img width="815" alt="Képernyőfotó 2022-10-12 - 13 51 30" src="https://user-images.githubusercontent.com/84326426/195335600-de97971c-86e2-46c9-bdbc-90200419ce26.png">


I already check what packages are included the bundle: shop.js.LICENSE.txt but when I added for my master.blade still not working just when is use shop.js (but it is conflicted my js)

<img width="942" alt="Képernyőfotó 2022-10-12 - 13 54 09" src="https://user-images.githubusercontent.com/84326426/195336079-654db97b-13d1-4c02-8758-96c489d7bb77.png">

**Comment by GergoKormoczy** [comment]
Short, I would like to use some defaults vue.component like (layered-navigation, filter-attribute-item) but are only working when I use <script type="text/javascript" src="{{ bagisto_asset('js/shop.js') }}" ></script> in my master.blade.php. 

BUT I don't want to use because has too many unnecessary js for me (and breaks my template js). I would like to use just necessary js (vue, vue-class-component) I guess. How can I import my master.blade.php or how can I build "my shop.js".

**Comment by GergoKormoczy** [comment]
up.

**Comment by devansh-webkul** [comment]
Have you loaded Vue JS, as for running the component you needed to load up the Vue JS which `shop.js` is doing,
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shop/src/Resources/assets/js/app.js#L2

May be some dependency got broken as yu are doing customization. So please check.

**Comment by shaikhmoinuddin** [comment]
> Have you loaded Vue JS, as for running the component you needed to load up the Vue JS which `shop.js` is doing, https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shop/src/Resources/assets/js/app.js#L2
> 
> May be some dependency got broken as yu are doing customization. So please check.
<img width="1629" alt="Screenshot 2023-01-26 at 10 04 33 AM" src="https://user-images.githubusercontent.com/123619508/214768992-c94ce9a5-be1f-4f78-9deb-3af6163ef923.png">

This issue exists even in your default theme! (refer to screenshot) Why would u guys close the issues without proper inspection or support?

**Comment by Danatelllo** [comment]
> > Have you loaded Vue JS, as for running the component you needed to load up the Vue JS which `shop.js` is doing, https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shop/src/Resources/assets/js/app.js#L2
> > May be some dependency got broken as yu are doing customization. So please check.
> 
> <img alt="Screenshot 2023-01-26 at 10 04 33 AM" width="1629" src="https://user-images.githubusercontent.com/123619508/214768992-c94ce9a5-be1f-4f78-9deb-3af6163ef923.png">
> 
> This issue exists even in your default theme! (refer to screenshot) Why would u guys close the issues without proper inspection or support?

Did u solve your problem?

**Comment by Danatelllo** [comment]
> Have you loaded Vue JS, as for running the component you needed to load up the Vue JS which `shop.js` is doing, https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shop/src/Resources/assets/js/app.js#L2
> 
> May be some dependency got broken as yu are doing customization. So please check.

Hi, we have the same problem, can you explain please how include our vue.js files in our pages without mistakes, when i include my file with @extends('shop::layouts.master) and so on it doesn't work at all.

**Comment by Danatelllo** [comment]
> > Hi there,
> > If you don't want to use the **shop.js** file then you can **replace** the shop.js file with your **custom js** file in the **blade** file. And make **sure** all the **components** should be **compatible** in your **custom js** file which is used in **shop.js.**
> 
> Please check the video it is more simple way for tell you what is my problem: https://watch.screencastify.com/v/boSPfvpIO6NKioA0yGhs
> 
> I don't know what packages need for this component for working without shop.js.
> 
> <img alt="Képernyőfotó 2022-10-12 - 13 51 30" width="815" src="https://user-images.githubusercontent.com/84326426/195335600-de97971c-86e2-46c9-bdbc-90200419ce26.png">
> 
> I already check what packages are included the bundle: shop.js.LICENSE.txt but when I added for my master.blade still not working just when is use shop.js (but it is conflicted my js)
> 
> <img alt="Képernyőfotó 2022-10-12 - 13 54 09" width="942" src="https://user-images.githubusercontent.com/84326426/195336079-654db97b-13d1-4c02-8758-96c489d7bb77.png">

Hi, did you solve your problem i have the same trouble but i don't know how to solve it, @extends('shop::layouts.master) break my vue.js files

**Comment by devansh-webkul** [comment]
Hi there,

See we have made sets of dependencies as per the requirement, but in your case, if you do not want to use that you can customize and rebuild your compiled files as per your need from here,
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shop/src/Resources/assets/js/app.js

And for ui packages, you can remove them from here,
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Ui/src/Resources/assets/js/app.js

And if you do not want to edit the package file then you can just override the master file and use your custom-compiled JS by copying the above one.

**Comment by GergoKormoczy** [comment]
> > Have you loaded Vue JS, as for running the component you needed to load up the Vue JS which `shop.js` is doing, https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shop/src/Resources/assets/js/app.js#L2
> > May be some dependency got broken as yu are doing customization. So please check.
> 
> <img alt="Screenshot 2023-01-26 at 10 04 33 AM" width="1629" src="https://user-images.githubusercontent.com/123619508/214768992-c94ce9a5-be1f-4f78-9deb-3af6163ef923.png">
> 
> This issue exists even in your default theme! (refer to screenshot) Why would u guys close the issues without proper inspection or support?

n

> > > Have you loaded Vue JS, as for running the component you needed to load up the Vue JS which `shop.js` is doing, https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shop/src/Resources/assets/js/app.js#L2
> > > May be some dependency got broken as yu are doing customization. So please check.
> > 
> > 
> > <img alt="Screenshot 2023-01-26 at 10 04 33 AM" width="1629" src="https://user-images.githubusercontent.com/123619508/214768992-c94ce9a5-be1f-4f78-9deb-3af6163ef923.png">
> > This issue exists even in your default theme! (refer to screenshot) Why would u guys close the issues without proper inspection or support?
> 
> Did u solve your problem?

this issue is still remain.

**Comment by GergoKormoczy** [comment]
> > > Hi there,
> > > If you don't want to use the **shop.js** file then you can **replace** the shop.js file with your **custom js** file in the **blade** file. And make **sure** all the **components** should be **compatible** in your **custom js** file which is used in **shop.js.**
> > 
> > 
> > Please check the video it is more simple way for tell you what is my problem: https://watch.screencastify.com/v/boSPfvpIO6NKioA0yGhs
> > I don't know what packages need for this component for working without shop.js.
> > <img alt="Képernyőfotó 2022-10-12 - 13 51 30" width="815" src="https://user-images.githubusercontent.com/84326426/195335600-de97971c-86e2-46c9-bdbc-90200419ce26.png">
> > I already check what packages are included the bundle: shop.js.LICENSE.txt but when I added for my master.blade still not working just when is use shop.js (but it is conflicted my js)
> > <img alt="Képernyőfotó 2022-10-12 - 13 54 09" width="942" src="https://user-images.githubusercontent.com/84326426/195336079-654db97b-13d1-4c02-8758-96c489d7bb77.png">
> 
> Hi, did you solve your problem i have the same trouble but i don't know how to solve it, @extends('shop::layouts.master) break my vue.js files

I can't figure how can I add vue && requirement vue-components but I fixed my custom jQuery functions for work..

**Comment by GergoKormoczy** [comment]
> And one more thing, in the latest version we are removing the default theme. So, for all the support you needed for the legacy things, you can contact Webkul and that will be paid.

I can't use default theme && this issue is still exist.
