### ISSUE TITLE
Add role

### ISSUE THREAD

**Issue by foxit07** [bagisto/bagisto#688]
![image](https://user-images.githubusercontent.com/38004078/54267362-24feea00-458a-11e9-9b8a-56e9918cc947.png)

**Comment by prashant-webkul** [comment]
@foxit07  Thanks for filing this issue.
This problem comes when PHP is running on strict mode. But, we have fixed this issue by removing '**roleItems**' argument.
The issue will get reflected in next update or release as resolved.

**Comment by prashant-webkul** [comment]
@jyoti-webkul Please verify the issue if it exists or not before release or update.

**Comment by jyoti-webkul** [comment]
Issue not found.Verified this issue on version 0.1.5.
