### ISSUE TITLE
The product's name should be visible properly in quick view.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6880]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Create a new product with a name **like Men's.**
**3.** Visit the shop.
**4.** Search the created product.
**5.** Try to **quick view** the product.

**Expected result:** The product's **name** should be visible properly in **quick view.**

**Actual result:** The product's **name** is not **visible** properly in **quick view** if the product's name is **like Men's.**  Please find the screenshot [Here](https://prnt.sc/8Ma4qeHUwZy_)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Can I work on it?

**Comment by papnoisanjeev** [comment]
@JunaidJaved248 

Working on it.
