### ISSUE TITLE
Want to Add Urdu Translation

### ISSUE THREAD

**Issue by JunaidJaved248** [bagisto/bagisto#6882]
`#Enhancement`
I checked the Lang folder, I didn't saw any Urdu translation file.
So, I want to add it, Can You assign this enhancement to me. I will add it.

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
You can create a **Pull Request**, it would be **appreciated**.

**Comment by Shrey-Nahar** [comment]
@JunaidJaved248 are you working in the issue?? or i would like to work on this ..

**Comment by JunaidJaved248** [comment]
@Shrey-Nahar I am working on it.

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Please add In Progress label in this issue, Working is in process. Thanks

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Add "In Progress" in it.

**Comment by devansh-webkul** [comment]
Feel free to deliver PR, I am closing this as this is pretty much common and we have many issues related to this.
