### ISSUE TITLE
The countries are not listed in the country dropdown while the customer is adding the billing address on the checkout page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6884]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Visi the shop
**2.** Add any item to the cart.
**3.** Process for **checkout**.
**4.** Add new billing **address**.
**5.** Try to select the **country**.

**Expected result:** The **countries** should be **visible** on the country **dropdown** while the customer is adding the billing **address** on the **checkout** page.

**Actual result:** The **countries** are **not listed** in the country **dropdown** while the customer is **adding** the billing **address** on the **checkout** page. Please find the screenshot [Here](https://prnt.sc/w9ePwylLh9Bo)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Please Assign this issue to me

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul I checked it, Countries are showing in countries dropdown in billing address. 
![image](https://user-images.githubusercontent.com/42333336/195501277-26d0c22f-1c9d-4113-a92f-5ecca4683ec6.png)

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
Please check with the **fresh database.**

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Okay Let me check

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul I checked with latest code pull & fresh tables migration but countries listing in dropdown.
