### ISSUE TITLE
The locale dropdown should be just the right side of the channel's dropdown on the product's page in mobile view.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6886]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin on mobile.
**2.** Click on products inside the catalog tab.
**3.** Try to change the app locale.

**Expected result:** The **locale** dropdown should be just the right side of the **channel's** **dropdown** on the product's page in the **mobile** view.

**Actual result:** The locale and channel **dropdowns** are **overriding** in **mobile** view. Please find the screenshot [Here](https://prnt.sc/Akjj-rukiwiV)

**Comment by jsvigneshkanna** [comment]
Please assign me this issue

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Fixed Proposed with this PR #6887

**Comment by Sanjaybhattwebkul** [comment]
> @Sanjaybhattwebkul Fixed Proposed with this PR #6887

@JunaidJaved248 
**Thanks** for your contribution.
