### ISSUE TITLE
Couple of missed translations in RU localisation for Shop app

### ISSUE THREAD

**Issue by daniloff200** [bagisto/bagisto#6892]
# Bug Report
I've checked the RU localisation and found couple of translations, that are still in English, for example:

```
 'comment' => [
                'subject'       => 'New comment added to your order #:order_id',
                'dear'          => 'Dear :customer_name',
                'final-summary' => 'Thanks for showing your interest in our store',
                'help'          => 'If you need any kind of help please contact us at :support_email',
                'thanks'        => 'Thanks!',
            ],

```
I also, as a native Russian speaker, want to double-check the whole RU file, perhaps, there are some typos or other issues

## Expected Result
All file with localisation translated in Russian

**Comment by Sanjaybhattwebkul** [comment]
@daniloff200 
**Thanks** for your contribution.
