### ISSUE TITLE
:ru:  Localisation of Admin app does not exist

### ISSUE THREAD

**Issue by daniloff200** [bagisto/bagisto#6895]
I see, that ru folder exists, and there's a file with the translations, but, all of them are still in English.

I can translate the whole file and make a PR with the reworks if that can be a useful and meaningful contribution

**Comment by Sanjaybhattwebkul** [comment]
Hi there,

Please have a look at the following translations and If you want to do any **corrections** then you **can**, it would be **appreciated**

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Admin/src/Resources/lang/ru

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Core/src/Resources/lang/ru

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Shop/src/Resources/lang/ru

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Velocity/src/Resources/lang/ru

**Comment by devansh-webkul** [comment]
I am able to see all the translations related to RU, so I am closing this.
