### ISSUE TITLE
Record per page  option is not visible in mobile, if the customer is trying to shop by category.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6898]
## Issue Description
When inspecting the Category Page in mobile view, there we can see that the show number of products filter is missing.

## Bagisto Version
**MASTER**

## Steps To Reproduce
**1.** Go to Store Front -> Show By Category -> Select any category -> Inspect in mobile view.
**2.** Refresh the Page in mobile view.

## Actual Result
Please check the video and screenshot for a better understanding of the issue.

**Video**

https://user-images.githubusercontent.com/92721837/195508138-d3cf683b-e1df-4baa-82aa-df8df4d7950f.mp4

## Expected Result
All the filters including the show number of products should be visible.
Please consider the image for the same as a sample.

**Image**
![Sample 1](https://user-images.githubusercontent.com/92721837/195508452-b538f40c-4d89-4c4c-a325-24286bef4d69.png)

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Assign it to me.

**Comment by JunaidJaved248** [comment]
@vivek-webkul Okay Thanks
