### ISSUE TITLE
City dropdown like state

### ISSUE THREAD

**Issue by KarimQaderi** [bagisto/bagisto#6903]
Iran's cities are dropdown and I want to add this feature to the system

I have two solutions for this problem

1- The city section should be a separate file and can be replaced like the country and sate

2- Or add directly to the system such as city and state to have this capability from the beginning

Or if do you have a better solution that I can add this feature to the system as a separate module please help me with it.

**Comment by art6573** [comment]
@Sanjaybhattwebkul hi there, I'm interested in working on this. issue As I understand your project participates in Hacktoberfest 22 and I can get special swag from you? Do you send swag outside India?

**Comment by Sanjaybhattwebkul** [comment]
@art6573 

**Sure**,  if you will create **four  acceptable** PRs then We **will send** swag outside of India
