### ISSUE TITLE
Guest welcome message translation missing in mobile view.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6908]
## Issue Description
In mobile view when we check the Welcome guest, where we can see the Sign In and Sign Up details, there we can see the Guest Translation is missing for some languages like Hindi, Arabic etc.

## Bagisto Version
**MASTER**

## Steps To Reproduce
**1.** Inspect the details of a storefront in mobile view -> Check the sidebar for Welcome Guest.
**2.** Change the Locale Translation and there we will be able to see this issue.

## Actual Result:

The **translation** is not correct for **guest** users in **mobile view**, please find the below **screenshot**.

![hindiss](https://user-images.githubusercontent.com/86394952/195570508-67434eee-4641-49c5-aebc-496b0ddb8f4c.png)

**Image**

![Guest Translation missing](https://user-images.githubusercontent.com/92721837/195569524-de58bea9-f410-43c6-9ebb-b71d4a653865.png)

## Expected Result
Please fix the translation issue related to the mobile view.

**Comment by codersrepo** [comment]
Can you assign this issue to me?

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/f8-KcQPbT_qm), for **future** reference.
