### ISSUE TITLE
There should be default image for the Locale in the store front.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6913]
## Issue Description
If we create a locale from the admin and there we do not add the locale image, then a default image should be set.

## Bagisto Version
**MASTER**

## Steps To Reproduce
**1.**  Go to Admin -> Settings -> Locale -> Create a new Locale without the image.
**2.** After the locale is set check the store front.

## Actual Result
Please check the Screenshot for the same.

**Screenshot**

![Default Image](https://user-images.githubusercontent.com/92721837/195578752-93b514f3-f212-490e-a825-f0bffb43fdb3.png)

## Expected Result
It would be much better if default image is set instead of Blank Space.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/ASvMINGQTi9X), for **future** reference.
