### ISSUE TITLE
Translation issue on the shopping cart page in the hindi locale

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/bagisto#6917]
### Terms

- [X] Before you opening this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

Remove translation is not meaningful in the Hindi locale on the cart page, Please find the screenshot [Here](https://prnt.sc/L2IYnuaRLDJG)

### Preconditions

Setup Bagisto from Master repository 

### Steps to reproduce

1. Visit the shop in the velocity theme.
2. Change the app locale to Hindi. 
3. Add to the cart product.
4. View the shopping cart  -> remove option.

### Expected Result

Should not be any translation issue on the shopping cart page in the Hindi locale

### Actual Result

Remove translation is not meaningful in the Hindi locale, 

### Screenshots

Please find the screenshot [Here](https://prnt.sc/L2IYnuaRLDJG)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/TnJ4FmxrWgu2), for **future** reference.
