### ISSUE TITLE
Color scheme/theme request

### ISSUE THREAD

**Issue by bl4ckz0ul** [bagisto/bagisto#692]
I dont have much knowledge to make my own customized theme, so i just modify the css as per my liking, so it will match the color to the  logo of my store.
I did changed the blue #0041ff (default scheme) to the color that i want but nothing happens. 
Hope youll add some theming or color picker for schemes options in the future.

**Comment by prashant-webkul** [comment]
**Note**: To see the changes, you will be required to compile the assets. For compilation of assets **NPM** should be installed in your system.

Then go inside each of these packages(path from project's root):
1. **packages\Webkul\Admin**
2. **packages\Webkul\Shop**
3. **packages\Webkul\Ui**

Then you need to run command '**npm install**' in each of the directories listed above.

**Go to your project root again**:

1. Find **_variables.scss** file by following this path in **shop** package:
**packages\Webkul\Shop\src\Resources\assets\sass\\_variables.scss**

In this file **_variable.scss** you will find all the **colors** values used in **Shop** package.

2. Find **_variables.scss** file by following this path in **Ui** package: **packages\Webkul\Ui\src\Resources\assets\sass\\_variables.scss**

In this file **_variable.scss** you will find all the **colors** values used in **Ui** package.

> But remember the colors in **UI** package file will affect **colors** in **Admin** panel also.

3. Find **_variables.scss** file by following this path in **Admin** package:
**packages\Webkul\Admin\src\Resources\assets\sass\\_variables.scss**

In this file **_variable.scss** you will find all the **colors** values used in **Admin** package.

**Note**: To compile these assets now, step into all these directories below:
1. **packages\Webkul\Admin**
2. **packages\Webkul\Shop**
3. **packages\Webkul\Ui**

And now run the command '**npm run prod**' -> for production and '**npm run watch**' -> for development.
