### ISSUE TITLE
The Edit Category Page is not responsive in mobile view.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6922]
### Terms

- [ ] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we check  the **Categories** in the **Admin Section**, there when we edit any **category** and **inspecting** the details in **Mobile view**, we can see the UI issue and data is overlapping.

### Preconditions

For checking the issue, **admin** should be **logged in** and also from the admin end atleast one **Category** should be **created**.

### Steps to reproduce

1. Go to Admin -> Catalog -> Categories -> Edit any Category.
2.  now inspect the details in mobile view

### Expected Result

The UI should be clear and all the information in the Category Edit page should be visible in mobile view.

### Actual Result

Please follow the Screenshot and video for a better understanding of the issue.

**Screenshot**
![UI](https://user-images.githubusercontent.com/92721837/195775444-531f1ec2-a9b4-4b31-be43-6cd02732f4d4.png)

**Comment by JunaidJaved248** [comment]
@ashishkumar-webkul this PR #6924 Resolved this Issue.

**Comment by Sanjaybhattwebkul** [comment]
@JunaidJaved248 
**Thanks** for your **contribution**.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/u6aQU4nmXQpv), for **future** reference.
