### ISSUE TITLE
Add Sinhalese localization 

### ISSUE THREAD

**Issue by manula2004** [bagisto/bagisto#6927]
### Is your feature request related to a problem? Please describe.

Add translation for Sinhalese, the primarily spoken language in Sri Lanka . I believe it will help attract a whole new userbase.

### Describe the solution you'd like

I would love to contribute to localize the project, but I'm not sure how start a localization for a new language. So, a little help would be much appreciated :)

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
If you want to create a **Pull Request** for the **Sinhalese** translation, then you can it would be **appreciated**.

**Comment by manula2004** [comment]
@Sanjaybhattwebkul Where do I start from? 

should I create a directory in https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Core/src/Resources/lang
and make a copy of the app.php & then translate all the strings?

**Comment by Sanjaybhattwebkul** [comment]
@manula2004 

You **need** to **add** translation for **following** packages.

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Admin/src/Resources/lang/it

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Core/src/Resources/lang/it

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Shop/src/Resources/lang/it

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Velocity/src/Resources/lang/it

**Comment by manula2004** [comment]
alright thanks

**Comment by devansh-webkul** [comment]
Translation has already been added as I am seeing the SIN folder. So closing this.
