### ISSUE TITLE
Smartarget Whatsapp plugin 

### ISSUE THREAD

**Issue by erezson** [bagisto/bagisto#6942]
### Is your feature request related to a problem? Please describe.

We created our [WhatsApp module](https://bagisto.com/en/extensions/laravel-ecommerce-whatsapp-contact/) for Bagisto (https://gitlab.com/erezson/smartarget-bagisto-whatsapp-contact-us), but many of you customers are non-technical, so they need our help all the time to install the module.

Unlike other platforms, extenstions cannot be installed with a single click. So we would like to contribute our code to the core bagisto modul and add our extension but it will be disabled, so only if customers wants, they can enable it (but they won't need to install it manually using composer/etc)

### Describe the solution you'd like

We want to add our plugin to composer.json, so plugin will be installed in Bagisto by default. But it will not be configured, so if user wants, he will configure the app inside admin panel.

### Describe alternatives you've considered

We already created plugin that can be installed (https://gitlab.com/erezson/smartarget-bagisto-whatsapp-contact-us), but it requires some technical skills, so it is not the best solution for simple customers.

**Comment by vivek-webkul** [comment]
Hi @erezson 
Thanks for your suggestion, and we always welcome our contributors for their submissions!

Actually, we already have our OpenSource [Bagisto Whatsapp Connect Extension](https://bagisto.com/en/extensions/laravel-ecommerce-whatsapp-contact/) which allows the customers to contact and communicate with the store admin via WhatsApp. You can also check the functionality of the same.

**Comment by erezson** [comment]
Hi @vivek-webkul  

This is our extension :) We contributed it after Bagisto contacted us and asked to bring our Whatsapp plugin to your platform too.

The problem is that the extension can be installed only by people with development skills. That cause many non-tech Bagisto users to contact us and request that we will install it for them. 

Therefore we submit this request to include the extension in the install of the Bagisto but to keep it disabled. So only customers who wants to use it will be able to enable it **without any** technical experience.

**Comment by vivek-webkul** [comment]
@erezson 
Ohh!! My mistake.

I have one question, does [bagisto-whatsapp-contact-us v1.0](https://packagist.org/packages/smartarget/bagisto-whatsapp-contact-us#1.0) compatible with [Bagisto Master ](https://github.com/bagisto/bagisto)or [v1.4.5](https://github.com/bagisto/bagisto/tree/v1.4.5)?

**Comment by erezson** [comment]
@vivek-webkul yes, it is

**Comment by erezson** [comment]
@vivek-webkul All good :) We're just trying to make things better for the Bagisto community.

It's compatible with Bagisto Master. Is that OK?

**Comment by erezson** [comment]
Hey guys, any update about this? anything I can support you to fix the fail of the PR?

**Comment by devansh-webkul** [comment]
Hi @erezson,

Currently, we cannot add dependency in the main core. You can simply make a package and opensource it. If devs want to use they can simply follow your docs.

Thanks! I am closing this.
