### ISSUE TITLE
Add the 🇮🇩 Indonesia translation

### ISSUE THREAD

**Issue by dicka88** [bagisto/bagisto#6947]
### Is your feature request related to a problem? Please describe.

I have looked in the lang folder but didn't see the Indonesia translation file.
if you want I can add it, please to be honest assign it to me and I will do it ASAP.

before I do it, which files should be translated?

### Describe the solution you'd like

Add several Indonesian translated files, don't worry about my translation. because my native language is Indonesia(Bahasa)

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
You **can** create a **pull request** for the **Indonesia** translation, it would be **appreciated**.

**Comment by Sanjaybhattwebkul** [comment]
@dicka88 

Please **add** the translation for the **following** packages.

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Admin/src/Resources/lang/

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Core/src/Resources/lang/

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Shop/src/Resources/lang/

https://github.com/bagisto/bagisto/tree/master/packages/Webkul/Velocity/src/Resources/lang/

**Comment by devansh-webkul** [comment]
Feel free to deliver PR, I am closing this as this is pretty much common and we have many issues related to this.
