### ISSUE TITLE
Core bagisto Vue.components can't work.

### ISSUE THREAD

**Issue by GergoKormoczy** [bagisto/bagisto#6954]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.3

### Issue Description

What should I do to make the bagisto core vue components like

```
Vue.component('layered-navigation', {
            template: '#layered-navigation-template',
}
```

work without include `<script type="text/javascript" src="{{ bagisto_asset('js/shop.js') }}" ></script>` because this bundle has much unnecessary js which I don't need (like @inotom/vue-go-top). But if I can't add my master.blade.php then Vue.component don't work (even if I added vue and vue-class-component by my hand)

### Preconditions

Nothing, it is a core question, already has too many issue with this..

### Steps to reproduce

Nothing, it is a core question, already has too many issue with this..

### Expected Result

I would like to see the vue filter..

```
Vue.component('layered-navigation', {
            template: '#layered-navigation-template',
}
```

### Actual Result

I can't see

```
Vue.component('layered-navigation', {
            template: '#layered-navigation-template',
}
```

### Screenshots

with `<script type="text/javascript" src="{{ bagisto_asset('js/shop.js') }}" ></script>`

<img width="368" alt="Képernyőfotó 2022-10-17 - 11 11 52" src="https://user-images.githubusercontent.com/84326426/196138311-40e563cf-3800-45cb-bbe1-bd2d294e964a.png">

without `<script type="text/javascript" src="{{ bagisto_asset('js/shop.js') }}" ></script>`

<img width="429" alt="Képernyőfotó 2022-10-17 - 11 12 46" src="https://user-images.githubusercontent.com/84326426/196138523-5818acc2-8c67-48b7-8b87-4739feb0b31b.png">

### Additional context

I haven't received a formal answer to my question for days, I've come across several of these here and on the forum. There is a license that includes what is in this bundle, but it is not willing to work even if I put all of them manually, it is only willing to do anything with this one shop.js bundle js..

let me know how I can delete unnecessary stuff in shop.js or how I can create my own shop.js or skip this whole thing and what should I include my master template for working vue.component.

Very frustrating for now.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please take a reference from [Here](https://github.com/bagisto/bagisto/issues/6879#issuecomment-1326341604),

**Comment by Sanjaybhattwebkul** [comment]
If **still** you have any **queries** then please raise a **support** ticket [here](https://bagisto.uvdesk.com/en/customer/create-ticket/)
