### ISSUE TITLE
Translation issue on the customers  order section in the arabic locale

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/bagisto#6957]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

Order  translation is missing in the Arabic locale 

### Preconditions

Setup Bagisto from the Master Repository 

### Steps to reproduce

1. Visit the admin end 
2. Change the app locale to Arabic. 
3. Go to the customers -> select orders.

### Expected Result

Should not be any translation issue on the customer order section in the Arabic locale.

### Actual Result

Order  translation is missing in the Arabic locale.

### Screenshots

![core2](https://user-images.githubusercontent.com/92033944/196171127-b0ff62b5-c653-460a-b468-7ad5af5b5d2d.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this **issue** is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/7pHIBYoLp306), for future reference.
