### ISSUE TITLE
 Translation issue on the export model box in the admin panel in Arabic locale

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6959]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Mater

### Issue Description

Getting Translation issue When the admin is trying to export the product's

### Preconditions

**1.** Admin should be login
**2.** Login users should have permission to export the products
**3.** Some products should be created.

### Steps to reproduce

**1.** log in as **admin** in **Arabic** locale.
**2.** Click on **products** inside the **catalog**
**3.** Click on the **export icon.**
**4.** Select the **export options**.

### Expected Result

The **export option** should be **translated** into **Arabic** locale.

### Actual Result

The **export options** are not **translating** in Arabic **locale**.

### Screenshots

Please find the **screenshot** [Here](https://prnt.sc/idFdbHqidFaN)

**Comment by Nikitajoshi39** [comment]
Please assign me this issue @Sanjaybhattwebkul

**Comment by JunaidJaved248** [comment]
@Sanjaybhattwebkul Check this PR #6960 , Issue fixed
