### ISSUE TITLE
Compare product page can be enhanced

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6972]
### Is your feature request related to a problem? Please describe.

The **add to cart** button is **breaking** into two lines in the **dutch** locale. Please find the screenshot [Here](https://prnt.sc/tXVMtiO9YUr7)

### Describe the solution you'd like

The **remove** and **wishlist** icons should be just **below** of **add to cart** button on compare page. Please take a **reference** from th**e below screenshot.**

![compare](https://user-images.githubusercontent.com/86394952/196704889-0885d53c-70c2-4880-8429-b355fe5991b4.png)

**Comment by shagun2405** [comment]
@Sanjaybhattwebkul assign this issue to me

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul  @shagun2405 
I am **reopening** this issue because I am getting the **UI issue** with the **wishlist icon.** on the product's **view** page.
Please find the **screenshot** [Here](https://prnt.sc/JVj-7mdHNmMv).
@papnoisanjeev    Please look into it.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/641d5e42af682a445352f9c0), for future reference.
