### ISSUE TITLE
Add tool tip on calendar and table icons on bookings in admin panel.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6987]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

In **Admin End**, **Sales section**, there we have an option to see the **Booking product** in list and calendar view, there we can add **tool tips** for the **notification.**

### Preconditions

It should be **noted** that there should be some **added** **information** related to the **booking** for a better **observation**.

### Steps to reproduce

**1.** Go to Admin -> Sales - > Booking
**2.** Click on the **Calendar and List View Icons.**

### Expected Result

Tool Tips information to be added for the **Calendar** and **List View**.

### Actual Result

Please check the **screenshot** for a better **understanding** of the **issue**.

### Screenshots

![Tool tips](https://user-images.githubusercontent.com/92721837/197111838-3188a780-dc0e-4598-a825-c948c02a6e87.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
