### ISSUE TITLE
No Events details are overlapping at bookings in admin panel.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6989]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we check the **Sales Section Bookings** information and there when we check the information in **calendar view**, after inspecting the details in **mobile view** it was found that the **No Events** text is **overlapping**.

### Preconditions

It should be **noted** that there should be some **added** **information** related to the **booking** for a better **observation**.

### Steps to reproduce

1. Go to the admin panel -> Sales -> Bookings.
2. Click on Calendar View Icon.
3. Inspect the details in mobile view.

### Expected Result

No overlapping of text should appear, information should appear clearly. Row tables should have proper space.

### Actual Result

Please check the **screenshot** for a better **understanding** of the **issue**.

### Screenshots

![Overlapping](https://user-images.githubusercontent.com/92721837/197114811-462c6803-8ffc-4e61-a032-45d096d801fc.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/6426d50d2a666707c404e365), for future reference.
