### ISSUE TITLE
Active category class missing

### ISSUE THREAD

**Issue by markteneikelder** [bagisto/bagisto#699]
When a parent category is selected the active class does not trigger the background to reposition. The radio button always shows the non-selected state.

**Comment by markteneikelder** [comment]
When trying to edit a product category the selected parent radio button active class is not set correctly. This way all the radiobuttons are unchecked and it is not visible which category is the parent.

**Comment by rahulshukla-webkul** [comment]
Hi @markteneikelder  Thanks for raising issue.
Can u please add screenshot or video for the same?

**Comment by markteneikelder** [comment]
Category 41 has a parent 18 (poetspapier) but does not show active when editing the child category.

![cat overview](https://user-images.githubusercontent.com/31850719/54432145-a42a2480-4728-11e9-9104-836d1dad3641.png)
<img width="668" alt="cat41-parent18" src="https://user-images.githubusercontent.com/31850719/54432146-a42a2480-4728-11e9-88ce-fa46f2613fc3.png">

**Comment by prashant-webkul** [comment]
@markteneikelder Hello, today we will be releasing a minor release please use that and this issue will get resolved.
More so ever if had selected parent category then it is saving inside the database correctly on the version you are using. Only on edit page for that category it was not showing the parent of it.

**Comment by markteneikelder** [comment]
@prashant-webkul I've upgraded to version 1.0.5 and the bug has not been fixed.

**Comment by prashant-webkul** [comment]
@markteneikelder  Really, I cannot believe its working for us on demo and on all dev systems:

![categoryissue](https://user-images.githubusercontent.com/41140572/54519855-7bef2f80-498d-11e9-9e49-3ef12f6d56e5.png)

**Comment by prashant-webkul** [comment]
May be you can edit all those categories and save them again by reassigning their parent.

**Comment by markteneikelder** [comment]
I tried saving the surrounding categories. Did not work for me. See attached images.
![image001](https://user-images.githubusercontent.com/31850719/54521256-d7f48c80-496a-11e9-934a-9920075c2244.jpg)
![image002](https://user-images.githubusercontent.com/31850719/54521257-d7f48c80-496a-11e9-91dd-95003940224c.jpg)

**Comment by prashant-webkul** [comment]
@markteneikelder Is root category visible on the top when you select the parent category for new or existing categories?

**Comment by markteneikelder** [comment]
@prashant-webkul No by default there was no root category in our system. I've added one now but it does not seem to fix the issue. Maybe it has something to do with the _lft and _rgt columns in the database?

![Schermafbeelding 2019-03-18 om 11 01 06](https://user-images.githubusercontent.com/31850719/54522391-62d68680-496d-11e9-8c28-a1a9eafad980.png)
<img width="798" alt="Schermafbeelding 2019-03-18 om 11 01 50" src="https://user-images.githubusercontent.com/31850719/54522396-65d17700-496d-11e9-8155-fad312609f30.png">

**Comment by prashant-webkul** [comment]
@markteneikelder You needed to run the seeder with the command php artisan db:seed. Bagisto puts all the categories inside root categories. As once seeder runs then all the categories comes under it.

**Comment by markteneikelder** [comment]
@prashant-webkul Is there a way to easily import categories (and content) into a clean installed version of bagisto? Then i'll delete our current installation and re-import the categories. The way the _lft and _rgt columns work are a complete mystery to me when there are parent/child relations in it.

**Comment by prashant-webkul** [comment]
@markteneikelder We are damn sure that big had been fixed and I am feeling really unfortunate that it didn't got resolved on your system.
Please try to install the new project and use the same database it should work after.
If not then delete all of your categories and recreate them.

**Comment by markteneikelder** [comment]
@prashant-webkul Created a completely new blank installation of Bagisto 1.0.5. The bug also seems to be in there. See attachments. 
<img width="785" alt="Schermafbeelding 2019-03-18 om 11 57 04" src="https://user-images.githubusercontent.com/31850719/54526298-9ec21980-4976-11e9-87d7-2607f50397ad.png">
![Schermafbeelding 2019-03-18 om 11 57 23](https://user-images.githubusercontent.com/31850719/54526299-9ec21980-4976-11e9-9d13-aea06bb65f96.png)

**Comment by prashant-webkul** [comment]
@markteneikelder When you created the category '**Test**' then you have to select a parent category for it, in this case while creating '**Test**' you have to select '**root**' as its parent. 
That is how it works.

**Comment by markteneikelder** [comment]
@prashant-webkul I get that. Also tried editing and reselecting root as its parent. It just does not show root as active/selected. See attached video.
[bagisto-categories-screencapture.mov.zip](https://github.com/bagisto/bagisto/files/2977795/bagisto-categories-screencapture.mov.zip)

**Comment by prashant-webkul** [comment]
@markteneikelder Its unfortunate but i am damn sure that parent system of your category is working. As your categories have been created according to parent you wanted.
Please keep patience and we will inspect the issue more and will provide a more concrete solution very soon.

**Comment by markteneikelder** [comment]
That is correct, it is saving according to parent selection. It seems like .radio .radio-view (background position for active) is not set correct on .tree-item.active

**Comment by prashant-webkul** [comment]
@markteneikelder We fixed this issue in this release but cannot understand why it is still persisting in your system.

**Comment by prashant-webkul** [comment]
**Hello**, @markteneikelder If its possible then please mail your dump of two tables '**categories** and '**category_translations**' on our support mail **support@bagisto.com**
And you can even file a support ticket at our dedicated support system https://bagisto.uvdesk.com
