### ISSUE TITLE
Details are unresponsive in bookings in Admin Panel when inspecting in mobile view.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6990]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we check the **bookings** information at the **admin end** in calendar view, there when we see the bookings information, when we take the **cursor** to the **booking information** it **automatically pops out with details.** 
Now when we **inspect** the detail in **mobile view**, there when we check the details are **not clearly visible**, The details should **appear clearly**. 

### Preconditions

It should be **noted** that there should be some **added** **information** related to the **booking** for a better **observation**.

### Steps to reproduce

**1.** Go to the admin panel -> Sales -> Bookings.
**2.** Click on **Calendar View** Icon.
**3.** Inspect the details in **mobile view.**
**4.** There we will be able to see the **issue**.

### Expected Result

The **Details** should be **clearly visible** in the **mobile view** with full details appearing in the desktop view.

### Actual Result

Please check the **Video** for a better **understanding** of the **issue**.

**Video**

https://user-images.githubusercontent.com/92721837/197118876-93ae457e-b5de-40ca-ac47-bdbf51754959.mp4

### Screenshots

Please check the **Screenshot** for a better **understanding** of the **issue**

**Screenshot**

![Mobile view](https://user-images.githubusercontent.com/92721837/197119344-e439364f-f7a7-43ba-a057-3f61df4a9979.png)

**Comment by prabhatkumaroc082** [comment]
found calendar view bug - https://github.com/bagisto/bagisto/issues/7142

**Comment by prabhatkumaroc082** [comment]
@ashishkumar-webkul 
it will auto-managed as per event date and time. already hover event is there to view full length content.

height will be adjusted as per slot time so can't set 100% height or display in other slot. 

In above video, 11-11:40 slot could be availed by multiple users, similarly nearby slots i.e., 12:00-1:00, etc could be filled by different events so can't display single event in different slot.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
As we discuss this is not an issue. so I am closing this issue.
