### ISSUE TITLE
Mobile view UI issue in booking product creating and editing them. Same slots all days, slot details.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6991]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we **create** or **edit** a **booking product**, there we can see the options of **Same Slots all days,** **inspecting** the details in **mobile view** we will be able to see the UI **issue** in the slots.

**THIS ISSUE IS APPEARING IN BELOW BOOKING TYPES**
**1.** Appointment Booking
**2.** Rental Booking
**3.** Table Booking

### Preconditions

**Create** a **new booking product** for a clear **observation** of the UI issue in **mobile view**.

### Steps to reproduce

1. Go to Admin -> Catalog -> Products -> Add Product -> Create a new booking product.
2. Inspect the details in mobile view.
3. **Select** the **booking type** - appointment
4. Select the **Same Slots all days** - **yes or no.**
5. In both the **selections** of slots we will be able to see the UI **issue**.

### Expected Result

The UI of the slot details and the icons which are used should be in proper position.

### Actual Result

Please follow the **Screenshots** for a better understanding of the **issue**.

### Screenshots

**Screenshots**
Same Slots all Days - NO

![Same Slots all Days No](https://user-images.githubusercontent.com/92721837/197130110-10d4c533-5cd9-45e8-b7e1-a5c8b41787b8.png)

Same Slots All Days - YES
![Same Slots all Days Yes](https://user-images.githubusercontent.com/92721837/197130128-4b130bf6-b296-45dc-a824-99d931d57c87.png)

**Comment by JunaidJaved248** [comment]
@ashishkumar-webkul Issue Fixed with this PR #7036
