### ISSUE TITLE
Add scroll bar in Tickets section, if the admin is creating the event booking

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#6993]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When checking the details related to the **Event Booking**, while inspecting the details in **mobile view**, the  tickets section UI is not proper, infact the whole page is **responsive**. It would be better if a **scroll bar** can be added for **mobile view** for tickets section in **Event Booking Product**.

### Preconditions

It would be much better if  a **new event booking product** is **created** for the checking of the **issue**.

### Steps to reproduce

**1.** Go to Admin -> Catalog -> Products -> Create a new Booking Product - > Select Event Booking.
**2.** Now check the Ticket Section.
**3.** Inspect the details in Mobile view, there we will be able to see the issue.

### Expected Result

Scroll bar Should be added in tickets section, if the admin is creating the event booking

### Actual Result
The complete page is scrolling if the admin is scrolling the tickets section.

### Screenshots

Please find the screenshot [Here](https://prnt.sc/fdZz40gO70OY)

**Comment by JunaidJaved248** [comment]
@ashishkumar-webkul Issue Fixed with this PR #7035
