### ISSUE TITLE
i18n: (spanish) Update missing translations 

### ISSUE THREAD

**Issue by hereje** [bagisto/bagisto#7051]
### Is your feature request related to a problem? Please describe.

18n: (spanish) Missing translation

### Describe the solution you'd like

Update missing translations for the following files:

- [x] `packages/Webkul/Tax/src/Resources/lang/es/app.php` - update translation
- [x] `packages/Webkul/Ui/src/Resources/lang/es/app.php` - update translation
- [x] `packages/Webkul/Admin/src/Resources/lang/es/app.php` - fix spellings
- [x] `packages/Webkul/Velocity/src/Resources/lang/es/app.php` - fix spellings
- [x] `packages/Webkul/Core/src/Resources/lang/es/validation.php` - update translation
- [x] `packages/Webkul/Shop/src/Resources/lang/es/app.php` - fix spellings , update translation
- [x] `packages/Webkul/Paypal/src/Resources/lang/es/app.php` - Create translated file

### Additional context

After comparing the base files (english) against the translated files (spanish) you can notice some translations are not completed or they are missing.

I listed both the base translation folders and the target folders (in my case spanish `es`) and did a manual comparison, first by folder and then reviewing the content of each translated file.

```bash
# Feel free to improve my snippet
# your target lang
FIND_LANG=es;
echo "current lang to find $FIND_LANG";


# Base lang is english
BASE_LANG=en;
echo "List base lang files";
find "$PWD" -type d -name $BASE_LANG -exec ls -d "{}" \; 

echo "List lang files to verify if missing";
find "$PWD" -type d -name $FIND_LANG -exec ls -d "{}" \; 

#Unset variables
unset $FIND_LANG;
unset $BASE_LANG;
```

**Comment by Sanjaybhattwebkul** [comment]
@hereje 
Can you please create a single pr for this issue.?

**Comment by hereje** [comment]
> @hereje Can you please create a single pr for this issue.?

Done!
