### ISSUE TITLE
Getting exception after run composer update.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7067]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

Getting exceptions when I am running the composer update after installing Bagisto using composer.

### Preconditions

The project should be installed by using composer [ composer create-project bagisto/bagisto ]

### Steps to reproduce

**1.** Install **bagisto** using the **composer** [_composer create-project bagisto/bagisto_ ]
**2.** Run the **_composer install_** command after completing the installation.
**3.** Visit the **shop**
**4.** See the error

### Expected Result

There should not be an **exception** if the admin runs the **composer update** command on the project's root **directory**.

### Actual Result

Getting the **exception** if the admin is running the **composer update** command after installing the project **using** the **composer**.

### Screenshots

Please find the **screenshot** [Here](https://prnt.sc/tRrLCJnQ6lgY)

**Comment by simokassab** [comment]
Dears,

Any update about this issue ?

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
@papnoisanjeev  is working on this issue, we will update you once this will fixed.

**Comment by lalitawagh** [comment]
Hello Team,

Any update about this issue ?Because we are facing issue on live instance through github

**Comment by devansh-webkul** [comment]
This is because of the DB Blade compiler dependency, as their version is not updated with the latest laravel version,
https://github.com/Flynsarmy/laravel-db-blade-compiler/issues/58

Either we need to check the alternative or we should wait for them to fix it.

**Comment by devansh-webkul** [comment]
It is not recommended to composer update unless and until you know what you are doing.

I am closing this issue, we will fix this when we upgrade our Laravel version and all other dependencies.

**Comment by harounbest** [comment]
i am facing the same problem, after having installed a fresh bagisto installation

**Comment by devansh-webkul** [comment]
If this is in a fresh instance then it must be an issue. In that case, we need to lock the Laravel version till the DBView compiler fixing.

@Sanjaybhattwebkul,
Can you verify this on a fresh instance?

**Comment by Sanjaybhattwebkul** [comment]
@harounbest 
Is it possible to share the steps which you followed for installing the Bagisto? Because I am not getting this issue while installing the Bagisto

**Comment by harounbest** [comment]
@Sanjaybhattwebkul I used the composer installation process,
1- I downloaded the bajisto store from repos
2- I set the .env file 
3- I run the "php artisan key:generate command 
5-i created the database, and I run the "php artisan migrate" followed by the "php artisan db:seed"
4-i run the command "php artisan vendor:publish" and linked the storage directory 
after that, I run the command "php artisan serve" that's when I get the error "Illegal offset type in isset or empty (View: D:\website\Bagisto\bagisto\resources\themes\velocity\views\home\index.blade.php)"

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please follow the below **steps** for installing the **Bagisto**.

**1.**  _composer create-project bagisto/bagisto_
**2.** _cd bagisto_
**3.** Configure the database details on the  **_.env_** file. 
**4.** _php artisan bagisto:install_

**Comment by Sanjaybhattwebkul** [comment]
@harounbest 
If still you are getting the same issue. then please let me know.

**Comment by harounbest** [comment]
@Sanjaybhattwebkul  unfortunately yes, I am still getting the same issue.

**Comment by harounbest** [comment]
@Sanjaybhattwebkul  unfortunately yes, I am still getting the same issue.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please raise a **ticket**  [here](https://bagisto.uvdesk.com/en/customer/create-ticket/), i **need** to check  on your system.

**Comment by devansh-webkul** [comment]
Hi @harounbest,

Please check this,
https://github.com/Flynsarmy/laravel-db-blade-compiler/issues/58#issuecomment-1288522289

I am sure this will help you.

Rest we are tracking this also. We will fix this when we update all of our dependencies.

**Comment by Mohitupa** [comment]
hello I am getting this error (Illegal offset type in isset or empty (View: /opt/lampp/htdocs/bagisto/bagisto-fisrt2/resources/themes/velocity/views/home/index.blade.php)) in my bagisto demo project in home page at this line 
{!! DbView::make($velocityMetaData)->field('home_page_content')->render() !!}

**Comment by akramcheraifia** [comment]
i'm facing the same problem

**Comment by devansh-webkul** [comment]
I am removing the db blade compiler dependency and giving a fix.

**Comment by devansh-webkul** [comment]
Fixed.
