### ISSUE TITLE
Dark Mode Name should be used.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7072]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

In Admin End, there when we change the Dark Mode Toggle button, there we can see the name is **Mode**.
It should be **Dark Mode**

### Preconditions

**Bagisto** Should be **installed** and the **Admin Panel** should be checked for the same.

### Steps to reproduce

1. Go to **Admin Panel**
2. Profile Drop Down -> Mode.

### Expected Result

The Name for the changing the Dark mode toggle button should be **DARK MODE**.

### Actual Result

Currently we can see that only Mode is visible.

### Screenshots

![Dark Mode](https://user-images.githubusercontent.com/92721837/199650732-0e2f96ef-1a0a-4529-89a4-21364242efbc.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/Qs9FY8OaOKsF), for future **reference**.
