### ISSUE TITLE
Alignment page Header should be in centre.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7073]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

The Alignment at  the page header should be in centre. When we create a new product, Category etc. there we can see the Add contents box should be shifted in centre.

### Preconditions

**Bagisto** should be installed and **Admin panel** should be **working**.

### Steps to reproduce

1. Go to the **Admin Panel**
2. Try to create a new Product, category, attribute etc.
3. Check the same concern for all other sections in the Admin Panel.

### Expected Result

The Alignment should be in centre. 

### Actual Result

Please check the screenshot for the issue.

### Screenshots

![Centre](https://user-images.githubusercontent.com/92721837/199652600-c1446443-aac9-4d80-902d-ac70b8728729.png)

**Comment by JunaidJaved248** [comment]
@ashishkumar-webkul Issue Fixed

**Comment by akhtarkhan1** [comment]
@ashishkumar-webkul 
Not able to reproduce the issue. Click [Here](https://prnt.sc/P0hkv8QR9Uvy)
