### ISSUE TITLE
Customer Review Images should pop-up and should be clearly visible with review.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7075]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When a customer Review a product with images, We should be able  to see the image clearly, after the approval of the Review from Admin End. We are unable to click the review image.

### Preconditions

**1.** The **Product** should be **Reviewed** with the **Images**.
**2.** **Review** should be **approved** from the **Admin End**.

### Steps to reproduce

1. Go to Store Front and Review a Product with Images.
2. Now go to the Admin End -> Customers -> Reviews -> Approve the Reviews.
3. Now check the same product at store front.
4. Click on the review images.

### Expected Result

The **review images** should **pop-up** with the **Review Comment and Stars Rating.**
If there are **multiple images** in the Reviews then we should be able to see **all the images with the help of Left Right Arrows**.

### Actual Result

Please Consider the Video for a better understanding of the **Suggestion**.

**Video**

https://user-images.githubusercontent.com/92721837/199734167-c7f3f075-f2b9-4655-85c1-4ad5c3ecfb05.mp4

### Screenshots

This is just a sample Screenshot. The Review should visible as similar as the Quick View pop-up box.

**Sample**

![Sample ](https://user-images.githubusercontent.com/92721837/199734715-dd2e80c3-bc0c-4d1c-811a-3e2758258f63.png)

**Comment by devansh-webkul** [comment]
No need will implement a new theme.
