### ISSUE TITLE
QTY check should be applied on the simple product which are added in Group Product.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7079]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we add a **simple product** to the **group product**, there we are able to **save** any qty,  even if the **simple product** qty is **less**.

Example.

**Simple Product QTY - 1000**

In Group Product when we add the same simple product we are able to save **above 1000.**

### Preconditions

**1. Simple Product with specific qty should be created in the Admin End.**
**2. We should be able to add the simpler product to the group product.**

### Steps to reproduce

1. Go to Admin End -> Create a Simple Product with specific QTY.
2.  Create a group Product and add the simple product to the Group Product.
3.  Once the product is added , please add the qty in group product more then the simple product.
4.  Now save the product.

### Expected Result

In group product we should not be able to save the group product if the simple product qty is more then that of the actual qty.
QTY check should be applied in the group product. less then or equal to the simple product qty should be added in the group product.

### Actual Result

Please follow the screenshot for a better understanding of the issue.

Here we are able to save the group product with more qty of the simple product.

### Screenshots

**Screenshot**

![QTy](https://user-images.githubusercontent.com/92721837/199905898-4654534c-3fba-4559-9b01-6736d7119eb3.png)

**Comment by ashishkumar-webkul** [comment]
This issue is appearing for the Bundle Product as well. Please fix the issue for the bundle product also.

**Comment by JunaidJaved248** [comment]
@ashishkumar-webkul Issue Fixed with this PR #7094 
I have Fixed this Soln for Grouped product, please check it first then I will implement on that bundle product also. Thanks

**Comment by atul-webkul** [comment]
i am working
