### ISSUE TITLE
Add Option button should shift downward for adding a new option in Bundle Product.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7080]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we create a **bundle product,** there we can see **Add option Button**, Once we add Options and we need to create a new Option, there we need to **scroll up** and then we select the add option button. It would be **better** if the **Add Option button** **shifts downward.**

### Preconditions

**1.** Simple product should be created so that to add the product to bundle options.
**2.** At least one option should be added, so that we can add new option.

### Steps to reproduce

1. Go to Admin -> Create a Bundle Product -> Add Options.
2. After adding First option, now create another option.
3.  Here we need to scroll up and then we select the add option button.

### Expected Result

It would be much better if the Add Option Button shifts downward after we add a new option. So that if we need to create another option so we would not scroll up for the button, in bottom we can see the button we can add directly.

### Actual Result

Please check the **video** for a better **understanding** of the **enhancement** what we can do in it.

**Video**

https://user-images.githubusercontent.com/92721837/199908038-f1e70d31-9080-434d-b694-6a480c81426c.mp4

### Screenshots

Please check the screenshot where we can add the button.

![Add option](https://user-images.githubusercontent.com/92721837/199908240-aa1be98b-9609-4847-ad4b-9aef5e2cb8d1.png)

**Comment by JunaidJaved248** [comment]
@ashishkumar-webkul Issue Fixed with this PR #7084

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have **attached** a **screenshot** below for **future** reference.

![addoption](https://user-images.githubusercontent.com/86394952/204759800-fb570226-7fbb-481a-a8a2-5a2a396ce71c.png)
