### ISSUE TITLE
Change the language code of bengali 

### ISSUE THREAD

**Issue by heysagnik** [bagisto/bagisto#7085]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Issue Description

I found in the Webkul package that the bengali language code is `ben` but actually it should be `bn`

**Comment by Sanjaybhattwebkul** [comment]
@heysagnik 
I have **fix** this **issue**, Can you please **verify** this: https://github.com/bagisto/bagisto/pull/7088

**Comment by heysagnik** [comment]
Here it's not [changed](https://github.com/bagisto/bagisto/tree/change-bengali-locale-code/packages/Webkul/Customer/src/Resources/lang/ben)

**Comment by Sanjaybhattwebkul** [comment]
@heysagnik 
Changes **done** for customer package.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
