### ISSUE TITLE
Allignment should be in straight line in Bundle Product Name text.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7091]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we create a bundle product and then we add options, there after adding simple product, after adding the simple product, there we can see the name text is a bit on upper side, which actually should be in proper line.

### Preconditions

1. Bagisto Admin panel should work properly.
2. Simple Product should be created for adding the product in bundle.

### Steps to reproduce

1.  Go to Admin Panel -> Catalog -> Create a Bundle Product.
2.  In Bundle Product -> Add options -> Add Product.
3. After adding products check the name, id and qty box alignment, there we will be able to see the UI issue.

### Expected Result

The alignment should be in straight line.

### Actual Result

Here we can see that the product name text is appearing a bit above the centre.
Please check  the screenshot for a better understanding of the issue.

### Screenshots

![Bundle Image](https://user-images.githubusercontent.com/92721837/200496883-37daf731-b930-4279-abcf-bd643ae9e528.png)

**Comment by JunaidJaved248** [comment]
@ashishkumar-webkul Issue Fixed with this PR #7092
