### ISSUE TITLE
add decimal to currency

### ISSUE THREAD

**Issue by gh-darvishani** [bagisto/bagisto#7096]
### Is your feature request related to a problem? Please describe.

in some of currency we have not any decimal for example in iranian currency (toman and rial) we have not some thing like this 
125.22 irt
so we need to add decima to curreny that I aleardy did it 

### Describe the solution you'd like

please review my PR :
https://github.com/bagisto/bagisto/pull/7095

**Comment by devansh-webkul** [comment]
PR is merged,
https://github.com/bagisto/bagisto/pull/7095

**Comment by devansh-webkul** [comment]
Hi @gh-darvishani,

Thank you for your contribution. :rocket:
