### ISSUE TITLE
New currency code not saved in capitals

### ISSUE THREAD

**Issue by markteneikelder** [bagisto/bagisto#711]
When creating a new currency the code is "faked" to uppercase in the input field but when saving it's actually saved as lowercase. Since you can't edit the code afterwards it's no longer consistent with the default Dollar currency.

**Comment by prashant-webkul** [comment]
@markteneikelder We verified the issue and we found out that you were saying right. But we are follow ISO 4217 standards which says to display currency codes in caps. While saving it in DB is our own format for matching currencies so there is a system wide consistency for devs.

**Comment by markteneikelder** [comment]
Might be good for system wide consistency to change the database seed that imports USD to usd? Now only USD is saved in caps in the database and every self created currency is not capitalized.

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Fixed. Now all currency code will be saved in caps
![Screenshot (2)](https://user-images.githubusercontent.com/45203177/55135437-b1480a00-5151-11e9-9d13-da51c03d459d.png)
