### ISSUE TITLE
The special price should be visible if the special price is less than the catalog rule price of a 

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7114]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

If the _special price_ is less than the _catalog rule price_ then the _catalog rule price_ is visible in the shop.

### Preconditions

**1.** Admin should be login
**2.** A product should be created with a special price.
**3.** The catalog rule should be applied to the same product.
**4.** The special price of that product should be less than the catalog rule price.

### Steps to reproduce

**1.** Go to the 'admin' Panel'
**2.** Create a new product with a special price
**3.** Create the catalog rule for the same product
**4.** The special price of that product should be less than the catalog rule price.
**5.** Select the Special price date day after today.
**6.** Visit the shop
**7.** Search the created product
**8.** See the error

### Expected Result

the _special price_ should be visible if the _special price_ is less than the _catalog rule price_ of a 

### Actual Result

The _catalog rule price_ is visible if the _special price_ should be visible if the _special price_ is less than the _catalog rule price_ of a 

### Screenshots

**_Admin panel creates a product with a special price and catalog rule_**

![product](https://user-images.githubusercontent.com/86394952/202644812-683630c1-f18c-4952-b085-32f773c58aea.png)

**_After searching for the created product in the shop._**

![shop](https://user-images.githubusercontent.com/86394952/202644823-b1bb677d-d68b-404d-b405-0fc774f8185b.png)

**Comment by prabhatkumaroc082** [comment]
@Sanjaybhattwebkul 
Here is the test case that i applied but special price is showing
[back-end product page](https://user-images.githubusercontent.com/50438561/202694441-b461f1e4-5fd7-42b5-8263-caa1dc5bc492.png)
[catalog rule](https://user-images.githubusercontent.com/50438561/202694498-ca1d22a0-33c2-4c2c-9216-2835c3436443.png)
[front-end product page](https://user-images.githubusercontent.com/50438561/202694551-ac94b119-e1c2-4b53-b780-91a99697c1d5.png)

In the shared image of issue description, I noticed special price date range from 2022-11-08 to 2022-11-09 which is old date as per today. kindly verify once if it is affecting.
