### ISSUE TITLE
Overlapping of cross icon in Search bar in customer profile.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7117]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

After login to the customer profile, there when we search any details where we can see the search bar, when we fill the details in the search bar we can see that the cross icon is overlapping.

### Preconditions

Login to the customer profile
Check the search bar in customer order section.

### Steps to reproduce

1. Go to Customer Profile -> Orders -> Search anything in the order section with search bar.
2.  When we will fill the details, we will be able to see the cross icon is overlapping.

### Expected Result

The cross icon should not overlap with the search bar.

### Actual Result

For a better **understanding** of the **issue** please check the **screenshot** for the **issue**.

### Screenshots

![Uploading Overlapping.png…]()

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Now not working please look into it.

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

First fetch all latest master updates (If bagisto master branch added as remote i.e upstream)

 **git fetch --all** 

**git reset hard upstream/master**

Finally run publish command and clear project cache and make a try.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is fixed. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/QOS3PuR2MFgG), for **future** reference.
