### ISSUE TITLE
The products are not visible on the channel for which channel updated by the admin.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7122]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

If we have two channels Channe-A and Channel-B, and 1 product is created for Channel-B, then that product is visible on only Channel-A

### Preconditions

Admin should be logged in
There should be multiple channels. 1. Channel-A and Channel-B.
A product should be created For channel-B

### Steps to reproduce

1. Go to the 'admin' panel
2. Click on 'Create multiple channels
3. Click on create product inside the catalog/products
4. Create a product and select only one channel from the channels section.
5. Visit all the channels and search for the created product
6. See an error

### Expected Result

The product should be visible only on the channel, for which the product is updated by the admin.

### Actual Result

The product is visible only on the channel-A.

### Screenshots

![ss-3](https://user-images.githubusercontent.com/86394952/203236631-4bb04a24-4400-4c3c-8866-d84131cbc10a.png)

**Comment by Amitk-webkul** [comment]
@akathuria289 
Any Update?

**Comment by devansh-webkul** [comment]
We are on the verge of removing the product_flat fully so to fix this we will make the status channel-wise.
