### ISSUE TITLE
Event Product UI issue in the ticket description.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7128]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we check the Event Product in the store front, there we can see that the tickets description is not in proper UI. Please fix the issue.

### Preconditions

1. Create a Event Booking Product from the admin end.
2. Make sure all the details should be filled and at least 2 tickets should be added.

### Steps to reproduce

1. Create a Event Booking Product from the admin end.
2. After creating the product go to the store front.
3.  Search the Event product and check the product in product view page.
4. Now there we will be able to see the tickets and its description.

### Expected Result

The Description should be displayed properly and UI should be clear.

### Actual Result

Please check the screenshot for a better understanding of the issue.

### Screenshots

![UI issue at event product](https://user-images.githubusercontent.com/92721837/203516965-2ae1a10c-a298-4de6-8795-e21d701d7cdb.png)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 

Here with this PR have fixed **ticket description** position, now if we shift quantity box down it will collapse with description so no need to change quantity box position here.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/PfbaHbA0MpwE), for future **reference**.
