### ISSUE TITLE
Validation message should appear in Event Booking Product tickets End Date Section.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7130]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we create a Event Booking  product and  then we set the Start Date and End Date of the Event. After that when we create the Tickets, in tickets when we add Special Price and in special price Valid from and Valid til, there in Valid till we are able to see that no validation message is added, if we add date after the event is ending.

### Preconditions

1. Create a Event Booking Product
2. Add the Event Start Date and End Date.
3. Once this is done, now create the tickets.

### Steps to reproduce

1. Go to Admin -> Catalog -> Products -> Create a booking Product.
2. Now Fill the details and select booking type - Event Booking.
3. Now add Event Start Date and End Date.
4. Now add Tickets, there in Valid till Date, add the date after the event is over.
5. See error, there we are unable to see the validation message.

### Expected Result

If we select the date which is more than the Event End date then a validation message should appear.

### Actual Result

Please check the screenshot for a better understanding of the issue.

### Screenshots

![Validation message at tickey](https://user-images.githubusercontent.com/92721837/203698886-3dc29d15-6e22-4621-bfe2-a37ad7795982.png)

**Comment by akhtarkhan1** [comment]
@ashishkumar-webkul 
I have checked the issue, This issue is not valid.
