### ISSUE TITLE
We are able to save Event Booking Product with tickets valid till more then the event end date.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7132]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we create a Event Booking product and then we set the Start Date and End Date of the Event. After that when we create the Tickets, in tickets when we add Special Price and in special price Valid from and Valid til. 
Make sure Valid till Date should be more then the event date.]
Once the details are added and then save it. We are able to save the product.

### Preconditions

1. Create a Event Booking Product
2. Add the Event Start Date and End Date.
3. Once this is done, now create the tickets.

### Steps to reproduce

1. Go to Admin -> Catalog -> Products -> Create a booking Product.
2. Now Fill the details and select booking type - Event Booking.
3. Now add Event Start Date and End Date.
4. Now add Tickets, there in Valid till Date, add the date after the event is over.
5. Once the details are added and save the product. We are able to save it.

### Expected Result

The product should not be saved if the Valid date of the ticket is more then the end of the event.

### Actual Result

Please check  the video for the reference for understanding the issue in a better manner.

### Screenshots

https://user-images.githubusercontent.com/92721837/203706191-ce390760-f8df-4593-9a1c-f13874dc814e.mp4

**Comment by prabhatkumaroc082** [comment]
found something that these dates are not in use.
