### ISSUE TITLE
UI issue in the Event Booking Product Tickets section after validation message appears.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7133]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we create a Event Booking product and then we set the Start Date and End Date of the Event. After that when we create the Tickets, in tickets when we add Special Price and in special price Valid from and Valid till make sure we add incorrect information so that validation message appears. Once the validation message appears check the calendar icon and also the table content moves upwards.

### Preconditions

1. Create a Event Booking Product
2. Add the Event Start Date and End Date.
3. Once this is done, now create the tickets.

### Steps to reproduce

1. Go to Admin -> Catalog -> Products -> Create a booking Product.
2. Now Fill the details and select booking type - Event Booking.
3. Now add Event Start Date and End Date.
4. Now add Tickets, there we need to add incorrect details, then validation message appears.
5. Now we will be able to see the UI issue is appearing.

### Expected Result

1. The calendar icon should be in proper position.
2.  The table content should not shift upward. it should remain in the same position. 

### Actual Result

Please check the screenshot for a better understanding of the issue. 

### Screenshots

![UI issue in ticket section](https://user-images.githubusercontent.com/92721837/203708743-b8726bb0-ca6a-472f-a8bb-7e81cf1132da.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://prnt.sc/k2xusplly1Lq), for **future** reference.
