### ISSUE TITLE
UI issue in downloadable product, download information section.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7135]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

After creating the downloadable product, there when we add the downloadable product information, there we can see the UI issue appearing.
The information box should be in same line and the add option other information should come below the box.

### Preconditions

1. Admin end should work properly.
2. Need to create a downloadable product.

### Steps to reproduce

1. Go to Admin -> catalog -> Products -> Create a downloadable product.
2. Click on Downloadable Information.
3. There we can see the UI issue.

### Expected Result

The Content box should appear in the same line and the add details should appear below the box.

### Actual Result

Please check the screenshot for a better understanding of the issue.

### Screenshots

https://prnt.sc/j4g2B0yWTde6

**Comment by prabhatkumaroc082** [comment]
explained here - https://github.com/bagisto/bagisto/issues/7136#issuecomment-1328025349
