### ISSUE TITLE
UI issue in mobile inspect and Desktop view -> Configurable product variants add section.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#7136]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

MASTER

### Issue Description

When we create a Configurable product and add  variant details, there we can see the UI issue in the Add image section. weather we add a single  image or multiple image we can see that the UI issue is still appearing. Checked the issue in the mobile view and desktop view.

### Preconditions

1. Admin end should work properly.
2.  Able to create a Configurable product.

### Steps to reproduce

1. Go to Admin -> Catalog -> Product -> Create a configurable product.
2. Now in the variants section add the details and images.
3.  Check the UI of the variants image section in Mobile View and Desktop View.
4.  There we will be able to see the UI issue.

### Expected Result

The Variants images should be clear and there should be no overlapping in the Delete button in mobile view.
All the images delete button should be in proper place. 
In Desktop View and Mobile Inspection view the details should appear clear.

### Actual Result

Please check the screenshots for a better understanding of the issues. Please check for the reference.

### Screenshots

**Desktop View**

![Desktop View](https://user-images.githubusercontent.com/92721837/203727589-a3d20ee2-6711-4380-aed0-56a9a195a726.png)

**Mobile View**

![Mobile view](https://user-images.githubusercontent.com/92721837/203727643-c84f355e-2405-4280-9fb0-b76019eb1b04.png)

**Comment by prabhatkumaroc082** [comment]
added changes for images responsive [here](https://github.com/bagisto/bagisto/pull/7149). 

other input fields are adjusted above as per content, it is set in all data grid to middle the vertical alignment, you must face the same in each grid. no need to apply any fixation for this.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
**All** the **input fields** should be in **alignment**, please take a **reference** from [Here](https://prnt.sc/cD1smAAYqjVm)
