### ISSUE TITLE
Ability to drag product image to upload

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7157]
### Is your feature request related to a problem? Please describe.

Ability to drag product images to upload product images.

### Describe the solution you'd like

There should be an option for dragging and dropping the product's image while editing the product.

**Comment by gitesh-webkul** [comment]
Pls assign this issue to me.

**Comment by Amitk-webkul** [comment]
please add Drag and Drop message in the category section.


![drag](https://user-images.githubusercontent.com/106804569/226891466-d79f10a6-d023-4f8f-abef-cd84eb12c5bf.png)

**Comment by Amitk-webkul** [comment]
@suraj-webkul It is working fine.
