### ISSUE TITLE
Improve the product card on the home page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7158]
### Is your feature request related to a problem? Please describe.

Improve the product card on the home page. if there is any bundle product then the size of product cards is not alignments.

### Describe the solution you'd like

**1.** Replace display: flex; with display: grid;  in the product card.
_**Use this CSS**_ :
  ````
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(225px, auto));
  gap: 20px;
  }
````
**2.** Remove the extra space between product detail in the product's card. **[** _for this take reference from the below screenshot_ **]**
**3.** The product card should be responsive on mobile.

### Describe alternatives you've considered

Please take a reference from the below screenshot.

![image (2)](https://user-images.githubusercontent.com/86394952/204508793-6bb46756-38cd-43f6-927c-93062483ea43.png)

**Comment by prabhatkumaroc082** [comment]
alignment issue also found with [configurable product](https://user-images.githubusercontent.com/50438561/205047916-40c9c7c6-fc86-43fd-afe5-b892852b453b.png)

**Comment by prabhatkumaroc082** [comment]
issue with [mobile view](https://user-images.githubusercontent.com/50438561/205048401-65f92378-5a0d-4d26-9466-29e34f27674f.png)

**Comment by prabhatkumaroc082** [comment]
another issue, product card UI is not similar in pages like search, category, home, etc
references: [home](https://user-images.githubusercontent.com/50438561/207863973-553dce13-92b7-4114-b7d7-e23aa5c39330.png), [search](https://user-images.githubusercontent.com/50438561/207863993-6dd20237-d4f9-4ad6-a652-ec0a4425eba3.png)

**Comment by devansh-webkul** [comment]
No need. Will implement new theme.
