### ISSUE TITLE
Url is not working "Add to Cart"  in drop shipping manager

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#717]
in dropshipping manager>>orders  module when we click on "**Add to cart" from backend, the blank page opened
![issue1](https://user-images.githubusercontent.com/47665137/54593065-b15e5080-4a53-11e9-9871-cfea7c5d101a.png)
![Screenshot from 2019-03-19 14-27-53](https://user-images.githubusercontent.com/47665137/54593093-bcb17c00-4a53-11e9-921b-d9704f75bc09.png)

**Comment by jitendra-webkul** [comment]
This issue in not related to bagisto.
