### ISSUE TITLE
The country in not visible in shipping and billing address

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7178]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

if the admin and customer are trying to view the invoice then The country is not visible in the shipping and billing address section.

### Preconditions

1 order should be created by the admin.
The billing and shipping address should be selected by the customer while creating the order.

### Steps to reproduce

**1.** Go to the shop
**2.** Create an order.
**3.** Select the billing and shipping address.
**4.** Go to the admin panel
**5.** Create shipping and invoice for the order.
**6.** Try to view the country in the billing/shipping address.
**7.** See an error

### Expected Result

The country should be visible in the invoice that they selected while creating the order.

### Actual Result

The country is not visible in the voice in the billing and shipping address section.

### Screenshots

![ss](https://user-images.githubusercontent.com/86394952/205635318-1e3284c5-c6cc-425e-8507-2353b91c52d2.png)

**Comment by alshahari1** [comment]
Didn't notice the error
![Uploading no bug.png…]()

**Comment by alshahari1** [comment]
Didn't notice the error

**Comment by Sanjaybhattwebkul** [comment]
Hi there,

Which version of **bagisto** are you using?

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/63eb40c9bf991905516aad2f), for future reference.
