### ISSUE TITLE
By default 12 should be selected in the item per page dropdown on the products listing page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7180]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

By default 12 should be selected in the item per page dropdown on the products listing page, if the customer is trying to shop by category by default 9 is selected.

### Preconditions

**1.** Some categories should be created.
**2.** At least 12 products should be added to the category.

### Steps to reproduce

1. Go to 'Shop'
2. Click on 'category in the top left corner.

### Expected Result

12 Products should be visible on 1 page. in the listing page.

### Actual Result

Only 9 products are listed on the products listing page.

### Screenshots

![sded](https://user-images.githubusercontent.com/86394952/206099362-d3e19f62-7d18-46d5-a39e-7e13e43e7f51.png)

**Comment by shivamwebkul** [comment]
I am working on it.
