### ISSUE TITLE
The Advertisement images are stretching in mobile view.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7190]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The Advertisement images are stretching in mobile view.

### Preconditions

 Advertisement images should be added by the admin.

### Steps to reproduce

**1.** Go to the 'admin panel'
**2.** Add Advertisement images from the **velocity / meta-data** section.
**3.** Visit the shop in mobile view.
**4.** View the uploaded Advertisement.
**5.** See an error

### Expected Result

The Advertisement images should be stretched in mobile view. Please take a reference from the below screenshot.

![screenshot_2022_12_12_at_12 52 08_pm](https://user-images.githubusercontent.com/86394952/206986080-04e52d03-658b-4e0d-be1b-9852eea59eca.png)

### Actual Result

The Advertisement images are stretching in mobile view. Please find the below screenshot.

### Screenshots

![screenshot_2022_12_12_at_1 02 22_pm](https://user-images.githubusercontent.com/86394952/206987182-2aacbc39-7a1f-41e8-b89a-3d5c342a44f6.png)

**Comment by suraj-webkul** [comment]
please assign this issue to me

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
