### ISSUE TITLE
Login as customer icon should be change in the admin panel.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7194]
### Is your feature request related to a problem? Please describe.

The log-in as customer icon should be changed in the admin panel.

### Describe the solution you'd like

There should be a signout icon instead of a lock icon if the admin is trying to log in as admin.

### Describe alternatives you've considered

Please find the below screenshot

![Screenshot(1)](https://user-images.githubusercontent.com/86394952/207535643-1139d7ad-fbb8-42b4-afd0-212c014649bd.png)

**Comment by shivamtiwariwebkul** [comment]
please assign me this issue

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/641d5d44af682a445352f99f), for future reference.
