### ISSUE TITLE
Mas Actions are not working in the admin panel.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7195]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The mass action is **not working** in the admin panel.

### Preconditions

**1.** Admin should be logged in.
**2.** Multiple products should be created

### Steps to reproduce

**1.** Go to 'The Admin panel
**2.** Try to update products by mass action.
**3.** See the error

### Expected Result

The admin should be able to update multiple products at a time by mass action.

### Actual Result

The admin is not able to update multiple products at a time by mass action.

**Comment by Sanjaybhattwebkul** [comment]
@prabhatkumaroc082 
Please look into it.

**Comment by prabhatkumaroc082** [comment]
@Sanjaybhattwebkul i checked master branch, it is not faced. Kindly check once and share the test case to reproduce the issue.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul 
I am **closing** this issue because I have taken a pull from the master repository and now this is **working fine**, Please find the screenshot [Here](https://prnt.sc/cPymH6d1O3f_)
