### ISSUE TITLE
Getting exception while trying to editing the configurable product.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7198]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

If the admin is trying to remove any variant of a configurable product getting the exception.

### Preconditions

**1.** Admin should be logged in.
**2.** A configurable product should be created.

### Steps to reproduce

**1.** Go to the 'Admin panel'
**2.** Click on 'Product' inside the catalog section.
**3.** Edit any configurable product.
**4.** Remove any variant of the product
**5.** Click on save.
**6.** See error

### Expected Result

The admin should be able to edit any configurable product.

### Actual Result

Not able to edit the configurable product.

### Screenshots

![bug](https://user-images.githubusercontent.com/86394952/208372244-2468286f-a109-4fb7-948c-50d2e6035acb.png)

**Comment by suraj-webkul** [comment]
Working on it.

**Comment by Amitk-webkul** [comment]
While Deleting the variant product it is showing an unnecessary [notification.](https://tinyurl.com/2jn3ob3f)

**Comment by devansh-webkul** [comment]
Not able to reproduce this and already been fixed here,
https://github.com/bagisto/bagisto/issues/7394
