### ISSUE TITLE
Option for deliverer the order in multiple addresses in in a shipping.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7199]
### Is your feature request related to a problem? Please describe.

If the customer places 1 orders with multiple quantities of the product. then there is no option to deliver the same order to multiple shipping addresses.

### Describe the solution you'd like

If the customer places 1 orders with multiple quantities of the product. then there should be an option to deliver the same order to 
 multiple shipping addresses.

**Comment by jitendra-webkul** [comment]
Needs to done by custom module
