### ISSUE TITLE
The tax is not applied if the customer is selecting the saved address on the checkout page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7200]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The tax is not applied if the customer is selecting the saved address on the checkout page. even if the address is meeting all the conditions of the tax rate.

### Preconditions

**1.** The tax should be applied to any product.
**2.** An address should be saved which meets all conditions of the tax rate.

### Steps to reproduce

**1.** Go to 'shop'
**2.** log in as a customer.
**3.** Add the product to the for which the tax is applied.
**4.** Process for checkout.
**5.** Select the saved address which meets all conditions of tax rate.
**6.** See the error

### Expected Result

The tax should be applied if the customer is selecting the shipping address.

### Actual Result

The tax is not applied if the customer is selecting the saved address for shipping the order.

### Screenshots

![sd](https://user-images.githubusercontent.com/86394952/208637086-b7562c93-e7c5-4000-8c29-11b274e2a94b.png)

**Comment by shivamtiwariwebkul** [comment]
assign this issue to me
