### ISSUE TITLE
There should be an option for upload category banner.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7202]
### Is your feature request related to a problem? Please describe.

If the admin is uploading the category banner then it occurring a UI issue on the home page. Please find the below screenshot.

![one](https://user-images.githubusercontent.com/86394952/208882748-346ab087-2519-4b57-a2ee-d19bb8c75d1a.png)

![two](https://user-images.githubusercontent.com/86394952/208882764-f7957f5b-12a0-4063-8952-4e2addf9628b.png)

### Describe the solution you'd like

There should be an option for uploading a category banner and category image.

![three](https://user-images.githubusercontent.com/86394952/208882965-02563de5-85f5-4135-a1df-53737daf39e3.png)

**Comment by Rachana1005** [comment]
@Sanjaybhattwebkul  assign this issue to me
