### ISSUE TITLE
Getting the exception while enabling the Share in Pinterest from the backend

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7203]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

If the Share in Pinterest is enabled from the backend and the customer is trying to view any product then there is an exception.

### Preconditions

**1.** Admin should be logged in
**2.** Some products should be created.
**3.** Social Share should be enabled for products from the backend.

### Steps to reproduce

**1.** Go to the **'admin panel'**
**2.** Click **catalog** inside the **configuration** tab.
**3.**  **Enable Share in Pinterest** inside the  **Social Share** section.
**4.** Visit the **shop**.
**5.** Try to **view any product.**
**6.** See the **error**.

### Expected Result

There should not be any exception if the  **Share in Pinterest** is enabled by the admin.

### Actual Result

If the Share in Pinterest is enabled from the backend and the customer is trying to view any product then there is an exception.

### Screenshots

![issue](https://user-images.githubusercontent.com/86394952/209289598-22c2e4de-36f0-4385-8830-5abeb9273a2d.png)

**Comment by suraj-webkul** [comment]
Please assign this bug to me.

**Comment by devansh-webkul** [comment]
This needs to be fixed in the vendor package. So either reduce dependency and use inside this or make a pull request to that specific repo.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Already done and merged - https://github.com/bagistobrasil/bagisto-product-social-share/pull/2
