### ISSUE TITLE
in edit role page, if user tries to uncheck a parent permission, some children permissions don't be unchecked

### ISSUE THREAD

**Issue by Faisal-s** [bagisto/bagisto#7210]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.5

### Issue Description

in edit role page, if user tries to uncheck a parent permission, some children permissions don't be unchecked

### Preconditions

add new role

### Steps to reproduce

1. Go to Admin Panel
2. Click on Settings
3. choose Users
4. go to role tab
5. add new role
6. checked some roles and save the role
7. edit the role 
8. try to uncheck parent role -> some children uncheck after click multiple times.

### Expected Result

when user tires to uncheck a parent permission that contains children permissions, all these children permissions should be unchecked

### Actual Result

if user tries to uncheck a parent permission, some children permissions don't be unchecked

### Screenshots

https://user-images.githubusercontent.com/71641587/209671414-dac26106-be74-4cdc-be17-938c40d8293e.mp4

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
**Thanks for reproduce**, but the issue is **already** raised for the same.  https://github.com/bagisto/bagisto/issues/6709
And the pull request is also created : https://github.com/bagisto/bagisto/pull/6741#issuecomment-1283597731

**Comment by Faisal-s** [comment]
is it resolved ?

**Comment by Faisal-s** [comment]
actually this Issus is different 
this bug is after create the role when you edit the role you have created if you uncheck the the parent the child still checked

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
We will fixed this on the same, please check [here](https://github.com/bagisto/bagisto/pull/6741#issuecomment-1283597731)
