### ISSUE TITLE
The configurable product price is visible as 0 on the home page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7216]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The configurable product price is visible like "$0 as low as" as 0 on the home page.

### Preconditions

**1.** There should be multiple configuration products added by the admin. 
**2.** All the configurable products should be listed on the home page.

### Steps to reproduce

**1.** Go to the 'admin panel'
**2.** Click on 'products' inside the catalog.
**3.** Create multiple products with different-2 prices.
**4.** Visit the shop.
**5.** See an error

### Expected Result

The minimum price from all variants should be visible on the home page for configurable products.

### Actual Result

For configurable products, the price is visible like $0 as low as. on the home page

### Screenshots

![issue-critical](https://user-images.githubusercontent.com/86394952/210035560-fc3bff0c-6fd2-4d14-8541-09c0804da9aa.png)

**Comment by shivamwebkul** [comment]
working on it

**Comment by ronaldmeran** [comment]
Hi everyone, I have faced somehow the same issue regarding this, after I created a configurable product with 2 variants, the `min_price`, `regular_min_price`, `max_price`, `regular_max_price` are all zero for configurable product in the database. 

Please see below where configurable product is product_id = 94 and the product_id 96 and 97 are it's variants

<img width="1076" alt="Screenshot 2024-04-12 at 11 28 48 AM" src="https://github.com/bagisto/bagisto/assets/7944050/79ed0e73-c0e8-4772-b238-5a48c3d793e0">
