### ISSUE TITLE
issue in configurable product

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#722]
when we select the configurable product type, after filling attribute family and SKU, when we click on save product, it is showing product type "simple"
![cnfgissue1](https://user-images.githubusercontent.com/47665137/54659890-d3aaa980-4af9-11e9-9355-dae6ebd6ed7d.png)
![cnfgissue2](https://user-images.githubusercontent.com/47665137/54659891-d907f400-4af9-11e9-9d81-5333d32831c4.png)

**Comment by rahulshukla-webkul** [comment]
Hi @sanjanasingh202 thanks for raising this issue. we will fix it by today.

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Fixed
![Screenshot (1)](https://user-images.githubusercontent.com/45203177/55080077-7a2b1780-50c3-11e9-905e-fc8d3bc97f69.png)
