### ISSUE TITLE
Gift cards feature should be introduced

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7224]
### Is your feature request related to a problem? Please describe.

The gift cards feature should be introduced

### Describe the solution you'd like

A gift cards feature should be introduced

**Comment by Sanjaybhattwebkul** [comment]
Gift vouchers/cards can be individually sent to customers through their email by other customers in the store front. The customer receiving the gift certificate can use the code provided in the email at the shopping cart to deduct the gift voucher amount from the order total. To manage the Gift Vouchers of the store, go to Sales > Gift Vouchers > Gift Vouchers.

**Comment by jitendra-webkul** [comment]
Needs to done by custom module
