### ISSUE TITLE
Missing update password notification?

### ISSUE THREAD

**Issue by alexdebeer3005** [bagisto/bagisto#7227]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.3.2

### Issue Description

My bagisto is sending e-mails fine, password reset etc.

After the password is updated there is no notification e-mail? When looking in Laravel debugbar, there is no mail send;

Is there something missing? 

### Preconditions

Working application including working e-mails.

### Steps to reproduce

1. click password reset
2. click the link in the e-mail
3. update your password
4. no mail send?

### Expected Result

E-mail notification about the password change

### Actual Result

no e-mail send

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am closing this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/63eb3588aac9534fac250a87), for future reference.
