### ISSUE TITLE
Image zoom lens is not working properly. in the product's view page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7229]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

**Image zoom lens** is not working properly. in the product's view page.

### Preconditions

**1.** Products should be created by the admin.
**2.** user should be on the product's view page.

### Steps to reproduce

**1.** Go to 'shop'
**2.** Click on 'any product'
**3.** Mouse hover on the product's image.
**4.** See the error

### Expected Result

The **image zoom lens** should work properly. in the product's view page.

### Actual Result

The **image zoom lens** is not working properly. in the product's view page.

### Screenshots

![isue](https://user-images.githubusercontent.com/86394952/212032433-a6738a33-cc57-4118-bda8-3c9335085d98.png)

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
The Image zoom lens is working only for square images. it should work for all types of images.

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Not able to find the issue
