### ISSUE TITLE
sorting should be work only after clicking on the tax of table header.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7230]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

shorting should work only after clicking on the tax of the table header.

### Preconditions

**1.** Admin should be login 
**2.** Admin should be on the products page inside the catalog section
**3.** Some products should be added by the admin

### Steps to reproduce

**1.** Go to the 'admin' panel
**2.** Click on 'products' inside the catalog.
**3.** Scroll down to 'click on slightly right of the SKU' on the table header section.
**4.** See the error

### Expected Result

shorting should work only after clicking on the tax on the table header.

### Actual Result

shorting is working if the admin clicks slightly right/left of the header tax.

### Screenshots

![k](https://user-images.githubusercontent.com/86394952/212070657-b21751da-6ada-4691-831a-98fbd1ceb08f.png)

**Comment by Amitk-webkul** [comment]
now, this is working fine.
