### ISSUE TITLE
Product view page should be improved for mobile view.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7233]
### Is your feature request related to a problem? Please describe.

The product view page is not properly responsive and with good UI.properly. Please find the below screenshot.

![ISSUE](https://user-images.githubusercontent.com/86394952/212320045-b48ad226-0feb-4849-a3ed-93b411a5a3ae.png)

### Describe the solution you'd like

If the user is trying to view any product on mobile then the page is not properly responsive and with attractive UI. please take a reference from the below screenshot.

![mobile-view](https://user-images.githubusercontent.com/86394952/212320202-838907ef-ac72-4097-9ccc-0542db705030.png)

### Describe alternatives you've considered

![mobile-view](https://user-images.githubusercontent.com/86394952/212319947-0a26c348-7103-4e64-a6a9-e84865d4424b.png)

**Comment by akathuria289** [comment]
@Sanjaybhattwebkul Not able to see the issue 
![Copy-of-Grouped-Product-83c38f-](https://user-images.githubusercontent.com/107393273/215757827-1e8ac1d8-ba25-4a6a-8918-6bcdac6f6aa0.png)

**Comment by devansh-webkul** [comment]
Will implement a new theme, as currently checking on the functionality.
