### ISSUE TITLE
The design of category section in home page should be enhanced

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7236]
### Is your feature request related to a problem? Please describe.

The category images are overlapping on the home page. Please find the below screenshot.

![issue](https://user-images.githubusercontent.com/86394952/213118091-bdb93c7b-2c74-487a-b24e-13545311403f.png)

### Describe the solution you'd like

The design of the category section on the home page should be enhanced. please take a reference from the below screenshot.

![image](https://user-images.githubusercontent.com/86394952/213118651-b8e30039-d87c-42bd-ba91-ec7989b0ce90.png)

**Comment by suraj-webkul** [comment]
Please assign this to me

**Comment by jitendra-webkul** [comment]
We are implementing a new theme so not needed this now.
