### ISSUE TITLE
Error on update Category 

### ISSUE THREAD

**Issue by asif-nadeem** [bagisto/bagisto#7237]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Bagisto Version 1.3.2

### Issue Description

Hi Sir/ Madam 
I have setup a shop on Bagisto Version 1.3.2,  now after some time, I am getting below error when I update the Category. SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'urlPath' at row 1
I think it's DB Tigger issue,
Please guide me to resolve this issue.

### Preconditions

I am using PHP V 7.3

### Steps to reproduce

1. Go to 'categories'
2. Click on 'edit any categories'
3. Scroll down to 'Position, just change Position any # to any #'
4. See error (SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'urlPath' at row 1)

### Expected Result

Updated categories

### Actual Result

String data, right truncated: 1406 Data too long for column 'urlPath' at row 1)

### Screenshots

![image](https://user-images.githubusercontent.com/15938319/213149482-c0faec37-7f9d-4a27-8da7-c1608443d79a.png)

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
This issue **is fixed** is our latest version. For this, you need to check the **size** of the _**urlPath**_ column in your **database table.**

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Hope your issue will be **resolved**. and if you are still facing the same issue then **feel free** to reopen this issue.
