### ISSUE TITLE
TBT (Total blocking time) issue 

### ISSUE THREAD

**Issue by hnabeel64** [bagisto/bagisto#7239]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.1

### Issue Description

Hello،
I've a problem while optimizing my site that the TBT and performance are very low. TBT is as high as 1600ms and performance is as low as 29%.
I've checked the website backend and there seems to be issue on loading shop.js script which is taking much load. And also there are single product view page which run the queries in foreach loop so the queries are about 1200 in count. How do I optimize my site to set the performance at least 60 to 70 percent and TBT as low as 200ms.

Thank you.

### Preconditions

Development environment

### Expected Result

60 to 70 percent performance

### Actual Result

29% performance

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
We have **fixed** this issue in our **master** branch and will reflect it in the **upcoming release**. we have implemented **Elasticsearch** also.
