### ISSUE TITLE
shop.js Cannot read properties of undefined (reading 'protocol')

### ISSUE THREAD

**Issue by shaikhmoinuddin** [bagisto/bagisto#7244]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v0.1.0

### Issue Description

<img width="1629" alt="Screenshot 2023-01-26 at 10 04 33 AM" src="https://user-images.githubusercontent.com/123619508/214769496-77e4fae2-a021-41db-a91a-34ed7acc487d.png">

This issue is duplicate of issue https://github.com/bagisto/bagisto/issues/6954 which was closed without proper investigation!

The default theme itself throws this error and documentation suggests the user to work on custom theme by replicating default theme! And default theme throws this shop.js error, please resolve at earliest! 

I have purchased bagisto multi tenant and this is a show stopper for us, please provide needed support at earliest.

NOTE: CLOSURE OF THIS TICKET WITHOUT PROPER RESPONSE WILL RESULT IN SEVERE REPRECUSSIONS!

### Preconditions

No Preconditions. Just setup a tenant and use the default theme provided.

### Steps to reproduce

1. Just setup a tenant website
2. Use the theme "default"
3. Navigate to product category
4. See error in inspect console

### Expected Result

There shouldn't be js error

### Actual Result

There shouldn't be js error

### Screenshots

<img width="1629" alt="Screenshot 2023-01-26 at 10 04 33 AM" src="https://user-images.githubusercontent.com/123619508/214769921-11570192-6ca3-49d9-b7c8-1cc69d59ec0d.png">

**Comment by shaikhmoinuddin** [comment]
<img width="1629" alt="Screenshot 2023-01-26 at 11 44 20 AM" src="https://user-images.githubusercontent.com/123619508/214782572-06b3ae44-2962-49d5-b701-9905e09ee3a2.png">

1. Setup a fresh repo of bagisto on v1.4.5
2. Set the default channel theme to "default"
3. Add a product category, add a product
4. Visit the product category frontend and this error appears

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63eb2f3cbf991905516aa564), for future reference.
