### ISSUE TITLE
Last Product Missing

### ISSUE THREAD

**Issue by jawed1412** [bagisto/bagisto#7254]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.5

### Issue Description

I am facing some strange issue. in some of my category the last item is missing. if i inactive that one then the 2nd last becomes last the its not coming in API. but same product is coming in different category. also not all the category is having this problem. For solution i deleted the category and created again problem is solved but again same problem came in other category.

I don't know if i have made you understand the problem or no

### Preconditions

nothing

### Steps to reproduce

nothing

### Expected Result

item missing

### Actual Result

item should show

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Can you please share the steps to reproduce the issue?

**Comment by jawed1412** [comment]
Actual it happens on specific category and there is no proper steps to reproduce that however i am available for a zoom/meet screen sharing to show the issue.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
If possible then please share a **short video** for the same, you can use the **loom** for making the **video**.
After that we will connect in meet **if needed.**

**Comment by jawed1412** [comment]
Hello,
i tried to show you in the video but i know its bit confusing please check once else i am available always to go on a screen sharing https://watch.screencastify.com/v/QDbs8d8wC0VwhhJ3sP7q

**Comment by jawed1412** [comment]
Hello 
Did you get a chance to see the video?

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Can you please verify this issue with our [live demo](https://demo.bagisto.com/). because i am not able to reproduce the issue.
And if you will get the same issue with live demo then please let me know.

**Comment by devansh-webkul** [comment]
Please use bagisto forum as this is not an issue. If you have valid details then please share I will reopen this.
