### ISSUE TITLE
Duplicate Address Creating in checkout page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7264]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

If the customer is clicking on save this address on the checkout page then. the duplicate addresses are created.

### Preconditions

The customer should be on the checkout page.

### Steps to reproduce

**1.** Go to 'shop'
**2.** Login as a customer.
**3.** Add any product to the cart.
**4.** Process for checkout.
**5.** Add a new shipping address.
**6.** Click on save this address after filling in all required fields.
**7.** click on the back button at the top of the address section.
**8.** Click on add new address button.
**9.** Click on the save this address button after filling in all required fields.
**10.** See the error

### Expected Result

Duplicate addresses should not be created.

### Actual Result

If the customer is clicking on the save address checkbox duplicate addresses are created on the checkout page.

### Screenshots

![screenshot_1675676943659](https://user-images.githubusercontent.com/86394952/216939755-d66014fd-9f79-4389-bf4e-b8517586da3d.png)

**Comment by shivamtiwariwebkul** [comment]
Please assign this issue to me.
