### ISSUE TITLE
Layered navigation filters not working

### ISSUE THREAD

**Issue by tahiryasin** [bagisto/bagisto#7273]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

0.1.0

### Issue Description

Layered navigation filters not working.

![final-filters](https://user-images.githubusercontent.com/2690391/217267163-3c46d870-96fa-4f95-b4cb-12bfc6be708a.gif)

### Preconditions

Open any category page

### Steps to reproduce

1. Go to any category page from main menu
2. Apply any filters, like price, color or brand
3. No results will show

### Expected Result

Filtered products should show

### Actual Result

No products showing 

### Screenshots

![image](https://user-images.githubusercontent.com/2690391/217267632-0a6c6489-a70c-43bc-af3d-a86bc9924cf4.png)

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
This issue is **fixed** in our **master**.Please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63e35e1d93ea2803a94342b0)

**Comment by tahiryasin** [comment]
@Sanjaybhattwebkul Appreciate your response.
Kindly tag the affected files so that we can apply the same fix in our project too.

**Comment by tahiryasin** [comment]
@Sanjaybhattwebkul 
The issue is still present, even your official demo has this issue as of today
Kindly do not close the tickets without proper testing and resolution.

https://demo.bagisto.com/bagisto-common/men?price=0,398

**Comment by saurav-webkul** [comment]
Hi @tahiryasin 

As we told the issue has been fixed in the master branch. The demo consists of the latest stable version which is v1.4.5 so you are getting the issues. But rest assured this has been fixed and in the next release that is about to come, it will be shown as fixed. Once the release will come then we will update the demo.

**Comment by tahiryasin** [comment]
@saurav-webkul @Sanjaybhattwebkul 

Could you please share the files that are updated

I want to apply the fix to our project too, we have purchased your Multitenant SaaS module too. 

Looking forward to your support.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please take a reference from [here](https://github.com/bagisto/bagisto/pull/7082)
