### ISSUE TITLE
getDefaultChannelLocaleCode() is undefined

### ISSUE THREAD

**Issue by tahiryasin** [bagisto/bagisto#7283]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

0.1.0

### Issue Description

core()->getDefaultChannelLocaleCode() is not defined 

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Core/src/Eloquent/TranslatableModel.php#L44

### Preconditions

No precondition

### Steps to reproduce

Open 

[packages/Webkul/Core/src/Eloquent/TranslatableModel.php](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Core/src/Eloquent/TranslatableModel.php)

and go to line#[44](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Core/src/Eloquent/TranslatableModel.php#L44)

`return core()->getDefaultChannelLocaleCode();`

But, `getDefaultChannelLocaleCode` function is not defined in Core.php

### Expected Result

it should return default channel's locale code

### Actual Result

Thrown fatal error

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
