### ISSUE TITLE
Bagistor. when npm run prod to minify velocity.js error

### ISSUE THREAD

**Issue by nguyen123** [bagisto/bagisto#7290]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.3.1

### Issue Description

when edit file vue and build .
I run npm run dev then ok, but npm run prod then error in below.

I add class to vue file and run cmd npm run prod to build vuejs.
but when run project then show error in javascript: "TypeError: o is not a function
at t (velocity.js:1:395593)"
- I check when npm run prod to minify velocity.js error.
If I npm run dev and use tool to minify velocity.js then product run ok, not error.

help me resole this issue, why edit Vuejs File and build then error. thanks
[
<img width="566" alt="error_vue" src="https://user-images.githubusercontent.com/11591574/217999163-24c6e2f3-f4b9-4a95-96dd-b10433a764b8.png">
](url)

### Preconditions

error can not load page

### Steps to reproduce

1. npm run dev then ok
2. npm run prod then error in below
3. I check when npm run prod to minify velocity.js error.
If I npm run dev and use tool to minify velocity.js then product run ok, not error.

help me resole this issue, thanks

### Expected Result

error can not load page

### Actual Result

error can not load page

### Screenshots

error can not load page

### Additional context

error can not load page

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
**Thanks** for reproducing, but i need to verify this issue with our 1.3.1. i will update you as soon as possible.

**Comment by nguyen123** [comment]
> Hi there, **Thanks** for reproducing, but i need to verify this issue with our 1.3.1, I will update you as soon as possible.

yes, please check help me, thanks

**Comment by devansh-webkul** [comment]
Hi @nguyen123,

Please check with the master version. If you want support for the existing one then you can contact webkul and that will be paid.

If this issue exists in the master version then let me know.

**Comment by nguyen123** [comment]
> Hi @nguyen123,
> 
> Please check with the master version. If you want support for the existing one then you can contact webkul and that will be paid.
> 
> If this issue exists in the master version then let me know.

hi @devansh-webkul @Sanjaybhattwebkul  I download on git mater version 1.3.1 
link : https://github.com/bagisto/bagisto/tree/v1.3.1
and test in local but still error, please help me. thanks

**Comment by Sanjaybhattwebkul** [comment]
Hi @nguyen123 
Please raise a support ticket [Here](https://bagisto.uvdesk.com/en/customer/create-ticket/)

**Comment by nguyen123** [comment]
> when edit file vue and build . I run npm run dev then ok, but npm run prod then error in below.
> 
> I add class to vue file and run cmd npm run prod to build vuejs. but when run project then show error in javascript: "TypeError: o is not a function at t (velocity.js:1:395593)"
> 
> * I check when npm run prod to minify velocity.js error.
>   If I npm run dev and use tool to minify velocity.js then product run ok, not error.
> 
> help me resole this issue, why edit Vuejs File and build then error. thanks

https://bagisto.uvdesk.com/en/customer/ticket/view/2854

**Comment by devansh-webkul** [comment]
A conversation is going on on the ticket and this is not an issue. So I am closing this.
