### ISSUE TITLE
The wishlist and compare options should not be visible if they disabled by the admin 

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7332]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The wishlist and compare options should not be visible if they are disabled by the admin.

### Preconditions

The wishlist and compare options should be disabled by the admin for all locales.

### Steps to reproduce

**1.** Go to the 'admin' panel
**2.** Click on 'general/content' inside the configuration tab on the sidebar.
**3.** Disable the wishlist and compare options.
**4.** Go shop.
**5.** Try to add any product to the comparison.
**6.** See the error

### Expected Result

The wishlist and compare options should not be visible if they disabled by the admin 

### Actual Result

The wishlist and compare options are visible if they disabled by the admin

**Comment by Sanjaybhattwebkul** [comment]
@vijaysingh-webkul 
Are you working on this issue?

**Comment by vijaysingh-webkul** [comment]
@Sanjaybhattwebkul yes

**Comment by vijaysingh-webkul** [comment]
@Sanjaybhattwebkul it needs to be discussed because we haven't got the issues https://prnt.sc/D7uTPKbGz38N

**Comment by shivamtiwariwebkul** [comment]
please assign this issue to me
