### ISSUE TITLE
Hello, can you make a simplified Chinese language?

### ISSUE THREAD

**Issue by 1825921819** [bagisto/bagisto#7335]
### Is your feature request related to a problem? Please describe.

This B2B program is very good. If there is a simplified Chinese language version, it would be better.

### Describe the solution you'd like

You can freely switch the simplified Chinese language, including the front and back ends.

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Are you asking for **Chinese language support** on the front end or back end of Bagisto? We are **giving** support for the same. please **verify [here](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/lang/zh_CN/app.php)** and let **me** know if there are any **changes** needed.

**Comment by Sanjaybhattwebkul** [comment]
@1825921819 

Please verify the given locale file. and if there is any correction needed then f**eel free to reopen** this issue.
