### ISSUE TITLE
Nested categories if level more then 2

### ISSUE THREAD

**Issue by alan-by** [bagisto/bagisto#7337]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.5

### Issue Description

I installed fresh version of bagista 1.4.5
And try to create categories tree.

Create 4 nested categories child-1 > child-2 > child-3 > child-4/
In db I see correct data in url_path , but in front end links is wrong for "child-3" and "child-4"

For child-3 link is http://localhost/child-1/child-1/child-2/child-3
For child-4 link is http://localhost/child-1/child-2/child-1/child-2/child-3/child-4

And I got 404 page 

### Preconditions

Bagisto ver is 1.4.5

### Steps to reproduce

1. Go to ' http://localhost/admin/catalog/categories.'
2. Click on Add Category
3. And create 4 categories

![Screenshot at Mar 07 13-31-09](https://user-images.githubusercontent.com/4834145/223396963-11eeb342-caf4-4789-b4eb-f76a8e9ad8c5.png)

### Expected Result

expected correct path - like in db, table "category_translations" field "url_path"

### Actual Result

wrong url in frontend for child-3 and child-4

### Screenshots

![Screenshot at Mar 07 13-24-27](https://user-images.githubusercontent.com/4834145/223397197-c257bb95-2c55-465c-b976-d5a53ff419f3.png)

**Comment by alan-by** [comment]
Looks like this going on when velocity theme selected. 
If default theme is selecting menu works correctly.

**Comment by Sanjaybhattwebkul** [comment]
https://github.com/bagisto/bagisto/issues/7330
