### ISSUE TITLE
Create custom field in configuration menu

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#7338]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Using system.php file inside config  folder, we are able to create easily a configuration area.

The desider feature is: 

create custom field and us it in configuration file system,php

a standard field is
    [
                'name'          => 'my_home_slider_image_width',
                'title'         => 'Desktop Width image  ',
                'type'          => 'number',              
                'channel_based' => true,
                'default' => 1440
            ],

a custom field is:

    [
                'name'          => 'my_field_picker_image',
                'title'         => 'my_field picker image',
                'type'          => 'image_picker',              
                'channel_based' => true,
                'default' => 1440
            ],

another custom file should be one 

    [
                'name'          => 'mycolor_picker',
                'title'         => 'Mycolor picker  ',
                'type'          => color_picker',              
                'channel_based' => true,
                'default' => 1440
            ],

and so on.

### Describe alternatives you've considered

Investigate further how improve it using current field option.

**Comment by devansh-webkul** [comment]
Currently, there is no plan to change this. In the future, we will check this. Currently, we will use the existing one.
