### ISSUE TITLE
Where can I find Persian language?

### ISSUE THREAD

**Issue by LQasemzadeh** [bagisto/bagisto#7339]
### Is your feature request related to a problem? Please describe.

Where can I find Persian language?

### Describe the solution you'd like

give me address of language files,

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
You can verify [Here](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/lang/fa/app.php)

**Comment by Sanjaybhattwebkul** [comment]
@LQasemzadeh 
Please verify the given locale file. and if there is any correction needed then feel free to reopen this issue.
