### ISSUE TITLE
Update documentation?

### ISSUE THREAD

**Issue by alexdebeer3005** [bagisto/bagisto#7352]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v1.4.3

### Issue Description

When looking at my route list I see options for api/v1/admin/sales/orders? and a controller behind it responsabel for the action "Webkul\RestApi\Http\Controllers\V1\Admin\Sale\OrderController@allResources".

But when searching in my project I can't find a webkul/restapi class? 

So what is going on? where is the documentation for this? 

### Preconditions

default installation

### Steps to reproduce

install bagisto clean and dump the route list

### Expected Result

good docs

### Actual Result

bad docs

**Comment by alexdebeer3005** [comment]
.

**Comment by akathuria289** [comment]
@alexdebeer3005 
Hii, Their 
Please check out this path - vendor/bagisto/rest-api for the RestAPI package, 
This function( allResources ) exist in vendor/bagisto/rest-api/src/Http/Controllers/V1/Admin/ResourceController.php

**Comment by devansh-webkul** [comment]
We have moved all the APIs into vendor dependencies, please have a look there,
https://github.com/bagisto/rest-api
