### ISSUE TITLE
It should not took extra spacing in the homepage after enabled toggle.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7355]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Enter footer details and enable footer toggle so it is showing extra spacing in the homepage in the footer.the 

### Preconditions

enable the toggle button for the footer.

### Steps to reproduce

1. Go to 'Configuration'
2. Click on 'general'
3. Click on 'Content'
4. Enable the 'toggle' button'
5. Click on the 'Save button'
6. Go to the 'homepage'
7. Scroll Down to the 'Footer'

### Expected Result

It should not be shown with extra spacing.

### Actual Result

It is showing the extra spacing.

### Screenshots

1. https://prnt.sc/1SGbnnGpwaZE
2. https://prnt.sc/-R3kvcCMjFq3

**Comment by mayank-webkul** [comment]
please assign this issue to me
