### ISSUE TITLE
It should not hide the menu options in the admin panel.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7356]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

At the admin panel if opening the setting option it is hiding the configure options menu.

### Preconditions

maximize the admin toggle sidebar. 

### Steps to reproduce

1. Go to the 'admin panel'
2. Click on 'setting option'
3. Scroll down to 'to view configure option'
4. See the error

### Expected Result

It should not hide the sidebar menus.

### Actual Result

It is hiding the menu.

### Screenshots

![image](https://user-images.githubusercontent.com/106804569/226327121-cd54c66a-02e8-4e0f-92f5-ef00cfc79fcd.png)

**Comment by vijay-webkul** [comment]
Resolved:
please check screenshot
https://prnt.sc/9V27aubpK5sa

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/642d45c2f0168c07d9f026a1), for future reference.
