### ISSUE TITLE
Sub-menu should be handled according to screen size in the admin panel

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7357]
### Is your feature request related to a problem? Please describe.

If the screen size is large and the sidebar is collapsed in the setting option not able to operate the below options

### Describe the solution you'd like

Add a scroller to reach easily.

### Additional context

![Desktop-screenshot](https://user-images.githubusercontent.com/106804569/226334588-cb0c6d6d-3756-4471-adc1-7beb9ea630e8.png)

**Comment by Sanjaybhattwebkul** [comment]
@amitkumarqa 
We can handle the **sub-menu** according to **screen size**

**Comment by devansh-webkul** [comment]
No need now. As we are developing a new theme.
