### ISSUE TITLE
While filtering dashboard sales and The month option should be dark in the Dark theme.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7358]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While filtering the dashboard with month So The month option should be dark in the Dashboard of the admin panel in the Dark theme.

### Preconditions

enable the Dark Theme

### Steps to reproduce

1. Go to the 'admin panel'
2. Click on the 'dark mode button'
3. Click on the 'date'
4. Click on the 'month'
5. See the error

### Expected Result

It should be shown in the dark.

### Actual Result

It is showing in the light theme.

### Screenshots

![Desktop-screenshot (1)](https://user-images.githubusercontent.com/106804569/226337668-cfe8bc5d-cf96-48cd-b119-f0fe28c86455.png)

**Comment by mayank-webkul** [comment]
please assign this issue to me
