### ISSUE TITLE
In Mobile view-> on the admin panel, It is hiding the velocity Title in the velocity page.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7360]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

In the admin panel on the velocity page, in the mobile view, it is hiding the metadata tab title to the update button. 

### Preconditions

Go to the velocity page on the admin panel.

### Steps to reproduce

1. Go to the 'admin panel'
2. Click on 'setting->velocity-> metadata tab'
3. open mobile view to 'inspect'
4. See the error

### Expected Result

it should not hide the title.

### Actual Result

it is hiding the title.

### Screenshots

![title](https://user-images.githubusercontent.com/106804569/226526844-f05e8f8e-08e5-4056-a8a2-3d56dea67481.png)

**Comment by mayank-webkul** [comment]
please assign this issue to me
