### ISSUE TITLE
In the velocity metadata option the channels and language option should be in the center same as the title.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7363]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While opening the velocity page in the metadata tab the channels and language button layout is not set. it is going down

### Preconditions

go to the velocity page.

### Steps to reproduce

1. Go to the 'admin panel'
2. Click on 'setting->velocity-> metadata tab'
4. See the error

### Expected Result

the options should be shown in the center same as the title.

### Actual Result

It is not showing in the center.

### Screenshots

![channeloption](https://user-images.githubusercontent.com/106804569/226533618-907745a0-72eb-4a97-ac48-263ae430ca45.png)

**Comment by amitkumarqa** [comment]
need improvement in the mobile view.

![Screenshot from 2023-03-21 18-01-50](https://user-images.githubusercontent.com/106804569/226616800-ab8d2777-191e-4e70-977a-ef1728758594.png)

![Screenshot from 2023-03-21 18-05-56](https://user-images.githubusercontent.com/106804569/226616884-d9265851-b1c8-4a4b-a7ff-f3e015b8b2cd.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/642eab5e2a666707c41296b5), for future reference.
