### ISSUE TITLE
on the admin panel, Capitalize each words of the title in the velocity page.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7364]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

on the admin panel, on the velocity page capitalize each word of the velocity meta data title.

### Preconditions

Go to the velocity page.

### Steps to reproduce

1. Go to the 'admin panel'
2. Click on 'setting-> velocity-> meta data tab'
4. See the error

### Expected Result

The title should be capitalize each word.

### Actual Result

It does not capitalize each word.

### Screenshots

![word](https://user-images.githubusercontent.com/106804569/226535882-9ba558f5-6ff1-4bfd-b621-fd087881d9e3.png)

**Comment by amitkumarqa** [comment]
The issue has been fixed.

![Screenshot from 2023-03-22 10-12-27](https://user-images.githubusercontent.com/106804569/226804084-19d3d8ed-b5e6-419e-a071-e9c9e27310af.png)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/641d537945ed2b05b130d2a6), for future reference.
