### ISSUE TITLE
Calendar should be same for new or edit the customer from admin panel.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7370]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While creating a new customer from the admin end the calendar is different and after editing the customer it is showing a different calendar.

### Preconditions

Should be logged in to the admin panel.
Go to the customer option.

### Steps to reproduce

1. Go to the 'admin panel'
2. Click on 'customer option'
3. Click on the 'add customer button'
4. Scroll down to the 'date of birth option'
5. Click on 'calendar option'
6. See the error

### Expected Result

Here the calendar should be shown the same as the default calendar. 

Reference:

![calenderview](https://user-images.githubusercontent.com/106804569/226864287-d5a55324-7d60-4a60-a8a7-8cd8dca239de.png)

### Actual Result

It is not showing the same calendar.

Reference:

![createcustomer](https://user-images.githubusercontent.com/106804569/226863949-6f5a613a-55fb-477a-9704-56b3ac483c5b.png)

**Comment by rachana-webkul** [comment]
@Sanjaybhattwebkul  now it's working,please verify

**Comment by devansh-webkul** [comment]
@rachana-webkul,

Please link the pull request.
