### ISSUE TITLE
The edit and delete address text is overlapping, on the customer address page on the shop in the Persian language.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7374]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The edit and delete address text is overlapping, on the customer address page on the shop in the Persian language.

### Preconditions

**1.** The language should be Persian
**2.** The customer should be on the address page.

### Steps to reproduce

**1.** Go to 'shop' and log in as a customer.
**2.** Click on 'address' inside the profile section
**3.** See error

### Expected Result

There should be a proper margin between edit or delete text if the customer is trying to edit or delete the address.

### Actual Result

The edit and delete address text is overlapping, on the customer address page on the shop in the Persian language.

### Screenshots

![Screenshot(4)](https://user-images.githubusercontent.com/86394952/227130639-7c0fc74c-4069-4f18-882b-bf792119fa14.png)

**Comment by Sanjaybhattwebkul** [comment]
@akathuria289 
Please look into it.

**Comment by rachana-webkul** [comment]
@Sanjaybhattwebkul  Persian language follow RTL direction, so when creating local admin should select RTL  direction then this issue will not appear
