### ISSUE TITLE
No need to show BUY NOW button in the Booking product.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7375]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If there is any booking product here no need to show the BUY NOW button.

### Preconditions

need to enable the buy now button options.
need to add booking product

### Steps to reproduce

1. Go to 'Homepage'
2. Click on 'Booking Product'
3. See the error

### Expected Result

In the Booking Product no need for the BUY NOW button.

### Actual Result

But It is showing the buy now button.

### Screenshots

![Screenshot from 2023-03-23 13-02-09](https://user-images.githubusercontent.com/106804569/227141075-26664c80-14c1-4b92-a14d-6eec3e8c3c09.png)

**Comment by mayank-webkul** [comment]
please assign this issue to me
