### ISSUE TITLE
The products should be updated in the cart if the admin is updating the product's price.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7378]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The products should be updated in the cart if the admin is updating the product's price.

### Preconditions

**1.** The products should be added to the cart.
**2.** The price of the same product should be updated by the admin.

### Steps to reproduce

**1.** Go to 'shop'
**2.** Add any item to the cart.
**3.** Go to the admin panel
**4.** Update the price of the product which is added to the cart.
**5.** Visit the shop and view the price of the same product
**6.** See the error

### Expected Result

The products should be updated in the cart if the admin is updating the product's price.

### Actual Result

The products are not updated in the cart if the admin is updating the product's price.

### Screenshots

![screenshot_1679653201607](https://user-images.githubusercontent.com/86394952/227508088-1b510e88-e968-4402-b622-c14db62aa5e7.png)

**Comment by SanjuDeveloper** [comment]
@devansh-webkul 
Getting the same issue after applying the **customer group price** and special price.

**Comment by akathuria289** [comment]
@SanjuDeveloper as we have checked the issue the Price is updating when we checkout the cart

**Comment by akathuria289** [comment]
@SanjuDeveloper as we have checked the issue the Price is updating when we checkout the cart

**Comment by SanjuDeveloper** [comment]
@akathuria289 
Yes. But the price should be updated in **mini cart** as well

**Comment by devansh-webkul** [comment]
No need we will handle this at the individual level because in small cases changing item prices for all carts is easy but when it comes to large scale or 1 lakh users it is very costly and not recommended as well.

We are already validating the price before order placement.
