### ISSUE TITLE
Impossible create configuration child acl

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#7382]
### Terms

- [ ] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.3

### Issue Description

I need to create a custom configuration acl,  for one role.

Currently When i set Configuration in role checkbox, all the menu items will displayed.

### Preconditions

laravel 9

### Steps to reproduce

I added configuration child in my package acl file:

        [
            'key'   => 'configuration.myhome',
            'name'  => 'myhome',
            'route' => 'admin.configuration.myhome',
            'sort'  => 9,
        ]

php artisan optimize
then check myhome  checkbox in the role.

All the configuration  menu is displayed in the new role left bar.

### Expected Result

Have just one menu item "myhome" inside configuration menu.

### Actual Result

full  menu is displayed

**Comment by devansh-webkul** [comment]
Looks like configuration not done properly, please check the docs.
