### ISSUE TITLE
In the Bundle product it is accepting bundle product and grouped product.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7383]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While creating Bundle products and adding products here it is accepting bundle products and grouped products and also configurated the main product.

### Preconditions

admin needs to log in.
need to create a new bundle product.

### Steps to reproduce

1. Go to the 'admin panel'
2. Click on 'catalog => product => add product'
4. Create a 'Bundle product'
5. search 'Bundle product'
6. Click on save Button
7. Go to 'Homepage'
8. Open that 'product'
9. See the error

### Expected Result

It should accept only simple products.

### Actual Result

It is accepting grouped, configured, and bundled products.

### Screenshots

![Screenshot from 2023-03-24 19-46-38](https://user-images.githubusercontent.com/106804569/227548046-bebf832c-e38b-4e93-8382-f3a000f82096.png)

**Comment by mayank-webkul** [comment]
please assign this issue to me

**Comment by Sanjaybhattwebkul** [comment]
@mayank-webkul 
Getting the issue only if the search mode is **elastic search.**

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
