### ISSUE TITLE
Undefined variable $__env error in fresh install

### ISSUE THREAD

**Issue by kartiksprajapati** [bagisto/bagisto#7384]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.5

### Issue Description

As I have first time installed the Bagisto and I'm getting error that there is variable named $__env on fresh install while accessing homepage.

Here is an error link https://flareapp.io/share/17xR3A1m

### Preconditions

Install the fresh Bagisto and fire the server.

### Steps to reproduce

Download and install Bagisto from composer and spun the server up and access the homepage

### Expected Result

Homepage should be visible without any error 

### Actual Result

Undefined variable $__env exception

Here is an error link : https://flareapp.io/share/17xR3A1m

### Screenshots

![image](https://user-images.githubusercontent.com/17043724/227800851-ee9cffba-d020-4a31-9e3f-995ac1ecb394.png)

**Comment by Sanjaybhattwebkul** [comment]
@kartiksprajapati 
I am **not able to reproduce** this issue.
Is it possible to share the sort video for the same. this will help me to reproduce the actual issue.

**Comment by Sanjaybhattwebkul** [comment]
Hi there, 

Please **follow** the below **commands** for installing the Bagisto. and if still you are getting the same issue then please **let me know.**


**1.** _git clone -b v1.4.5 https://github.com/bagisto/bagisto.git_
**2.** _cd bagisto_
**3.** _composer create_
**4.** _edit the .env file [ configure the app_url, email and database credentials]_
**5.** _php artisan bagisto:install_

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
I guess you run the **composer update** command? do not run the composer update command.
And follow the **above-given commands only**, with **php v8.1** and **composer 2.4** version. the bagisto will install successfully.
