### ISSUE TITLE
on the coupon page, what's meant by "parent only" and "children only" when adding a condition or how it works

### ISSUE THREAD

**Issue by o414** [bagisto/bagisto#7389]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

on the coupon page, what's meant by "parent only" and "children only" when adding a condition or how it works

### Preconditions

open add coupon page

### Steps to reproduce

1. go to add coupon page
2. click on add condition
3. check "parent only" and "children only" attributes

### Expected Result

it should be more clear

### Actual Result

what's meant by "parent only" and "children only" when adding a condition or how it works

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please take a reference from [Here](https://webkul.chatwhizz.com/share/screenshot/6422bd4bf0168c07d9d8cc1b).
 **"parent only"** and **"children only"** are specially used for **configurable**, **bundle**, and **grouped** products.

**Comment by o414** [comment]
@Sanjaybhattwebkul 
Hi, I appreciate your help 
OK, this is for categories but if I choose another condition like (price (children only)) for example, what does that mean?  
thanks

**Comment by Sanjaybhattwebkul** [comment]
Hi there,
Please take a **reference** from [Here](https://webkul.chatwhizz.com/share/screenshot/6422d95bf0168c07d9d93383).
And if you have any other queries then f**eel free to reopen this issue.**

**Comment by o414** [comment]
@Sanjaybhattwebkul 
thank you very much. appreciate your help
