### ISSUE TITLE
Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /home/mateo/Documents/bagisto/bootstrap/app.php:14

### ISSUE THREAD

**Issue by mateo2181** [bagisto/bagisto#739]
I have installed the project using "composer create-project bagisto/bagisto".
When I run php artisan serve I got this error:
Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /home/mateo/Documents/bagisto/bootstrap/app.php:14
But the class exists and composer install works fine.

**Comment by prashant-webkul** [comment]
@mateo2181 Please run command '**composer dump-autoload**' and if the issue still persists then try to reinstall **Bagisto**.

**Comment by mateo2181** [comment]
I have tried both things but not works.
![Screenshot (3)](https://user-images.githubusercontent.com/12451246/54918783-eba97100-4edd-11e9-81fd-5b7e5e5d60b4.png)

I am working with docker, mysql 5.7.23 and php 7.2.
Migration tables and seed work fine.

**Comment by prashant-webkul** [comment]
Please use this docker config, its tried and tested -> https://github.com/prashant-webkul/bagisto-docker

**Comment by mateo2181** [comment]
Ok, I am trying with that docker-compose.yml. But I think I should be able to clone the project out docker and use it in a service, I mean, I would like to use:
volumes:
      - ./:/var/www/html
instead
      image: webkul/apache-php:7.2

**Comment by louiesalvador** [comment]
The issue still exists until now
