### ISSUE TITLE
Getting  exception while trying to create configurable product.

### ISSUE THREAD

**Issue by kartikwebkul** [bagisto/bagisto#7394]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The product is not  updated when the admin updates the variant of the configurable product

### Preconditions

1. The user should be Login
2. Configurable product should be created

### Steps to reproduce

**1.** Login as an 'Admin'
**2.** Click on 'product' inside the 'catalog' tab.
**3.** Create a configurable product.
**4.** Delete some variants of products on the edit page.
**5.** Add only two  variants
**6.** Click on the save as product button
**7.** See the error

### Expected Result

product  detail should be updated

### Actual Result

product detail not updating

### Screenshots

Please find the screenshot [Here](https://prnt.sc/kG2uGEhDyNio)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/642d41142a666707c40f4500), for future reference.
