### ISSUE TITLE
The filter options are not in proper alignment in the mobile view. if the user is trying to filter products on the products listing page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7397]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The filter options are not in proper alignment in the mobile view. if the user is trying to filter products on the products listing page.

### Preconditions

1. Some categories should be added.
2. Some products should be added to the created category.
3. The user should be on the listing page of velocity in the mobile view

### Steps to reproduce

**1.** Go to 'shop' in mobile view.
**2.** Click on 'any category' in the shop by category section.
**3.** Try to filter the products.
**4.** See  the error

### Expected Result

The filter options should be in proper alignment with the mobile view. if the user is trying to filter products on the products listing page.

### Actual Result

The filter options are not in proper alignment in the mobile view. if the user is trying to filter products on the products listing page.

### Screenshots

![screenshot_1680065342787](https://user-images.githubusercontent.com/86394952/228431250-cbf90e8e-2a9d-42c6-9790-0ff45b1f0600.png)

**Comment by peeyush-webkul** [comment]
this task assigned to me
