### ISSUE TITLE
Multiple Photos are Added on the Velocity page

### ISSUE THREAD

**Issue by kartikwebkul** [bagisto/bagisto#7402]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master v1.4.5

### Issue Description

Photos are not shown on the home page who successfully added by admin on the Velocity page

### Preconditions

1. Admin Should be Login

### Steps to reproduce

1. Admin Panel=> Click on Setting=> Go to Velocity
2. Go to the Images section
3. Add Multiple images
4. See the Error on the  Website Home page

### Expected Result

Multiples images should not be added

### Actual Result

Multiples images added successfully

### Screenshots

https://prnt.sc/ypuHtFV2_1J_

**Comment by mayank-webkul** [comment]
assign this issue to me
