### ISSUE TITLE
In the admin panel while uploading image with max size and. It is showing 404 error.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7403]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While uploading an image with the maximum size and trying to save it shows a 404 error. same with uploading multiple images at the same time.

### Preconditions

admin needs to log in.
needs to upload image upto 6 MB

### Steps to reproduce

1. Log in as 'Admin'
2. Click on 'Product edit/create' inside Catalog
3. Scroll down to the 'image tab'
4. Upload an 'image upto 6 MB'
5. See the error

### Expected Result

It should not be shown a 404 error.

### Actual Result

It is showing an error.

**Comment by vijay-webkul** [comment]
@Amitk-webkul,
As per your concern, it's not an issue please **check the video**.

https://user-images.githubusercontent.com/123063852/228758584-8083483d-eb64-4559-b4b7-c68e7daafe06.mp4
