### ISSUE TITLE
Getting 404 [Page not found] issue after clicking on the advertisement image on home page.

### ISSUE THREAD

**Issue by kartikwebkul** [bagisto/bagisto#7406]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master v1.4.5

### Issue Description

Wrong URL display when mouse cursor goes upon the images

### Preconditions

The User should be Login

### Steps to reproduce

1. Go to 'Website'
2. Click on the advertisement image.
3. See the error

### Expected Result

The page should be redirected to the valid URL.

### Actual Result

Getting 404 [Page not found] issue after clicking on the advertisement image.

### Screenshots

https://prnt.sc/eDk7TF0ya-u4

**Comment by vijay-webkul** [comment]
@kartikwebkul ,
->It's not an issue, please go to **setting->velocity** page and change the URL: 
->Please check it screenshot below.
https://prnt.sc/ApknuDckbej8

**Comment by vijay-webkul** [comment]
After discussing with @Sanjaybhattwebkul working on this issue

**Comment by vijay-webkul** [comment]
@kartikwebkul,
It is working fine, localhost not supported, please check on the live site only
