### ISSUE TITLE
In the admin panel, review saved notification is not showing proper.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7407]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While editing the review and clicking on the save button here it is not showing the proper notification.

### Preconditions

need to give a review.
edit the review and save.

### Steps to reproduce

1. Log in to 'Admin'
2. Click on 'Customer => Review'
3. Edit to 'review'
4. Click on the 'save button'
6. See the error

### Expected Result

It should be shown the proper message

### Actual Result

It is not showing the proper message.[Here](https://tinyurl.com/2ncf5ynj)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/642d30fe83d74a61f2356e0f), for future reference.
