### ISSUE TITLE
I am adding more than 4 products in the related and cross-sell bar in the product and on the homepage in the product page it is showing only 4 products.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7410]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the admin panel, I am adding more than 4 products in the related and cross-sell bar, and on the homepage, on the product page, it is showing only 4 products.

### Preconditions

products should be added in the product related and cross-sell bar.

### Steps to reproduce

1. Log in as 'Admin'
2. Click on 'catalog-> product'
3. Edit the product and add multiple products more than 4 in the related and cross-sell bar.
4. Click on the 'save button'
5. See the error

### Expected Result

It should be shown all the added products.[Here](https://tinyurl.com/2lw23p96)

### Actual Result

It is showing only four products.[Here](https://tinyurl.com/2ja9oc2m)

**Comment by vijay-webkul** [comment]
Check screenshot
![image](https://user-images.githubusercontent.com/123063852/229532845-0b38935f-417b-49bf-a807-0d0d8b1d159f.png)
