### ISSUE TITLE
Catalog rule is not working according to User Groups.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7413]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If a user is a Wholesale user group and the catalog is applicable only for the general still wholesale user is able to purchase on the catalog rule.

### Preconditions

Needs to log in Admin.
should create a catalog rule with the wholesale user groups.
Give wholesale user group permission to a registered user.

### Steps to reproduce

1. Log in as 'Admin'
2. Click on 'catalog rule-> create rule'
3. Select the user group 'general' and save
4. Go to customer 'edit customer'
5. select the user group 'general to wholesale' and save
6. Go to the homepage
7. open the 'product page'
9. See the error

### Expected Result

Here it should be shown the product's [actual price.](https://tinyurl.com/2zu65lms)

### Actual Result

But It is showing catalog rule price.[Here](https://tinyurl.com/2k644q5y)

**Comment by mayank-webkul** [comment]
assign this issue to me

**Comment by akathuria289** [comment]
@shivamtiwariwebkul

**Comment by mayank-webkul** [comment]
## Issue Reference
> I checked all the terms and found that you need to update the product to reflect the new cart rule.

**Comment by devansh-webkul** [comment]
I think just need to do reindexing. Will check the flow first.

@jitendra-webkul please check.
