### ISSUE TITLE
The inactive products should not be visible on the product view page.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7417]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The user is able to access the inactive product. by the product's URL.

### Preconditions

The product that the user trying to access by URL. should be inactive from the admin panel.

### Steps to reproduce

**1.** Go to the 'admin panel'
**2.** Inactive any product from catalog/products 'Section'.
**3.** Visit the shop.
**4.** Try to access the inactive product by URL
**5.** See an error

### Expected Result

The user should not be able to access the inactive product. by URL

### Actual Result

The user is able to access the inactive product. by the product's URL.

**Comment by mayank-webkul** [comment]
assign this issue to me
