### ISSUE TITLE
Back icon is not working after clicking on add campaign button

### ISSUE THREAD

**Issue by gitesh-webkul** [bagisto/bagisto#7420]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Back button is not working after clicking on add campaign button

### Preconditions

1. The admin should be Login.
2. Campaigns should be created.

### Steps to reproduce

1. Login as an 'Admin'
2. Click on 'Email Marketing' inside the ''Marketing' tab.
3. Click on 'Campaigns' section.
4. Click on 'Add Campaign' button.
5. Click on back icon.
7. See the error.

### Expected Result

It should be redirected to campaign section.

### Actual Result

It is redirecting to review page.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
