### ISSUE TITLE
We can use (-) icon in Coupon Code Column 

### ISSUE THREAD

**Issue by kartikwebkul** [bagisto/bagisto#7426]
### Is your feature request related to a problem? Please describe.

In the Coupon code Column where Empty space is available there, we will use the (-) icon.

### Describe the solution you'd like

We can use the (-) icon 

scrshot:- ![Screenshot (5)](https://user-images.githubusercontent.com/128571666/228836085-420411b5-ba34-4028-a124-75b41e958c4e.png)

**Comment by shivamtiwariwebkul** [comment]
please assign this issue to me
