### ISSUE TITLE
No need to 'Update Rates' Button if data is not present for the Update

### ISSUE THREAD

**Issue by kartikwebkul** [bagisto/bagisto#7431]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master v1.4.5

### Issue Description

Nothing Data exists for the update but the **Update Rates** button is also present on Exchange Rates Page

### Preconditions

Admin should be Login.

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on 'Setting'
3. Go to the 'Exchange Rates'
4. See the error

### Expected Result

**Updates Rates** button should not be present  

### Actual Result

**Update Rates** button present

### Screenshots

![Update button](https://user-images.githubusercontent.com/128571666/229039124-b21d259f-b56b-4b30-bbf2-eb2fea9cc762.png)

**Comment by vijay-webkul** [comment]
assign to me this task

**Comment by devansh-webkul** [comment]
No need. Will check in the new theme.
