### ISSUE TITLE
The write-review option should not be visible on product card if Allow Guest Review is disabled.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#7432]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

The write-review option should not be visible on the product card if Allow Guest Review is disabled.

### Preconditions

**1.** The **Allow Guest Review** option should be disabled from admin **configurations**.
**2.** The customer should not be logged in.

### Steps to reproduce

**1.** log in as  'admin'
**2.** Click on 'products' inside the configuration/catalog
**3.** Disable **Allow Guest Review** in the review section.
**4.** See the error

### Expected Result

The write-review option should not be visible on the product card if Allow Guest Review is disabled.

### Actual Result

Getting 404 [Page not found] if the guest user trying to write a review of a product.

**Comment by shivamtiwariwebkul** [comment]
assign this issue to me
