### ISSUE TITLE
There should be a warning message if the admin is adding invalid date range for catalog rule

### ISSUE THREAD

**Issue by kartikwebkul** [bagisto/bagisto#7442]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master v1.4.5

### Issue Description

After filling Next month's date in the 'To Date' text box and the Past Month's date in the 'Form Date' Text box and then clicking on the 'Save Catalog Rule' Button, then I do not  give any warning or  pop-up notification like what I am doing wrong

### Preconditions

1. Admin should be **Login**

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on **Marketing => Promotion =>Catalog Rule**
3. Go to '**Add Catalog Rule**'
4. Fill Require Details
5. Fill  Form date =2023-03-31
6. Fill To date= 2023-05-01
7. Click on the '**Save Catalog Rule**' Button
8. See the error

### Expected Result

Should be given some Error / notification / pop-up message like:- "This date is not accepted"Error/notificationError/notificationError/notification

### Actual Result

Don't show any type of  Error / notification / pop-up messager Error/notification Error/notification

### Screenshots

![wrong date](https://user-images.githubusercontent.com/128571666/229129355-bac5f502-fb22-43a3-a207-107fd734cbc1.png)

**Comment by mayank-webkul** [comment]
please assign this issue to me

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/642d2ff2f0168c07d9efe48e), for future reference.
