### ISSUE TITLE
By default, the placeholder value should be selected for the filter dropdown.

### ISSUE THREAD

**Issue by kartikwebkul** [bagisto/bagisto#7449]
### Is your feature request related to a problem? Please describe.

![Screenshot (6)](https://user-images.githubusercontent.com/128571666/229430062-26a81ed4-c50c-4788-861d-aafa2d0143fe.png)

### Describe the solution you'd like

When we show "**Selected Column**" In the Filter  Search Box

**Comment by shivamtiwariwebkul** [comment]
please assign this issue to me
