### ISSUE TITLE
getting issue while installation

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#745]
![Screenshot from 2019-03-27 10-48-52](https://user-images.githubusercontent.com/47665137/55052438-f2bbb500-507e-11e9-88d0-792a164323fe.png)

**Comment by prashant-webkul** [comment]
One solution for this kind of issue is to turn off your php error notices.
This setting can be found in file **'php_ini'** file inside it there is a setting
**'error_reporting'**.
Under it there is a key called '**default**' against there will be a value **E~Notice**,
remove it, restart your server.

**Comment by rahulshukla-webkul** [comment]
Hi @sanjanasingh202 ,

We have fixed the issue mentioned by you, but it will take some time for the new release, so you can download the lasted bagisto from the master branch.

Here is a link - https://github.com/bagisto/bagisto

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Fixed
