### ISSUE TITLE
Search By Category Option is not visible On Mobile

### ISSUE THREAD

**Issue by kartikwebkul** [bagisto/bagisto#7450]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master v1.4.5

### Issue Description

On the Mobile App, Search by **Category** option is not present. You can take Reference from the Web:-

![Screenshot (7)](https://user-images.githubusercontent.com/128571666/229447501-ee7c055e-d882-4e7c-8ef1-c2141ce74d4f.png))

### Preconditions

The user should be Login

### Steps to reproduce

1. Go to '**App**'
2. Click on '**Search Bar**'
3. See the **Error**

### Expected Result

The search by Category option should be present on Mobile App

### Actual Result

Search by Category option is not present 

### Screenshots

![screenshot7](https://user-images.githubusercontent.com/128571666/229446071-27e67c40-d900-4210-a85a-f02ef859b246.png)

**Comment by peeyush-webkul** [comment]
Please assign this issue to me
