### ISSUE TITLE
The customer ->order history, here order ID sorting is not working properly.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7455]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While customers go to order history and try to sort order history. it is not showing properly.

### Preconditions

customer needs to log in.
In the order history should have a few orders. 

### Steps to reproduce

1. Log in as the 'Customer' 
3. Go to the 'Order History page'
4. Click on order ID for 'Sorting'
5. See the error

### Expected Result

It should be shown in ascending and descending order.

### Actual Result

But it is not showing in ascending/descending order. [Here](https://webkul.chatwhizz.com/share/screenshot/642abe2783d74a61f22fb325)

**Comment by shivendra-webkul** [comment]
It is working fine not an issue.
please check here

https://user-images.githubusercontent.com/121868701/229693029-91eea4c3-0e7b-4ccf-8ba9-abf11f76c46a.mp4
