### ISSUE TITLE
No Limit set for Contact Mobile Number text Box.

### ISSUE THREAD

**Issue by kartikwebkul** [bagisto/bagisto#7457]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master v1.4.5

### Issue Description

During adding an Inventory, when we enter Numeric data into the Contact Mobile number text box so there is no minimum or maximum limit set for the Contact Mobile number text box.

### Preconditions

Admin should be **Login**.

### Steps to reproduce

1. Go to '**Admin Panel**'.
2. Click on '**Setting**'.
3. Go to '**Inventory Source**'.
4. Click on  '**Add**' Button.
5. Fill required detail.
6. Enter mobile number in the **Contact Number** Text box . 
7. See the **Error**.

### Expected Result

There should set some minimum or maximum length.

### Actual Result

There is no limit set for the **Contact Mobile** text box.

### Screenshots

![Screenshot (8)](https://user-images.githubusercontent.com/128571666/229523469-fcdb6054-b027-4f58-a115-547534d206e7.png)

**Comment by Sanjaybhattwebkul** [comment]
Duplicate issue: https://github.com/bagisto/bagisto/issues/7400
