### ISSUE TITLE
Variants quantity field is not in dark mode.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7459]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While creating/editing the configurable product. so the quantity field is not in the dark mode.

### Preconditions

admin needs to create a configurable product.
admin needs to enable the dark theme.

### Steps to reproduce

1. Log in as 'Admin'
2. Click on 'enable dark theme'
3. Go to 'Product page' inside 'Catalog'
4. Create a 'configurable product'
5. Scroll down to 'variants'
6. See the error

### Expected Result

Here It should be shown quantity field in the dark mode.

### Actual Result

But it is not showing. [Here](https://webkul.chatwhizz.com/share/screenshot/642bb989f0168c07d9ec2ef4)

**Comment by kartikwebkul** [comment]
@shivendra-webkul 
This is **working fine**, please find the **Screenshot**:-[Here](https://prnt.sc/_acTf9DEcbyp)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/642d31a22a666707c40f1b37), for future reference.
