### ISSUE TITLE
On the homepage -> in the header option, currency sign is missing in the mobile view.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7466]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the homepage, while opening the header option It is not showing the Currency sign. 

### Preconditions

need to go on the homepage.
open mobile view.

### Steps to reproduce

1. Go to the 'Homepage'
2. Click on 'mobile view'
3. Click on the 'Header menu option'
4. Scroll down to 'currency'
5. See the error

### Expected Result

Here should be shown current currency sign.

### Actual Result

But it is not showing. [Here](https://prnt.sc/6NcIQI-ERcfw)

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue is **fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/642e79d183d74a61f238199d), for future reference.
