### ISSUE TITLE
The count of cart items should not be visible in mobile view if the cart is empty.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7467]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If the cart is empty so no need to show zero for an empty cart in mobile view.

### Preconditions

the cart should be empty.
open mobile view.

### Steps to reproduce

1. Go to the 'Homepage'
2. Open the 'Mobile view'
3. See the error

### Expected Result

Here It should not be shown count for an empty cart.

### Actual Result

But it is showing. [Here](https://prnt.sc/hSRcpPoo_6FP)

**Comment by shivamtiwariwebkul** [comment]
assign this issue to me
