### ISSUE TITLE
on coupon page, actions drop down menu, how can a "buy 1 get 1" action be applied or how it works 

### ISSUE THREAD

**Issue by o414** [bagisto/bagisto#7473]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

on coupon page, actions drop down menu, how can a "buy 1 get 1" action be applied or how it works 

### Preconditions

you are on add coupon page opening actions drop down menu

### Steps to reproduce

1. go to promotions > coupons
2. click add coupon
3. open actions drop down menu

### Expected Result

on coupon page, actions drop down menu, how can a "buy 1 get 1" action be applied or how it works 

### Actual Result

can't understand how it can be applied

**Comment by Sanjaybhattwebkul** [comment]
Hi there.
Please take a **reference** from [Here](https://bagisto.com/en/how-to-setup-promotions/)

**Comment by o414** [comment]
@Sanjaybhattwebkul 
hi there, appreciate your help, but it is still ambiguous for me, it needs to be more understandable. would you please show me an example of how we can set it and how it is applied in the front store?

**Comment by devansh-webkul** [comment]
Hi @o414,

@Sanjaybhattwebkul already shared you the docs. If you set `buy x get y`, in this case, the discount amount is the `y` quantity.

**Comment by devansh-webkul** [comment]
I am closing this, please use the Bagisto forum channel for discussion,
https://forums.bagisto.com/

As this channel is for reporting bugs.
