### ISSUE TITLE
While creating an attribute group in attribute family in the admin. It is adding the group but the container not removing.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#7475]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While I m creating a new attribute group in the attribute family it is creating the group but it is not removing the container. 

### Preconditions

needs to log in as Admin.
needs to create an attribute group.

### Steps to reproduce

1. Log in as 'Admin'
2. Click on 'attribute family' inside the catalog
3. Click on the add/edit **family**
4. Click on the **add group button** inside 'family'
5. See the error

### Expected Result

Here container should be removed after creating a group.

### Actual Result

but the container is not removed. [Here](https://webkul.chatwhizz.com/share/screenshot/642d65402a666707c40fb1af)

**Comment by akathuria289** [comment]
@atul-webkul
