### ISSUE TITLE
It is showing fatal error while creating configured products with 5 attributes and more than 10 attributes in 1 attribute options

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#7489]
### Terms

- [X] Before you open this issue, I have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While creating a configured product with multiple attributes and attribute options it is showing a fatal error.

### Preconditions

**1.** Admin  should be logged in
**2.** Admin needs to create 5 attributes.
**3.** Each attribute should have 10 attribute options. [Reference](https://prnt.sc/OLPna9YOZVDo)

### Steps to reproduce

**1.** Log in as 'Admin'
**2.** Click on the add product inside the Catalog/Products
**3.** Select configuration type
**4.** Click on **save button**
**5.** See the error
 
### Expected Result

Here It should not be shown fatal error.

### Actual Result

It is showing a fatal error. [Here](https://tinyurl.com/2at3lldh)

**Comment by devansh-webkul** [comment]
@mayank-webkul,

Please proceed on this.

**Comment by mayank-webkul** [comment]
please assign this issue to me

**Comment by devansh-webkul** [comment]
This is not an issue. The developer can increase the memory size.
