### ISSUE TITLE
Missing Password validation

### ISSUE THREAD

**Issue by ades4827** [bagisto/bagisto#7513]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.5

### Issue Description

In the Laravel error log it shows many times the error: Undefined index: password

### Preconditions

on every environment

### Steps to reproduce

1. Make post call to /customer/checkout/login with email without password
2. See error in /storage/logs/laravel.log

### Expected Result

validating the password field should prevent the submit by displaying a missing password notification

### Actual Result

the log file reports an error that can be avoided by inserting an additional validation in the controller.

### Additional context

in /packages/Webkul/Shop/src/Http/Controllers/OnepageController.php loginForCheckout() can we insert this validation? 'password' => 'required',

**Comment by Amitk-webkul** [comment]
The issue is not reproducing.
