### ISSUE TITLE
Javascript Error in demo using default theme

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#7515]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.5

### Issue Description

![image](https://user-images.githubusercontent.com/548424/232810865-bb1920c4-b839-4c36-a086-8321392e573a.png)

not display cart options
not allowed to add to cart

### Preconditions

demo version

### Steps to reproduce

https://demo.bagisto.com/bagisto-common/nike-air-retro-sneakers-for-men

### Expected Result

no javascript error detected

### Actual Result

not display cart options
not allowed to add to cart

**Comment by Amitk-webkul** [comment]
@ghena 
It is working fine. [Screenshot](https://tinyurl.com/264vvbal)

**Comment by devansh-webkul** [comment]
We are not supporting the default theme anymore. Default theme will get removed in future versions.

**Comment by ghena** [comment]
> We are not supporting the default theme anymore. Default theme will get removed in future versions.

Velocity is not a simple theme, seems very customized.

There will be a basic new theme in the future ?
Regards.
g.

**Comment by devansh-webkul** [comment]
Yes, we are making a new theme in Tailwind CSS and making it simple for our users. So that they can easily customize the stuffs.
