### ISSUE TITLE
Cannot use object of type Symfony\Component\HttpFoundation\FileBag as array

### ISSUE THREAD

**Issue by bluedawe** [bagisto/bagisto#7516]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.5

### Issue Description

Cannot use object of type Symfony\Component\HttpFoundation\FileBag as array

Webkul\Product \ Http \ Requests \ ProductForm: 71 rules

### Preconditions

Uploading product page with default theme (not Velocity)

### Steps to reproduce

1. Edit product
2. Add picture
3. Click save

### Expected Result

Saved picture

### Actual Result

Error message Cannot use object of type Symfony\Component\HttpFoundation\FileBag as array

Webkul\Product \ Http \ Requests \ ProductForm: 71 rules

**Comment by Amitk-webkul** [comment]
@bluedawe 
Please attach a **screenshot** or **short video** of the error.

**Comment by bluedawe** [comment]
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/15190343/232988022-05a36141-1cfe-4dd7-97b9-6c7d24452db2.png">

**Comment by devansh-webkul** [comment]
@Amitk-webkul,

Please verify.

**Comment by Amitk-webkul** [comment]
@bluedawe 
It is working fine. [Screenshot](https://tinyurl.com/2ygo9v2v)

**Comment by bluedawe** [comment]
Hello. I created brand new installation.
The problem appears after installing Multivendor Plugin when editing product as seller
