### ISSUE TITLE
It is not showing slider arrows in the carousel slider

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#7519]
### Terms

- [X] Before you open this issue, I have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the homepage, it is not showing slider arrows on the featured product carousels.

### Preconditions

**1.** Admin  should be logged in

### Steps to reproduce

**1.** Go to the 'Shop'
**2.** Scroll to the Carousels **Features** and **New products**
 
### Expected Result

Here It should show the arrows for the featured product.[Here](https://prnt.sc/tmSiaatquiw9)

### Actual Result

but It is not showing slider arrows.

**Comment by shivendra-webkul** [comment]
@devansh-webkul Found invalid issue

**Comment by shivendra-webkul** [comment]
@devansh-webkul Found this issue invalid
![invalid](https://user-images.githubusercontent.com/121868701/233551338-25a628a8-34f5-445b-bce7-62f3ddd6aa26.png)
