### ISSUE TITLE
On creating custom theme for shop it was also affecting admin panel's frontend

### ISSUE THREAD

**Issue by naresh-webkul** [bagisto/bagisto#752]
I was creating custom theme by the reference of this article [Bagisto Create Custom theme](https://bagisto.com/en/create-custom-theme-in-bagisto/)

after that i found that it also effecting the default theam 
![custom theme bug](https://user-images.githubusercontent.com/48952272/55158790-bb83fb80-5185-11e9-96a1-6bb1f51ea57c.png)

**Comment by yaser-alazem** [comment]
Have you resolved this issue yet ? any suggestions on how to create a custom theme for the dashboard and the front end ?
