### ISSUE TITLE
D.O.B box  Accepting multiple values .

### ISSUE THREAD

**Issue by kartikwebkul** [bagisto/bagisto#7536]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

During the editing of the User Profile, when the user fills in the date in the D.O.B box then it accepts multiple types of values.

### Preconditions

1. User should be **Login**.

### Steps to reproduce

1. Go to **Website**'>> **Profile**
2. Enter the Date of Birth in the **Date of Birth Box.**
3. See an **Error**.

### Expected Result

It should accept Numerical values only in the D.O.B Box and also should not accept multiples values.

### Actual Result

Accepting multiple types of values.

### Screenshots

![Screenshot (69)](https://user-images.githubusercontent.com/128571666/233987762-c2a13827-891c-417f-aa9a-92aa4593248c.png)

**Comment by devansh-webkul** [comment]
No need this is working fine, for further refinement we already changing the full theme in the new major version.
