### ISSUE TITLE
demo version Connection timed out

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#7554]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

demove version 

### Issue Description

https://demo.bagisto.com/ not load 

### Preconditions

previously it works

### Steps to reproduce

go to https://demo.bagisto.com/

![image](https://user-images.githubusercontent.com/548424/236810492-d9679a61-a6d8-4864-9ada-6bcbc06ce3a0.png)

### Expected Result

see the demo version portal

### Actual Result

![image](https://user-images.githubusercontent.com/548424/236810523-ffb3bf16-d7f8-486b-accb-8ac59280604d.png)

**Comment by Amitk-webkul** [comment]
@ghena 
**Thank you** for the **information**. we are **working** on it.

**Comment by Amitk-webkul** [comment]
The Demo is working.
