### ISSUE TITLE
Create a new checkout logic- onepage to onestep

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#7556]
### Is your feature request related to a problem? Please describe.

We are using bagisto 1.4.3, and seems that for the checkout process is available only onepage checkout process.
We suggest to implement possibility to switch to one step checkout process.

So each  checkout's step, define an action 

### Describe the solution you'd like

So each  checkout's step, define a aspecifi action / route

1) define billing address route
2) define shipping method route
3) define payment route
and so on...

**Comment by SanjuDeveloper** [comment]
And please let me know if any changes are required over the checkout flow of our Default theme

**Comment by ghena** [comment]
It works.
But I know that default theme will be dimmissed.
Please could you confirm ?

regards.

**Comment by SanjuDeveloper** [comment]
Hi @jitendra-webkul 
Can you please confirm for the same?

**Comment by jitendra-webkul** [comment]
> It works. But I know that default theme will be dismissed. Please could you confirm ?
> 
> regards.

@ghena , 

We have no plans to dismiss the default theme. Instead, we will be releasing it as a separate open-source module before completely removing it from the Bagisto core.

By the way, we are actively developing the entire frontend using Tailwind CSS, which will include the Onepage checkout flow. However, you will have the flexibility to easily customize the checkout flow to a one-step process.
