### ISSUE TITLE
Google Recaptcha not working  : Uncaught (in promise) Timeout

### ISSUE THREAD

**Issue by akies1** [bagisto/bagisto#7557]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v1.4.5

### Issue Description

 after clearing the cache it works fine but on the next refresh, it shows an error in the console and loads in the loop. anchor:1 Uncaught (in promise) Timeout (f)

### Preconditions

I am using Google reCaptcha v2 provided by Bagisto,I have created the site key and secret key.

### Steps to reproduce
0.you can enable the reCaptcha v2 from admin panel > configuration > customer >Captcha > add site key and secrete key >status enable and save 
1. Go to the 'login page'
2. Check on 'I am not a robot
3. the first time it will work fine, try 2-3 times
4. See the error in the console

### Expected Result

It should be checked after clicking the captcha checkbox

### Actual Result

after clicking the captcha checkbox it goes in a loop and throws an error in console Uncaught (in promise) Timeout.

**Comment by SanjuDeveloper** [comment]
@akies1 

Is it possible to share the **screenshot** for the same? This will help me to reproduce the problem.

**Comment by akies1** [comment]
[
![Screenshot from 2023-05-16 15-25-27](https://github.com/bagisto/bagisto/assets/44065937/76260d20-3d93-41a4-90d6-cd7d14b50e18)
](url)

**Comment by akies1** [comment]
![Screenshot from 2023-05-16 15-57-42](https://github.com/bagisto/bagisto/assets/44065937/ed615f2a-5b3c-456f-8060-0847d4e159a1)

**Comment by SanjuDeveloper** [comment]
Hi there.
Thanks for sharing. Let me check with our latest release.
I will update you soon.

**Comment by Amitk-webkul** [comment]
@akies1 Thank you for the information. will update you once the issue is fixed.

**Comment by JozefAB** [comment]
@akies1 I was having the same problem but believe I have figured it out now. It's not an issue with Bagisto, rather it's a problem with Google and the labyrinth that is their Google Cloud console. This is what I did.

1. Go to your Google Cloud 
2. Choose the project for your website from the dropdown at the top or create a new one if you don't already have a project
3. Click on the "Dashboard" link
4. In the menu on the left, scroll down to Security and choose reCAPTCHA Enterprise from the sub-menu
5. If there isn't already one, click "Create Key" to add a new Enterprise Key for your website. This is fairly self-explanatory, so I won't provide steps
6. Once you have your key created, click "Overview" in its card
7. Now click the "Details" tab
8. In the left column under "Web integration" you'll find "Legacy reCAPTCHA Secret Key". Expand this
9. Copy the secret key from here and paste that into your Bagisto Captcha secret key input field

This is what worked for me. It appears that the secret key generated from the old V2 reCAPTCHA admin panel does not work anymore so you have to use the Legacy key from the new Enterprise Key section.

Absolute pain in the neck to figure it out. Not at all a Bagisto problem.

I hope that helps

**Comment by JozefAB** [comment]
Well, spoke too soon. That hasn't fixed it

**Comment by devansh-webkul** [comment]
This is actually not an issue because it's also working on my instance but for double checking. I just remained open this. I will update you once verified.

**Comment by JozefAB** [comment]
@devansh-webkul This is definitely an issue. Please look into it further. By all means try it on my live site https://www.awlmart.co.uk/customer/register. It will work maybe once or twice after which it will fail reliably with "Uncaught (in promise) Timeout" errors in the console log. This same issue occurs in all browsers. I have spent quite a bit of time myself trying to figure out what is going wrong but to no avail.

**Comment by JozefAB** [comment]
For anybody having this same issue, I was able to resolve it by implementing a different recaptcha package. I used this one https://laravel-news.com/package/josiasmontag-laravel-recaptchav3

**Comment by rajan-parmar** [comment]
@jitendra-webkul @devansh-webkul 

I am using 2.2 and configured the google reCaptcha v2.0 site & secret key in the admin panel.
The snapshot is below for your reference. 
let me know if anything details are required.

![image](https://github.com/user-attachments/assets/95462134-143d-424c-8e7c-c032c593780b)

**Comment by rajan-parmar** [comment]
> @jitendra-webkul @devansh-webkul
> 
> I am using 2.2 and configured the google reCaptcha v2.0 site & secret key in the admin panel. The snapshot is below for your reference. let me know if anything details are required.
> 
> ![image](https://private-user-images.githubusercontent.com/53517816/396493258-95462134-143d-424c-8e7c-c032c593780b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1ODQxMjgsIm5iZiI6MTczNDU4MzgyOCwicGF0aCI6Ii81MzUxNzgxNi8zOTY0OTMyNTgtOTU0NjIxMzQtMTQzZC00MjRjLThlN2MtYzAzMmM1OTM3ODBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDA0NTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOGU0NThiOTllODBkMTU5ZTcyY2UyNzg1NDRhZDdkY2RmODI2OWQxODM5MmZmZWI4YjIwMzMxMjFjYTcwN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8PaFnjkJRNjA8YMuIVeob1T2ZSUcJegKgMwF5YWN7Co)

After spending hours I got a solution that js is not loading properly.
here is the solution:
`src/Captcha.php`
```
public function renderJS(): string
    {
        return $this->isActive()
            ? $this->getClientEndpoint()
            : '';
    }
    
    `getCaptchaJSView` method no more required
 ```
 `packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php`
 
 ```
 @push('scripts')
-- {!! Captcha::renderJS() !!} removed from here
        <script>
            function switchVisibility() {
                let passwordField = document.getElementById("password");

                passwordField.type = passwordField.type === "password" ?
                    "text" :
                    "password";
            }

            window.onload = function() {
                var script = document.createElement('script');
                script.src = '{!! Captcha::renderJS() !!}';
                document.body.appendChild(script);
            };
        </script>
        @endpush
   ```
   
NOTE:  `captcha/scripts.blade.php` file no more required

**Comment by strabek** [comment]
@rajan-parmar you have made my day. Thanks
