### ISSUE TITLE
installation fails with sql error

### ISSUE THREAD

**Issue by helgator** [bagisto/bagisto#7585]
**Describe the bug**
Using the GUI web installer or the CLI leads to the same error.

**To Reproduce**
Follow the [docs](https://devdocs.bagisto.com/1.x/introduction/installation.html#install-bagisto-using-composer) .

**Expected behavior**
All pages work.

**Actual behavior**
All pages in "admin" and "store front " give a  404. Only the homepage works.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser firefox

**Comment by Amitk-webkul** [comment]
Hi @helgator,

Can you please **share the steps** that you are following for installing the **Bagisto**? And which **version** of Bagisto are you trying to **install**?

**Comment by devansh-webkul** [comment]
Not able to reproduce this, please use Bagisto forum.
