### ISSUE TITLE
From fresh installed Bagisto master, composer require spatie/laravel-cookie-consent, after following the installation instructions from https://github.com/spatie/laravel-cookie-consent, either by adding @include('cookie-consent::index') to Velocity theme's master.blade.php or adding \Spatie\CookieConsent\CookieConsentMiddleware::class, to Kernel.php. The error appear after refresh.

### ISSUE THREAD

**Issue by arslan-talib** [bagisto/bagisto#7586]
From fresh installed Bagisto master, composer require spatie/laravel-cookie-consent, after following the installation instructions from https://github.com/spatie/laravel-cookie-consent, either by adding @include('cookie-consent::index') to Velocity theme's master.blade.php or adding \Spatie\CookieConsent\CookieConsentMiddleware::class, to Kernel.php. The error appear after refresh.

_Originally posted by @stevechai in https://github.com/bagisto/bagisto/issues/4988#issuecomment-872824653_

**Comment by arslan-talib** [comment]
Target class [Webkul\Shipping\Helper\Rate] does not exist

**Comment by devansh-webkul** [comment]
It looks like you are adding any third-party dependencies and have done some customization. Please use Bagisto forum.
