### ISSUE TITLE
Booking product-- Standard Bagisto 

### ISSUE THREAD

**Issue by Saurabhduttabde341** [bagisto/bagisto#7613]
### Is your feature request related to a problem? Please describe.

It is an advancement of the Standard Bagisto Booking feature. 

### Describe the solution you'd like

--> We can add color to the calendar date so that we can sort out the booked date and available dates visually. 

Screenshot:- 
![image](https://github.com/bagisto/bagisto/assets/80257377/07703d12-fc3a-4b7b-a5db-76751c04a096)

Thanks!

**Comment by devansh-webkul** [comment]
Currently, we are not providing any feature to `1.x` branch anymore. In the `1.x` branch we are now providing bug fixings only. For this, we will check the new theme.

So I am closing this.
