### ISSUE TITLE
Disable web routes

### ISSUE THREAD

**Issue by henryedwardss** [bagisto/bagisto#7643]
### Is your feature request related to a problem? Please describe.

When we use [bagisto/rest-api](https://github.com/bagisto/rest-api), we usually don't need any other routes except those that start with `/api`

Especially when we want to use bagisto only for backend

### Describe the solution you'd like

Disable web routes

**Comment by Amitk-webkul** [comment]
Hi @henryedwardss,

Can you please describe which web routes you are talking about?

**Comment by henryedwardss** [comment]
I want remove all routes except those starting with `/api`.

For example:
product-details/{slug}  ❌
api/locales?page=1 ✔

**Comment by Amitk-webkul** [comment]
Hi @henryedwardss,

You can remove all the web routes from the below route files.

https://github.com/bagisto/bagisto/tree/v1.4.5/packages/Webkul/Shop/src/Routes 

https://github.com/bagisto/bagisto/blob/v1.4.5/packages/Webkul/Velocity/src/Routes/front-routes.php
