### ISSUE TITLE
After saving the attribute value in field "Value Per Channel" and "Value Per Locale" changes to No even if we have selected that as "Yes"

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#766]
Framework Version: 0.1.5

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Not Fixed

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Fixed

**Comment by rsabzaali** [comment]
@jyoti-webkul I see this bug in the latest version bagisto.  I created text type attribute with 3 locales and selected YES on per locales. After savind I see No on my selected per locales
