### ISSUE TITLE
GUI installation does not work on windows

### ISSUE THREAD

**Issue by danhanfry** [bagisto/bagisto#768]
Good, the visual installation doesn't work on windows.

Windows 10
Apache 2.4.37
PHP 5.6.40, 7.0.33, 7.1.26, 72.14, 7.3.1
MySQL 5.7.24
MariaDB 10.3.12
bagisto-bagisto-v0.1.5-0-gb8b96ab

Once all the fields have been filled in, the following error appears.

`php_network_getaddresses: getaddrinfo failed: Unknown host.`

![image](https://user-images.githubusercontent.com/8139751/55292755-e1600900-53ee-11e9-876e-25c0bf75bb45.png)

**Comment by rahulshukla-webkul** [comment]
Hi @danhanfry,

This is basically problem of host. Kindly check your host and port of your database.
