### ISSUE TITLE
Bagisto Version 1.5.1 - Catalog Rule Bug - If i create catalog rule it not affect on Product price due to product_price_indices table

### ISSUE THREAD

**Issue by miteshpanchaltechsevin** [bagisto/bagisto#7700]
**Bagisto Version 1.5.1 - Catalog Rule Bug - If i create catalog rule it not affect on Product price due to product_price_indices table**

When i create catalog rule its not working until i update product because when we create catalog rule its entry only updates in catalog rule ralated product but it not updating entry of product_price_indices table
Because of this product updated price as per cart rule is not working. Then i have to update the product then after that product update function updates product_price_indices table values as per active cart rule and then it works

So can you please update this, Just need to write the code for Update product_price_indices table after Create/Update catalog rule

**To Reproduce**
1. Create one catalog rule in bagisto version 1.5.1
2. Check in front end it will not affect product price
3. Then update any product that matched the criteria of that cart rule 
4. Then again check the front end then it works
5. Again.... Update the cart rule and make it inactive
6. Check front end again, Even after inactive the cart rule it will show the cart rule discounted price
7. Now again go to admin and update that specific product and check front end only after it will update the latest price

Issue is clear.... 
Need to trigger one function which update the product_price_indices table after Create/Update cart rule 

**Expected behavior**
After Updating cart rule it will direct affect front end to product price

**Comment by Amitk-webkul** [comment]
Hello @miteshpanchaltechsevin,

We will fix this issue in the next release.
Meanwhile, you can add the below command in your cron job.

`php artisan indexer:index --mode=full
`

**Comment by SanjuDeveloper** [comment]
Hi @miteshpanchaltechsevin 
Hope your issue will be fix by adding the above command.
And if still you are getting the same issue then please let me know..

**Comment by ali-apadana** [comment]
Above command doesn't work for me (V 2 beta)
In my opinion, This is not good idea storing prices in table. Think about updating million records in product_price_indices table!
