### ISSUE TITLE
Category name displays in caps on frontend.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#775]
Framework Version: 0.1.5
![Screenshot (15)](https://user-images.githubusercontent.com/45203177/55329576-94426c80-54ac-11e9-8383-d3e2b693649b.png)

![Screenshot from 2019-04-01 18-32-25](https://user-images.githubusercontent.com/45203177/55329745-ff8c3e80-54ac-11e9-90e0-1c2a8ed0021d.png)

**Comment by samir-araujo** [comment]
Do you have a demo URL were we could take a look at it?

**Comment by rahulshukla-webkul** [comment]
Hi @samir-araujo 

Here is demo URL - https://demo.bagisto.com/

**Comment by samir-araujo** [comment]
If your installation is the same as the default demo, them you just have to remove the `text-transform: uppercase` rule in your theme.

This `text-transform` rule is within `.header .header-bottom .nav a`

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Fixed
![Screenshot from 2019-04-02 15-22-36](https://user-images.githubusercontent.com/45203177/55393605-3325a200-555b-11e9-8328-84e0123e9383.png)
