### ISSUE TITLE
Database column not found during GUI install

### ISSUE THREAD

**Issue by thewhiterabbit** [bagisto/bagisto#7767]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v1.5.1-0-g5ac164c

### Issue Description

2022_10_28_201144_add_columns_in_product_flat_table .............. 18ms FAILIn Connection.php line 793:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'products.type' in '  field list' (Connection: mysql, SQL: update `b4g_product_flat` inner join `  b4g_products` on `b4g_product_flat`.`product_id` = `b4g_products`.`id` set  `b4g_product_flat`.`type` = products.type, `b4g_product_flat`.`attribute_fa  mily_id` = products.attribute_family_id)In Connection.php line 603:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'products.type' in '  field list'

### Preconditions

Following GUI install directions.

### Steps to reproduce

[Download Bagisto](https://bagisto.com/en/download/)
(opens new window)
Extract the contents of the zip file.
Point your HTTP server to the public/ directory of the project and open it on your browser.
For example:

    https://example.com

Start the GUI installer
Use legit cred

### Expected Result

Response DONE instead of FAILIn

### Actual Result

   INFO  Configuration cached successfully.  Dropping all tables .............................................. 10ms DONE   INFO  Preparing database.  Creating migration table .......................................... 7ms DONE   INFO  Running migrations.  2014_10_12_000000_create_users_table ............................. 14ms DONE  2014_10_12_100000_create_admin_password_resets_table ............. 11ms DONE  2014_10_12_100000_create_password_resets_table .................... 9ms DONE  2018_06_12_111907_create_admins_table ............................. 9ms DONE  2018_06_13_055341_create_roles_table .............................. 4ms DONE  2018_07_05_130148_create_attributes_table ........................ 11ms DONE  2018_07_05_132854_create_attribute_translations_table ............ 19ms DONE  2018_07_05_135150_create_attribute_families_table ................. 4ms DONE  2018_07_05_135152_create_attribute_groups_table .................. 50ms DONE  2018_07_05_140832_create_attribute_options_table ................. 13ms DONE  2018_07_05_140856_create_attribute_option_translations_table ..... 18ms DONE  2018_07_05_142820_create_categories_table ........................ 11ms DONE  2018_07_10_055143_create_locales_table ........................... 11ms DONE  2018_07_20_054426_create_countries_table .......................... 5ms DONE  2018_07_20_054502_create_currencies_table ......................... 4ms DONE  2018_07_20_054542_create_currency_exchange_rates_table ........... 20ms DONE  2018_07_20_064849_create_channels_table .......................... 80ms DONE  2018_07_21_142836_create_category_translations_table ............. 19ms DONE  2018_07_23_110040_create_inventory_sources_table ................. 10ms DONE  2018_07_24_082635_create_customer_groups_table .................... 4ms DONE  2018_07_24_082930_create_customers_table ......................... 28ms DONE  2018_07_24_083025_create_customer_addresses_table ................ 13ms DONE  2018_07_27_065727_create_products_table ......................... 142ms DONE  2018_07_27_070011_create_product_attribute_values_table .......... 30ms DONE  2018_07_27_092623_create_product_reviews_table ................... 23ms DONE  2018_07_27_113941_create_product_images_table .................... 12ms DONE  2018_07_27_113956_create_product_inventories_table ............... 24ms DONE  2018_08_03_114203_create_sliders_table ........................... 13ms DONE  2018_08_30_064755_create_tax_categories_table .................... 24ms DONE  2018_08_30_065042_create_tax_rates_table ......................... 11ms DONE  2018_08_30_065840_create_tax_mappings_table ...................... 29ms DONE  2018_09_05_150444_create_cart_table .............................. 25ms DONE  2018_09_05_150915_create_cart_items_table ........................ 52ms DONE  2018_09_11_064045_customer_password_resets ........................ 9ms DONE  2018_09_19_092845_create_cart_address ............................ 23ms DONE  2018_09_19_093453_create_cart_payment ............................ 13ms DONE  2018_09_19_093508_create_cart_shipping_rates_table ............... 13ms DONE  2018_09_20_060658_create_core_config_table ....................... 12ms DONE  2018_09_27_113154_create_orders_table ............................ 27ms DONE  2018_09_27_113207_create_order_items_table ....................... 30ms DONE  2018_09_27_113405_create_order_address_table ..................... 23ms DONE  2018_09_27_115022_create_shipments_table ......................... 22ms DONE  2018_09_27_115029_create_shipment_items_table .................... 14ms DONE  2018_09_27_115135_create_invoices_table .......................... 28ms DONE  2018_09_27_115144_create_invoice_items_table ..................... 23ms DONE  2018_10_01_095504_create_order_payment_table ..................... 13ms DONE  2018_10_03_025230_create_wishlist_table .......................... 35ms DONE  2018_10_12_101803_create_country_translations_table .............. 13ms DONE  2018_10_12_101913_create_country_states_table .................... 14ms DONE  2018_10_12_101923_create_country_state_translations_table ........ 21ms DONE  2018_11_15_153257_alter_order_table ............................... 6ms DONE  2018_11_15_163729_alter_invoice_table ............................. 6ms DONE  2018_11_16_173504_create_subscribers_list_table .................. 12ms DONE  2018_11_17_165758_add_is_verified_column_in_customers_table ...... 10ms DONE  2018_11_21_144411_create_cart_item_inventories_table .............. 5ms DONE  2018_11_26_110500_change_gender_column_in_customers_table ......... 5ms DONE  2018_11_27_174449_change_content_column_in_sliders_table ......... 93ms DONE  2018_12_05_132625_drop_foreign_key_core_config_table ............. 19ms DONE  2018_12_05_132629_alter_core_config_table ........................ 19ms DONE  2018_12_06_185202_create_product_flat_table ...................... 13ms DONE  2018_12_21_101307_alter_channels_table ........................... 28ms DONE  2018_12_24_123812_create_channel_inventory_sources_table ......... 28ms DONE  2018_12_24_184402_alter_shipments_table .......................... 16ms DONE  2018_12_26_165327_create_product_ordered_inventories_table ....... 27ms DONE  2018_12_31_161114_alter_channels_category_table .................. 15ms DONE  2019_01_11_122452_add_vendor_id_column_in_product_inventories_table  9ms DONE  2019_01_25_124522_add_updated_at_column_in_product_flat_table .... 42ms DONE  2019_01_29_123053_add_min_price_and_max_price_column_in_product_flat_table  22ms DONE  2019_01_31_164117_update_value_column_type_to_text_in_core_config_table  15ms DONE  2019_02_21_145238_alter_product_reviews_table ..................... 8ms DONE  2019_02_21_152709_add_swatch_type_column_in_attributes_table ...... 4ms DONE  2019_02_21_153035_alter_customer_id_in_product_reviews_table ..... 17ms DONE  2019_02_21_153851_add_swatch_value_columns_in_attribute_options_table  4ms DONE  2019_03_15_123337_add_display_mode_column_in_categories_table ..... 4ms DONE  2019_03_28_103658_add_notes_column_in_customers_table ............. 4ms DONE  2019_04_24_155820_alter_product_flat_table ....................... 19ms DONE  2019_05_13_024320_remove_tables .................................. 16ms DONE  2019_05_13_024321_create_cart_rules_table ......................... 4ms DONE  2019_05_13_024322_create_cart_rule_channels_table ................ 28ms DONE  2019_05_13_024323_create_cart_rule_customer_groups_table ......... 26ms DONE  2019_05_13_024324_create_cart_rule_translations_table ............ 16ms DONE  2019_05_13_024325_create_cart_rule_customers_table ............... 22ms DONE  2019_05_13_024326_create_cart_rule_coupons_table ................. 13ms DONE  2019_05_13_024327_create_cart_rule_coupon_usage_table ............ 23ms DONE  2019_05_22_165833_update_zipcode_column_type_to_varchar_in_cart_address_table  25ms DONE  2019_05_23_113407_add_remaining_column_in_product_flat_table ..... 11ms DONE  2019_05_23_155520_add_discount_columns_in_invoice_items_table ..... 5ms DONE  2019_05_23_184029_rename_discount_columns_in_cart_table .......... 36ms DONE  2019_06_04_114009_add_phone_column_in_customers_table ............ 12ms DONE  2019_06_06_195905_update_custom_price_to_nullable_in_cart_items .. 10ms DONE  2019_06_15_183412_add_code_column_in_customer_groups_table ........ 9ms DONE  2019_06_17_180258_create_product_downloadable_samples_table ...... 12ms DONE  2019_06_17_180314_create_product_downloadable_sample_translations_table  12ms DONE  2019_06_17_180325_create_product_downloadable_links_table ........ 15ms DONE  2019_06_17_180346_create_product_downloadable_link_translations_table  12ms DONE  2019_06_19_162817_remove_unique_in_phone_column_in_customers_table  6ms DONE  2019_06_21_130512_update_weight_column_deafult_value_in_cart_items_table  17ms DONE  2019_06_21_202249_create_downloadable_link_purchased_table ....... 38ms DONE  2019_07_02_180307_create_booking_products_table .................. 15ms DONE  2019_07_05_114157_add_symbol_column_in_currencies_table ........... 4ms DONE  2019_07_05_154415_create_booking_product_default_slots_table ..... 15ms DONE  2019_07_05_154429_create_booking_product_appointment_slots_table . 14ms DONE  2019_07_05_154440_create_booking_product_event_tickets_table ..... 12ms DONE  2019_07_05_154451_create_booking_product_rental_slots_table ...... 12ms DONE  2019_07_05_154502_create_booking_product_table_slots_table ....... 13ms DONE  2019_07_11_151210_add_locale_id_in_category_translations ......... 13ms DONE  2019_07_23_033128_alter_locales_table ............................. 4ms DONE  2019_07_23_174708_create_velocity_contents_table .................. 4ms DONE  2019_07_23_175212_create_velocity_contents_translations_table .... 16ms DONE  2019_07_29_142734_add_use_in_flat_column_in_attributes_table ...... 5ms DONE  2019_07_30_153530_create_cms_pages_table ......................... 32ms DONE  2019_07_31_143339_create_category_filterable_attributes_table .... 22ms DONE  2019_08_02_105320_create_product_grouped_products_table .......... 26ms DONE  2019_08_12_184925_add_additional_column_in_wishlist_table ......... 7ms DONE  2019_08_20_170510_create_product_bundle_options_table ............ 13ms DONE  2019_08_20_170520_create_product_bundle_option_translations_table  16ms DONE  2019_08_20_170528_create_product_bundle_option_products_table .... 24ms DONE  2019_08_21_123707_add_seo_column_in_channels_table ................ 4ms DONE  2019_09_11_184511_create_refunds_table ........................... 14ms DONE  2019_09_11_184519_create_refund_items_table ...................... 34ms DONE  2019_09_26_163950_remove_channel_id_from_customers_table .......... 8ms DONE  2019_10_03_105451_change_rate_column_in_currency_exchange_rates_table  33ms DONE  2019_10_21_105136_order_brands ................................... 45ms DONE  2019_10_24_173358_change_postcode_column_type_in_order_address_table  20ms DONE  2019_10_24_173437_change_postcode_column_type_in_cart_address_table  9ms DONE  2019_10_24_173507_change_postcode_column_type_in_customer_addresses_table  15ms DONE  2019_11_21_194541_add_column_url_path_to_category_translations .... 8ms DONE  2019_11_25_171136_add_applied_cart_rule_ids_column_in_cart_table .. 4ms DONE  2019_11_25_171208_add_applied_cart_rule_ids_column_in_cart_items_table  5ms DONE  2019_11_30_124437_add_applied_cart_rule_ids_column_in_orders_table  4ms DONE  2019_11_30_165644_add_discount_columns_in_cart_shipping_rates_table  4ms DONE  2019_12_03_175253_create_remove_catalog_rule_tables ............... 9ms DONE  2019_12_03_184613_create_catalog_rules_table ...................... 5ms DONE  2019_12_03_184651_create_catalog_rule_channels_table ............. 28ms DONE  2019_12_03_184732_create_catalog_rule_customer_groups_table ...... 25ms DONE  2019_12_06_101110_create_catalog_rule_products_table ............. 44ms DONE  2019_12_06_110507_create_catalog_rule_product_prices_table ....... 49ms DONE  2019_12_14_000001_create_personal_access_tokens_table ............ 15ms DONE  2019_12_30_155256_create_velocity_meta_data ....................... 4ms DONE  2020_01_02_201029_add_api_token_columns .......................... 19ms DONE  2020_01_09_154851_add_shipping_discount_columns_in_orders_table ... 5ms DONE  2020_01_09_202815_add_inventory_source_name_column_in_shipments_table  4ms DONE  2020_01_10_122226_update_velocity_meta_data ....................... 4ms DONE  2020_01_10_151902_customer_address_improvements .................. 13ms DONE  2020_01_13_131431_alter_float_value_column_type_in_product_attribute_values_table  27ms DONE  2020_01_13_155803_add_velocity_locale_icon ........................ 4ms DONE  2020_01_13_192149_add_category_velocity_meta_data ................. 4ms DONE  2020_01_14_191854_create_cms_page_translations_table ............. 18ms DONE  2020_01_14_192206_remove_columns_from_cms_pages_table ............ 13ms DONE  2020_01_15_130209_create_cms_page_channels_table ................. 25ms DONE  2020_01_15_145637_add_product_policy .............................. 4ms DONE  2020_01_15_152121_add_banner_link ................................. 4ms DONE  2020_01_28_102422_add_new_column_and_rename_name_column_in_customer_addresses_table  28ms DONE  2020_01_29_124748_alter_name_column_in_country_state_translations_table  16ms DONE  2020_02_18_165639_create_bookings_table .......................... 22ms DONE  2020_02_21_121201_create_booking_product_event_ticket_translations_table  18ms DONE  2020_02_24_190025_add_is_comparable_column_in_attributes_table .... 4ms DONE  2020_02_25_181902_propagate_company_name ......................... 10ms DONE  2020_02_26_163908_change_column_type_in_cart_rules_table ......... 19ms DONE  2020_02_28_105104_fix_order_columns ............................... 0ms DONE  2020_02_28_111958_create_customer_compare_products_table ......... 23ms DONE  2020_03_23_201431_alter_booking_products_table ................... 20ms DONE  2020_04_13_224524_add_locale_in_sliders_table ..................... 4ms DONE  2020_04_16_130351_remove_channel_from_tax_category ................ 9ms DONE  2020_04_16_185147_add_table_addresses ............................ 77ms DONE  2020_05_06_171638_create_order_comments_table .................... 12ms DONE  2020_05_21_171500_create_product_customer_group_prices_table ..... 26ms DONE  2020_06_08_161708_add_sale_prices_to_booking_product_event_tickets  5ms DONE  2020_06_10_201453_add_locale_velocity_meta_data ................... 4ms DONE  2020_06_25_162154_create_customer_social_accounts_table .......... 18ms DONE  2020_06_25_162340_change_email_password_columns_in_customers_table  26ms DONE  2020_06_30_163510_remove_unique_name_in_tax_categories_table ...... 4ms DONE  2020_07_31_142021_update_cms_page_translations_table_field_html_content  17ms DONE  2020_08_01_132239_add_header_content_count_velocity_meta_data_table  4ms DONE  2020_08_12_114128_removing_foriegn_key ............................ 7ms DONE  2020_08_17_104228_add_channel_to_velocity_meta_data_table ......... 5ms DONE  2020_09_07_120413_add_unique_index_to_increment_id_in_orders_table  19ms DONE  2020_09_07_195157_add_additional_to_category ...................... 4ms DONE  2020_11_10_174816_add_product_number_column_in_product_flat_table . 6ms DONE  2020_11_19_112228_create_product_videos_table .................... 11ms DONE  2020_11_20_105353_add_columns_in_channels_table ................... 5ms DONE  2020_11_26_141455_create_marketing_templates_table ................ 4ms DONE  2020_11_26_150534_create_marketing_events_table ................... 4ms DONE  2020_11_26_150644_create_marketing_campaigns_table ............... 45ms DONE  2020_12_18_122826_add_is_tax_calculation_column_to_cart_shipping_rates_table  4ms DONE  2020_12_21_000200_create_channel_translations_table .............. 22ms DONE  2020_12_21_140151_remove_columns_from_channels_table ............. 30ms DONE  2020_12_24_131004_add_customer_id_column_in_subscribers_list_table  13ms DONE  2020_12_27_121950_create_jobs_table ............................... 9ms DONE  2021_02_03_104907_add_adittional_data_to_order_payment_table ...... 4ms DONE  2021_02_04_150033_add_download_canceled_column_in_downloadable_link_purchased_table  4ms DONE  2021_03_11_212124_create_order_transactions_table ................ 13ms DONE  2021_03_19_184538_add_expired_at_and_sort_order_column_in_sliders_table  4ms DONE  2021_04_07_132010_create_product_review_images_table ............. 12ms DONE  2021_06_17_103057_alter_products_table ............................ 4ms DONE  2021_10_14_122221_add_image_column_to_customers_table ............. 5ms DONE  2021_10_23_125017_add_transaction_amount_column ................... 5ms DONE  2021_10_29_030610_add_reminders_on_invoices_table ................. 4ms DONE  2021_10_30_112900_add_next_reminder_at_on_invoices_table .......... 4ms DONE  2021_12_15_104544_notifications .................................. 13ms DONE  2022_01_25_160015_update_country_state_and_zip_code_in_addresses_table  26ms DONE  2022_02_01_185800_add_position_column_to_product_images_table ..... 4ms DONE  2022_02_02_142616_add_is_suspended_column_to_customers_table ...... 4ms DONE  2022_02_03_120502_add_position_column_to_product_videos_table ..... 4ms DONE  2022_03_11_133408_add_enable_wysiwyg_column_in_attributes_table ... 4ms DONE  2022_03_15_160510_create_failed_jobs_table ....................... 10ms DONE  2022_03_22_105355_add_image_column_in_admins_table ................ 5ms DONE  2022_04_01_094622_create_sitemaps_table ........................... 4ms DONE  2022_10_03_144232_create_product_price_indices_table ............. 31ms DONE  2022_10_04_144444_create_job_batches_table ....................... 11ms DONE  2022_10_08_134150_create_product_inventory_indices_table ......... 31ms DONE  2022_10_28_161132_remove_product_flat_id_column_in_velocity_customer_compare_products_table  23ms DONE  2022_10_28_182304_drop_use_in_flat_column_from_attributes_table ... 5ms DONE  2022_10_28_200015_drop_columns_in_product_flat_table ............. 51ms DONE  2022_10_28_201144_add_columns_in_product_flat_table .............. 18ms FAILIn Connection.php line 793:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'products.type' in '  field list' (Connection: mysql, SQL: update `b4g_product_flat` inner join `  b4g_products` on `b4g_product_flat`.`product_id` = `b4g_products`.`id` set  `b4g_product_flat`.`type` = products.type, `b4g_product_flat`.`attribute_fa  mily_id` = products.attribute_family_id)In Connection.php line 603:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'products.type' in '  field list'

### Screenshots

![Screenshot 2023-07-05 051722](https://github.com/bagisto/bagisto/assets/5334222/d8f212b8-b803-4854-9e25-eaabce7563ac)

**Comment by Amitk-webkul** [comment]
Hi @thewhiterabbit,

Something went wrong in the installation process.

To install Bagisto using our GUI installer, follow these steps:


* [Download Bagisto](https://bagisto.com/en/download/) from our website.


* Extract the contents of the downloaded zip file.


* Navigate to the project root directory.


* Run the following command:

```
composer install
```

* Configure your HTTP server to point to the public/ directory of the project.


* Open your browser and access the following URL:


* http://localhost/bagisto/public/

This will launch the Bagisto installer.
