### ISSUE TITLE
Recommendations to install in windows

### ISSUE THREAD

**Issue by danhanfry** [bagisto/bagisto#777]
There are two ways to install bagisto

- GUI Mode
- Command line

currently the installation by gui does not work correctly check https://github.com/bagisto/bagisto/issues/768

The command line installation works, but with some errors

- composer create-project bagisto/bagisto
- configure .env
- php artisan migrate
- php artisan db:seed
- php artisan vendor:publish
- php artisan storage:link
- composer dump-autoload

![image](https://user-images.githubusercontent.com/8139751/55353330-53a21d80-54c3-11e9-9c92-711b8b785b20.png)

The solution I found was, download the project from [here](https://github.com/bagisto/bagisto/archive/v0.1.5.zip)

- composer install
- create the .env file copying the .env.example
- php artisan migrate
- php artisan db:seed
- php artisan vendor:publish
- php artisan storage:link
- composer dump-autoload

This way it all works out.

I think the code that is downloaded in zip is correct but the GUI installer fails.
In this tutorial we join the 2 ways of installation

**Comment by rahulshukla-webkul** [comment]
Hi @danhanfry 

We have fixed all mentioned issues by you, but it is going on testing phase.
For latest code you can download zip from master branch of bagisto repository & can test from there.Soon we will release our latest version.

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Checked the installation on windows and its working fine.

**Comment by georgiosdelimpasis** [comment]
still not working for me, tried everything

**Comment by rahulshukla-webkul** [comment]
Hi @georgiosdelimpasis 

Please install with our latest code on git & if still issues is there, please add a screenshot for the same.
