### ISSUE TITLE
Error when add item to cart

### ISSUE THREAD

**Issue by mateo2181** [bagisto/bagisto#778]
After confirm an order, I add a new item to the cart and get this error "A non-numeric value encountered", I think is a problem with session variables.

**Comment by prashant-webkul** [comment]
@mateo2181 Please provide more info on how you encountered this issue?

**Comment by mateo2181** [comment]
Yes, I will describe steps:
1. add an item to cart and go to checkout.
2. chose any send method and payment method and confirm order. (works fine)
3. I have seen the code and after create an order the method Cart::deActivateCart()  remove the cart with session()->forget('cart');
4. If I want to add a new item to the cart I got the error "A non-numeric value encountered".

I am working with currency ARS.

**Comment by prashant-webkul** [comment]
@mateo2181 Thanks for providing the steps we will look into this real soon and a fix will be provided real quick.

**Comment by mateo2181** [comment]
I see your comment now.
I have cloned the repo to work with docker. 
So I have running it in 80 by default.

**Comment by prashant-webkul** [comment]
> I see your comment now.
> I have cloned the repo to work with docker.
> So I have the server running in port 80 by default.

https://github.com/prashant-webkul/bagisto-docker -> Check this for running Bagisto in Docker.

**Comment by mateo2181** [comment]
Yes, I have cloned that repo.

**Comment by prashant-webkul** [comment]
@mateo2181 Are you still facing any issues with the cart?

**Comment by mateo2181** [comment]
Yes, I have the same problem. I have tried add new products but the error is the same.

**Comment by prashant-webkul** [comment]
@mateo2181 No one has encountered such issue till now. The problem here is that we cannot reproduce the issue.
Which trims the possibility that the issue may be due to some problem in your system which can be related to Docker.
But on the contrary our demo of Bagisto is also using docker container issue is not coming over there.

For more assistance further please file a support ticket at bagisto.uvdesk.com, we will look into the issue further more over there.

**Comment by mateo2181** [comment]
Ok, thanks!

**Comment by gydachandra** [comment]
Issue 'non-numeric is value encountered'. When I 'adding the cart' or 'buy now' from product page.
Step:
1. Add product 'simple product type' 
2. Linked product 'cross-selling' 
3. Front end I add product or buy now. 
4. Show notification 'non-numeric is value encountered' 

Let me show how to fix it. Any suggestion? 

I think my configuration absolutely clear and nothing.

**Comment by prashant-webkul** [comment]
@gydachandra Which version of Bagisto are you using?

**Comment by BrianMwangi21** [comment]
Also facing the same issue.

Using the latest commit of Bagisto

**Comment by gydachandra** [comment]
@prashant-webkul I'm using the latest update, v. 0.1.6

**Comment by BrianMwangi21** [comment]
Hi there, just asking if the issue has been resolved ?

Thanks

**Comment by prashant-webkul** [comment]
@BrianMwangi21 Please share the screenshot of the exception.

**Comment by gydachandra** [comment]
sorry, this thread was resolved. Thank you.

**Comment by BrianMwangi21** [comment]
Please point me to the resolve.

Thanks

**Comment by prashant-webkul** [comment]
Fixed this issue in PR #1363

**Comment by prashant-webkul** [comment]
@BrianMwangi21 @gydachandra Please take the latest.

**Comment by BrianMwangi21** [comment]
Thanks

**Comment by ket-c** [comment]
i get this error when i try to add to cart a  product that has a **customer group price**
