### ISSUE TITLE
Add African payment gateway (Paystack)

### ISSUE THREAD

**Issue by TheYoungestDev** [bagisto/bagisto#7817]
### Is your feature request related to a problem? Please describe.

The current project lacks support for African payment gateways, which is a significant limitation for users in Africa. This restriction prevents them from seamlessly integrating their preferred payment methods into the system, resulting in a poor user experience and hindering business growth.

### Describe the solution you'd like

I propose adding support for the African payment gateway, Paystack, to the project. Paystack is a widely used and trusted payment gateway in Africa, offering seamless integration with local payment methods such as mobile money, bank transfers, and card payments. By integrating Paystack into the project, we can provide African users with a familiar and reliable payment option, enabling them to transact easily and securely.

### Describe alternatives you've considered

Building a custom payment gateway: Developing a custom payment gateway specific to Africa would require significant time, resources, and expertise. It would also involve establishing relationships with local banks, complying with regulatory requirements, and addressing security concerns. Integrating with an existing and reputable payment gateway like Paystack eliminates these challenges and provides a proven solution.
Supporting other African payment gateways: While Paystack is one of the leading payment gateways in Africa, there are other regional options available. However, implementing multiple payment gateways could increase complexity and maintenance efforts. Initially integrating Paystack would cater to a large user base, and additional gateways could be considered in the future based on user demand and market trends.

### Additional context

Adding Paystack as an African payment gateway to the project will allow us to tap into the thriving African market, which is experiencing rapid growth in e-commerce and online transactions. By embracing Paystack, we can provide African users with a localized payment experience, enhancing their trust in the platform and facilitating their transactions. Integrating Paystack aligns with the goal of expanding the project's global reach and improving user satisfaction across diverse markets.

**Comment by Amitk-webkul** [comment]
Hi @TheYoungestDev,

You can customize this.

**Comment by TheYoungestDev** [comment]
Okay then.

**Comment by toluwagbemiga** [comment]
I've created a paystack package 
It's located in https://www.github.com/toluwagbemiga/bagisto-paystack
