### ISSUE TITLE
Hello, i've problem after install some packages

### ISSUE THREAD

**Issue by Davronjuraev** [bagisto/bagisto#7931]
![image](https://github.com/bagisto/bagisto/assets/15152078/d3bb4241-7dff-41ad-bae9-2a5e5d3e68c8)

After installing this two package i got this problem below in screenshot. When i go to Settings->Velocity showing me just white blank page. My added packages is: 
1.Show price after login
2.Hide Shop for guest

Please help me to solve this. Thanks for all

**Comment by Amitk-webkul** [comment]
Hello @Davronjuraev,

It looks like you are using the paid extension. Please open a support ticket for that as this is not related to the core part,

https://bagisto.uvdesk.com/en/

**Comment by Davronjuraev** [comment]
no it's not, i'm using free exts. All two ext also free

**Comment by Amitk-webkul** [comment]
Hello there,

This is only for the Bagisto Core part,
Please open a support ticket for that as this is not related to the core part.

https://bagisto.uvdesk.com/en/
