### ISSUE TITLE
Add new module

### ISSUE THREAD

**Issue by mateo2181** [bagisto/bagisto#797]
Hello,
I am trying to add a new Module inside pacakges folder.
I have created Custom/Mercadopago inside packages with models, migrations and providers.

in compose.json i have added 
"replace": {
  ...
  "bagisto/laravel-mercadopago": "v0.1.0"
} 
"autoload": {
    ...
    "psr-4": {
       ...
      "Custom\\Mercadopago\\": "packages/Custom/Mercadopago/src"    
   }
}

How can I run migrations of that module?
I have run "php artisan module:migrate Custom\\Mercadopago" but got error "Module [Custom\Mercadopago] does not exist!".

I read docs here https://nwidart.com/laravel-modules/v4/introduction but I didn't find a solution.

Thanks in advance.

**Comment by prashant-webkul** [comment]
You better **read** this: https://laravel.com/docs/5.8/packages
It will for sure help you in getting clear cut response for building a package inside **Bagisto**. Which is none different than **Laravel's**.
Follow pattern of **composer.json** for autoloading php classes inside any **package** like **Admin,** **Shop**, **project root's** **composer.json** file and lastly **config/app.php** file entries.

**Comment by mateo2181** [comment]
I had forgotten add provider in config/app.php.
Now works!!

Thanks!

**Comment by kkkasio** [comment]
Are you developing the module? how could I help and contend?

**Comment by alissonalberini** [comment]
@mateo2181  estou com o @kkkasio nesta, se eu puder participar, acredito ser útil.

**Comment by mateo2181** [comment]
Hi @alissonalberini @kkkasio, I haven't been working in the pacakge but I can share the code and we can continue working on it.

**Comment by alissonalberini** [comment]
Pode compartilhar, se puder descrever um readme, detalhando o andamento para prosseguirmos de onde parou, eu me comprometo a dar continuidade.

**Comment by mateo2181** [comment]
https://github.com/mateo2181/mercadopago-laravel inside the package write you two aclarations. You can

**Comment by Sinnercito** [comment]
Estoy Tratando de implementarlo pero no logro hacerlo! Alguien lo logro? me pueden dar una mano? solo llego a imprimir lo que esta en MPcontroller.php pero no me doy cuenta de que es lo que tengo que hacer con esos datos.. 

Gracias!!!

**Comment by mateo2181** [comment]
the way I am doing it is:
1. Clone package https://github.com/mateo2181/mercadopago-laravel inside packages folder.
2. In config/paymentmethods.php add: 
```
'mercadopago' => [
        'code' => 'mercadopago',
        'title' => 'Tarjeta de Crédito / Débito',
        'description' => '',
        'class' => 'Laravel\Mercadopago\Payment\MercadoPago',
        'active' => true
]

```
3.  In composer.json:
```
"autoload": {
     "psr-4": {
           . . .
           "Laravel\\Mercadopago\\": "packages/Laravel/Mercadopago/src"
      }
}
``` 

4. In config/app.php add inside providers: Laravel\Mercadopago\Providers\MPServiceProvider::class

I updated mercadopago/dx-php package to version 2.0.0 and I didn't check if everything is working correctly now. 
@Sinnercito @kkkasio @alissonalberini feel free to fork the package and do pull requests if you change/improve something.

**Comment by nosmk** [comment]
Soon the extension will be in bagisto extensions. It is in the process of approval. When available I share the link.

**Comment by CesarMdz** [comment]
> 
> 
> The steps I followed were:
> 
>     1. Clone package https://github.com/mateo2181/mercadopago-laravel inside packages folder.
> 
>     2. Add MP_CLIENT_ID and MP_CLIENT_SECRET in .env.
> 
>     3. In config/paymentmethods.php add:
> 
> 
> ```
> 'mercadopago' => [
>         'code' => 'mercadopago',
>         'title' => 'Tarjeta de Crédito / Débito',
>         'description' => '',
>         'class' => 'Laravel\Mercadopago\Payment\MercadoPago',
>         'active' => true
> ]
> ```
> 
>     1. In composer.json:
> 
> 
> ```
> "autoload": {
>      "psr-4": {
>            . . .
>            "Laravel\\Mercadopago\\": "packages/Laravel/Mercadopago/src"
>       }
> }
> ```
> 
>     1. In config/app.php add inside providers: Laravel\Mercadopago\Providers\MPServiceProvider::class
> 
> 
> I updated mercadopago/dx-php package to version 2.0.0 and I didn't check if everything is working correctly now.
> @Sinnercito @kkkasio @alissonalberini feel free to fork the package and do pull requests if you change/improve something.

Hola amigo, gracias por este aporte, la verdad estaba intentando hacer un pakage, pero no pude, ahora con tu proyecto veo una luz jeje, pero quiero preguntar, para no regarla, despues de hacer los 5  pasos, que comandos en que orden debo de correr del composer y del artisan.

Saludos y gracias

**Comment by CesarMdz** [comment]
Ya hice los pasos que mencionas pero ahora me aparece este error, no se si te paso tambien:
`<a href="https://ibb.co/n6xjqY9"><img src="https://i.ibb.co/sb8qpNn/Sin-t-tulo.png" alt="Sin-t-tulo" border="0"></a>```

**Comment by mateo2181** [comment]
Hola @CesarMdz, por lo que veo es un problema en la libreria de MP. Deberias probar volviendo a la versión anterior de mercadopago/dx-php y usar la 1.8.1 en lugar de la 2.0.0, tal vez eso lo solucione.

Saludos

**Comment by CesarMdz** [comment]
hola @mateo2181 gracias por responder, ok voy a instalar la version 1.8.1 y te digo como me fue, gracias, buen dia!

**Comment by tomasgelp** [comment]
Hola saben si salio las extensiones bagisto?

**Comment by nosmk** [comment]
https://bagisto.com/en/extensions/laravel-ecommerce-mercado-pago-payment-gateway/
