### ISSUE TITLE
Multiselect Attribute and Layered Navigation

### ISSUE THREAD

**Issue by ludioao** [bagisto/bagisto#799]
Hello 

I have a product with a attribute multiselect, at Product_Flat table we have: "103,105,106". 
But when I use it for search on store front, they search like product_flat.attribute = 105 or product_flat=attribute = 106... 
looking at MySQL documentation, we have to use something like this instead: 
```SELECT FIND_IN_SET('105', '103,105,106') AS result;```

**Comment by prashant-webkul** [comment]
@ludioao Thanks, we will surely look into this regard. Will reply you soon here.

**Comment by rahulshukla-webkul** [comment]
Hi @ludioao 

We Have implemented your suggestions.
Once again, thank you very much for your suggestions & hope to get more suggestions & advice in future.

**Comment by jyoti-webkul** [comment]
Framework version: 0.1.5
Fixed
