### ISSUE TITLE
SQL error when running with sqlite

### ISSUE THREAD

**Issue by bergstar** [bagisto/bagisto#802]
It seems it is not possible to use `DB_CONNECTION=sqlite`

Getting this error when running:
`php artisan migrate --fresh`

`SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "product_reviews" add column "name" varchar not null)
`

**Comment by jay-thanki** [comment]
You can't add column without default value in sqlite.
error comes from `2019_02_21_145238_alter_product_reviews_table.php` file 
can i fix it ? but i can't test it right now.

**Comment by rahulshukla-webkul** [comment]
Hi @jay-thanki 

You can fix it.we will test it.

**Comment by rahulshukla-webkul** [comment]
Sure, You can fix it. We will test it.

**Comment by jay-thanki** [comment]
need to change in migration file `2019_02_21_145238_alter_product_reviews_table.php` because if i create new migration file than error will fire from above file. @rahulshukla-webkul

**Comment by rahulshukla-webkul** [comment]
Hi @bergstar 

We have Fixed this issues.We will release our next version soon. You can wait for that release otherwise you can clone or download our latest code from git repository.
