### ISSUE TITLE
Problem with arrows symbols

### ISSUE THREAD

**Issue by santiagoduc0s** [bagisto/bagisto#8038]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.5.1

### Issue Description

when reloading the page some icons are broken

I am working in local

This happens to me on several occasions

![image](https://github.com/bagisto/bagisto/assets/66749801/f4b956fc-440b-4a32-971b-7b35350476a8)

![image](https://github.com/bagisto/bagisto/assets/66749801/b3a2d407-cdd8-4c87-bc1e-7ad365f85691)

![image](https://github.com/bagisto/bagisto/assets/66749801/d551836e-8cbe-4bc1-b954-064a51682e4e)

### Preconditions

...

### Steps to reproduce

Reload the page and sometimes it happens

### Expected Result

...

### Actual Result

...

**Comment by santiagoduc0s** [comment]
I don't have any custom settings, since I installed the package this happens to me, but it doesn't happen all the time, but often.

**Comment by Amitk-webkul** [comment]
Hello there,

Clear the cache and hard refresh then it will work fine.

If still facing the issue, you can take a reference from [here](https://bagisto.com/en/how-to-fix-image-broken-issue-in-bagisto/)
