### ISSUE TITLE
Not showing product image properly in the order listing page in the admin panel.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8070]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

In the Admin panel, Not showing proper product images if there are more than 3 products in a single order and the filter container should be opened.

### Preconditions

1.  Admin should be logged in.
2.  Filter container should be opened.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'sales '
3. Click on the orders
4. Click on the filter option
5. See the error

### Expected Result

The images should be shown.

### Actual Result

The image is not showing properly.[Here](https://prnt.sc/ihE-QVrANTlj)

**Comment by amit-webkul** [comment]
This Filter option is moved in slide bar. Now issue is not occurring.
You can check [Here](https://prnt.sc/5Iq0JLXIjbD1)
