### ISSUE TITLE
If the navigation collapse, customer icon is getting small in the overall details on the admin panel.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8071]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

While trying to collapse the navigation bar, the customer icon is getting smaller according to others in the overall icon on the admin panel. 

### Preconditions

1. Admin should be logged in.
2. The Admin should collapse the navigation bar.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'collapse'
3. See the error

### Expected Result

It should be the same according to another icon in the overall details.

### Actual Result

Getting small according to others. [Here](https://prnt.sc/6NxsrLBAonqG)

**Comment by amit-webkul** [comment]
This issue is fixed on our beta release.
You can check [Here](https://prnt.sc/diV2P9EzIAYa)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/FNR2jGl3y-Xn), for future reference.
