### ISSUE TITLE
Getting an error while installing the Bagisto v2.x with single command

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8075]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

It is showing service provider issues while installing.

### Preconditions

1. The project should be cloned.

### Steps to reproduce

1. Composer install
2. Configure .env file
3. Run the Bagisto installation command

### Expected Result

It should not be shown an exception while installing

### Actual Result

Getting exception of providers. [Here](https://prnt.sc/XWIGMaG_Uspl)

**Comment by amit-webkul** [comment]
This issue is now fixed in this [PR](https://github.com/bagisto/bagisto/pull/8145).

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
