### ISSUE TITLE
If there is no content in the stock threshold so it is not showing simulation.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8077]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

In the admin panel, on the dashboard, if there are no products it is not showing simulation in the stock threshold.

### Preconditions

1. Admin should be logged in.
2. Admin should not any products.

### Steps to reproduce

1. Go to 'Admin panel'
2. Scroll down to 'Stock Threshold'
3. See error

### Expected Result

It should be shown simulation.

### Actual Result

It is showing blank.[Here](https://prnt.sc/H5iTiAdICE7_)

**Comment by amit-webkul** [comment]
This Filter option is moved in slide bar. Now issue is not occurring.
You can check [Here](https://prnt.sc/5Iq0JLXIjbD1)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Fixed

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Fixed

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/6RJFe00qcoIv), for future reference.
