### ISSUE TITLE
Not able to save cms pages

### ISSUE THREAD

**Issue by mayank-webkul** [bagisto/bagisto#8152]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

Not being able to save CMS pages because the content field is required even if I field some content 

### Preconditions

local environment

### Steps to reproduce

1. Go to 'admin'
2. Click on 'cms'
3. Try to update any page

### Expected Result

Should be able to save the page

### Actual Result

Not able to save the page

### Screenshots

https://prnt.sc/FiQxVK6WwFNj

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/yisvGejA5eNJ), for future reference.
