### ISSUE TITLE
Translation Issue 

### ISSUE THREAD

**Issue by mayank-webkul** [bagisto/bagisto#8155]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

Translation issue in configuration

### Preconditions

Local environment

### Steps to reproduce

1. Go to 'Configuration'
2. Click on 'content'

### Expected Result

Translation should appear

### Actual Result

Translation not working

### Screenshots

https://prnt.sc/4GMGayFuY6nC

**Comment by amit-webkul** [comment]
Fixed

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/9AlFdEuiYV9N), for future reference.
