### ISSUE TITLE
Unable to edit User in admin panel

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/bagisto#8158]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

Want to edit the User in the admin panel but getting exception

### Preconditions

User should be LoggedIn

### Steps to reproduce

1. Goto Admin panel -> Settings -> Users 
 2. Now edit the user and Status disable then click on save button, but getting exception in console.

### Expected Result

User should be editted from admin panel

### Actual Result

Getting exception in console

### Screenshots

![Screenshot from 2023-09-06 11-00-47](https://github.com/bagisto/bagisto/assets/126852181/30be7fb2-9620-400b-a2fe-d5caf2c672c4)

**Comment by shivendra-webkul** [comment]
@mukulsharma-webkul not able to get issue please check

https://github.com/bagisto/bagisto/assets/121868701/fc0da3c7-f068-4eb1-a0d5-46366aab1498

**Comment by mukulsharma-webkul** [comment]
@shivendra-webkul , in the edit user page -> Status enable/disable button is there, 
-> If we disable the Status toggle button then the user is unable to edit.
**Video -**
https://webkul.chatwhizz.com/share/view-recording/64f81e8ded7413059a8452d9

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/M4zahrMA_yP7), for future reference.
