### ISSUE TITLE
Unable to update default attribute from the admin panel

### ISSUE THREAD

**Issue by girjesh-webkul** [bagisto/bagisto#8160]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0-BETA-1

### Issue Description

Unable to update default attribute from the admin panel

### Preconditions

Environment-
- Bagisto Version - v2.0.0-BETA-1
- PHP Version - PHP 8.1.21 
- MySQL Version - 8.0.25

### Steps to reproduce

1. Go to admin login page fill in the login detail
2. Click on Attributes under Catalog from the left sidebar menu
3. Edit any of the default attributes from the list.

### Expected Result

Attribute edit form should be open properly and update accordingly

### Actual Result

![default-attribute-edit-issue](https://github.com/bagisto/bagisto/assets/107393206/7aff2809-b247-468b-800f-b25c2ccda0a5)

### Screenshots

![default-attribute-edit-issue](https://github.com/bagisto/bagisto/assets/107393206/397b1eaf-4f2e-4ddd-b14e-13139a053cd3)

**Comment by jitendra-webkul** [comment]
Fixed in #8202

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/1SaFsmqjjjMb), for future reference.
