### ISSUE TITLE
Not able to disable guest checkout

### ISSUE THREAD

**Issue by mayank-webkul** [bagisto/bagisto#8162]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

Not able to disable guest checkout in product configuration

### Preconditions

Local environment

### Steps to reproduce

1. Go to 'Configuration'
2. Click on 'product'
3. Disable guest checkout
4. Save the configuration
5. See an error

### Expected Result

Configuration should be update

### Actual Result

Not able to disable guest checkout

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/fkzGqE5Y59HW), for future reference.
