### ISSUE TITLE
Product filter should be working properly

### ISSUE THREAD

**Issue by girjesh-webkul** [bagisto/bagisto#8163]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0-BETA-1

### Issue Description

Product filter is not working with attribute family input in filter form

### Preconditions

Environment-
Bagisto Version - v2.0.0-BETA-1
PHP Version - PHP 8.1.21
MySQL Version - 8.0.25

### Steps to reproduce

1. Go to admin login page fill in the login detail
2. Click on Products under Catalog from the left sidebar menu
3. Click on filter icon above the product list and apply attribute family input

### Expected Result

Product should be filtered as per the applied inputs.

### Actual Result

Getting below error while applying attribute family input.

### Screenshots

![product-filter-issue](https://github.com/bagisto/bagisto/assets/107393206/8cc57bf3-1f2e-4e47-955f-282e430c934c)

![Product-filter-issue-1](https://github.com/bagisto/bagisto/assets/107393206/f1370e7e-9ac7-4f37-9163-3a83b2776858)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue fixed.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/c5PLVs3ZvJ3R), for future reference.
