### ISSUE TITLE
Loader has to be shown after clicking on place order button

### ISSUE THREAD

**Issue by mayank-webkul** [bagisto/bagisto#8164]
**Describe the bug**
The loader should appear when we click on the Place Order button. Because the customer does not know whether the button has been clicked or not, he may click the Place Order button multiple times.

**To Reproduce**
1. Go to the 'Home page'.
2. Add any product to the cart.
3. Visit the cart page.
4. Fill the address details.
5. Select the shipping method and payment method.
6. Click on the place order button.
7. See error

**Expected behavior**
A loader should appear after the first click to confirm the user until the order is placed successfully.

**Screenshots**
https://prnt.sc/5VaFreOKedSt

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/7o_XoNBBTUt-), for future reference.
