### ISSUE TITLE
Internal server error on console during fresh installation 

### ISSUE THREAD

**Issue by girjesh-webkul** [bagisto/bagisto#8165]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0-BETA-1

### Issue Description

Internal server error on console during fresh installation 

### Preconditions

Environment-

Bagisto Version - v2.0.0-BETA-1
PHP Version - PHP 8.1.21
MySQL Version - 8.0.25

### Steps to reproduce

1. Go to 'Home page' on frontend and check the console
2. Go to 'Dashboard' on backend and check the console
3. See error

### Expected Result

Console should be clean without any error after fresh installation

### Actual Result

Getting internal server error after bagisto fresh installation of Beta  v2.0.0-BETA-1 version

### Screenshots

![console-error-fresh-installation](https://github.com/bagisto/bagisto/assets/107393206/5d228412-6df4-47fb-acc7-8edf65300e57)
![admin-console](https://github.com/bagisto/bagisto/assets/107393206/ce3db50a-a78d-46e3-b183-56e5d622ecf9)

**Comment by amit-webkul** [comment]
This issue is fixed in this [PR](https://github.com/bagisto/bagisto/pull/8171)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/jA0mQxQPXHG4 ) [Admin](https://prnt.sc/TMW6tVlNxmBT), for future reference.
