### ISSUE TITLE
Chart not updating after date filter

### ISSUE THREAD

**Issue by mayank-webkul** [bagisto/bagisto#8166]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

The chart not updating after the date filter on the dashboard page.

### Preconditions

Local environment

### Steps to reproduce

1. Go to 'Dashboard'
2. Click on 'add date filter'
5. Note:- you have to complete at least one order successfully.

### Expected Result

Chart Should be updated according to the selected date range.

### Actual Result

The chart not updating after the date filter on the dashboard page.

### Screenshots

https://prnt.sc/PGIpwT89hKFT

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/HUIp0O7MtjO2), for future reference.
