### ISSUE TITLE
Unable to create new category due to validation issue from the backend admin panel

### ISSUE THREAD

**Issue by girjesh-webkul** [bagisto/bagisto#8167]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0-BETA-1

### Issue Description

Unable to create new category due to validation issue from the backend admin panel

### Preconditions

Environment-

Bagisto Version - v2.0.0-BETA-1
PHP Version - PHP 8.1.21
MySQL Version - 8.0.25

### Steps to reproduce

1. Go to admin dashboard by login admin credentials
2. Click on Categories menu option under Catalog 
3. Create new category

### Expected Result

Validation error should not come if the required field value added and it will saved

### Actual Result

![category-validation-issue](https://github.com/bagisto/bagisto/assets/107393206/719abd16-5f82-4dea-9f7e-d29439e44c3f)

**Comment by amit-webkul** [comment]
Fixed in this [PR](https://github.com/bagisto/bagisto/pull/8215)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/VbxSeM6MXY63), for future reference.
