### ISSUE TITLE
Catalog Rule validation issue

### ISSUE THREAD

**Issue by mayank-webkul** [bagisto/bagisto#8168]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

Not able to create a catalog rule due to invalid validation.

### Preconditions

Local environment

### Steps to reproduce

1. Go to 'Admin'
2. Click on 'Marketing'
3. Click on the Create catalog rule.
4. Fill the details.
5. Add any condition.
6. See an error

### Expected Result

Validation should be fixed currently it is only accepting decimal value.

### Actual Result

Not able to save catalog rule due to invalid validation.

### Screenshots

https://prnt.sc/EaWMCgOx7e69

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/UdqpaKeuBhov), for future reference.
