### ISSUE TITLE
Datagrid improvements and bugs

### ISSUE THREAD

**Issue by mayank-webkul** [bagisto/bagisto#8169]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

The date filter should be improved while filtering in the datagrid. 

### Preconditions

Local environment

### Steps to reproduce

1. Go to 'Admin'
2. Click on 'Order'
3. Filter data on the basis of date in descending order.

### Expected Result

When we filter on dates in descending order then order with the same timestamp should be in descending order on the basis of id.

### Actual Result

When I filter data in datagrid on date order by descending then the order with the same timestamp is not ordered in descending order.

### Screenshots

https://prnt.sc/3aITijC-2bSp

**Comment by amit-webkul** [comment]
This issue is an Invalid.

**Comment by Amitk-webkul** [comment]
It is working fine. [Here](https://prnt.sc/w-VIHkdOTV7u)
So closing this issue.
