### ISSUE TITLE
On the Admin dashboard, not getting data of total unpaid invoices.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8175]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0-BETA-1

### Issue Description

In the overall details, the orders are pending it is still showing blank. 

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one pending order.

### Steps to reproduce

1. Go to 'Admin panel'
2. See the 'total unpaid invoices'
3. See the error

### Expected Result

It should be shown the pending data.

### Actual Result

Not getting the data.

### Screenshots

https://prnt.sc/Os7cFJsUFoPn

**Comment by amit-webkul** [comment]
The functionality is only active for pending invoices. It will only operate when the invoice state is pending. Therefore, it is not an invalid issue.
I'm closing this issue for now.
