### ISSUE TITLE
In the Order history on the admin panel, Find an extra filter as image.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8178]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0-BETA-1

### Issue Description

In the Order History on the admin panel, Find an extra filter as an image. There is no need for an image filter.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'sales'
3. Click on the filter button
4. See the error

### Expected Result

No need to show an extra filter.

### Actual Result

It is showing an extra filter option.[Here](https://prnt.sc/8WK5t7t_J2Cq)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul issue Fixed.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/Q5Sm_bVJjpyK), for future reference.
