### ISSUE TITLE
Getting duplicate tax heading of the tax in the invoice on the Admin panel.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8188]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0-BETA-1

### Issue Description

On the admin panel, while creating the invoice of the order and viewing the invoice it is showing an extra tax option in the amount section.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one pending/shipped order.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'view order' inside Sales/orders
3. Create an invoice for this order
4. Scroll down to 'amount section'
5. See an error

### Expected Result

It should not be shown as extra text.

### Actual Result

it is showing a duplicate name. [Here](https://prnt.sc/6QIpEtiaucju)

**Comment by amit-webkul** [comment]
Fixed

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/RJGOdLu7ct7k), for future reference.
