### ISSUE TITLE
On the admin panel, getting duplicate email title name in the send duplicate invoice pop-up.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8190]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0-BETA-1

### Issue Description

On the admin panel, showing a duplicate name of the title while trying to send a duplicate email to the customer.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one created invoice of the order.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on the 'view invoice option' inside the Sales/invoice
3. Click on the send duplicate invoice option
4. See the error

### Expected Result

It should not be shown duplicate title.

### Actual Result

Getting duplicate title name.[Here](https://prnt.sc/Mfak6EWmquQq)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue fixed.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/oNXIqgwxnN7u), for future reference.
