### ISSUE TITLE
Getting translation issue in the Attribute.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8234]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While creating the Attribute with select or multi-select types and after that creating an option for that here enables the option to create the option as default. here is getting translation issues.

### Preconditions

1. Admin should be logged in.
2. Admin needs to create an attribute.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Create Attribute' inside the Catalog/Attributes
3. Select attribute types as select/multi-select
4. Add an attribute row
6. See the error

### Expected Result

It should be shown the proper option.

### Actual Result

getting translation issues. [Here](https://prnt.sc/1Lvplk9KDNXM)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue fixed in https://github.com/bagisto/bagisto/pull/8229

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/sp-ngeVJ4R7t), for future reference.
