### ISSUE TITLE
Getting image size and default image text issue in the variant product image.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8238]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While creating a configurable product and adding a variant image so getting an image size compress issue and also it is showing the no image default text (product image) on the variant image.

### Preconditions

1. Admin should be logged in.
2. Admin needs to create configurable products.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on the 'Create product button' inside the Catalog/products.
3. Select product type configurable and fill all required fields.
5. Scroll down to 'variant section'
6. Add images in the variant
7. See the error

### Expected Result

It should compress the image and should not show the text on the product image if the image is added.

### Actual Result

It shows product image text on the image. [Here](https://prnt.sc/rBHRJ6HURU-l)

**Comment by jitendra-webkul** [comment]
Fixed in #8237

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/CZIyP4b-wbVp), for future reference.
