### ISSUE TITLE
Configurable parent product quantity status showing out of stock

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8242]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

For the configurable products variant products have stocks still it is showing out of stock for the parent products.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one configurable create product.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Products' inside the Catalog
3. See the error

### Expected Result

Here it should be shown as zero. or should be hidden. 

### Actual Result

It is showing out-of-stock status. [Here](https://prnt.sc/-reQ8IqL085G)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue Fixed

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/QJ3-5FsN0Ivc), for future reference.
