### ISSUE TITLE
Cancel order by Admin notification is not showing properly.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8244]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the admin panel, while canceling the order. In the notification, it is showing the translation issue.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one placed order.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'sales'
3. Edit the order and Click on the cancel button
5. See the error

### Expected Result

It should be shown notification message properly.

### Actual Result

Showing translation issue. [Here](https://prnt.sc/jJXU3eW5wKXp)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue fixed.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/VIxeJCcWkK9U), for future reference.
