### ISSUE TITLE
While creating a customer from the admin panel, it shows a duplicate customer group select option.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8247]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While creating a customer from the admin panel, it shows a duplicate customer group select option.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Create customer' inside the customers
4. See the error

### Expected Result

It should be shown single option.

### Actual Result

It shows the customer group select option twice. [Here](https://prnt.sc/EkRsDx_D4juX)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue Fixed.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/t8lg6B_ryQxj), for future reference.
