### ISSUE TITLE
unable to update ( is_filterable ) in attributes

### ISSUE THREAD

**Issue by develalfy** [bagisto/bagisto#825]
I'm trying to update an attribute **Use in Layered Navigation** but it will always be 0

Note:- I think the problem is here 
`if (! in_array($data['type'], ['select', 'multiselect', 'price'])) {
            $data['is_filterable'] = 0;
    }`

> \Webkul\Attribute\Repositories\AttributeRepository::validateUserInput

**Comment by rahulshukla-webkul** [comment]
Hi @develalfy 

Only select, multi select & price attribute can be used in Layered Navigation, so only value of these attribute type can be updated ( $data['is_filterable] =1 or Use in Layered Navigation ). Rest type of attribute can't used in layered navigation so there value can' update.(Use in Layered Navigation).
