### ISSUE TITLE
The Phone input field is not a required field in the customer create/edit form.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8251]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

The Phone input field is not a required field in the customer create/edit form.

Note:- Fix the same for the **Shop**.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on 'Create customer' inside the Customers/customer
3. See the error

### Expected Result

The field should not be required.

### Actual Result

The field is not required. [Here](https://prnt.sc/STOyeXi1rQKN)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue fixed.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/W85jMtIFERdk), for future reference.
