### ISSUE TITLE
Not working autogenerated coupons funtionality in the cart rule.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8254]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While trying to generate coupons it is not generating showing the undefined alert.

### Preconditions

1. Admin should be logged in.
2. Admin needs to create a cart rule.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Cart rule' inside the Marketing/promotion
3. Click on the Create Cart rule
4. Fill in all the required fields and select yes in Automatic generate coupon
5. In the coupon code set the quantity and prefix/suffix
6. Click on the generate option
7. See the error

### Expected Result

It should generate coupons and show the coupon listing.

### Actual Result

it is showing the undefied alert message. [Here](https://prnt.sc/3O1h-webtaMO)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue Fixed

**Comment by Amitk-webkul** [comment]
@shivendra-webkul  While using the filters and sorting it is automatically loading to save and redirected to the listing page. [Here](https://jam.dev/c/4c0cd7bd-1330-4d7e-bd0f-9865d3293085)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue fixed

**Comment by Amitk-webkul** [comment]
@shivendra-webkul the page is still loading on filters. [Reference](https://jam.dev/c/3cb3d068-996b-46d5-be3c-3c03861aef2b)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/FPt_LYCnVrCS), for future reference.
