### ISSUE TITLE
Impossible to create the root directory "".

### ISSUE THREAD

**Issue by yaser-alazem** [bagisto/bagisto#826]
This error message appeared for me two times, 
First after adding the product category, the second one after adding a product and hit save on this route (/admin/catalog/products/edit/1), however the category and the product seem to be added successfully even after this error.

I'm working on Ubuntu 18.04 for the last version of composer and Bagisto, not sure if it's a bug or there is something wrong with my basic installation of the packages.
Already update the composer dependencies.

**Update**: it seems to be a problem whenever I try to upload an image to the application whether it is a product or a category.

![Screenshot from 2019-04-15 20-32-52](https://user-images.githubusercontent.com/10104954/56152923-b0baca80-5fbd-11e9-8538-a3b5b8930001.png)
------------
**Environment & details**:

`

channel | "default"
-- | --
locale | "en"
_token | "RLXafVNeXfQygz20IK4jKFEmchuJfQZSH8eNyx6s"
_method | "PUT"
sku | "34127864523467"
name | "Men Navy Stripped T-Shirt"
url_key | "men-navy-stripped-tshirt"
tax_category_id | ""
new | "1"
featured | "0"
visible_individually | "1"
status | "1"
Wash_Care | "Machine-wash"
short_description | "<p>This is a short sleevs tshirt with rounded neck.</p>"
description | "<p>A men t-shrit most suitable for medern youth style.</p>"
meta_title | ""
meta_keywords | ""
meta_description | ""
price | "300"
special_price | "0"
special_price_from | ""
special_price_to | ""
weight | "20"
inventories | array:1 [▶]
images | array:3 [▶]
categories | array:1 [▶]

`

**Comment by jitendra-webkul** [comment]
Problem is, the "storage/app/public" directory is a symlink to the directory that does not exist anymore. That's why you are getting this error. Please follow the following points to resolve this issue:

1: Remove existing symlink:
`cd storage/app/public`

`unlink public`

2: From the project's root directory run the following command:

`php artisan storage:link`

**Comment by jyoti-webkul** [comment]
Fixed

**Comment by javoke96** [comment]
Experiencing same problem, white trying to upload an image. Never touched bagisto modules.
Also, unlinking and linking back public folder doesn't work.

**Comment by rahulshukla-webkul** [comment]
Hi @javoke96 

run - 
chown -R www-data:root .

in the root of directory.

**Comment by javoke96** [comment]
Thanks @rahulshukla-webkul, `$chown -R www-data:root .` didn't work as well as `$chmod -R 777 ./storage $chown -R www-data:root .` I'm running it on Mac 10.14.5; Composer version 1.8.5; laravel 5.6.39.  Any suggestions?

**Comment by BSalwiczek** [comment]
> Thanks @rahulshukla-webkul, `$chown -R www-data:root .` didn't work as well as `$chmod -R 777 ./storage $chown -R www-data:root .` I'm running it on Mac 10.14.5; Composer version 1.8.5; laravel 5.6.39. Any suggestions?

Having the same problem on linux

**Comment by y-ates** [comment]
The following fixed it for me:

1. _shutdown artisan_
2. cd storage/app/
3. unlink public
4. _startup artisan_

When running `php artisan storage:link`, it recreates the public directory as a symlink, which is pointing to itself. 
Not running `php artisan storage:link` won't create a symlink and fixes it (at least for me)

**Comment by richard457** [comment]
this is not solved.

**Comment by alkhachatryan** [comment]
> The following fixed it for me:
> 
> 1. _shutdown artisan_
> 2. cd storage/app/
> 3. unlink public
> 4. _startup artisan_
> 
> When running `php artisan storage:link`, it recreates the public directory as a symlink, which is pointing to itself.
> **Not running** `php artisan storage:link` won't create a symlink and fixes it (at least for me)

Strange, but it worked..

**Comment by MothanaDo** [comment]
> The following fixed it for me:
> 
> 1. _shutdown artisan_
> 2. cd storage/app/
> 3. unlink public
> 4. _startup artisan_
> 
> When running `php artisan storage:link`, it recreates the public directory as a symlink, which is pointing to itself.
> **Not running** `php artisan storage:link` won't create a symlink and fixes it (at least for me)

still not working

**Comment by y-ates** [comment]
> still not working

Did you skip `php artisan storage:link`?

**Comment by MothanaDo** [comment]
> > still not working
> 
> Did you skip `php artisan storage:link`?

ya , i make  php artisan storage:link , but the error still apper

**Comment by y-ates** [comment]
> > > still not working
> > 
> > 
> > Did you skip `php artisan storage:link`?
> 
> ya , i make php artisan storage:link , but the error still apper

You have to skip it:

1. shutdown artisan
2. cd storage/app/
3. unlink public
4. startup artisan

as stated above.

**Comment by MothanaDo** [comment]
shutdown artisan , startup artisan   whats mean ?

**Comment by MothanaDo** [comment]
when i call  'shutdown artisan"   the result is  : Failed to parse time specification: artisan

**Comment by MothanaDo** [comment]
> 3\. unlink public

great , it's work with error  when i'm try to add image .

but the image not apper ??

![Capture](https://user-images.githubusercontent.com/46019924/78166995-5fb61780-7456-11ea-8ce2-b7d3b27fba25.PNG)

**Comment by haratmalli** [comment]
First delete the PUBLIC folder/file from root/storage/app/ then delete STORAGE folder under root/publc, then first create PUBLIC folder in root/storage/app and then hit `php artisan storage:link`. All done. enjoy

**Comment by niraj-lal-rahi** [comment]
I am getting the same error and tried all the solutions mentioned here : 
Please have a look into the error : 

Thanks 

![Screenshot from 2021-01-18 23-32-16](https://user-images.githubusercontent.com/31951794/104949779-82b1b800-59e5-11eb-98db-5792a274d0b7.png)

**Comment by niraj-lal-rahi** [comment]
This worked for me:

cd public
unlink storage
php artisan storage:link

**Comment by ghermans** [comment]
First remove these folders
```
/public/storage
/storage/app/public
```
Then run the following command
```
php artisan storage:link
```

**Comment by Ajibolarilwan14** [comment]
> The following fixed it for me:
> 
> 1. _shutdown artisan_
> 2. cd storage/app/
> 3. unlink public
> 4. _startup artisan_
> 
> When running `php artisan storage:link`, it recreates the public directory as a symlink, which is pointing to itself. **Not running** `php artisan storage:link` won't create a symlink and fixes it (at least for me)

OMG!!! this looks like a magic but it works :)

**Comment by media1984** [comment]
I deleted it under mac system
storage/app/public
The public file can run normally.
