### ISSUE TITLE
The status filter is not working on the category listing page on the admin panel.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8263]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While trying to filter the category with status, but not able to filter it is showing no records available.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least two or more categories.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Category' inside the Catalog
3. Filter with inactive
4. See the error

### Expected Result

It should work according to status.

### Actual Result

For all statuses, it is showing no records found. [Here](https://prnt.sc/4fzHFPw3M7Dl)

**Comment by jitendra-webkul** [comment]
It's a boolean column, try to pass 0 and 1. Will add a dropdown in future where you can choose the option.

**Comment by ramkishansuthar** [comment]
@Amitk-webkul  It seems like you are trying filter with keyword "Active" or "Inactive" as Jitendra said try with boolean value. One possible solution is to make search filter as dropdown where you can select active or inactive filter.

Thanks

**Comment by ramkishansuthar** [comment]
Please assign this issue to me @Amitk-webkul

**Comment by Amitk-webkul** [comment]
this issue has already been implemented. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/FmapPJu3G8LZ), for future reference.
