### ISSUE TITLE
Not showing product video on the product page on the shop.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8268]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If the video is added to the product, and trying to play view it is showing blank on the product page.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one created product with added video.

### Steps to reproduce

1. Go to 'Shop'
2. Click on 'that product'
3. Hover to video
4. See the error

### Expected Result

Should be played video.

### Actual Result

Showing blank page instead of playing video. [Here](https://prnt.sc/s_YSPKHbgww4)

**Comment by SanjuDeveloper** [comment]
Hi @Amitk-webkul 
This issue is already opened and fixed previously
Can you please check once??

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/obhp4wJWkxqn), for future reference.
