### ISSUE TITLE
On the Shop, Sample is not added still it is showing the option to download sample in the downlaodable product.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8270]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If there are no samples added for the downloadable product. still, it shows the sample option on the product page of the shop.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one downloadable product.

### Steps to reproduce

1. Go to 'Shop'
2. Click on 'view Downloadable product'
4. See the error

### Expected Result

It should be shown only if the sample is added.

### Actual Result

It is showing a sample option and while clicking on the sample it is showing 404 pages not found. [Here](https://prnt.sc/5QXmJ-wVQ7ri)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue Fixed

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/DWoAMbpnsj4H), for future reference.
