### ISSUE TITLE
Not showing category image on the homepage.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8272]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

category images are added from the admin panel, While trying to view categories on the shop here images are not visible.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one category.

### Steps to reproduce

1. Go to the 'Hompage'
2. Scroll down to 'category'
3. See error

### Expected Result

It should be shown category images.

### Actual Result

Not showing images. [Here](https://prnt.sc/qYlM_FdkPQS5)

**Comment by amit-webkul** [comment]
Fixed in this [PR](https://github.com/bagisto/bagisto/pull/8280)

**Comment by suraj-webkul** [comment]
already fixed with this PR https://github.com/bagisto/bagisto/pull/8280

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/60mfftpf5cFp), for future reference.
