### ISSUE TITLE
Root category is visible in the category carousel on the homepage.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8273]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

The root category is visible on the Category list. it should not be shown in the root directory in the category carousel.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to the 'Homepage'
2. Scroll down to 'category carousel'
3. See the error

### Expected Result

should not be shown the root category.

### Actual Result

It is showing the root category. [Here](https://prnt.sc/lDxBrYoS9lIk)

**Comment by suraj-webkul** [comment]
this is not bug it can be handle theme customization using filter but image of category not visible it is fix now.

**Comment by Amitk-webkul** [comment]
We can manage the root directory from the theme customization using the filter in the Admin panel. [Here](https://prnt.sc/nMHqvy35VgT8)
So I'm closing this issue.
