### ISSUE TITLE
Validate the review attachment with image extensions only.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8277]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

In the review, attachments should accept only images, like image extensions only(.jpeg, .jpg, .png).

### Preconditions

1. Admin should have at least one product.

### Steps to reproduce

1. Go to the 'Homepage'
2. Click on the 'Product'
3. Scroll down to 'review'
4. Add an attachment with a video.
5. See the error

### Expected Result

It should accept only images.

### Actual Result

It is accepting all but showing the broken images in the admin panel. [Here](https://prnt.sc/AkxnmC3fRKZp)

**Comment by amit-webkul** [comment]
It is now also accepting videos in the product reviews section.

**Comment by Amitk-webkul** [comment]
Now videos can be added to the reviews so I'm closing this issue.
