### ISSUE TITLE
Not working delete attachment option while customer giving review.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8278]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

When customers try to give reviews and add other attachments and then want to delete the attachment but are not able to delete the delete option is not working.

### Preconditions

1. Admin should have at least one product.

### Steps to reproduce

1. Go to the 'Shop'
2. Click on view 'Product'
3. Scroll down to 'Review'
4. Add an attachment
5. Delete the attachment
6. See the error

### Expected Result

It should be deleted from the attachment.

### Actual Result

Not deleting the attachment. [Here](https://prnt.sc/rcgFptsZTt-A)

**Comment by amit-webkul** [comment]
Fixed In this [PR](https://github.com/bagisto/bagisto/pull/8294)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
