### ISSUE TITLE
On the shop in the category page, filters are not working.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8292]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the shop in the category page, filters are not working.

### Preconditions

1. Admin should have at least one category.
2. Admin should have two or more products in the category.

### Steps to reproduce

1. Go to 'Shop'
2. Click on the 'Category'
3. Apply filters
4. See the error

### Expected Result

Filters should work accordingly.

### Actual Result

Not showing product not found if any filter is applied. [Here](https://prnt.sc/Xm_GISbDiEMA)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Filters are working properly.

**Comment by jitendra-webkul** [comment]
All options should available in the product
