### ISSUE TITLE
While editing the Admin user, it shows the Confirm Password not matching notification.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8314]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While editing the Admin user, it shows the Confirm Password not matching notification. it should not be shown the message. confirm password mismatch or field is required message should be shown while entering the password.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one user.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Edit User' inside the Settings/User
3. Make some changes in the form and click on the save button
4. See the error

### Expected Result

It should not be shown the required message. the message should be shown while the password is entered.

### Actual Result

But Not able to edit the user due to the password confirmation message. [Here](https://prnt.sc/1HHtYcwuvLDS)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Issue Fixed

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/pu0uzs2XMc_i), for future reference.
