### ISSUE TITLE
While admin user trying to delete him/herself, getting an error in the console.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8320]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While the admin user trying to delete him/herself, getting an error in the console.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one user.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on the 'Delete button' inside the Settings/Users
3. Open the console
4. See the error

### Expected Result

The admin should be able to delete him/herself.

### Actual Result

Showing an error in the console. [Here](https://jam.dev/c/fc156184-f1f0-4d03-a481-53eb40c052a9)

**Comment by amit-webkul** [comment]
Already Fixed in this [PR](https://github.com/bagisto/bagisto/pull/8333)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/H2IosJjkhvJQ), for future reference.
