### ISSUE TITLE
catalog rule multiple products

### ISSUE THREAD

**Issue by althafn96** [bagisto/bagisto#8337]
adding multiple skus for a catalog rule doesn't work.

![image](https://github.com/bagisto/bagisto/assets/27689786/1b5d926d-fbd0-4f3c-8777-235306ce13d9)

Is there any other way I could add multiple products (selected products), for a catalog rule?

**Comment by jitendra-webkul** [comment]
You can create a custom select attribute with options (Ex. 0%, 10%, 20%, 30%), and set these values to selected products. And then add this attribute to the condition.

**Comment by althafn96** [comment]
will you be working on adding multiple sku to work? or is this gonna be the only solution?
