### ISSUE TITLE
Performance - Product Editor

### ISSUE THREAD

**Issue by caesarcxiv** [bagisto/bagisto#834]
![image](https://user-images.githubusercontent.com/13050060/56245517-9a6c4780-606d-11e9-97fe-9183d0f2d03a.png)

16k queries

/admin/catalog/products/edit/

**Comment by ludioao** [comment]
Same issue here. Sometimes the server goes down.

**Comment by jitendra-webkul** [comment]
Hi @caesarcxiv ,

We are working on the optimization of the product edit page. By this week, changes will be complete.

Thanks for your suggestion.

**Comment by jitendra-webkul** [comment]
Hi @caesarcxiv,

We have optimized the product edit page. Thanks for your suggestion, really appreciated.

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Fixed
