### ISSUE TITLE
Getting issues in the customer image on the edit profile page.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8341]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

1.  The required field border size should be exact to the attachment field.
2. Not getting proper add profile image message.

### Preconditions

1. Admin should have at least one registered customer.

### Steps to reproduce

1. Log in as 'Customer'
2. Click on 'edit profile'
3. Scroll down to 'save profile button'
4. Click on the save button 
5. See the error

### Expected Result

it should show the proper message and the size required should be exact to the attachment field.

### Actual Result

not showing the exact size and message. [Here](https://prnt.sc/h9ltnaq5PiEF)

**Comment by Amitk-webkul** [comment]
@shivendra-webkul Getting an exception while updating a profile without a profile image. [Here](https://prnt.sc/6Wnx3rrt64ls)

**Comment by shivendra-webkul** [comment]
Fixed in PR https://github.com/bagisto/bagisto/pull/8441

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/wXz9kEEQVMA1), for future reference.
