### ISSUE TITLE
Date of Birth field is missing in the customer edit profile form.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8343]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

in the profile detail, the date of birth option is available but while editing the profile there is no option to update/add D.O.B.

### Preconditions

1. Customer should be logged in.

### Steps to reproduce

1. Go to 'Shop'
2. Click on 'Edit profile'
3. See the error

### Expected Result

there should be an option to add the Date of Birth.

### Actual Result

Not able to update D.O.B. [Here](https://prnt.sc/5w3Uqck_bhSV)

**Comment by Amitk-webkul** [comment]
@shivendra-webkul the Calender is added. but update the calendar the same as the [Admin panel](https://prnt.sc/pI1kd3Qir_3d).  [Here](https://prnt.sc/OlNHNd533Hmk)

**Comment by jitendra-webkul** [comment]
Indeed, it's a third-party extension, and unfortunately, we don't have the ability to modify its CSS.
