### ISSUE TITLE
Parent Products show instock when all children have quantity 0

### ISSUE THREAD

**Issue by caesarcxiv** [bagisto/bagisto#835]
![image](https://user-images.githubusercontent.com/13050060/56252392-9f3cf580-6085-11e9-8ac6-0bdfeaa4841d.png)

Parent item appears as instock with add to cart button. No selectors are available.

**Comment by rahulshukla-webkul** [comment]
Hi @caesarcxiv 

Thanks for raising issue. We will solve it soon & update you.

**Comment by rahulshukla-webkul** [comment]
Hi @caesarcxiv 

We have fixed this issue, you can take pull from our master branch.

**Comment by jyoti-webkul** [comment]
Product not showing Out of stock

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Fixed
