### ISSUE TITLE
Not able to delete category.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8378]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While trying to delete the category but not able to delete showing notification.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one category.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'delete category' inside the catalog/category
4. See the error

### Expected Result

Should be able to delete the category.

### Actual Result

getting notifications but not able to delete them. [Here](https://prnt.sc/7qykG1wXZH-j)

**Comment by jitendra-webkul** [comment]
The issue isn't with deletion; it's related to translation. If a category serves as a channel's root category, it cannot be deleted.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/h0VC3Aj1bGqT), for future reference.
