### ISSUE TITLE
Packages as composer dependency

### ISSUE THREAD

**Issue by ludioao** [bagisto/bagisto#838]
Hey there, are this feature on the roadmap? We might use the packages as a composer dependency, then we can offer better support and mantain our projects

**Comment by jitendra-webkul** [comment]
Hi @ludioao ,

In the next release, Bagisto will be installed as composer dependency. We plan to create one more project called bagisto-standard, which will install https://github.com/bagisto/bagisto as composer dependency so that customer can easily update to the new version.

**Comment by ludioao** [comment]
Cool! I'll wait :)

**Comment by dahabit** [comment]
@jitendra-webkul is there is an estimated time for doing that?

**Comment by laurenwilliams92** [comment]
Is there a timeline for when this will be released?

Currently maintaining our project by updating files from zip is not ideal or maintainable long term.

**Comment by prashant-webkul** [comment]
@laurenwilliams92 On being towards more optimistic side we are developing our own Composer installer and it is in works.

**Comment by jitendra-webkul** [comment]
Hi @ludioao 

Please check the following repository

https://github.com/bagisto/bagisto-standard
