### ISSUE TITLE
Getting an error in the console on the payment method page in the Admin panel.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8390]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Getting an error in the console on the payment method page in the Admin panel. also get the same while clicking on the save configuration button.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Payment method' inside the configuration/sales
3. Open the console
4. See the error

### Expected Result

It should not be shown error in the console.

### Actual Result

getting errors in the console. [Here](https://prnt.sc/ZBizjRlNg5PB)

**Comment by Amitk-webkul** [comment]
@suraj-webkul The issue is still there. [Here](https://prnt.sc/qexpI5OqV3P6)

**Comment by suraj-webkul** [comment]
This already fixed need to run devlopment server.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/WPhsJILPHTzr), for future reference.
