### ISSUE TITLE
search is not working after latest release

### ISSUE THREAD

**Issue by tousifhasanzai** [bagisto/bagisto#840]
Hi,
in shop route previously it was
  ```
Route::get('/', 'Webkul\Shop\Http\Controllers\HomeController@index')->defaults('_config', [
        'view' => 'shop::home.index'
    ])->name('shop.home.index');
```
that was working now it is replaced with 
```
Route::get('/{any?}', 'Webkul\Shop\Http\Controllers\HomeController@index')->defaults('_config', [
        'view' => 'shop::home.index'
    ])->name('shop.home.index');
```
which is throwing 404

**Comment by jitendra-webkul** [comment]
Hi @tousifhasanzai ,

The issue has been fixed, please check again. 

Thanks for pointing out the issue.

**Comment by tousifhasanzai** [comment]
alot more mess happens, gallery images are not showing except primary image. product description is not showing css issue

**Comment by jitendra-webkul** [comment]
> alot more mess happens, gallery images are not showing except primary image. product description is not showing css issue
> ![Screenshot (2)](https://user-images.githubusercontent.com/18395540/56387377-92fb9880-623d-11e9-9c2f-91ef7425a6b8.png)

Please check the product description that you have saved during the product create/edit. I think you, you saved invalid HTML in the product description.

**Comment by jitendra-webkul** [comment]
FYI, we did not release the new version yet. You are trying from our master branch.

**Comment by jyoti-webkul** [comment]
Framework Version:0.1.5
Fixed
