### ISSUE TITLE
Getting an exception on the shop while replacing the sort order of image carousel and static conent (Offer Information). 

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8414]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Getting an exception on the shop while replacing the sort order of image carousel and static content (Offer Information) from the admin panel. 

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Theme' inside the Settings
3. Replace the sort order of image carousel and static content (Offer Information) and save it.
4. Go to the 'Shop'
5. See the error

### Expected Result

It should be shown the content according to sort order instead of exception.

### Actual Result

Getting an exception. [Here](https://prnt.sc/wzI57MhBrTfq) [Shop](https://prnt.sc/aMDBpOGOwo9d)

**Comment by suraj-webkul** [comment]
This is fixed in this [PR](https://github.com/bagisto/bagisto/pull/8387)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/j48NSxaeMVib), for future reference.
