### ISSUE TITLE
Create/Edit category, product mode is set to product only, the description is still required.

### ISSUE THREAD

**Issue by AmooAti** [bagisto/bagisto#8426]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Hi,
Fantastic work on the fresh design!
While creating a category, the description is still required when the product mode is set to product only.

### Preconditions

1. Admin must be logged in.

### Steps to reproduce

1. Go to category grid.
2. Click on Create button to create a new category.
3. From the Settings section in right column, change _Display Mode_ to _Products Only_

### Expected Result

The product description field should no longer be required.

### Actual Result

The product description field is still required.

### Screenshots

![Screenshot from 2023-09-19 13-21-29](https://github.com/bagisto/bagisto/assets/36756531/ad58ed08-c301-49bd-aa60-e5f6886ae25c)

**Comment by Amitk-webkul** [comment]
@AmooAti Thank you for the update.
