### ISSUE TITLE
The add slider should be clickable in the image carousel on the admin panel.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8447]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If there is no link in the default simulation the add button should be clickable. The add slider should be clickable in the image carousel on the admin panel.

### Preconditions

1. Admin should be logged in.
2. Delete all the default sliders in the image carousel.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Edit image carousel' inside the settings
3. Delete all the sliders
4. Click on the add slider button
5. See the error

### Expected Result

It should be clickable and should open the add slider pop-up.

### Actual Result

it is not clickable. [Here](https://prnt.sc/tj_wLlrWCRKR)

**Comment by shivendra-webkul** [comment]
Already fixed in PR https://github.com/bagisto/bagisto/pull/8441

**Comment by Amitk-webkul** [comment]
Now, the button is removed because a single button will appear. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/taJjoEblMARW), for future reference.
