### ISSUE TITLE
Product copy is a extra field to manage permission.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8479]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Product copy is an extra field in the user role. for now, in Bagisto 2.0 we are not providing product copy features.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'add/edit role' inside the settings/role
3. Scroll down to 'Product permission'
4. See the error

### Expected Result

it should not be shown.

### Actual Result

it is still showing. [Here](https://prnt.sc/V6gn8B6oIWYA)

**Comment by jitendra-webkul** [comment]
We will implement a copy feature.

**Comment by Amitk-webkul** [comment]
This is not an issue because the feature will be implemented. so I am closing this issue.
