### ISSUE TITLE
On the locale page in the Admin panel, the table headings show in the column.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8482]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the locale page in the Admin panel, the table headings show in the column.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Settings'
4. See the error

### Expected Result

It should show the table heading in a row according to the data grid.

### Actual Result

It shows the table heading in the column. [Here](https://prnt.sc/8UOvFgDblBgy)

**Comment by amit-webkul** [comment]
FIxed in this [PR](https://github.com/bagisto/bagisto/pull/8486)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/-QZ-jxbhAFC1), for future reference.
