### ISSUE TITLE
Getting error while changing admin locale from env file.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8485]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While trying to change the admin local from the env file. so it is showing a blank screen and has errors in the console.

### Preconditions

1. Admin should be logged in.
2. Admin should have two or more locales.

### Steps to reproduce

1. Go to the project root directory 
2. Edit .env file
3. Change locale en to nl and save it
4. Go to the Admin panel
5. See the error

### Expected Result

it should change the admin locale according to the set locale from the env file.

### Actual Result

it is showing a blank screen and has errors in the console. [Here](https://prnt.sc/I5Hoh4TMQX3o)

**Comment by Amitk-webkul** [comment]
@suraj-webkul, On the review page, it is still showing the same issue. [Here](https://prnt.sc/ll4Fu64P7PFF)

**Comment by amit-webkul** [comment]
@Amitk-webkul This is Fixed in this [PR](https://github.com/bagisto/bagisto/pull/8564)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/vFtGXgT3Dw3p), for future reference.
