### ISSUE TITLE
issue while selecting quantity more than 1 on buy now

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#850]
on the product page, there should be an **increase-decrease** option for **quantity** so that user can select a quantity and click on buy now, so it will be redirected on shipping page with selected quantity!!!!!

**Comment by prashant-webkul** [comment]
This is a duplicate of already closed issue https://github.com/bagisto/bagisto/issues/197

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Not fixed

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.5

Fixed

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

------------------------------------------
Again getting this issue

**Comment by bhanu-webkul** [comment]
Framework Version: 0.1.6

Still same issue

**Comment by bhanu-webkul** [comment]
Framework Version: 0.1.8

issue fixed
