### ISSUE TITLE
Description required validation error when creating category

### ISSUE THREAD

**Issue by ArthurHetem** [bagisto/bagisto#8508]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0-BETA-1

### Issue Description

When creating a new category, there is a validation error, the field is filed but when the user tries to create the category, it shows the validation like if the field was blank

### Preconditions

Just installed 2.0.0-BETA1 and tried to create a new category

### Steps to reproduce

1. Go to Catalog
2. Go to Categories
3. Click on Create Category
4. Fill the required fields
5. try to create and see the validation error

### Expected Result

The Category should be create when the required fields are filled

### Actual Result

![image](https://github.com/bagisto/bagisto/assets/7545272/97266f11-aff9-490f-bdb4-c8af9a4d0fd3)

**Comment by ArthurHetem** [comment]
This is happening for all pages that use tinymce

**Comment by Amitk-webkul** [comment]
Hello @ArthurHetem,

The [issue](https://github.com/bagisto/bagisto/issues/8167) is already fixed. please take a pull from the master branch.

**Comment by Amitk-webkul** [comment]
Hello @ArthurHetem,

I hope you found your solution. so I am closing this issue.
