### ISSUE TITLE
Getting exception on admin dashboard

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#851]
Framework Version: 0.1.5
![Screenshot from 2019-04-18 19-01-05](https://user-images.githubusercontent.com/45203177/56364507-56637900-620c-11e9-9f9a-2666e77ba41c.png)

**Comment by salahat** [comment]
I've the same issue

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Fixed
