### ISSUE TITLE
Add to create a configurable product option in the attribute creation form is not working on the edit attribute page. 

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8520]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Add to create a configurable product option in the attribute creation form is not working on the edit attribute page. 

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one attribute for configurable products.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Create an attribute' inside the Catalog/Attribute.
3. Fill in all the required fields select Create a configurable product option and save it  
4. Open the same attribute and save it again.
5. Reopen the same attribute
8. See the error

### Expected Result

It should be saved in the selected checkbox.

### Actual Result

it does not save the selected checkbox. [Here](https://jam.dev/c/54ee7db4-4e15-4c96-990c-50d0cec563de)

**Comment by ramkishansuthar** [comment]
Hi @Amitk-webkul 

Please assign this issue to me. 

Thanks

**Comment by saurav-webkul** [comment]
I have assigned to you @ramkishansuthar
