### ISSUE TITLE
Install Error: Extension Error: The validator 'default' must be a function. 

### ISSUE THREAD

**Issue by vaix-dungpx** [bagisto/bagisto#8524]
Source: branch: master
![image](https://github.com/bagisto/rest-api/assets/114124789/715377c3-7164-4f5f-8dfa-65fdba238cba)

![image](https://github.com/bagisto/rest-api/assets/114124789/62dc24b8-1622-428e-aee1-9a53d7b08005)

![image](https://github.com/bagisto/rest-api/assets/114124789/f5620bae-ee34-43bb-b364-8a5484a20a67)

**Comment by jitendra-webkul** [comment]
It's already fixed in #8523, take a pull from the master
