### ISSUE TITLE
In the mobile view, Language and currency options are not visible on the header menu navigation bar.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8555]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

In the mobile view, Language and currency options are not visible on the header menu navigation bar.

### Preconditions

1. Admin should be enabled for one locale and currency.

### Steps to reproduce

1. Go to 'Shop'
2. Open mobile view
3. Click on the Navigation button
4. See the error

### Expected Result

It should be shown the language and currency options.

### Actual Result

It does not show both options. [Here](https://prnt.sc/4ncVIY2r9HsE)

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Assign this issue to me
Thanks
