### ISSUE TITLE
Is required option in the attribute creation form is not working on the edit attribute page.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8556]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Is required option in the attribute creation form is not working on the edit attribute page.

### Preconditions

1. Admin should be logged in.
2. Admin needs to create an attribute.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'create attribute'
3. Scroll down to 'Validation'
4. Select is required fields, Fill in all the required fields, and save it
5. Reopen the same attribute and click on save
6. Reopen the same
7. See the error

### Expected Result

If the option is selected. It should be shown.

### Actual Result

Not updating from the edit page. [Here](https://prnt.sc/na0ZBB_df9A4)

**Comment by codeinnovers** [comment]
assign this to me please.

**Comment by amit-webkul** [comment]
Fixed in [PR](https://github.com/bagisto/bagisto/pull/8565)

**Comment by Amitk-webkul** [comment]
Now, this issue is already fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/XK4nxILBoroh), for future reference.
