### ISSUE TITLE
Configuration options in the attribute creation form are not updating from the edit attribute page.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8558]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Configuration options in the attribute creation form are not updating from the edit attribute page.

### Preconditions

1. Admin should be logged in.
2. Admin needs to create an attribute.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Create Attribute' inside the Catalog/Attributes
3. Fill in all the required options
4. Scroll down to 'Configuration'
5. Select all the options and save it
6. Reopen the same and Click on the save button
7. Reopen the same
8. See the error

### Expected Result

It should be shown the selected options.

### Actual Result

Not showing selected option .[Here](https://prnt.sc/6b39Vpogswin)

**Comment by amit-webkul** [comment]
@Amitk-webkul This Issue is already Fixed In this [PR](https://github.com/bagisto/bagisto/pull/8565)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/AMInMmOONnbK), for future reference.
