### ISSUE TITLE
The asterisk sign is missing in the admin email configuration fields.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8571]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

The asterisk sign is missing in the admin email configuration fields.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Configuration'
3. Scroll down to 'Email setting'
4. See the error

### Expected Result

It should be shown the asterisk sign for the required fields.

### Actual Result

The asterisk sign is missing. [Here](https://prnt.sc/LGei-tx0PxW9)

**Comment by nikita-webkul** [comment]
@Amitk-webkul  assign this issue to me

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Its Fixed
