### ISSUE TITLE
Getting an exception while creating catalog rule.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8584]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Getting an exception while creating a catalog rule.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on 'Promotions' inside the Marketing
3. Click on the Create Catalog rule
4. Fill in all the required fields and save it
5. See the error

### Expected Result

Should not be shown the error and should be able to create a catalog rule.

### Actual Result

Showing an error. [Here](https://prnt.sc/W8-T-5fdmeGP)

**Comment by JunaidJaved248** [comment]
@Amitk-webkul I Just checked it, Its not throwing any error, can you exact scenario, how this error getting??

**Comment by Amitk-webkul** [comment]
@JunaidJaved248 Please take a reference from [here](https://jam.dev/c/822af716-5bb5-4d38-a9d6-74c04b72ab43).

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/_1g26kfuBTbh), for future reference.
