### ISSUE TITLE
Profile Photo Not Displaying After Update

### ISSUE THREAD

**Issue by diusazzad** [bagisto/bagisto#8590]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v1.5.1

### Issue Description

Unable to see the updated profile photo on profile page

### Preconditions

Operating System:Windows 10
Web Browser: Chrome

### Steps to reproduce

Steps to Reproduce:

Navigate to the URL: http://127.0.0.1:8000/customer/account/profile
Click on the profile photo to upload a new image.
Select an image file from your computer and upload it.
After the upload, the profile photo does not display on the profile page.

### Expected Result

I expected the new profile photo to be displayed on my profile page after updating it

### Actual Result

 The updated profile photo is not displaying on the profile page.

**Comment by Amitk-webkul** [comment]
Hi @diusazzad,

This is not an issue. the functionality is working fine. 
Please take a reference [Here](https://prnt.sc/63Q3MMUBpfLU).


If you still facing the same please provide the exact **steps to reproduce** the issue or add a **screenshot** or **short video** to reach out to the exact issue.

Thanks.

**Comment by diusazzad** [comment]
![Screenshot 2023-10-03 162305](https://github.com/bagisto/bagisto/assets/83117020/94260f8b-dce9-4169-aa43-3673ddfa6a16)
![Screenshot 2023-10-03 162304](https://github.com/bagisto/bagisto/assets/83117020/b86c52db-2f04-4f6b-ac37-6e93c6ee8bef)

**Comment by Amitk-webkul** [comment]
Hi @diusazzad,

The app URL is not correct. Please check and enter the correct  APP_URL from the.env file.

**Comment by diusazzad** [comment]
Ok

**Comment by jitendra-webkul** [comment]
I hope the above solution worked for you. I am closing this issue.
