### ISSUE TITLE
On the product page, the Filter should be highlighted if the status filter is applied.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8591]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the product page, the Filter should be highlighted if the status filter is applied.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on the 'Product page'
3. Click on the filter and apply the status filter
4. See the error

### Expected Result

Should be shown the highlighted filter option.

### Actual Result

Not highlighted. [Here](https://prnt.sc/QgGR9QDIwwsW)

**Comment by amit-webkul** [comment]
This issue is Already fixed in this [PR](https://github.com/bagisto/bagisto/pull/8530).
please take a reference with the [Screen Shot](https://prnt.sc/3DPeXS4K4aWI).

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/IrYeivIJdTkO), for future reference.
