### ISSUE TITLE
Getting a few issues with the boolean filters.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8592]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Getting a few issues with the dropdown filters.
 A. Applied filters should not applied again.
 B. The applied filter should be shown the same as the filter label.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on 'Any Listing page' where a boolean filter exists
3. Click on the filter and apply the boolean filters
4. See the error

### Expected Result

It should not apply a duplicate filter and should be shown the label instead of the boolean number.

### Actual Result

Getting duplicate issue and visible boolean value instead of label. [Here](https://prnt.sc/Tb3SRVedtArs)

**Comment by Amitk-webkul** [comment]
@devansh-webkul, Here should be shown the Boolen label instead of True/False. [Here](https://prnt.sc/wjbVwrQm0XqJ)

**Comment by Amitk-webkul** [comment]
@devansh-webkul, Is there any update regarding this issue?

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the boolean related concern has been updated with the true or false value, hence I am closing the issue.  Please check the screenshot [here](https://prnt.sc/bC-fkprmiu5O)
PR of this issue has already merged.
