### ISSUE TITLE
Getting translation issues in the sort options on the Category carousel edit page.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8600]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Getting translation issues in the sort options on the Category carousel edit page.

### Preconditions

1. Admin should be logged in.
2. Admin should have created a category carousel.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Edit Category Carousel' inside the Settings/Theme
3. See the error

### Expected Result

It should be shown the proper translation.

### Actual Result

getting translation issues. [Here](https://prnt.sc/UTVEjxK7Nm5V)

**Comment by AK-Dev11** [comment]
@Amitk-webkul Assign this issue to me.
