### ISSUE TITLE
SQL error occurs when clicking on Print in the frontend invoice

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#8603]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

SQL error occurs when clicking on Print in the frontend invoice

### Preconditions

-  A user should be logged in on the user panel.
- The user needs to place an order, and an invoice should be generated by the admin for that order.

### Steps to reproduce

1. Navigate to the 'User panel.'
2. Place an order.
3. Access the 'Admin panel.'
4. Click on 'Sales' > 'Orders.'
5. Open the specific order and create an invoice.
6. Return to the 'User panel.'
7. Go to 'Home' > 'My Account' > 'Orders.'
8. Open the order and click on the invoice.
9. Then, click on 'Print.'
10. See the error.

### Expected Result

At this point, the invoice should ideally be printed or downloaded as a PDF.

### Actual Result

An error message is prompting to run php artisan migrate, but running it does not resolve the problem.

### Screenshots

![Screenshot from 2023-10-04 17-49-57](https://github.com/bagisto/bagisto/assets/45708520/a80d6819-30f5-45bc-88e5-175a65d29b83)

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh Thank you for Informing.

**Comment by sunarcrajneesh** [comment]
We would love to work on it.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh Okay, Please proceed.

**Comment by sunarcrajneesh** [comment]
We have resolved the SQL exception and fixed translation-related issues in the PDF.
Please review the pull request for more details.
