### ISSUE TITLE
After deleting the currency symbol. still, it is showing in the Shop.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8605]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

After deleting the currency symbol. still, it is showing in the Shop.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one currency.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Edit currency' inside the Settings/Currency
3. Delete the currency symbol and save it.
4. Go to the Shop
5. See the error

### Expected Result

It should show the currency code instead of the deleted symbol.

### Actual Result

Still shows a currency symbol instead of a currency code. [Here](https://prnt.sc/990bCjvJNFHA)

**Comment by sunarcrajneesh** [comment]
Do you want the currency code to appear before the price, after the currency symbol is removed, or do you want to display nothing at all? Please let us know your preference and we will be happy to work on it.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh It should be shown the currency code.

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Assign it to me, I have fixed this issue,

**Comment by devansh-webkul** [comment]
@JunaidJaved248,

This issue has already been assigned to @sunarcrajneesh.

**Comment by JunaidJaved248** [comment]
> @JunaidJaved248,
> 
> This issue has already been assigned to @sunarcrajneesh.

I already worked on it, Pull request generated, You can check it, I have fixed it

**Comment by devansh-webkul** [comment]
You can ask with @sunarcrajneesh. If it's okay then I will proceed because the issue will first get assigned. May be he is also working on it.

**Comment by sunarcrajneesh** [comment]
@devansh-webkul,
Since we are actively addressing the #1166 Currency Format issue, merging it with the master branch might render the resolution of #8605 redundant. Therefore, we kindly request clarification on whether it would be feasible to resolve this issue in conjunction with the 'format currency' issue.

**Comment by JunaidJaved248** [comment]
> @devansh-webkul, Since we are actively addressing the #1166 - Currency Format issue, merging that with the master branch might render the resolution of #8605 redundant. Therefore, we kindly request clarification on whether it would be feasible to resolve this issue in conjunction with the 'Currency Format' issue.

@sunarcrajneesh This Issue Fixed via Currency Format (`shop.js & Core.php` File) , I don't think i will cause any conflict.

**Comment by sunarcrajneesh** [comment]
@devansh-webkul,
As we said we are already working on it. However, you can delegate it to him if you want.

**Comment by sunarcrajneesh** [comment]
@devansh-webkul,

I found out that this is not an issue; Bagisto is using the NumberFormatter to format the currency, which uses the symbol related to the valid currency code. However, if you want to change this behavior, please let me know. We can provide a separate pull request for that.
