### ISSUE TITLE
Footer Copyright Year Displays Previous Year Instead of Current Year

### ISSUE THREAD

**Issue by JunaidJaved248** [bagisto/bagisto#8623]
**Describe the bug**
The copyright year in the footer of the sign-up, login, and forgot password pages is displaying the previous year instead of the current year.

**To Reproduce**
Steps to reproduce the behaviour:
1) Go to 'Shop'
2) Click the sign-up page, login page or Forgot Password Page
3) Scroll down to the footer of the above pages.
4) Observe that the copyright year is displaying the previous year.

**Expected behavior**
The copyright year in the footer of the sign-up, login, and forgot password pages should display the current year.

**Screenshots**
Please take Reference from [Here](https://paste.pics/350edb2675351879d8d37acff6b8c4bc)

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Please check it out, Can i work on it?
As per pointed issue, Previous Showing there, I would like to fix this issue, by making it dynamically, that will show always current year without modifying manually in lang files.

**Comment by saurav-webkul** [comment]
Hi @JunaidJaved248 , would you like to work on this so I can assign this to you?

**Comment by JunaidJaved248** [comment]
@saurav-webkul  Yes Sure
