### ISSUE TITLE
Product image get removed after saving the product.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#863]
Framework Version: 0.1.5
Test Steps:
1.Create a product and add image for that product.
2.Now edit the created product.
3.Image will be removed.

**Comment by jitendra-webkul** [comment]
duplicate to this #826

**Comment by richard457** [comment]
this is not solved.

**Comment by jyoti-webkul** [comment]
@richard457 
Which version of bagisto you are using?
