### ISSUE TITLE
Getting translation issues while adding downloadable product to the cart from the home/listing page.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8631]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Getting translation issues while adding downloadable products to the cart from the home/listing page.

### Preconditions

1. Admin should have at least one downloadable product.

### Steps to reproduce

1. Go to 'Shop'
2. Search the Downloadable product
3. Click on the Add to the Cart button
4. See the error

### Expected Result

It should be shown the proper notification.

### Actual Result

Getting translation issue. [Here](https://prnt.sc/E_rrH7roIl5B)

**Comment by AK-Dev11** [comment]
@Amitk-webkul Assign this issue to me

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/81iLc_qrCJkr), for future reference.
