### ISSUE TITLE
After deleting the category from mass action got a translation issue in the successfully deleted notification.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8633]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

After deleting the category from mass action got a translation issue in the successfully deleted notification.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one category.

### Steps to reproduce

1. Go to 'Admin Panel'
2. Select a category from mass action
3. Click on the delete and Agree
4. See the error

### Expected Result

It should be shown the proper message.

### Actual Result

Getting translation issue. [Here](https://prnt.sc/_z8aS9Q1LsYR)

**Comment by AK-Dev11** [comment]
@Amitk-webkul Assign this issue to me.
