### ISSUE TITLE
 while creating configurable products Configurable Attribute options are going out to the option fields. 

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8635]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If there are many options and the attribute is selected to create the configurable product. so while creating configurable products Configurable Attribute options are going out to the option fields. 

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one created attribute for the configurable product.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Create product' inside the Catalog/products
3. Select Configurable product and fill in all the required field
4. See the error

### Expected Result

It should be shown the options in the option layout.

### Actual Result

But going out to the field. [Here](https://prnt.sc/SOZBsctlJcUR)

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Assign this to me
