### ISSUE TITLE
The Calendar should be shown dark in the dark theme.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8636]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

The Calendar should be shown dark in the dark theme.

### Preconditions

1. Admin should be logged in
2. Admin needs to enable dark theme.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on the 'Dark theme button'
3. Click on the store state Calendar
4. See the error

### Expected Result

Should be shown the calendar in Dark.

### Actual Result

It shows the calendar the same as a light theme. [Here](https://prnt.sc/Tp0XbBsdzgEP)

**Comment by udeet27** [comment]
Hi can you please tell how to replicate this for myself, I opened the admin panel and the calendar dark mode is already working. 
<img width="957" alt="image" src="https://github.com/bagisto/bagisto/assets/75639351/0a802b5f-7c94-4136-83d3-84ce5c8fefc6">

**Comment by Amitk-webkul** [comment]
Hi @udeet27, The issue is replicated in the Bagisto 2.x. you are using Bagisto version 1.x.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed, please check the video for the reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/ef939d78-8eae-4fc2-be0f-9dc747d610c5

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the PR has been merged and issue has been fixed. Hence I am closing the issue.

PR - https://github.com/bagisto/bagisto/pull/9046
