### ISSUE TITLE
Not showing complete product description on front-end.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#865]
Framework Version: 0.1.5

![Screenshot (79)](https://user-images.githubusercontent.com/45203177/56580640-a79ab080-65f0-11e9-923e-168817ed4f0d.png)

![Screenshot (80)](https://user-images.githubusercontent.com/45203177/56580674-b7b29000-65f0-11e9-8d14-d257095a91e0.png)

**Comment by jitendra-webkul** [comment]
Probably product description HTML is not valid.

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.5
Fixed
