### ISSUE TITLE
The "Shop by Filter" need to include taxes if the storefront has the "Tax Inclusive" option enabled

### ISSUE THREAD

**Issue by emilthidell** [bagisto/bagisto#8654]
**Describe the bug**
The "Shop by Filter" need to include taxes if the storefront has the "Tax Inclusive" option enabled in admin.

**To Reproduce**
1. Add one product to a new Category
2. Make the price filterable in the new Category
3. Enable "Tax Inclusive" in admin
4. Go to the new Category store front
5. Filter the products by price
6. The product wont appear because the price including taxes in more than the maximum price generated in the function **getCategoryProductMaximumPrice()** in **\packages\Webkul\Shop\src\Http\Controllers**

**Expected behavior**
Maximum price should include taxes when the "Tax Inclusive" is enabled in store admin

**Comment by Amitk-webkul** [comment]
Hello @emilthidell, Thank you for the information.

**Comment by jitendra-webkul** [comment]
Fixed on #9711
