### ISSUE TITLE
If the bundle radio option is not required from the admin panel for the bundle product. so getting Space issue in the none option of the radio option on the bundle product on the shop.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8656]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If the bundle radio option is not required from the admin panel for the bundle product. so getting Space issue in the none option of the radio option on the bundle product on the shop.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one bundle product with radio option without required.

### Steps to reproduce

1. Go to 'Shop'
2. Click on 'The Bundle Product'
3. See the error

### Expected Result

Add space between radio box and text.

### Actual Result

Space is missing between radio box and text. [Here](https://prnt.sc/Q34-A9nrJem6)

**Comment by AK-Dev11** [comment]
@Amitk-webkul Assign this issue to me.
