### ISSUE TITLE
Compatible the admin panel calendar icon with multiple browsers.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8660]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Compatible with the admin panel calendar icon with multiple browsers.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. See the stats calendar icon OR
3. Click on 'edit/create product' inside the catalog/products
4. See customer group price date & time
5. See the error

### Expected Result

It should be shown in the same places.

### Actual Result

It is showing last in the Firefox browser. [Here](https://prnt.sc/a_KzJn3bCThb)

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Assign this issue to me

**Comment by JunaidJaved248** [comment]
> @Amitk-webkul Assign this issue to me

I am working on it

**Comment by Amitk-webkul** [comment]
@JunaidJaved248 Assigned this issue to you, please proceed.
