### ISSUE TITLE
Shipping title and rate input fields should be dark in the dark theme.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8671]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Shipping title and rate input fields should be dark in the dark theme.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on 'Edit shipping method' inside the Configurations/sales
3. See the error

### Expected Result

It should be shown in dark in a dark theme.

### Actual Result

same as a light theme. [Here](https://prnt.sc/MDphFIbnVk8N)

**Comment by sayyedarib** [comment]
Hey! @Amitk-webkul I would like to work on this issue.

**Comment by Amitk-webkul** [comment]
Hi @sayyedarib, Okay. I'm assigning this issue to you please proceed.

**Comment by shivendra-webkul** [comment]
Hey @sayyedarib this issue is already fixed in this PR https://github.com/bagisto/bagisto/pull/8676

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/_1OZcpoh8JoO), for future reference.
