### ISSUE TITLE
Select File button should be in the Dark in the Dark theme.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8673]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Select File button should be in the Dark in the Dark theme.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on 'Design' inside the Configurations/Design
3. See the error

### Expected Result

It should be a show button in the dark theme.

### Actual Result

Not showing button dark in the dark theme. [Here](https://prnt.sc/27wSHhhrcGzI)

**Comment by sayyedarib** [comment]
@Amitk-webkul can you assign this issue to me , as the last issue #8671 that you assigned me is already solved.

**Comment by Amitk-webkul** [comment]
Hi @sayyedarib, I have assigned this issue. Please continue with this issue.

**Comment by sayyedarib** [comment]
![Screenshot from 2023-10-14 19-36-26](https://github.com/bagisto/bagisto/assets/90370535/d5146d17-0f7e-49ee-bd5d-2bda37fd4553)
I couldn't find this choose file button anywhere. Please help me to figure out how to get this button?

**Comment by Amitk-webkul** [comment]
@sayyedarib, Please take a reference from [here](https://prnt.sc/E1GsO7k-Dzd7).

**Comment by Amitk-webkul** [comment]
Hi @sayyedarib, Is there any update regarding this issue?

**Comment by Amitk-webkul** [comment]
@sayyedarib, No problem at all. Thank you for dedicating your previous time to attempting to find a solution.

**Comment by eness** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/::file-selector-button

This is a new selector that can be used to style the file selector button. It has full support on recent browser versions.

@sayyedarib Take this example at https://codepen.io/spetsnaz/pen/bGzGWbO and try to fix the issue 🤝

**Comment by prajjwalkumar17** [comment]
Hey there I am willing to contribute to this issue can you assign this to me :)

**Comment by Amitk-webkul** [comment]
@prajjwalkumar17 Sure, I'm assigning this issue to you.

**Comment by prajjwalkumar17** [comment]
Thankyou I have started working on it :)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and PR has been merged. Hence I am closing the issue from here.
Please check the screenshot [here](https://prnt.sc/DzQLJr6yF-G1)
