### ISSUE TITLE
On the product review page, the reviewer profile image does not appear.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8682]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If the registered user has added a profile image and given a review on any product, after approving the review it does not show the profile image On the product review page.

### Preconditions

1. Admin should have at least one product available.
2. Customer must be logged in.
3. Customer must be added profile image.

### Steps to reproduce

1. Go to 'Shop'
2. Click on 'Product'
3. Write a review from the review tab
4. Approved the review from the admin panel
5. Go back again to the same product review page
6. See the error

### Expected Result

If the customer profile is added it should be shown the Image instead of Placeholder.

### Actual Result

Not showing the profile image. [Here](https://prnt.sc/4kb8WswTb6Yf)

**Comment by JunaidJaved248** [comment]
@Amitk-webkul I checked it, In code, its showing initials of reviewer name, no profile showing there. Its not bug.
If you want to add profile of customer that add review, we can consider it as enhancement, But doing this, will comprise privacy to showing customer profile publicly to all visitors.
