### ISSUE TITLE
If the address is added as default and while the customer updates that particular address it removes the default address.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8683]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If the address is added as default and while the customer updates that particular address it removes the default address.

### Preconditions

1. Customer must be logged in.
2. Customer should have at least one added address and set it as default.

### Steps to reproduce

1. Go to 'Shop' and login as User
2. Edit the default address and save it inside the Accounts/Addresses
3. See the error

### Expected Result

It should be saved as the default address until the user does not set another address as default or deletes that address.

### Actual Result

After updating the address it was removed as the default address.  [Here](https://webkul.chatwhizz.com/share/view-recording/652d3555ea63c532cde30324)

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Please assign this issue to me, i am working on it

**Comment by Amitk-webkul** [comment]
@JunaidJaved248, I have assigned the issue to you please proceed.
