### ISSUE TITLE
Zip Code/PostCode should only allowed integer in Billing Address while checkout Process

### ISSUE THREAD

**Issue by JunaidJaved248** [bagisto/bagisto#8685]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

When inputting the billing address during the checkout process, the system should prevent users from entering non-numeric values on the screen. However, if a user accidentally enters text or strings, the system will accept it, but the backend validation will detect the error. This error is not displayed to the user but can be found in the API response.
It should restrict user (show error message for adding integer value only)

### Preconditions

Customer must be logged in.
Customer should add order in cart & Proceed checkout 
And New billing address while checkout

### Steps to reproduce

1. Visit the Shop store.
2. Select a product and add it to your shopping cart, then proceed to the checkout.
3. Enter a new billing address, and intentionally input a non-integer value in the Zip/Postal code field.
4. When a non-integer value is entered, the system will not allow you to proceed to the next step due to an error occurring in the API, which is evident in the network response.

### Expected Result

It should only integer value in zip/postcode field

### Actual Result

It should only integer value in zip/postcode field

### Screenshots

Its allowing user to add non-integer value in zip/postcode field

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Please Assign this issue to me, I want to work on it. 
Do check it by reproducing it for validating this issue 
Thanks

**Comment by Amitk-webkul** [comment]
@JunaidJaved248, Thank you for informing. I've assigned this issue to you please proceed.

**Comment by shivendra-webkul** [comment]
Hi @JunaidJaved248  Thank you for taking the time to report this issue. After careful consideration, we have reviewed the problem, and it appears that this validation used in our previous version in new version we removed it. Because there are some countries whose Postcode/Zip code are alphanumeric. Here i have attach screenshot for [reference](https://prnt.sc/tezrAJBC_J57)
So this issue is invalid.

**Comment by JunaidJaved248** [comment]
I understand your point. You're proposing that we consider allowing alphanumeric characters in zip codes to accommodate countries with such codes. Therefore, we should revise the current backend validation rule, which currently triggers an error if the zip code is not purely numeric.

Furthermore, when users add an address through their profile, they encounter both frontend and backend validation errors specifying that the zip code should be numeric. We need to make a definitive decision on whether to retain or remove the numeric validation on zip codes, and ensure consistency in both frontend and backend validation for all address creation processes.

So, this issue remains valid until we make a decision regarding whether to eliminate the numeric validation for postcodes.
Then I will rename its title accordingly then modify it code.

**Comment by Amitk-webkul** [comment]
Hi @JunaidJaved248, We need to remove the integer validation for saving addresses from both the Admin and Shop ends. I kindly request you update the existing issue accordingly, and if applicable, adjust your pull request to align with this modification. Thank you for your assistance.

**Comment by JunaidJaved248** [comment]
> Hi @JunaidJaved248, We need to remove the integer validation for saving addresses from both the Admin and Shop ends. I kindly request you update the existing issue accordingly, and if applicable, adjust your pull request to align with this modification. Thank you for your assistance.

Okay Right @Amitk-webkul

**Comment by ashishkumar-webkul** [comment]
@JunaidJaved248 Any updated on the issue.

**Comment by JunaidJaved248** [comment]
> @JunaidJaved248 Any updated on the issue.

It was fixed by me, Pull request Successfully generated & QA Tested but that were closed by your team member, that they will find its solution internally etc,
