### ISSUE TITLE
If the customer added attachments both image and video at the same time. so it shows only videos from both admin/shop panel reviews.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8687]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If the customer added attachments both image and video at the same time. so it shows only videos from both admin/shop panel reviews.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one product created.

### Steps to reproduce

1. Go to 'Shop'
2. Write a review on the product page/review tab
3. Fill in all the required fields add image and videos and save it
4. Go to 'Admin panel'
5. Edit that review from Customers/reviews
6. Approved the review
7. Go back to the same product review section on Shop
8. See the error

### Expected Result

It should be shown the image/videos both with the review.

### Actual Result

But showing only video. [Here](https://prnt.sc/GHRTO7F6JG4-)

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Can you record of process of adding review, for understanding the actual issue.
As per my current, assumption you are adding video in first select & then again selecting image.
If you select both image & video in one go then you will not face this issue, Give it try., if still issue occurred show me. in view recording.

**Comment by JunaidJaved248** [comment]
I am unable to test it flow, because due to some configuration error, while uploading image, I got `Path could not be empty`, @devansh-webkul or @amit-webkul  Can you guide me in it, regarding which configuration issue need to fix for avoid `Path could not be empty`, on uploading any attachment??

**Comment by Amitk-webkul** [comment]
@JunaidJaved248 While uploading the image and then the video. so only video is visible. 

can you please elaborate on the `path could not be empty` where did you find this error?

**Comment by Amitk-webkul** [comment]
@JunaidJaved248, Any update regarding this issue.

**Comment by JunaidJaved248** [comment]
@Amitk-webkul I'm currently working on this issue, which is distinct from the issue of displaying only videos instead of all files. The problem I've been debugging occurs when a user uploads multiple images and videos in one go. In this scenario, all the files are sent to the store API for storage. However, if a user uploads an image first and then subsequently uploads a new attachment file, the default behaviour of the file upload process displays the most recently uploaded files. Consequently, only the most recently uploaded file is sent to the backend for storage, which is why we see the latest file being displayed.

**Comment by Amitk-webkul** [comment]
@JunaidJaved248,I have delegated this issue to you. Kindly proceed and provide an update at your earliest convenience.

**Comment by JunaidJaved248** [comment]
> @JunaidJaved248,I have delegated this issue to you. Kindly proceed and provide an update at your earliest convenience.

Okay Right @Amitk-webkul

**Comment by ashishkumar-webkul** [comment]
@JunaidJaved248 
I have checked the PR and still issue is appearing. Please check  and update for the same.
Check the PR for issues videos.

PR Link - https://github.com/bagisto/bagisto/pull/8754#issuecomment-1825256033

**Comment by suraj-webkul** [comment]
@ashishkumar-webkul sir this is working fine

**Comment by ashishkumar-webkul** [comment]
Check the video for issue.


https://github.com/bagisto/bagisto/assets/92721837/2c7049db-4f2b-4139-bb63-50da29e7c492


https://github.com/bagisto/bagisto/assets/92721837/72ea44dc-9156-4637-80df-ee641d02bfc9

**Comment by ashishkumar-webkul** [comment]
Issue is appearing when we add Video and Images together,

make sure to add 2 or more videos and images,

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul 
As I checked and found that now it is working fine. Please  check the  video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/f383cf9b-0900-488b-b19d-866fca4c1c47

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and PR has been merged.  Hence I am closing the issue from here.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/cc5b7f4a-df19-483a-9791-d8bdaf095baf
