### ISSUE TITLE
HTML/CSS theme editor should be shown dark in the Dark theme.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8689]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

HTML/CSS theme editor should be shown dark in the Dark theme.

### Preconditions

1. Admin should be logged in.
2. Admin should be enabled dark theme.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Edit theme content' inside the Settings/theme
3. See the error

### Expected Result

HTML/CSS editor is in a light theme. should be in the dark if the dark theme is enabled.

### Actual Result

Showing in light theme. [Here](https://prnt.sc/diXyRkfbuCLT)

**Comment by shakthi2003-ice** [comment]
@Amitk-webkul can you assign me this issue

**Comment by Amitk-webkul** [comment]
@shakthi2003-ice I have assigned this issue to you. Please proceed.

**Comment by Amitk-webkul** [comment]
Hi @shakthi2003-ice, Is there any update regarding this issue?

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul
Checked and Found that the issue has been fixed. Please check the screenshots for the same.

Screenshots

https://prnt.sc/2HzcvFx_Wssl

https://prnt.sc/a2IJF9CRv_eT

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and also the PR has been merged, hence I am closing the issue.
