### ISSUE TITLE
Request Feature: Need Coupon base functionality and Exchange rate conversion via API

### ISSUE THREAD

**Issue by syedMSohaib** [bagisto/bagisto#869]
Hey there, as i see there is no coupon base functionality in bagisto which is essential for any ecommerce store. 
and for exchange rate right now we have to add manually, 
If we can include some api which use cron to update its rate.

**Comment by prashant-webkul** [comment]
Hello @syedMSohaib We are soon going implement a package for coupons called Discount.
You will see the package within next two releases.

**Comment by syedMSohaib** [comment]
@prashant-webkul great to hear it.  Adding there are few more request features if you guys can work on it. because your product has quite potential and it will be great too.

1) Exchange Rate via API 
2) Custom Pages addition and in  menu

Thanks anyway,

**Comment by jitendra-webkul** [comment]
Hi @syedMSohaib 

Both features are planned for future release.
