### ISSUE TITLE
The customer is getting order confirmation mail twice.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8696]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

The customer is getting order confirmation mail twice.

### Preconditions

1. Admin should be configured mail.
2. Admin should have at least one product created.

### Steps to reproduce

1. Go to 'Shop'
2. Added a product to the cart and proceed to checkout
3. Fill in all the required fields and select the shipping/payment method
4. Click on the place order button
5. Go to the mailbox
6. See the error

### Expected Result

The customer should receive the order confirmation mail once.

### Actual Result

getting twice the mail for the same event. [Here](https://prnt.sc/E4yN2BS3IM1q)

**Comment by sunarcrajneesh** [comment]
@Amitk-webkul,
The order confirmation email is being sent twice because listeners for checkout.order.save.after have been created in both the admin and shop panels and both send mail. 
We will be happy to work on it.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh, I have assigned the issue to you. The order confirmation email should be sent to both the admin and the customer. But it is showing both for the customer. so please do accordingly.
