### ISSUE TITLE
If the email verification option is enabled still customer is still able to register and log in without verifying the email.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8698]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If the email validation option is enabled still customer is still able to register and log in without verifying the email.

### Preconditions

1. Admin should be logged in.
2. Admin should be enabled email verification.

### Steps to reproduce

1. Go to 'Shop'
2. Click on 'signup'
3. Registered user and log in
4. See the error

### Expected Result

It should be shown the notification to verify the email.

### Actual Result

Able to log in. [Here](https://prnt.sc/49waFVdmTtWI)

**Comment by JunaidJaved248** [comment]
@Amitk-webkul Assign this to me

**Comment by Amitk-webkul** [comment]
@JunaidJaved248 I have assigned this issue to you. Please proceed.

**Comment by Amitk-webkul** [comment]
@JunaidJaved248, The issue is not replicated. I'm Closing this issue. [Here](https://prnt.sc/0sZ88vCRY_Vl)
