### ISSUE TITLE
Prefixes and suffixes are not applied to order numbers and invoice numbers when the length field is left unspecified.

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#8700]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Prefixes and suffixes are not applied to order numbers and invoice numbers when the length field is left unspecified.

### Preconditions

On the admin panel, the order and invoice settings have been configured, but the length parameter has not been specified.

### Steps to reproduce

1. Navigate to 'Admin > Configuration > Sales > Order Settings.'
2. Configure the "Order Number Prefix" or "Order Number Suffix" as desired and save the settings.
3. Similarly, visit 'Admin > Configuration > Sales > Invoice Settings' and adjust the settings accordingly.
4. After making these changes, create an order and generate an invoice. 
5. Observation will reveal that the prefix and suffix are not applied as expected.

### Expected Result

The prefix or suffix should have been added to the order number and invoice number.

### Actual Result

Prefix or suffix not added to order number and invoice number.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh, Thank you for informing.

**Comment by sunarcrajneesh** [comment]
We will be happy to work on it.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh I have assigned this issue to you. please proceed.
