### ISSUE TITLE
When updating the logo from the channel settings, the change is not reflected on the shop as the new logo.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8705]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

When updating the logo from the channel settings, the change is not reflected on the shop as the new logo.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Edit channel' inside the Settings/Channel
3. Add logo and save it
4. Go to the Shop
5. See the error

### Expected Result

It should be shown the newly added logo.

### Actual Result

Still shows the default logo. [Admin panel](https://prnt.sc/6g4pv2kBvvJ0) [Shop](https://prnt.sc/waTxm4cpRubo)

**Comment by zackAJ** [comment]
try this @amit-webkul   it fixed a similar bug for me caused by me changing the app name in .env
```
cd public
unlink storage
```
then 
```
cd ..
php artisan storage:link
```
credit: [](https://forums.bagisto.com/topic/188/broken-image-logo-in-bagisto-with-causes-and-solutions)

**Comment by Amitk-webkul** [comment]
Hi @zackAJ, I appreciate your suggestion, but in this case, the issue doesn't seem to be related to the storage link. It appears to be a different matter.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/X0MyutTvaD3k), for future reference.
