### ISSUE TITLE
The customer receives the shipment confirmation email twice, and the email sent to the inventory source contact address does not display the correct name.

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#8713]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

The customer receives the shipment confirmation email twice, and the shipment confirmation email sent to the inventory source contact address does not display the correct name.

### Preconditions

1. Admin should be configured mail.
2. To change the email address associated with an inventory source, go to 'admin panel >settings > inventory-sources > edit' for the respective inventory source.
3. Admin should have at least one product created.

### Steps to reproduce

1. Go to 'Shop'
2. Add a product to the cart and proceed to checkout.
3. Fill in all the required fields and select the preferred shipping/payment method.
4. Click on the "Place Order" button.
5. Access the 'Admin Panel.'
6. Open the order and generate a shipment.
7. Check the mailbox of the customer and the inventory source..
8. See the error.

### Expected Result

The customer should receive the shipment confirmation email only once, and the inventory source email should display the correct contact name.

### Actual Result

The customer is receiving emails twice for the same event, and the inventory source email is displaying the customer's name.

**Comment by Amitk-webkul** [comment]
Hi @sunarcrajneesh, The shipment email from Twice is appearing twice. The contact name for the inventory source is displaying correctly. Could you please provide more details on this issue, or alternatively, include a screenshot for better clarity? [Here](https://prnt.sc/LvJwexTsQ1B9)

**Comment by sunarcrajneesh** [comment]
@Amitk-webkul,
Please check it here
![screenshot-prnt sc-2023 10 20-10_38_07](https://github.com/bagisto/bagisto/assets/45708520/ca4a4739-1775-4314-bd79-8d8b630befb8)

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh, Thank you for the information.

**Comment by sunarcrajneesh** [comment]
We would like to work on it.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh Sure, I have assigned this issue to you.
