### ISSUE TITLE
Velocity theme: "-&gt;" is not decoded to "->" when adding blade or php content

### ISSUE THREAD

**Issue by zackAJ** [bagisto/bagisto#8721]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.5.1

### Issue Description

I'm trying to fetch all categories slugs to pass it to a blade view in a loop, both `=>` and `->` are encoded to `=&gt;` and `-&gt;` respectively.
But when rendered in the blade only `=&gt;` is decoded to `=>`, while `-&gt;` stays the same and throws an error.

### Preconditions

 - OS: Windows 10
 - Browser: Brave

### Steps to reproduce

1. Go to "/admin/velocity/meta-data"
2. Click on  "Home Page Content" field
3. Click on the source code and add the code below
```php
@php 
    $categories=app('Webkul\Category\Repositories\CategoryRepository')->getVisibleCategoryTree(core()->getCurrentChannel()->root_category_id);
@endphp
<div>
    @include('shop::home.category',['category'=>'nike'])
    @include('shop::home.new-products')
    @include('shop::home.featured-products')
    @include('shop::home.product-policy')
</div>
```
```
syntax error, unexpected token "&" (View: C:\laragon\www\bagisto-old\storage\framework\views\f105dc5381b9206fad784f7bddb716a2.blade.php) (View: C:\laragon\www\bagisto-old\storage\framework\views\f105dc5381b9206fad784f7bddb716a2.blade.php)
```

### Expected Result

```php
$categories=app('Webkul\Category\Repositories\CategoryRepository')->getVisibleCategoryTree(core()->getCurrentChannel()->root_category_id);
```

### Actual Result

```php
<p><?php $categories=app('Webkul\Category\Repositories\CategoryRepository')-&gt;getVisibleCategoryTree(core()-&gt;getCurrentChannel()-&gt;root_category_id); ?></p>
```

### Screenshots

![image](https://github.com/bagisto/bagisto/assets/101515566/c14f30c4-e080-4f04-8c10-2b8b1dc240b5)
![image](https://github.com/bagisto/bagisto/assets/101515566/6353bc13-2ec6-4ff1-9f36-2c4ead3eb420)
![image](https://github.com/bagisto/bagisto/assets/101515566/000e589f-64a5-41f3-97fe-fd11b28307ee)

### Additional context

I've fixed the issue and I wanted to make a Pull Request but "Velocity" is a separate package and I'm not sure if it's open source.
Let me know where can I share the solution.

**Comment by Amitk-webkul** [comment]
@zackAJ, The Velocity theme is open source, so you're welcome to submit a pull request (PR). Feel free to contribute!
