### ISSUE TITLE
Currency Exchange Rate Update issue from admin end

### ISSUE THREAD

**Issue by vivek-webkul** [bagisto/bagisto#8730]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

Not able to update the currency exchange rate from the admin end:
https://prnt.sc/4qp6i40ZYIaF

### Preconditions

Go to admin => settings => Currency Exchange Rate and tried update any rate.

### Expected Result

The currency exchange rate needs to be updated successfully.

### Actual Result

Not able to update the currency exchange rate from the admin end:
https://prnt.sc/4qp6i40ZYIaF

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/MXxmxII6FT67), for future reference.
