### ISSUE TITLE
No data found default message is missing in the report listing page.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8737]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

No data found default message is missing in the report listing page.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Sales/Customer/Product' inside the Reporting
3. Click/View on any detail page
4. See the error

### Expected Result

It should be shown the No data available message.

### Actual Result

It is showing blank. [Here](https://prnt.sc/m5k8_LiBuYyJ)

**Comment by PentW0lf** [comment]
i wanna work on it !

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/cWyW-e4HWHt9), for future reference.
