### ISSUE TITLE
Percentage value is going out to layout in the reporting/sales on Purchase funnel section.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8741]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Percentage decimal value is going out to layout in the reporting/sales on Purchase funnel section.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least two or more products.
3. Admin should have at least one product added to the card.

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on 'Reporting/sales'
3. Scroll down to 'Purchase Funnel'
4. See the error

### Expected Result

It should be shown two decimal values.

### Actual Result

Percentage decimal value is going out to layout. [Here](https://prnt.sc/jtTvn2fdeW-9)

**Comment by IamSudhir-Kumar** [comment]
can you assign it to me...!

**Comment by Amitk-webkul** [comment]
@IamSudhir-Kumar, I have assigned this issue to you. please proceed.
