### ISSUE TITLE
Importing categories from CSV file

### ISSUE THREAD

**Issue by darkweb2015** [bagisto/bagisto#875]
Hi,

I am trying to import a list of categories from a csv file.  While I have written a script to do the import and it works well, I am unable to get the _lft and _rgt values calculated.

The script that I am using is shown below:
```php
$categoryId = DB::table('categories')->insertGetId([
                'id'         => $productGroup['id'],
                'parent_id'  => $productGroup['parent_id'] ?? null,
                'status'     => 1,
                'updated_at' => now(),
                'created_at' => now(),
            ]);

            DB::table('category_translations')->insert([
                'category_id'      => $categoryId,
                'name'             => $productGroup['name'],
                'description'      => $productGroup['name'],
                'slug'             => \Illuminate\Support\Str::slug($productGroup['name']),
                'locale'           => 'en',
                'meta_title'       => null,
                'meta_description' => null,
                'meta_keywords'    => null,
            ]);
```

How do I get the _lft and _rgt generated?

Thanks.

**Comment by jitendra-webkul** [comment]
Hi @darkweb2015 

Use Webkul/Category/src/Repositories/CategoryRepository.php class to create categories.

_lft and _rgt will be automatically generated for you.

**Comment by darkweb2015** [comment]
@jitendra-webkul

That seems to have done the trick :)

**Comment by hzeghari** [comment]
@darkweb2015 
How did u import the list of categories from csv file using this script and thank u
