### ISSUE TITLE
Cannot use Package Generator and cannot use admin/configuration

### ISSUE THREAD

**Issue by euge001** [bagisto/bagisto#8767]
1. I've installed Bagisto by following your official docs here: https://devdocs.bagisto.com/1.x/introduction/installation.html

2. Tried to install Bagisto Package Generator, but got:
"In InitCommand.php line 919: Could not find a version of package bagisto/bagisto-package-generator matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability."

3. Created Package manually based on your docs here: https://devdocs.bagisto.com/1.x/advanced/create-payment-method.html#_2-by-manually-setting-up-all-files

4. At /admin/configuration got an error Undefined array key "sort" at 1059 // if ($a['sort'] == $b['sort']) {

**Comment by Amitk-webkul** [comment]
Hi @euge001, Can you please inform us which version of Bagisto are you using for package generation?

**Comment by Amitk-webkul** [comment]
@euge001 Discussed the same on the FORUM query. so closing this issue from here because this is not an issue.
