### ISSUE TITLE
Create a search bar for settings to be searched

### ISSUE THREAD

**Issue by saurav-webkul** [bagisto/bagisto#8775]
### Is your feature request related to a problem? Please describe.

New Feature

### Describe the solution you'd like

We may create a search bar to easily search for the settings within the settings tab. Need to make sure that the search bar can search the words related to each of the settings

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the Feature have been implemented and working fine. Please check the Video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/c5a97b68-fd8a-4b20-996f-733f6c33e5fb
