### ISSUE TITLE
elasticsearch issue

### ISSUE THREAD

**Issue by AhmadRam** [bagisto/bagisto#8783]
1. Go to 'Admin panel'
2. Click on 'configuration -> catalog -> products -> Storefront'
3. Scroll down to 'Search Mode -> Elastic Search'
4. now when I search for a product See an error

**Screenshots**
![image](https://github.com/bagisto/bagisto/assets/54410321/a9b0d759-d7d8-42b7-883a-108565c955fd)

**Desktop:**
 - OS: windows
 - Browser: chrome
 - Version:  22

**Comment by Amitk-webkul** [comment]
Hi @AhmadRam, Thank you for bringing this issue to our attention.

**Comment by mustafaazad03** [comment]
Hi, Can I try to solve this issue ?

**Comment by jitendra-webkul** [comment]
Please run the following command to generate indices:

`php artisan indexer:index`

**Comment by hamedslyn** [comment]
Hi @jitendra-webkul 
I have a problem when I edit category of product , elastic search don't update category. 
I use second locale in Bagisto 2.0

**Comment by Amitk-webkul** [comment]
@hamedslyn, Can you please share a **Shot video** of the issue. because the issue is not replicable.

**Comment by jitendra-webkul** [comment]
> Hi @jitendra-webkul I have a problem when I try to edit the category of a product in Bagisto 2.0 with a second locale. Elastic search does not update the category. I have tried running the command php artisan indexer:index, but this problem has not been resolved.

We are doing indexing for products only not for the categories. If you save products only then reindexing will happen.

**Comment by AhmadRam** [comment]
@Amitk-webkul 
![image](https://github.com/bagisto/bagisto/assets/54410321/8f8b37a2-fa3f-4cdb-9d6e-8020374b8a82)
when i run php artisan indexer:index command

**Comment by jitendra-webkul** [comment]
This is a configuration issue.
