### ISSUE TITLE
Unable to Update Products After Adding a Second Language

### ISSUE THREAD

**Issue by huytechvn** [bagisto/bagisto#8799]
Adding a second language to our system is causing a critical problem. Once a second language is introduced, we are unable to update our product information.

**Comment by Amitk-webkul** [comment]
Hi @huytechvn, Can you please share the steps that you are following? And which version of Bagisto are you using?

If possible please share the **screenshot** or **short video** of the issue.

**Comment by hamedslyn** [comment]
Same issue.
in version 2.0 when I use elastic mode for showing products I get this error :

`{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index [products_default_fa_index]\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"products_default_fa_index\",\"index_uuid\":\"_na_\",\"index\":\"products_default_fa_index\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index [products_default_fa_index]\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"products_default_fa_index\",\"index_uuid\":\"_na_\",\"index\":\"products_default_fa_index\"},\"status\":404`

**Comment by Amitk-webkul** [comment]
Hi @hamedslyn, Please run the following command to generate indices:

`php artisan indexer:index`

If still facing the same please let us know.

**Comment by hamedslyn** [comment]
Thank you so much @Amitk-webkul . 
products were indexed in elastic with this command.

**Comment by huytechvn** [comment]
> Hi @huytechvn, Can you please share the steps that you are following? And which version of Bagisto are you using?
> 
> If possible please share the **screenshot** or **short video** of the issue.

Hi @Amitk-webkul I am using Bagisto version 2.0, and below is my video describing the process of updating products with errors.
[screen-recording.webm](https://github.com/bagisto/bagisto/assets/126238138/63f504c3-7153-48a1-b268-e8f6a854e6f7)

**Comment by Amitk-webkul** [comment]
Hi @hamedslyn, If your admin panel language is set to English (en), only products with English content will be visible. To make products in other languages visible, change the admin panel language from the .env file. Once this is done, the products in the respective language will be displayed.

If you still facing the same please let us know.

**Comment by ashishkumar-webkul** [comment]
@hamedslyn 

Steps to be followed.

Add Locales in Admin end

1. Go to Admin -> Settings -> Locales.
2. Add Locale with there symbols.
3. Go to Settings -> Channels -> Add the locale in the channel and save.
4. Go to Catalog -> Create a product -> Select locale -> https://prnt.sc/n64740ohGlpt
5. Fill the details of the product in the same locale.
6.  Save the product.
7. Go to .env file change the Admin locale to the required locale.
8. Check the product in same locale - https://prnt.sc/ybQCYUHJQ28j

In case you find any issyue please let us know. We would love to help you.
