### ISSUE TITLE
Not able to create a Catalog rule. it shows an exception in the console and shows a blank page for the same.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8801]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Not able to create a Catalog rule. it shows an exception in the console and shows a blank page for the same.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Create' inside the Marketing/promotions/Catalog rule
3. Fill in all the required fields and save it
4. See the error

### Expected Result

Should be loaded on the page and shown the catalog rule listing page.

### Actual Result

It should continue to load and while refreshing the catalog rule is created. [Here](https://prnt.sc/xU8_6YQ6H8nz)

**Comment by suraj-webkul** [comment]
This issue is not replicating or im not find that kind of issue

**Comment by shivendra-webkul** [comment]
@ashishkumar-webkul Catalog Rule is working fine it is an invalid issue.

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul checked and found that after taking the fresh installation and then checking the same issue, it is working fine, no issue is appearing. Please check  the video for the reference. Hence I am closing the issue.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/901618f5-7b5f-4dab-a8ba-0d1dd5c69e70
