### ISSUE TITLE
Currency symbol in RTL languages

### ISSUE THREAD

**Issue by hamedslyn** [bagisto/bagisto#8817]
### Is your feature request related to a problem? Please describe.

In RTL languages, the currency symbol should be on the left of the price.

### Describe the solution you'd like

In **Webkul/Core/Core.php** we can add below code in **formatPrice** method  

` if (core()->getCurrentLocale()->direction === 'rtl') {
            $formatter->setPattern("#,##0" . "¤");
   }
 `

**Comment by Amitk-webkul** [comment]
Hi @hamedslyn, I understand that the development of this feature is already underway, alongside the [currency format feature](https://github.com/bagisto/bagisto/issues/1166). Thank you for the update.
