### ISSUE TITLE
First Name and Last Name, We are able to fill any data in Registration form.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8821]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

We are able to Create a new customer with filling any data in the First Name and Last Name in Registration Form.

### Preconditions

Need to Create a new user from store front.

### Steps to reproduce

1. Go to Store Front.
2. Click on Sign Up
3. Fill the First Name and Last Name Information.
4. Sample Text - **test123243!@#$%^&*@fghjk.conhus**
5. Create User

### Expected Result

It should not take any unrequired data in store front registration form.

### Actual Result

Please check the video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/df480bd7-fd32-4b50-b760-b6ea64840873

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/iFw_w-bWsFA_), for future reference.
