### ISSUE TITLE
On admin panel, design option inside configure menu, checkbox not clickable

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/bagisto#8832]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master, V-2.0.0

### Issue Description

On admin panel -> Configurable -> Design option, checkbox not clickable

### Preconditions

Admin should be logged in.

### Steps to reproduce

1. Go to '**Admin panel**'

2. Click on '**Configure menu**'  ->  '**Design option**'
![image](https://github.com/bagisto/bagisto/assets/63539748/c75191b7-412d-4896-9d96-a235d7c96b73)

3. Click on **delete** text then checkbox is select, but if we click on **checkbox** then checkbox is not select:
![image](https://github.com/bagisto/bagisto/assets/63539748/cb8cf9fd-9148-4849-a702-734feccf6e10)

### Expected Result

When we click on checkbox then should be select checkbox and should be work with the delete text also.

### Actual Result

When we click on checkbox then checkbox not works, but click on delete text then checkbox works.

**Please check the video reference:**

https://www.awesomescreenshot.com/video/21962497?key=a679d96c30cd7c86c599f29e4404b98b

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/ZRMh3U5hOEWp), for future reference.
