### ISSUE TITLE
Translation missing in Settings -> Roles menu -> Create roles page

### ISSUE THREAD

**Issue by Komal-sharma-2712** [bagisto/bagisto#8835]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master, V-2.0.0

### Issue Description

Translation missing in settings -> roles menu -> create roles button then reporting word

### Preconditions

Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on '**Settings -> Roles -> Create role**'  button
3. Scroll down to bottom page go to **Sitemaps** **permissions** then below shows **reporting** **sections**  here translation missing:
![image](https://github.com/bagisto/bagisto/assets/63539748/09e5b9d3-e4e4-4d51-be64-9f4bcc57e7b4)

### Expected Result

Should be shown correct word **Reporting** here instead of like this

![image](https://github.com/bagisto/bagisto/assets/63539748/5e4c53fc-c8e6-42a4-933e-0a7e72da5d58)

### Actual Result

Here shows a like this:

![image](https://github.com/bagisto/bagisto/assets/63539748/09e5b9d3-e4e4-4d51-be64-9f4bcc57e7b4)

**Comment by Julian-Dumitrascu** [comment]
From what language is this text translated into English?

**Comment by Amitk-webkul** [comment]
@Julian-Dumitrascu, We have added [key, values] for English and other languages.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/63F0FDNISLV5), for future reference.
