### ISSUE TITLE
The customer is receiving the refund confirmation email twice, and the invoice confirmation email is not being sent to the admin.

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#8862]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

The customer is receiving the refund confirmation email twice, and the invoice confirmation email is not being sent to the admin.

### Preconditions

1. Admin should be configured mail.
2. Admin should have at least one product created.

### Steps to reproduce

1. Go to 'Shop'
2. Add a product to the cart and proceed to checkout.
3. Fill in all the required fields and select the preferred shipping/payment method.
4. Click on the "Place Order" button.
5. Access the 'Admin Panel.'
6. Open the order and generate a invoice.
7. Refund it now.
8. Check the mailbox of the customer and the admin.
9. See the error.

### Expected Result

Refund confirmation and invoice confirmation emails should be sent to both the customer and the admin once each.

### Actual Result

The refund confirmation email is being sent to the customer twice, and the invoice confirmation email is not being sent to the admin.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh, Thank you for informing.

**Comment by sunarcrajneesh** [comment]
We would like to work on it.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh Sure, I'm assigning this issue to you.

**Comment by sunarcrajneesh** [comment]
@Amitk-webkul,
The issue has been resolved. Please review it at your convenience.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh, Okay Checking.
