### ISSUE TITLE
Getting responsive issues on the sales/reporting page if the admin menus collapse.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8863]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Getting responsive issues on the sales/reporting page if the admin menus collapse.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Land on the sales page inside the reporting
3. Collapse side menus
4. See the error

### Expected Result

It should be responsive to collapse.

### Actual Result

But not showing the proper page. [Here](https://prnt.sc/UO6JabqUbm6r)

**Comment by suraj-webkul** [comment]
This issue is alread fixed or not replicating please find the video [here](https://webkul.chatwhizz.com/share/view-recording/6555da20585de410e9a93d8a)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that this is not an issue, hence I am closing the issue. Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/7fcc5a8a-016f-4f15-80de-74d4e1a81166
