### ISSUE TITLE
 Class "Elastic\Elasticsearch\ClientBuilder" not found.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8864]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Not getting client builder class. and showing Class "Elastic\Elasticsearch\ClientBuilder" not found.

### Preconditions

1. Take the pull from the master branch.

### Steps to reproduce

1. Go to 'Terminal'
2. Take a new pull
3. run optimize command
4. See the error

### Expected Result

the class should be there.

### Actual Result

Class is missing. [Here](https://prnt.sc/shf6vGigpHKF)

**Comment by amit-webkul** [comment]
@Amitk-webkul , 

Please Remove your vendor folder and run the command in your project root directory **'Composer install'** in your project root directory.
