### ISSUE TITLE
Invoice section at the Admin end, after selecting Transaction check box responsive issue is appearing.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8866]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

After selecting the transaction checkbox in Invoice section, there we can see that it is having responsive issue.

### Preconditions

1. More then 6 products should be added to the cart.
2. Checkout process should be completed.
 

### Steps to reproduce

1. Go to Admin -> Sales -> Orders -> Edit -> Invoice.
2. Click on Create transaction checkbox.
3. See the responsive issue.

### Expected Result

It should work properly. Please check the video for the reference.

https://github.com/bagisto/bagisto/assets/92721837/44f0ddf0-1b99-42c6-9826-870d9f94eb5a

Please check the screenshot [here](https://prnt.sc/DUuBLaCRirqe)

### Actual Result

It should be responsive after selecting the Checkbox.

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/294ni16CP3D0), for future reference.
