### ISSUE TITLE
Tax applied but categories are not visible.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8870]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Tax is applied but tax categories are not visible in the sales reporting.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one tax created (Tax rate, tax category).
3. Admin should have at least one product added with tax category.

### Steps to reproduce

1. Go to 'Shop'
2. Added product to the Cart
3. Proceed to checkout and place the order
4. Go to 'Admin panel'
5. Complete the order process
6. Go to the sales inside the reporting
7. Scroll down to 'Top Tax Categories'
8. See the error

### Expected Result

It should be shown the top tax categories accordingly.

### Actual Result

Tax categories are not visible.

### Screenshots

https://prnt.sc/4vbL4VRK023i

**Comment by jitendra-webkul** [comment]
Fixed, try with new orders

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/d2IPHXyVpoQz), for future reference.
