### ISSUE TITLE
The order cancellation emails are not being sent correctly. The emails are not being sent to the intended recipients.

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#8873]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

When an order is canceled, an email is sent to the customer, but the email is not being sent to the admin and the email which is currently being sent to the customer should be sent to the administrator and another mail to the customer.

### Preconditions

1. Admin should be configured mail.
2. Admin should have at least one product created.

### Steps to reproduce

1. Go to 'Shop'
2. Add a product to the cart and proceed to checkout.
3. Fill in all the required fields and select the preferred shipping/payment method.
4. Click on the "Place Order" button.
5. Access the 'Admin Panel.'
6. Open the order and cancel it.
7. Check the mailbox of the customer and the admin.
8. See the error.

### Expected Result

The email which is currently being sent to the customer should be sent to the administrator and another mail to the customer.

### Actual Result

When an order is canceled, an email is sent to the customer, but the email is not being sent to the admin and the email which is currently being sent to the customer should be sent to the administrator and another mail to the customer.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh Thank you for informing.

**Comment by sunarcrajneesh** [comment]
@Amitk-webkul,
We would like to work on it.

**Comment by Amitk-webkul** [comment]
@sunarcrajneesh It's fine. I'm assigning this issue to you.
