### ISSUE TITLE
Email Verification -> Mail is not showing User Name.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8874]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

After enabling Email Verification and then checking the verification mail, there we can see that the customer mail is not appearing.

### Preconditions

Mail Configurations should be done for checking the mails.

### Steps to reproduce

1. Go to Admin -> Configure -> Settings -> Allow Email Verification -> Enable it.
2. Go to Sign up -> Create a customer -> Check the Email verifcation mail.
3.  See the mail, there customer name is not appearing.

### Expected Result

Customer Name should appear over there in mails.

### Actual Result

Currently we are unable to see the customer name -> Check the screenshot [here](https://prnt.sc/EJMImUvzk5LZ)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/PZN_buH77L6C), for future reference.
