### ISSUE TITLE
In Shipping of an order -> Dark Theme -> Carrier Name Box should be dark and text should be light after filling the details. 

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8878]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

After filling the Carrier Name details, there we can see in Dark theme Box is appearing white and text is appearing in Black. Please Reverse the case.

### Preconditions

1. Customer/User must have purchase any Tangible products like Simple, Configurable etc. Products.

### Steps to reproduce

1. Go to Admin -> Sales -> Orders -> View Order -> Ship -> Create shipment -> Carrier Name.
2. Fill the Detail in Carrier Name and check the issue.

### Expected Result

Text Box should be in black colour and text should be white.

### Actual Result

Currently box is appearing white after filling the details.

### Screenshots

Please check the screenshot [here](https://prnt.sc/p8JKl2kVta0P)

**Comment by suraj-webkul** [comment]
As i check this issue and i found this is already working fine.Please find the screenshot below
![screenshot_1700120077225](https://github.com/bagisto/bagisto/assets/121420732/ddb0f8ea-bfe1-483d-a010-7dbd43040584)

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul As I have checked and found that the issue is fixed and hence I am marking this as closed. Please check the video for the reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/495877ba-33ab-4cee-a14b-248d1f6c79cb
