### ISSUE TITLE
 the Date option Effect should be affected on mouse hover it is visible permanently. 

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8882]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

In the Dark theme, on the Total sales inside the sales/reporting the Date option Effect should be affected on mouse hover it is visible permanently. 

### Preconditions

1. Admin should be logged in.
2. Admin Needs to enable dark theme.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'View Details of total sale' inside the Sales/Reporting
3. Enable the Dark theme
4. See the error

### Expected Result

It should be shown the effects on hover as dark theme effects.

### Actual Result

Effects visible permanently. [Reference](https://prnt.sc/jBfp2Gai3TY1)

**Comment by jitendra-webkul** [comment]
Fixed in #8905

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/FyiAz4gD7Q0O), for future reference.
