### ISSUE TITLE
In Customer Group pricing, Change the text "qty" to "Minimum QTY"

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8886]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

When we add customer group pricing to a product, there we need to enter the QTY, Please change the heading QTY to **Minimum qty**

### Preconditions

Create or Edit any product.

### Steps to reproduce

1. Go to Admin -> Catalog -> Products -> Create/Edit Product -> Add Customer Group Pricing-> QTY Heading.

### Expected Result

As per the functionality we need to enter the minimum qty to avail the benefits of customer group pricing. Hence Heading need to be changed.

### Actual Result

Currently it seems like the customer group pricing acts only for the entered qty of product.

### Screenshots

Please check  the screenshot [here](https://prnt.sc/-8rBwk1ZfOvx)

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/SSJFV9BlIkx8), for future reference.
