### ISSUE TITLE
The canceled order quantity is still visible in the pending order on product edit page.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8888]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

The canceled order quantity is still visible in the pending order so it is still showing the product in stock on a shop so not able to add the product cart. and the product will not be going out of stock.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one product available.
3. Admin should be 

### Steps to reproduce

1. Go to 'Shop' and login as Customer
2. Placed an order
3. Go to the Admin panel
4. Go to the Order listing inside the sales/orders
5. Edit that order and cancel it
6. Edit that product
7. Scroll down to pending orders in the Inventory section
8. See the error

### Expected Result

The count should be subtracted if the order is canceled.

### Actual Result

 But the quantity is still appearing so the product is not going out of stock and not able to add the product to the cart.

### Screenshots

https://prnt.sc/qWd8ZLe5dcRU

https://prnt.sc/hOiByub1B0lU

**Comment by jitendra-webkul** [comment]
Fixed try with new order

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/uvLLRTlpzVrj), for future reference.
