### ISSUE TITLE
Strike through price on category page is same price

### ISSUE THREAD

**Issue by caesarcxiv** [bagisto/bagisto#889]
Category page:
![image](https://user-images.githubusercontent.com/13050060/56823969-44dd2b00-6823-11e9-8938-c8c849341a57.png)

Product detail page:
![image](https://user-images.githubusercontent.com/13050060/56824005-5c1c1880-6823-11e9-9770-2f078ddd0227.png)

**Comment by rahulshukla-webkul** [comment]
Hi @caesarcxiv 

We have fixed this issue. You can pull from master branch.

**Comment by jyoti-webkul** [comment]
Framework version: 0.1.5
Fixed
