### ISSUE TITLE
If the email verification option is enabled so Customer/Admin both are not getting successful registration messages.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8896]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If the email verification option is enabled so customer and admin both are not getting successful registration messages.

### Preconditions

1. Admin should be logged in.
2. The Admin should have enabled the email verification option.

### Steps to reproduce

1. Go to 'Shop'
2. Register as a customer
3. Open the mailbox and verify the email
4. See the error

### Expected Result

It should be shown the customer registered mail for both Customer/Admin.

### Actual Result

Only received mail for the verification. [Here](https://prnt.sc/yhYumeENOrJB)

**Comment by shivam281590** [comment]
@Amitk-webkul  I'd like to contribute by fixing the issue

**Comment by Amitk-webkul** [comment]
@shivam281590, Sure, I'm assigning this issue to you.

**Comment by ashishkumar-webkul** [comment]
After checking the complete flow of the mail functionality only if the Email verification configuration is active (https://prnt.sc/PuoLyPaKNJ9v) and Mail Notification for customer is Active (https://prnt.sc/wZTm-da3KqHH),

In this case, the customer is not receiving the Registration mail. Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/d653dcba-f28a-46ad-92f0-af9cfff08c3f

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and PR has been merged. Hence the issue fixed and I am closing the issue. Please check  the video for the reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/2294ffa7-89b4-43c2-b817-d002e1151d8d
