### ISSUE TITLE
Invoice Settings - Prefix and Suffix functionality is not working properly.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8901]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.x

### Issue Description

After adding the prefix and suffix, In invoice settings, there we can see that for first time it is working fine, now change the prefix and suffix and then check the Order Id, there we can see that still the previous prefix and suffix details are appearing.

### Preconditions

1. Add Suffix and prefix in the Invoice Settings.
2. Please an order with the same details.

### Steps to reproduce

1. Go to Admin -> Configure -> Sales -> Invoice Settings.
2. Click on Now change the Suffix and Prefix in Invoice Number Settings.
3. Save the configurations.
4. Now Place a new Order.
5. After the order is placed check the order number.
6. There we can see that  the old prefix anc suffix is appearing.
7. Same details are appearing in Sales -> Orders.

### Expected Result

The Prefix and Suffix details should appear, according to the data which is saved.

### Actual Result

Currently what exactly  is happening, Previous Suffix and Prefix details are appeaing.

Please check the video for reference.

https://github.com/bagisto/bagisto/assets/92721837/72c0be96-47d8-4a5b-bd8f-6bf70a0166a0

 

### Screenshots

Please find the screenshots  below.

Invoice Settings  - https://prnt.sc/s8FyZGC8A4Pw
Admin Sales Section - https://prnt.sc/ZITy2jhY4BFL

**Comment by sunarcrajneesh** [comment]
@ashishkumar-webkul,
Please double check that you have updated the invoice settings and attempting to view the changes by referencing the order number. To review the updates in invoice settings, please generate an invoice for the related order and see the invoice number and for make changes in order number change setting of order number.

**Comment by ashishkumar-webkul** [comment]
@sunarcrajneesh 

I got your point and checked and found that it is working fine - Please check the screenshot here - https://prnt.sc/4GX5dYfOQWn0

Hence I am closing the issue.
