### ISSUE TITLE
Add to Cart button should be disable when the product is Out of Stock and we have disabled the Backorder functionality.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8908]
**Description**

In admin end i have disabled the Backorder option and also the product is Out of Stock, but in home page, add to cart button is still not disabled, It is redirecting to the product page.

**Steps To Reproduce**

1. Go to Admin -> Configure -> Catalog -> Inventory -> Backorder setting -> Disable it.
2. Click on Product which is Out of Stock.
3. There when we click on the Add to cart button, warning message appears and redirected to the product view page.

**Expected behavior**

Add to cart button should not be clickable and also when clicked it should show waring message.

**Screenshots**

Please check the screenshot where it need to be disabled - https://prnt.sc/7tah_-c-Tioe

**Actual Concern**

I have disabled the Backorder functionality and then when we click on the Add to cart button it redirects to Product View Page,

Please find the Image [here](https://prnt.sc/vcUBqcFfuhWG)

**Video**

https://github.com/bagisto/bagisto/assets/92721837/040d66df-14c2-484c-ad4a-303a0a98294b

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/odJo3d9EqJqG), for future reference.
