### ISSUE TITLE
Admin end -> Condigure -> Shipping Methods and Payment Methods, Shipping and Payment Method Status and Mandatory field response is not appropriate.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8921]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

When we click on the Status Button and enable it the asterick mandatory field response is inappropriate.
After visiting the page and saving the configurations and then enable or disable the toggle button we can see the unappropriate behaviour.

### Preconditions

1. Login to Admin.
2. Save the Shipping Method or Payment Method configurations once.

### Steps to reproduce

1. Go to Admin -> Configure -> Sales -> Shipping Method and Payment Method.
2. Click on Status toggle button and save it.
3. Now again change the status of toggle button and we can see that the asterick mark is unresponsive.

### Expected Result

Disable Toggle button should not work in mandatory field, but if it is enabled then it should act as a mandatory field.

### Actual Result

Currently responsive issue is appearing. Please check the video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/bdc7bcea-81dd-4123-84ce-49ea9bb7c771

**Comment by amit-webkul** [comment]
@ashishkumar-webkul , As I have checked, there are no issues. Currently, it works like if status is enabled, then the mandatory field is marked; otherwise, it is not.

**Comment by ashishkumar-webkul** [comment]
@amit-webkul Please save the data once and then again change the status, you will be able to replicate the issue.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed. Please check the video for the reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/109dc821-81ca-4761-9f8c-7d160fe25e5d

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the PR has been merged and issue has been fixed and hence I am closing the issue.

PR - https://github.com/bagisto/bagisto/pull/9053
