### ISSUE TITLE
Getting Shop logo responsive issue on the small screen.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8925]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Getting Shop logo responsive issue on the small screen.

### Preconditions

1. Admin should have a minimum of 5 or more categories.
2. A few category names should be more than 2 words

### Steps to reproduce

1. Go to 'Shop'
2. Click on 'Zoom in'
3. See the error

### Expected Result

It should be shown as properly responsive.

### Actual Result

logo shrinks. [Here](https://prnt.sc/IDCojndYmFjC)

**Comment by shivendra-webkul** [comment]
We consider the smallest cellphone screen size in active use is currently the iPhone 5 and , which comes in at 320 pixels wide and Shop logo  is responsive up to 280 pixels.
So It is not an issue. Hence I am closing the issue.
