### ISSUE TITLE
On the checkout page, without adding an address and clicking on the confirm button so get the error in the console.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8931]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the checkout page, without adding an address and clicking on the confirm button so get the error in the console.

### Preconditions

1. Admin should have at least one product created.

### Steps to reproduce

1. Go to 'Shop'
2. Added product to the cart and Proceed to checkout
3. On the billing address click on the confirm address without selecting/adding address
4. See the error

### Expected Result

It should show an alert message to add an address or the button should be disabled until the address is added.

### Actual Result

Getting errors in the console and on the shop continues loading.

### Screenshots

https://prnt.sc/g8rMh2JbeafO

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed, as the confirm button has been removed, once the billing address wull be filled then only the confirm button will appear.

Please check the screenshot [here](https://prnt.sc/_DfnmIwMU0yl)

**Comment by ashishkumar-webkul** [comment]
PR of this issue is merged and hence I am closing the issue now.
