### ISSUE TITLE
Getting Exceptional error in User profile Downloadable Products Section when downaloadable product  added with URL for downloadable Links and user purchases the same product.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8933]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

Created a Downloadable product and added Downloadable Links file type as URL and saved the product. Now when purchased the same product and after the complete invoice process. When in customer profile download products, when click on the Downloadable Product title we can see that exceptional error appearing.

### Preconditions

1. Downlaodable Product created wiith URL as file type.
2. Product must be purchased by the customer.

### Steps to reproduce

1. Go to Admin -> catalog -> Products -> Create a downloadable product.
2. Click on Downloadable Links -> Add File Type as URL and add a url to it.
3. Save the Downloadable Product.
4. Login with customer -> Purchase the product -> Go to admin -> Complete invoice  process.
5. Check the Downloadable Product in Customer profile.
6. Click on product title -> Exceptional Error is appearing.

### Expected Result

There should be no exceptional error appearing. Instead it should redirect to the given URL.

### Actual Result

Currently Exceptional error is appearing.

### Screenshots

1. Create a Downloadable Product  with Downloadable Link URL file type.
Screenshot - https://prnt.sc/N_iPj22-Yj_g

2. Save and Check the details 
Screenshot - https://prnt.sc/XlsxT9Bs0fZA

3. After the purchase click on the Product Title
Screenshot - https://prnt.sc/fVZK9vZdpYoN

4. Exceptional Error which is appearing.
Screenshot - https://prnt.sc/vi8OGQNmsHw5

**Comment by jitendra-webkul** [comment]
The system will not redirect to the link instead it tries to download the file from the given link. And the link you have provided is clearly not downloadable.

Admin should have put the correct URL if they the customer to download it.

**Comment by ashishkumar-webkul** [comment]
@jitendra-webkul sir,

I understood the concern completly. Hence I am marking this issue as closed.
