### ISSUE TITLE
In the channel page setting should be Maintenance mode.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8934]
### Is your feature request related to a problem? Please describe.

It shows the setting instead of Maintenance mode. The functionality is working for maintenance.

### Describe the solution you'd like

It should be shown the Maintenance mode instead of the setting, this functionality is working based on the maintenance mode. [Here](https://prnt.sc/zrEggxrrxI2g)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed, now it is appearing maintainance mode. Please check the screenshot [here](https://prnt.sc/GdpTGQLYQGFd)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and PR have been merged, hence I am closing the issue,
