### ISSUE TITLE
Inventory is not reducing after purchasing the downloadable product. 

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8935]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

Created a downloadable product and then  filling all the details including the Inventory. Now after saving the product and then a user purchases the  product and admin creates the invoice. Checking the admin end Downloadanle product inventory, it is still the same.

### Preconditions

1. Create a downloadable product with Inventory added.
2. Save the product.

### Steps to reproduce

1. Go to Admin -> Check the downloadable product QTY and save the product.
2. Go to Logged in user -> Purchase the product.
3. Go to Admin -> Sales -> Orders -> Create Invoice.
4. Go to Admin -> Catalog -> Product -> Check the inventory of the Downloadable Product.

### Expected Result

If we have added the inventory in Downloadable Product, If product is purchased, Inventory should be reduced.

NOTE - In Bagisto V1.5.1 - We do not have the field to add  Inventory for the downloadable Product, please check  the screenshot [here](https://prnt.sc/Az6wtaZBoZWJ)

### Actual Result

Currently we can see that the inventory details are added and also the inventory is not reduced after purchase.

Please check the video for the reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/e51975b7-2dc0-4a08-8b83-84dcf567da34

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/OsQJJi44WYYp), for future reference.
