### ISSUE TITLE
On the  Admin dashboard, in today's details, it shows two icons for negative values. it should be shown only one down arrow.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8937]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the  Admin dashboard, in today's details, it shows two icons for negative values. it should be shown only one down arrow.

### Preconditions

1. Admin should be logged in.
2. Admin should have previous day data.

### Steps to reproduce

1. Go to 'Admin panel' and Log in as Admin
4. See the error

### Expected Result

It should be shown only the down arrow for the negative value.

### Actual Result

two icons highlight the negative. (subtract sign and down arrow sign) [Here](https://prnt.sc/_clDA60PB6iP)

**Comment by ashishkumar-webkul** [comment]
As I have checked the PR and now only one symbol i.e Down arrow is appearing, Hence the issue is fixed. Please check the screenshot [here](https://prnt.sc/NSd_CzrvXxZ3)
