### ISSUE TITLE
Condition type check in rule validator

### ISSUE THREAD

**Issue by althafn96** [bagisto/bagisto#8945]
cart rule validator is checking the condition_type as boolean when condition_types are only either 1 or 2, which would always be true with the current code

![image](https://github.com/bagisto/bagisto/assets/27689786/e5671c40-5bdf-49ca-8557-2f8c5a4a347d)

**Comment by Amitk-webkul** [comment]
@althafn96, Thank you for the contribution. we will update this in the upcoming release.

**Comment by ashishkumar-webkul** [comment]
PR of this issue has been merged and hence I am marking this issue as closed.
