### ISSUE TITLE
On the cart/catalog rule create/edit page,  condition fields show a validate message after entering the correct value.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8947]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the cart/catalog rule create/edit page,  condition fields show a validate message after entering the correct value.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on 'Create cart/catalog rule' inside the promotions
3. Scroll down to 'Condition'
4. Add condition and select price fields
5. Enter correct value 
6. See the error

### Expected Result

It should not be shown the validation message if entered correct value.

### Actual Result

Entering the correct value still shows a validation message. [Here](https://prnt.sc/L1T8TRT_VRMj)

**Comment by suraj-webkul** [comment]
This bug is already fixed with [this](https://github.com/suraj-webkul/bagisto/commit/c50e84d0520cebd8f9d9e969b0a65b65e94cb795) pr.

**Comment by ashishkumar-webkul** [comment]
Checked and found that the validation issue is already fixed, Hence I am closing the issue.
Please check the screenshot [here](https://prnt.sc/S52TRGquz4uf)
