### ISSUE TITLE
Getting translation issue on the conditions in the catalog/cart rule.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8952]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Getting translation issue on the conditions in the catalog/cart rule.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Create cart/catalog rule' inside the Promotions/Cart/catalog rule
3. Click on add 'Condition'
4. Scroll down to 'Attribute'
5. See the error

### Expected Result

It should be shown the proper name.

### Actual Result

shows translation issue. [Here](https://prnt.sc/6fxnH7kr4K5s)

**Comment by amit-webkul** [comment]
As I have checked, there are no issues.

![Screen Shot](https://github.com/bagisto/bagisto/assets/121479029/198701c4-4ad7-445b-8c7b-6de29552f08d)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that there are no translation appearing, as I have installed bagisto with fresh  codes. Please check the screenshot [here](https://prnt.sc/20Qhg6Md0Fqo)
