### ISSUE TITLE
On the cart rule creation if the coupon type is 'no coupon' and any condition is not added it should be applied automation while the product added to the cart.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8954]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the cart rule creation if the coupon type is **no coupon** and any condition is not added it should be applied automation while the product is added to the cart.

### Preconditions

1. Admin should have at least one product created.
2. Admin should have created a coupon with no coupon type.

### Steps to reproduce

1. Go to 'Shop'
2. Added product to the cart
3. Click on the mini cart icon
4. Go to the cart page
5. See the error

### Expected Result

It should be applied automation cart rule on the landing cart/checkout page.

### Actual Result

not apply the cart rule. [Admin](https://prnt.sc/xcdxjb7szChn) [Shop](https://prnt.sc/I7i8WIcZTa9P)

**Comment by suraj-webkul** [comment]
Hello @Amitk-webkul and @ashishkumar-webkul Sir,
As i checked and found that this is working fine as you provided your screenshot of [Shop](https://prnt.sc/I7i8WIcZTa9P) and [Admin](https://prnt.sc/xcdxjb7szChn) already shows discounted amount. $330.28 into the cart. [Shop](https://prnt.sc/3OClWT-eJ7wv).

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the cart rule No Coupon issue is invalid, as I have checked and found it working. Please check the video.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/5518fc62-0a6b-4299-a703-4426d30fde92
