### ISSUE TITLE
The attribute family edit page is not saving.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8956]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

The attribute family edit page is not saving.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Edit product family' inside the Catalog/attribute family
3. Click on the Same attribute family
4. See the error

### Expected Result

It should be saved and update the changes accordingly.

### Actual Result

It is not saving the details. [Here](https://webkul.chatwhizz.com/share/view-recording/654b6b0fb4ff9d0a7bed47c1)

**Comment by suraj-webkul** [comment]
As I have made a fresh setup and checked, there is no such issue appearing. Please check with the latest installation.

**Comment by ashishkumar-webkul** [comment]
Checked and found that the issue is invaid, I was able to edit the attribute family. Please check the video for the reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/832e161d-93c8-4b4b-8504-250addbcbe61
