### ISSUE TITLE
It shows zero amount of the variant product if the catalog rule is applied.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8957]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

It shows zero amount of the variant product if the catalog/cart rule is applied.

### Preconditions

1. Admin should have at least one configurable product available.
2. Admin should have one catalog rule and should be applied to that product.

### Steps to reproduce

1. Go to 'Shop'
2. Scroll down to 'variant product'
4. See the error

### Expected Result

It should be shown the product discount amount instead of zero.

### Actual Result

It shows zero amount. [Here](https://prnt.sc/Y6YfNkskTUne)

**Comment by shivendra-webkul** [comment]
@ashishkumar-webkul  Issue not replicated. it is working fine.

**Comment by ashishkumar-webkul** [comment]
Checked the same with the latest code pull and found that there is no such issue which is appearing. Please check the screenshot for the same [here](https://prnt.sc/APhyXpvHZcpA)

Hence I am closing the issue from here.
