### ISSUE TITLE
On the admin panel, the Category page is not loading.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8963]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the admin panel, the Category page is not loading.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Category' inside the Catalog
3. See the error

### Expected Result

It should be reloading the category page.

### Actual Result

It shows an error in the console. [Here](https://prnt.sc/NZH0eSMs9RLo)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul Fixed issue in this PR https://github.com/bagisto/bagisto/pull/8967 please check

**Comment by Amitk-webkul** [comment]
Now, this issue is fixed. so I am closing this issue.
And I have attached a screenshot [Here](https://prnt.sc/xsHqLgJO5_iV), for future reference.
