### ISSUE TITLE
There should be a weight option in mass action for the variant products.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8965]
### Is your feature request related to a problem? Please describe.

While creating a configurable product and adding all the required fields with mass action but not able to add weight with mass action. [Here](https://prnt.sc/nR1wmV0drwtl)

### Describe the solution you'd like

There should be a weight option to apply mass action for the variant products.

**Comment by jitendra-webkul** [comment]
Implemented
