### ISSUE TITLE
Getting an exception while clicking the view all button of the carousel on the Homepage.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8966]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Getting an exception while clicking the view all button of the carousel on the Homepage.

### Preconditions

1. Admin should be logged in.
2. Admin should have a few products.

### Steps to reproduce

1. Go to 'Shop'
2. Scroll down to 'Carousel'
3. Click on the View All button
4. See the error

### Expected Result

It should be shown the listing page while clicking on view all.

### Actual Result

getting an exception. [Here](https://prnt.sc/SV4dzKz0CxPW)

**Comment by shivendra-webkul** [comment]
@Amitk-webkul please migrate your database not an issue.

**Comment by jitendra-webkul** [comment]
Run the following command:

`php artisan migrate`
