### ISSUE TITLE
In the Cart rule there should be adate & time calendar. currently it shows only date.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8969]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

In the cart rule create/edit form, there should be a date& time calendar. because In the calendar time option is missing and on the listing page it shows the time as 00:00. so there should be a date & time calendar.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Create cart rule' inside the Promotion/Cart rule
3. Fill in all the required fields and select the start end date
4. Save it
5. See the error

### Expected Result

It should show the date & time calendar. there should be a time in the promotions.

### Actual Result

it shows only the date calendar. [Here](https://prnt.sc/p3x9UXR2Ryqi)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the date and time calender has been added.

check screenshot [here](https://prnt.sc/LuBF1Yi8PaL2)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and also the PR has been merged, hence I am closing the issue.
Please check the screenshot [here](https://prnt.sc/4BTOkI76AnbX)
