### ISSUE TITLE
After adding the date in the cart rule, while editing the cart rule it shows the date fields as Text fields.

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8970]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

After adding the date in the cart rule, while editing the cart rule it shows the date fields as Text fields.

### Preconditions

1. Admin should be logged in.
2. Admin should have at least one created rule with the date.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Edit cart rule' inside the promotions/Cart Rule
3. Scroll down to 'Date fields'
4. See the error

### Expected Result

It should show the fields as date fields. and shown the dates accordingly.

### Actual Result

It shows the fields as text fields. [Here](https://prnt.sc/ejfZxqZxi4iL)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed. Please check the screenshot [here](https://prnt.sc/8aLnYy1EuldU)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and also the PR has been merged, hence I am closing the issue.
Please check the screenshot [here](https://prnt.sc/T3Y5VIEVNoQe)
