### ISSUE TITLE
Cannot access offset of type string on string

### ISSUE THREAD

**Issue by euge001** [bagisto/bagisto#8977]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2

### Issue Description

After successful payment via PayPal SmartButton trying to reach /admin/sales/transactions/view/1#stack (Transactions->view), got: Cannot access offset of type string on string

at packages /Webkul/Admin/src/Http/Controllers/Sales/TransactionController.php: 172

### Preconditions

Ubuntu, Apache, PHP 8.1.2

### Expected Result

Transaction details page

### Actual Result

Cannot access offset of type string on string

### Screenshots

![image](https://github.com/bagisto/bagisto/assets/12379144/7da62cf2-345b-408d-a1b9-018703e71300)

**Comment by suraj-webkul** [comment]
Hii [euge001](https://github.com/euge001).
As i checked and found that there is no such issue we are opening drawer for transactions details and there is no such method convertIntoSingleDimArray in TransactionController.php file.

**Comment by ashishkumar-webkul** [comment]
@euge001 

As per checking the concern, this method which is applied is not  used, and also for transactions we use drawer.

Hence I am closing the issue,

**Comment by sandyandi** [comment]
FYI we just encountered the exact same thing. @euge001 did you manage to fix your issue? Can you please share how you fixed it?

**Comment by Dansday** [comment]
Same issue here @euge001
