### ISSUE TITLE
Getting Console Errrors in Marketing Section, Search Term Option.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#8979]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

When we check the Marketing Section, and there we can see the option Search & SEO, there we can see that tthe shimmer effect is appearing and when we check the console, there we can see that the 500 Internal Server Error is appearing.

### Preconditions

Admin Should be logged in.

### Steps to reproduce

1. Go to Admin -> Marketing
2. Click on Search & Seo
3. Open Console and See errors.

### Expected Result

There should be no console errors.
And also if there are no search terms then it should show some message.

### Actual Result

Currently we can see that there are a lot of console errors. Please check the video for the reference,

** Video**

https://github.com/bagisto/bagisto/assets/92721837/5eecca9d-baaa-458b-aaab-48b90990a204

**Comment by suraj-webkul** [comment]
As i fresh installed bagisto and i am not getting this kind of error.

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul I have checked the same with the fresh installation and there no such issue is appearing, hence I am closing the issue.
Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/d158c853-306c-45a1-8948-eaa4f382ceb5
