### ISSUE TITLE
unable to see submenu on users with limited roles

### ISSUE THREAD

**Issue by eness** [bagisto/bagisto#9005]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

When I add a custom user with a custom role which has i.e only `Catalog > Categories (add, edit, delete)` permission, that user is unable to reach to the module since the submenu is hidden under `Catalog` menu item. Also `Catalog` text is linked to `/products` page which is meaningless since the user has no permission to manage Products

### Preconditions

Fresh bagisto install, add 1 custom role and 1 custom user assigned with it.

### Steps to reproduce

1. Go to Roles page.
2. Add custom role with Dashboard and Catalog > Categories (add, edit, delete) permissions
3. Add a new user with that role.
4. Switch (login) to dashboard using that user.
5. Try to reach to Categories menu item, which was hidden under Catalog's submenu.
6. Also once you click to Catalog menu item, it redirects you /products page which that user was not assigned the required role.

### Expected Result

When any user assigned to a sub-module role such as Catalog > Categories, the tree-menu layout should allow the user to access the module on UI. Currently the submenu is hidden and you can't expand it since the menu UI was not designed to work like that.

### Actual Result

Submenu is hidden and unable to reach Categories module's menu item.

### Screenshots

https://i.imgur.com/rSo0vAR.png

**Comment by eness** [comment]
As a solution, I think we need to turn the whole side menu into a collapsible system - or just convert ones that includes limited sub-menu items that my role has permissions to.

**Comment by ashishkumar-webkul** [comment]
@eness 
Thanks for the query as I have checked and found that this issue is appearing. Please check the video for the reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/a570bda6-8e6b-4d02-a8c4-d4f953349d28

**Comment by suraj-webkul** [comment]
Im Working on it.

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul 
Checked and Found that the issue has been fixed, please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/980b5a5b-9f2e-4e7e-9309-f4abed61a2de

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the PR has been merged and  issue has been fixed.
