### ISSUE TITLE
Implementing Notifications

### ISSUE THREAD

**Issue by yaser-alazem** [bagisto/bagisto#902]
Hi, 
I wonder if the notification feature is already enabled in Bagisto or I need to enable it ? If so, is there any settings I need to apply or I can do it with the classic Laravel way like: `php artisan make:notification name` ? 

Thanks

Edit: I should have posted this thread in the Bagisto Forums! Sorry about that.

**Comment by rahulshukla-webkul** [comment]
Hi @yaser-alazem 

You can implement everything which Laravel Perovides, You can implement notification using classic Laravel way.

Thanks
Rahul Shukla
