### ISSUE TITLE
Layered Navigation down icon  issue

### ISSUE THREAD

**Issue by jitendra-webkul** [bagisto/bagisto#903]
![download](https://user-images.githubusercontent.com/39991107/57295457-2fe87d80-70e8-11e9-85cb-38dc23bd0084.png)

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.5

------------------------------------------
Fixed
![Screenshot (31)](https://user-images.githubusercontent.com/45203177/58326832-97722d00-7e4b-11e9-926e-e4cfe49d4b61.png)
