### ISSUE TITLE
Italian translation is mixed with Spanish in Admin panel

### ISSUE THREAD

**Issue by matteodoozy** [bagisto/bagisto#9049]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

I noticed that if you select Italian as language for the Admin panel, the "Settings" section isn't well translated because some of the translation are in Spanish. So I checked the translation file in [root]/packages/Webkul/Admin/src/Resources/lang/it/app.php and I found out that the translations are half in Italian and half in Spanish.

### Preconditions

Bagisto v2.0.0
PHP version: 8.1.18

### Steps to reproduce

1. Go to Admin panel
2. Set admin language to Italian
3. Click on the menu 'Impostazioni'
5. Page title is in Spanish as well as table columns

This happens for all the pages in this section.

### Expected Result

Page title: 'Località'
Table columns: 'Codice', 'Nome', 'Direzione'

### Actual Result

Page title: 'Localidades'
Table columns: 'Código', 'Nombre', 'Dirección'

### Screenshots

![screenshot-bagisto](https://github.com/bagisto/bagisto/assets/77014914/9527d7f0-02ab-4c05-8f4d-6876649b69e1)

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 
Checked and found that the issue has been fixed. Please check the screenshot [here](https://prnt.sc/C1roJVnRZW8e)

**Comment by matteodoozy** [comment]
Thank you very much, this was fast, very much appraciated!

**Comment by shivendra-webkul** [comment]
@matteodoozy You're welcome! We are glad we could resolved issue promptly. If you encounter any more issues or have further questions, feel free to reach out.
