### ISSUE TITLE
Magic AI Configuration is disable, still we are able to see the Magic AI details in Categories.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9077]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

When we check the magic AI options, there we have disabled the Feature and when we check  the admin end categories, there we can see that the Magic AI option is still appearing.

### Preconditions

1. Admin Should be logged in.

### Steps to reproduce

1. Go to Admin -> Configure -> General -> Magic AI -> Status -> Disable -> Save.
2. Go to Catalog -> Categories -> Create/Edit any category -> Check the Magic AI option.
3. It should not appear if the feature is disabled.

### Expected Result

We should not be able to see the details related to the Magic AI if module is disabled.

### Actual Result

Currently we can see that the details related to the Magic AI is appearing in the categories.
Please check the screenshot [here](https://prnt.sc/7wzV880FiCjA)

### Screenshots

Admin End Confgurations - https://prnt.sc/QOlTdv7Ywfi9
Category Screenshot - https://prnt.sc/7wzV880FiCjA

**Comment by amit-webkul** [comment]
No need to fix this issue as we have disabled the AI tools button
