### ISSUE TITLE
Images not appearing

### ISSUE THREAD

**Issue by Thapelo-Laroc** [bagisto/bagisto#9143]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

latest

### Issue Description

i just installed the website on my cpanel host. i tried to update the logo and favicon. After i save configuration the logo does not appear but it shows a broken image icon. i also tried to add an item/product but the image does not appear also.

i ainstalled the website using the GUI intaller.

please assist

### Preconditions

I am using an online host and used the GUI installer to install

### Steps to reproduce

1. went to admin
2. tried to update logo, favicon and tried to add a product
3. saved the configuration
4. after saving the images do not appear but it shows a broken image icon

### Expected Result

Images should show

### Actual Result

images not showing but broken image icon appears

### Screenshots

![Screenshot (28)](https://github.com/bagisto/bagisto/assets/134364391/251a9b6f-e014-45e9-ad19-e4bc163eca0c)

**Comment by amit-webkul** [comment]
@Thapelo-Laroc ,

It might be possible that if you are facing a broken image issue, then maybe **app_url** is not set properly inside the **[.env]** file. Please check once and verify that **App_URl** contains your website URL properly (without the slash at the end of the URl).

**Comment by Thapelo-Laroc** [comment]
This was the issue thank you.

On my localhost the Images were showing but not on the online host. So I
compared the App_URl of the localhosted website and the online one. Turns
out that the localhosted URl has double slashes before public like this "
http://localhost/websites//public"

Then the online URl was "https://domain/public"

I had to insert the second slash on public "https://domain//public".
That fixed the problem.

Thank very much 🙏.
