### ISSUE TITLE
Checkout Experience

### ISSUE THREAD

**Issue by althafn96** [bagisto/bagisto#9144]
### Is your feature request related to a problem? Please describe.

the checkout experience

### Describe the solution you'd like

- address is not editable once confirmed, please fix it
- the address and selected shipping/payments methods are already saved in the cart object, why not autofill that on checkout page reloads? (eg: when i fill everything, and go to payment gateway and cancel the payment, i am asked to fill all the details again)

**Comment by jitendra-webkul** [comment]
Will fix that is the upcoming release

**Comment by DanVu1007** [comment]
Hi @jitendra-webkul,
Thanks for a great platform,
Please fix the above problem, it greatly affects the overall working experience of the website.
Thanks

**Comment by jitendra-webkul** [comment]
@DanVu1007 In the next week's release this change will be included.
