### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone'

### ISSUE THREAD

**Issue by jasbin** [bagisto/bagisto#916]
when I tried to fill the mobile number I got this exception: 
![z1](https://user-images.githubusercontent.com/25180100/57510720-36b10380-7327-11e9-89b4-b9624c51ec13.PNG)
and I checked out the customer table I found out that there is no column named phone
in the customer but the customer should be available with a feature to add their mobile number in their profile but it's missing, only admin has the feature to add the mobile number and we cannot add mobile from admin but instead we get the error if we try to do so.
![z2](https://user-images.githubusercontent.com/25180100/57510995-da9aaf00-7327-11e9-86b4-5b9c4c58423f.PNG)

we don't have add mobile number field in the customer profile
![z3](https://user-images.githubusercontent.com/25180100/57511081-15044c00-7328-11e9-8dc6-2f99ebf26e1d.PNG)

**Comment by rahulshukla-webkul** [comment]
Hi @jasbin 

We have added phone column in customer table. Now you can pull from master branch of repository. 
Thanks for your suggestion.

Thanks
Rahul Shukla

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.6

---------------------------------------

Fixed
