### ISSUE TITLE
Admin and Customer end ->  RTL View Arabic Locale, Invoice should be printed in RTL View.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9178]
**Describe the bug**

Admin and Customer end ->  RTL View Arabic Locale, Invoice should be printed in RTL View. When we print an invoice in arabic locale it should appear in RTL view. 

**Preconditions**

1. In Env file please change translation to Arabic for Admin Arabic locale view.
2. Add  locale arabic for customer profile view.

**To Reproduce**

1. Go to Admin -> Sales -> Invoice -> Print Invoice of any order.
3. Go to Customer -> Login -> Orders -> Invoice -> Print Invoice.

**Expected behavior**

Print Invoice should appear in arabic locale with RTL view.

**Reference - https://msofficegeek.com/wp-content/uploads/2021/12/UAE-VAT-Invoice-Template-Arabic.jpg**

**Actual Issue**

**Screenshots**

Please check the PDF for reference.
[invoice-18-12-2023.pdf](https://github.com/bagisto/bagisto/files/13700486/invoice-18-12-2023.pdf)

**Comment by edesignersa** [comment]
Dear Support,

I have same issues, the Arabic words not appear as it should be. your references is good. I have same issues as PDF.

**Comment by jitendra-webkul** [comment]
Fixed in #9887
