### ISSUE TITLE
The product video is not playing on the product view page of the shop.

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#9181]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the product page in the shop, videos are displayed alongside images in the list, but when clicking on a video, it shows a blank space.

### Preconditions

It is essential to have a product on the shop that includes both images and videos.

### Steps to reproduce

1. Go to 'Admin panel'
2. Then create a product.
3. Make sure to add pictures or videos when adding a product.
4. Visit the shop and check out the product. Click on the product to watch its video.
5. See error

### Expected Result

When clicking on the product video, the video should be displayed and played.

### Actual Result

When clicking on the product video, the video does not play, and a blank space is displayed.

### Screenshots

![Screenshot from 2023-12-18 16-21-57](https://github.com/bagisto/bagisto/assets/45708520/ff90aade-0342-4222-8728-3e4bf37dc5a7)

**Comment by sunarcrajneesh** [comment]
@jitendra-webkul,
We found that the video is not showing because the @load event does not work with videos in all browsers. Therefore, we can use 'loadeddata' here. and also fix unfocused video.

**Comment by ashishkumar-webkul** [comment]
Checked and found that the issue has been fixed, I checked the video play in Mozila Firefox and chrome browser, and it is working fine. 

Please check the video  for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/3d9e8151-bf57-426d-80de-4e6d1fd41ff0


https://github.com/bagisto/bagisto/assets/92721837/4b9aadc4-d939-4a06-8941-5c78965243e1
