### ISSUE TITLE
Admin End, Arabic Locale -> Product Edit/Create -> Price Section is having UI issue.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9187]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

When we check the arabic locale of admin end, create/edit a product and there in price section we can see the UI issue is appearing.

### Preconditions

1. .env file -> change Admin locale to Arabic.
2. Admin should be logged in.

### Steps to reproduce

1. Go to Admin -> Catalog -> Products -> Create/Edit
2. Click on Price Section.
3. See The UI issue.

### Expected Result

UI should be clear.

### Actual Result

Currently we can see that the price details are overlapping.

### Screenshots

Please check the screenshot below.

![UI Price](https://github.com/bagisto/bagisto/assets/92721837/1ae15748-2ae1-4765-9936-9d4aa9bf2ff6)

**Comment by KBM90** [comment]
I have the same issue I think the author should make a release , because softaculous app installer provide code from 23 october when the repo is having many commits since this date .

**Comment by jitendra-webkul** [comment]
Fixed in #9225

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and PR has been merged. Please find the screenshot [here](https://prnt.sc/qOCchh78GjoR)

Hence i am closing the issue.

**Comment by jitendra-webkul** [comment]
> I have the same issue I think the author should make a release , because softaculous app installer provide code from 23 october when the repo is having many commits since this date .

I plan to release a new version next week.
