### ISSUE TITLE
Lines in a Street Address - error when empty

### ISSUE THREAD

**Issue by ronaldrios** [bagisto/bagisto#920]
When click on save and the Lines in a Street Address is empty it throws an error. There is no filter to avoid this.

![admin-configuration-customer-settings](https://user-images.githubusercontent.com/1495454/57572742-34f54780-73dc-11e9-9350-daaa425bad35.jpg)
![error from admin-configuration-customer-settings](https://user-images.githubusercontent.com/1495454/57572743-36bf0b00-73dc-11e9-867a-e00003e42c2c.jpg)

**Comment by prashant-webkul** [comment]
@ronaldrios We cannot reproduce this issue can you check it again?
Although we will provide the fix by attaching 'required' validation on 
field for lines in address form.
You will be able to see these changes in next release of Bagisto.

Regards:
Prashant.

**Comment by jyoti-webkul** [comment]
Unable to reproduce, its working fine
