### ISSUE TITLE
Admin menu is not display

### ISSUE THREAD

**Issue by nicelizhi** [bagisto/bagisto#9200]
**Describe the bug**

when i login my store admin, i found the menu is not display child info

like this

![image](https://github.com/bagisto/bagisto/assets/34465153/b46c9b67-9085-4c7b-a448-249fdfd484fd)

i found the code have cart rule etc info.

![image](https://github.com/bagisto/bagisto/assets/34465153/46755e08-2e29-42fb-a055-315c09be8809)

Thank you

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 20.0.6099.110

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jitendra-webkul** [comment]
Will fix that in upcoming release

**Comment by jitendra-webkul** [comment]
Fixed in #9232

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed, now we are able to see the Fields of the side menu which are collaped by hovering mouse courser on the menu. Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/41d926d7-a80c-4132-bb19-43eb9b1390d7

**Comment by rcurrington** [comment]
Why is this labeled an enhancement? The navigation is broken making the admin unusable. This should be hot fixed and released. 

When is this going live so we can use the admin again?

**Comment by jitendra-webkul** [comment]
@rcurrington The issue has been resolved and merged into the master branch. We're planning to roll out the fix in the upcoming release, expected by the end of next week.
