### ISSUE TITLE
Missing required parameter for [Route: shop.product_or_category.index]

### ISSUE THREAD

**Issue by phyothiha** [bagisto/bagisto#9207]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

Update **Default Value** to **1** for *Visible Individually* and *Status* Attributes.
Create a new product or edit existing product(s) and 500 internal server appears.

`
Missing required parameter for [Route: shop.product_or_category.index] [URI: {fallbackPlaceholder}] [Missing parameter: fallbackPlaceholder]
`

### Preconditions

1. Logged into as admin.

### Steps to reproduce

1. Go to Admin > Catalog > Attributes > Visible Individually > Set Default Value to 1 > Save
2. Go to Admin > Catalog > Attributes > Status > Set Default Value to 1 > Save
3. Go to Admin > Catalog > Products > Create Product > Enter Type, Family,  SKU > Save
4. System redirected to Product Edit Page
5. Error page appear

### Expected Result

Should show the product edit page.

**NOTE**

The reason why I set this default value to 1 is because user is intended to create a new product and should be marked as active for Visible Individually and Status attribute.

### Actual Result

Missing required parameter for [Route: shop.product_or_category.index] [URI: {fallbackPlaceholder}] [Missing parameter: fallbackPlaceholder]. (View: packages/Webkul/Admin/src/resources/views/catalog/products/edit.blade.php)

### Video
https://github.com/bagisto/bagisto/assets/12383757/45719314-3936-430a-8200-998fa6591003

**Comment by jitendra-webkul** [comment]
Fixed in #9211
