### ISSUE TITLE
Issue with the cache "data" directory

### ISSUE THREAD

**Issue by ronaldrios** [bagisto/bagisto#921]
Issue:
D:\www\bagisto>php artisan cache:clear
Failed to clear cache. Make sure you have the appropriate permissions.

Cause:
The "data" directory (storage/framework/cache/data) doesn't exist,

Solution:
Create the data directory fixes the issue;

**Comment by prashant-webkul** [comment]
@ronaldrios Please run the command to resolve the permission issues with your instance cache.
In your terminal goto your project's root and run the command below:

```
sudo chmod -R 755 storage
```
