### ISSUE TITLE
Payment method configuration fields not validating as per the explained condition

### ISSUE THREAD

**Issue by girjesh-webkul** [bagisto/bagisto#9221]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0

### Issue Description

Steps to replicate the issue.

Before updating configuration settings let's add the status key in the system.php file with two input fields one for Production and the second for Development and each field depends upon status.

Case if status is enabled want to make  Production field as required and if status field is disabled want to Development field as required filed.

1. Login to admin panel
2. Go to the respective payment method and make sure as per the above condition in system.php added.

### Preconditions

Steps to replicate the issue.

Before updating configuration settings let's add the status key in the system.php file with two input fields one for Production and the second for Development and each field depends upon status.

Case if status is enabled want to make  Production field as required and if status field is disabled want to Development field as required filed.

1. Login to admin panel
2. Go to the respective payment method and make sure as per the above condition in system.php added.

### Expected Result

Validation should be displayed according to the configuration that we have added in the respective payment gateway system.php file.

### Actual Result

Not working as per above condition.

### Screenshots

![issue](https://github.com/bagisto/bagisto/assets/107393206/4ba6e622-397c-45b9-8421-445487d02cbe)

**Comment by AColtZz** [comment]
Running into similar issue, It seems that the results of the script in 
Admin/src/Resources/views/configuration/dependent-field-type.blade.php

Managed to fix this temporarily by doing the following:
``` php
data() {
    return {
        isRequire: false,
        appliedRules: [],
        value: this.result,
        dependSavedValue: (!this.dependSavedValue && this.dependSavedValue !== 0) ? 1 : 0
    };
},
```

before it was like so:
``` php
data() {
    return {
        isRequire: false,
        appliedRules: [],
        value: this.result,
        dependSavedValue: parseInt(this.dependResult)
    };
},
```
debugging this showed a result of this dependResult to the following values (first one 0, afterwards "on", "value" "") So I checked on it being empty/not valid for the 1/0 instead of parsingInt.

I am not too familiar with most of these things yet started out with Bagisto recently, but maybe this will provide help towards the solution/fix in the future.

**Comment by devansh-webkul** [comment]
No need for this, generally one thing will work at a time. So if production is enabled it's automatically required. If still someone needed they can customize it. But from my understanding generally two instances will not work simultaneously.
