### ISSUE TITLE
Currency not getting updated when place an order it's always showing in order list under sales inside admin panel

### ISSUE THREAD

**Issue by girjesh-webkul** [bagisto/bagisto#9224]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.0.0

### Issue Description

Currency not getting updated when we change from default $ to other currency(AED) and then place an order it's always showing with a dollar in sales orders

### Preconditions

Currency not getting updated when placing an order it's always showing with a dollar in sales orders

### Steps to reproduce

Follow the following step to reproduce issue.
1. Login to admin panel
2. Go to the channel and change default currency from dollar to other.
3. Place an order from the frontend.
4. Once order successfully place go to the admin panel 
5. Click on Orders under Sales menu, now you can see those order we have placed with different currency it showing in dollar.

### Expected Result

Place order currency should be displayed as per the default currency.

### Actual Result

Order currency showing in $.

### Screenshots

![sales](https://github.com/bagisto/bagisto/assets/107393206/92d27f22-fe99-4afb-a232-fa5949180c0c)
![admin1](https://github.com/bagisto/bagisto/assets/107393206/ed29b14a-7cb6-4421-b724-830c435b5175)
![frontend](https://github.com/bagisto/bagisto/assets/107393206/dc02d1d6-a100-4d15-a452-500cd1273a2c)

**Comment by shivendra-webkul** [comment]
@girjesh-webkul In the Admin section, the order price is in the currency which is the default currency of the Admin set in .env file.So it is not an issue.
