### ISSUE TITLE
getProductIdAttribute() does not work as expected

### ISSUE THREAD

**Issue by eness** [bagisto/bagisto#9227]
**Describe the bug**

`\Webkul\Product\Models\Product` model has a `getProductIdAttribute()` mutator definition. It can be accessed as ;

`app(\Webkul\Product\Repositories\ProductRepository::class)->first()->product_id`

but can not be accessed as if you specify columns to fetch from db ;

`app(\Webkul\Product\Repositories\ProductRepository::class)->where('type', 'simple')->get(['id', 'sku', 'parent_id'])->first()->product_id`

due to errors (tinker test) : 

`   WARNING  Attempt to read property "id" on null in packages/Webkul/Attribute/src/Repositories/AttributeRepository.php on line 186.

   WARNING  Attempt to read property "id" on null in packages/Webkul/Attribute/src/Repositories/AttributeRepository.php on line 190.

   WARNING  Attempt to read property "custom_attributes" on null in packages/Webkul/Attribute/src/Repositories/AttributeRepository.php on line 190.

   TypeError  Webkul\Product\Models\Product::checkInLoadedFamilyAttributes(): Return value must be of type object, null returned.`

**To Reproduce**
1. php artisan tinker
2. Try to get a product with custom columns and access product's id using a mutator : `echo app(\Webkul\Product\Repositories\ProductRepository::class)->where('type', 'simple')->get(['id', 'sku', 'parent_id'])->first()->product_id`
3. You will get errors since override of `getAttribute($key)` method does not check if the value can be accessed with a mutator.

**Expected behavior**

Get value of `id` column over `product_id` get mutator.

**Screenshots**

![image](https://github.com/bagisto/bagisto/assets/2032225/c98f6963-ef98-487c-8a2e-ed4db8e8cc3e)

**Comment by jitendra-webkul** [comment]
I have removed "getProductIdAttribute" and "getProductAttribute" functions from Product model as these functions are no longer needed.

**Comment by jitendra-webkul** [comment]
I'm closing this issue. Please feel free to reopen if you have any further questions or concerns.
