### ISSUE TITLE
Message is not stored in Maintainance Mode.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9233]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

When checking the Maintainance mode and adding  manual message in the box. After saving the details checking the information at home page no message appearing. When checking the details in channels, no message is stored.

### Preconditions

1. Admin Should Be Logged In.

### Steps to reproduce

1. Go to Admin -> Channels -> Edit the channel -> Maintainance mode. 
2. Add Message -> Save the details 
3. Go to home page -> No Warning message is appearing.

### Expected Result

Please add proper Maintainance Mode Page and Message.

### Actual Result

Currently we are unable to see proper message. Please check the video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/f30e43e4-0282-4321-b952-cd5f8d983acf

### Screenshots

Please find the screenshot for the reference from previous version [here](https://prnt.sc/FURiP8VriARd)

**Comment by jitendra-webkul** [comment]
The message won't be displayed when the application is running in the development environment. To enable the message, please update the following configuration settings:

```
APP_ENV=production
APP_DEBUG=false
```
