### ISSUE TITLE
Issue in updating customer profile

### ISSUE THREAD

**Issue by Anmol-Chauhan** [bagisto/bagisto#9235]
**Describe the bug**
login with any customer and update the profile fill mobile number which already a customer has taken then save

**Expected behavior**
Customer profile should be updated successfully

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://prnt.sc/VH4SiQZZ2QjG)

**Comment by ashishkumar-webkul** [comment]
Checked and found that the issue has been fixed and PR has been merged. Hence I am closing the issue. Please check the video for reference.

**Video**


Uploading Contact.mp4…
