### ISSUE TITLE
Integration of millat/laravel-hooks for Enhanced Customization

### ISSUE THREAD

**Issue by AColtZz** [bagisto/bagisto#9261]
### Is your feature request related to a problem? Please describe.

I'm currently working on a Laravel project and have identified a need for enhanced customization in various parts of the codebase. The [millat/laravel-hooks](https://github.com/SneherAdor/laravel-hooks) package offers a powerful solution similar to WordPress' do_actions by allowing developers to inject custom code at specific points in the application workflow.

### Describe the solution you'd like

The current customization options are limited, making it challenging to add functionality at specific points in the code without having to overwrite entire classes or create new packages for small changes.

Integrating the [millat/laravel-hooks](https://github.com/SneherAdor/laravel-hooks) package would provide a standardized and flexible way to inject custom code at desired locations within the application. This could greatly enhance the project's extensibility and allow for easier customization without the need for extensive modifications.

### Describe alternatives you've considered

None so far. The millat/laravel-hooks package seems to be a suitable and robust solution for the customization needs in Laravel.

**Comment by devansh-webkul** [comment]
We already have a list of events dispatched before and after every operation and also we have several modules that are already listening to those events you cant try that.
