### ISSUE TITLE
Mandatory Field like Visible Individually, Status and Guest Checkout when create and update, Validation not appearing. we are able to save the product without enabling them.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9276]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Mandatory Field like Visible Individually, Status and Guest Checkout when create and update, Validation not appearing. we are able to save the product without enabling them.

### Preconditions

1. Admin Should be logged in.

### Steps to reproduce

1. Go to Admin -> Catalog  -> Products -> Create any type of product.
2. Fill all the details -> In side Drawer -> Do not select Visible Individually, Status and Guest Checkout.
3. Check there Asterick mark is present.
4. Save the product.
5. We are able to save the product.

### Expected Result

There should be either validation or the asterik mark should be removed.

### Actual Result

Currently we are able to save the product.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/8eb98bf5-b65b-4bb5-b041-619a99219c01

**Comment by suraj-webkul** [comment]
In the case of a checkbox or switch, the value is always returned when the form is submitted. If the checkbox or switch is enabled, the value will be 'true' or '1' and if it is disabled, the value will be 'false' or '0'

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue is Invalid, as this is a mandatory field which is mentioned in the Attribute, It can be updated according to user requirements, hence this is an invalid issue, hence I am closing the issue.

**Please find the Screenshot [here](https://prnt.sc/oPhjeYqqRE7y)**
