### ISSUE TITLE
where is development document

### ISSUE THREAD

**Issue by mengdodo** [bagisto/bagisto#928]
i want to development  a shop by this project ,but where is development document?

 how can overwrite some modules is security?

please response for me

**Comment by saurav-webkul** [comment]
Hi @mengdodo, to let you know, the dev documentation is completed and will be live soon this week. We are just adding a few more of the functionalities.

**Comment by rahulshukla-webkul** [comment]
Hi @mengdodo 

Here is link for devdocs - https://devdocs.bagisto.com/.
