### ISSUE TITLE
UI issue in the Admin login and customer login button in GUI installation.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9292]
**Describe the bug**
After installing bagisto with the help of GUI, there we can see that the UI issue is appearing after the installation.

**To Reproduce**
1. Go to Bagito Link -> https://github.com/bagisto/bagisto
2. Take clone -> run composer create-project
3. Open the project in Localhost 
4. Complete the form filling and instructions.
5. Now when all the installation is complete we can see the UI issue.

**Expected behavior**
Both Admin and Customer buttons should appear seperataly.

**Screenshots**

Please find the screenshot [here](https://prnt.sc/W95j6fJgizkE)

**Comment by shivendra-webkul** [comment]
@ashishkumar-webkul sir issue not replicated please check https://prnt.sc/rOyU2O6smXY8

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 
as we have checked together with fresh installation and  this issue is still appearing. Please fix the issue.

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 

Checked and Found that the UI issue has been fixed -> https://prnt.sc/EabTpzdeDpjP

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the PR has been merged and issue has been fixed, hence I am closing the issue.  Please check  the screenshot after the fresh installation,[here](https://prnt.sc/tDM97bhuR-uA)
