### ISSUE TITLE
Localization for short description/description doesn't work

### ISSUE THREAD

**Issue by hqakva** [bagisto/bagisto#9319]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

I create several locales on channel, e.g **EN** and **DE**, then I added one product.
For description, I added "EN desc" then switch to DE, I added "DE desc" then save product. After that edit product again and "EN desc" is lost, "DE desc" is applied for both languages 

### Preconditions

Use latest 2.0.0

### Steps to reproduce

I create several locales on channel, e.g **EN** and **DE**, then I added one product.
For description, I added "EN desc" then switch to DE, I added "DE desc" then save product. After that edit product again and "EN desc" is lost, "DE desc" is applied for both languages 

### Expected Result

Product description must update correctly in correct languages. If we don't change description in a single language, then the description (or other attributes) must not change

### Actual Result

Change description in one language will change descriptions in other languages

**Comment by ashishkumar-webkul** [comment]
@hqakva 

Thank you so much for reporting the issue. 

Here is an explanation of how the localization of the Description and Short Description is managed:

1. When creating a product, let's assume the Admin Default Locale is English. In this case, fill the details in  English Description and Short Description. Save the details for the same.

2. If you want to save the details for another locale, such as Arabic, Dutch, etc., you need to edit the product again. Select the desired locale and fill in the details in the chosen locale. Once the Description and Short Descriptions are added in the respective locale, save it again.

**Result**

Please refer to the video for a better understanding of the issue.

https://github.com/bagisto/bagisto/assets/92721837/b897f9e9-e5ec-412e-921c-65874a8b0616

**Comment by ashishkumar-webkul** [comment]
@hqakva 
I hope so that you have understood the concern and hence I am closing the issue. Thank you so much for your contribution.
