### ISSUE TITLE
Getting incorrect price of product in case of configurable product if custom attribute of select type is used.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#932]
- Framework Version: 0.1.5

![Screenshot (41)](https://user-images.githubusercontent.com/45203177/58152069-28e57180-7c89-11e9-965d-a957f19f0323.png)
![Screenshot (42)](https://user-images.githubusercontent.com/45203177/58152081-34389d00-7c89-11e9-938f-1a535147beb5.png)

**Comment by jitendra-webkul** [comment]
Fixed in master branch

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.5

Fixed

![Screenshot from 2019-06-07 14-54-31](https://user-images.githubusercontent.com/45203177/59094633-33b02f80-8934-11e9-9192-d76ec9d5c772.png)

![Screenshot from 2019-06-07 14-54-35](https://user-images.githubusercontent.com/45203177/59094656-3e6ac480-8934-11e9-919c-a5f38448dcb4.png)
