### ISSUE TITLE
Webhooks for Specific Events in Bagisto

### ISSUE THREAD

**Issue by matts93** [bagisto/bagisto#9323]
### Is your feature request related to a problem? Please describe.

It is difficult to integrate external automated actions with Bagisto because it does not currently support webhooks for events such as new orders or user registrations. This lack limits the possibilities of interaction between Bagisto and other systems or applications.

### Describe the solution you'd like

I would like Bagisto to implement a webhook feature that allows you to send API notifications to external systems when certain events occur, such as the creation of new orders, the registration of new users, or an order shipped

**Comment by jitendra-webkul** [comment]
We trigger events for each action, allowing you to connect with specific events and call external APIs.

After Order Creation Event in RegistrationController:
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Shop/src/Http/Controllers/Customer/RegistrationController.php#L89


After Order Creation Event in OrderRepository:
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Sales/src/Repositories/OrderRepository.php#L97


To integrate with these events, you can refer to the following example in the EventServiceProvider:
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Product/src/Providers/EventServiceProvider.php


Feel free to hook into the relevant event based on your requirements and execute your desired external API calls.


Available Events:
https://devdocs.bagisto.com/2.x/advanced/events.html#manually-registering-listeners

**Comment by jitendra-webkul** [comment]
I hope the above reply answers your question. I am closing this issue, feel free to reopen it if you have any more queries.

**Comment by stockarea** [comment]
Why not have webhook support?
For subscribing to events you actually have to open source code and do your things. Why not just have webhooks for easy and seamless data flow?
