### ISSUE TITLE
Unknown array key "it"' error when saving a new image_carousel theme without images in the Italian admin panel of Bagisto 2.0

### ISSUE THREAD

**Issue by matts93** [bagisto/bagisto#9328]
**Describe the bug**
When attempting to create a new theme in the Italian administrator version of Bagisto 2.0 (master version with the latest corrections), specifically when adding a new carousel without images, the process results in an 'Undefined array key "it"' error. Although the theme is saved in the database, it is not visible in the theme administration panel. Additionally, adding images to the carousel does not display any errors, but the images are not shown on the frontend, nor are they visible in the backend theme administration panel. The data is inserted only in the theme_customizations table and not in the theme_customization_translations table.

**To Reproduce**

Go to the 'Themes' section in the Italian version of the administrator panel.
Click on 'Add New Theme'.
In the 'Carousel Images' section, attempt to save without adding images.
Encounter error 'Undefined array key "it"' and note that the theme is saved in the DB but not visible in the theme administration panel.
Try adding images to the carousel and observe that there are no errors, but the images do not appear on the frontend and the admin panel, with entries only in the theme_customizations table.

**Expected behavior**
The expected behavior is that after saving a new carousel in the theme, it should be visible in the theme administration panel, and any added images should be visible both on the frontend and in the theme administration panel. The data should be correctly inserted into both theme_customizations and theme_customization_translations tables.

**Additional context**
The issue seems to be related to the localization process in the theme creation, where the Italian language key does not seem to be properly recognized . This problem may be affecting both the display logic in the admin panel and the data storage process for theme configurations.

**Additional Information**

Bagisto Version: 2.0 (Master with latest corrections)
Environment: Administrator Panel
Locale: Italian (it)
Section: Settings > Themes > Add New Theme

**Comment by ashishkumar-webkul** [comment]
Checked and Found that issue is appearing, and also this issue is appearing for all locales. Please check the  video for reference. 

**Video**


https://github.com/bagisto/bagisto/assets/92721837/f29fef79-4864-4008-882b-21bd745d9762

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 

As I have checked the PR and here a new issue is appearing, when I am saving the image crousal information without any information, it is getting saved and also entry is rasied in the Database. but when we check the Admin end, there we are unable to see the entry.

Please check the video.


https://github.com/bagisto/bagisto/assets/92721837/df07f517-e587-440a-b630-42e37158e9d2
