### ISSUE TITLE
Cart Rule applied if we have selected NO in Apply to Shipping and Free Shipping condition. 

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9333]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

After creating a cart rule and there in cart rule,  **Action Section** there I have selected **NO** in Apply to shipping and Free shipping. 
Now when we checkout a product and select the shipping method and then add Cart Coupon, there we can see that the coupon is applied.

### Preconditions

1. Admin Should be logged in.
2.  Products should be created.

### Steps to reproduce

1. Go to Admin -> Marketing -> Promotions -> Cart Rule.
2. Create a Cart Rule -> In Action Section -> Select Shipping related details **NO**
3. Save the details.
4. Go to Shop Front -> Add product to cart -> Proceed to checkout
5. Add Address details -> Select shipping method -> Now add Cart Coupon
6. Check there we can see that the coupon is applied.

### Expected Result

Coupon should not be applied.

### Actual Result

Please check the video for the reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/5acb684d-4ad5-4179-a48d-213b3fe8040f

### Screenshots

Please check the screenshots for the reference.

Admin -> https://prnt.sc/W-9jxyOW4su3
User -> https://prnt.sc/A9DqVkQl5tv4
User -> https://prnt.sc/efYgRtt8GpMM

**Comment by devansh-webkul** [comment]
This is not an issue. In all the cases coupon will get applied.

-> If apply to shipping is enabled then discounts will get applied on the shipping rate also, for example,

item price is 100
shipping price is 10
fixed discount is 10

discount amount will be on item and shipping also,
item price will be 90
shipping price will be 0
total discount 20

-> if apply to shipping is disabled then dicount will not get applied on the shipping rate,

item price is 100
shipping price is 10
fixed discount is 10

discount amount will be on item and shipping also,
item price will be 90
shipping price will be 10
total discount 10

**Comment by ashishkumar-webkul** [comment]
As per the discussion I am closing the issue as it seems to be an invalid issue.
