### ISSUE TITLE
Catalog Rule is Inactive still we are able to see that the rule is applied.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9352]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

Created a new catalog rule and  status of the Catalog Rule is Inactive, when we check the store front, there we can see that the catalog rule is applied.

### Preconditions

1. Admin Should be logged in.

### Steps to reproduce

1. Go to Admin -> Marketing -> Promotions -> Create a Catalog Rule -> Status Inactive.
2. Go to Shop Front -> Check the products -> Rule Applied in Inactive State.

### Expected Result

The Rule should not be applied when in Inactive State.

### Actual Result

Please check  the video for the reference. 

**Video**

https://github.com/bagisto/bagisto/assets/92721837/304b12bd-5131-4372-8901-c8c980453589

### Screenshots

Admin End  -> https://prnt.sc/9GlZHxcFiJLu
Shop Front  -> https://prnt.sc/3HOcbawSI730

**Comment by sunarcrajneesh** [comment]
@ashishkumar-webkul,
We will be happy to work on it. Could you please assign this to us?

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul 

Please check this Issue, it is appearing. Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/704c39e5-f255-4bf1-89ef-13edcab629e3

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul 

@suraj-webkul 

Checked and Found that now the catalog rule is working fine,
Check in Active and Inactive State
Changed the condition and checked.
Changed the price of the product to check the condition.
Checked the details in product page.
Admin end conditions are not switching now, they are working fine.

Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/9ddf0c6b-8256-4f6f-a932-2f10854602ce

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul

Checked and Found that now the catalog rule is working fine,
Check in Active and Inactive State
Changed the condition and checked.
Changed the price of the product to check the condition.
Checked the details in product page.
Admin end conditions are not switching now, they are working fine.
Cheked the Status of Catalog rule with Special Price and working fine.

Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/3618cfcf-d485-4602-b3d6-9d83ef6ce20a
