### ISSUE TITLE
Cash on delivery payment method available when ordering only downloadable or virtual products.

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#9360]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

When ordering only downloadable or virtual products, the cash-on-delivery payment method is available.

### Preconditions

Downloadable and virtual products should be created and customer should be logged in.

### Steps to reproduce

1. Go to 'shop'
2. Add only downloadable and virtual products in cart.
3. Continue to checkout.

### Expected Result

Cash on delivery payment method should not be available when ordering only downloadable or virtual products.

### Actual Result

Cash on delivery payment method available when ordering only downloadable or virtual products.

**Comment by devansh-webkul** [comment]
We don't provide cash on delivery for downloadable and virtual products. Because the product is not physical.

**Comment by sunarcrajneesh** [comment]
@devansh-webkul,
Of course, cash on delivery should not be available for non-physical products, but Bagisto is providing it.
