### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by devit-chea** [bagisto/bagisto#938]
Notice: Undefined index: DB_HOST in C:\Users\devitchea\Desktop\All Learining\Learn laravel\bagisto\public\installer\install.php on line 36

Notice: Undefined index: DB_USERNAME in C:\Users\devitchea\Desktop\All Learining\Learn laravel\bagisto\public\installer\install.php on line 37

Notice: Undefined index: DB_PASSWORD in C:\Users\devitchea\Desktop\All Learining\Learn laravel\bagisto\public\installer\install.php on line 38

Notice: Undefined index: DB_DATABASE in C:\Users\devitchea\Desktop\All Learining\Learn laravel\bagisto\public\installer\install.php on line 39

Notice: Undefined index: DB_CONNECTION in C:\Users\devitchea\Desktop\All Learining\Learn laravel\bagisto\public\installer\install.php on line 40

Notice: Undefined index: DB_PORT in C:\Users\devitchea\Desktop\All Learining\Learn laravel\bagisto\public\installer\install.php on line 41

How can I fix it?

**Comment by rahulshukla-webkul** [comment]
Hi @devit-chea 

This error was with our old version of bagisto. Please download latest one from git repository.
Here is link -https://github.com/bagisto/bagisto

Thanks
Rahul Shukla

**Comment by devit-chea** [comment]
Thank you
