### ISSUE TITLE
Error in Inserting Products with Video in the Bagisto Administrator Panel

### ISSUE THREAD

**Issue by matts93** [bagisto/bagisto#9399]
**Describe the bug**
In the Italian administrator panel of the latest correct version of Bagisto, a problem occurs when inserting products with videos. After filling out a product's details and adding a video, the save fails to insert the product correctly, as if an error occurred, but no specific error message is displayed.

**To Reproduce**
Go to "Catalog" > "Products".
Click on "Create Product".

**Expected behavior**
Your product should be successfully entered into your system after saving, including details and associated video. In case of an error, a specific message should indicate the cause of the problem.
This issue may be related to the media file management system or product placement module.

**Additional context**
Bagisto version: 2.0 (Master with latest fixes)
Environment: Administrator Panel
Localization: Italian (it)

**Comment by ashishkumar-webkul** [comment]
Checked and found that we are able to save the products with the Video, but the concern which is appearing  here is that we are unable to see the video in Product page.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/1fdd8ee6-ea3e-4d46-a112-b3e41a951944

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue have been fixed and PR have been merged, hence I am closing the issue. Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/1e569aae-6a47-4717-a409-06c515e8b5df
