### ISSUE TITLE
Incorrect Selection of Variants for Changing Prices in Configurable Product

### ISSUE THREAD

**Issue by matts93** [bagisto/bagisto#9400]
**Describe the bug**
When using the quick price change function for configurable products in the Bagisto admin panel, the selection via the drop-down menu does not respect the specified parameters. Variants that do not match the set parameters are also selected, which leads to price changes even for unwanted products.

**To Reproduce**
Access the Bagisto Administrator Panel.
Navigate to "Catalog" > "Products" and select a configurable product.
Click on "Edit Product".
Scroll down to the "Edit Prices" section.
Use the drop-down menu to select specific variants of the configurable product (for example, Black color, TOP grade, 64GB memory).
Note that other variants not matching the selected parameters are also included in the selection.
Any price changes applied will also affect these unwanted variations.

**Expected behavior**
The drop-down menu should only select variants that match the parameters chosen by the user. Price changes should only apply to correctly selected variants.

**Screenshots**
![1](https://github.com/bagisto/bagisto/assets/22118523/21d54f1f-831c-4d38-83ef-a07807bc1b9d)
![2](https://github.com/bagisto/bagisto/assets/22118523/ac4433de-78dd-4edb-9222-5164d4c92402)
![3](https://github.com/bagisto/bagisto/assets/22118523/3e774a8a-44f6-46b9-9ebb-53595cf36c81)

**Additional context**
Bagisto version: 2.0 (Master with latest fixes)
Environment: Administrator Panel
Localization: Italian (it)

**Comment by ashishkumar-webkul** [comment]
@matts93 

When we are seleting any opotion in the Select Varient, Let Suppose in your case you have selected 
 Colore-> New
 Grado -> ECCELLENTE
 Memoria -> 64 GB
 
that means it will check and verify that which all varients are having these options, if any of the option selected  like 64GB. ECCELLENTE etc, then all the varients which are having these information will appear in mass price updating section.

Hence this is not a issue.

i hope that you are clear with the concern, You may check below video for the same.

**Video**
 

https://github.com/bagisto/bagisto/assets/92721837/460f62eb-bb1b-4fc5-8267-432ac11c92fb


Looking Ahead for your reply.

Thank You. Really appreciated for your contribution.

**Comment by matts93** [comment]
If we select those variants, the products that contain only those variants and not one of these should be selected
https://github.com/bagisto/bagisto/assets/22118523/09ee0edc-8060-4318-a4a2-9dbdc22adb36
