### ISSUE TITLE
Can not login as Admin user

### ISSUE THREAD

**Issue by devit-chea** [bagisto/bagisto#943]
It shows message error "**Please Check Your Credentials And Try Again**"
Email and password

email:admin@example.com
password:admin123

**Comment by rahulshukla-webkul** [comment]
Hi @devit-chea 

If you install through installer then you get a form to set admin credentials, kindly enter those credentials other wise check on database & reset it.

Thanks
Rahul Shukla

**Comment by devit-chea** [comment]
Thanks you
