### ISSUE TITLE
User account refund.

### ISSUE THREAD

**Issue by CatalinRobert** [bagisto/bagisto#9430]
### Is your feature request related to a problem? Please describe.

Is it possible for a user to make a refund? I mean... maybe as a user who buys something wants to make a refund.

### Describe the solution you'd like

As a user, or as a guest, I should be able to make a refund based on order id.

### Describe alternatives you've considered

Hmm... Is it possible to exist this feature? I looked through user dashboard and all I could see was only the admin dashboard refunds. Thanks.

**Comment by ashishkumar-webkul** [comment]
@CatalinRobert,

**Thank you so much for your contribution. We really appreciate it.**

Regarding your concern about refunding from the user account, we have a module called **RMA**. You can find the link to it **[here](https://github.com/bagisto/bagisto-rma.git)**.
With **RMA**, users can create a request for **return** or **exchange**. Once the return request is accepted and the product is received by the admin, the admin proceeds with the refund process. This is how it works.
I hope I was able to clarify your concern.

You can also check out this blog post for more information on Laravel eCommerce RMA: https://webkul.com/blog/laravel-ecommerce-rma/

For now I am closing the Feature Request, In case you have any doubt do let us know, we would really love to help you.
