### ISSUE TITLE
Paypal smart button not working. It's giving Order Id issue.

### ISSUE THREAD

**Issue by mabehiry** [bagisto/bagisto#9436]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0.0

### Issue Description

I tried PayPal with both Sandbox as well as Live version for PayPal smart button feature of Bagisto.
When we click on PayPal button on Checkout page, the alert box popups saying "something went wrong" and when we see the console, it shows the issue with the order id.

I am sure about the correct client ID and secret key. I have also setup the same currency as per my PayPal account.

### Preconditions

I use it on the production url:
https://ipecexpress.co.uk/

### Steps to reproduce

1- Enable PayPal Smart Button in admin panel
2- Add items into the cart
3- Fill up the chekout form and choose PayPal Smart Button.

### Expected Result

Showing PayPal page

### Actual Result

PayPal page hides after seconds and gets the following error in the console:
{err: 'Error: Expected an order id to be passed\n    at ht…m4TZKaZxCzYO742rToZGQqHWjz-&currency=USD:3:15912)', timestamp: '1707505453105', referer: 'www.paypal.com', sdkCorrelationID: 'f625515f3b2f6', sessionID: 'uid_5e87837a48_mtg6nde6mju', …}
buttonCorrelationID: "f34789345c3fb"
buttonSessionID: "uid_c4cadd9f04_mtg6ntk6ntm"
clientID: "AaItk-4xAoqC4khdBnPAsTd9Bu2iop..........."
env: "production"
err: "Error: Expected an order id to be passed\n    at 
referer: "www.paypal.com"
sdkCorrelationID: "f625515f3b2f6"
sessionID: "uid_5e87837a48_mtg6nde6mju"
timestamp: "1707505453105"
token: null

### Screenshots

![Screenshot_1](https://github.com/bagisto/bagisto/assets/33180080/7a7339fb-1069-4d88-86bb-870a38c4ac7f)

**Comment by suraj-webkul** [comment]
Hello, [mabehiry](https://github.com/mabehiry).
We are currently testing, and it appears there is no issue. We need to update the correct client ID and client secret ID for making payments using PayPal.

**Comment by suraj-webkul** [comment]
Please find the [video](https://webkul.chatwhizz.com/share/view-recording/65ca1fc574648505848f75e8)

**Comment by ashishkumar-webkul** [comment]
@mabehiry 

Thank You so much for your contribution for Bagisto, we really appreciate it.

Now as per the concern related to PayPal Smart Button. I have added proper details in Admin end  settings and then processed with the checkout. I was able to place the order successfully, hence No issue found. So I am closing the issue for now.

In case you find any such issue related to PayPal, do let us know with the details how you found the issue, we would love to help you in you rr concern.

**Please check the video for reference.**

**Video**


https://github.com/bagisto/bagisto/assets/92721837/b2ad3c27-a60e-4758-a7ef-2900dd28c1ea
