### ISSUE TITLE
Mobile view should be responsive -Front end

### ISSUE THREAD

**Issue by nikita-webkul** [bagisto/bagisto#9442]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

On the mobile view 

### Preconditions

The customer should be logged in 

### Steps to reproduce

1. Go to 'front end .'
2. Open the application on the mobile view 
3. scroll left to right or right to left 

### Expected Result

The mobile view should be responsive.

### Actual Result

Front-end mobile view is not responsive. getting issue 

### Screenshots

please find the attachment here

https://github.com/bagisto/bagisto/assets/146415222/0f71597b-5955-4c6f-93df-13549dbbfa36

**Comment by ashishkumar-webkul** [comment]
@amit-webkul 

Checked and Found that the issue has been fixed and working fine, please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/4d4c68c3-dff9-47e3-a92f-1fc8bbdde686

**Comment by ashishkumar-webkul** [comment]
Checked and found that the issue has been fixed and working fine and PR has been merged. Hence I am closing the issue, please find the screenshots below.

https://prnt.sc/dm9L1Xst77TI

https://prnt.sc/YAmae9chQqNe

https://prnt.sc/s3ZrMCzBgZ9E
