### ISSUE TITLE
Admin add product "compact(): Undefined variable: allProducts"

### ISSUE THREAD

**Issue by angemort** [bagisto/bagisto#946]
By deleting "**allProducts**" in **bagisto\packages\Webkul\Product\src\Http\Controllers\ProductController.php**, seems to solve the problem.

![image](https://user-images.githubusercontent.com/41084492/58328105-9207e900-7e31-11e9-8e3a-f671c53c8319.png)

**Comment by rahulshukla-webkul** [comment]
Hi @angemort 

We have removed this variable as it is giving error & updated code on our master. Please take latest pull.

Thanks
Rahul Shukla

**Comment by angemort** [comment]
it seemed to me that I had taken the latest version.
Thank you
