### ISSUE TITLE
Refresh cart on payment update

### ISSUE THREAD

**Issue by stefano73it** [bagisto/bagisto#948]
When you go back to previous steps in the Checkout onepage and change the payment method, the new value is not displayed in the Review section. The cart must be saved after saving the payment.

**Comment by jyoti-webkul** [comment]
Verified.
Getting this issue , changed payment method doesn't reflect on checkout

**Comment by jitendra-webkul** [comment]
Hi @stefano73it ,

Issue has been fixed, thanks for pointing out

**Comment by jyoti-webkul** [comment]
Framework version: 0.1.6

Not Fixed

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.6

------------------------------------
Fixed
