### ISSUE TITLE
Type filter in product catalog not working

### ISSUE THREAD

**Issue by Dansday** [bagisto/bagisto#9489]
### Terms

- [ ] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.0

### Issue Description

Hello. I try what's bagisto new feature in latest release and found a bug that's in filter section for type filter is not working. Can you help me to what's the quick fix to solve this?

### Preconditions

i'm using kalilinux and windows 11 to test it using local environtment

### Steps to reproduce

1. Go to Admin
2. Click on product catalog
3. Select any type in filter
4. See error the product not showing

### Expected Result

![image](https://github.com/bagisto/bagisto/assets/50676898/92cc4818-67cb-4106-84a6-8ddcd8bfc16b)

### Actual Result

![image](https://github.com/bagisto/bagisto/assets/50676898/1c803274-c508-480d-8f38-372677b0635d)

**Comment by ashishkumar-webkul** [comment]
@Dansday 

Thank you so much for the concern and brining the issue to light. We really appreciate  that, we will be fixing the issue and will update you for the same.

@amit-webkul 

Kindly check the video for the reference.

**Video**

**Comment by ashishkumar-webkul** [comment]
@Dansday 

Hello There,

The issue has been fixed and PR have been merged, please take the latest code pull from master. You can check the  video for reference.

Thank You so much for your contirubution.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/9c8380f4-ed5b-4cb2-8e65-c339987d4cc3
