### ISSUE TITLE
Refresh order summary on every checkout step

### ISSUE THREAD

**Issue by stefano73it** [bagisto/bagisto#949]
When you go back to previous steps in the Checkout page, and change the shipping method, the order summary is not updated with new shipping cost. The order summary should be refreshed on every step, in order to display all current values.

**Comment by jitendra-webkul** [comment]
Hi @stefano73it ,

Issue has been fixed, thanks for pointing out

**Comment by jyoti-webkul** [comment]
Framework Version: 0.1.6

---------------------------------------

Fixed
