### ISSUE TITLE
Buy Now Button does not work

### ISSUE THREAD

**Issue by webkul** [bagisto/bagisto#95]
http://demo.bagisto.com/products/leather-shoes
Here are the steps the reproduce 
- visit the link
- http://demo.bagisto.com/products/leather-shoes 
-choose any option from the attitbute as dropdown 
![image](https://user-images.githubusercontent.com/519857/47599383-7a1ad480-d9ca-11e8-8de7-6595f897604a.png)

**Comment by jitendra-webkul** [comment]
Buy Now button is working properly now.

**Comment by jitendra-webkul** [comment]
![download](https://user-images.githubusercontent.com/39991107/47784085-969c7100-dd2a-11e8-8065-03006f32f44e.png)

By clicking on invoice button in order view page.
