### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by MrPayam** [bagisto/bagisto#950]
Hi
I try to run this on windows with xampp and php version is  7.2.10 and when enter php artiasn migrate it says:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null,

should I have maria db while using mysql ?

**Comment by rahulshukla-webkul** [comment]
Hi @MrPayam 

Kindly check your MariaDB version, Bagisto need 10.2.7 or Higher.

Thanks
Rahul Shukla

**Comment by MrPayam** [comment]
@rahulshukla-webkul  finally bagisto Run after updating maria db with [this](https://stackoverflow.com/questions/44027926/update-xampp-from-maria-db-10-1-to-10-2) topic
-
the visual installer (on browser) dosent work and I use the cmd ...
thx man, bagisto seems to be perfect ...
