### ISSUE TITLE
document.onreadystatechange not fired in Opera

### ISSUE THREAD

**Issue by stefano73it** [bagisto/bagisto#951]
Opera browser does not fire document.onreadystatechange. It must be replaced with $(document).ready(), without considering the readyState value.

**Comment by rahulshukla-webkul** [comment]
Hi @stefano73it 

Thanks for notifying this to us. We will update it.

Thanks
Rahul Shukla

**Comment by rahulshukla-webkul** [comment]
Hi @stefano73it 

We have updated it & thanks for observation.
