### ISSUE TITLE
mb_strimwidth error

### ISSUE THREAD

**Issue by CatalinRobert** [bagisto/bagisto#9516]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0

### Issue Description

ON category page or admin dashboard products; When I try to enter the product page template I receive mb_strimwidth error;

### Preconditions

All set. The issue is not related to all the products, just part of them.

### Steps to reproduce

1. Go to 'a category page/dashboard products page'
2. Click on 'a product to see the offer'
4. See error "Call to undefined function Illuminate\Support\mb_strimwidth() (View:"

### Expected Result

See the normal product with all details and so on.

### Actual Result

Error.

### Screenshots

![image](https://github.com/bagisto/bagisto/assets/47644093/91e0b258-70b5-463e-b57f-10ec13280c31)

### Additional context

this issue happens from a few days when I started adding new products. Old products are ok.

**Comment by ghena** [comment]
install mbstring and retry:

https://stackoverflow.com/questions/14254943/call-to-undefined-function-mb-strimwidth
