### ISSUE TITLE
Allow to validate cart item before adding

### ISSUE THREAD

**Issue by stefano73it** [bagisto/bagisto#952]
The product add in cart should file a "validate" event with halt, in order to perform some validation and return to product page if there's something wrong:

public function add($id)   {
   try {
      	$result = Event::fire('checkout.cart.add.validate', $id, TRUE);
        if (!empty($result)) {
            	session()->flash('error', $result);
            	return redirect()->back();
         }

         Event::fire('checkout.cart.add.before', $id);
         ......................................................................

**Comment by jyoti-webkul** [comment]
Functionality is already implemented from version 0.1.5
