### ISSUE TITLE
Proceed Button disappears when clicking on Shipping Address checkbox  in Checkout. Shipping Details should not appear for Virtual and Downloadable product. 

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9536]
### Is your feature request related to a problem? Please describe.

**Bagisto Version** - **V2.1.0**

**Pre-Conditions**

1. Guest User/Logged in User checkout process.
2. Add virtual product or downloadable product (for logged in customer)

**Description**

When we checkout a Virtual or Downloadable product, there when we selecte the checkbox for the shipping method. We can see that the Proceed button disappears. 

**Actual Result**

1. Proceed button disappears hence we are unable to select the payment method.
2. After unselecting the shipping check box we can see the payment options and then we can checkout.

**Video for reference**

https://github.com/bagisto/bagisto/assets/92721837/904a3314-ac45-4b90-9039-0b07f902ae5e

### Describe the solution you'd like

**Expected Result**

For Products like Virtual and Downloadable, we should not show the shipping related concern.

If in case we are showing shipping address then Proceed button should not hide.

**Comment by jitendra-webkul** [comment]
Already fixed in #9547
