### ISSUE TITLE
Allow to save address2 field in Checkout page

### ISSUE THREAD

**Issue by stefano73it** [bagisto/bagisto#954]
A custom layout for the checkout onepage may have the address2 field, so that field must be saved in the saveCustomerAddress().

**Comment by rahulshukla-webkul** [comment]
Hi @stefano73it 

We have already implemented it. While checkout, When customer add any new address then it can be save as address of customer.

Thanks
Rahul Shukla

**Comment by stefano73it** [comment]
Hello Rahul,
I don't mean a new address, I mean the "address2" field in the billing/shipping address. See packages/Webkul/Checkout/src/Cart.php, there's only the address1 field.

**Comment by rahulshukla-webkul** [comment]
Hi @stefano73it

Off course , we can add this field but we are using Lines in a Street Address Field( https://prnt.sc/nud6t4) in which we can add lines for our address & it will display on checkout page.(https://prnt.sc/nud8eo) thats why we are not using address2 field.

Thanks
Rahul Shukla
