### ISSUE TITLE
For Guest User when we click on downloadable product add to cart button it should directly redirect to Login Page.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9542]
### Is your feature request related to a problem? Please describe.

For Guest User when we click on downloadable product add to cart button it should directly redirect to Login Page. Currently we can see that the product is added to cart and then in Main cart or mini cart we click on proceed to check out, there we can see that it is redirected to login page.

### Describe the solution you'd like

For Guest User's when clicked on Add to Cart for Downloadable Product, it should redirect to Login page.

**Check Video**

https://github.com/bagisto/bagisto/assets/92721837/9e925103-0d13-44c5-b29e-308177050c19

**Comment by phyothiha** [comment]
@ashishkumar-webkul Is guest checkout supposed to be able to checkout without logging in?

**Comment by ashishkumar-webkul** [comment]
@phyothiha 

Thank You so much for your contribution and we really appreciate it.

Yes, a guest user can complete the checkout process. However, in the case of downloadable products, a guest user cannot proceed with checkout. Only logged-in users can complete the checkout process for downloadable products.

**Comment by ashishkumar-webkul** [comment]
@phyothiha 

As per discussion and checking the details related to the Add to cart functionality. This enchancement is invalid and cannot be processed. Sorry for this but we really do appreciate your efforts towards Bagisto.
