### ISSUE TITLE
After applying a filter on the orders page ,  Sidebar Scroller should be working -Customer end 

### ISSUE THREAD

**Issue by nikita-webkul** [bagisto/bagisto#9567]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.1

### Issue Description

After applying a filter on the orders page,  Sidebar Scroller should be working  on the Customer end 

### Preconditions

The customer must be logged in.
Minimum 5 -6 order to be created 
orders

### Steps to reproduce

1. Go to 'customer end ...'
2. Click on 'orders 
3. Go to the filter section 
4. Apply filter ID name etc,  
5. 5. Sidebar Scroller is not working on the order oage 

### Expected Result

After applying a filter on the orders page ,  Sidebar Scroller should be working

### Actual Result

Currently, not working sidebar scroller after applying filters on the order page scroller

### Screenshots

https://github.com/bagisto/bagisto/assets/146415222/999783f1-ea64-48f5-880f-55e731d12205

**Comment by ashishkumar-webkul** [comment]
Checked and Verified and found the issue.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and working fine. Please find the video for the reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/5a8d0722-6b21-4ee3-b52d-d5c779ccffde
