### ISSUE TITLE
In Tax Rates -> Zip Code Status toggle button is not visible after saving the details and also in Tax Rates Datagrid Zip Code Column entry is empty.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9590]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.1

### Issue Description

When we are creating a new tax rates and in tax rates we have selected zip code toggle button active, and after entering the details and saving them. In the Tax Rate Datagrid there we can see Zip code colum is empty and also when we edit the tax rate with zip code we are unable to see the Status toggle button.

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to Admin -> Settings -> Taxes -> Tax Rates.
2. Tax Rates -> Create a Tax Rate with Zip Code.
3. There we can see that the status button is active and zip code is added.
4. Save -> Check the Zip Code Column -> Entry is empty.
5. Also Now Edit and  there we can see that the status toggle button is missing.

### Expected Result

1. Status Toggle Button should be visible and also we can change status of zip code according to our requirement.
2. Zip Code column in the Tax Rates Datagrid should have entry.

### Actual Result

Currently we can see that entry is not appearing and also we can see that the status toggle button is not appearing.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/648126d3-119b-456a-890c-6c6f855c4b81

### Screenshots

Please find the screenshot below.

Database -> https://scrsht.com/aa45da2c

Admin End -> https://scrsht.com/ed3f6e93
Admin End -> https://scrsht.com/03310e14

**Comment by shivendra-webkul** [comment]
@ashishkumar-webkul Not an issue. This toggle button serves as a switch between selecting a zip range and a single zip code. When 'zip range' is selected, updates should not be permitted. 
https://prnt.sc/AdeFD8QRmqI8

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul As per discussion it looks that this is an invalid issue hence I am closing the issue from here.
Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/859d1b7a-eeb0-4a2b-9e79-8f8fd9a1b829
