### ISSUE TITLE
Bundle products do not allow configurable products to be added

### ISSUE THREAD

**Issue by arne-s** [bagisto/bagisto#9594]
**Describe the bug**
It is in the latest version not possible to add configurable products to a configurable products. 
I am not sure if this is a bug or intentional, but in my current shop nearly all products are configurable products, so not being able to add configurable products would make the bundle option unusable. 

**To Reproduce**
- Create new bundle product
- Click on "Add product" in the "Group Products" section
- The configurable products are not listed whatever the search query

**Expected behavior**
The configurable products should be able to be added

**Additional context**
I'm using version 2.1.1 but the issue is also present in the current Bagisto Demo

**Comment by jitendra-webkul** [comment]
Please note that only simple products are eligible for addition to the configuration, bundle, and grouped product types.

**Comment by Dunicotech** [comment]
Is this a feature which is going to be add in the future?
