### ISSUE TITLE
http://127.0.0.1/api/products?new=1&sort=created_at-desc&limit=24

### ISSUE THREAD

**Issue by imanbahmani** [bagisto/bagisto#9607]
### Terms

- [ ] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1

### Issue Description

this address have 500 error!
but after sign in with customer account this api work!

### Preconditions

this address have 500 error!
but after sign in with customer account this api work!

### Expected Result

this address have 500 error!
but after sign in with customer account this api work!

### Actual Result

this address have 500 error!
but after sign in with customer account this api work!

**Comment by devansh-webkul** [comment]
Not able to reproduced this. Also please use Bagisto forum.
