### ISSUE TITLE
Serialization of 'Closure' is not allowed {"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at

### ISSUE THREAD

**Issue by xxl4** [bagisto/bagisto#9609]
**Describe the bug**
Dear All

i always found this error on my error file, Thank you.

`[2024-03-29 16:52:48] prod.ERROR: Serialization of 'Closure' is not allowed {"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Session/Store.php:173)
[stacktrace]
#0 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Session/Store.php(173): serialize()
#1 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(245): Illuminate\\Session\\Store->save()
#2 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(130): Illuminate\\Session\\Middleware\\StartSession->saveSession()
#3 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#4 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#5 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#6 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#7 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#9 /www/wwwroot/Bagisto/packages/Webkul/Shop/src/Http/Middleware/Currency.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\Shop\\Http\\Middleware\\Currency->handle()
#11 /www/wwwroot/Bagisto/packages/Webkul/Shop/src/Http/Middleware/Theme.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\Shop\\Http\\Middleware\\Theme->handle()
#13 /www/wwwroot/Bagisto/packages/Webkul/Shop/src/Http/Middleware/Locale.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\Shop\\Http\\Middleware\\Locale->handle()
#15 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#17 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#18 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#19 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#20 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#21 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#22 /www/wwwroot/Bagisto/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#24 /www/wwwroot/Bagisto/packages/Webkul/Installer/src/Http/Middleware/CanInstall.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\Installer\\Http\\Middleware\\CanInstall->handle()
#26 /www/wwwroot/Bagisto/packages/Webkul/Core/src/Http/Middleware/SecureHeaders.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Webkul\\Core\\Http\\Middleware\\SecureHeaders->handle()
#28 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#30 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#31 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#33 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#35 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#37 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#39 /www/wwwroot/Bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#40 /www/wwwroot/Bagisto/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#41 {main}
"} `

**Comment by xxl4** [comment]
> The error you're encountering, "Serialization of 'Closure' is not allowed," typically occurs when Laravel tries to serialize a session or cache data that contains a Closure. In Laravel, Closures cannot be serialized directly because they may contain context or state that is not serializable (like a live database connection).
> 
> This specific error stems from the Laravel framework's attempt to serialize the session data as part of the request lifecycle, which is indicated by the stack trace involving Illuminate\Session\Store->save() and further operations within the session middleware. It's likely that somewhere in your application, a Closure is being stored in the session or another context that gets serialized.
> 
> Here's how you can approach fixing this issue:
> 
> 1. Identify Where the Closure is Being Stored
>    The first step is to identify where in your application a Closure might be being stored in the session or passed in a way that leads to serialization. Common places to check include:
> 
> Session Data: Look for any part of your application that stores complex data in the session. This includes manually storing objects or arrays that might indirectly contain Closures. Events/Listeners: If you're attaching Closures as event listeners or broadcasting events that might serialize listener data, ensure those Closures are not stored in a way that requires serialization. Cache: Similar to session data, if you're caching complex data, ensure it doesn't contain Closures. 2. Refactor to Remove the Closure Once you've identified where the Closure is being stored, you'll need to refactor your code to remove the Closure from being serialized. This might mean changing how you store data in the session or cache or possibly using a different approach for event listeners that doesn't involve serializing Closures.
> 
> 3. Use Serializable Closure if Absolutely Necessary
>    If for some reason, you absolutely must store a Closure (which is highly discouraged due to the serialization issue), consider using a package like opis/closure to serialize Closures safely. This package provides a way to serialize Closures by extracting the code and context, allowing it to be serialized and unserialized. However, this should be a last resort, as storing simpler data types or using explicit classes and methods is usually a better approach.
> 4. Review Custom Middleware or Packages
>    Given that the stack trace includes paths that suggest this might be happening within a session save operation initiated by middleware and involves a custom or third-party package (Webkul\Shop), review any custom middleware or third-party packages used in your application. These might be storing data in the session inappropriately or hooking into the request lifecycle in a way that introduces serialization issues.
> 5. Update/Review Third-party Packages
>    Ensure that all third-party packages, including Webkul\Shop if it's a third-party package, are updated to their latest versions compatible with Laravel 11. Sometimes, these issues are known and fixed in newer versions of the packages.

Thank you for your reply, i use the default code, maybe need check it.

**Comment by devansh-webkul** [comment]
Please fill up the full issue format. So that we can check. Currently in latest one we are not able to reproduce that.

**Comment by xxl4** [comment]
> Please fill up the full issue format. So that we can check. Currently in latest one we are not able to reproduce that.

Thank you,i have fix it.
