### ISSUE TITLE
Changing UI

### ISSUE THREAD

**Issue by m2ura** [bagisto/bagisto#961]
How to change the UI and use my own?

**Comment by rahulshukla-webkul** [comment]
Hi @m2ura 

**Procedure 1 :-**
You can create custom theme in bagisto. I am sharing link of it - https://bagisto.com/en/create-custom-theme-in-bagisto/

**Procedure 2**
Override our view file, means create a view file inside default view of laravel ( resoureces->views->vendor).
Make sure that folder structure must be same as we used in our package with same file name. 

Thanks
Rahul Shukla
