### ISSUE TITLE
Fields in configuration that use depends do not respect the type chosen

### ISSUE THREAD

**Issue by jbohme** [bagisto/bagisto#9644]
**Describe the bug**
When I select a type, it is not respected when using depends.
It is always created as text.

**Screenshots**
![image](https://github.com/bagisto/bagisto/assets/32618269/b517ea19-9ae5-4245-b857-42f80cff00dd)
![image](https://github.com/bagisto/bagisto/assets/32618269/8c26d4ab-a2ba-474d-8978-e24f7c537ba7)
![image](https://github.com/bagisto/bagisto/assets/32618269/3e373531-c43b-4143-a40e-7f9a011a6213)

**Additional context**
Admin/src/Resources/views/configuration/dependent-field-type.blade.php

**Comment by suraj-webkul** [comment]
Thanks for the update! This bug has already been addressed and fixed. The solution can be found in PR #9711. Appreciate your efforts!
