### ISSUE TITLE
Refunded product status color box is not appearing.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9654]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

After the product, if we refund the product  then the status of the sales order changes to Closed, here the color of closed box is not appearing.

### Preconditions

1. Customer must have ordered a product from shop.
2. Admin must be logged in.

### Steps to reproduce

1. Go to admin -> Sales -> Create Invoice.
2. Now Click on refund. -> Complete all the steps.
3. Check the status color box, it is appearing blank.

### Expected Result

It should reflect color box so that it would be easy to understand the exact status.

Please find the screenshot [here](https://scrsht.com/8d9ecacf)

### Actual Result

Currently we can see that issue is appearing. Please check the screenshot [here](https://prnt.sc/5_FUTl7Tuwju)

**Comment by shivendra-webkul** [comment]
Fixed in this PR - https://github.com/bagisto/bagisto/pull/9656
