### ISSUE TITLE
sorting is not working (price)

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#968]
![Screenshot(58)](https://user-images.githubusercontent.com/47665137/58792068-15cf8b80-8611-11e9-87a7-cdcaabc6542a.png)

**Comment by karkiswapnil** [comment]
Also Filterable options should only show if the product has that attribute i.e. according to attribute family

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

---------------------------------------------
Fixed
