### ISSUE TITLE
Ability to expand all and collapse all in tree view component

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#9685]
### Discussed in https://github.com/bagisto/bagisto/discussions/9683

<div type='discussions-op-text'>

<sup>Originally posted by **hellodit** April 18, 2024</sup>
Hi guys, I want to make my category tree by default show only the root parent level and close all the child levels

The default like this 
![image](https://github.com/bagisto/bagisto/assets/32544683/cac8ca41-2d38-493f-b9fb-589c0e1228da)

I want to make it like this, the tree is closed 
![image](https://github.com/bagisto/bagisto/assets/32544683/911f3ffa-8a6f-4cdd-9e88-a2b2edb2ab38)
 

What should I modify? 

</div>

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 
checked and found that the issue has been fixed, by passing the value of collapse in props and making them true helps to collapse the category branch listing in product page. Hence this is working fine as I have checked the same in RTL and LTR view.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/cd8b3c79-31b7-4d64-b01c-447d52bff7d3

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue has been fixed and PR has been merged and hence I am closing the issue from here. Please check the video for reference.

**video**


https://github.com/bagisto/bagisto/assets/92721837/d14fd717-528b-41c1-a45e-b6f02ad93358
