### ISSUE TITLE
Unable to create a new admin assets build

### ISSUE THREAD

**Issue by dtchkoidze** [bagisto/bagisto#9690]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

I can't make a new build for admin. I've managed to rebuild the CSS assets but not the JS ones. Also, I am quite unsure what version of Vue is actually in the admin Build. Necessary modules seem to be not installed in the Admin package too. 

If this isn't an issue, guide me:  
1. How to create a new build for admin, so that I can fully use the functionality of Vue, JS and CSS files in general. 
2. What is the current situation with the usage of Vue, what version it is in the build.

Thank you in advance.

### Preconditions

Working on the master version of Bagisto.

### Steps to reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error

### Expected Result

I supposed, running `npm run build` in the packages/Admin would create a new build that I could use. 

### Actual Result

Getting the errors, because of absence of modules. After installing modules, getting other errors.

**Comment by amit-webkul** [comment]
Hello, @dtchkoidze,

I hope this message finds you well. I wanted to inform you that in the latest Bagisto version, we have upgraded to Vue version 3.4.19.

Regarding your inquiry, I observed your concern. If you need to generate a new build file for the admin package, please follow the outlined steps below:

1. Navigate to the admin folder using the integrated terminal.
2. Install NPM dependencies by executing the command `npm i`.
3. Generate a new build file by running the command `npm run build`.

By following the above steps, you will successfully create your new build files.

Should you encounter any challenges during this process, please don't hesitate to reach out to us. We are here to assist you every step of the way.

Feel free to ask if you have any further questions or concerns.

**Comment by dtchkoidze** [comment]
Your proposed solution only when bagisto is installed via a git clone. When installing with a composer or any other methods, described in the documentation, it doesn't work.

**Comment by amit-webkul** [comment]
Hello, @dtchkoidze 

I wanted to provide you with an update regarding your query. After conducting another check on your behalf, I'm pleased to confirm that I successfully installed `Bagisto via Composer` and followed the provided steps without encountering any errors. Everything seems to be working smoothly.

However, should you encounter any issues while following the steps, please don't hesitate to reach out. It would be immensely helpful if you could provide us with short videos of the `build process`. This will enable us to identify any potential issues more effectively and offer you the necessary assistance.

Thank you for your cooperation and understanding.

**Comment by devansh-webkul** [comment]
@dtchkoidze,

Please use Bagisto forum,
https://forums.bagisto.com/recent
