### ISSUE TITLE
value is missing for lines in a street address

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#9707]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

In the admin panel the lines in a street address is missing a value

![image](https://github.com/bagisto/bagisto/assets/1594411/9d204b47-703e-4d9e-9431-0d22f83f0d78)

### Preconditions

The issue occurs in the master branch

### Steps to reproduce

1. in the admin interface click on Configure
2. Click on **Address** in the **Customer** section

### Expected Result

the current value should be visible.

### Actual Result

Check the description.

**Comment by ashishkumar-webkul** [comment]
@ghermans 

Thank you so much for bringing the issue to light. We would love to inform you that we have fixed the issue, and it is working fine now. Please check the screenshot for reference [here](https://scrsht.com/ac7fd3ed).

You can check the PR [here](https://github.com/bagisto/bagisto/pull/9710).

Thank you.

**Comment by ashishkumar-webkul** [comment]
Checked and found that the admin configuration for address line. Value has been added, hence I am closing the issue and PR has been merged. Please check the video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/527a1169-0adb-4c36-be75-6daa1e85cc8d
