### ISSUE TITLE
VAT ID is missing in address create form

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#9713]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

In the blade file 
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/address/form.blade.php VAT ID field is missing in the form

### Preconditions

Default master branch

### Steps to reproduce

Check the description.

### Expected Result

The VAT ID field should be added.

### Actual Result

Check the description.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that VAT ID which was missing in the Admin Order Create form was added. Please check the Screenshots for reference.

Issue Screenshot -> https://prnt.sc/-MweVwOJmbMP

Fixed Screenshot -> https://scrsht.com/59004784

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the VAT ID entry has been added to the Admin Order Create Address form. Please check the video for reference, hence I am closing the issue as PR has been merged, please check the video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/b509f4db-096d-4b7f-89e2-31f04d0fabf5
