### ISSUE TITLE
price does not change when options changed at configurable product with variant 

### ISSUE THREAD

**Issue by digicatech** [bagisto/bagisto#9719]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.2

### Issue Description

For products with more than one options (configurable product with variant), the correct price appears when the options are first selected. However, the price does not change when the options are changed.

### Preconditions

Windows 11
Laragon 6
PHP 8.1.10
Apache 2.4.54
Mysql 8.0.30
and 
Linux  4.19.286-203.ELK.el7.x86_64
Apache 2.4.59
Mysql 5.7.23-23

### Steps to reproduce

1. Go to admin and add product with variants. Options should be two or more. And set prices different each other.
2. Go to front and product page and select options. You will see price is true for selected options.
3. Then change any option except the first option.
4. You will see that the price is either not calculated or calculated incorrectly.

### Expected Result

The warrant price selected in accordance with the options appears on the screen.

### Actual Result

You will see that the price is either not calculated or calculated incorrectly.

### Screenshots

![image](https://github.com/bagisto/bagisto/assets/32608447/7545304e-42c1-4017-aa36-c4b4adabe414)
![image](https://github.com/bagisto/bagisto/assets/32608447/47bf7aab-0d95-462a-8a85-e203c78714a8)
![image](https://github.com/bagisto/bagisto/assets/32608447/b35b58c8-40d0-41a5-84f9-7308443bd1a7)

**Comment by digicatech** [comment]
The problem is in the JavaScript code in this file
packages\Webkul\Shop\src\Resources\views\products\view\types\configurable.blade.php

![image](https://github.com/bagisto/bagisto/assets/32608447/6c1c4dee-95cd-4b76-b406-c3129a68faa0)

![image](https://github.com/bagisto/bagisto/assets/32608447/672f7ac9-ccf8-4b5d-a744-3bca8a4af5cb)

**Comment by digicatech** [comment]
The solution below works fine. But you should still take a look.

![image](https://github.com/bagisto/bagisto/assets/32608447/12263584-1908-48fb-a598-a1e6f0622504)

**Comment by ashishkumar-webkul** [comment]
@digicatech 
I have checked and found that the issue is indeed appearing. Kindly review the video and confirm whether you are concerned about this case.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/a8673944-180a-48e4-bd86-beb48bfc15cb

**Comment by digicatech** [comment]
@ashishkumar-webkul 

I mentioned the solution suggestion above.
