### ISSUE TITLE
Heavy download size due to .git of laravel. why that is there?

### ISSUE THREAD

**Issue by imanghafoori1** [bagisto/bagisto#972]
Normally, vendor folder does not contain any .git folder
Why that is there?!
My bagisto is over 700 MB !!!
That impacts the download rate.

![image](https://user-images.githubusercontent.com/6961695/58833167-b94a8b80-8665-11e9-9337-29ce3abc7627.png)

**Comment by prashant-webkul** [comment]
'.git' is a folder responsible for GIT installed on your system. And it does help only in using git operations on your project such as push, pull, clone, etc.

**Comment by imanghafoori1** [comment]
Why .git of laravel is in the vendor folder i have never seen such a thing

**Comment by saurav-webkul** [comment]
Hi @imanghafoori1, the same process is followed in every other laravel project installation. It's not something that we have customised.

**Comment by imanghafoori1** [comment]
Maybe it's because you are using dev-master version of laravel v5.6
