### ISSUE TITLE
Bug in search page with response cache

### ISSUE THREAD

**Issue by althafn96** [bagisto/bagisto#9724]
Search page with response cache on is not working properly. As I understand,you are hashing the response with pathInfo() which only will be "/search" no matter what query params are passed. So it will always return the search results of the first keyword search until the cache is invalidated. Pls fix this

**Comment by ashishkumar-webkul** [comment]
@althafn96

Thank you very much for your attention to this matter. We highly value your contributions to Bagisto.

Regarding your concern, could you please provide us with a more detailed explanation along with a video or screenshot? This would greatly assist us in understanding and addressing the issue effectively.

Your cooperation is greatly appreciated.

**Comment by devansh-webkul** [comment]
Please use Bagisto forum,
https://forums.bagisto.com/
