### ISSUE TITLE
Edit Slider, get wrong with: An invalid form control with name='image[image_0]' is not focusable.

### ISSUE THREAD

**Issue by silasyao** [bagisto/bagisto#973]
An invalid form control with name='image[image_0]' is not focusable.

when I edit slider.

![WechatIMG27](https://user-images.githubusercontent.com/3516626/58855788-7c1ce280-86d3-11e9-976d-f8ceec3847fc.png)

**Comment by silasyao** [comment]
by the way , I used the 1.6 version

**Comment by rahulshukla-webkul** [comment]
Hi @silasyao 

Thanks for notifying us, we are checking & update it.

Thanks
Rahul Shukla

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------------

Fixed
