### ISSUE TITLE
your installation documention is horrible

### ISSUE THREAD

**Issue by nyck33** [bagisto/bagisto#9743]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

9.9.9

### Issue Description

![image](https://github.com/bagisto/bagisto/assets/25189545/f6538a1c-f4e8-4006-bb17-dcdf622f6503)

then again to set .env vars

![image](https://github.com/bagisto/bagisto/assets/25189545/a9fd06a2-a67c-411c-8067-92c7bf7d2e61)

found at https://webkul.com/blog/laravel-ecommerce-website/

values for DB variables differ, why?  Why show it twice? Do I need two separate setups with different values?  

### Preconditions

not sure what to say

### Steps to reproduce

read that web page 

### Expected Result

Be more clear.  

### Actual Result

Give me one set of configurations perhaps just to run a demo which I can go back and edit later as I customize.

### Screenshots

see above

**Comment by devansh-webkul** [comment]
PLease follow this guide,
https://devdocs.bagisto.com/2.x/introduction/installation.html
