### ISSUE TITLE
no product descriptions after following installation instructions

### ISSUE THREAD

**Issue by nyck33** [bagisto/bagisto#9744]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

newest with php 8.1

### Issue Description

I get 
![image](https://github.com/bagisto/bagisto/assets/25189545/e84dd7c3-faa3-4670-aad0-621e25ec6e27)

but nothing is clickable I mean nothing moves to another more descriptive page, is this normal?  I ran all the migrate commands everything so expected a bit more in terms of having a full app instead of just the top page.  

https://webkul.com/blog/laravel-ecommerce-website/

### Preconditions

Installed from composer.  

### Steps to reproduce

install from composer, follow directions on installation instruction page.  

### Expected Result

I'd want a bit more than just a top page to really see your app.  This is very sad.  

### Actual Result

not much to talk about here.

**Comment by devansh-webkul** [comment]
In the starting phase, there are no categories and products. Once you create categories and products, you will be able to see them. For a cleaner look, we have provided a simple design. However, you are free to customize this as needed.

**Comment by nyck33** [comment]
Just to confirm the Github repo, the installation seems to have some `php artisan db seed` command but that does nothing?  I checked some of the tables and they were empty.  Is that correct?  What I want instead is the demo you provide at https://demo.bagisto.com/ locally so I pentest it and just get a better idea of how everything is glued together.  I believe some other frameworks like Saleor provides this, ie. a mock store that actually has products.

**Comment by jitendra-webkul** [comment]
@nyck33 This feature is on our roadmap; users will be able to choose whether they want to proceed with sample data during installation.

**Comment by nyck33** [comment]
why would you have that `db seed` command in your installation instructions?
