### ISSUE TITLE
Status for Order

### ISSUE THREAD

**Issue by aguin2013** [bagisto/bagisto#976]
How many order status is possible?
1. How to change the status to Delivered after the product is delivered successfully.
2. How are product can be cancelled once the product is not available?

**Comment by prashant-webkul** [comment]
Hi, @aguin2013 

1. As you generate shipment and invoice from admin panel the status is assumed as delivered.
2. There is no such thing as cancellation of product. Till now you cannot order products that are out of stock. But we have implemented the functionality of backorders which enables customers to order products that are out of stock.

**Comment by aguin2013** [comment]
There is no provision of return right? Or that is also maintained by some means?

**Comment by rahulshukla-webkul** [comment]
Hi @aguin2013 

We will add return feature in future release.

Thanks
Rahul Shukla
