### ISSUE TITLE
 In the Customer Group Pricing feature, there's a problem with the Fixed Price option accepting input values higher than the actual price of the product.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9767]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

When created a product and added Price $100, and when assigning Customer group pricing to the same product with fixed price of $500 for 5 QTY, it is saved.

On checking the product view page of the same product there I can see that it is showing -> Buy 5 for $100.00 each and save 0.00%

Issue is it should not save the price more then the product price.

### Preconditions

1. Admin must be logged in.
2. Atleast 1 product must be created.

### Steps to reproduce

1. Go to Admin -> Catalog -> Products -> Create a Product -> Enter all Fileds and set price $100.
2. Click on Customer Group Price -> Enter Minimum QTY.
3. Select Price Type -> Fixed 
4. Enter Price $500.
5. Save Product 
6. here we can see product is saved.
7. Check the home page -> Search Product -> Product view page -> Check the customer group pricing text.
8. Buy 5 for $100.00 each and save this appears.

### Expected Result

We should not be  able to see the customer group price more then the actual price of the product.

### Actual Result

Currently we  are able to save the details. Please check the video for the same.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/d0ac77e4-558c-4e00-af9a-faaed6916488

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, 

We are not implementing this type of validation for handling group price checks. As this is the admin panel, it is expected that the admin is aware of the appropriate prices to add in the group price section.

**Comment by ashishkumar-webkul** [comment]
As per the discussion with @amit-webkul, hence I am closing the issue from here.
