### ISSUE TITLE
Add prefix like "bagisto-common" to all my route

### ISSUE THREAD

**Issue by MespiIT** [bagisto/bagisto#9769]
### Is your feature request related to a problem? Please describe.

I want to add prefix like "bagisto-common" in demo site to all my route, but i can't find how can i do it. Please help me with this!
![Screenshot 2024-05-08 at 14 33 50](https://github.com/bagisto/bagisto/assets/153755358/b168ca93-605d-4da4-9208-3666ca27a45b)

### Describe the solution you'd like

I want solution to add prefix to all my route

**Comment by devansh-webkul** [comment]
Please use Bagisto forum.
