### ISSUE TITLE
Facebook/Whatsapp Share buttons don't work on mobile.

### ISSUE THREAD

**Issue by CatalinRobert** [bagisto/bagisto#9772]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.0

### Issue Description

When I click on share button (facebook or whatsapp) it tries to download/print pdf/doc file the entire product page. On iOS for example, I receive an other error like "Safari can't open". When using laptop, only the facebook share button works.

### Preconditions

Create a product and enable facebook/wwhatsapp share buttons.

### Steps to reproduce

1. Go to 'product page' on mobile
2. Click on 'share'
3. Gets different errors( IOS safari can't open and Android tries to download the product page with pdf apps)

### Expected Result

-

### Actual Result

-

### Screenshots

![WhatsApp Image 2024-05-08 at 19 27 39](https://github.com/bagisto/bagisto/assets/47644093/c74e91be-0637-4792-b6c2-8915ca40b1dd)
![image](https://github.com/bagisto/bagisto/assets/47644093/d852908d-a4a2-4a49-a1e5-5009f1d31e6a)

### Additional context

ON mobile exists only one button for share and it  tries to download/print pdf/doc file the entire product page. ON laptop you can see the both buttons, fb/wapp and only facebook button works on laptop.

**Comment by amit-webkul** [comment]
@CatalinRobert 

Thank you sincerely for your attention to this matter. Your contributions to Bagisto are greatly valued. 

We have addressed the reported issue, and the fix will be included in our upcoming release.

In the meantime, you can review the resolution related to your concern here: [link](https://github.com/bagisto/bagisto/pull/9773)

**Comment by ashishkumar-webkul** [comment]
@CatalinRobert
 The issue has been fixed and PR has been merged, for your reference I am attaching a video. Please feel free to reach out to us in case you find any other issue.
 
 Thank You.
 
 **Video**
 
https://github.com/bagisto/bagisto/assets/92721837/f0d9a669-bcf6-465e-a226-fec022f00305
