### ISSUE TITLE
Cyrillic is not supported

### ISSUE THREAD

**Issue by plyaskin** [bagisto/bagisto#9799]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.1.2

### Issue Description

I can't create the category with a Russian name.
EN - Organization and storage of things
RU - Организация и хранение вещей

Creating products in Russian also does not work correctly (URLs).

### Preconditions

When you create the new category with EN text it works, but Russian does not.

### Expected Result

Russian text

### Actual Result

When I change the language for text in Category
EN - Reloading page
RU - Screenshot
For Chinese the same - Undefined array key "zh_CN"

### Screenshots
![2024-05-14_23-58-46](https://github.com/bagisto/bagisto/assets/9464550/e8744791-c1d1-4ed4-96a4-9c1dccf76609)

_No response_

**Comment by plyaskin** [comment]
Thank you for the reply.
You can find my problem here.
https://disk.yandex.ru/i/NHayFEYMG-FijA

**Comment by ashishkumar-webkul** [comment]
@plyaskin 

The issue to which you are referring in the video has already been fixed. However, upon checking your concern, we need to discuss the slug-related issue in the Category for different locales. We will discuss this and inform you accordingly.

issue fixed in following PR -> https://github.com/bagisto/bagisto/pull/9613

**Comment by jitendra-webkul** [comment]
ALready fixed in the master

**Comment by plyaskin** [comment]
@jitendra-webkul It is still there - the Cyrillic Slug is corrupted "website.com/-".

**Comment by jitendra-webkul** [comment]
Will look into it

**Comment by plyaskin** [comment]
Hi @jitendra-webkul 
I'm not sure that it should save Cyrillic or another language in the URL address, because some URLs will not opened in this case... 
It will be better to save it in English.

**Comment by jitendra-webkul** [comment]
You will still have the option to save in the English.

**Comment by plyaskin** [comment]
But also customers will have errors with other languages... and a lot of reports to you.
Exclude the possibility of an error.

**Comment by plyaskin** [comment]
Could you confirm if the URL address supports Hindi, Hebrew, Arabic or Cyrillic symbols?
Did you try to open the product for 19 available locales in the browser with a localised slug?
I'm not sure that this URL will be opened and will not back an error like "The page not found"

**Comment by jitendra-webkul** [comment]
Tested with Hindi, Hebrew, Arabic, now it's working.
