### ISSUE TITLE
In Category Page -> Filters are Overlapping into the header.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#9801]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

When we were checking the filter and there we encounter this issue in which Category Dropdown filter is Overlapping with the header where the categories are present.

### Preconditions

1. Admin must be logged in.
2. Categories must be created.

### Steps to reproduce

1. Go to Shop Front -> Select Catgory -> Open the dropdown filter and Scroll the page.
2. There we can see that it is overlapping with the Header where categories are present.

### Expected Result

It should not overlap the category Header.

### Actual Result

Currently we can see that the flters are overlapping . I have checked and verified this issue in RTL and LTR view. Please check the video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/c70d0bf4-6761-4a85-81ce-2906b164fc02

**Comment by hussaincoder23** [comment]
@ashishkumar-webkul   Issue is fixed Check PR  [https://github.com/bagisto/bagisto/pull/9849](url)
