### ISSUE TITLE
Add the ability to add the same product in different variations (colors, size, etc.)

### ISSUE THREAD

**Issue by plyaskin** [bagisto/bagisto#9803]
### Is your feature request related to a problem? Please describe.

I should create it separately a lot of time 

### Describe the solution you'd like

Add the ability to add the same product in different variations (colors, size, etc.)
For example, when I creating a new product with one description and photos, I can add different variations (colors, sizes, SKUs, Qty, etc.) and after saving it system will separate it into several products.

**Comment by jitendra-webkul** [comment]
Variant and configurable products have a parent-child relationship, so it's not possible to use one variant in multiple configurable products. I don't think there will be any case where you need to add one variant to multiple configurable products.

For example:

**Configurable Product:**
Nike Sport T-Shirt

**Variants:**
- Small Red Nike T-Shirt
- Medium Red Nike T-Shirt
- Large Red Nike T-Shirt
- Small Green Nike T-Shirt

As you can see, these variants are specific to this configurable product. Only if you are creating a duplicate configurable product might you need to use the same variants.

**Comment by jitendra-webkul** [comment]
It's not possible yet, but we plan to implement this feature as "Custom Options" in the near future. This will allow you to add multiple options to products, such as color and size, with only one product being created for all options.
