### ISSUE TITLE
The result of the product preview in Admin panel is not expected

### ISSUE THREAD

**Issue by plyaskin** [bagisto/bagisto#9805]
**Describe the bug**
When I press the Preview button I'm waiting to see unsaved changes, but it is link to the published product in the shop.

**Expected behavior**
Unsaved changes

If it will be works like the preview it will be useful, also rename this link to the published product to "Open in Shop".

**Comment by ashishkumar-webkul** [comment]
@plyaskin
Thank you so much for bringing this concern to light. We really appreciate your efforts.
From my understanding of the concern, I see that:
You already have a product, and you edited it by changing some details like price, description, name, etc. However, without saving, when you clicked the preview button, you still see the old details.

As per your concern, any changes made should appear in the preview. If I am correct, please let me know.

Please check the video for reference.
I would really appreciate it if you could provide me with more information on this.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/edff5943-868b-4237-b360-1b8e50460557

**Comment by plyaskin** [comment]
Hi!
Yes, you are right.
I think the button should match the text on it.
The direct link to the product is also convenient.

**Comment by jitendra-webkul** [comment]
Preview is a relevant text on the button that means preview product on frontend.
