### ISSUE TITLE
Your configuration files are not serializable.

### ISSUE THREAD

**Issue by eness** [bagisto/bagisto#9814]
**Describe the bug**

php artisan config:cache not work because of closure's used in config files.

In Laravel, configuration files are meant to be simple PHP arrays, and they are loaded very early in the application's lifecycle. This means that the service container (which is responsible for resolving and managing class dependencies) is not yet fully available when configuration files are loaded. Therefore, you can't directly access the service container within configuration files.

If you need to access dynamic values from the service container and want to ensure they are only computed or resolved when needed, a good approach is to use closures or functions within the configurations that are evaluated at runtime. This means moving the logic that depends on the service container to the place where these values are actually used.

**To Reproduce**
1. Install fresh Bagisto
2. Execute `php artisan config:cache`
3. See error

**Expected behavior**

Caching config values without errors.

**Screenshots**

![image](https://github.com/bagisto/bagisto/assets/2032225/8eae9ba0-34b7-48ca-8a6b-cdeb0d2e2e93)

Lines that causes the error : 

`packages/Admin/src/config/system.php`

![image](https://github.com/bagisto/bagisto/assets/2032225/cdf79dd6-1cbb-423d-8fd8-5dd07c65bc79)

**Comment by jitendra-webkul** [comment]
I have fixed this issue, please verify

**Comment by eness** [comment]
the issue seems to be solved.

![image](https://github.com/bagisto/bagisto/assets/2032225/1d7d08f7-1d72-43ac-933c-2ce4034e2318)
