### ISSUE TITLE
bug on tax rate state check

### ISSUE THREAD

**Issue by eness** [bagisto/bagisto#9816]
**Describe the bug**

Available tax is not applied to cart item when added to cart.

**To Reproduce**
1. Create a tax for a country and for all (*) states.
2. Add a product with that tax.
3. Go to shop and add the item to cart
4. Navigate to Cart page. You will see that the tax was not applied.

**Expected behavior**

Apply the needed tax to the cart & cart item

**Comment by jitendra-webkul** [comment]
@eness You created the tax rate for all states, but the country is still not mentioned. Therefore, selecting all states (*) is not relevant. Once you add the address with the selected country, the tax rate will be applied regardless of the state.
