### ISSUE TITLE
Can't update Currencies

### ISSUE THREAD

**Issue by plyaskin** [bagisto/bagisto#9827]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.2

### Issue Description

The currencies don't update with Fixer and Exchangeratesapi
FIXER_API_KEY=fc3148230a2ab085fd406813somekey
EXCHANGE_RATES_API_KEY=a548080d54c6d34a1fadsomekey
EXCHANGE_RATES_API_ENDPOINT=http://api.exchangeratesapi.io/v1/latest

For the Fixer I have an error "URI must be a string or UriInterface" and for Exchangeratesapi the page just reloading without any effect. But I can get the result for both services with URL like "http://api.exchangeratesapi.io/v1/latest?access_key=a548080d54c6d34a1fadsomekey&symbols=RUB"
I tried to do this with Opera and Edge.

### Preconditions

Registration

### Steps to reproduce

You know

### Expected Result

Updated currencies

### Actual Result

Didn't update currencies

### Additional context

**Comment by suraj-webkul** [comment]
Hi @plyaskin,

Please go to [apilayer.com](https://apilayer.com/marketplace/exchangerates_data-api) to get your API key. The endpoint will be:

https://api.apilayer.com/exchangerates_data/convert

**Comment by plyaskin** [comment]
@suraj-webkul
It still doesn't work.
Please don't close the tasks before it is solved.

**Comment by suraj-webkul** [comment]
Hi @plyaskin,

By default, we are using the [Apilayer](https://api.apilayer.com/exchangerates_data/convert) API for exchanging rates, which is free. If you prefer to use Fixer, which has limitations and most of its features are paid, you can update the services.php file as follows:

```php
config/services.php
```
```diff
'exchange_api' => [
-   'default' => 'exchange_rates',
+   'default' => 'fixer',
    .....
],
```

**Comment by plyaskin** [comment]
@suraj-webkul 
I want to use something that works.
Why did you add the rest options and didn't add the preferred options?
No any link and hint to APILayer, whyyyy????
