### ISSUE TITLE
Error Payment with Stripe

### ISSUE THREAD

**Issue by plyaskin** [bagisto/bagisto#9829]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.2

### Issue Description

Used [Codenteq – Stripe Payment Gateway](https://bagisto.com/en/extensions/codenteq-stripe-payment-gateway/) with testing card. 
After paid an error
Class "Webkul\Sales\Transformers\OrderResource" not found

### Preconditions

Install, use, etc

### Steps to reproduce

Install, use, etc

### Expected Result

Class "Webkul\Sales\Transformers\OrderResource" not found

### Actual Result

Callback to Shop

### Screenshots

![image](https://github.com/bagisto/bagisto/assets/9464550/a740b8d0-f344-413a-ab9f-56bfca19c7e5)

**Comment by jitendra-webkul** [comment]
This issue is not related to this repo. You should report this issue in the following repo:

https://github.com/codenteq/stripe-payment-gateway
