### ISSUE TITLE
The folder Sales/Transformers don't publish to the project folder 

### ISSUE THREAD

**Issue by plyaskin** [bagisto/bagisto#9835]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.2

### Issue Description

Published bagisto project to the folder didn't copy the folder Sales/Transformers

### Preconditions

Nothing

### Steps to reproduce

composer create-project bagisto/bagisto **OR** composer create-project bagisto/bagisto website.com

### Expected Result

Sales/Transformers

### Actual Result

No folder and I have errors with Stripe
After manually copying folder I have another error

### Screenshots

![image](https://github.com/bagisto/bagisto/assets/9464550/ad89d967-09cd-4710-99a5-5808f903db5b)

**Comment by jitendra-webkul** [comment]
Please avoid raising duplicate issues. I've already replied in #9829.

**Comment by plyaskin** [comment]
It's not duplicate because you sent me to another github in this ticket but the problem in Bagisto core

**Comment by jitendra-webkul** [comment]
You are using version 2.1.2, but Sales/Transformers will be introduced in the upcoming release. This issue is a duplicate because you were using a third-party Stripe package that only supports the master branch, not the latest stable release.
