### ISSUE TITLE
Emails sent twice when custom theme active

### ISSUE THREAD

**Issue by ag84ark** [bagisto/bagisto#9839]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.2

### Issue Description

When you have a custom shop theme on the website active, the emails are sent twice to the customer as both the ` Webkul\Shop\Listeners\xxx.php` and `CustomTheme\Listeners\xxx.php` are listening to the same events, even if in the admin you have activated the custom theme for the frontend.

### Preconditions

I have a webshop with version 2.1.2 active, on which I have fallowed the steps from https://bagisto.com/en/create-custom-theme-in-bagisto/ to create a custom theme, as I needed to make some changes on the default one.

### Steps to reproduce

Create a custom theme fallowing https://bagisto.com/en/create-custom-theme-in-bagisto/ and make it active, then create a order and you as a customer will receive 2 emails instead of  one on any event, order created, invoice, transport, comment on the order

### Expected Result

Normally the customer should receive only one email

### Actual Result

The customer receives duplicated emails

**Comment by devansh-webkul** [comment]
@ag84ark,

Don't add a custom listener, as our existing listener is already handling it.

**Comment by ag84ark** [comment]
I understand that, but your listeners point to your email templates (original shop theme), not the ones from the custom theme where I could have changed things.

**Comment by devansh-webkul** [comment]
It's actually pointing to the shop namespace, so it automatically detects the current theme and changes the template. If the view is not found in the resources folder, it will fall back to the default theme. Therefore, you won't need an extra listener to point to your views.

**Comment by devansh-webkul** [comment]
Also, I will verify this whole flow once again. I don't think you need any extra listener here. Meanwhile can you share your listender code also.

**Comment by jitendra-webkul** [comment]
@devansh-webkul @ag84ark I have verified the scenario, and it works as expected. The view finder will first search for the blade in your current theme. If it is not found, it will use the blade from the default theme.
