### ISSUE TITLE
When i use paypal smart button for payment,but the transaction_id save the payment order id info , and not real transaction_id 

### ISSUE THREAD

**Issue by xxl4** [bagisto/bagisto#9847]
**Describe the bug**

Dear Master.

when i use paypal smart button for payment,but the transaction_id log the payment order id info

![1717036725744](https://github.com/bagisto/bagisto/assets/34465153/e322a7b6-8a75-4bfa-828f-f210900f3610)

![image](https://github.com/bagisto/bagisto/assets/34465153/7c4e14de-11c2-4271-9b6b-6c74d530674c)

**Comment by ashishkumar-webkul** [comment]
@xxl4 

Thank you so much for your concern, we really appreciate your efforts toward bagisto. 

I would love to know more about the issue. Can you please elaborate your query.

Thanks.

**Comment by devansh-webkul** [comment]
Thank you for reaching out. It looks like your request is not an issue report. For discussions, questions, or general support, we encourage you to use the [Bagisto Forum](https://forums.bagisto.com/). The forum is the best place for such queries, and you'll be able to connect with other community members and get the help you need.

Please reserve the GitHub issue tracker for reporting bugs and issues with the codebase. This helps us keep the issue tracker focused and ensures that problems are addressed promptly.

Thank you for your understanding!
