### ISSUE TITLE
Dynamically insert products

### ISSUE THREAD

**Issue by pelomedusa** [bagisto/bagisto#985]
My client's project requires importing products from an external database, along with categories, TVA prices etc ...

After searching in the documentation, i don't see anything like this and it seems like the web API only has GET methods, so it does not allow me to insert product.

How would i go about inserting a product with custom attributes ? Is there a simple way or do i need to update each table manually with something like `DB::table('products')->insert(...)`

Thanks

**Comment by prashant-webkul** [comment]
@pelomedusa We know it would be really tiresome for you to import products from sheet documents such as CSV and Excel files.
Currently we have been developing an addon related to bulk upload of products but it will be only compatible with our marketplace extension.
In near future after releasing the bulk upload addon we will release its variation for Bagisto Core framework.

But for your current situation you would need to develop a package which would require you to use ProductRepository to gain your purpose.

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Product/src/Repositories/ProductRepository.php

**Comment by pelomedusa** [comment]
Thanks, understood. 
I managed to use the `CategoryRepository` by creating it using
> $cr = new CategoryRepository(app());

and then using

> $cr->create([...]);

which seems to work pretty well.

However, the constructor of the `ProductRepository` seems a little bit more complicated. Any tip on how to use it?

Thanks

**Comment by pelomedusa** [comment]
Nevermind, i found the solution. Even if it's not related to Bagisto itself, for anyone wondering: You have to use the Repository pattern, here is an exemple for the categories:

In my case, importing is done with a Laravel command :
>  $category_controller = App::make('\App\Http\Controllers\CategoryController');
>  $category = $category_controller->getCreateCategory($category_title);

**Comment by prashant-webkul** [comment]
@pelomedusa Nice way of using container dependency injection.

**Comment by vnorbert94** [comment]
@pelomedusa can you send us some screenshots, with uploading csv or xml files ?

**Comment by pelomedusa** [comment]
@vnorbert94 i haven't really done more than this since we decided to use another framework instead. In this case were inserting products from an external database.

**Comment by lzomedia** [comment]
@pelomedusa What framework you decided to use?

**Comment by pelomedusa** [comment]
@lzomedia In the end, prestashop because we needed strong multilingual support

**Comment by prashant-webkul** [comment]
@pelomedusa Bagisto also have multi lingual support out of the box.
And its really easy to create a new localization also.

**Comment by pelomedusa** [comment]
I meant multishop, sorry

**Comment by prashant-webkul** [comment]
We have two solutions for multi shop scenarios:
1. SAAS module.
2. Multi vendor market place module.

Check below:
https://bagisto.com/en/extensions/

**Comment by niug** [comment]
Hi, I want to dynamically insert products and I do the following code. With this, the product are created and insered in database, tables 'products', 'product_attribute_values' are ok, but the table 'product_flat' the row is created but all values are NULL except locale and product_id:

` <?php

namespace Mo\Scripts\Http\Controllers;

use Webkul\Product\Contracts\Product;
use Webkul\Product\Contracts\ProductAttributeValue as ProductAttributeValueContract;
use Webkul\Category\Models\Category;
use Webkul\Category\Models\CategoryTranslation;
use Illuminate\Support\Facades\DB;

use Webkul\Product\Repositories\ProductRepository;
use Webkul\Product\Repositories\ProductAttributeValueRepository;
use Webkul\Product\Repositories\ProductImageRepository;
use Webkul\Product\Repositories\ProductInventoryRepository;

class ScriptsController extends Controller
{
    protected $_config;

    protected $product;
    protected $attr;
    protected $inve;
    protected $img;

    public function __construct(ProductRepository $product, ProductAttributeValueRepository $attr, ProductInventoryRepository $inve, ProductImageRepository $img)
    {
        $this->attr = $attr;
        $this->product = $product;
        $this->inve = $inve;
        $this->img = $img;

        $this->_config = request('_config');
    }

    public function index()
    {
        $this->create_products_mass();

        return view($this->_config['view'])->with(['result' => "Finish"]);
    }

    protected function create_products_mass()
    {
        $file = \Storage::get('importacio.csv');
        $rows = explode ("\n", $file);
        
        $header = true;
        foreach ($rows as $row)
        {
            $cols = explode(";", $row);
            if ($header) 
            {
                $header = false;
            } 
            else 
            {
                $pro = $this->product->create([
                    "sku" => $cols[$0],
                    "type" => "simple",
                    "attribute_family_id" => 1,
                    "parent_id" => null,
                ]);                

                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>1, "value"=>$pro->sku]);// Sku
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>2, "value"=>isset($cols[1])?$cols[1]:"", "locale"=>'es', "channel"=>'default']); // Name
                
                die();
            }
        }
    }
}
`
Some idea? Maybe I have to update the attributes with the update method of ProductRepository? I tried this code, but throw a 404 error:

`$prod = $this->product->update([
                    "value" => isset($cols[1])?$cols[1]:"",
                    "channels"=>['default'],
                    "locale" =>'es'
                ], $pro->id, 2);`

And finally, if I do a $prod->save(), that this have to throw the event of a product was been modified, and maybe its updated the product flat, when I do $prod->save(), this throw this error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'channels' in 'field list' (SQL: update `products` set `channels` = ?, `color` = ?, `size` = ?, `diameter` = ?, `special_price` = ?, `price` = ?, `products`.`updated_at` = 2020-05-10  3:37:55 where `id` = 141)`

**Comment by niug** [comment]
Hi! Finally I can resolve my problem. I added the following line at the end of product creation, and this event update the product flat:

`Event::dispatch('catalog.product.update.after', $pro);`

I put all the code for create a product, assign category, assign the attributes, inventory and images, that I use for import dynamically the products:

`namespace Mo\Scripts\Http\Controllers;

use Webkul\Product\Contracts\Product;
use Webkul\Product\Contracts\ProductAttributeValue as ProductAttributeValueContract;
use Webkul\Category\Models\Category;
use Webkul\Category\Models\CategoryTranslation;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Webkul\Product\Repositories\ProductRepository;
use Webkul\Product\Repositories\ProductAttributeValueRepository;
use Webkul\Product\Repositories\ProductImageRepository;
use Webkul\Product\Repositories\ProductInventoryRepository;
use Illuminate\Support\Facades\Event;

class ScriptsController extends Controller
{
    protected $_config;
 
    protected $product;
    protected $attr;
    protected $inve;
    protected $img;

    public function __construct(ProductRepository $product, ProductAttributeValueRepository $attr, ProductInventoryRepository $inve, ProductImageRepository $img)
    {
        $this->attr = $attr;
        $this->product = $product;
        $this->inve = $inve;
        $this->img = $img;

        $this->_config = request('_config');
    }

    public function index()
    {
        $this->create_products_mass();

        return view($this->_config['view'])->with(['result' => "Finish"]);
    }

    protected function create_products_mass()
    {
        $col_cb = 0;
        $col_sku = 1;
        $col_nom_es = 2;
        $col_nom_ca = 3;
        $col_desc_es = 4;
        $col_desc_ca = 5;
        $col_preu = 6;
        $col_quantitat = 7;
        $col_categoria = 8;

        $file = \Storage::get('importacio.csv');
        
        $rows = explode ("\n", $file);
        
        $header = true;
        foreach ($rows as $row)
        {
            $cols = explode(";", $row);
            if ($header) 
            {
                $header = false;
            } 
            else 
            {
                if(!isset($cols[$col_sku]))
                    continue;
                
                $pro = $this->product->create([
                    "sku" => $cols[$col_sku],
                    "type" => "simple",
                    "attribute_family_id" => 1,
                    "parent_id" => null,
                ]);
               
                DB::table('product_categories')->insert(
                    ['product_id' => $pro->id, 'category_id' => 6]
                );
             
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>1, "value"=>$pro->sku]);// Sku
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>2, "value"=>isset($cols[$col_nom_ca])?$cols[$col_nom_ca]:"", "locale"=>'en', "channel"=>'default']);// Nom
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>2, "value"=>isset($cols[$col_nom_es])?$cols[$col_nom_es]:"", "locale"=>'es', "channel"=>'default']);
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>2, "value"=>isset($cols[$col_nom_ca])?$cols[$col_nom_ca]:"", "locale"=>'ca', "channel"=>'default']);
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>3, "value"=>str_replace(' ', '-', isset($cols[$col_nom_ca])?$cols[$col_nom_ca]:"")]);// URL
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>4, "value"=>2, "channel"=>'default']); // IVA 21% -> 2; IVA 4% -> 1
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>5, "value"=>0]);// Novetats
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>6, "value"=>0]);// Destacats
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>7, "value"=>1]);// Mostrar individualment
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>8, "value"=>1]);// Actiu
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>9, "value"=>"<p></p>", "channel"=>'default', "locale"=>'en']);// Descripció curta
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>9, "value"=>"<p></p>", "channel"=>'default', "locale"=>'ca']);
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>9, "value"=>"<p></p>", "channel"=>'default', "locale"=>'es']);
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>10, "value"=>"<p>".(isset($cols[$col_desc_ca])?$cols[$col_desc_ca]:"")."</p>", "channel"=>'default', "locale"=>'en']);// Descripció llarga
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>10, "value"=>"<p>".(isset($cols[$col_desc_ca])?$cols[$col_desc_ca]:"")."</p>", "channel"=>'default', "locale"=>'ca']);// Descripció llarga
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>10, "value"=>"<p>".(isset($cols[$col_desc_es])?$cols[$col_desc_es]:"")."</p>", "channel"=>'default', "locale"=>'es']);// Descripció llarga
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>11, "value"=>str_replace(',','.',isset($cols[$col_preu])?$cols[$col_preu]:"")]);// Preu
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>12, "value"=>null]);// Cost
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>13, "value"=>null]);// Special price
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>14, "value"=>null]);// Special price from
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>15, "value"=>null]);// Special price to
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>16, "value"=>isset($cols[$col_nom_es])?$cols[$col_nom_ca]:"", "channel"=>'default', "locale"=>'en']);// Meta title
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>16, "value"=>isset($cols[$col_nom_es])?$cols[$col_nom_es]:"", "channel"=>'default', "locale"=>'es']);
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>16, "value"=>isset($cols[$col_nom_ca])?$cols[$col_nom_ca]:"", "channel"=>'default', "locale"=>'ca']);
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>17, "value"=>"", "channel"=>'default', "locale"=>'en']); // Meta Keywords
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>17, "value"=>"", "channel"=>'default', "locale"=>'ca']);
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>17, "value"=>"", "channel"=>'default', "locale"=>'es']); 
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>18, "value"=>isset($cols[$col_desc_es])?$cols[$col_desc_ca]:"", "channel"=>'default', "locale"=>'en']); // Meta Description
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>18, "value"=>isset($cols[$col_desc_es])?$cols[$col_desc_es]:"", "channel"=>'default', "locale"=>'es']); 
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>18, "value"=>isset($cols[$col_desc_ca])?$cols[$col_desc_ca]:"", "channel"=>'default', "locale"=>'ca']);
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>19, "value"=>null]);// Width
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>20, "value"=>null]);// Height
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>21, "value"=>null]);// Depth
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>22, "value"=>"0.5"]);// Weight
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>23, "value"=>"2"]);// Color
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>24, "value"=>"6"]);// Size
                $this->attr->create(["product_id"=>$pro->id,"attribute_id"=>26, "value"=>"0"]);// guest checkout

                $inventory = ["inventories" => [1 => (isset($cols[$col_quantitat])?$cols[$col_quantitat]:0)]];
                $this->inve->saveInventories($inventory, $pro);

                $allFiles = Storage::files('import_images');
                $matchingFiles = preg_grep('/^import_images\/' . $pro->sku . '/', $allFiles);
                foreach ($matchingFiles as $path) {
                    $ext = substr(strrchr( $path, '.'), 1);
                    $url_dest = 'product/' . $pro->id . '/' . uniqid() . "." . $ext;
                    Storage::move($path, $url_dest);
                    $this->img->create([
                            'path'       => $url_dest,
                            'product_id' => $pro->id,
                        ]);
                }

                Event::dispatch('catalog.product.update.after', $pro);
            }
        }
    }
}`
