### ISSUE TITLE
lang=ja, but the name input box can only input letters and numbers

### ISSUE THREAD

**Issue by chakson** [bagisto/bagisto#9852]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.2

### Issue Description

When I use Japanese, the name input box can only input letters and numbers, and it can't tell that I am currently in Japanese

### Preconditions

bagisto 2.1.2
ubuntu

### Steps to reproduce

1. Go to 'checkout page'
2. Click on 'address form submit'
3. Scroll down to 'name input of address form'
4. See the red string prompt

### Expected Result

When entering Japanese in the name input box, Japanese text can be entered, the red string alarm should not be prompted

### Actual Result

When entering Japanese in the name input box, a red string alarm appears

### Screenshots

![image](https://github.com/bagisto/bagisto/assets/13362753/70be4ecf-197a-4074-b8a0-983fa9d09289)

**Comment by ashishkumar-webkul** [comment]
@shivendra-webkul 
I have checked the PR with almost all locale and now it is working fine. As now no validation is appearing and it is accepting the desired locale translation which is required.

Please check the video for the reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/d76587ff-6254-44a7-ad91-aa06dfd2ed4c

**Comment by ashishkumar-webkul** [comment]
@chakson 

Thank You So much for bringing this issue to light. We really appreciate your contribution towards bagisto.

Checked and  verified the issue and also the issues has been fixed and PR has been created, once the PR will merged you task check the updated code. for  now PR link -> https://github.com/bagisto/bagisto/pull/9874

Thank You.
