### ISSUE TITLE
please support Swiss franc (CHF) as currency during installation

### ISSUE THREAD

**Issue by mkduew** [bagisto/bagisto#9854]
### Is your feature request related to a problem? Please describe.

title is self-explaining

### Describe the solution you'd like

integrate CHF like EUR in the installation

**Comment by shivendra-webkul** [comment]
Hi @mkduew,

Thank you for your valuable contribution! If you need more currency options, you can easily incorporate them through the admin panel. During installation, we provide only 13 currency options, but you can customize them according to your requirements.

**Comment by ashishkumar-webkul** [comment]
@mkduew

Thank you very much for your concern. We greatly appreciate your patience.

We are pleased to inform you that we have added the Swiss franc (CHF) currency to Bagisto. This has been resolved in [this PR](https://github.com/bagisto/bagisto/pull/9830).

Please check it out. We hope you are excited about this update.

For now, I am closing the feature request issue on GitHub. If you encounter any issues, please feel free to reach out to us.

Thank you.
