### ISSUE TITLE
A way to add other models to Webkul\Sitemap 

### ISSUE THREAD

**Issue by ag84ark** [bagisto/bagisto#9865]
### Is your feature request related to a problem? Please describe.

I have a blog package, but I can not add the blog route, and its articles to the sitemap without modifying this package. Should be nice if there was a way to do this.

### Describe the solution you'd like

A way that I can tap into Webkul\Sitemap and be able to add different fixed routes and models.

**Comment by jitendra-webkul** [comment]
Achieving this is straightforward. Please follow the steps below:

### Step 1: Implement the `Sitemapable` Interface in Your Model

First, implement the `Spatie\Sitemap\Contracts\Sitemapable` interface in your model and define the `toSitemapTag` method.

```php
<?php

namespace Webkul\ACME\Models;

use Spatie\Sitemap\Contracts\Sitemapable;
use Spatie\Sitemap\Tags\Url;
use Webkul\Core\Eloquent\TranslatableModel;

class Blog extends TranslatableModel implements PageContract, Sitemapable
{
    /**
     * Convert the model instance to a sitemap tag.
     *
     * @return mixed
     */
    public function toSitemapTag(): Url|string|array
    {
        if (! $this->url_key) {
            return [];
        }

        return route('acme.blogs.view', $this->url_key);
    }
}
```

### Step 2: Listen to Sitemap Events in Your Service Provider

Next, listen to the `marketing.search_seo.sitemap.create.after` and `marketing.search_seo.sitemap.update.after` events in your service provider and add the sitemap for the Blog model.

```php
public function boot()
{
    Event::listen('marketing.search_seo.sitemap.create.after', [self::class, 'generateSitemap']);
    Event::listen('marketing.search_seo.sitemap.update.after', [self::class, 'generateSitemap']);
}

public function generateSitemap($sitemap)
{
    Sitemap::create()
        ->add(Url::create('/'))
        ->add(Category::all())
        ->add(Product::all())
        ->add(Page::all())
        ->add(Blog::all())
        ->writeToDisk('public', $sitemap->path.'/'.$sitemap->file_name);
}
```

---
