### ISSUE TITLE
same error in alpha version

### ISSUE THREAD

**Issue by parimahziyi** [bagisto/bagisto#987]
hi
I install alpha version bagisto yesterday. but yet i have the same error include "Undefined index: 127.0.0.1 in C:\Users\Pasargad-Pc\Downloads\Compressed\bagisto-master\bagisto-master\bagisto\public\installer\install.php on line 36
". what should I do? and
Furthermore, all buttons and links don't work in the project. I followed all of the guideline steps by step and I am using win 10. plz, help me I need it.

**Comment by prashant-webkul** [comment]
@parimahziyi Hi,
It would be really better if you install it via command line.
Download release not alpha.

Extract the contents of your zip and run the commands below on your command prompt inside root of the project:
1. composer create-project
2. php artisan storage:link
3. php artisan vendor:publish
4. Then do the entries in your .env file(present in project's root) for your database name and its credentials.
5. php artisan migrate
6. php artisan db:seed

Please let us know if you still face any trouble. We are here to help right away.

**Comment by parimahziyi** [comment]
Hi
unfortunately, I should say I installed it again in your way but nothing happened..again the same line at the first of page and buttons doesn't work at all
note that I download master bagisto from here, the same Github link that we are
please help me...

**Comment by prashant-webkul** [comment]
@parimahziyi Please file a ticket on bagisto.uvdesk.com , we will personally handle your problem.

**Comment by rahulshukla-webkul** [comment]
Hi @parimahziyi ,

We have disabled strict mode in our installer so you download latest one from git repository,
