### ISSUE TITLE
Suggestion- On product page there should be a product video section

### ISSUE THREAD

**Issue by sanjanasingh202** [bagisto/bagisto#989]
**Suggestion**- there should be a product video section so that we can upload the video of that particular product in bagisto like Amazon and eBay.

**Comment by prowseed** [comment]
I suggest youtube/vimeo video as an alternative solution

**Comment by jitendra-webkul** [comment]
You can add youtube video in description

![download](https://user-images.githubusercontent.com/39991107/68383466-b9523880-017b-11ea-99ae-742dddddb8d2.png)
