### ISSUE TITLE
Admin OrderController error messages are not correctly displayed 

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#9932]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

In Webkul\Admin\src\Http\Controllers\Sales\OrderController.php the response messages are not correctly displayed

### Preconditions

master branch

### Steps to reproduce

Check the screenshots

### Expected Result

The message should be displayed correctly

![image](https://github.com/bagisto/bagisto/assets/1594411/7bdfd715-751c-4347-acc9-22a51cc0a6c3)

### Actual Result

![image](https://github.com/bagisto/bagisto/assets/1594411/d74173df-e5f3-4c3d-b897-3f9d0415e6ce)

**Comment by ashishkumar-webkul** [comment]
@ghermans 

Thank you so much for bringing the issue to light. I have verified the issue. Please check the screenshot for reference.

**Video**

![Screenshot from 2024-06-18 10-04-17](https://github.com/bagisto/bagisto/assets/92721837/7f588ef4-2156-4334-99d3-e727e8b92664)
