### ISSUE TITLE
AI image modal not fully showing

### ISSUE THREAD

**Issue by Yorgv** [bagisto/bagisto#9937]
**Describe the bug**
The modal to add AI images is not fully shown when opened from another modal. The close button and other fields are cut off.

**To Reproduce**
1. Go to Create Attributes page
2. Set attribute type as "select" 
3. use "Image swatch" as input option
4. Add new row
5. Click on "Magic AI" option.
6. The modal to create a prompt and generate the AI image is not fully shown. It takes the height of the "Add row" modal and not all content of the AI modal is shown. This issue prevents closing the modal since the close button is cut off.

**Expected behavior**
The AI modal should get the correct height without any overflow cutting of the content

**Screenshots**
<img width="1173" alt="image" src="https://github.com/bagisto/bagisto/assets/30804883/f7733df6-5a05-49ad-a078-700edb12677d">
<img width="1173" alt="image" src="https://github.com/bagisto/bagisto/assets/30804883/05a82793-766b-4f32-a18a-361f17615e94">

**Desktop (please complete the following information):**
 - OS: MacOS 14.2.1 (23C71)
 - Browser: Chrome Versie 126.0.6478.61 (Official build) (arm64)
 - Version v2.1.2

**Comment by ashishkumar-webkul** [comment]
@Yorgv

Thank you very much for your concern. We are able to generate images with the help of OpenAI.

However, we are having trouble understanding your specific concern. Could you please provide a video or a more detailed explanation of the issue? We would love to assist you further.

Thank you.

**Comment by devansh-webkul** [comment]
This is expected behavior, we are using modal with overflow behavior.
