### ISSUE TITLE
[default] en field of labels section disappear after entering data in "Global Label" field.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#995]
- Framework Version: 0.1.6

------------------------------------------

![Screenshot from 2019-06-10 15-01-39](https://user-images.githubusercontent.com/45203177/59187057-1ed0d780-8b92-11e9-89a7-6703798c1075.png)
![Screenshot from 2019-06-10 15-01-32](https://user-images.githubusercontent.com/45203177/59187088-2db78a00-8b92-11e9-884d-b431e68fd973.png)

**Comment by prashant-webkul** [comment]
Its the part of functionality itself. As it copies values to all the locale specifics defined with channels.
