### ISSUE TITLE
Laravel Sail Support

### ISSUE THREAD

**Issue by devansh-webkul** [bagisto/bagisto#9962]
### Is your feature request related to a problem? Please describe.

Since our project is fully Laravel-based, we should consider checking the feasibility of making our project Laravel Sail friendly. This would eliminate the need for the Bagisto Docker repository and consolidate everything in one place.

### Describe the solution you'd like

I will check the Laravel Sail installation.

**Comment by diegosurita** [comment]
Hi!
I added sail to my fork of the project. I just didn't setup the elastic search container.
But as far as I tested, it's working well.

Here's the commit: https://github.com/suritasolutions/bagisto/commit/2bcb3a6035f8ac3e4828bb5f8ba0333f91d677a8
