### ISSUE TITLE
Having to redo all the data models when adding a product 

### ISSUE THREAD

**Issue by pythonyalfa** [bagisto/bagisto#9969]
**Describe the bug**
I was trying to add a product and forgot the price. When I went back to update it, it forced me to input all the fields not just the price how do I make sure that the fields are prepopulated with whatI initially typed in? I don't want re type everything out just because I forgot the price.

**Comment by ashishkumar-webkul** [comment]
@pythonyalfa 

Thank you So Much bringing this to light, we will be discussing the same and we will update you for the same ASAP.

Your Patience will be really appreciated.

Thank You.
