### ISSUE TITLE
The new reviews display system does not make sense

### ISSUE THREAD

**Issue by ag84ark** [bagisto/bagisto#9972]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.2 / master

### Issue Description

I have added 3 reviews to a product for testing, and I don't see the value of displaying the total count of stars on product ratings like in my case 11 when there are only 3 reviews.

### Preconditions

none

### Steps to reproduce

Add reviews to a product and you will see the problem

### Expected Result

I think it should write 3 reviews, not 11

### Actual Result

It shows 11 ratings for 3 reviews

### Screenshots

<img width="702" alt="Screenshot 2024-07-02 at 12 13 50" src="https://github.com/bagisto/bagisto/assets/10678506/5eba172d-45f3-43bd-bf60-23235cca799a">
<img width="332" alt="Screenshot 2024-07-02 at 12 17 14" src="https://github.com/bagisto/bagisto/assets/10678506/131376c2-f944-422f-9707-ad3ac2494f83">

### Additional context

none

**Comment by jitendra-webkul** [comment]
Some people display ratings in the Chip instead of the total number of reviews. However, I agree that there should be an option to display reviews instead of ratings. In our next update, we will provide both options for you to choose from.

**Comment by ashishkumar-webkul** [comment]
Checked and found that the PR is working fine. I have checked the configurations which are added.
Checked the same in multilocale.
Fount it working, product Card, Product View Page,

https://prnt.sc/-kFCqwLkCBtx
https://prnt.sc/HLIZjerjhkxF
https://prnt.sc/7g5HMjBbHvgC
https://prnt.sc/HLYPy9fvRB3n
https://prnt.sc/j3be9OWkMLuK
https://prnt.sc/YJa3uXT4uRGL
