### ISSUE TITLE
if the source code file for the theme template is not provided?

### ISSUE THREAD

**Issue by missoy** [bagisto/bagisto#9975]
### Is your feature request related to a problem? Please describe.

Does it not support secondary development?

### Describe the solution you'd like

Does it not support secondary development?

### Describe alternatives you've considered

Does it not support secondary development?

**Comment by devansh-webkul** [comment]
Thank you for reaching out. It looks like your request is not an issue report. For discussions, questions, or general support, we encourage you to use the [Bagisto Forum](https://forums.bagisto.com/). The forum is the best place for such queries, and you'll be able to connect with other community members and get the help you need.

Please reserve the GitHub issue tracker for reporting bugs and issues with the codebase. This helps us keep the issue tracker focused and ensures that problems are addressed promptly.

Thank you for your understanding!
