### ISSUE TITLE
Product Image has cropped Automatically in 

### ISSUE THREAD

**Issue by shakib04** [bagisto/bagisto#9986]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.2

### Issue Description

After uploading my product image, it has cropped and some details has remvoed. 

### Preconditions

create a product with an image 

### Steps to reproduce

1. Go to 'Admin Panel'
2. Click on 'Create Product'
3. Add new product with image
4. see details in products details page.

### Expected Result

I want to show the full image without cropping anything

### Actual Result

Product image has cropped

### Screenshots

Right image is the actual image from short description. I want to show the exact image in product images.
![image](https://github.com/bagisto/bagisto/assets/51458806/1fc89b51-591e-4121-9c13-7518e41c5cf8)

**Comment by shivendra-webkul** [comment]
Hi @shakib04, Thank you for your attention to this matter. You can adjust the dimensions of images by navigating to "Configuration -> Catalog -> Products". From there, you can set the image dimensions according to your needs.

**Comment by shakib04** [comment]
@shivendra-webkul, I am getting this - Configuration -> Catalog -> Products
![image](https://github.com/bagisto/bagisto/assets/51458806/22afcc97-c450-41ad-bd58-1967ad7a0249)

**Comment by shakib04** [comment]
@shivendra-webkul, I do not want to crop any image. Here I want to show the original image like details page.


![image](https://github.com/bagisto/bagisto/assets/51458806/a329272e-45fa-4e52-a9cd-385fc1c38fff)

**Comment by amit-webkul** [comment]
Hello, @shakib04 ,

As per your concern, you need to set a dimension for the types of images to be displayed there. After that, you can set that particular size in the configuration settings. Otherwise, you can also override the page as per your modifications.

**Comment by shivendra-webkul** [comment]
@shakib04  As I reviewed the issue description, it appears that you are using version 2.1.2. The configuration you're referring to has been added in the latest versions.

Please update your code by pulling the latest changes from version 2.2.2

**Comment by shakib04** [comment]
@ashishkumar-webkul thanks for the update. Can you share where I will get this configuration?

**Comment by ashishkumar-webkul** [comment]
@shakib04 

You can navigate to **Configuration -> Catalog -> Products** for getting the desired configurtion.

Thank You.

**Comment by devansh-webkul** [comment]
Thank you for reaching out. It looks like your request is not an issue report. For discussions, questions, or general support, we encourage you to use the [Bagisto Forum](https://forums.bagisto.com/). The forum is the best place for such queries, and you'll be able to connect with other community members and get the help you need.

Please reserve the GitHub issue tracker for reporting bugs and issues with the codebase. This helps us keep the issue tracker focused and ensures that problems are addressed promptly.

Thank you for your understanding!
